apple/foundationdb

fdbclient/FileBackupAgent.actor.cpp
fdbclient/SystemData.cpp
fdbclient/include/fdbclient/BlobRestoreCommon.h
fdbclient/include/fdbclient/SystemData.h
fdbserver/BlobManager.actor.cpp
fdbserver/BlobManifest.actor.cpp
fdbserver/ClusterController.actor.cpp
fdbserver/Status.actor.cpp
fdbserver/workloads/BlobRestoreWorkload.actor.cpp

This PR includes the following changes:
1. Remove blobGranulesLastFlushKey and add lastFlushTs and lastFlushVersion to BlobGranuleBackupConfig.
2. Make BlobGranuleBackupConfig::enabled() as a trigger to trigger backups. watchBackupEnabled() is added to watch this flag and start/stop backup loops
3. refactor backupManifest loop and truncationMutations loop.

Move lastFlushTs to BlobGranuleBackupConfig

---

fdbclient/PaxosConfigTransaction.actor.cpp

Cherry pick of #10420 to `snowflake/release-71.3`.

Fix a dynamic knobs bug where fulfilling a promise could cause it to get deleted (snowflake/release-71.3)

---

fdbclient/FileBackupAgent.actor.cpp
fdbclient/SystemData.cpp
fdbclient/include/fdbclient/BlobRestoreCommon.h
fdbclient/include/fdbclient/SystemData.h
fdbserver/BlobManager.actor.cpp
fdbserver/BlobManifest.actor.cpp
fdbserver/ClusterController.actor.cpp
fdbserver/Status.actor.cpp
fdbserver/workloads/BlobRestoreWorkload.actor.cpp

Cherry-Pick of #10505
This PR includes the following changes:
1. Remove blobGranulesLastFlushKey and add lastFlushTs and lastFlushVersion to BlobGranuleBackupConfig.
2. Make BlobGranuleBackupConfig::enabled() as a trigger to trigger backups. watchBackupEnabled() is added to watch this flag and start/stop backup loops
3. refactor backupManifest loop and truncationMutations loop.
100k correctness 20230616-025543-huliu-f1ed2d71d896a3af

Move lastFlushTs to BlobGranuleBackupConfig (Cherry-Pick #10505 to snowflake/release-71.3)

---

fdbserver/BlobGranuleValidation.actor.cpp

cherrypick #10508
seed: `-f ./tests/fast/BlobGranuleVerifySmallClean.toml -s 3314301457 -b on`
commit: fdca5dcba
build: clang

fix flushing empty range [release-7.3]

---

fdbserver/BlobGranuleValidation.actor.cpp

Cherry-Pick of #10508
100k correctness: 20230616-160242-jslocum-29ee66ea5c3d8951 : 1 failure
(GetMappedRange which is not a feature we use and also cannot be caused by this change)
50k blob granule correctness: 0 failures
Buggified code could create an empty range if a test was using variable length null strings as keys.
Fixed it to check for this before flushing.

fix flushing empty range (Cherry-Pick #10508 to snowflake/release-71.3)

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/DDRelocationQueue.actor.cpp
fdbserver/DDTeamCollection.actor.cpp
fdbserver/include/fdbserver/DataDistributionTeam.h

In sharded Rocks, we don't want the number of shards to exceed certain value, which would make the number of on disk files too many. Therefore, in this PR, we added an option to select data move destination team that does not exceed `DESIRED_MAX_SHARDS_PER_TEAM`.
Ultimately, we want to control the number of shards per storage server. However, since we already have `DESIRED/MAX_TEAMS_PER_SERVER`. Adding a per team limit makes it easier to control.
Note that `DESIRED_MAX_SHARDS_PER_TEAM` is not a hard limit, and if no such team exists, `getTeam` will return the current best option ignoring `DESIRED_MAX_SHARDS_PER_TEAM`.
Later we will add a background balancer to rebalance shard counts to make it within the limit.
Added a unit test to test PreferWithinShardLimit logic. …

Add an option to limit the number of shard per team

---

fdbclient/ServerKnobs.cpp
fdbserver/include/fdbserver/WorkerInterface.actor.h
fdbserver/worker.actor.cpp

Current gray failure monitor before this PR only expires a bad communication between two processes after `CC_DEGRADED_LINK_EXPIRATION_INTERVAL`. If two processes' communication only has short disruption, this may cause a false positive recovery. This PR adds a logic to explicitly telling CC that the communication between a worker and its previous degraded peer has recovered.
This PR implements part 1 of this logic in the worker side. The follow up PR will implement the logic in the CC side to actually use the newly added `recoveredPeers` in the `UpdateWorkerHealthRequest`.
If …

Worker health monitor tracks recovered peers

---

fdbclient/NativeAPI.actor.cpp

Update the getExactRange function to not retry the get key location query until after it has checked whether the results have satisfied the min rows and can return early.
This fixes an assert in the GetMappedRange that depends on the range read returning once it has at least one result.

Fix check in getExactRange that determines whether we can return early

---

fdbcli/TenantCommands.actor.cpp
fdbcli/tests/metacluster_fdbcli_tests.py
fdbserver/workloads/MetaclusterRestoreWorkload.actor.cpp
metacluster/include/metacluster/ConfigureTenant.actor.h
metacluster/include/metacluster/RestoreCluster.actor.h

Cherry-Pick of #10507
If we restore a cluster and a previously created tenant was not included in the backup, then the tenant will be marked in an error state on the management cluster. It is then up to the operator to resolve the error, generally by deleting the tenant and recreating it if needed.
There is, however, the possibility that we restored a backup that was older than we wanted, and a newer backup would have the tenant. If we tried to restore the newer backup, it would not leave the previously missing tenant in a fully usable state.
We need to have a way to deal with this case. One option is to allow us to clear the error state of a tenant, and that can be performed before (or maybe even after) the second restore.
Test plan:
Joshua test 100K run …

Support restoring a cluster with a tenant in the error state (Cherry-Pick #10507 to snowflake/release-71.3)

---

fdbclient/include/fdbclient/SimKmsVault.cpp

SimKmsVault unit test when run as part of simulation Random test, based on the test order, SimKmsVaultKeyCtx can be initialized as part of some other test (FlowSingleton). Update the test to handle the scenario.

Update SimKmsVault unit test assert checking max encryption keys

---

fdbserver/ClusterController.actor.cpp
fdbserver/include/fdbserver/ClusterController.actor.h

Follow up PR of #10521 . Cluster controller examines the recovered peer from UpdateWorkerHealth request and remove it from degraded/disconnected peers.
Added unit test to test the new logic.

Cluster controller remove recovered peer in gray failure

---

fdbclient/TupleVersionstamp.cpp
fdbclient/include/fdbclient/FDBTypes.h
fdbclient/include/fdbclient/KeyBackedTypes.actor.h
fdbclient/include/fdbclient/TenantManagement.actor.h
fdbclient/include/fdbclient/TupleVersionstamp.h
fdbserver/workloads/MetaclusterManagementConcurrencyWorkload.actor.cpp
fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp
fdbserver/workloads/MetaclusterRestoreWorkload.actor.cpp
fdbserver/workloads/TenantManagementConcurrencyWorkload.actor.cpp
metacluster/MetaclusterMetadata.cpp
metacluster/include/metacluster/MetaclusterConsistency.actor.h
metacluster/include/metacluster/MetaclusterData.actor.h
metacluster/include/metacluster/MetaclusterMetadata.h
metacluster/include/metacluster/MetaclusterOperationContext.actor.h
metacluster/include/metacluster/RegisterCluster.actor.h
metacluster/include/metacluster/RestoreCluster.actor.h
tests/slow/MetaclusterRecovery.toml

Previously, the metacluster restore test did not use the metacluster to validate that it was functional after restoring. This updates the test to run the metacluster management workload on a restored metacluster.
This also addresses two bugs that were caught by this test:
1. Concurrent restores could interleave in a way that caused the data cluster to be left in a permanently restoring state, thus preventing normal metacluster operations on that cluster.
2. The data clusters would keep tenant tombstone data for the old tenant ID prefix when restored to a metacluster with a different tenant ID prefix. This ended up causing problems for tenant creation.
Please …

Test use of the metacluster after a restore

---

fdbserver/DDTeamCollection.actor.cpp
fdbserver/MoveKeys.actor.cpp

Fix the correctness bug, where the storage server is removed so the metadata is removed at version 1112391220.
After version 1112391220, the storage tracker will exit and cancel updateStorageMetadata in the tracker.
But before updateStorageMetadata actor is canceled, the transaction to update metadata has been committed. So the removed metadata has been written again.
The fix is to check the serverList before updating within the same transaction. If the item is missing in serverList, it just means the server is removed. …

check serverList before update storage metadata

---

tests/CMakeLists.txt

This disables all parallel restore tests in simulation.
Passes 100K correctness: 20230621-172656-abeamon-d1fe2a42b15a32e9

Disable all parallel restore tests (snowflake/release-71.3)

---

fdbclient/TupleVersionstamp.cpp
fdbclient/include/fdbclient/FDBTypes.h
fdbclient/include/fdbclient/KeyBackedTypes.actor.h
fdbclient/include/fdbclient/TenantManagement.actor.h
fdbclient/include/fdbclient/TupleVersionstamp.h
fdbserver/workloads/MetaclusterManagementConcurrencyWorkload.actor.cpp
fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp
fdbserver/workloads/MetaclusterRestoreWorkload.actor.cpp
fdbserver/workloads/TenantManagementConcurrencyWorkload.actor.cpp
metacluster/MetaclusterMetadata.cpp
metacluster/include/metacluster/MetaclusterConsistency.actor.h
metacluster/include/metacluster/MetaclusterData.actor.h
metacluster/include/metacluster/MetaclusterMetadata.h
metacluster/include/metacluster/MetaclusterOperationContext.actor.h
metacluster/include/metacluster/RegisterCluster.actor.h
metacluster/include/metacluster/RestoreCluster.actor.h
tests/slow/MetaclusterRecovery.toml

Previously, the metacluster restore test did not use the metacluster to validate that it was functional after restoring. This updates the test to run the metacluster management workload on a restored metacluster.
This also addresses two bugs that were caught by this test:
1. Concurrent restores could interleave in a way that caused the data cluster to be left in a permanently restoring state, thus preventing normal metacluster operations on that cluster.
2. The data clusters would keep tenant tombstone data for the old tenant ID prefix when restored to a metacluster with a different tenant ID prefix. This ended up causing problems for tenant creation.
Passed 100K correctness with 1 [unrelated failure](https://github.com/apple/foundationdb/pull/10536): …

Test use of the metacluster after a restore (snowflake-71.3)

---

fdbserver/DDTeamCollection.actor.cpp
fdbserver/MoveKeys.actor.cpp

Fix the correctness bug, where the storage server is removed so the metadata is removed at version 1112391220.
After version 1112391220, the storage tracker will exit and cancel updateStorageMetadata in the tracker.
But before updateStorageMetadata actor is canceled, the transaction to update metadata has been committed. So the removed metadata has been written again.
The fix is to check the serverList before updating within the same transaction. If the item is missing in serverList, it just means the server is removed.
100k pass: 20230621-223935-xwang-bbf1463962b9fe14
#10540  …

check serverList before update storage metadata (cherry-pick to 71.3)

---

fdbclient/BackupAgentBase.actor.cpp
tests/restarting/from_5.1.7_until_6.3.0/DrUpgradeRestart-1.txt
tests/restarting/from_5.1.7_until_6.3.0/DrUpgradeRestart-2.txt
tests/restarting/from_6.3.13_until_7.2.0/DrUpgradeRestart-1.txt
tests/restarting/from_6.3.13_until_7.2.0/DrUpgradeRestart-2.txt
tests/restarting/from_7.2.0_until_7.3.0/DrUpgradeRestart-1.toml
tests/restarting/from_7.2.0_until_7.3.0/DrUpgradeRestart-2.toml
tests/restarting/from_7.3.0/DrUpgradeRestart-1.toml
tests/restarting/from_7.3.0/DrUpgradeRestart-2.toml

This modifies a buggify to less frequently insert a delay and decreases the TPS rate of the cycle test being run during the DR in order to decrease the runtime of the DR upgrade tests.

Speed up DR upgrade tests

---

fdbclient/RESTClient.actor.cpp
fdbclient/RESTUtils.actor.cpp
fdbclient/include/fdbclient/RESTUtils.h
fdbserver/RESTKmsConnector.actor.cpp
tests/fast/RESTUnit.toml

* EaR: Update KMS URL refresh policy and fix bugs
Description
RESTKmsConnector implements discovery and refresh semantics i.e. on bootstrap it discovers KMS Urls and periodically refresh the URLs (handle server upgrade scenario). The current implementation caches the URLs in a min-heap, as part of serving a request, actor pops out elements from min-heap and attempts connecting to the server, on failure, the URL is temporarily stored in a stack, at the end of the request processing, the stack is merged back into the heap. The code doesn't work as expected if there are multiple requests consumes the heap causing following issues:
1. Min-heap would retain old URLs replaced by latest refresh (stack merge)
2. URL discovery file is read more than expected as multiple requests can empty heap, …

EaR: Update KMS URL refresh policy and fix bugs (#10382)

---

fdbclient/include/fdbclient/GetEncryptCipherKeys_impl.actor.h

Description
Optimize logging emitted from GetEncryptCipherKey module, especially the one more useful for debugging and not very useful in the production
Testing
SwizzledRollbackSideBand - randomSeed (276500218)
devRunCorrectness - 100k
(cherry picked from commit 4f21e0cfcd018f02c81b7ae25bdf7b09dc4fc738)

EaR: Optimize logging from GetEncryptCipherKey (#10326)

---

fdbserver/workloads/MutationLogReaderCorrectness.actor.cpp

This decreases its overall duration and helps avoids timeouts.
Passed 100K correctness: 20230622-204338-abeamon-08d501a986ce66ef

Decrease the number of records in MutationLogReaderCorrectness (snowflake/release-71.3)

---

fdbclient/BackupAgentBase.actor.cpp
tests/restarting/from_5.1.7_until_6.3.0/DrUpgradeRestart-1.txt
tests/restarting/from_5.1.7_until_6.3.0/DrUpgradeRestart-2.txt
tests/restarting/from_6.3.13_until_71.2.0/DrUpgradeRestart-1.txt
tests/restarting/from_6.3.13_until_71.2.0/DrUpgradeRestart-2.txt
tests/restarting/from_71.2.0_until_71.3.0/DrUpgradeRestart-1.toml
tests/restarting/from_71.2.0_until_71.3.0/DrUpgradeRestart-2.toml
tests/restarting/from_71.3.0/DrUpgradeRestart-1.toml
tests/restarting/from_71.3.0/DrUpgradeRestart-2.toml

This modifies a buggify to less frequently insert a delay and decreases the TPS rate of the cycle test being run during the DR in order to decrease the runtime of the DR upgrade tests.
Passed 100K correctness: 20230623-161027-abeamon-5a2087cd8a10ca13

Speed up DR upgrade tests (snowflake/release-71.3)

---

fdbserver/workloads/MutationLogReaderCorrectness.actor.cpp

This decreases its overall duration and helps avoids timeouts.

Decrease the number of records in MutationLogReaderCorrectness

---

tests/fast/BackupCorrectnessClean.toml

Decrease the transaction rate to speed up the backup correctness clean test

Speed up BackupCorrectnessClean

---

fdbclient/ServerKnobs.cpp
fdbserver/ClusterController.actor.cpp
fdbserver/include/fdbserver/ClusterController.actor.h
fdbserver/include/fdbserver/WorkerInterface.actor.h
fdbserver/worker.actor.cpp

Cherry pick explicit peer recovery to release 7.3. Including:
* #10325 
* #10521 
* #10534 

[Release 7.3] Gray failure degraded/disconnected peer recovery

---

tests/fast/BackupCorrectnessClean.toml

Decrease the transaction rate to speed up the backup correctness clean test
Passed 100K correctness: 20230623-232535-abeamon-5ca566c2043b08a7

Speed up BackupCorrectnessClean (snowflake/release-71.3)

---

fdbclient/NativeAPI.actor.cpp

This fixes a bug found by ASAN.

cancel durable change feed actors in DatabaseContext destructor

---

fdbclient/ServerKnobs.cpp
fdbserver/ClusterController.actor.cpp
fdbserver/ClusterController.actor.h
fdbserver/WorkerInterface.actor.h
fdbserver/worker.actor.cpp

Cherry pick explicit peer recovery to release 7.1. Including:
* #10325 
* #10521 
* #10534 

[Release 7.1] Gray failure degraded/disconnected peer recovery

---

fdbserver/BlobManifest.actor.cpp
fdbserver/BlobWorker.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/workloads/BlobRestoreWorkload.actor.cpp

This PR is to fix a few correctness failures
1.  blob restore is stuck.
2. Assertion finalSplit.keys.size() > 2 failed
100K blobrestore test passed

Fix blob restore stuck issue

---

fdbclient/BackupAgentBase.actor.cpp

Cherry pick #10059 
Adds blob key ranges to system mutation logs.
100K correctness test passed 20230628-150329-huliu-ba898fe4a0c7942f

Adding blob ranges to backup keys

---

fdbclient/BackupAgentBase.actor.cpp
fdbclient/BlobCipher.cpp
fdbclient/BlobGranuleFiles.cpp
fdbclient/ClientKnobs.cpp
fdbclient/FileBackupAgent.actor.cpp
fdbclient/include/fdbclient/ClientKnobs.h
fdbclient/include/fdbclient/CommitTransaction.h
fdbclient/include/fdbclient/GetEncryptCipherKeys_impl.actor.h
fdbserver/CommitProxyServer.actor.cpp
fdbserver/KeyValueStoreMemory.actor.cpp
fdbserver/fdbserver.actor.cpp
fdbserver/include/fdbserver/IPageEncryptionKeyProvider.actor.h
fdbserver/include/fdbserver/IPager.h
fdbserver/workloads/EncryptionOps.actor.cpp
fdbserver/workloads/SaveAndKill.actor.cpp
tests/TestRunner/local_cluster.py
tests/fast/BlobRestoreTenantMode.toml
tests/fast/EncryptionOps.toml
tests/fast/EncryptionUnitTests.toml
tests/restarting/from_71.3.0/BlobGranuleRestartCorrectness-1.toml
tests/restarting/from_71.3.0/BlobGranuleRestartCorrectness-2.toml
tests/restarting/to_71.3.1/BlobGranuleRestartCorrectness-1.toml
tests/restarting/to_71.3.1/BlobGranuleRestartCorrectness-2.toml
tests/slow/BlobGranuleCorrectness.toml
tests/slow/BlobGranuleCorrectnessClean.toml

Description
Given Configurable encryption has been checked in and being tested via simulation for more than a month and also to avoid penalty of accessing KNOBS in inline commit path, patch retires the KNOB and make ConfigurationEncryption default EaR mode for FDB.
BlobCipher still supports the old format header and encryption semantics, will remove the dead code as a followup PR.
Testing
(cherry picked from commit a7f33a5b67cf3123e72bd7db4d5d514c6a7abc84)

EaR: Remove usage of ENABLE_CONFIGURABLE_ENCRYPTION knob

---

fdbserver/ConsistencyScan.actor.cpp

Cherry-pick #10502 
100k correctness: 20230615-193302-jslocum-b0aa9db2f4402b8e: 0 failures
Did manual testing to confirm throttling worked as expected

[snowflake/release-71.3] fix per-scan-loop throttling to properly throttle in the loop

---

fdbserver/BlobManifest.actor.cpp
fdbserver/BlobWorker.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/workloads/BlobRestoreWorkload.actor.cpp

Cherry-Pick of #10574
100K test passed
20230628-161600-huliu-77ff5a59e54e921a
This PR is to fix a few correctness failures
1.  blob restore is stuck.
2. Assertion finalSplit.keys.size() > 2 failed

Fix blob restore stuck issue (Cherry-Pick #10574 to snowflake/release-71.3)

---

fdbclient/MultiVersionTransaction.actor.cpp

Cherry-Pick of https://github.com/apple/foundationdb/pull/10576
Throw error in tenantUpdater if result is an error
Duplicate of https://github.com/apple/foundationdb/pull/10577 because changes can't be pushed to origin
100k correctness with 1 known unrelated failure on `20230628-225819-jfu-810910c7a465645c`

Fix bug in FDB MultiVersionTransaction.actor.cpp (Cherry-Pick #10576 to snowflake/release-71.3) 

---

fdbserver/BlobWorker.actor.cpp

Fix ubsan error from tests/slow/BlobGranuleVerifyBalanceClean.toml
`/mnt/ephemeral/huliu/frostdb/flow/include/flow/flow.h:1092:33: runtime error: member access within address 0x7f2ce7d2bac0 which does not point to an object of type 'const NotifiedQueue<ReadResult<Standalone<RangeResultRef>>>
`

Fix ubsan error BlobGranuleVerifyBalanceClean.toml

---

fdbserver/BlobWorker.actor.cpp

Cherry-Pick of #10581
100k correctness test
20230629-151620-huliu-bc5245835abd0a0d
Fix ubsan error from tests/slow/BlobGranuleVerifyBalanceClean.toml
`/mnt/ephemeral/huliu/frostdb/flow/include/flow/flow.h:1092:33: runtime error: member access within address 0x7f2ce7d2bac0 which does not point to an object of type 'const NotifiedQueue<ReadResult<Standalone<RangeResultRef>>>
`

Fix ubsan error BlobGranuleVerifyBalanceClean.toml (Cherry-Pick #10581 to snowflake/release-71.3)

---

fdbserver/BlobManager.actor.cpp
fdbserver/Status.actor.cpp

This PR fixed a problem in status json. Without this PR, manifest backup fields in status json doesn't show up after blob manager restart

Show manifest dump info in status json even when no flushing

---

fdbserver/SimulatedCluster.actor.cpp
fdbserver/include/fdbserver/WorkerInterface.actor.h

Fix worker server treating IoTimeoutError as injected fault in trace log when (a) in non-simulation, or (b) in simulation but the process is actually reliable.

fix worker server reporting IoTimeoutError as injected fault

---

fdbrpc/include/fdbrpc/simulator.h
fdbrpc/sim2.actor.cpp
fdbserver/workloads/ClogTlog.actor.cpp

Current SimClogging only simulates high latency instead of disconnection. Adding a functionality to simulate connection failure between a specific pair of machines.
This is tested using the ClogTlog workload.
Simulated connection failure is logged like following
```
trace.0.0.0.0.13132.1688755404.7EuGiY.0.2.xml:<Event Severity="10" Time="207.158469" DateTime="2023-07-07T18:43:47Z" Type="SimulatedDisconnection" Machine="2.0.1.5:1" ID="0000000000000000" Phase="Connect" 
```

Simulate connection failure between specific pairs of machines

---

fdbclient/BlobGranuleFiles.cpp

Doing this as a global constant appears to change the unseed very occasionally, and doing it as a static constant in the function where it is used fixes it.
I'm not 100% clear why this fixes it but this is a bit cleaner anyway.

fixing apparent source of nondeterminism in bgfiles

---

fdbclient/include/fdbclient/KeyBackedTypes.actor.h
fdbserver/workloads/AutomaticIdempotencyWorkload.actor.cpp

The automatic idempotency test checks whether it has cleaned up too many idempotency keys and fails if so. This check uses timestamps generated prior to commit to make sure that we haven't deleted keys that are too new, but this runs into a subtle issue.
When trying to figure out what timestamps have been deleted, it looks at the oldest remaining timestamp and then sees what timestamps were created before that. Any timestamp created before that is assumed deleted, and the largest of those is treated as the timestamp that we deleted through. However, the timestamps used for deletion and the timestamps used in the test are not exactly the same, and if there is a difference then this can cause us to think that the most recently deleted timestamp is much newer than it actually was.
To correct …

Automatic idempotency test flagged improper cleanup

---

fdbclient/include/fdbclient/TenantManagement.actor.h
metacluster/include/metacluster/TenantConsistency.actor.h

If tenant mode is REQUIRED, then we should verify that in the normal key space, no data exists outside tenants' prefixes. This applies to data clusters (also known as partition clusters) in a metacluster and standalone clusters with tenants.
For the management cluster of a metacluster, we should verify that no data exists outside the prefix ranges specified by `tenant/` and `metacluster/` in the normal key space.
Test plan:
devRunCorrectnessFiltered +Metacluster* +Tenant* --max-runs 100000
20230702-052847-yajin-082705d269588494. 0 Failure
devRunCorrectness --max-runs 100000
20230702-134219-yajin-e9cce7bd165e70a9. 1 Failure, unrelated to this change
Please check …

SNOW-791059 Verify no data outside tenants in REQUIRED mode

---

tests/restarting/to_71.3.0/BlobGranuleRestartCycle-1.toml
tests/restarting/to_71.3.0/BlobGranuleRestartLarge-1.toml
tests/restarting/to_71.3.1/BlobGranuleRestartCorrectness-1.toml

Description
Given change-feed cache encryption support got added later to 71.3.0 release, using the features for those restarting test leads to tripping asserts due to mismtach detection for EaR state.
Testing

Disable Change-Feed cache for 71.3 restarting tests

---

fdbserver/tester.actor.cpp

As title.
With default tenant, not setting this ACCESS_SYSTEM_KEYS option can lead to the transaction reading
from somewhere else but not the tenant map, thus returning incorrect results.
100K Run:
- 20230711-175034-yajin-616c084995017695. All failures are in BlobGranule restarting tests

Allow reading from system keyspace even with default tenant

---

fdbclient/ClientKnobs.cpp
fdbclient/ServerKnobs.cpp

Disabling backup keys logging in simulation to avoid TracingTooManyLines error

Disabling backup keys logging in simulation to avoid TracingTooManyLines error

---

bindings/c/CMakeLists.txt

Fix Implib.so imports when 'amd64' architecture is using

---

fdbserver/DDTeamCollection.actor.cpp

After a storageMetadataTracker detects that a storage server has been removed, the storageServerTracker should stop tracking this server. Without this fix, the
```
when(wait(storageMetadataTracker)) {}
```
will be triggered repeatedly, and the outer loop may busy looping printing trace lines ("UndesiredStorageServer"), which eventually hit `TracedTooManyLines` error.
Test plan:
This failure was captured on snowflake/release-71.3 branch, but I believe the bug is also present on main. To verify that it fixes the issue, do the following:
1. Checkout branch snowflake/release-71.3
2. Profile: team ubsan
3. Commit: 507bbc98e29236e4ac2c11ac602fc7b7b823e225
4. Command: devRetryCorrectnessTest bin/fdbserver -r simulation -f tests/fast/SwizzledRollbackSideband.toml -s 1845441210 -b on  --crash …

Stop tracking a storage server after its removal

---

cmake/ConfigureCompiler.cmake
fdbserver/CMakeLists.txt
flow/include/flow/Optional.h
flow/include/flow/flow.h
flow/include/flow/swift_concurrency_hooks.h
flow/include/flow/swift_stream_support.h
flow/include/flow/swift_support.h

- We must pass `WITH_SWIFT` to clang importer.
- Migrate to `SWIFT_CONFORMS_TO_PROTOCOL` from `<swift/bridging>` correctly

[swift] fix Swift specific build regressions

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/GlobalTagThrottler.actor.cpp
fdbserver/Ratekeeper.actor.cpp
fdbserver/include/fdbserver/TagThrottler.h

Previously, when calculating the limiting TPS for a throttlingId, the quota throttler would take into account total quotas. With this PR, quotas are ignored when computing limiting TPS. The formula is simply: `limitingThrottlingRatio * currentTps`. This has two advantages:
- It is easier to reason about
- It allows setting extremely large quotas for workloads that we only want to throttle in the saturating case. (Previously these workloads would receive an unfairly large throughput in the saturating case) …

Simplify `GlobalTagThrottler` limiting TPS calculation

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/GlobalTagThrottler.actor.cpp
fdbserver/Ratekeeper.actor.cpp
fdbserver/include/fdbserver/TagThrottler.h

This is a backport of https://github.com/apple/foundationdb/pull/10633.

(snowflake/release-71.3) Simplify `GlobalTagThrottler` limiting TPS calculation

---

fdbserver/CommitProxyServer.actor.cpp

Specifically, added `(key, commitVersion)` pairs to `\xff\x02\dlog` space.
Manually verified backup mutations are logged in the new space.

Debug all backup keys by inserting them into the DB [release-7.1]

---

bindings/java/src/main/com/apple/foundationdb/LocalityUtil.java

It was difficult to get the locality information with both ip addresses and ports, So I added more information in javadoc

Added more javadoc information for com.apple.foundationdb.LocalityUtil.getAddressesForKey

---

fdbclient/BackupAgentBase.actor.cpp
fdbclient/include/fdbclient/BackupAgent.actor.h

Fix a bug of hash value for backup log keys in getLogKey()

---

fdbclient/AuditUtils.actor.cpp
fdbclient/ManagementAPI.actor.cpp
fdbclient/SpecialKeySpace.actor.cpp
fdbclient/include/fdbclient/AuditUtils.actor.h
fdbserver/DDTxnProcessor.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/MoveKeys.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/workloads/ValidateStorage.actor.cpp

This PR introduces a new DDMode called "SecurityMode". In the security mode, data moves are not allowed but auditStorage is enabled. DD security model is used when inconsistency shard location metadata is detected. At this time, the data distributor can have some serious bugs and the functionality of the data distributor cannot be trusted, and we want to enable auditStorage to do a consistency check and investigate the issue.
With this PR, we have three DDModes: (1) 0, DD is disabled; (2) 1, DD is enabled; (3) 2, DD is enabled but is in Security Mode.
MoveKeyLock is grabbed in the DD security mode.
Note that this PR does not break existing contract of blob restore and snapshot. When blob restore/snapshot starts, movekeys_conflicts is thrown (e.g. by polling MoveKeyLock) to trigger the …

Add DD Security Mode

---

fdbclient/AuditUtils.actor.cpp
fdbclient/ManagementAPI.actor.cpp
fdbclient/SpecialKeySpace.actor.cpp
fdbclient/include/fdbclient/AuditUtils.actor.h
fdbserver/DDTxnProcessor.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/MoveKeys.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/workloads/ValidateStorage.actor.cpp

Commit: [fix lock used by waitUntilDataDistributorExitSecurityMode](https://github.com/apple/foundationdb/pull/10660/commits/f4f1e2aa7235022e3af783402abff04aca3adff6) fixes moveKeyLock used by waitUntilDataDistributorExitSecurityMode. In the main branch, DD->lock references to DD->context->lock. So, after DD takes the lock, DD->context->lock is set. In release 73,  DD->lock does not references to DD->context->lock. So, DD->context->lock is empty after DD takes the lock. This commit avoids using DD->context->lock.
Correctness test with three irrelevant failures (i.e. external timeout by rocksdb engine, no audit module runs in the test):
20230723-212326-zhewang-bffe8ad438e44d6b           compressed=True data_size=33405135 duration=5150009 ended=100000 fail=3 fail_fast=10 max_runs=100000 …

[Release-7.3] Cherry-pick Add DD Security Mode (#10646)

---

cmake/ConfigureCompiler.cmake

It seems that in the current Okteto docker environment, USE_DTRACE flag is set ON by default, yet the generated code is not using DTrace since the environment does not support DTRACE. Explicitly print out the final result will be helpful understanding why DTrace may not available in the final code.

Report to stdout if DTrace is enabled

---

fdbcli/DebugCommands.actor.cpp
fdbcli/fdbcli.actor.cpp
fdbcli/include/fdbcli/fdbcli.actor.h

`checkall key1 key2` can perform consistency check on a (small) key range, consider `consistencycheck` for large key ranges.
Also refactor `getlocation` to bypass GRV calls.

 Add "checkall" debug command for fdbcli

---

fdbcli/DebugCommands.actor.cpp
fdbcli/fdbcli.actor.cpp
fdbcli/include/fdbcli/fdbcli.actor.h

cherrypick #10687
* Add "checkall" for checking \xff\x02/blog/ keys
* Avoid GRV calls for getlocation
* Update comments
* Add non-stopping checking and remove verbose output
* Update checkall command to accept customized range
* Fix format
* Fix a compiling issue and output

 Add "checkall" debug command for fdbcli [release-7.3]

---

fdbserver/Ratekeeper.actor.cpp

backport https://github.com/apple/foundationdb/pull/10627
Dropped the test, because there is a gap between 7.1 and main, which could take significant more amount of time.

Remove SS entries from RateKeeper once it is down [release-7.1]

---

packaging/make_public.py

Fixes #10700. (See that issue for a more detailed description of the problem.) `make_public.py` will fail if the cluster file contains comments, which is permitted per the [format](https://apple.github.io/foundationdb/administration.html#cluster-file-format).
Since this is a change to a Python file in the `packaging/` directory, and not the core FoundationDB application itself, I performed manual testing on the updated version of the file on a cluster I had running locally.

Configure make_public.py to ignore comments in the cluster file

---

documentation/sphinx/source/release-notes/release-notes-7130.rst
documentation/sphinx/source/release-notes/release-notes-7131.rst

Description
Remove 'latest' release notes marker from snowflake 71.3 & 71.3.1 release notes
Testing

Fix release-notes label

---

fdbclient/ServerKnobs.cpp

Based on calculations of expected write rate, further reduce the frequency of polling tenants' storage usage for the storage quota feature (`TENANT_CACHE_STORAGE_USAGE_REFRESH_INTERVAL`). The goal is to avoid overwhelming DD and storage servers with the requests for estimating the storage usage. Accordingly, also update related knobs (`TENANT_CACHE_LIST_REFRESH_INTERVAL` and `TENANT_CACHE_STORAGE_QUOTA_REFRESH_INTERVAL`).

Reduce the frequency of polling tenants' storage usage

---

cmake/ConfigureCompiler.cmake

1. The original lines are problematic -- <> are not paired.
2. Fixing the original line by pairing <> would cause build failure if
valgrind is turned on.
3. git grep BOOST_USE_VALGRIND returned only one single usage, which is
in the cmake file.
4. Removing the lines caused build success.

Fix the ConfigureCompiler.cmake 

---

cmake/FDBComponents.cmake
fdbserver/CMakeLists.txt
fdbserver/KeyValueStoreRocksDB.actor.cpp
fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
fdbserver/RocksDBCheckpointUtils.actor.cpp
fdbserver/RocksDBLogForwarder.actor.cpp
fdbserver/SimulatedCluster.actor.cpp
fdbserver/include/fdbserver/RocksDBLogForwarder.h
fdbserver/include/fdbserver/SimulatedCluster.h
tests/CMakeLists.txt

Previously we have to modify SimulatedCluster source code to enable/disable RocksDB storage engine in simulations. Now it is doable by using cmake flags/ccmake gui by setting the OPTION
WITH_ROCKSDB
ON/OFF.

Add a flag for enabling/disabling RocksDB storage engine in simulations

---

fdbserver/GrvProxyServer.actor.cpp

cherry pick of #10724
This causes the grv proxy to get stuck not processing any transactions
passed 100k correctness

fix: when requests are dropped from the queue the txnRequestOut becomes inconsistent with txnRequestIn

---

fdbserver/SimulatedCluster.actor.cpp

Enabling encryption in simulation forces the use of Redwood, which is the only storage engine type supporting encryption currently. We want to turn down the probability of testing Redwood in simulation, and so we need to turn the probability for encryption as well.

EaR: turn down the probability of enabling encryption in simulation

---

fdbserver/BlobManager.actor.cpp
fdbserver/BlobManifest.actor.cpp
fdbserver/BlobWorker.actor.cpp

Potential bug fix stuck blob manager, and just correct anyway even if it's not the cause of the fix.
after blob restore fix:
50k BlobRestoreTenant* test - 20230807-175903-jslocum-c097c3b0452c579e  
100k normal correctness - 20230807-180154-jslocum-c097c3b0452c579e
previous tests:
100k BlobGranuleCorrectness* with additional testing - 20230807-163755-jslocum-38ac1be71766caa0
100k normal correctness -  20230807-170707-jslocum-3330220ee725f5c0  - found issue with blob restore

Tenant watch fix

---

cmake/CompileBoost.cmake
cmake/ConfigureCompiler.cmake

Creating a shadow copy of the C++ and linker flags for the boost build because configure_file cannot expand generator expressions. `file(GENERATE...` can in theory, but CMake runs into memory corruption when it tries.
The generator expressions are used to filter out flags that are intended for the C/C++ compiler from going to the Swift compiler when building with Swift enabled, which doesn't understand them. The boost build system isn't integrated with CMake so flags are passed via a call to `configure_file` which generates are configuration, and CMake needs a target to expand target-generator-expressions agains, like `LINK_LANGUAGE`, for instance. Thus, generator expressions are not being expanded and the flags include the full generator expression, which b2 doesn't know how to deal with …

Shadow Cxx flags for Boost build

---

cmake/ConfigureCompiler.cmake

The issue caused Boost build failure is found and fixed at #10733. Here the flag BOOST_USE_VALGRIND is reintroduced back.

Bring Boost Valgrind flags back

---

fdbserver/GrvProxyServer.actor.cpp

cherrypick #10724
20230808-195422-jzhou-7945f311d8d60fbd

fix grv queue stats when requests are dropped [release-7.1]

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/workloads/ConsistencyCheck.actor.cpp

Introduce two new server knobs: 
CONSISTENCY_CHECK_ROCKSDB_ENGINE and CONSISTENCY_CHECK_SQLITE_ENGINE
Both knobs are off by default.
When both knobs are off, consistency check checks all data shards.
When any knob is on, consistency check only check data corruption for a shard which is in at least one SS with the specified storage engine.
When both knobs are on, consistency check does check for rocksdb.
Note that when enabling the new knobs, we may want to shorten CONSISTENCY_CHECK_ONE_ROUND_TARGET_COMPLETION_TIME to shorten the check period.
**Correctness tests**
100K correctness test with feature off
20230809-013840-zhewang-9d6d891996d26264           compressed=True data_size=23137221 duration=4920346 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 …

Add consistency check for rocksdb only

---

fdbclient/S3BlobStore.actor.cpp

For virtual hosting mode, `S3BlobStore::bucketExists` will issue an HTTP request with an empty `resource`, which will generate an incorrect HTTP method field.
This PR converts the empty `resource` to `/` to avoid the above issue.

Avoid to send request to empty resource

---

fdbserver/SimulatedCluster.actor.cpp
fdbserver/include/fdbserver/WorkerInterface.actor.h

Fix worker server treating IoTimeoutError as injected fault in trace log when (a) in non-simulation, or (b) in simulation but the process is actually reliable.

fix worker server reporting IoTimeoutError as injected fault (Cherry-pick #10589 to snowflake/release-71.3)

---

fdbclient/ServerKnobs.cpp

Cherry-pick https://github.com/apple/foundationdb/pull/10678

[snowflake/release-71.3] Reduce the frequency of polling tenants' storage usage

---

fdbserver/BlobManager.actor.cpp
fdbserver/Status.actor.cpp

Cherry-Pick of #10584
100K correctness 20230630-023510-huliu-9a12d3919540030c(with 1 unrelated failure VersionStampSwitchover.toml)
This PR fixed a problem in status json. Without this PR, manifest backup fields in status json doesn't show up after blob manager restart

Show manifest dump info in status json even when no flushing (Cherry-Pick #10584 to snowflake/release-71.3)

---

fdbserver/BlobManager.actor.cpp

Cherry-Pick of #10616
100K correctness 20230714-155826-huliu-d9648324563ccaf2. 1 failure from tests/restarting/from_5.0.0_until_6.3.0/CycleTestRestart-2.txt which is known and unrelated to blob
This is a fix for correctness failures. We need to find full keys for split points before calling alignKeys().

Find next full keys for split points (Cherry-Pick #10616 to snowflake/release-71.3)

---

fdbclient/ServerKnobs.cpp
fdbserver/KeyValueStoreShardedRocksDB.actor.cpp

1. Trace shardedrocks manifest size (in the unit of byte).
2. Try to reduce the chance of external timeout in simulation by reducing ROCKSDB_BLOCK_CACHE_SIZE.
3. Try to reduce the chance of external timeout in simulation by increasing ROCKSDB_MAX_MANIFEST_FILE_SIZE.

Trace shardedrocks manifest size

---

fdbserver/Ratekeeper.actor.cpp

This PR backports https://github.com/apple/foundationdb/pull/10725.

(snowflake/release-71.3) Monitor multiple write tags in `StorageQueueInfo::refreshCommitCost`

---

fdbserver/DDTeamCollection.actor.cpp

#10711 
100k correctness pass: `20230808-185121-xwang-ed62267b0dbf7830 ` 

Fix tss kill logic: only disable Tss check when zeroHealthyTeams=false (cherry-pick to snowflake/release-71.3) 

---

packaging/docker/Dockerfile
packaging/docker/Dockerfile.eks
packaging/docker/fdb_single.bash

add script to allow starting and running a singleton FDB database in the foundationdb docker image
This will not change the default behavior of the docker image, starting a standalone db will require overriding the entrypoint for the docker container. the command would look something like this: 
```
docker run -it --rm  --entrypoint /var/fdb/scripts/fdb_single.bash foundationdb/foundationdb:7.1.37
```

run singleton fdb instance in docker

---

fdbserver/BlobWorker.actor.cpp

encryptionAtRestMode needs to be in the system keyspace so that it is encrypted with the cluster specific encryption key rather than a tenant key
Passed 100k correctness

encryptionAtRestMode needs to be in the system keyspace

---

fdbclient/BlobCipher.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/include/fdbclient/BlobCipher.h
fdbclient/include/fdbclient/BlobWorkerCommon.h
fdbclient/include/fdbclient/GetEncryptCipherKeys_impl.actor.h
fdbserver/BlobGranuleServerCommon.actor.cpp
fdbserver/BlobManager.actor.cpp
fdbserver/BlobWorker.actor.cpp
fdbserver/EncryptKeyProxy.actor.cpp
fdbserver/RESTKmsConnector.actor.cpp
fdbserver/include/fdbserver/BlobGranuleServerCommon.actor.h
fdbserver/storageserver.actor.cpp
flow/include/flow/genericactors.actor.h

Observability improvements throughout BM, BW, and EKP, and a bug fix from investigations
100k correctness: 20230807-133125-jslocum-a2086e5a26b5e07c - 1 unrelated failure - TracedTooManyLines in SwizzledRollbackSideband.toml due to a stuck all_logs_recruited recovery
100k BlobGranule* correctness: 20230807-133021-jslocum-a2086e5a26b5e07c  - 0 failuers

More bm observability 713

---

fdbclient/ServerKnobs.cpp
fdbserver/KeyValueStoreRocksDB.actor.cpp
tests/slow/ApiCorrectness.toml

20230811-184819-zhewang-04218835bf219ef0           compressed=True data_size=34628215 duration=6048880 ended=100000 fail=9 fail_fast=10 max_runs=100000 pass=99991 priority=100 remaining=0 runtime=0:51:41 sanity=False started=100000 stopped=20230811-194000 submitted=20230811-184819 timeout=5400 username=zhewang

Revert inappropriate setting of ApiCorrectness test

---

fdbclient/ServerKnobs.cpp
fdbserver/KeyValueStoreRocksDB.actor.cpp
fdbserver/KeyValueStoreShardedRocksDB.actor.cpp

cherrypick #10764 and #10771
Correctness test
20230811-202914-zhewang-87aac16714e6743a           compressed=True data_size=33441672 duration=6750507 ended=100000 fail=7 fail_fast=10 max_runs=100000 pass=99993 priority=100 remaining=0 runtime=1:10:31 sanity=False started=100000 stopped=20230811-213945 submitted=20230811-202914 timeout=5400 username=zhewang
Tested the new trace event in kubenetes tests

[Release-7.3] Cherry-pick rocks manifest size trace event and some fixes

---

fdbserver/BlobWorker.actor.cpp

encryptionAtRestMode needs to be in the system keyspace so that it is encrypted with the cluster specific encryption key rather than a tenant key.
Cherry pick of #10777
Passed 100k correctness

encryptionAtRestMode needs to be in the system keyspace 

---

tests/rare/TransactionTagSwizzledApiCorrectness.toml
tests/restarting/from_7.3.0/DrUpgradeRestart-1.toml
tests/slow/SwizzledDdBalance.toml
tests/slow/ddbalance.toml

clang nightly failed for these tests.

Disable more RocksDB simulation tests due to timeout issue

---

fdbserver/DDTeamCollection.actor.cpp

Cherry-Pick of #10630
After a storageMetadataTracker detects that a storage server has been removed, the storageServerTracker should stop tracking this server. Without this fix, the
```
when(wait(storageMetadataTracker)) {}
```
will be triggered repeatedly, and the outer loop may busy looping printing trace lines ("UndesiredStorageServer"), which eventually hit `TracedTooManyLines` error.
Test plan:
This failure was captured on snowflake/release-71.3 branch, but I believe the bug is also present on main. To verify that it fixes the issue, do the following:
1. Checkout branch snowflake/release-71.3
2. Profile: team ubsan
3. Commit: 507bbc98e29236e4ac2c11ac602fc7b7b823e225
4. Command: devRetryCorrectnessTest bin/fdbserver -r simulation -f …

Stop tracking a storage server after its removal (Cherry-Pick #10630 to snowflake/release-71.3)

---

fdbclient/ServerKnobs.cpp
fdbserver/storageserver.actor.cpp

Set BLOB_RESTORE_SKIP_EMPTY_RANGES knob to false as default. The case that we don't have tenant data during restore should be very rare in real prod env. 

Set BLOB_RESTORE_SKIP_EMPTY_RANGES default value to false

---

fdbserver/Status.actor.cpp

Description
Patch addresses occurrences where Status.actor ends up bubbling timeout error up to the ClusterController causing recovery to be triggered when ClusterGetStatus timeout for some reason.
Testing
devRunCorrectness - 100K - 20230817-004526-ahusain-674b98a12fc8084e (in-progress)

Prevent Status actor from bubbling up timeout error

---

fdbserver/worker.actor.cpp

Particularly, we want to revert commit 47ad10a3af2afd65320202bbaec1027f46f3cf66 from #10391 . This commit has been applied to release-7.3 branch in #10541 . Applied it twice reverted some of the changes in #10541 
Gray failure is currently broken in release-7.3

[release 7.3] Revert the latest "Refactor healthMonitor in worker.actor.cpp"

---

fdbserver/DDTeamCollection.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/worker.actor.cpp

This PR adds `StorageServerInitProgress` to track the progress from a worker receiving a SS recruit request to the worker completes recruitment and the SS finishes init.
The new trace event is in particular useful when we want to see if there is an existing SS init getting stuck and the worker says "AttemptedDoubleRecruitment" for the new SS request.
20230818-230804-zhewang-cfdf06dce88911c4           compressed=True data_size=34652725 duration=6742211 ended=100000 fail=6 fail_fast=10 max_runs=100000 pass=99994 priority=100 remaining=0 runtime=1:18:10 sanity=False started=100000 stopped=20230819-002614 submitted=20230818-230804 timeout=5400 username=zhewang …

Trace SS init progress

---

fdbcli/ConfigureCommand.actor.cpp

https://github.com/apple/foundationdb/pull/8103/files is never backported to 7.1

Fix inaccurate PPW configure return code[release-7.1]

---

fdbserver/DDTeamCollection.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/worker.actor.cpp

Correctness test:
20230819-021415-zhewang-c4b9bc7db403682c           compressed=True data_size=33511438 duration=6492321 ended=100000 fail=2 fail_fast=10 max_runs=100000 pass=99998 priority=100 remaining=0 runtime=1:06:12 sanity=False started=100000 stopped=20230819-032027 submitted=20230819-021415 timeout=5400 username=zhewang

[Release-7.3] Cherry pick trace ss init progress

---

fdbserver/BlobManifest.actor.cpp

Need to wait container->deleteFile() to be completed before proceeding.
100K correctness test passed. 20230817-202759-huliu-a1c814164369f5ee 
100K blobrestore test passed. 20230817-195321-huliu-fd962e2aa1a6bab0

Wait file deleted in blob manifest cleanup

---

fdbclient/S3BlobStore.actor.cpp

The PR closes #8882.
In the previous implementation, a temporary `std::string` is constructed and destroyed immediately after constructing the `StringRef`, so the latter is a dangling reference.

Fix guess region from s3 URL

---

fdbcli/AuditStorageCommand.actor.cpp
fdbclient/ManagementAPI.actor.cpp
fdbclient/include/fdbclient/Audit.h
fdbclient/include/fdbclient/ManagementAPI.actor.h
fdbserver/ClusterController.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/tester.actor.cpp
fdbserver/workloads/ValidateStorage.actor.cpp

Allow users to specify the storage engine type when triggering auditStorage for `ha` and `replica`. Given an engine type, the auditStorage checks a range if the range is owned by a server which is using the specified engine. If no engine type specified, the auditStorage checks all ranges. Currently, `sqlite`, `rocksdb`, and `shardedrocksdb` engine types are supported.
100K correctness test with 3 irrelevant failures
20230823-030512-zhewang-1d52e021c28d5b2c           compressed=True data_size=34669011 duration=7414677 ended=100000 fail=3 fail_fast=10 max_runs=100000 pass=99997 priority=100 remaining=0 runtime=1:01:15 sanity=False started=100000 stopped=20230823-040627 submitted=20230823-030512 timeout=5400 username=zhewang
100K validateStorage test
20230823-024949-zhewang-be54b671437f2ec0 …

Audit storage for specific engine

---

flow/Knobs.cpp
flow/include/flow/IConnection.h
flow/include/flow/Knobs.h
flow/network.cpp

The default is to prefer IPv6 addresses.
This fixes #10816.

Add a knob RESOLVE_PREFER_IPV4_ADDR to prefer IPv4 addresses

---

flow/include/flow/IConnection.h

Could return ipv6 addresses due to the bug in #10822

Fix picking of IPv4 addresses

---

fdbserver/DataDistribution.actor.cpp
fdbserver/SimulatedCluster.actor.cpp
fdbserver/workloads/PerpetualWiggleStorageMigrationWorkload.actor.cpp

* Audit service will not be enabled when using Mock DD TxnProcessor
* PerpentualWiggleStorageMigrationWorkload will not run when RocksDB is disabled
* In simulation, if the test specified storage engine is not supported, an error is raised with proper description.
Passed simulation 100k without RocksDB enabled

A few test failure fixes

---

fdbserver/DDShardTracker.actor.cpp
fdbserver/DDTeamCollection.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/include/fdbserver/DDShardTracker.h
fdbserver/include/fdbserver/DDTeamCollection.h

correctness (100k passed) : `20230824-224139-xwang-9f2350745c7e5808`
Output example when the simulation test is configured as `double`:
```
<Event Severity="10" Time="331.886378" DateTime="2023-08-24T22:57:37Z" Type="DDTrackerStats" Machine="[abcd::2:0:2:1]:2" ID="b83966aaebdac68f" Shards="11" TotalSizeBytes="32250" SystemSizeBytes="32250" RangeCountLargeTeam3="3" RangeCountLargeTeam4="1" RangeCountLargeTeam6="2" ThreadID="3898103688851930672" LogGroup="default" Roles="DD,SS" TrackLatestType="Original" />
<Event Severity="10" Time="331.880267" DateTime="2023-08-24T22:57:37Z" Type="TotalDataInFlight" Machine="[abcd::2:0:2:1]:2" ID="b83966aaebdac68f" Primary="1" TotalBytes="0" UnhealthyServers="0" ServerCount="28" StorageTeamSize="2" ZeroHealthy="0" HighestPriority="140" …
```

Add trace details about over-replicated shard and range count (snowflake/release-71.3)

---

flow/Knobs.cpp

Description
KMS health check monitor is instrumental in determing FDB <-> KMS connectivity issues (no connection or flakiness). Patch lower the check interval to be under FDB commit timeout to get assist diagnosing such issues.
The change do translate to increased request to KMS, however, the health-check asks for FDB system keyspace encryption key, it would be hitting cache on KMS server all the time (unless a KMS server got replaced and the first read is a miss)
Testing
devRunCorrectness - 100K - 20230824-161727-ahusain-95898cba71ad603b - one failure for `BackupToDBCorrectnessClean.toml` which is unrelated and due to Backup getting stuck causing test to fail …

FDBCORE-6014: Update KMS Health Check timeouts

---

fdbserver/BlobManager.actor.cpp

Flushing may throw errors in some race conditions. we can catch the error and retry after. No need to crash blob manager
100k correctness test passed - 20230825-000758-huliu-52be0338639e10bb

Catch initial flush error and avoid crashing blob manager

---

bindings/go/CMakeLists.txt

See
https://forums.foundationdb.org/t/macos-build-finds-wrong-fdb-c-h-for-go-bindings-patch-included/3929
for details

Fix MacOS go build

---

bindings/c/fdb_c.cpp
bindings/c/foundationdb/fdb_c.h
bindings/c/test/fdb_api.hpp

Restoring original function names for old blob granule API for backwards compatibility with previous 71.3 patches. 
The change does not need to merged to main, because is based on API refactoring performed only on that release branch

Restore original function names for old blob granule API [release-71.3]

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/ClusterController.actor.cpp
fdbserver/TLogServer.actor.cpp

Add a knob to guard the gray failure detection during TLog recovery, to easily turn it off if anything goes wrong.

Add a knob to guard the gray failure detection during TLog recovery

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/ClusterController.actor.cpp
fdbserver/TLogServer.actor.cpp

[Release 7.1] Add a knob to guard the gray failure detection during TLog recovery

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/ClusterController.actor.cpp
fdbserver/TLogServer.actor.cpp

[Release 7.3] Add a knob to guard the gray failure detection during TLog recovery

---

SWIFT_GUIDE.md
fdbserver/include/fdbserver/MasterData.actor.h
flow/include/flow/DeterministicRandom.h
flow/include/flow/genericactors.actor.h
flow/include/flow/swift_support.h
flow/include/flow/unsafe_swift_compat.h

This spelling is deprecated and will be removed in the future version of Swift:
```
__attribute__((swift_attr("import_as_ref")))
```
The new correct spelling is:
```
__attribute__((swift_attr("import_reference")))
```

[swift] Remove deprecated Swift attr spelling: `import_as_ref`

---

fdbclient/ServerKnobs.cpp
fdbserver/GrvProxyServer.actor.cpp
fdbserver/GrvProxyTagThrottler.actor.cpp
fdbserver/include/fdbserver/GrvProxyTagThrottler.h

This PR makes the following changes:
- Fixes a bug where rejected transactions were reported to ratekeeper as having started, causing average transaction cost under-estimation, and thus overly lax throttling.
- Fixes a bug where `GrvProxyStats::txnStartIn` (but not `GrvProxyStats::txnStartOut`) is incremented for rejected transactions. This caused the measured queue of pending GRV requests to grow indefinitely, leading to `grv_proxy_memory_limit_exceeded` errors.
- Buggifies `START_TRANSACTION_MAX_QUEUE_SIZE` to cause the above bug to fail simulation tests without the fix
- Adds tag throttler queue stats to `GrvProxyStats` …

Fix GRV queue leak

---

fdbserver/Status.actor.cpp

DatabaseContext currently leaks memory by creating `Counter`s with unique IDs on construction. Each status json call creates a new `DatabaseContext` object, causing a memory leak over time.

Avoid creating a DatabaseContext on every status json call

---

fdbcli/StatusCommand.actor.cpp
fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/BlobRestoreCommon.h
fdbserver/BlobMigrator.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/workloads/BlobRestoreWorkload.actor.cpp

It's a fix for correctness test failure about blob restore. It caused by a data movement race with blob restore state update.
A new data movement is started right before all key ranges are copied from blob migrator. It still believes it should copy from s3 in fetchKeys
Blob migrator marks data copy is done and move to next restore phase to apply mutation logs.
Blob restore completes and cleanup bgm keys
The data movement continues to read from blob, but gets blob_granules_transactions_too_old error because bgm keys was removed, so it skips the data copy …

Add a new blob restore state to fix a race after data copy

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/DDTeamCollection.actor.cpp
fdbserver/DDTeamCollection.h
fdbserver/DataDistribution.actor.cpp

Perpetual wiggle pause on balance of the cluster
cherry-pick of #8774

Perpetual wiggle pause on balance of the cluster

---

fdbbackup/backup.actor.cpp

If there are many (> 100) backup agents running, then when each backup agent reads the layer status doc for all other backup agents and computes the final backup layer JSON doc (which is done for agent coordination reasons) the JSON manipulations could take long enough to trigger a SlowTask event.  
This PR adds yields both after parsing and after merging the per-agent JSON documents to avoid a SlowTask.  This is similar to what the Cluster Controller does when computing layer status.

Add yields to backup agents to avoid slow tasks

---

fdbclient/ServerKnobs.cpp
fdbserver/BlobManifest.actor.cpp
fdbserver/BlobMigrator.actor.cpp

Change default config for blob restore and disable output to stdout

Tune blob restore default knob

---

fdbserver/DDTeamCollection.actor.cpp

Locality check on perpetualStorageWiggleIDPrefix when DD restarts
cherry-pick of #10877 

Locality check on perpetualStorageWiggleIDPrefix when DD restarts

---

fdbbackup/backup.actor.cpp
fdbclient/BackupAgent.actor.h
fdbclient/FileBackupAgent.actor.cpp

backup agent itself does not have proxy info.
This changes adds the proxy via a global var.
proxy is already passed in from cmd [here](https://github.com/apple/foundationdb/blob/d47e0eaaaa2e985f0ff14cb8cca889d3751d7d83/fdbbackup/backup.actor.cpp#L3784) or from env var [here](https://github.com/apple/foundationdb/blob/d47e0eaaaa2e985f0ff14cb8cca889d3751d7d83/fdbbackup/backup.actor.cpp#L3493)

Add proxy to backup agent via global var(release-7.1)

---

fdbbackup/backup.actor.cpp
fdbclient/FileBackupAgent.actor.cpp
fdbclient/include/fdbclient/BackupAgent.actor.h

backup agent itself does not have proxy info.
This changes adds the proxy via a global var.

Add proxy to backup agent via global var

---

documentation/sphinx/source/release-notes/release-notes-710.rst

Release notes for 7.1.38/7.1.39
cherry-pick of #10883 #10883

Release notes for 7.1.38/7.1.39

---

tests/fast/GetEstimatedRangeSize.toml
tests/fast/MutationLogReaderCorrectness.toml
tests/rare/WriteTagThrottling.toml
tests/slow/SharedBackupCorrectness.toml

Saw ExternalTimeout test failures for these.

Disable sharded rocks for more sim tests

---

fdbclient/include/fdbclient/Audit.h
fdbserver/DataDistribution.actor.cpp

100K correctness with irrelevant failures:
20230911-211758-zhewang-e95db43052ad755e           compressed=True data_size=34719940 duration=6567216 ended=100000 fail=3 fail_fast=10 max_runs=100000 pass=99997 priority=100 remaining=0 runtime=1:43:22 sanity=False started=100000 stopped=20230911-230120 submitted=20230911-211758 timeout=5400 username=zhewang
100K AuditStorage test:
20230911-211852-zhewang-d614cadb38411bd7           compressed=True data_size=34754018 duration=9331095 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:45:14 sanity=False started=100000 stopped=20230911-230406 submitted=20230911-211852 timeout=5400 username=zhewang
The general pull request guidelines can be found [here](https://github.com/apple/foundationdb/wiki/FoundationDB-Com …

Fix audit state serializer

---

tests/rare/ClogTlog.toml

The buggified value 120 triggers assertion failure at [LogSystemPeekCursor.actor.cpp:349](https://github.com/jzhou77/foundationdb/blob/bed58e38f230f5a67f1a46b1ad952e2aa68219c8/fdbserver/LogSystemPeekCursor.actor.cpp#L349), so restore it to the default.
Reproduction seed: -f ./tests/rare/ClogTlog.toml -s 537536800 -b on
commit: 163774cfd at release-7.1

Fix an assertion failure in tests

---

tests/rare/ClogTlog.toml

cherrypick #10894
The buggified value 120 triggers assertion failure, so restore it to the default.
Reproduction seed: -f ./tests/rare/ClogTlog.toml -s 537536800 -b on
commit: 163774cfd at release-7.1

Fix an assertion failure in tests [release-7.1]

---

fdbserver/tester.actor.cpp
fdbserver/workloads/DcLag.actor.cpp
fdbserver/workloads/GcGenerations.actor.cpp
metacluster/include/metacluster/ConfigureTenant.actor.h
metacluster/include/metacluster/MetaclusterConsistency.actor.h

When I'm trying to compile FoundationDb with the clang-17 compiler, I receive some compilation errors.
All of them relate to miscapability of comparing objects of `T` and `Optional<T>` types.
This PR fixed the compilation errors. It adds excplicit calls `Optional::present()` and `Optional::get()` to such comparing.

Fixed compiling foundationdb with the clang 17 compiler

---

fdbserver/worker.actor.cpp

This test validates that in-flight commit to the storage engine is properly handled. As found in https://github.com/apple/foundationdb/pull/10714, an engine could miss in-flight data and cause data corruptions.
The test case is modeled after the above corruption: insert data, then clear the data in the next commit to the storage engine, and finally verify that the data is cleared.

Add a test case for storage engine

---

fdbcli/GetAuditStatusCommand.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/storageserver.actor.cpp

SSShard dispatches audit tasks for any SS except for TSS.
However, when checking whether the SSShard completes, it checks all SSes.
So, SSShard audit cannot stop when there are TSSes.
This PR fixes this issue.
100K correctness with 2 irrelevant failures:
20230913-182451-zhewang-93d6990f5d847e68           compressed=True data_size=34722150 duration=5538344 ended=100000 fail=2 fail_fast=10 max_runs=100000 pass=99998 priority=100 remaining=0 runtime=1:32:55 sanity=False started=100000 stopped=20230913-195746 submitted=20230913-182451 timeout=5400 username=zhewang
100K AuditStorage:
20230913-182519-zhewang-c75e981c056ed633           compressed=True data_size=34754183 duration=8699036 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:18:38 sanity=False …

Fix SSShard Audit

---

fdbserver/DataDistribution.actor.cpp

100K correctness test with 4 irrelevant failures:
20230914-053527-zhewang-7915c27f65a8d5f8           compressed=True data_size=34728639 duration=6631017 ended=100000 fail=4 fail_fast=10 max_runs=100000 pass=99996 priority=100 remaining=0 runtime=1:25:01 sanity=False started=100000 stopped=20230914-070028 submitted=20230914-053527 timeout=5400 username=zhewang
100K ValidateStorage test:
20230914-053545-zhewang-7d0e16d28e001394           compressed=True data_size=34757861 duration=9504942 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:28:05 sanity=False started=100000 stopped=20230914-070350 submitted=20230914-053545 timeout=5400 username=zhewang …

Fix duplicated requests from DDDoAudit

---

fdbcli/GetAuditStatusCommand.actor.cpp
fdbclient/include/fdbclient/Audit.h
fdbserver/DataDistribution.actor.cpp
fdbserver/storageserver.actor.cpp

20230914-183045-zhewang-10f2a796f72500ab           compressed=True data_size=33605057 duration=6796592 ended=100000 fail=3 fail_fast=10 max_runs=100000 pass=99997 priority=100 remaining=0 runtime=1:36:35 sanity=False started=100000 stopped=20230914-200720 submitted=20230914-183045 timeout=5400 username=zhewang
100K AuditStorage:
20230914-183135-zhewang-19a88159b6352b18           compressed=True data_size=33635669 duration=11088227 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:45:58 sanity=False started=100000 stopped=20230914-201733 submitted=20230914-183135 timeout=5400 username=zhewang
Please check …

[Release-7.3] Cherry-pick multiple fixes to AuditStorage

---

fdbbackup/backup.actor.cpp
fdbclient/BackupContainer.actor.cpp
fdbclient/BackupContainerFileSystem.actor.cpp
fdbclient/S3BlobStore.actor.cpp

https://github.com/apple/foundationdb/pull/10885 added support for the proxy parameter in the backup_agent but the proxy was not passed down to all calls properly. This PR makes sure we use the proxy if specified. For better debugging I added the proxy value to some TraceEvents.
The PR is against 7.1 as I tested the setup with 7.1. Once the changes are approved I can open a PR against main, 7.3 and 7.2.

Correct the way how the backup agent makes use of the proxy and add proxy to trace events

---

fdbclient/SystemData.cpp
fdbclient/include/fdbclient/StorageServerInterface.h
fdbclient/include/fdbclient/SystemData.h
fdbserver/ClusterController.actor.cpp
fdbserver/DDTeamCollection.actor.cpp
fdbserver/MoveKeys.actor.cpp
fdbserver/Status.actor.cpp
fdbserver/include/fdbserver/ClusterController.actor.h
fdbserver/include/fdbserver/Status.actor.h
fdbserver/worker.actor.cpp

To retrieve storage metadata for every status json request is very expensive for clusters with a large number of storage servers. So I change the logic so that ClusterController actively monitors changes to storage metadata, and only retrieves them when there is a change.
20230915-213205-jzhou-0679d18f63c68424
20230918-204319-jzhou-cd2418370504940b
For the status json part, i.e.,
```
"storage_metadata" : {
"created_time_datetime" : "2023-09-18 20:27:54.526 +0000",
"created_time_timestamp" : 1695068874.5260661,
"storage_engine" : "ssd-2"
},
```
it is manually verified with a loop back cluster. …

ClusterController watches changes to storage metadata

---

fdbclient/SystemData.cpp
fdbclient/include/fdbclient/StorageServerInterface.h
fdbclient/include/fdbclient/SystemData.h
fdbserver/ClusterController.actor.cpp
fdbserver/DDTeamCollection.actor.cpp
fdbserver/MoveKeys.actor.cpp
fdbserver/Status.actor.cpp
fdbserver/include/fdbserver/ClusterController.actor.h
fdbserver/include/fdbserver/Status.actor.h

cherrypick #10907
To retrieve storage metadata for every status json request is very expensive (each SS is a point read) for clusters with a large number of storage servers. So I change the logic so that ClusterController actively monitors changes to storage metadata, and only retrieves them when there is a change.
20230915-205744-jzhou-32f4f354d2fd8d71

ClusterController watches changes to storage metadata [release-7.3]

---

contrib/Implib.so/implib-gen.py

Update Implib.so for upstream - [Modified ELF dynamic symtab list: added additional space separator](https://github.com/yugr/Implib.so/pull/31).
It's good to cherry-pick into 7.3.

Implib.so: Fix issue with trailing newline in c++filt output

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbclient/StorageServerInterface.h
fdbserver/DDTeamCollection.actor.cpp
fdbserver/DataDistribution.actor.h
fdbserver/DataDistributionQueue.actor.cpp
fdbserver/StorageMetrics.actor.h
fdbserver/TCInfo.actor.cpp
fdbserver/TCInfo.h
fdbserver/storageserver.actor.cpp

When get a dest team, we want to choose a team which does not have too long storage queue. In this PR, we set a threshold for the storage queue when getTeam(). If the longest storage queue of a team is over **1/3** of the `TARGET_BYTES_PER_STORAGE_SERVER`, this team will not be selected as the destination for any split/rebalancing data move. We should note that it is possible that getTeam may not be able to select any team when worrying the storage queue length. To address this issue, we simply retry getTeam without storage-queue-aware. 
Concerns:
1. When wantsNewServers==false, we do not check the queue size. Do we want to check this case as well?
2. Do we want to count potential increase of storage queue by inflight data moves when checking the storage queue length of the team …

Storage-Queue-Aware GetTeam

---

fdbserver/IPager.cpp

The `PAGE_SIZE` constant [is used](https://github.com/freebsd/freebsd-src/blob/e39e6bef6725bde54f94aac7f0cda47c2170dc48/sys/amd64/include/param.h#L98) in the FreeBSD's `param.h`. There's an error while building foundationdb on FreeBSD. It's proposed to rename the const to `_PAGE_SIZE`.
It's good to cherry-pick into 7.3.

Rename PAGE_SIZE constant

---

fdbclient/FDBTypes.cpp
fdbclient/include/fdbclient/FDBTypes.h
fdbserver/DDTeamCollection.actor.cpp
fdbserver/workloads/ConfigureDatabase.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp
tests/SpecificUnitTest.txt

The format of the option will be a `";"` seperated locality list, such as `"processid:123;dcid:456"`
20230913-214228-zhewu_wiggle_list-273c7d29666ffd1c compressed=True data_size=34726723 duration=6745515 ended=100000 fail=5 fail_fast=10 max_runs=100000 pass=99995 priority=100 remaining=0 runtime=1:38:57 sanity=False started=100000 stopped=20230913-232125 submitted=20230913-214228 timeout=5400 username=zhewu_wiggle_list
all failures are related to ShardedRocksDBNonDeterminism

Make `perpetual_storage_wiggle_locality` database option to take a list of localities

---

flow/ThreadPrimitives.cpp
flow/include/flow/ThreadPrimitives.h

I have a benchmark using [nanobench](https://nanobench.ankerl.com/reference.html) that measures the time it takes to round-trip reading from the ryw cache from libfdb_c. It looks like the following:
```
fdb_transaction_clear_range(tr, (const uint8_t*)"", 0, (const uint8_t*)"\xff", 1);
bench.run("ryw read", [&]() {
FDBFuture* f = fdb_transaction_get(tr, (const uint8_t*)"", 0, 0);
checkError(fdb_future_block_until_ready(f));
fdb_future_destroy(f);
});
```
Before this change:
|               ns/op |                op/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|           32,281.52 |           30,977.47 |    0.5% |      0.39 | `ryw read`
After this change:
|               ns/op |                op/s |    err% |     total …

Implement Event using std::latch from c++20

---

fdbserver/DDTeamCollection.actor.cpp

Erase storageWiggleID from disk if not used

Erase storageWiggleID from disk if not used

---

contrib/CMakeLists.txt

The proposed change adds support of preinstalled libfmt.
Ex., there's a building problem on a FreeBSD platform with preinstalled devel/libfmt.
It's good to cherry-pick into 7.3

Add preinstalled libfmt support

---

fdbserver/QuietDatabase.actor.cpp
tests/slow/ExcludeIncludeStorageServers.toml

cherry-pick #10934
Found in release correctness tests:
```
-f ./tests/slow/ExcludeIncludeStorageServers.toml -s 3517392333 -b off
./fdbserver.6.3.16 -r simulation -f ./tests/restarting/from_6.3.13_until_7.2.0/DrUpgradeRestart-1.txt -s 3218805329 -b on --logsize 1GB
-f ./tests/restarting/from_6.3.13_until_7.2.0/DrUpgradeRestart-2.txt --restarting -s 3218805330 -b on
```

Fix two test failures [release-7.3]

---

bindings/go/src/fdb/fdb_darwin.go

The new MacOS linker from Xcode 15 has some changes that breaks things in our current setup (e.g. https://github.com/golang/go/issues/62598 + https://github.com/golang/go/issues/61229). I tested this change with go 1.20.8 and Xcode 15:
```text
$ xcodebuild -version
Xcode 15.0
Build version 15A240d
```
I haven't tested this with an older Xcode version.
Related forum post.: https://forums.foundationdb.org/t/golang-bindings-after-upgrading-to-xcode-15/4163/2
I opened the PR against 7.1 as my testing application uses 7.1 (and I have that library locally installed). I'm happy to open the PRs for 7.3/main once we agree that the fix is the right approach.
Before the change:
```bash
$ go test ./fdbclient/...
ld: warning: '/private/var/folders/mh/mr__47051f18gpsd3x_synbc0000gn/T/go-link-2252000032/ …
```

Update CGO LDflags for new MacOS linker

---

bindings/go/src/fdb/database.go
bindings/go/src/fdb/fdb.go

Fix panic when connecting to database from multiple threads in Go bindings

Fix panic when connecting to database from multiple threads in Go bindings

---

fdbserver/DataDistribution.actor.h
fdbserver/DataDistributionTracker.actor.cpp
fdbserver/workloads/ManualShardSplit.actor.cpp

This PR uses std::set to store the split points to remove duplicated split points.
This PR makes the logic of handling split points more clear. When DD tracker receives a manual split request, it checks the current shards and uses shard->manualSplitTrigger.trigger() to trigger the corresponding shard to check the shard->manualSplitPoints. If there is any split point in the shard->manualSplitPoints, the shard evaluator will call shardSplitter to consume the split point. After the shardSplitter has split the shard, shard->manualSplitPoints will be cleared.
Add more complicated simulation tests.
20230927-031129-zhewang-cf1af847da936422           compressed=True data_size=24117230 duration=4858229 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 …

[Release-7.1] Avoid duplicated split points input to manual shard split

---

tests/fast/BackupToDBCorrectnessClean.toml
tests/fast/KillRegionCycle.toml
tests/rare/Throttling.toml
tests/slow/ApiCorrectness.toml
tests/slow/ApiCorrectnessSwitchover.toml
tests/slow/ClogWithRollbacks.toml

Found in nightly and can't reproduce the ExternalTimeout error.

Disable sharded rocks for more simulation tests

---

tests/CMakeLists.txt

Nightly shows valgrind failure of starting workload for this test.

Disable noSim/RandomUnitTests.toml in simulation

---

tests/CMakeLists.txt
tests/fast/BackupToDBCorrectnessClean.toml
tests/fast/KillRegionCycle.toml
tests/rare/Throttling.toml
tests/slow/ApiCorrectness.toml
tests/slow/ApiCorrectnessSwitchover.toml
tests/slow/ClogWithRollbacks.toml

Found in nightly and can't reproduce the ExternalTimeout error.
cherrypick #10939 #10944 

Disable sharded rocks for more simulation tests [release-7.3]

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/DDTeamCollection.actor.cpp
fdbserver/DataDistribution.actor.h
fdbserver/DataDistributionQueue.actor.cpp
fdbserver/workloads/ManualShardSplit.actor.cpp

This PR:
1. Set wantsNewServers=true for manualShardSplit; thus, manualShardSplit actively uses storage-queue-aware getTeam().
2. Add more trace event to cover the path from triggering manual split, to getTeam, to completing relocation.
3. Add more simulation tests.
20230928-204300-zhewang-3e9f16868636ae7d           compressed=True data_size=24123116 duration=4986160 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:17:28 sanity=False started=100000 stopped=20230928-220028 submitted=20230928-204300 timeout=5400 username=zhewang
100K manual shard split test:
20230928-204326-zhewang-f0c72fb0eae93cd4           compressed=True data_size=24154639 duration=8470353 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 …

[Release-7.1] Actively use storage-queue-aware getTeam for manual shard split

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/DDRelocationQueue.actor.cpp

Add WIGGLING_RELOCATION_PARALLELISM_PER_SOURCE_SERVER to set the parallelism of wiggling relocations.
The knob takes effects when wiggling data moves are at PRIORITY_PERPETUAL_STORAGE_WIGGLE.
To achieve so, we need to set PRIORITY_PERPETUAL_STORAGE_WIGGLE to a value larger than PRIORITY_TEAM_HEALTHY.
Correctness test with 3 external timeouts:
20231003-024433-zhewang-f493ac44a8330708           compressed=True data_size=35906170 duration=7594894 ended=100000 fail=3 fail_fast=10 max_runs=100000 pass=99997 priority=100 remaining=0 runtime=1:10:13 sanity=False started=100000 stopped=20231003-035446 submitted=20231003-024433 timeout=5400 username=zhewang
Please check …

Throttle wiggling data moves

---

fdbclient/S3BlobStore.actor.cpp

Found by Valgrind. `valueEnd` points to the temporary memory location, and can't be dereferenced.

Fix an invalid memory access

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/DDRelocationQueue.actor.cpp

Cherry-pick PR[#10953](https://github.com/apple/foundationdb/pull/10953)
20231003-203703-zhewang-1f1d75c5d1d7053f           compressed=True data_size=34486099 duration=7449312 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:21:39 sanity=False started=100000 stopped=20231003-215842 submitted=20231003-203703 timeout=5400 username=zhewang

[Release-7.3] Cherry-pick throttle data move for perpetual wiggle

---

fdbclient/S3BlobStore.actor.cpp

cherrypick #10950 #10763
Fixed two use-after-free bugs.

Fix an invalid memory access [release-7.1]

---

fdbcli/RedistributeCommand.actor.cpp

100K correctness with 1 irrelevant failure
20231003-223444-zhewang-917d61c0f4ece38b           compressed=True data_size=24124672 duration=4942302 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:07:35 sanity=False started=100000 stopped=20231003-234219 submitted=20231003-223444 timeout=5400 username=zhewang
Tested by kubernetes test

[Release-7.1] Fix redistribute cli

---

bindings/c/CMakeLists.txt
flow/Platform.actor.cpp

Added two fixes for FreeBSD support:
- CMake: Disable linking `stdc++fs` for CLang, not only for Apple;
- Added FreeBSD `environ` implementation.

Some fixes for FreeBSD support: c-bindings and flow

---

fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
tests/rare/ClogTlog.toml
tests/rare/SwizzledLargeApiCorrectness.toml
tests/slow/GcGenerations.toml
tests/slow/ParallelRestoreNewBackupCorrectnessAtomicOp.toml
tests/slow/VersionStampBackupToDB.toml

Valgrind complains this for RecentRocksDBBackgroundWorkStats event.
Disable more sharded rocks for simulation tests.

Fix an unitialized variable

---

fdbserver/DataDistribution.actor.cpp

It should be `g_network` instead of `g_simulator`.

Replace the wrong usage of g_simulator in the snapshot code

---

fdbclient/FDBTypes.h
fdbclient/SpecialKeySpace.actor.cpp
fdbserver/DataDistributionTracker.actor.cpp

Users get shard write traffic and bytes by `getrange "\xff\xff/metrics/data_distribution_stats/<shardbegin>" "\xff\xff/metrics/data_distribution_stats/<shardend>"`
Correctness test with 2 irrelevant failures:
20231016-174827-zhewang-654839c5d6f9aaa1           compressed=True data_size=24138808 duration=5091577 ended=100000 fail=2 fail_fast=10 max_runs=100000 pass=99998 priority=100 remaining=0 runtime=0:54:44 sanity=False started=100000 stopped=20231016-184311 submitted=20231016-174827 timeout=5400 username=zhewang
Checked by Kubernetes test …

[Release-7.1] Add write traffic metrics to ddMetricsGetRange

---

fdbserver/KeyValueStoreRocksDB.actor.cpp

Compaction rate limiter changes.
I want to test the changes in prod(with more read workload).  After that I will cherry-pick to main branch

Compaction rate limiter changes.

---

flow/Knobs.cpp
flow/include/flow/IConnection.h
flow/include/flow/Knobs.h
flow/network.cpp

cherrypick #10822 and #10827. Those changes are in main and 7.1 but not 7.3.

IPv4 prefer release 7.3

---

fdbserver/Status.actor.cpp

Correct the check for a machine being excluded. In the previous version a machine was not shown as excluded if a process was excluded by localities. I already ran some tests on a real cluster, but I have to run some more tests.

Correct the check for a machine being excluded

---

fdbclient/Schemas.cpp
fdbclient/SpecialKeySpace.actor.cpp
fdbclient/include/fdbclient/FDBTypes.h
fdbserver/DDShardTracker.actor.cpp

This PR cherry-picks https://github.com/apple/foundationdb/pull/10985 and https://github.com/apple/foundationdb/pull/10989 from release-7.1
100K correctness test (1 irrelevant failure)
20231018-193759-zhewang-11c8b2fe8693af14           compressed=True data_size=35922779 duration=7375902 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0:00:00 runtime=2:00:58 sanity=False started=100000 submitted=20231018-193759 timeout=5400 username=zhewang

Add write traffic metrics to ddMetricsGetRange

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/DDTeamCollection.actor.cpp
fdbserver/DDTeamCollection.h

Perpetual wiggle option to have multiple SS in rebalance state during wiggling
I will test this perf cluster and port the changes in main branch. 

Perpetual wiggle option to have multiple SS in rebalance state during wiggling

---

fdbclient/Schemas.cpp
fdbclient/SpecialKeySpace.actor.cpp
fdbclient/include/fdbclient/FDBTypes.h
fdbserver/DDShardTracker.actor.cpp

This PR cherry-picks https://github.com/apple/foundationdb/pull/10987.
20231019-182456-zhewang-0cfefafa39a1fe2a           compressed=True data_size=34493324 duration=8175372 ended=100000 fail=2 fail_fast=10 max_runs=100000 pass=99998 priority=100 remaining=0 runtime=1:07:20 sanity=False started=100000 stopped=20231019-193216 submitted=20231019-182456 timeout=5400 username=zhewang
1 failure is external timeout with rocksdb storage engine in a restart test.
1 failure is a shared tLog failure in `tests/rare/DcLag.toml:`
`<SharedTLogFailed Severity="40" ErrorKind="DiskIssue" Time="315.123440" DateTime="2023-10-19T19:13:15Z" Type="SharedTLogFailed" Machine="2.2.1.1:1" ID="a77c36aeb3b94777" Error="io_error" ErrorDescription="Disk i/o operation failed" ErrorCode="1510" …

[Release-7.3] Cherry-pick Add write traffic metrics to ddMetricsGetRange

---

bindings/go/src/fdb/fdb_darwin.go

Fix the usage of the go bindings for 6.3 on newer macOS versions. This doesn't require a release and users of the go bindings just have to update the reference.

Update macos cgo 6.3

---

bindings/go/src/fdb/fdb_darwin.go

Fix the usage of the go bindings for 6.3 on newer macOS versions. This doesn't require a release and users of the go bindings just have to update the reference.

Update macos cgo 6.2

---

fdbclient/ManagementAPI.actor.cpp

Otherwise servers that are excluded based on localities are ignored in the [InProgressExclusion](https://github.com/apple/foundationdb/blob/main/fdbclient/SpecialKeySpace.actor.cpp#L1221) actor.
I have to run some tests on a real cluster.

Make sure the get all excluded servers method returns servers that are excluded based on locality

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/StorageMetrics.actor.cpp

Problem: when calculating split points of a shard, DD skips splitting if the size of the remaining shard size is reasonably small. However, it is possible that a shard size is small but the write traffic is high, resulting in rate keeping due to a storage queue. 
Solution: we want to continue splitting the remaining shard even when the size is small but the write traffic is high. This may lead to more shards and more data movements. We need to test this solution in a real cluster before merge it.
Usage: set ENABLE_WRITE_BASED_SHARD_SPLIT to enable this feature.
Passed 100K tests with 3 external timeout failures:
20231011-210230-zhewang-4fbc5fa5e9cb65e1           compressed=True data_size=35910250 duration=6595407 ended=100000 fail=3 fail_fast=10 max_runs=100000 pass=99997 priority=100 …

Check write traffic when bypass shard split

---

bindings/c/test/unit/third_party/CMakeLists.txt

The proposed change adds support of preinstalled doctest.
Ex., there's a building problem on the FreeBSD Ports framework.
It's good to cherry-pick into 7.3.
P.S. Also, there's an issue on the upstream - https://github.com/doctest/doctest/pull/812

Add preinstalled doctest support

---

fdbclient/ManagementAPI.actor.cpp
fdbserver/include/fdbserver/ExclusionTracker.actor.h
fdbserver/workloads/RemoveServersSafely.actor.cpp
tests/slow/MoveKeysSideband.toml

This workload can have timeout error when using locality-based exclusion. The
sequence is:
1. RemoveServerSafely workload exclude locality by processid
1. Attrition reboots the target process, thus changing the processid, because processid is generated for each worker process at fdbd()
1. RemoveServerSafely waits for the process exclusion, which never succeed
1. Timeout
The fix monitors processid locality changes and reissue the exclusion with the
correct locality.
To reproduce:
seed: -f ./tests/fast/SwizzledRollbackSideband.toml -s 879108103 -b on
commit: https://github.com/apple/foundationdb/commit/a3dbd4baf7eef987a8b7b77c296476127707a8f3 release-7.1
Test done in #11000 
The general pull request guidelines can be found [here](https://github.com/apple/foundationdb/wiki/FoundationDB-Commit …

Fix RemoveServersSafely workload timeout error

---

fdbclient/ManagementAPI.actor.cpp
fdbserver/ExclusionTracker.actor.h
fdbserver/workloads/RemoveServersSafely.actor.cpp
tests/slow/MoveKeysSideband.toml

cherrypick #11001 
This workload can have timeout error when using locality-based exclusion. The
sequence is:
1. RemoveServerSafely workload exclude locality by processid
2. Attrition reboots the target process, thus changing the processid, because
processid is generated for each worker process at fdbd()
3. RemoveServerSafely waits for the process exclusion, which never succeed
4. Timeout
The fix monitors processid locality changes and reissue the exclusion with the
correct locality.
To reproduce:
seed: -f ./tests/fast/SwizzledRollbackSideband.toml -s 879108103 -b on
commit: a3dbd4baf release-7.1
500k 20231020-040336-jzhou-42bd5d69b66f383a …

Fix RemoveServersSafely workload timeout error [release-7.1]

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/StorageMetrics.actor.cpp

This PR cherry-picks PR https://github.com/apple/foundationdb/pull/10974
**100K correctness test with 4 failures:**
20231020-191640-zhewang-cd645ce644e60f7f           compressed=True data_size=34493556 duration=6529908 ended=100000 fail=4 fail_fast=10 max_runs=100000 pass=99996 priority=100 remaining=0 runtime=1:38:17 sanity=False started=100000 stopped=20231020-205457 submitted=20231020-191640 timeout=5400 username=zhewang
- rare/WriteTagThrottling.toml:
```
<HealthMetricsStoppedUpdating Severity="40" ErrorKind="Unset" Time="208.018929" DateTime="2023-10-20T19:50:44Z" Type="HealthMetricsStoppedUpdating" Machine="[abcd::3:4:3:5]:1" ID="0000000000000000" ThreadID="13065669644775959922" Backtrace="cd /root/build_output/bin; addr2line -e fdbserver -p -C -f -i 0x54020ed 0x54023b3 0x3a3fbd6 …
```

[Release-7.3] Cherry-pick Check write traffic when bypass shard split

---

fdbcli/ExcludeCommand.actor.cpp
fdbclient/DatabaseConfiguration.cpp
fdbclient/ManagementAPI.actor.cpp
fdbclient/SpecialKeySpace.actor.cpp
fdbclient/include/fdbclient/DatabaseConfiguration.h
fdbclient/include/fdbclient/ManagementAPI.actor.h
fdbrpc/Locality.cpp
fdbrpc/include/fdbrpc/Locality.h

If a process is either partitioned or not running anymore, the worker endpoint is not returning information about this process, even thought the process might still holds data that is not yet replicated. In this case running the exclude command with a locality misses the process that still needs to be excluded from the database status. Based on https://apple.github.io/foundationdb/command-line-interface.html#exclude:
```text
adds the address/locality to the set of excluded servers and localities. It then waits until all database state has been safely moved off the specified servers.
```
I would expect that the exclude command blocks in this case until all server that have the specified locality are removed from the server list.
I ran some e2e tests for this case and with those changes the …

Make sure server list is validated against the excluded localities

---

fdbserver/ConsistencyScan.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp

This PR adds trace events to expose performance of consistency checker. With this PR, we want to understand whether consistency check can run as fast as we expected and whether the rate limiter actually takes effects.
For collecting performance numbers to compare AuditStorage and ConsistencyChecker.
100K correctness test with 2 external timeout failures with rocksdb and sharded rocksdb
20231023-225000-zhewang-baac37bdaf31b6ff           compressed=True data_size=35938644 duration=6460390 ended=100000 fail=2 fail_fast=10 max_runs=100000 pass=99998 priority=100 remaining=0 runtime=1:13:38 sanity=False started=100000 stopped=20231024-000338 submitted=20231023-225000 timeout=5400 username=zhewang …

Improve visibility of consistency checker

---

fdbcli/ExcludeCommand.actor.cpp

Otherwise a user can not exclude a locality without at least one server running in it.

Allow the exclusions of localities that are not matching any process

---

packaging/osx/buildpkg.sh

fdb_c.h depends on this header, and it is not currently included. This results in build failures as described in #11036 . This change adds this header to the osx package.
Re testing: I successfully built and installed the new package on my own osx system, and the minimal case described in the issue now builds fine. Also confirmed that `/usr/local/include/foundationdb/fdb_c_apiversion.g.h` now exists.
I can add this file to other packaging scripts as part of this PR, but I am not able to test them eg for debian linux.

add fdb_c_apiversion.g.h to osx package

---

documentation/sphinx/source/administration.rst

Documentation of: https://github.com/apple/foundationdb/issues/11026 + https://github.com/apple/foundationdb/pull/11009

Document the current limitation of locality-based exclusions

---

packaging/osx/buildpkg.sh

cherrypick #11037 
fdb_c.h depends on this header, and it is not currently included. This results in build failures as described in #11036 . This change adds this header to the osx package.

Add fdb_c_apiversion.g.h to osx package [release-7.3]

---

fdbclient/ServerKnobs.cpp

Adjusting rocksdb write buffer size in simulation.
cherry-pick of #11058

Adjusting rocksdb write buffer size in simulation.

---

fdbclient/FileBackupAgent.actor.cpp
fdbclient/ServerKnobs.cpp
fdbserver/BackupWorker.actor.cpp
fdbserver/TLogServer.actor.cpp
fdbserver/tester.actor.cpp

Fix backup workers stability issues
This PR includes a few stability fixes for Backup Worker
* Fixed memory bookkeeping issue in Backup Worker. Previously
it didn't release flow lock correctly when erasing messages.
* Added TLogServer fix to return 0 from poppedVersion() for
unrecognized log router tags.
20231108-200845-haofu-5251dcb714767308 

Fix backup workers stability issues

---

fdbcli/LocationMetadataCommand.actor.cpp
fdbclient/SystemData.cpp
fdbclient/include/fdbclient/SystemData.h
fdbserver/DDRelocationQueue.actor.cpp
fdbserver/MoveKeys.actor.cpp
fdbserver/include/fdbserver/DataDistribution.actor.h
fdbserver/storageserver.actor.cpp
fdbserver/workloads/DataLossRecovery.actor.cpp
fdbserver/workloads/PhysicalShardMove.actor.cpp
fdbserver/workloads/RandomMoveKeys.actor.cpp
fdbserver/workloads/StorageServerCheckpointRestoreTest.actor.cpp

This PR propagates data move reason from DD to SS by encoding data move reason to data move id.
The PR originates from PR https://github.com/apple/foundationdb/pull/10977 while following the datamoveId creation framework established by PR https://github.com/apple/foundationdb/pull/11057.
The PR is used for throttling fetch key: PR https://github.com/apple/foundationdb/pull/11060.
More:
Added validation of data move id decode.
Found and fixed a bug of shard id assignment when seedShardServers.
Tested by unit test for the correctness of encoding and decoding data move id:
`../build_output/packages/bin/fdbserver -r unittests -f noSim/SystemData/DataMoveId`
Tested by correctness test with 2 irrelevant failures:
20231115-183721-zhewang-0a153d8925b6bb02           compressed=True …

Propagate data move reason from DD to SS

---

fdbclient/BlobCipher.cpp

https://github.com/apple/foundationdb/pull/11068 triggers some test failures when ENABLE_MUTATION_TRACKING_WITH_BLOB_CIPHER is on.
This PR clear those failures.
100K test with feature on:
20231116-233700-zhewang-c407a066b6c12931           compressed=True data_size=36157330 fail_fast=10 max_runs=100000 priority=100 remaining=not_started runtime=0:00:27 sanity=False submitted=20231116-233700 timeout=5400 username=zhewang
100K test with feature off:
20231116-234529-zhewang-a3b9d3b87acbbfcf           compressed=True data_size=36157735 fail_fast=10 max_runs=100000 priority=100 sanity=False submitted=20231116-234529 timeout=5400 username=zhewang …

Clear blobcipher test failures when enabling mutation tracking

---

fdbclient/BlobCipher.cpp
fdbserver/tester.actor.cpp
fdbserver/workloads/EncryptionOps.actor.cpp

ENABLE_MUTATION_TRACKING_WITH_BLOB_CIPHER on
20231117-075715-zhewang-f3e5dc62fbf7f5c6           compressed=True data_size=36158746 duration=6945914 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:02:04 sanity=False started=100000 stopped=20231117-085919 submitted=20231117-075715 timeout=5400 username=zhewang
ENABLE_MUTATION_TRACKING_WITH_BLOB_CIPHER off
20231117-061006-zhewang-157a37d233e487de           compressed=True data_size=36158992 duration=6060409 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:21:32 sanity=False started=100000 stopped=20231117-073138 submitted=20231117-061006 timeout=5400 username=zhewang
1 irrelevant failure …

Nits for blobcipher test

---

cmake/FindCoroutines.cmake
design/coroutines.md
documentation/CMakeLists.txt
documentation/coro_tutorial/CMakeLists.txt
documentation/coro_tutorial/tutorial.cpp
fdbrpc/CoroTests.cpp
fdbserver/workloads/UnitTests.actor.cpp
flow/CMakeLists.txt
flow/include/flow/Arena.h
flow/include/flow/CoroUtils.h
flow/include/flow/Coroutines.h
flow/include/flow/CoroutinesImpl.h
flow/include/flow/flow.h
flow/include/flow/genericactors.actor.h
flow/include/flow/network.h
flow/network.cpp

With these changes, we can write FDB code using C++ coroutines. Like:
```c++
Future<int> foo() {
auto res = co_await calcRes();
co_await bar(res);
co_return res;
}
```
This PR also contains documentation in `design/coroutines.md`.
For testing:
1. Added several coroutine specific tests.
2. Rewrote the tutorial in the documentation.
3. (Not included in this PR): Refactored Redwood to use 100% C++ coroutines and made sure the correctness test is succeeding. Then I ran a Redwood benchmark (with memory-only mode and small kv-pairs to increase actor-churn) and verified that there's no performance regression. …

Added C++ Coroutine support to Flow

---

fdbrpc/CoroTests.cpp

Sim2FileSystem::open() seems to require this flag, otherwise assertion failed.
Found by nightly.

Fix coroutine generator test failure

---

fdbserver/DataDistribution.actor.cpp
fdbserver/MoveKeys.actor.cpp
fdbserver/storageserver.actor.cpp

Adding field length to audit storage trace events.

Adding field length to audit storage trace events.

---

fdbcli/DebugCommands.actor.cpp

This will make "fdbcli checkall" results reliable until the number of keys in the requested range exceed CLIENT_KNOBS->KRM_GET_RANGE_LIMIT/CLIENT_KNOBS->KRM_GET_RANGE_LIMIT_BYTES.
Testing:
Joshua job: 20231211-201217-sre-0bc522bf3dc28038 (started)

Bump up the number of keys that "fdbcli checkall" can fetch per GetKeyValueRequest call

---

fdbclient/ClientKnobs.cpp
fdbserver/tester.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp

500K Correctness test:
20231211-211641-zhewang-19c5d25a7e789359           compressed=True data_size=24177283 duration=18503562 ended=500000 fail=2 max_runs=500000 pass=499998 priority=100 remaining=0 runtime=1:48:22 sanity=False started=500000 stopped=20231211-230503 submitted=20231211-211641 timeout=5400 username=zhewang

[Release-7.1] Range-Customizable Consistency Checker

---

fdbcli/DebugCommands.actor.cpp

the begin key has to be updated for checkall command when a shard
is large, this PR makes this change.
Testing: upload `fdbcli` binary to `ck5-p210-wu-stateless-1:/var/dynamic-conf`, with name `fdbcli_c2`.

Fix checkall when shard is large

---

packaging/docker/Dockerfile
packaging/docker/build-images.sh

Config changes to also build the fdb kubernetes monitor, this allows easier testing and a better transition in the future. We probably want to backport this to 7.1 and 7.3.

Build the FDB Kubernetes monitor

---

fdbclient/NativeAPI.actor.cpp
fdbserver/storageserver.actor.cpp

Fix stuck watch bug with racing watches
* buggify watch version retry and fix multiple watch race after retry
* watch debugging improvements

Stuck watch bug fix

---

fdbserver/storageserver.actor.cpp

Do not allow synthetic data creation if the version is invalid.

Fix bug in synthetic data creation

---

fdbcli/DebugCommands.actor.cpp

backport https://github.com/apple/foundationdb/pull/11091, https://github.com/apple/foundationdb/pull/11098 and https://github.com/apple/foundationdb/pull/11118

Fix checkall when shard is large(release-7.3)

---

fdbclient/ConsistencyCheckUtil.actor.cpp
fdbserver/tester.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp

This PR aims at preventing testers from being overloaded when there are multiple checkers. 
If there are multiple tasks issued by different checkers on a tester at a time, the tester replaces the existing task with the new task.
This guarantees following invariants: 
- Any tester executes workload from at most one checker at a time.
- If there are two checkers: 1 is a transient checker and 1 is a stable checker, the stable checker wins (by tries).
- If two checkers are stable checker: neither checker makes progress and a s40 trace event is logged. Removing anyone of the checker will bring the system back to the single checker state.
This PR also adds trace events to record bytes and keys that are compared at each time.
500K correctness test with 1 irrelevant failure: …

[Release-7.1] ConsistencyCheckerUrgent should tolerate busy restart loop of the checker

---

cmake/GetMsgpack.cmake

The proposed change adds support msgpack v.4+.
It's good to cherry-pick into 7.1 and 7.3.

GetMsgpack: add 4+ versions of upstream

---

contrib/crc32/crc32c.cpp

The fork of the `crc32` library in `contrib` makes use of streaming SIMD instructions where possible. This is achieved via a preprocessor directive, but short-circuiting of the evaluation previously meant that any use of clang or GCC opted into SSE regardless.
This commit adds additional parentheses to ensure a warning-free build of the CRC32 library using clang on ARM64 machines.
On macOS on Apple Silicon:
```
$ uname -m
arm64
```
Before:
```
$ ninja crc32
[0/2] Re-checking globbed directories...
[3/4] Building CXX object contrib/crc32/CMakeFiles/crc32.dir/crc32c.cpp.o
'+sse4.2' is not a recognized feature for this target (ignoring feature)
'+sse4.2' is not a recognized feature for this target (ignoring feature)
[4/4] Linking CXX static library lib/libcrc32.a
```
After:
```
$ ninja -t …
```

Do not opt into sse4.2 for arm64 CPUs in crc32 library

---

fdbcli/DebugCommands.actor.cpp

[Release-7.1] Fix checkAll command

---

fdbcli/DebugCommands.actor.cpp

Consider two key sets stored in SS1 and SS2:
SS1 (current server): 1, 2, 3, 4, 5, 6, 7, 8, 9
SS2 (reference server): 1, 2, 3, 4, 7, 8, 9
In this case, SS2 omitted some keys, and the expected output of checkall is 5, 6 as the unique keys on SS1.
However, the existing checkall does not output as expected.
Without loss of generality, suppose the checkall command request 6 successive keys to a SS in batch. Then, in the first batch, SS1 replies 1, 2, 3, 4, 5, 6 and SS2 replies 1, 2, 3, 4, 7, 8. Then, checkall is failed to find 5, 6 on SS2 and failed to find 7, 8 on SS1. Therefore, the tool outputs 5, 6 as the uniques keys on SS1 and 7, 8 as the uniques keys on SS2.
The problem stems from the tool arbitrarily selects the nextBeginKey (currently, the nextBeginKey is the last key replied by the …

Fix checkall false alarms and refactor code

---

fdbserver/DDTeamCollection.actor.cpp

healthyzone is not modified when "ignoressfailuers" is set. As a result, "ignoressfailuers" cannot take effect in real time

Fix healthyzone is not modified when ignoressfailuers is set

---

fdbbackup/backup.actor.cpp

This fixes a typo I noticed when I was testing the restore command.
I did not perform any testing, since this should be a straightforward text-only change.
- [] The PR has a description, explaining both the problem and the solution.

Fixes a typo in the output from the restore command.

---

fdbclient/include/fdbclient/StorageServerInterface.h
fdbserver/storageserver.actor.cpp

This interface is critical to implement checksum based consistency checking in the future, which will significantly improve the checking speed while incur minimal read traffic.
100K test:
20240124-193432-zhewang-c94734b99c8b3186           compressed=True data_size=36373629 duration=7032105 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=0:59:15 sanity=False started=100000 stopped=20240124-203347 submitted=20240124-193432 timeout=5400 username=zhewang

Add storage interface for checksum

---

fdbcli/DebugCommands.actor.cpp

Consider two storage servers:
SS1: 1,2,3,4
SS2: 1
The output of checkall should be 2,3,4 as the unique key of SS1.
However, the checkall gets stuck in this case.
WLOG, suppose the checkall read batch is 2 at a time.
In the first step, the beginKey is 1; 1 and 2 are read from SS1 and 1 is read from SS2; The checker sets 1 as the nextBeginKey.
In the second step, the beginKey is still 1 => the checker gets stuck --- repeatedly access to the beginKey 1.
To avoid this issue, if the checkall algorithms finds that the nextBeginKey remains the same as the beginKey of the current round, the checkall splits the remaining range into two subRanges, where the maximum endKey of the current round is the pivot. In this example:
In the second step, the checkall finds beginKey == nextBeginKey. Then, the …

Fix checkall Command Blocking Issue

---

fdbclient/include/fdbclient/StorageServerInterface.h
fdbserver/storageserver.actor.cpp

To cherry-pick audit storage checksum interface, we have to cherry-pick GetHotShardsRequest interface as well.
100K correctness test
20240125-194457-zhewang-22a35a6e3a4f69b4           compressed=True data_size=34701652 duration=6353071 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:15:39 sanity=False started=100000 stopped=20240125-210036 submitted=20240125-194457 timeout=5400 username=zhewang

[Release-7.3] Cherry-pick audit storage checksum interface

---

fdbserver/ClusterController.actor.cpp

workerAvailabilityWatch is an actor spawned when a new worker is registered to CC. However, the tester (ProcessClass::TesterClass) is ignored in workerAvailabilityWatch. For the removed tester, the corresponding worker has registered to CC but no workerAvailabilityWatch is monitoring the availability of the tester. Therefore, CC does not get notified when the tester has been physically removed and CC still keeps the worker interface. In clusterGetStatus(), [CC still contacts to the removed tester but failed](https://github.com/kakaiu/foundationdb/blob/2a2adf3b9564a4e5349dd41f7e749c6affc140f9/fdbserver/Status.actor.cpp#L2912). Then, [the removed worker interface is added to mergeUnreachable.](https://github.com/kakaiu/foundationdb/blob/2a2adf3b9564a4e5349dd41f7e749c6affc140f9/fdbserver/Stat …

[Release-7.1] Fix tester stale interface issue at CC

---

CMakeLists.txt
cmake/FindJinja2.cmake
documentation/CMakeLists.txt
flow/CMakeLists.txt
flow/protocolversion/requirements.txt

I was recently trying to build foundationdb on a fresh install of Sonoma, and I ran into the following issue when running `ninja`:
```
FAILED: flow/include/flow/ProtocolVersion.h /Users/eccolnu/fdb/flow/include/flow/ProtocolVersion.h
...
File "/Users/home/foundationdb/flow/protocolversion/protocol_version.py", line 18, in <module>
import jinja2
ModuleNotFoundError: No module named 'jinja2'
```
The problem is that `protocol_version.py` implictly expects `jinga2` to be installed in the system python environment.
So, this PR has patches that do three things:
1. `8fea64db80bb89fb7325164380c199153163e87e` makes the build fail correctly during the configure step, instead of failing once we are actually compiling.
2. `2bfff79fd36dbd4ee4482e4083f158acfeeb34c6` …

Fix for `No module named 'jinja2'` on Sonoma

---

fdbcli/DebugCommands.actor.cpp

So we can use the output easily for fdbcli and analyzing scripts.

Update value to be hex output [release-7.1]

---

fdbrpc/AsyncFileWriteChecker.h

backport https://github.com/apple/foundationdb/pull/11152

Allow AsyncFileWriteChecker history.timestamp to have better precision(release-7.1)

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbclient/include/fdbclient/StorageServerInterface.h
fdbserver/BlobMigrator.actor.cpp
fdbserver/DDRelocationQueue.actor.cpp
fdbserver/DDTeamCollection.actor.cpp
fdbserver/MockGlobalState.actor.cpp
fdbserver/StorageMetrics.actor.cpp
fdbserver/TCInfo.actor.cpp
fdbserver/include/fdbserver/DataDistributionTeam.h
fdbserver/include/fdbserver/StorageMetrics.actor.h
fdbserver/include/fdbserver/TCInfo.h
fdbserver/storageserver.actor.cpp

Cherrypick: https://github.com/apple/foundationdb/pull/10905
Correctness test:
20240130-182419-zhewang-a1ddb6eb007e8e5a           compressed=True data_size=36376774 duration=6102849 ended=100000 fail=3 fail_fast=10 max_runs=100000 pass=99997 priority=100 remaining=0 runtime=1:06:57 sanity=False started=100000 stopped=20240130-193116 submitted=20240130-182419 timeout=5400 username=zhewang

Storage-queue-aware getTeam (Cherrypick from release-7.1)

---

documentation/sphinx/source/backups.rst

We are currently running a backup and we had to throttle bandwidth.
We spent quite some time understanding why our tuning wasn't matching our parameters, until we found out that those parameters are giving restrictions per `backup_agent` and not to the whole cluster. I believe it wasn't clear in the documentation 

docs: add backup details about parameters

---

flow/Platform.actor.cpp
flow/SystemMonitor.cpp

Failure without this patch:
```text
[STARTED 150, FINISHED 67 OF 609 IN 37.177 SEC]Building CXX object flow/CMakeFiles/flow.dir/SystemMonitor.cpp.o
FAILED: flow/CMakeFiles/flow.dir/SystemMonitor.cpp.o
ccache /opt/rh/devtoolset-11/root/usr/bin/g++ -DBOOST_CONTEXT_NO_LIB -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_SYSTEM_NO_DEPRECATED -DNO_INTELLISENSE -I/root/src/foundationdb -I/root/build_output -I/root/src/foundationdb/contrib/fmt-8.1.1/include -isystem /opt/boost_1_78_0/include -O3 -DNDEBUG -std=gnu++17 -DCMAKE_BUILD -ggdb -fno-omit-frame-pointer -mavx -Werror -Wno-pragmas -Wno-attributes -Wno-error=format -Wunused-variable -Wno-deprecated -fvisibility=hidden -Wreturn-type -fPIC -Wclass-memaccess -DHAVE_OPENSSL -pthread -MD -MT flow/CMakeFiles/flow.dir/SystemMonitor.cpp.o -MF …
```

[release-7.1] Fix compile issue for ALLOC_INSTRUMENTATION

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/KeyValueStoreRocksDB.actor.cpp
fdbserver/KeyValueStoreShardedRocksDB.actor.cpp

This PR evaluates the current RocksDB checksum mechanism:
- Block checksum is written to disk when generating SST files. When reading the data from a SST file, the block checksum is checked. This covers any corruption that happens to data block of SST file after the block has been persisted. Ref: https://github.com/facebook/rocksdb/wiki/Full-File-Checksum-and-Checksum-Handoff
- paranoid_file_checks: Right after generating a SST file on disk, RocksDB reads the data of the SST file and compare it with the data before the SST file generation. This covers cases where the file system says that the data has been persisted but it is actually not. Ref: https://rocksdb.org/blog/2021/05/26/online-validation.html
- SST file checksum: When generating a SST file, a checksum of the file is attached and …

Improvements on RocksDB and ShardedRocksDB checksum

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/KeyValueStoreRocksDB.actor.cpp
fdbserver/KeyValueStoreShardedRocksDB.actor.cpp

Cherry-pick https://github.com/apple/foundationdb/pull/11169
20240202-180921-zhewang-103e53c70c3daa06           compressed=True data_size=34701813 duration=6879121 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:02:13 sanity=False started=100000 stopped=20240202-191134 submitted=20240202-180921 timeout=5400 username=zhewang

[Release-7.3] Cherry-pick add omitted checksum for rocksdb (#11169)

---

fdbserver/LogRouter.actor.cpp

In production there have been occurrences where a recruited LR never received the log system within dbInfo. Flag a `SevWarnAlways` for manual intervention in these circumstances, as the LR may become a bottleneck on the system and need to be excluded.

Flag error if log router is not learning its primary peek location

---

cmake/FDBComponents.cmake

align this section with `release-7.3`

fix find toml in release-7.1 to avoid macos pr failures

---

fdbserver/DDTeamCollection.actor.cpp

100K test:
20240212-231957-zhewang-e4c7635a4885d056           compressed=True data_size=36692703 duration=6842483 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:58:50 sanity=False started=100000 stopped=20240213-001847 submitted=20240212-231957 timeout=5400 username=zhewang

Fix calculateTeamStorageQueueThreshold

---

flow/Knobs.cpp
flow/Knobs.h
flow/Platform.actor.cpp

If the processes are exiting with the `_exit` method, that is considered a graceful shutdown and will not cause the kernel to generate a core dump.
I'm still doing some testing, once we validated that this setup works and the change looks good, we can merge it and I can create the PRs to add this change to 7.3 and main.

[RELEASE-7.1] Abort process when abnormal shutdown is initiated to allow coredumps to be generated

---

fdbclient/include/fdbclient/StorageServerInterface.h

cherrypick #11201
bytesDurable and bytesInput are not initilized here: https://github.com/apple/foundationdb/blob/09b593c328e0dbd3d98c3e54a10c5b4fb22d3a77/fdbserver/BlobMigrator.actor.cpp#L505
Found by Valgrind nightly:
```
-f ./tests/fast/BlobRestoreBasic.toml -s 4063154784 -b on
-f ./tests/fast/BlobRestoreLarge.toml -s 4249568466 -b on
```

Fix valgrind error [release-7.3]

---

documentation/sphinx/source/configuration.rst

Make a simple correction to documentation in the context of changing "usable_regions".

Correct documentation

---

fdbserver/tester.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp

Passed 500k correctness tests with 1 irrelevant failure (with redwood engine)
20240215-232832-zhewang-afeea68f5f5e159d           compressed=True data_size=26923973 duration=16888575 ended=500000 fail=1 fail_fast=10 max_runs=500000 pass=499999 priority=100 remaining=0 runtime=2:32:37 sanity=False started=500000 stopped=20240216-020109 submitted=20240215-232832 timeout=5400 username=zhewang
Verified in a real cluster.

Fix single consistency checker

---

fdbserver/tester.actor.cpp

This is a corner case triggers s40 error while no fatal event actually happens. The story is that: In round 1, the checker tried to request a tester to run the workload. At the tester side, the request was received and the workload started. However, the checker was failed to decide whether the tester had received the request (request_maybe_delivered  in ConsistencyCheckUrgent_RunWorkloadError2 trace event). So, the checker thought that this tester had failed and the checker marked all ranges assigned to this tester as failed (will retry later). Then the checker immediately proceeded to round 2. However, the tester was still running the workload of round 1. In round 2, the checker issued a new workload to the tester. The tester saw a new workload while the existing workload of round 1  is …

Fix false-alarm of sev40 error in distributed consistency checker setting

---

fdbserver/storageserver.actor.cpp

This happens only when all replicas of a key range are lost.

Fix missing shard in ShardedRocks with EmptyRange data move.

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/KeyValueStoreRocksDB.actor.cpp
fdbserver/KeyValueStoreShardedRocksDB.actor.cpp

Rocksdb in-memory data structures protection checksums.

Rocksdb in-memory data structures protection checksums.

---

CMakeLists.txt
bindings/java/CMakeLists.txt
bindings/java/src/main/com/apple/foundationdb/Database.java
bindings/java/src/main/com/apple/foundationdb/FDB.java
bindings/java/src/main/com/apple/foundationdb/Tenant.java
documentation/sphinx/extensions/relativelink.py

Fixes https://github.com/apple/foundationdb/issues/9120. So the problem wasn't just that it needed a new link. The problem was that the javadoc docs weren't being generated at all, and in fact some of the existing javadoc comments actively broke a javadoc build.
This PR
* Adds a javadoc build
* Fixes the comments that broke said build
* Fixes the relative link support

Add javadoc and fix the Java API link

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/DDTeamCollection.actor.cpp

Changes from: https://github.com/apple/foundationdb/pull/11207

Allow to disable the removal of maintenance mode when a SS outside of the maintenance zone fails

---

fdbserver/TagPartitionedLogSystem.actor.cpp

The EmptyMessageRatio LatencySample was not calculated when version vector was enabled.

Fix calculation of EmptyMessageRatio when version vector was enabled.

---

fdbserver/tester.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp

Cherrypick https://github.com/apple/foundationdb/pull/11229
20240301-023957-zhewang-14b0d12cd1318775           compressed=True data_size=26924489 duration=4818415 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:58:24 sanity=False started=100000 stopped=20240301-033821 submitted=20240301-023957 timeout=5400 username=zhewang

[Release-7.1] Cherry-pick Fix ConsistencyCheckUrgent stuck with transaction_too_old

---

fdbserver/Status.actor.cpp
fdbserver/include/fdbserver/LogSystem.h
tests/slow/ApiCorrectnessSwitchover.toml
tests/slow/WriteDuringReadSwitchover.toml

The clear in status call can cause corruptions.
To reproduce with clang build:
seed: -f ./tests/slow/ApiCorrectnessSwitchover.toml -s 223736449 -b on
commit: f8eca6a80
Apply the ./tests/slow/ApiCorrectnessSwitchover.toml file in this commit.
Alternatively, existing binary can enable the knob `DISABLE_DUPLICATE_LOG_WARNING=true` to avoid the data corruptions.

Fix a DR corruption bug

---

fdbclient/ServerKnobs.cpp
fdbserver/KeyValueStoreRocksDB.actor.cpp

Added max range deletions before flush knob and some knob changes.

Added max range deletions before flush knob and some knob changes.

---

fdbserver/DDTeamCollection.actor.cpp

Fixing setting perpetual_storage_wiggle_engine is considered as wrongly configured.
cherry-pick of #11250

Fixing setting perpetual_storage_wiggle_engine is considered as wrongly configured

---

fdbserver/include/fdbserver/LogSystem.h
tests/CMakeLists.txt

cherry pick 11236
The resolver logic under PROXY_USE_RESOLVER_PRIVATE_MUTATIONS miscounted the number of private mutations. This led us to write to all TLs when version vector was enabled. The number of mutations can be found by looking at a count in LogPushMutations (subsequence). The bug was this value is initialized to 1, not 0. So to find the count of mutations, 1 must be subtracted.
Verified by enabling version vector, and observing a subset of TLs were selected for the CP to send messages to, rather than all TLs.
Removed version vector upgrade tests pending fix to recovery.

Fix bug in which private mutations were detected incorrectly

---

documentation/sphinx/source/release-notes/release-notes-730.rst

Cherrypick #11188 and fixes from release-7.3 branch

Add 7.3.28 to 7.3.31 release notes

---

fdbserver/CommitProxyServer.actor.cpp

Remove assertion on TPCV equality between resolver replies. This [commit](https://github.com/apple/foundationdb/commit/54d96633c011bd10c1708b997aeb57685fc6f6d6) let only resolver 0 process metadata mutations and generate private mutations, so the assertion is invalid.

Remove assertion equality in tcpvmap size on resolver return

---

fdbserver/DDTeamCollection.actor.cpp

Added perpetualStorageWiggleSpeed check to pick perpetualStoreType

Added perpetualStorageWiggleSpeed check to pick perpetualStoreType

---

fdbserver/CommitProxyServer.actor.cpp
fdbserver/Resolver.actor.cpp
tests/CMakeLists.txt

Version vector checks for the existence of private mutations in a transaction on the resolver. 
* A private mutation is sent in `req.txnStateTransactions` 
* Or, a private mutation is found in the version history of changes from another resolver. 
Add an assertion testing the invariant: "transactions with primate mutations are sent to all logs in version vector mode."
The version vector upgrade tests do not yet pass because other recovery bugs still exist. Their fixes belong in separate PRs.
`20240327-182929-henrylambright-18e4bdff29dd3c6c`

Fix detection of private mutations in version vector

---

fdbrpc/AsyncFileWriteChecker.cpp
fdbrpc/include/fdbrpc/AsyncFileWriteChecker.actor.h
flowbench/BenchAsyncFileWriteCheckerLRU.cpp

now timestamp has uint64 and page number starts at 1
simulation : 20240401-164704-haofu-249f9bb66e85638b  

fix signed int and overflow bugs

---

fdbserver/DDTeamCollection.actor.cpp

There are many simulation failures of PerpetualWiggleStorageMigration.toml due to TracedTooManyLines, and most of the traces are from here.
Suppress it to make simulation stable.

Suppress ChosenMachine to fix simulation error

---

fdbserver/CommitProxyServer.actor.cpp
fdbserver/Resolver.actor.cpp

Version vector checks for the existence of private mutations in a transaction on the resolver.
* A private mutation is sent in req.txnStateTransactions
* Or, a private mutation is found in the version history of changes from another resolver.
Add an assertion testing the invariant: "transactions with primate mutations are sent to all logs in version vector mode."
The version vector upgrade tests do not yet pass because other recovery bugs still exist. Their fixes belong in separate PRs.

cherry pick pr 11268 - Fix detection of private mutations in version vector

---

fdbclient/ClientKnobs.cpp
fdbclient/include/fdbclient/Atomic.h
fdbclient/include/fdbclient/ClientKnobs.h
fdbclient/include/fdbclient/CommitTransaction.h
fdbserver/AccumulativeChecksumUtil.cpp
fdbserver/ApplyMetadataMutation.cpp
fdbserver/ClusterRecovery.actor.cpp
fdbserver/CommitProxyServer.actor.cpp
fdbserver/include/fdbserver/AccumulativeChecksumUtil.h
fdbserver/include/fdbserver/ProxyCommitData.actor.h
fdbserver/include/fdbserver/WorkerInterface.actor.h
fdbserver/storageserver.actor.cpp

Cherry-pick ACS Index (PR https://github.com/apple/foundationdb/pull/11225) to release-7.3 to guarantee the downgrade compatibility from 7.4, similar to MutationChecksum feature.
Feature on:
20240405-003157-zhewang-23b09646a07dc913           compressed=True data_size=34888425 duration=4969776 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:29:34 sanity=False started=100000 stopped=20240405-020131 submitted=20240405-003157 timeout=5400 username=zhewang
Feature off:
20240405-003006-zhewang-ada6b9ade0623502           compressed=True data_size=34888438 duration=5580015 ended=100000 fail=2 fail_fast=10 max_runs=100000 pass=99998 priority=100 remaining=0 runtime=1:34:46 sanity=False started=100000 stopped=20240405-020452 submitted=20240405-003006 …

[Release-7.3] Cherry-pick Enable Accumulative Checksum in MutationRef (#11225)

---

fdbclient/SystemData.cpp
fdbclient/include/fdbclient/SystemData.h
fdbserver/storageserver.actor.cpp

When downgrading from 7.4, the release-7.3 storage server should know the ACS private mutation (for the accumulative checksum feature). Otherwise, there will be an assertion failure for `Unknown private mutation`.
100K tests:
20240409-230139-zhewang-6fd6ad32e7d39452           compressed=True data_size=34888753 duration=5979425 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=0:37:55 sanity=False started=100000 stopped=20240409-233934 submitted=20240409-230139 timeout=5400 username=zhewang …

[Release-7.3] Add acs mutation support

---

cmake/InstallLayout.cmake
packaging/docker/Dockerfile
packaging/docker/Dockerfile.eks
packaging/docker/build-images.sh

minor updates to include `fdbkubernetesmonitor` in the developer workflow and docker build.

updates to add fdb-kubernetes-monitor to the standard build flow

---

fdbclient/ClientKnobs.cpp
fdbserver/AccumulativeChecksumUtil.cpp
fdbserver/include/fdbserver/AccumulativeChecksumUtil.h
fdbserver/storageserver.actor.cpp

This PR validates the key invariant kept by the transaction system:
Given a mutation sent by a commit proxy at a commit version, a storage server sees this mutation at the same version provided by tLog cursor.
20240411-201533-zhewang-1565e777065b17fe           compressed=True data_size=36595364 duration=4889247 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:21:30 sanity=False started=100000 stopped=20240411-213703 submitted=20240411-201533 timeout=5400 username=zhewang …

Validate Mutation Version in Accumulative Checksum Framework

---

packaging/docker/samples/golang/app/fdb.cluster
packaging/docker/samples/golang/docker-compose.yml

When I run `docker-compose up -d`, I can't use http://localhost:8080/counter to test golang app.
This is because docker-compose.yaml does not expose the port, and fdb.cluster needs to replace the address with the container name.

fix: golang docker compose example

---

contrib/convert.py

the first commit is copied from https://github.pie.apple.com/jingyu-zhou/corruption/blob/main/convert.py while the second commit is a bug fix.

Add convert.py that converts between timestamp and version for clusters

---

fdbserver/DDTeamCollection.actor.cpp

Reverts apple/foundationdb#11272
#11272diff is necessary to avoid unintended changes in prod. But, with this the simulation changes is broken. So reverting the change temporarily.

Revert "Added perpetualStorageWiggleSpeed check to pick perpetualStoreType"

---

documentation/sphinx/source/mr-status-json-schemas.rst.inc
fdbclient/Schemas.cpp
fdbserver/KeyValueStoreRocksDB.actor.cpp
fdbserver/Status.actor.cpp

cherry-pick of #11321
Rocksdb metrics in status json.

Rocksdb metrics in status json.

---

fdbclient/NativeAPI.actor.cpp
fdbserver/workloads/BlobRestoreWorkload.actor.cpp

In the current code, errors are retried in getConsistentReadVersion, so it's possible that the client has cancelled the GRV request, but readVersionBatcher continue retrying, which can lead to many clients DDoS GRV proxies, especially when the database has become unavailable for a while and clients are issuing many GRV requests.
20240417-171921-jzhou-e8ea0f89556204b8

Throw errors in getConsistentReadVersion

---

fdbclient/ClientKnobs.cpp
fdbserver/AccumulativeChecksumUtil.cpp
fdbserver/CommitProxyServer.actor.cpp

Improve ACS implementation in following aspects:
- Refactor processAccumulativeChecksum
- Refactor ACS corruption event
- Open ACS by default
- Fix memory corruption of ACS mutation
Passed 100K correctness test:
20240420-000939-zhewang-b8e8fae4b2b6179c           compressed=True data_size=36684040 duration=6349222 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:34:19 sanity=False started=100000 stopped=20240420-004358 submitted=20240420-000939 timeout=5400 username=zhewang …

Fix ACS mutation bug and improve accumulative checksum

---

bindings/go/CMakeLists.txt

update go bindings build to play nice with golang 1.22 -- remove `go get` command

update go bindings build to play nice with golang 1.22

---

fdbserver/tester.actor.cpp

20240423-200024-zhewang-f3342f263b0c4f72           compressed=True data_size=36681690 fail_fast=10 max_runs=100000 priority=100 sanity=False submitted=20240423-200024 timeout=5400 username=zhewang

Fix assert false in consistency check urgent

---

flow/Knobs.cpp

Enabling this knob caused a simulation test run failure (like the failure reported in PR https://github.com/apple/foundationdb/pull/11311). Disable this knob until we investigate the underlying issue that caused that failure.

Disable replica consistency check related knob

---

fdbserver/DataDistribution.actor.cpp

cherrypick #10984
Fix https://github.com/apple/foundationdb/issues/11308

Replace the wrong usage of g_simulator in the snapshot code [release-7.3]

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/DDRelocationQueue.actor.cpp
fdbserver/DDShardTracker.actor.cpp

Add a knob for merge parallelism and add log for max shard size.

---

fdbkubernetesmonitor/.golangci.yml
fdbkubernetesmonitor/errcheck_excludes.txt
fdbkubernetesmonitor/go.mod
fdbkubernetesmonitor/main.go

Updates the golangci-lint config for go 1.22 and remove unused variables.

Update the config for golangci-lint and remove unused variables

---

fdbclient/vexillographer/fdb.options

`SetSpanParent` does not take a 16-bytes trace id as documentation mentions, but rather requires a specific serialized binary format (described in description field).
I would merge this to the `release-7.3` release branch as well.

Document format for SetSpanParent

---

fdbclient/NativeAPI.actor.cpp

cherrypick #11311 
In the current code, errors are retried in getConsistentReadVersion, so it's possible that the client has cancelled the GRV request, but readVersionBatcher continue retrying, which can lead to many clients DDoS GRV proxies, especially when the database has become unavailable for a while and clients are issuing many GRV requests.
20240501-211653-jzhou-094f2617b102aa5c

Throw errors in getConsistentReadVersion [release-7.1]

---

fdbclient/ServerKnobs.cpp

Adjusting block cache size knob.

Adjusting block cache size knob.

---

fdbclient/NativeAPI.actor.cpp

cherrypick https://github.com/apple/foundationdb/pull/11311
In the current code, errors are retried in getConsistentReadVersion, so it's possible that the client has cancelled the GRV request, but readVersionBatcher continue retrying, which can lead to many clients DDoS GRV proxies, especially when the database has become unavailable for a while and clients are issuing many GRV requests.

Throw errors in getConsistentReadVersion [release-7.3]

---

documentation/sphinx/source/experimental-features.rst
documentation/sphinx/source/technical-overview.rst

Cherry-pick of 58ce209 for `release-7.3` branch.

[Release-7.3] Add documentation about experimental features

---

fdbserver/DDShardTracker.actor.cpp
fdbserver/DDTeamCollection.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/include/fdbserver/DDShardTracker.h
fdbserver/include/fdbserver/DDTeamCollection.h
fdbserver/include/fdbserver/DataDistribution.actor.h
fdbserver/workloads/MockDDTrackerShardEvaluator.actor.cpp
fdbserver/workloads/PerpetualWiggleStatsWorkload.actor.cpp

Fix data move trigger for rebalancing SS queue
Cleanup code
Passed 100K correctness test:
20240508-002131-zhewang-8aafdf9e0f16b9a5           compressed=True data_size=36912057 duration=8304145 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:08:10 sanity=False started=100000 stopped=20240508-012941 submitted=20240508-002131 timeout=5400 username=zhewang

Fix data move trigger for rebalancing SS queue

---

fdbserver/LogRouter.actor.cpp

* Add logging to waitForVersion
* Respond to review comments.
---------
20240506-225105-dlambrig-26746fe25a2b23c8

Add logging to LogRouter's waitForVersion function (cherry pick #11359)

---

packaging/docker/Dockerfile
packaging/docker/Dockerfile.eks
packaging/docker/run_ycsb_standalone.sh

context (useful for running ycsb against bare metal cluster).
* packaging/docker/Dockerfile
* packaging/docker/Dockerfile.eks Make the ycsb target inherit from foundationdb-base so we pick up libfdb_c.so. Add in a version of run_ycsb.sh that doesn't presume k8s. Use 'entrypoint' rather than 'cmd' so can override on 'docker run'.
* packaging/docker/run_ycsb_standalone.sh Version of run_ycsb.sh w/o the presumption of k8s.

Make it so can run the ycsb container standalone without need of a k8s

---

fdbserver/DDShardTracker.actor.cpp
fdbserver/DDTeamCollection.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/include/fdbserver/DDShardTracker.h
fdbserver/include/fdbserver/DDTeamCollection.h
fdbserver/include/fdbserver/DataDistribution.actor.h
fdbserver/workloads/MockDDTrackerShardEvaluator.actor.cpp
fdbserver/workloads/PerpetualWiggleStatsWorkload.actor.cpp

Cherrypick https://github.com/apple/foundationdb/pull/11375
100k correctness test with 1 irrelevant failure (external timeout with sharded rocksdb):
20240508-164530-zhewang-a84a9fbd96aabd3e           compressed=True data_size=35046455 duration=7488409 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:06:25 sanity=False started=100000 stopped=20240508-175155 submitted=20240508-164530 timeout=5400 username=zhewang

[Release-7.3] Cherry-pick Fix data move trigger for rebalancing SS queue (#11375)

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbrpc/include/fdbrpc/LoadBalance.actor.h
fdbserver/storageserver.actor.cpp

Extend the replica consistency check framework to do consistency check on data movement.
NOTE: Disable the knob until we address all known issues in this context (like, the consistency check failure on fetch keys after recovery)
Joshua job (with the knob enabled): 20240507-233804-sre-892d884618091f1d (shows failures; will need to investigate them)

Support for doing replica consistency check on data movement

---

fdbserver/GrvProxyServer.actor.cpp
fdbserver/include/fdbserver/MasterData.actor.h
fdbserver/masterserver.actor.cpp

Only emit version vector counters when the feature is enabled.
20240512-183112-dlambrig-4181400e8b14570e

Only emit version vector counters when enabled.

---

fdbclient/ServerKnobs.cpp

Disabling WRITE_CLIENT_LATENCY_TRACEEVENT knob

Disabling WRITE_CLIENT_LATENCY_TRACEEVENT knob

---

bindings/go/src/fdb/database.go
bindings/go/src/fdb/fdb.go

A mix of pointer/non-pointer receivers makes it impossible to use interfaces for the `fdb.Database` type; I propose to change the `Close()` method for consistency.
See https://go.dev/play/p/PQ_FDXajpnB for an example of the problem (needs to be run locally):
```
./main.go:18:22: cannot use fdb.Database{} (value of type fdb.Database) as FoundationDB value in variable declaration: fdb.Database does not implement FoundationDB (method Close has pointer receiver)
```
Custom interfaces can still be used by using a pointer instead of directly the `fdb.Database` type:
```go
var _ FoundationDB = &fdb.Database{}
```
But that's less efficient.
NOTE: no test was updated …

Go binding: do not use pointer receiver for Close()

---

fdbserver/ClusterController.actor.cpp

CC's `checkBetterSingletons()` calls `getUsedIds()` that asserts proxy interfaces are present. However, when a GRV/commit proxy failed, before CC starts a new recovery, the proxy's processId becomes empty, thus triggering the failure.
The fix is to cancel the caller while waiting for recovery.
To reproduce 7.1 commit 725a08a3ff clang build:
```
./fdbserver.6.0.15 -r simulation -f ./tests/restarting/from_5.2.0_until_6.3.0/ClientTransactionProfilingCorrectness-1.txt -s 900000399 -b on 
-f ./tests/restarting/from_5.2.0_until_6.3.0/ClientTransactionProfilingCorrectness-2.txt --restarting -s 900000400 -b on
```
20240514-200259-jzhou-997b28767e4a84f0
Please check each …

Fix an assertion failure when waiting for recovery

---

CMakeLists.txt

build: disable swift prebuilt_for_ide target when Swift is disabled

---

fdbserver/ClusterController.actor.cpp

cherrypick #11399
CC's `checkBetterSingletons()` calls `getUsedIds()` that asserts proxy interfaces are present. However, when a GRV/commit proxy failed, before CC starts a new recovery, the proxy's processId becomes empty, thus triggering the failure.
The fix is to cancel the caller while waiting for recovery.
To reproduce 7.1 commit 725a08a3ff clang build:
```
./fdbserver.6.0.15 -r simulation -f ./tests/restarting/from_5.2.0_until_6.3.0/ClientTransactionProfilingCorrectness-1.txt -s 900000399 -b on
-f ./tests/restarting/from_5.2.0_until_6.3.0/ClientTransactionProfilingCorrectness-2.txt --restarting -s 900000400 -b on
```
correctness: 20240514-184616-jzhou-8376a3b76500b2be
The general pull request guidelines can be found [here](https://github.com/apple/foundationdb/wiki/FoundationDB-Commi …

Fix an assertion failure when waiting for recovery [release-7.1]

---

fdbbackup/backup.actor.cpp

Add default timeout for fdbbackup to prevent the fdbbackup to hang infinitely in some cases. In general I think having a default timeout is a good practice instead of waiting for an infinite amount of time. We have seen some cases in testing where the fdbbackup agent was able to connect to the cluster but was not able to perform a transaction, in this case the fdbbackup, e.g. describe, will hang forever. Another improvement, in a new PR, could be to add the `timeout` flag to the `fdbbackup` command.
I have to perform some additional testing, so far I verified that the build works and tests are passing. …

Add default timeout for fdbbackup

---

bindings/java/src/integration/com/apple/foundationdb/MultiClientHelper.java
fdbclient/GlobalConfig.actor.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/include/fdbclient/CommitProxyInterface.h
fdbclient/include/fdbclient/GlobalConfig.actor.h
fdbserver/ClusterController.actor.cpp
fdbserver/GrvProxyServer.actor.cpp

CC sets a version to int_max in ClientDBInfo indicating a refresh, however, proxy server would reject this version for the error of future_version.
This change fixes this issue by not sending int_max, instead maintaining a lastKnown in memory and send it to grvproxy to get latest globalconfig.
this change also fixes some java tests that were used to test the fix
proof of this change fixes the issue: https://quip-apple.com/qaSKAr8jdgiL
20240514-225413-haofu-b2b463a2bf73a452  

Fix globalconfig refresh hang issue

---

fdbserver/TLogServer.actor.cpp

During destruction, rejoinClusterController actor should be cancelled to avoid accessing TLogData object.
20240517-212153-jzhou-362ae64fb4cc186e

Fix a segfault when tlog encounters platform_error

---

documentation/sphinx/source/release-notes/release-notes-710.rst
fdbserver/ClusterController.actor.cpp

cherrypick #11399 and https://github.com/apple/foundationdb/pull/11404
CC's checkBetterSingletons() calls getUsedIds() that asserts proxy interfaces are present. However, when a GRV/commit proxy failed, before CC starts a new recovery, the proxy's processId becomes empty, thus triggering the failure.
The fix is to cancel the caller while waiting for recovery.
To reproduce 7.1 commit 725a08a3ff clang build:
./fdbserver.6.0.15 -r simulation -f ./tests/restarting/from_5.2.0_until_6.3.0/ClientTransactionProfilingCorrectness-1.txt -s 900000399 -b on -f ./tests/restarting/from_5.2.0_until_6.3.0/ClientTransactionProfilingCorrectness-2.txt --restarting -s 900000400 -b on …

Fix an assertion failure when waiting for recovery [release-7.3]

---

fdbserver/TLogServer.actor.cpp

cherrypick #11407
During destruction, rejoinClusterController actor should be cancelled to avoid accessing TLogData object.
Reproduction:
commit: c15448fac7 clang build
seed: `-f ./tests/rare/CycleWithKills.toml -s 4253735514 -b off`
20240517-175903-jzhou-0d9d8397f18a09a7

Fix a segfault when tlog encounters platform_error [release-7.3]

---

fdbserver/GrvProxyServer.actor.cpp
fdbserver/include/fdbserver/MasterData.actor.h
fdbserver/masterserver.actor.cpp

use unique point to ensure memory recovery for dynamically allocated LatencyMetrics
`20240520-191358-dlambrig-373d0b73dd02e6c5`

use unique pointer to ensure memory recovery 

---

fdbserver/Ratekeeper.actor.cpp

cherry-pick of #11412
RKUpdate metrics changes.

RKUpdate metrics changes.

---

cmake/AddFdbTest.cmake

Since we are using TestHarness2 now.

Remove old test harness binaries from correctness packages

---

tests/restarting/to_7.3.0_until_7.3.39/BlobGranuleRestartCorrectness-1.toml
tests/restarting/to_7.3.0_until_7.3.39/BlobGranuleRestartCorrectness-2.toml
tests/restarting/to_7.3.0_until_7.3.39/ConfigureStorageMigrationTestRestart-1.toml
tests/restarting/to_7.3.0_until_7.3.39/ConfigureStorageMigrationTestRestart-2.toml
tests/restarting/to_7.3.0_until_7.3.39/CycleTestRestart-1.toml
tests/restarting/to_7.3.0_until_7.3.39/CycleTestRestart-2.toml
tests/restarting/to_7.3.39_until_7.4.0/BlobGranuleRestartCorrectness-1.toml
tests/restarting/to_7.3.39_until_7.4.0/BlobGranuleRestartCorrectness-2.toml
tests/restarting/to_7.3.39_until_7.4.0/ConfigureStorageMigrationTestRestart-1.toml
tests/restarting/to_7.3.39_until_7.4.0/ConfigureStorageMigrationTestRestart-2.toml
tests/restarting/to_7.3.39_until_7.4.0/CycleTestRestart-1.toml
tests/restarting/to_7.3.39_until_7.4.0/CycleTestRestart-2.toml

When downgrading to release-7.3 from a higher version, the tenant group is not compatible. So, we disable tenant in all downgrade tests to release-7.3.
100K test:
20240524-180057-zhewang-4ffef132b258f6e1           compressed=True data_size=36919045 fail_fast=10 max_runs=100000 priority=100 sanity=False submitted=20240524-180057 timeout=5400 username=zhewang

Disable tenant in downgrade test to 7.3

---

bindings/go/src/fdb/tenant.go

Fix the FDB_API_VERSION define. 
When creating the main PR I noticed that the API VERSION at the top was not defined correctly. Not sure why that didn't cause an issue when I tested it, or in CI but nevertheless, here is a fix.

fix API_VERSION.

---

bindings/go/src/fdb/database.go

Do not commit read-only transactions following the [C API documentation](https://apple.github.io/foundationdb/api-c.html#c.fdb_transaction_commit):
> It is not necessary to commit a read-only transaction – you can simply call fdb_transaction_destroy().
No forms of testing were done as I cannot locate a test suite for the Go bindings; would be happy to contribute some in a separate PR.

Go binding: do not commit read-only transactions

---

fdbkubernetesmonitor/copy.go
fdbkubernetesmonitor/copy_test.go
fdbkubernetesmonitor/main.go

With the recent changes in the copy logic we introduced a bug in the fdb-kubernetes-monitor for the sidecar mode. The operator expects that the sidecar mode copies the files to `/var/fdb/shared-binaries/bin/$version/fdbserver`, e.g. `/var/fdb/shared-binaries/bin/7.3.42/fdbserver` for `7.3.42` but right now it copies the files to `/var/fdb/shared-binaries/7.3/fdbserver` and therefore upgrades are not working with the unified image.
Once those changes are merged I create PRs to back port this fix to 7.1 and 7.3. …

Correct the path where the fdb-kubernetes-monitor copies the binary into when running in sidecar mode

---

tests/fast/BackupCorrectnessClean.toml
tests/fast/BackupToDBCorrectness.toml

Excluding some sharded rocksdb tests in simulation.
These tests are timing out in simulation, so excluding them temporarily from simulation.

Excluding some sharded rocksdb tests in simulation

---

fdbkubernetesmonitor/copy.go
fdbkubernetesmonitor/copy_test.go
fdbkubernetesmonitor/main.go

Back port of https://github.com/apple/foundationdb/pull/11428

[RELEASE-7.1] Correct the path where the fdb-kubernetes-monitor copies the binary into when running in sidecar mode

---

contrib/Joshua/scripts/bindingTestScript.sh
contrib/Joshua/scripts/localClusterStart.sh

This change allows people to run this script on macOS, which has quite an old version of bash at /bin/bash. Without it, I see the following error:
```
build/bindingtester/localClusterStart.sh: line 209: syntax error near unexpected token `>'
build/bindingtester/localClusterStart.sh: line 209: `  elif "${BINDIR}/fdbcli" -C "${FDBCONF}" --exec "kill; kill ${FDBCLUSTERTEXT}; sleep 3" --timeout 120 &>> "${LOGDIR}/fdbcli-kill.log"'
```
Also, note that the old shebang in bindingTestScript.sh was also missing the ! character.
localClusterStart.sh didn't need to be changed since it is directly sourced by bindingTestScript.sh, but there's no harm to correct it, and it could perhaps become useful if one tries to use it directly. …

Fix bindingTestScript.sh shebang and use /usr/bin/env to find bash

---

fdbkubernetesmonitor/monitor.go
fdbkubernetesmonitor/monitor_test.go

Before the monitor used a hardcoded value of 60 seconds. The exponential backoff, might help to recover the cluster faster.
Once those changes are merged I can open the PR's for 7.1 and 7.3.

Add exponential backoff mechanism for restarting fdbserver processes in the monitor

---

fdbkubernetesmonitor/kubernetes.go
fdbkubernetesmonitor/monitor.go

This PR also setups the process ID slice, as the process count is configured at runtime and cannot be changed dynamically.

Check in acceptConfiguration if the configuration has actually changed.

---

fdbkubernetesmonitor/monitor.go
fdbkubernetesmonitor/monitor_test.go

Backport: https://github.com/apple/foundationdb/pull/11447

[RELEASE-7.3] Add exponential backoff mechanism for restarting fdbserver processes in the monitor 

---

fdbkubernetesmonitor/monitor.go
fdbkubernetesmonitor/monitor_test.go

Backport: https://github.com/apple/foundationdb/pull/11447

[RELEASE-7.1] Add exponential backoff mechanism for restarting fdbserver processes in the monitor

---

fdbkubernetesmonitor/kubernetes.go
fdbkubernetesmonitor/main.go
fdbkubernetesmonitor/monitor.go

In cases where multiple operator instances are managing the same FDB cluster, like in the multi-dc setup, there can be a delay between a change in the coordinators and the operator instance updating the ConfigMap and all related resources. Especially in cases where only pods in a single dc are failing and the other operator instances are not receiving any events.

fdbkubernetesmonitor: Update the pod annotation if the cluster file changes

---

fdbkubernetesmonitor/metrics.go
fdbkubernetesmonitor/metrics_test.go
fdbkubernetesmonitor/monitor.go

We can add more metrics if we see the need for it.

Initial add of custom prometheus metrics for the fdbkubernetesmonitor

---

fdbclient/DatabaseBackupAgent.actor.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/include/fdbclient/NativeAPI.actor.h
fdbserver/DDRelocationQueue.actor.cpp
fdbserver/QuietDatabase.actor.cpp
fdbserver/SimulatedCluster.actor.cpp
fdbserver/fdbserver.actor.cpp
fdbserver/workloads/FuzzApiCorrectness.actor.cpp
flow/flow.cpp
flow/include/flow/Buggify.h
flow/include/flow/flow.h

This patch fixes a stateful ASSERT statement by moving the internal function call out of the ASSERT context.
Also rewrite BUGGIFY and gained pretty good performance improvement during simulation
See #11422 and #6771

Fix the stateful ASSERTs and rewrite BUGGIFY

---

contrib/mockkms/mock_kms.go
contrib/mockkms/mockkms_test.go

This PR fixes two minor typos in the comments. 
It does not change any functionality.

fix two misspelled words

---

fdbkubernetesmonitor/kubernetes.go
fdbkubernetesmonitor/monitor.go

Follow up of: https://github.com/apple/foundationdb/pull/11455#pullrequestreview-2113278192

fdbkubernetesmonitor: Retry update pod annotations in case of an error

---

fdbclient/NativeAPI.actor.cpp
fdbclient/StorageServerInterface.cpp
fdbrpc/include/fdbrpc/LoadBalance.actor.h
fdbrpc/include/fdbrpc/TSSComparison.h

Do not refer to TSS when logging error/trace messages in the context of replica comparison.
Testing:
Joshua job: 
20240618-164125-sre-1bd7af425d6bb76b (shows test failures but it is unlikely they were caused by this change set).
20240618-182439-sre-1bd7af425d6bb76b (shows a "cacheTest.toml" failing, again it is unlikely that was caused by this change set).

Replica comparison error message cleanup

---

fdbkubernetesmonitor/api/annotations.go
fdbkubernetesmonitor/api/config.go
fdbkubernetesmonitor/api/config_test.go
fdbkubernetesmonitor/api/suite_test.go
fdbkubernetesmonitor/api/version.go
fdbkubernetesmonitor/api/version_test.go
fdbkubernetesmonitor/copy.go
fdbkubernetesmonitor/copy_test.go
fdbkubernetesmonitor/kubernetes.go
fdbkubernetesmonitor/kubernetes_test.go
fdbkubernetesmonitor/main.go
fdbkubernetesmonitor/metrics.go
fdbkubernetesmonitor/metrics_test.go
fdbkubernetesmonitor/monitor.go
fdbkubernetesmonitor/monitor_test.go
fdbkubernetesmonitor/suite_test.go

Implements the fdb-kubernetes-monitor support for: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1906

Add support for the isolate process group annotation to shutdown fdbserver processes

---

fdbserver/TestTLogServer.actor.cpp

Disable TestTLogServer unit test. They should not run nightly.  They are not that robust yet.
Also set flag to put caller in client context, which appears to be necessary for class `TimedRequest`.

Disable TestTLogServer unit tests

---

design/dynamic-knobs.md
fdbserver/ConfigNode.actor.cpp
fdbserver/Coordination.actor.cpp
fdbserver/include/fdbserver/ConfigNode.h

By continuing to serve the configuration database interface used by clients even when disabled, clients no longer need to specify a special `--no-config-db` option when running commands which talk to the configuration database.

Serve no-op configuration database interface when disabled

---

fdbserver/SimulatedCluster.actor.cpp
fdbserver/fdbserver.actor.cpp
fdbserver/include/fdbserver/TesterInterface.actor.h
fdbserver/include/fdbserver/WorkerInterface.actor.h
fdbserver/tester.actor.cpp
fdbserver/worker.actor.cpp

This PR allows to do `--consistency-check-urgent-mode` when starting testers for distributed consistency checker. Then, the tester server will start a workload if the workload title is `ConsistencyCheckUrgent`. Otherwise, the tester will drop the workload with a SevError trace event: `StartingTesterServerCoreUnexpectedWorkload`.
Tested by loop back clusters.
20240709-170225-zhewang-5130153a2bf2bad6           compressed=True data_size=37027894 duration=7153738 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:02:04 sanity=False started=100000 stopped=20240709-180429 submitted=20240709-170225 timeout=5400 username=zhewang …

Add consistency-check-urgent-mode to tester process class

---

documentation/sphinx/source/consistency-check-urgent.rst
fdbserver/SimulatedCluster.actor.cpp
fdbserver/fdbserver.actor.cpp
fdbserver/include/fdbserver/TesterInterface.actor.h
fdbserver/include/fdbserver/WorkerInterface.actor.h
fdbserver/tester.actor.cpp
fdbserver/worker.actor.cpp

1 sharded-rocksdb external failure in 100K correctness test:
20240710-163303-zhewang-a048cab01a130a95           compressed=True data_size=35053760 duration=7571606 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:03:12 sanity=False started=100000 stopped=20240710-173615 submitted=20240710-163303 timeout=5400 username=zhewang
Tested by loopback cluster.

[Release-7.3] Cherrypick Distributed Consistency Checker Updates

---

packaging/docker/Dockerfile

hack the centos7 based Dockerfile so it will build images after CentOS 7 EOL.

patch image for building after EOL

---

fdbserver/SimulatedCluster.actor.cpp
fdbserver/TesterInterface.actor.h
fdbserver/WorkerInterface.actor.h
fdbserver/fdbserver.actor.cpp
fdbserver/tester.actor.cpp
fdbserver/worker.actor.cpp

Cherry-pick [11484](https://github.com/apple/foundationdb/pull/11484)
Passed 100K correctness tests:
20240711-211001-zhewang-61e110f9b1d5360a           compressed=True data_size=26943305 duration=4489836 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:48:33 sanity=False started=100000 stopped=20240711-215834 submitted=20240711-211001 timeout=5400 username=zhewang
Tested by loopback cluster.

[Release-7.1] Cherry-pick Add consistency-check-urgent-mode to tester process class (#11484)

---

fdbserver/ClusterController.actor.cpp
fdbserver/include/fdbserver/ClusterController.actor.h

`DBInfo::logGenerations` in ClusterController looks like dead code so deleting it.
- Ran `ctest`, all tests passed.
- Ran `fdbserver -r unittests -f noSim`, all tests passed.
- Ran `fdbserver -r simulation -f tests/fast/RandomUnitTests.toml`, all tests passed.
- Ran 100K Joshua test (`20240712-185721-praza-94ed9d61cb4505d3`). 99999 tests passed, 1 failed (`fast/BlobRestoreTenantMode.toml`). Can reproduce the failing test but don't think it's related to my change -- will discuss with @jzhou77. 
---

[cluster-controller] Remove unused DBInfo::logGenerations

---

cmake/ConfigureCompiler.cmake
cmake/FDBComponents.cmake
cmake/Jemalloc.cmake

A new flag, USE_CUSTOM_JEMALLOC, is added. If it is turned on, e.g. `cmake $HOME/src/foundationdb/ -GNinja -DUSE_CUSTOM_JEMALLOC`, the builder will download Jemalloc and ignore local version.

Add flag for custom jemalloc build

---

design/dynamic-knobs.md

fdb expects these to be bytes, not str.
It looks a bit uglier than `str`, but without `b` prefix, this example doesn't work, and throws `Key/Value must be a type of bytes`.
Alternatively, Python interface can be made to accept `str` and it can encode to `bytes` internally, but that may cause trouble in the future, or it requires a bit more careful thinking (e.g. it would be surprising to put `str`, and get `bytes`).
So for now, this is the simplest fix I think.

Update dynamic-knobs.md for Python 3

---

fdbserver/TestTLogServer.actor.cpp

Without this change, `cmake --build` fails with (on macOS with Apple clang 15.0.0):
fdbserver/TestTLogServer.actor.cpp:363:125: error: use 'template' keyword to treat 'getReply' as a dependent template name
Full error:
```
FAILED: fdbserver/CMakeFiles/fdbserver.dir/TestTLogServer.actor.g.cpp.o
/opt/homebrew/bin/ccache /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_SYSTEM_NO_DEPRECATED -DFMT_SHARED -DNO_INTELLISENSE -D_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION -DCOMPILATION_UNIT=/Users/sepeth/Code/foundationdb/build/fdbserver/TestTLogServer.actor.g.cpp -I/Users/sepeth/Code/foundationdb/bindings/c -I/Users/sepeth/Code/foundationdb/build/bindings/c -I/Users/sepeth/Code/foundationdb/fdbserver/include …
```

Fix a compilation issue in TestTLogServer.actor.cpp

---

fdbserver/CommitProxyServer.actor.cpp

Make commit proxies update known committed version after receiving a reply (for the commit version request) from the sequencer, instead of after making the committed transactions persistent on tLogs.
Testing:
With version vector disabled (and no knobs explicitly set):
Job id: 20240718-101540-sre-c8a4b8fcac91c90d (no failures).
By setting "ProxyCommitData::minKnownCommittedVersion" in "reply()" actor in "CommitProxyServer.actor.cpp" in all cases:
Job id: 20240718-131047-sre-8b5549fd2f3d236e (no failures). …

Compute known committed version correctly when version vector unicast is enabled

---

fdbserver/CommitProxyServer.actor.cpp

Compute known committed version correctly when version vector unicast is enabled (#11511).
Testing:
With version vector disabled (and no knobs explicitly set):
JobId: 20240719-071611-sre-c0311924c42fb1e6 (no failures).
By setting "ProxyCommitData::minKnownCommittedVersion" in "reply()" actor in "CommitProxyServer.actor.cpp" in all cases:
JobId: 20240719-094358-sre-9824baf57069c0d4 (no failures).

Cherry pick PR Compute known committed version correctly when version vector unicast is enabled #11511 

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/ClusterController.actor.cpp

Add a knob to pause gray failure recoveries. While paused, the health checks will still be done and the `ClusterControllerHealthMonitor` messages logged. However, no action will be taken. 
The knob is defined with Atomic set to false, meaning the system does not need to be rebooted when the knob is set. The dynamic knob feature does not use the transaction system. The knob is intended for use during production incidents where running a heavy duty temporal script is difficult.
To pause health monitoring, run the command below from fdbcli:
`fdb> setknob cc_pause_health_monitor true`
Please check each of the following things and check *all* boxes before accepting a …

Add dynamic knob to disable gray failure recoveries.

---

fdbserver/workloads/ClientMetric.actor.cpp
tests/restarting/from_7.1.63_until_7.2.0/ClientMetricRestart-1.toml
tests/restarting/from_7.1.63_until_7.2.0/ClientMetricRestart-2.toml
tests/restarting/from_7.3.49/ClientMetricRestart-1.toml
tests/restarting/from_7.3.49/ClientMetricRestart-2.toml

This change also disable waitForQuiescenceEnd in clientmetric test. There are other transactions happening, so there will be lots of conflicts in fdbClientInfo/client_latency prefix.
This change lower the sample rate of client metric to avoid such conflicts. It also increases the keys to write correspondingly to make sure client latency are being written.

lower the sample rate of client metric in simulation

---

fdbrpc/tests/AuthzTlsTest.actor.cpp
fdbserver/storageserver.actor.cpp
flow/Net2.actor.cpp
flow/TLSConfig.actor.cpp
flow/Trace.cpp
flow/include/flow/Error.h
flow/include/flow/TLSConfig.actor.h

This patch adds more output about TLS failures, e.g.
<Event Severity="20" Time="1716265824.713579" DateTime="2024-05-21T04:30:24Z" Type="TLSPolicyFailure" ID="0000000000000000" SuppressedEventCount="0" Reason="Rule.Cert.Issuer" Rule="Rule{ verify_cert=1, verify_time=1, Subject=[ ], Issuer=[ ], Root=[ ] }" ThreadID="7547317051334743152" LogGroup="default" />
The failure data will include the rule, the reason of failure and the value of corresponding fields. …

Better TraceEvent output for TLS failures

---

fdbrpc/FlowTransport.actor.cpp
fdbrpc/sim2.actor.cpp
fdbserver/CommitProxyServer.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/LogRouter.actor.cpp
fdbserver/LogSystemPeekCursor.actor.cpp
fdbserver/OldTLogServer_4_6.actor.cpp
fdbserver/OldTLogServer_6_0.actor.cpp
fdbserver/OldTLogServer_6_2.actor.cpp
fdbserver/TLogServer.actor.cpp
fdbserver/include/fdbserver/ClusterController.actor.h
fdbserver/storageserver.actor.cpp
fdbserver/worker.actor.cpp
flow/Net2.actor.cpp

Add PeerAddress to all PeerAddr/Peer TraceEvent [release-7.3]

---

bindings/go/src/fdb/generated.go
fdbclient/vexillographer/fdb.options

Documentation currently mentions that the `datacenter_id` needs to be hexadecimal, however that is not the case.

Documentation fix: datacenter_id does not need to be hexadecimal

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/ClusterController.actor.cpp

Add a knob to pause gray failure recoveries. While paused, the health checks will still be done and the ClusterControllerHealthMonitor messages logged. However, no action will be taken.
The knob is defined with Atomic set to false, meaning the system does not need to be rebooted when the knob is set. The dynamic knob feature does not use the transaction system. The knob is intended for use during production incidents where running a heavy duty temporal script is difficult.
To pause health monitoring, run the command below from fdbcli:
`fdb> setknob cc_pause_health_monitor true`
Joshua `20240722-163317-dlambrig-2fec58a027c97688`
Tests confirmed the fdbcli command modified the value of the knob in a running system without causing a reboot, to show gray failure stopped taking any action. A …

Cherry pick Add dynamic knob to disable gray failure recoveries. (#11509)

---

fdbclient/include/fdbclient/BulkLoading.h
fdbserver/include/fdbserver/DataDistribution.actor.h
fdbserver/include/fdbserver/RocksDBCheckpointUtils.actor.h
fdbserver/storageserver.actor.cpp

100K correctness test with 1 irrelevant failure:
20240725-010922-zhewang-49e2a943ab51bb85           compressed=True data_size=37148235 duration=6949335 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:03:58 sanity=False started=100000 stopped=20240725-021320 submitted=20240725-010922 timeout=5400 username=zhewang

Fix Valgrind Issue of BulkLoading

---

fdbserver/SimulatedCluster.actor.cpp
tests/fast/BulkLoading.toml

When bulk loading selects destination team to inject a range, it always select teams that do not own the range. As a result, it is hard to select an available team when the available machine count per DC is small. The bulk loading test simulation can get stuck when HA mode is one since each DC only has 4 storage machine in the worst case. Previously, we worked around by disabling remote DC (disabling HA) in the bulk loading test. Now, by enforcing extra storage machines to each DC, bulk loading can easily find available team when HA is on.
In this PR, we add `extraStorageMachineCountPerDC` config to simulation. We enable HA in bulk loading test.
20240725-233033-zhewang-d4de5e544b98a7d6           compressed=True data_size=37148289 duration=6329756 ended=100000 …

Add extraStorageMachineCountPerDC config to simulation

---

fdbserver/TestTLogServer.actor.cpp
fdbserver/include/fdbserver/TestTLogServer.actor.h

The TLog test should better simulate actual versions.
`20240725-231728-dlambrig-6db4a7c650dbb1d6 `

Use actual versions in tlog tests

---

fdbserver/DDTeamCollection.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/worker.actor.cpp

During simulation tests, mute `MachineTeamInfo` and `MoveInUpdatesPrePersist` and `PeerHealthMonitor`, as they account for 20% ~ 50% of the total trace events when TraceTooManyLines occurs.
Avoid selecting destination team with high disk util to bulkload the data. If we select dest team to do bulkloading without considering the leftover machine bytes, it can result in MachineTeamInfo is intensively generated by printSnapshotTeamsInfo() when the leftover machine bytes is too small.
20240726-220113-zhewang-9ab0a468cd9a92ab           compressed=True data_size=37147684 duration=5159112 ended=100000 fail=2 fail_fast=10 max_runs=100000 pass=99998 priority=100 remaining=0 runtime=1:12:23 sanity=False started=100000 stopped=20240726-231336 submitted=20240726-220113 …

Fix TraceTooManyLines in BulkLoading Simulation Test

---

fdbserver/DDRelocationQueue.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/include/fdbserver/DataDistribution.actor.h

In early minor versions of release-7.3, DD does not encode DataMoveType in DataMoveID when persisting DataMoveID to the system metadata. Thus, when upgrading to the current version from the old system, DD can load a data move metadata but decoding the metadata in a wrong way. In particular, the data move type can be decoded as a bulkLoading type while no bulkLoadState is in the data move metadata. In this case, SS DD cancels such data move to keep the correctness.
20240727-061611-zhewang-06d38ad830126b01           compressed=True data_size=37149430 duration=7053009 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=0:58:01 sanity=False started=100000 stopped=20240727-071412 submitted=20240727-061611 timeout=5400 …

Fix Compatibility Issue of DataMoveId with BulkLoad type

---

fdbserver/workloads/BulkLoading.actor.cpp

When a complete task's metadata has been erased, acknowledgeBulkLoadTask should not retry, since this task has been acknowledged.
100K bulkLoad tests with 1 failure which is getTeamForBulkLoad stuck:
20240729-170524-zhewang-94893831862647e8           compressed=True data_size=37184050 duration=30443390 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=3:50:49 sanity=False started=100000 stopped=20240729-205613 submitted=20240729-170524 timeout=5400 username=zhewang
100K correctness test with 3 irrelevant failures:
20240729-173441-zhewang-17db2fe2631bfdfe           compressed=True data_size=37151002 duration=6648073 ended=100000 fail=3 fail_fast=10 max_runs=100000 pass=99997 priority=100 remaining=0 runtime=0:56:30 sanity=False started=100000 …

Fix acknowledgeBulkLoadTask stuck

---

fdbclient/ServerKnobs.cpp

When dest SS applying mutations accumulated for data moves, the fetchShard partitions the mutations into batches to apply. Each batch size is at most `fetch_shard_updates_byte_limit`. When `fetch_shard_updates_byte_limit` is set to 1, there can be tons of rounds of applying mutations when the number of mutations accumulated during the data move is large. As a result, a data move takes super long time to complete the data move, which triggers DDGotStuck.
100K correctness tests with 1 failure:
20240730-002044-zhewang-3c99c31d6adfe116           compressed=True data_size=37152805 duration=7193275 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:01:49 sanity=False started=100000 stopped=20240730-012233 submitted=20240730-002044 timeout=5400 …

Fix DD stuck due to too many rounds of FetchShardApplyingUpdates

---

packaging/docker/Dockerfile
packaging/docker/entrypoint.bash
packaging/docker/kubernetes/test_config.yaml

Changes the default base image from centos7 (EOL) to RockyLinux 9.3. I'm doing some e2e tests with the operator to see if anything breaks.

Change the default base image to RockyLinux9

---

fdbclient/BackupAgentBase.actor.cpp

In the restore test, there are hot ranges with writes to customized range with prefix "BeforeRestart" or "AfterRestart". As a result, FDB can return transaction_throttled_hot_shard errors and cause test failure.
This is usually happening UpgradeAndBackupRestore-2.toml tests (roughly 2 out 20k  20240801-195603-jzhou-c4fa6aff5d7d6b4c), e.g.,
```
fdbserver-7.3.43 -f ./tests/restarting/from_7.3.0/UpgradeAndBackupRestore-1.toml -s 2514831264 -b on
-f ./tests/restarting/from_7.3.0/UpgradeAndBackupRestore-2.toml --restarting -s 2514831265 -b on
```
100k 20240801-211333-jzhou-58d8e2565e953e7f …

Fix ApplyMutationsError test failure due to hot shard throttling

---

bindings/go/src/fdb/errors.go
bindings/go/src/fdb/fdb.go

This PR contains the following notable changes:
1. make sure that database creation is happening only while network thread is running
2. panic if the call to `fdb_run_network()` fails, instead of logging an error only
3. `StartNetwork()`, already deprecated, effectively becomes a no-op
4. expose a new `StopNetwork()` method which allows to follow spec for issues like https://github.com/apple/foundationdb/issues/2978 and https://github.com/apple/foundationdb/issues/3015
Any advice for test coverage?

Go binding: add StopNetwork()

---

documentation/sphinx/source/configuration.rst
fdbmonitor/fdbmonitor.h
fdbmonitor/fdbmonitor_lib.cpp
fdbmonitor/fdbmonitor_tests.cpp

Add environment variable support to fdbmonitor. Users can now provide a space separated environment variable list in their fdbmonitor conf file via `envvars` field. 
This PR required quite a lot of iteration as I was learning the nuances of [putenv](https://man7.org/linux/man-pages/man3/putenv.3.html) around memory management (read the history section to understand the complexity involved), what's allowed in the string and what's not, etc. 
Eventually I ended up these design and implementation decisions:
- Overall, the idea is to follow delete-envvars and optimize for feature consistency. 
- I do not use `putenv`, [this resource](https://wiki.sei.cmu.edu/confluence/display/c/POS34-C.+Do+not+call+putenv%28%29+with+a+pointer+to+an+automatic+variable+as+the+argument) provides some good …

[fdbmonitor] Environment variable support

---

flow/TLSConfig.actor.cpp

BIO_get_mem_data will return the length of the string, however, the string is not zero-terminated. The length value determines where the string terminates.

Fix the misuse of BIO_get_mem_data

---

fdbmonitor/fdbmonitor.h
fdbmonitor/fdbmonitor_lib.cpp

Grouping fixes for some bugs I found in fdbmonitor:
1. When a child process fails, it exits and is retried by parent after a `restart-delay`. This delay did not account for setting/unsetting environment variables, but now it does. Fix was simply to move the delay a bit up in code. 
2. Some string processing bugs when unsetting environment variables due to `delete-envvars` configuration. These are related to not handling `std::string::npos` properly, which means previously we could have been reading outside the string buffer which is [undefined behavior](https://en.cppreference.com/w/cpp/string/basic_string/operator_at). 
3. The trickiest one was reading invalid memory issue that I found as part of `delete-envvars` use-case but can happen for other fdbmonitor use-cases. It happens because …

[fdbmonitor] Bug fixes

---

fdbmonitor/fdbmonitor_tests.cpp

Simple tests to ensure we don't regress on logic that extracts key and value from a key-value pair. 
- `ctest` on `fdbmonitor_tests` target passes
---

[fdbmonitor] Ctests for envvars key-value extraction

---

fdbmonitor/fdbmonitor.cpp
fdbmonitor/fdbmonitor.h
fdbmonitor/fdbmonitor_lib.cpp

This is potentially happening on FreeBSD as well.
Without this change, the build fails with multiple identifiers not found, such as `gettimeofday`, `sigprocmask`, `kqueue` and some more related ones. `watch_conf_dir` and  `watch_conf_file` were also missing in the `fdbmonitor.h`.

Fix fdbmonitor build issues on macOS

---

fdbserver/DataDistribution.actor.cpp
fdbserver/include/fdbserver/DataDistribution.actor.h

100K Correctness with 1 external timeout:
20240809-181227-zhewang-d1ca44ea98a1392f           compressed=True data_size=37152430 duration=5869844 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=0:56:22 sanity=False started=100000 stopped=20240809-190849 submitted=20240809-181227 timeout=5400 username=zhewang
100K BulkLoading:  
20240809-191033-zhewang-a6d9be6480a32fa6           compressed=True data_size=37185806 duration=10528867 ended=37929 fail=1 fail_fast=10 max_runs=100000 pass=37928 priority=100 remaining=1:51:30 runtime=1:08:08 sanity=False started=44063 submitted=20240809-191033 timeout=5400 username=zhewang …

Fix uninitialized bulkLoadMode

---

design/tlog-spilling.md.html

And, add two related metrics to the empty metrics section for Spilling (`PersistentDataVersion` and `PersistentDataDurableVersion`).
I think some more can be useful and added to this doc such as `SharedBytesInput` and `SharedBytesDurable` because spilling happens when the difference between them is higher than `TLOG_SPILL_THRESHOLD`. I didn't add them (yet), because first, I wanted to ask if that sounds good. And second, Spilling metrics may not be necessarily the best place as they are more TLogServer related general metrics (still very related though). What do you think?
If …

Fix some minor errors in design/tlog-spilling.md.html

---

fdbcli/ExcludeCommand.actor.cpp
fdbcli/Util.actor.cpp

To debug exclude timeout issues. https://github.com/apple/foundationdb/pull/11009 validates there are servers for the given excluded locality, which might be related to the timeout problem.
Use PRIORITY_SYSTEM_IMMEDIATE for excludeServersAndLocalities() call.

Add more trace events for exclude command

---

fdbserver/Status.actor.cpp

The logSystemConfig could be changed after the yield(), thus the iterator can points to invalid memory.
To reproduce with gcc build at commit 3e90644779:
-f tests/slow/DDBalanceAndRemoveStatus.toml -s 3134372275 -b off
20240814-041243-jzhou-19b95ae325eb46fb

Fix a cluster controller crash in status server

---

fdbbackup/backup.actor.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/ReadYourWrites.actor.cpp

These options were being cast from integer literals to pointers, which caused a segfault. I tried to follow the pattern I see for how these kind of options were set in other parts of the code, like this binding tester actor: https://github.com/apple/foundationdb/blob/main/bindings/flow/tester/Tester.actor.cpp#L1652.
I was able to get this to build, and to run a backup status command successfully. I added debug logging to confirm that the fdbbackup command is applying the expected option.

Capture default database options in fdbbackup in a local variable.

---

documentation/sphinx/source/release-notes/release-notes-730.rst

Add 7.3.44-7.3.49 release notes [release-7.3]

---

fdbserver/TestTLogServer.actor.cpp
fdbserver/include/fdbserver/TestTLogServer.actor.h

Add support for multiple tags, to enable differentiating the number of commits per tLog.
20240813-205527-dlambrig-77d878858b487400

Modify tlog unit tests to work with multiple tags

---

fdbcli/ExcludeCommand.actor.cpp
fdbcli/Util.actor.cpp
fdbserver/Status.actor.cpp

Use PRIORITY_SYSTEM_IMMEDIATE for excludeServersAndLocalities() call.
Fixed a cluster controller crash bug in status server
cherrypick #11571 #11573

Add more trace events for exclude command [release-7.1]

---

fdbbackup/backup.actor.cpp

This fixes issues that were identified after #11575 was merged. The initialization section is meant to be setting up `sourceDb`, but it was updated in that PR to set up `db`.

Fix references to the wrong DB in the backup actor initialization.

---

documentation/tutorial/tutorial.actor.cpp

The client calls `connect` as part of bootstrapping the connection with the server and getting the `SimpleKeyValueStoreInterface` back. Right now, to make this call, we first create a temporary  `SimpleKeyValueStoreInterface` just to hold an inner `RequestStream`. As far as I can tell, this is not needed and was confusing me because to get a `SimpleKeyValueStoreInterface` from server, the client is itself creating a temporary `SimpleKeyValueStoreInterface` first. We can instead just create a `RequestStream` object directly without going through `SimpleKeyValueStoreInterface`. 
Ran `kvSimpleClient` and `multipleClients` against `kvStoreServer`, ensured clients got expected responses. 
--- …

[tutorial] Simplify connect() logic

---

fdbserver/TLogServer.actor.cpp
fdbserver/TagPartitionedLogSystem.actor.cpp
fdbserver/include/fdbserver/TLogInterface.h
fdbserver/include/fdbserver/TagPartitionedLogSystem.actor.h

Part of version vector recovery.
Cherry pick cluster level RV when tLogs advance at different rates (#11557)
* simulate more than one tlog
* Draft use cluster RV for tlogs in version vector
* add TestTLogRecovery2
* Respond to review comments
* Add assert
* Send clusterRV to all locked tlogs
* Fix typo on rebase
* add memory managed IdToInterf structure
---------
Joshua
20240823-184245-dlambrig-f51e257379a9b2cf

Cherry pick cluster level RV when tLogs advance at different rates (#11557)

---

fdbserver/TagPartitionedLogSystem.actor.cpp

Stash correct id for tlog identification in recovery
(prior, the one associated with the interface did not match the dbgid returned on the lock call, resulting in a failed lookup [here](https://github.com/apple/foundationdb/blob/8475ad87bb68eb2bca99dfc8db462115ac4acf15/fdbserver/TagPartitionedLogSystem.actor.cpp#L2538))
Joshua
`20240826-181851-dlambrig-4ff8b42f5a49e024`

Stash correct id for tlog identification in recovery

---

fdbserver/TagPartitionedLogSystem.actor.cpp

Cherry pick check existence of optional interface (https://github.com/apple/foundationdb/pull/11593)
Joshua
`20240826-183254-dlambrig-c67d2e4cbd8a9233`

Cherry-pick check existence of optional interface (#11593)

---

fdbserver/TagPartitionedLogSystem.actor.cpp

Cherry pick:  Stash correct id for tlog idenfication in recovery (#11604)
Joshua:
`20240826-220057-dlambrig-0c4f65e71f1c3e33`

Cherry pick:  Stash correct id for tlog idenfication in recovery (#11604)

---

design/coroutines.md
fdbclient/include/fdbclient/NativeAPI.actor.h
fdbrpc/include/fdbrpc/fdbrpc.h
fdbserver/LogRouter.actor.cpp
fdbserver/LogRouter.cpp
fdbserver/include/fdbserver/WorkerInterface.actor.h
fdbserver/workloads/Watches.actor.cpp

20240824-010621-jzhou-ab2df94b5f043c18
The watches workload has one actor left, which is not easy to do without introducing some ugly workaround. Specifically,
```
} catch (Error& e) {
if (tr != nullptr) {
wait(tr->onError(e));
}
}
```
This piece of code is the one, not easy to be replaced with a `db.run()` call.

Refactor LogRouter and Watch workload using coroutines

---

fdbserver/workloads/ClientMetric.actor.cpp

uint64_t should be used instead of int
```
Read from globalconfig: rate=0.010000 size=3621340
VersionStamp is 2181719979
vs1=2181719979
writeRandomKeys finish, written=136
Read from globalconfig: rate=0.010000 size=3621340
VersionStamp is 2284603078
Assertion vs >= previousVS failed @ /root/src/foundationdb/fdbserver/workloads/ClientMetric.actor.cpp 199:
```
reproduced the issue, and 2181719979 is overflow

Fix overflow

---

fdbserver/TagPartitionedLogSystem.actor.cpp

Cherry-pick PR https://github.com/apple/foundationdb/pull/11617.
Testing:
Joshua job: 20240829-190837-sre-bac092f07172c0c4 (shows a failure in "BlobGranuleRangesChangeLog.toml" test, likely not related to this change)

Cherry-pick PR #11617 (Address an assertion failure)

---

fdbserver/TLogServer.actor.cpp
fdbserver/TagPartitionedLogSystem.actor.cpp
fdbserver/include/fdbserver/TLogInterface.h

Refactor `uncommitedVersions` to use struct rather than tuple. The struct is more readable and concise.
We saw serialization problems when using tuples (e.g. `tests/fast/Watches.toml` with seed 814493817). The tuple was embedded in a deque. The size element of the vector in the third position of the tuple (tLogLocIds) was corrupted. Using a struct in serialization is a common pattern in the code. The serialization problems do not manifest in testing with version vector enabled: `20240829-154514-dlambrig-4f44b1d4e56b905b`.
This should be loaded on top of [PR 11617](https://github.com/apple/foundationdb/pull/11617)
Joshua 
`20240829-175112-dlambrig-fdae5c124340f01d `
The general pull request guidelines can be found [here](https://github.com/apple/foundationdb/wiki/FoundationDB-Commit-Process …

refactor to use struct rather than tuple for "uncommitedVersions"

---

fdbserver/TLogServer.actor.cpp
fdbserver/TagPartitionedLogSystem.actor.cpp
fdbserver/include/fdbserver/TLogInterface.h

Cherry pick 11619: refactor to use struct rather than tuple for "uncommitedVersions"
* refactor to use struct rather than tuple for uncommitedVersions
* Document UnknownCommittedVersions struct
---------

Cherry pick 11619: refactor to use struct rather than tuple for "uncommitedVersions"

---

fdbserver/TagPartitionedLogSystem.actor.cpp

Entries in LogSet::logServers shouldn't be skipped while computing the ids of log servers (as it would cause a mismatch in the ids computed by the commit proxy and the cluster controller).
Testing:
- Test "/root/src/foundationdb/tests/fast/Unreadable.toml -b on -s 3902225582" fails on an assertion without this change, succeeds with it.
- Joshua job (with version vector disabled): 20240830-223342-sre-8b2b901fe1957f98

Address a bug related to computing the ids of log servers

---

bindings/go/src/fdb/snapshot.go
bindings/go/src/fdb/transaction.go

Allow cancelling snapshots and R/O transactions.
It is beneficial to cancel a transaction, even if not performing any changes, so that futures and other associated resources can be released early.

Go binding: allow cancelling snapshots and R/O transactions

---

fdbserver/CommitProxyServer.actor.cpp
fdbserver/LogSystem.cpp
fdbserver/include/fdbserver/LogSystem.h

In the commit path, random log routers are chosen to write mutations to. They are chosen after resolution. In version vector all  tags must be chosen prior to resolution to obtain the previous versions for logs. This PR modifies the version vector code to select a single random log router prior to resolution. It is believed a single remote tag for the entire batch of mutations is more performant than a different remote tag per mutation, because fewer logs will be selected.  
version vector enabled `tests/rare/TransactionTagSwizzledApiCorrectness.toml`  `2560436537`
Joshua
`20240905-173820-dlambrig-fb30d554e645f976` 2560436537 …

Choose log router tag prior to resolution in commit path for version vector

---

fdbserver/TagPartitionedLogSystem.actor.cpp

Cherry-pick PR https://github.com/apple/foundationdb/pull/11623.
Testing:
Joshua job: 20240905-231740-sre-cf375feac6ff1aa9 (no failures)

Cherry-pick PR #11623 (Address a bug related to computing the ids of log servers)

---

bindings/go/src/fdb/database.go
bindings/go/src/fdb/fdb_test.go
bindings/go/src/fdb/futures.go
bindings/go/src/fdb/transaction.go

Fix bug with R/O transaction destroyed before futures, add GC references for db/tx
In a [previous PR](https://github.com/apple/foundationdb/pull/11366) the R/O transaction was optimized and the finalizer was removed; however this prevents using any future, since transaction is already destroyed by the time future is attempted evaluation.
Additionally, a new issue is uncovered and addressed: the Go Database, Transaction and Future objects are all garbage-collected independently, which is incorrect because Database and Transaction must not be garbage-collected if any future has not yet been garbage-collected.
A test has been added to verify that futures work right after their creation within a `ReadTransact` call.

Go binding: fix bug with R/O transaction destroyed before futures, add GC references for db/tx

---

fdbclient/S3BlobStore.actor.cpp
flow/include/flow/error_definitions.h

s3 token is from local disk and might be expired or invalid,
before this change backup retries to upload data to s3 indefinitely,
thus it is a waste of network bandwidth.
Now retry with a get request of list all buckets in the case of
s3 token error, and only retry the upload when token error disappears.

Retry with dryrun in the presence of s3 token error

---

fdbclient/ServerKnobs.cpp
fdbserver/CommitProxyServer.actor.cpp
fdbserver/Resolver.actor.cpp

Disable version vector on batches that contain mutations that overlap with backup ranges. When such a mutation is found, an empty set of tags is sent to the resolver, which is interpreted as a signal to revert to non-version vector behavior. The technique will work for other features for which integration is deferred, e.g. encryption.
fixed test with vv enabled
`src/foundationdb/tests/slow/ParallelRestoreOldBackupCorrectnessCycle.toml` `2560435537`
Joshua
`20240906-181155-dlambrig-b8b076afc599653a` 

Disable version vector on batches with backed up mutations

---

tests/fast/RawTenantAccessClean.toml

Disable version vector for tenant test. `proxy_use_resolver_private_mutations` was already disabled for the test. I ran Joshua with `proxy_use_resolver_private_mutations` enabled and it passed for the test. However, it is possible the chosen seed did not result in a failure. It is safer to disable version vector entirely for the test. We do not maintain the tenant feature and making it work with experimental features like version vector is premature.

Disable version vector for tenant test.

---

fdbclient/ServerKnobs.cpp

buggifyShortReadWindow used unitialized variable ENABLE_VERSION_VECTOR.
Seed: `-r simulation -f ./tests/fast/SimpleAtomicAdd.toml -s 4205467688 -b on`

Fix a Valgrind error

---

fdbbackup/backup.actor.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/ReadYourWrites.actor.cpp

the bug was introduced in #11403 and affects 7.1.60 and 7.1.61
cherrypick #11575 #11588

Fix fdbbackup crashes [release-7.1]

---

fdbclient/ServerKnobs.cpp

cherry-pick of #11637
Enabling rocksdb direct_io and wiggle knobs

Enabling rocksdb direct_io and wiggle knobs

---

fdbcli/BulkLoadCommand.actor.cpp
fdbcli/DebugCommands.actor.cpp
fdbcli/GetAuditStatusCommand.actor.cpp

Probably not a big issue and not sure if anyone is running FDB on 32 bit, but this still helps to suppress perhaps unnecessary warnings.

Fix warnings for long long or int64_t format specifiers by switching to fmt::print*

---

fdbclient/ServerKnobs.cpp

These knobs are used in gray failure detection and recovery. Turning on in simulation tests to match production behavior for clusters that are opting in. 
100K Joshua: `20240912-214205-praza-2e531fce2f1d8d00`
---

[CC+Worker] Enable WORKER_HEALTH_MONITOR related knobs in simulation tests

---

fdbclient/ReadYourWrites.actor.cpp

#11591 has a very verbose trace event

Fix TracedTooManyLines in simulation [release-7.1]

---

fdbserver/tester.actor.cpp
fdbserver/workloads/ConsistencyCheckUrgent.actor.cpp

To speed up ConsistencyCheckUrgent workload that can take very long time in simulation.

Reduce retry count when SS interface is not found

---

fdbclient/ReadYourWrites.actor.cpp
fdbclient/include/fdbclient/Atomic.h
fdbserver/workloads/Unreadable.actor.cpp
fdbserver/workloads/WriteDuringRead.actor.cpp

As explained in [this](https://forums.foundationdb.org/t/why-is-read-or-wrote-unreadable-key-necessary/3753/11) forum post, the range that gets marked as unreadable should start from the next possible read version, not the current one. That's because the final version stamp can't possibly start with the current read version. The `+1` should be added to the read version if it's known.
The test script (JS):
```js
import { beforeEach, test } from 'node:test';
import * as fdb from 'foundationdb';
import assert from 'node:assert';
fdb.setAPIVersion(720);
const db = fdb.open();
beforeEach(() => db.clearRange(Buffer.from([]), Buffer.from([0xff])));
// currently works
test('read from the range of the previous read version', async () => {
await db.doTn(async tn => {
const readVersion = await …
```

Fix the key range affected by setting version stamped key

---

fdbmonitor/fdbmonitor.h
fdbserver/tester.actor.cpp

Hi there,
This was one of the issues when compiling on macOS. See here: https://forums.foundationdb.org/t/building-on-macos/4491/3
This replaces `boost::filesystem` with `std::filesystem`.`std::filesystem::recursive_directory_iterator` is supported since C++17  and `std::string::ends_with` is since C++20. FoundationDB is configured to C++20.

Fix errors when linking fdbserver on macOS due to boost::filesystem

---

fdbrpc/include/fdbrpc/SimulatorProcessInfo.h
flow/include/flow/IConnection.h
flow/include/flow/IPAddress.h

I use clangd in my editor which reports errors related to missing headers or misplaced type forward declarations. Fixing some of these issues in this PR. 

[fdbserver] Fix some issues reported by clangd

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/DDShardTracker.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/include/fdbserver/DDShardTracker.h
fdbserver/include/fdbserver/DataDistribution.actor.h
fdbserver/workloads/MockDDTrackerShardEvaluator.actor.cpp

Backport https://github.com/apple/foundationdb/pull/11543
When usableRegions changes, data moves should be triggered to satisfy the new usableRegions. In a restarting test, a restored data move can be cancelled when encode shard location metadata is on in the first test. For details, see trace event: `RelocateShardCancelDataMoveTeamNotFound` and `DDInitScheduledCancelDataMove`. If no further data move is triggered, the shard's usableRegions can never match the new usableRegions on a shard, which can block the simulation team size consistency check. To fix this issue, this PR adds a usableRegion checker per shard when a shard is created. If a shard destination team does not meet the new usableRegions, issue a data move for the shard. To avoid tons of shards triggering data moves at the …

[Release-7.3] Backport: add usable region check per shard for encode shard location metadata

---

fdbserver/SimulatedCluster.actor.cpp
fdbserver/TagPartitionedLogSystem.actor.cpp

Changes:
- Disable logWriteAntiQuorum when version vector is enabled (as we don't use logWriteAntiQuorum in production and we don't like to put in the effort needed to make version vector work with logWriteAntiQuorum at this stage)
- Refactor the version vector related recovery version computation logic in order to make it work better with the recovery restart logic
Testing:
Joshua job (with version vector disabled): 20240911-200559-sre-99f295f99cda7e02 (started)

Refactor version vector related recovery version computation logic

---

fdbserver/workloads/MutationLogReaderCorrectness.actor.cpp

MutationLogReaderCorrectness is too heavy, which can cause TracedTooManyLines failures in simulation tests.
100K MutationLogReaderCorrectness tests with the change:
20240923-220004-zhewang-0a9705842327e11e           compressed=True data_size=35146791 duration=3279293 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:38:59 sanity=False started=100000 stopped=20240923-223903 submitted=20240923-220004 timeout=5400 username=zhewang

[Release-7.3] Reduce workload of MutationLogReaderCorrectness

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/DDShardTracker.actor.cpp
fdbserver/DDTeamCollection.actor.cpp

This PR validates an invariant after buildTeam: if latest buildTeam succeeds, then each server must have at least targetTeamNumPerServer serverTeams, where
`targetTeamNumPerServer = (SERVER_KNOBS->DESIRED_TEAMS_PER_SERVER * (configuration.storageTeamSize + 1)) / 2`
20240924-175550-zhewang-9fcd9bcbc610bd46           compressed=True data_size=35114195 duration=7341988 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:05:59 sanity=False started=100000 stopped=20240924-190149 submitted=20240924-175550 timeout=5400 username=zhewang
20240925-004837-zhewang-bc7fb58338fa24de           compressed=True data_size=35113749 duration=228037 ended=4998 fail_fast=10 max_runs=100000 pass=4998 priority=100 remaining=3:47:08 runtime=0:11:57 …

[Release-7.3] Validate ServerTeam count per server in simulation

---

fdbclient/ServerKnobs.cpp

cherry-pick of #11683
Increasing minimum age to wiggle to avoid re-wiggling migrated rocksdb storage servers during storage migration.
Currently, rocksdb region migration takes between 20-30 days. The StorageServers which are already migrated are getting re-wiggled. To avoid that, the minimum age to wiggle is increased to 35 days.

Increasing minimum age to wiggle to avoid re-wiggling migrated rocksdb storage servers.

---

design/transaction-state-store.md
fdbclient/ReadYourWrites.actor.cpp
fdbclient/include/fdbclient/FDBTypes.h
fdbserver/LogSystem.cpp
fdbserver/MutationTracking.cpp
fdbserver/StorageCache.actor.cpp
fdbserver/TagPartitionedLogSystem.actor.cpp
fdbserver/storageserver.actor.cpp

This tag is used for FDB 6.1 and is no longer needed now.
20240926-235242-jzhou-7ed3304c415ae65e             compressed=True data_size=34265556 duration=7364570 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:42:23 sanity=False started=100000 stopped=20240927-003505 submitted=20240926-235242 timeout=5400 username=jzhou

Remove the usage of txsTag

---

bindings/bindingtester/tests/test_util.py

Fixes issue causing binding tester to throw error ('float' object cannot be interpreted as an integer) when using certain Python versions (encountered with 3.12.6).

Explicitly type 1e3 as int

---

fdbserver/include/fdbserver/TLogInterface.h

Address a serialization issue that was causing a log server crash during a patch upgrade: any fields/members added (to a message) in a patch release should be serialized after the existing fields/members, and not in between them.
Testing:
Joshua job: 20241001-200314-sre-66f14df1e2a4d802 (no failures)

Address a serialization issue that is blocking a patch upgrade

---

fdbserver/workloads/ClogTlog.actor.cpp

For some seeds, I found out that the `ClogTlog` test was timing out for force exclude use-case. The reason behind timeout was that when we decide to exclude, dbInfo can still keep changing and timeout value is reset every time. This meant that the test never triggered exclude. 
The fix is simply to not reset the timeout on dbInfo changes. For success, we still rely on dbInfo to reach `>= RecoveryState::ACCEPTING_COMMITS` as before. 
Ran 100K Joshua with only ClogTlog: `20240930-235558-praza-5a534ad91caaaf40` …

[fdbserver][sim] Remove timeout reset in ClogTlog test

---

fdbserver/include/fdbserver/TLogInterface.h

Address another log interface related incompatibility issue between patch releases 7.3.43 and 7.3.53.
Testing:
- Joshua job: 20241009-165019-sre-acfb3b9fb88dc679 (no failures)
- Operator upgrade test https://github.com/FoundationDB/fdb-kubernetes-operator/blob/45fe4ccdfe5509b5ef1f02301947e64de7ab41d1/e2e/test_operator_upgrades_variations/operator_upgrades_variations_test.go#L174 (ran successfully)

Address another protocol incompatibility issue between patch releases 7.3.43 and 7.3.53

---

fdbclient/ServerKnobs.cpp
fdbserver/KeyValueStoreShardedRocksDB.actor.cpp

[release-7.3] Use a single iterator pool for all physical shards. 

---

fdbclient/ServerKnobs.cpp
fdbserver/KeyValueStoreShardedRocksDB.actor.cpp

Use a single iterator pool for all physical shards.

---

fdbclient/include/fdbclient/IKeyValueStore.actor.h
fdbserver/CommitProxyServer.actor.cpp
fdbserver/KeyValueStoreMemory.actor.cpp

In version vector, during commits, all tags in the batch must be known by the post resolution phase. This contract was violated in a special case immediately after `KeyValueStoreMemory` is constructed. During this phase, `KeyValueStoreMemory` will snapshot its data, even though no metadata mutations were done, and hence no transaction tags included in the batch. This phase is denoted by boolean `KeyValueStoreMemory::replaceContent`. The PR checks for that case to ensure the snapshot is sent to all logs. …

fix bug TxnStateStoreCycleTest for version vector

---

fdbserver/storageserver.actor.cpp

Requests to the storage server validate the version calculated by `waitForVersion()`, not the one in the request. This rule was not followed in `getMappedKeyValuesQ()`, as it was elsewhere (`getKeyValuesQ()`, `getValueQ`, `getKeyValuesStreamQ()`, etc.), leading to an assert in `checkTenantEntry()`.

check correct version in getMappedKeyValuesQ

---

fdbserver/TLogServer.actor.cpp

Remove an assertion (that validates prevVersion in the proxy to log server commit message) that is causing version incompatibility between 7.3.43 and 7.3.53 patch releases. The assertion can fail, even on a valid commit message, when the proxy and the log server are running on 7.3.43 and 7.3.53 patch release versions.
Testing:
Joshua job: 20241025-201225-sre-667b90991a0a5f57 (had a failure in "ReadSkewReadWrite.toml" test with RocksDB storage engine). 20241025-212258-sre-667b90991a0a5f57 (no failures).
Operator upgrade and downgrade tests: Ran the tests over image "7.3.54-sre-dev" (that's built over this PR's commit) and the tests succeeded (note: ran the downgrade test five times). …

Address another patch release version incompatibility issue

---

fdbserver/tester.actor.cpp
flow/include/flow/error_definitions.h

1. As part of a different PR, I found an issue in urgent consistency checker where because of its handling of duplicate tester requests, the tester recruitment endpoint was marked as permanently failed. This means that subsequent phases e.g. consistency check were stuck since that phase relies to get interfaces for _all_ testers. To fix this, I changed the duplicate request handling in urgent consistency checker to be more explicit: the tester server drops the requests and explicitly sends a duplicate error back to the client. This way, the endpoint is not marked as permanently failed since no promise was broken.
2. After the change in (1), the urgent consistency checker itself started becoming stuck for some tests. After debugging, it was because the shards/batch mapping to tester ids …

Urgent consistency checker fixes

---

fdbserver/include/fdbserver/StorageServerUtils.h

Found by Valgrind nightly
| Test File                                           |       Seed |   Buggify |
|-----------------------------------------------------|------------|-----------|
| slow/ParallelRestoreNewBackupWriteDuringReadAtomicRestore.toml| 4164037972 |         1 |
| fast/MoveKeysCycle.toml                             |  642705924 |         0 |
| fast/BulkLoading.toml                               |  608748010 |         0 |

Fix valgrind errors of uninitialised values

---

fdbserver/tester.actor.cpp
flow/include/flow/error_definitions.h

Cherry-pick https://github.com/apple/foundationdb/pull/11734
100K Joshua: 
`20241026-053950-praza-7c7c473d844efeb1ab1456d244e56d60356e7e compressed=True data_size=34263733 fail_fast=10 max_runs=100000 priority=100 sanity=False submitted=20241026-053950 timeout=5400 username=praza-7c7c473d844efeb1ab1456d244e56d60356e7ed5`

Urgent consistency checker fixes (cherrypick 7.3)

---

fdbclient/ServerKnobs.cpp

Max range deletions knob update to prevent OOMs.

Max range deletions knob update to prevent OOMs.

---

fdbclient/ManagementAPI.actor.cpp
fdbclient/SystemData.cpp
fdbclient/include/fdbclient/ManagementAPI.actor.h
fdbclient/include/fdbclient/RangeLock.h
fdbclient/include/fdbclient/SystemData.h
fdbserver/ApplyMetadataMutation.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/MoveKeys.actor.cpp
fdbserver/include/fdbserver/ProxyCommitData.actor.h
fdbserver/storageserver.actor.cpp
fdbserver/workloads/BulkLoading.actor.cpp
fdbserver/workloads/ConflictRange.actor.cpp
fdbserver/workloads/ReportConflictingKeys.actor.cpp
tests/fast/BulkLoading.toml

- Refactor and simplify BulkLoad test workload;
- Use RangeLock in BulkLoad tasks: when users trigger a bulk load task and stop the task on a range, lock/unlock the range atomically;
- Add background write traffic in BulkLoad workload to test if RangeLock and BulkLoad work well together.
20241031-000646-zhewang-a87ec67a142a93ba           compressed=True data_size=36813144 fail_fast=10 max_runs=100000 priority=100 sanity=False submitted=20241031-000646 timeout=5400 username=zhewang …

BulkLoading Use RangeLock

---

fdbserver/CommitProxyServer.actor.cpp
fdbserver/include/fdbserver/ProxyCommitData.actor.h
fdbserver/workloads/RandomRangeLock.actor.cpp
tests/fast/RangeLockCycle.toml
tests/fast/RangeLocking.toml

disable version vector with range lock tests.
while developing the feature, we can set three switches to be sure it is disabled.
TODO Range Locking to work with version vector.

disable version vector with range lock tests

---

fdbserver/LogSystemPeekCursor.actor.cpp
fdbserver/TLogServer.actor.cpp
fdbserver/TagPartitionedLogSystem.actor.cpp
fdbserver/include/fdbserver/TLogInterface.h

An [earlier PR](https://github.com/apple/foundationdb/pull/11677) added `end` as a parameter to Peek requests. This is used in version vector unicast recovery to indicate the final version to be recovered. It has to be set for streaming peek as well; when `PEEK_USING_STREAMING` is set, the tLog will use the feature to retrieve data from old tlogs on recovery.
Joshua `20241030-161218-dlambrig-d0ef240536265fd1`

fix vv unicast recovery for streaming peek.

---

fdbserver/AccumulativeChecksumUtil.cpp
fdbserver/CommitProxyServer.actor.cpp
fdbserver/storageserver.actor.cpp

When SS persists accumulative checksum value, each acsIndex has exactly one value. Do not persist the value by epoch. 
20241104-192732-zhewang-c7ae1f5843aa7835           compressed=True data_size=36888178 duration=6140327 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:14:52 sanity=False started=100000 stopped=20241104-204224 submitted=20241104-192732 timeout=5400 username=zhewang

Fix accumulative checksum

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/ClusterController.actor.cpp

In gray failure, processes complain about each other. There are scenarios where multiple workers complain about a bad process to CC, but at the same time, that bad process also complains about those workers. In such cases, gray failure algorithm in CC goes by unique complainer count, so workers complaining against bad process would win, recovery would be triggered in which bad process will not be recruited again because it would have been added to an excluded list. 
However, in the example above, there could be another subsequent recovery (or theoretically, multiple recoveries) because of the original complaints from the bad process. This PR fixes that by immediately invalidating the complaints from bad process (or multiple bad processes) when it's added to exclude list and recovery is …

Invalidate gray failure complaints from excluded processes

---

fdbserver/include/fdbserver/ProxyCommitData.actor.h
tests/fast/RangeLockCycle.toml
tests/fast/RangeLocking.toml

Do not check for PROXY_USE_RESOLVER_PRIVATE_MUTATIONS in rangeLockEnabled
Joshua with `PROXY_USE_RESOLVER_PRIVATE_MUTATIONS` enabled and `ENABLE_READ_LOCK_ON_RANGE` 
disabled:
`20241104-211756-dlambrig-a5cb3b9fac7ed2ca` 
with `ENABLE_READ_LOCK_ON_RANGE` and `PROXY_USE_RESOLVER_PRIVATE_MUTATIONS` enabled:
`20241104-231600-dlambrig-bfad63339bc07b5e`

Do not check for PROXY_USE_RESOLVER_PRIVATE_MUTATIONS in rangeLockEnabled

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/include/fdbserver/WorkerInterface.actor.h
fdbserver/worker.actor.cpp
fdbserver/workloads/ClogRemoteTLog.actor.cpp
tests/rare/ClogRemoteTLog.toml

There are two main changes:
1. This PR lets storage servers, both in primary and/or remote DCs, to complain about workers in the txn subsystem. For example, if a remote tlog is degraded (e.g. network issue), remote storage servers to which this tlog is a buddy of, can report the tlog to CC. This gives an opportunity for CC and gray failure to then exclude this degraded tlog and trigger recovery. This is especially useful in pathological network failure modes e.g. tlog's network link to SS is degraded, but to log router is fine. In this scenario, log routers won't complain about this tlog, and this tlog will remain degraded and exist in the cluster. This PR fixes that problem.
2. The existing remote tlog simulation test is improved in different ways. The test now _always_ checks that it …

Gray failure allows storage servers to complain

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/DDRelocationQueue.actor.cpp
fdbserver/DDShardTracker.actor.cpp
fdbserver/DDTeamCollection.actor.cpp
fdbserver/include/fdbserver/DataDistributionTeam.h

100K correctness tests: 
20241105-190136-zhewang-a29ead6a3bc35486           compressed=True data_size=36894452 duration=5528198 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:10:07 sanity=False started=100000 stopped=20241105-201143 submitted=20241105-190136 timeout=5400 username=zhewang

Cherrypick recent DD changes from release-7.3

---

fdbclient/ServerKnobs.cpp
fdbserver/worker.actor.cpp

Addressed feedback in #11753
100K Joshua: `20241106-011613-praza-bb0025a30daeea25e4bf77797b6995e3eae366 compressed=True data_size=36041626 duration=5281330 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:38:18 sanity=False started=100000 stopped=20241106-025431 submitted=20241106-011613 timeout=5400 username=praza-bb0025a30daeea25e4bf77797b6995e3eae36605`. The failure does not seem related to my change. 

Address feedback in PR #11753

---

tests/fast/BulkLoading.toml

Do not test bulk loading and version vector simultaneously
tested with proxy_use_resolver_private_mutations enabled
`20241106-165853-dlambrig-01fee3d240275ced`

Do not test bulk loading and version vector simultaneously

---

fdbserver/workloads/BulkLoading.actor.cpp

Reduce bulkload workload size to mitigate trace too many events and external timeout.
100K bulk loading tests:
20241107-221205-zhewang-b8e3c370da084c29

Reduce Bulkload Workload Size

---

fdbserver/SimulatedCluster.actor.cpp

Do not choose `two_satellite_fast` in simulation tests when version vector unitcast is enabled. This configuration sets `antiQuorum` to 2, because only one out of two satellites need reply before commit. The unicast recovery does not yet work with the quorum feature.
Joshua
`20241108-181740-dlambrig-fb666c04e0900aff `

Do not choose two_satellite_fast in simulation tests with version vector

---

fdbserver/fdbserver.actor.cpp
flow/Knobs.cpp

For both cases, the root cause is that `deterministicRandom` is called before rng is setup based on cli provided seed (in `setThreadLocalDeterministicRandomSeed`). Below are brief descriptions of the issues and their fixes.
1. `SIM_CONNECT_ERROR_MODE` used `deterministicRandom` unconditionally unlike other knobs in the file guarded by `randomize && BUGGIFY`. Fix is to do the same for `SIM_CONNECT_ERROR_MODE`. Picked 0 as the default value based on usage. 
2. The call stack `fdbserver main -> parseArgsInternal -> machineId = getSharedMemoryMachineId() -> newUID = deterministicRandom()->randomUniqueID()` runs _before_ `setThreadLocalDeterministicRandomSeed` is called in fdbserver main. This meant that `machineId` was different across runs with the same seed. Unfortunately, the random seed …

Fix two cases of non-determinism in simulation

---

cmake/CompileBoost.cmake
flow/include/flow/FastAlloc.h

This fixes https://github.com/apple/foundationdb/issues/10813
There are multiple problems:
- The boost 1.78 doesn't work well with ASAN build, which was fixed in later versions
- The compiling missed "context-impl=ucontext" flag for b2 command
- missing /usr/local/include/c++/v1/__config_site in the developer environment
I didn't make boost 1.86 as the default for normal build, because of issues in developer environment. We can make the change after developer environment is fixed.
I ran ctest and the problem from #10813 is gone, but the test failed for other errors, i.e., memory leaks, which can be investigated/fixed in a separate PR. …

Fix ASAN build errors

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/ClusterController.actor.cpp
fdbserver/DDRelocationQueue.actor.cpp
fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
tests/fast/BulkLoading.toml

Observed three causes of TraceTooManyEvents error in BulkLoading tests:
1. `RefreshIterators` trace event pops very frequently;
2. CC repeatedly creates a new DD throughout the test (very rare, investigating..);
3. QuietDatabaseStartFail keeps happening (very rare, investigating..).
Observed that physical shard move (BulkLoad replies on PhysicalShardMove) can cause external timeout. One interesting thing here is that we didn't see this external timeout error in the bulkLoading test before the last BulkLoading relevant PR. So, there might be some change recently causing the issue, e.g. new RocksDB binary (rare, investigating..).
This PR:
1. Avoid frequently popping `RefreshIterators` trace event;
2. Add some trace event for debugging;
3. Introduce a knob …

Improve BulkLoading Simulation Test

---

fdbserver/TagPartitionedLogSystem.actor.cpp

Otherwise the trace event will not be shown when filtering with the debug ID. Once the changes are merged I can create a PR for release 7.1 and 7.3.

Add log system debug ID to trace event

---

documentation/sphinx/source/mr-status-json-schemas.rst.inc
fdbclient/Schemas.cpp
fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/ClusterController.actor.cpp
fdbserver/Status.actor.cpp
fdbserver/include/fdbserver/ClusterController.actor.h
fdbserver/include/fdbserver/Status.actor.h
fdbserver/workloads/ClogRemoteTLog.actor.cpp

Under a server side (specifically, cluster controller) knob, status json now returns data about gray failure. Something like this is shown:
This is under the `cluster` section of status json. 
If there are no excluded processes, we still display empty section to communicate _absence_ of excluded processes.
The definition of exclusion here is based on whatever gray failure algorithm decides. These are the same processes based on which recovery is triggered. 
The definition of time is whenever the process was _most recently_ or _last_ excluded by gray failure. The unit of time is the same as whatever `now()` returns.
The intent behind exposing this information in a machine readable way is that components like FDB's Kubernetes operator can leverage it and potentially make host/pod level …

Gray failure machine readable status

---

packaging/docker/sidecar.py

The lack of return is causing both the 200 /check_hash/fdbmonitor.conf and 404 Path not found to be printed in the logs of the sidecar

Do not print an erroneous message 404 error message when /check_hash is called

---

fdbserver/include/fdbserver/ProxyCommitData.actor.h
fdbserver/storageserver.actor.cpp

It appears there is an incompatibility between the accumulated checksum feature and the version vector feature. Disable accumulated checksum when version vector is enabled, for now.
Testing:
Joshua job (with version vector feature disabled): 20241113-231421-sre-1d33d0fe4e5a1f17 (started)

Disable accumulated checksum when version vector is enabled

---

fdbserver/fdbserver.actor.cpp

As title, was reported in https://github.com/apple/foundationdb/pull/11766#issuecomment-2475403300. The fix is to call `setThreadLocalDeterministicRandomSeed` even if the seed is not provided. Note that previously for cases where seed was not provided, simulation still worked for function calls like `deterministicRandom`. This is because those functions will lazily initialize the seed. But it does not work for calls to `debugRandom` because that assumes that seed is already setup before, which was not the case after #11766, and what is precisely what this PR fixes. `debugRandom` is currently used by tester and consistency checker. 
Ran simulation without seed and ensured no crash happens.
100K Joshua: `20241114-071804-praza-d516b91e25c11971cb9cce5336741acc83ff1d compressed=True …

Fix debugRandom() bug introduced in PR #11766 where seed is not provided via cli

---

bindings/c/foundationdb/CWorkload.h
bindings/c/foundationdb/CppWorkload.h
bindings/c/test/workloads/CWorkload.c
bindings/c/test/workloads/RustWorkload/Cargo.toml
bindings/c/test/workloads/RustWorkload/build.rs
bindings/c/test/workloads/RustWorkload/src/bindings.rs
bindings/c/test/workloads/RustWorkload/src/lib.rs
bindings/c/test/workloads/RustWorkload/src/mock.rs
bindings/c/test/workloads/SimpleWorkload.cpp
bindings/c/test/workloads/workloads.h
bindings/java/JavaWorkload.cpp
fdbserver/workloads/ExternalWorkload.actor.cpp

I'm utilizing the `ExternalWorkload` to test custom layers within the FoundationDB simulation. The layers under test are authored in Rust and are based on the [foundationdb-rs project](https://github.com/foundationdb-rs/foundationdb-rs). The workload API is defined by the C++ header file `ClientWorkload.h`. Interoperability between Rust and C++ presents challenges, although creating a C++ to C shim was relatively straightforward. My main concern is the unstable ABI of the C++ API, as it relies on the compiler, linker, and system libraries. This proved to be an issue when transitioning from version 7.1 to 7.3, where the workload I was using suddenly broke due to a change in the representation of the `std::string` class as the fdbserver switched from gcc to clang, as detailed in [this forum …

C workload bindings

---

tests/fast/CacheTest.toml

Recently, shardedrocks experiences external timeout with cache test.
Temporarily turn off shardedrocks in this test until we fix the issue.

Turn off shardedrock in cache test

---

fdbclient/StatusClient.actor.cpp
fdbclient/include/fdbclient/Status.h
fdbserver/workloads/ClogRemoteTLog.actor.cpp

In #11758, I added capability to include gray failure information in machine readable status. To test this, I modified ClogRemoteTLog simulation test to also fetch status json, and assert that relevant fields are present. 100K passed. However, as we run simulation more, there are cases where the assert I added fails. The reason is that it's normal for status json to sometimes fail outside of gray failure check e.g. network issue between client and CC. This PR makes the test more resilient by accounting for these errors. 
There are two changes:
1. The first commit is a pure refactor of StatusClient such that there should be no functionality change. The refactor introduces a hash map of message enum type to message name. 
2. The second commit modifies the check to reuse this map to skip the …

Make ClogRemoteTLog more resilient and refactor StatusClient

---

cmake/FDBComponents.cmake

Fixed cmake 3.31 arm (https://github.com/FoundationDB/fdb-build-support/pull/82) build error:
```
CMake Error at /usr/local/share/cmake-3.31/Modules/FindOpenSSL.cmake:186 (set_property):
The link interface of target "OpenSSL::Crypto" contains:
ZLIB::ZLIB
but the target was not found.  Possible reasons include:
* There is a typo in the target name.
* A find_package call is missing for an IMPORTED target.
* An ALIAS target is missing.
Call Stack (most recent call first):
/usr/local/share/cmake-3.31/Modules/FindOpenSSL.cmake:733 (_OpenSSL_target_add_dependencies)
cmake/FDBComponents.cmake:35 (find_package)
CMakeLists.txt:72 (include)
``` …

Fix ZLIB not found error

---

bindings/go/CMakeLists.txt
bindings/go/src/fdb/database.go
bindings/go/src/fdb/errors_test.go

When user wraps a FoundationDB error in their transaction function, the `retryable()` logic will always reset it back to a FoundationDB error, without any wrapping.
This change makes sure that original error is preserved, unless `fdb_transaction_on_error()` returned a different error or error code.
NOTE: `fdb_transaction_on_error()` does not currently ever return a different error than original, so the new logic is being defensive for future changes

Go binding: do not override wrapped transaction error

---

fdbmonitor/fdbmonitor.cpp

Fixes: https://github.com/apple/foundationdb/issues/11775
Testing: https://github.com/apple/foundationdb/pull/11802#pullrequestreview-2457666840

Only delay the restart of fdbserver if the process exited with an exit code other than 0

---

fdbmonitor/fdbmonitor.cpp

https://github.com/apple/foundationdb/pull/11802 for release-7.3 (I'm not cherry picking this change for 7.1).

[RELEASE-7.3] Only delay the restart of fdbserver if the process exited with an exit code other than 0

---

fdbserver/TagPartitionedLogSystem.actor.cpp

Modify the unicast-based recovery version computation algorithm the following ways:
- Make it use "max(KCV)", instead of "min(KCV)", as the default recovery version (details below)
- Make it return the <max(KCV), recovery version> pair as output
- Make the invoker use the "max(KCV)" version returned by the algorithm
- Address a bug related to the computation of recovery version (in the case where a subset of log servers have empty "unknownCommittedVersions" list)
And, make the invoker compute the max() and min() of recovery versions of primary and satellite DCs based on the recovery versions computed by the appropriate (with/without unicast) recovery version computation algorithms.
Testing:
Joshua job (with version vector feature disabled): 20241111-215149-sre-3f2cb6906ac4ea16 (no …

Improvements to the unicast-based recovery version computation algorithm

---

bindings/c/CMakeLists.txt
bindings/c/external_workload.map
bindings/c/foundationdb/CppWorkload.h
bindings/c/test/workloads/CWorkload.c
bindings/c/test/workloads/RustWorkload/README.md
bindings/c/test/workloads/RustWorkload/src/bindings.rs
bindings/c/test/workloads/RustWorkload/src/lib.rs
bindings/c/test/workloads/RustWorkload/src/mock.rs
bindings/c/test/workloads/RustWorkload/test_file.toml
bindings/java/src/main/com/apple/foundationdb/testing/PerfMetric.java
tests/SimpleExternalTest.txt

Follow up to #11288.
As you asked @spraza I added a README to the Rust crate and fixed the `format_code` in the C++ (and java) bindings.
I also added the corresponding `test_file.toml`, ran the Rust formatter, refactored some small parts, and updated some doc strings.

Rust external workload modifications

---

tests/loopback_cluster/run_custom_cluster.sh

Bug introduced by recent refactor adding being able to specify storage as an option.
Was inserting the empty string -- i.e. '' -- when no knob option was empty. Instead
insert nothing.
This link is good on the issue: https://unix.stackexchange.com/questions/415990/how-can-i-expand-a-quoted-variable-to-nothing-if-its-empty
Found by @spraza

Fix 'ERROR: unknown option: `'' when no options supplied.

---

fdbclient/tests/seaweedfs_fixture.sh

Seaweed is started in a subprocess so setting the global had no effect. Instead write the pid to a file so its available at cleanup time.
Found by Zhe Wang.

Seaweed process was not getting cleaned up after test.

---

fdbserver/TLogServer.actor.cpp

In case of spill by reference, log servers should use the logic that is based over "TagData::popped" to decide how long to keep the disk queue positions of versions in memory (instead of using the logic that is based over "LogData::persistentDataVersion", which is applicable to spill by value case).
NOTE: I found this issue while investigating a related issue in the context of version vector, so don't have a specific simulation test that showed this issue.
Testing:
Joshua id (with version vector disabled): 20241205-225451-sre-0bf0e246ccc69b55 (a failure in "LargeApiCorrectnessStatus.toml", with sharded RocksDB engine).
Please check each of the following things …

An issue related to maintaining the disk queue positions of versions (in memory) in case of spill by reference

---

bindings/c/CMakeLists.txt
cmake/AddFdbTest.cmake
fdbcli/CMakeLists.txt

Mostly are unused and noisy tests, `single_process_external_client_fdbcli_tests` complains memory leak, which is a TODO item.

Ignore some ctests for ASAN

---

fdbserver/workloads/ClogRemoteTLog.actor.cpp

On both Apple clang (M2) version 15.0.0 (clang-1500.1.0.2.5) and 16.0.0, compile fails here:
/Users/stack/checkouts/fdb/foundationdb/fdbserver/workloads/ClogRemoteTLog.actor.cpp:254:67: error: invalid operands to binary expression ('Standalone<StringRef>' and 'Optional<Standalone<StringRef>>')
if (ssi.locality.dcId().present() && ssi.locality.dcId().get() == g_simulator->remoteDcId)

error: invalid operands to binary expression in ClogRemoteTLog.actor.cpp on appleclang

---

bindings/c/CMakeLists.txt
bindings/c/test/fdb_api.hpp
cmake/ConfigureCompiler.cmake
fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
fdbserver/worker.actor.cpp

Found with clang 19 compiling the code.
For mako, the problem is that
`std::char_traits<T>` is being [deprecated](https://github.com/jtv/libpqxx/issues/738) for types other than char, wchar_t, char8_t, char16_t, and char32_t. So code `using ByteString = std::basic_string<uint8_t>;` causes compiling errors:
```
In file included from /root/foundationdb/bindings/c/test/fdb_api.hpp:34:
/usr/local/bin/../include/c++/v1/string:820:42: error: implicit instantiation of undefined template 'std::char_traits<unsigned char>'
820 |   static_assert(is_same<_CharT, typename traits_type::char_type>::value,
|                                          ^
/root/foundationdb/bindings/c/test/fdb_api.hpp:58:6: note: in instantiation of template class 'std::basic_string<unsigned char>' requested here
58 | …
```

Fix issues with clang 19

---

bindings/java/CMakeLists.txt

Clang19 doesn't like missing symbols
A followup for #11834 

Fix java lib missing symbols issue

---

fdbserver/KeyValueStoreMemory.actor.cpp
fdbserver/TransactionStoreMutationTracking.cpp
fdbserver/include/fdbserver/TransactionStoreMutationTracking.h

Add transaction store mutation tracking capability. This works similar to normal mutation tracking. The first iteration of the feature does not support encryption.

Add transaction store mutation tracking capability

---

fdbserver/workloads/ClogRemoteTLog.actor.cpp
tests/rare/ClogRemoteTLog.toml

When writing the gray failure simulation test, I make sure that the test goes through a series of phases by doing an invariant check in the `check` phase of the test. I made the incorrect assumption that `check` failures would result in Joshua failures too, but that is not true. To count check failures as Joshua failures, this PR makes it so that the test emits a severity 40 error if `check` failed. When I did that, I got Joshua failures because the test needed more tuning. This PR tunes the test to ensure Joshua passes now, meaning that `check` is also passing. There are a bunch of tunings I had to do, mostly because these got compounded as `check` failures were getting masked over time. 
100K Joshua: `20241216-033032-praza-81a7cd863636dbf9c9020ba8b6a74e88d204d7 compressed=True …

Make ClogRemoteTlog pass when check failures count as Joshua failures

---

fdbcli/ExcludeCommand.actor.cpp
fdbclient/SpecialKeySpace.actor.cpp

Restructure some of the exclusion code to reduce the requests that are made by locality-based exclusions and make sure we fetch the information only once. Under normal circumstances the additional work is not critical but in some cases when the cluster is under heavy load or a set of workers is slow in responding, the additional work can prevent that locality-baed exclusions work (but the IP:port based exclusions work).
I made the PR against 7.1 as I was testing against a 7.1 cluster. Once the changes look good I'll create a PR for main and 7.3 (and make sure we merge the PR for the main branch first). …

[RELEASE-7.1] Refactor locality-based exclusion checks to reduce additional overhead

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/include/fdbserver/ClusterController.actor.h
tests/rare/ClogRemoteTLog.toml

In the context of gray failure, sometimes we want to only trigger recovery if the minimum number of complainers is greater or equal to a configurable value (lower bound). An upper bound version of this functionality is already present, specifically we only trigger recovery if the number of complainers is less or equal to `CC_DEGRADED_PEER_DEGREE_TO_EXCLUDE`. This PR adds a lower bound version (`CC_DEGRADED_PEER_DEGREE_TO_EXCLUDE_MIN`).
100K: `20241217-203855-praza-2de25e1368238ed05c025adfe68b43c5a88451 compressed=True data_size=36247064 fail_fast=10 max_runs=100000 priority=100 sanity=False submitted=20241217-203855 timeout=5400 username=praza-2de25e1368238ed05c025adfe68b43c5a884518b`
Explicitly ran `fdbserver -r unittests -f /fdbserver/clustercontroller/` to run gray failure unit tests, …

Lower bound version of CC_DEGRADED_PEER_DEGREE_TO_EXCLUDE

---

fdbcli/ExcludeCommand.actor.cpp
fdbclient/SpecialKeySpace.actor.cpp

Changes from: https://github.com/apple/foundationdb/pull/11835
Restructure some of the exclusion code to reduce the requests that are made by locality-based exclusions and make sure we fetch the information only once. Under normal circumstances the additional work is not critical but in some cases when the cluster is under heavy load or a set of workers is slow in responding, the additional work can prevent that locality-baed exclusions work (but the IP:port based exclusions work).
I decided not to cherry-pick the changes as the `checkExclusion` is different between 7.1 and main.
Please check each of the following things and check *all* boxes before accepting a …

Refactor locality-based exclusion checks to reduce additional overhead

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/ClusterController.actor.cpp

Backport of #11749 to 7.3. This helps reduce the number of false positive recoveries caused by gray failure. 
100K Joshua: `20241220-220204-praza-ca639e469878f9980f8963f2e1e18114e5d6f2 compressed=True data_size=34270926 duration=5812375 ended=100000 fail_fast=100 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:56:11 sanity=False started=100000 stopped=20241220-225815 submitted=20241220-220204 timeout=5400 username=praza-ca639e469878f9980f8963f2e1e18114e5d6f2f8`

Backport "Invalidate gray failure complaints from excluded processes" to 7.3 (#11749)

---

fdbserver/TransactionStoreMutationTracking.cpp
fdbserver/include/fdbserver/TransactionStoreMutationTracking.h

- Simplify how to define traces for point mutations to transaction state store keys. 
- Include location in trace when provided.

Refine transaction store mutation tracking

---

bindings/java/src/main/com/apple/foundationdb/tuple/ByteArrayUtil.java

As a very, very modest suggestion, it might be nice to make `ByteArrayUtil#EMPTY_BYTES` public. Many use cases ([simple indices](https://apple.github.io/foundationdb/simple-indexes.html), for example) call for empty byte arrays, and having a static zero-length array available is handy. While users can certainly manage this bit of engineering on their own, it can be nice to have a named, centrally-located instance in a utility class that's clearly associated with FoundationDB.

Make `ByteArrayUtil#EMPTY_BYTES` public

---

fdbserver/TagPartitionedLogSystem.actor.cpp

- The code was using "size()", instead of "count()", to find the number of bits set in a dynamic_bitset structure. Correct this.
Found this while going through this code in the context of another version vector recovery related issue. We can theorize that this issue could cause a version to be recovered even though not enough log servers that received this version are available during recovery.
- Comment out code that computes the recovery versions of individual log servers ("RVs") in "getRecoverVersionUnicast()" (this was a review comment in another PR). This information is not currently used, but we may use this information to do error checking later.
Testing:
Joshua job id (with version vector disabled): 20250102-101000-sre-8b17f3a3070c548a (in progress). …

A bug in the code that computes the (version vector) recovery version

---

cmake/CompileBoost.cmake

See https://github.com/boostorg/boost/issues/996

Fix boost URL

---

cmake/AddFdbTest.cmake

Something changed and `bindingtester` was trying to build before the Python bindings. Turns out there's no dependency between them.

Fix missing `bindingtester` dependency

---

fdbclient/ClientKnobs.cpp
fdbclient/S3BlobStore.actor.cpp
fdbclient/S3Client.actor.cpp
fdbclient/S3Client_cli.actor.cpp
fdbclient/include/fdbclient/ClientKnobs.h
fdbclient/include/fdbclient/S3BlobStore.h
fdbclient/include/fdbclient/S3Client.actor.h
fdbclient/tests/s3client_test.sh

* fdbclient/ClientKnobs.cpp
* fdbclient/include/fdbclient/ClientKnobs.h Add knob BLOBSTORE_ENABLE_ETAG_ON_GET
* fdbclient/S3BlobStore.actor.cpp Optionally check etag (md5) volunteered by s3 against the content we have downloaded and fail if not equal (TODO: check the checksum after we've saved the content to the filesystem --  would require  good bit of a refactoring).
* fdbclient/S3Client.actor.cpp Add deleteResource support.
* fdbclient/S3Client_cli.actor.cpp Add COMMAND support; currently either 'cp' or 'rm'. Set the knob blobstore_enable_etag_on_get to true by default for s3client.
* fdbclient/tests/s3client_test.sh Add clean up of resources written up to s3 at end of test. (Awkward in bash)
The general pull request guidelines can be …

Add checksum checking of downloads. Add cleanup of test data.

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/include/fdbserver/ClusterController.actor.h

Backport of #11840. This helps reduce the number of false positive recoveries triggered by gray failure. 
Note that the test in  #11840 (`ClogRemoteTlog.toml`) is not present in this PR. That's because that test relies on new gray failure features not present in 7.3. For this specific change, the knob default (1) should not change any functional behavior. Increasing the knob to higher values like 2 would lead to less number of false positive recoveries. 
100K Joshua: `20241223-232125-praza-9946e5e869ace5bdb8486d4740934346fbc113 compressed=True data_size=34271818 duration=6215497 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:00:07 sanity=False started=100000 stopped=20241224-002132 submitted=20241223-232125 timeout=5400 …

Lower bound version of CC_DEGRADED_PEER_DEGREE_TO_EXCLUDE (#11840)

---

packaging/docker/sidecar.py
packaging/docker/sidecar_test.py

Ran the unit tests:
```bash
$ python3 sidecar_test.py
...........
----------------------------------------------------------------------
Ran 11 tests in 0.048s
OK
```
I tried to setup a test for the new code but it seems like doing directly a request against the mocked server doesn't work as the relative path is resolved by the server before passing the path into the methods. So I ended up building dedicated tests for new methods.

Check the requested path in the fdb Kubernetes sidecar

---

fdbkubernetesmonitor/main.go

I think it's better to listen to the signals instead of ignoring it and just block the whole time. This should improve the interactions with the sidecar when the pod is shutdown.

Block until a signal is received in sidecar mode

---

documentation/sphinx/source/release-notes/release-notes-710.rst
fdbclient/SpecialKeySpace.actor.cpp

Adding feedback from https://github.com/apple/foundationdb/pull/11835#pullrequestreview-2512909787. I also added the release notes to be able to cut a new release with the fix.

[RELEASE-7.1] Add release notes and update exclusion logic with feedback

---

documentation/sphinx/source/backups.rst
fdbclient/S3Client_cli.actor.cpp

Clarifying documentation on blob backup URL and credentials file.
* documentation/sphinx/source/backups.rst
Minor edit. Add more examples making it clearer how to do S3
backup URLs in particular. Explain the 'trick' for omitting
api_key, secret, and token from URL instead picking them up from
the credentials file.
* fdbclient/S3Client_cli.actor.cpp
Minor cleanup of usage.

Documentation says backup blob URL can optionally contain key/secret/token

---

fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/ClusterController.actor.cpp

Extend gray failure recentHealthTriggeredRecoveryTime state to reflect any recovery, including non-gray failure triggered ones. This helps reduce number of false positive gray failure recoveries.
Let's take an example. `CC_MAX_HEALTH_RECOVERY_COUNT` is 1 and `CC_TRACKING_HEALTH_RECOVERY_INTERVAL` is 120.
Previously, gray failure will trigger another recovery after a non-gray failure recovery regardless of the knob values above.
Now, the knobs account for non-gray failure recoveries as well. So in this example, gray failure will not trigger another recovery after non-gray failure recovery for atleast 2 minutes. After 2 minutes, if complaints have not expired and workers have not recovered, gray failure can decide to trigger a recovery. 
Once accepted, will also create a backport PR for …

Extend gray failure recentHealthTriggeredRecoveryTime to reflect any recovery trigger

---

fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/ClusterController.actor.cpp

Cherry pick https://github.com/apple/foundationdb/pull/11877 to 7.3 branch. 
100K: `20250114-220152-praza-6a4ba01ddd74f594f8c642ed156b604e2c002e compressed=True data_size=34270149 duration=5144969 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:05:16 sanity=False started=100000 stopped=20250114-230708 submitted=20250114-220152 timeout=5400 username=praza-6a4ba01ddd74f594f8c642ed156b604e2c002e0e`

Extend gray failure recentHealthTriggeredRecoveryTime to reflect any recovery trigger (cherrypick 7.3)

---

contrib/SimpleOpt/include/SimpleOpt/SimpleOpt.h
fdbbackup/tests/s3_backup_test.sh
fdbclient/ClientKnobs.cpp
fdbclient/S3BlobStore.actor.cpp
fdbclient/S3Client.actor.cpp
fdbclient/S3Client_cli.actor.cpp
fdbclient/include/fdbclient/ClientKnobs.h
fdbclient/include/fdbclient/S3BlobStore.h
fdbclient/include/fdbclient/S3Client.actor.h
fdbclient/tests/aws_fixture.sh
fdbclient/tests/bulkload_test.sh
fdbclient/tests/fdb_cluster_fixture.sh
fdbclient/tests/s3client_test.sh
fdbclient/tests/seaweedfs_fixture.sh
fdbclient/tests/tests_common.sh

The s3client ctest will now use s3 directly if available (oketeto). The bulkdump ctest is yet to be converted (need
to do work internally to fdbserver so it can talk to S3 first -- a subsequent PR).
Also fix the object integrity check; original approach doesn't work when serverside encryption is enabled (awz:kms).
* contrib/SimpleOpt/include/SimpleOpt/SimpleOpt.h Address sanitizer was complaining about how SimpleOpt manipulates the array of options. While memcpy inside a buffer is 'odd', it seems fine. Its old code. Leaving it.
* fdbbackup/tests/s3_backup_test.sh Pass in weed_dir rather than rely on fixture global (the latter didn't work).
* fdbclient/ClientKnobs.cpp
* fdbclient/include/fdbclient/ClientKnobs.h
* fdbclient/include/fdbclient/S3BlobStore.h Add a knob to ask for object …

Have ctests use s3 if it is available.

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/TLogServer.actor.cpp

While debugging version vector, it is useful to enable/disable peek changes using a knob. Default to disabled.

Add ENABLE_VERSION_VECTOR_REPLY_RECOVERY switch

---

bindings/go/src/fdb/database.go
bindings/go/src/fdb/fdb_test.go
documentation/sphinx/source/api-c.rst

Add `GetClientStatus` method to `Database`.
Allow fetching client status JSON information for any database.
Added a test to make sure that it works with an open database.
By looking in `fdbclient/MultiVersionTransaction.actor.cpp` I found out that `fdb_database_get_client_status()` will return an empty string when the db is invalid; I will document this in this same PR.
Related: #11621

Go binding: add GetClientStatus method to Database

---

fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
fdbserver/MoveKeys.actor.cpp

In https://github.com/apple/foundationdb/pull/11841, sharded rocks was made deterministic in simulation except for code paths where we create checkpoint metadata and process it. As a result, the noUnseed flag was conditionally set to true when checkpoint is created (before, it was set to true always for sharded rocks storage engine). However, checkpoint creation at a high level follows these code paths:
1. DD and moveKeys creates the CheckpointMetadata request. 
2. Storage server processes this request and takes action by calling IKeyValue implementation for sharded rocks. 
I set noUnseed=true at (1) above but the problem is that for non sharded rocks storage engine, we can still determine that we need to create checkpoints and then create CheckpointMetadata request. It's only at the …

Fix the scope of sharded rocks checkpoint determinism flag

---

fdbclient/ServerKnobs.cpp
fdbserver/KeyValueStoreRocksDB.actor.cpp

Rocksdb manual flush code changes.
cherry-pick of #11849 

Rocksdb manual flush code changes

---

fdbbackup/tests/dir_backup_test.sh
fdbbackup/tests/s3_backup_test.sh
fdbcli/BulkLoadCommand.actor.cpp
fdbclient/BulkLoading.cpp
fdbclient/S3BlobStore.actor.cpp
fdbclient/S3Client.actor.cpp
fdbclient/include/fdbclient/BulkLoading.h
fdbclient/tests/bulkload_test.sh
fdbclient/tests/fdb_cluster_fixture.sh
fdbserver/BulkLoadUtil.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/fdbserver.actor.cpp
tests/loopback_cluster/run_custom_cluster.sh

Add using s3 if available when running the bulkload ctest.
It was disabled until we made it so the SS could talk to s3
(Added by this PR). Also finish the bulkload test. It was
missing bulkload support recently.
Added passing knobs to the fdb cluster so available to the
fdbserver when it goes to talk to s3. Also added passing SS
count to start in fdb cluster.
* fdbclient/tests/fdb_cluster_fixture.sh Add ability to pass multiple knobs to fdb cluster and to specify more than just one SS.
* fdbserver/fdbserver.actor.cpp Add --blob-server option and processing of FDB_BLOB_CREDENTIALS if present (hijacked the unused, unadvertised -- blob-credentials-file).
* tests/loopback_cluster/run_custom_cluster.sh Allow passing more than just one knob.
* fdbclient/BulkLoading.cpp
* …

Enable SS upload/download to S3 (for BulkLoad)

---

fdbserver/workloads/Cycle.actor.cpp

Valgrind caught a "invalid read of size 1" issue because of the [recent cycle workload changes](https://github.com/apple/foundationdb/pull/11890/files#diff-ac00cde936baa1f06996a1d58bef8e99fea94cccec7be3f47cd4c26839c51b68R127-R189). The issue is that we return a `KeyRangeRef` so no one holds the value, and so when it's referenced, valgrind complains. 
As a result, most (all?) tests that rely on Cycle workload were failing valgrind. 
Ran valgrind again and ensured 0 instances of "invalid read of size 1".
100K correctness: `  20250124-230058-praza-923fa93d522695e134a1e4d3e9ce842de01b6c compressed=True data_size=36476956 duration=3800253 ended=100000 fail=5 fail_fast=10 max_runs=100000 pass=99995 priority=100 remaining=0 runtime=2:11:42 sanity=False started=100000 stopped=20250125-011240 …

Fix cycle test valgrind issue

---

fdbserver/workloads/Cycle.actor.cpp

Cherry-pick https://github.com/apple/foundationdb/pull/11906 to 7.3 branch.
100K correctness: ` 20250124-234338-praza-a6fafae2ad6ea434c92a663740003edbd1b26e compressed=True data_size=34272699 duration=3261773 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:25:26 sanity=False started=100000 stopped=20250125-010904 submitted=20250124-234338 timeout=5400 username=praza-a6fafae2ad6ea434c92a663740003edbd1b26e2a`

[release-7.3] Fix cycle test valgrind issue

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/DDTeamCollection.actor.cpp
fdbserver/include/fdbserver/DDTeamCollection.h

Pause storage wiggle if all SS does not have minimum available space.

Pause storage wiggle if all SS does not have minimum available space.

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/DDTeamCollection.actor.cpp
fdbserver/include/fdbserver/DDTeamCollection.h

cherry-pick of #11905
Pause store wiggle if all SS does not have minimum available space.

Pause store wiggle if all SS does not have minimum available space.

---

fdbserver/workloads/DataLossRecovery.actor.cpp
fdbserver/workloads/PhysicalShardMove.actor.cpp
fdbserver/workloads/RandomMoveKeys.actor.cpp
fdbserver/workloads/StorageServerCheckpointRestoreTest.actor.cpp

Currently, createCheckpoint can block the simulation test and causing external timeout. Disable physical shard move everywhere before fully understanding what happens to create checkpoints.
20250128-012736-zhewang-93629742b026f92b           compressed=True data_size=36751089 fail_fast=10 max_runs=100000 priority=100 sanity=False submitted=20250128-012736 timeout=5400 username=zhewang

Using knob to enable physical shard move in failure injection workloads

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/SimulatedCluster.actor.cpp

1. Turn off SHARDED_ROCKSDB_DELAY_COMPACTION_FOR_DATA_MOVE. When this knob is open the knob can significantly slow down the simulation, causing external timeout.
2. Add ENFORCE_SHARDED_ROCKSDB_SIM_IF_AVALIABLE. Set to run shardedrocksdb as much as possible.
20250130-005724-zhewang-ac78fae5876e6a6d           compressed=True data_size=36752360 duration=5233632 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:00:46 sanity=False started=100000 stopped=20250130-015810 submitted=20250130-005724 timeout=5400 username=zhewang …

Turn Off SHARDED_ROCKSDB_DELAY_COMPACTION_FOR_DATA_MOVE in Simulation

---

fdbserver/workloads/ChangeConfig.actor.cpp

When a simulation starts, we use ChangeConfig workload to setup the database configuration. If the simulated cluster needsRemote == true, the workload sets the config using g_simulator->startingDisabledConfiguration at first and then set config using self->configMode. However, since startingDisabledConfiguration and configMode share the same prefix, the workload tries to "new" the database for twice.  However, changeConfig managementAPI is failed to set the second config (suppose to be the expected final state after the workload) because the configuration has been set with the startingDisabledConfiguration. Meanwhile, the startingDisabledConfiguration sets the remote DC priority as -1. As a result, the remote DC cannot be selected to do failover. Then, the recovery gets stuck and the …

Fix double new database in ChangeConfig workLoad

---

fdbrpc/include/fdbrpc/simulator.h
fdbrpc/sim2.actor.cpp
fdbserver/tester.actor.cpp
fdbserver/workloads/GcGenerations.actor.cpp

Sometimes Cycle Setup can take a long time (`setupRange()` in BulkSetup.actor.h probably has high conflict rate, maybe need a fix in a separate PR), so we need to enable connection failures injection for clogRemoteDc() to work properly. Otherwise, assertions in generateMultipleTxnGenerations() can fire, because of no clogging, and the recovery count can go down.
100k correctness 20250206-050816-jzhou-d6d9cbed80c1e96d             compressed=True data_size=36488909 duration=5076752 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:29:32 sanity=False started=100000 stopped=20250206-063748 submitted=20250206-050816 timeout=5400 username=jzhou
100k GcGeneration tests 20250206-055005-jzhou-05f58be99772b35b             compressed=True data_size=36522282 …

Fix assertion failure in GcGenerations workload.

---

fdbserver/ClusterController.actor.cpp
fdbserver/include/fdbserver/ClusterController.actor.h
fdbserver/worker.actor.cpp

For easier/faster debugging, adding more trace events to the gray failure code. Note that this spans both worker code that sends the complaints, and CC code that processes them.
For each trace event, we have to make sure that it is not too verbose. I have added comments in the PR for each trace event explaining the rationale behind the severity. Feel free to recommend changes. 
100K correctness: `20250204-081819-praza-e31fb0efda7ef69bb858b6e27322af5b622ec3 compressed=True data_size=36628836 duration=4975910 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:08:49 sanity=False started=100000 stopped=20250204-092708 submitted=20250204-081819 timeout=5400 username=praza-e31fb0efda7ef69bb858b6e27322af5b622ec387`. Only failure is in BulkLoading.toml, …

Gray failure observability

---

fdbserver/workloads/ConfigureDatabase.actor.cpp

The `ConfigureDatabase` workload used by tests like `ConfigureStorageMigrationTest.toml` issues multiple db reconfigurations, some of which can be storage engine type changes. In such cases, we rely on perpetual wiggle (driven by DD / data distributor) to eventually move all storage servers to the new storage engine type (specified in the db config). 
There are certain topologies where it's not possible for DD to migrate storage servers to the new storage engine. As an example, if the DC has just 1 SS, [DD will decide not to do perpetual wiggle because there's no room](https://github.com/apple/foundationdb/blob/06cdf2e0303a921c6a88d18e001b9d09ba589fcd/fdbserver/DDTeamCollection.actor.cpp#L2317-L2319). This was happening for some Joshua tests which were then failing the `check` phase of …

Update ConfigureDatabase workload to issue aggressive storage migration if needed

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/BulkDumpUtil.actor.cpp
fdbserver/BulkLoadUtil.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/include/fdbserver/BulkDumpUtil.actor.h
fdbserver/include/fdbserver/BulkLoadUtil.actor.h
fdbserver/storageserver.actor.cpp
fdbserver/tester.actor.cpp
tests/fast/BulkDumping.toml
tests/fast/BulkLoading.toml

This PR mainly addresses comments of PR https://github.com/apple/foundationdb/pull/11898:
1. Add comments.
2. Avoid doing fallback when a SS is failed to get the bulkLoad metadata. Here, we assume that if a datamoveId indicating this is a bulkload data move, the data move metadata should contain the bulkLoad metadata. Note that if the cluster is restarts from an old system, it is possible that the data move ID is misleading. However, when DD restarts, any data move with a bulkload id is cancelled. So, if a SS is failed to get the bulkLoad metadata, this data move is guaranteed to be cancelled. 
3. Using clearFileFolder at all places for bulkload to do folder clean up. This code cleanup is helpful in the future when we want to do this operation in background.
4. Add …

Improve BulkLoad Implementation

---

fdbserver/TagPartitionedLogSystem.actor.cpp

When version vector is enabled use "min(DV)" as the recovery version when trying to decide whether to restart recovery or not. Otherwise, we may not copy all the needed data to the log servers in the latest epoch during recovery and also the changes that we made to the cursor peek logic in the context of version vector may cause it to return incorrect results.
Testing:
- Simulation test "tests/fast/MoveKeysCycle.toml -b off -s 4070406963" fails with an assertion failure in storage server code without this change, succeeds with this change (the failure was because the "pullAsync" logic was not copying all the needed versions to a log server in the latest epoch during recovery).
- Joshua id (with version vector disabled): 20250115-115834-sre-1d6488b208a8980a (no failures)
The general pull …

Do not use "safe range" logic in recovery code when version vector is enabled

---

fdbserver/MoveKeys.actor.cpp

cherrypick #11933
At commit: fff5439e with clang, seed -f ./tests/slow/SharedDefaultBackupCorrectness.toml -s 2189316179 -b on We found a corruption where the destination storage server can get the incorrect serverKeys mutations. Note this only happens when shard_encode_location_metadata is enabled.
The reason is that one of the actors in the previous iteration encountered transaction_too_old error, and the transaction restarted. However, because the actors are not cancelled, these can still modify the next transaction that retried.
20250210-221107-jzhou-0c392d2cdd03d0ae
If …

Fix startMoveShards() caused corruption [release-7.3]

---

fdbserver/worker.actor.cpp
tests/fast/BulkDumping.toml
tests/fast/BulkLoading.toml

Reduce ShouldCheckPeer frequency and increase max_trace_lines for bulkload tests.
20250210-231437-zhewang-9dda6b1ec86a55b8           compressed=True data_size=36782485 fail_fast=10 max_runs=100000 priority=100 sanity=False submitted=20250210-231437 timeout=5400 username=zhewang

Resolve BulkLoad test failure for TooManyTraceEvent issue

---

fdbclient/include/fdbclient/FDBTypes.h
fdbserver/DDTeamCollection.actor.cpp
fdbserver/DataDistribution.actor.cpp

Migration to consider wiggling based on perpetualStorageEngine and then on configureStorageEngine.
cherry-pick of #11917

Migration to consider wiggling based on perpetualStorageEngine and then on configureStorageEngine.

---

fdbserver/DataDistribution.actor.cpp
fdbserver/include/fdbserver/BulkDumpUtil.actor.h

Address comments in PR https://github.com/apple/foundationdb/pull/11937
100K bulkLoad:
20250211-213711-zhewang-9f4ec6f191089214           compressed=True data_size=36815216 duration=7384577 ended=100000 fail=2 fail_fast=10 max_runs=100000 pass=99998 priority=100 remaining=0 runtime=1:13:21 sanity=False started=100000 stopped=20250211-225032 submitted=20250211-213711 timeout=5400 username=zhewang
100K bulkDump:
20250212-002253-zhewang-597e2d9511140438           compressed=True data_size=36815258 duration=11831522 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:25:02 sanity=False started=100000 stopped=20250212-014755 submitted=20250212-002253 timeout=5400 username=zhewang …

Improve code readability for ParallelismLimitor used by BulkLoad

---

fdbserver/workloads/SnapTest.actor.cpp

A combination of this workload only doing snapshot once and attrition fault injection means that it's possible that not all ss/tlog/coordinator data gets snapshotted. This workload does retry on snapshot errors but note that the absence of machines is not considered an error from snapshot request point of view. Since snapshot restart tests rely on snapshot data, I disabled attrition fault injection for this workload.
The sequence of events that led to this fix:
- Our nightly run found `SnapCycleRestart` failure
- This is an update test, the old binary runs fine, then the new binary gets stuck
- The symptom was that one of the tester process could not successfully run ChangeConfig workload which makes a txn against the cluster. 
- The reason txn failed was because cluster did not fully …

Disable attrition fault injection in snapshot workload

---

fdbbackup/tests/s3_backup_test.sh
fdbclient/BulkLoading.cpp
fdbclient/S3BlobStore.actor.cpp
fdbclient/S3Client.actor.cpp
fdbclient/S3Client_cli.actor.cpp
fdbclient/include/fdbclient/S3BlobStore.h
fdbclient/include/fdbclient/S3Client.actor.h
fdbrpc/HTTP.actor.cpp

Add multiparting uploading/downloading to s3client.
Fix boost::urls::parse_uri 's dislike of credentialed blobstore urls.
Add specific logging when an inspecific exception is thrown.
Limit response content output (big files crashed logging).
* fdbclient/BulkLoading.cpp
Add blobstore regex to extract credentials before feeding the boost
parse_uri.
* fdbclient/include/fdbclient/S3BlobStore.h
* fdbclient/S3BlobStore.actor.cpp
Add cleanup of failed multipart -- abortMultiPartUpload l(s3 will do
this in the background eventually but lets clean up after ourselves).
Also add  getObjectRangeMD5 so can do multipart checksumming.
* fdbclient/S3Client.actor.cpp
Change upload file and download file to do multipart always.
Retry too.
* fdbclient/S3Client_cli.actor.cpp
Add command line to trace rather …

Add multiparting to s3client.

---

fdbclient/ManagementAPI.actor.cpp
fdbserver/DDRelocationQueue.actor.cpp

This PR fixes a bulkload bug causing DD restarts.
In the bulkLoad datamove mechanism, when a bulkload is triggered, this task is registered on a map. For any following data move on the same range, the data move is converted to a "bulkload" data move, which triggers SS to load data. When the bulkload data move starts. it updates the bulkload metadata. At this time, it checks if the metadata shows correct phase (the metadata should not indicate the move has been completed). If the task has been marked as completed, the data move triggers DD restart.
The problem happens when a previous data move for the bulkload task is cancelled by the new data move for the same task. The issue happens when the previous data move marks the bulkload task as completed, before the new data move starts the same …

DataMove Should Decide BulkLoading After Old DataMove Actor Has Been Cleared

---

fdbclient/ManagementAPI.actor.cpp
fdbclient/include/fdbclient/BulkLoading.h
fdbserver/DDRelocationQueue.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/workloads/BulkLoading.actor.cpp
flow/include/flow/error_definitions.h
tests/fast/BulkLoading.toml

It is possible that a bulkload task can never be completed, e.g. no enough machine, no enough space, network outage of blob store. For those cases, we persist "Error" state to the bulkload metadata. Users can "acknowledge" this error task while the system and client will explicitly trace this operation. 
100K bulkload tests:
20250214-044539-zhewang-4b0a08c0b4673fa1           compressed=True data_size=36860787 duration=1523915 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=0:31:05 sanity=False started=100000 stopped=20250214-051644 submitted=20250214-044539 timeout=5400 username=zhewang
20250214-181348-zhewang-8d2daf1775d4a3e1           compressed=True data_size=36822059 fail_fast=10 max_runs=100000 priority=100 …

Allow BulkLoadEngine to Handle Non-Retriable Task

---

README.md

Update 7.3.59 as the latest release

---

fdbclient/SystemData.cpp
fdbclient/include/fdbclient/SystemData.h
fdbserver/BackupWorker.actor.cpp
fdbserver/ClusterRecovery.actor.cpp
fdbserver/QuietDatabase.actor.cpp
fdbserver/tester.actor.cpp

When TLog replies with a popped version, it means the peek request is missing mutations from the peek's begin version to the popped version. This was not handled in backup worker previously. (#10990 has a different fix of removing the noop mode.)
This PR addresses this by checking if the missing versions are caused by NOOP mode pops. This can only happen when the worker requests mutations in the previous epoch. If so, the worker reads the max popped version due to noop mode, which should be >= tlog reply's popped version. If not, an assertion is triggered, because mutations are missing.
In the NOOP mode, we save the popped version in the system key space "backupWorkerMaxNoopVersionKey". The transaction that saves noop version can cause QuietDatabase workload failure, so I disabled it …

Handle cases when backup worker pulling may miss mutations

---

fdbclient/ManagementAPI.actor.cpp
fdbclient/include/fdbclient/BulkLoading.h
fdbserver/DDRelocationQueue.actor.cpp
fdbserver/DDShardTracker.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/include/fdbserver/DataDistribution.actor.h
fdbserver/workloads/BulkDumping.actor.cpp
fdbserver/workloads/BulkLoading.actor.cpp
flow/include/flow/error_definitions.h
tests/fast/BulkDumping.toml
tests/fast/BulkLoading.toml

**Enable BulkLoad Job to Give Up Unretrievable Task**
PR https://github.com/apple/foundationdb/pull/11950 introduced BulkLoad task engine to handle unretrievable task. 
As the bulkload job system relies on the bulkload task engine, the job range is marked as Error if the corresponding task on the range is Error. A job metadata does not erase by the system automatically if the job has some range is marked as Error.
**Fix DDStuck/MaxTLogQueue bugs** 
This issue happens when a bulkload task is failed for an unretrievable error. In this scenario, with the previous mechanism, there is always a data move that gets stuck because the data move keeps retrying to find a valid destination team. If the data move is triggered for team unhealthy, the stuck data move causes the above bugs. To fix this, …

Enable BulkLoad Job to Give Up Unretrievable Task and Fix DDStuck Bug

---

fdbserver/workloads/UnitTests.actor.cpp
tests/fast/RandomUnitTests.toml
tests/rare/AllSimUnitTests.toml
tests/rare/SpecificUnitTests.toml

Ignore multiple tests using `;` as delimiter. Also ignores gRPC unit tests
Testing: https://github.com/apple/foundationdb/pull/11956#discussion_r1958756594

Add ability to ignore multiple tests

---

fdbserver/KeyValueStoreRocksDB.actor.cpp

This was found in https://github.com/apple/foundationdb/pull/11956#issuecomment-2664294162, specific error from Joshua log:
```
<StdErrOutput Severity="40"
Output="fdbserver: /root/build_output/fdbserver/rocksdb-prefix/src/rocksdb/utilities/checkpoint/checkpoint_impl.cc:321: virtual Status rocksdb::CheckpointImpl::ExportColumnFamily(Colum nFamilyHandle *, const std::string &amp;, ExportImportFilesMetaData **): Assertion `*metadata == nullptr' failed." />
```
Basically we were passing uninitialized pointer variable to rocksdb ExportColumnFamily, sometimes the pointer is not null, and rocksdb asserts that it is null. The fix is to simply initialize to nullptr, not doing so is undefined behavior.
100K: `20250218-004547-praza-fix-rocksdb-checkpoint-crash-58a0ea506 compressed=True …

Fix rocksdb crash caused because of passing uninitialized metadata to ExportColumnFamily

---

fdbserver/tester.actor.cpp

Previously `disableBackupWorker` actor would unconditionally trigger config change to disable backup worker even if the existing db config already has it disabled. This can result in a circular loop and `TracedTooManyLines`:
1. disableBackupWorker -> change config -> `tr->set(moveKeysLockOwnerKey, versionKey)` -> dd restarts
2. dd restarts -> can't do movement and health check -> some ss can't be taken out or have their storage engine type changed
3. storage engine type does not converge -> consistency check fails and keeps retrying -> we call disableBackupWorker again -> back to (1)
To break this circular loop, in step (1), we conditionally disable backup worker only if it is enabled in the db config, which means that we don't issue change config again and again, giving time for DD to …

Conditionally disable backup worker

---

fdbserver/DDTeamCollection.actor.cpp
fdbserver/workloads/RandomMoveKeys.actor.cpp

RandomMoveKey should choose SSes from different data halls if the SS data hall is set.
100K test:
20250221-033738-zhewang-ab060216fa6d0ec5           compressed=True data_size=36850511 fail_fast=10 max_runs=100000 priority=100 sanity=False submitted=20250221-033738 timeout=5400 username=zhewang

RandomMoveKey should choose SSes from different data halls

---

fdbserver/BulkLoadUtil.actor.cpp
fdbserver/DDRelocationQueue.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/MoveKeys.actor.cpp
fdbserver/include/fdbserver/DataDistribution.actor.h
fdbserver/storageserver.actor.cpp

Make bulkLoad trace event name organized:
1. Search `DDBulkLoad*` to get all trace events generated by DD.
2. Search `SSBulkLoad*` to get all events generated by SS.
3. Search `DDBulkLoadJob*` to get all events from the DD BulkLoad Job module.
4. Search `DDBulkLoadTask*` to get all events from the DD BulkLoad Task module.
5. Search `DDBulkLoadTaskPersist*` to get all events for DD updating bulkLoad task metadata.
20250225-213220-zhewang-018d0a5991f04f6e           compressed=True data_size=40825804 duration=5271737 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:00:10 sanity=False started=100000 stopped=20250225-223230 submitted=20250225-213220 timeout=5400 username=zhewang …

Improve BulkLoad TraceEvent

---

CMakeLists.txt
tests/CMakeLists.txt

Add compile switch NO_RESTART_TEST to disable restart simulation tests. When set, the restart tests to do upgrades or downgrades are no included in the packaged build.
Tested by running with and without the switch, and confirmed tests pass and restart tests were not included in the package's build when NO_RESTART_TEST was set.
With switch set
`20250225-201214-dlambrig-ac6311932d492f41 `
Without switch set
`20250225-202012-dlambrig-58425c084683efc2`

Add compile switch to disable restart simulation tests

---

fdbcli/BulkDumpCommand.actor.cpp
fdbcli/BulkLoadCommand.actor.cpp
fdbclient/ManagementAPI.actor.cpp
fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/BulkDumping.h
fdbclient/include/fdbclient/BulkLoading.h
fdbclient/include/fdbclient/ManagementAPI.actor.h
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/BulkDumpUtil.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/workloads/BulkDumping.actor.cpp

More clear logic and better trace events.
500K bulkDump tests:
20250226-064557-zhewang-bafded6719b54226           compressed=True data_size=40872385 duration=8890904 ended=500000 fail_fast=10 max_runs=500000 pass=500000 priority=100 remaining=0 runtime=1:47:43 sanity=False started=500000 stopped=20250226-083340 submitted=20250226-064557 timeout=5400 username=zhewang
500K bulkLoad tests:
20250226-183127-zhewang-eae0a34e7a14f617           compressed=True data_size=40875651 duration=7105827 ended=500000 fail_fast=10 max_runs=500000 pass=500000 priority=100 remaining=0 runtime=1:50:40 sanity=False started=500000 stopped=20250226-202207 submitted=20250226-183127 timeout=5400 username=zhewang
100K correctness with 1 irrelevant failure:
20250226-210202-zhewang-ea1e57fa7ffd4175 …

Improve BulkDump Implementation

---

fdbserver/TagPartitionedLogSystem.actor.cpp

Correct an issue to do with populating the list of reporting log servers during recovery with version vector - the list of reporting log servers should include even those that have an empty unknown committed version list.
Testing:
Job id (with version vector disabled): 20250225-202516-sre-bc04a8bf2ed33162 (in progress)

An issue with populating available log servers during recovery with version vector

---

fdbrpc/include/fdbrpc/simulator.h
fdbrpc/sim2.actor.cpp
fdbserver/tester.actor.cpp

isOnMainThread() is used to check if the currently running task is on the FDB's event loop. However, in simulation this behaviour is broken and always returns false.
In other modes such as UnitTest mode since `runTests()` is called before `g_network->run()`, but without a wait() statement the event loop never gets chance to set itself as main thread and the tests never sees current thread as main thread. Therefore we add a yield inside `runTests()` so yield control back to caller block and continue with g_network->run() which eventually schedule it back after initialization.
Correctness:
20250227-185124-vishesh-9307854450c9b575           compressed=True data_size=40831150 duration=4429189 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=
100 remaining=0 runtime=0:53:17 …

Fix isOnMainThread in Simulation and Testing

---

fdbserver/KeyValueStoreRocksDB.actor.cpp
fdbserver/KeyValueStoreShardedRocksDB.actor.cpp

`CreateColumnFamilyWithImport()` expects that the value inside handle is `nullptr`. This patch fixed a codepath where we pass a stale handle left by destroyed column family.
Correctness:
20250228-050542-vishesh-092ebfeaa86e077c           compressed=True data_size=40840277 duration=5414232 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=0:52:30 sanity=False started=100000 stopped=20250228-0558
12 submitted=20250228-050542 timeout=5400 username=vishesh

rocksdb: fix crash due to uninitialized/stale ColumnFamilyHandle

---

fdbclient/ServerKnobs.cpp

When TRACK_TLOG_RECOVERY is turned on, older TLog generations can be garbage collected during the recovery before reaching `fully_recovered`. This was not tested except in the GcGeneration workload. Similarly, `RECORD_RECOVER_AT_IN_CSTATE ` was not widely tested in simulation. So test both randomly now.
correctness 20250301-044651-jzhou-6adf07f987e2e754             compressed=True data_size=35789793 duration=5423943 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:00:42 sanity=False started=100000 stopped=20250301-054733 submitted=20250301-044651 timeout=5400 username=jzhou …

Enable TRACK_TLOG_RECOVERY as default

---

fdbserver/workloads/Cycle.actor.cpp
tests/restarting/from_7.3.29/CycleTestRestart-2.toml
tests/restarting/to_7.4.0/CycleTestRestart-2.toml

Useful for testing upgrade/downgrade tests. Otherwise, the second phase's setup re-initialize the cycle data, thus not actually testing the consistency after the upgrade.
100k correctness of two restarting tests:
20250301-061614-jzhou-fdbafbf4175a72ed             compressed=True data_size=35835172 duration=2806102 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:36:48 sanity=False started=100000 stopped=20250301-065302 submitted=20250301-061614 timeout=5400 username=jzhou
100k regular correctness has a RocksDB DR ExternalTimeout error (`-f ./tests/fast/AtomicBackupToDBCorrectness.toml -s 3645469319 -b on`, which can't be reproduced): 
20250301-194836-jzhou-ba1a8e1268a38bca             compressed=True data_size=35792829 duration=5645259 ended=100000 …

Add an option to Cycle workload to skip setup phase

---

fdbserver/CommitProxyServer.actor.cpp
fdbserver/LogSystem.cpp
fdbserver/TagPartitionedLogSystem.actor.cpp
fdbserver/include/fdbserver/LogSystem.h
fdbserver/include/fdbserver/TagPartitionedLogSystem.actor.h

During commits with version vector enabled, compute location list only once on the resolver. Recalculating a second time could generate a different random number, hence a different set of locations. The location list is generated with a call to `getPushLocations`, which chooses random locations if the total number of tLogs mod the replica count results in collisions.  
Tested by loading commits from branch version-vector-disk-queue and observing `getPushLocations ` is called in both the resolver and on the CP in `assignMutationsToStorageServers`. Observed different locations chosen without the PR, resulting in data not sent to tLogs when it should have been. Added an assert if data was generated for a location but was not sent to a tLog to catch any such future cases.
This PR exposed …

Version vector: compute locations only once during commits.

---

fdbcli/BulkLoadCommand.actor.cpp
fdbclient/BulkLoading.cpp
fdbclient/ClientKnobs.cpp
fdbclient/ManagementAPI.actor.cpp
fdbclient/SystemData.cpp
fdbclient/include/fdbclient/BulkLoading.h
fdbclient/include/fdbclient/ClientKnobs.h
fdbclient/include/fdbclient/ManagementAPI.actor.h
fdbclient/include/fdbclient/SystemData.h
fdbserver/DataDistribution.actor.cpp
fdbserver/workloads/BulkDumping.actor.cpp

When a bulkload job completes, the metadata is moved from the job key range map to the history metadata. The history metadata is a map. The key is the job Id, and the value is the job metadata. 
If the number of jobs in the history is more than `BULKLOAD_JOB_HISTORY_COUNT_MAX`, clear the oldest one before inserting a new one. 
Note that it is possible that a job with the same job id is repeatedly submitted and executed. The history only keeps the job metadata with the latest execution.
500K bulkdump:
20250304-054123-zhewang-9ce7c36a50ada097           compressed=True data_size=40898659 duration=10230830 ended=500000 fail_fast=10 max_runs=500000 pass=500000 priority=100 remaining=0 runtime=1:50:53 sanity=False started=500000 stopped=20250304-073216 submitted=20250304-054123 timeout=5400 …

Add BulkLoad History

---

fdbserver/tester.actor.cpp
flow/include/flow/error_definitions.h

Previously, when tester receives a request from the DCC leader, the tester always rejects the request if existing an old request sent by a different leader. However, it is possible the old task never completes when the old leader is dead.
To fix this, testers should always accept the new request.
20250305-203526-zhewang-622b988368a8b648           compressed=True data_size=40857908 fail_fast=10 max_runs=100000 priority=100 sanity=False submitted=20250305-203526 timeout=5400 username=zhewang …

DCC Tester Should Always Accept New Request from ConsistencyCheckUrgent Role

---

fdbrpc/FlowGrpc.cpp
fdbrpc/FlowGrpcTests.actor.cpp
fdbrpc/FlowGrpcTests.cpp
fdbrpc/include/fdbrpc/FlowGrpc.h
fdbrpc/include/fdbrpc/grpc/AsyncGrpcClient.h
fdbrpc/include/fdbrpc/grpc/AsyncTaskExecutor.h

This PR has three changes:
- gRPC Lifecycle: Adds methods that can be used by worker to register/unregister services. The gRPC wrapper will automatically shutdown/restart services accordingly. Later PR will use these methods to tie life of gRPC service to the life of the worker role.
- AsyncTaskExeuctor: Just a wrapper around IThreadPool that is easier to use, somewhat like `asio::post` or `std::async`. There is `AsyncTaskThread` in fdbclient which serves similar purpose, however it doesn't use `IThreadPool` hence doesn't set the simulation thread_locals correcly, and also just uses one thread. That should be equivalent of setting num_thread = 1 in this class.
- Update existing GrpcServer and  AsyncGrpcClient to use the AsyncTaskExeuctor instead of `asio::thread_pool`.
**Testing:**
Some …

grpc: AsyncTaskExecutor and basic server lifecycle

---

fdbserver/tester.actor.cpp
flow/include/flow/error_definitions.h

Cherrypick: https://github.com/apple/foundationdb/pull/11995
20250306-040234-zhewang-3a90866eab2b6c8f           compressed=True data_size=49592201 duration=5873521 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:58:02 sanity=False started=100000 stopped=20250306-050036 submitted=20250306-040234 timeout=5400 username=zhewang

[Release-7.3] Cherry-pick Fix DCC tester (#11995)

---

fdbclient/S3Client.actor.cpp
fdbserver/BulkDumpUtil.actor.cpp
fdbserver/BulkLoadUtil.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/include/fdbserver/BulkDumpUtil.actor.h
fdbserver/include/fdbserver/BulkLoadUtil.actor.h
fdbserver/storageserver.actor.cpp
packaging/docker/fdb-aws-s3-credentials-fetcher/fdb-aws-s3-credentials-fetcher.go

In tests at scale, processing a large job-manifest.txt was blocking
and causing the bulk job to fail. This is part 1 of two patches.
The second is to address data copy added in the below when we
made methods ACTORs (ACTOR doesn't allow passing by reference).
* fdbserver/BulkDumpUtil.actor.cpp
Removed writeStringToFile and buldDumpFileCopy in favor of new methods
in BulkLoadUtil. Made hosting functions ACTORs so could wait on
async calls.
* fdbserver/BulkLoadUtil.actor.cpp
Added async read and write functions.
* fdbserver/DataDistribution.actor.cpp
Making uploadBulkDumpJobManifestFile async made it so big bulkloads
work.

Make bulkload file reads and writes async and memory parsimonious

---

flow/IThreadPoolTest.actor.cpp
flow/include/flow/flow.h
flow/include/flow/genericactors.actor.h

When a value/error is sent via `ThreadReturnPromiseStream` we assume that the underlying `PromiseStream` will be alive when the client waits. However, if the last `ThreadReturnPromiseStream` gets destroyed after sending values/end_of_stream(), the underlying `PromiseStream` will as well resulting in `broken_promise`. This happens because the actual work of sending the value/error is deferred on the main thread.
This is likely to happen because the sender did its work and it isn't supposed to check if client got the value. Hence, little reason to keep the promise. Meanwhile, client is free to read values from its future whenever it needs to.
This patch just holds the reference to underlying `NotifiedQueue` by copying `PromiseStream` until the value/error is sent. The test added would fail …

Hold `ThreadReturnPromiseStream` reference when sending value/error

---

fdbrpc/include/fdbrpc/LoadBalance.actor.h

This issue was exposed in a simulation failure (test: fast/UDP.toml, seed: 357604555, buggify: on, compiler: g++).
The symptom was ConsistencyCheckFailure because of TracedTooManyLines. 
TLDR of root cause: native api / client relies on `wrong_shard_server` error to invalidate its shard map cache, but replicaComparison was absorbing this error under certain condition. 
If interested, this is the story from symptom to root cause: 
- ConsistencyCheck workload was stuck in setup phase, eventually leading to TracedTooManyLines
- The reason it was stuck was because it was waiting on QuietDatabase
- The reason QuietDatabase was failing was because it constantly observed DataDistributionQueueSize to be 1
- The reason DataDistributionQueueSize was 1 was because there was 1 InFlight data move
- …

Never absorb wrong_shard_server in LoadBalance replicaComparison

---

fdbserver/BulkLoadUtil.actor.cpp
fdbserver/DDRelocationQueue.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/workloads/BulkLoading.actor.cpp

**Problem 1**
Increase the bulkload workload to load upto 1000 keys. The probability of fetchKey split increases. Then, we can observe a data inconsistency bug. When a fetchKey splits, the fetchKey range can be partially marked as ReadWrite, which updates the storage server shard key range map. When the data move ends, the storage server will receive the second pair of serverKeys private mutation which updates the storage server bulkload map in the storage server local metadata. When updating the map, we may use the bulkload task value of the ReadWrite part boundary. However, the bulkload task information is not included in the ReadWrite shard. If the SS restarts at this point, SS forgets the existence of bulkload task on the range. As a result, the range can be partially load but mark …

Improve BulkLoad Test Coverage And Fix Bugs

---

fdbserver/CommitProxyServer.actor.cpp
fdbserver/storageserver.actor.cpp
tests/fast/KillRegionCycle.toml

Simulation found an assertion failure in SS:
ASSERT(rollbackVersion >= data->storageVersion());
The reason is that storage version is updated to a version larger than the forced recovery version, due to only 1'000'000 for max_read_transaction_life_versions. Also added debugging for cumulative checksum mutations.
See rdar://144550725
20250309-185039-jzhou-5145c65b0e8071b7             compressed=True data_size=35841048 duration=5476425 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:57:08 sanity=False started=100000 stopped=20250309-194747 submitted=20250309-185039 timeout=5400 username=jzhou
The general pull request guidelines can be found [here](https://github.com/apple/foundationdb/wiki/FoundationDB-C …

Set max_read_transaction_life_versions for KillRegionCycle.toml

---

fdbclient/BulkLoading.cpp
fdbclient/ManagementAPI.actor.cpp
fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/BulkLoading.h
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/BulkDumpUtil.actor.cpp
fdbserver/BulkLoadUtil.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/include/fdbserver/BulkDumpUtil.actor.h
fdbserver/include/fdbserver/BulkLoadUtil.actor.h
fdbserver/storageserver.actor.cpp
fdbserver/workloads/BulkDumping.actor.cpp

1. Fix RangeLock assert error in BulkDump tests. The error happens if the DD registers the lock owner after the workload submits a task. In this case, when the workload submits a task, it finds that no lock owner has been registered. To solve this issue, we register the lock owner at the beginning of the workload.
2. Simplify the async write/read bulk file code and avoid memory copy of the string.
100K Correctness Test with 1 irrelevant failure:
20250309-232400-zhewang-ba2181eb902cf272           compressed=True data_size=40925783 duration=5300730 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:12:08 sanity=False started=100000 stopped=20250310-003608 submitted=20250309-232400 timeout=5400 username=zhewang
500K BulkLoad Test: …

Fix RangeLock in BulkDump Test and Avoid Memory Copy For Async Read/Write Bulk Files

---

fdbclient/ServerKnobs.cpp

Sometimes persistentData->commit() in tlogs take more than 15 simulation seconds. This leads to sev40, where tlog worker exits unexpectedly. Doubling the knob value to 30.0, only in simulation.
100K correctness: 20250310-225544-praza-r143141719-41a56f2bff2f837dc81003fe418 compressed=True data_size=35830954 duration=5761620 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:12:45 sanity=False started=100000 stopped=20250311-000829 submitted=20250310-225544 timeout=5400 username=praza-r143141719-41a56f2bff2f837dc81003fe418164b8a903fe68. The 1 failure is in AuthzSecurityWithBlobGranules.toml and is not related to this change. 
The general pull request guidelines can be found [here](https://github.com/apple/foundationdb/wiki/FoundationDB-Commit-Proce …

Increase TLOG_MAX_CREATE_DURATION in simulation

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/BulkLoadUtil.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/workloads/RangeLock.actor.cpp

1. Fix range lock assertion failure due to operation_cancelled.
2. When SS receives a bulkdump request, it creates at most 10 batches for the request. To avoid a SS slows down the entire bulkdump progress. This can also increase the test coverage in the simulation.
3. When DDBulkDump scheduler finds a complete task, the scheduler should update the beginKey to avoid DDBulkDump scheduling stuck.
20250311-201413-zhewang-00f48817ad9f26a3           compressed=True data_size=40925829 duration=4732358 ended=100000 fail=4 fail_fast=10 max_runs=100000 pass=99996 priority=100 remaining=0 runtime=1:45:47 sanity=False started=100000 stopped=20250311-220000 submitted=20250311-201413 timeout=5400 username=zhewang
100K bulkdump: …

A Couple for Fixes for BulkDump and RangeLock

---

fdbserver/storageserver.actor.cpp

MutationLogReaderCorrectness.toml sometimes fails with sharded rocks and PSM:
```
<Event Severity="40" ErrorKind="Unset" Time="227.606157" DateTime="2025-03-07T23:48:34Z" Type="SSUpdateError" Machine="[abcd::2:0:1:1]:1" ID="8a92bc88d663ff8a" Error="data_move_conflict"
ErrorDescription="Data move conflict in SS" ErrorCode="1086" ThreadID="851768266932647122" Backtrace="addr2line -e fdbserver.debug -p -C -f -i 0x5be2f6d 0x5be3233 0x5bdd324 0x36ffacd 0x37
02685 0x3702323 0x3701753 0x37009dc 0x37005b6 0x36fe8c4 0x2d66ae8 0x2d6620c 0x2d671a8 0x2d66c4a 0x2d62de8 0x2d624ac 0x20ff468 0x20ff19a 0x59aa72d 0x59aa003 0x1dddde8 0x5ab19b5 0x5ab14ea 0
x35bafdc 0x7fc1250115d0" LogGroup="default" Roles="BK,CS,DD,GP,MS,RK,ST" />
<Event Severity="40" ErrorKind="Unset" Time="227.606157" …
```

Request reboot for TSS data move conflicts in simulation

---

fdbrpc/include/fdbrpc/LoadBalance.actor.h

As title. This is useful for debugging.
100K: `20250311-235946-praza-wrongshard-trace-b53b275e154e2928a5594 compressed=True data_size=36820573 duration=7094906 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:00:49 sanity=False started=100000 stopped=20250312-010035 submitted=20250311-235946 timeout=5400 username=praza-wrongshard-trace-b53b275e154e2928a5594df9ffde95d99686bdab`

Add replica comparison wrong_shard_server trace event

---

fdbserver/KeyValueStoreRocksDB.actor.cpp

Adding rocksdb obsolete files size property in metrics. Include it in the rocksd kv store used space.
cherry-pick of #11993
Simulation run:
20250311-221716-neethu-obsolete-c73da44d92e4befa   compressed=True data_size=55975135 duration=5953557 ended=100000 fail=6 fail_fast=10 max_runs=100000 pass=99994 priority=100 remaining=0 runtime=1:56:18 sanity=False started=100000 stopped=20250312-001334 submitted=20250311-221716 timeout=5400 username=neethu-obsolete
I don't see any errors in j tail.

Adding rocksdb obsolete files size property in metrics.

---

fdbclient/include/fdbclient/BulkLoading.h
fdbserver/BulkLoadUtil.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/include/fdbserver/BulkLoadUtil.actor.h

1. Persist bulkload taskCount in the job metadata so that the user can check the progress using fdbcli.
2. Avoid memory copy when a BulkLoadJob loads bulkload job-manifest.txt.
100K BulkDump Test:
20250312-193056-zhewang-3017858d2af6ea7f           compressed=True data_size=40967788 fail_fast=10 max_runs=100000 priority=100 sanity=False submitted=20250312-193056 timeout=5400 username=zhewang

Persist BulkLoad Task Count in BulkLoadJob Metadata

---

fdbcli/BulkLoadCommand.actor.cpp
fdbclient/BulkLoading.cpp
fdbclient/ManagementAPI.actor.cpp
fdbclient/include/fdbclient/BulkLoading.h
fdbserver/BulkLoadUtil.actor.cpp
fdbserver/DDTeamCollection.actor.cpp
fdbserver/DataDistribution.actor.cpp

1. Add error message to the bulkload job metadata;
2. Persist error message for failures when building the job manifest map from a remote path;
3. Add FDBCLI support to print the error message;
4. Clear TODO(BulkLoad) comments.
Error message output when doing `bulkload history`:
```
fdb> bulkload history
Job 3216165d7553b74024f7c2bcba1466a0 submitted at 1741825798.148600 for range { begin=  end=\xff }. The job ran for 0.898142 mins and exited with status Error.
Error message: Failed to build job-manifest map with error code 1511. The remote file path is /root/3216165d7553b74024f7c2bcba1466a0/job-manifest.txt. The local file path is /root/build_output/loopback-cluster/1/data/ddBulkLoadFiles/3216165d7553b74024f7c2bcba1466a0/job-manifest.txt. The transport method is Local …
```

Add Error Message To BulkLoadJob Metadata

---

fdbcli/BulkDumpCommand.actor.cpp
fdbcli/BulkLoadCommand.actor.cpp
fdbclient/tests/bulkload_test.sh

Tighten up options for bulk*. Compound 'local' and 'blobstore' as 'dump' or 'load'. Ditto for 'history'.
Make it so 'bulkload mode' works like 'bulkdump mode': i.e. dumps current mode.
If mode is not on for bulk*, ERROR in same manner as for writemode.
Make it so we can return bulk* subcommand specific help rather than dump all help when an issue.
Commands look like this now:
```
fdb> help bulkload
bulkload [mode|load|status|cancel|history] [ARGs]
Bulkload commands.
To set bulkload mode: bulkload mode [on|off]
To load a range of key/values: bulkload load <JOBID> <BEGINKEY> <ENDKEY> <DIR>
where <JOBID> is the id of the bulkdumped job to load, <BEGINKEY> to <ENDKEY>
denotes the key/value range to load, and <DIR> is a local directory OR
blobstore url to load SST files from.
To get status: …
```

More cleanup of bulk* cli

---

fdbserver/TLogServer.actor.cpp

`ENABLE_VERSION_VECTOR_REPLY_RECOVERY` can be true only if `ENABLE_VERSION_VECTOR_TLOG_UNICAST` is true. There are some tests which set `ENABLE_VERSION_VECTOR_TLOG_UNICAST` to true (`tests/fast/RawTenantAccessClean.toml`) and it should not be necessary to set `ENABLE_VERSION_VECTOR_REPLY_RECOVERY` for each of those tests individually. 
Joshua:
`20250312-192846-dlambrig-13074ff7154a31fc `

ENABLE_VERSION_VECTOR_REPLY_RECOVERY can be T only if ENABLE_VERSION_VECTOR_TLOG_UNICAST is T

---

fdbrpc/include/fdbrpc/grpc/AsyncTaskExecutor.h
flow/IThreadPoolTest.actor.cpp
flow/include/flow/IThreadPool.h

`getFuture()` should be called before post as `send`/`sendError` operation in `ThreadReturnPromise` moves the underlying Promise to `tagAndForward()`.
Ideally, `ThreadReturnPromise` behaviour should stay consistent with the `Promise`. However, the problem is that it relies on the invariant that there will always be one owner of its internal `Promise` which is either itself or `tagOrForward`  -- which is necessary to ensure that only one thread can operate on the Promise's internal state (ref count, flags etc) and avoid race conditions.
This patch (1) makes sure that in case of `post()` function we get future before, (2) adds an ASSERT as this should never happen, (3) documentation for future users and (4) a test case for potentially fixing this in future.
Correctness: …

Fix use-after-move issue in AsyncTaskExecutor

---

fdbcli/BulkLoadCommand.actor.cpp
fdbclient/BulkLoading.cpp
fdbclient/ManagementAPI.actor.cpp
fdbclient/include/fdbclient/BulkLoading.h
fdbserver/DataDistribution.actor.cpp

100K BulkDumping Tests:
20250314-070441-zhewang-8894df97ad941b29           compressed=True data_size=40996735 duration=2866985 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:39:45 sanity=False started=100000 stopped=20250314-074426 submitted=20250314-070441 timeout=5400 username=zhewang
20250314-165930-zhewang-4845a7c46e5181b2           compressed=True data_size=40956892 duration=5320041 ended=100000 fail=2 fail_fast=10 max_runs=100000 pass=99998 priority=100 remaining=0 runtime=1:05:01 sanity=False started=100000 stopped=20250314-180431 submitted=20250314-165930 timeout=5400 username=zhewang
Please …

BulkLoadJob Should Not Schedule Completed BulkLoadTask

---

fdbclient/ClientKnobs.cpp
fdbclient/ManagementAPI.actor.cpp
fdbclient/S3Client.actor.cpp
fdbclient/include/fdbclient/BulkLoading.h
fdbclient/include/fdbclient/ClientKnobs.h
fdbclient/include/fdbclient/S3Client.actor.h
fdbserver/BulkLoadUtil.actor.cpp
fdbserver/DDRelocationQueue.actor.cpp
fdbserver/DDShardTracker.actor.cpp
fdbserver/DDTeamCollection.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/MoveKeys.actor.cpp
fdbserver/include/fdbserver/DataDistribution.actor.h
fdbserver/storageserver.actor.cpp
fdbserver/workloads/BulkLoading.actor.cpp

Add two client knobs to control the verbose of trace events for bulkloading.
```
int BULKLOAD_VERBOSE_LEVEL; // Set to 1 to minimize the verbosity. Set to 5 to turn on all events for performance insights. Set to 10 to turn on all events.
int S3CLIENT_VERBOSE_LEVEL; // Similar to BULKLOAD_VERBOSE_LEVEL
```
20250315-005936-zhewang-8d2555a5f1f1439e           compressed=True data_size=40961034 duration=6006744 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:14:41 sanity=False started=100000 stopped=20250315-021417 submitted=20250315-005936 timeout=5400 username=zhewang …

Add Verbose Level for BulkLoad Trace Events

---

fdbclient/BulkLoading.cpp
fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/BulkLoading.h
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/BulkLoadUtil.actor.cpp
fdbserver/DDRelocationQueue.actor.cpp
fdbserver/DDShardTracker.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/MoveKeys.actor.cpp
fdbserver/include/fdbserver/BulkLoadUtil.actor.h
fdbserver/include/fdbserver/DataDistribution.actor.h
fdbserver/storageserver.actor.cpp
fdbserver/workloads/BulkLoading.actor.cpp

This PR significantly reduces the DD business and improves SS efficiency by batching multiple manifests into a single bulkload task.
A manifest includes one SST file and one byte sample file, where all keys of the SST files are dumped at a single version. Each SST file is around 15 ~ 30 MB.
Previously, each bulkload task only does one manifest. As a result, while DD has to maintains thousands of bulkload tasks and data moves at the same time, DD still cannot achieve a high utilization at SSes for bulk loading, as a result DD is very busy and becomes a bottleneck of the cluster-wide bulkloading throughput.
This PR solves this issue by batching multiple manifests into a single bulkload task. As a result, each task includes more data to load at storage servers. Given the same amount of …

Allow One BulkloadTask Do Multiple Manifests 

---

fdbrpc/FlowGrpc.cpp
fdbrpc/FlowGrpcTests.cpp
fdbrpc/include/fdbrpc/FlowGrpc.h
fdbrpc/include/fdbrpc/grpc/AsyncGrpcClient.h
fdbrpc/include/fdbrpc/grpc/Credentials.h
fdbserver/fdbserver.actor.cpp
flow/include/flow/network.h

This patch adds TLS support for GrpcServer and AsyncGrpcClient by implementing `GrpcCredentialsProvider` and using that to get channel credentials. It adds `FlowGrpc` which is a flow global instance, and initializes TLS credentials that are consistent with the ones provided to FlowTransport.
- Added `FlowGrpc` to manage gRPC server initialization and TLS configuration globally.
- `GrpcCredentialsProvider` abstracts secure/insecure communications configurations for server/clients.
- Introduced `GrpcTlsCredentialProvider` for dynamic TLS certificate reloading from filesystem and `GrpcTlsCredentialStaticProvider` for static in-memory credentials.
- Updated `GrpcServer` to accept a `GrpcCredentialProvider`, enabling dynamic TLS credential management.
- Modified `fdbserver` to use …

Implement TLS support for Flow/gRPC

---

tests/fast/BulkDumping.toml
tests/fast/BulkLoading.toml
tests/fast/RangeLockCycle.toml
tests/fast/RangeLocking.toml
tests/fast/RawTenantAccessClean.toml
tests/negative/ResolverIgnoreTooOld.toml

Disable enable_version_vector_reply_recovery in tests that disable the version vector feature.
This knob will eventually be removed once version vector testing is completed.

Disable enable_version_vector_reply_recovery in tests disabling version vector.

---

fdbclient/include/fdbclient/FDBTypes.h
fdbserver/BackupWorker.actor.cpp
fdbserver/LogSystemPeekCursor.actor.cpp

Previously I used arena size for accouting, which has problems such as arena memory usage changes and arena memory block circular reference. And we are acquiring flow lock multiple times, even though the cursor has already fetched data into memory.
This change simplifies the accounting to just use message sizes, reducing the number of flow lock acquisitions.
20250319-002950-jzhou-a9ecc09dd1c8812a             compressed=True data_size=53104759 duration=4787313 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:49:48 sanity=False started=100000 stopped=20250319-011938 submitted=20250319-002950 timeout=5400 username=jzhou
20250313-220439-jzhou-95096a8b4f3411fa             compressed=True data_size=36851302 duration=4408042 ended=100000 fail_fast=10 …

Change backup worker memory accounting to use message sizes

---

fdbserver/DataDistribution.actor.cpp
fdbserver/storageserver.actor.cpp

100K correctness with 3 irrelevant failures:
20250319-232139-zhewang-bbcc4061e7d350dd           compressed=True data_size=41053246 duration=4118530 ended=100000 fail=3 fail_fast=10 max_runs=100000 pass=99997 priority=100 remaining=0 runtime=0:56:43 sanity=False started=100000 stopped=20250320-001822 submitted=20250319-232139 timeout=5400 username=zhewang

Audit Replica Should Not Read Empty Range To Check

---

fdbclient/BackupAgentBase.actor.cpp
fdbclient/FileBackupAgent.actor.cpp
fdbclient/include/fdbclient/BackupAgent.actor.h

cherrypick #12037
20250319-043859-jzhou-f180ec751c099669             compressed=True data_size=34291720 duration=6526800 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:05:30 sanity=False started=100000 stopped=20250319-054429 submitted=20250319-043859 timeout=5400 username=jzhou

Fix a restore bug due to a race [release-7.3]

---

design/backup_v2_partitioned_logs.md
fdbserver/BackupWorker.actor.cpp
fdbserver/TagPartitionedLogSystem.actor.cpp
tests/CMakeLists.txt

Refactor such that messages in the queue have to reserve memory first. Thus, when we release the memory, it must have already been reserved.
The second bug fix is to disallow popped version to go lower, because different GRV proxies may return lower version.
100k ParallelRestoreNewBackupCorrectnessAtomicOp.toml
20250321-025532-jzhou-77e2dbd5fd035157             compressed=True data_size=35955443 duration=7391647 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:25:42 sanity=False started=100000 stopped=20250321-042114 submitted=20250321-025532 timeout=5400 username=jzhou
The failure is `TracedTooManyLines` due to 200+k `CommitDummyTransactionError` and `CommitDummyTransaction` events.
100k regular  20250321-025429-jzhou-a088c3f119331b93 …

Fix backup worker assertion failure on memory usage

---

documentation/sphinx/source/rangelock.rst
fdbcli/BulkLoadCommand.actor.cpp
fdbclient/ManagementAPI.actor.cpp
fdbclient/SystemData.cpp
fdbclient/include/fdbclient/ManagementAPI.actor.h
fdbclient/include/fdbclient/RangeLock.h
fdbclient/include/fdbclient/SystemData.h
fdbserver/workloads/BulkDumping.actor.cpp
fdbserver/workloads/BulkLoading.actor.cpp
fdbserver/workloads/RandomRangeLock.actor.cpp
fdbserver/workloads/RangeLock.actor.cpp
fdbserver/workloads/Watches.actor.cpp
flow/include/flow/error_definitions.h

This PR addresses the issue in the [PR](https://github.com/apple/foundationdb/pull/12044) by making range lock API more clear to use:
A request of locking/releasing a range is rejected if it conflicts to a lock on the range with a different lock.range or a different lock.user or a different lock.type.
This PR also:
1. Add range lock API to bulkload commands, so that the cluster can be recovered from unexpected range lock bugs.
2. Add checks at the end of BulkLoad/BulkDump/RandomRangeLock workload -- the range locked by the workload must be fully unlocked at the end of the workload.
3. Disable range lock injection workload in Watch tests because the watchesWorker() does not catch the transaction error. So, the test can be failed because of the transaction_rejected_range_locked triggered by …

Reject Range Lock/Unlock Requests with Conflicting Range, User, or Lock Type

---

fdbclient/NativeAPI.actor.cpp
flow/Platform.actor.cpp
flow/include/flow/Trace.h

Mostly in simulation, to address TraceTooManyLines errors.
20250326-041623-jzhou-f1b84849666be150             compressed=True data_size=36909535 duration=5387674 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=2:05:32 sanity=False started=100000 stopped=20250326-062155 submitted=20250326-041623 timeout=5400 username=jzhou
The failed seed `-f ./tests/rare/BlobRestoreToVersion.toml -s 599190995 -b on` is an assertion failure on DD (unrelated to this PR):
```
FailedAssertion=!this-&gt;meta.ranges.empty() &amp;&amp; this-&gt;meta.ranges.front().contains(range) File=/root/src/foundationdb/fdbserver/DataDistribution.actor.cpp Line=163
DataMove::validateShard(DDShardInfo const&, KeyRangeRef, int) at …
```

Suppress a few verbose trace events

---

fdbserver/ApplyMetadataMutation.cpp
fdbserver/Resolver.actor.cpp
fdbserver/include/fdbserver/LogSystem.h

Fix version vector incompatibility with backup range changes. When a change to the range set is detected (clear range or add range), indicate the transaction must be sent to all logs in the same manner as shard moves. This is because new ranges can mean additional tags than the set originally found pre resolution.

Fix version vector incompatibility with backup range changes

---

fdbserver/DataDistribution.actor.cpp
fdbserver/MoveKeys.actor.cpp
tests/rare/BlobGranuleApiCorrectness.toml
tests/rare/BlobGranuleCorrectness.toml
tests/rare/BlobGranuleCorrectnessClean.toml
tests/rare/BlobGranuleMergeBoundaries.toml
tests/rare/BlobGranuleMoveVerifyCycle.toml
tests/rare/BlobGranuleRanges.toml
tests/rare/BlobGranuleRangesChangeLog.toml
tests/rare/BlobGranuleVerifyAtomicOps.toml
tests/rare/BlobGranuleVerifyBalance.toml
tests/rare/BlobGranuleVerifyBalanceClean.toml
tests/rare/BlobGranuleVerifyCycle.toml
tests/rare/BlobGranuleVerifyLarge.toml
tests/rare/BlobGranuleVerifyLargeClean.toml
tests/rare/BlobGranuleVerifySmall.toml
tests/rare/BlobGranuleVerifySmallClean.toml
tests/rare/BlobRestoreBasic.toml
tests/rare/BlobRestoreLarge.toml
tests/rare/BlobRestoreTenantMode.toml
tests/rare/BlobRestoreToVersion.toml

Fix an issue mentioned by https://github.com/apple/foundationdb/pull/12051#issue-2948354091
Blob and SHARD_ENCODE_LOCATION_METADATA  are not compatible. Blob uses `assignKeysToServer` which changes ServerKeys and KeyServers without changing data move metadata. On the other hand, ShardEncodeLocationMetadata requires to update data move metadata when updating the shard maps (see StartMoveShard and FinishMoveShard). 
If `prepareBlobRestore` runs when ShardEncodeLocationMetadata is on, when DD restarts, DD loads data move metadata and key server metadata, there can be a mismatch detected by `DataMove::validateShard`.
20250327-004138-zhewang-a7fa5eee90608b1d           compressed=True data_size=41070986 duration=6706291 ended=100000 fail_fast=10 max_runs=100000 pass=100000 …

Disable SHARD_ENCODE_LOCATION_METADATA in Blob Features

---

fdbclient/BackupContainerFileSystem.actor.cpp
fdbserver/workloads/BackupCorrectness.actor.cpp

This PR focuses the production issue of missing backup log ranges and eventually expire workflow blocked and restorable state not set correctly.
- In the case of missing mutation logs, each snapshot restorability has to be recalculated based on whether the snapshot can be restored from the existing logs
- In the case of missing mutation logs, cluster level minRestorableVersion and maxRestorableVersion has to be recalculated from the existing logs
- Apart from this added two new unit tests to test the missing log case.
Testing:
1) Tested with the custom backup binary on iclouddb1/P01_DC2 and iclouddb1/PO2_DC2. The snapshots restore and the cluster level restore are set properly and able to expire the old backups. More details at: https://a1391190.slack.com/archives/C01LS31J3R7/p174016468221 …

Set snapshot restore state from mutation logs information.

---

README.md

The path was leading to the generic site, so added a more direct link to the download resources

Added direct download path to CMake

---

fdbclient/BackupContainerFileSystem.actor.cpp
fdbserver/workloads/BackupCorrectness.actor.cpp

cherry-pick of https://github.com/apple/foundationdb/pull/12038
This PR focuses the production issue of missing backup log ranges and eventually expire workflow blocked and restorable state not set correctly.
In the case of missing mutation logs, each snapshot restorability has to be recalculated based on whether the snapshot can be restored from the existing logs
In the case of missing mutation logs, cluster level minRestorableVersion and maxRestorableVersion has to be recalculated from the existing logs
Apart from this added two new unit tests to test the missing log case. …

Set snapshot restore state from mutation logs information. 

---

fdbserver/workloads/BackupCorrectnessPartitioned.actor.cpp

Partitioned logs backup test fix.
This test does not exist in 7.3 release, so missed in my testing.
This particular test fails in the scenario like:
```
URL: file://simfdb/backups/backup-1970-01-01-00-01-31.083618
Restorable: true
Partitioned logs: true
Snapshot:  startVersion=188535558 (maxLogEnd -0.00 days)  endVersion=188535558 (maxLogEnd -0.00 days)  totalBytes=120013  restorable=true  expiredPct=0.00
Snapshot:  startVersion=593303745 (maxLogEnd +-0.00 days)  endVersion=593303745 (maxLogEnd +-0.00 days)  totalBytes=120013  restorable=true  expiredPct=0.00
SnapshotBytes: 240026
MinLogBeginVersion:      82953666 (maxLogEnd -0.01 days)
ContiguousLogEndVersion: 585088375 (maxLogEnd -0.00 days)
MaxLogEndVersion:        585088375 (maxLogEnd -0.00 days)
MinRestorableVersion:    593303745 …
```

Partitioned logs backup test fix

---

fdbclient/BackupContainerFileSystem.actor.cpp

Fix for continuousLogEnd not updating correctly.
Testing:
- Manually running fdbbackup in iCloud/p01_DC2 cluster
- Simulation passed:
- 20250402-070850-neethu2-513a0e2db70671b6           compressed=True data_size=51318294 duration=5423037 ended=100000 fail_fast=10 max_runs=100000 pass=100000 
- Simulation also passed with the new unit test:
- 20250403-013206-neethubackup-100k-31486078ff7f3894 compressed=True data_size=51333966 duration=5258662 ended=100000 fail_fast=10 max_runs=100000 pass=100000

Fix for continuousLogEnd not updating correctly.

---

bindings/java/src/main/overview.html.in
bindings/python/CMakeLists.txt
cmake/CPackConfig.cmake
cmake/FDBInstall.cmake
cmake/InstallLayout.cmake
documentation/sphinx/source/downloads.rst
documentation/sphinx/source/guide-common.rst.inc
packaging/docker/Dockerfile
packaging/rpm/buildrpms.sh

Fixed issues found when building release binaries, cherrypick #12084
- The Javadoc API version is hard coded.
- Update RPM to be RHEL9
- Fixed a Dockerfile issue: `podman` doesn't like incomplete URL
- cherrypick #12082

Fix Javadoc build error, RPM packaging, and Dockerfile [release-7.4]

---

bindings/java/src/main/overview.html.in
cmake/CPackConfig.cmake
cmake/FDBInstall.cmake
cmake/InstallLayout.cmake
documentation/sphinx/source/downloads.rst
documentation/sphinx/source/guide-common.rst.inc
packaging/docker/Dockerfile
packaging/rpm/buildrpms.sh

Fixed issues found when building 7.4 release binaries.
- The Javadoc API version is hard coded.
- Update RPM to be RHEL9
- Fixed a Dockerfile issue: podman doesn't like incomplete URL

Fix Javadoc build error, RPM packaging, and Dockerfile

---

fdbclient/BackupAgentBase.actor.cpp

20250416-003102-zhewang-3bc17630a6bc295c           compressed=True data_size=49637939 duration=4547169 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:58:41 sanity=False started=100000 stopped=20250416-012943 submitted=20250416-003102 timeout=5400 username=zhewang
Performance gain is verified by a real cluster.

Fix Restore Speed Regression

---

fdbserver/TagPartitionedLogSystem.actor.cpp

In version vector, a "restricted" locality set is created representing which logs were chosen on the commit proxy. They are returned from the RV in the tpcv structure and numbered 0..n where n is the total # logs on the cluster. However, the locality set object uses a different numbering scheme. Each log in the set is numbered from 0 up to the number of logs in the locality. This bug is not seen with single region tests, only in multi region tests. 

Fix how non local restricted log sets are built.

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/DataDistribution.actor.cpp
fdbserver/RocksDBCheckpointUtils.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/workloads/BulkDumping.actor.cpp

20250421-204803-zhewang-5eccac3a7d9a104f           compressed=True data_size=41107013 duration=5513529 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=0:55:05 sanity=False started=100000 stopped=20250421-214308 submitted=20250421-204803 timeout=5400 username=zhewang

Add Option to Turn Off Failure Injection to BulkLoad Process

---

bindings/java/CMakeLists.txt
fdbserver/storageserver.actor.cpp

cmake is not following the redirect. Trying repo1.maven.org instead of search.maven.org (works locally -- see if it works up here in ci/cd).  Here is the error:
```
-- Building fat jar to /Users/ec2-user/foundationdb_build_output_macos_x86_64/packages
CMake Error at bindings/java/CMakeLists.txt:339 (file):
file DOWNLOAD HASH mismatch
for file: [/Users/ec2-user/foundationdb_build_output_macos_x86_64/packages/junit-platform-engine-1.7.1.jar]
expected hash: [37df5a9cd6dbc1f754ba2b46f96b8874a83660e1796bf38c738f022dcf86c23f]
actual hash: [e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855]
status: [22;"HTTP response code said error"]
CMake Error at bindings/java/CMakeLists.txt:348 (file):
file DOWNLOAD HASH mismatch
for file: …
```

foundationdb-pr-macos-m1 on macOS Ventura 13.x fails downloading jar

---

fdbclient/NativeAPI.actor.cpp
fdbclient/include/fdbclient/VersionVector.h

Clear the client's version vector when recovery is detected when the set of proxies in the dbinfo changed. Clearing the version vector when the proxy changes indicates recovery occurred and all proxies will have a new epoch's version.
It is necessary to clear the version vector on recovery, otherwise commits right before recovery may not be returned back to the client to populate the version vector (see [PR](https://github.com/apple/foundationdb/pull/5942)).
Prior, the version vector was cleared when the cluster id was detected to have changed. At that point, transactions may have already started in the new epoch, and a race condition can break the invariant `info->readVersion() > ssVersionVectorCache.getMaxVersion())` (scenario below).
----
Versions V1<V2<V3
1. There are two GRVProxies A …

Clear vv on client when recovery detected via dbinfo update.

---

fdbclient/include/fdbclient/StorageServerInterface.h
fdbserver/DDRelocationQueue.actor.cpp
fdbserver/DDTeamCollection.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/MockGlobalState.actor.cpp
fdbserver/StorageMetrics.actor.cpp
fdbserver/TCInfo.actor.cpp
fdbserver/include/fdbserver/DataDistributionTeam.h
fdbserver/include/fdbserver/StorageMetrics.actor.h
fdbserver/include/fdbserver/TCInfo.h
fdbserver/storageserver.actor.cpp
packaging/docker/Dockerfile

This PR adds DD BulkLoad load balancing: When DD chooses a dest team to do bulkload, DD filters out any invalid teams for low available disk space and unhealthy status; then DD randomly chooses 1/4 valid teams as the candidates. Finally, DD chooses the team with the minimal concurrent ongoing bulkload tasks. The team ongoing tasks count is the maximum ongoing tasks count among all storage servers.
100K correctness (with 1 irrelevant failure):
20250424-235519-zhewang-237cc05a9945d7c1           compressed=True data_size=41108679 duration=5653635 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:35:16 sanity=False started=100000 stopped=20250425-013035 submitted=20250424-235519 timeout=5400 username=zhewang
500K BulkLoad (with 2 irrelevant …

DD BulkLoadTask Load Balance

---

fdbrpc/FlowGrpcTests.actor.cpp
fdbrpc/FlowTests.actor.cpp
fdbrpc/include/fdbrpc/grpc/AsyncGrpcClient.h
fdbrpc/include/fdbrpc/grpc/AsyncTaskExecutor.h
fdbserver/KeyValueStoreRocksDB.actor.cpp
flow/IThreadPoolTest.actor.cpp
flow/actorcompiler/ActorCompiler.cs
flow/include/flow/CoroutinesImpl.h
flow/include/flow/FlowThread.h
flow/include/flow/IThreadPool.h
flow/include/flow/ThreadPrimitives.h

The original `ThreadReturnPromiseStream` didn't handle reference counting
in a thread-safe way. This led to subtle and hard-to-debug race conditions, especially since Future
and Promise often live on different threads in this use case.
This patch introduces a new implementation of ThreadReturnPromiseStream that uses an atomics backed
spinlock to safely manage reference counts. As a result, the Flow compiler also needs to support a
new type: `ThreadFutureStream`, in addition to the existing `FutureStream`.
The underlying `NotifiedQueue` now has a parallel implementation called `ThreadNotifiedQueue` to
make this possible. The higher-level thread-safe promise and promise counterpart are built on top of
that.
The new `ThreadFutureStream` is compatible with both Flow and C++ coroutines. The …

ThreadReturnPromiseStream: do ref-counting safely

---

fdbserver/CommitProxyServer.actor.cpp

cherry-pick #12104 
Replacing expensive two RangeMap lookups with one.
20250425-015949-jzhou-416e3b1f31acdc34             compressed=True data_size=35967701 duration=4413633 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=2:14:13 sanity=False started=100000 stopped=20250425-041402 submitted=20250425-015949 timeout=5400 username=jzhou

Optimize keyInfo lookup in commit proxy [release-7.4]

---

fdbkubernetesmonitor/monitor.go

A "Error could not close file" error is logged, even if error is `nil`. This seems like an obvious mistake. I noticed this when looking over my FDB logs.

fdbkubernetesmonitor: Only log error when there is one

---

fdbkubernetesmonitor/monitor.go

Back-port of https://github.com/apple/foundationdb/pull/12085

[RELEASE-7.3] fdbkubernetesmonitor: Only log error when there is one (#12085)

---

fdbkubernetesmonitor/monitor.go

Back-port of https://github.com/apple/foundationdb/pull/12085

[RELEASE-7.4] fdbkubernetesmonitor: Only log error when there is one (#12085)

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/BackupWorker.actor.cpp

Increase the buffer size for backup workers and rename the knob.
Seed: -f ./tests/slow/ParallelRestoreNewBackupCorrectnessAtomicOp.toml -s 3120109021 -b on
100k  20250428-201446-jzhou-c68b81af1576e419             compressed=True data_size=36001424 duration=5667059 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:58:03 sanity=False started=100000 stopped=20250428-211249 submitted=20250428-201446 timeout=5400 username=jzhou

Fix assertion failure due to small knob value

---

fdbclient/BackupContainerFileSystem.actor.cpp

Backup unit test fix. The code did not handle the missing log file overlapping with the snapshots after the next one. Fixed it.
Running 100k run:
20250429-185014-neethu-66201b418bd449a4            compressed=True data_size=56176309 duration=5334503 ended=100000 fail=3 fail_fast=10 max_runs=100000 pass=99997 
Failures not related to backup test

Backup unit test fix.

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/BackupWorker.actor.cpp

cherrypick #12115 
Increase the buffer size for backup workers and rename the knob.
commit: [6152e1486dec6831774319869ebde93c6f3d6083](https://github.com/apple/foundationdb/commit/6152e1486dec6831774319869ebde93c6f3d6083)
Seed: -f ./tests/slow/ParallelRestoreNewBackupCorrectnessAtomicOp.toml -s 3120109021 -b on
100k 20250428-174035-jzhou-24a3f0b34263b742

Fix assertion failure due to small knob value [release-7.4]

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/IKeyValueStore.actor.h
fdbclient/include/fdbclient/ServerKnobs.h
fdbclient/tests/fdb_cluster_fixture.sh
fdbserver/KeyValueStoreRocksDB.actor.cpp
fdbserver/storageserver.actor.cpp

* fdbclient/ServerKnobs.cpp
* fdbclient/include/fdbclient/ServerKnobs.h Add BULK_LOAD_USE_SST_INGEST knob.
* fdbclient/include/fdbclient/IKeyValueStore.actor.h Add ingestSSTFiles and supportSStIngestion.
* fdbserver/KeyValueStoreRocksDB.actor.cpp
* fdbserver/KeyValueStoreShardedRocksDB.actor.cpp Implement ingestSSTFiles and supportSStIngestion
* fdbserver/storageserver.actor.cpp If BULK_LOAD_USE_SST_INGEST and BulkLoadType::SST, ingest sst file rather than read keyvalues.
* fdbclient/tests/fdb_cluster_fixture.sh Use rocksdb instead of sqllite in tests.

Ingest sst files rather than their keyvalue content (2nd attempt)

---

documentation/sphinx/source/release-notes/release-notes-730.rst

cherrypick https://github.com/apple/foundationdb/pull/12122

Add 7.3.63 to 7.3.67 release notes [release-7.3]

---

fdbserver/storageserver.actor.cpp

At this point, RocksDB bulkload with SST ingestion is as fast as the SQLite bulkload.
20250501-170037-zhewang-f3e4b3f8cacecb7b           compressed=True data_size=41162458 duration=5640698 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:24:32 sanity=False started=100000 stopped=20250501-182509 submitted=20250501-170037 timeout=5400 username=zhewang

RocksDB Do Compact After BulkLoad

---

packaging/docker/build-images.sh

If CLANG is set to 1, copy binaries and client library from the current local `cbuild_output` of foundationdb.

set build_output_directory for cbuild_output when CLANG set

---

fdbclient/ClientKnobs.cpp

Backport #12132 to 7.4 branch. 
100K correctness: `20250502-234839-praza-disable-backup-consistency-check-7.4-f compressed=True data_size=36924407 duration=6648505 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:37:28 sanity=False started=100000 stopped=20250503-002607 submitted=20250502-234839 timeout=5400 username=praza-disable-backup-consistency-check-7.4-fdc8c665bf59eaecbfc5b0ab88df8ca08e7eb747`.

[release-7.4] Disable ENABLE_REPLICA_CONSISTENCY_CHECK_ON_BACKUP_READS by default

---

fdbclient/ClientKnobs.cpp

As title. 
100K correctness running:  `20250502-225848-praza-disable-backup-consistency-check-7f511 compressed=True data_size=36982835 duration=5566814 ended=100000 fail=2 fail_fast=10 max_runs=100000 pass=99998 priority=100 remaining=0 runtime=0:56:08 sanity=False started=100000 stopped=20250502-235456 submitted=20250502-225848 timeout=5400 username=praza-disable-backup-consistency-check-7f51188ba7ea2a6b81904805ba76064f7ee461ca`. Both failures not related to this change.

Disable ENABLE_REPLICA_CONSISTENCY_CHECK_ON_BACKUP_READS by default

---

fdbclient/include/fdbclient/BulkLoading.h
fdbserver/DataDistribution.actor.cpp

In case the dataset folder is moved across different roots, we still want to load the data. In this case, the root path in the task metadata is not consistent to the job root path. The job root should overwrite the task root in the task metadata.

BulkLoad Job Root Should Overwrite Task Root Path

---

fdbbackup/backup.actor.cpp

Backup URL validation for directory traversals.
Running 100k simulation test.
20250508-180315-neethu-url-main-4810fcb2e1710507  ended=100000 fail_fast=10 max_runs=100000 pass=100000 
BEFORE:
```
./fdbbackup describe -d 'file:///tmp/../../../etc/passwd'
ERROR: 'Backup Container URL invalid' on URL 'file:///tmp/../../../etc/passwd': Backup path '/tmp/../../../etc/passwd' must be the absolute path '/etc/passwd'
Try `./fdbbackup --help' for more information.
ERROR: Backup Container URL invalid
Fatal Error: Backup Container URL invalid
```
AFTER:
```
ERROR: Backup Container URL 'file:///tmp/../../../etc/passwd' contains directory traversals
Try `./fdbbackup --help' for more information.
ERROR: Backup Container URL invalid
Fatal Error: Backup Container URL invalid
``` …

Backup URL validation for directory traversals.

---

packaging/docker/Dockerfile
packaging/docker/build-images.sh

These changes introduce the possibility of building a working `arm64` Docker image using `build-images.sh`; a few further changes were necessary to get it to work, but I am submitting in this PR the minimum changes necessary.

Allow building a working Docker image when target architecture is arm64

---

fdbclient/S3BlobStore.actor.cpp

Fixes #12150
Duplicate printing of a secret in the backup url when using S3 storage.

Fix duplicate secret key in S3BlobStore URL construction

---

fdbserver/KeyValueStoreRocksDB.actor.cpp
fdbserver/Status.actor.cpp

Cherrypick -  #12145 
When knob_rocksdb_block_cache_size is updated in the custom parameters section and and storage servers were restarted, fdbcli status json reports the old value for block_cache_limit for rocksdb metrics.
Coordinator was fetching ServerKnob value which was value set for Coordinator rather than fetching updated value from each StorageServer
Testing:
1.  Ran run_custom_cluster.sh with rocksdb as storage engine.
2. Killed one of the fdbserver and restarted that process by passing knob value
`../build_output//bin/fdbserver -p auto:1504 -c storage -d ./loopback-cluster/4/data -L ./loopback-cluster/4/log -C ./loopback-cluster/fdb.cluster --datacenter_id DC1 --locality-zoneid DC1-Z-0 --locality-machineid M-4 --knob_rocksdb_block_cache_size 300000`
3. fdbcli status json shows …

Fix fdbcli status json to fetch updated knob_rocksdb_block_cache_size value from StorageServers

---

fdbbackup/backup.actor.cpp
fdbclient/Tuple.cpp
fdbrpc/Locality.cpp
fdbrpc/include/fdbrpc/SimulatorProcessInfo.h
fdbserver/worker.actor.cpp

100k correctness:  20250515-223418-jzhou-a4203dbe05d36206             compressed=True data_size=36031695 duration=5523122 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:02:16 sanity=False started=100000 stopped=20250515-233634 submitted=20250515-223418 timeout=5400 username=jzhou
The failure is an external timeout with sharded rocks `-f ./tests/slow/ParallelRestoreOldBackupCorrectnessAtomicOp.toml -s 2425397265 -b on`, which can't be reproduced.

Refactor: some duplicated code patterns found by teamscale

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/DataDistribution.actor.cpp

20250515-222705-zhewang-6ee8aa4ac29f1f2e           compressed=True data_size=41167928 duration=5199924 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:04:43 sanity=False started=100000 stopped=20250515-233148 submitted=20250515-222705 timeout=5400 username=zhewang

Fix BulkLoad DD Busy Loop

---

documentation/sphinx/source/administration.rst
documentation/sphinx/source/api-reference.rst
documentation/sphinx/source/getting-started-linux.rst
documentation/sphinx/source/getting-started-mac.rst

Current link relative://javadoc/index.html doesn't work.
I manually checked the generated pages have correct links via `cmk docpreview` target.

Update Javadoc locations

---

documentation/sphinx/source/administration.rst
documentation/sphinx/source/api-reference.rst
documentation/sphinx/source/getting-started-linux.rst
documentation/sphinx/source/getting-started-mac.rst

Current link relative://javadoc/index.html doesn't work.
cherrypick #12169

Update Javadoc locations [release-7.4]

---

fdbclient/ServerKnobs.cpp
fdbserver/storageserver.actor.cpp
tests/fast/AtomicBackupToDBCorrectness.toml

20250610-164440-zhewang-032e866a85878b19           compressed=True data_size=41255833 duration=5387342 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=3:29:27 sanity=False started=100000 stopped=20250610-201407 submitted=20250610-164440 timeout=5400 username=zhewang
100K AtomicBackupToDBCorrectness:
20250610-212947-zhewang-6234e861a99c8ee9           compressed=True data_size=41296380 duration=265406 ended=2401 fail_fast=10 max_runs=100000 pass=2401 priority=100 remaining=1 day, 14:10:35 runtime=0:56:21 sanity=False started=2576 submitted=20250610-212947 timeout=5400 username=zhewang …

Mitigate rocksdb external timeout in AtomicBackupToDBCorrectness test

---

documentation/CMakeLists.txt
documentation/sphinx/conf.py

Before the fix:
cbuild_output/documentation/html/anti-features.html:    <title>Anti-Features &#8212; FoundationDB OFF documentation</title>
cbuild_output/documentation/html/api-c.html:    <title>C API &#8212; FoundationDB OFF documentation</title>
cbuild_output/documentation/html/api-error-codes.html:    <title>Error Codes &#8212; FoundationDB OFF documentation</title>
cbuild_output/documentation/html/api-general.html:    <title>Using FoundationDB Clients &#8212; FoundationDB OFF documentation</title>
...
After the fix:
cbuild_output/documentation/html/anti-features.html:    <title>Anti-Features &#8212; FoundationDB 7.4.0 documentation</title>
cbuild_output/documentation/html/api-c.html:    <title>C API &#8212; FoundationDB 7.4.0 documentation</title> …

Fix documentation titles

---

design/replication-policy.md

Make information in tables readable from terminal, they were too wide.

Make tables in replication doc readable from terminal

---

documentation/sphinx/source/configuration.rst

Updating documentation of configuring FDB storage subsystem.
Added redwood and rocksdb storage engine information.

Updating documentation of configuring FDB storage subsystem.

---

tests/CMakeLists.txt
tests/fast/PhysicalShardMove.toml

100K physical shard move:
20250614-003601-zhewang-bb980ea0cdcf3cae           compressed=True data_size=41296503 duration=3960350 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=2:45:40 sanity=False started=100000 stopped=20250614-032141 submitted=20250614-003601 timeout=5400 username=zhewang
20250614-034427-zhewang-ac439db66a590a6e           compressed=True data_size=41255650 duration=4796963 ended=100000 fail=2 fail_fast=10 max_runs=100000 pass=99998 priority=100 remaining=0 runtime=3:07:59 sanity=False started=100000 stopped=20250614-065226 submitted=20250614-034427 timeout=5400 username=zhewang …

Fix physical shard move external timeout

---

fdbserver/ClusterRecovery.actor.cpp
fdbserver/TagPartitionedLogSystem.actor.cpp
fdbserver/include/fdbserver/LogSystem.h
fdbserver/include/fdbserver/TagPartitionedLogSystem.actor.h

When purging old generations, these no longer needed generations are removed in
the in-memory LogSystem data structure. Then the change is made durable on
coordinators.
If there is a recovery happened before the change is durable, and ServerDBInfo
broadcast is sent to the old tlogs and they can be displaced/removed. As a
result, the recovery will become stuck waiting for locking these old tlogs.
This PR updates the purging so that it  modifies states on coordinators first and then update in-memory states.
In this way, the race won't cause recovery to become stuck.
Note this is a pretty rare case, which requires the race, as well as multiple generations during the recovery. When it happens, `PurgeOldTLogGeneration` events should be present before the recovery.
Found by simulation on PR …

Fix a race that can cause recovery to be stuck

---

fdbserver/ClusterRecovery.actor.cpp
fdbserver/TagPartitionedLogSystem.actor.cpp
fdbserver/include/fdbserver/LogSystem.h
fdbserver/include/fdbserver/TagPartitionedLogSystem.actor.h

cherrypick https://github.com/apple/foundationdb/pull/12212
20250630-000131-jzhou-807a320576a5e2eb             compressed=True data_size=35964360 duration=5757872 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=0:54:29 sanity=False started=100000 stopped=20250630-005600 submitted=20250630-000131 timeout=5400 username=jzhou
The failed seed is external timeout using RocksDB engine, which can't be reproduced.

Fix a race that can cause recovery to be stuck [release 7.4]

---

bindings/go/src/fdb/fdb_test.go

fdb_test.go:409:1: ExampleGetClientStatus refers to unknown identifier: GetClientStatus

Fix go compiling errors

---

bindings/go/src/fdb/fdb_test.go

fdb_test.go:409:1: ExampleGetClientStatus refers to unknown identifier: GetClientStatus
cherrypick #12239

Fix go compiling errors [release-7.4]

---

bindings/go/src/fdb/fdb_test.go

fdb_test.go:409:1: ExampleGetClientStatus refers to unknown identifier: GetClientStatus
cherrypick #12239

Fix go compiling errors [release-7.3]

---

fdbrpc/Locality.cpp
fdbrpc/include/fdbrpc/Locality.h
flow/TDMetric.cpp
flow/include/flow/TDMetric.actor.h

Follow-on from #12225
Actually fix all the alignment complaints from compiler on mac osx such as the one below
`ld: building fixups: pointer not aligned at __ZN12LocalityData9keyZoneIdE+0x0 from lib/libfdbrpc.a[20](Locality.cpp.o)`

Fix alignment on mac arm

---

fdbclient/S3BlobStore.actor.cpp

When a request to S3BlobStore fails, it can be retried. Within that loop, we set:
`req->resource = getCanonicalURI(bstore, req);`
However, if this request is a retry, this will result in double-encoding of `resource`.
After a failure, reset `req.resource`. `req.resource` is recomputed on each loop because the set headers are reset on each loop, and `setHeaders` expects an unencoded `request.resource`.
When running `s3_backup_test` with some custom code to force retry, note that the second (retry) PUT has double-encoding:
`[5339570d0947c8ef187555aa69137a04] HTTP starting PUT /testbucket/data/ctests/test_s3_backup_and_restore/snapshots/snapshot%2C3074378%2C3074378%2C4293 ContentLen:313
[5339570d0947c8ef187555aa69137a04] HTTP starting PUT …

Prevent double-encoding of URIs in requests to S3BlobStore

---

CMakeLists.txt
cmake/CompileBoost.cmake
cmake/GetFmt.cmake

Find zstd lib on macosx so we pick it up even when homebrew installed so boost can compile.
Ditto for fmt.

Workaround for macos x arm build: find zstd for boost and fmt

---

fdbcli/BulkLoadCommand.actor.cpp
fdbclient/ManagementAPI.actor.cpp
fdbclient/include/fdbclient/ManagementAPI.actor.h
fdbclient/tests/bulkload_test.sh
fdbserver/DataDistribution.actor.cpp
fdbserver/workloads/BulkLoading.actor.cpp

Previously, a bulkload job requires `task count` amount of range locks. If the task count is large, a job can result in too many range lock, and the commit proxy will be come super busy, causing performance issue.
With PR, we lock a range per job. The job range is locked when the job is submitted. The range is unlocked when the job completes.
In the ctest, we need to manually create a range lock owner, otherwise, the job submission will be failed due to unknown range lock owner.
20250712-032026-zhewang-6d95af17ac9dcd38           compressed=True data_size=41276985 duration=5256693 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:59:07 sanity=False started=100000 stopped=20250712-041933 submitted=20250712-032026 timeout=5400 …

A BulkLoad Job Should Use One Range Lock

---

fdbcli/fdbcli.actor.cpp

This PR adds the `--no-history` command line option to `fdbcli`.
It implements the issue #12219

Added option --no-history to fdbcli (#12219)

---

fdbserver/workloads/MemoryLifetime.actor.cpp
fdbserver/workloads/QueuePush.actor.cpp
fdbserver/workloads/WriteDuringRead.actor.cpp

Fix MemoryLifetime workload and update remaining workloads with value as random string
Changes:
- In MemoryLifetime file, transaction was not resetting in the begining of the loop. As result it was retaining the value changes from previous loop's transaction and resulting in values mismatch when value is changed to random string. Initially because of value = "..." it didn't matter as value would always be the same.
- Updated all remaining workloads as random string.
100k correctness tests completed:
`  20250715-212420-ak_random_value-13649e8ba9d8009d   compressed=True data_size=41300258 duration=5501480 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:39:50 sanity=False started=100000 stopped=20250715-230410 submitted=20250715-212420 timeout=5400 …

Fix MemoryLifetime workload and update remaining workloads with value as random string

---

flow/Net2.actor.cpp
flow/SystemMonitor.cpp
flow/include/flow/SystemMonitor.h

Also add a comment suggesting that using the main thread for this is a bad idea.
Copied the metrics idioms from related stats.
To emit these stats it seems like we need to do lookup by name, using hard-coded strings.
If any of these strings have typos, I'm not sure it would be caught.
I manually confirmed by git diff | less and then typing in the two string constants and ensuring there were exactly two places where they were found.
Also, testing in progress:   20250722-220537-gglass-5b21e0dddb9c2a32            compressed=True data_size=41305257 duration=32016 ended=452 fail_fast=10 max_runs=100000 pass=452 priority=100 remaining=1 day, 0:13:34 runtime=0:06:36 sanity=False started=872 submitted=20250722-220537 timeout=5400 username=gglass

Add metrics to count how often we run TLS handshake on the main thread

---

flow/Net2.actor.cpp
flow/SystemMonitor.cpp
flow/include/flow/SystemMonitor.h

Rename existing (just-added) metrics to indicate that they are client-side.

Add server-side metrics for TLS handshakes on side threads and on the main thread. 

---

fdbserver/workloads/MemoryLifetime.actor.cpp
fdbserver/workloads/QueuePush.actor.cpp
fdbserver/workloads/WriteDuringRead.actor.cpp

Cherry pick #12250 
100k correctness tests:
`20250722-181121-ak_memory_7.4-df7415a29deeeb7d     compressed=True data_size=41225703 duration=5200055 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:16:24 sanity=False started=100000 stopped=20250722-192745 submitted=20250722-181121 timeout=5400 username=ak_memory_7.4
` 
1 test failing in tests/fast/DataLossRecovery.toml  - Not related to this PR

Fix MemoryLifetime workload and update remaining workloads (#12250)

---

documentation/sphinx/source/class-scheduling.rst

Update class-scheduling.rst
Fix a little typo in the python. Use ```print()``` instead of ```print```.

fix-typo-python-tutorial

---

fdbserver/include/fdbserver/workloads/ReadWriteWorkload.actor.h
fdbserver/include/fdbserver/workloads/workloads.actor.h
fdbserver/workloads/BulkLoad.actor.cpp
fdbserver/workloads/MemoryLifetime.actor.cpp
fdbserver/workloads/ReadWrite.actor.cpp
fdbserver/workloads/StreamingRangeRead.actor.cpp
fdbserver/workloads/StreamingRead.actor.cpp
fdbserver/workloads/Throughput.actor.cpp
fdbserver/workloads/WriteBandwidth.actor.cpp

Cherrypick #12221 
* Replace '...' with actual data
* Add zeroPaddingRatio Knob in simulation workloads.
* Refactor randomValue API to include in KVWorkload
* Addressed comments - Add const and remove valueString - not needed
---------
100k correctness tests:
`20250724-030208-ak_valueString_7.3-f0bd9232d12121bd compressed=True data_size=35183640 duration=6453667 ended=100000 fail=2 fail_fast=10 max_runs=100000 pass=99998 priority=100 remaining=0 runtime=1:00:16 sanity=False started=100000 stopped=20250724-040224 submitted=20250724-030208 timeout=5400 username=ak_valueString_7.3`
Failing tests not related to this change - 
```
Results for test ensemble: 20250724-030208-ak_valueString_7.3-f0bd9232d12121bd
Ensemble stopped
RandomSeed="526754425" …
```

Replace '...' with actual random data in simulation workloads (#12221)

---

contrib/Joshua/scripts/correctnessTest.sh
contrib/TestHarness2/README.md
contrib/TestHarness2/analyze_determinism_failure.py
contrib/TestHarness2/test_harness/run.py
contrib/joshua_logtool.py

Previous the second run would overwrite the logs from the first run.
The below also includes a hefty edit of the
contrib/TestHarness2/README.md that fills out the example, removes joshua context specifics, and adds section on this new saving of the determinacy runs.
This is https://github.com/apple/foundationdb/pull/12184 but simplified, only focused on the determinacy check.

When the determinacy check runs, save both sets of logs.

---

fdbrpc/ReplicationPolicy.cpp
fdbrpc/include/fdbrpc/ReplicationUtils.h
flowbench/BenchSelectReplicas.cpp

This benchmark for the `selectReplicas` function tests triple and double replica topologies and sets the policy's fault domain (aka locality_zoneid) to be the "rack". Arguments to the test try varying numbers of "already chosen" servers. The intention is to test two cases
1. too few "already chosen" servers, so the code selects "additional" servers from the locality's pool until the desired replication count is met. 
2. enough "already chosen" servers, and there is no need to select "additional" servers. …

benchmark for selectReplicas function

---

fdbbackup/backup.actor.cpp

Pass encryption file name to backup to encrypt backup files locally.
1. Ran local cluster and supplied workload to add some key values to database.
2. Started backup agent - 
` backup_agent --cluster_file ./loopback-cluster/fdb.cluster  & `
3. Create a key : 
`openssl rand 32 > key`
4. Ran fdbbackup :
` fdbbackup start -d file:///root/local_testing/backup -C ~/local_testing/loopback-cluster/fdb.cluster --encryption-key-file ~/local_testing/key  --log --logdir .`
5. Checked the files inside backup directory. Before this change files were not encrypted and after this fix, all files (kvranges, logs, snapshots) shows encrypted.
6. fdbrestore completed successfully :
`fdbrestore start -r  file:///root/local_testing/backup/backup-2025-07-31-18-24-29.748382/ --dest-cluster-file …

Pass encryption file name to backup to encrypt backup files locally

---

fdbbackup/tests/s3_backup_test.sh
fdbclient/ClientKnobs.cpp
fdbrpc/AsyncFileEncrypted.actor.cpp
fdbrpc/include/fdbrpc/AsyncFileEncrypted.h

When backup encyrption is enabled for S3, it gives an error - `Range missing `because mutation_log_type is 1 bytes and encryption tries to read beyond the file size.
```
<Error><Code>InvalidRange</Code><Message>The requested range is not satisfiable</Message><RangeRequested>bytes=4096-8191</RangeRequested><ActualObjectSize>1</ActualObjectSize><RequestId>898ZDME8HDHCWZ3Y</RequestId><HostId>WiW+gUJF90iu+7BgSRiYuNPOU1EgXw6H7m3Bb8vF5IWY92ACR03q1Y0fy55PUMV+8SwsT3i12eI=</HostId></Error>
```
When encryption is enabled, the code path is:
`AsyncFileReadAheadCache` → `AsyncFileEncrypted` → `AsyncFileS3BlobStoreRead`
The `AsyncFileReadAheadCache` tries to read 1048576 bytes starting at offset 0.
The `AsyncFileEncrypted` layer reads data in fixed-size encrypted blocks (4096 bytes based on …

Backup encryption fix on S3

---

fdbrpc/FlowTransport.actor.cpp
flow/Net2.actor.cpp
flow/SystemMonitor.cpp
flow/include/flow/SystemMonitor.h

20250808-212207-zhewang-db155ea4951cb7f9           compressed=True data_size=41377748 fail_fast=10 max_runs=100000 priority=100 sanity=False submitted=20250808-212207 timeout=5400 username=zhewang

Add connection counters

---

fdbrpc/FlowTransport.actor.cpp
flow/Net2.actor.cpp
flow/SystemMonitor.cpp
flow/include/flow/SystemMonitor.h

[Release-7.3] Cherrypick Add connection counters (#12292)

---

fdbserver/TLogServer.actor.cpp

As title. See #12298 for details.
Main branch 100K Joshua: `20250813-230939-praza-main-743-tag-v216-f43-346f6a56cc3980e7 compressed=True data_size=40330757 duration=5860050 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:08:54 sanity=False started=100000 stopped=20250814-001833 submitted=20250813-230939 timeout=5400 username=praza-main-743-tag-v216-f43c339635295f6548ec255e8b42c0cbda2dac00`
The 1 failure is not related. It's a DrUpgrade restart test which is failing because db is not quite at the end, due to dd being stuck. The change here should not change simulation determinism, so I actually went back to the previous change, re ran the test, and it ended up with the same failure, proving that this change is not causing the failure. 
The …

Forward port #12298: Revert condition for releasing memory from tlog's versionLocation data structure 

---

fdbserver/Status.actor.cpp
flow/Trace.cpp

Cherry-pick #12310 to main branch. See that PR for description of the issues. 
100K: `20250819-180858-praza-trace-bugs-v1-main-f6-c0f6aae1349aa899 compressed=True data_size=40325921 fail_fast=10 max_runs=100000 priority=100 sanity=False submitted=20250819-180858 timeout=5400 username=praza-trace-bugs-v1-main-f63020d998062d2691d25982e925578c6cd7c591`. Currently running.

[main branch] Reduce frequency of two categories of Sev30s

---

fdbrpc/FlowTransport.actor.cpp

`pingLatencyLogger` iterates all peers and check one peer every 3s. This event has become very frequent for logging, thus reduced.

Suppress PingLatency events

---

fdbserver/Status.actor.cpp
flow/Trace.cpp

As part of 7.4 qualification, we noticed two categories of frequent Sev30's:
1. `Type=StorageServerStatusJson` with `MissingAttribute=BytesStored`. This can happen if storage server sends an incomplete metrics response to cluster controller as part of status json generation. The fix here is to reduce the frequency of this trace event. Currently, it's suppressed for 5 sec.
2. `Type=SuppressionFromNonNetworkThread` with `Event=TLSPolicySuccess`. This is interesting because here we have a non-suppressable verbose event that gets triggered when we try to suppress another event. It's also interesting because the intent seems to be that we do not expect any suppressions from a non-fdbmain thread. The intent makes sense if the non-fdbmain threads are not doing much, because if they are, by law …

Reduce frequency of two categories of Sev30s

---

tests/CMakeLists.txt

Testing in progress:
20250820-172658-gglass-61aa1c93fba18c44            compressed=True data_size=41400570 duration=1400375 ended=30328 fail_fast=10 max_runs=100000 pass=30328 priority=100 remaining=0:55:37 runtime=0:24:13 sanity=False started=32660 submitted=20250820-172658 timeout=5400 username=gglass

Disable BlobRestoreTenantMode.toml which is flaky, but tests stuff we do not use

---

bindings/go/src/fdb/errors_test.go
bindings/go/src/fdb/generated.go

Found by nightly. Manually validate the fixes:
```
Test project /root/cbuild_output
Start  2: test_venv_setup
1/2 Test  #2: test_venv_setup ..................   Passed    2.26 sec
Start 64: fdb_go_test
2/2 Test #64: fdb_go_test ......................   Passed    3.45 sec
Test project /root/cbuild_output
Start 66: update_bindings_go_src_fdb_generated_go
1/1 Test #66: update_bindings_go_src_fdb_generated_go ...   Passed    0.00 sec
100% tests passed, 0 tests failed out of 1
Total Test time (real) =   0.01 sec
``` …

Fix go ctest failures [release-7.3]

---

flow/TLSConfig.actor.cpp
flow/include/flow/TLSConfig.actor.h

Cherrypick https://github.com/apple/foundationdb/pull/12014

[Release-7.4] Cherry-pick TLS should accept same key with different values (#11763)

---

fdbclient/NativeAPI.actor.cpp

cherrypick #12328
handleTssMismatches(DatabaseContext* cx) uses a pointer to DatabaseContext object, which can be destroyed when "tr" is reset within this actor. However, the actor can't be destroyed because it's on the stack. Introducing this delay gives a chance to cancel the actor.
20250826-165641-jzhou-a1cbfc05926fdfd9             compressed=True data_size=59276546 duration=4833332 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:22:44 sanity=False started=100000 stopped=20250826-181925 submitted=20250826-165641 timeout=5400 username=jzhou
Interestingly, the failure is `-f ./tests/rare/ClogRemoteTLog.toml -s 870359747 -b off` with `ClogRemoteTLogCheckFailed` Sev40, which is not the crashing failure this PR fixed. …

Fix handleTssMismatches crashes. [release-7.4]

---

flow/SimpleCounter.cpp
flow/Trace.cpp
flow/include/flow/Trace.h
flow/include/flow/UnitTest.h

Expose validateField() from Trace.cpp and just call it directly from "unit tests" in SimpleCounter.cpp.  Add some
comments in various places about the unit test execution environment.  The updated test cases would catch the 
prior issue where they themselves manufacture counters with invalid label names.  Updated the tests to use 
hierarchical metrix names that get munged into compliant field names.
Unit test:
[root@gglass-dev-okteto-56b45ddbf4-kkwcl flow]# git log -n 1 
commit 4e5d9b2a846f0dcef38b61b208f5fd4cce5aaebc (HEAD -> tracenames, origin/tracenames)
Author: Gideon Glass <gxglassgithub@gmail.com>
Date:   Wed Aug 27 18:30:20 2025 -0700
always be munging metric names
[root@gglass-dev-okteto-56b45ddbf4-kkwcl flow]# !fdbserver
fdbserver -r unittests -f /flow/simplecounter …

Update SimpleCounter unit tests not to use metric names that break Trace.cpp simulation-only checks

---

design/tuple.md

This allocates tuple type codes for a length-prefixed bytes type, and an End of Tuple indicator.
A length-prefixed bytes type was desired as my use case involves indexing by hashes that are fixed length. This provides higher performance when decoding compared to the Byte String type which requires replacing and allocations, and eliminates the need for adding new custom type codes like the 64-bit ID in the future.
The end-of-tuple indicator was added to allow applications to use custom key encodings alongside tuple encoding without conflicts.
I have implemented this in my private fork of the Go bindings alongside an optimized Tuple decoder, and I intend to PR that separately later.

Allocate tuple type codes for length-prefixed bytes and end-of-tuple

---

flow/Platform.actor.cpp
flow/SystemMonitor.cpp

* Refactor ifdefs to make format_backtrace() be exposed for _WIN32, and remove WIN32 ifdefs in non-Platform.cpp code.
* In shell commands emitted by format_backtrace, change the addr2line command to specify the full path to the addr2line binary, to avoid people getting hung up by the broken shell alias in /root/.bashrc.  As far as I can tell this alias exists to invoke gcc- or clang-specific addr2line binaries, which is easy enough to solve in the .cpp code.
* Delete logic that naively appends "debug" related suffixes to the fdbserver binary name.  The code doesn't know if it's a debug binary or not, and if it's not, the most obvious solution is to rebuild everything.  Copying binaries around manually is not needed and the emitted commands shouldn't encourage this, as far as I can tell. …

Updates to Platform.cpp relating to format_backtrace

---

fdbclient/ManagementAPI.actor.cpp
fdbrpc/ReplicationPolicy.cpp
fdbrpc/ReplicationUtils.cpp
fdbrpc/include/fdbrpc/Replication.h
fdbrpc/include/fdbrpc/ReplicationPolicy.h
flowbench/BenchSelectReplicas.cpp

Cache PolicyAcross key lookups to improve selectReplicas performance
PR12301 added memoization for getValueViaGroupKey() calls in the PolicyAcross selectReplicas hot path. By caching the results of these expensive binary search operations, we avoid repeated lookups. This was enabled for simple policies like double/triple replication modes. This PR strengthens cache validation and invalidation:
- Adding lazy depth/maxdepth caching to replication policies
- Runtime pattern detection instead of explicit caching flags (avoids serialization problems from previous revision).
If this …

Optimize PolicyAcross key lookup performance with caching

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/ClusterController.actor.cpp

This to keep the naming consistent for gray failure knobs. 
Trivial change so should not cause any issues, but 100K results: 
```
20250915-004611-praza-rename-enable-remote--a9374ae6d006256d compressed=True data_size=40470937 duration=5636180 ended=100000 fail=2 fail_fast=10 max_runs=100000 pass=99998 priority=100 remaining=0 runtime=1:19:11 sanity=False started=100000 stopped=20250915-020522 submitted=20250915-004611 timeout=5400 username=praza-rename-enable-remote-log-router-knob-fa5b21bef9ba484e2c73a0bc6c72e2765bd157ed
```
Both failures are not related. One is an external timeout. The other is an assertion in client metric code, which should not be related to this PR change. This PR overall does not change any functional behavior of the code.
The general pull request guidelines can be …

Rename CC_ENABLE_REMOTE_LOG_ROUTER_MONITORING to CC_ENABLE_REMOTE_LOG_ROUTER_DISCONNECT_MONITORING

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/ClusterController.actor.cpp

Backport https://github.com/apple/foundationdb/pull/12368 to 7.4. 
7.4 100K: 
```
20250915-010636-praza-rename-enable-remote--dac8f683a687892a compressed=True data_size=40163172 duration=5744812 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:04:04 sanity=False started=100000 stopped=20250915-021040 submitted=20250915-010636 timeout=5400 username=praza-rename-enable-remote-log-router-knob-74-4aa3b61d605fddbea9140d82ccde576a487082c1
```

(7.4 Backport) Rename CC_ENABLE_REMOTE_LOG_ROUTER_MONITORING to CC_ENABLE_REMOTE_LOG_ROUTER_DISCONNECT_MONITORING

---

fdbserver/SimulatedCluster.actor.cpp

In toml11 3.0, comments were discarded by default, so this declaration was redundant. In toml11 ≥ 4.0, they are preserved by default, but opting out is more baroque. It doesn’t seem clear to me why discarding comments is specifically relevant here, so I’ve opted to simplify the code by using the default uniformly, but a version conditional would be possible if this is important.
Many major Linux distributions have already moved to toml11 ≥ 4.0, so this simplifies packaging. …

Fix the build with toml11 4.0

---

fdbserver/TagPartitionedLogSystem.actor.cpp

Version vector/Unicast specific: Restart recovery if the list of available tLogs change in such a way that the current in-progress recovery could stall.
More details: Let "listA" be the list of known locked tLogs of the current in-progress recovery. Suppose the list of known locked tLogs change and "listB" be the current list. If "listA" is not a subset of "listB" then there is a chance that the current in-progress recovery would stall, hence restart recovery (even if the recovery version hasn't changed).
We don't need to restart recovery in "main" in this case because the cursor logic tracks these changes (code: https://github.com/apple/foundationdb/blob/d45a17b6576b1dc246104155ff4777e7880b782e/fdbserver/LogSystemPeekCursor.actor.cpp#L1155) and can reset "bestServer" after that (code: …

Version vector related extensions to the recovery restart logic

---

fdbserver/SkipList.cpp

Replace MiniConflictSet std::vector<bool> with uint64_t word operations for 64x faster range set/query performance in conflict resolution.
The PR replaces the O(n) individual bit manipulations in MiniConflictSet() with O(n/64) word manipulations. The previous MiniConflictSet implementation performed bit-by-bit operations using std::vector. This is because std::vector<bool> is a specialized container that packs bits tightly but requires individual bit manipulation operations that cannot be vectorized / optimized.
When conflict sets grow large (many key boundary intervals), the O(range_size) bit-by-bit loops become expensive since each bit must be accessed individually through bit shifts and masks. That prevents the CPU from leveraging word-level operations possible with native integer …

Optimize conflict detection with word-level bitmap operations

---

cmake/AddFdbTest.cmake
tests/BGServerCommonUnit.toml
tests/BlobManagerUnit.toml
tests/CMakeLists.txt
tests/restarting/from_7.1.0_until_7.2.0/DrUpgradeRestart-1.txt
tests/restarting/from_7.2.0_until_7.3.0/ConfigureStorageMigrationTestRestart-1.toml
tests/restarting/from_7.2.0_until_7.3.0/ConfigureTestRestart-1.toml
tests/restarting/from_7.2.0_until_7.3.0/DrUpgradeRestart-1.toml
tests/restarting/from_7.2.4_until_7.3.0/UpgradeAndBackupRestore-1.toml

Fixed simulation tests that were running with an error.

Fixed errors in simulation tests

---

fdbbackup/tests/s3_backup_test.sh
fdbclient/BackupContainerFileSystem.actor.cpp

Added logic to return a clear error message when the backup and restore encryption keys do not match:
```
ERROR: Failed to read data. Verify that backup and restore encryption keys match (if provided) or 
the data is corrupted.
```
Because snapshot files are read first during restore, the check is implemented while reading/decrypting snapshot files. If the JSON parsing fails at this stage, it indicates either:
- an encryption key mismatch, or
- corrupted snapshot data.
**Example: Snapshot file without encryption**
```
{"beginVersion":1839108,"endVersion":1853166,"files":["kvranges/snapshot.000000000001793504/0/range,1842360,7012f82e5a32aa06695e7c3c302384fb,1048576",
"kvranges/snapshot.000000000001793504/0/range,1853166,5698a5782a1eaa145bd791bb0d29bbc0,1048576", …
```

Update error message for encryption key mismatches between backup and restore

---

fdbserver/ClusterRecovery.actor.cpp
fdbserver/TagPartitionedLogSystem.actor.cpp
flow/include/flow/genericactors.actor.h

Whenever we've a recovery that takes too long, TraceEvents are invaluable to debug why it took so long. The recovery state trace event generally is enough to point out what phase takes long. For initializing_transaction_servers phase, we can have better observability to do fine grained analysis. This PR adds trace events in that direction. 
A common pattern of waiting in FDB is:
```
wait(A && B && C)
```
In such cases, having a trace event _after the entire_ wait is not good enough if we're stuck in A or B or C. To _easily_ have _finer grained_ trace events, I was thinking to have a library function:
```
Future<T> observable(Future<T> in, const std::string& msg)
```
It turns out that genericactor.actor.h already had traceAfter, which was similar to my implementation. No one is using …

Long recovery observability (phase: initializing_transaction_servers)

---

tests/CMakeLists.txt

Disable BlobGranule-related tests as they are currently failing and this feature is not supported internally.
We can re-enable these tests once the issues/tests are fixed.
Completed 100k tests:
` 20250924-025519-ak_pr-35bdab83db83ed76             compressed=True data_size=41578667 duration=9021200 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:00:06 sanity=False started=100000 stopped=20250924-035525 submitted=20250924-025519 timeout=5400 username=ak_pr`

Disable BlobGranuleTests in Simulation

---

fdbbackup/backup.actor.cpp
fdbclient/BackupContainer.actor.cpp
fdbclient/BackupContainerFileSystem.actor.cpp
fdbclient/BackupContainerLocalDirectory.actor.cpp
fdbclient/BackupContainerS3BlobStore.actor.cpp
fdbclient/ClientKnobs.cpp
fdbclient/FileBackupAgent.actor.cpp
fdbclient/azure_backup/BackupContainerAzureBlobStore.actor.cpp
fdbclient/include/fdbclient/BackupContainer.h
fdbclient/include/fdbclient/BackupContainerFileSystem.h
fdbrpc/AsyncFileEncrypted.actor.cpp
fdbrpc/include/fdbrpc/AsyncFileEncrypted.h
fdbserver/workloads/AtomicRestore.actor.cpp
fdbserver/workloads/Backup.actor.cpp
fdbserver/workloads/BackupAndParallelRestoreCorrectness.actor.cpp
fdbserver/workloads/BackupCorrectness.actor.cpp
fdbserver/workloads/BackupCorrectnessPartitioned.actor.cpp
fdbserver/workloads/IncrementalBackup.actor.cpp
fdbserver/workloads/Restore.actor.cpp
fdbserver/workloads/RestoreBackup.actor.cpp
fdbserver/workloads/RestoreMultiRanges.actor.cpp
fdbserver/workloads/SubmitBackup.actor.cpp
tests/rare/BlobRestoreBasic.toml
tests/rare/BlobRestoreTenantMode.toml
tests/rare/BlobRestoreToVersion.toml
tests/slow/BackupNewAndOldRestore.toml
tests/slow/BackupOldAndNewRestore.toml

Cherrypick in order: 
https://github.com/apple/foundationdb/pull/12287  
https://github.com/apple/foundationdb/pull/12289
https://github.com/apple/foundationdb/pull/12293
https://github.com/apple/foundationdb/pull/12354
https://github.com/apple/foundationdb/pull/12375
Completed 500K Simulation tests:
`
20250923-214132-ak_bk1-d79919c41efab1a1            compressed=True data_size=41383872 duration=23066098 ended=500000 fail=3 fail_fast=10 max_runs=500000 pass=499997 priority=100 remaining=0 runtime=3:25:35 sanity=False started=500000 stopped=20250924-010707 submitted=20250923-214132 timeout=5400 username=ak_bk1
`

Backup Encryption Fixes and Metadata Changes (#12287)

---

bindings/c/CMakeLists.txt

This broke because of https://github.com/apple/foundationdb/pull/12357. From the build logs:
```
FAILED: share/foundationdb/libc_workloads.dylib : && /Library/Developer/CommandLineTools/usr/bin/cc -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk -dynamiclib -Wl,-headerpad_max_install_names -o share/foundationdb/libc_workloads.dylib -install_name @rpath/libc_workloads.dylib bindings/c/CM akeFiles/c_workloads.dir/test/workloads/CWorkload.c.o && : Undefined symbols for architecture x86_64: "_fdb_future_set_callback", referenced from: _workload_start in CWorkload.c.o ld: symbol(s) not found for architecture x86_64
```
More context: https://github.com/apple/foundationdb/pull/12390/files#r2377140614. 
This PR fixes that. Test is CI not giving the same error as …

Fix mac build

---

fdbclient/DatabaseContext.actor.cpp
fdbclient/StorageServerInterface.cpp
fdbrpc/FlowTransport.actor.cpp
fdbrpc/include/fdbrpc/FlowTransport.h
fdbrpc/include/fdbrpc/LoadBalance.actor.h
fdbrpc/include/fdbrpc/QueueModel.h
fdbrpc/include/fdbrpc/SimulatorKillType.h
fdbrpc/include/fdbrpc/fdbrpc.h
fdbrpc/include/fdbrpc/simulator.h
fdbrpc/sim2.actor.cpp
flow/include/flow/ChaosMetrics.h
flow/include/flow/network.h

Small changes accumulated while reading through a bunch of files in fdbrpc (mostly).
Throughout: add FIXME comments where it would be useful to have a comment explaining something or suggesting a change of some kind.
Several places: rename a variable to get a better name
A few places: delete code that has been commented out for > 5 years
A few places: delete useless or apparently out of date, incorrect comments
One place: delete a function that has no callers
One place: reorder methods, listing them in the order which users are to call them (i.e. the natural order for explanation)
One or more places: delete unneeded FIXME comments
network.h: put the function comments *before* the functions they describe

Misc small changes and FIXME comment additions from reading fdbrpc code

---

fdbserver/TLogServer.actor.cpp

When clients peek data for a specific tag, the log server:
1. Counts how many versions contain data for that tag (versionCount)
2. Records this count as a latency/performance measurement in the LatencySample associated with that tag
3. Uses this data for monitoring and performance analysis
Instead of doing separate map operations to check if a tag exists, insert if needed, and then retrieve the LatencySample, we do all that in one try_emplace() call to create a new LatencySample for a new tag, or return the existing LatencySample for an existing tag. This reduces the number of tree traversals in std::map from 3 to 1.
100K pass `20250930-135027-dlambrig-a039c1865693d9af `
The general pull request guidelines can be found [here](https://github.com/apple/foundationdb/wiki/FoundationDB-Commit-P …

Optimize peekVersionCounts to use single map op instead of three lookups.

---

fdbrpc/HTTP.actor.cpp
fdbrpc/include/fdbrpc/HTTP.h
fdbserver/MockS3Server.actor.cpp
fdbserver/RESTKmsConnector.actor.cpp
fdbserver/RESTSimKmsVault.actor.cpp
fdbserver/include/fdbserver/MockS3Server.h

Support HEAD range requests.
Made mocks3 storage global rather than instance-based.
Enabled some tests disabled in simulation; required some fixups.
20251002-143002-stack-8f737ba026f25da9             compressed=True data_size=41596786 duration=5769725 ended=100000 env=username=stack2 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:58:33 sanity=False started=100000 stopped=20251002-152835 submitted=20251002-143002 timeout=5400 username=stack

Add HTTP range header support to mocks3

---

fdbserver/ConsistencyScan.actor.cpp
fdbserver/workloads/ConsistencyCheckUrgent.actor.cpp

DatabaseContext maintains a mapping of storage server interface UIDs to the corresponding storage server tags. NativeAPI APIs populate this (UID -> tag) map in DatabaseContext and also make use of it while reading data from storage servers (note that version vector maintains a mapping of storage server tags to their latest commit versions, and storage server read APIs take storage server interface UIDs as input). 
Consistency checker code doesn't use NativeAPI APIs, and uses direct storage server RPCs to read data from storage servers. This PR extends the consistency checker code to provide the (UID -> tag) mapping in DatabaseContext so the code can use the version vector APIs to fetch the latest commit versions of storage servers while they make read calls to storage servers.
Joshua id …

Extend consistency checkers to be compatible with version vector

---

fdbclient/FileBackupAgent.actor.cpp

Decode range file interpreting keys and values bug fix.

Decode range file interpreting keys and values bug fix.
