documentation/sphinx/source/release-notes.rst, fdbserver/OldTLogServer_6_0.actor.cpp, fdbserver/QuietDatabase.actor.cpp, fdbserver/QuietDatabase.h, fdbserver/TLogServer.actor.cpp, fdbserver/workloads/ConsistencyCheck.actor.cpp, fdbserver/workloads/workloads.actor.h
fix: the tlog would not pop data from the disk queue after a storage server was removed, because the tag still exists in memory on the logs
fix: we could incorrectly make data durable if eraseMessagesFromMemory was in progress while running updatePersistentData
the quiet database check now ensure that tlogs have no more than 30 seconds of versions unpopped from the disk queue
=> The disk queue files on tlogs would grow after removing storage servers

documentation/sphinx/source/api-c.rst
The C documentation used a bunch of cross-references to types, variables, and macros that we didn't define in our documentation. This didn't break the documentation, but it had the effect of making variables that did have links look the same as those that do not. I've switched these to use normal code formatting instead.
=> Docs: remove invalid C domain cross references

fdbserver/TLogServer.actor.cpp
If a removed storage server was popped to exactly the persistDataVersion on a TLog; its disk queue file would grow indefinitely
=> fixed a very rare bug would could cause files sizes to grow on TLogs

tests/SnowflakeJenkins
After all testing iterations are complete, run sql_create_report to generate the sql
file and (for now) archive it with the job.
Some additional changes to re-use virtualenv directories, and to better archive logs, in the eventuality that a test passes
SNOW-78373
=> Add sql_create_report call to generate sql file

documentation/sphinx/source/downloads.rst
The links to the Ubuntu packages were pointing to 6.1.7 instead of to 6.1.8 due to (I assume) a typo when updating the links as part of the 6.1.8 release.
=> Fix Ubuntu 6.1.8 links

flow/Platform.cpp
Remove the unwanted include of sys/wait.h in Platform.cpp.
=> windows build fix : del sys/wait.h in Platform.cpp

bindings/go/src/fdb/directory/directory.go, bindings/go/src/fdb/directory/directoryLayer.go
This pull requests changes common directory errors to public package level variables for easy comparison. This allows user code to check for obvious error, like an directory that does not exist when opening:
```
d, err := directory.Open(tx, []{"table"}, l)
if err != nil {
if err == directory.ErrDirNotExists {
return nil, errors.New("table not found")
}
// ...
}
```
=> change common directory errors for easy comparison

flow/Trace.h
The use of `auto` hid that TraceableString<T>::begin(value) was a signed
char, and therefore `*iter` was -1, and -1/16 is 0.
Thus, a 0xFF byte was printed as \x0f.  Forcing it to an unsigned type
makes it correctly become \xff.
=> Fix printable() being incorrect for bytes >127.

flow/Platform.cpp
Because our supported build environments no longer include Ubuntu 14.04,
and this is causing problems with libc++-based builds.
=> Remove a horrible hack aiming at Ubuntu 14.04's libstdc++_pic.

fdbclient/VersionedMap.h, fdbserver/storageserver.actor.cpp, flow/FastAlloc.h
With C++17, nextFastAllocatedSize can be made much more readable.
=> Refactor NextFastAllocatedSize to be constexpr function

documentation/sphinx/source/cap-theorem.rst, documentation/sphinx/source/features.rst
Fix a couple of small typos in the docs:
1. In CAP Theorem, [What does choosing Availability mean?](https://github.com/apple/foundationdb/blob/3b86576b69aba565d4c2b8ab509ae87d155c6c80/documentation/sphinx/source/cap-theorem.rst#what-does-choosing-availability-mean), second paragraph, I think "unable communicate" should be "unable *to* communicate"
2. In Features, [Ordered Key-Value API](https://github.com/apple/foundationdb/blob/3b86576b69aba565d4c2b8ab509ae87d155c6c80/documentation/sphinx/source/features.rst#ordered-key-value-api), first paragraph, I think there should be a closing bracket
=> Small typos

bindings/c/test/mako/mako.c, bindings/c/test/mako/mako.h
Stupid bug was introduced in the last minute retry logic changes.
This PR fixes that.
=> Fix retry logic in mako benchmark

fdbserver/FDBExecHelper.actor.cpp
The windows build is currently broken, and I believe this gets it working again. Once we are able to resolve the actual problem, we can reenable this code.
=> Temporarily remove boost usage from FDBExecHelper

ACKNOWLEDGEMENTS, documentation/CMakeLists.txt, documentation/sphinx/Makefile, documentation/sphinx/conf.py, documentation/sphinx/extensions/rubydomain.py, documentation/sphinx/requirements.txt
Sphinx documentation builds will now fail if there are warnings.
This introduces a copy of the rubydomain extension with some modifications to eliminate warnings that it generated.
=> Sphinx convert warnings to errors

fdbclient/NativeAPI.actor.cpp, fdbclient/NativeAPI.actor.h
FDB clients talk to coordinators to monitor the leader, and then ask
them for proxies. Once proxies are known, the clients still keep
talking to coordinators. This patch, stops this monitoring and
reconnects to coordinators only if one of the proxy is no longer
available.
=> Monitor leader only when proxies are unknown or any dies

fdbclient/MultiVersionTransaction.actor.cpp, fdbclient/MultiVersionTransaction.h, fdbclient/SystemData.cpp, fdbrpc/FlowTransport.actor.cpp, fdbserver/LogSystem.h, fdbserver/LogSystemPeekCursor.actor.cpp, fdbserver/TLogServer.actor.cpp, fdbserver/storageserver.actor.cpp, fdbserver/workloads/ClientTransactionProfileCorrectness.actor.cpp, flow/Net2.actor.cpp, flow/ProtocolVersion.h, flow/serialize.cpp, flow/serialize.h
This fixes #1214
The basic idea is that ProtocolVersion is now its own type. This
alone is an improvement as it makes many things more typesafe. For
each version, we can now add breaking features (for example Fearless).
After that, there's no need to test against actual (confusing) version
numbers. Instead a developer can simply test
`protocolVersion->hasFearless()` and this will return true iff the
protocolVersion is newer than the newest version that didn't support
fearless.
=> Make protocol version a type

documentation/sphinx/source/client-testing.rst, fdbclient/NativeAPI.actor.cpp, fdbclient/NativeAPI.actor.h, fdbclient/vexillographer/fdb.options, fdbserver/SimulatedCluster.actor.cpp, fdbserver/fdbserver.actor.cpp, flow/flow.cpp, flow/flow.h
This PR will add a special client side buggify. The overall idea is that a user can enable this client-side buggify to test client libraries and layers.
If enabled, the client will start throwing errors with a configurable probability. This way an application or layer implementer can test that her exception handling works correctly.
=> Overall framework and first buggify entries

cmake/ConfigureCompiler.cmake
pass -fno-omit-frame-pointer as we otherwise see broken back traces.
This should fix #1631 as well.
=> Fix backtraces

bindings/bindingtester/bindingtester.py
The binding tester was taking the min() of a list of tuples, but that could fail if the tuple contained incomparable types. Instead, use fdb.tuple.compare() to do the comparison.
=> Use fdb.tuple.compare to do tuple comparison in binding tester

tests/TestRunner/TestRunner.py
HugeArenaAllocation in particular is a bit spammy of backtraces,
intentionally, and is causing testing in the CI to time out.
=> Remove symbolication from ctest, as a large number of backtraces times out tests

fdbclient/FDBTypes.h
Thus making spill-by-reference and crc32c disk queue checksums the default.
=> Bump the default log_version to 3 and log_spill to 2

fdbserver/Knobs.cpp
10s is a bit short for starting data distribution, which is rather
expensive.  60s is a bit more reasonable.
=> Increase how long FDB will wait before starting DD to repair data loss.

fdbclient/NativeAPI.actor.cpp, fdbclient/NativeAPI.actor.h, fdbserver/workloads/SnapTest.actor.cpp
NativeAPI did not have a retry logic implemented and a partial implementation was done, this change was to revert the partial implementation.
=> Undo the partial retry implementation in NativeAPI

flow/Platform.cpp
Our Windows build broke as one line in a recent PR was changed to use the wrong definition for determining the Windows platform. This switches to the same definition used elsewhere on the file.
There's another line, that is kind of weird, as it also uses the wrong definition:
https://github.com/apple/foundationdb/blob/b92e6b09ad67fa382e17500536fd13b10bb23ede/flow/Platform.cpp#L2746
That line hasn't been changed since the original OSS release two years ago, so under the "don't fix what's not broke" idea, I've left it the same, but I could be convinced to change it as well.
=> Fix Windows build caused by incorrect definition check

fdbrpc/FlowTransport.actor.cpp, fdbrpc/FlowTransport.h, flow/Knobs.cpp, flow/Knobs.h
On the sending side, a large packet is split into smaller pieces. On the
receiving side, use packet length to allocate buffer to avoid multiple memcpy
and allocations.
This fixes #1466 and #1680 .
=> Better handling for large packets

build/docker-compose.yaml, cmake/ConfigureCompiler.cmake
This way you can run with -DCMAKE_COLOR_MAKEFILE=0 in CI and not get
garbled escape characters in your log
=> Remove -fdiagnostics-color=always

fdbserver/WorkerInterface.actor.h, fdbserver/storageserver.actor.cpp, fdbserver/worker.actor.cpp
Sorry, had to open a new PR on this issue
Issue we(Wavefront) have:
#53 
Solution:
Based on branch **[mater](https://github.com/apple/foundationdb)**
During recovery process for memory storage engine, we’ll check periodically whether we can safely remove this storage engine (by calling canRemoveStorageServer() method). If the cluster is healthy then abort recovery and join in as an empty node. Otherwise, keep going until it’s done.
=> Recovery Optimization

documentation/sphinx/source/release-notes.rst, fdbserver/DataDistribution.actor.cpp, fdbserver/QuietDatabase.actor.cpp
This PR solves issue #1754.
When team collection computes the number of servers (and machine) teams, it also considers the number of teams each server (and team) needs to reach the DESIRED_TEAMS_PER_SERVER.
When new machine is added to the cluster, no matter how many machine teams the cluster already has, the new logic will re-kick the logic of building teams.
Simulation test is ongoing...
=> [Release 6.1 Patch] Ensure new added machines are used to build teams

fdbserver/DataDistribution.actor.cpp
When interface changes, we set doBuildTeams to true only when
the interface location changes.
=> StorageServerTracker:Do not always set doBuildTeams

fdbserver/KeyValueStoreMemory.actor.cpp
This should result in some speedup.  I haven't measured how much for memory storage engine, but CPU usage should decrease at least.
=> Memory storage engine to use crc32c DiskQueue by default (in 6.2).

fdbserver/TagPartitionedLogSystem.actor.cpp
It is implied that knownCommittedVersion (KCV) <= recoveryVersion. This change explicitly does a Sev40 if KCV > recoveryVersion. KCV is determined as the max of all the KCVs of the TLogs.
Once snapshot v2 code is enabled, this Sev40 will be removed, because we can recover with KCV > recoveryVersion, because the tlogs and snapshots can get snapshotted at different versions with many seconds or minutes apart.
=> sev40 if knownCommittedVersion > recoveryVersion

fdbcli/fdbcli.actor.cpp, fdbrpc/ReplicationPolicy.h, fdbrpc/fdbrpc.h, flow/Arena.h, flow/ObjectSerializerTraits.h, flow/flat_buffers.cpp, flow/flat_buffers.h, flow/serialize.h
This is part of #1676 . 
This PR introduces the `--object-serializer` flag to fdbcli for testing purposes, and the plan is to remove all occurrences of `--object-serializer`, when making it the default setting.
CC @mpilman
=> Flatbuffers part2

fdbserver/workloads/Cycle.actor.cpp
So that it can be used in the real world for consistency checking of backup and DR.
See https://forums.foundationdb.org/t/test-backup-and-restore-on-fdb-6-1-8-cluster/1504
=> Add a checkOnly parameter to Cycle workload.

fdbserver/DataDistribution.actor.cpp
The redundant team removed by teamRemover will not exist
in the global teams data structure. So we will not find
the redundant team from shard-to-team mapping in the system key.
Before this change, teamTracker marks such team as PRIORITY_TEAM_UNHEALTHY.
With this change, it marks it as PRIORITY_TEAM_REDUNDANT.
This helps us to understand from trace events whether or not a shard relocation is caused by the fact that a redundant team is removed by teamRemover actor.
=> TeamTracker:Set redundant team priority as PRIORITY_TEAM_REDUNDANT

fdbbackup/backup.actor.cpp, fdbcli/fdbcli.actor.cpp, fdbclient/DatabaseContext.h, fdbclient/NativeAPI.actor.cpp, fdbclient/NativeAPI.actor.h, fdbclient/ThreadSafeTransaction.actor.cpp, fdbserver/Restore.actor.cpp, fdbserver/tester.actor.cpp, fdbserver/worker.actor.cpp, flow/Stats.actor.cpp, flow/Stats.h
Add a random UID to TransactionMetrics in case a client opens multiple connections and also a field to indicate whether the connection is internal. Convert some of the metrics to our Counter object instead of running totals.
=> Improve TransactionMetrics

fdbserver/OldTLogServer_6_0.actor.cpp, fdbserver/TLogServer.actor.cpp
When onlySpilled transitions from true (don't peek memory) to false (do
peek memory) as part of a parallel peek, we'll end up wasting the rest
of the replies because we'll honor their onlySpilled=true setting and
thus not have any additional data to return.
Instead, we thread the onlySpilled back through in the same way that the
ending version of the last peek is used overrides the requested starting
version of the next peek.  This simulated the same behavior that the
client has, where the value of onlySpilled that we reply with comes back
in the next request.
I haven't actually seen it be a problem, but this should help make sure
the onlySpilled transition when catching up doesn't ever cause any ill
effects if a process starts riding the line between onlySpilled settings.
Original PR was …
=> Improve the behavior of parallelPeekMore+onlySpilled.

bindings/python/tests/size_limit_tests.py
Both key and value has to be of type bytes.
=> Fix python3 binding test failure

documentation/sphinx/source/mr-status-json-schemas.rst.inc, fdbclient/Schemas.cpp, fdbserver/Status.actor.cpp, fdbserver/storageserver.actor.cpp
This value is also reported in status, addressing issue #1698. Because counter values are
integers, we must report rejections per million instead of local rate
as a double between 0.0 and 1.0.
=> Track the local ratekeeper rate in status

cmake/ConfigureCompiler.cmake
This is a suggestion to resolve #1780
This change introduces a new cmake flag `RELATIVE_DEBUG_PATHS`.
If this flag is set or FDB is compiled with `-DFDB_RELEASE=ON`,
the resulting binary will have debug information using relative
file paths to source files. This simulates the behavior of the
old build system but might break local debugging (making the
debugger aware of build and source directory will be required).
=> Compile relative paths into the debug info

documentation/sphinx/source/release-notes.rst, fdbserver/MoveKeys.actor.cpp, fdbserver/MoveKeys.actor.h
This allows a new data distributor to update the owner lock so that older
data distributor can't hang on to the lock. This fixes #1821
=> Make takeMoveKeysLock() update move key owner lock

bindings/java/CMakeLists.txt
Porting changes that @amotivala made in FDB 3 here to expose the version information (plus a bit more) through the MANIFEST file for the java bindings.  This can allow an application to check that it is using the correct version.
=> Add more information to the java binding jar's MANIFEST.

fdbserver/OldTLogServer_4_6.actor.cpp, fdbserver/OldTLogServer_6_0.actor.cpp, fdbserver/TLogServer.actor.cpp, fdbserver/storageserver.actor.cpp, flow/genericactors.actor.h
Because no one expects the comma overload.
Now, this is a slightly trickier change than it looks.  Before this change, one could write:
```
std::vector<int> z;
z , 1;
doSomethingWith(z);
```
And after this change, this is still valid, compile-able C++.  It just does something different, and `doSomethingWith(z)` will get an empty vector instead of a one element vector.
So I added `ASSERT(false)` to these, ran simulation on that, and then removed them.  Nothing in simulation crashed, so it looks like these are unused, thankfully.
=> Remove `operator , (vector<T>, T)` as an append operator.

fdbserver/MasterProxyServer.actor.cpp
This can help debugging where large transactions are coming from.
This is for #1466.
=> Log large transactions at proxy

fdbserver/workloads/BulkLoad.actor.cpp, fdbserver/workloads/Cycle.actor.cpp, tests/fast/TxnStateStoreCycleTest.txt
* Changes BulkLoad workload to support a specific volume of data to load
* Changes BulkLoad and Cycle to correctly handle \xff in keyPrefix
* Adds BulkLoad to TxnStateStoreCycleTest
I keep cherrypicking this commit around because all of my txnStateStore performance tests (e.g. #1869) depend on it to provide the "Bulk Load 500MB into txnStateStore" functionality.
=> Add ability to bulk load data into TxnStateStore

flow/Trace.cpp, flow/Trace.h
This change fixes the problem of accessing the current time from multiple threads by having non-network threads use a real-time clock for trace events.
This will add cost to trace logging on non-network threads as well as on the network thread prior to the point when `setNetworkThread` is called. Because of that, we may want to consider whether this  approach is the best option.
=> Fix unsafe usage of now() function from multiple threads in trace logging.

documentation/sphinx/source/release-notes.rst, flow/FileTraceLogWriter.cpp, flow/FileTraceLogWriter.h
This resolves #1825
The basic idea is that we prefix every sequence number with its with,
separated by a dot. That way the filename length isn't increased
drastically (unlike using a fixed whidth number with 0-padding)
and the file names will be lexicographically ordered.
The main motivation for this case is to make it easier to investigate issues
in traces through the command-line. Without this change a command like this:
```
grep ProcessMetrics *.xml | tail -1
```
won't necessary work as one would expect as the last trace-file in the list might not be the newest one.
=> Make trace files lexicographically ordered

fdbclient/MasterProxyInterface.h
Uninitialized memory is getting sent over the network, and valgrind is complaining. Fix that.
=> Fix uninitialized memory

fdbclient/ManagementAPI.actor.cpp
setDDMode disable enable disable - would not disable DD sometimes. setDDMode does not set the moveKeysLockWriteKey which can cause the above.
After takeMoveKeysLock notes down the moveKeysLockOwnerKey and the moveKeysLockWriteKey value, it monitors the above two in pollMoveKeysLock and checks if anything is changed, but setDDMode was not setting the moveKeysLockWriteKey and so a sequence like disable, enable and disable would not really disable DD unless the intermediate enable had a change in the moveKeysLockOwnerKey.
This will fix the issue #1865 .
=> setDDMode should set moveKeysLockWriteKey

flow/flow.h
Before this fix, the encoding of Void happens to 'work' in that this
implementation can both read and write it, but it is not a flatbuffers
message since it contains a invalid offset (the implementation 'works'
because it does not dereference that offset).
CC @mpilman
=> Fix Void flatbuffers serialization

fdbserver/ClusterController.actor.cpp
This was deleted during a code refactor in ef868f5. Because no tests were complaining, we didn't find this until now.
=> Add a monitorServerInfoConfig() call back

fdbserver/LogSystem.h, fdbserver/OldTLogServer_6_0.actor.cpp, fdbserver/TLogServer.actor.cpp, fdbserver/TagPartitionedLogSystem.actor.cpp
I'm getting really good at these 1 line changes that spiral out of control...
There's part of this that is a decently mechanical transformation of changing `txsTags==0` to `tLogVersion < V4`.
The other part of this is handling copying txnStateStore mutations between the Known Committed Version and the Recovery Version when configuring from V4 to V3.  This is code that didn't need to exist previously, because it wasn't possible to do.  We now force all sharded txsLocality tags to be copied to the preferred location for the txsTag.
I have this baking in correctness, so I'll updraft it in the morning if it's safe.
=> Make sharded txsTag upgradeable and downgradeable

fdbserver/MasterInterface.h, flow/network.h
With sharded txs tags, the master now receives data from transaction logs at an order of magnitude higher rate.  This is the intentional desires result of sharding the txs tag.  With a sufficient number of TLogs, the master will saturate its CPU time handling the peek responses.
Performance tests revealed some unstable oddities in how long a recovery would take, which was eventually root caused to a priority inversion between TLogRejoin requests (happening at TaskPriority::Default) and processing TLog peek replies (happening at TaskPriority::TLogPeekReply).
Once peek replies saturate the CPU, the master would proceed to ignore further TLogRejoin messages.  TLogRejoin is what marks a TLog as available to the failure monitor, which is also what decides between a ServerPeekCursor and a …
=> Raise the priority of TLogRejoin above TLogPeekReply

documentation/sphinx/source/release-notes.rst, fdbcli/fdbcli.actor.cpp
Fault tolerance reports in terms of zones unless machine ID matches zone ID. Resolves #1420, partially completes the items for #1421 (this doesn't change the status field names).
=> Add reporting for zone count

fdbclient/StorageServerInterface.h, fdbserver/DataDistribution.actor.cpp, fdbserver/DataDistribution.actor.h, fdbserver/DataDistributionQueue.actor.cpp, fdbserver/StorageMetrics.actor.h, fdbserver/storageserver.actor.cpp, fdbserver/worker.actor.cpp, flow/ProtocolVersion.h
This will allow us to make data distribution decisions based on the current write loads to a process. 
Note that I also renamed `PhysicalMetrics` to `StorageMetrics` to reflect the fact that we weren't reporting just physical metrics.
=> Send bytes input rate to data distribution

documentation/sphinx/source/release-notes.rst, fdbserver/DataDistributionQueue.actor.cpp, fdbserver/Knobs.cpp, fdbserver/Knobs.h
Set the default to request new servers in \xff but not in main key space.
I made this one knob with 3 values, but if you prefer two separate knobs I can do it that way instead.
=> Add knob to control whether merges request new servers or not.

documentation/sphinx/source/mr-status-json-schemas.rst.inc, documentation/sphinx/source/release-notes.rst, fdbcli/fdbcli.actor.cpp, fdbclient/DatabaseConfiguration.h, fdbclient/Schemas.cpp, fdbclient/StatusClient.actor.cpp, fdbserver/SimulatedCluster.actor.cpp, fdbserver/Status.actor.cpp, tests/status/local_6_machine_no_replicas_remain.json, tests/status/separate_2_of_3_coordinators_remain.json, tests/status/separate_cannot_write_cluster_file.json, tests/status/separate_no_database.json
This is the potentially more contentious change related to #1421. It renames the fields in status that report fault tolerance in terms of the number of machines that can be lost into the more accurate number of zones that can be lost (note the actual number stays the same, just the name has changed).
=> Rename max_machine_failures_without_losing_X to max_zone_failures_without_losing_X in status.

fdbclient/NativeAPI.actor.cpp, fdbserver/DataDistribution.actor.cpp, fdbserver/DataDistributionQueue.actor.cpp, fdbserver/MasterProxyServer.actor.cpp, fdbserver/MoveKeys.actor.cpp, fdbserver/MoveKeys.actor.h
Currently, the mechanism available to disable DD is by setting a persistent state on the database.  This mechanism is mostly used by operators to stall DD. But, to disable and enable DD after a certain time interval or other event, across process restarts - needs additional logic.
To help such cases, a mechanism to disable DD and enable DD by setting an in-memory state is added. If there is a process re-start then the disable DD will be forgotten. In all other cases, it is the responsibility of the caller to disable and enable DD.  Additionally, changes to use this mechanism in snapshot v2 is also part of this change.
Please note commit `731e996` is in a separate PR, some changes are dependent on it hence this PR is made on top of it, review only commits other than `731e996`.
=> disable DD with a in-memory flag and use it for snap v2

fdbserver/fdbserver.actor.cpp
=> Move memory and locality arguments from --dev-help to --help. 

fdbclient/FDBTypes.h, flow/Arena.h, flow/flat_buffers.cpp, flow/flat_buffers.h
This is undefined behavior, since it's potentially a misaligned access.
But it's _probably_ not worse than the status quo
=> Avoid memcpy for small types

Makefile
Add `-Wno-undefined-var-template` and `-Wno-unknown-warning-option` flags to be consistent with `cmake` and Darwin `clang` flags. Otherwise, Linux clang can generate spurious errors.
=> Suppress warnings for clang on Linux

build/Dockerfile, build/docker-compose.yaml
[Ninja](https://ninja-build.org) is a build tool replacement for GNU
Make. It is much faster than GNU Make and cmake can generate Ninja build
files.
This change would allow us to write `cmake -G Ninja $FDB_SRC` and then
build with Ninja in the docker container. This makes the build
significantly faster.
=> Add Ninja to the Dockerfile

fdbserver/sqlite/btree.c
Our internal benchmark showed that the storage server spends 12.4% of its time in sqlite3BtreeMovetoUnpacked() for GET only workload.
Out of 12.4%, significant time is spent to load the pCell from memory.
```
Overhead  Command    Shared Object       Symbol
+   12.41%  fdbserver  fdbserver           [.] sqlite3BtreeMovetoUnpacked
+    7.39%  fdbserver  libc-2.12.so        [.] __swapcontext
+    7.22%  fdbserver  fdbserver           [.] std::_Hashtable<long, std::pair<long const, AFCPage*>, std::allocator<std::pair<long const, AFCPage*> >, std::__detail::_Select1st, std::equal_to<long>, std::hash<long>, std::__detail::_Mod_range_hashing, std::__de
+    5.59%  fdbserver  fdbserver           [.] AsyncFileCached::readZeroCopy
+    4.92%  fdbserver  fdbserver           [.] …
```
=> Prefetch B-Tree cells in sqlite3BtreeMovetoUnpacked() to reduce cache misses

fdbcli/fdbcli.actor.cpp, fdbserver/LogSystemConfig.h, fdbserver/Status.actor.cpp, fdbserver/fdbserver.actor.cpp, flow/Arena.h, flow/ObjectSerializer.h, flow/genericactors.actor.h
std::result_of is deprecated in C++17. And some other improvements.
This is for #1255
=> Fix compiler warnings

fdbserver/LogSystem.h, fdbserver/LogSystemDiskQueueAdapter.actor.cpp, fdbserver/LogSystemDiskQueueAdapter.h, fdbserver/MasterProxyServer.actor.cpp, fdbserver/OldTLogServer_4_6.actor.cpp, fdbserver/TagPartitionedLogSystem.actor.cpp, fdbserver/masterserver.actor.cpp
… to avoid restoring data that is later found to be popped
=> the master checks the popped version of the txsTag before recovering the txnStateStore

fdbcli/fdbcli.actor.cpp
`consistencycheck` help text made it sound like it would cause
consistency checking to be done, which was not the case.  Consistency
checking still requires dedicated `-r consistencycheck` processes to be
running.
Snapshotting requires documentation and a bit more work, cleanup, and
polish before it could be used by users without great confusion.  Thus,
it's being shuffled over to a hidden command, until that work is done.
=> Reword consistencycheck and remove snapshot.

fdbserver/fdbserver.actor.cpp
Currently main has many non-const local variables that represent parsed
options. These variables get changed by parsing code intermixed with
code that does things with these variables. This commit extracts the
parsing code from main and moves the local variables to a const struct.
I think the main value of this change is making all those parsed options const within main. LMK what you think (I don't mind abandoning this change if people don't think it improves readability.)
=> Extract argv parsing code from main

fdbclient/NativeAPI.actor.cpp
Also avoid some other work that only needs to be done if we haven't started a read version request.
=> Don't count read version requests if we've already started one. 

fdbserver/ClusterController.actor.cpp, fdbserver/StorageMetrics.actor.h
This PR suppress two warnings with no functional change, because too many same errors cause false positive in nightly test and thus should be suppressed:
1) `RecruitStorageNotAvailable` warning.
When too many outstanding requests cannot find a worker for storage server
role, many same errors will be put into trace log. Only one error is enough
to alert the problem.
2) `PhysicalDiskMetrics` warning.
Because PhysicalDiskMetrics metric is quite stable within short period of time,  we should suppress it with 60 second interval to avoid spammy log messages.
=> Suppress spammy warnings

CMakeLists.txt, README.md
`add_link_options` is not available in CMake version 3.12, so we now need version 3.13.
=> Bump CMake minimum required version to 3.13

fdbserver/Ratekeeper.actor.cpp
The reporting of these values is inaccurate (`worstStorageLocalLimit` is always 0), and since they aren't being used for anything I'm opting to just remove them.
=> Remove unused local rate limit variables in ratekeeper.

documentation/sphinx/source/release-notes.rst, fdbcli/fdbcli.actor.cpp, fdbclient/ManagementAPI.actor.cpp
Fix an unknown_error when the file passed to fileconfigure doesn't contain a valid object (e.g. if you omit the enclosing {} of your object).
Fix an internal error when configuring regions with some storage servers that don't have a datacenter set.
=> Fix some validation logic when using the fdbcli fileconfigure command

packaging/deb/DEBIAN-foundationdb-server/postinst
When the processes are started outside of the init system and that init system is systemd, the documented procedure to stop foundationdb (`sudo service foundationdb stop`) does not work.
This fixes the issue by creating the service unit and starting it with systemd when possible.
=> Start service with systemd when possible

fdbrpc/sim2.actor.cpp
trackLeakedConnection actor should give server enough time to
close its connection due to idle connection.
The current logic waits for at least 24 seconds to detect and close
an idle connection.
The current trackLeakedConnection actor waits for about 30 seconds
to claim LeakedConnection error.
We increase the delay in trackLeakedConnection actor to avoid
false positive error in simulation test.
Co-authored by: Vishesh Yadav
=> Increase delay in monitoring LeakedConnection

fdbrpc/FlowTransport.actor.cpp
If client is incompatible, connectionMonitor relies on peer->resetPing
to be triggered whenever data is received to prevent ping timeout.
The server stopped sending pings since 6.2 which meant resetPing
doesn't get triggered.
=> Add comment to explain why server ping incompatible clients

fdbserver/FDBExecHelper.actor.cpp
Avoid passing snap binary path as an argument while invoking the binary.
=> snap binary path not to be passed as an argument

fdbclient/DatabaseContext.h, fdbclient/NativeAPI.actor.cpp, fdbserver/DataDistribution.actor.cpp, fdbserver/MasterProxyServer.actor.cpp, fdbserver/workloads/SnapTest.actor.cpp, flow/error_definitions.h
Many snapshot failures are marked with the same error code of operation_failed() which gives very little information about where the command really failed.
In this PR:
- introduced specific error codes that reflects where the snapshot command failed
- reworded error codes to remove the snap v1 history
- enable tlog pop in snapshot failure cases so that the subsequent snapshot command need not wait for the timeout to enable popping of the tlogs
=> improved error msgs for snapshot cmd

fdbcli/fdbcli.actor.cpp, fdbclient/ManagementAPI.actor.cpp, fdbclient/ManagementAPI.actor.h, fdbclient/NativeAPI.actor.cpp, fdbclient/NativeAPI.actor.h, fdbserver/FDBExecHelper.actor.cpp, fdbserver/FDBExecHelper.actor.h, fdbserver/OldTLogServer_6_0.actor.cpp, fdbserver/TLogServer.actor.cpp, fdbserver/worker.actor.cpp
snapshot command when invoked from command line like : fdbcli --exec 'snapshot create.sh' fails, because the client db info gets populated after snapshot is invoked. snapshot command monitors for change in client db info and uses that as a proxy for cluster recovery happening and fails the request. So, when invoked with --exec - snapshot command fails, because it assumes it detected a recovery.
This PR allows the snapshot commands to succeed when run via --exec or from inside the cli shell.
Additionally, snapshot binary script will take posix compliant arguments and not custom style arguments.
=> fix fdbcli --exec 'snapshot create.sh' failure

fdbserver/QuietDatabase.actor.cpp
Reenable the consistency check that validate properties of team collections in `data_hall` mode.
=> ConsistencyCheck:Check teamCollectionValid for data_hall mode

fdbserver/Status.actor.cpp
Found at 8f912ca with
```
r -r simulation --crash -f ./foundationdb/tests/slow/DDBalanceAndRemoveStatus.txt -s 22355704 -b on
```
=> Fix a crash failure due to iterator passing the end

fdbclient/CommitTransaction.h, fdbclient/FDBTypes.h, fdbserver/LogRouter.actor.cpp, fdbserver/LogSystem.h, fdbserver/LogSystemPeekCursor.actor.cpp, fdbserver/OldTLogServer_6_0.actor.cpp, fdbserver/TLogServer.actor.cpp
Consolidate deserialization of TagsAndMessages in the structure itself and change both TLog and ServerPeekCursor to use it. Hopefully this change makes the code more readable.
=> Refactor deserialization of on-wire buffer with TagsAndMessage

CMakeLists.txt
Currently we maintain the current fdb version in cmake and in the `versions.target` file. Because of that they are now out of sync.
This PR sync them and also adds a check in CMake to make sure that they are synced. This check only works on MacOS and Linux but not on Windows (but that should be fine for our purpose).
In the future I would like to remove the `versions.target` file from the source tree to make this easier to maintain.
=> Assert that version in versions.target and cmake are in sync

bindings/python/fdb/tuple.py, documentation/sphinx/source/release-notes.rst
Versionstamp ordering was dependent on `__cmp__`, which is not used in Python 3.
=> Fix versionstamp ordering in Python3

fdbserver/LogRouter.actor.cpp, fdbserver/LogSystemPeekCursor.actor.cpp, fdbserver/OldTLogServer_6_0.actor.cpp, fdbserver/TLogServer.actor.cpp
This implements (and uses) parallel peeking for remote log router to log router peeks, and causes a merge cursor of parallel server peek cursors to top off their internal batch of requests when one cursor is exhausted.
=> Improve log router -> remote log bandwidth

build/Dockerfile, build/docker-compose.yaml
Updated docker  compose builds to use ninja rather than make.
This is very important since the Makefile built via cmake does not seem to allow multiple projects to be built in parallel and I'm not sure if this is based on the CMake configuration files or cmake Makefile builder. Nonetheless, producing and building via ninja seems to allow full parallelism.
=> Ninja CMake

fdbmonitor/local.mk
Backported fix for properly linking fdbmonitor with pthread
=> Backport Fdbmonitor Link Fix

fdbcli/fdbcli.actor.cpp, fdbclient/ManagementAPI.actor.cpp, fdbclient/ManagementAPI.actor.h
Currently, snapshot CLI command does not print the UID in failure cases. Operator needs to cleanup any disk level snapshots that were created by the failed snapshot command. Without a UID available to the operator it is difficult to find the snapshots and clean it up.
The fix as part of this PR will print the UID in failure cases too.
=> snapshot cli to print UID in failure cases too

fdbmonitor/CMakeLists.txt, flow/CMakeLists.txt
1. `-isystem ../flow/-lpthreads` was appearing as an include flag
Due to an apparent mistake of specifying CMAKE_THREAD_LIBS_INIT
as a system include.  The correct way to do this is to link
against Threads::Threads, which was already done below.
2. fdbmonitor wouldn't link due to missing pthread_once
So it also needs to link against Threads::Threads
=> Fix some CMake build issues

documentation/sphinx/source/release-notes.rst, fdbrpc/Locality.h, fdbserver/DataDistribution.actor.cpp, fdbserver/Knobs.cpp, fdbserver/Knobs.h
This is the part 1 of a PR set for Issue#2100
When a storage server has misconfigured locality information, e.g., missing data_hall or zone_id entry, the current data distribution algorithm may get stuck and cannot recover by itself. This may leave a cluster to an unrecoverable situation.
This change aims to make DD resilient to such misconfiguration.
=> Improve FDB reliability from misconfigured localities - Part 1

fdbserver/workloads/ConfigureDatabase.actor.cpp
[This is @alexmiller-apple's PR#2140. We merge it to master for nightly test.]
It turns out that in rare situations, simulation can run into a case
where recovering to the point that tlog generations can be dropped takes
longer than 3s, and thus tests fail with an OOM as an ever increasing
number of tlogs are recruited and never removed.
=> Make one case in ConfigureDatabase wait for >3s.

bindings/c/fdb_c.cpp, bindings/c/foundationdb/fdb_c.h
Don't export the `fdb_future_get_version_v619` symbol. Mark `fdb_future_get_version` as a removed function.
=> fdb_future_get_version cleanup

bindings/c/fdb_c.cpp, bindings/c/foundationdb/fdb_c.h, documentation/sphinx/source/release-notes.rst
When creating a database with API version <610 and client libraries 6.1 or newer, the `fdb_cluster_create_database` function was implemented by calling `fdb_create_database`. When using the multi-version API with a program that was explicitly linked against `fdb_c`, this could result in an infinite recursion where an external library calls `fdb_create_database` on the primary library, who then calls back into the external, etc.
This is known to affect programs written using the Go and Flow bindings as well as some written using the C bindings.
The solution implemented here removes `DLLEXPORT` from a variety of functions that don't need to be public and avoids calling `fdb_create_database` by adding a private implementation function.
I've opened this PR against release-6.1, as it is …
=> Fix multi-version API infinite recursion when creating database

fdbserver/workloads/Cycle.actor.cpp
`checkOnly` param added for cycleTest verification actually fails the test.
`runSetup=false` is sufficient for cycleTest verification in real world or in the simulator.
=> Fix #2119:remove checkOnly parameter for cycleTest

cmake/FlowCommands.cmake
Before, changing the actor compiler would not cause actor
files to get recompiled. Fix that.
=> Depend on actorcompiler.exe, rather than target

FDBLibTLS/CMakeLists.txt, fdbrpc/CMakeLists.txt
They're statically linked anyway, and this fixes an issue with CMake
complaining that there are cyclic dependencies that are non-static.
No idea why I'm hitting this and our CMake builder isn't though?
=> Make FDBLibTLS and thirdparty static libraries.

fdbserver/DataDistribution.actor.cpp, fdbserver/DataDistribution.actor.h, fdbserver/DataDistributionQueue.actor.cpp, fdbserver/Knobs.cpp, fdbserver/tester.actor.cpp, fdbserver/workloads/Cycle.actor.cpp
[This PR fixes bugs found in nightly correctness test on 09-06-2019]  
When mountainChopper and valleyFiller balances data across teams, it should only choose the team with healthy free space as the candidate.
Non-functional change: This commit removes unneeded printf introduced by
fast restore PR 1404.
=> DD:fix:getTeam may fail to get a team when it can

fdbclient/FDBTypes.h, fdbserver/CMakeLists.txt, fdbserver/DiskQueue.actor.cpp, fdbserver/OldTLogServer_6_2.actor.cpp, fdbserver/TLogServer.actor.cpp, fdbserver/WorkerInterface.actor.h, fdbserver/fdbserver.vcxproj, fdbserver/worker.actor.cpp, flow/ProtocolVersion.h
In preparing to do some TLog overhauling again for #1031 , I started pondering what to do about spill-by-value and spill-by-reference being in two separate files.  It turns out that I had done 98% of the work to have spill-by-value and spill-by-reference coexist in the same source file and disk queue file, and just didn't realize it.  This PR leaves us with TLogServer being the only file from which one can recruit a new TLog, and introduces V5 of the log system, with which I'll continue making future changes.
I initially tried in this PR to fully fix my mistake, and combine OldTLogServer_6_0, OldTLogServer_6_2, and TLogServer into one file.  However, it turns out that the key format that we use when storing metadata into the sqlite btree is rather unfriendly to a future restarting test …
=> Recover Txs Faster [0/?]: Combine spill-by-value and spill-by-reference into one file/SharedTLog

flow/FastAlloc.cpp
FastAlloc is the major memory use case in FDB, yet we can't profiling its usage.
This commit replaces FastAlloc memory allocation with malloc so that we may
track its memory usage when gperftool is used.
This partially addresses #1411.
=> Add memory profiling for FastAlloc when gperftool is used

fdbserver/OldTLogServer_6_0.actor.cpp, fdbserver/OldTLogServer_6_2.actor.cpp, fdbserver/TLogServer.actor.cpp, fdbserver/WorkerInterface.actor.h, fdbserver/worker.actor.cpp
This PR is being posted as rebased on top of #2208, so begin the review only from "Spill SharedTLog when there's more than one".
Internally, we have a larger container around TLog generations, called a SharedTLog.  Currently, when configuring between e.g. log_version:=4 and log_version:=5, this will cause two different SharedTLogs to be created, because each log version wants to live in its own file.  SharedTLog was meant to allow multiple generations of TLogs to work harmoniously to never store more than 2GB of mutations in memory, and having more than one of them defeats this.
This PR is a re-post of #2029 , and does the same fix, but more.  When a new TLog is recruited, we:
(1) Announce the ID of the SharedTLog that did the recruitment to all SharedTLogs
(2) All old SharedTLogs stop …
=> Stop and spill TLogs when a new TLog is recruited in a different SharedTLog

bindings/c/test/mako/mako.c, bindings/c/test/mako/mako.h
Add a capability to change the throttling rate between "--tpsmin" and "--tpsmax" in the interval of "--tpsinterval".
Three types of changes are added in this PR:
- Sin: TPS oscillates in the shape of sine curve
- Square: TPS changes from "min" to "max" periodically
- Pulse: TPS goes "max" for 1 second then stays at "min"
=> Mako benchmark:  Add variable throttling

fdbclient/MultiVersionTransaction.actor.cpp
The previous code, which technically incorrect, is believed to be asymptomatic because new versions of the client do have this symbol in order to support old API header versions.
=> Don't require fdb_future_get_database from new client binaries.

fdbserver/FDBExecHelper.actor.cpp, fdbserver/FDBExecHelper.actor.h, fdbserver/OldTLogServer_6_0.actor.cpp, fdbserver/OldTLogServer_6_2.actor.cpp, fdbserver/TLogServer.actor.cpp
`isTLogInSameNode` was a functionality used in snapshot V1 to detect if the storage and TLog are on the same process and use that to determine if the snap create needs to be done. With snapshot V2, we no long user this functionality, hence deprecating this and all the dependent functions.
=> deprecate isTLogInSameNode used by snapshot V1

fdbserver/DataDistribution.actor.cpp
When there is only one healthy team, the bug will set a server's status as unhealthy;
which causes the healthyTeam to 0, triggering StorageServerTracker to loop back;
which resets the server's status to healthy, and thus the healthyTeam to non-zero.
This pattern will cause infinite loop.
Infinite loop will prevent TraceEvent from flushing, which causes
TraceEvent to use most of memory and out-of-memory.
Kudos to JingYu Zhou (jingyu_zhou@apple.com), the main contributor who found the bug!
=> StorageServerTracker:Fix OOM bug caused by server healthiness toggles infinitely

documentation/sphinx/source/release-notes.rst, fdbserver/DataDistributionTracker.actor.cpp
This changes the `keys` parameter to `changeSizes` to not be a reference.
=> Fix invalid access to a reference value

fdbserver/DataDistribution.actor.cpp, fdbserver/DataDistribution.actor.h, fdbserver/DataDistributionQueue.actor.cpp, fdbserver/DataDistributionTracker.actor.cpp, fdbserver/Knobs.cpp, fdbserver/Knobs.h, fdbserver/Status.actor.cpp, fdbserver/workloads/DDMetrics.actor.cpp
By making splits higher priority than restoring fault tolerance we will avoid creating hot write shards.
=> Raised the data distribution priority of splitting shards

fdbclient/SystemData.cpp, fdbclient/SystemData.h, fdbserver/RestoreApplier.actor.cpp
When a transaction that apply mutations to destination cluster fails with error, especially `commit_unknown_result`, we cannot blindly rerun the transaction if the transaction has atomic operations.
This change ensures each transaction is only successfully executed once.
=> Performant restore [2/XX]: RestoreApplier: Handle transaction with errors

flow/CMakeLists.txt
This way if we rebuild after reconfiguring, the binaries will pick up
the new hgVersion.h
=> Include hgVersion.h in FLOW_SRCS

fdbserver/RestoreApplier.actor.h, fdbserver/RestoreCommon.actor.h, fdbserver/RestoreLoader.actor.h, fdbserver/RestoreMaster.actor.cpp, fdbserver/RestoreMaster.actor.h, fdbserver/RestoreRoleCommon.actor.h, fdbserver/RestoreWorkerInterface.h
The new coming backup system will create multiple backup files (one per log tag) that hold mutations at the same version. This raise new challenges for the performant restore to handle exact-once semantics.
This PR is a preparation for extending the performant restore to handle the above situation.
This PR makes two changes:
1) Add fileIndex to RestoreFileFR struct; fileIndex will be the unique identifier for backup files;
2) Fix some bugs in RestoreMaster: For example, ensure database is locked before starts restore.
=> Performant restore [3/XX]: Add fileIndex to RestoreFileFR struct and fix bugs for RestoreMaster

documentation/sphinx/source/administration.rst
The previous language was ambiguous about which processes would not be
restarted on configuration change. This makes it clear that its the
monitored processes and not fdbmonitor itself.
=> Clarify docs on `kill_on_configuration_change`

fdbserver/RestoreApplier.actor.cpp, fdbserver/RestoreApplier.actor.h, fdbserver/RestoreMaster.actor.cpp
When RestoreLoader sends the parsed mutations to RestoreAppliers, the message can be resent.
RestoreApplier should only cache the parsed mutations exactly once, because those mutations may include atomic operations.
RestoreApplier keeps a NotifiedVersion for each parsed file to achieve the above exact-once requirement.
=> Performant restore [5/XX]:RestoreApplier should cache mutations sent from RestoreLoader exactly once

fdbserver/Status.actor.cpp
Keys in the destUIDLookupPrefix can be cleaned up automatically if they do not have an associated entry in the logRangesRange keyspace
=> Automatically cleanup backup and DR sharing metadata

fdbserver/LogSystemPeekCursor.actor.cpp, fdbserver/OldTLogServer_4_6.actor.cpp, fdbserver/OldTLogServer_6_0.actor.cpp, fdbserver/TLogServer.actor.cpp
This version uses `timed_out` instead of `operation_obsolete`, as we can't introduce a new error type on the wire in a backwards compatible way.  This means we might kill some parallel peeks when we could have just ignored a response or two, but that will be fixed on master.
=> More fixes to prevent 10min stalls in recovering secondaries

fdbserver/OldTLogServer_6_0.actor.cpp, fdbserver/TLogServer.actor.cpp, fdbserver/WorkerInterface.actor.h, fdbserver/worker.actor.cpp
When switching between spill_type or log_version, a new instance of a
SharedTLog is created in the transaction log processes.  If this is done
in a saturated database, then doubling the amount of memory to hold
mutations in memory can cause TLogs to be uncomfortably close to the 8GB
OOM limit.
Instead, we now thread which UID of a SharedTLog is active, and the
other TLog spill out the majority of their mutations.
This is a backport of #2213 (fef89aa1) to release-6.2
Once this merges, please ping me, as this PR and #2213 will conflict, and I should go handle the 6.2->master merge.
=> Spill SharedTLog when there's more than one

bindings/c/test/mako/mako.c, bindings/c/test/mako/mako.h, bindings/c/test/mako/mako.rst
Fixed retry logic.
Fixed API_VERSION handling.
Fixed verbose message handling.
Changed the default values.
Updated mako.rst accordingly.
Note: clang-format fix is NOT in this PR.
=> Mako benchmark cleanup

fdbserver/DiskQueue.actor.cpp
Initialized AsyncVar member variable using class constructor.
This resolves issue #2122
=> Fixed Compiler Error in GCC 4.8.5

flow/IRandom.h, flow/Net2.actor.cpp
`~IRandom` is useful for deleting derived class instances.
=> Clean up some memory after network thread exits

fdbserver/tester.actor.cpp
This is necessary for the `LockDatabase` workload to succeed outside of the simulator.
=> Use lock aware transaction for pingDatabase

fdbrpc/FlowTests.actor.cpp
Seems that we don't want the property that delays become ready in order
to hold, so make sure it doesn't hold in the simulator.
CC #2148
=> Replace /flow/delayOrdering with /flow/buggifiedDelay

flow/IRandom.h, flow/Net2.actor.cpp
Reverts apple/foundationdb#2300
This seems to cause client segfault when existing. Presumably the client is still accessing the deleted `g_network`.
=> Revert "Clean up some memory after network thread exits"

fdbserver/RestoreLoader.actor.cpp, fdbserver/RestoreUtil.h, flow/Knobs.cpp, flow/Trace.h
We toggle the value of the macro `SevFRMutationInfo` to turn on and off the trace events that tracks mutations in the new performance restore systems
If we want to toggle a specific trace events, we can define a macro like `SevFRMutationInfo ` and toggle it to turn it on and off.
This is an updated PR for PR. https://github.com/apple/foundationdb/pull/2232
=> Raise MIN_TRACE_SEVERITY from 0 to 1 to allow customized tunable trace severity

fdbserver/workloads/RemoveServersSafely.actor.cpp
Fixed test case scenario where having a larger failed set than non-failed set would break the db and cause the test to time out. Also re-arranged ordering of non-failed set replacement due to dependency on an iterator
=> Fixed bug in maintaining kill set size in RemoveServersSafely workload

fdbclient/BackupContainer.h, fdbclient/RestoreWorkerInterface.actor.h, fdbserver/RestoreApplier.actor.cpp, fdbserver/RestoreCommon.actor.h, fdbserver/RestoreLoader.actor.cpp, fdbserver/RestoreMaster.actor.cpp, fdbserver/workloads/AtomicOps.actor.cpp
The current AtomicOps test checks if two key spaces (`ops` and `logs`)  produces the same results and reports an error if they don't match.
This PR adds more detailed trace information for AddValue opType when inconsistent error is detected:
(1) It tells which `ops` key is missing; and 
(2) It tells which `ops` key does not match the value of which `logs` key when the `actorCount` is set to 1 per test client.
The detailed trace information is very useful in debugging: Knowing a specific key is inconsistent with another can help narrow down the debug surface.
=> AtomicOps Test: Add more detailed debug information when test fails with opType = AddValue

fdbclient/SystemData.cpp, fdbclient/SystemData.h, fdbserver/RestoreApplier.actor.cpp, fdbserver/RestoreLoader.actor.cpp, fdbserver/RestoreMaster.actor.h, fdbserver/RestoreRoleCommon.actor.cpp, fdbserver/RestoreRoleCommon.actor.h, tests/CMakeLists.txt, tests/slow/ParallelRestoreCorrectnessAtomicOpTinyData.txt, tests/slow/ParallelRestoreCorrectnessCycle.txt
The applyToDB step writes mutations to the destination database. Atomic mutations must be applied exactly once for correctness. Other mutations should be applied exactly once for performance benefit.
The current code has a bug that neglects the serialized form (little endian) of the integer type of transaction id. This leads to the serialized transaction ids in the system keyspace are not ordered by the integer value. When transaction throws unknown error and the old transaction id is not properly cleared, we will lose some mutations.
This PR fixes the above bug.
This PR also enhance the tests:
(a) Increase the workload of the AtomicOps tests;
(b) Add the Cycle test for the fast restore.
=> Performant restore [8/XX]: Fix bugs in applyToDB logic and add more tests

fdbrpc/FlowTransport.actor.cpp, fdbserver/workloads/ApiCorrectness.actor.cpp, fdbserver/workloads/FuzzApiCorrectness.actor.cpp
Also remove Net2_ prefix from packet size trace events.
=> Rename LargePacket warnings to distinguish between sent and received packets.

tests/CMakeLists.txt
I find it odd that we did not include these two tests. It seems CTest doesn't run them even if `IGNORE` is removed, so I assume it's safe to do so.
=> Reenable restart tests in from_5.*

flow/flat_buffers.h
Writing a value which is not 0 or 1 to the underlying memory of a bool
is undefined behavior. Conformant flatbuffers implementations must
accept bytes that are not 0 or 1 as booleans [1]. (Conformant
implementations are only allowed to write the byte 0 or 1 as a boolean
[1])
So this protects us from undefined behavior if we ever read a
flatbuffers message written by an almost-conformant implementation.
[1]: https://github.com/dvidelabs/flatcc/blob/master/doc/binary-format.md#boolean
=> Fix a potential UB instance

cmake/ConfigureCompiler.cmake
There seems to be an overwhelming amount of misaligned memory access, and it seems to be a large effort to fix them (see #1434 e.g.) Other types of undefined behavior seem to be more manageable, so I propose we fix those first, and suppress misaligned access for now. Hopefully this will help us resolve #965
=> Ignore -fsanitize=alignment for UBSAN

flow/Arena.h, flow/flow.h
This does _not_ fix any potential uses of uninitialized memory, but without
this change, gcc issues false-positive -Wuninitialized warnings.
I'm hoping this does not have a noticeable impact on performance
=> Initialize memory for Optional and ErrorOr

fdbserver/storageserver.actor.cpp
UBSAN has this to say:
flow/Arena.h:982:10: runtime error: reference binding to null pointer of type 'KeyValueRef'
After this change UBSAN no longer complains about this occurrence
=> Fix reference binding to nullptr

fdbclient/FDBTypes.h, flow/flat_buffers.h
These were found via enabling `-Wuninitialized` with gcc. It might be a good idea to merge this into release-6.2, as otherwise if we do a protocol-compatible deprecation of a field (or introduction of a new alternative in a union), fdbserver processes running without this change may start using uninitialized memory.
A binary which introduces a field (and has this change) can safely interact with a binary without this change.
=> Default initialize absent flatbuffers members

cmake/ConfigureCompiler.cmake, fdbclient/SnapshotCache.h, fdbclient/vexillographer/cpp.cs, fdbrpc/FlowTransport.actor.cpp, fdbserver/DiskQueue.actor.cpp, fdbserver/KeyValueStoreSQLite.actor.cpp, fdbserver/Ratekeeper.actor.cpp, fdbserver/SkipList.cpp, fdbserver/TLogInterface.h, fdbserver/VersionedBTree.actor.cpp, fdbserver/sqlite/sqlite3.amalgamation.c, fdbserver/storageserver.actor.cpp, fdbserver/workloads/FuzzApiCorrectness.actor.cpp, fdbserver/workloads/RyowCorrectness.actor.cpp, flow/Arena.h, flow/Deque.h, flow/Platform.cpp, flow/Platform.h, flow/serialize.h
This fixes ~~all the errors~~ some of the errors I'm seeing with `-fsanitize=undefined -fno-sanitize=alignment`
PTAL at the KeyValueStoreSQLite and Ratekeeper changes, as it's not 100% clear to me I've preserved the original author's intent.
=> Fix more UBSAN reports

fdbserver/SkipList.cpp
It seems to me that the original author was under the impression that `x << y` is semantically equivalent to `x << (y % (sizeof(x) * 8))`. This is the behavior we were getting and seem to rely on, so let's keep the behavior but make it not UB
Resolves #2398
=> Fix ub in MiniConflictSet (Skiplist.cpp)

bindings/c/test/mako/mako.c
One uninitialized variable, one out-of-bound memory access.
=> Mako: fix minor bugs

documentation/sphinx/source/release-notes.rst, fdbclient/NativeAPI.actor.cpp
Resolves #2424 
Also:
Move some buggify errors into a try catch block so that the normal error handling path can run.
Initialize `startTime` so that it's valid in the case of errors thrown early.
=> Fix internal error when client buggify fails successful transaction with commit_unknown_result

bindings/java/src/main/com/apple/foundationdb/tuple/ByteArrayUtil.java, documentation/sphinx/source/release-notes.rst
Copied from https://github.com/apple/foundationdb/blob/master/fdbclient/FDBTypes.h#L416
Not sure if I should add a check against [0xFF 0xFF] here.
@alecgrieser Could you please review this?
=> Add keyAfter method to Java bindings

documentation/sphinx/source/mr-status-json-schemas.rst.inc
This is the PR from https://github.com/apple/foundationdb/pull/2461, rebased against 6.2.
=> Add status documentation comments to 6.2

fdbclient/BackupContainer.actor.cpp, fdbclient/BlobStore.actor.cpp, fdbclient/BlobStore.h
Added BlobStoreEndpoint::listBuckets(), renamed listBucket() and several related functions with similar names to listObjects() to avoid confusion and closer match what it actually does.
Added a bytesDeleted output statistic to BlobStoreEndpoint::deleteRecursively().
None of these API features are used yet on master, but they were tested/used by me in a one-off tool I wrote to clean up some very old (pre 5.0 I think) backup data. 
These new features could be used to enhance fdbbackup to be able to find buckets which contain backups or to report the amount of data deleted during backup expiration or deletion.
=> BlobStoreEndpoint enhancements

fdbserver/OldTLogServer_6_2.actor.cpp, fdbserver/TLogServer.actor.cpp
This wasn't detected by simulation until @jzhou77's new changes because nothing in our current codebase peeks below what was popped.  The bug exists because we will pop the disk queue based off a version that we haven't persisted to disk, so if the TLog crashes, the btree index and the disk queue disagree on what versions have been popped, and thus a peek can get through that tries to read data from the disk queue that no longer exists.
=> Fix an issue where a peek starting from version 1 could crash a TLog

fdbserver/RestoreLoader.actor.cpp, fdbserver/RestoreRoleCommon.actor.h
Remove the suffix `MX` from the structure name. 
=> Performant restore [12/XX add-on]: Rename StringRefReaderMX to BackupStringRefReader

fdbclient/FileBackupAgent.actor.cpp, fdbclient/RestoreWorkerInterface.actor.h, fdbserver/RestoreApplier.actor.cpp, fdbserver/RestoreApplier.actor.h, fdbserver/RestoreLoader.actor.cpp, fdbserver/RestoreMaster.actor.cpp, fdbserver/RestoreUtil.actor.cpp, fdbserver/RestoreUtil.h
Version batch is a batch of backup range and log files to process in a restore pass: we parse the files, save the parsed mutations into buffers on loaders, and sort them on appliers, which applies them onto the destination cluster.
For better performance (such as pipelining the processing of more than one version batch) and avoidance of out of memory (because a version batch has more data than all appliers or loaders can buffer), we want data size in version batches does not vary too much.
To achieve that, our new restore can process the same file for multiple times, each time focusing on a certain key range and version range.  This requires loaders and appliers able to process the same file multiple times while still keep the exact-once processing semantics. 
This PR introduces …
=> Performant restore [13/XX]: Introduce RestoreAsset to uniquely identify the backup block to restore

fdbrpc/fdbrpc.h
This catches a potential bug where a request object is unintentionally reused, and gives a much nicer diagnostic than say a timeout.
I ran 10 ctest suites on it.
=> Assert that a request hasn't already gotten a reply

bindings/bindingtester/bindingtester.py, bindings/bindingtester/tests/directory.py
Python 3 fix;
Don't allow using partitions with the high-contention allocator in comparison tests due to non-determinism if the partition creation fails to commit.
=> Fixes to binding tester

bindings/flow/CMakeLists.txt, bindings/flow/tester/CMakeLists.txt
Moved the STATIC_LIBRARY and EXECUTABLE keyword to the beginning of t…he function argument list
=> Debug Strip Failure Exploration

documentation/sphinx/source/release-notes.rst, flow/Net2.actor.cpp, flow/Platform.cpp
The slow task profiler includes a call to `timer()` to get the time that the backtrace was captured. This seems to be unsafe if the signal is raised in the middle of a call to `time()`, among possibly other things.
This PR removes the call to `timer()` in the signal handler and instead relies on the check thread to capture a time and propagate it to the signal handler using an atomic variable. In the event that atomic variables on the platform are not lock-free, this mechanism will not be used and instead the logs will not report the time that the backtrace was taken.
Resolves #2364 (hopefully)
=> Fix slow task profiler crash

fdbcli/fdbcli.vcxproj
Added bigobj compilation option to FdbCli project in order to fix problem with too many sections in object file for Windows
=> Windows Build Fix

cmake/FlowCommands.cmake
Moved object stripping command to multiple commands in order to prevent strange error of file non-existence from occurring
=> Fixed Object Stripping Command

cmake/FlowCommands.cmake
This make the dependency between `stip` and `objcopy` explicit - therefore it will hopefully prevent races between the two
=> make dependencies explicit

bindings/c/test/mako/mako.c, bindings/c/test/mako/mako.h
This PR adds a new option "--txntrace N" to emit debug transaction tracing every N seconds.
In addition to the debug tracing, the client-side trace format is changed from XML to JSON.
=> Add periodical debug transaction tracing

documentation/sphinx/source/administration.rst, documentation/sphinx/source/api-general.rst, documentation/sphinx/source/api-python.rst, documentation/sphinx/source/downloads.rst, documentation/sphinx/source/getting-started-linux.rst
This PR fixes #2392 by updating documentation about separate Python bindings installation on Linux systems.
=> Clarify Docs for Using Python Bindings on Linux

bindings/java/src/test/com/apple/foundationdb/test/AsyncStackTester.java, bindings/java/src/test/com/apple/foundationdb/test/StackTester.java
We weren't using a retry loop, so in the rare cases where we got errors in this transaction the test would fail.
=> Add retry loop to Java binding tester instruction reader

documentation/sphinx/source/api-common.rst.inc, fdbclient/Atomic.h, fdbclient/NativeAPI.actor.cpp, fdbclient/NativeAPI.actor.h, fdbclient/ReadYourWrites.actor.cpp, fdbclient/ReadYourWrites.h, fdbserver/workloads/Unreadable.actor.cpp, fdbserver/workloads/WriteDuringRead.actor.cpp
If the read version of a transaction is known when the versionstamped operation is performed, then the read version can be used as a safe lowerbound of what commit version will be filled into the versionstamped key.
See #2504 for far more context/information.
=> Narrow the unreadable range of keys after a versionstamped key operation

fdbclient/RestoreWorkerInterface.actor.h, fdbserver/RestoreApplier.actor.cpp, fdbserver/RestoreLoader.actor.cpp, fdbserver/RestoreMaster.actor.cpp, fdbserver/RestoreMaster.actor.h, fdbserver/RestoreUtil.h, fdbserver/RestoreWorker.actor.cpp
A version batch is a set of backup files to be parsed and applied to the destination cluster. The new restore split backup files into multiple version batches and process each one by one.
The earlier version of implementation split backup files (based on the version range in log filename) into version batches such that a file is only processed exactly once for all of its data at various versions.  The size of version batch is not controlled.
When a version batch size is larger than the memory size of the restore systems' cluster, the cluster will experience out of memory (OOM) error. To prevent this, this PR limits the size of each version batch to be no larger than the preconfigured value. 
The challenge to achieve that is that each file will need to be processed multiple times, but the …
=> Performant restore [14/XX]: Ensure each version-batch not exceed a configured size

flow/Profiler.actor.cpp
The `gettid()` function is part of glibc 2.30[1]. I decided to keep the
`gettid` implementation here under a different name to remain compatible
to older glibc versions.
[1] https://sourceware.org/ml/libc-alpha/2019-08/msg00029.html
=> Fix build with glibc 2.30

fdbserver/workloads/Mako.actor.cpp
Added checksum verification part in MakoWorkload.
In test spec file added five parameters:
`keyPrefix`=mako // prefix for all the keys to be generated
`doChecksumVerificationOnly`=true // Skip setup, start phases and only do check phase.
`csSize`=100 // How many values are used to calculate one checksum
`csCount`=5 // How many different checksums are calculated, if it is not zero, the workload will check the consistency of checksums in the check phase
=> Add consistency verification in mako workload

documentation/Makefile
The SimpleHTTPServer module is called http.server in python3, so if we don't explicitly choose a version it won't work if our python alias isn't the expected version.
A recent change to the docker image seems to have made python3 the default, so this fix is needed to work with it.
=> Use python3 in docpreview make target

fdbclient/StorageServerInterface.h, fdbserver/RestoreMaster.actor.h
Built-in variable may not be zero initialized by compiler provided default constructor, which fails valgrind tests.
This add-on PR fixes the error.
=> Performant restore [14/XX Add-on]: Fix initialized field in VersionBatch struct

documentation/sphinx/source/flow.rst, documentation/sphinx/source/kv-architecture.rst
Those are some minor edits in the documentation to fix typos.
=> Documentation: fix some typos

fdbcli/fdbcli.actor.cpp, fdbclient/DatabaseConfiguration.cpp, fdbclient/FDBTypes.h, fdbclient/ManagementAPI.actor.cpp, fdbclient/Schemas.cpp, fdbserver/IKeyValueStore.h, fdbserver/KeyValueStoreMemory.actor.cpp, fdbserver/SimulatedCluster.actor.cpp, fdbserver/Status.actor.cpp, fdbserver/storageserver.actor.cpp, fdbserver/worker.actor.cpp, fdbserver/workloads/ConfigureDatabase.actor.cpp, fdbserver/workloads/KVStoreTest.actor.cpp, flow/IKeyValueContainer.h, flow/IndexedSet.h, flow/RadixTree.h
This PR adds a new memory storage engine based on the radix tree. (Because Wavefront’s use case involves a large amount of prefix-overlap in keys, we decided to adopt a different data structure, the radix tree, to make our FDB clusters more space-efficient) 
1. Change **KeyValueStoreMemory** class to a template class. If the storage engine type is **Memory**, we pass in original *IndexedSet*, otherwise, we pass in *RadixTree*
2. Users can configure memory storage engine type via fdbcli. 
```
fdb> configure memory-radixtree
```
This command will configure SS to MEMORY_RADIXTREE and TLog to SSD_BTREE_V2
@panghy
=> New Radix-Tree based Memory Storage Engine 

fdbserver/ConflictSet.h, fdbserver/SkipList.cpp
There was a lot of dead code left over from past experiments. This PR deletes code that is either commented out or behind an `if 0` or `for (i = 0; i < 0...` loop, so the outputted binary shouldn't change at all. I've also clang-formatted the code for good measure. There may be more dead code I missed, but I haven't tried to set up the Clang dead code checker yet.
I'm pretty sure that I used the correct clang-format config file, but please let me know if things look off.
=> Clean up SkipLists (formatting / dead code no op)

documentation/sphinx/source/release-notes.rst, fdbserver/storageserver.actor.cpp
The storage server could fail to update its version to the latest processed if the peeked data contained a non-empty commit and ended with an empty commit.
=> Fix: storage server version could fail to advance in response to empty commits

fdbserver/DataDistribution.actor.cpp
The current names could be misinterpreted to be giving some sort of ID, so I changed the names to hopefully be clearer that they are giving a count.
=> Clarify the names of a couple trace fields

.gitignore
clangd is the default language server for Visual Studio Code and generally seems to gain popularity.
=> Add .cland to .gitignore

documentation/sphinx/source/release-notes.rst, fdbserver/Knobs.cpp
The following knobs were not settable at runtime:
```
TR_FLAG_DISABLE_MACHINE_TEAM_REMOVER
TR_FLAG_REMOVE_MT_WITH_MOST_TEAMS
TR_FLAG_DISABLE_SERVER_TEAM_REMOVER
BUGGIFY_ALL_COORDINATION
```
Also adjust the whitespace of a few lines to match surrounding lines.
=> Fix: Several boolean knobs could not be set at runtime

documentation/sphinx/Makefile, documentation/sphinx/extensions/rubydomain.py
Fixes #2581 
In addition to creating the `virtual environment` with Python3 itself, another change I had to do was to port `documentation/sphinx/extensions/rubydomain.py` to Python3 for the documentation to build successfully.
=> Port documentation to build via Python3

fdbserver/BackupWorker.actor.cpp
The deserialization of mutation from a `StringRef` was done by a `BinaryReader`, which actually creates a copy of the data and returns the copy. As a result, when the reader is out of scope, the memory is no longer valid. Changing to `ArenaReader` solves the problem.
This PR also includes some code refactoring, including dead code removal.
The Valgrind Errors are:
```
<ValgrindError Severity="40" What="Conditional jump or move depends on uninitialised value(s)"/>
<ValgrindError Severity="40" What="Use of uninitialised value of size 8"/>
<ValgrindError Severity="40" What="Invalid read of size 1"/>
```
These are found at: 
commit: 2d4f24ac
seed: -f fast/BackupCorrectness.txt -s 183149587 -b off
unseed: 81917
To reproduce the error, the first step is to create the binary with `VALGRIND := 1` …
=> Fix valgrind error on backup workers

fdbbackup/FileConverter.actor.cpp
Avoid using BinaryReader that creates copies for deserializing StringRef, which is safe for `MutationRef`.
=> Use ArenaReader to deserialize MutationRef

fdbserver/QuietDatabase.actor.cpp
Fixes the test bug surfaced by the new ConfigureLocked test
=> Set options _within_ the retry loop

fdbserver/SkipList.cpp
This showed a ~25% reduction in the SkipListTest runtime.
A rebased version of https://github.com/apple/foundationdb/pull/2669
=> Revert to memcmp comparison in SkipList

bindings/go/src/fdb/fdb_darwin.go, bindings/go/src/fdb/fdb_windows.go
When applied these changes will tell the CGO toolchain on macOS
the default installation location for the headers and libs.
I've recently started playing around with FDB go bindings on my mac.
I've followed the tutorial to set everything up but whilst doing so
I've started getting some error messages like so:
/Users/sevki/go/pkg/mod/github.com/apple/foundationdb/bindings/go@v0.0.0-20200125010749-6945a6ea0141/src/fdb/cluster.go:26:11: fatal error: 'foundationdb/fdb_c.h' file not found
#include <foundationdb/fdb_c.h>
^~~~~~~~~~~~~~~~~~~~~~
These errors are most probably caused by me unsetting LDFLAGS, CFLAGS
globally as the installer installs the header files and the libraries
to sane default locations.
However, I believe explicitly telling the CGO toolchain here is a
better experience for …
=> bindings/go: explicit CFLAGS and LDFLAGS for macOS and windows

bindings/go/src/fdb/generated.go, documentation/sphinx/source/api-common.rst.inc, documentation/sphinx/source/api-python.rst, documentation/sphinx/source/api-ruby.rst, fdbclient/NativeAPI.actor.cpp, fdbclient/NativeAPI.actor.h, fdbclient/vexillographer/fdb.options, flow/Trace.cpp, flow/Trace.h
This option allows clients to select the clock source for trace events
similar to the `--traceclock` command line parameter for `fdbserver`.
Using the `realtime` clock sources makes loading event data into
OpenTracing systems like Jaeger more useful.
This is heavily cribbed from #1092 so hopefully it covers all the bases. I wasn't 100% certain on the `selectTraceClockSource`/`validateTraceClockSource` differences but rather than be creative I just followed the pre-existing pattern.
=> Add network option for the trace clock source

packaging/docker/samples/python/README.md, packaging/docker/samples/python/app/Dockerfile, packaging/docker/samples/python/app/requirements.txt, packaging/docker/samples/python/app/start.bash
Add additional client libraries to the sample python app to show how …to prepare for upgrades.
Skip the creating of the cluster file in the sample python app if it exists and is non-empty.
Document that we have published the sample python app image.
Resolves #2484
=> Improvements to sample python docker app

documentation/sphinx/source/release-notes.rst, fdbclient/BackupContainer.actor.cpp
… to find the last part of a path string, since it shouldn't touch the local filesystem in the remote case.
=> BackupContainerFilesystem no longer unnecessarily depends on abspath()..

fdbserver/OldTLogServer_4_6.actor.cpp, fdbserver/OldTLogServer_6_0.actor.cpp, fdbserver/TLogServer.actor.cpp, fdbserver/WorkerInterface.actor.h, fdbserver/worker.actor.cpp
Add the worker ID, the TLog version, and under what circumstances the TLog is being started (Restored, Recruited, or Recovered).
The SharedTLog role was being started and stopped twice, so remove one instance of it.
=> Improve TLog "Role" event

fdbcli/fdbcli.actor.cpp, fdbclient/DatabaseBackupAgent.actor.cpp, fdbclient/DatabaseContext.h, fdbclient/Knobs.cpp, fdbclient/Knobs.h, fdbclient/ReadYourWrites.actor.cpp, fdbclient/StatusClient.actor.cpp, fdbclient/StatusClient.h, fdbserver/workloads/DDMetricsExclude.actor.cpp, fdbserver/workloads/StatusWorkload.actor.cpp
It is very likely that if a client fetches status once, it will fetch it again. This PR will avoid closing the connect with the cluster controller until two minutes after the last time status was fetched.
=> Clients should not disconnect from the CC after fetching status

packaging/rpm/foundationdb.spec.in
This was being "helpfully" automatically added for us by rpmbuild as it
saw that we listed a python file (make_public.py) in %files.  As that
isn't a vital thing for running FDB, it's better to not make it a hard
requirement.
=> Don't require /usr/bin/python in RPMs.

documentation/sphinx/source/release-notes.rst, fdbserver/DataDistribution.actor.cpp, fdbserver/DataDistribution.actor.h, fdbserver/DataDistributionQueue.actor.cpp
Add new criteria to DD's `GetTeamRequest` that allow you to require shards be present on the team and that the team have a minimum free ratio. This can be used to avoid scenarios where the team chosen when processing the request is later rejected by the requestor. Hopefully resolves #1884.
=> Fix issue with rebalancing data movement doing no work

fdbserver/workloads/BackupAndParallelRestoreCorrectness.actor.cpp, fdbserver/workloads/BackupCorrectness.actor.cpp, tests/slow/ParallelRestoreCorrectnessAtomicOpTinyData.txt, tests/slow/ParallelRestoreCorrectnessCycle.txt
The new performant restore tests disabled buggify explicitly in the text file.
The BUGGIFY covers two more test cases for the existing backup and (old) restore tests:
1) Start two backup procedure and abort one;
2) Abort an ongoing restore and restart the restore.
This PR:
1) Enables BUGGIFY option for parallel restore test files;
2) Cover the test case 1) above. Disable test for the test case 2) because the new restore does not allow agent to abort a restore;
3) Pick changes Steve made on BackupCorrectness.actor.cpp when the backupContainer behavior was changed at `604ad062d5`.
=> Performant restore [18/xx]: Enable BUGGIFY for new restore tests

documentation/sphinx/source/backups.rst
I've been exercising backups and TLS lately and thought the documentation could use a small update.
I have not personally verified the disaster recovery behaviors with TLS options set although I can't see cluster comms working otherwise. Both clusters would need to already be using TLS and the TLS options set for `fdbdr` and `dr_agent` yeah?
I did confirm blob store traffic is encrypted on backup and restore when configured to use TLS, via `tcpdump` running across a cluster during testing.
The `FDB_TLS_PLUGIN` option is depreciated. I removed it and added the peer verification option to the docs.
=> Update backup in-flight TLS support documentation

packaging/rpm/foundationdb.service
This change makes starting foundationdb.service only after a public ip adress apears
=> #2691 start foundationdb only after the public ip adress exists

documentation/sphinx/source/configuration.rst
* Don't suggest Windows is more production tested than macOS
* Update multi-region deficencies, as spill-by-reference is the
default in 6.2+
* Suggest that `double` replication can be reasonable for production
deployments if the underlying disks are already replicated as well.
I was doing a rewrite-the-world locally, but realized I should probably start to get at least some of the edits off my local machine.
=> A variety of minor, yet potentially contentious, documentation changes:

documentation/sphinx/source/configuration.rst
This is a change grabbed from a suggestion on #2477.
=> Document effects of using double on availability fault tolerance

bindings/java/src/main/com/apple/foundationdb/directory/DirectoryLayer.java
=> Fix: Java directory layer was unpacking little endian numbers without properly handling signs

documentation/sphinx/source/backups.rst
Which is mostly a shame on me for not running the CI on #2696
=> reStructuredText uses ``x`` as code font and not `x`.

documentation/sphinx/source/administration.rst, documentation/sphinx/source/api-c.rst, documentation/sphinx/source/api-ruby.rst, documentation/sphinx/source/cap-theorem.rst, documentation/sphinx/source/configuration.rst, documentation/sphinx/source/data-modeling.rst, documentation/sphinx/source/old-release-notes/release-notes-100.rst, documentation/sphinx/source/tls.rst
These issues were causing undesired formatting in the output.
=> Fix some indentation issues in the sphinx documentation

bindings/c/test/mako/mako.c
I'm not sure this is the right fix, but I thought I'd let you know @kaomakino
=> Fix heap buffer overflow in mako

fdbclient/Knobs.h, fdbserver/DataDistributionQueue.actor.cpp, fdbserver/Knobs.cpp, fdbserver/Knobs.h
Background: We are exploring if there exists a better/smarter data distribution. 
The evaluation of the current DD requires more data about relocate shard decision.
This adds a trace in DD for relocate shard's source, destination, storage metrics (like shard size), relocation reason, and shard boundary.
This trace is guarded by `DD_ENABLE_VERBOSE_TRACING` knob which is disabled by default.
=> DD: Record relocated shard detailed info in one trace event

contrib/commit_debug.py
I make no guarantee that I've interpreted the existing CommitDebug messages into an appropriate simplified explanation.
=> commit_debug can visualize CommitDebug TraceEvents via chrome://tracing

fdbclient/ClusterInterface.h, fdbclient/MonitorLeader.actor.cpp, fdbclient/MonitorLeader.h, fdbclient/NativeAPI.actor.cpp, fdbclient/NativeAPI.actor.h, flow/genericactors.actor.h
Our binaries that act like clients (fdbcli, backup and DR binaries) were reporting an unknown client version. Clients did not react if the list of supported versions changed.
=> Improvements to client version reporting

fdbclient/ReadYourWrites.actor.cpp
Status JSON returned from `\xff\xff/status/json` will have unprintable characters escaped. This resolves a truncation bug where null bytes would end the status string.
Also updates the code to work even if it does encounter a null byte.
Resolves #2803.
=> Escape unprintable characters in status JSON output read from magic key

documentation/sphinx/source/mr-status-json-schemas.rst.inc, fdbclient/Schemas.cpp, fdbserver/Status.actor.cpp, flow/Net2.actor.cpp, flow/SystemMonitor.cpp, flow/SystemMonitor.h
I didn't realize that status works via collecting traceevents from workers, so I'm trimming my plans down to just "hz", and the playbooks can link to a dashboard that aggregates TLSPolicyFailure trace events itself.
A trimmed status json from a failing process now looks like:
```
{
"cluster" : {
"processes" : {
"bd91289b650802668e2217cc68f0463b" : {
"address" : "127.0.0.1:5000:tls",
"network" : {
"tls_errors" : {
"hz" : 0.4
}
}
}
}
}
}
```
=> Add TLS Policy Failure count to ProcessMetrics and status json

fdbclient/DatabaseConfiguration.h, fdbserver/ClusterController.actor.cpp, fdbserver/Status.actor.cpp, fdbserver/TagPartitionedLogSystem.actor.cpp
The satellites serve no purpose when we only are replication to one region, and we have observed out of memory errors when they are recruiting in this situation.
=> do not recruit satellite tlogs when usable regions=1

fdbserver/DataDistribution.actor.cpp, fdbserver/DataDistribution.actor.h, fdbserver/DataDistributionTracker.actor.cpp
Avoid calling into SABTF so frequently. Use a cheaper call that only checks that shards exist. This is intended to address a regression in a recent release.
=> Improve performance of get team requests.

fdbserver/Knobs.cpp, fdbserver/Knobs.h, fdbserver/OldTLogServer_6_0.actor.cpp, fdbserver/TLogServer.actor.cpp, flow/genericactors.actor.h
If a process with a bad disk is recruited to become a TLog, it can hang instead of failing when creating its disk queue file.
=> Treat a tlog which takes a long time to create its disk queue as failed

documentation/sphinx/source/downloads.rst, documentation/sphinx/source/release-notes.rst, fdbserver/TagPartitionedLogSystem.actor.cpp
Increasing the number of log routers in this location appears to cause some mutations to not make it to the secondary. This seems pretty fragile, so it should be investigated at some point to figure out what is happening.
=> reverted broken change and updated release notes for 6.2.19

flow/Stats.actor.cpp, flow/Stats.h
This documents the derivation for roughness, which has also been modified slightly:
* An unexplained factor of 2 was removed
* Window edges are handled differently. Now, roughness is calculated considering all the way back to the previous event rather than the beginning of the window. The time at the end of window after the last event is ignored.
* Subtract 1 from the previous value. This is intended to make the value a more standard variance.
=> Clean up and add comments to Roughness calculation

fdbclient/ManagementAPI.actor.cpp, fdbclient/StorageServerInterface.h, fdbrpc/FlowTransport.h, fdbrpc/sim2.actor.cpp, fdbrpc/simulator.h, fdbserver/LogSystemDiskQueueAdapter.actor.cpp, fdbserver/LogSystemPeekCursor.actor.cpp, fdbserver/OldTLogServer_6_0.actor.cpp, fdbserver/TLogInterface.h, fdbserver/WorkerInterface.actor.h, fdbserver/worker.actor.cpp, fdbserver/workloads/ConsistencyCheck.actor.cpp, fdbserver/workloads/RemoveServersSafely.actor.cpp
Nightly correctness test found multiple failures on master commit `0e6ac08f268e0e6e51bb471d59c58b98423542c2`.
This is an attempt to fix the error on `DDBalanceAndRemove.txt ` test workload.
Command to reproduce the error `-r simulation --logsize 1024MiB -f foundationdb/tests/slow/DDBalanceAndRemove.txt -b on -s 948610707`
Failure diagnosis: Simulation test's consistency check reboots or kills worker that has extra data file left on disk (ConsistencyCheck_ExtraStore). If worker is reliable, it reboots the worker; otherwise, it kills the worker. In the test case, the worker with extra store was a SS, is in the process of being kill but has not been killed. Before consistency check identifies the worker and reboots it, another workload changes coordinators using AutoQuorum. The same worker …
=> Fix correctness failure on master branch

fdbserver/BackupWorker.actor.cpp, fdbserver/Knobs.cpp, fdbserver/Knobs.h, fdbserver/TagPartitionedLogSystem.actor.cpp
Right now, the upload delay is hard coded as 10 and comes with the comment that Buggify the delay will cause consistency check failure. 
This draft PR is to investigate why we cannot buggify it and then buggify it.
=> Buggify upload delay when backup worker upload data to blob

fdbserver/RestoreWorker.actor.cpp, tests/slow/ParallelRestoreCorrectnessAtomicOpTinyData.txt, tests/slow/ParallelRestoreCorrectnessCycle.txt
We want to test if the new restore works well when the destination FDB cluster has failures.
We adds restore workers into protected address list to prevent them from being killed, since the current restore assumes its process does not crash.
This allows us to enable assassination workload to kill other processes in simulation.
=> Performant restore [21/xx]: Enable assassination workload in restore test

tests/CMakeLists.txt, tests/slow/ParallelRestoreCorrectnessMultiCycles.txt
This aims to increase the test pressure on the new performance restore system.
=> Performant restore [22/xx]: Introduce multiple cycle tests for the restore

tests/slow/ParallelRestoreCorrectnessAtomicOpTinyData.txt, tests/slow/ParallelRestoreCorrectnessCycle.txt, tests/slow/ParallelRestoreCorrectnessMultiCycles.txt
For each parallel restore tests, enable Rollback test workload and abortAndRestartAfter option in BackupAndParallelRestoreCorrectness. 
This is an effort to improve test coverage for the new restore system.
=> Performant restore [23/xx]: Enable Rollback test workload and abortAndRestartAfter option for restore tests

fdbserver/masterserver.actor.cpp
As far as I can tell, the intent here is that recoverAndEndEpoch should only throw, and shouldn't ever actually become ready.
=> Assert recoverAndEndEpoch does not become ready

fdbbackup/backup.actor.cpp, fdbclient/BackupAgent.actor.h, fdbclient/FileBackupAgent.actor.cpp, fdbserver/RestoreMaster.actor.cpp, fdbserver/workloads/AtomicRestore.actor.cpp, fdbserver/workloads/BackupAndParallelRestoreCorrectness.actor.cpp, tests/CMakeLists.txt, tests/slow/ApiCorrectnessAtomicRestore.txt, tests/slow/ParallelRestoreApiCorrectnessAtomicRestore.txt
The old restore has been tested with API correctness workload.
This is an effort to add that test for the new performant restore.
This also help improve the test coverage for the new backup because the new backup is only integrated with the new restore's simulation test workloads.
Note: This PR is WiP until it is marked as Ready.
=> Add ApiCorrectnessAtomicRestore workload for the new performant restore

fdbclient/NativeAPI.actor.cpp, fdbserver/workloads/Watches.actor.cpp
The `self` pointer may point to invalid memory after a wait in `watch`, so try to prevent a potential heap-use-after-free
=> Test watch outliving transaction

fdbbackup/FileDecoder.actor.cpp, fdbserver/BackupWorker.actor.cpp
This will make the log bytes written available to backup status and describe backup calls.
This PR is part of #1003
=> Update mutation bytes written for new backups

bindings/go/src/fdb/transaction.go, documentation/sphinx/source/api-common.rst.inc, documentation/sphinx/source/api-python.rst, documentation/sphinx/source/api-ruby.rst
This was missed from original PR #1756, where only C API was documented.
Java API was documented inline.
This will fix #2856.
=> Add documentation of get_approximate_size for Python, Ruby, and Go

flow/Net2.actor.cpp
This includes N2_ReadError and N2_WriteError.
=> Fix boost error trace event fields to match other trace events by the same name

design/tlog-spilling.md.html
I stupidly merged #2088 without double checking how all the changes to the file get rendered, and there were a few things that looked bad, so here's quick fixes.
=> Fix a few markdown rendering issues in TLog spilling design doc.

fdbserver/VersionedBTree.actor.cpp
Now that the windows compile error fix has been merged, ART can be reenabled.
=> Re-enable ART mutation buffer in Redwood.

README.md
Make builds one project to completion, and then builds the next project.
Ninja can build multiple projects in parallel, and thus is strictly faster.
=> Make the README give instructions to use ninja to build.

fdbbackup/backup.actor.cpp, fdbclient/BackupAgent.actor.h, fdbclient/FileBackupAgent.actor.cpp, fdbclient/SystemData.cpp, fdbclient/SystemData.h, fdbserver/BackupWorker.actor.cpp, fdbserver/workloads/BackupAndParallelRestoreCorrectness.actor.cpp, fdbserver/workloads/BackupCorrectness.actor.cpp
To pause/resume the backup workers, the fdbbackup command will write to the
backupPausedKey. Then backup workers noticed the value of the key has been
changed and stops/resumes pulling from TLog.
This is part of #1003.
=> Add pause/resume for new backups

fdbserver/RestoreApplier.actor.cpp, fdbserver/RestoreCommon.actor.h, fdbserver/RestoreLoader.actor.cpp
The bug was introduced in the previous PR that restore applier can have mysterious segmentation fault. 
After this fix, there is no error found by correctness by running 100K restore-on-old-backup tests only. The 100K backup-and-restore focused correctness run is more intense than the 100K correctness runs that include all test workloads, because other tests are irrelevant with the backup and restore systems.
=> Performant restore [26/xx]: Fix the remaining rare error

bindings/go/src/fdb/generated.go, documentation/sphinx/source/api-common.rst.inc, documentation/sphinx/source/release-notes.rst, fdbclient/vexillographer/fdb.options
Includes other latent generated go changes to the documentation.
=> Including port in addresses option is deprecated in 630 rather than 700

fdbserver/RestoreApplier.actor.cpp, fdbserver/RestoreApplier.actor.h
Version stamp ops are converted into SET at the proxy, so the backup files will never have them.
This is a part of #2858
=> Remove version stamp ops from RestoreApplier

fdbclient/BackupContainer.actor.cpp, fdbclient/BackupContainer.h, fdbserver/BackupProgress.actor.cpp, fdbserver/BackupProgress.actor.h, fdbserver/BackupWorker.actor.cpp, fdbserver/RestoreMaster.actor.cpp, fdbserver/workloads/BackupAndParallelRestoreCorrectness.actor.cpp
Consolidate `describePartitionedBackup()` into `describeBackup()` and remove `isPartitionedBackup()`, `getPartitionedRestoreSet()`.
This is a part of #2858
=> Consolidate backup container APIs

fdbclient/FDBTypes.h, fdbclient/RestoreWorkerInterface.actor.h, fdbserver/Knobs.cpp, fdbserver/Knobs.h, fdbserver/RestoreApplier.actor.cpp, fdbserver/RestoreApplier.actor.h, fdbserver/RestoreLoader.actor.cpp, fdbserver/RestoreUtil.h
With this PR, loaders no longer has the constraint: mutations in a message sent to applier must belong to the same version.
The size of mutation message is tunable.
=> Performant restore [28/xx]: Improve bandwidth of sending mutations from loaders to appliers

fdbserver/KeyValueStoreMemory.actor.cpp
KeyValueStoreMemory now uses key delta compression in partial snapshots.  This is done with a new log opcode, OpSnapshotItemDelta, so old files can still be read but new files would not be readable by the old code.
This should improve recovery speed from disk of the txnStateStore.
=> Added key delta compression to KeyValueStoreMemory on-disk state. 

fdbserver/CoroFlow.actor.cpp, fdbserver/KeyValueStoreSQLite.actor.cpp, flow/IThreadPool.cpp, flow/IThreadPool.h, flow/Trace.cpp
When one of the reader or writer thread pools fails, the other is now failed with the same error.
=> Fix assertion failure in SQLite thread pools on io_error

flow/CMakeLists.txt
This cmake line generated a bogus and nonsensical include path, so as
the entire line isn't necessary, just remove it.
Thus finally answering where this strange line came from in my compile_commands.json.
=> Remove `-isystem flow/-lpthread` from INCLUDES/CXXFLAGS

fdbserver/RestoreCommon.actor.cpp
Whenever a backup file (range or log) throws error in parsing, treat it as failure.
=> Treat backup file parsing error as failure

fdbrpc/AsyncFileKAIO.actor.h, fdbrpc/Net2FileSystem.cpp
- Adds some asserts in KAIO to ensure that when knob is set, we don't
end up using KAIO in any case.
- Fixes a bug where we initialize AsyncFileKAIO on Linux builds even
when KAIO is disabled. This can cause problems in systems such as
Windows Subsystem for Linux where KAIO is not supported.
FIXES #2382
=> Net2FileSystem: Add guards to honor DISABLE_POSIX_KERNEL_AIO

fdbclient/NativeAPI.actor.cpp, flow/TLSConfig.actor.cpp, flow/TLSConfig.actor.h
If client code initiates an FDB operation to a TLS cluster, and then
immediately exits the main thread, then OpenSSL's atexit handler would
potentially run while the network thread is attempting to do TLS
operations, and thus crash.
This commit removes the OpenSSL atexit hander, and instead relies on a
client intentionally ending the network thread to do TLS cleanup.  If
the client code exits without stopping the network thread, then we'll
never free OpenSSL data structures, which is the safer thing to do.
This addresses #2841, but with caveats that will be added to the bug.
=> Fix clients crashing in TLS code on exit.

fdbclient/BackupContainer.actor.cpp, fdbserver/BackupProgress.actor.cpp, fdbserver/BackupWorker.actor.cpp, fdbserver/TagPartitionedLogSystem.actor.cpp
The oldest epoch the master gets can assume its begin version is some lower number (e.g., 1), which can be wrong. In this case, we use the saved backup progress to "true-up" the real begin version.
Another true-up is done for a backup's begin version to the exact version of the first mutation. This is needed to ensure the strict less than relationship between two mutation logs, if one's version range is within the other.
A problematic scenario is as follows:
Epoch 1: a mutation log A [200, 900] is saved, but its progress is NOT saved.
Epoch 2: master recruits a worker for [1, 1000], 1000 is epoch 1's end version.
New worker saves a mutation log B [100, 1000]
A's range is strict within B's range, but A's size is larger than B.
This happens because B's start version is true-up to the …
=> Fix backup progress calculation

flow/Net2.actor.cpp
There were similar TraceEvents in the FDBLibTLS/LibreSSL TLS
implementaiton that were accidentally dropped in the TLS rewrite.
This makes it so that one does not have to use magic to figure out if a
process was configued with TLS correctly when some of the settings come
from environment variables.
=> Log Net2TLSConfig with paths and settings when using TLS.

cmake/InstallLayout.cmake
Before, the file /etc/foundationdb conflicted between the server and
clients package, and /usr/lib64/cmake and /usr/lib64/pkgconfig
conflicted with some system packages.
=> Prevent server and clients rpm's from conflicting

ACKNOWLEDGEMENTS, bindings/java/src/junit/com/apple/foundationdb/tuple/ArrayUtilTests.java, bindings/java/src/main/com/apple/foundationdb/tuple/ByteArrayUtil.java, bindings/java/src/main/com/apple/foundationdb/tuple/FastByteComparisons.java
Manually ran the unit tests and then added them to the ArrayUtilTests.  
This is a standard optimization for java key value stores and query layers (Tez, HBase, Cassandra).  This code path is used quite a bit by the fdb-record-layer.
=> Fix #2822: ByteArrayUtil does not use the now standard Unsafe Approach for byte[] comparisons.

ACKNOWLEDGEMENTS, bindings/java/CMakeLists.txt, bindings/java/src/junit/com/apple/foundationdb/tuple/ArrayUtilTests.java, bindings/java/src/main/com/apple/foundationdb/tuple/ByteArrayUtil.java, bindings/java/src/main/com/apple/foundationdb/tuple/FastByteComparisons.java
This is a continuation of https://github.com/apple/foundationdb/pull/2823
=> Fix #2822: ByteArrayUtil does not use the now standard Unsafe Approach for byte[] comparisons

fdbclient/BackupAgent.actor.h, fdbclient/BackupContainer.actor.cpp, fdbclient/BackupContainer.h, fdbclient/FileBackupAgent.actor.cpp, fdbclient/JSONDoc.h, fdbserver/RestoreCommon.actor.cpp, fdbserver/RestoreCommon.actor.h, fdbserver/RestoreLoader.actor.cpp, fdbserver/RestoreMaster.actor.cpp, fdbserver/workloads/BackupAndParallelRestoreCorrectness.actor.cpp
This information can be very useful in knowing the content in these files, especially for restores.
The `RestorableFileSet` has been changed to provide range file's key ranges read from the manifest, as well as providing the continuous logs' version range.
Now the manifest looks like:
```
{
"beginVersion": 503220272,
"endVersion": 782301777,
"files": [
"kvranges/snapshot.000000000498286936/0/range,782301777,9dfec472659756f8d2547ffca4b00570,1048576",
"kvranges/snapshot.000000000498286936/0/range,775960292,d6e5f43d28f6c6abb286d1f5513e50d2,1048576",
"ranges/0000000/0007/range,769914768,8363975cad03a74170d519014ab2a286,868778",
"kvranges/snapshot.000000000498286936/0/range,764039809,e45e003119bd2ac558c29fe9210d9bb1,342769",
"ranges/0000000/0007/range,752129017,91d5ea777b3b80c7c920a80965c939f7, …
```
=> Write range files' begin & end keys to backup's manifest file

fdbclient/NativeAPI.actor.cpp, fdbrpc/AsyncFileEIO.actor.h, fdbrpc/AsyncFileWinASIO.actor.h, fdbrpc/FlowTests.actor.cpp, fdbrpc/Net2FileSystem.cpp, fdbrpc/Net2FileSystem.h, fdbrpc/sim2.actor.cpp, fdbserver/fdbserver.actor.cpp, flow/Net2.actor.cpp, flow/network.h
This will stop eio threads for both the client (`fdb_stop_network()`)
and the server.  This change is being done more for the former, but I
don't see any harm in doing the latter as well.
Tested using an (AJ-provided) [reproduction test](https://gist.github.com/alexmiller-apple/0ac7c4cea6b0b2b746677e61af1def4b), where one attaches gdb and looks at the threads that exist after `fdb_stop_network()` is called.
Before:
```
0x00007f1c6469d728 in __GI___nanosleep (requested_time=requested_time@entry=0x7ffe00ae7310, remaining=remaining@entry=0x7ffe00ae7310)
at ../sysdeps/unix/sysv/linux/nanosleep.c:28
28	  return SYSCALL_CANCEL (nanosleep, requested_time, remaining);
Missing separate debuginfos, use: dnf debuginfo-install libgcc-8.3.1-2.fc29.x86_64 libstdc++-8.3.1-2.fc29.x86_64
(gdb) thread …
```
=> Stop background eio threads on Net2::stop()

bindings/go/CMakeLists.txt
Added support for getting go dependencies before install source
This is needed to allow support of third-party libraries not included in source or build environment
=> Get Go Dependencies Before Installing

build/gen_dev_docker.sh
Without this, vscode complains that clangd just crashes.
Also make ~/bin/clangd executable
=> Don't simulate a TTY if clangd is invoked by IDE

flow/flat_buffers.cpp, flow/flat_buffers.h
We recently witnessed (using tsan) that if the main thread exits without first
joining the network thread, we can see data races and
heap-use-after-free's in flatbuffers globals.
Now the lifetime of these globals will be tied to the network thread
itself (and I guess every thread, but the one that actually uses memory
will be owned by the network thread.)
Fixes #2463
=> Prevent main thread from destroying flatbuffers globals

fdbserver/BackupWorker.actor.cpp
Fixed:
- Backup worker saves the same version's mutations in multiple log files, which violates the contract with restore;
- Backup container may contain empty minRestorableVersion
This is part of #2858
=> Backup fixes

flow/Net2.actor.cpp
Which is to proceed past Net2 creation, and allow certificate refresh to
try and eventually load valid certs.  Additionally, fix certificate
refeshing dieing if the certificate is not readable when first called.
In testing, I also found and fixed an issue where if a cert went from
unreadable to readable, we wouldn't reload the TLS context, due to not
considering it as a file change.
---
This PR builds on top #2980, which should be merged first, and then all but one of the commits here will drop out.
Fixes #2992 
---
```
FDBLibTLS/testdata $ mv test-client-1.pem test-client-1.pem.bak
```
```
$ FDB_TLS_CA_FILE=FDBLibTLS/testdata/test-ca-1.pem FDB_TLS_CERTIFICATE_FILE=FDBLibTLS/testdata/test-client-1.pem FDB_TLS_KEY_FILE=FDBLibTLS/testdata/test-client-1.pem ./bin/fdbcli  -C ../local.cluster …
```
=> Match 6.2.15's behavior in how invalid/unreadable/non-existent certs are handled.

fdbclient/StorageServerInterface.h, fdbserver/DataDistribution.actor.cpp, fdbserver/Knobs.cpp, fdbserver/Knobs.h, fdbserver/StorageMetrics.actor.h, fdbserver/storageserver.actor.cpp, fdbserver/workloads/KillRegion.actor.cpp
Mark lagging storage servers as undesired. Fixes #1510.
Mark storage servers which are not progressing as undesired. Fixes #1184.
Have a backstop mechanism from not marking too many storage servers as undesired.
=> Mark the storage servers that are continually lagging as unhealthy

flow/flat_buffers.cpp
The vtables are sorted by address, so ASLR makes this test
non-deterministic
=> Remove brittle ASSERT

design/backup_v2_partitioned_logs.md
The new backup system the new backup system introduces a new role, backup worker, to pull mutations from transaction logs and save them, thus removing the burden of saving mutation logs into the database.
This work is tracked in #1003 and has been merged into master.
=> Add design doc for the new backup system

fdbclient/BackupContainer.actor.cpp
The sanity check parses each range file to get its key range and use the parsed key range to validate the metadata file's content.
The parsing currently incurs restore_unsupported_file_version error.
Because we haven't used the backup metadata file, we disable the check for now to have a cleaner nightly correctness results.
We need to include this sanity check before 6.3 release.
=> Remove sanity check on backup metadata file

cmake/FlowCommands.cmake
Fixes #2985
This was originally done in 0443cf89eafdaaf7db813b3229f01a0debe0de37,
and removed in 75f692b9317b42bc3237e940228cf23d996dea35, but I'm
not sure why it was removed. I'm guessing it was a botched merge.
Separately it looks like 5c294e2646 removed this dependency in the name of fixing parallel builds on Windows. If this PR breaks parallel builds on windows, maybe we can just leave the WIN32 branch as is.
=> Depend on actorcompiler.exe

flow/genericactors.actor.cpp, flow/genericactors.actor.h
I don't know if this measurably improves performance or not, but I feel like we should avoid unnecessary copies just as good hygiene
=> Avoid some unnecessary copies in generic actors

bindings/go/src/fdb/futures.go
Running Go bindings with `-race` argument will enable instrumentation to check
pointer conversions, and complain about potential unsafe conversion in
`stringRefToSlice`.
This patch adds annotation `go:nocheckptr` annotation to skip that check, since
our conversion is safe, and can let users take advantage of check for their code
without this false positive.
It will be useful to check if, we can potentially rewrite this code to obey Go
pointer conversion rules.
FIXES #2843
=> go: Don't complain about unsafe pointer conversion in stringRefToSlice

fdbbackup/FileConverter.actor.cpp, fdbclient/BackupAgent.actor.h, fdbclient/BackupContainer.actor.cpp, fdbclient/BackupContainer.h, fdbclient/FileBackupAgent.actor.cpp, fdbserver/BackupWorker.actor.cpp, fdbserver/RestoreLoader.actor.cpp, fdbserver/RestoreMaster.actor.cpp
Several bug fixes:
- A memory corruption bug introduced in #2966
- Fixed the backup unit test to write range files in the right format.
- Fixed a rare corruption bug due to incorrect restore version.
This PR fixes #3020.
=> Several bug fixes for new backups

bindings/go/src/fdb/directory/directorySubspace.go, bindings/go/src/fdb/subspace/subspace.go, bindings/go/src/fdb/subspace/subspace_test.go, bindings/go/src/fdb/tuple/tuple.go, bindings/go/src/fdb/tuple/tuple_test.go
This PR is built on top of yet unmerged #2421. 
- Instead of printing plain bytes, this one produces human-readable output which is consistent with out Python and Java bindings. The examples of output can be found in `test_tuple.go` file in this patch.
- Minor refactoring by renaming `Subspace.b` to `Subspace.rawPrefix`.
- Implements `Stringer` interface for `UUID`.
- Don't enforce `fmt.String()` in `Subspace` interface. This will enforce implementing `String()` for all types that implement Subspace, which in turn will break out current build. Since Go uses duck-typing, its also unnecessary because any type that implements `String()` will automatically be treated as `String()`.
Notes:
- ~~Currently, `Stringer` for VersionStamp is missing.~~
- Missing `DirectorySubspace.String()` …
=> go: Update Stringer interface on Tuple and Subspace

cmake/AddFdbTest.cmake
Source generated by vexilographer were not copied into bindingtester. This patch
manually adds those files in `cmake/AddFdbTest.cmake`, since there doesn't seem
to be any easy way to make bindingtester script know about these generated
files (except copying these files to source directory).
FIXES #3029
=> cmake: Copy generated files to bindingtester bundle

documentation/sphinx/source/release-notes.rst, fdbclient/HTTP.actor.cpp, flow/network.h
HTTP client was using stated contract for IConnection, which was different from the contract assumed by FlowTransport and implemented by SSLConnection.  Updated HTTP client, added comments to IConnection to clarify the actual interface contract.
This only has been an issue since the switch to boost ssl_socket.
=> Bug fix:  HTTPS requests could hang.

fdbclient/BackupContainer.actor.cpp
Which can increase the false positive rate of TooManyFiles error.
The backup-metadata file is not used by 6.2 restore or the new performant restore.
=> Fix:Disable sanity check backup-metadata file

fdbclient/ReadYourWrites.actor.cpp, fdbserver/workloads/VersionStamp.actor.cpp
CC #1685
Let's test this in simulation, and if that doesn't show any problems I suggest we change the documentation to allow set_versionstamped_key without ryw. As far as I can tell we support it just fine.
=> Test SetVersionstampedKey without ryw enabled

fdbserver/Status.actor.cpp
Using the old name results in the field being missing in status
=> Use the updated field name in status when fetching process busyness info

fdbserver/RestoreApplier.actor.cpp, fdbserver/RestoreLoader.actor.cpp, fdbserver/RestoreWorker.actor.cpp
Trace.error() must explicitly include `error_code_actor_cancelled`
to handle the error.
Typically, we will not report error on `error_code_actor_cancelled `.
In the fast restore worker, we want to know when fast restore worker exists for more diagnosis info.
=> Fix Valgrind error InvalidSuppression_FastRestoreWorkerError

cmake/AddFdbTest.cmake, tests/TestRunner/TestRunner.py
So that tests with ASSERTion failures don't cause CI to run slow and
produce massive logs.  There's also rarely a reason to continue through
assertion failures.
=> Make ctest use --crash when running simulation tests.

fdbclient/CommitTransaction.h
During vtable collection, neither `isSerializing` or `isDeserializing` is true. In this case, we are calling `serialize` with an uninitialized `MutationRef`, so we can't inspect its `type` member.
=> MutationRef serialization depended on uninitialized data

fdbserver/worker.actor.cpp
It seems some of the file handling mechanisms of simulation prevented the file from being cleaned up properly. This changes the delete function called and drops the reference to the `IAsyncFile` handle so that simulation can clean it up properly.
=> More aggressively cleanup a bad process ID file in simulation

flow/flat_buffers.cpp, flow/flat_buffers.h
As of #2188, we expect to see flatbuffers messages with many empty strings within them. Save 4 bytes per additional empty string by pointing relative offsets for all empty strings to the same memory.
=> Reduce size of flatbuffers messages

bindings/go/src/fdb/generated.go
Simply runs `vexilographer` on `fdb.options` for Go.
=> go: Update `generated.go` for 6.3

fdbclient/FileBackupAgent.actor.cpp, fdbclient/RestoreWorkerInterface.actor.h, fdbserver/Knobs.cpp, fdbserver/Knobs.h, fdbserver/RestoreApplier.actor.cpp, fdbserver/RestoreApplier.actor.h, fdbserver/RestoreCommon.actor.h, fdbserver/RestoreLoader.actor.cpp, fdbserver/RestoreLoader.actor.h, fdbserver/RestoreMaster.actor.cpp, fdbserver/RestoreRoleCommon.actor.cpp, fdbserver/RestoreRoleCommon.actor.h, fdbserver/fdbserver.actor.cpp
In simulation test, we didn't see a key not exist in the destination DB. 
In a circus test, I saw it could be a case. 
To diagnose the problem and understand which key does not exist when it happens, appliers should retry and then continue.
This PR also has other non-functional clean ups, such as removing unused field in RestoreRequest.
=> Performant restore: Various improvements based on circus test

fdbserver/DeltaTree.h, fdbserver/IPager.h, fdbserver/VersionedBTree.actor.cpp
This is a large refactor of how commitSubtree works with regard to internal pages.  Numerous comparisons of adjacent internal boundary keys and mutation buffer lookups are avoided.  More can be done, but for random workloads on large trees this will result in a massive reduction in CPU overhead, on the order of (branching factor / paths affected by mutations).
=> Redwood Update - Internal page incremental updates and efficient cleared/unchanged subtree skipping

ACKNOWLEDGEMENTS, bindings/c/CMakeLists.txt, bindings/c/generate_asm.py, cmake/ConfigureCompiler.cmake, flow/Net2.actor.cpp, flow/Platform.cpp, flow/Platform.h, flow/ThreadPrimitives.h, flow/crc32c.cpp, flow/sse2neon.h
aarch64 (ARM) Linux Port
- Replace rdtsc with virtual counter
- SSE instructions to NEON (Used this project: https://github.com/DLTcollab/sse2neon)
- Prefetch using compiler builtin function provided by sse2neon (Presumably it will get translated into prfm instruction)
- Use native CRC instructions
- Ported assembly to generate backward-compatible entry points in libfdb_c.so
=> aarch64 Linux port

fdbclient/CoordinationInterface.h, fdbclient/FDBTypes.h, fdbclient/MonitorLeader.actor.cpp, fdbclient/MonitorLeader.h, fdbserver/Coordination.actor.cpp, fdbserver/CoordinationInterface.h, fdbserver/LeaderElection.actor.cpp, fdbserver/worker.actor.cpp, fdbserver/workloads/Sideband.actor.cpp
Storage servers might need to become the cluster controller if no other process in the same DC can become the cluster controller and it is the preferred data center.
A cluster controller should be considered failed if we do not see in serverDBInfo because it means the interface we are talking to has not become a cluster controller.
Forwarding leader information was broken, and could write a cluster file without verifying the new coordinators are active.
The sideband workload did not support errors being thrown from getReadVersion()
=> Fixed a number of problems with monitorLeaderRemotely

fdbserver/Knobs.cpp, fdbserver/Knobs.h, fdbserver/worker.actor.cpp
This will prevent all storage servers from attempting to become the cluster controller, because the ones with the shorter delay will become the cluster controller and then let the other ones know it exists.
=> Added a large random delay on failure detection

fdbserver/workloads/FuzzApiCorrectness.actor.cpp
When getting a special key and the relaxed option isn't set.
Also some whitespace changes on adjacent lines from git clang-format. I can back these out if someone opposes them.
=> Allow error_code_special_keys_no_module_found

fdbserver/StorageMetrics.actor.h
This fixes a rare bug where `endKey` might be reset to the `beginKey` by the `lower_bound` call, and thus the loop makes no progress and got stuck.
=> Fixed a bug where the loop might get stuck.

fdbserver/workloads/ReadHotDetection.actor.cpp
This was due to storing a value in a non-standalone StringRef.
=> Fix invalid memory access in ReadHotDetection test

fdbserver/RestoreApplier.actor.cpp, fdbserver/RestoreMaster.actor.cpp, fdbserver/RestoreWorker.actor.cpp
This resolves issue: https://github.com/apple/foundationdb/issues/3146
=> Fast restore: Delay leader election after restore request is set

fdbserver/Ratekeeper.actor.cpp
Ratekeeper is its own role but we don't pass its ID when we trace messages. This PR fixes this and makes the behavior consistent with other roles.
=> Pass Ratekeeper ID to all RK traces

fdbclient/DatabaseContext.h, fdbclient/NativeAPI.actor.cpp, fdbclient/SpecialKeySpace.actor.cpp, fdbclient/SpecialKeySpace.actor.h, fdbserver/workloads/ReportConflictingKeys.actor.cpp, fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp, tests/fast/RandomUnitTests.txt
- Allow all clients to run the test in `ReportConflictingKeys` and `SpecialKeySpaceCorrectness`
- Reformat part of the code for `module` in special-key-space
- Add tests to make sure `special_keys_cross_module_read` is thrown correctly
- Solve several [issues](https://github.com/apple/foundationdb/issues/2979)
TODO(In following PRs):
- Add documentation for the `module` concept in special-key-space
- Merge [dd_metrics](https://github.com/apple/foundationdb/pull/2547) into special-key-space
=> Improvement on special key space

contrib/transaction_profiling_analyzer/transaction_profiling_analyzer.py
* Fetch the boundary keys once and cache the results
* Try to get addresses for shards in the same transaction and in parallel
* Simplify the range count logic (this seems not to be a clear win performance-wise, I've seen this go twice as fast or take 50% longer)
Also added a flag to enable ports on addresses.
=> Performance improvements to the transaction profiling analyzer

documentation/sphinx/source/mr-status-json-schemas.rst.inc, fdbclient/Schemas.cpp, fdbserver/Status.actor.cpp
The fields are `worst_version_lag_storage_server` and `limiting_version_lag_storage_server`.
=> Remove deprecated fields in status

fdbbackup/backup.actor.cpp
Arguments specified using an '=' would truncate the '=' and value.
=> Backup's ProgramStart command line string was incomplete

fdbclient/ClientLogEvents.h, fdbclient/NativeAPI.actor.cpp, fdbserver/workloads/ClientTransactionProfileCorrectness.actor.cpp
This is not the most efficient implementation. But it is quick and easy one. All these inefficiencies will be gone once we switch to flat buffers
=> Add locality data

fdbbackup/backup.actor.cpp
These two options used the incorrect number of hyphens and were deprecated in a patch release of 6.2, to be deleted in 6.3.
=> Remove erroneous restore options

fdbserver/workloads/ConfigureDatabase.actor.cpp
This is safe when no backups are running. We can't run with
backup_worker_enabled:=1 and a running backup job, and then switch to
backup_worker_enabled:=0, because no backup workers will be available then.
=> Toggle backup mode in ConfigureDatabase workload

design/special-key-space.md, fdbclient/NativeAPI.actor.cpp, fdbclient/ReadYourWrites.actor.cpp, fdbclient/ReadYourWrites.h, fdbclient/SpecialKeySpace.actor.cpp, fdbclient/SpecialKeySpace.actor.h, fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp
Previously the special key space would take a reference to the
transaction, but this doesn't make sense since the transaction might not
be refcounted
Some context: https://forums.foundationdb.org/t/use-after-free-when-having-addref-on-readyourwritestransaction-object/2127/4
=> Cancel pending special key space reads on destroy

fdbserver/BackupWorker.actor.cpp
When a backup worker stops pulling for an old epoch, we cannot clear mutations.
This is because these muations are needed for saving.
This is part of #2858.
=> Fix a super rare missing mutation bug in backup workers

design/special-key-space.md, fdbserver/MasterProxyServer.actor.cpp, fdbserver/workloads/ReportConflictingKeys.actor.cpp
Two minors:
- fix typos in special-key-space doc
- add assertions and traces in `ReportConflictingKeys` for debugging
Major one (`MasterProxyServer.actor.cpp`):
Fix a bug caught by a nightly test that happens when we have multiple resolvers.
Previously, I only add logic to handle the case that `commitTransactionRef` is only sent to specific resolvers. However, not only the `commitTransactionRef` but also the `read_conflict_range` is can be omitted.  Thus I need to add the logic to handle the index mapping for `read_conflict_range`. 
Context: in the beginning, we return narrowed key ranges from resolvers, which contains conflicting keys. After discussion, to reduce overhead, we change to send back indices of `read_conflict_range` that caused conflicts. Instead of returning keys,  numbers …
=> Fix nightly failure in ReportConflictingKeys test

fdbcli/fdbcli.actor.cpp
There should be no completion options, but it would continue showing "auto" as an option.
=> Auto completion choices for "throttle disable auto" were wrong

documentation/sphinx/source/command-line-interface.rst, documentation/sphinx/source/release-notes.rst, fdbcli/fdbcli.actor.cpp, fdbclient/ManagementAPI.actor.cpp, fdbclient/ManagementAPI.actor.h
Add the `lock`, `unlock`, `getversion`, and `advanceversion` commands to release 6.2. The PRs these come from are at https://github.com/apple/foundationdb/pull/2883, https://github.com/apple/foundationdb/pull/2890, and https://github.com/apple/foundationdb/pull/2965.
=> Add several new fdbcli commands to 6.2

documentation/sphinx/source/api-c.rst
=> Document that fdb_run_network can only be run once ever during the lifetime of a program

fdbclient/NativeAPI.actor.cpp, fdbrpc/FlowTests.actor.cpp, fdbrpc/sim2.actor.cpp, flow/Net2.actor.cpp, flow/error_definitions.h, flow/network.h
=> Eliminate the undefined behavior of calling run_network twice, instead returning an error

documentation/sphinx/source/api-version-upgrade-guide.rst, documentation/sphinx/source/release-notes.rst
Also add a release note for changes to the `\xff\xff/worker_interfaces/` keyspace and a couple minor release notes fixes.
=> Update the API version upgrade guide for 6.3

flow/Deque.h
This reverts commit e898cb7f38ba7a5ba501001c5dc748ded8bfa192, reversing
changes made to 18c2c3d346c48fb62e532647f09e4c5d1987d427.
Nightly correctness founds failures at rate of 1 out of 10k tests. 
Reverting the PR cleans the correctness. 
Root reason is still in investigation.
=> Revert "Merge pull request #3197 from tclinken/optimize-deque-copy-ctor"

documentation/sphinx/source/command-line-interface.rst, fdbcli/fdbcli.actor.cpp
These commands are present when typing ``help`` in ``fdbcli``, but they were not part of our online documentation.
Some of these commands control features which are currently not very well documented (e.g. profiling, consistency check, zone IDs). I've regarded adding that extra documentation as being outside the scope of this PR, but we should work to add it in the future. I don't think that it should prevent us from adding this documentation, but if there is disagreement I can omit some commands as needed.
=> Add documentation for several missing fdbcli commands

documentation/sphinx/source/api-c.rst, documentation/sphinx/source/api-common.rst.inc, documentation/sphinx/source/api-python.rst, documentation/sphinx/source/api-ruby.rst
We test this combination now (#3067), and don't know of any reason why
this shouldn't work
=> Remove warning about combining ryw-disabled w/ versionstamped keys

fdbclient/MultiVersionTransaction.h
It could be the case that db is null for old client versions
=> Only destroy db if non-null

cmake/InstallLayout.cmake
This flag is used by one of my recent PRs, but it wasn't added until 6.3.
=> Backport the GENERATE_DEBUG_PACKAGES flag to 6.2

fdbclient/HTTP.actor.cpp, flow/Net2.actor.cpp
Workarounds for strange behaviors in Boost ssl sockets on MacOS and Linux.  When writing to the ssl socket, write_some() would sometimes return BrokenPipe instead of WouldBlock unless onWriteable on the raw socket was checked first.  On MacOS, even with the onWriteable check using a send size greater than 2016 (determined experimentally) would still result in the error.  Also consolidated two identical copies of SendBufferIterator.
=> HTTPS workarounds for strange socket behavior

documentation/sphinx/source/release-notes.rst, fdbserver/worker.actor.cpp
In 6.2, this would have just been a process of `coordinator` class.
=> Fix: the cluster controller role could be recruited on a process class with NeverAssign fitness

fdbserver/BackupProgress.actor.cpp
Sometimes, the true-up has to go backup multiple epochs for saved versions,
because a tag's progress can be missing in an epoch. In other words, we need to
check progress for all tags.
This part of #2858
=> Fix a backup progress true-up bug

flow/IKeyValueContainer.h, flow/IndexedSet.cpp, flow/IndexedSet.h
Allows constant iteration over an `IndexedSet`, `Map`, or `IKeyValueContainer`. Outside of unit tests, this PR does not actually implement constant iteration anywhere, that can be done in separate pull requests.
=> Add IndexedSet::const_iterator

fdbclient/BackupAgent.actor.h, fdbclient/FileBackupAgent.actor.cpp, fdbserver/RestoreApplier.actor.cpp, fdbserver/RestoreCommon.actor.cpp
It turns out that the PR https://github.com/apple/foundationdb/pull/3283 complicates things. 
Txn handles the keys-not-exist by returning `Optional<Value>()`. 
This can simplify code.
Lesson learned: error_code_key_not_found is not an error thrown from txn. It is a customized error thrown from the old backup agent. ¯\_(ツ)_/¯
=> FastRestore: Simplify getAndComputeStagingKeys on RestoreApplier

fdbclient/FileBackupAgent.actor.cpp, fdbclient/ReadYourWrites.actor.cpp, fdbserver/RestoreApplier.actor.cpp, fdbserver/RestoreMaster.actor.cpp, fdbserver/RestoreWorker.actor.cpp, fdbserver/workloads/BackupAndParallelRestoreCorrectness.actor.cpp
Restore workers will only clear the key ranges that are going to be restored.
Also some improvements on the code.
We still need the restore-tool support to expose this functionality to DBA.
=> Fast Restore: Support restoring sub ranges in the framework

flow/Trace.cpp
`TraceBatch::flush()` calls `Net2::now()` from whatever thread `flush()` is called from, which causes a race with `Net2::updateNow()`. This PR moves the call to `flush()` onto the main thread which (should) make `TraceBatch` thread compatible.
=> Make TraceBatch no longer thread hostile

fdbbackup/backup.actor.cpp, fdbserver/fdbserver.actor.cpp
This is needed so that backup workers (fdbserver) can upload files to blobs.
This is part of #2858.
=> Set up blob credentials for backup workers

documentation/sphinx/source/release-notes.rst, flow/TLSConfig.actor.cpp
Refreshing TLS files was done to an incorrect location that resulted in random memory being wiped out. Also fixed a typo that loaded the key bytes into the CA bytes in some cases.
=> Fix invalid memory writes in TLS certificate refresh

fdbserver/Coordination.actor.cpp
When a process receives a message to the coordination interface, it in most circumstances starts reporting that it is a coordinator. If a non-coordinator process gets the `OpenDatabaseCoordRequest` or `ElectionResultRequest` message, it would start a function call `monitorLeaderForProxies` that would prevent this non-coordinator from stopping acting like a coordinator.
This change prevents starting `monitorLeaderForProxies` in circumstances where the request immediately returns, since it is not required.
This doesn't prevent a non-coordinator from ever reporting itself as a coordinator, but it does limit the amount of time it will do so in some cases. I'm not sure if the example I observed in #2837 matches one of these cases or not.
=> Avoid non-coordinator reporting coordinator role indefinitely

bindings/c/CMakeLists.txt, bindings/c/test/mako/mako.c
This addresses https://github.com/apple/foundationdb/issues/3232 by suppressing overly aggressive warnings.
=> Suppress array-bounds warnings in mako.c

fdbclient/SpecialKeySpace.actor.cpp, fdbclient/SpecialKeySpace.actor.h, fdbserver/DataDistributionTracker.actor.cpp, fdbserver/workloads/DataDistributionMetrics.actor.cpp, tests/DataDistributionMetrics.txt
The pr does several things:
- Fix a bug in `fetchShardMetricsList_impl`.  `containedRanges` breaks the contract. For example, the query range is `[b,e)` and `shards` contains `[b,c)` and `[d, f)`. Then by contract, we should return `\xff\xff/metrics/data_distribution_stats/b:<json_string>` and `\xff\xff/metrics/data_distribution_stats/d:<json_string>`. However, it only returns the first one. The tests did not catch the bug since we use the whole range or an exact range existing in `shards` in queries, which cannot trigger the bug.
- Add more complex getRange call using random keys
- Another potential issue is inconsistent results. The special-key-space originally only deal with local information which is not changed during the call or `get` which does not need to resolve keySelector. For …
=> Fix fetchShardMetricsList_impl and add read cache in special key space

fdbcli/linenoise/linenoise.c
Note for consideration: this is a file that has been obtained from an external source. This change could add a little friction when incorporating updates from the external version of this code, or it may require us making this change again if the source version isn't changed similarly.
=> Update a comment to remove use of word blacklist

fdbclient/RestoreWorkerInterface.actor.h, fdbserver/RestoreWorker.actor.cpp, flow/network.h
Endpoint for later restore step should have higher priority for
better performance: later step will not be blocked by the
next version batch's earlier steps.
=> FastRestore: Add priorities for loader and applier endpoints

fdbclient/SpecialKeySpace.actor.cpp, fdbclient/SpecialKeySpace.actor.h, fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp
The pr for this [post](https://forums.foundationdb.org/t/thoughts-on-cross-module-read-error-in-special-key-space/2177/10).
The goal is to make each module is treated as its own little keyspace by default.
The `special_keys_cross_module_read` error is thrown in two scenarios right now:
- Base keys of the begin key selector and the end key selector belong to different modules
- Two base keys belong to the same module, but one or two of them will read through the module’s boundary during key resolution
The code is to make the second one legal and set `readToBegin` or `readThroughEnd` as reference.
Also, the code adds an assertion for the `ryw` to be not `null`, which was the case in unit tests. Since we already have the correctness workload, the unit tests can be removed, and then `ryw` …
=> Update special_keys_cross_module_read error handler

fdbclient/RYWIterator.cpp, fdbclient/RYWIterator.h, fdbclient/SnapshotCache.h, fdbclient/WriteMap.h, fdbserver/IKeyValueStore.h, fdbserver/IPager.h, fdbserver/IVersionedStore.h, fdbserver/KeyValueStoreCompressTestData.actor.cpp, fdbserver/KeyValueStoreMemory.actor.cpp, fdbserver/KeyValueStoreRocksDB.actor.cpp, fdbserver/KeyValueStoreSQLite.actor.cpp, fdbserver/StorageMetrics.actor.h, fdbserver/VersionedBTree.actor.cpp, flow/IKeyValueContainer.h, flow/IndexedSet.h, flow/MetricSample.h, flow/RadixTree.h
Using the recently added IndexedSet::const_iterator (#3185), we can improve the const-correctness of many functions. In this PR const is added in some places where applicable. Also, wherever I came across the following while adding const, I made additional changes:
- virtual function overrides are marked as override
- NULL is replaced with nullptr
- git clang-format is applied
=> Improve const-correctness

fdbserver/MasterProxyServer.actor.cpp
This is a bug I found when working on https://github.com/apple/foundationdb/pull/3307 and decide to make the change a patch against 6.3.
- The problem is that GetReadVersionReply.recentRequests should always reflect the serving proxy's number of recent requests. Currently we may override it with other proxy's reply which is always 0 [1].
[1] https://github.com/apple/foundationdb/blob/master/fdbserver/MasterProxyServer.actor.cpp#L2086
=> Fix GetReadVersionReply.recentRequests to reflect a proxy's number of recent requests in the commit stats.

cmake/ConfigureCompiler.cmake
Some flags are not compatible with non-x86 platforms like aarch64.
=> Handle processor specific flags properly

fdbclient/ClusterInterface.h, fdbserver/RestoreMaster.actor.cpp, fdbserver/VersionedBTree.actor.cpp, fdbserver/WorkerInterface.actor.h, fdbserver/workloads/ApiCorrectness.actor.cpp, fdbserver/workloads/TPCCWorkload.h, flow/Arena.h, flow/flat_buffers.cpp
VectorRef<T> relies on T being trivially destructible, but this was not yet enforced. By statically asserting that T is trivially destructible, we avoid leaking memory by not calling the destructor for non-trivially destructible types.
=> Fix memory leaks in VectorRef

bindings/java/README.md, design/backup.md, design/recovery-internals.md, design/special-key-space.md, design/tuple.md
=> Corrects spelling mistakes in various markdown files.

contrib/transaction_profiling_analyzer/transaction_profiling_analyzer.py
When no reads are found, the logic used to process reads didn't work. This fix short-circuits that code.
=> Fix crash when no reads are found by the transaction profiling analyzer

documentation/sphinx/source/developer-guide.rst, fdbclient/NativeAPI.actor.cpp, fdbclient/Schemas.cpp, fdbclient/Schemas.h, fdbclient/SpecialKeySpace.actor.cpp, fdbclient/SpecialKeySpace.actor.h, fdbserver/workloads/DataDistributionMetrics.actor.cpp, fdbserver/workloads/Throttling.actor.cpp
Implements a slight variant of proposal 2 in https://forums.foundationdb.org/t/add-health-metrics-feature-to-special-key-space/2193/6. The difference is that logs and storages have separate keys now, allowing to define their schemas more precisely.
Also adds a field "Storages" to the data_distribution_stats which indicates the storage ids responsible for a shard. This combines well with the health metrics feature for application-level throttling. For example you could (if it makes sense for your application) move write load away from shards with high storage queue. Technically you could have gotten this information by joining information from status json and the locality api, but it would be less precise, more complicated, and more expensive.
Would like to get some feedback on the …
=> Expose health metrics via special keys

documentation/sphinx/source/downloads.rst
Per the [Python API docs](https://apple.github.io/foundationdb/api-python.html), Python versions 2.7-3.7 are now supported. This PR updates the [Download](https://www.foundationdb.org/download/) page to reflect that Py 3.6 and 3.7 are supported.
=> Update supported Python versions in downloads.rst

fdbclient/ClusterInterface.h, fdbserver/VersionedBTree.actor.cpp, fdbserver/WorkerInterface.actor.h, fdbserver/workloads/TPCC.actor.cpp, fdbserver/workloads/TPCCWorkload.h, flow/Arena.h, flow/ObjectSerializerTraits.h, flow/README.md, flow/flat_buffers.cpp, flow/network.cpp, flow/network.h
This simplifies the code some and allows us to use type traits more effectively. It also allows us to get rid of the `TRIVIALLY_DESTRUCTIBLE` macro.
=> Use STL for optional and variant

documentation/sphinx/source/api-python.rst
Fix a malformed auto-class reference in the description of the has_incomplete_versionstamp() class (located under the [Tuple layer section](https://apple.github.io/foundationdb/api-python.html#module-fdb.tuple).
=> Fix malformed class ref in Python API docs

contrib/TestHarness/CMakeLists.txt, contrib/TestHarness/Program.cs, contrib/TraceLogHelper/JsonParser.cs, contrib/TraceLogHelper/XmlParser.cs
This PR will enable TestHarness to read trace logs in JSON format.
The "TLS Plugin" change piggy backed to this PR is not necessarily required, but this will allow us (Snowflake) to test with older version of FDB.
=> Add JSON trace support in TestHarness

documentation/sphinx/source/mr-status-json-schemas.rst.inc, documentation/sphinx/source/release-notes/release-notes-620.rst, fdbclient/MasterProxyInterface.h, fdbclient/Schemas.cpp, fdbclient/StorageServerInterface.h, fdbrpc/CMakeLists.txt, fdbrpc/ContinuousSample.h, fdbrpc/Stats.actor.cpp, fdbrpc/Stats.h, fdbrpc/batcher.actor.h, fdbrpc/fdbrpc.vcxproj, fdbserver/Knobs.cpp, fdbserver/Knobs.h, fdbserver/LogRouter.actor.cpp, fdbserver/MasterProxyServer.actor.cpp, fdbserver/OldTLogServer_4_6.actor.cpp, fdbserver/OldTLogServer_6_0.actor.cpp, fdbserver/Status.actor.cpp, fdbserver/TLogServer.actor.cpp, fdbserver/storageserver.actor.cpp, flow/CMakeLists.txt, flow/flow.vcxproj
This includes min, max, mean, and various percentiles for read, commit, and GRV requests. Based on the current parameters, they are measured over a whole minute.
The percentiles chosen were done because the particular tool I intend to integrate with wants these percentiles, but others could be added too.
=> Capture and report latency statistics for server-side requests

documentation/sphinx/source/mr-status-json-schemas.rst.inc, documentation/sphinx/source/mr-status.rst, fdbclient/Schemas.cpp, fdbserver/Status.actor.cpp
The backport of a change in later versions didn't include some updates to the schema and a change to the name of one of the messages.
=> Add missing messages to schema and rename one to match later versions

fdbserver/Knobs.cpp
This increases the size of the latency sample by a factor of 10. I mainly opened this for purposes of discussion, with the target number up for consideration.
At the prior value of 10000, we would have an expected 10 samples beyond the 99.9th percentile, which will probably be fairly noisy. Increasing this number improves that, but it should be balanced against memory usage (8 bytes per sample) and the cost of sorting the samples (currently done at the logging time once per minute).
Increasing by a factor of 10 seemed reasonable to me, but I'm open to feedback.
As mentioned previously, there are other more involved changes to improve our accuracy proposed in other issues.
=> Increase size of latency sample

cmake/AddFdbTest.cmake
As part of the changes in #3218, the correctness and valgrind correctness packages would copy the test files to another directory and pack up the entire thing. Existing tests in that directory are not removed, so if a test gets deleted or if you go back in time and build an old version that's missing a newer test, you might include extra test files.
This change makes it so the package built specifically lists all the files to be included, meaning that any random extra files will still persist in the folder but be excluded from the package.
=> Fix: correctness packages included removed/future tests

fdbserver/TagPartitionedLogSystem.actor.cpp, fdbserver/WaitFailure.actor.cpp, fdbserver/WaitFailure.h, fdbserver/masterserver.actor.cpp
So when there is master recovery due to failed tlog, proxy, resolver, log
router, backup worker, or resolver, we can have a trace event tells which address that the
master thinks is dead.
=> Log peer address whose failure can cause master recovery

fdbserver/MasterProxyServer.actor.cpp, fdbserver/Ratekeeper.actor.cpp
* Master proxy reports transaction counts to ratekeeper for throttled tags only
* The ramp up behavior at the end of an auto-throttle was broken
* Fixed some issues with computing the initial transaction rate for auto-throttles
=> Various fixes to tag throttling

fdbserver/DataDistributionQueue.actor.cpp
Add comments to help understand Evan's PR 3487  that fixes the problem: replication factor could drop unexpected in fearless config.
=> Add comment to GetTeam in DataDistribution

flow/Platform.cpp
`net2backtraces_count` is defined to be an `int` in Net2.actor.cpp. Defining it to be an `int64_t` here causes us to read 4 bytes of extra memory.
=> Use consistent integer size for net2backtraces_count

fdbclient/BackupContainer.actor.cpp
If a file backup url usesng a symlink then fdbbackup fails with an unclear error message 'Disk i/o operation failed'
1. Create a FDB cluster
2. Create a symlink file to a backup location
3. Start fdbbackup using the symlink file as the backup destination
```
fdbbackup start -C fdb-primary.cluster -d file:///mnt/backup/fdb/hot/9
```
Starting backup progress or a clear error message why it can not start
```
ERROR: 'Disk i/o operation failed' on URL 'file:///mnt/backup/fdb/hot/9'
```
The BackupContainerLocalDirectory constructor compares the url file path with the it's absolute path and throws io_error if these paths are different. I don't know the reason of this checking, but the exception thrown does not contain any useful information about the failed check
Proposal
1. Put a clear …
=> Unclear error message in fdbbackup if the backup url uses a symlink

fdbserver/Ratekeeper.actor.cpp
The trace event shows the `limitReason_t` as integer. 
Adding the number of the enum item to make counting easier.
=> Add number comment to limitReason_t entries

fdbserver/DataDistribution.actor.cpp, flow/error_definitions.h, flow/flow.h, flow/genericactors.actor.h
This fixes the rare bug that has been a ghost in nightly test for a while. The most recent bug reproduction is at https://github.com/apple/foundationdb/issues/3525. 
**Bug analysis:**
teamTracker only works when all DDTeamCollections are valid.
However, teamTracker can be triggered by zeroTeamSignalling event 
after a DDTeamCollection is destructed and the other DDTeamCollection has not been
destructed yet.
This causes teamTracker to uses a pointer to the destructed DDTeamCollection and thus
has mysterious failure.
**Fix**
When DDTeamCollection is destructed, we need to reset other  DDTeamCollections' pointer that points to the destructed DDTeamCollection. 
In TeamTracker, we check all DDTeamCollections are valid; otherwise, throw actor_cancelled() error.
=> Fix wild pointer to destructed DD that causes DD crash rarely

fdbclient/ManagementAPI.actor.cpp, fdbclient/MasterProxyInterface.h, fdbclient/RestoreWorkerInterface.actor.h, fdbrpc/fdbrpc.h, fdbserver/CoordinationInterface.h, fdbserver/DataDistributorInterface.h, fdbserver/RestoreUtil.h, fdbserver/WorkerInterface.actor.h, flow/Arena.h, flow/FileIdentifier.h, flow/flat_buffers.h, flow/flow.h, flow/serialize.h
This addresses https://github.com/apple/foundationdb/issues/3405. The first byte of a file identifier is now reserved for composed identifiers, while the next 3 bytes are manually specified. This helps to avoid file identifier conflicts  There are the following restrictions:
- All manually specified file identifiers must be less than 2^24
- There are a maximum of 15 allowed composed identifiers
- Only 2 levels of composition are allowed (types with 3 or more levels of composition like `ReplyPromise<ErrorOr<Optional<T>>>` will not get file identifiers and should be wrapped in other classes if necessary).
=> Fix file identifier conflicts

fdbclient/CoordinationInterface.h, fdbclient/DatabaseConfiguration.h, fdbclient/FDBTypes.h, fdbclient/RYWIterator.cpp, fdbclient/RYWIterator.h, fdbclient/SnapshotCache.h, fdbclient/StatusClient.actor.cpp, fdbclient/VersionedMap.cpp, fdbclient/WriteMap.h, fdbrpc/Locality.h, fdbrpc/ReplicationTypes.h, fdbserver/ArtMutationBuffer.h, fdbserver/ClusterController.actor.cpp, fdbserver/CoordinationInterface.h, fdbserver/DBCoreState.h, fdbserver/DataDistribution.actor.cpp, fdbserver/DataDistribution.actor.h, fdbserver/DataDistributionQueue.actor.cpp, fdbserver/IDiskQueue.h, fdbserver/LogSystemDiskQueueAdapter.h, fdbserver/VersionedBTree.actor.cpp, flow/Arena.h, flow/Deque.h, flow/FastRef.h, flow/IKeyValueContainer.h, flow/IRandom.h, flow/IndexedSet.h, flow/TreeBenchmark.h, flow/flow.h, flow/network.h
`using namespace std::rel_ops;`
This causes the following to not compile
```
#include <utility>
#include <vector>
using namespace std::rel_ops;
int main() {
std::vector<int> xs;
return xs.rbegin() != xs.rend();
}
```
See https://godbolt.org/z/s1977n.
This would mean that we have to write some extra boilerplate comparison operators now
=> Remove using namespace std::rel_ops

documentation/sphinx/source/downloads.rst, documentation/sphinx/source/release-notes/release-notes-620.rst, fdbcli/fdbcli.actor.cpp, fdbclient/ReadYourWrites.actor.cpp
The purpose of this command is to kill a process and prevent it from rejoining the cluster for a period of time. In particular, if a process is degraded such that it is either much slower than other processes, or its network connection is unstable, having the process in the cluster can impact the performance of the whole cluster.
=> added the ability to suspend processes from fdbcli

flow/Tracing.cpp
Updates the format of request trace events to output a fully precise double instead of a truncated timestamp. Also sets Span end time before it gets written on destruction.
=> Fix request tracing time format

flow/Arena.cpp, flow/Arena.h
Test that SmallVectorRef is a drop-in replacement for VectorRef. Includes changes from #3509.
TODO make sure test coverage is adequate.
=> Add unit tests for SmallVectorRef and VectorRef

fdbclient/SpecialKeySpace.actor.cpp, fdbserver/workloads/ReportConflictingKeys.actor.cpp
The `Standalone<RangeResultRef>` can outlive the transaction, so we do need push_back_deep
=> Fix memory error in report conflicting keys special keys

fdbclient/BackupContainer.actor.cpp, fdbclient/MasterProxyInterface.h, fdbserver/Knobs.cpp, fdbserver/RestoreController.actor.cpp, fdbserver/RestoreController.actor.h
This helps to understand where bc gets stuck and how large range and log files are.
=> FastRestore:Add trace for file size and bc progress

fdbclient/Knobs.cpp, fdbserver/Knobs.cpp, flow/Knobs.cpp
Some of these knobs were originally off to support a limited amount of downgradability, however other features already prevent that so we are enabling them now.
=> Changed a few default knob values to improve recovery speeds

fdbserver/MasterProxyServer.actor.cpp
We don't need to cast away constness here. It's already not const
=> Remove redundant cast

fdbclient/FDBTypes.h
In 7.0, you'll be forced to upgrade from V3 -> V4, and we'll start new clusters on V5 by default.
=> Walk TLogVersion forward for 7.0 now that 6.3 has been branched.

fdbserver/workloads/Cycle.actor.cpp, fdbserver/workloads/Increment.actor.cpp
In workloads, cycleCheck and incrementCheck, both might trigger a test
failure with reason "Rate below desired rate", and the other text are
the same. Adding a File field will help differentiate these two events.
=> Add File field in TestFailure event for cycleCheck and incrementCheck

fdbclient/ManagementAPI.actor.cpp, fdbrpc/sim2.actor.cpp, fdbrpc/simulator.h, fdbserver/ClusterController.actor.cpp, fdbserver/workloads/RemoveServersSafely.actor.cpp
Master branch currently has 4 failures  out of 177,766  tests. This is a much higher failure rate that we want. It is also the type of tests that cause most of failures in nightly test.
**Failure analysis:** 
Simulation randomly picks two sets of processes to kill.
If we simply kill all processes in toKill1 or toKill2, we may kill too many processes to make the cluster unavailable. We won't be able to include those killed processes when the cluster is unavailable. So we get stuck in `includeServers()` (https://github.com/xumengpanda/foundationdb/blob/a2089b354afab43dab62d0ee9e30e3492258c669/fdbserver/workloads/RemoveServersSafely.actor.cpp#L350)
**Solution:**
Similar as how toKill2 were modified when  it can cause cluster unavailable …
=> Fix master branch failure on DDBalanceAndRemove.toml test

fdbserver/Knobs.cpp, fdbserver/Knobs.h, fdbserver/RestoreApplier.actor.cpp, fdbserver/RestoreApplier.actor.h, fdbserver/RestoreController.actor.cpp, fdbserver/RestoreController.actor.h, fdbserver/RestoreLoader.actor.cpp, fdbserver/RestoreLoader.actor.h, fdbserver/RestoreRoleCommon.actor.cpp
1) Add knob `FASTRESTORE_NOT_WRITE_DB` to short-cut DB for performance evaluation;
2) Add more info in periodic tracing.
3) Fix a segmentation fault.
=> Fast Restore: Misc improvements

documentation/sphinx/source/developer-guide.rst, fdbclient/ManagementAPI.actor.cpp, fdbclient/SpecialKeySpace.actor.cpp, fdbclient/SpecialKeySpace.actor.h, fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp
For `exclude` command, the related special key is `\xff\xff/management/excluded/`
And the corresponding option special key for `force` is `\xff\xff/management/options/excluded/force`.
Fix the bug using `unordered_set` and add a test to catch it.
Fix another memory bug.
=> Fix special keys doc

flow/Deque.cpp, flow/Deque.h
If `Deque::grow` throws an exception while relocating its contents, it would leave the `Deque` in an unrecoverable state.
=> Add exception-safety to Deque::grow

fdbcli/fdbcli.actor.cpp
This is an attempt at exposing the enabling and disabling of cache ranges to the client API to allow for testing on non-simulated FDB clusters
=> Add cache_range command to fdbcli

documentation/sphinx/source/release-notes/release-notes-630.rst, fdbclient/DatabaseConfiguration.cpp, fdbclient/DatabaseConfiguration.h
With this patch, if there is a configuration special key in the
database, even if the value is reverted to default/hidden, it will still
be forwarded when constructing a JSON string. This should address the
requirements described in https://github.com/apple/foundationdb/issues/3551.
=> When a configuration K/V pair is modified, always output the K/V pair values

bindings/java/src/main/com/apple/foundationdb/tuple/FastByteComparisons.java
Fixed warnings for documentation greater than and less than charactees which appear as errors within Java 1.8
Removed broken link
=> JavaDoc Fixes

fdbclient/NativeAPI.actor.cpp
Visibility bug fix: spans uses their destructor to write to the log and should therefore stick around until the function they are tracking completes. This fix moves span creation to `extractReadVersion` since variables cannot be passed by reference to actors, allowing the span to stick around until `extractReadVersion` completes.
=> Fix span early destruction

documentation/sphinx/source/configuration.rst
I noticed this while reviewing region documentation.
=> Fix a small typo in the region configuration docs

fdbserver/RestoreController.actor.cpp
batchIndex starts at 1 instead of 0. So batchIndex can be the batch.size()
=> Fast Restore: Fix an incorrect ASSERT

versions.target
This file was accidentally pushed back into the master branch (it is still needed in 6.2)
=> Remove file that is generated from cmake

fdbclient/AsyncFileBlobStore.actor.h
Compilers could choose to evaluate `joinErrorGroup` between the `FlowLock::Releaser` allocation and the `std::shared_ptr` construction, so exceptions from `joinErrorGroup` could cause memory leaks. Using `std::make_shared` fixes this potential issue.
=> Fix potential memory leak in AsyncFileBlobStore

fdbclient/NativeAPI.actor.cpp
These two actors take a reference type, without necessary mechanism to ensure the lifetime of the referenced memory is long enough. And thus these two actors(actually maybe all actors) should not take reference types but copies of data(or at least reference counted types) that it would work on.
Specifically, the only call site of function `getStorageMetricsLargeKeyRange()` is inside `Transaction::getStorageMetrics(KeyRange&, int)`, where a `KeyRangeRef` is created based on the `KeyRange&` passed in. Now if for some reason(for example in the case that got fixed in d198c310f4b47cfb84eb752eb56bf5388e098677) the lifetime of the underlying `KeyRange` ends after the first `wait()` is hit inside `getStorageMetricsLargeKeyRange()`, the `KeyRangeRef` now points to invalid memory and thus the …
=> Fix potential invalid memory access bug.

fdbclient/AsyncFileBlobStore.actor.h
This builds on https://github.com/apple/foundationdb/pull/3640, which fixed a potential memory leak, but not a potentially unreleased lock.
=> Construct FlowLock::Releaser before AsyncFileBlobStore upload

fdbclient/DatabaseContext.h, fdbclient/NativeAPI.actor.cpp, flow/Arena.h, flow/FastAlloc.h, flow/IThreadPool.cpp
This has the benefits of:
- Easier to understand compiler error messages
- Moves some errors from link-time to compile-time
- NonCopyable classes can still specify default move constructors
=> Use =delete to disable special member functions

contrib/TraceLogHelper/JsonParser.cs
We once added a special case handling in case JSON trace logs contain XML-unfriendly characters.
However, FDB supports both XML and JSON and we know that it won't contain such characters.
Therefore removing the (somewhat hacky) special handling here.
=> Remove unnecessary special case handling from JsonParser

fdbserver/MasterProxyServer.actor.cpp
The `Optional` was being destroyed prior to use on the next line.
=> Fix memory error caused by referencing a value with limited lifetime

fdbrpc/ReplicationPolicy.cpp
Commented out verbose `printf` statements in `ReplicationPolicy.cpp`
Closes #1647
=> Verbose printf cleanup

documentation/sphinx/source/command-line-interface.rst, documentation/sphinx/source/mr-status-json-schemas.rst.inc, documentation/sphinx/source/mr-status.rst, fdbcli/fdbcli.actor.cpp, fdbclient/TagThrottle.actor.cpp, fdbclient/TagThrottle.h, fdbserver/Ratekeeper.actor.cpp, fdbserver/Status.actor.cpp, flow/ProtocolVersion.h
* add command line support: `throttle list [throttled|recommended|all]`
* add status json support for recommended tags
```JSON
"throttled_tags" : {
"auto" : {
"busy_read" : 0,
"busy_write" : 0,
"count" : 0
},
"manual" : {
"count" : 1
},
"recommend" : {
"busy_read" : 0,
"busy_write" : 0,
"count" : 0
}
},
```
* Let `enableAutoThrottle` take effects. Stop all auto-throttled tags once `enableAutoThrottled` is set to false.
=> Report recommended tx tag to be throttled to status json

fdbserver/MasterProxyServer.actor.cpp
The `MasterProxyServer.actor.cpp` refactor (#3575) moved some tracing code to a function, but this function was never called.
=> Add call to set up tracing on transaction commit path

fdbclient/BackupContainer.actor.cpp, fdbrpc/simulator.h
Problem:
The current BackupContainer:readFile() uses a randomly generated filename as the soft link to the actual file. 
This means every time when simulation calls readFile(), it will create a soft link under `simfdb`.
The number of files, including soft link, will be counted as the `fileCount` -- the total number of opened files -- in simulation. 
Simulation fails with TOO_MANY_FILES error if the `fileCount` is larger than 3000. 
In one backup and restore test, I have seen more than 2K soft links created. 
The TOO_MANY_FILES error prevent how long the backup can run and how much data the backup can generate. This further limits the scenarios of how backup files may look like and impede the ability of testing backup & restore in simulation. 
Solution:
Assign a UID to each simulated …
=> Mitigate TOO_MANY_FILES error

fdbrpc/FlowTransport.actor.cpp
This means we could immediately attempt to reestablish a connection if an incoming connection failed in the first few seconds. It also means we could mark a later connection from the same peer as redundant if we have not closed our side of the connection yet when the attempt comes in.
=> LastConnectTime was not being set for incoming connections

fdbserver/ApplyMetadataMutation.cpp
This was previously a pointer, and the logging indicated whether the caller expected a result. It is now a reference type, and we can't determine what the caller expects.
=> Remove a line that logs whether confChange was non-null

fdbserver/workloads/Mako.actor.cpp
To enable logging, add `latencyForLocalOperation=true` in `Mako.txt.`
Change latency time from `ms` to `us`
=> Log latency for set, clear, clearrange in MakoWorkload

fdbserver/RestoreController.actor.cpp
batchIndex in restore asset was forgotten to initialized. It won't cause correctness failure but will cause confusion in the trace events.
=> FastRestore: Fix valgrind error

fdbserver/Status.actor.cpp
Fix workloadStatusFetcher for GrvProxyStats. Fix confirmed by running fdb locally.
Thanks to Xiaoxi for identifying the issue!
=> Fix status fetcher for GrvProxyStats

fdbclient/Schemas.cpp, fdbserver/Ratekeeper.actor.cpp, fdbserver/Status.actor.cpp, fdbserver/workloads/TagThrottleApi.actor.cpp
* update `status json` to report busiest write tag of each storage server
* update TagThrottleApiWorkload
=> report busiest write tag of each storage server

cmake/CompileRocksDB.cmake, cmake/FDBComponents.cmake, fdbserver/SimulatedCluster.actor.cpp
RocksDB currently does not build with Clang 10 (the version in the dev Docker container), so this is only turning on for GCC.
This PR also steals a fix to the RocksDB auto-download path from @sears .
=> Enable the RocksDB engine by default with GCC

fdbclient/BackupAgent.actor.h, fdbclient/BackupContainer.actor.cpp, fdbclient/FileBackupAgent.actor.cpp, fdbserver/RestoreApplier.actor.cpp, fdbserver/RestoreApplier.actor.h, fdbserver/RestoreCommon.actor.cpp, fdbserver/RestoreCommon.actor.h, fdbserver/RestoreLoader.actor.cpp
Fix bugs when doing tests on real clusters:
1. When blob has http error, restore should retry, but it didn't. Simulation didn't simulate this type of error.
2. CompareAndClear atomicOp is not included in the atomicOps test workload. Simulation fails to test this scenario.
=> Restore: Simulate blob error when restore read files

fdbserver/workloads/FuzzApiCorrectness.actor.cpp
Using this option enables `READ_SYSTEM_KEYS`, which interferes with the expected contract of other operations.
Resolves #3760
=> Don't set SPECIAL_KEY_SPACE_ENABLE_WRITES randomly in Fuzz API test

fdbserver/workloads/AtomicOps.actor.cpp
This resolves part of https://github.com/apple/foundationdb/issues/3762.
CompareAndClear should be tested separately.
Merge to 6.3 branch because it is only simulation change.
=> Add MinV2 and AddV2 test into AtomicOp workload

documentation/sphinx/source/release-notes/release-notes-630.rst, fdbcli/fdbcli.actor.cpp, fdbclient/ManagementAPI.actor.cpp, fdbclient/Schemas.cpp, fdbserver/Status.actor.cpp
This can help users to identify the failed tlogs information when storage servers are not recovered but we may have some corrupted old generations of tlogs because this means storage servers may never be able to catch up these logs.
#3580
=> Report missing old tlogs in recovery before storage servers are fully recovered

documentation/sphinx/source/api-c.rst, documentation/sphinx/source/api-error-codes.rst, flow/ThreadHelper.actor.h, flow/Trace.cpp, flow/error_definitions.h
As described in https://apple.github.io/foundationdb/api-c.html?highlight=fdb_future_block_until_ready#c.fdb_future_block_until_ready, it's an error to call fdb_future_block_until_ready from the main thread (the one running fdb_run_network). This PR changes the current behavior of deadlocking (difficult to debug and to know what to do to recover from it) to throwing an error and tracing a diagnostic.
I'm also wondering if it would be even better to have a new error code for this, in case the client doesn't have tracing enabled.
=> Disallow calling blockUntilReady from main thread

fdbclient/Schemas.cpp
When I'm trying to set up region configuration with `fileconfigure` command in fdbcli, I receive an error
```
fdb> fileconfigure regions_2dcs.json
Assertion false failed @ /home/oleg/work/fdb/foundationdb/fdbcli/fdbcli.actor.cpp 1988:
addr2line -e fdbcli.debug -p -C -f -i 0x996353 0x413e93 0x508ba5 0x50d27b 0x510ed8 0x5174a1 0x5cff78 0x9bc998 0x68ada2 0x4d837f 0x7fea1cdb41a3
ERROR: An internal error occurred (4100)
```
The reason is an incorrect json schema in fdbclient/Schemas.cpp
=>  fileconfigure fails with Assertion false failed

fdbserver/RestoreApplier.actor.cpp, fdbserver/RestoreController.actor.cpp
Backport fix for 6.3 branch of PR: https://github.com/apple/foundationdb/pull/3827
=> FastRestore:Fix segmentation fault

fdbcli/fdbcli.actor.cpp, fdbclient/ManagementAPI.actor.cpp, fdbrpc/Locality.h
Our prod operations and automation team is heavily using the 'proxy' class types. To reduce failures, we should support backward compatibility for specifying 'proxy' as process class, convert it to commit proxy and give warning of deprecated usage.
=> Support specifying proxy as process class and converting it to commit proxy

fdbclient/Knobs.cpp
This addresses https://github.com/apple/foundationdb/issues/3825.
=> Lower WATCH_TIMEOUT default value to 30.0

fdbclient/ClusterInterface.h, fdbclient/MultiVersionTransaction.actor.cpp, fdbclient/NativeAPI.actor.cpp, flow/Arena.h
This fixes undefined behavior in the creation of `ClientVersionRef`.
=> Backport #3426 to release-6.2

documentation/sphinx/source/release-notes/release-notes-630.rst, flow/Net2.actor.cpp
It is currently possible to open a connection but then fail to handshake for a long time. This PR adds a timeout as a safety precaution so that a connection cannot get stuck on a handshake.
=> added a timeout to TLS handshakes

CMakeLists.txt, packaging/msi/FDBInstaller.wxs
Step 11 of the release script. 
For 6.3 release (CMake), I have to trick the script by copying the old _versions.target_ from 6.1 (or 6.2) to foundationdb repo, although the file will not be committed.
=> Post release cleanup 6.3.9

tests/CMakeLists.txt
Avoid running joshua correctness on these test files until https://github.com/apple/foundationdb/issues/3873 is resolved
=> Disable SnapIncrementalRestore tests temporarily

fdbserver/DataDistribution.actor.cpp, fdbserver/DataDistributionQueue.actor.cpp
Fix a couple places where we were creating vectors with default elements rather than reserving space.
=> Fix reporting issue with team descriptions in trace logs

fdbserver/ApplyMetadataMutation.cpp, fdbserver/ApplyMetadataMutation.h, flowbench/BenchMetadataCheck.cpp, flowbench/CMakeLists.txt
This applies a fix from the closed PR https://github.com/apple/foundationdb/pull/3663 that prevents `clear(normalKeys)` from being classified as a metadata mutation.
=> Fix isMetadataMutation condition

fdbserver/storageserver.actor.cpp
- Moved `debug_advanceMaxCommittedVersion` to right before the commit future is waited. 
- Throw the storage engine commit failure that was previously silently swallowed.
This resolves #3885
=> Fix a silent commit failure in SS commit pipeline

bindings/c/CMakeLists.txt, bindings/c/test/unit/fdb_api.cpp, bindings/c/test/unit/fdb_api.hpp, bindings/c/test/unit/setup_tests.cpp, bindings/c/test/unit/third_party/CMakeLists.txt, bindings/c/test/unit/unit_tests.cpp, cmake/ConfigureCompiler.cmake
Adds unit tests covering C API functionality. Behavior is tested based off functionality described in the [documentation](https://apple.github.io/foundationdb/api-c.html).
Unit tests use [doctest](https://github.com/onqtam/doctest) as the testing framework. The doctest header is downloaded during the build process. Produces two new binaries, `fdb_c_setup_tests` and `fdb_c_unit_tests`.
Uses #3808 to add binaries to ctest, which will run with them with a temporary `fdbserver`. Run with ctest by specifying the name of the binary as regex, ie `ctest -R unit_tests -VV`.
Thanks to @sfc-gh-anoyes for helping with this work.
=> Add C API unit tests

fdbserver/VersionedBTree.actor.cpp
In page remap cleanup, if a page update's next update was at exactly the oldest retained version then the earlier update would still choose to copy the updated page over top of the original (but it shouldn't) which would race with the later update's copy if the same remap cleanup cycle pops both updates from the queue, which can only happen if the remap cleanup window is 0 (not a default, but buggify covers this case).
I'm still working on increasing the frequency of this type of situation.
=> Very rare Redwood bug fix

documentation/sphinx/source/administration.rst, documentation/sphinx/source/configuration.rst, packaging/rpm/foundationdb.service
This change makes foundationdb.service fully restartable after killing of fdbmonitor.
Previously all fdb children processes remained running that prevented a new instance of fdbmonitor from starting new fdbserver processes #3838
=> Unable to restart foundationdb after fdbmonitor has died #3838

fdbserver/VersionedBTree.actor.cpp
Added a simulation-only check for pager remap cleanup writing the same page twice in a cleanup cycle, which should never happen, but a bug leading to this was fixed recently.  Adjusted some buggify logic to widen edge case coverage around remap cleanup parameters.
=> Improved Redwood simulation testing to cover recent bug fix involving zero width remap cleanup window.

fdbserver/workloads/VersionStamp.actor.cpp
This call could return retryable errors, in which case we should retry them rather than fail the test.
=> Add error checking for a getReadVersion call in Versionstamp workloads

fdbclient/ManagementAPI.actor.cpp, fdbclient/ManagementAPI.actor.h
This fixes a virtual function overload in NameQuorumChange
=> Make getDesiredClusterKeyName const

fdbclient/ReadYourWrites.actor.cpp, fdbclient/SpecialKeySpace.actor.cpp, fdbserver/workloads/FuzzApiCorrectness.actor.cpp, fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp
Previously, we throw `special_keys_cross_module_read` when `SPECIAL_KEY_SPACE_RELAXED` is not enabled if start key is in the special key range but the end key is not.
We did not add the same behavior when `SPECIAL_KEY_SPACE_RELAXED` is enabled, 
thus we saw the inverted range error in #3905 .
This pr does three things: 
- `getRange` only enters the special keyspace code path when both begin key and end key are in (\xff\xff, \xff\xff\xff).
- update the contract in the FuzzApiCorrectness test
- add a test to test this behavior in the SpecialKeySpaceCorrectness test
- Increase the probability(to 15%) of the randomly generated keys in `FuzzApiCorrectness` to go after `\xff\xff`
=> Fix issue -3905

documentation/sphinx/source/mr-status-json-schemas.rst.inc, fdbclient/Schemas.cpp, fdbserver/Status.actor.cpp, fdbserver/masterserver.actor.cpp
This expose a new field under `recovery_state` named `time_since_last_fully_recovered_seconds` which has a value of either
- -1 if the current generation has not fully recovered yet;
- Or the time, in seconds, since current generation fully recovered.
=> This resolves issue #3739 by exposing time since last full recovery.

fdbrpc/Stats.actor.cpp
The roughness changes made in #2741 claimed that the end of a measurement window after the last event was not considered for roughness. However, that does not seem to have actually been the case. Instead, the entire window plus the time extending to the last event of the previous window were counted.
This had the effect of skewing the mean time between increments because it counted the last span as 0 increments rather than a partial increment. For example, if we have a window running from 10 to 15s, the last previous increment at 8s, and one new increment at 12s, then the old method would compute a mean increment time as (15-8)/1 = 7s. The new approach will ignore all the time after the last increment, and would yield (12-8)/1 = 4s. 
The latter more accurately reflects the time between …
=> Fix roughness elapsed time

build/docker-compose.yaml
Now that we're adding a few small tests to cover some code that's not covered in simulation (e.g. fdbcli, fdb-java.jar, etc.) we should also run it in CI, not just tests that have `fast` in their name
=> Run all ctest tests

fdbclient/BackupAgent.actor.h, fdbclient/DatabaseBackupAgent.actor.cpp, fdbserver/workloads/BackupToDBCorrectness.actor.cpp, fdbserver/workloads/BackupToDBUpgrade.actor.cpp
After submit a backup, immediately abort the backup may cause a rare race
condition, which results in `BackupCorrectnessLeftoverVersionKey` error.
Specifically, in the `StartFullBackupTaskFunc`:
1st Txn sets the `destUid` at the source database and the 2nd Txn writes it to the dest DB.
An abort can come after the 1st Txn succeeds, and clears the config rage so
that the 2nd Txn above would fail. Because 2nd Txn didn't write `destUid`, the
3rd Txn of abort can't read the correct source DB for `latestVersionKey`, which
contains the `destUid` value.
The fix is to let the 1st Txn of abort to wait until `destUid` becomes valid, and this is wait is currently only added to the test workload, i.e., `BackupToDBCorrectness.actor.cpp`. The `fdbdr` command behaves as before.
=> Fix a race between submit and abort backup

fdbserver/Status.actor.cpp
This value is used to add a data lag message to status.
=> Restore line that stores the data lag seconds of a storage server

fdbserver/LogSystem.h
To enable downgrades from 7.0.0 to 6.3.5, features associated with `TLogVersion::V6` need to be disabled by default in 7.0.0. This PR fixes an issue where `SpanContextMessage`s, a feature associated with `TLogVersion::V6` (#3748), were being sent from the proxy to the transaction logs even for `TLogVersion::V5`.
Fixes #3909.
=> Only serialize span if TLogVersion >= 6

fdbclient/NativeAPI.actor.cpp
Don't use key references from an iterator in insertion when those iterators will be invalidated by the insertion. Resolves #3936.
=> Fix memory error due to iterator invalidation

documentation/sphinx/source/developer-guide.rst, fdbclient/NativeAPI.actor.cpp, fdbclient/SpecialKeySpace.actor.cpp, fdbclient/SpecialKeySpace.actor.h, fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp
-  Add `consistencycheck` command to special key `\xff\xff/management/consistency_check_suspended`
- get("\xff\xff/management/consistency_check_suspended"), if not empty, then consistencycheck is suspended
- set("\xff\xff/management/consistency_check_suspended") <--> `consistencycheck off`
- clear("\xff\xff/management/consistency_check_suspended") <--> `consistencycheck on`
- Change `\xff\xff/management/dbLocked` to `\xff\xff/management/db_locked`, using snake_case naming style
- `consistencycheck` is now only used in the ConsistencyCheck Workload, so the correctness test here is trivial
- read from the special key is consistent with read directly from the system key
- `set` and `clear` works after `commit`
=> Add consistencycheck command to special keys

flow/flat_buffers.h
Apparently clang11 warns if you pass uninitialized memory to a function
accepting a const reference. Seems fair. This change doesn't actually
fix any bugs, but it silences the warning.
=> Fix clang11 warning (cherrypick #3901)

build/Dockerfile, build/Dockerfile.devel, build/docker-compose.yaml
The enables using -DUSE_ASAN=1 (cmake option) to build an asan-enabled libfdb_c.so in the foundationdb-build docker image, which should be useful for detecting things like memory errors or memory leaks in the multiversion client. fdbserver simulation still isn't ready for asan. CC #3854 (not closing it for now to track publishing the new image)
Let me know if I missed anything required for updating the Dockerfile (I think I remembered everything)
=> Install asan in foundationdb-build docker image

contrib/TestHarness/Program.cs.cmake
This allows joshua to run on binaries older than the most recent version,
because restarting/upgrade tests won't start with a newer version than what is
under test.
This is an alternative implementation to #3963
=> TestHarness should check --version before choosing an old binary.

fdbserver/workloads/WriteDuringRead.actor.cpp
This fixes an "Out of Memory" error in the WriteDuringReadClean test (https://github.com/apple/foundationdb/issues/3988)
=> Decrease maximumTotalData in WriteDuringRead workload

contrib/TestHarness/Program.cs.cmake
This first brings the changes from #3970 from release-6.3 to master, as the actual change I want to make conflicts with that PR, but I have no reason to land this one on a release branch.
The motivation for this PR is so that Snowflake can add use TestHarness to run FDB3 in Joshua, and be able to load FDB3 binaries into the image for restarting tests.  I could run two different joshua instances/images, but this seems much simpler for everyone.
=> Ignore old binaries before 4.x when running restarting tests

fdbserver/DataDistribution.actor.cpp, fdbserver/DataDistribution.actor.h, fdbserver/DataDistributionQueue.actor.cpp, fdbserver/Knobs.cpp, fdbserver/Knobs.h
Added detailed logging, with level `SevWarnAlways`, when there is no servers left in a server team, because if all servers in a server team are permanently lost, all shards on them will not be able to be replicated to other servers and thus that means data in those shards are now lost.
=> Added detailed logging for PRIORITY_TEAM_0_LEFT

fdbrpc/sim2.actor.cpp, fdbrpc/simulator.h, fdbserver/workloads/KVStoreTest.actor.cpp, flow/CMakeLists.txt, flow/Histogram.cpp, flow/Histogram.h, flow/SystemMonitor.cpp, flow/Trace.cpp, flow/flow.vcxproj
I tested this on a feature branch (against code that's been rewritten there).  Here's an example of how to use it:
```
diff --git a/fdbrpc/FlowTransport.actor.cpp b/fdbrpc/FlowTransport.actor.cpp
index 0e9f1e54b..400a2cdd3 100644
--- a/fdbrpc/FlowTransport.actor.cpp
+++ b/fdbrpc/FlowTransport.actor.cpp
@@ -34,6 +34,7 @@
#include "flow/ActorCollection.h"
#include "flow/Error.h"
#include "flow/flow.h"
+#include "flow/Histogram.h"
#include "flow/Net2Packet.h"
#include "flow/TDMetric.actor.h"
#include "flow/ObjectSerializer.h"
@@ -236,6 +237,10 @@ public:
Int64MetricHandle countConnClosedWithError;
Int64MetricHandle countConnClosedWithoutError;
+	Histogram readSizeDistribution = {"N2", "ReadSize", Histogram::Unit::bytes};
+	Histogram writeSizeDistribution = {"N2", "WriteSize", …
```
=> Lightweight, power of two spaced histogram implementation + automatic reporting

bindings/c/fdb_c.cpp
I'm working on detecting potential memory leaks in the c client, and this seems like the best way to get around the fact that fdb_stop_network intentionally leaks a bunch of memory.
=> Do leak check before stopping network

cmake/FDBComponents.cmake
Prior to this change, it was impossible to disable building RocksDB with GCC. This change has the negative side effect of making it impossible to build RocksDB on not GCC, but that is a minor issue as the version of RocksDB we use doesn't build with the version of Clang we use (we need a release with https://github.com/facebook/rocksdb/pull/7025 in it).
=> Fix the ability to disable building RocksDB with GCC

fdbserver/LogSystemPeekCursor.actor.cpp, fdbserver/MasterProxyServer.actor.cpp
All TraceLogs that are related to ConnectionReset should be prefixed with
ConnectionReset. This should make it easy to query and aggregate by address and
role.
These logs should be enough to make Splunk queries and make timecharts quite easily.
Another alternative is logging them periodically, but I'm not sure if that adds any value
currently.
=> Make ConnectionReset logs query friendly #3977

fdbrpc/Stats.actor.cpp, fdbrpc/Stats.h, fdbserver/LogRouter.actor.cpp, fdbserver/TLogServer.actor.cpp, fdbserver/storageserver.actor.cpp
- Attach the paired TLog ID to `LogRouterMetrics` and router tag for better discoverability.
- Attach the storage server's tag to `StorageMetrics` too.
- Attach the generation(recovery count) to TLog and LogRouter metrics.
=> Add a way to decorate the trace event created by `traceCounters` with more details.

cmake/FDBComponents.cmake
This backports https://github.com/apple/foundationdb/pull/4017 to release-6.3
=> Backport ability to disable building RocksDB with GCC (release 6.3)

cmake/FDBComponents.cmake
https://github.com/apple/foundationdb/pull/4017 accidentally disabled RocksDB by default.
=> Restore building RocksDB by default with GCC

fdbclient/StatusClient.actor.cpp, fdbrpc/FlowTests.actor.cpp, fdbrpc/sim2.actor.cpp, fdbserver/Status.actor.cpp, fdbserver/storageserver.actor.cpp, fdbserver/workloads/StatusWorkload.actor.cpp, flow/Net2.actor.cpp, flow/SystemMonitor.cpp, flow/network.h
This change seems to be incorrect since afaict INetwork::timer isn't
guaranteed to be monotonic. Maybe we can make that guarantee or add an
INetwork::timer_monotonic symbol?
Closes #3982
Closes #3944
=> Make status tests deterministic

fdbserver/ApplyMetadataMutation.cpp, fdbserver/LogSystem.h
**Failed test:** *slow/ParallelRestoreOldBackupCorrectnessCycle.toml*
**Seed:** *891553841*
**Buggify:** *off*
**Commit:** *053cbc23690db7af63ee874c7d7ae1ce7cf999ff*
**Compiler:** *gcc/g++*
```
./bin/fdbserver -r simulation -f ../foundationdb/tests/slow/ParallelRestoreOldBackupCorrectnessCycle.toml --buggify off --seed 891553841
```
This addresses a failure found in the nightly, related to https://github.com/apple/foundationdb/pull/3748. The error caused was an [assertion failure](https://github.com/apple/foundationdb/blob/053cbc23690db7af63ee874c7d7ae1ce7cf999ff/flow/serialize.h#L109) in `serialize.h` where the protocol version was 0 when attempting to deserialize a `MutationRef`.
After investigation, there are a few things that went wrong. First, a bug in …
=> Fix deserialization issue with out of order SpanContextMessage

tests/DDMetricsExclude.txt, tests/fast/ConstrainedRandomSelector.toml, tests/fast/RandomSelector.toml, tests/fast/SelectorCorrectness.toml, tests/randomSelector.txt, tests/selectorCorrectness.txt, tests/slow/DDBalanceAndRemove.toml, tests/slow/DDBalanceAndRemoveStatus.toml, tests/slow/SwizzledDdBalance.toml, tests/slow/ddbalance.toml
These test titles are used in trace lines, so having an underscore followed by a lower-case character leads to invalid trace lines.
=> Make sure only uppercase characters follow underscore in test titles

tests/restarting/from_7.0.0/SnapIncrementalRestore-1.toml
Updating this workload to be in line with the other backup workloads. Some of the other workloads explicitly remove the backup agents from the simulator to allow the database to quiesce, this change instead postpones the quiescent check until the backup agent is stopped normally
=> Don't run consistency check until after the backup is discontinued

cmake/ConfigureCompiler.cmake
This warning is necessary for the compiler to emit warnings when ignoring the return value of a non-cancellable actor. I think it keeps getting added back when we merge release-6.2 upstream so let's remove it in release-6.2
=> Remove -Wno-unused-value for clang

documentation/sphinx/source/class-scheduling-go.rst, documentation/sphinx/source/class-scheduling-java.rst, documentation/sphinx/source/class-scheduling-ruby.rst
Cherrypick @schedutron's fix https://github.com/apple/foundationdb/commit/d1c823b3d710d509e303fb5c66de18e350fea07e to release-6.2
=> Fix transaction retry typo for other lang tutorials (in 6.2)

pull_request_template.md
This PR fix typo in the PR template.
- Only document change.
=> Fix typo CP to CPU

fdbclient/ManagementAPI.actor.cpp, fdbserver/workloads/RemoveServersSafely.actor.cpp
This PR resolves a small issue found from https://github.com/apple/foundationdb/issues/4039, but does not resolve it completely. The other issues are being investigated in separate PRs.
- Make the `toKill` and `toKillMarkFailed` overlap more consistently in terms of machines affected, to avoid going over the limit of how many machines we want to exclude
Please verify that all things listed below were considered and check them. If an item doesn't apply to this type of PR (for example a documentation change doesn't …
=> Sort the failed sets before modifying them in attempts to make changes consistent

fdbserver/storageserver.actor.cpp, flow/Histogram.cpp, flow/Histogram.h
- Add bytes_per_second Unit for histogram
- Includes unit when logging histogram information
- Fixs StorageServer histograms so it uses the correct unit.
[] All variable and function names make sense.
[*] The code is properly formatted (consider running `git clang-format`).
[] The code was sufficiently tested in simulation.
[] If there are new parameters or knobs, different values are tested in simulation.
[] `ASSERT`, `ASSERT_WE_THINK`, and `TEST` macros are added in appropriate places.
[] Unit tests were added for new algorithms and data structure that make sense to unit-test
[] If this is a bugfix: there is a test that can easily reproduce the bug.
=> Add bytes_per_second unit in histograms

fdbserver/fdbserver.actor.cpp, flow/Tracing.cpp, flow/Tracing.h
Tracing should be tested in simulation. This PR opens a random tracer when a simulation test is run.
**Context:** #3329.
@sfc-gh-mpilman should `TraceEvent`s be disabled in simulation? Could this effect speed of simulation tests?
=> Open random tracer in simulation

fdbserver/workloads/LowLatency.actor.cpp
This fixes https://github.com/apple/foundationdb/issues/3993.
=> Lower DELAY_CC_WORST_FIT_CANDIDACY_SECONDS for LowLatencyWorkload

fdbserver/DataDistribution.actor.cpp, fdbserver/DataDistribution.actor.h, fdbserver/DataDistributionTracker.actor.cpp, flow/error_definitions.h
- Fixes memory errors that can occur when the data distribution tracker is cancelled
=> Fix data distribution tracker memory bugs

fdbclient/SpecialKeySpace.actor.cpp
`dd_not_found` is introduced in `7.0`, in `6.3` we used `operation_failed` instead
- Catch `dd_not_found` error instead of `operation_failed` in special key implementation
=> Change operation_failed to dd_not_found

flow/error_definitions.h
This is safe because it's not been in a release, and it doesn't get
serialized.
=> Change dd_tracker_cancelled to 1215 to avoid conflict

fdbbackup/backup.actor.cpp
- The `--incremental` command will be recognized on the command line for FDB backup and restore
-
-
=> Enable --incremental usage for fdbbackup on command line

build/Dockerfile, build/Dockerfile.devel, build/docker-compose.yaml
Updated docker to use Vault repositories since Centos 6 is no longer listed in active repositories. This update is required for not only this dockerfile but for the many that are based upon it.
This PR is in response to Issue #4124
=> Updated docker repositories to Vault repos

fdbclient/NativeAPI.actor.cpp
This removes a stray line that counted range reads for (some of the) physical range reads, when we intended to and already do count them for logical range reads.
=> Fix double counting of range reads in TransactionMetrics

fdbclient/SpecialKeySpace.actor.cpp, fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp
This PR is fixing the bug when normalizing key selectors if `module` is the same as the registered range.
In particular, `get \xff\xff/worker_interfaces/<network_address>` will fail due to this bug,
though `getrange \xff\xff/worker_interfaces/ \xff\xff/worker_interfaces0` is good.
=> Fix bug when module same as registered range

fdbrpc/sim2.actor.cpp
The nightly surfaced a failure in the UDP simulation test.
Commit: `15b2f77de6477592e22779fece7af2744e20fec2`
Test: `fast/UDP.toml`
Buggify: `on`
Seed: `833187778`
Root cause:
- Sockets are [created with a randomly selected port](https://github.com/apple/foundationdb/blob/master/fdbrpc/sim2.actor.cpp#L1911) in the range [40000, 60000]. If two sockets are created and happen to randomly generate the same port *before the first socket is closed*, this issue occurs.
- If the randomly generated port for a socket is currently in use, generate a new random port for the socket. Continue until the socket has an unassigned port.
- Add an `ASSERT` to crash early if a new socket is created with the same port as an existing socket.
Passed 10k runs of just `fast/UDP.toml` on Joshua.
=> Fix UDP simulation bug

cmake/ConfigureCompiler.cmake, flow/CMakeLists.txt, flow/FastAlloc.h, flow/Platform.h, flow/config.h.cmake
This is just a refactoring change: instead of having all compiler definitions in cmake, I moved them into a header file. This should make the code much more readable
=> Move compiler definitions into config file

bindings/c/test/mako/mako.c, bindings/c/test/mako/mako.h
- Add a new argument `--streaming` to `mako` to change the streaming mode.  The supported modes are `all` (default), `iterator`, `small`, `medium`, `large`, and `serial`.  (Note that `extract` is *not* supported in this PR)
Please verify that all things listed below were considered and check them. If an item doesn't apply to this type of PR (for example a documentation change doesn't need to be performance tested), you should make a ~~strikethrough~~ (markdown syntax: `~~strikethrough~~`). …
=> Add streaming mode support to mako

build/Dockerfile, build/Dockerfile.devel, build/docker-compose.yaml
This PR rolls up a few different updates to build/Dockerfile
- add ctest2junit.xsl which allows us to generate pretty unit test failure reports in some CI environments
- include and compile boringssl, but don't use it (yet).
- add SHA verification to Ninja's zip file
- move environment-independent CCACHE environment variables from build/Dockerfile.devel to build/Dockerfile.  These are needed in any environment that uses ccache, and there's no reason for other build environments to override them.  They don't have any effect if ccache is not enabled.
- bump version number
This is marked draft because merging it will break CI until the new docker image is generated + published.
- ~~[ ] All variable and function names make sense.~~
- ~~[ ] The code is properly formatted …
=> Docker ci fixes

build/Dockerfile.c7.layered
This PR resolves #4147 
- Adding required lz4 libs for compilation.
=> Adding LZ4 to Centos 7 Docker Image: #4147

flow/CMakeLists.txt, flow/config.h.cmake
That's the only place they're needed. This fixes at least the USE_TSAN
build and possibly other sanitizer builds
=> Set special sanitizer annotations in stacktrace.amalgamation.cpp

documentation/sphinx/source/read-write-path.rst
Changes in this PR: Only change the doc text.
The rest of PR guideline is not applied here.
=> Remove "WiP" from the FDB Read and Write Path doc

fdbclient/NativeAPI.actor.h, fdbclient/ThreadSafeTransaction.h
This PR resolves a compilation error that seems to only occur within Windows CMake build. This errors seems to have been introduced in PR #3858. I'm not certain how it was able to pass CI.
=> Fixed error with Windows CMake Compilation Error

bindings/c/test/unit/unit_tests.cpp, fdbclient/NativeAPI.actor.cpp
- Removes `a/` from `tracing` namespace in special-key-space. For example, `\xff\xff/tracing/a/transaction_id` becomes `\xff\xff/tracing/transaction_id`.
=> Remove "a/" from tracing keys in special-key-space

fdbserver/VersionedBTree.actor.cpp
This PR resolves #4133 
- Added yield to remap cleanup loop to prevent a stack overflow if too many queue entries are processed without waiting on IO.
=> Fix stack overflow in Redwood

fdbclient/DatabaseConfiguration.h, fdbserver/LogSystemConfig.h, fdbserver/Status.actor.cpp
This PR is partially addresses #4163 but by no means resolves it.
This PR consists of three patches, each revertable on its own:
- Some comments and clang-format on code around fault-tolerance.
- Fix a bug where we calculated fault-tolerance wrong when keys are not fully replicated. Fault tolerance in that case should of total tLog replicas should be primary and satellite tLogs - 1.
- HACK: Ignore fault-tolerance of satellite to keep the fault-tolerance number same as 6.2. This is not a fix, but we will have a fix soon, with clear definition of fault tolerance.
- [TODO] Same for fault_tolerance_without_losing_availability
- ~[ ] All CPU-hot paths are well optimized.~
=> Docs, fix and hack for Fault Tolerance 

cmake/ConfigureCompiler.cmake
I don't know how this keeps reappearing. I've removed it several times already.
=> Remove -Wno-unused-value

fdbclient/SystemData.cpp, fdbclient/SystemData.h
https://github.com/apple/foundationdb/issues/4186
Adding more documentation to `/xff` system keys
=> Adding more documentation to system keys

flow/Platform.actor.cpp
The preceding `#ifdef _WIN32`  falls through on FreeBSD without this.
This could possibly be a `__unixish_` if desired.
~All CPU-hot paths are well optimized~
~The proper containers are used (for example `std::vector` vs `VectorRef`)~
~There are no new known `SlowTask` traces~
~The code was sufficiently tested in simulation~
~If there are new parameters or knobs, different values are tested in simulation~
~`ASSERT`, `ASSERT_WE_THINK`, and `TEST` macros are added in appropriate places~
~Unit tests were added for new algorithms and data structure that make sense to unit-test~
~If this is a bugfix: there is a test that can easily reproduce the bug~
=> flow: fix ifdef fall-through on FreeBSD

fdbbackup/backup.actor.cpp, fdbclient/ClientLogEvents.h, fdbclient/ClientWorkerInterface.h, fdbclient/TagThrottle.h, fdbserver/LogSystemConfig.h, fdbserver/RecoveryState.h, fdbserver/RestoreUtil.h, fdbserver/fdbserver.actor.cpp, fdbserver/workloads/ClientTransactionProfileCorrectness.actor.cpp, flow/serialize.h
- Makes enums automatically binary-serializable, removing the need to use the `BINARY_SERIALIZABLE` outside `serialize.h`
- Uses enum classes to improve type safety in client log events, as well as `fdbserver.actor.cpp` and `backup.actor.cpp`
=> Make enums automatically binary serializable

flow/ThreadPrimitives.h
In #3506,  a new preprocessor define is introduced, which clashes with [FreeBSD's own](https://cgit.freebsd.org/src/tree/sys/amd64/include/param.h#n88) :
```
/*
* CACHE_LINE_SIZE is the compile-time maximum cache line size for an
* architecture.  It should be used with appropriate caution.
*/
#define CACHE_LINE_SHIFT        6
#define CACHE_LINE_SIZE         (1 << CACHE_LINE_SHIFT)
```
Proposed fix is to prepend `MAX_` to the FDB code, which is then unique again.
~All CPU-hot paths are well optimized~
~The proper containers are used (for example `std::vector` vs `VectorRef`)~
~There are no new known `SlowTask` traces~
~The code was sufficiently tested in simulation~
~If there are new parameters or knobs, different values are tested in simulation~
~`ASSERT`, `ASSERT_WE_THINK`, and `TEST` …
=> build: don't clash with FreeBSD native defines

bindings/c/CMakeLists.txt, bindings/c/foundationdb/fdb_c.h, bindings/c/test/fdb_c89_test.c, bindings/c/test/fdb_c90_test.c, fdbclient/vexillographer/c.cs
It came up [here](https://github.com/apple/foundationdb/pull/4094#discussion_r546991555) that we don't know if we need to keep compatibility with c90 for fdb_c.h. It looks like we are currently compatible, so add a test to keep it that way.
Please verify that all things listed below were considered and check them. If an item doesn't apply to this type of PR (for example a documentation change doesn't need to be performance tested), you should make a ~~strikethrough~~ (markdown syntax: `~~strikethrough~~`). More infos on the guidlines …
=> Make sure that fdb_c.h is c90 compliant

fdbbackup/backup.actor.cpp
Currently, some of the binaries produced by `fdbbackup/backup.actor.cpp` do not support any top-level CLI options other than `-h` or `--help`. Running `$ ./fdbbackup --version` returns `ERROR: Unsupported backup action`. These options are instead baked into the actions for `fdbbackup`, so `$ ./fdbbackup start --version` works. This makes sense for certain flags to change the behavior of the action, but for other flags like checking the version of FDB these options should be provided at the top level of the binary (matching what `$ ./fdbbackup -h` prints).
This PR adds support for top-level CLI options for the backup binaries (`backup_agent`, `fdbbackup`, `fdbrestore`, `fastrestore_tool`, `dragent`, `fdbdr`). A few of these already supported top-level CLI options, but now they all do.
This …
=> Add top level CLI options to backup binaries

flow/Knobs.cpp, flow/Knobs.h, flow/Net2.actor.cpp
This PR adds a capability to reserve the underlying vector container of the priority_queue used for the ready queue.
We defaulted it to 8192 elements, but it's configurable through a new flow knob `READY_QUEUE_RESERVED_SIZE` also introduced in this PR.
Please verify that all things listed below were considered and check them. If an item doesn't apply to this type of PR (for example a documentation change doesn't need to be performance tested), you should make a ~~strikethrough~~ (markdown syntax: `~~strikethrough~~`). More infos on …
=> Reserve the priority queue container

fdbserver/storageserver.actor.cpp
- Added a trace line to help debug a rare failure
~- [ ] All CPU-hot paths are well optimized.~
~- [ ] The proper containers are used (for example `std::vector` vs `VectorRef`).~
~- [ ] There are no new known `SlowTask` traces.~
~- [ ] The code was sufficiently tested in simulation.~
~- [ ] If there are new parameters or knobs, different values are tested in simulation.~
~- [ ] `ASSERT`, `ASSERT_WE_THINK`, and `TEST` macros are added in appropriate places.~
~- [ ] Unit tests were added for new algorithms and data structure that make sense to unit-test~
~- [ ] If this is a bugfix: there is a test that can easily reproduce the bug.~
=> Add a SevWarnAlways trace line to help debug a rare failure.

fdbrpc/FlowTransport.actor.cpp
Fixes a warning due to "control reaches end of non-void function [-Wreturn-type]".
=> Fix -Wreturn-type warning

flow/IThreadPool.h
This fixes some "-Winconsistent-missing-override" warnings.
=> Add override keyword to DummyThreadPool methods

fdbserver/CommitProxyServer.actor.cpp
The original PR #4113 is lost when merging 6.3 to master.
- [] ~~Unit tests were added for new algorithms and data structure that make sense to …
=> Proxy rejects long enqueued transactions

fdbclient/SpecialKeySpace.actor.h, fdbrpc/FailureMonitor.h, flow/TDMetric.actor.h
This PR adds the override keyword in specific files to clean up warnings given by the compiler
=> Add override keyword properly to squash compiler warnings

cmake/ConfigureCompiler.cmake, cmake/InstallLayout.cmake, flow/Platform.actor.cpp, flow/ThreadPrimitives.h
This PR is fixes minor issues for aarch64.
- Use timestampCounter() instead of __rdtsc()
- Use appropriate architecture name in the package names
- Do not generate "amd64" deb packages
- Use isb instruction in the spin latch
Please verify that all things listed below were considered and check them. If an item doesn't apply to this type of PR (for example a documentation change doesn't need to be performance tested), you should make a ~~strikethrough~~ (markdown syntax: `~~strikethrough~~`). More infos on the …
=> Fix minor issues for aarch64

fdbcli/fdbcli.actor.cpp
This seems to have been inadvertently changed in
5b2e88b187c485d80119808c85e97fff98a30f8e.
=> Only print general help once in fdbcli

CMakeLists.txt, fdbbackup/FileConverter.actor.cpp, fdbbackup/FileConverter.h, fdbbackup/FileDecoder.actor.cpp, fdbbackup/backup.actor.cpp, fdbcli/fdbcli.actor.cpp, fdbclient/BuildFlags.h.in, fdbserver/fdbserver.actor.cpp
Adds a command line argument to most of the FDB binaries to print build information.
Example:
```
$ ./bin/fdbserver --build_flags
{
"arch" : "Linux-5.6.6-300.fc32.x86_64",
"boost_version" : "1_72",
"ccache" : "ON",
"cmake_version" : "3.13.4",
"compiler" : "Clang",
"cpp_standard" : 201703,
"fdb_version" : "7.0.0",
"git_hash" : "989299dc748a33040c0f6aa811d2399a0092c1da",
"glibc_version" : "2.12"
}
```
Binaries that support the `--build_flags` option:
* `fdbserver`
* `fdbcli`
* `backup_agent`
* `fdbbackup`
* `fdbrestore`
* `fastrestore_tool`
* `dr_agent`
* `fdbdr`
* `fdbconvert`
* `fdbdecode`
Dependent on #3771.
=> Add CLI argument to print build information

fdbrpc/FlowTests.actor.cpp
This wasn't included in my last PR since FlowTests.actor.cpp is not compiled in OPEN_FOR_IDE mode. I _think_ this is the last of the missing overrides.
=> Fix missing override in fdbrpc/FlowTests.actor.cpp

bindings/c/test/unit/unit_tests.cpp, fdbclient/NativeAPI.actor.cpp, fdbclient/vexillographer/fdb.options
- In order to capture spans emitted in fdbclient code, a tracer must be opened (using `openTracer`) in `fdbclient` and `fdbserver` code separately.
- Add a network option to set the tracer in fdbclient.
- Eventually, the goal is to allow one universal option to set the tracer in both client and server.
- ~~[ ] All CPU-hot paths are well optimized.~~
- ~~[ ] The proper containers are used (for example `std::vector` vs `VectorRef`).~~
- ~~[ ] `ASSERT`, `ASSERT_WE_THINK`, and `TEST` macros are added in appropriate places.~~
- ~~[ ] Unit tests were added for new algorithms and data structure that make sense to unit-test~~
- ~~[ ] If this is a bugfix: there is a test that can easily reproduce the bug.~~
=> Add network option to set tracer in fdbclient

build/docker-compose.yaml
This PR will enable warnings as errors within CI. This should allow us to increase the reliability and validity of our software.
=> Enabled warnings as errors within CI

fdbserver/KeyValueStoreSQLite.actor.cpp
PR #4212  introduced VFSAsyncFile::checkInjectedError() to detect injected fault.
This pr simply changes the two places left.
=> Use VFSAsyncFile::checkInjectedError to detect injected faults

fdbbackup/backup.actor.cpp
This fixes the Windows CI by undoing a change to `BackupType` enum names.
=> Fix Windows build

build/Dockerfile, build/Dockerfile.devel, build/docker-compose.yaml, cmake/FDBComponents.cmake, flow/TLSConfig.actor.cpp
This PR changes the default SSL implementation from OpenSSL to BoringSSL.  We're considering doing this in production.
- Set OPENSSL_ROOT_DIR to point to the version of BoringSSL included in the build docker
- Update some #ifdefs to work with BoringSSL.
- ~~[ ] The code was sufficiently tested in simulation.~~
- ~~[ ] `ASSERT`, `ASSERT_WE_THINK`, and `TEST` macros are added in appropriate places.~~
- ~~[ ] Unit tests were added for new algorithms and data structure that make sense to unit-test~~
- ~~[ ] If this is a bugfix: there is a test that can easily reproduce the bug.~~
Simulation doesn't touch this code path, but we run the boringssl unit tests after compiling it.  This has been tested + benchmarked on real hardware (vs. 6.3, but this PR is against 6.2).
=> Switch to BoringSSL by default

flow/Platform.cpp
Added a trace line in the `readFileBytes` path to provide more details about what caused `fopen` to fail
=> Add tracing to fileopen failure before throwing error for more info

fdbrpc/HealthMonitor.actor.cpp, fdbserver/MoveKeys.actor.cpp
Compiling with -D_GLIBCXX_DEBUG enables libstdc++ "debug mode", where
additional debug information is tracked with iterators and reported if
iterators are misused. This turned up two bugs.
I threw in removing dead code and avoiding an unnecessary map lookup
while I was in the neighborhood.
Please verify that all things listed below were considered and check them. If an item doesn't apply to this type of PR (for example a documentation change doesn't need to be performance tested), you should make a ~~strikethrough~~ (markdown syntax: …
=> Fix bugs turned up by _GLIBCXX_DEBUG

fdbserver/Coordination.actor.cpp, fdbserver/CoordinationInterface.h, fdbserver/Knobs.cpp, fdbserver/Knobs.h, fdbserver/SimulatedCluster.actor.cpp, fdbserver/worker.actor.cpp, flow/error_definitions.h
This PR is resolves #4251
Coordinators will not serve following requests after this change:
- A request that needs to be forwarded after the forward was set for a long(configured via Knobs) time.
- A request that has a different connection string than the CD's local connection string.
Simulation has been made to work with this change.
- No error found after 10k runs. Then simulation stopped due to 10 `JoshuaTimeout`
~- [ ] `ASSERT`, `ASSERT_WE_THINK`, and `TEST` macros are added in appropriate places.~
~- [ ] Unit tests were added for new algorithms and data structure that make sense to unit-test~
~- [ ] If this is a bugfix: there is a test that can easily reproduce the bug.~
=> CDs reject requests from external cluster or requests need to be forwarded based on an old forward request.

fdbserver/workloads/SnapTest.actor.cpp
Removes a space from a trace event name in the snapshot test workload.
=> Fix a trace event name that has a space in it

fdbrpc/AsyncFileCached.actor.h, fdbserver/KeyValueStoreSQLite.actor.cpp
- In simulation, KVStoreSQLite can outlive its process during a simulated reboot so its file references must be cleared explicitly during shutdown instead of implicitly during destruction.
- Code cleanup in AFCached, removing unnecessary things.
=> Simulation bug fix involving process reboot and destruction/recreation of KVSQLite

fdbclient/ManagementAPI.actor.cpp
The simulator could choose an unreliable process (one that has had fault injection enabled) to be a coordinator, even though this is something it had been trying to prevent.
This bug had been previously identified and addressed in #2802, but there seems to have been a bug in that fix that still allowed unreliable processes to be chosen.
=> Fix bug in simulated coordinator selection

documentation/sphinx/source/downloads.rst, documentation/sphinx/source/release-notes/release-notes-620.rst, fdbserver/Knobs.cpp
Also update release notes for the 6.2.30 release.
-
-
-
=> Updated knobs to enable low priority reads when durability lag is larger than 200 seconds

build/Dockerfile.c7.layered
Add distcc to c7.layered Dockerfile
cleanup Dockerfile for general readability
Implement pattern where each RUN directive cleans up after itself
source devtoolset-8 where needed, and avoid running scl enable before commands
change LLVM compile so it works (Ninja is failing)
This will be the base image for other centos7 containerized work. 
Please verify that all things listed below were considered and check them. If an item doesn't apply to this type of PR (for example a documentation …
=> cleanup Dockerfile.c7.layered, add distcc

contrib/TestHarness/Program.cs.cmake
TestHarness has two mechanisms that it uses to limit the amount of stderr output logged. One is that the sum total of all error messages be below 1000 bytes, the second is that each message be limited to 100 bytes and that there are no more than 10 messages.
This latter mechanism doesn't need to be so restrictive, and in fact 100 bytes is too few to capture some errors that we're seeing on tests right now. Also, the second mechanism silently truncates errors rather than providing any indication of the truncation.
This change increases the limit of each message to 1000 bytes and tries to make it more obvious when truncation is happening.
=> Increase the maximum length of the error strings logged by test harness

fdbrpc/FlowTransport.actor.cpp
This PR resolves #4294
- Ping endpoint is a stable endpoint so that incompatible connections can be kept alive
- Fix bug where we could start scanning for packets before finishing the connect packet
=> Make the ping enpoint a stable interface

fdbclient/ManagementAPI.actor.cpp
I [recently](https://github.com/apple/foundationdb/pull/4285) introduced a bug in a unit test that causes an invalid memory access at the end of simulated runs of that unit test. This fixes that bug by making the name of the process a literal string.
=> Fix memory bug in unit test

build/Dockerfile.c7.layered
clang was accidentally removed from this image. This adds it back
=> add clang back to c7 docker image

documentation/sphinx/source/release-notes/release-notes-620.rst, fdbserver/DataDistribution.actor.cpp, fdbserver/DataDistribution.actor.h, fdbserver/DataDistributionTracker.actor.cpp, fdbserver/fdbserver.actor.cpp, flow/Trace.cpp
- Fix a heap-use-after-free in data distribution. We found a valgrind error here. This is the same heap-use-after-free that 6235d087a6 intends to fix, but it turns out that there's still an ordering of callbacks that can get called that results in a heap-use-after-free even after that change.
- Also fix a heap-use-after-free that happens when you enable buggify in simulation
Please verify that all things listed below were considered and check them. If an item doesn't apply to this type of …
=> Fix memory errors

bindings/c/test/unit/unit_tests.cpp
#4241  forgot to initialize the random seed in the unit test, this pr simply add it and change the code to use C++ random generator instead of the C `rand()`.
=> Add seed initialization in snapshot c unit test 

cmake/CompileBoost.cmake
Previously in the official foundationdb/foundationdb-build docker image cmake could build against boost 1.72. This is the same bug fixed in 697a9422f5605fdb86afc485f90877931121238b for release-6.3 and master. For release-6.2 we need to make sure we build against 1.67 exactly.
(Alternatively we could backport 697a9422f5605fdb86afc485f90877931121238b, but I prefer this in the interest of making the minimal possible change to release-6.2)
=> Use boost version 1.67 exactly on release-6.2

flow/TLSConfig.actor.cpp
This PR increases the Severity of TLS handshake errors from 10 to 20.  
- [ X ] All variable and function names make sense.
- [ X ] The code is …
=> Tls verify warning

documentation/sphinx/source/mr-status-json-schemas.rst.inc, documentation/sphinx/source/release-notes/release-notes-700.rst, fdbclient/Schemas.cpp, fdbserver/CommitProxyServer.actor.cpp, fdbserver/ProxyCommitData.actor.h, fdbserver/Status.actor.cpp
This PR is a follow up of https://github.com/apple/foundationdb/pull/4113
- A transaction batch will be rejected immediately if it has been queued longer than the MVCC window, this commit counts this kind of rejection separately from `txnConflicts` 
- also added this field in `Status#workloadStatusFetcher` and changed schema accordingly.
=> Add txnRejectedForQueuedTooLong in ProxyStats

flow/Error.cpp
unknown_error usually gets created when an exception of some type other
than `Error` is thrown. If the current exception is a std::exception
(and it usually is), we can log more information about it - which is
(incredibly!) helpful for figuring out what the heck happened.
=> Log std::exception::what when creating an unknown_error

fdbclient/NativeAPI.actor.cpp, fdbserver/fdbserver.actor.cpp, flow/Tracing.actor.cpp, flow/Tracing.h
Should fix #4292 (see this issue for an explanation of what went wrong).
- Removes `AsyncUDPTracer`, which was used to serialize `Span`s and send them as UDP packets to a server.
- Updates `TraceRequest` object to use `unique_ptr` for better memory management.
Please verify that all things listed below were considered and check them. If an item doesn't apply to this type of PR (for example a documentation change doesn't need to be performance tested), you should make a ~~strikethrough~~ (markdown syntax: …
=> Remove async tracer

fdbclient/ManagementAPI.actor.cpp
Fix bug in code I recently added where the process name memory was not long-lived and was later used.
=> Backport 5b74556733228482bfc64ab6c3ef2894e9d139c4 to release-6.2

fdbserver/workloads/FuzzApiCorrectness.actor.cpp
This PR resolves #4371 
`timed_out`(e.g. `\xff\xff/status/json`) and `special_keys_api_failure`(e.g. the newly added `\xff\xff/management/auto_coordinators`) can happen in very rare cases.
=> Catch special key error in FuzzApiCorrectness test

fdbserver/DataDistribution.actor.cpp, fdbserver/TLogServer.actor.cpp, fdbserver/workloads/SnapTest.actor.cpp
This PR resolves https://github.com/apple/foundationdb/issues/4293.
- Add delay between `SnapTest` retries.
- Reenable pops on tlogs even if some tlogs never disable pops.
- Enforce disable pop deadline even if no more pop requests are received.
=> Fix Snapshot test failure

packaging/docker/Dockerfile
The PR https://github.com/apple/foundationdb/pull/4247 introduced a subtle issue so that thee image can't be build anymore:
```bash
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:2 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1391 kB]
Get:3 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [1929 kB]
Get:4 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [293 kB]
Get:5 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [35.5 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:9 …
```
=> Fix docker image

fdbcli/fdbcli.actor.cpp
This PR is resolves #4318
- fdbcli outputs errors and warning to `stderr` instead of `stdout` to make using fdbcli in scripts more easier. 
Please verify that all things listed below were considered and check them. If an item doesn't apply to this type of PR (for example a documentation change doesn't need to be performance tested), you should make a ~~strikethrough~~ (markdown syntax: `~~strikethrough~~`). More infos on the guidlines can be found [here](https://github.com/apple/foundationdb/wiki/FoundationDB-Commi …
=> fdbcli: Output errors and warnings to stderr

build/docker/centos6/build/Dockerfile, build/docker/centos7/build/Dockerfile
This PR allows `-DBUILD_AZURE_BACKUP` to be enabled on the default docker image.
=> Add Azure backup dependencies to Docker image

fdbclient/BackupContainerAzureBlobStore.actor.cpp
This PR resolves a compile error when compiling `master` branch using the default `foundationdb/foundationdb-build` docker along with the flag `cmake -DBUILD_AZURE_BACKUP=ON`
- A one line fix to BackupContainerAzureBlobStore.actor.cpp:93 related to a use of std::string::insert and some c++ version differences
- PR may be edited further by @sfc-gh-tclinkenbeard . 
- See https://github.com/apple/foundationdb/pull/3961#issuecomment-787401185
- Code in question is included only if compiled with `cmake -DBUILD_AZURE_BACKUP=ON`
I will be happy to manually test the feature once I confirm some other URL format issues I am tracking.
=> Fix a compile error: Related to pr 3961

fdbrpc/libeio/xthread.h
Fix a crash when running outside of simulation with libeio
=> Use default stack size for libeio threads

fdbserver/IKeyValueStore.h, fdbserver/KeyValueStoreRocksDB.actor.cpp
This PR makes the RocksDB storage engine `init()` method idempotent. After a storage server rollback, the `init()` method gets called a second time. Prior to this PR, that would fail as it would attempt to open a second copy of the RocksDB DB, which is a contract violation. This PR also adds a comment to the KeyValueStore interface noting the requirement on `init()`.  
Please verify that all things listed below were considered and check them. If an item doesn't apply to this type of PR (for example a documentation change doesn't need …
=> Make the RocksDB init method idempotent

build/docker/centos6/devel/Dockerfile, build/docker/centos7/devel/Dockerfile
This PR avoids the download of RocksDB for the development environment alias
- updating the cmake command line in the `cmk` alias
- [✅ ] All variable and function names make sense.
- [✅ ] The code is properly formatted (consider running `git clang-format`).
=> stop downloading RocksDB in dev container

fdbserver/fdbserver.actor.cpp, flow/Tracing.actor.cpp, flow/Tracing.h
- Stop running log file tracer in simulation. This was causing a large amount of log output in certain scenarios, causing tests to fail that otherwise wouldn't.
Please verify that all things listed below were considered and check them. If an item doesn't apply to this type of PR (for example a documentation change doesn't need to be performance tested), you should make a ~~strikethrough~~ (markdown syntax: `~~strikethrough~~`). More infos on the guidlines can be found …
=> Stop running log file tracer in simulation

fdbserver/storageserver.actor.cpp, fdbserver/workloads/WatchesSameKeyCorrectness.actor.cpp, flow/genericactors.actor.h
This PR relates to #3826
[Design Doc
](https://docs.google.com/document/d/11Wi00ZJqkiyYBmHXqL6aT3-IUcmrW-VM69nzzWTuYo0/edit?usp=sharing)
- Collapsing server watches to reduce memory overhead
Please verify that all things listed below were considered and check them. If an item doesn't apply to this type of PR (for example a documentation change doesn't need to be performance tested), you should make a ~~strikethrough~~ (markdown syntax: `~~strikethrough~~`). More infos on the guidlines can be found …
=> Optimize Watches Server

build/docker/centos6/devel/Dockerfile, build/docker/centos7/devel/Dockerfile
This PR resolves being able to submit correctness jobs from the devel container image
- install joshua python package from github source
- install old fdb binaries
- [✅] All variable and function names make sense.
- [✅] The code is properly formatted (consider running `git clang-format`).
=> install fdb-joshua and old fdb binaries

fdbrpc/AsyncFileEIO.actor.h, fdbrpc/AsyncFileWinASIO.actor.h, fdbrpc/IAsyncFile.actor.cpp, fdbrpc/IAsyncFile.h, fdbrpc/Net2FileSystem.cpp, fdbrpc/Net2FileSystem.h, fdbrpc/sim2.actor.cpp, fdbrpc/simulator.h
We ran into issues where slow metadata operations on NFS slows down backup_agents enough to create failures. This causes a backup to slow down and potentially stall.
This change adds a new rename function to AsyncFileSystem that utilizes EIO in order to execute this in another thread. This will not make renames go faster, but it will not block the network thread.
This still needs to be plumbed into the backup_agent, but this will be added in a later PR.
=> Add async rename

fdbserver/CoroFlow.actor.cpp, fdbserver/KeyValueStoreRocksDB.actor.cpp, flow/IThreadPool.cpp, flow/IThreadPool.h, flow/Platform.cpp, flow/Platform.h, flow/Trace.cpp
This PR adds support for naming threads on Linux to `Platform.h` and uses that functionality to name the RocksDB reader and writer threads. Adding support for additional platforms could be done via additional ifdefs.
=> Name the RocksDB background threads

fdbserver/DataDistribution.actor.cpp
- Change SSVersionDiffLarge event severity to warning to better identify lagging SS.
- [ x ] The code is properly formatted (consider running `git clang-format`).
=> Change SSVersionDiffLarge event severity to warning

fdbserver/GrvProxyServer.actor.cpp
This PR resolves #3919 
- This essentially adds changes from https://github.com/apple/foundationdb/pull/3960 made to MasterProxyServer.actor.cpp to GrvProxyServer.actor.cpp, since MasterProxyServer.actor.cpp has been broken down into GrvProxyServer.actor.cpp and CommitProxyServer.actor.cpp
- The changes are all in GrvProxyServer.actor.cpp
=> Adding proxy local rate limit metrics reporting back to GrvProxyServer

fdbserver/DeltaTree.h
If n == nullptr here, then we'll dereference a nullptr. Add an assert.
=> Add ASSERT to help clang-tidy

bindings/java/CMakeLists.txt, bindings/java/src/integration/com/apple/foundationdb/RangeQueryIntegrationTest.java, bindings/java/src/junit/com/apple/foundationdb/EventKeeperTest.java, bindings/java/src/junit/com/apple/foundationdb/FakeFDBTransaction.java, bindings/java/src/main/com/apple/foundationdb/Database.java, bindings/java/src/main/com/apple/foundationdb/EventKeeper.java, bindings/java/src/main/com/apple/foundationdb/FDB.java, bindings/java/src/main/com/apple/foundationdb/FDBDatabase.java, bindings/java/src/main/com/apple/foundationdb/FDBTransaction.java, bindings/java/src/main/com/apple/foundationdb/FutureKey.java, bindings/java/src/main/com/apple/foundationdb/FutureResult.java, bindings/java/src/main/com/apple/foundationdb/FutureResults.java, bindings/java/src/main/com/apple/foundationdb/MapEventKeeper.java, bindings/java/src/main/com/apple/foundationdb/NativeFuture.java, bindings/java/src/main/com/apple/foundationdb/RangeQuery.java, bindings/java/src/main/com/apple/foundationdb/tuple/FastByteComparisons.java, bindings/java/src/tests.cmake
This PR resolves #4384 
- Adds an `EventKeeper` interface to allow external plug-in instrumentation
- Adds some (limited) instrumentation to `FDBTransaction` and `RangeQuery` 
- Adds testing to verify instrumentation at java driver level only.
Please verify that all things listed below were considered and check them. If an item doesn't apply to this type of PR (for example a documentation change doesn't need to be performance tested), you should make a ~~strikethrough~~ (markdown syntax: `~~strikethrough~~`). More …
=> Add the ability to instrument java driver actions

bindings/go/CMakeLists.txt, cmake/CompileBoost.cmake, cmake/ConfigureCompiler.cmake, cmake/FDBComponents.cmake, fdbserver/CoroFlow.actor.cpp
This fixes the "client switching stacks?" warning that valgrind is
currently issuing.
Also fix a memory error that currently doesn't manifest because of the
way FastAllocator works (if you free a small buffer and then immediately
allocate the same size buffer in FastAllocator you always get the same
buffer back). You can see it if you set `FDB_VALGRIND_PRECISE=` in the environment (causes
FastAllocator to use malloc)
Also minor refactoring and cleanup of CoroFlow.actor.cpp
Also (probably) fix the other sanitizer builds. I tested ASAN …
=> Inform boost context of valgrind usage

fdbserver/Knobs.cpp, fdbserver/Knobs.h, fdbserver/TagPartitionedLogSystem.actor.cpp
- During recovery, wait for TLOG_SLOW_REJOIN_WARN_TIMEOUT_SECS and
log the tLogs that has not joined yet.
=> Add TraceEvent to warn tLogs which has not joined after timeout

fdbclient/MultiVersionTransaction.actor.cpp, tests/python_tests/multithreaded_client.py
The recent change to add client threading support through the multi-version client had a behavior change to cause external clients to be copied even when we aren't using multiple threads. One side effect of this is that if the primary library is included in your list of external libraries, we will now generate an extra trace file for the copied primary library.
=> Multi-version client: don't copy external libraries if we aren't using multiple threads

fdbcli/fdbcli.actor.cpp
- When listing regions in fdbcli status, the second and later regions would erroneously include satellites from prior regions. This change causes the vector of satellites to be reset for each region.
=> Fix bug where regions reported extra satellites

flow/Platform.h
This PR is meant to help work around the clang-format problem described in #4476 for flow/Platform.h. By changing to a static assertion, clang-format no longer mistakenly believes the file is an Objective-C file.
This PR also applies clang-format to flow/Platform.h that couldn't be done without this change. This is done as a second commit to simplify reviewing.
Note that I did not make the same fix for fdb_c.h because that file supports older versions of C that don't support static assertions.
I tested this by adding an `exit()` call to the code and making sure it failed to compile.
=> Change the macro that forbids exit() calls to be a static assertion

packaging/docker/Dockerfile
This PR resolves #2511
- Adding tini as PID 1
=> Add tini as PID 1 to docker image

documentation/sphinx/source/api-common.rst.inc
- Add serialization endianness info for versionstamps. Currently this info is missing from the C, Python, and Ruby APIs.
- The Java documentation already contains endianness info for versionstamps (see https://apple.github.io/foundationdb/javadoc/com/apple/foundationdb/MutationType.html#SET_VERSIONSTAMPED_KEY).
- The Go documentation also contains this info (https://pkg.go.dev/github.com/apple/foundationdb/bindings/go/src/fdb?utm_source=godoc#Transaction.SetVersionstampedKey).
Versionstamps are written [here](https://github.com/apple/foundationdb/blob/335df9b052ca1f5f6e3ef9c88bc10f83c1d255a7/fdbclient/Atomic.h#L249).
- If this PR still needs work, …
=> Add versionstamp endianness information to public documentation

pull_request_template.md
So I got the markdown for the PR template wrong :( This fixes it. I tested this by copy&pasting it into a GitHub PR and checked that the preview looked correct.
=> Fix markdown of PR template

bindings/c/fdb_c.cpp, bindings/java/CMakeLists.txt, contrib/Joshua/scripts/correctnessTest.sh, fdbcli/FlowLineNoise.actor.cpp, fdbclient/NativeAPI.actor.cpp, fdbserver/worker.actor.cpp, fdbserver/workloads/ApiCorrectness.actor.cpp, flow/Arena.cpp, flow/FastAlloc.cpp, flow/IThreadPool.cpp, flow/Net2.actor.cpp
Fix several memory leaks and a thread leak. I've been using leak sanitizer (comes with ASAN) and thread sanitizer to find these.
fdb_c_external_client_unit_tests is still showing memory leaks, indicating a possible memory leak in the multi-version client.
Passed 10k tests in joshua.
=> Fix several leaks

fdbrpc/simulator.h
Fixes issue #4445
Injected faults add a fault injection probability to both the process and its machine, however the isReliable() check did not look to see if it was enabled for the machine. This lead to a bug where simulation thought a process was reliable when it was not.
20k correctness tests passed
Please verify that all things listed below were considered and check them. If an item doesn't apply to this type of PR (for example a documentation change doesn't need to be performance tested), you should make a …
=> Fixed a bug in isReliable() of a simulated process

flow/Platform.h
This is a backport of #4479 meant to help us finish applying clang-format to the release-6.3 branch.
This PR is meant to help work around the clang-format problem described in #4476 for flow/Platform.h. By changing to a static assertion, clang-format no longer mistakenly believes the file is an Objective-C file.
This PR also applies clang-format to flow/Platform.h that couldn't be done without this change. This is done as a second commit to simplify reviewing.
Note that I did not make the same fix for fdb_c.h because that file supports older versions of C that don't support static assertions.
I tested this by adding an exit() call to the code and making sure it failed to compile.
=> Change the macro that forbids exit() calls to be a static assertion (release-6.3)

fdbserver/CommitProxyServer.actor.cpp
The problem is described in https://github.com/apple/foundationdb/issues/4426.
MasterProxyServer.actor.cpp on master is replaced with CommitProxyServer.actor.cpp and GrvProxyServer.actor.cpp and changes in #4004 is lost.
=> Port lost changes from PR #4004

flow/Platform.h
This is a backport of #4479 meant to help us finish applying clang-format to the release-6.2 branch.
This PR is meant to help work around the clang-format problem described in #4476 for flow/Platform.h. By changing to a static assertion, clang-format no longer mistakenly believes the file is an Objective-C file.
This PR also applies clang-format to flow/Platform.h that couldn't be done without this change. This is done as a second commit to simplify reviewing.
Note that I did not make the same fix for fdb_c.h because that file supports older versions of C that don't support static assertions.
I tested this by adding an exit() call to the code and making sure it failed to compile.
=> Change the macro that forbids exit() calls to be a static assertion (release-6.2)

fdbserver/CommitProxyServer.actor.cpp, fdbserver/ProxyCommitData.actor.h
This fixes #4426, where bad merge from 6.3 to master lost some PRs and changes to MasterProxyServer.actor.cpp, which on master is replaced with CommitProxyServer.actor.cpp and GrvProxyServer.actor.cpp.
=> Port lost PR #4166 back

bindings/c/foundationdb/fdb_c.h
This is a manual cherry-pick of #4499. As this is only a formatting change, no testing was done for this PR. As we applied clang-format on all active release branches, this should be cherry-picked down.
=> clang-format fdb_c.h

bindings/c/foundationdb/fdb_c.h
Clang format doesn't like the way `This_FoundationDB_API_function_is_removed_at_this_FDB_API_VERSION` was implemented (due to the angle brackets it identified the file as being Objective-C instead of C++).
I change the macro to use `{}` instead of `[]` which makes `clang-format` happy and should have the same semantic (it will break compilation). Additionally I applied `clang-format` to the file.
This resolves #4476
=> Fix clang-format issue with fdb_c.h

build/docker/centos7/build/Dockerfile
- Use Python38 and Ruby27 on aarch64
- Use CMake v3.19.6 official build for aarch64
=> Add aarch64 support in CentOS7 Dockerfile

packaging/docker/samples/golang/app/Dockerfile
This PR resolves the error on updating Go.
- Support Go 1.16
- Use apt-get instead of apt to suppress warnings
- Install ca-certificates to resolve the error on downloading foundationdb.
Please verify that all things listed below were considered and check them. If an item doesn't apply to this type of PR (for example a documentation change doesn't need to be performance tested), you should make a ~~strikethrough~~ (markdown syntax: `~~strikethrough~~`). More infos on the guidlines can be found …
=> Update example Dockerfile

bindings/c/test/unit/unit_tests.cpp, fdbclient/ThreadSafeTransaction.cpp, flow/Net2.actor.cpp
Fix a data race in the new fdb_get_server_protocol function found by running its unit test under TSAN. TSAN confirmed the fix as well.
```
2: WARNING: ThreadSanitizer: data race (pid=47)
2:   Write of size 4 at 0x7b1c00000770 by thread T1:
2:     #0 ThreadUnsafeReferenceCounted<ClusterConnectionFile>::addref() const /home/anoyes/workspace/foundationdb/flow/FastRef.h:71:24 (libfdb_c.so+0x4b93aa)
2:     #1 void addref<ClusterConnectionFile>(ClusterConnectionFile*) /home/anoyes/workspace/foundationdb/flow/FastRef.h:94:7 (libfdb_c.so+0x4b93aa)
2:     #2 Reference<ClusterConnectionFile>::Reference(Reference<ClusterConnectionFile> const&) /home/anoyes/workspace/foundationdb/flow/FastRef.h:114:4 (libfdb_c.so+0x4b93aa)
2:     #3 (anonymous namespace)::GetCoordinatorProtocolsActorState<(anonymous …
```
=> Fix data race in fdb_get_server_protocol

fdbserver/ClusterController.actor.cpp
The current event trace during recruitment doesn't contain which datacenter the recruitment is executing. This is especially hard to debug in HA mode. So logging dc information can help us quickly identify the recruitment DC.
=> Log dcIDs during TLog recruitment.

fdbserver/ClusterController.actor.cpp
This PR adds more logging information during Tlog worker recruitment.
When a worker is considered as unavailable during Tlog recruitment in the cluster controller, there are several reasons, and the current logging message is hard to tell what's the real cause. This makes debugging hard especially Tlog recruitment is critical for database availability.
Tested by existing unit tests and joshua tests.
=> Logging more detailed information during Tlog recruitment

fdbserver/CommitProxyServer.actor.cpp
This issue relates to: #4523 
We were never decrementing commitBatchesMemBytesCount when rejecting a commit batch causing this value to "blow up". This PR address this to make sure we are decrementing before returning.
This PR passes 10k Joshua runs
=> Decrement commitBatchesMemBytesCount when rejecting commit batch

fdbserver/ClusterController.actor.cpp
This is a cleanup after #4516 and #4518 . We also want to show the target DC IDs where the recruitment is going on.
10k Joshua run:
20210319-210932-zhewu-c5bdd7968acbe533             compressed=True data_size=22088549 duration=354133 ended=10180 fail_fast=10 max_runs=10000 pass=10000 pr=tlog-dcid priority=100 remaining=0 runtime=0:16:20 sanity=False started=10484 stopped=20210319-212552 submitted=20210319-210932 timeout=5400 username=zhewu
=> Add targeting DC ids in the tlog recruitment event trace.

fdbserver/Status.actor.cpp
We can have LogSets where there are no tLogs but some LogRouters. Its
the way recruiting is implemented for old LogRouters in
TagPartitionedLogSystem, where it adds an empty LogSet for missing
locality.
Here's where the new LogSets are being added for missing locality:
https://github.com/apple/foundationdb/blob/7066513109f7b7f4ae716e07c1b595251cafcb18/fdbserver/TagPartitionedLogSystem.actor.cpp#L1996-L2001
https://github.com/apple/foundationdb/blob/7066513109f7b7f4ae716e07c1b595251cafcb18/fdbserver/TagPartitionedLogSystem.actor.cpp#L2041-L2045
- If you wish to get feedback/code-review, please add the label RFC …
=> status: Ignore LogSets with no tLogs when computing FT

.gitignore
- Add `.cache` directory to `.gitignore`. Seems to be default for index  cache in some setups. 
- Also, ignore `.projectile` and `.dir-locals.el` which are Emacs project setup files.
=> Add some entries to `.gitignore` 

documentation/sphinx/source/release-notes/release-notes-620.rst
The 6.2 release notes had a link with a bad title (wrong PR number). This seemingly broke the build on release-6.3 during the final merge up (or maybe it was a coincidental transient error?), so I've already fixed in the release-6.3 merge PR (#4496) and it's soon to be merged to master. This is backporting the fix to release-6.2.
=> Fix the link title in a 6.2.33 release note

fdbserver/ClusterController.actor.cpp
Fixes #4341
We do not want a process switching between degraded and not degraded to repeatedly cause recoveries with every switch. To avoid this pathology, if better master exists detects that a new configuration removes a degraded process but also lowers the total number of recruited processes, it will no longer force a recovery.
passed 20k correctness tests
=> Do not trigger BetterMasterExists if it lowers the number of processes

fdbserver/SimulatedCluster.actor.cpp, fdbserver/TesterInterface.actor.h
As we add more and more arguments to the test configuration for a given test workload, the code begins to grow unwieldy. The goal of this is to factor out these extra arguments into a struct and pass them around to the appropriate places to be used.
This PR include a new argument `storageEngineExcludeType` that allows exclusion of a storage engine type when testing (mostly to prevent redwood from begin chosen for downgrades)
The main changes were to `SimulatedCluster.actor.cpp` in the construction of `SimulationConfig` and to the arguments of existing functions that used the parameters factored out into the new structure `TestConfig`, such as `restartSimulatedSystem` and `setupSimulatedSystem`
The general guidelines can be found [here](https://github.com/apple/foundationdb/wiki/FoundationD …
=> Factor out the checks for test configuration in simulation tests + added new parameter

fdbserver/workloads/FastTriggeredWatches.actor.cpp
Relates to: #4481 
Currently the FastTriggeredWatches test in simulation fails because a watch takes longer to fire than the expected limit (12s). This PR increases the limit to 25s in hopes of reducing the flakiness of the test. We should consider moving this test out of simulation if this test continues to fail (for flaky reasons).
This has passed 50k Joshua runs
=> Increase watch trigger time limit in FastTriggeredWatches

fdbserver/DataDistribution.actor.cpp, fdbserver/QuietDatabase.actor.cpp
This is a cherry-pick of a [fix](https://github.com/apple/foundationdb/pull/4450) from `release-6.3`.
The [change](https://github.com/apple/foundationdb/pull/3933/commits/7ebb2e5c09564a35196b0a56cdcddbc705b232fc#diff-f3e66a6ee528a2fb4f9f61766269750c368f639ff9e231b00d6c514bbe5e21a6R2107) updated the trace attribute name
from CurrentTeams to CurrentServerTeams,
but did not change the code where QuietDatabase read the trace,
thus causing QuietDatabase to fail.
Related issue: #4521 #4522 
The fix is very straightforward to use the latest name `CurrentServerTeams` when reading the trace.
=> Fix base trace event name inconsistency

fdbserver/DataDistribution.actor.cpp, fdbserver/DataDistribution.actor.h, fdbserver/DataDistributionTracker.actor.cpp
This PR resolves #4440
Exclude failed modifies the keyServers key space directly, however it does not prevent modifications happening in parallel from the data distribution queue. This means data distribution can end up with a state in the database that does not match its in memory state. For example, if a relocate shard has a start move keys complete, but the before finish move keys completes one of the destination servers is removed, that relocation will never complete.
This PR executes excludes fails after shutting down the data distribution queue, to prevent any inconsistency between the two different operations.
20k correctness passed
- If this …
=> Execute exclude failed commands after shutting down the rest of data distribution

fdbrpc/sim2.actor.cpp
Opening a file with OPEN_ATOMIC_WRITE_AND_CREATE should create a new file handle, so that if a file with the same name is still in use, operations against it will not happen to the new file. This can happen when the disk queue replaces a file.
=> Fixed a simulation only durability error

fdbserver/ClusterController.actor.cpp
This fixes a bug found by simulation where: `ASSERT(!oldSatelliteFallback || (region.satelliteTLogPolicyFallback.isValid() && logSet.tLogPolicy->info() == region.satelliteTLogPolicyFallback->info()));` in better master exists was failing.
This was happening because the `region` configuration did not match with the `dbi.config` because the cluster was in the process of changing the configuration. However, if the current configuration does not have a satellite fallback policy we do not care if the old configuration is in fallback mode, so we can avoid checking this condition.
If this PR is …
=> Fixed an assertion failure in better master exists

fdbrpc/simulator.h, fdbserver/workloads/RemoveServersSafely.actor.cpp
This is a backport of #4549 -- as this only affects simulation I didn't do a whole lot of testing but 10k simulation tests succeeded. This fix is necessary to make nightlies succeed again
=> Backport fix 4549

fdbserver/masterserver.actor.cpp
This is an alternative fix to #4376 that is potentially safer because it accounts for the other parts of the configuration being different besides just what is in the assert. 
=> Do not call expectedLogSets() with the wrong configuration

bindings/java/CMakeLists.txt, bindings/java/src/README.md, bindings/java/src/integration/com/apple/foundationdb/BasicMultiClientIntegrationTest.java, bindings/java/src/integration/com/apple/foundationdb/DirectoryTest.java, bindings/java/src/integration/com/apple/foundationdb/MultiClientHelper.java, bindings/java/src/tests.cmake, cmake/AddFdbTest.cmake, tests/TestRunner/local_cluster.py, tests/TestRunner/tmp_cluster.py, tests/TestRunner/tmp_multi_cluster.py
This PR assists PR #4339 in order to make it easier to write tests against the multi-threaded java client.
- Brings over `tmp_cluster.py` and `local_cluster.py` to the 6.3 branch
- Adds a "MultiClient" run for ctest
- Filters out multi-client tagged tests (tests that are tagged with `@Tag("MultiClient")` from normal integration tests
Please verify that all things listed below were considered and check them. If an item doesn't apply to this type of PR (for example a documentation change doesn't need to be …
=> Add multi-cluster FDB java tests through cmake

fdbserver/SimulatedCluster.actor.cpp, fdbserver/TesterInterface.actor.h
This fix is for https://github.com/apple/foundationdb/issues/4543. The `extraDB` parameter in `SimulationConfig` was left uninitialized and was still being referenced in `generateNormalConfig` as `extraDB` instead of `testConfig.extraDB`. Instead of removing the struct field and referencing `testConfig`, I decided to leave it in and have it be populated correctly in the constructor.
=> Initialize extraDB in simulationConfig according to TestConfig parameter

fdbrpc/AsyncFileNonDurable.actor.h, fdbrpc/IAsyncFile.actor.cpp
Before this, truncating and reading concurrently in simulation could cause to read
uninitialized memory. So could truncating then reading, since the effect
of the truncate in the actual file was allowed to be delayed. Now reads
will wait for a truncate that extends the file to complete if they
intersect the newly-zeroed region. Also add a simple unit test that fails before this fix and passes after.
=> In simulation, fix treatment of extending a file with truncate as a "pending modification"

fdbserver/workloads/FuzzApiCorrectness.actor.cpp
This is basically a cherry-pick of pr #4378 (Some changes not backported since the code is not available on `6.3`)
In general, when reading `\xff\xff/status/json`, `timed_out` can be thrown.
And the contract is now missing in the FuzziApiCorrectness test.
Issue: #4560
=> Catch timed_out error in FuzziApiCorrectness when reading \xff\xff/status/json

fdbserver/SimulatedCluster.actor.cpp, fdbserver/TesterInterface.actor.h
This PR is the cherry-pick of the commits in https://github.com/apple/foundationdb/pull/4537 and https://github.com/apple/foundationdb/pull/4544 from `master` to `release-6.3`. The reason these changes need to go into 6.3 is to support a test configuration that allows redwood as a storage engine type to be disabled for particular simulation tests. This is necessary for testing correctness of 6.3->6.2 downgrades.
There are some additional changes that remove references to fields only present on master and were carried over through the cherry-pick. `protocolVersion` as a parameter, and references to `g_simulator.hasDiffProtocolProcess` and `g_simulator.setDiffProtocol` were removed.
The general guidelines can be found [here](https://github.com/apple/foundationdb/wiki/FoundationDB-Commit-Proc …
=> Factor out the checks for test configuration in simulation tests + added new parameter (6.3)

documentation/sphinx/source/release-notes/release-notes-630.rst, fdbclient/FileBackupAgent.actor.cpp
Part of the restore process loads the saved mutation log from the backup into the database for application to restored snapshot key ranges.  The log is in approximate version order and not organized by key range, so if the restore was targeting a small range most of the log data loaded was unnecessary and would be loaded into the database only to be ignore during a later mutations application phase.
This PR enables partial filtering of log mutation data during restore, which should be extremely effective in most restore scenarios.  All log data is still read from the backup, but as each 1MB chunk is loaded it is checked for any *complete* sets of mutation chunks, each of which cover a specific commit version, and if any are found which do not contain any relevant data for the restore's …
=> Mutation log filtering during restore

fdbserver/tester.actor.cpp, tests/restarting/to_6.3.10/CycleTestRestart-1.txt, tests/restarting/to_6.3.10/CycleTestRestart-2.txt
https://github.com/apple/foundationdb/pull/4559 introduced a new test workload option `storageEngineExcludeType`, but was missing some code in `tester.actor.cpp` to recognize the option and avoid failing tests. Also added the option to some test files with the default option to ensure the option is being parsed properly.
=> Updated test parser to read new option correctly

fdbserver/Knobs.cpp, fdbserver/Knobs.h, fdbserver/fdbserver.actor.cpp
Allow the system monitoring frequency to be changed to something other than 5.0 to reduce the splunk log space.
=> add SYSTEM_MONITOR_FREQUENCY knob.

fdbserver/tester.actor.cpp, tests/fast/MoveKeysCycle.txt
Backporting https://github.com/apple/foundationdb/pull/4573 fix to 6.3 as well. The test parsing code between 7.0 and 6.3 are different, so the code changes are not cherry-picked from the original commit. This is necessary on 6.3 to fix a missed part from https://github.com/apple/foundationdb/pull/4559.
=> Updated test parser to read new option correctly (6.3)

cmake/CompileBoost.cmake
The current OS X build is failing with
```
clang: error: unknown argument: '-fcoalesce-templates'
```
I found the fix from this [post](https://github.com/alisw/alidist/pull/2159)
=> Fix boost build on OS X

fdbserver/ClusterController.actor.cpp, fdbserver/workloads/LowLatency.actor.cpp, flow/IRandom.h, flow/flow.cpp
This PR fixes two bugs that cause LowLatency to fail occasionally:
When recruiting the tlogs currently don't take into account how many roles are already running on a process. However, `betterMasterExists` would check for this. As a result, `betterMasterExists` would sometimes return true but recruitment would still end up doing the same recruitment. This can cause multiple recoveries.
The second bug causes a very similar problem: in three-data-hall mode `betterMasterExist` might not recruit tlogs in the same data hall as the recruitement. The fix here is to always prefer tlogs in other data halls.
Additionally this PR reintroduces `debugRandom`, a function which can be used to generate deterministic random numbers without changing the determinism of the simulation run.
Ran 100k Joshua …
=> Fix bug where betterMasterExist and recruitment disagree

fdbclient/BackupAgentBase.actor.cpp
The backup log data is stored in the "backupLogKeys" (i.e., \xff\x02/blog/) keyspace.
=> Fix a comment on backup log data location

fdbbackup/backup.actor.cpp, fdbclient/BackupContainerFileSystem.actor.cpp, fdbclient/FileBackupAgent.actor.cpp
This change will use the actual restore range as the filter for choose files during the restore, which can significantly reduces the number of range files (by filtering based on ranges) being used. See the issue description in #4585.
Correctness passed 100k tests.
20210328-043707-jingyu_zhou-46d4c41ac5c7db7f       compressed=True data_size=20363511 duration=3787745 ended=106739 fail_fast=10 max_runs=100000 pass=100001 priority=100 remaining=0 runtime=0:23:27 sanity=False started=106761 stopped=20210328-050034 submitted=20210328-043707 timeout=5400 username=jingyu_zhou …
=> Use the restored range in the actual restore

fdbbackup/backup.actor.cpp, fdbclient/BackupAgentBase.actor.cpp, fdbclient/BackupContainer.actor.cpp, fdbclient/FileBackupAgent.actor.cpp
This is the cherry-pick of #4568. Correctness of 100k tests passed.
This is for solving #4585.
=> Cherry-pick 4568 to 6.3: Use the restored range in the actual restore

fdbserver/DataDistribution.actor.cpp
We see segfault failure in release-6.3 joshua run recently (reference: #4593), and it appears that this issue has been fixed in master 7 month ago. So this PR cherry-pick the fix into release-6.3.
100K joshua run passed:
20210330-232404-zhewu_4594-c66be81196788115        compressed=True data_size=20342059 duration=5550892 ended=105589 fail_fast=10 max_runs=100000 pass=100001 priority=100 remaining=0 runtime=0:27:43 sanity=False started=107992 stopped=20210330-235147 submitted=20210330-232404 timeout=5400 username=zhewu_4594 …
=> Cherry pick #3698 to release-6.3

fdbrpc/simulator.h, fdbserver/SimulatedCluster.actor.cpp, fdbserver/workloads/ChangeConfig.actor.cpp
Simulations with region configurations that enables automatic failover could failover before both regions are fully replicated.
2 failures out of 200k tests
=> Fixed simulations which timeout setting starting configuration

build/docker/centos6/devel/Dockerfile, build/docker/centos7/devel/Dockerfile
Developer aliases do not cover the same build/test options as CI, this leads to discrepancies between dev environment and CI environment builds. 
These commands are currently run in CI, and have been tested in a `devel` image by the author, and work as expected. 
These Dockerfiles are only maintained in the master branch. 
- [✅] The PR has a description, explaining both the problem and the solution.
- [✅] The description mentions which forms of testing were done and the testing seems reasonable.
- [⛔] Every function/class/actor that was touched is reasonably well documented.
If this PR is …
=> align developer aliases with CI build commands

bindings/java/src/junit/com/apple/foundationdb/EventKeeperTest.java
There are two tests in `EventKeeperTest` that don't really test for anything--they are just present to verify that a particular metric is being incremented. But the test design relies on not having the FDB native libs available to the system. In `ctest`, this is never true. 
There are three possible approaches:
1. put in a special case junit test area just for those two small tests so that ctest will test them without the library
2. Ignore those tests as they aren't meaningfully important.
3. redesign those tests to allow for the library being present
Option 3 would likely have some (extremely minor) performance implications (an extra method call, which isn't exactly expensive and HotSpot might inline it anyway, but still), and Option 1 is like using a bazooka to go dove hunting--the …
=> Disabling some broken java tests

fdbserver/Knobs.cpp, fdbserver/LogSystemPeekCursor.actor.cpp
#4586 also shows up in release-6.3. So we need to cherry pick the fix.
I ran joshua test, and the two test failures are the known fast/BackupCorrectnessClean.txt tests.
20210402-054125-zhewu_4607-ed25143158a1f3e1 compressed=True data_size=20342072 duration=4516122 ended=107257 fail=2 fail_fast=10 max_runs=100000 pass=99998 priority=100 remaining=0 runtime=0:22:55 sanity=False started=107322 stopped=20210402-060420 submitted=20210402-054125 timeout=5400 username=zhewu_4607
=> Cherry pick #4601 to fix #4586 in release-6.3

documentation/sphinx/requirements.txt
set docutils version discretely for documentation build. 
docutils 0.17 was released on 3-April-2021 and caused out documentation build to break. There are unicode/utf-8 characters in the some part of the docutils package/documentation that cause sphinx_build to fail to parse with the error: 
```
File "/root/build_output/documentation/venv/lib64/python3.6/site-packages/sphinx/cmdline.py", line 295, in main
opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
File "/root/build_output/documentation/venv/lib64/python3.6/site-packages/sphinx/application.py", line 189, in __init__
self.setup_extension(extension)
File "/root/build_output/documentation/venv/lib64/python3.6/site-packages/sphinx/application.py", line 512, in setup_extension
mod = …
```
=> specify docutils version

documentation/sphinx/requirements.txt
set docutils version discretely for documentation build. 
docutils 0.17 was released on 3-April-2021 and caused out documentation build to break. There are unicode/utf-8 characters in the some part of the docutils package/documentation that cause sphinx_build to fail to parse with the error: 
```
File "/root/build_output/documentation/venv/lib64/python3.6/site-packages/sphinx/cmdline.py", line 295, in main
opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
File "/root/build_output/documentation/venv/lib64/python3.6/site-packages/sphinx/application.py", line 189, in __init__
self.setup_extension(extension)
File "/root/build_output/documentation/venv/lib64/python3.6/site-packages/sphinx/application.py", line 512, in setup_extension
mod = …
```
=> specify docutils version -- cherry-pick 4621 from master

fdbrpc/simulator.h, fdbserver/Coordination.actor.cpp, fdbserver/SimulatedCluster.actor.cpp, fdbserver/workloads/ChangeConfig.actor.cpp
These are the fixes @etschannen did on master to resolve test start up timeout issue (e.g., SwizzledRollbackSideband.txt).
100K tests all passed:
20210405-191834-zhewu_4619-896e44cecce881c0        compressed=True data_size=20344237 duration=5810848 ended=108614 fail_fast=10 max_runs=100000 pass=100001 priority=100 remaining=0 runtime=0:28:55 sanity=False started=108637 stopped=20210405-194729 submitted=20210405-191834 timeout=5400 username=zhewu_4619
=> Cherry pick #4596 and #4599 into release-6.3

build/docker/centos6/build/Dockerfile, build/docker/centos6/devel/Dockerfile, build/docker/centos7/build/Dockerfile, build/docker/centos7/devel/Dockerfile, tests/CMakeLists.txt
CI build was not able to test upgrade/downgrade
- add old fdb binaries to build image and update cmake to look in the right place
Testing CI failures was cumbersome and involved inspecting buildspec files
- add new alias `cmk_ci` to devel image so CI style builds can be performed by engineers 
The TLS lib install uses non-intuitive path
- update FDBTLS lib install for joshua
- remove old fdb binaries install from devel -- moved to build image
The joshua install steps in the devel docker file reference a non-existent git branch
- get the default fdb-joshua branch when building the devel image
- [✅] The PR has a description, explaining both the problem and the solution.
- [✅] The description mentions which forms of testing were done and the testing seems reasonable.
- [✅] Every …
=> Docker image updates

fdbclient/DatabaseConfiguration.h, fdbserver/Status.actor.cpp
We need to cherry pick #4515 (which updates fault tolerance field) in release-6.3, and included in release 6.3.12.
No failures in 100K joshua test
20210408-205825-zhewu_4634-9a0a693c1c282e38        compressed=True data_size=20343759 duration=5205258 ended=107372 fail_fast=10 max_runs=100000 pass=100002 priority=100 remaining=0 runtime=0:26:18 sanity=False started=107714 stopped=20210408-212443 submitted=20210408-205825 timeout=5400 username=zhewu_4634
=> Cherry pick #4515 into release-6.3: populate min_replicas_remaining fields in the cluster status for all regions.

build/docker/centos7/build/Dockerfile
Update to the latest valgrind, and install the headers in a more standard location than devtoolset 8 did. We need the updated valgrind so that we work smoothly with clang 11 - see https://www.valgrind.org/docs/manual/dist.news.html. We were seeing false positives with clang 11 and older versions of valgrind. After this change, `cmake -DUSE_VALGRIND=ON` succeeds again.
=> Add valgrind to foundationdb/build image

bindings/java/src/junit/com/apple/foundationdb/tuple/ByteArrayUtilTest.java, bindings/java/src/main/com/apple/foundationdb/tuple/ByteArrayUtil.java, bindings/java/src/tests.cmake
String.format can be potentially expensive, and if using `printable()` within a hot loop that can be a performance penalty. Admittedly, it doesn't seem like a good idea to call printable() from within a hot loop, but if you have to, it's good for it to perform well.
This removes the `String.format` call and replaces it with a simple char lookup table. Also adds a test file to check that it does what the javadoc says it does.
=> Removing String.format from ByteArrayUtil.printable.

documentation/sphinx/source/release-notes/release-notes-630.rst, fdbserver/Status.actor.cpp
Cherry-pick of PR #4454.
This bug is has showed up in production enough times, hence should be cherry-picked into 6.3.
=> Cherry-pick #4454 status: Ignore LogSets with no tLogs when computing FT

fdbclient/FileBackupAgent.actor.cpp, fdbclient/Knobs.cpp, fdbclient/Knobs.h
#4565 completely ignores log files. We should make it a knob and get it merged. The knob should be disabled at all times, thus not affecting existing code. The knob should only be enabled when we know the restored data are inconsistent and still want to do so.
Joshua test:
20210408-180848-renxuan-823f2ad63aaee7d5           compressed=True data_size=20342970 duration=4738393 ended=106564 fail_fast=10 max_runs=100000 pass=100001 priority=100 remaining=0 runtime=0:26:24 sanity=False started=107427 stopped=20210408-183512 submitted=20210408-180848 timeout=5400 username=renxuan
If this PR is …
=> Cherry pick #4625 to release-6.3

documentation/sphinx/source/api-common.rst.inc
This is a small documentation change adding information about the endianness of serialized versionstamps. Currently this info is missing from the C, Python, and Ruby APIs. The Java documentation contains endianness info for versionstamps (see https://apple.github.io/foundationdb/javadoc/com/apple/foundationdb/MutationType.html#SET_VERSIONSTAMPED_KEY), as does the Go documentation (https://pkg.go.dev/github.com/apple/foundationdb/bindings/go/src/fdb?utm_source=godoc#Transaction.SetVersionstampedKey).
This PR is a low risk change (documentation change only) and would help developers using the API as a reference when using versionstamps. For example, I spent more than a few hours recently debugging why my versions were incorrect because the C API did not state versionstamps are written in …
=> Add versionstamp serialization endianness to API documentation

contrib/monitoring/fdb_c_version.py
The tool will check  the version of `libfdb_c.so` file. 
@ajbeamon  is the original author. We put it here to make it available to community. 
I tested by running it on my local machine:
`python fdb_c_version.py /usr/lib64/libfdb_c.so`
=> Add python tool to get client version

documentation/sphinx/source/release-notes/release-notes-630.rst, fdbclient/FileBackupAgent.actor.cpp, fdbclient/Knobs.cpp, fdbclient/Knobs.h, fdbserver/Status.actor.cpp
After these two PRs were merged last Friday, correctness showed new failures in *Status related tests. 
Example: rare/LargeApiCorrectnessStatus.txt,  buggify=on, random seed=937634288. 
Reverted PRs:
PR#4630
PR#4536
After reverting these two PRs, correctness only found timeout in `BackupCorrectnessClean.txt` and longer latency in`LowLatency.txt` tests.  
Correctness results after reverting both PRs:
20210411-023744-mengxu6312revert4536and4630-ebdb6138e4e51117 compressed=True data_size=21126684 duration=22733959 ended=408169 fail=5 fail_fast=5 max_runs=400000 pass=398177 priority=100 remaining=0 runtime=0:56:31 sanity=False started=408486 stopped=20210411-033415 submitted=20210411-023744 timeout=5400 username=mengxu6312revert4536and4630 …
=> Revert PR#4630 and PR#4536 on release-6.3

contrib/monitoring/fdb_c_version.py
These are some changes to fix issues with the recently added fdb_c_version.py.
* Support Python 3 and make it the default
* Use `str(e)` instead of `e.message` to print errors (some errors don't have a `message` field.
* Don't convert `library_path` to an absolute path so that we can load the system fdb_c.
I tested each of these cases manually. This should have no impact on other code.
=> Some cleanup of fdb_c_version.py

bindings/java/fdbJNI.cpp, bindings/java/src/main/com/apple/foundationdb/Database.java, bindings/java/src/main/com/apple/foundationdb/FDBDatabase.java, bindings/java/src/test/com/apple/foundationdb/test/AsyncStackTester.java
This PR adds Java support for calling the network busyness API which was implemented in #4504 
Passed 10k joshua runs for bindingtester.
=> Network Busyness Java API

packaging/docker/create_server_environment.bash, packaging/docker/fdb.bash
This PR resolves #4484
- Make use of `hostname -i`  and use only the first IP address
=> Use only one IP address that matches the hostname

fdbclient/NativeAPI.actor.cpp, fdbserver/CommitProxyServer.actor.cpp, fdbserver/DiskQueue.actor.cpp, fdbserver/Ratekeeper.actor.cpp, fdbserver/masterserver.actor.cpp
The code coverage tool requires a comment to exist on the same line as the associated `TEST` macro. As a result, we had some cases where the line length exceeded the desired 120 characters. Leaving these lines too long makes things complicated for anybody using tools that automatically format their files, as these lines have to be repeatedly fixed.
This change updates the macros to reduce the comment length and/or extract the `TEST` condition to a separate variable.
Because this is mostly a formatting change, I did not seek to understand what was going on in the affected functions and therefore I did not add any documentation to those functions.
This passed 10K correctness tests. Because it doesn't change logic at all, I haven't run more than that. …
=> Fix line length of test macro + comments to be within the 120 character limit

fdbbackup/BackupTLSConfig.cpp, fdbbackup/BackupTLSConfig.h, fdbbackup/CMakeLists.txt, fdbbackup/FileConverter.h, fdbbackup/FileDecoder.actor.cpp, fdbbackup/backup.actor.cpp
Update description for `fdbdecode` and add TLS support so that it can directly read mutation log files from blob.
This is manually tested, e.g.,
`./fdbdecode --tls_certificate_file fullchain.pem --tls_ca_file fdb_root_ca_file.pem --tls_key_file private.key --blob_credentials blob.json -r 'blobstore://userid@blob.xxx.com/container_path/' -i 13263697214954,13263717214954`
`./fdbdecode -r 'blobstore://userid@blob.xxx.com/container_path/?sc=0' --blob_credentials blob.json -i 13263697214954,13263717214954`
=> Add TLS support to fdbdecode

fdbrpc/Locality.cpp, fdbserver/ClusterController.actor.cpp
tlog recruitment used a degraded LogClass process over a non-degraded TransactionClass process.
tlog recruitment would not use TransactionClass processes if it fulfulled the required amount with LogClass processes.
Better master exists did not account for how many times a process had been used when comparing recruitments.
Better master exists did not account for the fact that tlogs prefer to be in a different dc than the cluster controller.
RoleFitness comparison did not properly order count before degraded or bestFit.
betterCount was returning worstFit when worstIsDegraded did not match.
backupWorker recruitment did not attempt to avoid sharing processes with other roles.
If any of the commit_proxy, grv_proxy, or resolver are forced to share a process, allow the recruitment for all of …
=> Fixed 8 bugs related to recruitment of processes by the cluster controller

fdbclient/NativeAPI.actor.cpp
A recent PR #4649 attempted to change a line, but accidentally ended up committing an extra line rather than replacing it. This removes the line that was supposed to have been changed.
=> Remove extra line caused by commit issue

bindings/c/fdb_c.cpp, bindings/c/foundationdb/fdb_c.h, bindings/c/test/unit/unit_tests.cpp, fdbclient/IClientApi.h, fdbclient/MultiVersionTransaction.actor.cpp, fdbclient/MultiVersionTransaction.h, fdbclient/NativeAPI.actor.cpp, fdbclient/NativeAPI.actor.h, fdbclient/ThreadSafeTransaction.cpp, fdbclient/ThreadSafeTransaction.h
`fdb_get_server_protocol` is a function that has been added on master, and I'd like to get it into a state where we are happy with the API before we cut 7.0.
This makes the following changes:
1. `fdb_get_server_protocol` is moved to operate on the database (`fdb_database_get_server_protocol`) and no longer needs to take a cluster file argument.
2. `fdb_database_get_server_protocol` takes an argument for the expected protocol version and won't return unless the version is different. Passing a protocol version of 0 disables this feature. The purpose of this change is that it will allow the multi-version client to call this function on the active client and wait for the version to change without having to continuously poll the external client or connect to the database itself.
To test this, …
=> Some changes to how fdb_get_server_protocol works

fdbcli/fdbcli.actor.cpp, fdbclient/CMakeLists.txt, fdbclient/CommitProxyInterface.h, fdbclient/GlobalConfig.actor.cpp, fdbclient/GlobalConfig.actor.h, fdbclient/GlobalConfig.h, fdbclient/NativeAPI.actor.cpp, fdbclient/SpecialKeySpace.actor.cpp, fdbclient/SpecialKeySpace.actor.h, fdbclient/SystemData.cpp, fdbclient/SystemData.h, fdbclient/Tuple.cpp, fdbclient/Tuple.h, fdbserver/ClusterController.actor.cpp, fdbserver/workloads/ClientTransactionProfileCorrectness.actor.cpp, fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp, flow/network.h
This PR introduces an implementation of the global configuration framework, designed by @sfc-gh-mpilman.
Design doc: https://docs.google.com/document/d/1kye2aHHkwvg3Ze-aldeHO9BprWkfLmldG88DuvHbWAs/edit#
The global configuration framework is an eventually consistent configuration mechanism to efficiently make runtime changes to all clients and servers. It works by only broadcasting changes made to the configuration, allowing the amount of data broadcast to nodes to be small. Nodes that fall behind can catch up by reading the `\xff/globalConfig/k/ - \xff/globalConfig/k0` key range.
If this …
=> Add global configuration framework implementation

fdbrpc/AsyncFileNonDurable.actor.h, flow/Knobs.cpp, flow/Knobs.h
Cherry-pick #4653 to release-6.3.
Simulation run `20210414-062218-satherton_pr4655-caf14c59939dac44`, 0 failures out of 100k.
CI failures are due to `ctest` not running restart tests properly.
=> Simulation write delay fix cherry-picked to release-6.3

fdbserver/SimulatedCluster.actor.cpp, fdbserver/TesterInterface.actor.h, fdbserver/tester.actor.cpp, tests/fast/MoveKeysCycle.txt
6.3 Port of https://github.com/apple/foundationdb/pull/4628. The changes are not a direct copy from the master branch because the test parsing code is slightly different on 6.3. Otherwise, the functions changed are the same. This change is required to support downgrade testing from 6.3 to 6.2.
=> Added extra options to test config that specify maxtlogversion and array of excluded storage engine types (6.3 port)

fdbserver/ClusterController.actor.cpp
20210409-195037-renxuan-2cb367f8e931f72d           compressed=True data_size=22960013 duration=3822881 ended=106733 fail=2 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:22:41 sanity=False started=106764 stopped=20210409-201318 submitted=20210409-195037 timeout=5400 username=renxuan
The failed tests are unrelated Operation timed out.
=> Log a warning when remote dc is disabled (priority < 0)

CONTRIBUTING.md
Just adds link to [FoundationDB Commit Process](https://github.com/apple/foundationdb/wiki/FoundationDB-Commit-Process) in our `CONTRIBUTING.md` document.
=> doc: Link FDB Commit Process doc in CONTRIBUTING.md

build/docker/centos6/devel/Dockerfile, build/docker/centos7/devel/Dockerfile
This will check if there is a `.bashrc.local` available in the synced directory,
and load it.
- This is useful so that any changes users make to `bashrc` in Okteto containers
doesn't get lost between re-deployement of containers.
- Can also used to automate setting up environment, e.g. copy various dotfiles
etc from the synced directory to $HOME folder during first run.
=> docker: Load custom `bashrc` if available

bindings/c/test/unit/unit_tests.cpp, bindings/python/fdb/__init__.py, bindings/python/fdb/impl.py
This function was moved and changed in the C API as part of #4662, so it no longer functions correctly in the Python bindings. The implementation of these in the bindings is incomplete (no documentation or testing, Python only), so rather than complete them now I'm removing it and deferring that task to later if we decide we want it.
This also renames a unit test for accuracy.
This passed 10K binding tester runs.
=> Remove get_server_protocol from the Python bindings

fdbclient/SpecialKeySpace.actor.cpp
The `version` field was uninitialized.
=> Fix uninitialized field in global configuration

fdbrpc/AsyncFileNonDurable.actor.h, flow/Knobs.cpp, flow/Knobs.h
Until now, in simulation all disk writes can take up to 5 seconds.  This causes simulations with low log system commit pipeline depth to advance versions at a very slow rate.  This causes some tests, especially backup/restore tests which use version as a proxy for time, to not complete within the sim time test duration limit.
Passed 100k correctness `20210414-062253-satherton_pr4656-cbaddeac8c3ded72` with 7 failures, possibly some new ones.
=> Correctness fix:  Prevent writes from being too slow in simulation

fdbclient/vexillographer/fdb.options
This will ultimately get plumbed to the javadocs. Apparently the python docs already mention something about this. Ping #2070.
=> Document that ryw disable can only be set at beginning of transaction

fdbserver/StorageCache.actor.cpp, fdbserver/storageserver.actor.cpp
canReplyWith was declared inline in two translation units with different
definitions. When building with clang, this resulted in
storageserver.actor.cpp using the definition from
StorageCache.actor.cpp. Fix that by giving both symbols internal
linkage.
For testing, I observed that `canReplyWith(watch_cancelled())` called in storageserver.actor.cpp returned false before my change and true after. I will follow up with the results of 10k simulation runs.
=> Fix multiple (inline) definitions of canReplyWith

fdbclient/FileBackupAgent.actor.cpp, fdbclient/Knobs.cpp, fdbclient/Knobs.h
This reverts commit 6bd58753821180401d816af4540a87804d66d6ca.
20210419-215334-renxuan-04448872632c1f46           compressed=True data_size=21129626 duration=3916245 ended=106509 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:27:51 sanity=False started=106657 stopped=20210419-222125 submitted=20210419-215334 timeout=5400 username=renxuan
=> Revert "Revert "Merge pull request #4630 from RenxuanW/release-6.3""

fdbserver/CMakeLists.txt, fdbserver/masterserver.actor.cpp, fdbserver/ptxn/test/Driver.actor.cpp, fdbserver/ptxn/test/Driver.h, fdbserver/ptxn/test/FakeResolver.actor.h, tests/CMakeLists.txt, tests/ptxn/Resolver.toml
Fake a resolver in the unit test for testing. I manually ran the new unit test and it works.
The CI failure is not related restart test failures.
=> Add Resolver role to unit test

documentation/sphinx/source/client-testing.rst
See #4686
The Client Testing document https://apple.github.io/foundationdb/client-testing.html demands to run a simulator by launching fdbserver with simulator role. But such role doesn't exist
[oleg@fdbs ~]$ fdbserver -r simulator -f /mnt/host/root/home/oleg/work/fdb/FoundationDb/tests/fast/AtomicBackupCorrectness.txt
ERROR: Unknown role simulator' Try fdbserver --help' for more information.
The right role name is simulation, not simulator.
=> Fixed Typo in the Client Testing document

documentation/sphinx/source/client-testing.rst
See #4686
The Client Testing document https://apple.github.io/foundationdb/client-testing.html demands to run a simulator by launching fdbserver with simulator role. But such role doesn't exist
[oleg@fdbs ~]$ fdbserver -r simulator -f /mnt/host/root/home/oleg/work/fdb/FoundationDb/tests/fast/AtomicBackupCorrectness.txt
ERROR: Unknown role simulator' Try fdbserver --help' for more information.
The right role name is simulation, not simulator.
=> Fixed Typo in the Client Testing documentation (6.3)

build/docker/centos6/build/Dockerfile, build/docker/centos7/build/Dockerfile
add redhat-lsb-core to build images
cpack uses lsb_release
=> add redhat-lsb-core to build images -- cpack uses lsb_release

fdbclient/BackupAgentBase.actor.cpp, fdbclient/DatabaseBackupAgent.actor.cpp, fdbserver/workloads/BackupToDBCorrectness.actor.cpp
Fixes a conditional that was potentially causing data copying to stop early during DR backup.
Background:
* Disaster recovery is a special form of backup that backs up one FDB database to another FDB database. Read more about it at https://apple.github.io/foundationdb/backups.html.
* DR locks the destination database during a backup to ensure consistency, and therefore needs to know when the backup has completed in order to unlock the database.
* The current check used to determine if the backup is complete checks whether the version of the latest applied mutation is greater than or equal to the "stop version", or what version the backup should end at. Instead, the check should be made against `applyVersion`, which determines which versions have actually been applied.
* The potential …
=> Fix early cutoff when DR copies logs

fdbclient/FileBackupAgent.actor.cpp, fdbserver/workloads/BackupCorrectness.actor.cpp, tests/fast/BackupCorrectnessClean.toml
- BackupCorrectness workload would sometimes generate an empty restore target range set.  This would cause the test to time out because restore() would still queue the job, but then during execution the restore tasks would repeatedly fail because the restore range set is empty.  BackupCorrectness should no longer generate empty restore ranges, but just in case restore() will now throw an error if the target ranges are empty which will cause a much faster failure.  
- Restore start was not properly checking restore target ranges against the remove prefix option.
- Some code clarity changes.
Passed 30k runs of only BackupCorrectness and BackupCorrectnessClean.  Code changes are restricted to BackupCorrectness and restore().
Passed 20k runs of all correctness tests.  I think CI just got …
=> Restore target range handling bug fixes

documentation/sphinx/source/mr-status-json-schemas.rst.inc, fdbclient/Schemas.cpp, fdbserver/GrvProxyServer.actor.cpp, fdbserver/Status.actor.cpp, fdbserver/storageserver.actor.cpp
Add GRVLatencyMetrics for batched transactions.
(See also Capture and report latency statistics for server-side requests #3480)
Tested by submitting batched transactions and observing in logs the metrics were recorded.
Ran in simulation (joshua) and confirmed no new failures.
=> Log latency metrics for batch GRV requests

fdbclient/FileBackupAgent.actor.cpp
#4665
Joshua:
20210421-165643-renxuan-7636213d919cec01           compressed=True data_size=21135262 duration=5625605 ended=105506 fail_fast=10 max_runs=100000 pass=100001 priority=100 remaining=0 runtime=0:28:01 sanity=False started=108319 stopped=20210421-172444 submitted=20210421-165643 timeout=5400 username=renxuan
Simulation:
```
Snapshot:  startVersion=483371170 (1970/01/01.00:02:16+0000)  endVersion=495275616 (1970/01/01.00:02:28+0000)  totalBytes=1200239  restorable=true  expiredPct=0.00
SnapshotBytes: 1200239
MinLogBeginVersion:      478036592 (1970/01/01.00:02:11+0000)
ContiguousLogEndVersion: 518036592 (1970/01/01.00:02:48+0000)
MaxLogEndVersion:        518036592 (1970/01/01.00:02:48+0000)
MinRestorableVersion:    495275616 (1970/01/01.00:02:28+0000)
MaxRestorableVersion: …
```
=> Cherrypick #4665 to 6.3.

fdbserver/storageserver.actor.cpp
This PR adds a dependency between the KVS response arena and the GetKeyValuesReply arena instead of explicitly copying all of the KVS responses into the reply. In my mako tests, it seemed like this improved the range read throughput by 1-2%.
=> Remove unnecessary copy of KVS entries into range read response

fdbserver/ptxn/test/Driver.actor.cpp, fdbserver/ptxn/test/Driver.h, flow/UnitTest.cpp, tests/ptxn/Driver.toml
This patch depends on #4617.
The PTXN Driver test is configurable via the Driver.toml, as illustrated
in this commit.
=> Make PTXN Driver test configurable

fdbserver/CMakeLists.txt, fdbserver/ptxn/test/Driver.actor.cpp, fdbserver/ptxn/test/Driver.h, fdbserver/ptxn/test/TestResolver.actor.cpp
Add a simple test that sends several empty batches of transactions to a Resolver.
Manually tested the unit test.
=> Add resolver unit tests

documentation/sphinx/source/backups.rst, fdbbackup/backup.actor.cpp, fdbclient/BackupAgent.actor.h, fdbclient/FileBackupAgent.actor.cpp, fdbclient/Knobs.cpp, fdbclient/Knobs.h, fdbserver/workloads/IncrementalBackup.actor.cpp
20210422-211800-renxuan-d4c3be87bdd030d5           compressed=True data_size=23019146 duration=3901759 ended=102985 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:23:13 sanity=False started=106072 stopped=20210422-214113 submitted=20210422-211800 timeout=5400 username=renxuan
=> Implement restoring an inconsistent snapshot as a real feature.

fdbclient/Knobs.cpp, fdbserver/MoveKeys.actor.cpp, tests/CMakeLists.txt, tests/restarting/to_6.3.10/CycleTestRestart-1.txt, tests/restarting/to_6.3.10/CycleTestRestart-2.txt
Reverts apple/foundationdb#4469 due to nightly correctness failures in `20210423-044228-nightly_correctness_release-6.3-0daa283027479e7c`
=> Revert "Changed code flow to fix loophole that avoided the knob guarding higher protocol versions"

documentation/sphinx/source/mr-status-json-schemas.rst.inc, fdbclient/Schemas.cpp, fdbrpc/Locality.h, fdbrpc/ReplicationPolicy.h, fdbserver/ClusterController.actor.cpp, fdbserver/SimulatedCluster.actor.cpp, fdbserver/WorkerInterface.actor.h, fdbserver/workloads/LowLatency.actor.cpp, flow/Knobs.cpp
The goal of this rewrite is to prevent better master exists from triggering spuriously because tlogs randomly get located on different processes each time the function is called.
Changing the recruitment logic also has the benefit that now the cluster controller will ensure Log class processes are recruited before Transaction class processes.
Passed: 934930
Failed: 10
Failing tests:
RandomSeed="994272039" BuggifyEnabled="1" TestFile="tests/slow/SwizzledCycleTest.toml" 
TooManyFiles
RandomSeed="325685976" BuggifyEnabled="1" TestFile="tests/slow/FastTriggeredWatches.toml" 
Test timed out
RandomSeed="58742398" BuggifyEnabled="1" TestFile="tests/fast/SwizzledRollbackSideband.toml" 
Error starting workload
JoshuaMessage Severity="40" Error="JoshuaTimeout" TimeoutCommandRun="true" …
=> rewrote tlog recruitment logic so that it is deterministic

fdbclient/MultiVersionTransaction.actor.cpp, flow/FastRef.h, flowbench/BenchRef.cpp, tests/CMakeLists.txt
Add some existing thread safety tests to ctest, so that if you build with -DUSE_TSAN=ON and run ctest, then these tests are also run.
Also change the implementation of ThreadSafeReferenceCounted so that the usage of debugGetReferenceCount in tests is thread safe.
Testing was done by running the /fdbclient/multiversionclient/ tests under TSAN, and also a small benchmark consisting of calling addref and delref in a loop in several threads shows this does not degrade performance on x86 or ARM.
=> Add /fdbclient/multiversionclient/ to ctest, and fix thread safety

cmake/InstallLayout.cmake
Also remove the unused legacy mapping for install dirs
For testing I installed the generated debian package in an ubuntu docker image. Closes #4726 (Well it will after cherry picking to 6.3)
=> Fix the data dir for DEB and EL7 to be /usr/lib/foundationdb/data

fdbclient/FileBackupAgent.actor.cpp
First consistent version should be:
- In a logs-only restore, it is the begin version the user said to start applying logs for;
- In an inconsistent-snapshot-only restore, if all range files have the same version, then it is that version, otherwise unknown (use -1);
- If using both range files and logs, then it is the highest version of any range file in the RestoreSet’s ranges vector.
20210427-174013-renxuan-1a165fca54229c68           compressed=True data_size=23062686 duration=4813312 ended=107542 fail=2 fail_fast=10 max_runs=100000 pass=99998 priority=100 remaining=0 runtime=0:29:40 sanity=False started=107547 stopped=20210427-180953 submitted=20210427-174013 timeout=5400 username=renxuan
The general guidelines can be found [here](https://github.com/apple/foundationdb/wiki/FoundationDB- …
=> Fix the logic of getting firstConsistentVersion.

fdbclient/Schemas.cpp, fdbserver/Status.actor.cpp
Changes:
Schemas.cpp:
- Extend JSON schema to include aggregated information about
CommitBatchingWindowSize samples.
Status.actor.cpp:
- Extend getStorageServersAndMetrics() to gather metrics about
CommitBatchingWindowSize.
- Extend CommitProxy AddRole() to populate the status-JSON object
with the metrics about CommitBatchingWindowSize.
Testing:
- Ran simulated tests. There were some failures, a couple of them (restarting/from_7.0.0/ConfigureTestRestart-1.txt and restarting/from_7.0.0/ConfigureTestRestart-2.txt) are known to have failed on Snowflake nightly tests too, I don't know the status of the other failures.
- Manual testing: Started a FoundationDB cluster and verified that commitBatchingWindowSize is getting populated in the "status json" output:
{
"commit_batching_window_size" : { …
=> Expose CommitBatchingWindowSize metric to fdbcli status

fdbclient/MultiVersionTransaction.actor.cpp, fdbclient/MultiVersionTransaction.h
Destruction of the thread futures for the protocol version monitors does not cancel the monitors. This explicitly calls cancel on the thread futures, which cancel the underlying activity.
This also fixes some issues that arose when the future returned a cancellation error.
- Passed 10K correctness tests
- Passed fdb_c_unit_tests
- Passed 10K binding tester runs
- Passed multithreaded_client.py tests
This also passed the same tests run in #4667.
=> Fix: explicitly cancel MVC thread futures for version monitors

fdbserver/ClusterController.actor.cpp, flow/Error.cpp, flow/Error.h, flow/Trace.cpp, flow/Trace.h
This resolves https://github.com/apple/foundationdb/issues/4442. We want to maintain the current definition of a `SevError` event, while also providing an additional field for all `SevError` events to provide more context, in order to determine which `SevError` events are worth alerting on. Currently, there are three error kinds: `Unset`, `DiskIssue`, and `BugDetected`, but this can be expanded in the future. `BugDetected` `SevError` events should be addressed more urgently than other `SevError` events.
=> Add ErrorKind field to Severity 40 traces

fdbrpc/LoadBalance.actor.h
This is a backport of #4561 being done to fix a performance regression that impacts 6.3 clusters.
Between FDB 3 and FDB 6, load balancing got more expensive, causing a reduction in client throughput. This seems to be largely because an extra actor was added to the call stack in FDB 6.
This PR refactors load balancing to remove the makeRequest actor in an attempt to recapture that lost performance.
This has been tested with a few synthetic performance workloads, and the results demonstrated that the performance of this code is almost as good as the FDB 3 load balancing (75+% of the gap has closed) without removing any of the new logic.
Correctness passed 100K tests.
Please …
=> Improve load balancing performance (release-6.3)

fdbclient/RYWIterator.cpp, fdbclient/RYWIterator.h, fdbclient/ReadYourWrites.actor.cpp, fdbclient/ReadYourWrites.h, fdbclient/SnapshotCache.h, fdbclient/vexillographer/fdb.options, fdbserver/workloads/Unreadable.actor.cpp
The main use case for this option is to read your writes for incomplete SetVersionstampValue atomic operations.
4 failures out of 200k, none of them are new.
=> Added a new option to bypass unreadable protection in read your writes for calls to get

fdbclient/Knobs.cpp, fdbserver/MoveKeys.actor.cpp, tests/CMakeLists.txt, tests/restarting/to_6.2.33/CycleTestRestart-1.txt, tests/restarting/to_6.2.33/CycleTestRestart-2.txt
Reverts apple/foundationdb#4707
Updated the 6.2 binary from https://github.com/apple/foundationdb/pull/4673 to account for a comparison mismatch for certain 6.3 version protocols. No changes made on 6.3. Awaiting testing results for confirmation.
=> Revert "Revert "Changed code flow to fix loophole that avoided the knob guarding higher protocol versions""
