apple/foundationdb

- FDBLibTLS/FDBLibTLSPlugin.cpp
- FDBLibTLS/FDBLibTLSPlugin.h
- FDBLibTLS/FDBLibTLSPolicy.cpp
- FDBLibTLS/FDBLibTLSPolicy.h
- FDBLibTLS/FDBLibTLSSession.cpp
- FDBLibTLS/FDBLibTLSSession.h
- FDBLibTLS/ITLSPlugin.h
- FDBLibTLS/ReferenceCounted.h
- FDBLibTLS/plugin-test.cpp
- FDBLibTLS/scripts/make-test-certs.sh
- FDBLibTLS/verify-test.cpp
Adds appropriate header files for our project to the files within the FDBLibTLS directory.
> fix headers of FDBLibTLS files

- documentation/sphinx/source/class-scheduling.rst
The available_classes function is using Subspace.unpack to
obtain the tuple, not fdb.tuple so update the description to
reflect this.
The limited seat tutorial section was missing the code and
text describing the update of the drop function.
> Fixups for python tutorial documentation

- packaging/msi/FDBInstaller.wxs
Modified Windows installer to comply with initial dialog requirements
> Windows Installer Modified

- documentation/sphinx/source/api-python.rst
- documentation/sphinx/source/class-scheduling.rst
Fixes docs to make sure they run on Python 3
Fixes #245
> Make docs Python 3 compatible

- documentation/sphinx/source/class-scheduling.rst
There have been two updates to the class scheduling tutorial that landed on master. This is to cherry pick them to release-5.1.
> Cherrypick updates to class scheduling tutorial

- fdbclient/BackupAgent.h
- fdbclient/BackupAgentBase.actor.cpp
- fdbclient/DatabaseBackupAgent.actor.cpp
- fdbserver/SimulatedCluster.actor.cpp
- fdbserver/workloads/BackupToDBUpgrade.actor.cpp
- tests/restarting/from_5.1.7/DrUpgradeRestart-1.txt
- tests/restarting/from_5.1.7/DrUpgradeRestart-2.txt
Add some TaskFunc to support DR upgrade
> Upgrade DR from 5.1 to 5.2

- build/packages.mk
Added TLS target to packages target
> Added target for building TLS plugin

- fdbclient/FileBackupAgent.actor.cpp
In order to support backup/DR upgrade in 5.2. We need to map all existing backup tasks to abortBackupTask
> Abort 5.1 backup for 5.2 upgrade

- FDBLibTLS/local.mk
- build/packages.mk
- documentation/sphinx/source/tls.rst
- fdbrpc/TLSConnection.actor.cpp
Changed the name of the TLS artifact to fdb-libressl-plugin.so
> TLS Artifact Name Change

- fdbrpc/BlobStore.actor.cpp
- fdbrpc/BlobStore.h
Default is https. Setting secure_connection=0 makes it http.
> Add secure_connection param to BlobStore to configure security.

- documentation/sphinx/source/downloads.rst
- documentation/sphinx/source/old-release-notes/release-notes-510.rst
- flow/Net2.actor.cpp
- packaging/msi/FDBInstaller.wxs
Updated version within download documentation
Added old release notes
Updated Wix GUID Product ID
> Updated Protocol Version

- fdbclient/MultiVersionAssignmentVars.h
- fdbclient/NativeAPI.actor.cpp
- fdbrpc/AsyncFileCached.actor.cpp
- fdbrpc/AsyncFileCached.actor.h
- fdbserver/TLogServer.actor.cpp
- fdbserver/VFSAsync.cpp
- flow/IThreadPool.cpp
Clone of #234 with smallest subset of changes needed to fix the build.
> Fix for 5.1 OSX build.

- bindings/java/pom.xml.in
> Modified the groupId to org.foundationdb

- fdbserver/TLogServer.actor.cpp
I didn't rename every variable here, because some appear to be data structures (like a map) following the pattern keydesc_valuedesc, and I wasn't sure that the straightforward keydescValuedesc rename made sense. I did rename a couple of instances of these where it seemed reasonable, though.
> Rename several variables in TLogServer.actor.cpp to follow our normal camel case conventions.

- fdbclient/BackupAgentBase.actor.cpp
- fdbclient/ClientLogEvents.h
- fdbclient/DatabaseBackupAgent.actor.cpp
- fdbclient/FileBackupAgent.actor.cpp
- fdbclient/NativeAPI.actor.cpp
- fdbrpc/Platform.cpp
- fdbserver/KeyValueStoreSQLite.actor.cpp
- fdbserver/LogSystem.h
- fdbserver/OldTLogServer.actor.cpp
- fdbserver/SimulatedCluster.actor.cpp
- fdbserver/Status.actor.cpp
- fdbserver/VFSAsync.cpp
- fdbserver/WaitFailure.actor.cpp
- fdbserver/fdbserver.actor.cpp
- fdbserver/storageserver.actor.cpp
- fdbserver/worker.actor.cpp
- fdbserver/workloads/DDMetrics.actor.cpp
- fdbserver/workloads/Performance.actor.cpp
- fdbserver/workloads/StatusWorkload.actor.cpp
- fdbserver/workloads/TaskBucketCorrectness.actor.cpp
- fdbserver/workloads/WatchAndWait.actor.cpp
- flow/AsioReactor.h
- flow/DeterministicRandom.h
- flow/Net2.actor.cpp
- flow/Platform.cpp
- flow/SystemMonitor.cpp
- flow/ThreadHelper.actor.h
- flow/Trace.cpp
Also relaxed the rules about Types to allow multiple underscores, leading underscores, and consecutive underscores.
> Some more trace event normalization

- documentation/sphinx/source/administration.rst
- documentation/sphinx/source/index.rst
> Add administration and TLS sections to the site map.

- fdbrpc/Locality.cpp
- fdbrpc/Locality.h
- fdbserver/ClusterController.actor.cpp
- fdbserver/ClusterRecruitmentInterface.h
- fdbserver/LogRouter.actor.cpp
- fdbserver/OldTLogServer.actor.cpp
- fdbserver/RecoveryState.h
- fdbserver/ServerDBInfo.h
- fdbserver/TLogServer.actor.cpp
- fdbserver/masterserver.actor.cpp
- flow/genericactors.actor.h
These are a few patches I had from when I was reviewing one of the remote logs merges.
There's no particular theme, other than things that bothered me but didn't seem actually troublesome enough to warrant asking you to fix.
> Feature remotelogs improvements

- FDBLibTLS/FDBLibTLSVerify.cpp
This patch allows specifying UID and DC fields in verify peers strings
> Tls additional subject fields

- build/csprojtom4.py
- build/vcxprojtom4.py
added import for print_function, changed all occurences of print to a function to enable make to run under Py2 and Py3.
> Fix for issue #491 - added import for print_function

- flow/Trace.cpp
The log group field was not being properly set.
> The Machine field was missing in early trace events.

- versions.target
This bumps the version on the master branch to 6.1. All future work on 6.0 should go on the release-6.0 branch.
> Bump version to 6.1

- documentation/sphinx/source/release-notes.rst
Fixed a typo, added two items.
> Updated release notes for 5.2.6.

- fdbrpc/BlobStore.actor.cpp
Added log event detail for whether or not a connection was established.  When throwing an error on failure, differentiate between a timeout in attempting to connect vs a timeout on an active connection by converting timeouts during connection attempts to connection_failed errors.  Also stops converting dns lookup errors to the less specific http_failed_request.
> More backup error improvements

- documentation/sphinx/source/administration.rst
- documentation/sphinx/source/downloads.rst
- documentation/sphinx/source/release-notes.rst
- packaging/msi/FDBInstaller.wxs
- versions.target
Updates the relevant links and documentation for the 6.0.1 release.
> Prepare 6.0.1 Release

- FDBLibTLS/FDBLibTLSPlugin.cpp
- FDBLibTLS/FDBLibTLSPlugin.h
- FDBLibTLS/FDBLibTLSPolicy.cpp
- FDBLibTLS/FDBLibTLSPolicy.h
- FDBLibTLS/FDBLibTLSSession.cpp
- FDBLibTLS/FDBLibTLSSession.h
- FDBLibTLS/Makefile
- FDBLibTLS/local.mk
- FDBLibTLS/plugin-test.cpp
- fdbrpc/ITLSPlugin.h
- fdbrpc/TLSConnection.actor.cpp
> Replaced separate TLS Log function with FDB TraceEvent logger

- fdbclient/ReadYourWrites.actor.cpp
- fdbrpc/ReplicationPolicy.cpp
- fdbrpc/sim2.actor.cpp
- fdbserver/ClusterController.actor.cpp
- fdbserver/DataDistribution.actor.cpp
- fdbserver/DataDistributionQueue.actor.cpp
- fdbserver/MoveKeys.actor.cpp
- fdbserver/storageserver.actor.cpp
- fdbserver/workloads/MemoryKeyValueStore.cpp
- fdbserver/workloads/RemoveServersSafely.actor.cpp
- flow/IRandom.h
- flow/Util.h
- flow/genericactors.actor.h
> Fix bugs uncovered by -D_GLIBCXX_DEBUG

- documentation/sphinx/source/downloads.rst
- packaging/msi/FDBInstaller.wxs
Changed Windows GUID
Updated documentation version for release
> Release 6.0.6 prerequisite changes

- fdbrpc/TLSConnection.actor.cpp
- flow/Trace.cpp
Downgrade some trace events related to trace logging problems from SevError to SevWarnAlways.
> Remove suppressions happening off the network thread

- fdbclient/FDBOptions.h
- fdbclient/MultiVersionTransaction.actor.cpp
- fdbclient/NativeAPI.actor.cpp
Throw an exception if the option being set doesn't exist.
> Log network, cluster, and database options when they are set. 

- packaging/msi/FDBInstaller.wxs
- versions.target
This updates the versions.target file and WIX installer GUID following a release.
> Post release cleanup

- fdbserver/DataDistribution.actor.cpp
> fix: team->setHealthy was not being called correctly

- fdbrpc/Locality.cpp
over a storage server class machine
> the cluster controller should prefer to be located on a transaction class machine

- design/backup.md
Correct small confusion and typos in backup document.
Signed-off-by: Meng Xu <meng_xu@apple.com>
> Doc: clarify the backup document

- documentation/sphinx/source/index.rst
- documentation/sphinx/source/known-limitations.rst
Fixing what appears to be a small type-o on line 17 of the index.rst documentation.
Fixing what appears to be a small type-o on line 79 of the known-limitations.rst documentation.
> Fixing a couple of type-Os in documentation.

- bindings/python/fdb/six.py
Many bug fixes
https://github.com/benjaminp/six/blob/15e31431af97e5e64b80af0a3f598d382bcdd49a/six.py
> Update vendored Python module `six` to latest released version

- tests/RandomReadWrite.txt
Update `alpha` note in workload file according to source [code](https://github.com/apple/foundationdb/blob/f418a85390734373b74f022ae6a61bed23eb92ee/fdbserver/workloads/ReadWrite.actor.cpp#L541)
> Update note for alpha parameter

- bindings/c/local.mk
Added shared library option to allow the c project tests to build using community Dockerfile
> Fixed build of bindings target

- flow/Net2.actor.cpp
The tcp_resolver lifetime change is an attempt at working around an issue where long running backup processes reach a state where DNS resolution requests always time out but other processes on the same host can still resolve successfully.  In case this was somehow caused by a bad boost tcp_resolver state, each request now uses a unique tcp_resolver instance.
> DNS would fail if IPv6 responses are received, and shortened tcp_resolver lifetime

- CMakeLists.txt
- bindings/java/CMakeLists.txt
> Move Java specific setup into bindings/java/CMakeLists.txt

- fdbrpc/ContinuousSample.h
- fdbrpc/Smoother.h
- fdbrpc/libcoroutine/Coro.c
- fdbserver/Knobs.cpp
- flow/Knobs.cpp
- flow/Platform.cpp
- flow/TDMetric.actor.h
- flow/flow.h
Changes that enable compiling with gcc 8.2.1. Fixes #606, #347.
> Modern gcc

- build/Dockerfile
This is the first step of the work for #978.
(I'm not super sure who to pull as a reviewer.  From #972, I think you have the largest care, but you're welcome to reassign elsewhere.)
> Add boost-1.67.0 to the Dockerfile alongside 1.52.0

- build/docker-compose.yaml
Defined the CI PRB build services for linux builds within docker-compose
> PRB Build Services

- fdbrpc/TLSConnection.actor.cpp
> Improve TLS logging on error scenarios.

- fdbclient/ManagementAPI.actor.cpp
- fdbrpc/sim2.actor.cpp
- fdbrpc/simulator.h
- fdbserver/SimulatedCluster.actor.cpp
- fdbserver/workloads/ConsistencyCheck.actor.cpp
- fdbserver/workloads/MachineAttrition.actor.cpp
- fdbserver/workloads/RandomMoveKeys.actor.cpp
- fdbserver/workloads/RemoveServersSafely.actor.cpp
- fdbserver/workloads/SaveAndKill.actor.cpp
simulation now tests two machines in the same zone
> fix: coordinators auto could put two coordinators in the same zone

- fdbbackup/backup.actor.cpp
> Support TLS command line options in backup

- README.md
- cmake/InstallLayout.cmake
- fdbmonitor/CMakeLists.txt
- packaging/osx/scripts-server/preinstall
A set of cmake patches to generate a MacOS installer with cpack
> MacOS installer

- build/Dockerfile
Added support for python3 and cmake
> Updated Build Docker Image

- build/docker-compose.yaml
Added support for building via cmake when present via docker-compose
Added support for running ctests via docker-compose
> Docker-Compose Support For CMake And CTest (when present)

- build/packages.mk
Added support for building binaries package
> Added Binaries Package Target

- build/docker-compose.yaml
Added support for a type of correctness service run against the fdbserver binary via docker-compose
> Server Correctness Via Docker-compose

- cmake/AddFdbTest.cmake
- tests/TestRunner/TestRunner.py
> Generate distinct pseudo-random number for each test

- fdbserver/fdbserver.actor.cpp
Rejects listen addresses if the IP:PORT matches with that found in
cluster file, but the TLS state is different.
> fix: Don't disallow FDB listen addresses which are not in cluster file #1189

- bindings/bindingtester/tests/test_util.py
- bindings/python/fdb/tuple.py
- bindings/python/tests/tester.py
- documentation/sphinx/source/release-notes.rst
Updated the tester to exercise this path.
> Python: creating a SingleFloat with an integer didn't work.

- documentation/sphinx/source/simple-indexes.rst
Based on discussion here Implements a fix discussed in https://github.com/apple/foundationdb/pull/225
> Some fixes to Python simple indexes Example

- documentation/sphinx/source/developer-guide.rst
> Document behavior on the ordering of writes and read conflict ranges

- fdbrpc/FlowTransport.actor.cpp
- fdbrpc/FlowTransport.h
I'm still running correctness but created this PR so that it can unblock people. Although, I still have to investigate why it is so rare in simulated. Looking at change, I would expect it to be more frequent.
> fix: segfault due external assignment of Endpoint::addresses #1201

- fdbbackup/backup.actor.cpp
- fdbclient/BackupAgent.actor.h
- fdbclient/DatabaseBackupAgent.actor.cpp
> Add some basic checks before doing an atomic switchover.

- fdbbackup/backup.actor.cpp
- fdbclient/BackupAgent.actor.h
- fdbclient/FileBackupAgent.actor.cpp
- fdbserver/workloads/AtomicRestore.actor.cpp
- fdbserver/workloads/BackupCorrectness.actor.cpp
- tests/fast/BackupCorrectnessClean.txt
> Add support for restoring multiple ranges.

- cmake/ConfigureCompiler.cmake
Add a compiler flag for generating program database file (PDB) for Visual Studio.
> Enable .pdb file generation on Windows

- Makefile
- fdbcli/fdbcli.actor.cpp
- fdbclient/AutoPublicAddress.cpp
- fdbclient/FDBTypes.h
- fdbclient/ManagementAPI.actor.cpp
- fdbclient/MonitorLeader.actor.cpp
- fdbclient/NativeAPI.actor.cpp
- fdbclient/SystemData.cpp
- fdbrpc/FlowTransport.actor.cpp
- fdbrpc/TLSConnection.actor.cpp
- fdbrpc/sim2.actor.cpp
- fdbrpc/simulator.h
- fdbserver/SimulatedCluster.actor.cpp
- fdbserver/Status.actor.cpp
- fdbserver/fdbserver.actor.cpp
- fdbserver/workloads/CpuProfiler.actor.cpp
- fdbserver/workloads/MemoryLifetime.actor.cpp
- fdbserver/workloads/RemoveServersSafely.actor.cpp
- fdbserver/workloads/SaveAndKill.actor.cpp
- flow/Net2.actor.cpp
- flow/Platform.cpp
- flow/Platform.h
- flow/SystemMonitor.cpp
- flow/SystemMonitor.h
- flow/TDMetric.actor.h
- flow/Trace.cpp
- flow/Trace.h
- flow/network.cpp
- flow/network.h
- flow/serialize.h
This is *WIP* patch!
This patch makes the codebase ready for IPv6 support. In particular we enable NetworkAddress to take both IPv4 and IPv6 addresses.
> IPv6 Support

- bindings/java/fdbJNI.cpp
- bindings/java/src/main/com/apple/foundationdb/FutureResults.java
- bindings/java/src/main/com/apple/foundationdb/FutureVoid.java
- documentation/sphinx/source/release-notes.rst
Issue #1235 was resolved on master with PR #1236. This cherry picks the change onto release 6.0 so that if we do a 6.0.19 build, we get this performance improvement as part of that release.
> Cherry pick #1236 onto release-6.0

- flow/Platform.cpp
No idea why this was fine until now.
> Fix part of the windows build by adding a header

- documentation/sphinx/source/release-notes.rst
This does not have functional change.
> Add release note for teamRemover PR

- documentation/sphinx/source/api-python.rst
This change updates the documentation to reflect that we support python 3.7.
> Update python3.7 documentation

- fdbclient/DatabaseConfiguration.cpp
- fdbclient/MasterProxyInterface.h
- fdbclient/MultiVersionTransaction.actor.cpp
- fdbclient/NativeAPI.actor.cpp
- fdbclient/StatusClient.actor.cpp
- fdbclient/TaskBucket.actor.cpp
- fdbrpc/FlowTransport.actor.cpp
- fdbrpc/ReplicationPolicy.h
- fdbrpc/ReplicationTypes.h
- fdbrpc/ReplicationUtils.cpp
- fdbserver/Coordination.actor.cpp
- flow/Arena.h
- flow/DeterministicRandom.h
- flow/FileTraceLogWriter.cpp
- flow/Net2.actor.cpp
- flow/Platform.cpp
- flow/Platform.h
This PR fixes some compiler warnings that had been reported by the Windows build some months ago. It's not exhaustive, and there very well may have been new warnings introduced since.
Related to https://github.com/apple/foundationdb/issues/1255
> Fix various compiler warnings

- fdbserver/fdbserver.actor.cpp
Public address is required for roles FDBD, NetworkTestServer and
Restore only. Therefore, check those cases, and for others follow the
earlier behaviour of using default ip address 0.
FIXES #1305
> fix: fdbserver segfault when started with wrong arguments

- documentation/sphinx/source/mr-status-json-schemas.rst.inc
- fdbclient/Schemas.cpp
Add data_distributor and ratekeeper roles to schema.
> Fix SchemaMismatch error

- build/packages.mk
Added missing binary: backup_agent to TGZ package
> Updated TGZ Package

- cmake/CompileCoverageTool.cmake
Fixed some dotnet reference errors that actually produced errors that did not fail the build
> Fixed Dotnet Reference errors

- fdbmonitor/CMakeLists.txt
Added support for stripping symbols from fdbmonitor binary
> Strip Fdbmonitor Symbols

- build/cmake/build.sh
- build/cmake/docker-compose.yml
I also don't really see the need for the linux-pkgs command, so I'm removing that. CC @mpilman
> Fix return code plumbing

- fdbrpc/AsyncFileWriteChecker.cpp
- fdbrpc/AsyncFileWriteChecker.h
- fdbserver/CoroFlow.actor.cpp
- fdbserver/workloads/VersionStamp.actor.cpp
- flow/IndexedSet.cpp
- flow/flow.h
> Address review comments from #1446

- bindings/c/generate_asm.py
Modified syntax to support python 2.6
> Binding Tool Update

- bindings/java/CMakeLists.txt
> Remove fdb_c from fat-jar

- Makefile
- bindings/c/local.mk
- bindings/flow/tester/local.mk
- build/Dockerfile
- build/docker-compose.yaml
- documentation/sphinx/Makefile
Added environmental variable representing the docker version
Added Java Home environmental variable
Removed unnecessary packages
> Updated Build Docker

- fdbserver/fdbserver.actor.cpp
This adds support for the `--parentpid` option to non-Windows platforms.
This option is intended for testing layer implementations. When running
higher level CI chains its useful to ensure that any ephemeral instances
of fdbserver are automatically reaped.
> Extend support for parentpid

- flow/ObjectSerializerTraits.h
- flow/flat_buffers.cpp
- flow/network.h
Switched variant to use boost variant for source consistency
> Switched Variant Header

- tests/SnowflakeJenkins
We (snowflake) want to run build and simulation tests against PRs.
For this we need a jenkins file in the repository. This should not
impact anything else
> Added jenkins file for Snowflake

- tests/TestRunner/TestRunner.py
> Hardcode flatbuffers to off for ctest

- documentation/sphinx/source/configuration.rst
the each --> east, datacenter have --> datacenters has, mean signal --> signal
> Fix minor typos in config docs

- fdbserver/workloads/Cycle.actor.cpp
This is a simple PR without functional change.
> TraceEvent:First letter must be capitalized

- flow/ProtocolVersion.h
> Fixed version for PseudoLocalities

- build/Dockerfile
Define default compiler via environmental variables
> Update Build Docker

- fdbserver/fdbserver.actor.cpp
> Make public address and listen address a comma separated list

- build/Dockerfile
- build/docker-compose.yaml
Added distcc package in the event that package builders use remote compilation nodes
> Build Docker Update

- fdbserver/workloads/ExternalWorkload.actor.cpp
Check step should call check()
> Fix minor bug in External Workload

- fdbserver/DeltaTree.h
- fdbserver/VersionedBTree.actor.cpp
Replaced zero-length members with functions returning either a pointer for arrays or a reference for single (optional) items.
While it would also have been possible to change all of the declarations to a size of 1 and then adjust calculations involving size of these variable-sized structures to accommodate the change, this seems clunkier than using a function to access the possibly-missing variable-sized part of the structures.
> Fixed windows build failure due to use of the C "struct hack"

- flow/network.h
Flow should be an independent library.
> Remove a fdbprc header from flow library

- fdbclient/FDBTypes.h
- fdbserver/SimulatedCluster.actor.cpp
- fdbserver/worker.actor.cpp
- fdbserver/workloads/ConfigureDatabase.actor.cpp
And refactor some code to make adding more TLogVersions easier.
This is code that was already posted as part of #1795, but I've pulled it out as #1729 is going to want to reference it also, and I'm not sure which PR is going to be merged first.
> Add a TLogVersion::V4

- packaging/msi/MSIInstaller.wixproj
Disabled the validation of the wix builder
> Support For Windows Builder

- fdbrpc/sim2.actor.cpp
> sim2: Remove obsolete comment

- tests/CMakeLists.txt
SnapTestAttrition the test file was removed in a53bf928
CC @etschannen
> Remove SnapTestAttrition from ctest

- cmake/ConfigureCompiler.cmake
- flow/ObjectSerializerTraits.h
- flow/flat_buffers.cpp
- flow/network.cpp
- flow/network.h
> statically link libstdc++ on Linux and remove std::variant

- fdbcli/fdbcli.actor.cpp
- fdbclient/ManagementAPI.actor.cpp
- fdbclient/ManagementAPI.actor.h
- fdbserver/workloads/RemoveServersSafely.actor.cpp
> fdbcli: Add `no_wait` option in `exclude` command to avoid blocking

- build/link-validate.sh
- documentation/sphinx/source/release-notes.rst
- flow/Arena.h
- flow/FastAlloc.cpp
- flow/FastAlloc.h
- flow/Platform.h
- flow/SystemMonitor.cpp
- flow/Trace.cpp
- flow/Trace.h
> Fix huge arena tracking thread-safety issues.

- fdbserver/DataDistribution.actor.cpp
- fdbserver/DataDistributionQueue.actor.cpp
- fdbserver/DataDistributionTracker.actor.cpp
Add comments to explain the functionalities of some code.
> DataDistribution:Add comments to help understand the code

- fdbcli/fdbcli.actor.cpp
- fdbclient/ManagementAPI.actor.cpp
- fdbserver/DataDistribution.actor.cpp
- fdbserver/QuietDatabase.actor.cpp
Minor snap client improvements.
Only commit 354620f is relevant, rest of the commits are part of another PR # 1896.
> Few minor snapshot create client improvements

- documentation/sphinx/source/release-notes.rst
Added Release notes for snapshot snapshot v2 project.
> Release notes for snapshot feature

- fdbserver/DataDistribution.actor.cpp
This is a cosmetic change to [PR#1907](https://github.com/apple/foundationdb/pull/1907).
Change the threshold team number per server that should set lastBuildTeamsFailed
from DESIRED_TEAMS_PER_SERVER to
(SERVER_KNOBS->DESIRED_TEAMS_PER_SERVER * (configuration.storageTeamSize + 1)) / 2;
> DD:Change condition for lastBuildTeamsFailed

- documentation/sphinx/source/release-notes.rst
- flow/README.md
> Update flatbuffers documentation

- documentation/sphinx/source/release-notes.rst
- fdbserver/fdbserver.actor.cpp
This was branched off of #1926 to avoid some conflicts, we should merge that one first.
> --machine_id now sets locality_machineid

- fdbclient/MasterProxyInterface.h
- fdbclient/StorageServerInterface.h
- fdbrpc/LoadBalance.actor.h
- fdbserver/MasterProxyServer.actor.cpp
- fdbserver/storageserver.actor.cpp
- flow/Stats.h
https://github.com/apple/foundationdb/pull/1942 needs some work, so I split out the changes that pass tests.
> Improve read performance part 1 of 2

- build/docker-compose.yaml
Added missing quote for correctness command string
> Fix Correctness PRB

- fdbclient/SystemData.cpp
- fdbserver/DiskQueue.actor.cpp
- fdbserver/IDiskQueue.h
- fdbserver/LogSystem.h
- fdbserver/LogSystemConfig.h
- fdbserver/MoveKeys.actor.cpp
- fdbserver/TLogServer.actor.cpp
- fdbserver/TagPartitionedLogSystem.actor.cpp
- flow/genericactors.actor.h
Add comments to explain some structures and functions related to DiskQueue and TagPartitionedLogSystem.
Acknowledgement:
Thank @alexmiller-apple  for helping on explaining the code.
> Add comments to DiskQueue and tLog

- Makefile
- build/link-wrapper.sh
- fdbmonitor/local.mk
Added support for linking with clang c++ libraries when using Clang compiler
> Clang Link Support

- fdbbackup/backup.actor.cpp
- fdbserver/fdbserver.actor.cpp
> Add --loggroup to fdbserver and fdbbackup help text.

- CMakeLists.txt
Should we instead go to version 6.2.3 and tag this commit as 6.2.3? Maybe fold it into the next patch release?
> Update cmake version

- documentation/sphinx/source/mr-status-json-schemas.rst.inc
- fdbcli/fdbcli.actor.cpp
- fdbclient/ManagementAPI.actor.cpp
- fdbclient/ManagementAPI.actor.h
- fdbclient/Schemas.cpp
- fdbserver/Status.actor.cpp
Also fixed a bug which prevented fdbcli from starting when the database is down
> Added a sleep command to fdbcli

- bindings/flow/tester/Tester.actor.cpp
- bindings/go/src/_stacktester/stacktester.go
- bindings/go/src/fdb/generated.go
- bindings/java/src/test/com/apple/foundationdb/test/AsyncStackTester.java
- bindings/java/src/test/com/apple/foundationdb/test/StackTester.java
- bindings/python/tests/tester.py
- bindings/ruby/tests/tester.rb
- documentation/sphinx/source/api-c.rst
- documentation/sphinx/source/api-common.rst.inc
- documentation/sphinx/source/api-python.rst
- documentation/sphinx/source/api-ruby.rst
- documentation/sphinx/source/data-modeling.rst
- documentation/sphinx/source/developer-guide.rst
- documentation/sphinx/source/release-notes.rst
- fdbclient/NativeAPI.actor.cpp
- fdbclient/NativeAPI.actor.h
- fdbclient/vexillographer/fdb.options
> Add database/transaction option to control includePort behavior in get_addresses_for_key

- bindings/c/test/mako/mako.c
- flow/Knobs.cpp
- flow/Knobs.h
- flow/Net2.actor.cpp
> TCP_QUICKACK test

- documentation/sphinx/source/mr-status-json-schemas.rst.inc
- documentation/sphinx/source/release-notes.rst
- fdbclient/Schemas.cpp
- fdbserver/Status.actor.cpp
> Added lockUID to status output if database is locked

- fdbserver/fdbserver.actor.cpp
> Verify that we have enough memory if cache_memory is set

- cmake/ConfigureCompiler.cmake
- flow/Error.h
- flow/Platform.cpp
Added required modifications to source and configuration files to support CLANG compilations
> Clang cmake

- fdbserver/workloads/ConfigureDatabase.actor.cpp
It turns out that in rare situations, simulation can run into a case
where recovering to the point that tlog generations can be dropped takes
longer than 3s, and thus tests fail with an OOM as an ever increasing
number of tlogs are recruited and never removed.
I did 100k runs of ConfigureTest and got no OOMs.
> Make one case in ConfigureDatabase wait for >3s.

- fdbserver/DataDistribution.actor.cpp
When an address whose locality was configured incorrectly and later corrected, DD should start recruit SS on the address once its locality is correct.
Correctness found that some storage process may not have SS on it in the consistency check. 
Reason: Race between the `StorageRecruitment` actor and `checkAndRemoveInvalidLocalityAddr`  actor. When recruitment request because worker is bounced is executed before the actor that removes the address from invalidLocality list, the recruitment request will not successfully recruit a server on the worker. 
This PR fixes the problem.
> DD:Trigger storage recruitment when an invalid address locality is corrected

- cmake/ConfigureCompiler.cmake
- flow/Platform.cpp
This will currently complain quite loudly, but it's the first step to fixing all the undefined behavior.
> Add USE_UBSAN cmake option

- CMakeLists.txt
Fixed CMake version to match versions.target
> CMake Version Sync

- fdbrpc/FlowTests.actor.cpp
> Add test for delay ordering

- fdbserver/ClusterController.actor.cpp
> Add cluster controller metrics

- fdbserver/fdbserver.actor.cpp
- flow/FastAlloc.h
- tools/alloc_instrumentation.py
This also include a C++17 fix for `ALLOC_INSTRUMENTATION`
> Add script to parse output from enabling ALLOC_INSTRUMENTATION_STDOUT

- fdbclient/StorageServerInterface.h
- fdbserver/DataDistributionTracker.actor.cpp
- fdbserver/Knobs.cpp
- fdbserver/Knobs.h
- fdbserver/StorageMetrics.actor.h
- fdbserver/storageserver.actor.cpp
This is the draft I am going to iterate on.
> Added metrics for read hot key detection

- cmake/ConfigureCompiler.cmake
- flow/Platform.h
> Fix compiler errors on Catalina

- fdbserver/VersionedBTree.actor.cpp
BTree height was not being reset when a new empty root is written.  IKeyValueStore wrapper was not obeying the row limit in a reverse range query.  Added yields to and delays to break up tasks and set IO priorities.
> Bug fixes in Redwood

- fdbclient/FDBTypes.h
- fdbclient/FileBackupAgent.actor.cpp
- fdbclient/SystemData.cpp
- fdbclient/SystemData.h
- fdbserver/RestoreCommon.actor.cpp
- fdbserver/RestoreRoleCommon.actor.h
- flow/Arena.h
- flow/ObjectSerializerTraits.h
- flow/flat_buffers.h
- flow/flow.h
A const return type has no effect
> Remove several nonsensical const uses

- fdbbackup/backup.actor.cpp
- fdbclient/BackupAgentBase.actor.cpp
Also added cleanup to the usage output printed for fdbbackup.
I opted not to add a release note, but I can add one if desired.
> Cleanup the fdbbackup cleanup command output

- documentation/sphinx/source/release-notes.rst
- fdbclient/Knobs.cpp
- fdbclient/Knobs.h
- fdbclient/ReadYourWrites.actor.cpp
> Limit lifetime of timeout memory for transactions that have terminated

- fdbclient/Notified.h
- flow/TDMetric.actor.h
Add [[nodiscard]] to `whenAtLeast` and make `Notified` generic
Resolves #2340
> Refactor Notified

- flow/genericactors.actor.h
Since QuorumCallback<T> is a non trivial type, we need to construct it
before we interact with it
This change fixes the following UBSAN message
/Users/anoyes/workspace/foundationdb/flow/genericactors.actor.h:930:18: runtime error: member access within address 0x0001243f63d0 which does not point to an object of type 'Callback<Standalone<StringRef> >'
0x0001243f63d0: note: object has invalid vptr
> Fix invalid vptr

- fdbserver/RestoreWorker.actor.cpp
- fdbserver/workloads/BackupAndParallelRestoreCorrectness.actor.cpp
Thanks to @ajbeamon's reminder, we have two actors that do not have wait statement.
This PR fixes that.
No functional change in this PR.
> Fix compilation warning that actor that does not contain wait statement

- fdbrpc/FlowTests.actor.cpp
- flow/CMakeLists.txt
- flow/DeterministicRandom.cpp
- flow/DeterministicRandom.h
- flow/flow.vcxproj
- flow/flow.vcxproj.filters
- tests/fast/RandomUnitTests.txt
> Fix deterministic random ub

- cmake/ConfigureCompiler.cmake
CC @mpilman 
See https://pzemtsov.github.io/2016/11/06/bug-story-alignment-on-x86.html for some more context.
> Disable alignment-requiring instructions until #1434 is resolved

- fdbserver/workloads/FuzzApiCorrectness.actor.cpp
I confirmed that this catches the bug described in #2424, and also that #2427 fixes it.
> Test client-side buggify in simulation

- fdbclient/RestoreWorkerInterface.actor.h
- fdbserver/RestoreApplier.actor.cpp
- fdbserver/RestoreLoader.actor.cpp
- fdbserver/RestoreMaster.actor.cpp
No functional change. Just clean up the code a bit.
> Performant restore [11/XX]: Clean up unused fields in LoadingParam

- build/docker-compose.yaml
Added more verbose compilation statements when building via ninja to give more specific error details
> More Verbose Compilation Details

- build/Dockerfile
- build/docker-compose.yaml
> Include libubsan in the docker image

- bindings/go/src/fdb/transaction.go
- bindings/java/src/main/com/apple/foundationdb/Transaction.java
- documentation/sphinx/source/api-c.rst
- documentation/sphinx/source/api-common.rst.inc
- documentation/sphinx/source/api-python.rst
- documentation/sphinx/source/api-ruby.rst
Clarifying documentation for clear_range repo - copied from https://forums.foundationdb.org/t/question-about-range-clear/1132
> DocBlitz : Clarify Documentation for clear_range API

- design/recovery-internals.md
This PR adds a design doc about how FDB recovery works.
This is based on Evan's internal talk and my understanding. 
@mpilman @alexmiller-apple @jzhou77 @ajbeamon, could you please chime in to help improve the document?
> Design doc: Recovery internals

- fdbclient/SnapshotCache.h
Resolve follow up comment on #2400
> Use consistent "> 0" style for guarding memcpy

- README.md
This is an attempt to improve the readability of step 3 for Linux Makefile config.
> Improve readability for Makefile Linux step

- documentation/sphinx/source/administration.rst
- documentation/sphinx/source/api-general.rst
- documentation/sphinx/source/developer-guide.rst
Also fix a minor documentation formatting problem in administration.
> Add some documentation for the client network thread and client logging.

- flow/Knobs.cpp
> Changed failure monitor ping delay to 1 second

- bindings/go/src/fdb/doc.go
- documentation/sphinx/source/api-c.rst
- documentation/sphinx/source/api-common.rst.inc
- documentation/sphinx/source/api-python.rst
- documentation/sphinx/source/api-ruby.rst
- documentation/sphinx/source/developer-guide.rst
Originally reviewed against master: https://github.com/apple/foundationdb/pull/2440
> DocBlitz: atomic compare and clear

- bindings/flow/CMakeLists.txt
- bindings/java/CMakeLists.txt
- cmake/InstallLayout.cmake
Fixed the naming of the rpm and deb packages
> Cmake Package Name Fix

- bindings/flow/CMakeLists.txt
- cmake/InstallLayout.cmake
Changed the name of the rpm packages to conform to the existing name when building release project
> CMake Release Fix

- documentation/sphinx/source/disk-snapshot-backup.rst
- documentation/sphinx/source/operations.rst
Disk snapshot restore documentation.
> Disk snapshot backup and restore documentation

- packaging/docker/samples/golang/.env
- packaging/docker/samples/golang/README.md
- packaging/docker/samples/golang/app/Dockerfile
- packaging/docker/samples/golang/app/go.mod
- packaging/docker/samples/golang/app/go.sum
- packaging/docker/samples/golang/app/main.go
- packaging/docker/samples/golang/app/start.bash
- packaging/docker/samples/golang/docker-compose.yml
This PR is fixing #2404 by adding a new docker-compose sample using Go.
> Add a docker-compose go sample (#2404)

- packaging/make_public.py
> make_public.py doesn't need python to be invoked with the -B argument

- bindings/c/test/mako/mako.c
- bindings/c/test/mako/mako.h
- bindings/c/test/mako/utils.c
- bindings/c/test/mako/utils.h
Format mako's code. This will mess up git-blame but that's a problem we'll have to accept 🙂
> clang-format mako

- fdbserver/workloads/Mako.actor.cpp
Fixed the location of crc32c.h from fdbrpc to flow
This update should fix the build of workloads which has been broken for several days but may not be tested within CI
> Updated crc32c File Location

- documentation/sphinx/requirements.txt
This applies #2611 to release-6.2, so I probably should have done this the other way around, but oh well.
> Fix the build on release-6.2 also

- fdbserver/Knobs.cpp
Explain why it may cost 100MB data movement.
No code change.
> Explain knob SHARD_MAX_BYTES_PER_KSEC

- fdbbackup/FileConverter.actor.cpp
- fdbbackup/FileDecoder.actor.cpp
- fdbserver/StorageCache.actor.cpp
- fdbserver/workloads/AtomicOps.actor.cpp
- tests/CMakeLists.txt
> Fix OPEN_FOR_IDE build

- fdbserver/Ratekeeper.actor.cpp
> Fix inaccurate limiting durability lag

- documentation/sphinx/source/api-c.rst
- documentation/sphinx/source/api-common.rst.inc
- documentation/sphinx/source/api-python.rst
- documentation/sphinx/source/api-ruby.rst
- documentation/sphinx/source/data-modeling.rst
- documentation/sphinx/source/developer-guide.rst
- fdbclient/NativeAPI.actor.cpp
- fdbclient/NativeAPI.actor.h
- fdbclient/vexillographer/fdb.options
- fdbserver/workloads/MemoryLifetime.actor.cpp
- flow/network.cpp
- flow/network.h
> Enable include_port_in_address by default for api version 700

- fdbclient/vexillographer/fdb.options
Also fix typo. Resolves #2603.
> Fix database default retry limit documentation.

- fdbserver/BackupWorker.actor.cpp
Since backup worker doesn't catch this error, a deleted BackupConfig can cause
the backup worker to get key_not_found error. Fix by adding a check if the
container can be found.
> Fix key_not_found error due to deleted BackupConfig

- fdbrpc/FlowTransport.h
- fdbrpc/fdbrpc.h
- flow/serialize.h
This PR removes some dead code which allows us to avoid some template instantiations. This improves compile time and memory consumption during compilation slightly
> Removed dead code

- documentation/sphinx/source/administration.rst
- documentation/sphinx/source/old-release-notes/release-notes-600.rst
> Document role affinity changes that occurred in 6.0

- flow/flat_buffers.cpp
- flow/flat_buffers.h
> Fix flatbuffers heap buffer overflow

- flow/flat_buffers.cpp
- flow/serialize.h
> Encode Void as a valid flatbuffers message

- fdbclient/NativeAPI.actor.cpp
- flow/Stats.actor.cpp
> Increase priority of the logging of various metrics trace events

- fdbserver/workloads/Mako.actor.cpp
Since there are already checks for `keySize` and `valueSize` and also default byte limit for `getRange`, there is no need to keep these parameters.
> Delete unnecessary parameters in MakoWorkload

- build/gen_dev_docker.sh
This is an attempt to automate the creation of a docker dev-image and a command to run it. This also hopefully resolves confusion around the fact that the user doesn't exist
> added script that will generated a dev-docker img

- fdbclient/NativeAPI.actor.cpp
- flow/Trace.cpp
- flow/Trace.h
This addresses https://github.com/apple/foundationdb/issues/2859
> Allow trace log group to be set after database is created

- contrib/Joshua/README.md
- contrib/Joshua/scripts/bindingTest.sh
- contrib/Joshua/scripts/bindingTestScript.sh
- contrib/Joshua/scripts/bindingTimeout.sh
- contrib/Joshua/scripts/correctnessTest.sh
- contrib/Joshua/scripts/correctnessTimeout.sh
- contrib/Joshua/scripts/localClusterStart.sh
- contrib/Joshua/scripts/valgrindTest.sh
- contrib/Joshua/scripts/valgrindTimeout.sh
Added Readme file describing Joshua correctness for FoundationDB
Added required scripts to implement Joshua correctness for fdbserver, debug fdbserver, and binding tester
> Support for Joshua Bundles

- documentation/sphinx/source/command-line-interface.rst
- fdbcli/fdbcli.actor.cpp
This addresses https://github.com/apple/foundationdb/issues/2864.
> Added fdbcli getversion command

- cmake/AddFdbTest.cmake
- contrib/Joshua/scripts/bindingTestScript.sh
Fixed the creation of binding test package
> Binding Test Package fix

- fdbbackup/backup.actor.cpp
I.e., "-p", or "--partitioned_log" to enable it. By default, old backup system is used. I've manually verified the "start" command works as intended.
This is part of #1003
> Add an option for fdbbackup to use new backup system

- fdbclient/CommitTransaction.h
- fdbclient/RestoreWorkerInterface.actor.h
- fdbserver/RestoreApplier.actor.cpp
- fdbserver/RestoreMaster.actor.cpp
- fdbserver/RestoreMaster.actor.h
- fdbserver/RestoreRoleCommon.actor.cpp
- fdbserver/RestoreUtil.actor.cpp
- fdbserver/RestoreUtil.h
- fdbserver/fdbserver.actor.cpp
Fix the very rare bugs that were found by the `ParallelRestoreOldBackupApiCorrectnessAtomicRestore.txt` test
> Performant restore [25/xx]: Fix rare bugs found by API correctness test

- documentation/sphinx/source/command-line-interface.rst
- fdbcli/fdbcli.actor.cpp
This is similar to https://github.com/apple/foundationdb/pull/2039.
> Add lock and unlock commands to fdbcli

- fdbserver/Knobs.cpp
This is related to Issue https://github.com/apple/foundationdb/issues/2937
> Test the knob DESIRED_TEAMS_PER_SERVER between 1 and 10

- flow/Trace.cpp
- flow/Trace.h
This addresses https://github.com/apple/foundationdb/issues/2878
> Annotate trace batch events before dumping

- bindings/java/CMakeLists.txt
Added support for creating Fdb java tests artifact package
> Create Java Tests Package

- fdbserver/Knobs.cpp
> Buggify master recruit backup worker delay

- fdbclient/NativeAPI.actor.cpp
- fdbserver/Coordination.actor.cpp
These include fdbcli, DR, and backup.
Resolves #2836
> Don't include internal tools in the status client list

- design/special-key-space.md
The documentation for special-key-space(#2662 ).
> Documentation for special-key-space

- flow/Net2.actor.cpp
Normal "connection refused" messages would show up with a long verbose
string that doesn't really provide any useful information otherwise.
Fixes #2900
> Only log OpenSSL error strings for OpenSSL errors.

- flow/actorcompiler/ActorCompiler.cs
195 of these situations were found, but I'm not sure what the impact will be.  Many were trivial or reference counted types (which at least will avoid a reference ++/--), some were in templated actors and could be anything, and there were a few vectors, sets, and maps but I'm not sure how often they are called.
> Actor compiler will std::move() return expressions that exactly match a state variable

- bindings/java/fdbJNI.cpp
Attempt at a small optimization in JNI...  Not clear to me what the testing strategy is for the bindings.
> 2808: Add caching for jmethodID, jfieldID and jclass for JNI for Java Binding

- fdbserver/Knobs.cpp
Kudos to A.J. and Bala who found this bug.
> Add BUGGIFY back to DESIRED_TEAMS_PER_SERVER knob

- cmake/AddFdbTest.cmake
> Don't create package directories in source dir

- cmake/ConfigureCompiler.cmake
- fdbclient/FDBTypes.h
- fdbserver/DiskQueue.actor.cpp
- fdbserver/VFSAsync.cpp
- flow/Arena.h
This addresses https://github.com/apple/foundationdb/issues/3000
> Enable -Wclass-memaccess and fix warnings

- cmake/ConfigureCompiler.cmake
- fdbclient/FDBTypes.h
- fdbserver/DiskQueue.actor.cpp
- fdbserver/VFSAsync.cpp
- flow/Arena.h
Reverts apple/foundationdb#3017
> Revert "Enable -Wclass-memaccess and fix warnings"

- fdbclient/FileBackupAgent.actor.cpp
Fix submitParallelRestore() when targetVersion is unset
> Fix performant restore bug introduced in PR 3041

- fdbclient/ReadYourWrites.actor.cpp
If you set a transaction timeout, and that timeout expires while your commit is in-flight, that in-flight commit might commit _after_ other commits done by this client. This is subtle and hard to reason about but unavoidable since confirming a commit is no longer in-flight requires an rpc.
One way around this is to confirm your transaction is no longer in-flight by committing a dummy transaction that conflicts.
Here's an (optionally) buggy python app whose bug can be found with this client buggify. Comment the last line out to make it buggy (you may need to run it several times to actually see the assert fire)
```
import fdb
fdb.api_version(620)
fdb.options.set_client_buggify_enable()
max_x_seen = -1
def make_self_conflicting(tr, x):
tr.add_read_conflict_key(str(x)) …
```
> Simulate a timeout for an in-flight commit with client buggify

- build/Dockerfile.devel
Added Dockerfile used to build a development docker image
> Development Docker image

- build/Dockerfile
- build/docker-compose.yaml
Added newer version of git to build docker in order to allow directories to be created during cloning
> Newer Git To Build Docker

- cmake/CompilerChecks.cmake
- cmake/ConfigureCompiler.cmake
> Disable TSAN + STATIC_LINK_LIBCXX

- documentation/sphinx/source/mr-status-json-schemas.rst.inc
- fdbclient/NativeAPI.actor.cpp
- fdbclient/Schemas.cpp
- fdbserver/Ratekeeper.actor.cpp
- fdbserver/Status.actor.cpp
- fdbserver/storageserver.actor.cpp
* Add details about the busiest tag to status
* Fix tag throttle count status
* Fix debug tagging was always enabled
> Add and fix tag throttling status fields

- fdbbackup/backup.actor.cpp
- fdbrpc/sim2.actor.cpp
- fdbrpc/simulator.h
- fdbserver/fdbserver.actor.cpp
- flow/Error.cpp
- flow/Error.h
This addresses https://github.com/apple/foundationdb/issues/3105
> Removed uses of outdated cpuTicks and errorCounts

- fdbclient/NativeAPI.actor.cpp
Some other small tweaks to avoid map lookups when tags aren't used.
> Add back an std::move that was accidentally removed

- README.md
- cmake/ConfigureCompiler.cmake
> Improve build-from-source user experience

- README.md
- cmake/ConfigureCompiler.cmake
Reverts apple/foundationdb#3189
> Revert "Improve build-from-source user experience"

- contrib/transaction_profiling_analyzer/transaction_profiling_analyzer.py
I also went ahead and passed it to all messages that are being deserialized for future use.
> Fix: transaction_profiling_analyzer wasn't passing protocol_version everywhere it was used

- fdbserver/Status.actor.cpp
Also changes it so that we don't report more available memory than the limit set for the process. This second change seems reasonable to me, but I'm curious if anybody disagrees with it.
> Balance available memory based on the limits set for each process.

- fdbserver/BackupProgress.actor.cpp
- fdbserver/BackupWorker.actor.cpp
- fdbserver/Knobs.cpp
- fdbserver/Knobs.h
- fdbserver/RestoreLoader.actor.cpp
- fdbserver/workloads/BackupAndParallelRestoreCorrectness.actor.cpp
> Limit memory usage of backup workers

- cmake/ConfigureCompiler.cmake
- flow/flow.h
Also fixed bugs this uncovered in flow.h.
> Added -Woverloaded-virtual warning for clang

- bindings/go/src/fdb/fdb_test.go
Also fix a couple things so the tests would run
> Update API version of Go test

- build/docker-compose.yaml
Added support for building tests and correctness build packages via docker compose
An important ingredient to allow Correctness support within CI
> Tests Packages Build Support

- bindings/java/src/main/com/apple/foundationdb/tuple/ByteArrayUtil.java
> Fixes 3316 ByteArrayUtil.join is used heavily and creates a lot of objects

- flow/ProtocolVersion.h
Discussion with A.J. to clarify the protocol version's dev column.
> Explain the dev version in protocol version

- fdbclient/ReadYourWrites.actor.cpp
This was accidentally smuggled in at PR 3329.
> Revert debugTransaction in ReadYourWritesTransaction

- documentation/sphinx/source/mr-status-json-schemas.rst.inc
- documentation/sphinx/source/release-notes.rst
- fdbcli/fdbcli.actor.cpp
- fdbclient/Schemas.cpp
- fdbserver/Status.actor.cpp
- fdbserver/workloads/TriggerRecovery.actor.cpp
Version 6.3 introduced a new status field `active_primary_dc` as well as some extra info in fdbcli status output. This backports that change to the release 6.2 branch and also fixes a documentation issue related to this feature.
> Backport region config status changes to release-6.2

- fdbserver/VersionedBTree.actor.cpp
Make a flow lock instance a reference to avoid it getting destroyed before accessing it.
> Fix bad mem access caused by destruction race

- fdbserver/VersionedBTree.actor.cpp
Similar fix to #3365 but for the read concurrency lock.
> Crash fix in Redwood during storage engine destruction with reads in progress

- documentation/sphinx/source/release-notes/release-notes-620.rst
> Fix the link for a release note

- fdbserver/MasterProxyServer.actor.cpp
This PR is to fix recent Joshua failures on fast/CycleAndLock which was introduced through [PR3307](https://github.com/apple/foundationdb/pull/3307).
The root cause is that we may update 'lockedAfter' and 'metadataVersion' to stale value when the commitVersion is less than the self->committedVersion.
> Fix getting read version while locked

- fdbserver/Knobs.cpp
There are still some Joshua errors related to PR_3307. Now I quickly unblock other devs by flipping ASK_READ_VERSION_FROM_MASTER.
> Fix Joshua errors related to PR_3307 by flipping ASK_READ_VERSION_FROM_MASTER temporarily.

- bindings/c/test/mako/mako.c
- bindings/c/test/mako/mako.h
- bindings/c/test/mako/utils.c
- bindings/c/test/mako/utils.h
added median and 99.9 percentile latency measurement
> added median and 99.9 percentile latency measurement

- fdbclient/ClusterInterface.h
- fdbclient/MultiVersionTransaction.actor.cpp
- fdbclient/NativeAPI.actor.cpp
- flow/Arena.h
> fix ClientVersionRef versionString should be passed by ref

- fdbserver/workloads/LowLatency.actor.cpp
This addresses https://github.com/apple/foundationdb/issues/3357
> Test commits in LowLatency workload

- fdbbackup/backup.actor.cpp
- fdbclient/BackupAgent.actor.h
- fdbclient/FileBackupAgent.actor.cpp
- fdbclient/TaskBucket.h
- fdbserver/workloads/TPCCWorkload.h
This reverts commit 0c39006b0711fa477564c2ec15e9d95b6271a684.
> Revert "Fixed some dangling pointers"

- fdbrpc/RangeMap.h
- fdbserver/RestoreLoader.actor.cpp
- tests/CMakeLists.txt
- tests/slow/ParallelRestoreTestSplitMutation.txt
This simplifies code by reusing `KeyRangeMap` class.
> Use KeyRangeMap for splitMutation

- documentation/sphinx/source/release-notes/release-notes-630.rst
- fdbbackup/backup.actor.cpp
- fdbclient/BackupAgent.actor.h
- fdbclient/DatabaseBackupAgent.actor.cpp
I can make a fast consistent copy of a fdb cluster by stopping a DR site and copy all the files from all DR nodes to a new cluster nodes. But detaching this copy with fdbdr abort affects replication to the origin DR site.
1. Create a three-node Primary FDB cluster
2. Make some workload to the database
3. Create a three-node DR FDB cluster. Set up replication from the primary cluster with three instances of dr_agent
4. Wait until the DR cluster becomes a full copy of the primary cluster
5. Pause the dr agents
6. Stop FoundationDB on all DR site nodes
7. Prepare three nodes for the clone FDB cluster
8. Copy all the files from the dr site to the clone nodes
9. Make a cluster file for the clone: take the cluster id and description from the DR cluster and the ip adresses of the clone nodes
10. …
> Detach a Clone of DR Site without Affecting Replication to the Original DR Site

- contrib/TestHarness/CMakeLists.txt
- contrib/TestHarness/Program.cs
- contrib/TraceLogHelper/JsonParser.cs
- contrib/TraceLogHelper/XmlParser.cs
This reverts commit 5e96fd9a96691858ebaac716ed185e9cfe91949a.
It seems that this has caused many failures in Joshua. We should revert and then commit it again as soon as we know what the problem is
> Revert "Add JSON trace support in TestHarness"

- flow/Arena.h
- flow/IThreadPool.h
This mostly simplifies the SmallVectorRef class to use
VectorRef (instead of replicating code...)
> Address review comments from tracing work

- fdbrpc/sim2.actor.cpp
- fdbrpc/simulator.h
- fdbserver/DataDistribution.actor.cpp
- fdbserver/DataDistributionQueue.actor.cpp
- fdbserver/SimulatedCluster.actor.cpp
- fdbserver/WaitFailure.actor.cpp
> Minor improvement on comments

- flow/Platform.actor.cpp
This has caused backup tests to fail.
> Fix Unseed Mismatch Error

- tests/slow/LowLatencyWithFailures.txt
connectionFailuresDisableDuration and minimumReplication global variable should come before testName
> Fix LowLatencyWithFailures.txt test for nightly

- fdbbackup/CMakeLists.txt
- fdbbackup/backup.actor.cpp
- fdbclient/FileBackupAgent.actor.cpp
- fdbserver/RestoreMaster.actor.cpp
- fdbserver/workloads/AtomicSwitchover.actor.cpp
- fdbserver/workloads/BackupToDBCorrectness.actor.cpp
- fdbserver/workloads/BackupToDBUpgrade.actor.cpp
- fdbserver/workloads/ParallelRestore.actor.cpp
> Rename fastRestore_agent to fastRestoreTool

- fdbclient/RestoreWorkerInterface.actor.h
- fdbserver/CMakeLists.txt
- fdbserver/RestoreController.actor.cpp
- fdbserver/RestoreController.actor.h
- fdbserver/RestoreLoader.actor.h
- fdbserver/RestoreRoleCommon.actor.cpp
- fdbserver/RestoreRoleCommon.actor.h
- fdbserver/RestoreUtil.actor.cpp
- fdbserver/RestoreUtil.h
- fdbserver/RestoreWorker.actor.cpp
> Fast Restore: Rename master to controller

- bindings/c/test/mako/mako.c
- bindings/java/JavaWorkload.cpp
- cmake/CompileBoost.cmake
- cmake/ConfigureCompiler.cmake
- fdbclient/BackupContainer.actor.cpp
- fdbclient/FDBTypes.h
- fdbclient/FileBackupAgent.actor.cpp
- fdbclient/MultiVersionTransaction.actor.cpp
- fdbserver/workloads/ApiCorrectness.actor.cpp
- fdbserver/workloads/AsyncFileCorrectness.actor.cpp
- flow/Arena.h
- flow/AsioReactor.h
- flow/ObjectSerializerTraits.h
- flow/flat_buffers.h
- flow/flow.h
> Add -Wall and -Wextra for clang, and explicitly ignore some warnings for now

- bindings/flow/tester/Tester.actor.cpp
- bindings/flow/tester/Tester.actor.h
- fdbclient/RunTransaction.actor.h
- flow/IRandom.h
- flow/Platform.h
- flow/ThreadHelper.actor.h
- flow/actorcompiler/ActorCompiler.cs
- flow/flow.h
- flow/genericactors.actor.h
`std::declval` was created for just this purpose.
> s/fake/std::declval/

- bindings/java/src/main/com/apple/foundationdb/RangeQuery.java
- bindings/java/src/main/com/apple/foundationdb/testing/WorkloadContext.java
- bindings/java/src/main/com/apple/foundationdb/tuple/Tuple.java
- bindings/java/src/main/com/apple/foundationdb/tuple/TupleUtil.java
Finally got vscode to understand the java bindings.
Adding this to .vscode/settings.json did the trick
"java.project.referencedLibraries": [
"fdb-build/packages/*.jar"
]
Where fdb-build is my cmake build dir
> Fix a few java warnings

- fdbbackup/backup.actor.cpp
fastrestore_tool uses the same option list as fdbrestore does. 
The option list for fdbrestore was changed about one year ago, but the related code for fastrestore_tool has not been updated accordingly. 
Because we don't have tests for the option list and the fastrestore_tool is not used officially, so we didn't fix it until now.
> FastRestoreTool: Fix --dest_cluster_file option

- cmake/ConfigureCompiler.cmake
- fdbbackup/FileConverter.actor.cpp
- fdbclient/BackupContainer.actor.cpp
- fdbclient/TagThrottle.actor.cpp
- fdbserver/BackupProgress.actor.cpp
- fdbserver/BackupWorker.actor.cpp
- fdbserver/MasterProxyServer.actor.cpp
- fdbserver/StorageCache.actor.cpp
- flow/TreeBenchmark.h
Haven't tried building on osx yet, so that might fail. clang 10 seems happy with it though
> Re-enable -Wall -Wextra for clang

- flow/FastAlloc.cpp
- flow/FastAlloc.h
These came up in a TSAN run I had going.
> Fix some unprotected accesses to global data

- flow/Arena.cpp
The test would fail if size is 0, then the iterator points to invalid memory.
> Fix unit test failure

- contrib/TestHarness/CMakeLists.txt
- contrib/TestHarness/Program.cs
- contrib/TraceLogHelper/JsonParser.cs
- contrib/TraceLogHelper/XmlParser.cs
This is the second attempt to PR #3350.
> Add JSON trace support in TestHarness (Take 2)

- contrib/fdbcstat/README.md
- contrib/fdbcstat/fdbcstat
eBPF/bcc script to collect and display statistics for the major fdb_transaction_* function calls inside libfdb_c.so library.
> fdbcstat: FDB C API monitoring utility

- flow/ThreadPrimitives.h
> Make ThreadSpinLock large to prevent false sharing

- fdbclient/RestoreWorkerInterface.actor.h
- fdbserver/Knobs.cpp
- fdbserver/Knobs.h
- fdbserver/RestoreApplier.actor.cpp
- fdbserver/RestoreApplier.actor.h
- fdbserver/RestoreController.actor.cpp
- fdbserver/RestoreController.actor.h
- fdbserver/RestoreLoader.actor.cpp
- fdbserver/RestoreLoader.actor.h
- fdbserver/RestoreRoleCommon.actor.h
- fdbserver/RestoreUtil.h
- fdbserver/RestoreWorker.actor.cpp
- fdbserver/RestoreWorker.actor.h
Fix issue: https://github.com/apple/foundationdb/issues/3589
> Fast Restore: Fix the sampling packet size at sampling phase

- fdbclient/NativeAPI.actor.cpp
- fdbclient/NativeAPI.actor.h
- fdbclient/StorageServerInterface.h
- fdbserver/DataDistributionTracker.actor.cpp
- fdbserver/Knobs.cpp
- fdbserver/StorageMetrics.actor.h
- fdbserver/workloads/ReadHotDetection.actor.cpp
Increased some knobs to throttle the spammy read hot logging. Also added more details inside the read hot log to make it useful
> Increased some knobs to throttle the spammy read hot logging.

- fdbserver/KeyValueStoreRocksDB.actor.cpp
- fdbserver/Knobs.cpp
- fdbserver/Knobs.h
TODO
The added knobs allow you to add background threads for doing compactions and making the memtable larger.
> Add some RocksDB optimizations and configuration knobs

- build/Dockerfile.devel
> Updated Development Docker

- documentation/sphinx/source/mr-status-json-schemas.rst.inc
- fdbclient/Schemas.cpp
Update #3669 . Schema check will fail without updating Schemas.cpp
> add throttle objects into Schemas.cpp

- fdbserver/VersionedBTree.actor.cpp
To avoid running too long, the Redwood correctness unit test now limits the size of the KV verification map.  This map only grows as the test runs, as it contains a record for every key set or clear committed during the test.
> Prevent Redwood unit test timeout from trying to do too much work

- fdbserver/RestoreRoleCommon.actor.cpp
The periodic status tracing in fast restores traces all version batches (VB) states.
When we have too many version batches in pipeline, which happens primarily in simulation tests, it will create a long trace that is larger than `maxEventLength`.
Solution:
Limit the number of pending VBs' status tracing.
> FastRestore:Fix trace event overflow in traceRoleVersionBatchProgress

- fdbclient/TaskBucket.actor.cpp
This addresses https://github.com/apple/foundationdb/issues/3747
> Use consistent prefix for task bucket traces

- documentation/sphinx/source/architecture.rst
See fixed version [here](https://github.com/jzhou77/foundationdb/blob/master/documentation/sphinx/source/architecture.rst)
> Fix a missing image in doc

- contrib/Joshua/scripts/localClusterStart.sh
After the changes made on 9/17/20, bindingtester stopped working on our Joshua on k8s.
This PR will fix it.
> Make bindingtester scripts more k8s friendly

- fdbserver/workloads/IncrementalBackup.actor.cpp
- tests/fast/IncrementalBackup.toml
adjustment to test approach to avoid failing nightlies with joshua timeouts
> Attempt to use version instead of test duration to have backup capture all changes

- build/Dockerfile
- build/Dockerfile.devel
- build/docker-compose.yaml
Updated OpenSsl version from 1.1.1d to 1.1.1h
> OpenSsl Update

- fdbserver/storageserver.actor.cpp
This addresses https://github.com/apple/foundationdb/issues/3740
> Add comments for WATCH_OVERHEAD_BYTES

- contrib/Joshua/scripts/bindingTestScript.sh
- contrib/Joshua/scripts/localClusterStart.sh
Added support for specifying the FDB Cluster IP:Port combination
Added support for specifying the number of port from which to choose
Swtiched tabs for spaces to make Markus happy 😃
> Updated BindingTester

- bindings/java/pom.xml.in
(which is apparently still in use)
> Restore pom.xml.in

- build/Dockerfile.devel
This helps with parsing JSON logs
> Install jq in development Docker image

- documentation/sphinx/source/release-notes/release-notes-620.rst
- fdbrpc/RangeMap.h
- fdbserver/DataDistribution.actor.cpp
- fdbserver/DataDistribution.actor.h
- fdbserver/DataDistributionTracker.actor.cpp
- flow/IndexedSet.h
This addresses https://github.com/apple/foundationdb/issues/3824.
> Avoid slow task in ~DataDistributionTracker

- documentation/sphinx/source/release-notes/release-notes-620.rst
The PR is https://github.com/apple/foundationdb/pull/3891
> Add release note for PR 3891

- fdbserver/ConflictSet.h
- fdbserver/Resolver.actor.cpp
- fdbserver/SkipList.cpp
There are no functional changes.
> Add more comments and refactor for SkipList

- fdbserver/DataDistribution.actor.cpp
No heap use after free's seen with this patch after ~4000 tests.
> Fix heap use after free

- flow/Trace.cpp
Currently TraceBatch, although using the mechanism (and output) for the normal logging, does not obey the knob created to cut off lower-severity events. This patch encodes the implicit severity of TraceBatch as it was printed into the log.
One possible complaint about this approach is that it is not compatible with dynamic knob changes. This patch prevents adding events into the batch - not just simply preventing the output of events that have been bactched up. As such, a knob change during runtime could have odd effects -- a tradeoff against the other approach of collecting all events and simply not writing them out.
> Add a check against the current minimum priority for TraceBatch logging

- build/docker-compose.yaml
Reverts apple/foundationdb#3886
> Revert "Run all ctest tests"

- build/Dockerfile
- build/Dockerfile.devel
- build/docker-compose.yaml
- fdbserver/CMakeLists.txt
I tested + rebased https://github.com/apple/foundationdb/pull/3711 against 6.2.  This is the result.
> Rocksdb fixes

- fdbserver/ClusterController.actor.cpp
> Fixed a crash found by nightly correctness.

- fdbserver/fdbserver.actor.cpp
- fdbserver/worker.actor.cpp
- flow/SystemMonitor.cpp
- flow/SystemMonitor.h
This is related to #3987, if not resolving it.
> Attach datacenter id to process, network, machine and memory metrics.

- .gitignore
- fdbserver/LogRouter.actor.cpp
Add peek latency metrics using histogram into log router.
> Add log router peek latency metrics

- fdbclient/NativeAPI.actor.cpp
- fdbclient/ReadYourWrites.actor.cpp
- fdbclient/SpecialKeySpace.actor.cpp
- fdbclient/WriteMap.h
- fdbrpc/genericactors.actor.h
- fdbrpc/sim2.actor.cpp
- fdbserver/ClusterController.actor.cpp
- fdbserver/CommitProxyServer.actor.cpp
- fdbserver/CoordinatedState.actor.cpp
- fdbserver/DataDistribution.actor.cpp
- fdbserver/LogSystemPeekCursor.actor.cpp
- fdbserver/OldTLogServer_4_6.actor.cpp
- fdbserver/OldTLogServer_6_0.actor.cpp
- fdbserver/OldTLogServer_6_2.actor.cpp
- fdbserver/SimulatedCluster.actor.cpp
- fdbserver/StorageCache.actor.cpp
- fdbserver/StorageMetrics.actor.h
- fdbserver/TLogServer.actor.cpp
- fdbserver/storageserver.actor.cpp
- fdbserver/workloads/BackupAndParallelRestoreCorrectness.actor.cpp
- fdbserver/workloads/BackupCorrectness.actor.cpp
- fdbserver/workloads/BackupToDBCorrectness.actor.cpp
- fdbserver/workloads/ConfigureDatabase.actor.cpp
- fdbserver/workloads/DifferentClustersSameRV.actor.cpp
- fdbserver/workloads/Increment.actor.cpp
- fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp
- fdbserver/workloads/VersionStamp.actor.cpp
- flow/Platform.actor.cpp
- flow/coveragetool/Program.cs
We want to analyze TEST macros across multiple github hashes. This is only possible if we can get a primary key. This PR enforces that `Filename + comment` is unique.
> Make test macros enforce unique comments

- fdbserver/MasterProxyServer.actor.cpp
> Expose local transaction rate and limit info on commit proxies.

- documentation/sphinx/source/downloads.rst
Changes in this PR: Update downloads.rst for 6.2.28
- ~~[ ] All variable and function names make sense.~~
- ~~[ ] The code …
> Update downloads.rst for 6.2.28

- CMakeLists.txt
- packaging/msi/FDBInstaller.wxs
- versions.target
Changes in this PR: update installer WIX GUID following release
> update installer WIX GUID following release

- documentation/sphinx/source/client-design.rst
- documentation/sphinx/source/command-line-interface.rst
- documentation/sphinx/source/transaction-profiler-analyzer.rst
FDB does support transaction profiling and analyzing natively. But, since it wasn't documented anywhere, most folks are unaware of it. This adds some basic documentation on the premise and usage.
> Documentation on transaction profiling and analyzing.

- fdbserver/DataDistributionTracker.actor.cpp
This should resolve https://github.com/apple/foundationdb/issues/4012.
> Fix HasBeenTrueFor::set function

- documentation/sphinx/source/release-notes/release-notes-620.rst
> Add 6.2.29 release notes

- fdbserver/KeyValueStoreRocksDB.actor.cpp
This uses the RocksDB `SuggestCompactRange()` API to explicitly request compaction for a key range that has been cleared. This is a workaround for the fact that RocksDB (by default) won't compact a key range that is no longer receiving any writes. This change will increase the write amplification, potentially severely for a workload that clears a range and writes back into that range. For the current workload using RocksDB, we are not bottlenecked on RocksDB and never write into a previously cleared range.
When https://github.com/facebook/rocksdb/issues/7395 is resolved, we can shift to that API as a better (and more tunable) option.
> Attempt to suggest compactions after commit finishes

- fdbserver/worker.actor.cpp
This PR removes the word Ghetto from the repo. It's a strictly trivial change (affects 1 comment), so shouldn't affect anything.
For context, I'm taking a Distributed Systems class at UIUC and for an assignment we were told to look for biased / borderline-racist terminology used in libraries we might work with. While this comment was obviously written comedically, there's not much of a reason for it to stay in the codebase so I figured I might as well help remove it.
Some further context if you're interested: https://www.npr.org/sections/codeswitch/2014/04/27/306829915/segregated-from-its-history-how-ghetto-lost-its-meaning  
- Remove word from comment
- If this PR is ready to be merged (and all checkboxes below are either ticked or not applicable), make this a regular …
> Remove word Ghetto from repo

- fdbrpc/CMakeLists.txt
- flow/config.h.cmake
Fixes a bug that broke our nightlies
> Fix Coro ucontext bug introduced in #4109

- documentation/sphinx/source/downloads.rst
- documentation/sphinx/source/release-notes/release-notes-620.rst
This PR prepares 6.2.29 release.
> Update release notes and download links.

- CMakeLists.txt
- packaging/msi/FDBInstaller.wxs
- versions.target
This PR clean up after 6.2.29 release.
> Post release cleanup 6.2.29

- documentation/sphinx/source/downloads.rst
- documentation/sphinx/source/release-notes/release-notes-630.rst
- Update release notes and download links for 6.3.10
> Update downloads and release notes for 6.3.10

- fdbclient/DatabaseContext.h
- fdbclient/NativeAPI.actor.cpp
- fdbclient/ReadYourWrites.actor.cpp
Adds a new metric for tracking the number of status requests made by a client.
> Add a counter for the number of status requests made by a client

- fdbclient/BackupContainerAzureBlobStore.actor.cpp
> Remove unnecessary copy from BackupContainerAzureBlobStoreImpl::read

- flow/serialize.h
Encapsulates `serializeBytesAcrossBoundary` and `nextBuffer` methods.
> Encapsulate PacketWriter methods

- fdbserver/MutationTracking.cpp
This is a minor performance optimization to prevent unnecessary moves.
> Enable copy elision in debugTagsAndMessageEnabled

- fdbserver/DataDistribution.actor.cpp
> Merge 6.3 to master 1 26 21

- documentation/sphinx/source/release-notes/release-notes-620.rst
- Added a line in release note for `6.2.29` for PR #4166
-
-
~- [ ] All CPU-hot paths are well optimized.~
~- [ ] The proper containers are used (for example `std::vector` vs `VectorRef`).~
~- [ ] There are no new known `SlowTask` traces.~
~- [ ] The code was sufficiently tested in simulation.~
~- [ ] If there are new parameters or knobs, different values are tested in simulation.~
~- [ ] `ASSERT`, `ASSERT_WE_THINK`, and `TEST` macros are added in appropriate places.~
~- [ ] Unit tests were added for new algorithms and data structure that make sense to unit-test~
~- [ ] If this is a bugfix: there is a test that can easily reproduce the bug.~
> Add release note for PR 4166

- fdbrpc/SimExternalConnection.actor.cpp
Minor change to the `SimExternalConnection::read` implementation.
> Improve SimExternalConnection::read performance

- packaging/docker/Dockerfile
This PR is resolves #2386
- Adding debug tools to runtime Docker image
> Adding debug tools to FDB runtime image

- fdbserver/Coordination.actor.cpp
- fdbserver/CoordinationInterface.h
- fdbserver/Knobs.cpp
- fdbserver/Knobs.h
- fdbserver/SimulatedCluster.actor.cpp
- fdbserver/worker.actor.cpp
- flow/error_definitions.h
Reverts apple/foundationdb#4252
This PR resulted in a large number of correctness failures, so we should fix those and then merge it back in.
> Revert "CDs reject requests from external cluster or requests need to be forwarded based on an old forward request."

- CMakeLists.txt
- packaging/msi/FDBInstaller.wxs
- versions.target
This PR is resolves release 6.2.30
Changes in this PR: updates post 6.2.30 release
> Post release cleanup 6.2.30

- fdbclient/StorageServerInterface.h
- Document two fields in storage metrics
> Document two fields in storage metrics

- pull_request_template.md
- Fixes a typo in the PR template.
-
-
> Fix typo in template

- documentation/sphinx/source/release-notes/release-notes-620.rst
- fdbserver/DataDistribution.actor.h
- fdbserver/DataDistributionTracker.actor.cpp
- fdbserver/fdbserver.actor.cpp
- flow/Error.cpp
- flow/Trace.cpp
> Merge Release 6.2 into Release 6.3

- documentation/sphinx/source/release-notes/release-notes-620.rst
- fdbclient/ManagementAPI.actor.cpp
- fdbserver/DataDistribution.actor.h
- fdbserver/DataDistributionTracker.actor.cpp
- flow/Error.cpp
- flow/TLSConfig.actor.cpp
- flow/Trace.cpp
> Merge release-6.3 into master

- fdbclient/ManagementAPI.actor.cpp
> Backport #4285 and 1513df22f3 to release-6.2

- contrib/TestHarness/Program.cs.cmake
Ignore an expected ASAN message in test harness
> Ignore expected ASAN message

- documentation/sphinx/source/api-general.rst
- documentation/sphinx/source/release-notes/release-notes-630.rst
- fdbclient/ManagementAPI.actor.cpp
- fdbclient/MultiVersionTransaction.actor.cpp
- fdbclient/MultiVersionTransaction.h
- fdbclient/vexillographer/fdb.options
- tests/loopback_cluster/run_cluster.sh
- tests/python_tests/multithreaded_client.py
> Merge Release 6.3 into master

- CMakeLists.txt
- cmake/InstallLayout.cmake
- documentation/sphinx/source/release-notes/release-notes-620.rst
- fdbbackup/CMakeLists.txt
- packaging/msi/FDBInstaller.wxs
- versions.target
https://discourse.cmake.org/t/installing-a-symlink-with-a-relative-path-for-rpm/895
closes #2681
> Avoid using relative symlinks to work around cpack bug

- documentation/sphinx/source/release-notes/release-notes-700.rst
> Remove rejected_for_queued_too_long from release notes

- documentation/sphinx/source/api-general.rst
- fdbclient/MultiVersionTransaction.actor.cpp
- fdbclient/vexillographer/fdb.options
This PR resolves PR comments from the multithreaded client work.  AJ, thanks for the feedback.  I think this addresses all the comments (except the golang bindings conversation).
> Multithreaded pr comments

- fdbrpc/LoadBalance.actor.h
- fdbrpc/QueueModel.cpp
- fdbrpc/QueueModel.h
Add documentation to client-side load balancing algorithms.
> Add documentation to client-side load balancing algorithm

- build/docker/centos6/devel/Dockerfile
- build/docker/centos7/devel/Dockerfile
> Add jq and cgdb to development docker image

- fdbbackup/backup.actor.cpp
This PR resolves https://github.com/apple/foundationdb/issues/4265
Added more detail to help messages in fdbbackup and fdbrestore binaries
> Added more help messages to fdbbackup and fdbrestore for incremental backup

- fdbserver/MoveKeys.actor.cpp
Cherry pick 08997d860 back to release-6.2
> Fix comparison of iterators from different containers

- fdbclient/MultiVersionTransaction.actor.cpp
- fdbclient/MultiVersionTransaction.h
- fdbclient/SystemData.cpp
- fdbserver/BackupProgress.actor.cpp
- fdbserver/BackupWorker.actor.cpp
- fdbserver/MasterProxyServer.actor.cpp
This is a non-functional change that just fixes a bunch of compiler-warnings that were introduced relatively recently.
> Fix multiple compiler warnings

- documentation/sphinx/source/release-notes/release-notes-630.rst
- Only release notes are changed. No functional change.
-
-
~~- [ ] All variable and function names make sense.~~
~~- [ ] The …
> Add 6.3.11 release notes for PRs that miss release notes

- documentation/sphinx/source/release-notes/release-notes-620.rst
- fdbclient/BackupContainer.actor.cpp
- fdbclient/FileBackupAgent.actor.cpp
- fdbclient/Knobs.cpp
- fdbrpc/AsyncFileNonDurable.actor.h
- fdbrpc/sim2.actor.cpp
This only contains the recent fixes to backup
> Merge 6.2 changes into 6.3

- bindings/go/src/fdb/generated.go
- documentation/sphinx/source/release-notes/release-notes-630.rst
- fdbclient/MultiVersionTransaction.actor.cpp
- fdbclient/MultiVersionTransaction.h
- fdbclient/SystemData.cpp
- fdbrpc/AsyncFileEIO.actor.h
- fdbrpc/AsyncFileWinASIO.actor.h
- fdbrpc/IAsyncFile.actor.cpp
- fdbrpc/IAsyncFile.h
- fdbrpc/Net2FileSystem.cpp
- fdbrpc/Net2FileSystem.h
- fdbrpc/sim2.actor.cpp
- fdbrpc/simulator.h
- fdbserver/BackupProgress.actor.cpp
- fdbserver/BackupWorker.actor.cpp
- fdbserver/CoroFlow.actor.cpp
- fdbserver/CoroFlowCoro.actor.cpp
- fdbserver/DataDistribution.actor.cpp
- fdbserver/KeyValueStoreRocksDB.actor.cpp
- fdbserver/QuietDatabase.actor.cpp
- flow/IThreadPool.cpp
- flow/IThreadPool.h
- flow/Platform.actor.cpp
- flow/Platform.h
Merges `release-6.3` before the big reformat into master.
> Merge release-6.3 (before the format) into master

- fdbclient/MultiVersionTransaction.actor.cpp
The current code will trigger an `ASSERT` if this happens, and older versions would let you do this but hang if you tried to do anything.
> Multi-version client: throw an error if local client is disabled an there are no external clients

- pull_request_template.md
We decided on a set of new rules for PRs. For that we should change the PR template to reflect that
> Add new PR template for master

- documentation/sphinx/source/release-notes/release-notes-620.rst
- fdbserver/storageserver.actor.cpp
This is the final merge of release-6.2 into release-6.3 before adopting our new branching workflow. Simulation testing is pending.
> Final merge of release-6.2 into release-6.3

- fdbserver/masterserver.actor.cpp
The problem is described in Issue #4376, where a configuration change can
occur before the database is fully recovered, thus triggering the assertion
failure.
Because of the configuration change, the master needs to do the recovery. So
the fix is to trigger the recovery when this happens.
> Fix a race between configuration change and recovery

- documentation/sphinx/source/release-notes/release-notes-620.rst
- documentation/sphinx/source/release-notes/release-notes-630.rst
Update release notes for the bugfixes made in 6.3 (#4526) and 6.2 (#4529)
> Update Release Notes

- fdbserver/workloads/RemoveServersSafely.actor.cpp
The checkSafeExclusions function only ensures the exclusion is safe from the storage server prospective, but does not confirm it is safe in terms of the tlog replication. 
> Fixed simulation timeouts of the RemoveServerSafely workload

- fdbserver/DataDistribution.actor.cpp
This fixes #4493, where `DDTeamCollection::~DDTeamCollection` creates new teams
that hold pointer to the `DDTeamCollection`, thus later causes assertion failure
because the memory is invalid. The creation of new teams is kind of funny: 
- `~DDTeamCollection` cancels all teams, and causes "ZeroTeamsHealthySignalling".
- `zeroHealthyTeams` triggers `teamBuilder` to build new teams
- `DDTeamCollection` becomes invalid memory
- The new team started running and reaches "ZeroTeamsHealthySignalling" and tries to trigger `zeroHealthyTeams`, which is already the invalid memory.
The fix is to cancel teamBuilder at the begining of the `~DDTeamCollection`. …
> Fix DD Assertion failed in canBeSet

- documentation/sphinx/source/release-notes/release-notes-630.rst
- fdbclient/FileBackupAgent.actor.cpp
> Cherry-pick restore log filtering (PR #4554) to release-6.3.

- documentation/sphinx/source/downloads.rst
update download links for release 6.3.12
`:%s/6.3.10/6.3.12/g`
> update links for release 6.3.12

- contrib/apply_copyright.rb
- fdbclient/FDBTypes.h
- fdbrpc/FlowTransport.actor.cpp
- fdbrpc/FlowTransport.h
- fdbserver/CMakeLists.txt
- fdbserver/ptxn/Config.h
- fdbserver/ptxn/ProxyTLogPushMessageSerializer.cpp
- fdbserver/ptxn/ProxyTLogPushMessageSerializer.h
- fdbserver/ptxn/Serializer.h
- fdbserver/ptxn/StorageServerInterface.cpp
- fdbserver/ptxn/StorageServerInterface.h
- fdbserver/ptxn/TLogInterface.cpp
- fdbserver/ptxn/TLogInterface.h
- fdbserver/ptxn/test/Driver.actor.cpp
- fdbserver/ptxn/test/Driver.h
- fdbserver/ptxn/test/FakeProxy.actor.cpp
- fdbserver/ptxn/test/FakeProxy.actor.h
- fdbserver/ptxn/test/FakeStorageServer.actor.cpp
- fdbserver/ptxn/test/FakeStorageServer.actor.h
- fdbserver/ptxn/test/FakeTLog.actor.cpp
- fdbserver/ptxn/test/FakeTLog.actor.h
- fdbserver/ptxn/test/TestSerialization.cpp
- flow/Error.cpp
- flow/Error.h
- flow/serialize.h
- tests/CMakeLists.txt
- tests/ptxn/Driver.toml
- tests/ptxn/Serialization.toml
* An preliminary implementation of Proxy/TLog/Storage Server for teamed partition transaction.
* Test code for the implementation
> Preliminary implementation of Proxy/TLog/StorageServer interface

- fdbclient/FileBackupAgent.actor.cpp
> Typo fix: latestVersion should be lastVersion

- CMakeLists.txt
- versions.target
update version references in CMakeLists.txt and versions.txt for 6.3.12 release
> update version references for 6.3.12

- CMakeLists.txt
- packaging/msi/FDBInstaller.wxs
- versions.target
> Post release cleanup 6.3.12

- fdbserver/TagPartitionedLogSystem.actor.cpp
- fdbserver/masterserver.actor.cpp
> Add some comments on sendInitialCommitToResolvers() 

- tests/TestRunner/TestRunner.py
The directory hierarchy for restart tests encode implicit version constraints that ctest was not previously respecting. It's always safe (although not great for coverage) to fall back to using the current binary in restart tests, so we do that if the constraints don't hold. I tested with ctest locally and inspected the logger output to see that it's using the old binary where constraints allow.
> Respect the version constraints for restart tests in ctest

- tests/TestRunner/TestRunner.py
This is necessary to go into release-6.3 as it fixes restart tests that are currently failing in CI.
I tested with ctest locally and inspected the logger output to see that it's using the old binary where constraints allow.
> Cherry pick pull request #4646

- fdbserver/ClusterController.actor.cpp
This is cherry pick to merge #4516 #4518 and #4528 into release 6.3.
100K Joshua run:
20210320-024313-zhewu_cherrypick-46259655dda637e3  compressed=True data_size=20336966 duration=3952325 ended=100494 fail=3 fail_fast=10 max_runs=100000 pass=99997 priority=100 remaining=0 runtime=2:18:46 sanity=False started=100498 stopped=20210320-050159 submitted=20210320-024313 timeout=5400 username=zhewu_cherrypick
> Cherrypick tlog recruitment logging

- cmake/ConfigureCompiler.cmake
- fdbclient/CoordinationInterface.h
- fdbclient/MonitorLeader.actor.cpp
- fdbserver/workloads/FileSystem.actor.cpp
This catches the bug fixed in #4656 at compile time.
Passed 10k/10k correctness tests.
> Add -Wshift-sign-overflow

- fdbclient/FileBackupAgent.actor.cpp
Joshua test:
20210421-225204-renxuan-f79a4e81fd2ad12f           compressed=True data_size=23013850 duration=4924071 ended=107489 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:26:37 sanity=False started=107490 stopped=20210421-231841 submitted=20210421-225204 timeout=5400 username=renxuan
Simulation:
```
Snapshot:  startVersion=377359226 (1970/01/01.00:01:41+0000)  endVersion=390735575 (1970/01/01.00:01:55+0000)  totalBytes=1200147  restorable=true  expiredPct=0.00
SnapshotBytes: 1200147
MinLogBeginVersion:      362513737 (1970/01/01.00:04:41+0000)
ContiguousLogEndVersion: 404259760 (1970/01/01.00:02:08+0000)
MaxLogEndVersion:        404259760 (1970/01/01.00:02:08+0000)
MinRestorableVersion:    390735575 (1970/01/01.00:01:55+0000)
MaxRestorableVersion: …
```
> Add first consistent version in restore status.

- fdbbackup/backup.actor.cpp
- fdbclient/BackupAgent.actor.h
- fdbclient/FileBackupAgent.actor.cpp
> Rename incrementalBackupOnly to onlyAppyMutationLogs in all restore configs and functions.

- fdbserver/Ratekeeper.actor.cpp
> Add TraceEvent to see whether RateKeeper is too busy to get SS list or fails to get SS list.

- flow/TLSConfig.actor.cpp
fixes #4588
👋 Saw this issue, and figured it'd be a good chance to actually jump in, and contribute something i'd been wanting to do for awhile. I apologize if I did anything wrong!
This change starts logging when a TLS Certificate/Key/CA were specified, and the files themselves could not be read. I'm sure there are other things that can be improved, but this is what the issue mentioned (one step at a time 😄 ).
Overall this makes it so if you're an administrator connecting to a cluster that requires TLS, and accidentally mess up a filename, you can see immediately before looking into something that requires much more effort. Since this probably almost always means you need to exit the shell and resupply arguments.
Since this were just log lines, I didn't feel adding a unit test, or any …
> fdbcli prints error on TLS File not found

- fdbserver/Ratekeeper.actor.cpp
> Cherrypick #4661 to 6.3.

- contrib/grv_proxy_model/grv_test.py
- contrib/grv_proxy_model/plot.py
- contrib/grv_proxy_model/priority.py
- contrib/grv_proxy_model/proxy_model.py
- contrib/grv_proxy_model/rate_model.py
- contrib/grv_proxy_model/ratekeeper_model.py
- contrib/grv_proxy_model/smoother.py
- contrib/grv_proxy_model/workload_model.py
This is a little GRV model that I built to help me evaluate some different approaches to giving out GRVs when limited by ratekeeper.
I'm not sure exactly where it should live, and it may be out of date now, but I'm sharing it here because of its possible utility.
> A model used to quickly simulate various GRV scenarios and algorithms

- documentation/sphinx/source/administration.rst
- documentation/sphinx/source/release-notes/release-notes-620.rst
This PR updates the 6.2 release notes regarding downgrades and operational details to pay attention to.
> Added release notes regarding 6.3 to 6.2 downgrades

- documentation/sphinx/source/administration.rst
- documentation/sphinx/source/release-notes/release-notes-620.rst
Some misaligned headers and spacing corrections made to the documentation files.
> Fix documentation build

- fdbrpc/AsyncFileNonDurable.actor.h
- fdbrpc/sim2.actor.cpp
- flow/flow.h
Reverts apple/foundationdb#4562
> Revert "Actually close files in simulation"

- documentation/sphinx/source/administration.rst
- documentation/sphinx/source/release-notes/release-notes-620.rst
Backport of https://github.com/apple/foundationdb/pull/4674 and https://github.com/apple/foundationdb/pull/4763
> Backport 620 release notes to release-6.3

- documentation/sphinx/source/administration.rst
- documentation/sphinx/source/release-notes/release-notes-620.rst
Backport of https://github.com/apple/foundationdb/pull/4674 and https://github.com/apple/foundationdb/pull/4763
> Backport 620 release notes to release-6.2

- documentation/sphinx/conf.py
Updating copyright footer on web site to be inclusive of 2021
> updated copyright year on web site

- fdbserver/ptxn/test/RealTLog.actor.cpp
- fdbserver/ptxn/test/RealTLog.actor.h
- tests/CMakeLists.txt
- tests/ptxn/RealTLog.toml
- tests/ptxn/RealTLogGroup.toml
Support tlog groups and tags in unit test.
> Update realtlog to support multiple tags/log servers

- fdbclient/FileBackupAgent.actor.cpp
This solves issue #4849.
The current behavior is blindly change the configuration, which is undesirable if using old backups. This fix will only make the configuration change if partitioned logs are specified in the `fdbbackup` command line.
Correctness has a failure of non-backup test:
20210521-234442-jingyu_zhou-e8bb7698ea0330cc       compressed=True data_size=23417523 duration=3531346 ended=101427 fail=1 fail_fast=10 max_runs=100000 pass=100128 priority=100 remaining=0 runtime=0:20:04 sanity=False started=102209 stopped=20210522-000446 submitted=20210521-234442 timeout=5400 username=jingyu_zhou
I manually verified `fdbbackup` command line will only change the configuration when passing `--partitioned_log_experimental` flag. …
> Only enable backup worker when using partitioned logs

- bindings/c/test/unit/unit_tests.cpp
We saw this test fail due to a retriable error in our CI, so I made sure that the tests pass when client buggify is enabled. "fdb_transaction_set_read_version future_version" still doesn't pass with client buggify enabled, since client buggify can inject an error that's not future_version. I also restructured the cli parsing so that we can pass doctest arguments.
> Handle retriable errors better in fdb_c_unit_tests

- fdbserver/FDBExecHelper.actor.cpp
Backporting #4866 to 6.3, as it fixes a simulation failure.
Failed 1 out of 100k correctness tests, and the failure should be unrelated (DifferentClustersSwitchNotComplete) on tests/slow/DifferentClustersSameRV.txt
> 6.3 Cherrypick - Removing spaces in SevWarn trace event names

- fdbserver/FDBExecHelper.actor.cpp
Backporting https://github.com/apple/foundationdb/pull/4866 to 7.0, as it fixes a simulation failure.
> 7.0 Cherrypick - Removing spaces in SevWarn trace event names

- flow/Error.cpp
- flow/Error.h
- flow/Trace.cpp
- flow/Trace.h
This backports https://github.com/apple/foundationdb/pull/4741.
> Backport ErrorKind trace field to release 6.3

- documentation/sphinx/source/release-notes/release-notes-630.rst
Add release notes for PR #4863
> Add release notes for PR 4863

- fdbrpc/AsyncFileCached.actor.h
Cherry pick https://github.com/apple/foundationdb/pull/4900 to release-6.3
Fixes bug introduced in #4893 and resolves #4897.
The refactoring of AsyncFileCached changed the implementation of `open_impl` so that it wasn't modifying anything in `openFiles` directly. In the case where a file was opened synchronously, this code path had been responsible for implicitly inserting an entry into the map.
This fix changes `open` so that an entry is inserted into the map regardless of whether it is ready.
This bug is not currently reproducible in simulation (see #4901), so the fix was verified with a real-world cluster. Previously configuring a cluster would trigger assertion failures, and it now does not. …
> Fix: when a file open completes synchronously, it wasn't being stored in the openFiles map (release-6.3)

- fdbclient/FDBTypes.h
- fdbclient/ManagementAPI.actor.cpp
- fdbrpc/Stats.h
- fdbserver/DataDistributionTracker.actor.cpp
- fdbserver/DeltaTree.h
- fdbserver/GrvProxyServer.actor.cpp
- fdbserver/LogRouter.actor.cpp
- fdbserver/RadixTree.h
- fdbserver/SkipList.cpp
- fdbserver/VersionedBTree.actor.cpp
- fdbserver/sqlite/sqlite3.amalgamation.c
- fdbserver/storageserver.actor.cpp
- flow/Arena.h
- flow/FastAlloc.cpp
- flow/Histogram.cpp
Found by building with `-DUSE_UBSAN=ON` (and clang11), and running simulation tests. Now passes ~50k simulation tests with no failures. I manually compared a few simulations before and after this change and confirmed that they have the same unseed. Each commit explains the particular UB it's fixing.
> Fix several instances of undefined behavior

- documentation/sphinx/source/release-notes/release-notes-700.rst
Also fixes a bad link.
No testing performed on these documentation only changes besides the PR build.
> Add some release notes for 7.0 changes

- documentation/sphinx/source/release-notes/release-notes-700.rst
> Add a release note for PR 3759

- fdbserver/GrvProxyServer.actor.cpp
There are several issues in the current code:
1. When there's network latency (>50ms) between proxies and ratekeeper, proxy will not get rate from ratekeeper, both normal txns and batch txns rate will be set to 0 immediately;
2. When batch txns are throttled, they are still counted in txnRequestIn. When a lot of batch txns are throttled, that will make txnRequestIn keep increasing, which then throttle system and normal txns.
This pr changes the behavior to:
1. When lease expires, instead of setting rate to 0 immediately, we set smoothRate.setTotal(0). The smoothing window there is 2 seconds;
2. For batch txns, only increase txnRequestIn if txns are put into the batch queue.
20210609-192400-renxuan-8aef50536ecebcd1           compressed=True data_size=23751929 duration=3939665 ended=101298 …
> Fix batch txn throttling.

- fdbserver/GrvProxyServer.actor.cpp
This is patching #4938 to 7.0.
There are several issues in the current code:
1. When there's network latency (>50ms) between proxies and ratekeeper, proxy will not get rate from ratekeeper, both normal txns and batch txns rate will be set to 0 immediately;
2. When batch txns are throttled, they are still counted in txnRequestIn. When a lot of batch txns are throttled, that will make txnRequestIn keep increasing, which then throttle system and normal txns.
This pr changes the behavior to:
1. When lease expires, instead of setting rate to 0 immediately, we set smoothRate.setTotal(0). The smoothing window there is 2 seconds;
2. For batch txns, only increase txnRequestIn if txns are put into the batch queue.
20210610-002654-renxuan-39051f0f812336a1           compressed=True data_size=23365110 …
> Fix batch txn throttling (release-7.0).

- fdbserver/storageserver.actor.cpp
The hard part was actually figuring out how everything worked. So I'm also adding comments about how data distribution and updates work in storage server.
> Metrics to compare the bandwidth used by data distributions and updates

- fdbclient/S3BlobStore.actor.cpp
- fdbclient/S3BlobStore.h
This fixes merge conflicts from https://github.com/apple/foundationdb/pull/3822.
> [fdbbackup] make credentials optional

- fdbserver/DataDistribution.actor.cpp
- fdbserver/DataDistributionQueue.actor.cpp
- fdbserver/Knobs.cpp
- fdbserver/tester.actor.cpp
- fdbserver/workloads/ConsistencyCheck.actor.cpp
- fdbserver/workloads/workloads.actor.h
Reverts apple/foundationdb#4929
Find bugs in nightly correctness, so need to fix it
> Revert "Properly set simulation test for perpetual storage wiggle and bug fixing"

- fdbserver/storageserver.actor.cpp
Squash PR #4907 and bring it to 6.3 branch to investigate traffic in current production.
> Metrics to compare the bandwidth used by data distributions and updates (bring PR #4907 to 6.3)

- documentation/sphinx/source/command-line-interface.rst
- documentation/sphinx/source/operations.rst
- documentation/sphinx/source/tss.rst
- fdbcli/fdbcli.actor.cpp
Added documentation for TSS.
I "tested" it by looking at my branch in github and verifying that the formatted documentation looks visually correct.
> Added TSS documentation

- documentation/sphinx/source/release-notes/release-notes-700.rst
> Add 7.0 release notes

- packaging/docker/Dockerfile.eks
- packaging/docker/misc/flamegraph.sha256sum
This is a cherry pick of eac54c36b82caba16c727311bbb1756db5b66daa from master to 7.0
This does not change the released binaries, but it does allow us to gather CPU profiles during performance testing.
> Add perl + flamegraph to EKS docker images

- documentation/sphinx/source/release-notes/release-notes-700.rst
> Add 7.0 release notes (to release-7.0)

- fdbclient/DatabaseConfiguration.cpp
- flow/FileTraceLogWriter.cpp
- flow/FileTraceLogWriter.h
- flow/Histogram.cpp
- flow/Histogram.h
- flow/ITrace.h
- flow/Platform.actor.cpp
- flow/Platform.h
- flow/SystemMonitor.cpp
- flow/SystemMonitor.h
- flow/Trace.cpp
- flow/Trace.h
- flow/flow.cpp
- flow/flow.h
- flow/network.cpp
- flow/network.h
> Remove unnecessary std::string copies from flow

- contrib/TestHarness/Program.cs.cmake
> Respect JOSHUA_SEED if set

- documentation/sphinx/source/release-notes/release-notes-700.rst
This is a backport of #4915 and #4926 
Adds some release notes for 7.0 changes and fixes a bad link.
No testing performed on these documentation only changes besides the PR build.
> Add some release notes for 7.0 changes (release-7.0)

- tests/TestRunner/TestRunner.py
Make CI don't report injected failure.
> add injected fault check

- fdbserver/VersionedBTree.actor.cpp
Fixed a HEAP use after free bug. 
Passes manual valgrind test with the failing seed. 
Passes 10k successful Joshua test runs. 
> Fix a heap use after free issue.

- documentation/sphinx/source/release-notes/release-notes-630.rst
> 6.3.15 release notes.

- CMakeLists.txt
- documentation/sphinx/source/downloads.rst
update version strings in CMakeLists.txt and documentation/sphinx/source/downloads.rst
> update version information for 6.3.15 release

- documentation/sphinx/source/release-notes/release-notes-630.rst
> 6.3.15 release notes (release-7.0).

- documentation/sphinx/source/release-notes/release-notes-630.rst
> 6.3.15 release note (release-6.3).

- documentation/sphinx/source/release-notes/release-notes-700.rst
Added line on TSS.
I'll cherry-pick to 7.0 once merged and make a separate PR.
I "tested" by looking at the markdown file in github.
> Added TSS to 7.0 release notes

- CMakeLists.txt
- documentation/sphinx/source/downloads.rst
- packaging/msi/FDBInstaller.wxs
update version in CMakeLists.txt documentation/sphinx/source/downloads.rst and update WIX installer GUID
> Post release cleanup 6.3.15

- documentation/sphinx/source/release-notes/release-notes-700.rst
Updated the 7.0 release notes with multiple items from the last year
> Updated 7.0 release notes

- documentation/sphinx/source/command-line-interface.rst
- documentation/sphinx/source/operations.rst
- documentation/sphinx/source/perpetual-storage-wiggle.rst
> Add document for perpetual storage wiggle 

- fdbserver/GrvProxyServer.actor.cpp
Backporting #5044 to release 7.0.
1. Add the count of # of getRateInfo() and # of leaseTimeout;
2. Add SystemGRVQueueSize, DefaultGRVQueueSize and BatchGRVQueueSize.
20210622-181025-renxuan-8a35ea3aabd1f398           compressed=True data_size=23832715 duration=3382951 ended=104088 fail_fast=10 max_runs=100000 pass=100001 priority=100 remaining=0 runtime=0:25:16 sanity=False started=104918 stopped=20210622-183541 submitted=20210622-181025 timeout=5400 username=renxuan
> Add a few ProxyStats fields (release-7.0).

- fdbserver/GrvProxyServer.actor.cpp
1. Add the count of # of getRateInfo() and # of leaseTimeout;
2. Add SystemGRVQueueSize, DefaultGRVQueueSize and BatchGRVQueueSize.
20210622-171956-renxuan-5d57b672e4560cfe           compressed=True data_size=24730837 duration=5707054 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:34:31 sanity=False started=100006 stopped=20210622-175427 submitted=20210622-171956 timeout=5400 username=renxuan
> Add a few ProxyStats fields.

- fdbserver/MasterProxyServer.actor.cpp
Backporting #5044 to release 6.3.
1. Add the count of # of getRateInfo() and # of leaseTimeout;
2. Add SystemGRVQueueSize, DefaultGRVQueueSize and BatchGRVQueueSize.
20210622-184341-renxuan-0ddd0c401ef7ab4b           compressed=True data_size=21419492 duration=5174203 ended=100609 fail_fast=10 max_runs=100000 pass=100024 priority=100 remaining=0 runtime=0:17:48 sanity=False started=100796 stopped=20210622-190129 submitted=20210622-184341 timeout=5400 username=renxuan
> Add a few ProxyStats fields (release-6.3).

- fdbclient/SystemData.cpp
- fdbclient/SystemData.h
- fdbserver/DataDistribution.actor.cpp
- fdbserver/MoveKeys.actor.cpp
- fdbserver/MoveKeys.actor.h
> Add storage team IDs and create related maps

- CMakeLists.txt
- packaging/msi/FDBInstaller.wxs
update versions after 6.3.16 release
> Post release cleanup 6.3.16

- documentation/tutorial/tutorial.actor.cpp
Otherwise, the Assertion in `ReplyPromiseStream` will fail.
> add setByteLimit in tutorial

- fdbmonitor/fdbmonitor.cpp
Was running ASAN for other reasons, and these showed up.
> fdbmonitor leak fixes

- documentation/sphinx/source/request-tracing.rst
- documentation/sphinx/source/special-keys.rst
- documentation/sphinx/source/visibility.rst
- fdbclient/vexillographer/fdb.options
Adds documentation for tracing. Tested by running `ninja docpreview` and making sure things look alright.
> Add tracing documentation

- documentation/sphinx/source/index.rst
- documentation/sphinx/source/redwood.rst
- documentation/sphinx/source/release-notes/release-notes-700.rst
- documentation/sphinx/source/request-tracing.rst
- documentation/sphinx/source/visibility.rst
Cherry pick #5027 for consolidated 7.0 Release Notes
> Cherry pick 7.0 release notes

- flow/Platform.actor.cpp
> Set error kind to BugDetected for Crash trace events

- documentation/sphinx/source/index.rst
- documentation/sphinx/source/request-tracing.rst
- documentation/sphinx/source/special-keys.rst
- documentation/sphinx/source/visibility.rst
- fdbclient/vexillographer/fdb.options
Cherry pick of #5085.
Adds documentation for tracing. Tested by running `ninja docpreview` and making sure things look ok.
> Add tracing documentation (release-7.0)

- fdbclient/BackupAgent.actor.h
- fdbclient/BackupAgentBase.actor.cpp
- fdbclient/FileBackupAgent.actor.cpp
> Move BackupAgentBase method implementations to .cpp file

- fdbserver/Knobs.cpp
- fdbserver/Knobs.h
- fdbserver/OldTLogServer_6_2.actor.cpp
- fdbserver/TLogServer.actor.cpp
Backporting #5117 and #5129 to release 7.0.
> Add trace event to tLog pop for release-7.0

- fdbserver/ClusterController.actor.cpp
Trace needs the field name to be Camel-Case.
> fix invalid trace detail name

- contrib/TestHarness/Program.cs.cmake
Cherry pick https://github.com/apple/foundationdb/pull/4940 to release-7.0
Closes #4913
> Respect JOSHUA_SEED if set (release-7.0)

- bindings/java/src/integration/com/apple/foundationdb/CycleMultiClientIntegrationTest.java
- bindings/java/src/tests.cmake
Change the version to 710.
Add CycleMultiClientIntegrationTest
> Cherry pick 871b098e95b3107e216a986cfec4225c65b54252 from 6.3

- bindings/java/src/integration/com/apple/foundationdb/CycleMultiClientIntegrationTest.java
- bindings/java/src/tests.cmake
> Add CycleMultiClientIntegrationTest to release 7.0

- bindings/java/src/integration/com/apple/foundationdb/SidebandMultiThreadClientTest.java
- bindings/java/src/tests.cmake
backporting https://github.com/apple/foundationdb/pull/5201
> Add SidebandMultiThreadClientTest (to release6.3)

- bindings/java/src/integration/com/apple/foundationdb/SidebandMultiThreadClientTest.java
- bindings/java/src/tests.cmake
backporting https://github.com/apple/foundationdb/pull/5197
> Add SidebandMultiThreadClientTest (to release 7.0)

- fdbclient/CMakeLists.txt
> Fix missing dependency of `fdbclient` on generated header(s) from fdb_c.

- fdbserver/fdbserver.actor.cpp
> Simfdb cleanup did not recognize the unittests directory

- .gitignore
Ignores VSCode workspace definition files.
> Add VSCode workspace file pattern to .gitignore.

- documentation/sphinx/source/ha-write-path.rst
> Fix broken image link

- fdbserver/VersionedBTree.actor.cpp
> increment the Redwood METAKEY VERSION

- packaging/docker/sidecar/entrypoint.bash
- packaging/docker/sidecar/sidecar.py
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/824 the idea is to move the script completely into this repository. This PR just updates the sidecar script to the latest state.
The idea is to have these changes in the next `6.3` release of Foundationdb.
> Update sidecar to match latest changes in operator

- bindings/java/src/main/com/apple/foundationdb/KeySelector.java
Addresses the easy part of #5190
> Make orEquals() public

- contrib/TestHarness/Program.cs.cmake
> Ignore warning from valgrind about F_SET_RW_HINT usage.

- contrib/TestHarness/Program.cs.cmake
> Move stderr exception checking so that ignored output does not count against error limit

- flow/IThreadPoolTest.actor.cpp
> Fix MacOS build, symbol was only defined on linux.

- documentation/sphinx/source/release-notes/release-notes-630.rst
Release notes for new changes in 6.3.17.
> Release notes for 6.3.17

- documentation/sphinx/source/release-notes/release-notes-630.rst
Cherry pick 6.3.17 release note to release-7.0
> Cherry pick 6.3.17 release note to release-7.0

- documentation/sphinx/source/release-notes/release-notes-630.rst
Cherry pick 6.3.17 release note to release-6.3
> Cherry pick 6.3.17 release note to release-6.3

- fdbbackup/FileConverter.h
- fdbbackup/FileDecoder.actor.cpp
> Add more options to fdbdecode

- fdbserver/worker.actor.cpp
When checking whether an endpoint is in the same DC as the worker during a health checking, worker goes though all the roles in ServerDbInfo. However, satellite and remote TLog interface may not present. So we need to account for this case.
Update unit test to cover this case.
100k joshua run: 20210731-045236-zhewu_5314-6a2d042e39adcc9c
> Account for the case where TLogInterface may not present in ServerDbInfo in worker health monitor

- fdbserver/QuietDatabase.actor.cpp
- fdbserver/tester.actor.cpp
> add information print in simulation test

- fdbserver/DataDistribution.actor.cpp
> remove unused variables

- flow/Knobs.cpp
This fixes potential memory issues in calls to `parseIntegral`.
> Replace parseIntegral with standard parsing functions

- documentation/sphinx/source/release-notes/release-notes-630.rst
> Release note 6.3.18

- documentation/sphinx/extensions/rubydomain.py
Fix the docs build by cherry-picking some fixes for python3 that were
made upstream.
> Cherry-pick python3 changes from master

- fdbserver/DataDistribution.actor.cpp
- fdbserver/DataDistributionQueue.actor.cpp
Disables data movement (anything that makes RelocateShard requests).
> Disable data movement for demo

- fdbserver/MutationTracking.cpp
MutationTracking can now track 0 or more ranges, and will match on any mutations to any part of any of the ranges.
> Added range tracking support to MutationTracking.

- bindings/java/src/integration/com/apple/foundationdb/CycleMultiClientIntegrationTest.java
> Setup cycleTest in the same txn(release-6.3)

- bindings/java/src/integration/com/apple/foundationdb/RepeatableReadMultiThreadClientTest.java
> Add RepeatableReadMultiThreadClientTest(release-7.0)

- bindings/java/src/integration/com/apple/foundationdb/RepeatableReadMultiThreadClientTest.java
- bindings/java/src/tests.cmake
apply https://github.com/apple/foundationdb/pull/5211 to 6.3
> Add RepeatableReadMultiThreadClientTest(release-6.3)

- fdbclient/NativeAPI.actor.cpp
- fdbclient/StorageServerInterface.cpp
- fdbserver/DataDistribution.actor.cpp
- fdbserver/MoveKeys.actor.cpp
- fdbserver/storageserver.actor.cpp
https://github.com/apple/foundationdb/pull/5347 for master. Passed 100k correctness tests on master, in addition to the 250k on release-7.0.
> Various TSS improvements from snowblower testing

- fdbserver/ClusterController.actor.cpp
- fdbserver/TesterInterface.actor.h
- fdbserver/WorkerInterface.actor.h
- fdbserver/masterserver.actor.cpp
- fdbserver/tester.actor.cpp
- fdbserver/worker.actor.cpp
- fdbserver/workloads/ReadWrite.actor.cpp
- fdbserver/workloads/workloads.actor.h
> Add const qualifiers to several parameters in `worker.actor.cpp`

- fdbserver/KeyValueStoreRocksDB.actor.cpp
Update RocksDB's log directory to fdb log directory. An AutoRollLogger will be created and writes logs to the directory. 
File name will look like
root_simfdb_f1330ae89d5dfc8d0a1682343ae2021f_storage-828a401e15d0543be38e15ee3f59fcf1.rocksdb_LOG
> Update log directory to server log directory.

- fdbserver/CommitProxyServer.actor.cpp
Reads the txnState from TxnStateRequest in CommitProxyServer, collects the
storage server to team mapping along with keyServers, and updates
ServerCacheInfo accordingly.
Joshua Run:
```
20210818-071452-vishesh-f877cb9982f43ee5           compressed=True data_size=26677056 duration=4691298 ended=102455 fail_fast=10 max_runs=100000 pass=100001 priority=100 remaining=0 runtime=0:24:02 sanity=False started=102459 stopped=20210818-073854 submitted=20210818-071452 timeout=5400 username=vishesh
```
> Add StorageTeams into ServerCacheInfo

- fdbclient/SpecialKeySpace.actor.cpp
- fdbserver/SigStack.cpp
- packaging/msi/FDBInstaller.wxs.cmake
Add Windows specific code for system time
> Fix windows build with system time

- fdbserver/ClusterController.actor.cpp
Example logs:
```
trace.0.0.0.0.0.1629275119.mlVgdn.0.1.xml:<Event Severity="10" Time="15.409136" DateTime="2021-08-18T08:25:19Z" Type="TimeKeeperCommit" Machine="2.0.1.1:1" ID="5f132f639a4ad17b" Version="407228" Timestamp="15" ThreadID="9788943724220871241" LogGroup="default" Roles="CC,CP,DD,GP,MS,RK,RV,SS,TL" />
trace.0.0.0.0.0.1629275119.mlVgdn.0.1.xml:<Event Severity="10" Time="27.321964" DateTime="2021-08-18T08:25:19Z" Type="TimeKeeperCommit" Machine="2.0.1.1:1" ID="0f02ea8bcbc12446" Version="6786252" Timestamp="27" ThreadID="9788943724220871241" LogGroup="default" Roles="BK,CC,CP,DD,GP,MS,RK,RV,SS,TL" />
trace.0.0.0.0.0.1629275119.mlVgdn.0.1.xml:<Event Severity="10" Time="38.616454" DateTime="2021-08-18T08:25:20Z" Type="TimeKeeperCommit" Machine="2.0.1.1:1" ID="574b788a0ab225f6" …
```
> Add version and timestamp to TimeKeeperCommit event.

- contrib/Joshua/scripts/correctnessTest.sh
- contrib/TestHarness/Program.cs.cmake
- fdbrpc/sim2.actor.cpp
* 8cb591e
* cb7a265
* 4a74baa
in order to use Joshua ensemble without buggify or fault injection use the following commands:
```
j start --tarball [package] --command "./joshua_test --fault-injection-disabled --buggify-disabled"
```
**Passed 100K Joshua test**
```
20210819-001753-sajjad-880613db8773613b       
compressed=True 
data_size=26375438
duration=4580340 
ended=102380 
fail_fast=10 
max_runs=100000 
pass=100002 
priority=100
remaining=0 
runtime=0:25:06 
sanity=False 
started=102613 
stopped=20210819-004259 
submitted=20210819-001753 
timeout=5400 
username=sajjad
```
If this PR is …
> Fault injection Activation

- fdbserver/ClusterController.actor.cpp
https://github.com/apple/foundationdb/pull/5408
> [cherrypick] Add version and timestamp to TimeKeeperCommit event. 

- flow/actorcompiler/Actor checklist.txt
> fix spelling error

- fdbserver/ClusterController.actor.cpp
https://github.com/apple/foundationdb/pull/5408
> [cherrypick] Add version and timestamp to TimeKeeperCommit event.

- fdbserver/ClusterController.actor.cpp
> Cherry pick CC health monitor cancellation fix to release 7.0

- fdbserver/ClusterController.actor.cpp
> Cherry pick CC health monitor cancellation fix to release 6.3

- fdbserver/KeyValueStoreRocksDB.actor.cpp
We were not properly handling errors returned from RocksDB (e.g. timeouts or corruption).
> Fix error handling of reads.

- flow/singleton.h
Most executables crash on Windows before attempting the main function. This occurs when std::mutex::lock() is invoked while initializing the program (static or global variables). 
For now, this crash is only related to the singleton class. It appeared after adding `transactionLineageCollector` and `nameLineageCollector` to native API which use singleton.
> Fix Windows std::mutex crash

- fdbserver/ClusterController.actor.cpp
> Add trace event for role recruitment by CC (for release-7.0)

- fdbserver/ClusterController.actor.cpp
> Add trace event for role recruitment by CC (for release-6.3)

- fdbserver/CommitProxyServer.actor.cpp
- fdbserver/LogSystem.h
- fdbserver/ProxyCommitData.actor.h
- fdbserver/TagPartitionedLogSystem.actor.cpp
(cherry picked from commit 8609b45354a8fa573ab589057ee0e4f97eb54c27)
> [cherry-pick] Add histograms to CommitProxyServer. (#5299)

- fdbclient/DatabaseConfiguration.h
- fdbserver/ClusterController.actor.cpp
- fdbserver/CommitProxyServer.actor.cpp
- fdbserver/MoveKeys.actor.cpp
- fdbserver/MoveKeys.actor.h
- fdbserver/SimulatedCluster.actor.cpp
- fdbserver/TLogGroup.actor.cpp
- fdbserver/TLogGroup.actor.h
- fdbserver/masterserver.actor.cpp
> Map split keys to storage team IDs

- fdbserver/CommitProxyServer.actor.cpp
> Refactor TxnStateRequest handler in commitProxyServerCore

- fdbservice/ThreadPool.h
> use make_unique instead of new - exception safe

- fdbserver/TagPartitionedLogSystem.actor.cpp
- fdbserver/masterserver.actor.cpp
Fix bugs with TLOG_NEW_INTERFACE=true
> Fix bugs with TLOG_NEW_INTERFACE=true

- fdbserver/LogSystemConfig.h
- fdbserver/TagPartitionedLogSystem.actor.cpp
- fdbserver/ptxn/TLogInterface.cpp
- fdbserver/ptxn/TLogInterface.h
* 3cfadbf69 - Fix array out of bound error
* 78fa61075 - Fix invalid format string
* c8b44f7ff - Fix endpoint serializations
> Fix integration bugs

- cmake/CompileBoost.cmake
> Cherrypick CompileBoost.cmake to ptxn branch

- fdbserver/DiskQueue.actor.cpp
- fdbserver/ptxn/test/CommitUtils.cpp
- fdbserver/ptxn/test/CommitUtils.h
- fdbserver/ptxn/test/TestSerialization.cpp
> Remove unused code to fix clang errors

- fdbclient/SystemData.cpp
- fdbclient/SystemData.h
- fdbserver/CommitProxyServer.actor.cpp
- fdbserver/masterserver.actor.cpp
> Send SS -> TeamId mutations in TxnStateRequest

- fdbserver/SimulatedCluster.actor.cpp
> Fix reading the disableTss option

- contrib/TestHarness/Program.cs.cmake
> Cherry-pick 5540 Return if no available binary in the given range

- fdbclient/SystemData.cpp
- fdbclient/SystemData.h
- fdbserver/ApplyMetadataMutation.cpp
- fdbserver/CommitProxyServer.actor.cpp
- fdbserver/MoveKeys.actor.cpp
This allows us to get source/destination team IDs when applying a keyServer
changes, i.e., update proxy's keyInfo data with teams.
20210906-163653-jzhou-a7642d371a5a5d9b             compressed=True data_size=20941625 duration=4965563 ended=102020 fail_fast=10 max_runs=100000 pass=100149 priority=100 remaining=0 runtime=0:21:29 sanity=False started=102568 stopped=20210906-165822 submitted=20210906-163653 timeout=5400 username=jzhou
> Add team IDs to keyServer values

- packaging/docker/sidecar/sidecar.py
> Fix kubernetes sidecar

- fdbserver/worker.actor.cpp
> Use setUnconditional in worker's health monitor (release-6.3)

- fdbserver/CMakeLists.txt
- fdbserver/LogSystem.cpp
- fdbserver/LogSystem.h
- fdbserver/LogSystemConfig.cpp
- fdbserver/LogSystemConfig.h
- fdbserver/TagPartitionedLogSystem.actor.cpp
- fdbserver/TagPartitionedLogSystem.actor.h
Extract class methods out of classes for
*  LogSystemConfig.h
*  LogSystem.h
* TagPartitionedLogSystem.h
tested by 10000 correctness runs
> Extract class methods out of classes

- fdbserver/ptxn/TLogPeekCursor.actor.cpp
- fdbserver/ptxn/TLogPeekCursor.actor.h
> TLogPeekCursor ServerPeekCursor use ptxn/MessageSerializer

- fdbclient/DatabaseConfiguration.cpp
Cherry-pick of https://github.com/apple/foundationdb/pull/5624. 
> fixing db config parenthesis

- fdbserver/workloads/StreamingRangeRead.actor.cpp
> fix compilation error

- bindings/c/CMakeLists.txt
Cherry pick of #5451 to `release-7.0`.
> Fix OPEN_FOR_IDE build (release-7.0)

- documentation/sphinx/source/release-notes/release-notes-630.rst
Added #5461 to the release-notes
> Complete release notes for 6.3.20

- packaging/docker/sidecar/sidecar.py
Backport changes from the release-6.3 branch to the master branch based on: https://github.com/apple/foundationdb/pull/5270#pullrequestreview-725594484 this PR ensures that the changes in both branches are the same for the sidecar.
I build the sidecar locally and run the container (started up).
> Fix kubernetes sidecar master

- fdbserver/FDBExecHelper.actor.cpp
Fixed minor bug in `spawnProcess` that caused it to block.
> spawnProcess blocking bug fix

- fdbserver/GrvProxyServer.actor.cpp
- flow/Histogram.cpp
Add histogram in GrvProxyServer. Backporting #5278.
> Add histogram in GrvProxyServer (release-7.0).

- fdbserver/MasterProxyServer.actor.cpp
- flow/Histogram.cpp
original change https://github.com/apple/foundationdb/pull/5278
> [cherrypick]  Add GRV related histograms.

- CMakeLists.txt
- contrib/pkg_tester/__snapshots__/test_fdb_pkgs.ambr
- documentation/sphinx/source/downloads.rst
We're going to create a 6.3.21 release, so we need to increase the version number in the code (6.3.20 has already been tagged)
> Increase version to 6.3.21

- fdbserver/ClusterController.actor.cpp
Throwing errors from simulation only code was changing recruitment behavior. This PR adds asserts if any simulation only code ever throws an error.
Passed 100k correctness tests
> Simulation only code could change the behavior of the cluster controller

- flowbench/BenchHash.cpp
- flowbench/BenchMem.cpp
- flowbench/CMakeLists.txt
> Separate out memory benchmarks in flowbench

- documentation/sphinx/source/api-common.rst.inc
- documentation/sphinx/source/api-python.rst
https://github.com/apple/foundationdb/issues/5583
> Add documation about network options.

- fdbserver/ptxn/TLogServer.actor.cpp
Previously there are duplicate call to commitQueue, which is a bug.
> fix /fdbserver/ptxn/test/commit_peek test

- fdbserver/TLogServer.actor.cpp
Fix corner-case where poppedVersion races with wait on new mutations in tLog.
Taken from PR5058.
> Fix corner-case where poppedVersion races with wait on new mutations in tLog

- fdbrpc/fdbrpc.h
- fdbserver/DataDistribution.actor.cpp
> Improve tracing in `ddSnapCreateCore`

- packaging/docker/Dockerfile.eks
> Add libsanitizer to fdb image.

- fdbserver/masterserver.actor.cpp
Capture the following metrics on the sequencer:
- Commit requests that are invoking waitForPrev
- Commit requests that are not invoking waitForPrev
- Time spent waiting for prevVersions to be committed (in "waitForPrev()")
Testing:
- Ran simulation tests: 20211105-213536-sre-34cc704af9548c7e. No failures.
> Version vector prototype: capture waitForPrev-related metrics

- documentation/sphinx/source/transaction-tagging.rst
Backports https://github.com/apple/foundationdb/pull/5913
> Update tag throttling documentation (release-7.0)

- fdbclient/vexillographer/fdb.options
> Fix typo in fdb.options

- fdbclient/vexillographer/fdb.options
Cherry-pick of #5938 for release-6.3, related to #5937
>  Cherry pick Fix typo in fdb.options for release-6.3

- fdbserver/KeyValueStoreRocksDB.actor.cpp
https://github.com/apple/foundationdb/pull/5396
> Update log directory to server log directory. (release-7.0)

- fdbserver/KeyValueStoreRocksDB.actor.cpp
https://github.com/apple/foundationdb/pull/5433
> Fix error handling of reads. (release-7.0)

- fdbserver/KeyValueStoreRocksDB.actor.cpp
https://github.com/apple/foundationdb/pull/5515
> Log SubCode and Severity for RocksDB erros. (release 7.0)

- bindings/c/test/unit/unit_tests.cpp
Verified by running ctest (before and after the fix) with ASAN
> Fix (test only) heap use after free

- bindings/c/test/unit/unit_tests.cpp
- documentation/sphinx/source/request-tracing.rst
- fdbclient/DatabaseContext.h
- fdbclient/NativeAPI.actor.cpp
- fdbclient/vexillographer/fdb.options
- fdbserver/GrvProxyServer.actor.cpp
- fdbserver/storageserver.actor.cpp
- flow/Knobs.cpp
- flow/Tracing.actor.cpp
- flow/Tracing.h
Fixes some issues related to sampling of distributed traces. Cherry pick of #5903.
Passed 99,999/100,000 correctness tests. The one failure was a timeout from `to_6.3.13_until_7.0.0/CycleTestRestart-1.txt`. It looks like there have been recent failures for this test on the 7.0 branch.
> Improve distributed trace sample collection (release-7.0)

- cmake/CompileRocksDB.cmake
- cmake/FindRocksDB.cmake
- fdbserver/KeyValueStoreRocksDB.actor.cpp
https://github.com/apple/foundationdb/pull/5605
> Enforcing 6.22.1 rocksdb version. (release 7.0)

- fdbserver/IKeyValueStore.h
- fdbserver/KeyValueStoreCompressTestData.actor.cpp
- fdbserver/KeyValueStoreMemory.actor.cpp
- fdbserver/KeyValueStoreRocksDB.actor.cpp
- fdbserver/KeyValueStoreSQLite.actor.cpp
- fdbserver/VersionedBTree.actor.cpp
- fdbserver/storageserver.actor.cpp
https://github.com/apple/foundationdb/pull/5785
> Add an enum to IKeyValueStore to indicate the source/priority of the read (release 7.0)

- fdbclient/MultiVersionTransaction.actor.cpp
Addresses both issues described in #5638.
Tested manually by running various sequences of setting the option and starting the network thread and confirming that the correct result was returned.
> Fix issues with setting CLIENT_THREADS_PER_VERSION option

- fdbserver/storageserver.actor.cpp
Without this change, if a change feed was completely moved from one storage server to another, the mutations would not be cleaned up from the source server.
> cleanup change feeds which have been completely removed from a storage server

- fdbserver/CommitProxyServer.actor.cpp
- flow/error_definitions.h
> Make snapshot errors more descriptive

- fdbserver/tester.actor.cpp
Patch improves logging in "tester.actor" to assist better tracking
of workload run & check status
> Improve tester actor logging to track workload run & check status

- fdbserver/Coordination.actor.cpp
Cherry pick of #6003
Passed 100k correctness
> fix: coordinators would process forwarding requests before making them durable

- fdbserver/KeyValueStoreRocksDB.actor.cpp
https://github.com/apple/foundationdb/pull/5971
> Clean up RocksDB error logging (release-7.0)

- fdbserver/DataDistribution.actor.cpp
Fixes a race with wiggle pausing and waiting for healthy. Since the wiggle checks cluster status and pauses/unpauses on an interval, the cluster could be unhealthy but have pauseWiggle == false when the wiggler runs.
This test experienced the following sequence of events:
Start: pauseWiggle == false but cluster has since become unhealthy
1. wiggler runs, starts waitForHealthy
2. clusterHealthCheckForPerpetualWiggle runs and pauseWiggle is set to true because cluster is unhealthy
3. Cluster becomes healthy, waitForHealthy finishes and wiggle starts
4. Cluster becomes unhealthy again, to the point the wiggle can't complete
5. clusterHealthCheckForPerpetualWiggle runs and tries to set pauseWiggle to true. But because the asyncVar is already true, it is a no-op and doesn't wake the wiggler
6. …
> Fixed pause race with waitUntilHealthy

- fdbserver/Knobs.cpp
> Do not buggify the peek cursor expire time to be too small

- fdbclient/DatabaseContext.h
- fdbclient/NativeAPI.actor.cpp
- fdbrpc/fdbrpc.h
- fdbrpc/sim2.actor.cpp
- fdbrpc/simulator.h
- fdbserver/fdbserver.actor.cpp
- fdbserver/storageserver.actor.cpp
- fdbserver/workloads/ChangeFeeds.actor.cpp
This PR also strengthens the change feed testing.
Passed 200k correctness.
> Fixed a large number of bugs related to empty version notification in change feeds

- fdbserver/DataDistributionQueue.actor.cpp
- fdbserver/Knobs.cpp
> Data distribution could miss storage server failures

- flow/IThreadPool.cpp
> Remove unnecessary boost/bind.hpp.

- flow/IThreadPool.cpp
> Remove unnecessary boost/bind.hpp (release-6.3).

- flow/IThreadPool.cpp
> Remove unnecessary boost/bind.hpp (release-7.0).

- bindings/java/src/main/com/apple/foundationdb/JNIUtil.java
Cherry pick https://github.com/apple/foundationdb/pull/4930 to release-6.2
After this change, users would be able to add all fdb shared libraries they need in the jar itself with something like `jar uf`, and then they could export them and add them with the network option. Users could also put their shared libraries and external clients in a separate jar.
Users could then add lines like
```
fdb.options().setExternalClientLibrary(JNIUtil.exportLibrary("fdb_c_6_2").getAbsolutePath());
fdb.options().setExternalClientLibrary(JNIUtil.exportLibrary("fdb_c_6_3").getAbsolutePath());
fdb.options().setExternalClientLibrary(JNIUtil.exportLibrary("fdb_c_7_0").getAbsolutePath());
```
at the beginning of their application for each server version they want to support.
The main libfdb_c.so client could …
> Add exportLibrary for exporting external clients from jar (release-6.2)

- fdbserver/storageserver.actor.cpp
> fix: fetched change feeds did not get their durable version updated

- bindings/flow/fdb_flow.actor.cpp
- fdbbackup/backup.actor.cpp
- fdbcli/MaintenanceCommand.actor.cpp
- fdbcli/fdbcli.actor.cpp
- fdbclient/BackupContainer.actor.cpp
- fdbclient/BackupContainerFileSystem.actor.cpp
- fdbclient/BackupContainerFileSystem.h
- fdbclient/FileBackupAgent.actor.cpp
- fdbclient/ManagementAPI.actor.cpp
- fdbrpc/sim2.actor.cpp
- fdbserver/Status.actor.cpp
- fdbserver/workloads/ApiWorkload.actor.cpp
- fdbserver/workloads/AsyncFileCorrectness.actor.cpp
- fdbserver/workloads/DiskDurabilityTest.actor.cpp
- fdbserver/workloads/KVStoreTest.actor.cpp
- fdbserver/workloads/MutationLogReaderCorrectness.actor.cpp
- fdbserver/workloads/SlowTaskWorkload.actor.cpp
- flow/DeterministicRandom.cpp
- flow/IndexedSet.cpp
- flow/flow.cpp
> Remove some usages of PRId64 macro

- fdbserver/ptxn/TLogPeekCursor.actor.h
- fdbserver/ptxn/TLogServer.actor.cpp
> Fix initialization order

- fdbserver/masterserver.actor.cpp
This is a backport of #6076.
During master recovery, it was possible for the master to write the cstate but get blocked waiting for the minimum recovery duration. If this happened, it could send an invalid master registration that updated the recovery count but reported no proxies. This would cause the current proxies to terminate and start the recovery over.
This PR changes the logic to disallow updating the master registration between the point when the cstate is updated and the recovery enters the accepting commits phase.
This bug was detected by the ConfigureTest.
Please check each of the following things and check *all* boxes before accepting a …
> Fix a race condition with updating the coordinated state and updating the master registration (release-6.3)

- packaging/docker/Dockerfile
- packaging/docker/Dockerfile.eks
- packaging/docker/build-images.sh
Minor Docker cleanup post 7.0.0-rc1
- make all curl and sha256sum commands quiet
- make {user,group}add commands easier to read
- update build-images script for 7.0, fix some bugs
> docker cleanup post 7.0.0-rc1

- fdbclient/NativeAPI.actor.cpp
> fix: whenAtLeast updates lastReturnedVersion

- fdbclient/NativeAPI.actor.cpp
- fdbserver/BlobManager.actor.cpp
- fdbserver/ClusterController.actor.cpp
- fdbserver/storageserver.actor.cpp
> A variety of bug fixes

- fdbserver/ClusterController.actor.cpp
> [6.3] Use CC_ENABLE_WORKER_HEALTH_MONITOR knob to guard remoteDCIsHealthy logic

- flowbench/benchmark.cmake
This fixes a compile error with clang 13. Cherry pick of #6091
> Upgrade google benchmark to v1.6.0

- fdbclient/NativeAPI.actor.cpp
- fdbclient/Notified.h
- fdbserver/ClusterController.actor.cpp
- fdbserver/DataDistributionTracker.actor.cpp
- fdbserver/VersionedBTree.actor.cpp
- fdbserver/storageserver.actor.cpp
- flow/MetricSample.h
- flow/Net2.actor.cpp
> Avoid creating unnecessary temporary objects

- fdbserver/DataDistributionTracker.actor.cpp
This fixes a bug that turns up very rarely in simulation where a shard gets merged too soon (`ShardMergeTooSoon`). The problem is that if a shard goes from low to normal and back to low bandwidth quickly enough, the tracker may fail to register the update. As a result, it could merge a shard earlier than it should.
> Fix: Merge too soon bug

- fdbserver/DataDistributionTracker.actor.cpp
This is a cherry-pick of #6103.
This fixes a bug that turns up very rarely in simulation where a shard gets merged too soon (ShardMergeTooSoon). The problem is that if a shard goes from low to normal and back to low bandwidth quickly enough, the tracker may fail to register the update. As a result, it could merge a shard earlier than it should.
Passed 100K correctness except one joshua timeout in tests/rare/RedwoodCorrectnessBTree.toml.
> Fix: Merge too soon bug (release-7.0)

- fdbclient/NativeAPI.actor.cpp
> fix: merge cursors can have more mutations sent to self->mutations after it goes empty

- fdbclient/MonitorLeader.actor.cpp
20211118-050236-renxuan-31e4fee6dcdf06d1           compressed=True data_size=27852769 duration=3657167 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:40:10 sanity=False started=100284 stopped=20211118-054246 submitted=20211118-050236 timeout=5400 username=renxuan
> Remove trimFromHostname().

- documentation/sphinx/source/release-notes/release-notes-630.rst
> Release notes for 6.3.23
