bindings/c/test/mako/mako.c
bindings/c/test/mako/mako.h

This change allows a user to set a "loggroup" in mako.
I rebased this change on `release-6.3` and tested because the build was broken at the time of this PRs creation.
When loggroup is set, traces look like this:
```
<Event Severity="10" Time="1620162104.837037" DateTime="2021-05-04T21:01:44Z" Type="SetNetworkOption" ID="0000000000000000" Option="TRACE_LOG_GROUP" Machine="127.0.0.1:5454" LogGroup="testing123" />
```

Mako should be able to set loggroup

---

documentation/sphinx/source/backups.rst
fdbbackup/backup.actor.cpp
fdbclient/BackupAgent.actor.h
fdbclient/FileBackupAgent.actor.cpp
fdbclient/Knobs.cpp
fdbclient/Knobs.h

20210501-084453-renxuan-958b73fe59006902           compressed=True data_size=21141598 duration=4531605 ended=105028 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=2:06:48 sanity=False started=105102 stopped=20210501-105141 submitted=20210501-084453 timeout=5400 username=renxuan
The failed test is unrelated.

Cherrypick #4691, #4704 and #4725 to 6.3.

---

cmake/GetMsgpack.cmake

Fix msgpack dependency

---

cmake/GetMsgpack.cmake

Backport of #4759 to fix an issue when building a cmake component with an fdb_c dependency but not an explicit fdbclient dependency.

Fix msgpack dependency (release-7.0)

---

documentation/sphinx/source/administration.rst
documentation/sphinx/source/release-notes/release-notes-620.rst

Cherry pick https://github.com/apple/foundationdb/pull/4763 to release-7.0
Some misaligned headers and spacing corrections made to the documentation files.

Fix documentation build (release-7.0)

---

bindings/c/test/mako/mako.c
bindings/c/test/mako/mako.h

Cherry-pick "Mako should be able to set loggroup" (#4750) to release-6.3
Cherry-picking so older releases can be tested with this feature.

Cherry-pick "Mako should be able to set loggroup" (#4750) release-6.3

---

fdbrpc/AsyncFileNonDurable.actor.h
fdbrpc/sim2.actor.cpp
flow/flow.h

Cherry pick https://github.com/apple/foundationdb/pull/4756 to release-7.0
Reverts apple/foundationdb#4562. It was causing segfaults in simulation.

Revert "Actually close files in simulation" (release-7.0)

---

flow/Trace.h

This fixes an assertion failure due to uninitialized memory.

Use default initializer for TraceEvent::errorKind

---

bindings/c/test/mako/mako.c
bindings/c/test/mako/mako.h

Cherry-pick "Mako should be able to set loggroup" (#4750) to release-6.2
Cherry-picking so older releases can be tested with this feature.

Cherry-pick "Mako should be able to set loggroup" (#4750) to release-6.2

---

README.md
build/cmake/Dockerfile
build/docker/centos6/build/Dockerfile
build/docker/centos7/build/Dockerfile
cmake/CompileBoost.cmake

Bintray is shut down, so our download links for boost need to be updated. I replaced them with links from https://www.boost.org/users/history/ (also see https://sourceforge.net/p/boost/discussion/23622/thread/9fa9141990/?limit=25).

Fix boost download links

---

README.md
build/cmake/Dockerfile
build/docker/centos6/build/Dockerfile
build/docker/centos7/build/Dockerfile
cmake/CompileBoost.cmake

Cherry pick https://github.com/apple/foundationdb/pull/4746 to release-7.0
Bintray is shut down, so our download links for boost need to be updated. I replaced them with links from https://www.boost.org/users/history/ (also see https://sourceforge.net/p/boost/discussion/23622/thread/9fa9141990/?limit=25).

Fix boost download links (release-7.0)

---

fdbclient/SpecialKeySpace.actor.cpp

Cherry pick https://github.com/apple/foundationdb/pull/4747 to release-7.0
… space
Fix unseed mismatches in the special key space tests for the clang build

Use a deterministic iteration order for committing in the special key… (release-7.0)

---

README.md
build/Dockerfile
build/cmake/Dockerfile
cmake/CompileBoost.cmake

Cherry pick https://github.com/apple/foundationdb/pull/4746 to release-6.2
Bintray is shut down, so our download links for boost need to be updated. I replaced them with links from https://www.boost.org/users/history/ (also see https://sourceforge.net/p/boost/discussion/23622/thread/9fa9141990/?limit=25).

Fix boost download links (release-6.2)

---

README.md
build/Dockerfile
build/cmake/Dockerfile
cmake/CompileBoost.cmake

Cherry pick https://github.com/apple/foundationdb/pull/4746 to release-6.3
Bintray is shut down, so our download links for boost need to be updated. I replaced them with links from https://www.boost.org/users/history/ (also see https://sourceforge.net/p/boost/discussion/23622/thread/9fa9141990/?limit=25).

Fix boost download links (release-6.3)

---

fdbserver/CMakeLists.txt
fdbserver/ptxn/test/RealTLog.actor.cpp
fdbserver/ptxn/test/RealTLog.actor.h

Add a new test to run a single stand-alone tlog. The test runs "numCommits" transactions using the tLog commit and peek interfaces. Data and versions are checked. This can be used for benchmarking. 

tLog component level test

---

fdbserver/VersionedBTree.actor.cpp

Rewrote FIFOQueue::Cursor read and write actors for more clarity, less overhead, and to fix bugs during pager shutdown.
Correctness runs of 100K each, one with all tests, one with Redwood unit test default params, one with Redwood unit test forced to 200 byte pages to force more queue page churn.
```
20210504-225410-satherton_full-1ebe42cf5255a1eb
20210504-224519-satherton_btree_p200_po5M-93d49844384b77a4
20210504-224903-satherton_btree-a5c4097a9c81eceb
```

Refactor FIFOQueue::Cursor read/write operations

---

fdbserver/ClusterController.actor.cpp

Adding TraceEvent when a worker is removed from cluster controller.
Joshua Test Run:
20210427-234349-neethuhaneeshabingi-4475c28eb626c378 compressed=True data_size=23064173 duration=4817701 ended=103281 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:53:16 sanity=False started=103302 stopped=20210428-013705 submitted=20210427-234349 timeout=5400 username=neethuhaneeshabingi
Simulation Test log:
Command: build_output/bin/fdbserver -r simulation --crash --logsize 1024MB -f src/foundationdb/tests/fast/BackupCorrectness.toml -s 235461 -b on
Log: Event Severity="10" Time="148.085736" DateTime="2021-04-29T00:17:33Z" Type="ClusterWorkerFailed" Machine="2.0.1.0:1" ID="fdf2765d9846a8d7" WorkerProcessId="7b840c8d8bd67f36f7bf59bbbd049f3c" …

Adding TraceEvent when a worker is removed from cluster controller.

---

bindings/CMakeLists.txt
tests/CMakeLists.txt

`OPEN_FOR_IDE` is currently broken on master, this fixes it by excluding some targets.
```
CMake Error at bindings/c/CMakeLists.txt:122 (add_custom_command):
Error evaluating generator expression:
$<TARGET_FILE:fdb_c>
Target "fdb_c" is not an executable or library.
CMake Error at tests/CMakeLists.txt:266 (add_test):
Error evaluating generator expression:
$<TARGET_FILE:fdbserver>
Target "fdbserver" is not an executable or library.
CMake Error at bindings/c/CMakeLists.txt:122 (add_custom_command):
Error evaluating generator expression:
$<TARGET_FILE:fdb_c>
Target "fdb_c" is not an executable or library.
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
``` …

Fix OPEN_FOR_IDE option for cmake

---

fdbclient/ActorLineageProfiler.cpp
fdbclient/GlobalConfig.actor.cpp
fdbclient/GlobalConfig.actor.h
fdbclient/NativeAPI.actor.cpp
fdbserver/ClusterController.actor.cpp
fdbserver/worker.actor.cpp
flow/genericactors.actor.h

See #4330 and [this wiki page](https://github.com/apple/foundationdb/wiki/Global-Configuration-Framework) for context on global configuration.
This PR fixes an issue where only clients were being updated when keys in global configuration changed.
* When a role (such as a storage server or tlog) starts up, it calls `openDBOnServer` to create a `DatabaseContext` object, in order to be able to run transactions and do other database related things.
* `openDBOnServer` ends up calling into the `DatabaseContext` constructor. This constructor is also used by clients to create an initial database object. Based on this, I was running global configurations initialization function in the `DatabaseContext` constructor.
* If running using less than one `fdbserver` binary per role, multiple FDB roles …

Fix global config not triggering changes on server processes

---

fdbclient/ActorLineageProfiler.cpp
fdbclient/GlobalConfig.actor.cpp
fdbclient/GlobalConfig.actor.h
fdbclient/NativeAPI.actor.cpp
fdbserver/ClusterController.actor.cpp
fdbserver/worker.actor.cpp
flow/genericactors.actor.h

Reverts apple/foundationdb#4782. This PR is causing failures in `restarting/from_5.2.0/ClientTransactionProfilingCorrectness-1.txt` tests.

Revert "Fix global config not triggering changes on server processes"

---

contrib/apiversioner.py

This is the tool we used to change API version after a major version release. The tool is modified to be Python 3 style and added a few more exclusion file patterns.
I've manually tested all command line arguments to make sure they all work with Python 3.

Add a tool for changing API versions in the code base

---

fdbserver/ptxn/TLogStorageServerPeekMessageSerializer.cpp
fdbserver/ptxn/test/TestSerialization.cpp

For the iterator, check StringRef::begin() and size() should be sufficient and avoid the expensive `memcmp()` calls.
Found by running `perf record -F 99 -ag ./build_output/bin/fdbserver -r test -b on --crash -s 1 -f tests/ptxn/Serialization.toml`.

Fix deserialization performance issue

---

fdbserver/fdbserver.actor.cpp

Without this change, fdbserver will immediately segfault when configured via the operator.

Set connectionFile instead of creating a shadow

---

documentation/sphinx/source/release-notes/release-notes-630.rst
flow/Net2.actor.cpp

When breaking from the inner run loop due to yield, we weren't updating the time used to record that we are running at run loop priority. As a result, our priority tracking could be inaccurate.

Fix accounting for time spent in run loop after breaking due to yield

---

documentation/sphinx/source/release-notes/release-notes-630.rst
flow/Net2.actor.cpp

Backport of #4824
When breaking from the inner run loop due to yield, we weren't updating the time used to record that we are running at run loop priority. As a result, our priority tracking could be inaccurate.
This is being backported because the reporting bug affects in-use versions and could have non-trivial impact.

Fix accounting for time spent in run loop after breaking due to yield (release-7.0)

---

documentation/sphinx/source/release-notes/release-notes-630.rst
flow/Net2.actor.cpp

Backport of #4824
When breaking from the inner run loop due to yield, we weren't updating the time used to record that we are running at run loop priority. As a result, our priority tracking could be inaccurate.
This is being backported because the reporting bug affects in-use versions and could have non-trivial impact.

Fix accounting for time spent in run loop after breaking due to yield (release-6.3)

---

fdbclient/FDBTypes.h
fdbclient/StorageServerInterface.h
fdbserver/CommitProxyServer.actor.cpp
fdbserver/ProxyCommitData.actor.h
fdbserver/ptxn/MessageTypes.h
fdbserver/ptxn/ProxyTLogPushMessageSerializer.cpp
fdbserver/ptxn/ProxyTLogPushMessageSerializer.h
fdbserver/ptxn/TLogStorageServerPeekMessageSerializer.cpp
fdbserver/ptxn/test/FakeProxy.actor.cpp
fdbserver/ptxn/test/FakeTLog.actor.cpp
fdbserver/ptxn/test/TestSerialization.cpp
tests/CMakeLists.txt
tests/ptxn/CycleTest.toml

Add serialization of transaction data in commit proxy's memory. Modify `SubsequenceMutationItem` to support span ID and write already serialized mutations out, which makes the serialization more complex than I would like to.
The follow-on PRs will actuall send team's data to tlog groups, which depends on tlog group recruitment. Another follow-on work is to manage team data in Proxies, i.e., update `ServerCacheInfo::teams`.
Correctness passed:
20210518-161723-jingyu_zhou-f6fe5a0208a4b87e       compressed=True data_size=23490415 duration=6132277 ended=100880 fail_fast=10 max_runs=100000 pass=100022 priority=100 remaining=0 runtime=0:32:33 sanity=False started=100905 stopped=20210518-164956 submitted=20210518-161723 timeout=5400 username=jingyu_zhou …

Proxy serializes data for storage teams (dual-write path).

---

contrib/TestHarness/Program.cs.cmake
contrib/TraceLogHelper/JsonParser.cs
contrib/TraceLogHelper/XmlParser.cs

I accidentally created a trace event with an invalid xml detail name that caused the xml file to not parse correctly.
Because this parsing code swallowed the exceptions and essentially just truncated the trace file, the error presented itself as "TestUnexpectedlyNotFinished" in joshua because it wasn't parsing all of the trace events.
Unless there is a case i'm missing, it seems like it would be much better to propagate this error so that, if this happens again, it's much easier to debug what went wrong.

Not swallowing exceptions on malformed XML

---

fdbserver/ptxn/TLogServer.actor.cpp
fdbserver/ptxn/test/Driver.actor.cpp
fdbserver/ptxn/test/Driver.h
fdbserver/ptxn/test/FakeProxy.actor.cpp
fdbserver/ptxn/test/FakeProxy.actor.h
fdbserver/ptxn/test/Utils.cpp
flow/UnitTest.cpp
flow/UnitTest.h
tests/ptxn/TLogServer.toml

Integrate fake proxy to talk to team partitioned TLogServer.  
- Disk queue still has some problem so not enabled. It's not needed for implementing peek.
- Commit validation in TLogServer is disabled for now and will be added later.
- Testing: ptxn/TLogServer.toml 
- [ x ] The PR has a description, explaining both the problem and the solution.
- [ x ] The description mentions which forms of testing were done and the testing seems reasonable.
- [ x ] Every function/class/actor that was touched is reasonably well documented. …

Integrate team partitioned TLogServer with fake proxy to test commit

---

fdbserver/OldTLogServer_6_0.actor.cpp
fdbserver/OldTLogServer_6_2.actor.cpp
fdbserver/TLogServer.actor.cpp

This resulted in a recovery never reaching the fully_committed state and causing the test to timeout.
passed 200k correctness on a separate branch where the problem was found while fixing other correctness issues.

fixed a rare simulation bug where missingFinalCommit could be skipped by two successive logSystem changes

---

fdbserver/ptxn/TLogServer.actor.cpp
fdbserver/ptxn/test/Driver.actor.cpp
tests/ptxn/TLogServer.toml

Currently 'run_tlog_server' have some flaky timeout errors due to multiple groups share version variable through NotifiedVersion.initMetric(). This PR tries to fix it.
- [ x ] The PR has a description, explaining both the problem and the solution.
- [ x ] The description mentions which forms of testing were done and the testing seems reasonable.
- [ x ] Every function/class/actor that was touched is reasonably well documented.

Fix tlog commit timeout error

---

documentation/sphinx/source/mr-status-json-schemas.rst.inc
documentation/sphinx/source/release-notes/release-notes-700.rst
fdbclient/Schemas.cpp
fdbserver/LogSystem.h
fdbserver/LogSystemPeekCursor.actor.cpp
fdbserver/Status.actor.cpp
fdbserver/storageserver.actor.cpp

Task: Report bounce impact in fdbcli status
Changes:
Schemas.cpp: Extend the JSON schema to include new fields that report
whether the cluster is bounceable and if not, report the reason for why it 
is not bounceable.
Status.actor.cpp: Extend recoveryStateStatusFetcher() to populate the
bounce related field(s).
mr-status-json-schemas.rst.inc: Update the schema to reflect the change
made in Schemas.cpp.
release-notes-700.rst: Add a note about the new status fields in "Status"
section.
Task: Report how fast an SS is catching up to its tLog-SS lag
Changes:
LogSystem.h, LogSystemPeekCursor.actor.cpp:  Add APIs to find the ID
of the tLog from which an SS has fetched the latest set of versions.
storagegroupserver.actor.cpp: 
- Add two new counters to StorageServer::Counters in order to capture …

Expose "bounce impact" and Storage Server "version catch-up rate" metrics

---

.gitignore
fdbcli/fdbcli.actor.cpp
fdbclient/DatabaseConfiguration.cpp
fdbclient/DatabaseConfiguration.h
fdbclient/ManagementAPI.actor.cpp
fdbclient/Schemas.cpp
fdbclient/SystemData.cpp
fdbclient/SystemData.h

Implement the following command in fdbcli
```
configure perpetual_storage_wiggle=speed
```
The value speed will be the number of processes that the Data Distributor should exclude at a time. We’re currently only planning to support up to 1. So any value different than 0 or 1 will return an error.

perpetual storage wiggling command line support

---

documentation/sphinx/source/release-notes/release-notes-630.rst

There were discrepancies between the `release-6.3` branch patch notes and all other versions. This change is to make them consistent.
Changes on release-7.0: https://github.com/apple/foundationdb/pull/4859

Update release notes to match the ones on release-6.3

---

documentation/sphinx/source/release-notes/release-notes-630.rst

The changes written to 6.3.13 did not make it to the 6.3.13 tag, so it has been moved forward. Also, new patch notes were added for 6.3.14 changes.

Move patch notes to correct section

---

fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp

This backports a test fix introduced in https://github.com/apple/foundationdb/pull/4255/ to resolve a correctness issue on the release-6.3 branch. Note this is not done as a cherry pick because the original commit that made this change was part of a much larger change.
This change already exists on both master and release-7.0.
Passed 100K correctness with 1 failure in a different test.

Fix test to handle case where worker interface list is empty

---

fdbserver/VersionedBTree.actor.cpp

Resolves #4855 and #4705.
I implemented the quick fix steve suggested for 4855, and the fix steve and I talked about for 4705 to avoid consecutive keys in the input. I also added a useful debugging thing I'd used when tracking down redwood simulation failures.
This passed 100k redwood random unit test runs and 10k simulation tests with redwood forced as the storage engine.

Fixing multiple small redwood test bugs

---

fdbserver/ptxn/TLogPeekCursor.actor.cpp
fdbserver/ptxn/TLogServer.actor.cpp
fdbserver/ptxn/test/Driver.actor.cpp
fdbserver/ptxn/test/TestTLogPeek.actor.cpp
fdbserver/ptxn/test/Utils.h
tests/ptxn/TLogServer.toml

Add peek request handling for tlogs and a test that commits, peeks, and verifies the data is correct.
More tests are needed to verify peek request wait for future version data.

Add peek request handling for tlogs

---

documentation/sphinx/source/release-notes/release-notes-630.rst
fdbclient/FileBackupAgent.actor.cpp

This cherrypicks #4850 and addresses issue #4849.
Correctness passed:
20210525-155913-jzhou-26da657e37f658b6             compressed=True data_size=21409444 duration=6132685 ended=105830 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:37:03 sanity=False started=105864 stopped=20210525-163616 submitted=20210525-155913 timeout=5400 username=jzhou

Cherrypick to 6.3: Only enable backup worker when using partitioned logs

---

fdbclient/FileBackupAgent.actor.cpp
fdbserver/workloads/BackupCorrectness.actor.cpp
tests/fast/BackupCorrectnessClean.txt

This is a backport of #4684.
Resolves #4716.
- BackupCorrectness workload would sometimes generate an empty restore target range set. This would cause the test to time out because restore() would still queue the job, but then during execution the restore tasks would repeatedly fail because the restore range set is empty. BackupCorrectness should no longer generate empty restore ranges, but just in case restore() will now throw an error if the target ranges are empty which will cause a much faster failure.
- Restore start was not properly checking restore target ranges against the remove prefix option.
- Some code clarity changes. …

Restore target range handling bug fixes (release-6.3)

---

documentation/sphinx/source/release-notes/release-notes-630.rst
fdbclient/FileBackupAgent.actor.cpp

This cherrypicks #4850 and addresses issue #4849.
Correctness passed:
20210525-165231-jzhou-d77a6832e5ae7fe3             compressed=True data_size=23357932 duration=3757601 ended=101309 fail_fast=10 max_runs=100000 pass=100478 priority=100 remaining=0 runtime=0:21:30 sanity=False started=101816 stopped=20210525-171401 submitted=20210525-165231 timeout=5400 username=jzhou

Cherrypick to 7.0: Only enable backup worker when using partitioned logs

---

fdbclient/NativeAPI.actor.cpp

Client buggified reads were set to fail 25% of the time. If a transaction had a lot of reads, that could make it very likely for the transaction to fail. In some cases, data movement transactions had enough reads that they were never succeeding and blocking the quiet database check.
This decreases the probability that a buggified read will be failed from 25% to 1%.
Passed 10K correctness with 1 unrelated failure (hopefully fixed by #4873)

Reduce the frequency that buggified reads are failed

---

fdbrpc/AsyncFileCached.actor.cpp
fdbrpc/AsyncFileCached.actor.h
fdbrpc/AsyncFileNonDurable.actor.h
fdbrpc/sim2.actor.cpp
fdbrpc/simulator.h
fdbserver/SimulatedCluster.actor.cpp
flow/flow.h
flow/genericactors.actor.h

This revives PR #4562, addressing an issue where removing a file from the `openFiles` map could result in us doing a reentrant call to erase the file again and crash.
During simulation we only close files when a simulated machine reboots. This is problematic as some tests (most notably backup tests) open many files. So we get into trouble if these tests run for too long.
Passed 100K correctness with 1 unrelated failure (addressed in https://github.com/apple/foundationdb/pull/4879/files)

Actually close files in simulation

---

fdbclient/NativeAPI.actor.cpp

This is a backport of #4879.
Client buggified reads were set to fail 25% of the time. If a transaction had a lot of reads, that could make it very likely for the transaction to fail. In some cases, data movement transactions had enough reads that they were never succeeding and blocking the quiet database check.
This decreases the probability that a buggified read will be failed from 25% to 1%.

Reduce the frequency that buggified reads are failed (release-7.0)

---

fdbclient/NativeAPI.actor.cpp

This is a backport of #4879 to help solve simulation issues.
Client buggified reads were set to fail 25% of the time. If a transaction had a lot of reads, that could make it very likely for the transaction to fail. In some cases, data movement transactions had enough reads that they were never succeeding and blocking the quiet database check.
This decreases the probability that a buggified read will be failed from 25% to 1%.

Reduce the frequency that buggified reads are failed (release-6.3)

---

fdbrpc/AsyncFileCached.actor.cpp
fdbrpc/AsyncFileCached.actor.h
fdbrpc/AsyncFileNonDurable.actor.h
fdbrpc/sim2.actor.cpp
fdbrpc/simulator.h
fdbserver/SimulatedCluster.actor.cpp
flow/flow.h
flow/genericactors.actor.h

This is a backport of #4873 to fix correctness issues.
During simulation we only close files when a simulated machine reboots. This is problematic as some tests (most notably backup tests) open many files. So we get into trouble if these tests run for too long.

Actually close files in simulation (release-7.0)

---

fdbserver/IPager.h
flow/Arena.cpp

Previously, when running with FDB_VALGRIND_PRECISE, we would see a false positive since we dereferenced memory immediately after marking it no access. Also it no longer makes sense to mark an ArenaPage's buffer as anything but accessible in the destructor since ArenaPages have shared ownership of their buffers. Tested by re-running a failing valgrind seed and seeing it pass (no simulator behavior changes in this PR).

Fix two valgrind false positives

---

fdbrpc/AsyncFileCached.actor.h

Fixes bug introduced in #4893 and resolves #4897.
The refactoring of AsyncFileCached changed the implementation of `open_impl` so that it wasn't modifying anything in `openFiles` directly. In the case where a file was opened synchronously, this code path had been responsible for implicitly inserting an entry into the map.
This fix changes `open` so that an entry is inserted into the map regardless of whether it is ready.
This bug is not currently reproducible in simulation (see #4901), so the fix was verified with a real-world cluster. Previously configuring a cluster would trigger assertion failures, and it now does not. …

Fix: when a file open completes synchronously, it wasn't being stored in the openFiles map

---

fdbrpc/AsyncFileCached.actor.h

Cherry pick https://github.com/apple/foundationdb/pull/4900 to release-7.0
Fixes bug introduced in #4893 and resolves #4897.
The refactoring of AsyncFileCached changed the implementation of `open_impl` so that it wasn't modifying anything in `openFiles` directly. In the case where a file was opened synchronously, this code path had been responsible for implicitly inserting an entry into the map.
This fix changes `open` so that an entry is inserted into the map regardless of whether it is ready.
This bug is not currently reproducible in simulation (see #4901), so the fix was verified with a real-world cluster. Previously configuring a cluster would trigger assertion failures, and it now does not. …

Fix: when a file open completes synchronously, it wasn't being stored in the openFiles map (release-7.0)

---

fdbserver/CommitProxyServer.actor.cpp
fdbserver/MasterInterface.h
fdbserver/masterserver.actor.cpp

When a sequence number is assigned to a transaction the "previous sequence number" is also assigned. The PR adds logic to wait for the transaction corresponding to the previous sequence number to be acknowledged to the client for any transaction commit.
In partitioned FDB this is needed in recovery. In the example below, the min rv (recovery version) of all tlogs would be invalid. 
```
tlog group 1 rv=1
tlogA 1	2
tlogB 1	
tlog group 2 rv=3
tlog C 3
tlog D 3
```
Here the min rv would be 1 over all tlogs, even though 3 was acked.
With this PR, 3 would not be acked until 2 was acked.
Note in classic FDB
- all tlogs receive txn versions so this scenario wouldn't happen.
- an ack can be sent back out of order, but this is only done after all tlogs has been updated in order.
tested both …

Wait for previous txns to ack before acking current txn

---

fdbclient/GlobalConfig.actor.cpp
fdbclient/GlobalConfig.actor.h
fdbclient/NativeAPI.actor.cpp
fdbclient/SpecialKeySpace.actor.cpp
fdbclient/Tuple.cpp
fdbclient/Tuple.h
fdbserver/ClusterController.actor.cpp
fdbserver/worker.actor.cpp
flow/genericactors.actor.h

Second implementation of https://github.com/apple/foundationdb/pull/4782 which was reverted by https://github.com/apple/foundationdb/pull/4793 due to 5.2.0 restart test failures.
See #4330 and [this wiki page](https://github.com/apple/foundationdb/wiki/Global-Configuration-Framework) for context on global configuration.
Fixes an issue where fdbserver processes were not receiving updates made to global configuration, because the `Database` object held by global configuration was no longer valid.
Also adds the ability to add watches for keys in global configuration and receive a notification when the value changes.
Passed 50k tests run on Joshua. #4782 was causing 5.2.0 restart test failures. I ran 1,000 of just these on Joshua and they all passed.
Passed 100/100 Valgrind runs.
The general …

Fix global config not triggering changes on server processes (attempt 2)

---

bindings/python/CMakeLists.txt
bindings/python/tests/fdbcli_tests.py

Using the existing CMake function `add_fdbclient_test`, we add test coverage for fdbcli.
Through a python script where we run shell command and capture the console output,
we add assertions for the fdbcli output.
If any of the assertions failed, it means fdbcli is not working as expected or the test needs to be updated.

Add test coverage for fdbcli commands using a python script

---

fdbserver/VersionedBTree.actor.cpp

7.0 cherrypick of https://github.com/apple/foundationdb/pull/4868 to fix some redwood simulation failures.
Passed 10k redwood correctness unit tests and 10k simulation tests with redwood forced as the storage engine.

7.0 Cherrypick - Redwood patches

---

fdbserver/ClusterController.actor.cpp
fdbserver/masterserver.actor.cpp

1. Add logging when DC switch happens;
2. Add logging when CC recruits workers;
3. Log the DC Ids when master recruits everrthing.
20210524-195906-renxuan-13e040d67739fe53           compressed=True data_size=23376650 duration=8558269 ended=102300 fail=2 fail_fast=10 max_runs=100000 pass=100028 priority=100 remaining=0 runtime=0:57:52 sanity=False started=102551 stopped=20210524-205658 submitted=20210524-195906 timeout=5400 username=renxuan

Improve logging on the current view of the database configuration that the cluster controller is using.

---

bindings/c/CMakeLists.txt
bindings/c/external_workload.map
bindings/c/generate_asm.py
bindings/c/test/unit/unit_tests_version_510.cpp
bindings/java/CMakeLists.txt

Previously, lld was unable to link fdb_c.g.S because it required dynamic relocation. This change fixes fdb_c.g.S to not require dynamic relocation, and also fixes a few other issues lld complained of.
Also add a very basic test for an old api header version since I realized we don't have that.

Fix clang build on Arm

---

fdbclient/FDBTypes.h
fdbclient/ManagementAPI.actor.cpp
fdbrpc/Stats.h
fdbserver/DataDistributionTracker.actor.cpp
fdbserver/DeltaTree.h
fdbserver/GrvProxyServer.actor.cpp
fdbserver/LogRouter.actor.cpp
fdbserver/RadixTree.h
fdbserver/SkipList.cpp
fdbserver/VersionedBTree.actor.cpp
fdbserver/sqlite/sqlite3.amalgamation.c
fdbserver/storageserver.actor.cpp
flow/Arena.h
flow/FastAlloc.cpp
flow/Histogram.cpp

Cherry pick https://github.com/apple/foundationdb/pull/4909 to release-7.0
Found by building with `-DUSE_UBSAN=ON` (and clang11), and running simulation tests. Now passes ~50k simulation tests with no failures. I manually compared a few simulations before and after this change and confirmed that they have the same unseed. Each commit explains the particular UB it's fixing.

Fix several instances of undefined behavior (release-7.0)

---

fdbserver/masterserver.actor.cpp

Cherrypicking  #4626. Add logging to master role to count the number of requests of each type received. This helps to determine whether the master is making progress. We need it in 6.3 to debug master-stall issues.

Cherrypick "add MasterMetrics periodic logging" to 6.3.

---

flow/genericactors.actor.h

Calling broken_on_destruct.sendError() calls arbitrary callbacks, which
might delete the FlowLock. It's more robust to copy to a local variable
before sending.
This fixes a heap-use-after-free from our nightly tests.

Allow FlowLock::kill to delete self

---

documentation/sphinx/source/mr-status-json-schemas.rst.inc
fdbclient/DatabaseConfiguration.cpp
fdbclient/Schemas.cpp

Fixes https://github.com/apple/foundationdb/issues/4812
The underlying problem was that the k8s operator was looking for a `"proxies"` field in the status json that was no longer present. Because of that, the operator thought that the database configuration was improperly applied, so it would repeatedly call `configure` through the fdbcli. Each call to `configure` interrupted data distribution initialization. DD would only start when the initialization managed to be fast enough to finish prior to the successive `configure` call.
The backwards compatible field ignores the `auto` proxies. I think this is the correct design, but I'm unsure. …

Add a backwards-compatible 'proxies' field to status json

---

packaging/docker/Dockerfile.eks
packaging/docker/misc/flamegraph.sha256sum

This adds flamegraph.pl to the EKS docker images, which allows us to generate flamegraph.svg's during performance runs.

Add perl + flamegraph to EKS docker images

---

fdbclient/SpecialKeySpace.actor.cpp
fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp

Cherry-pick PR #4877  , the transaction should grab moveKeysLockOwnerKey and moveKeysLockWriteKey when update data distribution related system keys.

Fix the place when changing dd system key without changing the lock key

---

packaging/docker/Dockerfile.eks

To enable fast loading of YCSB data into EKS clusters, this adds the aws cli tool used to download from s3.

Add AWS CLI tool for downloading from s3

---

bindings/c/test/mako/mako.c
bindings/c/test/mako/mako.h
bindings/c/test/mako/utils.c
bindings/c/test/mako/utils.h
packaging/docker/Dockerfile.eks
packaging/docker/misc/flamegraph.sha256sum

If the mako key string is shorter than 'keylen' it is padded out to 'keylen' bytes.
i.e. keylen = 16 and rows = 1000 generates keys that look like `mako0000xxxxxxxx`.
The `--prependpadding` option instead prepends this 'x' padding and thus keys look like `xxxxxxxxmako0000`.
This is useful for testing prefix compression in Redwood.
~Pending testing.~ Tested working.

Add option to prepend key padding in mako

---

fdbserver/OldTLogServer_6_2.actor.cpp
fdbserver/TLogServer.actor.cpp

When using trace events to look into a long recovery, we often need to distinguish TLogs of different generations.
However, it is hard to get such information from existing trace events.
Thus, we decide to add RecoveryCount info to events when any TLog begins. 
Q: Why do not leverage the existing "TLog Role Begin" event to carry the RecoveryCount info?
A: When the current "TLog Role Begin" event is created, logData->RecoveryCount is unset yet. 
Passed 100K joshua tests.
Add RecoveryCount info to TLogPersistentStateRestore event and TLogStart events in restorePersistentState() and tLogStart() respectively.
We add the events to both TLogServer.actor.cpp and OldTLogServer_6.2.actor.cpp.
The general guidelines can be found [here](https://github.com/apple/foundationdb/wiki/FoundationDB-Commit-P …

Add RecoveryCount info to trace events when tLog begins

---

tests/slow/DifferentClustersSameRV.toml

This fixes a failure in last night's release-7.0 correctness run

150 was too short and we were seeing false positives

---

fdbserver/OldTLogServer_6_2.actor.cpp
fdbserver/TLogServer.actor.cpp

When using trace events to look into a long recovery, we often need to distinguish TLogs of different generations.
However, it is hard to get such information from existing trace events.
Thus, we decide to add RecoveryCount info to events when any TLog begins.
Q: Why do not leverage the existing "TLog Role Begin" event to carry the RecoveryCount info?
A: When the current "TLog Role Begin" event is created, logData->RecoveryCount is unset yet.
Passed 100K joshua tests.
Add RecoveryCount info to TLogPersistentStateRestore event and TLogStart events in restorePersistentState() and tLogStart() respectively.
We add the events to both TLogServer.actor.cpp and OldTLogServer_6.2.actor.cpp.
The general guidelines can be found [here](https://github.com/apple/foundationdb/wiki/FoundationDB-Commit-Pro …

add epoch info to trace events when tLog begins (for release-6.3)

---

documentation/sphinx/source/mr-status-json-schemas.rst.inc
fdbclient/DatabaseConfiguration.cpp
fdbclient/Schemas.cpp

Cherry-pick https://github.com/apple/foundationdb/pull/4922 to release-7.0
The underlying problem was that the k8s operator was looking for a "proxies" field in the status json that was no longer present. Because of that, the operator thought that the database configuration was improperly applied, so it would repeatedly call configure through the fdbcli. Each call to configure interrupted data distribution initialization. DD would only start when the initialization managed to be fast enough to finish prior to the successive configure call.
The backwards compatible field ignores the auto proxies. I think this is the correct design, but I'm unsure. …

Add a backwards-compatible 'proxies' field to status json (release-7.0)

---

fdbserver/SimulatedCluster.actor.cpp
fdbserver/tester.actor.cpp
tests/restarting/to_6.3.10/CycleTestRestart-1.txt
tests/restarting/to_6.3.10/CycleTestRestart-2.txt

Since TSS introduces new private mutations, once TSS is enabled, a 7.0 -> 6.3 downgrade could cause ASSERT failures in the storage server, if the cluster was downgraded within 5 seconds of a TSS private mutation being sent to servers.
So, we will just recommend not to downgrade 7.0 -> 6.3 if TSS has been enabled.
Thus, the only downgrade testing we have to do is test 7.0 with TSS disabled downgrading to 6.3, checking that the StorageServerInterface data format change is downgrade-able as expected.
Testing:
I did manual testing locally to confirm that downgrading without enabling TSS is fine, and that downgrading immediately after enabling TSS causes the "unknown private mutations" assert to fail in the storage server.
I added a new flag in downgrade tests to disable TSS, and ran 10k 6.3 …

TSS downgrade changes

---

fdbserver/DataDistribution.actor.cpp
fdbserver/DataDistributionQueue.actor.cpp
fdbserver/Knobs.cpp
fdbserver/tester.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp
fdbserver/workloads/workloads.actor.h

1. Modify simulation test setting: properly set perpetual_storage_wiggle value to its original value. This change makes all test of which waitQuiescentStart=true also can test perpetual wiggle.
2. Fix time-out bug. Sometimes invalid wiggle server appears because the data distributor changing prevents the wiggler from properly setting the status to NONE, which makes this server unavailable afterward. If the number of invalid wiggle server keep increasing, finally the cluster will be unavailable. This PR let servers check whether they are invalid wiggling server and set themselves healthy if so to fix the bug.
3. Fix the double wigglers bug. Now only primary DC can have a wiggler that controls both primary DC and secondary DC wiggle.
4. Add trace details to help debug; Code refactor.
100k …

Properly set simulation test for perpetual storage wiggle and bug fixing

---

bindings/c/test/mako/utils.c

FDBCORE-617: Allocate mako prefix on stack

---

documentation/sphinx/source/administration.rst

Remove use of the word "master" to describe fdbmonitor in documentation.

Documentation wording tweak

---

fdbserver/KeyValueStoreRocksDB.actor.cpp

When estimating the per storage server disk usage, we should estimate the disk usage from the SSTs and not from the underlying data size. This leaves out the memtable, sst files to be deleted and files pinned due to snapshots. I think this is still the most comparable number to other storage engines. 

[RocksDB] Estimate live SST file size and not live data size

---

packaging/docker/Dockerfile.eks

Cherry-pick of https://github.com/apple/foundationdb/pull/4899
To enable fast loading of YCSB data into EKS clusters, this adds the aws cli tool used to download from s3.

Add AWS CLI tool for downloading from s3 (release-7.0)

---

fdbserver/KeyValueStoreRocksDB.actor.cpp

Cherry pick of https://github.com/apple/foundationdb/pull/4956
When estimating the per storage server disk usage, we should estimate the disk usage from the SSTs and not from the underlying data size. This leaves out the memtable, sst files to be deleted and files pinned due to snapshots. I think this is still the most comparable number to other storage engines.

[RocksDB] Estimate live SST file size and not live data size (release-6.3)

---

fdbserver/KeyValueStoreRocksDB.actor.cpp

Cherry pick of https://github.com/apple/foundationdb/pull/4956
When estimating the per storage server disk usage, we should estimate the disk usage from the SSTs and not from the underlying data size. This leaves out the memtable, sst files to be deleted and files pinned due to snapshots. I think this is still the most comparable number to other storage engines.

[RocksDB] Estimate live SST file size and not live data size (release-7.0)

---

fdbserver/workloads/HealthMetricsApi.actor.cpp

Fix TraceEventOverflow error in HealthMetricsApi workload.
2 failed tests are unrelated unit test `/flow/flow/FlowMutex`.
20210613-010706-jzhou-1692d8417464e976             compressed=True data_size=23756603 duration=4098050 ended=104747 fail=3 fail_fast=10 max_runs=100000 pass=100011 priority=100 remaining=0 runtime=0:22:32 sanity=False started=106265 stopped=20210613-012938 submitted=20210613-010706 timeout=5400 username=jzhou

Fix TraceEventOverflow error in HealthMetricsApi workload

---

documentation/sphinx/source/api-c.rst
documentation/sphinx/source/api-python.rst
documentation/sphinx/source/api-ruby.rst

The estimated range size bytes function and similar functions had a few rendering issues in the Sphinx documentation. This attempts to address them.
No testing done except for the PR build.

Fix some documentation rendering issues

---

fdbserver/Resolver.actor.cpp
fdbserver/ResolverInterface.h
fdbserver/ptxn/TeamVersionTracker.actor.cpp
fdbserver/ptxn/TeamVersionTracker.h
fdbserver/ptxn/test/TestResolver.actor.cpp

Because DD can create new teams and remove old teams dynamically, Resolvers
are changed track these teams' changes, notified by proxies.
20210611-230704-jzhou-eafcb05684df6850             compressed=True data_size=24574346 duration=6538006 ended=101421 fail=1 fail_fast=10 max_runs=100000 pass=100330 priority=100 remaining=0 runtime=0:40:59 sanity=False started=101445 stopped=20210611-234803 submitted=20210611-230704 timeout=5400 username=jzhou
This one failure is not related.

Resolvers track new teams or staled teams

---

documentation/sphinx/source/administration.rst
documentation/sphinx/source/api-c.rst
documentation/sphinx/source/api-python.rst
documentation/sphinx/source/api-ruby.rst

This is a backport of #4952 and #4919.
The estimated range size bytes function and similar functions had a few rendering issues in the Sphinx documentation. This attempts to address them.
Remove use of the word "master" to describe fdbmonitor in documentation.
No testing done except for the PR build.

Documentation fixes (release-6.3)

---

documentation/sphinx/source/administration.rst
documentation/sphinx/source/api-c.rst
documentation/sphinx/source/api-python.rst
documentation/sphinx/source/api-ruby.rst

This is a backport of #4952 and #4919.
The estimated range size bytes function and similar functions had a few rendering issues in the Sphinx documentation. This attempts to address them.
Remove use of the word "master" to describe fdbmonitor in documentation.
No testing done except for the PR build.

Documentation fixes (release-7.0)

---

bindings/c/CMakeLists.txt
bindings/c/external_workload.map
bindings/c/generate_asm.py
bindings/c/test/unit/unit_tests_version_510.cpp
bindings/java/CMakeLists.txt

Cherry pick https://github.com/apple/foundationdb/pull/4911 to release-7.0
Previously, lld was unable to link fdb_c.g.S because it required dynamic relocation. This change fixes fdb_c.g.S to not require dynamic relocation, and also fixes a few other issues lld complained of.
Also add a very basic test for an old api header version since I realized we don't have that.

Fix clang build on Arm (release-7.0)

---

fdbclient/NativeAPI.actor.cpp
fdbserver/GrvProxyServer.actor.cpp

Before this change, batch txns are counted together with system/normal txns. When workload is very large, batch txns will be put in queue but never have chance to be executed, thus taking spaces and reduce the throughput of normal txns.
Now in this change, when the limit is hit, we will pop lower priority txn requests, so that new-coming higher priority txn requests can replace them. I've verified that now when both workloads are heavy, batch txns throughput will be reduced to ~0, and normal txns throughput can stay at a way higher level compared to the previous behavior.
20210614-212215-renxuan-499a3d72693f99be           compressed=True data_size=23760870 duration=3343345 ended=101151 fail=2 fail_fast=10 max_runs=100000 pass=100016 priority=100 remaining=0 runtime=0:48:03 sanity=False …

Replace lower priority txn request when limit is hit.

---

bindings/java/src/main/com/apple/foundationdb/JNIUtil.java

After this change, users would be able to add all fdb shared libraries they need in the jar itself with something like `jar uf`, and then they could export them and add them with the network option. Users could also put their shared libraries and external clients in a separate jar.
Users could then add lines like
```
fdb.options().setExternalClientLibrary(JNIUtil.exportLibrary("fdb_c_6_2").getAbsolutePath());
fdb.options().setExternalClientLibrary(JNIUtil.exportLibrary("fdb_c_6_3").getAbsolutePath());
fdb.options().setExternalClientLibrary(JNIUtil.exportLibrary("fdb_c_7_0").getAbsolutePath());
```
at the beginning of their application for each server version they want to support.
The main libfdb_c.so client could also go in a jar, and it will already automatically get used if present.
The …

Add exportLibrary for exporting external clients from jar

---

fdbserver/DataDistribution.actor.cpp
fdbserver/DataDistributionQueue.actor.cpp
fdbserver/Knobs.cpp
fdbserver/tester.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp
fdbserver/workloads/workloads.actor.h

1. Modify simulation test setting: properly set perpetual_storage_wiggle value to its original value. This change makes all tests of which waitQuiescentStart=true also can test perpetual wiggle.
2. Fix `time_out` bug. Sometimes invalid wiggle server appears because the data distributor changing prevents the wiggler from properly setting the status to NONE, which makes this server unavailable afterward. If the number of invalid wiggle server keep increasing, finally the cluster will be unavailable. This PR let servers check whether they are invalid wiggling server and set themselves healthy if so to fix the bug.
3. Fix the double wigglers bug. Now only primary DC can have a wiggler that controls both primary DC and secondary DC wiggle.
4. Add trace details to help debug; Code refactor.
--- …

Fix revert 4929 “Properly set simulation test for perpetual storage wiggle and bug fixing”

---

packaging/docker/release/Dockerfile

Adding `openssl` for debugging TLS related issues.

Add openssl for TLS debugging

---

bindings/java/src/main/com/apple/foundationdb/JNIUtil.java

Cherry pick https://github.com/apple/foundationdb/pull/4930 to release-7.0
After this change, users would be able to add all fdb shared libraries they need in the jar itself with something like `jar uf`, and then they could export them and add them with the network option. Users could also put their shared libraries and external clients in a separate jar.
Users could then add lines like
```
fdb.options().setExternalClientLibrary(JNIUtil.exportLibrary("fdb_c_6_2").getAbsolutePath());
fdb.options().setExternalClientLibrary(JNIUtil.exportLibrary("fdb_c_6_3").getAbsolutePath());
fdb.options().setExternalClientLibrary(JNIUtil.exportLibrary("fdb_c_7_0").getAbsolutePath());
```
at the beginning of their application for each server version they want to support.
The main libfdb_c.so client could …

Add exportLibrary for exporting external clients from jar (release-7.0)

---

fdbserver/StorageMetrics.actor.h
fdbserver/storageserver.actor.cpp

The storage server write path has a number of components that all could be the cause of a write slowdown (e.g.tlog reads, ptree update, disk update, commit). Any of these could be the cause of a storage server’s write path to get behind, but we do not currently have visibility into which component is causing the slowdown.
In this PR, several latency histograms are added into the storage server write path which should help us in understanding/debugging the bottlenecks or performance issues if any.
Testing:
Created a local cluster and done some writes using fdbcli commmands. The trace file showed the following log:
Event Severity="10" Time="1623449363.059950" DateTime="2021-06-11T22:09:23Z" Type="Histogram" ID="0000000000000000" Group="StorageServer" Op="EagerReadsLatency" …

Histograms for storage server write path components.

---

fdbserver/GrvProxyServer.actor.cpp

Patching #4977 to release-7.0.
Before this change, batch txns are counted together with system/normal txns. When workload is very large, batch txns will be put in queue but never have chance to be executed, thus taking spaces and reduce the throughput of normal txns.
Now in this change, when the limit is hit, we will pop lower priority txn requests, so that new-coming higher priority txn requests can replace them. I've verified that now when both workloads are heavy, batch txns throughput will be reduced to ~0, and normal txns throughput can stay at a way higher level compared to the previous behavior.
20210615-211301-renxuan-3d8b67fadee4252b           compressed=True data_size=23365187 duration=3636378 ended=102663 fail_fast=10 max_runs=100000 pass=100038 priority=100 remaining=0 …

Replace lower priority txn request when limit is hit (release-7.0).

---

fdbclient/Schemas.cpp
fdbserver/MasterProxyServer.actor.cpp
fdbserver/Status.actor.cpp

Cherrypicking #4977 to release 6.3. Also, adding GRVBatchLatencyMetrics to release-6.3, which is already in release-7.0 and above.
Before this change, batch txns are counted together with system/normal txns. When workload is very large, batch txns will be put in queue but never have chance to be executed, thus taking spaces and reduce the throughput of normal txns.
Now in this change, when the limit is hit, we will pop lower priority txn requests, so that new-coming higher priority txn requests can replace them. I've verified that now when both workloads are heavy, batch txns throughput will be reduced to ~0, and normal txns throughput can stay at a way higher level compared to the previous behavior.
20210615-185957-renxuan-8fcb95656e18baec           compressed=True data_size=21415399 …

Replace lower priority txn request when limit is hit (release-6.3).

---

documentation/sphinx/source/mr-status-json-schemas.rst.inc
fdbclient/Schemas.cpp

Simple change on JSON schemas: "perpetual_storage_wiggle: 0"

update json schemas

---

fdbserver/worker.actor.cpp

100k joshua run: 20210616-221423-zhewu-4991-eda5176d17c858ce

Remove unused parameters in registrationClient method

---

documentation/sphinx/source/api-general.rst

Clarify a few points about the multi-threaded client that I stumbled upon while using the feature.

Clarify a few points about the multi-threaded client

---

fdbcli/fdbcli.actor.cpp

The `db` in fdbcli is initialized as _-1_ and all `db->apiVersionAtLeast(…)` will succeed whatever the version is considering the [code](https://github.com/apple/foundationdb/blob/master/fdbclient/DatabaseContext.h#L230) .
Thus the check is okay to remove.

remove unnecessary version check in fdbcli commands kill, suspend and expensive_data_check

---

fdbcli/fdbcli.actor.cpp

Cherry-pick #5005 
The _db_ in fdbcli is initialized as _-1_ and all _db->apiVersionAtLeast(…)_ will succeed whatever the version is considering the [code](https://github.com/apple/foundationdb/blob/master/fdbclient/DatabaseContext.h#L230) .
Thus the check is okay to remove.

remove unnecessary version check in fdbcli

---

fdbserver/QuietDatabase.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp

Fixes a simulation bug with TSS fault injection, where the infinite sleep caused markus' double recruitment case to trigger.
I also removed the logic in the consistency check and quiet database that checked the infinite sleep, since with this fix, they should no longer fail indefinitely.
Failed 2 out of 100k correctness tests, but they appear unrelated, as neither of them had TSS enabled, and these changes only change behavior when TSS is enabled with fault injection.

Don't inject TSS faults if speedUpSimulation is set

---

fdbserver/workloads/ConfigureDatabase.actor.cpp
tests/restarting/from_7.0.0/ConfigureTestRestart-1.txt
tests/restarting/from_7.0.0/ConfigureTestRestart-2.txt

The upgrade test (step 1) may choose to modify the descriptor name and kill the cluster before all the processes have made the change. In this case (in step 2), an error could be generated if descriptor mismatches are disallowed. The error is only generated if a knob is set. It is possible the knob was off in step 1 and on in step 2.
For more information see: [issue4984](https://github.com/apple/foundationdb/issues/4984)
This PR adds a switch to the upgrade test forcing the knob to be the same in both steps 1 and 2 of the upgrade. If the knob is set to enable cross cluster traffic, mismatched descriptors is not an error. Otherwise, the descriptor will not be changed so there will also be no error. 
Tested by recreating the original problem, then retesting with the fix.

Do not allow descriptor to change on upgrade tests

---

fdbserver/workloads/ConsistencyCheck.actor.cpp

Fixes a bug in my previous fix of https://github.com/apple/foundationdb/pull/5014.
Failed 2 FlowMutex random unit tests out of 100k, which is unrelated.

Don't fail consistency check if tss is unresponsive

---

fdbserver/QuietDatabase.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp

Cherry-picking https://github.com/apple/foundationdb/pull/5014, https://github.com/apple/foundationdb/pull/5022 to release 7.0
Passed 100k correctness tests

7.0 Cherrypick - Don't inject TSS faults if speedUpSimulation is set

---

fdbserver/masterserver.actor.cpp

Problem:
(1) When a recovery blocks at recovery_transaction phase and we do root cause analysis of it, it is often hard to distinguish which step in the phase blocks the recovery --- The recovery may block at the special transaction, or block at sending TxnStateStore to proxies, or block at initializing resolvers.
(2) In the root cause analysis, we may want to see which proxy is the proxy 0. Proxy 0 is the proxy that accepts special transactions that must keep serial order. However, the current way to identify the proxy 0 is somewhat tricky. We want to clearly see this information in the trace event.
Solution:
(1) Add two trace events --- SentTxnStateStoreToCommitProxies and InitializedAllResolvers to sendInitialCommitToResolvers() in masterserver.actor.cpp.
In recovery_transaction phase, …

Add trace event to recovery_transaction step in recovery (release-7.0)

---

fdbserver/masterserver.actor.cpp

Backporting #5015 to release 6.3.
Problem:
(1) When a recovery blocks at recovery_transaction phase and we do root cause analysis of it, it is often hard to distinguish which step in the phase blocks the recovery --- The recovery may block at the special transaction, or block at sending TxnStateStore to proxies, or block at initializing resolvers.
(2) In the root cause analysis, we may want to see which proxy is the proxy 0. Proxy 0 is the proxy that accepts special transactions that must keep serial order. However, the current way to identify the proxy 0 is somewhat tricky. We want to clearly see this information in the trace event.
Solution:
(1) Add two trace events --- SentTxnStateStoreToCommitProxies and InitializedAllResolvers to sendInitialCommitToResolvers() in …

Add trace event to recovery_transaction step in recovery (release-6.3)

---

fdbrpc/FlowTests.actor.cpp
fdbserver/SimpleConfigDatabaseNode.actor.cpp

FlowMutex test could fail with buggify on due to additional injected delays.  This fix waits for each future to be ready regardless of delay.
Fixed macOS compilation error, for some reason AppleClang is pickier.
I ran the affected unit test with buggify on a few dozen times to prove it works.  It used to fail almost always.

FlowMutex unit test bug and macOS compilation fix

---

fdbserver/StorageMetrics.actor.h
fdbserver/storageserver.actor.cpp

Cherrypick of #4961 . The storage server write path has a number of components that all could be the cause of a write slowdown (e.g.tlog reads, ptree update, disk update, commit). Any of these could be the cause of a storage server’s write path to get behind, but we do not currently have visibility into which component is causing the slowdown.
In this PR, several latency histograms are added into the storage server write path which should help us in understanding/debugging the bottlenecks or performance issues if any. We need these changes in 6.3 to debug the write path issues.
Testing:
20210620-085117-neethuhaneeshabingi-1d003eeb189e1ddf compressed=True data_size=21418697 duration=6522330 ended=100027 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:36:12 …

Cherrypick "Histograms for storage server write path components." to 6.3

---

fdbserver/StorageMetrics.actor.h
fdbserver/storageserver.actor.cpp

Cherrypick of #4961 of master branch in 7.0 branch. The storage server write path has a number of components that all could be the cause of a write slowdown (e.g.tlog reads, ptree update, disk update, commit). Any of these could be the cause of a storage server’s write path to get behind, but we do not currently have visibility into which component is causing the slowdown.
In this PR, several latency histograms are added into the storage server write path which should help us in understanding/debugging the bottlenecks or performance issues if any. We need these changes in 7.0 to debug the write path issues if any.
Testing:
20210621-120318-neethuhaneeshabingi-05e3666f3dc929ed compressed=True data_size=23556711 duration=4809619 ended=101975 fail=1 fail_fast=10 max_runs=100000 pass=100852 …

Cherrypick "Histograms for storage server write path components." to 7.0

---

cmake/CompileRocksDB.cmake

Without these CMake variables, the sanitizers will not be properly enabled for RocksDB. For TSAN in particular, that will lead to false positive failures.

Properly enable santizers in RocksDB build

---

fdbserver/ClusterController.actor.cpp

Cherrypick of #4730 from master to release-6.3 branch. 
Adding TraceEvent when a worker is removed from cluster controller. This log statement helps the SRE's to easily find that a worked is removed form the cluster controller.
As this piece of information is critical to know, it would be beneficial to have it in the release branch.
Testing:
Joshua test run:
20210621-200941-neethuhaneeshabingi-144f310e2f3d01eb compressed=True data_size=21416937 duration=6062686 ended=100268 fail=1 fail_fast=10 max_runs=100000 pass=100115 priority=100 remaining=0 runtime=0:23:08 sanity=False started=100728 stopped=20210621-203249 submitted=20210621-200941 timeout=5400 username=neethuhaneeshabingi
1 test failure seems unrelated to this change and passes when run locally.
Simulation Test run: …

Cherrypick "Adding TraceEvent when a worker is removed from cluster controller." to 6.3

---

fdbserver/ClusterController.actor.cpp

Cherrypick of #4730 from master to release-7.0 branch.
Adding TraceEvent when a worker is removed from cluster controller. This log statement helps the SRE's to easily find that a worked is removed form the cluster controller.
As this piece of information is critical to know, it would be beneficial to have it in the release branch.
Testing:
Joshua test run:
20210621-215037-neethuhaneeshabingi-479aa9e8b40028eb compressed=True data_size=23557640 duration=4917490 ended=100614 fail_fast=10 max_runs=100000 pass=100077 priority=100 remaining=0 runtime=0:48:21 sanity=False started=100704 stopped=20210621-223858 submitted=20210621-215037 timeout=5400 username=neethuhaneeshabingi
Simulation Test run:
build_output/bin/fdbserver -r simulation --crash --logsize 1024MB -f …

Cherrypick "Adding TraceEvent when a worker is removed from cluster controller." to 7.0

---

flow/serialize.h

BinaryWriter::serializeBinaryItem will accept *any* objects and
serialize them by memory copy. If the object is a struct, padding bytes
will also be copied, which is not expected (at this stage, the
serializer will NOT include any padding). If padding exists, the caller
is required to use _Reader::serializeBinaryItem when reading.
Due to this inconsistency, it is helpful to restrict
serializedBinaryItem calls to limited types. Base on the current
implementation, one reasonable approach is allowing only those types
are BINARY_SERIALIZABLE. This patch addresses such restriction.
The restriction is also applied to other classes:
* OverWriter
* _Reader
* PacketWriter
Please …

Add static_assert to serializeBinaryItem

---

documentation/sphinx/source/api-reference.rst
documentation/sphinx/source/global-configuration.rst
documentation/sphinx/source/special-keys.rst

Adds documentation for global configuration and tracing special key space modules. Tested by manually running `ninja docpreview` and verifying the generated pages look right.

Add documentation for global configuration and tracing special key space modules

---

fdbclient/IKnobCollection.h

Deletes are done through a pointer to the base class, so a virtual destructor is needed.

Fix leak due to missing virtual destructor

---

fdbclient/FDBTypes.h
fdbserver/MockLogSystem.cpp
fdbserver/MockLogSystem.h
fdbserver/MockPeekCursor.cpp
fdbserver/MockPeekCursor.h
fdbserver/ptxn/test/RealStorageServer.actor.cpp
tests/ptxn/StorageServer.toml

This can be updated to standalone performance testing for storage server (including the MVCC part). But there are too many dimensions that we can test. I'm not sure which ones are most important to the team. So I'd like to push the less controversial part out for review first and discuss what other knobs (e.g. Make `maxVersionsInMemory` different from default) that we should have.

Support generating arbitrary number of mutations in storage server test

---

fdbserver/storageserver.actor.cpp

This was breaking valgrind correctness

fixed a trace event which used fetchVersion before it was defined in the actor

---

fdbclient/ParallelStream.actor.h

Cherry pick of #5049 
This needs to be in 7.0 because it breaks correctness.

Fixed a destruction order bug with parallel stream

---

fdbserver/storageserver.actor.cpp

cherry pick of #5073
needs to be in 7.0 because it is a correctness problem

fixed a trace event which used fetchVersion before it was defined in the actor 

---

documentation/sphinx/source/api-reference.rst
documentation/sphinx/source/global-configuration.rst
documentation/sphinx/source/special-keys.rst

Cherry-pick of #5060 to 7.0.
Adds documentation for global configuration and tracing special key space modules. Tested by manually running `ninja docpreview` and verifying the generated pages look right.

Add documentation for global configuration and tracing special key space modules (release-7.0)

---

fdbserver/WorkerInterface.actor.h

As pointed out by @xumengpanda [here](https://github.com/apple/foundationdb/pull/5062#discussion_r659467481), we can only append new endpoints in an existing interface.
This PR moves the new updateWorkerHealth endpoint to the end of ClusterControllerFullInterface.
100K Joshua tests: 20210628-185650-zhewu-5081-20de31bc069ead53

Fix endpoint ordering by moving the new updateWorkerHealth to the end of ClusterControllerFullInterface

---

documentation/sphinx/source/api-general.rst

Cherry pick https://github.com/apple/foundationdb/pull/5000 to release-7.0
Clarify a few points about the multi-threaded client that I stumbled upon while using the feature.

Clarify a few points about the multi-threaded client (release-7.0)

---

documentation/sphinx/source/api-general.rst

Cherry pick https://github.com/apple/foundationdb/pull/5000 to release-6.3
Clarify a few points about the multi-threaded client that I stumbled upon while using the feature.

Clarify a few points about the multi-threaded client (release-6.3)

---

fdbserver/CommitProxyServer.actor.cpp
fdbserver/LogSystem.h
fdbserver/ProxyCommitData.actor.h
fdbserver/TagPartitionedLogSystem.actor.cpp

This metric is to understand the impact of batching on empty commit messages.
If the ratio is high, it means proxy sends many empty commit messages, which
can potentially be optimized for better performance. If the ratio is low, which
means the spread factor is large, thus we need to optimize the proxy to reduce
such a factor.
20210625-043841-jzhou-fb2bfa691220d153             compressed=True data_size=24730710 duration=5597181 ended=102238 fail_fast=10 max_runs=100000 pass=100186 priority=100 remaining=0 runtime=0:58:18 sanity=False started=102614 stopped=20210625-053659 submitted=20210625-043841 timeout=5400 username=jzhou …

Add metric to track the ratio of empty messages to tlogs

---

fdbserver/CommitProxyServer.actor.cpp
fdbserver/LogSystem.h
fdbserver/ProxyCommitData.actor.h
fdbserver/TagPartitionedLogSystem.actor.cpp

Cherry-pick #5071 
This metric is to understand the impact of batching on empty commit messages.
If the ratio is high, it means proxy sends many empty commit messages, which
can potentially be optimized for better performance. If the ratio is low, which
means the spread factor is large, thus we need to optimize the proxy to reduce
such a factor.
20210628-165245-jzhou-e5554cc567e42ad3             compressed=True data_size=23832694 duration=4823648 ended=100892 fail_fast=10 max_runs=100000 pass=100001 priority=100 remaining=0 runtime=0:56:33 sanity=False started=101391 stopped=20210628-174918 submitted=20210628-165245 timeout=5400 username=jzhou …

Cherry-pick Release-7.0: Add metric to track the ratio of empty messages to tlogs

---

fdbserver/LogSystem.h
fdbserver/MasterProxyServer.actor.cpp
fdbserver/TagPartitionedLogSystem.actor.cpp

Cherry-pick #5071
This metric is to understand the impact of batching on empty commit messages.
If the ratio is high, it means proxy sends many empty commit messages, which
can potentially be optimized for better performance. If the ratio is low, which
means the spread factor is large, thus we need to optimize the proxy to reduce
such a factor.
20210629-002733-jzhou-fea1469beaa2a5e1             compressed=True data_size=21408446 duration=5882385 ended=102187 fail=1 fail_fast=10 max_runs=100000 pass=100094 priority=100 remaining=0 runtime=1:01:35 sanity=False started=102305 stopped=20210629-012908 submitted=20210629-002733 timeout=5400 username=jzhou
`DDBalanceAndRemoveStatus.txt` has timeout error of "Unable to perform consistency check", which is unrelated to this PR.
The general …

Cherrypick Release 6.3: Add metric to track the ratio of empty messages to tlogs

---

flow/ThreadHelper.actor.h

The `onMainThread` functions are currently under documented and somewhat hard to use. This PR reorganizes the code slightly and adds some documentation. 
The only actual code change is to make the `err` parameter in `onMainThreadVoid` optional. Most uses of it currently already pass in `nullptr`, so those could be made more concise. I did not make those changes simply to make this PR smaller.

Add some documentation for the onMainThread functions

---

fdbserver/workloads/UnitTests.actor.cpp
flow/CMakeLists.txt
flow/IThreadPool.cpp
flow/IThreadPoolTest.actor.cpp

A refactoring accidentally deleted passing the `name` parameter along to `startThread`. This both fixes that error and adds a test to ensure that future changes don't break the feature.

Fix IThreadPool thread naming

---

cmake/AddFdbTest.cmake

By default the correctness package will be built to `packages/correctness-${FDB_MAJOR_VERSION}.${FDB_MINOR_VERSION}.${FDB_PATCH_VERSION}.tar.gz` (and similar for valgrind package).
This is inconvenient for scripting. This PR simply adds two new cmake targets that will copy the correctness and valgrind packages to a new file that doesn't contain the version (`packages/correctness.tar.gz`).
I tested this just by running it locally. As currently no automation exists that runs these target (and these targets don't depend on `all`), this should be very high risk. …

Add target to build unversioned correctness pkgs

---

fdbrpc/fdbrpc.h

Sending the error is leading to the destruction of the acknowledgementReceiver,
so we keep a local copy.

Hold a local copy of the ready promise to avoid the destruction of acknowledgementReceiver

---

flow/IThreadPoolTest.actor.cpp

Per discussion on original PR (https://github.com/apple/foundationdb/pull/5092), this test is currently failing on Joshua with a segfault somewhere inside simulation. This runs the test outside simulation, which has succeeded for me locally a number of times. (Joshua job pending)

Don't run IThreadPool name test on simulation

---

fdbclient/CMakeLists.txt
fdbclient/FDBTypes.h
fdbclient/VersionVector.h
fdbserver/masterserver.actor.cpp

Changes:
VersionVector.h: Create a data structure to hold the version vector. 
FDBTypes.h: Customize hash so we can use Tag as the key for an unordered_map.
masterserver.actor.cpp: Create an instance of the version vector in "MasterData".
Notes:
- I imagine more fields will be added to the version vector (and improvements will be made to its "serialize()" method) as we add various suggested optimizations to the version vector.
- I hope to use the version vector to also hold the previous commit versions of logs (TPCVs) on the sequencer. If we do decide to do that then we can templatize the version vector to be a map of Tag/UUID to a Version.
Testing:
- Started simulation tests (ID: 20210629-194901-sre-3273684ea475d6bd) …

Introduce Version Vector

---

flow/Trace.cpp
flow/Trace.h

This is needed for multithreaded client debugging, and should also be helpful for multithreaded storage engines, SSL handshake threadpools, and so on
I'd rather use more human-readable numbers (0, 1, 2, ...) by incrementing a static int once per thread, but that won't work for client code, which uses linker tricks to create one copy of all the global variables per client thread.
I tested this by running:
```
~/src/foundationdb/tests/loopback_cluster/run_cluster.sh . 3 '/root/src/foundationdb/tests/python_tests/multithreaded_client.py loopback-cluster-*/fdb.cluster --threads 3 '
```
and then:
```
for i in client-logs/* ; do echo $i; perl -ne 's/^.+(ThreadID\S+).+$/$1/ && print;'< $i | uniq -c  ;done
client-logs/trace.127.0.0.1.24723.1625088374.3EabNv.0.1.xml
25 …
```

Add a ThreadID field to each TraceEvent.

---

fdbclient/ManagementAPI.actor.cpp

Valgrind surfaced an invalid read on commit de898cd8abe448cbbb70197cc697602ffc7c4848:
```
./bin/fdbserver -r simulation -f ../foundationdb/tests/fast/SwizzledRollbackSideband.toml --seed 462862274 --buggify on
```
Relevant backtrace from valgrind log:
```
==1030== Invalid read of size 16
==1030==    at 0x331A5BC: _mm_loadu_si128 (emmintrin.h:703)
==1030==    by 0x331A5BC: rte_mov16 (rte_memcpy.h:306)
==1030==    by 0x331A5BC: rte_memcpy_generic (rte_memcpy.h:404)
==1030==    by 0x331A5BC: rte_memcpy (rte_memcpy.h:870)
==1030==    by 0x331A5BC: memcpy (flow.cpp:38)
==1030==    by 0x4204F7: std::char_traits<char>::copy(char*, char const*, unsigned long) (char_traits.h:352)
==1030==    by 0x4320F6: std::string::_M_copy(char*, char const*, unsigned long) (basic_string.h:3382)
==1030==    by …
```

Fix invalid read

---

fdbclient/ManagementAPI.actor.cpp

Cherry pick of #5112 to `release-7.0`.
Fixes an invalid read surfaced by Valgrind. See linked PR for an explanation.
Passed 100k correctness tests.

Fix invalid read (release-7.0)

---

tests/TestRunner/TestRunner.py

Cherry-pick CI fix #4985 
50k simulation tests pass.

Cherry-pick #4985 "add injected fault check"

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/OldTLogServer_6_2.actor.cpp
fdbserver/TLogServer.actor.cpp

Problem:
There are two incidents where disk occupancy of TLogs can abnormally large: (1) the recovery gets stuck between accepting_commits step and full_recovery step; (2) SS falls far behind the TLog.
In both incidents, we want to know whether existing a TLog which disk occupancy is abnormally large? If yes, which tag blocks discarding the tail of DiskQueue of the tLog? Since the tail of the DiskQueue can be discarded only if all the tags have been popped from the oldest commit in the DiskQueue. 
Solution:
logData->queuePoppedVersion is the oldest version that is still useful.
logData->persistentDataDurableVersion is the latest version spilled on disk.
Then the field PoppedVersionLag (= logData->persistentDataDurableVersion - logData->queuePoppedVersion) indicates us how many versions …

Add trace event to tLog pop

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/VersionedBTree.actor.cpp

Added range read prefetching back to Redwood with a conservative approach that should rarely read blocks not needed for the range read.  Removed unused knob declarations.
Passed 200k correctness with storage engine set to Redwood
```
20210704-041110-satherton_foundationdb.redwood-ce6b51371777ad64
20210704-090850-satherton_foundationdb.redwood-9ecc6688e4701412
```

Redwood range read prefetching

---

fdbclient/ServerKnobs.cpp
fdbserver/OldTLogServer_6_2.actor.cpp
fdbserver/TLogServer.actor.cpp

For PR #5117:
1. Clean up code added by PR #5117.
2. Change config. In PR #5117, respecting to the overhead, this event message appears only in recovery (before the tLog pop passes recoveryAt) or when the version scope on tLog disk queue is larger than 2/5 * STORAGE_DURABILITY_LAG_SOFT_MAX.
Now, we change 2/5 * STORAGE_DURABILITY_LAG_SOFT_MAX to STORAGE_DURABILITY_LAG_SOFT_MAX.
3. Generate the event only when logData->queuePoppedVersion > 0 to avoid generating massive events at beginning.
Passed Joshua correctness-7.1.0 test: 20210707-203250-zhewang-8a8bcf83b66fe8f0 …

Clean up add_trace_event_to_tLog_pop

---

fdbbackup/backup.actor.cpp
fdbclient/BackupAgent.actor.h
fdbclient/TaskBucket.actor.cpp
fdbclient/TaskBucket.h
fdbserver/SimulatedCluster.actor.cpp

Adds reference counting and const-correctness to the `pollDelay` argument of `*BackupAgent::run`, for clarity and safety. `std::shared_ptr` is used because `double` is not reference counted, and the thread safety overhead shouldn't matter here.

Improve safety of backup agent poll delay

---

fdbserver/Knobs.cpp
fdbserver/Knobs.h
fdbserver/OldTLogServer_6_2.actor.cpp
fdbserver/TLogServer.actor.cpp

Backporting #5117 and #5129 to release 6.3.
Passed Joshua test correctness-6.3.17: 20210707-225700-zhewang-1221428759db34c7.

Add trace event to tLog pop for release-6.3

---

fdbclient/CommitProxyInterface.h
fdbclient/DatabaseContext.h
fdbclient/FDBTypes.h
fdbclient/NativeAPI.actor.cpp
fdbserver/GrvProxyServer.actor.cpp
fdbserver/masterserver.actor.cpp

Changes:
GrvProxyServer.actor.cpp:
- Cache the version vector on the grv proxy
- Update the local version vector cache on receiving the latest version vector (from the sequencer)
as part of the GetRawCommittedVersionReply message.
- Provide the latest version vector to the client as part of the GetReadVersionReply message.
masterserver.actor.cpp:
- Provide the latest version vector to the grv proxy as part of the GetRawCommittedVersionReply
message.
DatabaseContext.h:
- Cache the version vector to be made available to the client.
NativeAPI.actor.cpp:
- Update the local version vector cache on receiving the latest version vector (from the grv proxy)
as part of the GetReadVersionReply message.
CommitProxyInterface.h:
- Extend GetReadVersionReply and GetRawCommittedVersionReply so as to be …

Version vector prototype: cache version vector on grv proxy and client

---

fdbserver/ptxn/MessageSerializer.cpp
fdbserver/ptxn/MessageSerializer.h
fdbserver/ptxn/Serializer.h
fdbserver/ptxn/TLogPeekCursor.actor.cpp
fdbserver/ptxn/test/CommitUtils.cpp
fdbserver/ptxn/test/CommitUtils.h
fdbserver/ptxn/test/TestTLogServer.actor.cpp
fdbserver/ptxn/test/Utils.cpp
fdbserver/ptxn/test/Utils.h
tests/ptxn/TLogServer.toml

* Enable the peek TLog server test
* Add a test that interlaces commit and peek for TLog
* Add a note on the deserializer related to the use of the internal arena

Re-enable the test for TLog peek

---

fdbclient/BackupAgent.actor.h
fdbclient/BackupAgentBase.actor.cpp
fdbclient/DatabaseBackupAgent.actor.cpp

I can make a fast consistent copy of a fdb cluster by stopping a DR site and copy all the files from all DR nodes to a new cluster nodes and detach this copy from the primary site.
I can perform a point-in-time recovery from this copy with fdbrestore start --incremental --begin_version XXXXXXX.
But there is no easy way to get a source db version for using with --begin_version option.
When dr agent runs it executes dr_copy_diff_logs tasks for copying version intervals of the mutation log to the DR database, When the task is executing, it has beginVersion: the version all changes before have been copied.
Store beginVersion to the state subspace of system keyspace each time dr_copy_diff_logs executes
Read this version from the state subspace and return as result of fdbdr status
This pull …

Provide log version information to fdbdr status

---

fdbclient/CommitProxyInterface.h
fdbclient/GrvProxyInterface.h
fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/ClusterController.actor.cpp
fdbserver/ResolverInterface.h

This PR implements the main logic in cluster controller that triggers a recovery when a degraded server in the current transaction system is detected.
Currently, following constraints are applied when triggering a recovery:
- We only allow at most 2 recoveries within 1 hour due to degradation.
- We only allow at most 3 servers to be excluded due to degradation.
- When more than 3 servers are complaining about one server, that server won't be considered as degraded, to avoid excluding a hot server.
Also when knob `CC_HEALTH_TRIGGER_RECOVERY` is set to false, no recovery is triggered but a TraceEvent is generated to hint that there should be a recovery.
Unit tests are created to test all the new functions.
100K joshua tests: 20210630-055303-zhewu-5088-3083ec780ba38790
The general guidelines …

Implement the main logic of gray network triggered recovery in Cluster Controller

---

fdbserver/KeyValueStoreRocksDB.actor.cpp

RocksDB reports a missing key as an error, but that is not an error from the FoundationDB perspective. This is already the behavior for `readValue`. This PR makes `readValuePrefix` consistent.

Don't log key not found as an error

---

fdbclient/ManagementAPI.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/Knobs.cpp
fdbserver/Knobs.h
fdbserver/tester.actor.cpp

When test perpetual wiggle and the TSS recruitment on a real cluster, We found perpetual storage seldomly make a progress. The reason is following:
* `AddressExclusion addr(info->lastKnownInterface.address().ip);` will exclude not only the chosen process but all the processes on a machine. Other processes on the machine will reset the WIGGLING status to NONE once they detect their processId != wigglingId, which will pause the wiggle of the chosen process. This is fixed by also assign the port `AddressExclusion addr(info->lastKnownInterface.address().ip, info->lastKnownInterface.address().port);`
Some improvements:
* This PR also relax the wiggle pause condition a little by changing one of the pause condition to `self->bestTeamKeepStuckCount > …

Fix perpetual wiggle AddressExclusion bug and relax pause condition

---

fdbserver/KeyValueStoreRocksDB.actor.cpp

Cherry pick of https://github.com/apple/foundationdb/pull/5143
RocksDB reports a missing key as an error, but that is not an error from the FoundationDB perspective. This is already the behavior for readValue. This PR makes readValuePrefix consistent.

Don't log key not found as an error (release-7.0)

---

fdbserver/LogSystem.h
fdbserver/LogSystemConfig.h
fdbserver/MockLogSystem.cpp
fdbserver/MockLogSystem.h
fdbserver/StorageCache.actor.cpp
fdbserver/TagPartitionedLogSystem.actor.cpp
fdbserver/WorkerInterface.actor.h
fdbserver/ptxn/TLogInterface.h
fdbserver/ptxn/TLogPeekCursor.actor.cpp
fdbserver/ptxn/TLogPeekCursor.actor.h
fdbserver/ptxn/test/Driver.h
fdbserver/ptxn/test/TestTLogPeek.actor.cpp
fdbserver/ptxn/test/TestTLogServer.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/worker.actor.cpp
tests/ptxn/TLogServer.toml

- Add storage team concept into StorageServer (for now, storage server only manages single storage team)
- Implement ServerPeekCursor to be compatible with storage server which talks to ptxn tlog interfaces.
- Add run_storage_server unit test that runs against new ptxn tlogs

Implement ServerPeekCursor to be compatible with storage server

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbclient/VersionVector.h
fdbserver/CommitProxyServer.actor.cpp
fdbserver/LogSystem.h
fdbserver/LogSystemConfig.h
fdbserver/MasterInterface.h
fdbserver/masterserver.actor.cpp
flow/network.h

- after commit resolve: The Proxy sends the sets of affected tlogs (index format) to the sequencer;
- the Sequencer returns each tlog’s previous commit version (TPCV) 
- The TPCV has dummy values for now. A subsequent PR will use the TPCV.
- after tlogs persist data: the Proxy notifies the Sequencer that the transaction with CV has committed with the sets of affected storage tags (including replicas in team)
- created knob for the feature

Features/version vector - Initial proxy changes

---

flow/Trace.h

0x5C `'\'` should not be counted as normal printables

Fix printable bytes that may be escaped incorrectly

---

fdbclient/MultiVersionTransaction.actor.cpp
fdbrpc/FlowTests.actor.cpp
fdbrpc/sim2.actor.cpp
fdbserver/DataDistributionQueue.actor.cpp
fdbserver/KeyValueStoreMemory.actor.cpp
fdbserver/fdbserver.actor.cpp
fdbserver/workloads/ThreadSafety.actor.cpp
flow/IThreadPool.cpp
flow/IThreadPoolTest.actor.cpp
flow/Net2.actor.cpp
flow/UnitTest.h
flow/network.h

Prior to this change, running nearly any FDB code on an IThreadPool thread in simulation would crash because the necessary thread locals were not getting set. This change pipes through the necessary configuration so that IThreadPool can use the `g_network` API that will properly set the thread locals. It also changes the one test I was aware of that uses the background thread pool to run in simulation.

Enable IThreadPool in simulation

---

flow/Arena.h
flow/flow.h

This has several advantages:
- If `std::is_trivially_destructible_v<T>`, then `std::is_trivially_destructible_v<ErrorOr<T>>`, so `VectorRef<ErrorOr<T>>` now works for trivially destructible types T.
- No need for error-prone reimplementation of STL functions (and we get the benefits of STL improvements for free).
- Several optimizations have been added to `ErrorOr` and `Optional` to support perfect forwarding.

Use std::variant for ErrorOr implementation

---

fdbserver/KeyValueStoreRocksDB.actor.cpp

Cherry pick of https://github.com/apple/foundationdb/pull/5143
RocksDB reports a missing key as an error, but that is not an error from the FoundationDB perspective. This is already the behavior for readValue. This PR makes readValuePrefix consistent.

Don't log key not found as an error (release-6.3)

---

bindings/java/CMakeLists.txt
bindings/java/src/README.md
bindings/java/src/integration/com/apple/foundationdb/BasicMultiClientIntegrationTest.java
bindings/java/src/integration/com/apple/foundationdb/DirectoryTest.java
bindings/java/src/integration/com/apple/foundationdb/MultiClientHelper.java
bindings/java/src/tests.cmake
cmake/AddFdbTest.cmake
tests/TestRunner/tmp_cluster.py
tests/TestRunner/tmp_multi_cluster.py

This is cherry-pick of #4456 which was merged into 6.3 but appears to be missing in master.

Making it possible to run a multiple-cluster Java integration test (cherry-pick of #4456 from 6.3)

---

fdbserver/ClusterController.actor.cpp

Cherry pick of #5104.
This fixes a simulation failure originally surfaced on the `release-7.0` branch (commit 540da1e4abd78165ab4423735ad00c7f3f8739aa):
```
./bin/fdbserver -r simulation -f ../foundationdb/tests/slow/CommitBug.toml --seed 322853697 --buggify on
```
Passed 100,000 correctness tests on Joshua.

Disable recruitment determinism check for configurations with remote satellites (release-7.0)

---

fdbserver/ClusterController.actor.cpp

This fixes a simulation failure originally surfaced on the `release-7.0` branch (commit 540da1e4abd78165ab4423735ad00c7f3f8739aa):
```
./bin/fdbserver -r simulation -f ../foundationdb/tests/slow/CommitBug.toml --seed 322853697 --buggify on
```
The recruitment phase has a determinism check to make sure running two recruitments using the same input results in the same configuration. This is to help prevent constantly changing between configurations.
However, when specifically recruiting satellite tlogs in a remote region, the order is not always deterministic. Since using satellites in a remote region is somewhat rare, this fix just disables the determinism check when there are satellites in a remote region. If using a remote region for satellites, there could potentially be some thrashing …

Disable recruitment determinism check for configurations with remote satellites

---

bindings/java/src/integration/com/apple/foundationdb/CycleMultiClientIntegrationTest.java
bindings/java/src/tests.cmake

FDB clients are multi-threaded and connecting to multiple clusters,
this commit adds a test to validate the multi-threaded client can
achieve atomicity.
See https://github.com/FoundationDB/fdb-kubernetes-tests/pull/229 for k8s part.
log proof:
log 
```
<Event Severity="10" Time="1625847081.711147" DateTime="2021-07-09T16:11:21Z" Type="CopyingExternalClient" ID="0000000000000000" FileName="libfdb_c.so" LibraryPath="/var/dynamic-conf/lib/libfdb_c.so" TempPath="/tmp/libfdb_c.so-M2p7Z8\x00\x96\xed\xcaCI\x7f\x00\x00p\xc4\x09\x00\x01\x00\x00\x00\xb0#2CI\x7f\x00\x00\x00\xe7\xa6AI\x7f\x00\x00\x00\x …
```

    Add CycleMultiClientIntegrationTest

---

fdbserver/workloads/UnitTests.actor.cpp
flow/CMakeLists.txt
flow/IThreadPool.cpp
flow/IThreadPoolTest.actor.cpp

Cherry pick of https://github.com/apple/foundationdb/pull/5092 and https://github.com/apple/foundationdb/pull/5097 (the latter fixes the test)
A refactoring accidentally deleted passing the name parameter along to startThread. This both fixes that error and adds a test to ensure that future changes don't break the feature.

Fix IThreadPool thread naming (release 7.0)

---

fdbserver/TagPartitionedLogSystem.actor.cpp

An invalid read was surfaced by Joshua on commit 74e1f49512016c5e613750c6a4f637ade664012d (on the `release-7.0` branch). The same bug appears to be in master.
```
valgrind --log-file=valg8.log ./bin/fdbserver -r simulation -f ../foundationdb/tests/fast/FuzzApiCorrectness.toml --seed 671659932 --buggify off
```
```
﻿==33317== Invalid read of size 8
==33317==    at 0x16C7EF6: TagPartitionedLogSystem::GetPoppedTxsActorState<TagPartitionedLogSystem::GetPoppedTxsActor>::a_body1cont1(Void const&, int) (TagPartitionedLogSystem.actor.cpp:1535)
==33317==    by 0x16BD8E2: TagPartitionedLogSystem::GetPoppedTxsActorState<TagPartitionedLogSystem::GetPoppedTxsActor>::a_body1when1(Void const&, int) (TagPartitionedLogSystem.actor.g.cpp:3182)
==33317==    by 0x16F2F2A: …
```

Fix invalid read in TagPartitionedLogSystem

---

fdbmonitor/fdbmonitor.cpp

Resolves #5172
Fdbmonitor had a bug where it would silently fail to start processes that have the same ID, which is possible if you configure something like:
```
[sectionA.1]
...
[sectionB.1]
```
I'm guessing this was mostly not an experienced issue because fdbserver used port numbers as IDs and we generally only ran backup agents as the second binary starting from ID 1, resulting in no collisions.
This change updates it so that IDs are instead section unique.
Tested by manually creating conf files and observing the results. …

Make fdbmonitor IDs unique per section rather than globally unique

---

fdbclient/ServerKnobs.cpp
fdbserver/KeyValueStoreRocksDB.actor.cpp
fdbserver/SimulatedCluster.actor.cpp
tests/restarting/from_6.2.33/SnapCycleRestart-1.txt
tests/restarting/from_6.2.33/SnapCycleRestart-2.txt
tests/restarting/from_6.2.33/SnapTestAttrition-1.txt
tests/restarting/from_6.2.33/SnapTestAttrition-2.txt
tests/restarting/from_6.2.33/SnapTestRestart-1.txt
tests/restarting/from_6.2.33/SnapTestRestart-2.txt
tests/restarting/from_6.2.33/SnapTestSimpleRestart-1.txt
tests/restarting/from_6.2.33/SnapTestSimpleRestart-2.txt
tests/restarting/from_7.0.0/SnapIncrementalRestore-1.toml
tests/restarting/from_7.0.0/SnapIncrementalRestore-2.toml

Changes required to enable RocksDB in production. The biggest change is to use the `CoroFlow` thread pool so that all RocksDB actions happen on the main thread. Otherwise, the network thread will advance time too fast because it has nothing to do.
RocksDB is disabled in the snapshot tests due to https://github.com/apple/foundationdb/issues/5155. Has 
passed >50k Joshua tests with the RocksDB engine selected.

RocksDB in simulation

---

fdbclient/ServerKnobs.cpp
fdbserver/KeyValueStoreRocksDB.actor.cpp
fdbserver/SimulatedCluster.actor.cpp
tests/restarting/from_6.2.33/SnapCycleRestart-1.txt
tests/restarting/from_6.2.33/SnapCycleRestart-2.txt
tests/restarting/from_6.2.33/SnapTestAttrition-1.txt
tests/restarting/from_6.2.33/SnapTestAttrition-2.txt
tests/restarting/from_6.2.33/SnapTestRestart-1.txt
tests/restarting/from_6.2.33/SnapTestRestart-2.txt
tests/restarting/from_6.2.33/SnapTestSimpleRestart-1.txt
tests/restarting/from_6.2.33/SnapTestSimpleRestart-2.txt
tests/restarting/from_7.0.0/SnapIncrementalRestore-1.toml
tests/restarting/from_7.0.0/SnapIncrementalRestore-2.toml

Reverts apple/foundationdb#5144
Correctness failed 10/20 tests with the following segfault: Output="Assertion false failed @ /mnt/ephemeral/etschannen/foundationdb/fdbserver/KeyValueStoreRocksDB.actor.cpp 899:" /><StdErrOutput Severity="40" Output="  addr2line -e fdbserver.debug -p -C -f -i 0x2fba0e1 0x17b4eb1 0x212f461 0x2117efd 0x1342dec 0x2e81067 0x2e80d41 0x114e898 0x2f284c3 0x2f28316 0x2f28a0c 0x114e898 0x2ffdf06 0x2fef07d 0x2ef79ab 0x17324c3 0x7f946bb35555" /><StdErrOutput Severity="40" Output="SIGNAL: Segmentation fault (11)" /><StdErrOutput Severity="40" Output="Trace: addr2line -e fdbserver.debug -p -C -f -i 0x7f946bef0630 0x2fba1ed 0x17b4eb1 0x212f461 0x2117efd 0x1342dec 0x2e81067 0x2e80d41 0x114e898 0x2f284c3 0x2f28316 0x2f28a0c 0x114e898 0x2ffdf06 0x2fef07d 0x2ef79ab 0x17324c3 …

Revert "RocksDB in simulation"

---

fdbrpc/FlowTransport.actor.cpp
fdbrpc/fdbrpc.h
fdbserver/storageserver.actor.cpp
flow/network.h

This bug could result in data loss or data corruption in the rare event that a storage server fetched data from itself.
failed 1/200k - the failure was a non-determinism in a status test which should not be related to this change.

fix: reply promise streams could receive messages out of order when using local delivery

---

bindings/java/src/integration/com/apple/foundationdb/SidebandMultiThreadClientTest.java
bindings/java/src/tests.cmake

This test validates causal consistency for multi-threaded client
This test validates causal consistency for multi-threaded client
I have tested that if we offer the key to consumer before the producer commits the txn, we see failures as below, thus we have confident it is really testing against causal consistency.
```
2021/07/13 14:34:53 pods.go:166: Exception in thread "main" org.opentest4j.AssertionFailedError: Sideband test failed ==> expected: <true> but was: <false>
at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:193)
at com.apple.foundationdb.SidebandMultiThreadClientTest.check(SidebandMultiThreadClientTest.java:65)
at …
```

Add SidebandMultiThreadClientTest

---

bindings/java/src/integration/com/apple/foundationdb/CycleMultiClientIntegrationTest.java

In order to have multiple threads running against same cluster, this has to be done.

Setup cycleTest in the same txn

---

contrib/TestHarness/Program.cs.cmake

When I run FoundationDb with joshua testing framework, all tests are failed with `NoTraceFileGenerated` error. I asked for a help in https://forums.foundationdb.org/t/simulation-testing-of-foundationdb/2654/6 but nobody could troubleshoot it.
After some debugging I found that TestHarness.exe tried to start fdbserver but it couldn't start (in my case due an incompatible glibc version). In this case fdbserver did not write any trace files, so TestHarness.exe raised `NoTraceFileGenerated`. But such troubleshooting is not possible without debugging.
If fdbserver failed to start, then log the root cause instead of `NoTraceFileGenerated`.
After running correctness tests with changed TestHarness.exe, I receive a log with the real errors
```
python3 -m joshua.joshua -C …
```

Fixed 'NoTraceFileGenerated' error in simulation tests when the fdbserver process could not start

---

fdbclient/CommitProxyInterface.h
fdbclient/DatabaseContext.h
fdbclient/NativeAPI.actor.cpp
fdbclient/StorageServerInterface.h
fdbclient/VersionVector.h
fdbserver/BackupWorker.actor.cpp
fdbserver/CommitProxyServer.actor.cpp
fdbserver/GrvProxyServer.actor.cpp
fdbserver/TLogServer.actor.cpp
fdbserver/masterserver.actor.cpp
fdbserver/storageserver.actor.cpp

Main changes:
- Propagate latest commit version from client to storage server
- Make a storage server read at the latest commit version (instead of the actual read version)
- Make a peek request block on a tlog until the tlog has a commit that is relevant to the requester (code changes to accomplish this have been extracted from https://github.com/apple/foundationdb/pull/5058)
- Propagate version vector deltas between processes
Changes related to the propagation of the latest commit version from client to storage server and to make a storage server read at the latest commit version:
CommitProxyInterface.h:
- Let the proxy return the tags of storage servers (along with the storage server interfaces) as part of GetKeyServerLocationsReply.
DatabaseContext.h:
- Map the tags of storage servers …

Version vector prototype: propagate latest commit version from client to storage server

---

fdbserver/CommitProxyServer.actor.cpp
fdbserver/LogSystem.h
fdbserver/MasterInterface.h
fdbserver/TagPartitionedLogSystem.actor.cpp
fdbserver/masterserver.actor.cpp

version vector support, enabled with knob:
- Maintain the previous commit version per tLog (the `TPCV` vector) in the sequencer.
- Update the TPCV vector only once the previous transaction (at cluster level) has updated it.
- Do not reply to the client out of order.
- process transactions in "per-tLog order" in the tLog
This must be integrated with [PR5161](https://github.com/apple/foundationdb/pull/5161), else, reads stall as transactions are no longer written to all tLogs. note reads are internally generated, (e.g. `getServerListAndProcessClasses` generates transactions to read the system keyspace) …

version vector / maintain tLog previous commit version vector

---

fdbserver/TagPartitionedLogSystem.actor.cpp

Cherry pick of #5180. Fixes #5165.
Fixes an invalid read found by Valgrind on commit 74e1f49512016c5e613750c6a4f637ade664012d.
```
valgrind --log-file=valg8.log ./bin/fdbserver -r simulation -f ../foundationdb/tests/fast/FuzzApiCorrectness.toml --seed 671659932 --buggify off
```
See the linked issue for more info.
Passed 100,000 correctness tests on Joshua.

Fix invalid read in TagPartitionedLogSystem (release-7.0)

---

README.md

This PR fixes #4921 by updating the docker image to used to build fdb.

Update documentation to build with docker

---

fdbserver/VersionedBTree.actor.cpp
flow/Arena.h

Tested that `LiteralStringRef(std::to_string(levelCounter).c_str())` no longer compiles

Static assert that LiteralStringRef arg is literal string

---

bindings/python/tests/fdbcli_tests.py

`Exclude` can take longer than current time_out time,
not sure if it's a bug or it's flaky, disable it for now to fix CI

Disable test for exclude for now which can time out sometime

---

fdbclient/BackupContainerAzureBlobStore.actor.cpp
fdbclient/BackupContainerFileSystem.actor.cpp
fdbclient/BackupContainerS3BlobStore.actor.cpp
fdbrpc/AsyncFileEncrypted.h
fdbrpc/CMakeLists.txt
fdbrpc/Net2FileSystem.cpp
fdbrpc/sim2.actor.cpp
flow/CMakeLists.txt
flow/StreamCipher.h

This resolves https://github.com/apple/foundationdb/issues/5148 by using an `ENCRYPTION_ENABLED` macro to disable usages of `openssl` when they won't compile.

Fix build with DISABLE_TLS=ON

---

documentation/sphinx/source/release-notes/release-notes-700.rst

7.0 release notes of exclude locality and write path histogram features.

7.0 release notes of exclude locality and write path histogram features.

---

documentation/sphinx/source/ha-write-path.rst
documentation/sphinx/source/technical-overview.rst

Fix problems in #5223:
(1) Include FDB HA write path doc in toctree.
(2) Fix format issue in RST.
(3) Change code pointer to apple/foundationdb repo.

Include FDB HA write path doc in toctree

---

fdbserver/workloads/UnitTests.actor.cpp

It is not always possible to create the `/private` directory.

Change default data directory for unit tests outside simulation

---

bindings/c/test/mako/mako.c
bindings/c/test/mako/mako.h
bindings/c/test/mako/utils.c
bindings/c/test/mako/utils.h

Description
This PR backports mako latency measurements from master to release-6.3 branch. This is so we'd have latency data for mako workloads with 6.3 clusters.
Current workaround is to get mako binary from a 7.0/master build.
Git command to cherry-pick:
```
git checkout release-6.3
git cherry-pick 22a48f8349739f745adc18136d83681910e2746c^..c88986b1530cbd952a45ef36e4f89789c8f13bc6
```
Testing

Backport to 6.3: Added median and 99.9 percentile latency measurement

---

.gitignore

Cherry-pick of #5237
Add VSCode workspace file pattern to .gitignore.

Cherry pick #5237 to release-7.0:  Add VSCode workspace file pattern to .gitignore.

---

cmake/AddFdbTest.cmake

We shouldn't rely on python scripts having execute permissions. This change calls the python interpreter instead.
I verified that with this change, `ctest -R integration` succeeds.

Fix Java integration tests

---

bindings/python/tests/fdbcli_tests.py

The original test did not catch the warnings when a coordinator is excluded.
The pr fixed it and reenable the test.

Fix exclude test and re-enable it in ctest

---

bindings/c/test/mako/mako.c
bindings/c/test/mako/mako.h
bindings/c/test/mako/utils.c
bindings/c/test/mako/utils.h

This reverts commit 6e97e8e30e4a054d99928e60d05087cae6e8d735.
Unfortunately there are a few issues with mako that need to be resolved. E.g.
```*** Error in `mako': double free or corruption (top): 0x0000000000bbaf00 ***```
Reverting this backport for now. I will work on a fix and make another attempt later.

Revert "added median and 99.9 percentile latency measurement"

---

fdbclient/NativeAPI.actor.cpp
fdbclient/VersionVector.h
fdbserver/CommitProxyServer.actor.cpp
fdbserver/masterserver.actor.cpp

- use version vector in GetRange
- add toString in version vector
- two minor fixes preventing compilation

use version vector in GetRange

---

contrib/TestHarness/Program.cs.cmake

When I run FoundationDb with joshua testing framework, all tests are failed with `NoTraceFileGenerated` error. I asked for a help in https://forums.foundationdb.org/t/simulation-testing-of-foundationdb/2654/6 but nobody could troubleshoot it.
After some debugging I found that TestHarness.exe tried to start fdbserver but it couldn't start (in my case due an incompatible glibc version). In this case fdbserver did not write any trace files, so TestHarness.exe raised `NoTraceFileGenerated`. But such troubleshooting is not possible without debugging.
If fdbserver failed to start, then log the root cause instead of `NoTraceFileGenerated`.
After running correctness tests with changed TestHarness.exe, I receive a log with the real errors
```
python3 -m joshua.joshua -C …
```

Fixed 'NoTraceFileGenerated' error in simulation tests when fdbserver process could not start

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/ClusterController.actor.cpp
fdbserver/LogSystem.h
fdbserver/LogSystemConfig.h
fdbserver/MockLogSystem.cpp
fdbserver/MockLogSystem.h
fdbserver/TagPartitionedLogSystem.actor.cpp
fdbserver/masterserver.actor.cpp
fdbserver/ptxn/test/TestTLogServer.actor.cpp

Master tells cluster controller about TLog groups
In TagPartitionedLogSystem(running on master), build the maps:
* From group id to interfaces of tlog belong to the group
* From tlog to the TLogGroups id it belongs to
The first map is needed in ServerDBInfo and will be broadcasted.
The second map is needed when creating a TLog
Joshua 1 failure out of 100000 runs:  20210722-181643-haofu-36797f886a3c3d26 

Master tells cluster controller about TLog groups

---

bindings/c/test/mako/mako.c
bindings/c/test/mako/mako.h
bindings/c/test/mako/utils.c
bindings/c/test/mako/utils.h

This PR backports mako latency measurements from master to release-6.3 branch. This is so we'd have latency data for mako workloads with 6.3 clusters. 
This is a copy and paste of the current mako files in master branch. The only edit I made was to hard-code `FDB_API_VERSION=630` since this is for `release-6.3` branch.
**Test**
- I built and ran a performance test using mako and confirmed that latency stats are now there.
**How to Review?**
@sfc-gh-anoyes @sfc-gh-kmakino could you please double check that the current mako doesn't contain any incompatible changes to 6.3? …

Backported mako from master to release-6.3

---

documentation/sphinx/source/release-notes/release-notes-630.rst
documentation/sphinx/source/release-notes/release-notes-700.rst
fdbclient/MultiVersionTransaction.actor.cpp
fdbclient/MultiVersionTransaction.h

This fixes two bugs with multi-version databases:
1. Closing a multi-version database cancels the protocol version monitor, invalidating its future. If a version change is triggered after that happens, then an assertion will be triggered that expects the future to be valid.
2. If creating a database on an external client returned an error, the error would be ignored and an invalid database would be used.
This changes the behavior so that closing the database prevents us from doing any work to update the version and errors when creating a database are propagated correctly.
Tested by running a test that failed both of these cases and then succeeded after the change. Passed 10K correctness and 10K binding tester runs. …

Fix problems with using multi-version databases

---

documentation/sphinx/source/release-notes/release-notes-630.rst
fdbclient/MultiVersionTransaction.actor.cpp
fdbclient/MultiVersionTransaction.h

This is a cherry-pick of #5219. Also includes a fix that was part of #5089 and a release note fix in #5261.
This fixes two bugs with multi-version databases:
1. Closing a multi-version database cancels the protocol version monitor, invalidating its future. If a version change is triggered after that happens, then an assertion will be triggered that expects the future to be valid.
2. If creating a database on an external client returned an error, the error would be ignored and an invalid database would be used.
This changes the behavior so that closing the database prevents us from doing any work to update the version and errors when creating a database are propagated correctly.
Tested by running a test that failed both of these cases and then succeeded after the change. Passed 100K …

Fix problems with using multi-version databases (release-6.3)

---

documentation/sphinx/source/release-notes/release-notes-630.rst

There are two patch releases which are not currently documented in the release notes. This updates the version of the latest fixes to account for those.

Fix release note version to account for two undocumented versions

---

fdbrpc/sim2.actor.cpp
fdbserver/SimulatedCluster.actor.cpp
fdbserver/fdbserver.actor.cpp
fdbserver/workloads/MachineAttrition.actor.cpp
flow/FaultInjection.cpp
flow/FaultInjection.h

Enable or disabling fault injection in the simulator,
```
./fdbserver -r simulation -f [TestFile] --fault_injection [on/off]
```
Three major changes in this PR:
- INJECT_FAULT Macro
- TSSMode in Simulated Cluster
- Machine Attrition Workload

Fault Injection Active/Deactivation

---

flow/IThreadPoolTest.actor.cpp
flow/flat_buffers.h

This PR fixes flow build issues on Windows :
- flow/IThreadPoolTest.actor.cpp : needs to include <iterator> (which included by another dependency on Linux)
- flow/flat_buffers.h : pthread.h is not under linux section

Fix flow build issues on Windows

---

fdbclient/ServerKnobs.cpp
fdbserver/ClusterController.actor.cpp

goodRecruitmentTime is initially set to Never() until the first worker joins the cluster controller.
If the workerHealthMonitor waits on goodRecruitmentTime, there is a race that it may wait for indefinitely.
100K joshua run 20210726-054823-zhe-5268-4d3060be5443cfd2: 20210726-054823-zhe-5268-4d3060be5443cfd2          compressed=True data_size=25963564 duration=5702933 ended=101264 fail=3 fail_fast=10 max_runs=100000 pass=99998 priority=100 remaining=0 runtime=0:59:23 sanity=False started=101324 stopped=20210726-064746 submitted=20210726-054823 timeout=5400 username=zhe-5268 (3 failures are out of memory) …

Change how to wait for goodRecruitmentTime and populate default PEER_LATENCY_CHECK_MIN_POPULATION

---

fdbclient/FDBTypes.cpp
fdbclient/FDBTypes.h
fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbclient/StorageServerInterface.h
fdbserver/CMakeLists.txt
fdbserver/ClusterController.actor.cpp
fdbserver/CommitProxyServer.actor.cpp
fdbserver/LogSystem.h
fdbserver/LogSystemConfig.h
fdbserver/MockLogSystem.cpp
fdbserver/MockLogSystem.h
fdbserver/ProxyCommitData.actor.h
fdbserver/Resolver.actor.cpp
fdbserver/ResolverInterface.h
fdbserver/TagPartitionedLogSystem.actor.cpp
fdbserver/masterserver.actor.cpp
fdbserver/ptxn/MessageSerializer.cpp
fdbserver/ptxn/MessageSerializer.h
fdbserver/ptxn/TLogGroupVersionTracker.actor.cpp
fdbserver/ptxn/TLogGroupVersionTracker.h
fdbserver/ptxn/TLogInterface.h
fdbserver/ptxn/TLogServer.actor.cpp
fdbserver/ptxn/test/TestResolver.actor.cpp
fdbserver/ptxn/test/TestTLogServer.actor.cpp

- Change resolver interface to take tlog groups instead of storage teams
- Change TeamVersionTracker to TLogGroupVersionTracker

Make resolver to track version by tlog group

---

fdbrpc/FlowTests.actor.cpp
fdbrpc/FlowTransport.actor.cpp
fdbrpc/fdbrpc.h
fdbrpc/sim2.actor.cpp
flow/Net2.actor.cpp
flow/flow.h
flow/network.h

Backport of #5288
This is a bugfix needed to make correctness clean on release 7.0.
Passed 10k correctness tests

Flow transport uses an ordered delay to avoid out of order reply promise stream messages

---

fdbcli/fdbcli.actor.cpp
fdbclient/GlobalConfig.actor.cpp
fdbclient/GlobalConfig.actor.h

When running `fdbcli --exec 'profile client get'`, an incorrect value would be returned since GlobalConfig had not been initialized yet. This PR adds a `wait` to make sure GlobalConfig is initialized when running `fdbcli --exec`. It also adds some TraceEvents to GlobalConfig to make future debugging easier.
Passed 10k correctness tests on Joshua.

Wait for GlobalConfig initialization when running fdbcli --exec

---

bindings/java/src/integration/com/apple/foundationdb/RepeatableReadMultiThreadClientTest.java
bindings/java/src/tests.cmake

Add RepeatableReadMultiThreadClientTest to verify transactions have repeatable read.

Add RepeatableReadMultiThreadClientTest

---

flow/CMakeLists.txt

To build FDB using Linux/Clang, an additional library,libatomic, is needed.

Add libatomic for building FDB using Clang

---

bindings/c/test/unit/unit_tests.cpp
documentation/sphinx/source/api-version-upgrade-guide.rst
documentation/sphinx/source/release-notes/release-notes-700.rst
fdbclient/NativeAPI.actor.cpp
fdbserver/ClusterController.actor.cpp
fdbserver/StorageCache.actor.cpp
fdbserver/workloads/CommitBugCheck.actor.cpp
fdbserver/workloads/DifferentClustersSameRV.actor.cpp
fdbserver/workloads/RandomSelector.actor.cpp
fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp
fdbserver/workloads/StatusWorkload.actor.cpp

Long ago (API version 4XX), the API was changed so that a transaction would not be reset when it was committed. This change was not fully made however, and so the transaction would be reset in NativeAPI but not ReadYourWrites. The main implication of this seems to be that trying to access the read version after commit would return a new read version rather than the original one, but the transaction could not be used to read any keys or commit outside of the special key-space.
This change makes it so that commit does not reset the transaction in NativeAPI either. It is guarded by API version 700. It also changes many internal usages of NativeAPI transactions to reset after committing if the transaction is reused.
Tested by adding a new unit test to fdb_c_unit_tests. Passed 10K correctness. …

Do not partially reset a transaction when it is committed or fails to commit with an error

---

bindings/c/test/unit/unit_tests.cpp
documentation/sphinx/source/api-version-upgrade-guide.rst
documentation/sphinx/source/release-notes/release-notes-700.rst
fdbclient/NativeAPI.actor.cpp
fdbserver/ClusterController.actor.cpp
fdbserver/StorageCache.actor.cpp
fdbserver/workloads/CommitBugCheck.actor.cpp
fdbserver/workloads/DifferentClustersSameRV.actor.cpp
fdbserver/workloads/RandomSelector.actor.cpp
fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp
fdbserver/workloads/StatusWorkload.actor.cpp

This is a cherry pick of #5271
Long ago (API version 4XX), the API was changed so that a transaction would not be reset when it was committed. This change was not fully made however, and so the transaction would be reset in NativeAPI but not ReadYourWrites. The main implication of this seems to be that trying to access the read version after commit would return a new read version rather than the original one, but the transaction could not be used to read any keys or commit outside of the special key-space.
This change makes it so that commit does not reset the transaction in NativeAPI either. It is guarded by API version 700. It also changes many internal usages of NativeAPI transactions to reset after committing if the transaction is reused.
Passed 100K correctness and new unit test.
The …

Do not partially reset a transaction when it is committed or fails to commit with an error (release-7.0)

---

documentation/sphinx/source/release-notes/release-notes-630.rst
documentation/sphinx/source/release-notes/release-notes-700.rst
fdbclient/MultiVersionTransaction.actor.cpp
fdbclient/MultiVersionTransaction.h

This is a cherry-pick of #5219. Also includes a fix that was part of #5089 and a release note fix in #5261.
This fixes two bugs with multi-version databases:
1. Closing a multi-version database cancels the protocol version monitor, invalidating its future. If a version change is triggered after that happens, then an assertion will be triggered that expects the future to be valid.
2. If creating a database on an external client returned an error, the error would be ignored and an invalid database would be used.
This changes the behavior so that closing the database prevents us from doing any work to update the version and errors when creating a database are propagated correctly.
Tested by running a test that failed both of these cases and then succeeded after the change. Completed 10K …

Fix problems with using multi-version databases (release-7.0)

---

fdbserver/DataDistribution.actor.cpp

Data Distributor is replaced by an infinity loop

Disable DD for demo

---

flow/CMakeLists.txt

This reverts commit f533317b73aa0a12b46b441d451642d4e8989518, reversing
changes made to 82603ff7645c7eabba320beb5d22ed6e36bd7f2a.

Revert "Merge pull request #5286 from xis19/master"

---

fdbserver/worker.actor.cpp

Fix the bug that when the health monitor checking local peers, it doesn't consider proxies.
Also added test coverage for this case.
100K 20210727-012414-zhewu-5279-98bf6413b617b882        compressed=True data_size=25969228 duration=5750593 ended=100819 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:39:01 sanity=False started=100901 stopped=20210727-020315 submitted=20210727-012414 timeout=5400 username=zhewu-5279

Include proxies in the local worker list in health monitoring

---

fdbserver/ApplyMetadataMutation.cpp
fdbserver/LogSystem.h
fdbserver/LogSystemConfig.h
fdbserver/MockLogSystem.cpp
fdbserver/MockLogSystem.h
fdbserver/ProxyCommitData.actor.h
fdbserver/TLogGroup.actor.cpp
fdbserver/TLogGroup.actor.h
fdbserver/TagPartitionedLogSystem.actor.cpp
fdbserver/masterserver.actor.cpp
fdbserver/ptxn/TLogInterface.h

- We were using WorkerInterface ID which isn't useful as just using TLogInterface ID directly. 
- Use new ptxn::TLogInterface instead of older one.
- Add vector<ptxn::TLogInterface> to LogSystemConfig: We have tLog groups to tLog mapping in there, but       tLogGroupCollection needs to know the list of available tLogs first, which is available only via LogSystemConfig. Alternatively, we can also do tLogGroupCollection recruitment as part of
LogSystem, and possibly also add tLogGroupCollection to LogSystem itself, as it
is infact part of LogSystem.
Please check each of the following things and check *all* boxes before accepting a PR. However, getting tLog IDs needs us to wait …

TLogGroup: Use new ptxn::TLogInterface not old TLogInterface

---

cmake/CompileRocksDB.cmake

This has been tested both in simulation and with YCSB. It does not seem to impact write throughput, but it does seem to substantially improve read throughput.
The equivalent Dockerfile PR: https://github.com/FoundationDB/fdb-build-support/pull/4

Update RocksDB version

---

contrib/TestHarness/Program.cs.cmake

##TestHarness ability to disable or enable Buggify/FI 
```
mono bin/TestHarness.exe joshua-run [OldBinary] [useValgrind] [maxTries=3] [buggify=true] [faultInejction=true]
mono bin/TestHarness.exe joshua-run "" false 3 false false
```
Passed Joshua 100K test:
```
20210729-173614-sajjad-d7db758e232d3faf            
compressed=True data_size=25968396 duration=5751049 ended=103646 fail=1 fail_fast=10 max_runs=100000 
pass=100002 priority=100 remaining=0 runtime=0:43:41 sanity=False started=103973 stopped=20210729-181955
submitted=20210729-173614 timeout=5400 username=sajjad
```
The one failure is `ERROR: Out of memory`. …

Test harness Buggify/FaultInjection argument 

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/CommitProxyServer.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/TLogGroup.actor.cpp
fdbserver/ptxn/TLogGroupVersionTracker.actor.cpp

Support adding empty transactions in resolver & proxy to move version forward for each tlog group.

Support adding empty transactions in resolver & proxy to move version forward for each tlog group

---

fdbclient/BackupContainerFileSystem.actor.cpp
fdbrpc/AsyncFileEncrypted.actor.cpp
fdbrpc/AsyncFileEncrypted.h

Fixed issues with reads crossing file end, block memory lifetime, and file size limit.
Also, fixed IDE / clangd warnings and clang-formatted code.

Bug fixes in IAsyncEncryptedFile

---

fdbclient/FDBTypes.h
fdbserver/CommitProxyServer.actor.cpp
fdbserver/LogSystem.h

CommitBatchContext::written_tags captures all tags that have been affected by a transaction batch.  
We were not updating written_tags in applyMetadataToCommittedTransactions() and so we were not capturing all tags affected by a transaction batch. Address this by moving this logic, the logic that populates written_tags, to LogPushData.
Changes:
FDBTypes.h: 
Tag: Add a method to identify whether the tag represents a non-primary tlog type.
LogSystem.h: 
LogPushData: 
- Add a new member, written_tags, which captures all tags affected a transaction batch.
- Update writeMessage() and writeTypedMessage() methods to populate written_tags.
- Modify saveTags() to copy written_tags, after filtering out any pseudo tags.
CommitProxyServer.actor.cpp:
- Remove code that populates written_tags in …

Version vector prototype: Tweak the logic that populates CommitBatchContext::written_tags

---

fdbserver/SimulatedCluster.actor.cpp

For valgrind builds, if rocksdb is chosen for the storage engine then simulation tests often timeout, even when they are not run under valgrind.  At least some of the tests hang indefinitely and stop writing TraceEvents to the log.
Although these tests aren't deterministic once the cluster starts, many choices prior to that are deterministic, so this commit hash and command should be able to reproduce the problem even if not every time.
```
0ce468198db3c4daf755cd1c17e2c02cdda755b9
bin/fdbserver -r simulation -f tests/slow/FastTriggeredWatches.toml -s 356712494 -b on  --crash
```
If this PR …

Disable using rocksdb in valgrind builds.

---

fdbbackup/FileDecoder.actor.cpp
fdbclient/BackupAgent.actor.h
fdbclient/BackupContainer.h
fdbclient/FileBackupAgent.actor.cpp

Refactor `fdbdecoder` to reuse `AccumulatedMutations` and mutation log decoding functions for restores. Because KV chunks can be out-of-order, now the process is to load the whole file into memory and to emit one version's data at a time. The out-of-order chunks are handled by `AccumulatedMutations` to avoid the original complicated logic.
The `fdbdecoder` has been manually tested to work as intended.

Refactor decoder for better handling KV blocks

---

flow/ThreadHelper.actor.h

Cherry pick https://github.com/apple/foundationdb/pull/5290 to release-7.0
Bring back optimization removed in #3750. Tested with the ctest suite both with/without TSAN

Bring back optimization that avoids hop to network thread (release-7.0)

---

bindings/c/CMakeLists.txt
bindings/c/test/unit/trace_partial_file_suffix_test.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/NativeAPI.actor.h
fdbclient/vexillographer/fdb.options
flow/FileTraceLogWriter.cpp
flow/FileTraceLogWriter.h
flow/Trace.cpp
flow/Trace.h

This option configures a suffix for partial trace files that gets removed once the trace file is complete. This is useful for cases where your trace log ingestion infrastructure on the client expects files matching a certain pattern to be complete - you can use the suffix to "hide" incomplete trace files from being ingested prematurely.

Add the trace_partial_file_suffix option

---

fdbclient/GlobalConfig.actor.cpp
fdbclient/GlobalConfig.actor.h

#5291 added a `TraceEvent` on a hot code path (called every time a `Transaction` is created). Steve let me know that it was causing >50% of all `TraceEvent`s in the logs for most simulation tests. The date #5291 also lines up with a big dip in grv performance as reported by our nightly performance testing. This trace could be involved in the performance regression as well.
This PR removes all info-level `TraceEvent`s associated with GlobalConfig. The hot trace was `GlobalConfig_Get`, being called at https://github.com/apple/foundationdb/blob/cf7b42e65289e7f9ade481cb0a45aecd35c0bb90/fdbclient/NativeAPI.actor.cpp#L6314 which is in turn called from the `Transaction` constructor.
Passed 10k correctness tests.
Currently running performance testing. …

Remove hot TraceEvents from GlobalConfig

---

documentation/sphinx/source/release-notes/release-notes-630.rst
documentation/sphinx/source/release-notes/release-notes-700.rst

I made sure the rst renders as intended locally.

Add release note for trace_partial_file_suffix

---

documentation/sphinx/source/release-notes/release-notes-630.rst

Cherry pick release note 6.3.18 to release-7.0

Cherry pick release note 6.3.18 to release-7.0

---

documentation/sphinx/source/release-notes/release-notes-630.rst

Cherry pick release note 6.3.18 to release-6.3

Cherry pick release note 6.3.18 to release-6.3

---

bindings/c/CMakeLists.txt
bindings/c/test/unit/trace_partial_file_suffix_test.cpp
documentation/sphinx/source/release-notes/release-notes-630.rst
documentation/sphinx/source/release-notes/release-notes-700.rst
fdbclient/NativeAPI.actor.cpp
fdbclient/NativeAPI.actor.h
fdbclient/vexillographer/fdb.options
flow/FileTraceLogWriter.cpp
flow/FileTraceLogWriter.h
flow/Trace.cpp
flow/Trace.h

Cherry pick https://github.com/apple/foundationdb/pull/5325 to release-7.0
This option configures a suffix for partial trace files that gets removed once the trace file is complete. This is useful for cases where your trace log ingestion infrastructure on the client expects files matching a certain pattern to be complete - you can use the suffix to "hide" incomplete trace files from being ingested prematurely.

Add the trace_partial_file_suffix option (release-7.0)

---

fdbserver/GrvProxyServer.actor.cpp
flow/Histogram.cpp

Add grvConfirmEpochLiveDist and grvRawDist to GrvProxyServer. 
```
j list --stopped | grep  20210730-225754-yaoxiao-c9abab775d808237
20210730-225754-yaoxiao-c9abab775d808237           compressed=True data_size=25963959 duration=5536583 ended=106011 fail_fast=10 max_runs=100000 pass=100002 priority=100 remaining=0 runtime=0:30:21 sanity=False started=106053 stopped=20210730-232815 submitted=20210730-225754 timeout=5400 username=yaoxiao
```

Add histogram in GrvProxyServer.

---

bindings/c/CMakeLists.txt
bindings/c/test/unit/trace_partial_file_suffix_test.cpp
cmake/ConfigureCompiler.cmake
documentation/sphinx/source/release-notes/release-notes-630.rst
fdbclient/NativeAPI.actor.cpp
fdbclient/NativeAPI.actor.h
fdbclient/vexillographer/fdb.options
flow/FileTraceLogWriter.cpp
flow/FileTraceLogWriter.h
flow/Trace.cpp
flow/Trace.h

Cherry pick https://github.com/apple/foundationdb/pull/5325 to release-6.3
This option configures a suffix for partial trace files that gets removed once the trace file is complete. This is useful for cases where your trace log ingestion infrastructure on the client expects files matching a certain pattern to be complete - you can use the suffix to "hide" incomplete trace files from being ingested prematurely.

Add the trace_partial_file_suffix option (release-6.3)

---

cmake/ConfigureCompiler.cmake

Attempting to link with `-latomic` will make the build fail with clang and the official docker image. I tested this by compiling on our teamserver using the official docker image

Don't use -latomic with clang

---

bindings/python/tests/fdbcli_tests.py

The current test setting can cause the database unavailable afterward.
It used to be good so need to find out what logic is changed here and redesign the test.

Disable advanceversion ctest

---

.gitignore

This PR is adding the `build` folder in the `.gitignore`, allowing IDE to use the standard `$SOURCE_DIR/build`, as discussed in #3098.
I didn't find any reference to a `builds` folder, so I changed it to `build`.

allow build folder as $BUILD_DIR

---

fdbclient/DatabaseConfiguration.cpp
fdbclient/DatabaseConfiguration.h
fdbclient/ManagementAPI.actor.cpp
fdbserver/SimulatedCluster.actor.cpp
fdbserver/TLogGroup.actor.cpp
fdbserver/masterserver.actor.cpp
tests/ptxn/CycleTest.toml

This is done for the first time DB is created. The split points are specified
in the TOML file and persisted into the database configuration.
I tested that `InitialSplitPoint` matches the splits defined in TOML file.
Correctness has a random unit test failure that can't be reproduced.
20210806-044301-jzhou-f317276c80168837             compressed=True data_size=26379470 duration=5230705 ended=104974 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=0:21:30 sanity=False started=105036 stopped=20210806-050431 submitted=20210806-044301 timeout=5400 username=jzhou …

Add split points and pass to database configuration

---

bindings/c/CMakeLists.txt
bindings/c/test/unit/trace_partial_file_suffix_test.cpp
cmake/ConfigureCompiler.cmake
documentation/sphinx/source/release-notes/release-notes-620.rst
fdbclient/NativeAPI.actor.cpp
fdbclient/NativeAPI.actor.h
fdbclient/vexillographer/fdb.options
flow/FileTraceLogWriter.cpp
flow/FileTraceLogWriter.h
flow/Trace.cpp
flow/Trace.h

Cherry pick https://github.com/apple/foundationdb/pull/5330 to release-6.2
This option configures a suffix for partial trace files that gets removed once the trace file is complete. This is useful for cases where your trace log ingestion infrastructure on the client expects files matching a certain pattern to be complete - you can use the suffix to "hide" incomplete trace files from being ingested prematurely.

Add the trace_partial_file_suffix option (release-6.2)

---

CMakeLists.txt

This cherry picks how this works on master back to release-7.0

Fix build with compile_commands.json enabled

---

fdbbackup/backup.actor.cpp

Cherry picks: https://github.com/apple/foundationdb/pull/5336
Just adds error detail to a TraceEvent.

backup: Show error info for RemovedDeadBackupLayerStatus (release-6.3)

---

fdbbackup/backup.actor.cpp

Cherry picks: https://github.com/apple/foundationdb/pull/5336
Just adds error detail to a TraceEvent.

backup: Show error info for RemovedDeadBackupLayerStatus (release-7.0)

---

bindings/python/tests/fdbcli_tests.py

Sometimes the `exclude` command can fail with _not_enough_space_ error,
the original test did not catch it thus retry until timeout.
The fix catches the error and uses _FORCE_ option to proceed.
(It also adds the test coverage for the _FORCE_ option)

Fix the exclude command ctest

---

fdbclient/NativeAPI.actor.cpp
fdbclient/NativeAPI.actor.h
flow/Trace.cpp

Avoid doing thread-unsafe things in the ReadYourWritesTransaction
default constructor since we now will be calling it in a foreign thread.
Here's the warning we're fixing:
```
Write of size 8 at 0x7b6800000398 by thread T1:
#0 N2::Net2::updateNow() /home/jenkins/fdb/extra/long/path/to/work/around/strange/cpack/debug/rpm/behavior/flow/Net2.actor.cpp:192:33 (libfdb_c.so+0xe74568)
#1 N2::Net2::run() /home/jenkins/fdb/extra/long/path/to/work/around/strange/cpack/debug/rpm/behavior/flow/Net2.actor.cpp:1459:3 (libfdb_c.so+0xe74568)
#2 runNetwork() /home/jenkins/fdb/extra/long/path/to/work/around/strange/cpack/debug/rpm/behavior/fdbclient/NativeAPI.actor.cpp:2036:13 (libfdb_c.so+0x575004)
#3 ThreadSafeApi::runNetwork() /home/jenkins/fdb/extra/long/path/to/work/around/strange/cpack/debug/rpm/behav …
```

Fix TSAN warnings

---

fdbserver/MutationTracking.cpp
fdbserver/RestoreApplier.actor.h
fdbserver/RestoreLoader.actor.cpp

MutationTracking events will now contain a Label field which references the first tracked key or range that matched the mutation.

Added Label field for keys and ranges in MutationTracking.

---

bindings/java/src/integration/com/apple/foundationdb/CycleMultiClientIntegrationTest.java

backporting https://github.com/apple/foundationdb/pull/5204
In order to have multiple threads running against same cluster, this has to be done.

Setup cycleTest in the same txn (release-7.0)

---

flow/IThreadPool.h
flow/IThreadPoolTest.actor.cpp
flow/genericactors.actor.h
tests/IThreadPool.txt
tests/WorkerTests.txt

It is the stream version of [ThreadReturnPromise](https://github.com/apple/foundationdb/blob/857d5704dace1ed4e1c43908710da9900132bb03/flow/IThreadPool.h#L83), enabling us to send signals back safely to the main thread from a [TypedAction](https://github.com/apple/foundationdb/blob/857d5704dace1ed4e1c43908710da9900132bb03/flow/IThreadPool.h#L72)(possibly on another thread).
Its first use case is passing notifications back to SS from RocksDB, on [completion of memlayer flushes](https://github.com/facebook/rocksdb/blob/052c24a6680c7de4aabf42c9efe24b345dcb18fd/include/rocksdb/listener.h#L377). …

Introduced ThreadReturnPromiseStream

---

fdbclient/NativeAPI.actor.cpp

For unknown reasons, The previous implementation crashed while
(according to valgrind and ubsan) trying to interpret uninitialized memory as a
shared_ptr. This only happened when CMAKE_BUILD_TYPE=Debug. This change
works for debug mode and also still addresses this TSAN issue the
original change addressed.

Fix a crash in debug mode

---

fdbserver/VersionedBTree.actor.cpp

Some of the per-Level trace event detail fields had a level number that was off by 1.

Redwood Metric Level

---

fdbserver/DataDistribution.actor.cpp

Cherry-pick of andrew's fix https://github.com/apple/foundationdb/pull/5371, fixes an ASAN issue in release-7.0

7.0 cherry-pick: tss heap use after free

---

fdbclient/NativeAPI.actor.cpp
fdbclient/StorageServerInterface.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/MoveKeys.actor.cpp
fdbserver/storageserver.actor.cpp

As a result of larger scale performance and operational testing, I found these improvements:
- duplicating other storage server metadata requests that go through load balance, to ensure equal load on SS/TSS
- Not killing a TSS if an individual data move takes too long
- Adding details to traces for, and fixing a bug in TSS recruitment that can cause the cluster to recruit fewer TSS than desired
- Adding  the count of wrong_shard_server errors to StorageMetrics, to be able to track any divergence in shards between the SS and TSS and the rate of tss reads not completed due to that divergence
Besides the real cluster testing, passed 250k correctness tests. …

Various TSS improvements from snowblower testing (7.0 version)

---

bindings/python/tests/fdbcli_tests.py

It seems to be flaky when cluster is unavailable after the coordinator change but the test is going on.
Make it to wait until cluster is back and enable logging if it fails.
For now, I cannot reproduce the failure locally thus enable logging by default.
If it fails again, it can at least give more info about the failure.

Try to fix flaky exclude fdbcli test

---

fdbclient/NativeAPI.actor.cpp

We observed that multi-threaded client has more memory usage,
and we would like to understand it better.
One suspect is that this shard-to-SS cache is playing a role,
logging the size of it to get better vision.

Log size of locationCache in client

---

fdbclient/PaxosConfigTransaction.actor.cpp

This fixes `subobject-linkage` warning from `gcc`.

Remove anonymous namespace in PaxosConfigTransaction.actor.cpp

---

fdbrpc/sim2.actor.cpp
fdbserver/workloads/KillRegion.actor.cpp

Fixed bug in nightly correctness where killDatacenter with forceKill=true didn't always actually kill the whole datacenter.
In this case, on KillRegionCycle, it skipped killing a tlog in the primary DC that allowed it to get partially through a recovery and take over the cluster controller, but not enough to actually finish the recovery and make the database available.
Passed 100k correctness tests.

Force kill in killDatacenter didn't actually force kill always

---

fdbserver/ConfigDatabaseUnitTests.actor.cpp
fdbserver/LocalConfiguration.actor.cpp
fdbserver/LocalConfiguration.h
fdbserver/worker.actor.cpp

After discussing reference counting vs yielding, I decided to go with reference counting since it would fix this issue if it ever came up elsewhere, and avoids yielding in a response from the network thread, which evan mentioned could cause performance problems.
Passed 10k correctness tests. It's essentially a no-op with the config initialize step disabled.

Fix worker segfault by reference counting LocalConfiguration

---

fdbserver/OldTLogServer_6_2.actor.cpp

This fixes the Valgrind test failures of many restarting tests.
1k Valgrind tests pass

fix uninitialized int

---

fdbserver/ApplyMetadataMutation.cpp
fdbserver/ApplyMetadataMutation.h
fdbserver/CommitProxyServer.actor.cpp
fdbserver/ptxn/test/TestTLogServer.actor.cpp

This was missed in the PR #5399. Also added some comments.
20210818-230909-jzhou-6dbf4ceda72525df             compressed=True data_size=26378427 duration=4760661 ended=101236 fail=1 fail_fast=10 max_runs=100000 pass=100223 priority=100 remaining=0 runtime=0:29:25 sanity=False started=101567 stopped=20210818-233834 submitted=20210818-230909 timeout=5400 username=jzhou
The failed test is a non-deterministic unit test `/fdbserver/ptxn/test/commit_peek`, as unseed values are different. I fixed in the second commit.

Add destination team to ServerCacheInfo

---

documentation/sphinx/source/request-tracing.rst

Relating to #5416, this commit is fixing the documentation about the data layout used in the tracing feature.

Fix documentation about the tracing data layout

---

fdbserver/ClusterController.actor.cpp

Last night's snowflake 6.3 nightly had 7/100k correctness failures and 1/1k valgrind failures in `RandomUnitTests.txt` because the trace event detail names weren't capitalized here.
It appears this was introduced in https://github.com/apple/foundationdb/pull/5249.
`<StdErrOutput Severity="40" Output="Trace event detail name `peer' is invalid in:"/>`
`<"Severity"="10", "Time"="6.985623", "DateTime"="2021-08-20T09:26:34Z", "Type"="WorkerPeerHealthRecovered", "Machine"="3.4.3.3:1", "ID"="0000000000000000", "Worker"="17.17.17.17:1", "peer"="3.3.3.3:1", "LogGroup"="default", "Roles"="TS""/>`
`<StdErrOutput Severity="40" Output="Trace event detail name `worker' is invalid in:"/>`
`<"Severity"="10", "Time"="6.033279", "DateTime"="2021-08-20T05:42:52Z", "Type"="WorkerAllPeerHealthRecovered", …

Fixing Trace Event Names

---

fdbserver/ClusterController.actor.cpp

Previously, the health monitor in Cluster controller runs a loop despite of any errors encountered. When the actor is cancelled, the loop drops the cancellation error and still running, which causes the health monitor to stuck. To fix the issue, we need to return the cancellation error, which is also suggested [here](https://github.com/apple/foundationdb/tree/master/flow#actor-cancellation).
100k joshua test: 20210819-235625-zhewu_5381-c40c02fc8f0678cb

Allow CC health monitor to handle Actor cancellation

---

fdbrpc/fdbrpc.h
fdbserver/DataDistribution.actor.cpp
flow/genericactors.actor.h

When `printSnapshotTeamsInfo` yields, the referenced objects in `machine_info` can change causing the snapshot to become invalid. This resulted in simulation failures on the 7.0 branch. This PR also includes several changes cherry-picked from https://github.com/apple/foundationdb/pull/4289 to improve the const-correctness of `DataDistribution.actor.cpp`.

Capture deep copy of `machine_info` in `printSnapshotTeamsInfo`

---

fdbbackup/backup.actor.cpp

Also updates the usage text for dr_agent cluster files to include the long form options.
Tested by running the commands manually and verifying the correct error message appeared and that the usage text looked correct.
Also passed 10K correctness.

Fix crash when DR binaries are invoked without a source cluster file.

---

fdbrpc/FlowTransport.actor.cpp

`fdbrpc` should not depend on `fdbclient` files. This will hopefully fix the macOS CI failure.
Passed 10k correctness.

Remove fdbclient dependency from fdbrpc file

---

fdbserver/SimulatedCluster.actor.cpp

Some recent change broke the RocksDB engine in simulation. Disable it for now to unblock folks before looking for a fix.

Disable RocksDB storage engine in simulation

---

documentation/sphinx/source/request-tracing.rst

This is a cherry-pick of #5417, relating to #5416.
This commit is fixing the documentation about the data layout used in the tracing feature.

[cherry-pick] Fix documentation about the tracing data layout

---

documentation/sphinx/source/mr-status-json-schemas.rst.inc

The status schema included many fields that weren't present in the documentation. This adds those fields and also fixes one missing comma.

Update the status documentation to include missing fields

---

fdbserver/ConfigBroadcaster.actor.cpp
fdbserver/ConfigBroadcaster.h
fdbserver/ConfigDatabaseUnitTests.actor.cpp

Adds a unit test to test whether the `ConfigBroadcaster` correctly catches the death of a worker.
Passed 10k correctness.

Unit test ConfigBroadcaster detection of worker death

---

fdbserver/ClusterController.actor.cpp

In some long recovery, the recruiting_transaction_servers step takes abnormally long time. 
We want to understand why the recruiting_transaction_servers step takes long time to finish.
A starting point of root cause analysis is to see whether (1) CC repeatedly retry the recruitment; or (2) the recruitment is delay to backend; or (3) some CC error occurs and CC dies.
For case (2) and (3), we already have RecruitFromConfigurationNotAvailable event and RecruitFromConfigurationError event to decide the case. 
For case (1), we add RecruitFromConfigurationRetry event by this PR.
The appearance of this new event should be rare since (1) the event happens when no enough available servers in recruitment and (2) the retry (not in backend) lasts at most 1 second (set by …

Add trace event for role recruitment by CC

---

fdbclient/NativeAPI.actor.cpp
fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/TLogServer.actor.cpp
fdbserver/masterserver.actor.cpp
fdbserver/storageserver.actor.cpp

Changes:
TLogServer.actor.cpp:
- Pull commits 5e37bc37a07ea54136865d1933758d9769ef8a94 and
95e85aaffba7e7ad8dad85774ac7370f23a1e769 from the version indexer branch.
- Do not enable the blocking-peek logic if ENABLE_VERSION_VECTOR flag is set to false.
masterserver.actor.cpp:
- Sequencer should update the version vector once for a given commit version (irrespective of the number of times that it receives and processes the ReportRawCommittedVersionRequest message for that commit version). Issue found by simulation tests.
storageserver.actor.cpp:
- Storage server should take both its latest commit version and the read version into account while processing a read request. This is to address "transaction too old" error that we saw while testing with mako (and also in YCSB tests). …

Version vector prototype: Pull changes related to tlog-peek from the version indexer branch and address some bugs

---

documentation/sphinx/source/mr-status-json-schemas.rst.inc

This is a cherry-pick of #5420.
The status schema included many fields that weren't present in the documentation. This adds those fields and also fixes one missing comma.

Update the status documentation to include missing fields (release-7.0)

---

documentation/sphinx/source/mr-status-json-schemas.rst.inc

This is a cherry-pick of #5420.
The status schema included many fields that weren't present in the documentation. This adds those fields and also fixes one missing comma.

Update the status documentation to include missing fields (release-6.3)

---

ACKNOWLEDGEMENTS
flow/aarch64/memcpy.S

Replacing `memcpy` implementation with `advsimd` version.
Added an entry to `ACKNOWLEDGEMENTS`.

Add ACKNOWLEDGEMENTS. Replace memcpy with advsimd implementation.

---

fdbcli/CMakeLists.txt
fdbcli/SetClassCommand.actor.cpp
fdbcli/Util.actor.cpp
fdbcli/fdbcli.actor.cpp
fdbcli/fdbcli.actor.h

Cherry-pick from #5171 (Part of the pr, it was too large, so we split it and merge one-by-one),
- Print out error message in _setClass_ if get `special_keys_api_failure`
- Refactor transaction related commands like `commit`, `begin`, etc.

Refactor transaction related commands

---

fdbserver/ApplyMetadataMutation.cpp
fdbserver/ApplyMetadataMutation.h

The original ApplyMetadataMutation is nearly 1k lines. Splitting it into small functions improves readability.
The change is verified by running 10000 correctness tests.

Refactor ApplyMetadataMutation for better readability

---

fdbserver/LogSystem.h
fdbserver/MasterProxyServer.actor.cpp
fdbserver/TagPartitionedLogSystem.actor.cpp

(cherry picked from commit 8609b45354a8fa573ab589057ee0e4f97eb54c27)

Cherry-pick (#5299) Add histograms to CommitProxyServer. 

---

flow/TLSConfig.actor.cpp
flow/TLSConfig.actor.h

This also removes one use of the macro that is no longer needed now that actors can access private members.
Passed 10K correctness with 1 seemingly unrelated redwood failure.

Refactor our PRIVATE_EXCEPT_FOR_TLSCONFIG_CPP macro to be compatible with clang-format

---

flow/TLSConfig.actor.cpp
flow/TLSConfig.actor.h

This is a cherry-pick or #5492.
This also removes one use of the macro that is no longer needed now that actors can access private members.
Passed 10K correctness with only unrelated snapshot restarting test failures.

Refactor our PRIVATE_EXCEPT_FOR_TLSCONFIG_CPP macro to be compatible with clang-format (release-7.0)

---

flow/TLSConfig.actor.cpp
flow/TLSConfig.actor.h

This is a cherry-pick of #5492 
This also removes one use of the macro that is no longer needed now that actors can access private members.

Refactor our PRIVATE_EXCEPT_FOR_TLSCONFIG_CPP macro to be compatible with clang-format (release-6.3)

---

ACKNOWLEDGEMENTS
flow/CMakeLists.txt
flow/aarch64/asmdefs.h
flow/aarch64/memcmp.S
flow/aarch64/memcpy.S
flowbench/BenchHash.cpp

Cherry pick https://github.com/apple/foundationdb/pull/4920 to release-7.0
We observed improved performance for get range queries on Arm with these memcpy and memcmp implementations.

Use custom mem{cmp,cpy} impl on Arm (release-7.0)

---

tests/restarting/from_5.0.0/CycleTestRestart-1.txt
tests/restarting/from_5.0.0/StorefrontTestRestart-1.txt
tests/restarting/from_5.1.7/DrUpgradeRestart-1.txt
tests/restarting/from_5.2.0/ClientTransactionProfilingCorrectness-1.txt
tests/restarting/from_6.2.33/SnapCycleRestart-1.txt
tests/restarting/from_6.2.33/SnapTestAttrition-1.txt
tests/restarting/from_6.2.33/SnapTestRestart-1.txt
tests/restarting/from_6.2.33/SnapTestSimpleRestart-1.txt

https://github.com/apple/foundationdb/issues/5507 has raised some issues involving restarting tests and 6.3. This change is aiming to mitigate the errors caused by Redwood's on-disk data being incompatible across releases.

Exclude redwood from part 1 of restarting tests that are from versions < 6.3

---

fdbserver/ClusterController.actor.cpp

checkRegions may cause DC priority change, which shouldn't be done in CC health monitor.
20210827-205304-zhewu_5489-39c30994bd57aa10        compressed=True data_size=25177840 duration=5651374 ended=101579 fail=1 fail_fast=10 max_runs=100000 pass=100105 priority=100 remaining=0 runtime=1:26:17 sanity=False started=101592 stopped=20210827-221921 submitted=20210827-205304 timeout=5400 username=zhewu_5489 (failed one is a tmp file non exist error, and not reproducable).

Remove checkRegions in shouldTriggerRecoveryDueToDegradedServers

---

fdbserver/SimulatedCluster.actor.cpp

This feature will cause recovery by modifying key
"\xff/conf/perpetual_storage_wiggle".

Disable perpetual_storage_wiggle when no fault injection allowed

---

fdbclient/MultiVersionTransaction.actor.cpp

The main thread busyness API currently reports the busyness of the network thread corresponding with the database being used. For external clients, we are also impacted by the primary network thread, so this change causes us to report the larger of the two busyness numbers for the two network threads.
Tested by running a sample client application that reports the main thread busyness. Also passed 10K correctness.
cc @sfc-gh-gkliot 

When using an external client, report the larger of the primary and external network thread busyness

---

tests/restarting/from_5.0.0/CycleTestRestart-1.txt
tests/restarting/from_5.0.0/StorefrontTestRestart-1.txt
tests/restarting/from_5.1.7/DrUpgradeRestart-1.txt
tests/restarting/from_5.2.0/ClientTransactionProfilingCorrectness-1.txt
tests/restarting/from_6.2.33/SnapCycleRestart-1.txt
tests/restarting/from_6.2.33/SnapTestAttrition-1.txt
tests/restarting/from_6.2.33/SnapTestRestart-1.txt
tests/restarting/from_6.2.33/SnapTestSimpleRestart-1.txt
tests/restarting/to_6.3.10/CycleTestRestart-1.txt

This is a cherry-pick of https://github.com/apple/foundationdb/pull/5508 onto `release-7.0` with the additional change to the test file of `tests/restarting/to_6.3.10/CycleTestRestart-1.txt` since a 7.0 downgrade will be to 6.3

Exclude redwood from part 1 of restarting tests that are from versions < 6.3 (release-7.0)

---

fdbserver/KeyValueStoreRocksDB.actor.cpp

Example 
`trace.127.0.0.1.4503.1630440279.a5Q2jo.0.1.xml:<Event Severity="40" ErrorKind="Unset" Time="1630440291.196540" DateTime="2021-08-31T20:04:51Z" Type="RocksDBError" ID="0000000000000000" Error="IO error: No space left on device" Method="Commit" RocksDBSeverity="0" SubCode="4" ThreadID="16869869807533468410" Backtrace="addr2line -e fdbserver.debug -p -C -f -i 0x2becf2c 0x2bec0f0 0x2bec4d1 0xf29787 0xf2b7e2 0x2b68d46 0x2b6a285 0x7fb2598fbea5" Machine="127.0.0.1:4503" LogGroup="default" Roles="CC,CP,DD,GP,MS,RK,RV,SS,TL" />` …

Log SubCode and Severity for RocksDB erros. 

---

flow/Platform.h

When compiling FDB using clang++, self-assign warning appears due to the
code
pos = littleEndian32(pos);
in Atomic.h, which expands to
pos = pos;
as littleEndian32 is defined as
#define littleEndian32(value) value
This warning is not interesting, but annoying, by adding a
no-side-effect casting, the warning is suppressed.
Tested by 100000 correctness runs.

Fix the self-assign warning in Atomic.h

---

fdbserver/TagPartitionedLogSystem.actor.cpp

Cherry pick of https://github.com/apple/foundationdb/pull/5180. Fixes https://github.com/apple/foundationdb/issues/5165.

Fix invalid read in TagPartitionedLogSystem (release-6.3)

---

fdbserver/TagPartitionedLogSystem.actor.cpp

Cherry pick of https://github.com/apple/foundationdb/pull/5180. Fixes https://github.com/apple/foundationdb/issues/5165.

Fix invalid read in TagPartitionedLogSystem (release-6.2)

---

packaging/docker/sidecar/sidecar.py

This fixes a bug where we used the non-existent constant `none` rather than `None`. This caused the sidecar to crash loop when the `FDB_PUBLIC_IP` environment variable was not provided.

Fix fallback logic for getting pod IPs in the sidecar

---

fdbclient/MultiVersionTransaction.actor.cpp

This is a cherry-pick of #5484 
The main thread busyness API currently reports the busyness of the network thread corresponding with the database being used. For external clients, we are also impacted by the primary network thread, so this change causes us to report the larger of the two busyness numbers for the two network threads.
Tested manually. Correctness not yet run due to it being in a broken state.

When using an external client, report the larger of the primary and external network thread busyness (release-7.0)

---

fdbserver/ClusterController.actor.cpp

RecruitFromConfigurationRetry should wait for goodRecruitmentTime to be ready.
Otherwise, findWorkersForConfiguration will just retry every 35ms and fail wastefully.
20210830-180016-zhewu_5486-9b5a3a708b4096d8        compressed=True data_size=25179429 duration=4441952 ended=100452 fail_fast=10 max_runs=100000 pass=100006 priority=100 remaining=0 runtime=0:33:47 sanity=False started=102291 stopped=20210830-183403 submitted=20210830-180016 timeout=5400 username=zhewu_5486

RecruitFromConfigurationRetry should wait for goodRecruitmentTime to be ready

---

fdbserver/ClusterController.actor.cpp

Cherrypick [6.3] Remove checkRegions in shouldTriggerRecoveryDueToDegradedServers

---

flow/ThreadHelper.actor.h

This is a cherry-pick of #5290.
Bring back optimization removed in #3750. 

Bring back optimization that avoids hop to network thread (release-6.3)

---

contrib/TestHarness/Program.cs.cmake

A follow-up on #5529,
~~if the allowed upper bound version is smaller than the server version,
then do not add it to the old binary list~~
----------
Update:
We only add the current binary to the list of old binaries if "until_" is not specified in the folder name
The reason is as below:
<version> in until_<version> should be less or equal to the current binary version
otherwise, using "until_" makes no sense
thus, by definition, if "until_" appears, we do not want to run with the current binary version

Handle the edge case correctly when the upper bound version is less than the binary version

---

flow/aarch64/asmdefs.h

A [recent change](https://github.com/apple/foundationdb/pull/5478) was cherry-picked to release-7.0 at around the same time we applied clang-format to the entire repo. The result was that this file was formatted on master but not on release-7.0, and that now impacts CI.

Fix formatting in cherry-picked change

---

fdbclient/Knobs.cpp
fdbclient/Knobs.h
fdbclient/NativeAPI.actor.cpp

This is a cherry-pick of #5495.
This allows us to detect situations where the network thread is busy at smaller time intervals than our measurement period in a way that would impact performance.
The score is computed based on the value of the maximum non-idle time in the measurement interval, and converts that duration to a 0-1 scale. This is done linearly from the configured range (right now 100ms - 500ms), so 100ms corresponds to 0 and 500ms corresponds to 1. These values were intended to be somewhat conservative, but they can be configured differently via knob and we could also change the defaults.
Tested manually using a client that generated bursts of work.
Please check …

Busyness API incorporates a burstiness score based on the max busyness interval in a measurement period (release-7.0)

---

fdbserver/CommitProxyServer.actor.cpp
fdbserver/LogSystemConfig.h
fdbserver/TLogGroup.actor.h
fdbserver/TagPartitionedLogSystem.actor.cpp

Also fix crash in empty message calculation.
20210903-175936-jzhou-6a824505eeb3669d             compressed=True data_size=20936960 duration=4951106 ended=102201 fail_fast=10 max_runs=100000 pass=100050 priority=100 remaining=0 runtime=0:34:29 sanity=False started=102394 stopped=20210903-183405 submitted=20210903-175936 timeout=5400 username=jzhou

Initialize tlog group collection at commit proxy

---

fdbserver/SimulatedCluster.actor.cpp

Fix reading the disableTss option

---

contrib/TestHarness/Program.cs.cmake

The CI does not have `6.2.33` and also if in any environment,
no binary version in the expected range,
print out a message and return to skip the test.

Return if no available old binary in the given range

---

documentation/sphinx/requirements.txt

Attempt to repair documentation build so PR builds complete as needed

put upper bound on setuptools version

---

fdbserver/CommitProxyServer.actor.cpp
fdbserver/TLogGroup.actor.h
fdbserver/TagPartitionedLogSystem.actor.cpp

Was not using PTXN tlog before.
This PR also fixed serialization bug/inefficiency in TLog push.
Force empty writes to all tlog groups:
When a proxy generate an empty commit, we force such a write to all groups.
This won't generate a lot of traffic, since empty commit is created if there
are no commits in a few seconds, i.e., MAX_COMMIT_BATCH_INTERVAL (2s).
20210908-163436-jzhou-49cce751f7ac079f             compressed=True data_size=20943480 duration=4678849 ended=102739 fail=1 fail_fast=10 max_runs=100000 pass=100031 priority=100 remaining=0 runtime=0:26:46 sanity=False started=103271 stopped=20210908-170122 submitted=20210908-163436 timeout=5400 username=jzhou
There is a failure that is probably not related:
```
-r simulation -f …
```

Fix TLog push in partitioned txns

---

fdbserver/OldTLogServer_6_0.actor.cpp
fdbserver/OldTLogServer_6_2.actor.cpp
fdbserver/TLogServer.actor.cpp

TLogServer popped version calculation was off-by-one for retired tags after master recovery (release-6.3)

---

tests/restarting/to_6.3.13_until_7.0.0/CycleTestRestart-1.txt
tests/restarting/to_6.3.13_until_7.0.0/CycleTestRestart-2.txt

The nightlies were surfacing restart test failures in the 7.0 -> 6.3 downgrade tests. At least some of these failures appear to be because the `TLogVersion` being selected by the first cycle test was `TLogVersion::V6`, which is not supported on 6.3. We just need to bump the max TLogVersion down to fix these issues.
This change does not need to go into master because there are no downgrade tests to 6.3 in versions of FDB greater than 7.0 (only single version downgrades are supported).
Passed 10k `restarting/to_6.3.13_until_7.0.0/*`, 10k `restarting/*`, and 100k `*` correctness tests.
If …

Lower max TLogVersion to V5 during 6.3 downgrade tests

---

fdbserver/KeyValueStoreRocksDB.actor.cpp
fdbserver/SimulatedCluster.actor.cpp

Enable rocksdb storage in simulation with some simulation fixes.
Joshua runs with setting storage_engine_type = rocksdb, so that it runs all the tests with rocksdb.
20210902-154815-neethuhaneeshabingi-c9a73d3cec65a203 compressed=True data_size=25173336 duration=8196797 ended=105309 fail=3 fail_fast=10 max_runs=100000 pass=100001 priority=100 remaining=0 runtime=0:42:19 sanity=False started=105509 stopped=20210902-163034 submitted=20210902-154815 timeout=5400 username=neethuhaneeshabingi
20210902-164230-neethuhaneeshabingi-c9a73d3cec65a203 compressed=True data_size=25173336 duration=7375889 ended=104200 fail=1 fail_fast=10 max_runs=100000 pass=100064 priority=100 remaining=0 runtime=0:39:42 sanity=False started=105454 stopped=20210902-172212 submitted=20210902-164230 timeout=5400 …

Enable rocksdb storage in simulation with some simulation fixes.

---

fdbserver/worker.actor.cpp

So that even the degraded peers don't change, worker will still send the degraded peers to CC. Otherwise, if CC doesn't hear from a worker about a bad peer, it'll consider it is recovered.
This problem doesn't exist in master branch since the master branch doesn't use async var to trigger a reporting to CC.

use setUnconditional in worker's health monitor

---

flow/aarch64/asmdefs.h

Because `clang-format` breaks the assembly syntaxes,
this PR reverts the `clang-format` formatting on `flow/aarch64/asmdefs.h`,
and disables `clang-format` for this file.

Disable clang-format on flow/aarch64/asmdefs.h

---

fdbclient/ManagementAPI.actor.cpp
fdbserver/OldTLogServer_6_0.actor.cpp
fdbserver/OldTLogServer_6_2.actor.cpp
fdbserver/TLogServer.actor.cpp
fdbserver/TagPartitionedLogSystem.actor.cpp
fdbserver/ptxn/TLogGroupVersionTracker.actor.cpp
fdbserver/ptxn/TLogInterface.h
fdbserver/ptxn/TLogServer.actor.cpp

Fix missing group ID in serializing ptxn::TLogCommitRequest
20210909-171712-jzhou-9095b7ee08d1f87d             compressed=True data_size=20943723 duration=4796355 ended=101975 fail_fast=10 max_runs=100000 pass=100197 priority=100 remaining=0 runtime=0:32:23 sanity=False started=101975 stopped=20210909-174935 submitted=20210909-171712 timeout=5400 username=jzhou

Fix missing group ID in serializing ptxn::TLogCommitRequest

---

fdbserver/ConfigDatabaseUnitTests.actor.cpp
fdbserver/ConfigNode.actor.cpp
fdbserver/ConfigNode.h
fdbserver/LocalConfiguration.actor.cpp
fdbserver/LocalConfiguration.h
fdbserver/OnDemandStore.actor.cpp
fdbserver/OnDemandStore.h

The unit test `/fdbserver/ConfigDB/TransactionToLocalConfig/KillWorker` was causing occasional failures when run using the `RandomUnitTests.toml` test. Initial investigation showed Sev40s in the form:
```
<Event Severity="40" ErrorKind="Unset" Time="6.000321" DateTime="2021-08-27T16:51:27Z" Type="RenameFile" Machine="0.0.0.0:0" ID="0000000000000000" FromPath="simfdb/unittests/globalconf-0.fdq.part" ToPath="simfdb/unittests/globalconf-0.fdq" UnixErrorCode="2" UnixError="No such file or directory" ThreadID="5087479302342525366" Backtrace="addr2line -e fdbserver.debug -p -C -f -i 0x579b467 0x57e21e0 0x57e2472 0x57e2cac 0x5796d39 0x55f5b1b 0x55f56c0 0x55f508d 0x55f4f92 0x55f115b 0x36cb1e4 0x36cb0d3 0x36caf45 0x36ca7af 0x36c5273 0x36c480a 0x36c32d3 0x36c2fde 0x36c320f 0x36c2df3 0x36cc0cb …
```

Add fix for KillWorker unit test

---

fdbserver/SimulatedCluster.actor.cpp

Disable rocksdb in simulation to unblock CI.

Disable rocksdb in simulation to unblock CI.

---

fdbserver/ApplyMetadataMutation.cpp
fdbserver/CommitProxyServer.actor.cpp
fdbserver/MasterInterface.h
fdbserver/TLogGroup.actor.cpp
fdbserver/TLogGroup.actor.h
fdbserver/ptxn/TLogInterface.cpp
fdbserver/ptxn/TLogInterface.h
fdbserver/ptxn/TLogPeekCursor.actor.cpp
fdbserver/ptxn/TLogPeekCursor.actor.h
fdbserver/ptxn/TLogServer.actor.cpp

This was was causing undeliverable messages: sender uses `peekMessages` and receiver expects `peek`.
20210914-163012-jzhou-7c9c9ea207181aa0             compressed=True data_size=20959730 duration=4855892 ended=100866 fail_fast=10 max_runs=100000 pass=100129 priority=100 remaining=0 runtime=0:28:06 sanity=False started=102153 stopped=20210914-165818 submitted=20210914-163012 timeout=5400 username=jzhou

Remove redundant RequestStream in ptxn TLogInterface

---

fdbserver/SimulatedCluster.actor.cpp

In a refactor of SimulatedCluster.actor.cpp, tss was changed to be disabled in tests when fault injection isn't enabled.
We still want to run tss in normal (non fault injected) mode when fault injections aren't active.

fixing tss enablement with fault injections

---

cmake/AddFdbTest.cmake
fdbserver/fdbserver.actor.cpp
flow/SimpleOpt.h
tests/CMakeLists.txt
tests/TestRunner/TestRunner.py

Prepare the windows CI by repairing the tests paths.
For now, most tests fails on Windows, and need important work to all be fixed. In order to do not change the build script of the CI, the tests will run and systematically succeed on Windows for now. Once fixed, the tests will really run by changing the source code (without modifying the build script).
This PR duplicate #5444 blocked by the CI.

Prepare windows ci

---

fdbclient/DatabaseContext.h
fdbclient/FDBTypes.h
fdbclient/IClientApi.h
fdbclient/IConfigTransaction.h
fdbclient/ISingleThreadTransaction.h
fdbclient/MultiVersionTransaction.actor.cpp
fdbclient/MultiVersionTransaction.h
fdbclient/NativeAPI.actor.cpp
fdbclient/NativeAPI.actor.h
fdbclient/ReadYourWrites.h
fdbclient/ThreadSafeTransaction.cpp
fdbclient/ThreadSafeTransaction.h
fdbclient/VersionVector.h
fdbserver/BackupWorker.actor.cpp
fdbserver/LogSystem.h
fdbserver/LogSystemConfig.h
fdbserver/MasterInterface.h
fdbserver/Status.actor.cpp
fdbserver/workloads/ApiWorkload.h

Address simulation test failures caused by:
- Assertion failures in MoveKeys.actor.cpp
- Wrong results returned by getRange()
- Assertion failure in DatabaseContext::getLatestCommitVersions(()
Changes:
DatabaseContext.h, NativeAPI.actor.[h,cpp]:
- Introduce a new flag, TransactionInfo::readVersionObtainedFromGrvProxy.
- Set this flag to true by default, and clear it when the read version of a
transaction is explicitly set (by using setVersion()).
- Modify getLatestCommitVersions() to not populate "latestCommitVersions" if
this flag is not set. (This will cause storage server to read at the specified
read version.)
- Modify getRange() actor to always use the specified version as the read
version (except when the specified version is latestVersion).
- Modify waitForCommittedVersion(), …

Version vector prototype: Address simulation test failures

---

fdbclient/MonitorLeader.actor.cpp
fdbclient/MonitorLeader.h
fdbserver/Coordination.actor.cpp
fdbserver/LeaderElection.actor.cpp
fdbserver/LeaderElection.h
fdbserver/worker.actor.cpp

1. Rename monitorLeaderRemotely* functions to monitorLeaderWithDelayedCandidacy*. "Remote" is not clearly describing what the functions are doing;
2. Rename monitorLeaderForProxies() to monitorLeaderAndGetClientInfo() to better describe the function;
3. Remove monitorLeaderRemotelyInternal() and monitorLeaderRemotely() in MonitorLeader.actor.cpp, to eliminate code duplication. They already exist in worker.actor.cpp;
4. Move the declaration of getLeader() from LeaderElection.actor.cpp to MonitorLeader.h;
5. Update a few comments.
20210914-004908-renxuan-8ff93566406bdf00           compressed=True data_size=25526454 duration=5089580 ended=102088 fail_fast=10 max_runs=100000 pass=100196 priority=100 remaining=0 runtime=0:58:52 sanity=False started=102218 stopped=20210914-014800 …

Minor leader election code improvements.

---

cmake/CompileRocksDB.cmake
cmake/FindRocksDB.cmake
fdbserver/KeyValueStoreRocksDB.actor.cpp

The deadline option for readRange op in rocksdb is supported only from v6.22.1.tar.gz rocksdb version.
We use this deadline option in our fdb code (currently disabled). So,eEnforcing 6.22.1 rocksdb version and enabling readRange deadline option.
Test scenarios tested:
FRESH INSTALL: Removed build_output and /opt/rocksdb directories and checked if 6.22.1 is installed
Backporting: After the fresh install, Changed the version  and url_hash to 6.20.3 and checked if it is overwriting 6.22.1 version and installing 6.20.3
Forward porting: After 6.20.3 is installed, changed the version and url_hash to 6.22.1 and checked if it is overwriting 6.20.3 version and installing 6.22.1 …

Enforcing 6.22.1 rocksdb version and enabling readRange deadline option.

---

fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp

```
bin/fdbserver -r simulation -f tests/fast/SpecialKeySpaceCorrectness.toml -s 33857219 -b off  --crash --trace_format json
```
at commit `e68b131e4a23d7a780cc3767fc6bd1cd31a21966` failed because of a bug in the special keyspace workload:
1. We attempt to lock the database.
2. The transaction returns the error `commit_unknown_result`.
3. We retry
4. The transaction fails with `database_locked`
5. Goto 3 until we time out
The fix is to simply check the error code and then succeed.
I tested this by introducing the fix and reruning the test. As this only changes the workload, there's no need to rerun a full set of joshua tests. …

Fix error handling when locking database

---

documentation/sphinx/source/release-notes/release-notes-630.rst
documentation/sphinx/source/release-notes/release-notes-700.rst
fdbclient/MultiVersionTransaction.actor.cpp
fdbclient/MultiVersionTransaction.h
flow/ThreadHelper.actor.h

This could happen if, for example, the client has never been able to connect to the cluster or if the version of the cluster change to one not supported by the client.
Resolves #5595.
Passed correctness, bindingtester, and some TSAN tests.

Transactions would not honor the transaction timeout option if the MVC did not have an active database

---

documentation/sphinx/source/release-notes/release-notes-630.rst
fdbclient/MultiVersionTransaction.actor.cpp
fdbclient/MultiVersionTransaction.h
flow/ThreadHelper.actor.h

This could happen if, for example, the client has never been able to connect to the cluster or if the version of the cluster change to one not supported by the client.
This is a cherry-pick of #5598.

Transactions would not honor the transaction timeout option if the MVC did not have an active database (release 6.3)

---

fdbclient/FDBTypes.cpp
fdbclient/FDBTypes.h
fdbclient/ServerKnobs.cpp
fdbserver/ApplyMetadataMutation.cpp
fdbserver/ClusterController.actor.cpp
fdbserver/CommitProxyServer.actor.cpp
fdbserver/TLogGroup.actor.cpp
fdbserver/TLogGroup.actor.h
fdbserver/masterserver.actor.cpp
fdbserver/ptxn/TLogInterface.h
fdbserver/ptxn/TLogPeekCursor.actor.cpp
fdbserver/ptxn/TLogServer.actor.cpp

SS can choose TLog groups randomly, instead of deterministically, due to the unordered list of group IDs.
TLog is not updating end version in PeekReply for empty message.
20210918-165714-jzhou-923899f1f7901006             compressed=True data_size=26539941 duration=5143330 ended=101295 fail_fast=10 max_runs=100000 pass=100121 priority=100 remaining=0 runtime=0:22:07 sanity=False started=102254 stopped=20210918-171921 submitted=20210918-165714 timeout=5400 username=jzhou

Fix 2 SS peek bugs

---

fdbclient/FDBOptions.h
fdbclient/MultiVersionTransaction.actor.cpp
fdbclient/vexillographer/cpp.cs

Description
Previously, the environment setting via shell cannot be extracted correctly, due to the code is't ablle to
determine input parameter type.
Now the logic to determien parameter and give it different processing is added.
Resolves #4127 
Testing
1. Pass an invalid env var:
FDB_NETWORK_OPTION_TRACE_ROLL_SIZE=xyz - error
FDB_NETWORK_OPTION_TRACE_ROLL_SIZE=123xyz) - error
2. Pass an out-of-ranged env var:
FDB_NETWORK_OPTION_TRACE_ROLL_SIZE=9999999999999999999999999999 - error
FDB_NETWORK_OPTION_TRACE_ROLL_SIZE=-9999999999999999999999999999 - error
3. Pass a valid env var
FDB_NETWORK_OPTION_TRACE_ROLL_SIZE=1000 - ok
4. Pass a float env var(not support)
FDB_NETWORK_OPTION_TRACE_ROLL_SIZE=3.1415926535 - error …

Enable support for integers in environment variable network options

---

fdbclient/DatabaseConfiguration.cpp

I messed up the parenthesis here for the storage migration cli config isValid check. Thanks to @neethuhaneesha for finding.
Passed 10k joshua tests.

fixing db config parenthesis

---

fdbserver/ClusterController.actor.cpp

Missed a namespace (`std`, specifically) qualifier in #5601.

Add missing namespace qualifier to vector.

---

documentation/sphinx/source/cap-theorem.rst
documentation/sphinx/source/ha-write-path.rst
documentation/sphinx/source/performance.rst
documentation/sphinx/source/read-write-path.rst

The images in the website are fine, but broken on github. Fix these links on github.
See results at https://github.com/jzhou77/foundationdb/blob/master/documentation/sphinx/source/read-write-path.rst and https://github.com/jzhou77/foundationdb/blob/master/documentation/sphinx/source/ha-write-path.rst, which correctly shows images.
Verified the `docpreview` target displays images for these pages.

Fix image links in read-write-path documentation

---

documentation/sphinx/source/release-notes/release-notes-630.rst
documentation/sphinx/source/release-notes/release-notes-700.rst
fdbclient/MultiVersionTransaction.actor.cpp
fdbclient/MultiVersionTransaction.h
flow/ThreadHelper.actor.h

This could happen if, for example, the client has never been able to connect to the cluster or if the version of the cluster change to one not supported by the client.
This is a cherry-pick of #5598.

Transactions would not honor the transaction timeout option if the MVC did not have an active database (release 7.0)

---

documentation/tutorial/tutorial.actor.cpp
fdbclient/CMakeLists.txt
fdbclient/ConfigTransactionInterface.cpp
fdbclient/CoordinationInterface.h
fdbclient/MonitorLeader.actor.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/ProcessInterface.h
fdbclient/SpecialKeySpace.actor.cpp
fdbclient/StatusClient.actor.cpp
fdbclient/WellKnownEndpoints.h
fdbrpc/FlowTransport.actor.cpp
fdbrpc/FlowTransport.h
fdbrpc/fdbrpc.h
fdbserver/ConfigFollowerInterface.cpp
fdbserver/Coordination.actor.cpp
fdbserver/CoordinationInterface.h
fdbserver/SimulatedCluster.actor.cpp
fdbserver/fdbserver.actor.cpp
fdbserver/networktest.actor.cpp
fdbserver/workloads/ProtocolVersion.actor.cpp

The identifiers of well-known endpoints must be maintained unique and stable. Also transport must know the maximum possible identifier value in advance. The goal of the refactoring is to maintain the list of all well-known endpoint IDs in a single place.
Changes done:
- List all well-known endpoints of FDB in a single enum
- Identify well-known endpoints by plain IDs

Refactoring well-known endpoint registration

---

bindings/CMakeLists.txt
bindings/c/CMakeLists.txt

Fixes the `OPEN_FOR_IDE` build. Resolves #5419.

Fix OPEN_FOR_IDE build

---

fdbserver/ConfigDatabaseUnitTests.actor.cpp
fdbserver/ConfigFollowerInterface.h
fdbserver/ConfigNode.actor.cpp

Add rollback and rollforward functionality to `ConfigNode`s, which run on each coordinator. This allows the `ConfigBroadcaster` to update an out of date `ConfigNode` (rollforward) or to tell it to rollback any changes it may have mistakenly made.
Ran `ConfigDB` unit tests a bunch and didn't see any failures. Also passed 10k correctness.

Add first stage of rollback and rollforward to ConfigNode

---

fdbclient/NativeAPI.actor.cpp

The computation of tag throttling backoff was taking a minimum with a knob for how long a throttle lasts. When this knob was buggified to 0 in simulation, the backoff would then be 0, and this could cause some transactions to get stuck in a retry loop that failed to advance time. Eventually the test would timeout or potentially run out of memory.
This knob is intended here to put a bound on how large the throttle duration can be. By rearranging the computation, we can enforce this bound while still keeping a minimum exponential backoff.
This fix should have no impact on most non-simulation runs unless the maximum backoff for a transaction has been changed from its default of 1 second or the knob here has been changed from its default of 5 seconds.
The general …

Fix computation of backoff for tag throttling

---

fdbserver/ClusterController.actor.cpp

checkRecoveryStalled should perform failover only when remote is enabled (priority >= 0). Otherwise, forcing failover will cause constant primary DC flip. Issue found in Snowflake nightly runs.
Since the issue doesn't cause test to fail directly (only generate non-zero exit code), I've manually verified the fix. With the new change, release-6.3 with commit 482b3cd5a69a186716cfa3c73d577540fae5886c and seed 718072587 no longer generate any Sev40 errors, and exit successfully.
100K joshua: 20210923-212452-zhewu_5659-9e6707ad01d7e682        compressed=True data_size=20708483 duration=4098214 ended=100041 fail_fast=10 max_runs=100000 pass=100041 priority=100 remaining=0 runtime=1:22:35 sanity=False started=100052 stopped=20210923-224727 submitted=20210923-212452 timeout=5400 …

Fix failover logic in checkRecoveryStalled

---

fdbclient/ServerKnobs.cpp
fdbserver/BackupWorker.actor.cpp

The `BACKUP_LOCK_BYTES` knob could be buggified to a value that was too low, resulting in backup getting stuck. This also adds an assert to try to make it more obvious if this problem is encountered.
Passed 100K correctness and 10K extra correctness of the `ParallelRestoreNewBackupWriteDuringReadAtomicRestore.toml` test.

Fix buggification for backup_lock_bytes knob

---

fdbrpc/Stats.actor.cpp
fdbrpc/Stats.h
fdbserver/ClusterController.actor.cpp
fdbserver/Ratekeeper.actor.cpp
fdbserver/masterserver.actor.cpp
fdbserver/storageserver.actor.cpp

Various trace events get logged by particular instances and are rolled when the trace file rolls. For example, the MasterRecoveryState is logged by the master and tracks the most recent state of master recovery.
When these instances are terminated, the rolled trace events continue to exist and are repeated in each new trace file for as long as the owning process continues running. With the above example, then, we may have multiple former master processes continuing to log MasterRecoveryState. Another example is with something like TLogMetrics which continues rolling on former transaction log processes, creating the potential for incorrect metrics aggregations unless care is taken.
It would be better if trace events associated with a particular role instance were to stop rolling when the …

Stop rolling trace events that are associated with a process role when the role terminates

---

flow/DeterministicRandom.cpp
flow/DeterministicRandom.h
flow/IRandom.h
flow/Trace.cpp
flow/Trace.h

…aded client debugging, and should also be helpful for multithreaded storage engines, SSL handshake threadpools, and so on
Backports https://github.com/apple/foundationdb/pull/5108 to 6.3. Also added the definition of DeterministicRandom::randomUInt64 to make it work.

Add a ThreadID field to eachTraceEvent.  This is needed for multithre…(release 6.3)

---

fdbserver/storageserver.actor.cpp

fix the warn about initialization order chaos in storageserver.actor.cpp

fix the warn about initialization order chaos in storageserver.actor.cpp

---

fdbserver/DataDistribution.actor.cpp
fdbserver/DataDistributionQueue.actor.cpp
fdbserver/DataDistributionTracker.actor.cpp

Various trace events get logged by particular instances and are rolled when the trace file rolls. For example, the MasterRecoveryState is logged by the master and tracks the most recent state of master recovery.
When these instances are terminated, the rolled trace events continue to exist and are repeated in each new trace file for as long as the owning process continues running. With the above example, then, we may have multiple former master processes continuing to log MasterRecoveryState. Another example is with something like TLogMetrics which continues rolling on former transaction log processes, creating the potential for incorrect metrics aggregations unless care is taken.
It would be better if trace events associated with a particular role instance were to stop rolling when the …

fix roll trace event issue for data distribution(master)

---

fdbclient/ServerKnobs.cpp

Avoid unexpectedly flooding the TraceEvent. We can turn it on optionally at first rollout, and then decide if we want to turn it on by default.

disable ENABLE_DETAILED_TLOG_POP_TRACE by default

---

fdbclient/FDBOptions.h
fdbclient/MultiVersionTransaction.actor.cpp
fdbclient/vexillographer/cpp.cs

Previously, the environment setting via shell cannot be extracted correctly, due to the code is't able to determine input parameter type.
Now the logic to determine parameter and give it different processing is added.
backport #5616
Testing
1. Pass an invalid env var:
FDB_NETWORK_OPTION_TRACE_ROLL_SIZE=xyz - error
FDB_NETWORK_OPTION_TRACE_ROLL_SIZE=123xyz) - error
2. Pass an out-of-ranged env var:
FDB_NETWORK_OPTION_TRACE_ROLL_SIZE=9999999999999999999999999999 -error
FDB_NETWORK_OPTION_TRACE_ROLL_SIZE=-9999999999999999999999999999 -error
3. Pass a valid env var
FDB_NETWORK_OPTION_TRACE_ROLL_SIZE=1000 -ok
4. Pass a float env var(not support)
FDB_NETWORK_OPTION_TRACE_ROLL_SIZE=3.1415926535 - error
5. Pass string as env var for places where string type var is required …

Enable support for integers in environment variable network options(release 7.0)

---

fdbserver/ClusterController.actor.cpp

Cherry pick #5659
20210924-215944-zhewu_5662-b20c533a4fba0245        compressed=True data_size=24521280 duration=5176863 ended=100001 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:45:25 sanity=False started=100056 stopped=20210924-224509 submitted=20210924-215944 timeout=5400 username=zhewu_5662

Cherry pick fix recovery stalled to release-7.0

---

flow/Trace.cpp

We recently had a correctness failure (see #5650) where a test got stuck in a loop that did not advance time. It was logging trace events in this loop, which eventually caused the process to run out of memory. However, because we weren't advancing time we did not actually flush the trace log, and this made it unclear what was happening.
To diagnose the problem initially, I increased the memory of the process and observed no change in the output logs. From this I surmised we were stuck in a loop and used gdb to figure out where.
With this change, it should be possible from the trace logs to tell that we were stuck in a loop that involves trace events, and the trace events should make it clear where.
Passed 100K correctness with one unrelated failure. …

Fail simulation if the trace log buffer gets large

---

bindings/c/test/mako/mako.c
bindings/c/test/mako/mako.h

Added option to disable snapshot RYW in `mako` at the database level.

Support disabling RYW in mako

---

fdbclient/NativeAPI.actor.cpp

This is a backport of #5650.
The computation of tag throttling backoff was taking a minimum with a knob for how long a throttle lasts. When this knob was buggified to 0 in simulation, the backoff would then be 0, and this could cause some transactions to get stuck in a retry loop that failed to advance time. Eventually the test would timeout or potentially run out of memory.
This knob is intended here to put a bound on how large the throttle duration can be. By rearranging the computation, we can enforce this bound while still keeping a minimum exponential backoff.
This fix should have no impact on most non-simulation runs unless the maximum backoff for a transaction has been changed from its default of 1 second or the knob here has been changed from its default of 5 seconds.
Passed 10K …

Fix computation of backoff for tag throttling (release-7.0)

---

fdbserver/BackupWorker.actor.cpp
fdbserver/Knobs.cpp

This is a backport of #5661.
The `BACKUP_LOCK_BYTES` knob could be buggified to a value that was too low, resulting in backup getting stuck. This also adds an assert to try to make it more obvious if this problem is encountered.

Fix buggification for backup_lock_bytes knob (release-7.0)

---

fdbmonitor/fdbmonitor.cpp

Currently, if fdbmonitor fails to call `execv` on a child process, it will print a generic error ("unable to launch"). It does not include any information about why `execv` failed. This updates the error string to include details from `errno`. For example:
```
Sep 28 16:26:47 host fdbmonitor[31215]: LogGroup="default" Process="fdbserver.4500": Unable to launch /home/user/fdbserver for fdbserver.4500 (execv error 13: Permission denied)
```
Tested by running `fdbmonitor` manually with a binary that had inadequate permissions set. …

Include the errno details if execv fails in fdbmonitor

---

flow/Trace.cpp

This is a backport of #5668.
This makes it an error in simulation for the trace log buffer to get too large.

Fail simulation if the trace log buffer gets large (release-7.0)

---

fdbserver/storageserver.actor.cpp

fix the problem about initialization list disorder in storageserver.actor.cpp file

fix initialization list disorder

---

fdbclient/DatabaseConfiguration.cpp

Cherry-pick for #5647.
Without this change after an upgrade, the grv_proxy and commit_proxy counts would revert to their default amounts
Ran 100K correctness.
In addition, tested using the following sequence on a local cluster.
Started a 6.3 cluster
Configured the number of proxies to be 10
Upgraded the cluster to 7.0 unchanged - status showed default number of proxies
Upgraded the cluster to 7.0 with this fix - status showed Desired Commit Proxies - 8 Desired GRV Proxies - 2

fix: use DEFAULT_COMMIT_GRV_PROXIES_RATIO to pick the number of grv_proxies and commit_proxies after an upgrade

---

fdbclient/MultiVersionTransaction.actor.cpp

The `timeoutTsav` variable was accessed unsafely when setting a timeout or returning a future on a transaction that is not connected to a database.
This passes the new tests in #5692:
- Run normally
- Run with TSAN
- Run with UBSAN (except for a seemingly unrelated openssl problem)
- Run with ASAN (except for a seemingly unrelated problem with storing supported client versions)
For completeness I also ran the following, though I don't expect they really exercise these changes:
- Passed 10K correctness.
- Passed 10K binding tester runs. …

Fix MVC timeout thread safety issue

---

bindings/c/CMakeLists.txt
bindings/c/test/unit/disconnected_timeout_tests.cpp
cmake/AddFdbTest.cmake
tests/TestRunner/fake_cluster.py

This adds a number of tests of the client timeout behavior when the client cannot connect to a cluster. These are intended to be run using `ctest`, but can also be invoked manually using `bin/disconnected_timeout_unit_tests`.
I've run these through a variety of tests, including with TSAN, ASAN, and UBSAN. Since this is added to ctest, it will also be exercised by CI.

Add some tests for timeout behavior with disconnected clusters

---

documentation/sphinx/source/release-notes/release-notes-630.rst

Adding missing release notes from 6.3.19 to 6.3.21

Adding missing release notes from 6.3.19 to 6.3.21

---

fdbserver/Knobs.cpp

Cherry pick disable ENABLE_DETAILED_TLOG_POP_TRACE by default to release 7.0

---

fdbserver/Knobs.cpp

Cherry pick disable ENABLE_DETAILED_TLOG_POP_TRACE by default to release 6.3

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/ApplyMetadataMutation.cpp
fdbserver/ApplyMetadataMutation.h
fdbserver/CommitProxyServer.actor.cpp
fdbserver/LogSystem.h
fdbserver/MasterInterface.h
fdbserver/TLogServer.actor.cpp
fdbserver/TagPartitionedLogSystem.actor.cpp
fdbserver/masterserver.actor.cpp

We wish to remove the overhead of sending empty transactions from proxies to tLogs [1]. To do this, the vector: "previous commit version per tLog" (TPCV) must be maintained. 
This was first implemented by maintaining the TPCV on the sequencer. The proxy would call the sequencer to obtain the TPCV for tLogs after the resolve step. This solution generated an extra call in the transaction path. The extra call is expensive and degrades performance.
This PR removes that extra hop, by "piggybacking" how the TPCV is obtained over an existing call (`GetCommitVersionRequest`) from the proxy to the sequencer.  This call is made before the resolve step. 
Prior to the call, all the transactions in the batch are scanned to find the set of tags affected (if any metadata mutations exist, send the batch …

remove network hop by getting previous commit versions in GetCommitVersionRequest

---

fdbrpc/Stats.actor.cpp
fdbrpc/Stats.h
fdbserver/ClusterController.actor.cpp
fdbserver/Ratekeeper.actor.cpp
fdbserver/masterserver.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/workloads/StreamingRangeRead.actor.cpp

Various trace events get logged by particular instances and are rolled when the trace file rolls. For example, the MasterRecoveryState is logged by the master and tracks the most recent state of master recovery.
When these instances are terminated, the rolled trace events continue to exist and are repeated in each new trace file for as long as the owning process continues running. With the above example, then, we may have multiple former master processes continuing to log MasterRecoveryState. Another example is with something like TLogMetrics which continues rolling on former transaction log processes, creating the potential for incorrect metrics aggregations unless care is taken.
It would be better if trace events associated with a particular role instance were to stop rolling when the …

Fix roll trace event issue(release-7.0)

---

documentation/sphinx/source/command-line-interface.rst
documentation/sphinx/source/mr-status-json-schemas.rst.inc
documentation/sphinx/source/perpetual-storage-wiggle.rst
fdbcli/ConfigureCommand.actor.cpp
fdbcli/fdbcli.actor.cpp
fdbclient/DatabaseConfiguration.cpp
fdbclient/DatabaseConfiguration.h
fdbclient/FDBTypes.h
fdbclient/ManagementAPI.actor.cpp
fdbclient/Schemas.cpp
fdbclient/SystemData.cpp
fdbclient/SystemData.h
fdbserver/DataDistribution.actor.cpp
fdbserver/SimulatedCluster.actor.cpp
fdbserver/workloads/ConfigureDatabase.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp

Locality filter support to perpetual storage wiggler feature. 
By configuring perpetual_storage_wiggle_locality, the processes which match the given locality will only be wiggled.
perpetual_storage_wiggle_locality=<<LOCALITY_KEY>:<LOCALITY_VALUE>|0>: Set the process filter for wiggling. The processes that match the given locality key and locality value are only wiggled. The value 0 will disable the locality filter and matches all the processes for wiggling.

Locality filter support to perpetual storage wiggler feature.

---

fdbclient/FDBTypes.h
fdbserver/VersionedBTree.actor.cpp
fdbserver/workloads/MutationLogReaderCorrectness.actor.cpp

After clearing nearly all data from Redwood, it can be confusing to see the reported disk space in use be non-trivial.  This can occur because while the space represented by the pages in the free list and the versioned free list are accounted for as usable space, the space used to store those lists of pages was still being tracked as used and not reusable.  Since using pages from the free lists shrinks the free list, it is reasonable to also report the list footprint space as "free".
Also added a `destructiveSanityCheck` option to the `/set` unit test which is useful for running the sanity check on a real data file.
Passes 100k correctness. …

Redwood now reports space used to store metadata about free space as free space

---

bindings/c/CMakeLists.txt
bindings/c/test/unit/disconnected_timeout_tests.cpp
bindings/c/test/unit/fdb_api.cpp
bindings/c/test/unit/fdb_api.hpp
bindings/c/test/unit/third_party/CMakeLists.txt
cmake/AddFdbTest.cmake
fdbclient/MultiVersionTransaction.actor.cpp
tests/TestRunner/fake_cluster.py

This is a backport of #5690 and #5692. It also includes some other changes from master to support running the unit tests and the fix in #5697.
The timeoutTsav variable was accessed unsafely when setting a timeout or returning a future on a transaction that is not connected to a database.
Most of the changes here are for testing, only `fdbclient/MultiVersionTransaction.actor.cpp` has changes that should affect the behavior of the client.
This has passed the new unit tests introduced in this change.
This has also passed the following, which likely don't exercise these changes:
- 10K correctness
- 10K bindingtester …

Fix MVC timeout thread safety issue (release-6.3)

---

bindings/c/CMakeLists.txt
bindings/c/test/unit/disconnected_timeout_tests.cpp
cmake/AddFdbTest.cmake
fdbclient/MultiVersionTransaction.actor.cpp
tests/TestRunner/fake_cluster.py

This is a backport of #5690, #5692, and #5697. It also includes some other changes from master to support running the unit tests.
The timeoutTsav variable was accessed unsafely when setting a timeout or returning a future on a transaction that is not connected to a database.
Most of the changes here are for testing, only fdbclient/MultiVersionTransaction.actor.cpp has changes that should affect the behavior of the client.
This passes the new unit tests, 10K correctness, and 10K binding tester.

Fix MVC timeout thread safety issue (release-7.0)

---

fdbmonitor/fdbmonitor.cpp

This is a backport of #5682 
Currently, if fdbmonitor fails to call execv on a child process, it will print a generic error ("unable to launch"). It does not include any information about why execv failed. This updates the error string to include details from errno. For example:
```
Sep 28 16:26:47 host fdbmonitor[31215]: LogGroup="default" Process="fdbserver.4500": Unable to launch /home/user/fdbserver for fdbserver.4500 (execv error 13: Permission denied)
```
Tested by running fdbmonitor manually with a binary that had inadequate permissions set. …

Include the errno details if execv fails in fdbmonitor (release-7.0)

---

fdbserver/MasterProxyServer.actor.cpp

A [recent PR](https://github.com/apple/foundationdb/pull/5689/files) accidentally removed the initialization of a couple variables. This adds back this initialization.
These variables look to still be correctly initialized on release-7.0 and master:
release-7.0: https://github.com/apple/foundationdb/blob/72bedfeb530c0ed92e5e777bafc6c698f7a308ee/fdbserver/GrvProxyServer.actor.cpp#L98
master: https://github.com/apple/foundationdb/blob/f27c6ef57cb65d63031e07ae69e0e7005b8079a6/fdbserver/GrvProxyServer.actor.cpp#L99
This was detected with valgrind correctness. The failing test worked correctly with this change. Also passed 1000 valgrind correctness. …

Restore missing variable initialization in proxy (release-6.3)

---

documentation/sphinx/source/release-notes/release-notes-630.rst

Add two release notes for the 6.3.21 patch release.

Updating release notes for 6.3.21

---

bindings/python/tests/fdbcli_tests.py
fdbcli/fdbcli.actor.cpp

As now we have multi-version fdbcli
we add the option `--api-version` to specify the API version to use.

Add option --api-version for fdbcli

---

fdbserver/DataDistribution.actor.cpp
fdbserver/DataDistributionQueue.actor.cpp
fdbserver/DataDistributionTracker.actor.cpp

Various trace events get logged by particular instances and are rolled when the trace file rolls. For example, the MasterRecoveryState is logged by the master and tracks the most recent state of master recovery.
When these instances are terminated, the rolled trace events continue to exist and are repeated in each new trace file for as long as the owning process continues running. With the above example, then, we may have multiple former master processes continuing to log MasterRecoveryState. Another example is with something like TLogMetrics which continues rolling on former transaction log processes, creating the potential for incorrect metrics aggregations unless care is taken.
It would be better if trace events associated with a particular role instance were to stop rolling when the …

Fix roll trace event issue for data distribution(release-7.0)

---

fdbserver/BackupWorker.actor.cpp
fdbserver/Knobs.cpp

This is a backport of #5661.
The BACKUP_LOCK_BYTES knob could be buggified to a value that was too low, resulting in backup getting stuck. This also adds an assert to try to make it more obvious if this problem is encountered.

Fix buggification for backup_lock_bytes knob (release-6.3)

---

fdbserver/ptxn/test/TestTLogServer.actor.cpp
tests/ptxn/TLogServer.toml

Fix /fdbserver/ptxn/test/read_persisted_disk_on_tlog
Previously, ach tlog interface would receive information of all tlog
groups, and there are redudent resources created.
This commit fixes it: it should be that a tlog interface only
receives information of tlog groups affiliated to it.

Fix /fdbserver/ptxn/test/read_persisted_disk_on_tlog

---

fdbserver/ptxn/test/Driver.h
fdbserver/ptxn/test/TestTLogServer.actor.cpp
tests/ptxn/TLogServer.toml

Previously all tlogs are sent to all tlog servers, in PR 5869 it was
fixed by assigning non-overlapping subsets of groups to each tlog server.
Now this test must respect that so that it still passes in the case
of multiple tlog servers.

Fix /fdbserver/ptxn/test/lock_tlog

---

fdbserver/ptxn/test/TestTLogServer.actor.cpp
fdbserver/ptxn/test/Utils.cpp

The test should only be invoked from tests/ptxn/TLogServer.toml, where the
number of SS is the same as storage teams. Otherwise, an assertion failure will
be triggered at startStorageServers().
We can't run the unit test from either random unit test `tests/fast/RandomUnitTests.toml`
or specific unit test `tests/rare/SpecificUnitTests.toml`, since we can't set specific test parameters in.
Correctness: failed tests are other unit tests, `/fdbserver/ptxn/test/commit_peek` and `/fdbserver/ptxn/test/lock_tlog`
20211102-041336-jzhou-b37ad2e0ac3dde6c             compressed=True data_size=21601005 duration=4931735 ended=100001 fail=8 fail_fast=10 max_runs=100000 pass=99993 priority=100 remaining=0 runtime=0:46:48 sanity=False started=100199 stopped=20211102-050024 submitted=20211102-041336 …

Disable test /fdbserver/ptxn/test/run_storage_server

---

fdbserver/ptxn/test/TestTLogServer.actor.cpp
fdbserver/ptxn/test/Utils.cpp

Reverts apple/foundationdb#5895
The fix makes that test no longer runnable.

Revert "Disable test /fdbserver/ptxn/test/run_storage_server"

---

fdbrpc/FlowTransport.actor.cpp

Changed FlowTransport to use 64 bit XXHash instead of CRC32, also cleaned up packet scanner a bit.
Correctness and Valgrind correctness are in progress.

Change FlowTransport to use 64 bit XXHash instead of CRC32

---

fdbserver/IPager.h
fdbserver/VersionedBTree.actor.cpp

Changed hash function from CRC32 to XXHash.
Passes 10k correctness (it's a simple change).

Use XXHash in Redwood

---

fdbrpc/FlowTransport.actor.cpp

Cherry-pick of #5906
Changed FlowTransport to use XXHash instead of CRC32.
Passes 10k correctness.

Changed FlowTransport to use XXHash instead of CRC32 (release-7.0)

---

fdbserver/ApplyMetadataMutation.cpp
fdbserver/ptxn/test/Driver.h
fdbserver/ptxn/test/TestTLogServer.actor.cpp
fdbserver/ptxn/test/Utils.cpp

Fix the default so that `numStorageServers == numStorageTeamIDs` when running as specific/random unit test.

Fix run_storage_server test

---

fdbclient/MonitorLeader.actor.cpp
fdbrpc/FlowTransport.actor.cpp
flow/ProtocolVersion.h
flow/network.cpp
flow/network.h

This is a substep in supporting hostnames in cluster files. So that in fdbcli, `coordinator` command will print out whether the coordinators' network addresses are resolved from hostnames, e.g., `127.0.0.1:4501(fromHostname)`.
20211103-181211-renxuan-a8b9b501483ff61c           compressed=True data_size=27440027 duration=5716161 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=0:51:46 sanity=False started=100181 stopped=20211103-190357 submitted=20211103-181211 timeout=5400 username=renxuan
The failed test is an unrelated KillRegionCycle test.
If …

Add Hostname struct, and fromHostname in NetworkAddress struct.

---

documentation/sphinx/source/transaction-tagging.rst

Now that tag throttling considers writes as well, the tag throttling documentation was out of date.

Update tag throttling documentation

---

fdbrpc/fdbrpc.h
fdbserver/DataDistribution.actor.cpp

Backports https://github.com/apple/foundationdb/pull/5887.

Improve tracing in ddSnapCreateCore (release-6.3)

---

fdbclient/KeyBackedTypes.h
fdbserver/BlobManager.actor.cpp
fdbserver/VersionedBTree.actor.cpp

Added `KeyBackedObjectMap` and `KeyBackObjectProperty`, which work like `KeyBackedMap` and `KeyBackedProperty` but use `ObjectWriter/Reader` for Value serialization so that the type can evolve over time.
Also cleaned up some existing lambdas using relatively (since original writing) new `x=y` syntax to avoid capturing `this` by reference in a more elegant way.
The new classes aren't used yet.

Added KeyBackedObjectMap and KeyBackedObjectProperty classes for storing serializable objects in FDB

---

fdbrpc/fdbrpc.h
fdbserver/DataDistribution.actor.cpp

Backports https://github.com/apple/foundationdb/pull/5887

Improve tracing in ddSnapCreateCore (release-7.0)

---

fdbserver/ptxn/TLogInterface.cpp
fdbserver/ptxn/TLogInterface.h
fdbserver/ptxn/test/Driver.actor.cpp
fdbserver/ptxn/test/Driver.h
fdbserver/ptxn/test/FakeTLog.actor.h
fdbserver/ptxn/test/Utils.h

Earlier the plan was to use TestDriverContext for *all* roles and
ACTORs. This is obviously brining more complexity than benefits. In this
patch, TestEnvironment is introduced as a global singleton. By accessing
TestEnvironment, one could construct fixtures and access the test
environment easier.
The example will be given in following commits. 

Add a TestEnvironment for testing

---

fdbserver/TLogServer.actor.cpp

Unblock waiting peek requests, if any, before stopping a tlog instance. (This allows the waiting storage server to make progress by requesting/receiving mutations from the new "committing" tlog instance.)
NOTE: We were doing this "unblocking" in "updatePersistentData()" which is not very efficient. This PR removes that code, and does the "unblocking" before an instance gets stopped.
Testing:
- Ran simulation tests. Job 20211109-153401-sre-0deb84d998bf107c completed without any failures. Job 20211109-003616-sre-0deb84d998bf107c shows failures in the following tests: ConstrainedRandomSelector.toml and MutationLogReaderCorrectness.toml. These tests don't cause any tlog failures/restarts so these failures might not be related to this issue.
- Mako testing: Ran an insert workload (provided by …

Version vector prototype: unblock waiting peeks

---

flow/ProtocolVersion.h

After discussion Markus and I agreed we should bump the protocol version on master to 7.1 with release 7.0 getting finalized.

bump protocol version on master to 7.1

---

fdbrpc/FlowTests.actor.cpp
fdbserver/OldTLogServer_6_0.actor.cpp
fdbserver/OldTLogServer_6_2.actor.cpp
fdbserver/Status.actor.cpp
fdbserver/TLogServer.actor.cpp
fdbserver/VersionedBTree.actor.cpp
tests/PerfUnitTests.toml
tests/rare/AllSimUnitTests.toml
tests/rare/RedwoodDeltaTree.toml
tests/rare/StatusBuilderPerf.toml
tests/rare/TLogVersionMessagesOverheadFactor.toml

This applied the following policy to our unit tests:
1. `/`: (current default) means that this test is meant to run in simulation and will finish very quickly. These tests will be executed often (I will add them to CI)
1. `L`: (for long-running) means the test shouldn’t be included with the rest but instead the author created a separate toml-file (for example in rare).
1. `#`: (for “number”): The purpose of this unit test is to measure the performance of something and therefore it doesn’t make sense to run it in simulation and we won’t ever run it.
Additionally this adds a test `AllSimUnitTests.toml` to `rare` to make sure we execute unit tests often enough
Please check each …

Make sure unit tests are run often enough

---

fdbserver/KeyValueStoreRocksDB.actor.cpp

The ColumnFamilyOptions passed directly through `DB::Open()` wasn't being read by the DB at all. Only the ColumnFamilyOptions passed as part of the `ColumnFamilyDescriptor` was being read. Moving the code to the correct helper ensures that it is being set everywhere.
h/t to @neethuhaneesha for finding this bug

Move table factory options to CFOptions

---

fdbserver/DeltaTree.h
fdbserver/VersionedBTree.actor.cpp

Refactored mutation application in leaf nodes to handle existing mutation boundary keys more efficiently and do in-place value string updates when an existing value is being replaced with a new value of the same length.
Passed 200k correctness only choosing Redwood storage.  

Redwood inline same-size value updates

---

fdbclient/NativeAPI.actor.cpp
fdbserver/ApplyMetadataMutation.cpp
fdbserver/CommitProxyServer.actor.cpp
fdbserver/storageserver.actor.cpp

Clear client VV cache after recovery and fix assertion of resolver returned mutation count.
correctness passed:
20211109-195155-jzhou-abe7493d362d20ec             compressed=True data_size=21968230 duration=5553598 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:31:16 sanity=False started=100355 stopped=20211109-212311 submitted=20211109-195155 timeout=5400 username=jzhou

Fix two bugs

---

fdbserver/BlobManager.actor.cpp

If we accept arena arguments by value, then the lifetime of any memory
allocated by that arena ends when the function returns. Given that we
seem to be appending to VectorRef's passed by pointer this is unlikely
to be what we want.
Found using valgrind, and tested the fix by running under valgrind. We get the same unit test with the same seed after this change so I'm pretty confident that this fixes the memory error.
Closes #5904 

Fix a heap use after free

---

bindings/c/test/unit/unit_tests.cpp
documentation/sphinx/source/request-tracing.rst
fdbclient/DatabaseContext.h
fdbclient/NativeAPI.actor.cpp
fdbclient/vexillographer/fdb.options
fdbserver/GrvProxyServer.actor.cpp
fdbserver/storageserver.actor.cpp
flow/Knobs.cpp
flow/Tracing.actor.cpp
flow/Tracing.h

Fixes some issues with spans not being recorded correctly. Also fixes some of the logic around distributed trace sampling. Now, traces are sampled in bunches. For example, if you want to sample 10 percent of distributed traces, all samples will be taken in the first six seconds of every minute, instead of evenly spreading the sampling out throughout the minute.
I gathered some data on the distribution of recorded spans and the breakdown of each span type. I ran
```
./bin/mako --cluster fdb.cluster --mode run --rows 1000000 --procs 8 --threads 256 --keylen 32 --vallen 16 --transaction "i8" --seconds 120 --trace
```
on a single FDB server binary with the `network_lossy` tracer type and `TRACING_SAMPLE_RATE` set to 0.25 (meaning there should be a 15 second continious window each minute where …

Improve distributed trace sample collection

---

fdbclient/StorageServerInterface.h

We need this to make things consistent when bring `getKeyValuesAndFlatMap` to 7.0 while not bring "change feed" endpoints to 7.0
Ref: https://github.com/apple/foundationdb/pull/5954/files#diff-4211eb7af4805410c408ffb6657278e8c01c34bb46ccc4cfd264ad0b6c7aaca6

Change SSI endpoints order to be consistent with 7.0

---

fdbclient/ServerKnobs.cpp
fdbserver/CommitProxyServer.actor.cpp
fdbserver/LogSystem.h
fdbserver/Resolver.actor.cpp

This is needed so that private mutation tags are propagated from Resolvers to
commit proxies. Otherwise, the master's VV won't be correct and can cause data
corruptions.
I ran correctness with `init( PROXY_USE_RESOLVER_PRIVATE_MUTATIONS,                  true );`:
20211111-182905-jzhou-fa403806e62d4e98             compressed=True data_size=21968423 duration=5445268 ended=100001 fail_fast=10 max_runs=100000 pass=100001 priority=100 remaining=0 runtime=0:49:40 sanity=False started=100482 stopped=20211111-191845 submitted=20211111-182905 timeout=5400 username=jzhou …

Fix written_tags not propagated to commit proxies

---

fdbrpc/SimExternalConnection.actor.cpp
fdbrpc/SimExternalConnection.h

This is a substep in supporting hostnames in cluster files. So that in simulation, we can add <hostname, ip addresses> mappings to mock DNS.
20211109-010322-renxuan-33a909a7b07173e1           compressed=True data_size=27446727 duration=5607621 ended=100001 fail_fast=10 max_runs=100000 pass=100001 priority=100 remaining=0 runtime=0:57:14 sanity=False started=100499 stopped=20211109-020036 submitted=20211109-010322 timeout=5400 username=renxuan

Add DNS mock in SimExternalConnection.

---

fdbserver/DataDistribution.actor.cpp

DataDistribution actor helps in building teams as server count changes
(add/removal), however, it is possible that total_healthy_server count
is insufficient to allow team formation. If happens, even healthy server
count recover, the buildTeam operation will not be triggered.
Patch proposal is to trigger `checkBuildTeam` operation if server
transitions from unhealthy -> healthy state. Incase system already
has created enough teams (desiredTeamCount/maxTeamCount), the operation
incurs a very minimal cost. …

Trigger buildTeam operation if server transition from unhealthy -> healthy

---

fdbserver/KeyValueStoreRocksDB.actor.cpp

This lowers the severity of timeout trace events during the RocksDB reads to be consistent with the pre-emptive timeout trace events. It also catches a call site that wasn't converted to `logRocksDBError` when that API was introduced.

Clean up RocksDB error logging

---

fdbserver/storageserver.actor.cpp
fdbserver/workloads/IndexPrefetchDemo.actor.cpp

I recently find out that the `GetKeyValuesAndFlatMap` endpoint will retry forever for a non-retriable error (e.g. the "mapper" in user's request is invalid). We need this fix in 7.0 to make the new feature useful. 

GetKeyValuesAndFlatMap should return error if not retriable

---

fdbrpc/FlowTransport.actor.cpp

Optimizations in FlowTransport's use of XXHash to enable inlining, avoid a `malloc()` when using the stream API, and to avoid the stream API when a message being sent is contiguous within a single packet buffer block.  
This is purely a CPU overhead optimization and could be cherry-picked to release-7.0.

Optimized FlowTransport's use of XXHash

---

fdbserver/IDiskQueue.h
fdbserver/WorkerInterface.actor.h
fdbserver/ptxn/TLogInterface.h
fdbserver/ptxn/TLogServer.actor.cpp
fdbserver/ptxn/test/TestTLogServer.actor.cpp

When I try to do tlog recovery, found that we never persist data
into tlog, does not pop from tlog either.
This change intends to fix that, but it is a big change.
Tested with joshua `20211105-012455-haofu-59e4fd6fe54c2287`

Populate persistent data in IKeyValueStore in TLog

---

bindings/c/test/unit/fdb_api.hpp
bindings/c/test/unit/unit_tests.cpp
bindings/java/src/integration/com/apple/foundationdb/RangeAndFlatMapQueryIntegrationTest.java
bindings/java/src/main/com/apple/foundationdb/FDBTransaction.java
bindings/java/src/main/com/apple/foundationdb/ReadTransaction.java
fdbclient/ReadYourWrites.actor.cpp
fdbserver/workloads/IndexPrefetchDemo.actor.cpp

We can only support snapshot because the current implementation doesn't update the conflict ranges perfectly (It will add the scanned range to read conflicts, but won’t add the keys in the secondary requests to read conflicts). This PR tries to add this restriction both systematically and verbally, so that users wont have incorrect result unexpectedly.

Restricted getRangeAndFlatMap to snapshot

---

bindings/c/test/mako/mako.c

This PR fixes `mako` to clean up its temporary file under `/dev/shm` properly

Remove mako temp shared memory file

---

fdbrpc/SimExternalConnection.actor.cpp
fdbrpc/SimExternalConnection.h
fdbrpc/sim2.actor.cpp
flow/Net2.actor.cpp
flow/network.h

This is a revise PR of #5934. In simulation, we don't have direct access to SimExternalConnection.
20211115-230109-renxuan-916bc186f0ad6df6

Move DNS mock from SimExternalConnection to Sim2.

---

fdbserver/BlobManager.actor.cpp

When we have an empty key range map, the default range is `allKeys`. In the case of a BM failure before any ranges were assigned, the new BM will try to assign the range `['', \xff\xff)`, so we clamp this down to the normal key space `['', \xff)`.

Clamp end of system keys down to normal keys.

---

fdbserver/ptxn/test/TestTLogServer.actor.cpp

https://github.com/apple/foundationdb/blob/c3b0f5b3f38587c190b0db9569/fdbserver/ptxn/TLogServer.actor.cpp#L1931
It has a default value 30, thus updateStorage actor would wait 30s
and test is finished before the next iteration can commit the mutations.
Manually set the knob to a smaller value to fix it.

Fix flaky test read_persisted_disk_on_tlog

---

fdbserver/Coordination.actor.cpp

This could result in some processes not getting forwarded to the next generator of coordinators.
Passed 50k correctness

fix: coordinators would process forwarding requests before making them durable

---

fdbserver/ClusterController.actor.cpp
fdbserver/WorkerInterface.actor.h
fdbserver/worker.actor.cpp

This issue first appeared in nightly correctness runs on master commit `020b02ea4c2af1e28d6087d36c84316d817fb5f8`.
Test: `tests/slow/ConfigureTest.toml`
Seed: `29463510`
Buggify: `off`
This test timed out due to Master Recovery getting stuck while attempting to recruit TLogs. The root of the issue was that a DBInfo broadcast to the worker was arriving very late, while at the same time the worker's CC interface also reverted to that of an older generation. Because of that, the stale generation's DBInfo was accepted and updated. The worker's CC interface eventually got updated back to the correct one, but it did not trigger the cluster controller to rebroadcast the DBInfo because it was receiving a worker registration request from a machine it had already seen before. This change makes it …

Change dbinfo broadcast to be explicitly requested by the worker registration message

---

bindings/c/test/unit/unit_tests.cpp

Tests for "Restricted getRangeAndFlatMap to snapshot #5978"

---

fdbserver/ClusterController.actor.cpp
fdbserver/WorkerInterface.actor.h
fdbserver/worker.actor.cpp

This is a cherry-pick of https://github.com/apple/foundationdb/pull/5909. This is necessary to fix a rare correctness issue where Master Recovery could get stuck.

Change dbinfo broadcast to be explicitly requested by the worker registration message (release-7.0)

---

fdbserver/storageserver.actor.cpp

This is a cherry-pick of https://github.com/apple/foundationdb/pull/5899 that fixes a rare segmentation fault.

Fix rare segfault that can occur when SS terminates while an actor that uses the StorageServer is still on the stack (release-7.0)

---

cmake/ConfigureCompiler.cmake

explicitly disable to compile warning-free with clang
```
In file included from /root/src/foundationdb/fdbrpc/FlowTransport.actor.cpp:44:
/root/src/foundationdb/flow/xxhash.h:1743:8: error: use of logical '||' with constant operand [-Werror,-Wconstant-logical-operand]
if (0 || 0) {
^  ~
/root/src/foundationdb/flow/xxhash.h:1743:8: note: use '|' for a bitwise operation
if (0 || 0) {
^~
|
1 error generated.
```

Not warn on constant-logical-operand when compile with clang

---

flow/Net2.actor.cpp
flow/network.h

@sfc-gh-anoyes found a data race surfaced by TSAN, where a thread (doing some transaction creation work) tries to resize `globals` at the same time the main thread is reading it. This fix removes the on demand resizing of `globals` and instead initializes it once when `Net2` is constructed.
Passed 10k correctness.
TSAN output:
```
WARNING: ThreadSanitizer: data race (pid=415)
Write of size 8 at 0x7b6800000758 by thread T2:
#0 std::__1::vector<void*, std::__1::allocator<void*> >::_ConstructTransaction::~_ConstructTransaction() /usr/local/bin/../include/c++/v1/vector:905:19 (libfdb_c.so+0x10ce795)
#1 std::__1::vector<void*, std::__1::allocator<void*> >::__construct_at_end(unsigned long) /usr/local/bin/../include/c++/v1/vector:1050:1 (libfdb_c.so+0x10ce795)
#2 std::__1::vector<void*, …
```

Fix possible Net2 data race

---

packaging/multiversion/clients/postinst

This isn't necessary, and causes spurious error messages on centos.
Tested with pkg_tester

Don't adduser in client postinstall

---

fdbclient/json_spirit/json_spirit_reader_template.h
fdbrpc/Net2FileSystem.cpp
flow/AsioReactor.h
flow/Net2.actor.cpp

This eliminates many useless warnings when compiling.
`#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.`

Replace <boost/bind.hpp> with <boost/bind/bind.hpp>.

---

fdbclient/json_spirit/json_spirit_reader_template.h
fdbrpc/Net2FileSystem.cpp
flow/AsioReactor.h
flow/Net2.actor.cpp

Backporting #6023.
This eliminates many useless warnings when compiling.
`#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.`

Replace <boost/bind.hpp> with <boost/bind/bind.hpp> (release-7.0).

---

fdbclient/json_spirit/json_spirit_reader_template.h
fdbrpc/Net2FileSystem.cpp
flow/AsioReactor.h
flow/Net2.actor.cpp

Backporting #6023.
This eliminates many useless warnings when compiling.
`#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.`

Replace <boost/bind.hpp> with <boost/bind/bind.hpp> (release-6.3).

---

bindings/bindingtester/spec/bindingApiTester.md

`string` can be ambiguous as `Tuple` layer supports both `byte string`
and unicode `string`.
Further links to relevant part of [Go](https://github.com/apple/foundationdb/blob/22e34bd6b93bd556539219414aff5235069fa37d/bindings/go/src/_stacktester/stacktester.go#L97) and [Java](https://github.com/apple/foundationdb/blob/22e34bd6b93bd556539219414aff5235069fa37d/bindings/java/src/test/com/apple/foundationdb/test/StackUtils.java#L42-L44) code.

docs: Clarify that `"ERROR"` is a byte string

---

packaging/multiversion/clients/postinst

Cherry pick https://github.com/apple/foundationdb/pull/6020 to release-7.0
This isn't necessary, and causes spurious error messages on centos.
Tested with pkg_tester

Don't adduser in client postinstall (release-7.0)

---

packaging/docker/run_ycsb.sh

This updates the YCSB launcher so that load will succeed even if the thing monitoring its progress fails.  It also adds support for building YCSB from checked out source (the build defaults to the old behavior).
The launcher script changes break compatibility with existing fdb-kubernetes-tests (since they require fdbcli to be injected into the YCSB container at runtime; currently it is not).  A companion PR for that repo should be merged before this one (will send link out-of-band).

New ycsb launcher

---

fdbserver/VersionedBTree.actor.cpp

The window size was assuming seconds and multiplying by versions/sec, which was from an unfinished attempt to change to this model.

Bug fix:  incorrect remap cleanup window size in KeyValueStoreRedwood

---

fdbserver/VersionedBTree.actor.cpp

Cherry-pick of #6034 
The window size was assuming seconds and multiplying by versions/sec, which was from an unfinished attempt to change to this model.

Bug fix: incorrect remap cleanup window size in KeyValueStoreRedwood (release-7.0)

---

fdbserver/IPager.h
fdbserver/VersionedBTree.actor.cpp

- Fixed bugs in `performance/set` unit test which didn't work with the recent `commit(v)` API change.
- Added clearRemapQueue() to Pager to more cleanly and reliably expire all old data and process the remap queue, fixing a bug where with certain configuration parameters and a lot of data the DestructiveSanityCheck would fail because it would not run cleanup long enough.  
- Added more logging detail and .toTraceEvent() to Pager and BTree to get some useful info into a trace event.
- Added more parameters to performance/set unit test. …

Test-only bug fixes in Redwood along with debug logging detail improvements.

---

fdbclient/MultiVersionTransaction.actor.cpp

Previously we could not load external clients that did not have the fdb_transaction_get_range_and_flat_map symbol. Tested by loading an external client without the fdb_transaction_get_range_and_flat_map symbol.

Don't require fdb_transaction_get_range_and_flat_map in older clients

---

fdbclient/MultiVersionTransaction.actor.cpp

Cherry pick https://github.com/apple/foundationdb/pull/6040 to release-7.0
Previously we could not load external clients that did not have the fdb_transaction_get_range_and_flat_map symbol. Tested by loading an external client without the fdb_transaction_get_range_and_flat_map symbol.

Don't require fdb_transaction_get_range_and_flat_map in older clients (release-7.0)

---

fdbclient/ServerKnobs.cpp

It could cause the log routers to fail to make progress in scenarios where sequence 0 of a parallel peek request is sent twice because of a network disconnect, and the first message makes it back to the tlog, but the resent version is at a very large version. In this scenario the log router thinks the tlog has all of the data, so it will not send the tlog any more mutations until the tlog send a pop request, however the tlog will never pop because it does not have all of the data.

Do not buggify the peek cursor expire time to be too small

---

fdbclient/DatabaseConfiguration.cpp
fdbclient/DatabaseConfiguration.h
flow/Arena.h

Patch improves on handling scenarios where either commit or grv proxies
value is update to -1 OR `proxies_count` is being reset.
The code splits the proxies between two proxies by ensuring for invalid
input configuration, the min (read as 1) proxies gets provisioned, otherwise,
the split is done based on input values
Patch handles the scenario where mutation supplied values to update grv_proxies
and/or commit_proxies is -1, however, the total proxy count > 1,
uses DEFAULT_COMMIT_GRV_PROXIES_RATIO to split proxies between
grv_proxies & commit_proxies.
If this PR is …

Override commit/grv proxies_count if mutation supplied new value is -1 (cherry-pick)

---

fdbclient/DatabaseConfiguration.cpp
fdbclient/DatabaseConfiguration.h
flow/Arena.h

Patch handles the scenario where mutation supplied values to update grv_proxies and/or commit_proxies is -1, however, the total proxy count > 1, hence, uses DEFAULT_COMMIT_GRV_PROXIES_RATIO to split proxies between grv_proxies & commit_proxies. 

Use DEFAULT_COMMIT_GRV_PROXIES_RATIO to override proxies_count if mutation supplied value is -1 

---

fdbrpc/FlowTransport.actor.cpp
flow/network.cpp
flow/network.h

So that it can be serialized.
20211122-064359-renxuan-14b1eabe92c21204           compressed=True data_size=28077409 duration=5867662 ended=100001 fail=1 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:52:15 sanity=False started=100393 stopped=20211122-073614 submitted=20211122-064359 timeout=5400 username=renxuan
The failed test is an unrelated io timeout.

Change member variable fromHostname to type bool.

---

fdbclient/DatabaseContext.h
fdbclient/MultiVersionTransaction.actor.cpp
fdbclient/MultiVersionTransaction.h
fdbclient/NativeAPI.actor.cpp
fdbclient/NativeAPI.actor.h
flow/Platform.actor.cpp
flow/Platform.h
flow/Trace.cpp

1. Add a trace event when a database is created and move the cluster file / connection string from ClientStart to the new trace event
2. Add a detail for the path to the image being loaded
3. Add a detail for whether a client library is primary or not
4. Set a thread name for each external client thread that includes the release version (e.g. `fdb-7.1.0-0`).
5. Set a thread name for the trace logging thread (`fdb-trace-log`).
Tested manually to confirm each of the trace event changes produces the correct result and that the threads are named as desired.
If this PR …

Client logging improvements

---

fdbserver/IPager.h
fdbserver/VersionedBTree.actor.cpp

Removed explicit cache `tryEvict(x)` as it is unused and it is functionally replaced by `prioritizeEviction(x)`.

Remove unused / unwanted code in Redwood.

---

fdbclient/MultiVersionTransaction.actor.cpp

Recently there was an issue where we added a new symbol to the c api and
we did not include the right header version guard to see if it was
required. Let's make this not a default so that we force callers to
think about what the right header versions to require it are.

Don't provide default for requireFunction in loadClientFunction

---

fdbclient/NativeAPI.actor.cpp

PR #6033 introduced a change that logged some details about the connection record when connecting to a database. In practice, it seems as if this connection record is generally present, though it is not actually a contract of the function that it be non-null. This change fixes the use of it to check for null.
Passed 10K correctness and a manual test of this trace event.

Fix: Check whether connRecord is null before logging it

---

fdbclient/DatabaseContext.h
fdbclient/MultiVersionTransaction.actor.cpp
fdbclient/MultiVersionTransaction.h
fdbclient/NativeAPI.actor.cpp
fdbclient/NativeAPI.actor.h
fdbrpc/FlowTests.actor.cpp
fdbrpc/sim2.actor.cpp
flow/Net2.actor.cpp
flow/Platform.actor.cpp
flow/Platform.h
flow/Trace.cpp
flow/network.h

This backports #6033 and #6068. It also includes some of the changes that were part of #5142.
- Add a trace event when a database is created and move the cluster file / connection string from ClientStart to the new trace event
- Add a detail for the path to the image being loaded
- Add a detail for whether a client library is primary or not
- Set a thread name for each external client thread that includes the release version (e.g. fdb-7.1.0-0).
- Set a thread name for the trace logging thread (fdb-trace-log).
Tested manually to confirm each of the trace event changes produces the correct result and that the threads are named as desired.
Please check …

Client logging improvements (release-7.0)

---

fdbserver/masterserver.actor.cpp

During master recovery, it was possible for the master to write the cstate but get blocked waiting for the minimum recovery duration. If this happened, it could send an invalid master registration that updated the recovery count but reported no proxies. This would cause the current proxies to terminate and start the recovery over.
This PR changes the logic to disallow updating the master registration between the point when the cstate is updated and the recovery enters the accepting commits phase.
This bug was detected by the ConfigureTest. …

Fix a race condition with updating the coordinated state and updating the master registration

---

fdbbackup/backup.actor.cpp
fdbclient/ManagementAPI.actor.cpp
fdbmonitor/fdbmonitor.cpp
fdbserver/BlobWorker.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/Resolver.actor.cpp
fdbserver/art_impl.h
fdbserver/workloads/ConsistencyCheck.actor.cpp
fdbserver/workloads/SnapTest.actor.cpp
flow/Net2.actor.cpp

These warnings started showing up once we upgraded to `clang` version 13.

Fix `-Wunused-but-set-variable` warnings

---

fdbclient/ServerKnobs.cpp
fdbserver/ApplyMetadataMutation.cpp
fdbserver/ApplyMetadataMutation.h
fdbserver/CommitProxyServer.actor.cpp
fdbserver/LogSystem.cpp
fdbserver/LogSystem.h
fdbserver/Resolver.actor.cpp
fdbserver/ResolverInterface.h
fdbserver/ptxn/MessageSerializer.cpp
fdbserver/ptxn/MessageSerializer.h
fdbserver/ptxn/TLogGroupVersionTracker.actor.cpp
fdbserver/ptxn/TLogGroupVersionTracker.h
fdbserver/ptxn/TLogServer.actor.cpp
fdbserver/ptxn/test/TestResolver.actor.cpp

When private mutations are generated at Resolvers, accumulate them and assign them to corresponding TLog groups for version tracking. However, if any shard change is detected, the transaction batch has to switch back to broadcast.
The version tracker at Resolvers now accounts both groups from commit proxies and TLog groups for private mutations. Use "LogPushData" to accumulate private mutations.
The serialized private mutations are sent for each TLog group. After receiving them, the commit proxy deserializes all mutations and then writes to its internal buffer, before processing the rest of transaction data.
One unit test failure is unrelated (`-f ./tests/fast/RandomUnitTests.toml -s 755382714 -b on`, unit test `/fdbserver/ConfigDB/TransactionToLocalConfig/KillWorker`): …

Track metadata mutations' group version at Resolvers

---

fdbbackup/backup.actor.cpp
fdbclient/ManagementAPI.actor.cpp
fdbmonitor/fdbmonitor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/Resolver.actor.cpp
fdbserver/VersionedBTree.actor.cpp
fdbserver/art_impl.h
fdbserver/workloads/ConsistencyCheck.actor.cpp
fdbserver/workloads/SnapTest.actor.cpp
flow/Net2.actor.cpp

Cherry-pick #6082 to fix clang 13 warnings

Fix -Wunused-but-set-variable warnings

---

fdbserver/ClusterController.actor.cpp
fdbserver/WorkerInterface.actor.h
fdbserver/worker.actor.cpp

This is a cherry-pick of https://github.com/apple/foundationdb/pull/5909. This fixes a rare correctness issue where Master Recovery could get stuck.

Change dbinfo broadcast to be explicitly requested by the worker registration message (release-6.3)

---

fdbclient/CommitTransaction.h
fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/ptxn/MessageSerializer.cpp
fdbserver/ptxn/MessageSerializer.h
fdbserver/ptxn/MessageTypes.cpp
fdbserver/ptxn/MessageTypes.h
fdbserver/ptxn/TLogGroupVersionTracker.actor.cpp
fdbserver/ptxn/TLogInterface.cpp
fdbserver/ptxn/TLogPeekCursor.actor.cpp
fdbserver/ptxn/TLogPeekCursor.actor.h
fdbserver/ptxn/TLogServer.actor.cpp
fdbserver/ptxn/test/CommitUtils.cpp
fdbserver/ptxn/test/CommitUtils.h
fdbserver/ptxn/test/Delay.h
fdbserver/ptxn/test/Driver.actor.cpp
fdbserver/ptxn/test/Driver.h
fdbserver/ptxn/test/FakeProxy.actor.cpp
fdbserver/ptxn/test/FakeTLog.actor.cpp
fdbserver/ptxn/test/FakeTLog.actor.h
fdbserver/ptxn/test/TestSerialization.cpp
fdbserver/ptxn/test/TestTLogPeek.actor.cpp
fdbserver/ptxn/test/TestTLogPeek.h
fdbserver/ptxn/test/TestTLogServer.actor.cpp
fdbserver/ptxn/test/Utils.cpp
flow/Arena.h
tests/ptxn/TLogPeekCursor.toml

This set of commits provides the following features:
* Provide an implementation of merged cursor for the broadcast model. The broadcast model assumes for each commit, all storage teams are informed.
* Provide a test for the merged cursors
* Update the ptxn tests to differentiate commit versions and storage team versions.

Merge cursor

---

tests/slow/DiskFailureCycle.toml

Excluding DiskFailureCycle test for rocksdb storage engine. DiskFailureCycle injects chaos faults in AsyncFile layer, so this test is not valid for rocksdb storage engine as it does not used AsynFile.

Excluding DiskFailureCycle test for rocksdb storage engine.

---

fdbclient/ManagementAPI.actor.cpp
fdbserver/worker.actor.cpp

A process can be marked unreliable (due to fault injection) after it has been added to the protected list. Recheck for reliabilty during quorum change and exclude the unreliable processes.
The bug was found during Release 7.0 testing.

Don't include an unreliable process in the protected list.

---

fdbserver/masterserver.actor.cpp

This is a backport of #6076.
During master recovery, it was possible for the master to write the cstate but get blocked waiting for the minimum recovery duration. If this happened, it could send an invalid master registration that updated the recovery count but reported no proxies. This would cause the current proxies to terminate and start the recovery over.
This PR changes the logic to disallow updating the master registration between the point when the cstate is updated and the recovery enters the accepting commits phase.
This bug was detected by the ConfigureTest.
Passed 100K tests with no new failures. …

Fix a race condition with updating the coordinated state and updating the master registration (release-7.0)

---

fdbclient/ManagementAPI.actor.cpp
fdbclient/rapidjson/rapidjson.h
fdbserver/worker.actor.cpp
fdbserver/workloads/HealthMetricsApi.actor.cpp
flow/TDMetric.actor.h

Cherry-picck of #6095
A process can be marked unreliable (due to fault injection) after it has been added to the protected list. Recheck for reliability during quorum change and exclude the unreliable processes.
This fix surfaced another trace overflow issue which is also fixed in this PR why disabling the event for normal cases.

Cherry pick 7.0 sim fix

---

flowbench/benchmark.cmake

This fixes a compile error with clang 13. For some reason this only seems to come up on Arm.

Upgrade google benchmark to v1.6.0

---

fdbserver/ClusterController.actor.cpp

remoteDCIsHealthy() currently doesn't take CC_ENABLE_WORKER_HEALTH_MONITOR into account. When this knob is turned off, CC doesn't run any health monitoring logic. So when a failover happens due to primary region unhealthy, it may not be able to failback due to that the remote worker health monitoring is never started.
This fix is validated in kubernetes test. I'm also working on a simulation test to reproduce the behavior.

Use CC_ENABLE_WORKER_HEALTH_MONITOR knob to guard remoteDCIsHealthy logic

---

fdbserver/ClusterController.actor.cpp

[7.0] Use CC_ENABLE_WORKER_HEALTH_MONITOR knob to guard remoteDCIsHealthy logic

---

tests/slow/ApiCorrectnessSwitchover.toml

The ApiCorrectnessSwitchover test would very rarely (1/100K for just this test) run out of memory. This reduces some of the parameters in the test to try to use less memory.
Passed 500K correctness with no OOMs.

Modify parameters of ApiCorrectnessSwitchover test to avoid out of memory errors

---

tests/slow/ApiCorrectnessSwitchover.toml

This is a cherry-pick of #6102.
The ApiCorrectnessSwitchover test would very rarely (1/100K for just this test) run out of memory. This reduces some of the parameters in the test to try to use less memory.
Passed 10K targeted correctness of modified test.

Modify parameters of ApiCorrectnessSwitchover test to avoid out of memory errors (release-7.0)

---

fdbserver/CMakeLists.txt
fdbserver/workloads/BulkSetup.actor.h
fdbserver/workloads/MiniCycle.actor.cpp

This PR introduces the minicycle tester workload. The goal of the minicycle test is to reduce the runtime memory requirements of a large cycle test. To achieve this, the minicycle test splits the nodecount by the number of test processes into what we'll call "minicycles", and only checks one "minicycle" at a time by having each checkClient grab a lock before they're able to check their cycle. In this way, the memory usage of the minicycle test is `nodeSize * nodeCount/#testerProcesses`.
The minicycle test differs from the cycle test in one other major way: the "setup" phase and "check" phase are not separate.  The cycles are checked for errors while the cycles are perturbed by cycleClients. After `duration` lapses the cycles are checked one last time for consistency. If there are errors …

Add MiniCycle Test

---

bindings/c/test/unit/disconnected_timeout_tests.cpp

When checking whether a timeout fired too early, use a larger epsilon from the target duration.

Fix false positive in disconnected_timeout_test

---

fdbserver/KeyValueStoreRocksDB.actor.cpp

Enabling rocksdb metrics logger in simulation.

Enabling rocksdb metrics logger in simulation.

---

fdbserver/ptxn/TLogServer.actor.cpp
fdbserver/ptxn/test/Driver.h
fdbserver/ptxn/test/TestTLogServer.actor.cpp
fdbserver/worker.actor.cpp
tests/ptxn/TLogServer.toml

Single TLog can recover from disks
This PR makes it possible for single TLog server to recover from disk.
It assumes tlog was serving the same set of groups before the recovery,
which is not ideal. It can be fixed by persisting TLog groups metadata
onto TLog disk and only recover groups who sit in the overlap
of (old_from_disk, new_from_request).
Each interface serves a certain epoch that might include multiple groups,
but recovery must happen per group because data is stored per group.
Thus the recovery process is:
1. recover each group from disk
2. aggregate by epoch and group in TLogServer level
3. sstart previous and current epoch if necessary
joshua: 20211207-223418-haofu-4686b6c3973227dc
The general guidelines can be found [here](https://github.com/apple/foundationdb/wiki/FoundationD …

Single TLog can recover from disks

---

fdbclient/NativeAPI.actor.cpp

Removed knob check as it's overly restrictive and not useful

Removing this check as it still won't work if the knob is set

---

fdbserver/storageserver.actor.cpp

Added explicit empty version back for now

Adding explicit empty version back to change feeds for now

---

bindings/c/fdb_c.cpp
bindings/c/test/mako/mako.c
fdbclient/MultiVersionTransaction.actor.cpp
fdbclient/MultiVersionTransaction.h
fdbclient/ThreadSafeTransaction.cpp
flow/ThreadHelper.actor.h

Bug fixes and some refactoring for blob granules + handling inverted_range errors for other functions in fdb_c

Bg client cleanup

---

fdbcli/ConfigureCommand.actor.cpp
fdbcli/fdbcli.actor.cpp
fdbclient/ClientKnobs.cpp
fdbclient/ClientKnobs.h
fdbclient/DatabaseConfiguration.cpp
fdbclient/DatabaseConfiguration.h
fdbclient/ManagementAPI.actor.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/Schemas.cpp
fdbserver/BlobManager.actor.cpp
fdbserver/BlobManagerInterface.h
fdbserver/BlobWorker.actor.cpp
fdbserver/ClusterController.actor.cpp
fdbserver/SimulatedCluster.actor.cpp
fdbserver/Status.actor.cpp
fdbserver/workloads/BlobGranuleVerifier.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp
tests/fast/BlobGranuleCorrectness.toml
tests/fast/BlobGranuleCorrectnessClean.toml
tests/fast/BlobGranuleCycle.toml
tests/fast/BlobGranuleCycleClean.toml
tests/slow/BlobGranuleCorrectnessLarge.toml
tests/slow/BlobGranuleCorrectnessLargeClean.toml

This change allows us to use the CLI to dynamically turn on/off blob granules. Specifically, the configure command is
```
configure blob_granules_enabled=1
```
By default, blob granules are **disabled**.
Non-blob tests (w/ config turned off): 50k tests passed
Blob tests (w/ config turned on): approximately same passing rate as `blob_integration`
Verified that when the config is disabled by default, blob processes won't be recruited until the configure command is issued. Also verified that you can teardown easily by disabling the option.
Verified that when the config is enabled by default, blob processes are recruited when the database is started. …

Move blob granules knob to database config.

---

fdbserver/CommitProxyServer.actor.cpp
fdbserver/Resolver.actor.cpp
fdbserver/TLogGroup.actor.cpp
fdbserver/TagPartitionedLogSystem.actor.cpp

Before setting private mutations in the reply, addStateTransactions() tells us
if shard change happened in previous versions. In this way, the detection of
shard change becomes accurate.
non-PTXN correctness passed:
20211209-013138-jzhou-292915832167e63c             compressed=True data_size=20382368 duration=5371700 ended=100004 fail_fast=10 max_runs=100000 pass=100004 priority=100 remaining=0 runtime=1:09:49 sanity=False started=100114 stopped=20211209-024127 submitted=20211209-013138 timeout=5400 username=jzhou
PTXN test passed (with/without proxy-to-tlog group broadcast):
-r simulation --crash --logsize 1024MB --knob_tlog_new_interface 1 -fi off -f src/foundationdb/tests/ptxn/CycleTest.toml -b off -s 101
-r simulation --crash --logsize 1024MB --knob_tlog_new_interface 1 -fi off -f …

Resolver saves shardChanged in recent state transactions

---

fdbserver/TLogServer.actor.cpp
fdbserver/ptxn/TLogServer.actor.cpp

Not sure if there is a good way to test this, could you please advise @jzhou77 . It seems the read path is from master during a global recovery, is there an easy way to do that in unit test?
joshua: 20211213-165341-haofu-eca436c7d8f0c283 

Persist txsTag in TLog

---

bindings/c/test/unit/disconnected_timeout_tests.cpp

This is a cherry-pick of #6123.
When checking whether a timeout fired too early, use a larger epsilon from the target duration.

Fix false positive in disconnected_timeout_test (release-7.0)

---

fdbclient/ManagementAPI.actor.cpp

When no workers are chosen, we should return 0 coordinators.

Fix a bug in getDesiredCoordinators().

---

fdbclient/ManagementAPI.actor.cpp

Backporting #6150.
When no workers are chosen, we should return 0 coordinators.

Fix a bug in getDesiredCoordinators() (release-7.0).

---

fdbclient/ManagementAPI.actor.cpp

Backporting #6150.
When no workers are chosen, we should return 0 coordinators.

Fix a bug in getDesiredCoordinators() (release-6.3).

---

packaging/docker/Dockerfile.eks

To iterate faster on perf benchmarking, the storage and log servers will persist and restore their state from S3 after a load. To communicate with S3, this proposes to install the aws cli in the base image, rather than in ycsb.

Move awscli to base image from YCSB

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/KeyValueStoreRocksDB.actor.cpp

KeyValueStoreRocksDB histograms to track latencies 

KeyValueStoreRocksDB histograms to track latencies

---

bindings/python/CMakeLists.txt
bindings/python/tests/fdbcli_tests.py
cmake/AddFdbTest.cmake

We've been seeing some timeouts for add_fdbclient_test in CI. Maybe we need a longer timeout set.

Increase default timeout to 5 minutes for add_fdbclient_test

---

fdbserver/KeyValueStoreRocksDB.actor.cpp
fdbserver/Knobs.cpp
fdbserver/Knobs.h

cherry-pick #6149 to 7.0
KeyValueStoreRocksDB histograms to track latencies

cherry-pick #6149 to 7.0. KeyValueStoreRocksDB histograms to track latencies

---

fdbrpc/fdbrpc.h
fdbrpc/networksender.actor.h
flow/error_definitions.h
tests/TestRunner/tmp_cluster.py

~Ctest now runs cleanly on linux for ASAN builds.~ Ok there's still memory leaks but it's better
Previously, a memory leak detected by ASAN was causing "actual cluster" tests to fail with an exceptionally unhelpful error message, when the answer was in the logs along. To improve that, also output the logs if a test fails and look for sev40s.

Fix ctest under ASAN

---

fdbserver/RestoreLoader.actor.cpp

Fix a duplicate trace field in some debugging logic.

Fix duplicate trace field

---

bindings/c/test/workloads/SimpleWorkload.cpp
cmake/ConfigureCompiler.cmake
fdbserver/CoroFlowCoro.actor.cpp
fdbserver/DiskQueue.actor.cpp
fdbserver/LogSystemDiskQueueAdapter.h
flow/DeterministicRandom.h
flow/actorcompiler/ActorCompiler.cs
flow/flow.h
flow/genericactors.actor.h

We had been disabling -Wdelete-non-virtual-dtor, because this seems to be done intentionally in the generated code of the actor compiler. I spent some time trying to rewrite it in a way that doesn't literally delete/destroy through a pointer to a base class without a virtual destructor, but I was unable to come up with something that passes correctness. My best guess is that we do this so that we can destroy actor state classes, call callbacks registered on the actor SAV, and then destroy the SAV. 
Anyway now we'll detect new usages of deleting through a pointer to a base class without a virtual destructor. …

Enable -Wdelete-non-virtual-dtor for clang build

---

bindings/go/CMakeLists.txt
bindings/go/src/fdb/cluster.go
bindings/go/src/fdb/generated.go
fdbclient/vexillographer/fdb.options

It looks like we distribute the go bindings directly from github, so we need to keep the checked-in generated file up to date.
Also remove some unnecessary cgo stuff, and add a description to trace_partial_file_suffix.

Update generated.go, and test to keep it up to date

---

tests/CMakeLists.txt

Follow-up to https://github.com/apple/foundationdb/pull/6200 that removes the check against `SSD_ROCKSDB_EXPERIMENTAL` which is confusing and not working as one would expect. Overall design should be addressed further on https://github.com/apple/foundationdb/issues/6201

Ignore RocksDB unit test

---

fdbserver/Resolver.actor.cpp
fdbserver/TLogServer.actor.cpp
fdbserver/TagPartitionedLogSystem.actor.cpp
fdbserver/WorkerInterface.actor.h

This is incremental work towards passing cycle and upgrade tests in vv's UNICAST mode. Recall "recovered" tLogs crashed and are restarted. "restored" did not crash and can accept peeks during recovery.
- replace maxRv with recoverAt, so recovered tLogs pull data up to the max version rolled forward.
- Do not create invalid (null) versions in recovery.
- Broadcast to all tLogs metadata mutations.
Upgrades tested following [this](https://github.com/apple/foundationdb/wiki/How-to-reproduce-a-restart-test-failure) guide. 
TBD:
- investigate if necessary to manage "gaps" in versions peeked (per offline discussion).
- refactor, e.g. metadata mutations may not need to be broadcast, optimizations can be investigated in later work.
```
-r simulation --logsize=4096MiB -f …
```

Set recovered tLogs' recoverAt to max of all restored tLogs' RV in UNICAST mode

---

fdbserver/TLogInterface.h
fdbserver/WorkerInterface.actor.h

If the Request/Reply doesn't have *Ref types, we typically don't need to have an Arena.
Correctness passed:
20220107-222327-jzhou-5bb7456ab1585db9             compressed=True data_size=21063430 duration=5646565 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:50:43 sanity=False started=100103 stopped=20220107-231410 submitted=20220107-222327 timeout=5400 username=jzhou

Remove unneeded Arena in Requests/Replies

---

fdbserver/storageserver.actor.cpp

fix: localChangeFeeds cannot get wrong_shard_server errors

---

bindings/c/CMakeLists.txt
bindings/python/CMakeLists.txt

Issues can occur when loading a file named `libfdb_c.so` as an external client. We have various dependencies that load the `libfdb_c.so` generated as part of a build, as an external client. This PR renames the copy of `libfdb_c.so`at `bindings/c/` to `libfdb_c_external.so`.
Passed `ctest`.

Rename libfdb_c in bindings/c

---

fdbserver/ptxn/test/TestTLogServer.actor.cpp
tests/ptxn/TLogServer.toml

Previously only had a test to verify spilling happens with 0 threshold, not the other way.
Now adding it.

Add test to assert spilling not happen with a higher threshold

---

fdbserver/worker.actor.cpp

Change `AttemptedDoubleRecruitement` to `AttemptedDoubleRecruitment`.

Fix typo in trace event name

---

fdbserver/tester.actor.cpp
fdbserver/workloads/workloads.actor.h

This removes the explicit use of `new` and `delete` and makes the implementation more stable and resilient to memory leaks and invalid memory access in the future.

Use smart pointers to manage `TestWorkload` objects

---

fdbclient/DatabaseBackupAgent.actor.cpp
fdbclient/DatabaseContext.h
fdbclient/NativeAPI.actor.cpp
fdbclient/NativeAPI.actor.h
fdbclient/ReadYourWrites.actor.cpp
fdbclient/ReadYourWrites.h
fdbclient/SpecialKeySpace.actor.cpp
fdbserver/BackupWorker.actor.cpp
fdbserver/BlobManager.actor.cpp
fdbserver/DataDistributionTracker.actor.cpp
fdbserver/MoveKeys.actor.cpp
fdbserver/StorageCache.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp
fdbserver/workloads/IndexScan.actor.cpp
fdbserver/workloads/ReadHotDetection.actor.cpp
fdbserver/workloads/ReadWrite.actor.cpp
fdbserver/workloads/TargetedKill.actor.cpp
fdbserver/workloads/WriteTagThrottling.actor.cpp

I have a need to add new state to transactions and use it in the various operations, but the current state of transactions makes this difficult to do. I wanted to add some new state to the transaction that gets passed around to all the various actors without having to do a bunch of plumbing, so I modified the Transaction object to keep much of its data in a reference counted state object. New fields can be added to this state object and they will be usable in each of the operations.
I didn't pass around a pointer to the transaction itself because I'm not sure it's guaranteed that the transaction will outlive its operations at the NativeAPI layer.
I also changed the watch API to not store the now defunct `TransactionInfo` objects but instead to store its own data. …

Refactor Native API Transactions

---

fdbserver/TLogServer.actor.cpp
fdbserver/TagPartitionedLogSystem.actor.cpp

Fixes simulation failures below. 
1.
In vv UNICAST mode, recovery restarted too frequently, resulting in 20-30 second periods between the master's reading coordinated state and the set of recovered tLogs settling to a new epoch. 
To prevent this long cycle of convergence, the logic should be the same as existing fdb. In other words, only restart recovery when the set of recovered tLogs changes such that the recovery version is calculated to be less than what was derived in the previous set.
2.
Prior to the PR, a separate RV was computed for each tLog. This led to a situation where an RV for one tLog was less than another. If tLog A and B are in the same replica set, the latest key's versions must be stored on both A and B. Otherwise, a read to the SS peeked from A would different from …

Fix recovery restarts in vv UNICAST mode

---

fdbclient/DatabaseContext.h
fdbclient/NativeAPI.actor.cpp

Fixes a memory issue introduced by #6165. The watch map had been changed to hold Keys instead of KeyRefs, but then some usages of the key still held KeyRefs that could be invalidated.
Passed 1K valgrind correctness.
Passed 20K correctness.

Fix memory issue with client watch metadata

---

flow/actorcompiler/ActorParser.cs

The actor compiler does surprising things (and may even compile "successfully") if there's a preprocessor directive in an ACTOR. Disallow that. Tested by adding `#warning` inside an actor and seeing that it no longer compiles.

Reject preprocessor directives in ACTORs

---

fdbcli/ExcludeCommand.actor.cpp

I was looking into the exclusion internals and stumbled across that typo.

Fix typo in comment

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/KeyValueStoreRocksDB.actor.cpp

Added rocksdb read range iterator pool to reuse iterators.
Impact: Throughput double after this change.

Rocksdb read range iterator pool to reuse iterators.

---

fdbclient/SystemData.h
fdbserver/ClusterController.actor.cpp
fdbserver/ClusterController.actor.h
fdbserver/DataDistribution.actor.cpp
fdbserver/ServerDBInfo.actor.h

Patch updates code documentation to reflect the recent code
refactoring where ClusterController process drives recovery
instead of sequencer/master process.

Update code documentation for cluster recovery

---

fdbrpc/SimExternalConnection.actor.cpp
fdbrpc/SimExternalConnection.h
fdbrpc/sim2.actor.cpp
flow/Net2.actor.cpp
flow/network.cpp
flow/network.h

These functions will be used in restarting tests, where mock DNS needs to be saved to and read from files.
20220115-032454-renxuan-5abb2d445a658c60           compressed=True data_size=28103027 duration=5590149 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:50:16 sanity=False started=100252 stopped=20220115-041510 submitted=20220115-032454 timeout=5400 username=renxuan

Add the functions to convert mock DNS to and from string.

---

flow/IThreadPool.cpp
flow/IThreadPool.h
flow/Platform.actor.cpp
flow/Platform.h

Enabled setting thread poll priorities, so that we can put some work in low-priority thread-pool in RocksDB, e.g., garbage collection.

Enabled setting thread poll priorities.

---

contrib/transaction_profiling_analyzer/transaction_profiling_analyzer.py
fdbclient/ClientLogEvents.h

I painstakingly went through both transaction_profiling_analyzer.py and
fdbclient/ClientLogEvents.h to make sure that we really can read these
versions. I also tested with a local cluster built from this source tree that I can read the client log event info with transaction_profiling_analyzer.py. I also added some comments I would have found helpful along the way.

Add support for 7.0 and 7.1 in transaction_profiling_analyzer

---

fdbserver/ptxn/test/Driver.actor.cpp
fdbserver/ptxn/test/TestStorageServer.actor.cpp

FakeTLogs was using its own LogGroupID<->StorageTeamID mapping mechanism
With this patch, it uses tLogGroupByStorageTeamID
Letting FakeTLogs behaves better.

Let FakeTLogs uses tLogGroupByStorageTeamID

---

fdbclient/CoordinationInterface.h
fdbclient/MonitorLeader.actor.cpp
flow/network.cpp
flow/network.h

This PR comes without simulation tests except some unit tests. The simulation tests will be in the PR that uses hostname in code logic.
20220120-202432-renxuan-0f33a5da4ed10b20           compressed=True data_size=28129621 duration=5456030 ended=100002 fail_fast=10 max_runs=100000 pass=100002 priority=100 remaining=0 runtime=0:26:18 sanity=False started=100428 stopped=20220120-205050 submitted=20220120-202432 timeout=5400 username=renxuan

Add the support of using hostname in ConnectionString.

---

fdbclient/ServerKnobs.cpp

This matches the release-7.0 branch.

Change Redwood default page size knob to 8192

---

fdbserver/SimulatedCluster.actor.cpp
fdbserver/tester.actor.cpp
fdbserver/workloads/SaveAndKill.actor.cpp
tests/restarting/to_7.0.0/CycleTestRestart-1.toml
tests/restarting/to_7.0.0/CycleTestRestart-2.toml

This PR does NOT turn the feature on. Also, disable hostname in downgrade restarting tests.
20220121-032155-renxuan-40a38d1b3e140002           compressed=True data_size=28128486 duration=5311678 ended=100002 fail_fast=10 max_runs=100000 pass=100002 priority=100 remaining=0 runtime=0:58:53 sanity=False started=100166 stopped=20220121-042048 submitted=20220121-032155 timeout=5400 username=renxuan

Add the support for using hostname in simulation.

---

fdbserver/workloads/BlobGranuleVerifier.actor.cpp

fix: do not report errors when the blob verifier is actor_cancelled

---

cmake/ConfigureCompiler.cmake

Add a cmake option to pass the path to a library to link in an implementation
for the stub functions produced by -fsanitize-coverage=trace-pc-guard. Compile
with -fsanitize-coverage=trace-pc-guard if that option is set.

Add TRACE_PC_GUARD_INSTRUMENTATION_LIB

---

fdbclient/FDBTypes.h
fdbserver/TagPartitionedLogSystem.actor.cpp
fdbserver/ptxn/TLogInterface.h
fdbserver/ptxn/TLogPeekCursor.actor.cpp
fdbserver/ptxn/TLogPeekCursor.actor.h
fdbserver/ptxn/TLogServer.actor.cpp
fdbserver/ptxn/test/Driver.actor.cpp
fdbserver/ptxn/test/Driver.h
fdbserver/ptxn/test/TestTLogServer.actor.cpp
fdbserver/ptxn/test/Utils.cpp

Fixed invalid tlog group at TLog by looking up the group ID at the TLog receiving the TLogPeekRequest. Also fixed test driver to use the consistent team to group mapping.
Correctness `20220122-000750-jzhou-876a5b352f538db4` has 2 unit tests failed at `FailedAssertion="fVers.get().size() == fRecoverCounts.get().size()" File="/root/src/foundationdb/fdbserver/ptxn/TLogServer.actor.cpp" Line="1543"`, which seems not related to this change.

Remove TLogGroupID from TLogPeekRequest & ServerPeekCursor

---

bindings/c/CMakeLists.txt
contrib/pkg_tester/__snapshots__/test_fdb_pkgs.ambr
contrib/pkg_tester/test_fdb_pkgs.py

Cherry pick https://github.com/apple/foundationdb/pull/6120 to release-7.0
Tested by compiling and then using `execstack -q` to see if the stack is executable or not
Closes #6119 

Link libfdb_c with `-z noexecstack` (release-7.0)

---

fdbclient/SystemData.cpp

Using `ObjectWriter` to serialize the `StorageServerInterface`, allowing FDB 7.0 to continue to deserialize it even as fields are added (#6053 adds a new field to `NetworkAddress`, which is contained as a nested field within an object in `StorageServerInterface`).
Passed 10k `CycleTestRestart` main -> 7.0 downgrade tests.

Use ObjectWriter to write storage cache data (fixes CycleTestRestart downgrade test)

---

fdbclient/NativeAPI.actor.cpp
flow/Trace.cpp
flow/Trace.h

This is implemented using new functionality to set a universal trace field that is logged with every event. It serves to enhance the detail provided by `ThreadID` because the `ThreadID` may or may not actually identify the network thread logging an event depending on whether the event was logged on a different thread.
The client description is comprised of three parts: `<primary or external>-<release version>-<network thread ID>`. The network thread ID is the same as the field `ThreadID` that gets logged on trace events logged from the network thread.
Tested manually with a client process configured to use the multi-version client. Also passed 10K correctness.
An example of this field is shown below from a single client process:
```
<Event Severity="10" Time="1639161147.776237" …
```

Add ClientDescription field for client processes to identify the client logging an event.

---

fdbserver/storageserver.actor.cpp

Discovered by valgrind Joshua simulation tests. I re-ran a seed that reproduced this issue with the fix and observed that valgrind no longer complains.

Fix uninitialized memory in storage server

---

fdbclient/Schemas.cpp
fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbrpc/Locality.cpp
fdbrpc/Locality.h
fdbrpc/simulator.h
fdbserver/CMakeLists.txt
fdbserver/ClusterController.actor.cpp
fdbserver/ClusterController.actor.h
fdbserver/EncryptKeyProxy.actor.cpp
fdbserver/EncryptKeyProxyInterface.h
fdbserver/ServerDBInfo.actor.h
fdbserver/Status.actor.cpp
fdbserver/WorkerInterface.actor.h
fdbserver/worker.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp

Major changes includes:
1. Add a new FDB role responsible- EncyrptKeyProxy. The role is
responsible to expose APIs to fetch encyrption keys interacting
with external Encryption KeyManager interface.
2. The process is a FDB singleton process for now.
3. Code to recruit the worker process; given the encryption keys are
needed during recovery (decode TLog records), for now the process
is co-located in same datacenter as ClusterController and is the
first process to be recruited.
4. Skeleton process actor code; more functionality will be added in
subsequent PRs.
NOTE: The code is protected under a SERVER_KNOB with the default
value as 'false' for now. …

Add new FDB EncryptKeyProxy role

---

fdbcli/ChangeFeedCommand.actor.cpp

Change feed ranges can include unprintable characters, so they should use printable when displaying them. Tested manually using fdbcli, an example output is the following:
```
fdb> changefeed list
Found 1 range feeds:
myfeed: `\x15 a' - `\x15 z'
```

Use printable when formatting change feed ranges in fdbcli

---

bindings/python/tests/fdbcli_tests.py

Disable setclass fdbcli test for now

---

fdbserver/ptxn/TLogServer.actor.cpp
fdbserver/storageserver.actor.cpp

When TLog receives a peek request before it's ready, i.e., accepting commits,
the TLog can't find the correct TLog group.

Fix tlog group not found error

---

fdbserver/ptxn/TLogServer.actor.cpp
fdbserver/ptxn/test/Driver.actor.cpp
fdbserver/ptxn/test/Driver.h
fdbserver/ptxn/test/TestTLogServer.actor.cpp

This is to ensure in unit test, TLogServer won't be blocked when receiving peek requests.
I manually run ptxn/TLogServer.toml and it passed.
Correctness 20220128-042806-jzhou-19fda37d5a28aa57 passed

Set recovery state in updateServerDBInfo

---

fdbserver/IKeyValueStore.h
fdbserver/KeyValueStoreSQLite.actor.cpp
fdbserver/fdbserver.actor.cpp

To recover data from a broken cluster, we could use this new 'kvfiledump'
role to dump key-values from storage file(sqlite) directly.
Dumped key-values will print to stdout in binary format:
`[4-bytes key len][key binary][4-bytes value len][value binary]`
(len is in little endianness)
Users can use environment var to control the dump:
* `FDB_DUMP_STARTKEY`: start key for the dump, default is empty
* `FDB_DUMP_ENDKEY`: end key for the dump, default is \xff\xff\xff\xff
* `FDB_DUMP_DEBUG`: print key-values to stderr in escaped format …

Add role 'kvfiledump' to dump key-values from storage file

---

fdbclient/AutoPublicAddress.cpp
fdbclient/ClusterConnectionFile.actor.cpp
fdbclient/ClusterConnectionFile.h
fdbclient/ClusterConnectionKey.actor.cpp
fdbclient/ClusterConnectionKey.actor.h
fdbclient/ClusterConnectionMemoryRecord.actor.cpp
fdbclient/ClusterConnectionMemoryRecord.h
fdbclient/CoordinationInterface.h
fdbclient/MonitorLeader.actor.cpp
fdbclient/NativeAPI.actor.cpp
fdbrpc/SimExternalConnection.actor.cpp
fdbrpc/SimExternalConnection.h
fdbrpc/sim2.actor.cpp
fdbserver/LeaderElection.actor.cpp
fdbserver/fdbserver.actor.cpp
fdbserver/worker.actor.cpp
flow/Net2.actor.cpp
flow/network.h

When connection string contains hostname, there are places (e.g., `determinePublicIPAutomatically()`) where async resolving is impossible. The new added functions will and should only be used in those cases. For all other cases, the regular async `resolveHostnames()` and `resolveTCPEndpoint()` should be preferred.
Also, combine `IClusterConnectionRecord::getConnectionString()` and `IClusterConnectionRecord::getMutableConnectionString()` to `IClusterConnectionRecord::getConnectionString()`, and rename `setConnectionString()` to `setAndPersistConnectionString()`.
20220128-014412-renxuan-5e1c616c1b75b5c8           compressed=True data_size=28344993 duration=5093169 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=0:56:48 sanity=False started=100412 …

Add resolveHostnamesBlocking() and resolveTCPEndpointBlocking() to resolve hostnames where async resolving is impossible.

---

bindings/c/test/unit/trace_partial_file_suffix_test.cpp
bindings/python/tests/fdbcli_tests.py
flow/FileTraceLogWriter.cpp
tests/TestRunner/local_cluster.py
tests/TestRunner/tmp_cluster.py

Fix a few sources of flakiness in our "ctest" tests. Flakiness found by running the tests many times in Joshua, using #6237 

Fix flaky ctest tests

---

fdbclient/GlobalConfig.actor.cpp
fdbclient/ManagementAPI.actor.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/SpecialKeySpace.actor.cpp

Currently, access to the system keys is enforced by RYW, so native transactions that access system keys do not have to declare their intent to do so. In the [multi-tenant API](https://github.com/apple/foundationdb/pull/6274), these options will have an additional effect that applies to certain native transactions, and so we need to set this option in more places.
In particular, it will be required to use the `RAW_ACCESS` option when accessing system keys when the cluster is configured to require tenants. This option will be implied by using `READ_SYSTEM_KEYS` or `ACCESS_SYSTEM_KEYS`, so we can use those instead.
This rule is not enforced for internal transactions, so we don't need to update transactions everywhere. We do, however, need to update all transactions that are run from the …

Mark various externally exposed system transactions as read/access system keys

---

fdbserver/ApplyMetadataMutation.cpp
fdbserver/ApplyMetadataMutation.h
fdbserver/ProxyCommitData.actor.h
fdbserver/Resolver.actor.cpp

Just refactor set to unordered_set.

ssToStorageTeam: Use unordered_set instead of set

---

flow/Arena.cpp
flow/Arena.h

This adds a hash function that can be used for `Optional`. It also introduces a default boost hash function for types that cannot be hashed using boost but can be hashed using `std::hash`. This is useful if we want to take advantage of boost's ability to hash certain types, like `std::pair`, that are not hashable by `std::hash` but that have members that are.
These hash functions are not currently used anywhere on main (they will be in https://github.com/apple/foundationdb/pull/6274), so simulation will not exercise them. The newly added unit tests pass …

Add a hash function for Optional and a default boost hash function

---

fdbclient/NativeAPI.actor.cpp
fdbclient/NativeAPI.actor.h

Previously, resetting a transaction would modify the transaction state reference object. This object could still be in use by operations that were in-flight during the reset. There haven't been any apparent issues with the fields currently in this state, but there are some future fields where this will be a problem.
This change makes it so that we create a new transaction state upon reset and copy relevant values.
Passed 10K correctness with 1 restarting failure that matches the pattern of an unrelated issue.

Copy transaction state during reset

---

fdbserver/CommitProxyServer.actor.cpp
flow/Arena.h

This makes `VectorRef<T>` `noexcept` movable, improving the performance of resizing any `std::vector<U>` object where `U` has some field `VectorRef<T>` (assuming all other fields have `noexcept` move constructors).

Make `VectorRefPreserializer` move constructor noexcept

---

fdbcli/fdbcli.actor.cpp

The `printAtCol` function does some helpful wrapping, etc. for printing in `fdbcli`. Update this function to allow printing to other streams, such as `stderr`.
Tested manually in fdbcli:
```
fdb> help getrange
getrange <BEGINKEY> [ENDKEY] [LIMIT]
Fetch key/value pairs in a range of keys.
Displays up to LIMIT keys and values for keys between BEGINKEY (inclusive) and
ENDKEY (exclusive). If ENDKEY is omitted, then the range will include all keys
starting with BEGINKEY. LIMIT defaults to 25 if omitted.
For information on escaping keys, type `help escaping'.
``` …

Support other output streams in fdbcli printAtCol

---

fdbcli/fdbcli.actor.cpp

This change adds an additional flag to `fdbcli` to set the log group otherwise the log group will be `default`.
I did a local test to show that the `LogGroup` will be used:
```xml
<Event Severity="10" Type="ClientStart" ID="0000000000000000" SourceVersion="e942fb9cb55b3da2e5ce6789683e5f0a9460a11f" Version="6.3.24" mageOffset="(nil)"  LogGroup="test" TrackLatestType="Original" />
```

Add LogGroup support to fdbcli

---

fdbclient/SystemData.cpp
fdbclient/SystemData.h
fdbserver/ApplyMetadataMutation.cpp
fdbserver/ApplyMetadataMutation.h
fdbserver/CommitProxyServer.actor.cpp
fdbserver/ProxyCommitData.actor.h
fdbserver/Resolver.actor.cpp

Refactor code to use `ptxn::StorageServerStorageTeams` instead of set.

ptxn: Use StorageServerStorageTeams class instead of set

---

fdbserver/ptxn/TLogPeekCursor.actor.cpp
fdbserver/ptxn/TLogPeekCursor.actor.h
fdbserver/storageserver.actor.cpp

This adds subscribedStorageTeamIDs to ptxn::StorageServer class, contains storage team ID the storage server is using.

Storage server should have storage team ID accessible

---

fdbserver/storageserver.actor.cpp

TSS comparison assumes that the SS and TSS will chunk stream replies the same way for the same underlying data. A buggify for changing the chunk size did not take into account restarting tests having a different tss mode in the second test, but tss being enabled in the first test.
Passed 10k restarting tests and 100k correctness tests.

Fixing TSS buggify in restarting tests

---

fdbserver/TLogServer.actor.cpp
fdbserver/ptxn/TLogInterface.h
fdbserver/ptxn/TLogServer.actor.cpp
fdbserver/ptxn/test/Driver.actor.cpp
fdbserver/ptxn/test/TestTLogServer.actor.cpp
fdbserver/storageserver.actor.cpp
tests/ptxn/TLogServer.toml

Previously TLog does not support pop, it is needed because
otherwise we cannot trim data on memory/disk.
This commit only changes the memory part, disk part will be a separate PR

    Add pop API for TLog

---

flow/ProtocolVersion.h
flow/serialize.h

The last bit of the protocol version has been set, though this bit is typically masked out and I don't think has a need to be used here. I've unset it and also reordered the various protocol version feature declarations to match their version order.
This adds some comments documenting the expectations for the protocol version and the min invalid protocol version, and it also adds some static assertions to ensure that those expectations are being met.

Unset the last bit of the protocol version

---

bindings/go/src/fdb/generated.go
fdbclient/vexillographer/fdb.options

Update the description to start with Deprecated, so that it will be
deprecated in the generated java files.

Deprecate transaction_include_port_in_address

---

contrib/ctest_to_joshua.py

This could be used to diagnose flaky tests

Create joshua package from ctest tests

---

bindings/go/src/_stacktester/directory.go
bindings/go/src/fdb/directory/allocator.go
bindings/go/src/fdb/directory/directorySubspace.go
bindings/go/src/fdb/directory/node.go
bindings/go/src/fdb/subspace/subspace.go
bindings/go/src/fdb/tuple/tuple.go
bindings/go/src/fdb/tuple/tuple_test.go
recipes/go-recipes/blob.go
recipes/go-recipes/doc.go
recipes/go-recipes/graph.go
recipes/go-recipes/indirect.go
recipes/go-recipes/priority.go
recipes/go-recipes/queue.go
recipes/go-recipes/table.go

Go is very opinionated about the code style and offers tools to enforce those guidelines like `gofmt` and `goimports`. I ran the following command to get those changes:
```bash
gofmt -s -w  .
goimports -w .
```
We might want to consider to add this to our CI pipeline to enforce this style.

Fix go style issues

---

fdbserver/CommitProxyServer.actor.cpp
fdbserver/ptxn/TLogServer.actor.cpp

Let only resolver 0 to process metadata mutations and generate private mutations.
20220207-173004-jzhou-ab775e34e5ba041b has one failure (timeout) of unit test `read_persisted_disk_on_tlog`, which is unrelated.

Do not sent metadata mutations to all resolvers

---

fdbclient/FDBTypes.h
fdbserver/DiskQueue.actor.cpp
fdbserver/IDiskQueue.h
fdbserver/KeyValueStoreMemory.actor.cpp
fdbserver/worker.actor.cpp
fdbserver/workloads/ConfigureDatabase.actor.cpp

The PR addresses #5141 
Support using xxhash3 to checksum DiskQueue blocks, when TLogVersion >= 7. Also changing default TLogVersion to V6 for FDB 7.1.
For now KeyValueStoreMemory will still be using crc32 checksum for the underlying DiskQueue.

Support xxhash3 for checksuming DiskQueue for TLogs

---

cmake/AddFdbTest.cmake

Tested by inspecting the contents of the valgrind joshua package before and after this change

Don't run downgrade tests for valgrind. Closes #6322

---

flow/Knobs.cpp
flow/Knobs.h
flow/Tracing.actor.cpp

This PR introduces a change to allow a user to configure a destination addr/port pair, rather than simply a port when enabling the `network_lossy` tracer.
Previously the address of the tracing receiver was hardcoded to `127.0.0.1`. It will be quite common for users to provision tracing collector agents as sidecars or on separate hosts. In many cases sidecars will use various networking configurations with bridge or overlay style networks that will require sending traces to a specific IP other than localhost. The same of course is applicable to collectors provisioned on other hosts.
If this …

Refactor TRACING_UDP_LISTENER_PORT to TRACING_UDP_LISTENER_ADDR.

---

fdbservice/FDBService.cpp

Missed new path to SimpleIni.h in FDBService.cpp after has been moved by #6336

Fix path to SimpleIni.h in FDBService.cpp

---

fdbserver/DiskQueue.actor.cpp
fdbserver/IDiskQueue.h
fdbserver/TLogServer.actor.cpp
fdbserver/ptxn/TLogServer.actor.cpp
fdbserver/ptxn/test/Driver.actor.cpp
fdbserver/ptxn/test/TestTLogServer.actor.cpp

TLog pop works for on-disk data
Previously only in-memory data is popped, this commit makes
on-disk data work with pop API.
This PR also tests for spilling data, because when popping
we need to consider both spilling and disk queue.
Due to the way the code is written, I find no easy way to
disable spill while still popping, so they are tested together.
This commit also sets the spill threshold to default value
for tests who needs to peek, to avoid spilling because peek
does not work for on-disk data now, need fo fix it before
uncomment them.
20220204-032133-haofu-b98c5e0b37b2b2a9  (3 failures, fixed)
20220204-042420-haofu-c371efc0424eaa86
3rd commit: 20220208-022341-haofu-7e048f4907113fb3
This PR is based on https://github.com/apple/foundationdb/pull/6299 (merge 6299 first)
The general …

TLog pop works for on-disk data

---

cmake/CompileBoost.cmake
cmake/CompileRocksDB.cmake
cmake/FDBComponents.cmake
cmake/Finduring.cmake
fdbserver/CMakeLists.txt
fdbserver/KeyValueStoreRocksDB.actor.cpp

Update Boost to 1.78 (for io_uring support)
Update RocksDB to latest 6.27.3
Make WITH_LIBURING, PORTABLE_ROCKSDB available at CMake command line (instead of hardcoded)

support io_uring for RocskDB storage engine

---

cmake/CompileBoost.cmake
cmake/CompileRocksDB.cmake
cmake/FDBComponents.cmake
cmake/Finduring.cmake
fdbserver/CMakeLists.txt
fdbserver/KeyValueStoreRocksDB.actor.cpp

add Finduring, and include into fdbserver
add BOOST asio/uring settings to fdbserver compile
move portable rocks, liburing up to be configurable at build time.
CPing https://github.com/apple/foundationdb/pull/6351.

update RocskDB and Boost (partitioned-txns)

---

fdbserver/DDTeamCollection.actor.cpp
fdbserver/DDTeamCollection.h
fdbserver/DataDistribution.actor.cpp

This is a follow-up to https://github.com/apple/foundationdb/pull/6342. Method implementations are moved into the `DDTeamCollection.actor.cpp` file. Several other minor fixes are included as well.

Move `DDTeamCollection` method implementations into `.cpp` file

---

cmake/CompileBoost.cmake
cmake/CompileRocksDB.cmake
cmake/FDBComponents.cmake
cmake/Finduring.cmake
fdbserver/CMakeLists.txt
fdbserver/KeyValueStoreRocksDB.actor.cpp

add Finduring, and include into fdbserver
add BOOST asio/uring settings to fdbserver compile
move portable rocks, liburing up to be configurable at build time.
Backporting #6351.

update RocksDB and Boost (release-7.0)

---

cmake/CompileBoost.cmake
cmake/CompileRocksDB.cmake
cmake/FDBComponents.cmake
cmake/Finduring.cmake
fdbserver/CMakeLists.txt
fdbserver/KeyValueStoreRocksDB.actor.cpp

add Finduring, and include into fdbserver
add BOOST asio/uring settings to fdbserver compile
move portable rocks, liburing up to be configurable at build time.
Backporting https://github.com/apple/foundationdb/pull/6351.

update RocksDB and Boost (release-6.3)

---

fdbcli/ExcludeCommand.actor.cpp

The help text for fdbcli exclude has some typos and formatting issues and also refers to some internal concepts. This attempts to fix those issues.
The previous help text looked like this:
```
fdb> help exclude
exclude [FORCE] [failed] [no_wait] [<ADDRESS...>] [locality_dcid:<excludedcid>] [locality_zoneid:<excludezoneid>] [locality_machineid:<excludemachineid>] [locality_processid:<excludeprocessid>] or any locality data
Exclude servers from the database either with IP address match or locality match.
If no addresses or locaities are specified, lists the set of excluded addresses
and localities.
For each IP address or IP:port pair in <ADDRESS...> or any LocalityData
attributes (like dcid, zoneid, machineid, processid), adds the address/locality
to the set of excluded servers and …
```

Improve the help for fdbcli exclude

---

cmake/InstallLayout.cmake
packaging/docker/build-images.sh
packaging/docker/fdb.bash

Capture the changes that we missed (somehow) during the "git merge" done by commits 9544379cd and 72e06369a.
NOTE: It is not clear how we missed these changes while doing the above "git merge" commits.
Changes:
cmake/InstallLayout.cmake: Capture the change made to this file by commit 95d33cb363.
packaging/docker/build-images.sh: Capture the change made to this file by commit 8aab68303b.
packaging/docker/fdb.bash: Capture the changes made to this file by commits 504f08a102 and f24adc7b6a.
Testing:
Did a clean "cmk" and verified that "packages/docker" directory got created under "build_output".
Simulation tests: 20220211-185314-sre-47ce66fcf5ad7b40 (but the results of this test run are probably not going to be very interesting in the context of this PR). …

Version vector prototype: Capture changes missed while doing the recent "git merge"

---

fdbrpc/FlowTransport.actor.cpp

It was previously possible (at least in simulation) that registering an interface in the endpoint map would assign it endpoints from the spaces reserved for well-known endpoints. This changes the assignment logic to skip the well-known section when allocating these endpoints.

When inserting multiple streams into an EndpointMap, don't assign them to the well-known endpoint space

---

fdbrpc/FlowTransport.actor.cpp

Logging a protocol version object directly gives a human readable version of the protocol version. Update the `ConnectionRejected` event to do this rather than logging the integer form of the protocol version.

Log protocol version as a hex string rather than a uint64_t

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/LogRouter.actor.cpp
fdbserver/TLogServer.actor.cpp

This PR implements a tradeoff that reduce TLog CPU consumption by reducing empty peek reply, at the potential cost of increasing read latency.
As shown in a real cluster test, the biggest CPU contributor in TLogs is sending out messages (more specifically, the connectionWriter actor), and majority of the messages are peek reply (>80% in a modified YCSB test workload). Among those peek reply, majority of them do not contain any data (40% to 80%, depending on system load). The rate of peek reply is also very high (> 10k qps). It's unclear that to serve read requests, we need this aggressive empty peek reply to notify SS the latest version.
This PR implements a mechanism to batch empty peek reply in short window (1 ms, configurable). Preliminary result shows that this reduces empty peek …

Reduce the number of empty peek reply by not always returning empty peek reply immediately

---

fdbclient/CommitTransaction.h
fdbrpc/fdbrpc.h
fdbrpc/networksender.actor.h
fdbserver/Resolver.actor.cpp
fdbserver/ptxn/TLogServer.actor.cpp
flow/error_definitions.h

Fix Valgrind error of uninitialized data in `CommitTransactionRef`. Cherrypick another fix and fix a tlog initialization order.
I manually ran failed seeds and they now passed.
20220218-234822-jzhou-88ccac247082cd5e passed.

Fix Valgrind error

---

fdbserver/Knobs.cpp
fdbserver/Knobs.h
fdbserver/LogRouter.actor.cpp
fdbserver/TLogServer.actor.cpp

Cherry pick #6402 
20220217-224246-zhe-opt-7.0-3da0e652ca9b399f       compressed=True data_size=25337405 duration=5376245 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:09:02 sanity=False started=100083 stopped=20220217-235148 submitted=20220217-224246 timeout=5400 username=zhe-opt-7.0

[release 7.0] Reduce the number of empty peek reply by not always returning empty peek reply immediately

---

fdbclient/CommitTransaction.h
fdbserver/Resolver.actor.cpp

I manually verified the failed seeds now pass.
20220219-004736-jzhou-908ce3b7dbcb9a60 has one unrelated timeout failure in `ConsistencyCheck`.

Fix Valgrind error of uninitialized data in CommitTransactionRef

---

README.md

Not available: https://www.foundationdb.org/download/
Change to https://github.com/apple/foundationdb/releases

Fix invalid link to download page

---

fdbclient/CoordinationInterface.h
fdbclient/MonitorLeader.actor.cpp

When multiple threads try to resolve hostnames concurrently, we should have only one resolving and others wait on the result. Otherwise, they would add duplicated resolved results to coordinators.
20220218-230559-renxuan-4d4bf3f715ac7c6d           compressed=True data_size=28966687 duration=5017964 ended=100002 fail_fast=10 max_runs=100000 pass=100002 priority=100 remaining=0 runtime=0:31:23 sanity=False started=100191 stopped=20220218-233722 submitted=20220218-230559 timeout=5400 username=renxuan

Change ClusterConnectionString's status flag from boolean to enum.

---

fdbserver/Knobs.cpp
fdbserver/Knobs.h
fdbserver/LogRouter.actor.cpp
fdbserver/TLogServer.actor.cpp

Cherry pick #6402 
20220217-225226-zhe-opt-6.3-bc952c4c08075aa5       compressed=True data_size=22138016 duration=5661842 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:06:59 sanity=False started=100290 stopped=20220217-235925 submitted=20220217-225226 timeout=5400 username=zhe-opt-6.3

[release 6.3] Reduce the number of empty peek reply by not always returning empty peek reply immediately

---

fdbserver/DDTeamCollection.actor.cpp
fdbserver/DDTeamCollection.h

Put test case actors for DD in a UT class that that is a friend of the DDTeamCollection class. Make the test-specific methods of DDTeamCollection private. Have TEST_CASEs invoke these UT class static ACTORs.

Dd utestclass

---

flow/StreamCipher.cpp
flow/StreamCipher.h

StreamCipher keeps record of CipherKeys created
(including globalCipherKey) to ensure the sensitive data gets
ZERO-OUT and not recorded as part of FDB process dump. However,
in current code it is maintained as an unordered_set indexed
by the object itself. Approach adds non determinism given
object pointer based indexing scheme.
Patch addresses the concern by updating the recording to use
a map indexed by UID.

Update StreamCipher ctx/cipher management to respect determinism

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/KeyValueStoreRocksDB.actor.cpp

PerfContext can help us understand the performance bottleneck of **individual** DB operations. 
In this PR, we randomly sample DB operations and get the corresponding PerfContext on each thread (four read thread and one write thread). We periodically output the metrics. The metric includes the metric of each thread and the sum of all read/write threads.
How to use:
Set `ROCKSDB_PERFCONTEXT_ENABLE` to open this function.
Search `RocksDBPerfContextMetrics` traceevent.
`ROCKSDB_PERFCONTEXT_SAMPLE_RATE` indicates the sample rate of PerfContext.
Passed Joshua test:
20220224-040144-zhewang-8bcbc1507aa03be5           compressed=True data_size=29007273 duration=5146654 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:51:19 sanity=False started=100600 …

Add RocksDB PerfContextMetrics

---

packaging/docker/Dockerfile

Since we started releasing `rc` versions of FDB, we need to ensure we can copy versions of the libraries for two rc versions to support upgrading. With this change we remove the munging of the version when we copy them inside `/var/fdb/lib` and `/usr/lib/fdb/multiversion`.

sidecar: use full version of fdb to support incompatible release candidates

---

fdbserver/WorkerInterface.actor.h
fdbserver/ptxn/TLogServer.actor.cpp
fdbserver/ptxn/test/TestTLogServer.actor.cpp
tests/ptxn/TLogServer.toml

Now only support peeking when it is spill-by-value.
Support for spill-by-reference will come in another PR.
20220220-034042-haofu-5bbdc35a35c70f41
latest: 20220224-162602-haofu-9c1af27a48dec20b

Partitioned TLog can peek from disk

---

fdbclient/ClientKnobs.cpp
fdbclient/ClientKnobs.h
fdbclient/DatabaseContext.h
fdbclient/NativeAPI.actor.cpp

This PR tries to fix a case where proxies are overloaded by GetKeyLocation when a SS is failed.
The situation this can happen is when a SS is terminated (e.g. experience an IO failure), but the worker is still up and running. After this time, client GetKeyLocation returns a failed endpoint. There is a logic that when the endpoint is failed, but the worker is healthy, the client will invalidate the cache. This is to account for the case when we bounce the cluster, all SSes' endpoints will get updated. However, in this case, the proxies will still return the failed enpoint until the data movement is finished, and this period can last for a quite sometime (hours). During this period, all read requests will result in GetKeyLocation requests to the proxy, including the reads performed by the …

Fix get key location overloading proxies

---

fdbserver/CoroFlow.actor.cpp

foundationdb/fdbserver/CoroFlow.actor.cpp:262:8: error: no member named 'errorUnsuppressed' in 'BaseTraceEvent'

Fix macOS CI broken by #6449.

---

fdbclient/VersionedMap.h
fdbserver/Timing.h
fdbserver/ptxn/MutableTeamPeekCursor.actor.h
fdbserver/ptxn/TLogPeekCursor.actor.cpp
fdbserver/ptxn/TLogPeekCursor.actor.h
fdbserver/ptxn/test/Driver.actor.cpp
fdbserver/ptxn/test/Driver.h
fdbserver/ptxn/test/FakeTLog.actor.cpp
fdbserver/ptxn/test/RealStorageServer.actor.cpp
fdbserver/ptxn/test/TestStorageServer.actor.cpp
fdbserver/ptxn/test/TestTLogPeek.actor.cpp
fdbserver/storageserver.actor.cpp
tests/ptxn/TLogPeekCursor.toml

* Allow ptxn cursors re-iterate messages between each RPC call.
* Storage server now have code path (enabled by ENABLE_PARTITIONED_TRANSACTIONS knob) that reads from TLogs via ptxn cursor
* Storage server update code is cleaned up

Storage server accepts storage team based cursor

---

contrib/CMakeLists.txt
contrib/debug_determinism/CMakeLists.txt
contrib/debug_determinism/README.md
contrib/debug_determinism/debug_determinism.cpp
fdbclient/FDBTypes.h
fdbrpc/sim2.actor.cpp
fdbserver/DDTeamCollection.actor.cpp
fdbserver/MoveKeys.actor.cpp
flow/Arena.cpp
flow/FastAlloc.cpp
flow/SystemMonitor.cpp
flow/flow.cpp

Add an instrumentation-based technique for debugging unseed mismatches. Also guard a few existing sources of nondeterminism that don't affect unseeds with the DEBUG_DETERMINISM macro.
Also change the simulated run loop to not run as the only task inside the real run loop, since that was a source of nondeterminism.
Also fix nondeterminism from calling `timer_int`

Add contrib/debug_determinism

---

fdbclient/DatabaseContext.h
fdbclient/Knobs.cpp
fdbclient/Knobs.h
fdbclient/NativeAPI.actor.cpp

Cherry-pick #6446 to release 6.3
20220225-201358-zhe-6.3-8127bf61dbe5ffe0           compressed=True data_size=22141129 duration=5380432 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:20:17 sanity=False started=100077 stopped=20220225-213415 submitted=20220225-201358 timeout=5400 username=zhe-6.3

 [release 6.3] Fix get key location overloading proxies

---

fdbserver/ptxn/TLogServer.actor.cpp

This is a follow-up PR for 6404
20220225-213408-haofu-3c1f61d536ce2d55

Use Standalone rather than pair of StringRef and Arena

---

bindings/c/test/mako/mako.c
bindings/c/test/txn_size_test.c
documentation/tutorial/tutorial.actor.cpp
fdbbackup/backup.actor.cpp
fdbcli/AdvanceVersionCommand.actor.cpp
fdbcli/ChangeFeedCommand.actor.cpp
fdbcli/StatusCommand.actor.cpp
fdbcli/fdbcli.actor.cpp
fdbclient/ConfigKnobs.cpp
fdbclient/FileBackupAgent.actor.cpp
fdbclient/ManagementAPI.actor.cpp
fdbserver/ConfigDatabaseUnitTests.actor.cpp
fdbserver/DDTeamCollection.actor.cpp
fdbserver/KeyValueStoreSQLite.actor.cpp
fdbserver/Status.actor.cpp
fdbserver/fdbserver.actor.cpp
fdbserver/workloads/Mako.actor.cpp
fdbserver/workloads/ReadWrite.actor.cpp
flow/Platform.actor.cpp

MacOS warnings are format warnings, e.g., `format specifies type 'long' but the argument has type 'Version' (aka 'long long')`.
Windows warnings are `ACTOR does not contain a wait() statement`.

Eliminate warnings in macOS and Windows CI builds.

---

tests/restarting/to_7.0.0/CycleTestRestart-1.txt

This fixes an issue where old binaries are unable to parse connection strings in simulation.

Set `disableHostname=true` in CycleTestRestart downgrade test

---

cmake/InstallLayout.cmake
contrib/pkg_tester/test_fdb_pkgs.py

- Use centos:7 for pkg_tester
- Avoid conflict between versioned client/server rpms
- Remove brittle fdbcli help text snapshot test

Use centos:7 for pkg_tester

---

fdbclient/DatabaseContext.h
fdbclient/Knobs.cpp
fdbclient/Knobs.h
fdbclient/NativeAPI.actor.cpp

Cherry pick #6446 to release 7.0
20220225-050412-zhewu-7.0-212f06981b78cf4b         compressed=True data_size=25339644 duration=5445358 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:19:20 sanity=False started=100033 stopped=20220225-062332 submitted=20220225-050412 timeout=5400 username=zhewu-7.0

[release 7.0] Fix get key location overloading proxies

---

fdbclient/NativeAPI.actor.cpp

Port back addressed comments from #6453 
20220228-225404-zhewu-port-116444662ba44f3a        compressed=True data_size=29094365 duration=5761746 ended=100001 fail=1 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:51:03 sanity=False started=100135 stopped=20220228-234507 submitted=20220228-225404 timeout=5400 username=zhewu-port

Port back addressed comments for fixing get key location issue

---

fdbserver/DDTeamCollection.actor.cpp

Fixes nightly correctness issue.
It looks like adding the getClusterId function caused a race in SS recruitment that could cause many (in this case, thousands) of recruitment requests to spam to the same server at the same time.
Passed 10k correctness

Fix many repeated recruitment bug

---

fdbserver/ProxyCommitData.actor.h

This fixes a bug causing `status json` to omit commit latency statistics, because `commitLatencyBands` and `commitLatencySample` used the same name.

Fix name of `ProxyCommitData::commitLatencyBands` sample

---

fdbcli/StatusCommand.actor.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/NativeAPI.actor.h
fdbclient/Schemas.cpp
fdbserver/DDTeamCollection.actor.cpp
fdbserver/Status.actor.cpp
fdbserver/workloads/StatusWorkload.actor.cpp

This PR
1. report wiggle server's UID and address in `status json`
2. report wiggle server's address in `status`
```
Configuration:
Redundancy mode        - single
Storage engine         - ssd-2
Coordinators           - 1
Usable Regions         - 1
Cluster:
FoundationDB processes - 3
Zones                  - 1
Machines               - 1
Memory availability    - 8.0 GB per process on machine with least available
Fault Tolerance        - 0 machines
Server time            - 03/02/22 19:28:52
Data:
Replication health     - (Re)initializing automatic data distribution
Moving data            - unknown (initializing)
Sum of key-value sizes - unknown
Disk space used        - 420 MB
Storage wiggle:
Wiggle server addresses- 10.180.1.234:9000
Wiggle server count    - 1
```
The general guidelines can …

Print the IP:Port address of wiggling server in status

---

fdbserver/ptxn/TLogInterface.h
fdbserver/ptxn/TLogServer.actor.cpp
fdbserver/ptxn/test/Driver.actor.cpp
fdbserver/ptxn/test/Driver.h
fdbserver/ptxn/test/FakeTLog.actor.cpp
fdbserver/ptxn/test/RealTLog.actor.cpp
fdbserver/ptxn/test/TestTLogServer.actor.cpp

Manually verified the fixes work.

Fix several Valgrind errors of uninitialized memory

---

bindings/c/test/mako/mako.c

Mako attempts to create this directory multiple times in normal operation. It's ok if this directory already exists.

Allow for mako tmp directory to already exist

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/KeyValueStoreRocksDB.actor.cpp

RocksDB increasing background threads to speedup compaction.
max_background_compactions = 4;  // Maximum number of concurrent background jobs(threads used for flush and compaction)
max_subcompactions = 2;   // Maximum number of threads that will concurrently perform a compaction job by breaking it into multiple smaller ones that are run simultaneously
Why?
1)To give more cpu resources/time for compaction, as compaction is giving low priority and always postponed to do until we reach the thresholds.
2)Observed that a SS having high(>80 billion bytes) pendingCompactionBytes is not using 100% CPU. So, with this we can use the unused CPU for compaction.
3)We see write stalls upto 50 seconds in the case where we have lot of pending compacted data in L0 of LSM. The data in L0 to L1 mostly …

RocksDB increasing background threads to speedup compaction.

---

fdbserver/workloads/WriteDuringRead.actor.cpp

I made one quick attempt to use `clang-format off`, but the proposed change here was more effective.

Fix formatting issues caused by clang-format in WriteDuringRead workload

---

fdbclient/NativeAPI.actor.cpp
fdbserver/workloads/SidebandSingle.actor.cpp

The GRV caching PR used `TraceEvent().error(e, true)`, which was removed in another recent commit. This updates those calls to use the new `errorUnsuppressed` function and fixes the build.

Fix conflict between two recent merges by using the new errorUnsuppressed function

---

fdbclient/FDBTypes.h
fdbclient/SpecialKeySpace.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp
fdbserver/workloads/DataDistributionMetrics.actor.cpp
fdbserver/workloads/FuzzApiCorrectness.actor.cpp
fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp
fdbserver/workloads/WriteDuringRead.actor.cpp

We were converting keys, ranges, and selectors into strings before passing them into trace events in numerous places. This had the effect of causing those strings to be escaped by `printable` twice.
This PR fixes some of the locations where this was occurring.

Fix several instances where trace events were double-escaping strings

---

flow/Trace.cpp

A trace event that was too long would log a truncated version of the event. That truncation was done incorrectly and could itself be too long, which could in some cases result in an infinite loop.

Fix possible infinite loop when a trace event is too long

---

fdbserver/ProxyCommitData.actor.h

Backports https://github.com/apple/foundationdb/pull/6486.

(release-7.0) Fix name of `ProxyCommitData::commitLatencyBands` sample

---

fdbclient/ClientKnobs.cpp
fdbclient/ClientKnobs.h
fdbclient/NativeAPI.actor.cpp
fdbrpc/ContinuousSample.h
fdbrpc/TSSComparison.h

TSS Metrics Improvements for 7.1
- Cleaned up tss metrics code
- Fixed ContinuousSample's percentiles to be statistically correct
- Configurable and default larger interval for logging tss metrics
- separate out counts by request type, and only logging latencies if any requests of that type happened
- only logging high percentile latency metrics when enough samples are present for it to be useful in aggregate
Passed 10k simulation tests
Ran local testing to verify behavior. Example new trace log, when only point reads were done:
`<Event Severity="10" Time="1645025119.592454" DateTime="2022-02-16T15:25:19Z" Type="TSSClientMetrics" ID="037402dae0309635" TSSID="c174bfb8d2fe9728" Elapsed="120.005" Internal="1" Requests="692.987 40935.1 86562" StreamComparisons="0 -1 0" SSErrors="0 -1 0" …

TSS Metrics improvements

---

contrib/debug_determinism/debug_determinism.cpp
flow/Platform.actor.cpp

Also detect reading past the end of the infile for debug_determinism tracing

Flush all output streams in flushAndExit

---

fdbserver/workloads/ConflictRange.actor.cpp

Changes to the system keys that happen at the right time could cause the conflict range test to think that a transaction should have failed when it didn't. This PR changes the logic to ignore differences in the system keys.
Passed 10K targeted correctness of the conflict range tests.

Fix bug in conflict range test due to system key changes

---

fdbclient/ManagementAPI.actor.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/SpecialKeySpace.actor.cpp
fdbclient/SpecialKeySpace.actor.h
fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp

A special keys range read can use this hint to limit the amount of reading they do in a range.
This PR also fixes a typo in a function name and moves some comments to avoid weird code formatting effects.

Add support for a limits hint in special keys range reads

---

flowbench/BenchVersionVector.cpp
flowbench/CMakeLists.txt

This one measures cost of "getDelta" calls:
```
./flowbench --benchmark_filter=bench_vv
2022-03-08T22:01:42+00:00
Running ./cbuild_output/bin/flowbench
Run on (32 X 1789.72 MHz CPU s)
CPU Caches:
L1 Data 32 KiB (x16)
L1 Instruction 32 KiB (x16)
L2 Unified 1024 KiB (x16)
L3 Unified 36608 KiB (x1)
Load Average: 0.33, 0.51, 1.05
--------------------------------------------------------------------------------------
Benchmark                            Time             CPU   Iterations UserCounters...
--------------------------------------------------------------------------------------
bench_vv_getdelta/16/1            33.9 ns         33.9 ns     20604111 Tags=16 getDeltaTimes=1 items_per_second=29.514M/s
bench_vv_getdelta/64/1            33.5 ns         33.5 ns     20989482 Tags=64 …
```

Add version vector microbenchmark

---

fdbclient/ClientKnobs.cpp
fdbclient/ClientKnobs.h
fdbclient/VersionVector.h

Changes:
- Introduce a new knob "CLIENT_KNOBS::SEND_ENTIRE_VERSION_VECTOR"
- Send the entire version vector on the read commit version code path (sequencer -> grv proxy and grv proxy -> client) when this knob is set.
Testing: 20220308-204217-sre-9132d04b0a225952. Job report shows a failure in test ApiCorrectnessSwitchover.toml, but the test succeeds locally:
build_output/bin/fdbserver -r simulation --crash -f /root/src/foundationdb/tests/slow/ApiCorrectnessSwitchover.toml -b on -s 642707319
....
0 tests failed.

Version vector prototype: propagate the entire version vector

---

fdbcli/CoordinatorsCommand.actor.cpp

We are splitting by comma https://github.com/apple/foundationdb/blob/402fa4dd9e2151807fc8a89d6471f2da41e41d4a/fdbclient/SpecialKeySpace.actor.cpp#L1686 So when we concatenating, if we use ", ", there will be an extra space, causing hostname parsing error. NetworkAddress happens not to have the same issue because it uses sscanf. https://github.com/apple/foundationdb/blob/402fa4dd9e2151807fc8a89d6471f2da41e41d4a/flow/network.cpp#L119

When storing coordinators string, we should concatenate by comma.

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/CMakeLists.txt
fdbserver/ClusterController.actor.cpp
fdbserver/EncryptKeyProxy.actor.cpp
fdbserver/EncryptKeyProxyInterface.h
fdbserver/SimEncryptVaultProxy.actor.cpp
fdbserver/SimEncryptVaultProxy.actor.h
fdbserver/Status.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp
fdbserver/workloads/UnitTests.actor.cpp

Description
Major changes proposed are:
1. Rename ServerKnob->ENABLE_ENCRYPT_KEY_PROXY to
ServerKnob->ENABLE_ENCRYPTION. Approach simplifies enabling
controlling encyrption code change using a single knob (desirable)
2. Implement EncyrptKeyVaultProxy simulated interface to assist
validating encyrption workflows in simulation runs. The interface
is leveraged to satisfy "encryption keys" lookup which otherwise
gets satisfied by integrating organization preferred Encryption
Key Management solution.
Testing
Unit test to validate the newly added code …

Introduce a simulate EncryptKeyVaultProxy interface

---

fdbclient/VersionVector.h
flow/flat_buffers.h
flow/serialize.h

Introduce setVersionNoCheck() to avoid building a temporary map.
`std::map` is faster than `std::unordered_map` in benchmarks, while `boost::flat_map` beats both.
boost::flat_map is the fastest
bench_vv_getdelta/512/1024     8768606 ns      8768555 ns           80 Tags=512 getDeltaTimes=1024 items_per_second=116.781k/s
bench_vv_getdelta/1024/1024   12051740 ns     12051549 ns           58 Tags=1024 getDeltaTimes=1024 items_per_second=84.9683k/s
std::unordered_map
bench_vv_getdelta/512/1024    43800487 ns     43799915 ns           16 Tags=512 getDeltaTimes=1024 items_per_second=23.379k/s
bench_vv_getdelta/1024/1024   64894719 ns     64893852 ns           11 Tags=1024 getDeltaTimes=1024 items_per_second=15.7796k/s
std::map
bench_vv_getdelta/512/1024    34068779 ns     34068233 ns …

Use boost::flat_map and optimize getDelta/applyDelta

---

fdbclient/StorageServerInterface.cpp
fdbserver/storageserver.actor.cpp

Fix for TSS nightly failure and metrics (SS forgets about its TSS pair on restart) and improvement to debug tracing
Failed 1 test out of 50k, but it's the same as another unrelated failure from the nightly where this failure occurred.

Tss improvement

---

fdbclient/SpecialKeySpace.actor.cpp

Cherry pick https://github.com/apple/foundationdb/pull/6570 to release-7.0
`maxAllowedVerion` was statically initialized with a dependency on `CLIENT_KNOBS`, which is also statically initialized. In some cases these two were constructed in the wrong order and led to a segfault on startup. Fix by deferring initialization of `maxAllowedVerion` into the first call to `advanceVersionCommitActor()`.
Tested by compiling and running fdbcli and fdbserver. Previously both crashed instantly. Now both run normally and print the expected first message. A sample simulation test runs as well. Extensive simulation was not run on this change.

Fix static initialization order for maxAllowedVersion (release-7.0)

---

fdbserver/workloads/ConflictRange.actor.cpp

Backports https://github.com/apple/foundationdb/pull/6562 and https://github.com/apple/foundationdb/pull/6565 to 7.0

Fix bug in conflict range test due to system key changes (7.0)

---

fdbclient/NativeAPI.actor.cpp
fdbserver/storageserver.actor.cpp

Some recent changes updated mapped range requests, but in the process tenant support was removed. This reintroduces tenant support to these requests.

Add tenant support back to mapped range requests

---

fdbserver/DDTeamCollection.actor.cpp
fdbserver/DDTeamCollection.h
fdbserver/TCInfo.actor.cpp
fdbserver/TCInfo.h

This PR solves issue #6325. In function`getTeam()`, if a team is under wiggle but in a paused state because of healthy compliance, this team won't be chosen unless there is no other healthy team. 
Also, added a unit test to verify the correctness.
Pass 100k simulation test.

Deprioritize seleting team in the wiggle paused state

---

fdbserver/TagPartitionedLogSystem.actor.cpp
fdbserver/WorkerInterface.actor.h

On recovery in version vector unicast mode:
* ensure all versions less than or equal to the RV are durable.   The prior algorithm did not guarantee that, which could have created a gap (e.g. sequence v1,v2,v3 ; v1 and v3 recovered, v2 not recovered)
* Replicas must be in the same log group for a version to be considered recovered for that log group. 
* More information [here](https://docs.google.com/document/d/11oR1MOVl6rOhXqaTdLBMzEtsh56en7KAT5wfKRGKM7U/edit)   In section TagPartitionedLogSystem.actor.cpp (recovery path)
Simulation test
20220313-184813-henrylambright-38edfef0e5d536df

logical fixes to recovery algorithm

---

fdbserver/DataDistribution.actor.cpp

The header file is not ordered properly, especially for actorcompiler.h

Fix the includes in DataDistribution.actor.cpp

---

fdbclient/CommitProxyInterface.h
fdbclient/DatabaseContext.h
fdbclient/NativeAPI.actor.cpp
fdbserver/GrvProxyServer.actor.cpp
flow/error_definitions.h
flow/flat_buffers.h

The events that led to the assertion failure are:
1.    Many txn started, some get ReadVersion1, some get ReadVersion2.
1.    Recovery happened.
1.    GRV proxy change detected and the client version cache is cleared.
1.    Old GRV responded with ReadVersion1, and client version cache is updated to ReadVersion1.
1.    A txn starts reading with ReadVersion2, triggering the assertion.
The fix is to throw an error to trigger transaction restart so that a new GRV will update the version cache, validated with previously failed seed: `-f ./foundationdb/tests/slow/DDBalanceAndRemoveStatus.toml -s 559021579 -b on` …

Fix a rare race with version vector cache

---

cmake/Jemalloc.cmake
cmake/jemalloc.patch
flow/FastAlloc.cpp
flow/config.h.cmake

See https://github.com/jemalloc/jemalloc/pull/1924
Before this 4k aligned allocations always got at least 16k usable space. After
this change we can do 4k aligned allocations up to 16k with no fragmentation.

Apply jemalloc fix, and always build jemalloc

---

fdbclient/DatabaseContext.h
fdbrpc/LoadBalance.actor.h
fdbrpc/QueueModel.cpp
fdbrpc/QueueModel.h
fdbrpc/Smoother.h
fdbserver/DataDistribution.actor.h
fdbserver/DataDistributionTracker.actor.cpp
fdbserver/Ratekeeper.actor.cpp
fdbserver/TagThrottler.actor.cpp
fdbserver/TagThrottler.h

The `Smoother::estimate` and `Smoother::time` fields are marked mutable, because updating these fields in `Smoother::update` does not affect the underlying state of the `Smoother` object. This allows `Smoother::smoothTotal`, `Smoother::smoothRate`, and many other methods and object references to be marked `const`.

Mark `Smoother::smooth*` methods `const`

---

fdbserver/StorageCache.actor.cpp
tests/fast/CacheTest.toml

Most added request types assert false, but one is updated to send a `broken_promise` as a workaround to the fact that we do expect some of these requests to go to the storage cache in simulation for now. The `broken_promise` emulates the behavior when the endpoint isn't found, indicating that the requestor should try a different alternative.

Update the storage cache to handle all requests types

---

flow/Arena.cpp

Change assertions to not rely on the first argument being evaluated before the second.

Fix arena size test failure on GCC

---

fdbserver/storageserver.actor.cpp

Calling lower_bound essentially duplicates much of the work already performed
by lastLessOrEqual, so avoid duplicating the work. Passed 10k correctness tests.

Avoid a call to VersionedMap::ViewAtVersion::lower_bound

---

contrib/TestHarness/Program.cs

I think these tests are responsible for the frequent unseed mismatch CI failures recently.

Non-simulated test harness runs don't check the unseed

---

fdbclient/GenericManagementAPI.actor.h
fdbclient/SpecialKeySpace.actor.cpp

Special keys operations often need to access system keys, but setting the option to access system keys within the operation causes the transaction to have system key access for the user as well. Special keys relies on using the native API transaction to avoid needing system key access enabled, but we do now need raw access for tenant reasons. This converts special keys from using system key access to using raw access.

Avoid promoting transactions to have system key access when using special keys

---

cmake/ConfigureCompiler.cmake
cmake/Jemalloc.cmake
contrib/TestHarness/Program.cs
fdbrpc/AsyncFileCached.actor.h
fdbserver/fdbserver.actor.cpp
flow/Deque.h
flow/FastAlloc.cpp
flow/FastAlloc.h

Fix the cmake logic that decides whether or not to link to jemalloc. It was incorrectly linking to jemalloc for sanitizer builds previously.
Also include the filename in the test harness output for tests in the noSim directory.
Also check aligned_alloc for nullptr, and make sure that jemalloc does not have internal fragmentation when requesting fast alloc magazines (since I think we want to make use of that later)

Jemalloc integration fixes

---

fdbclient/ClientKnobCollection.h
fdbclient/IKnobCollection.h
fdbclient/ServerKnobCollection.h
fdbclient/TestKnobCollection.h
fdbserver/CMakeLists.txt
fdbserver/KnobProtectiveGroups.cpp
fdbserver/KnobProtectiveGroups.h
fdbserver/Knobs.h
fdbserver/tester.actor.cpp
fdbserver/workloads/workloads.actor.h
flow/Knobs.cpp
flow/Knobs.h

With this patch, for a given test, it is possible to override the knob values, e.g.
```
[[test]]
[[test.knobs]]
watch_timeout = 999
```
will set CLIENT_KNOBS->WATCH_TIMEOUT in the current test to 999. After the test completes, the knob value will be reverted. 

Allow temporarily changing the knobs during test

---

fdbserver/VersionedBTree.actor.cpp
flow/genericactors.actor.h

Changed a `SignallableActorCollection` to a simple `vector<Future<Void>>` as the semantics of the actor collection aren't needed anymore.
Added generic `Future<T> detach(Future<T>)` which allows futures that will exist for a long time hold a smaller actor that contains the result of a much larger actor to save the larger actor's memory footprint from being held alive long after its actor has finished.

Redwood small memory usage reductions and a small CPU reduction

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/VersionedBTree.actor.cpp

Currently the remap cleanup window knob is specified by number of versions, and since commit size can vary, it is hard to deduce how much disk space is used by the remapped pages and the number of entries in the page map (and thus the memory usage). Changing it to by size of total remapped page.  Under the hood the size translates to number of remap queue entries by divide it by page size.

Redwood: config remap cleanup by size instead of versions

---

fdbserver/workloads/TenantManagement.actor.cpp

Setting a tenant subspace in the special keys causes various errors, and having a tenant subspace in the system keys could cause problems with the test depending on the prefix chosen.

Limit tenant subspace to the normal key space

---

flow/SystemMonitor.cpp

This size was missing in three places reporting FastAlloc memory stats.

Added missing 16k magazine size to memory stats.

---

fdbclient/SystemData.cpp

This is a typo from https://github.com/apple/foundationdb/commit/83fa2e2c626bb27ddddaa68fe12fe014a416188a#diff-48d9eb52a8b2837c32fa75fe526faff0949d52a0ca9170276e5731016081e3a5R337

Fix incorrect prefix in storageServerListToTeamIdKey

---

fdbserver/PaxosConfigConsumer.actor.cpp

Move the Promise<QuorumVersion> before the Future vector to let it be destroyed after the vector.
Passed the 1k Valgrind test and 10K correctness
-----------
From nightly Valgrind result
```
Results for test ensemble: 20220322-053356-nightly_valgrind_main-502b143cd34ecf22
Ensemble stopped
devRetryCorrectnessTest valgrind bin/fdbserver -r simulation -f tests/rare/ConfigIncrementWithKills.toml -s 10235636 -b on  --crash --trace_format json
{
"BuggifyEnabled" : "1",
"Command" : "devRetryCorrectnessTest valgrind bin/fdbserver -r simulation -f tests/rare/ConfigIncrementWithKills.toml -s 10235636 -b on  --crash --trace_format json",
"DeterminismCheck" : "0",
"Errors" : [
{
"Severity" : "40",
"Type" : "ValgrindError",
"What" : "Invalid read of size 2"
},
{
"Severity" : "40",
"Type" : …
```

Fix Valgrind error where Promise is already destroyed when actors are being cancelled

---

fdbbackup/FileDecoder.actor.cpp

If the ClearRange mutation happens within the given key prefix space,
previously the mutation is not printed. Fix by checking the prefix range
overlaps with the ClearRange mutation.

Fix decoder for missing ClearRanges

---

fdbserver/ApplyMetadataMutation.cpp

This is used to remove the following error during compiling:
```
/root/src/fdbserver/ApplyMetadataMutation.cpp:174:78: error: private field 'changedTeams' is not used [-Werror,-Wunused-private-field]
std::unordered_map<UID, std::vector<std::pair<ptxn::StorageTeamID, bool>>>* changedTeams = nullptr;
```

Remove unused class private variable

---

fdbserver/CMakeLists.txt
fdbserver/ClusterRecovery.actor.cpp
fdbserver/ClusterRecovery.actor.h
fdbserver/MasterInterface.h
fdbserver/ResolutionBalancer.actor.cpp
fdbserver/ResolutionBalancer.actor.h
fdbserver/masterserver.actor.cpp
fdbserver/workloads/KillRegion.actor.cpp

This revert the behavior done by a recent refactor on master recovery in PR #6191.
This PR fixes #6633
Correctness 20220321-235949-jzhou-d6ddd662e364ebcc passed. I've verified the added `TEST()` line was covered.

Move resolutionBalancing() back to master

---

fdbserver/KeyValueStoreRocksDB.actor.cpp

To understand RocksDB memory usage, we should collect counters from RocksDB instance, as described in [https://github.com/facebook/rocksdb/wiki/Memory-usage-in-RocksDB](https://github.com/facebook/rocksdb/wiki/Memory-usage-in-RocksDB)
Some of the counter we already have. Some of them we need to add.
For block cache, we can add `kBlockCacheUsage` to our propertyStats.
For indexes and filter blocks, we have already monitored it --- `EstimateSstReaderBytes` in our propertyStats.
For memtable, we have it as `AllMemtablesBytes` in our propertyStats.
For blocks pinned by iterators, we could add `kBlockCachePinnedUsage` to our propertyStats.
**Passed Joshua test**
20220323-200456-zhewang-99aa6ca2a65e8a71           compressed=True data_size=29939315 duration=5702184 ended=100000 fail_fast=10 …

Add RocksDB Memory Usage Metrics

---

fdbclient/DatabaseConfiguration.cpp
fdbserver/ClusterRecovery.actor.cpp

- Improve assert diagnostics
- Make overwriteProxiesCount a deterministic function of conf keys

Make overwriteProxiesCount a function of conf keys

---

fdbbackup/FileConverter.h
fdbbackup/FileDecoder.actor.cpp
fdbclient/JSONDoc.h
fdbclient/S3BlobStore.actor.cpp

This causes failures of backup_auth_missing: ErrorDescription="Cannot find
authentication details (such as a password or secret key) for the specified
Backup Container URL"
Correct header with the fix:
```
Request Header: Authorization: AWS XXXSECRET_KEYXXX:+F/GfXKLqd4x1Cb75yux7chK1Co=
```
Wrong header without the fix:
```
Request Header: Authorization: AWS :n4Zuwh75fptP3furmlPVDbwo3VI=
```
This is found by manually running "fdbdecode". I verified the fix works as intended.
Also added `--knob-` option to `fdbdecode` to allow easier debugging, i.e., `--knob_http_request_aws_v4_header 0 --knob_http_verbose_level 4`. …

Fix missing blob access key in credentials

---

fdbserver/DataDistributionQueue.actor.cpp

Follow-on PR to #6178 
Improve cancelling logic in DDQueue to more accurately reflect when a move has started.
This behavior was desired before the previous PR, but is now much more desirable, since the destination limiting causes significantly more moves to spend time in the state where the dataDistributionRelocator actor is started, but startMoveKeys has not yet been called.
Passed 100k correctness.

Better cancelling logic that reflects whether move has actually started

---

fdbserver/ClusterRecovery.actor.cpp
fdbserver/TagPartitionedLogSystem.actor.cpp

- Refactor for readability. 
- Add bug fix lost in previous rebase - do not limit transaction store recovery to a single DC
- Consult number of tLogs per log group affected by transaction for recovery.

refactor unicast recovery

---

flow/flat_buffers.cpp
flow/flat_buffers.h
flow/serialize.h

Extend flat_buffer to support unordered_set (de)serialize
Description
Extend flat_buffer to support unordered_set (de)serialize
Testing

Extend flat_buffer to support unordered_set (de)serialize

---

documentation/sphinx/requirements.txt
fdbserver/CommitProxyServer.actor.cpp
fdbserver/masterserver.actor.cpp

SeedTeam SS need to get all mutations in txn whose version is 1,
otherwise these mutations are lost, because SeedTeam SS would not
know they need to fetch the data from this version until after this
version.
Fixing it by manually adding all mutations in txn V1 to private teams
of SeedTeam SS.
Note: some temporary comments are added for now, to facilitate code review, and will be removed

SeedTeam Storage Server can get mutations in version 1 txn

---

fdbserver/storageserver.actor.cpp

From PR: #6484
Passed Joshua Test:
20220325-170717-zhewang-eee62db9c1bb3215           compressed=True data_size=25343555 duration=5126003 ended=100001 fail_fast=10 max_runs=100000 pass=100001 priority=100 remaining=0 runtime=1:26:57 sanity=False started=100296 stopped=20220325-183414 submitted=20220325-170717 timeout=5400 username=zhewang

Quick fix fetchKey (release-7.0)

---

bindings/c/test/unit/unit_tests.cpp
fdbclient/SpecialKeySpace.actor.cpp

When the end key of a tenant map range read was \xff\xff/management/tenant_map0, the operation would incorrectly return no results. This also adds a unit test that covers this behavior.

Fix bug in tenant map range reads when the end key is outside of the tenant map range

---

fdbclient/WellKnownEndpoints.h

Enforce that WLTOKEN_PROTOCOL_INFO does not change with a static_assert. It's more robust than a comment.

Enforce comment with static assert

---

fdbclient/NativeAPI.actor.cpp

There's a code jump that can happen after
```
results->lastReturnedVersion.set(feedReply.mutations.back().version);
```
when the child actor goes to the parent actor's(_getChangeFeedStreamActor_) catch block.
in particular, where it clears the `results->streams` vector. 
However, as there's no _wait_ there until the next
```state ChangeFeedStreamReply feedReply = waitNext(results->streams[0].getFuture());```
We will have a segfault here.
The fix is to add a _wait_ in this rare case and also add ASSERTIONs to catch unexpected behavior. …

Fix the case where we access the memory after cleaning

---

fdbmonitor/CMakeLists.txt

Don't compile fdbmonitor with thread sanitizer instrumentation, since this
appears to change its behavior (it no longer seems to restart killed
processes). fdbmonitor is single-threaded anyway.
This fixes ctest with tsan for the tests that use fdbmonitor

Don't instrument fdbmonitor with thread sanitizer

---

fdbclient/BlobGranuleCommon.h
fdbclient/BlobGranuleFiles.cpp
fdbclient/SystemData.cpp
fdbclient/SystemData.h
fdbserver/BlobGranuleServerCommon.actor.cpp
fdbserver/BlobGranuleServerCommon.actor.h
fdbserver/BlobWorker.actor.cpp

Add full file size to bg metadata to be forward-compatible with multiplexing multiple logical files across a single blob storage object.
Passed 1k BlobGranule* correctness.

Future-proof blob granules with full file size

---

fdbbackup/FileConverter.actor.cpp
fdbbackup/FileDecoder.actor.cpp
fdbbackup/backup.actor.cpp
fdbclient/BackupAgent.actor.h
fdbclient/BackupContainer.actor.cpp
fdbclient/BackupContainer.h
fdbclient/BackupContainerFileSystem.actor.cpp
fdbclient/BackupContainerFileSystem.h
fdbclient/FileBackupAgent.actor.cpp
fdbclient/RestoreInterface.h
fdbclient/S3BlobStore.actor.cpp
fdbclient/S3BlobStore.h
fdbserver/BlobManager.actor.cpp
fdbserver/BlobWorker.actor.cpp
fdbserver/RestoreController.actor.cpp
fdbserver/RestoreController.actor.h
fdbserver/RestoreLoader.actor.cpp
fdbserver/RestoreLoader.actor.h
fdbserver/RestoreWorkerInterface.actor.h
fdbserver/workloads/AtomicRestore.actor.cpp
fdbserver/workloads/BackupAndParallelRestoreCorrectness.actor.cpp
fdbserver/workloads/BackupCorrectness.actor.cpp
fdbserver/workloads/BackupToBlob.actor.cpp
fdbserver/workloads/BlobGranuleCorrectnessWorkload.actor.cpp
fdbserver/workloads/BlobGranuleVerifier.actor.cpp
fdbserver/workloads/IncrementalBackup.actor.cpp
fdbserver/workloads/RestoreBackup.actor.cpp
fdbserver/workloads/RestoreFromBlob.actor.cpp
fdbserver/workloads/SubmitBackup.actor.cpp

This is the first step to add proxy support in backup/restore. The next step is adding environment variable. The last step will be adding the actual proxy functionality.
20220329-021946-renxuan-e2b29b85ae228248           compressed=True data_size=30760042 duration=5079769 ended=100004 fail_fast=10 max_runs=100000 pass=100004 priority=100 remaining=0 runtime=0:47:50 sanity=False started=100165 stopped=20220329-030736 submitted=20220329-021946 timeout=5400 username=renxuan

Add proxy option to backup and restore params.

---

fdbserver/ptxn/TLogServer.actor.cpp

Fix size calculation in spill by reference

---

bindings/c/test/unit/fdb_api.cpp
bindings/c/test/unit/fdb_api.hpp
fdbcli/TenantCommands.actor.cpp

When using an external client, it's actually the ThreadFuture object (and not
the contained Standalone) that owns the underlying memory. Extend the lifetime
of some ThreadFuture's in TenantCommands.actor.cpp to accommodate this confusing
situation. Ideally we find a better way to deal with this, but this is what we
have right now.
Also call fdb_tenant_destroy in the unit tests.

Fix a few memory issues found by ASAN

---

fdbclient/BackupAgent.actor.h

The Tuple form of IBackupContainer was changed to be incompatible with prior written data.  This fixes it, the packed form is now
`url [, encryptionKeyFile [, proxy]]`
which is backward compatible.  Even when present in the Tuple, encryptionKeyFile and proxy are treated as omitted when their strings are empty.
This passes 3000 tests of specifically `UpgradeAndBackupRestore`.
Bug introduced in #6705 
#6721 includes this PR

Fixed Codec<Reference<IBackupContainer>> backward compatibility bug from #6705

---

fdbmonitor/CMakeLists.txt

It looks like #6698 had the effect of removing _all_ compile options from fdbmonitor, not just -fsanitize=thread. Fix that.

Fix typo from pull request #6698

---

fdbclient/BackupAgent.actor.h
flow/ThreadHelper.actor.h

When using `DEBUG_DETERMINISM` to investigate unseed mismatches it is problematic to have an unordered_map of pointers as the iteration order of the logical objects pointed to will vary across executions.
This refactor removes the unordered map and replaces it with a doubly linked fast allocated list of MultiCallbackHolder objects which provide a place to store the per-MultiCallback index of the callback in each ThreadMultiCallback that holds it.  The first entry of the list is included in ThreadCallback inline.
Experimentally via correctness testing it seems that the common case is at most 1 ThreadMultiCallback holder for a given ThreadCallback.  For this, or up to a several holders this new implementation should be faster.
I ran 20 executions of the `AbortableSingleAssignmentVar` unit …

Remove unordered_map of pointers from ThreadMultiCallback

---

fdbrpc/AsyncFileKAIO.actor.h

Adding read/write/sync latency histograms to `AsyncFileKAIO`. Reusing server knob `DISK_METRIC_LOGGING_INTERVAL` which is for SQLite for the interval for writing out the histogram.
For now the metrics doesn't work for other file types. It would probably be cleaner to make the metrics generic in `IAsyncFile`.

AsyncFileKAIO: add latency histograms

---

documentation/sphinx/source/command-line-interface.rst
fdbcli/fdbcli.actor.cpp

Also adds missing documentation for tenant_mode in one spot.
Resolves #6704 

Fix issues with command completion for exclude and storage_migration_type
