fdbclient/NativeAPI.actor.cpp, fdbserver/storageserver.actor.cpp
=> Fixed a few more change feed bugs

documentation/sphinx/source/release-notes/release-notes-630.rst
=> [7.0] Update release notes for 6.3.23

documentation/sphinx/source/release-notes/release-notes-630.rst
=> [6.3] Update release notes for 6.3.23

fdbserver/Coordination.actor.cpp
1. Coordinator should only reply client data if it's valid. Because when a coordinator restarts or newly joins a cluster, a client trying to connect to it may already have client data, while the coordinator doesn't. In this case, the coordinator should not reply empty client data.
2. Coordinator should reply clientInfo when it changes. This bug is introduced in #5231.
20211210-220423-renxuan-2cc36e183e4384a7
=> Fix 2 coordinator bugs.

bindings/c/CMakeLists.txt, contrib/pkg_tester/__snapshots__/test_fdb_pkgs.ambr, contrib/pkg_tester/test_fdb_pkgs.py
Tested by compiling and then using `execstack -q` to see if the stack is executable or not
Closes #6119 
=> Link libfdb_c with `-z noexecstack`

cmake/InstallLayout.cmake, packaging/docker/README.md, packaging/docker/build-images.sh
copy packaging/docker to PROJECT_BINARY_DIR (undoing part of #5994),
fetch commit_sha from source_code_directory (don't assume we're in the source tree anymore),
allow custom tag (if a parameter is passed in as $1)
update README.md
=> fix issues with build-images script

CMakeLists.txt
Accidently deleted when cherry-picking.
=> Restore version.txt file

fdbserver/IKeyValueStore.h, fdbserver/KeyValueStoreRocksDB.actor.cpp
=> Add shard metadata mutation related API.

design/transaction-state-store.md
Also explains what is "txsPoppedVersion" and how it is used in recovery.
=> Update txnStateStore doc with new CC initiated recovery

fdbclient/NativeAPI.actor.cpp
=> fix: poppingChangeFeeds did not properly handle broken promise errors

bindings/c/test/mako/mako.c
`mako` benchmark's JSON output was not properly formatted.
This PR fixes the malformed JSON.
=> Fix malformed JSON

fdbserver/BlobGranuleServerCommon.actor.cpp, fdbserver/BlobGranuleServerCommon.actor.h, fdbserver/BlobManager.actor.cpp, fdbserver/BlobWorker.actor.cpp
=> fix: changed loadHistoryFiles to take a database object

fdbclient/NativeAPI.actor.cpp
I cannot seem to figure out why LSAN is reporting this, but if it is a
real leak than it's only a few bytes. Better to have the ASAN tests
actually passing IMO.
=> Suppress a small leak that LSAN is reporting

fdbserver/ptxn/test/Driver.h, fdbserver/ptxn/test/TestTLogServer.actor.cpp
Remove duplicate code
follow up PR of https://github.com/apple/foundationdb/pull/6222
=> Refactor TLog test

fdbserver/IKeyValueStore.h, fdbserver/KeyValueStoreRocksDB.actor.cpp
=> Implement get*Mutation interface.

bindings/java/CMakeLists.txt, bindings/java/JavaWorkload.cpp, bindings/java/fdbJNI.cpp, bindings/java/src/main/com/apple/foundationdb/FutureResults.java
This will help ensure that native java functions are implemented with
the right type. Also fix some that were the wrong type.
=> Build native headers for jni

fdbserver/BlobManager.actor.cpp
=> fix: do not submit assignments if the worker has already been removed

bindings/c/test/mako/mako.c
... so shells without pseudo-terminals see realtime progress, such as when output is being redirected to a log file.
=> Set stdout to line buffered in mako

fdbclient/FDBTypes.h, fdbserver/storageserver.actor.cpp
=> Added storage engine metrics in SS.

documentation/sphinx/source/backups.rst, fdbbackup/backup.actor.cpp
This resolves https://github.com/apple/foundationdb/issues/6153.
=> Add `fdbbackup tags` command

fdbclient/DatabaseBackupAgent.actor.cpp
=> Correct the JSON path to check DB lock status while switching over DR cluster

fdbserver/ptxn/test/TestTLogServer.actor.cpp
With random group to tlog assignment, it's possible that a tlog doesn't have
any group assigned.
This fix was not included in #6269, because I forgot to push the commit. Correctness was done in that PR.
=> Fix another unit test failure

fdbclient/ServerKnobs.cpp
enable unicast in version vector
=> enable unicast in version vector branch

fdbclient/CommitTransaction.h, fdbclient/ServerKnobs.cpp, fdbserver/KeyValueStoreRocksDB.actor.cpp, fdbserver/storageserver.actor.cpp
=> Add shard related private mutations.

fdbserver/LogSystem.cpp, fdbserver/LogSystem.h
The variable name means exactly the opposite, thus is changed.
=> Rename isEmptyMessage to messagesWritten

contrib/TestHarness/CMakeLists.txt, contrib/TestHarness/Program.cs, contrib/TestHarness/VersionInfo.cs.cmake
This way editors/tools will understand that it's a c sharp file
=> Move generated part of Program.cs to its own file

bindings/go/CMakeLists.txt, bindings/go/src/fdb/fdb_test.go, bindings/go/src/fdb/range.go, bindings/go/src/fdb/snapshot.go, bindings/go/src/fdb/transaction.go, cmake/AddFdbTest.cmake
Also arrange for ctest to run the existing go tests, and add a test.
Closes #6265 
=> Allow access to transaction options through a go `ReadTransaction` interface

cmake/FDBComponents.cmake
Skip documentation build on APPLE machines. 
- [✅] The PR has a description, explaining both the problem and the solution.
=> skip documentation build on Apple machines

fdbcli/ConfigureCommand.actor.cpp, fdbclient/ManagementAPI.actor.cpp
This PR some name mismatches in the error message.
=> change storage_migration_mode to storage_migration_type

fdbcli/CoordinatorsCommand.actor.cpp, fdbcli/fdbcli.actor.cpp, fdbclient/AutoPublicAddress.cpp, fdbclient/CoordinationInterface.h, fdbclient/MonitorLeader.actor.cpp, fdbclient/MonitorLeader.h, fdbclient/NativeAPI.actor.cpp, fdbserver/CoordinatedState.actor.cpp, fdbserver/Coordination.actor.cpp, fdbserver/QuietDatabase.actor.cpp, fdbserver/SimulatedCluster.actor.cpp, fdbserver/fdbserver.actor.cpp, fdbserver/worker.actor.cpp, fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp
20220222-192324-renxuan-e1c56850272b67fc           compressed=True data_size=28990781 duration=5741135 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:57:58 sanity=False started=100156 stopped=20220222-202122 submitted=20220222-192324 timeout=5400 username=renxuan
=> Turn on hostname logic.

fdbcli/CoordinatorsCommand.actor.cpp, fdbclient/CoordinationInterface.h, fdbclient/ManagementAPI.actor.cpp, fdbclient/ManagementAPI.actor.h, fdbclient/MonitorLeader.actor.cpp, fdbclient/SpecialKeySpace.actor.cpp, fdbclient/StatusClient.actor.cpp, fdbserver/ClusterController.actor.cpp, fdbserver/ClusterRecovery.actor.cpp, flow/network.cpp, flow/network.h
20220225-061451-renxuan-416d575fa270313d           compressed=True data_size=29103852 duration=5722157 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:45:17 sanity=False started=100139 stopped=20220225-070008 submitted=20220225-061451 timeout=5400 username=renxuan
=> Support hostname in coordinators commands.

flow/Platform.actor.cpp
Some Windows specific code is messed by refactoring done by #6449
=> Fix Windows build broken by #6449

documentation/sphinx/source/release-notes/release-notes-630.rst
=> Update 6.3.24 release notes

bindings/c/test/mako/mako.c
Fix an issue in mako where the stats process would hang if the worker process
was unable to open a file.  Previously, the worker process would segfault when
trying to dereference a null FILE* and never increment the stopcount variable
in shared memory. Now we check for a null FILE* and increment stopcount when
the worker process stops regardless of success or failure.
=> Account for possibility that fopen might fail in mako

fdbserver/VersionedBTree.actor.cpp, flow/flat_buffers.h
Fix two minor issues discovered while trying to use _GLIBCXX_DEBUG to track down nondeterminism.
=> Fix minor bugs turned up by _GLIBCXX_DEBUG

documentation/sphinx/source/release-notes/release-notes-630.rst
=> [Release 6.3] Update 6.3.24 release notes

fdbserver/TLogServer.actor.cpp
=> Fix tLogServer.actor.cpp

cmake/CompileBoost.cmake, cmake/CompileRocksDB.cmake, cmake/FDBComponents.cmake, cmake/Finduring.cmake, fdbclient/FDBTypes.h, fdbserver/CMakeLists.txt, fdbserver/KeyValueStoreRocksDB.actor.cpp, fdbserver/SimulatedCluster.actor.cpp, fdbserver/storageserver.actor.cpp, tests/noSim/KeyValueStoreRocksDBTest.toml
=> Logging and bug fixes

documentation/sphinx/source/release-notes/release-notes-630.rst
=> [release 7.0] Update 6.3.24 release notes

bindings/c/test/mako/mako.c, bindings/c/test/txn_size_test.c, fdbcli/AdvanceVersionCommand.actor.cpp, fdbcli/ChangeFeedCommand.actor.cpp
This fixes https://github.com/apple/foundationdb/pull/6148#issuecomment-1054575608.
=> Use PRId64 and PRIu64 to replace lld and llu.

flow/Error.cpp
This defines a macro that can be enabled to enable trace logging for a configurable set of errors. Anytime the error is created, it will log a backtrace of that error.
=> Add a mechanism to enable error backtrace logging for select errors

fdbserver/ptxn/TLogServer.actor.cpp, fdbserver/ptxn/test/TestTLogServer.actor.cpp
Previously only works for spill-by-value.
20220224-173000-haofu-02eca54504444d1a
20220228-171339-haofu-57b96f4598931a17
20220301-005519-haofu-d389bf0c8bc28e25
=> Partitioned TLog to support peeking from disk for spill-by-ref

fdbserver/MoveKeys.actor.cpp
=> Fix corner case when there is only 1 SS

fdbserver/MoveKeys.actor.cpp
=> Assert seed team with stronger assertion

fdbserver/KeyValueStoreRocksDB.actor.cpp
=> Update error type for timeouts.

fdbserver/workloads/ConflictRange.actor.cpp
An update to https://github.com/apple/foundationdb/pull/6562
=> Apply stricter condition for special keys check

cmake/Jemalloc.cmake, fdbrpc/AsyncFileCached.actor.cpp, fdbrpc/AsyncFileCached.actor.h, flow/FastAlloc.h
=> Use jemalloc for SQLite/Redwood page cache allocation

fdbrpc/CMakeLists.txt, flow/CMakeLists.txt, flow/StreamCipher.h
Add missed encryption files on Windows
=> Enable encryption for Windows

bindings/c/test/workloads/SimpleWorkload.cpp, bindings/c/test/workloads/workloads.cpp, fdbserver/BackupProgress.actor.h, fdbserver/ProxyCommitData.actor.h, fdbserver/RestoreController.actor.h, flow/ArgParseUtil.h, flow/BooleanParam.h, flow/folly_memcpy.h
=> Fix file names in copyright headers

fdbclient/NativeAPI.actor.cpp
Also avoid using `.toString()` in trace event details and rename (and move) a couple variables.
=> Fix merge conflict between tenants and checkpointing API

fdbserver/ptxn/TLogServer.actor.cpp
=> [PTXN] Peek ignores invalidversion. It treats -1 as end version and never returns any data.

fdbserver/ptxn/TLogPeekCursor.actor.cpp, fdbserver/ptxn/test/FakeTLog.actor.cpp
EndVersion from last peek is exclusive.
=> [PTXN] Peek begin version is greater than 1

fdbserver/ptxn/test/FakeTLog.actor.cpp
=> Fix format

fdbserver/storageserver.actor.cpp
**Problem:**
When the versions of src SS and dest SS diverge much, the fetchKey repeatedly retries. 
Since the retrials are in lock area, it blocks following fetchKeys and it makes the load balance slow, where many fetchKeys can be blocked, and finally overwhelming the system. Experimentally, this cannot be healed by RateKeeper.
Essentially, the retrials are waiting for the healing of the version lag between the SSes --- say **Lag Healing Period**.
**How to reproduce:**
(1) Using YCSB with very high traffic and use RocksDB.
(2) Manually shut down several SSes.
(3) You should see that many SSes ends due to io_timeout/1521 (A disk IO operation failed to complete in a timely manner) and `FetchKeyTooLong Duration` becomes arbitrarily large and finally Ratekeeper throttles input rate down to …
=> Quick fix fetchKeys

documentation/sphinx/source/index.rst, documentation/sphinx/source/monitored-metrics.rst
This page contains a description of suggested alerts and dashboard graphs to have to support a production FDB cluster.
(Credit to AJ for the actual text.)
Screenshot of the rendered page:
=> [doc] Add "Monitored Metrics" page to the docs.

fdbclient/SystemData.cpp, fdbclient/SystemData.h, fdbserver/ApplyMetadataMutation.cpp, fdbserver/TLogGroup.actor.cpp, fdbserver/masterserver.actor.cpp
It is not useful for now as it the mapping is hash based.
20220315-230615-haofu-d48243b86b98842a
=> Delete team to TLogGroup mapping from ptxn metadata

fdbserver/ApplyMetadataMutation.cpp
For a mutation that has SS to teams mapping metadata change,
it has to be persisted in txnStateStore, moreover, the SS
being changed also needs to be notified.
=> Persist SS to teams info in txnStateStore then notify SS private team

fdbclient/StorageCheckpoint.h
=> Fixed uninitialized member issue.

fdbcli/ThrottleCommand.actor.cpp, fdbclient/TagThrottle.actor.cpp, fdbclient/TagThrottle.actor.h, fdbserver/workloads/WriteTagThrottling.actor.cpp
This fixes the bug found in https://github.com/apple/foundationdb/issues/6573.
=> Fix `fdbcli` output for unthrottling tag

fdbserver/CommitProxyServer.actor.cpp
This fixes a bug found by antithesis.
If we reply to the final txnStateRequest before initializing the txnStateStore, we can receive the recovery transaction and attempt to access the txnStateStore before it is ready.
=> Do not reply to a txnStateRequest for the final sequence unless we have processes the txnStateStore

fdbclient/JsonBuilder.cpp, fdbclient/VersionedMap.cpp, fdbserver/FDBExecHelper.actor.cpp, fdbserver/KeyValueStoreRocksDB.actor.cpp, fdbserver/SigStack.cpp, fdbserver/workloads/Cache.actor.cpp, fdbserver/workloads/Mako.actor.cpp, fdbserver/workloads/SnapTest.actor.cpp, fdbserver/workloads/SuspendProcesses.actor.cpp, fdbserver/workloads/TriggerRecovery.actor.cpp, flow/IThreadPoolTest.actor.cpp
=> Add missing copyright headers

fdbserver/Status.actor.cpp
According to the FIXME, the code blocks can be removed to simplify the code.
=> remove some fixme in workload status fetcher

bindings/bindingtester/bindingtester.py, bindings/bindingtester/known_testers.py, bindings/bindingtester/spec/bindingApiTester.md, bindings/bindingtester/spec/tenantTester.md, bindings/bindingtester/tests/api.py, contrib/Joshua/scripts/localClusterStart.sh
This includes the spec and the ability to generate tenant tests. Implementations of the tester in Python and Java will come in the respective bindings updates.
=> Tenant binding tester support

documentation/sphinx/source/backups.rst
=> Add backup documentation to select between v2 and v4 signature protocol.

documentation/sphinx/requirements.txt
use fixed version for Jinja2 dependency in documentation
=> used fixed Jinja2 version for documentation

documentation/sphinx/requirements.txt
Cherry-pick #6676,
fix the Jinja2 version for documentation.
=> cherry-pick pr#6676, fix Jinja2 verion for documentation

tests/fast/BlobGranuleVerifyAtomicOps.toml, tests/fast/BlobGranuleVerifyCycle.toml, tests/fast/BlobGranuleVerifySmall.toml, tests/fast/BlobGranuleVerifySmallClean.toml, tests/slow/BlobGranuleCorrectness.toml, tests/slow/BlobGranuleCorrectnessClean.toml, tests/slow/BlobGranuleVerifyBalance.toml, tests/slow/BlobGranuleVerifyBalanceClean.toml, tests/slow/BlobGranuleVerifyLarge.toml, tests/slow/BlobGranuleVerifyLargeClean.toml
Disable rocks in blob granule tests
=> Disabling rocks in blob granule tests

documentation/tutorial/tutorial.actor.cpp
=> Fix typo in SimpleKeyValueStoreInterface class name

bindings/c/foundationdb/fdb_c.h, bindings/c/test/unit/unit_tests.cpp, fdbclient/ThreadSafeTransaction.cpp
Adding unit tests for blob granule functions
=> Adding Blob Granule Client C Unit Tests

design/encryption-data-at-rest.md
Patch details FDB Encryption data at-rest design documentation
=> FDB Encryption data at-rest design documentation

fdbclient/StorageServerInterface.h, fdbserver/BlobManager.actor.cpp, fdbserver/storageserver.actor.cpp
Fixes to copy-pasted file identifiers, and a couple new metrics
=> misc bg fixes

fdbclient/NativeAPI.actor.cpp, fdbserver/BlobManager.actor.cpp, fdbserver/BlobWorker.actor.cpp
Adding useful trace events for debugging blob granule state
=> Adding useful debugging trace events

fdbserver/KeyValueStoreRocksDB.actor.cpp
Integration of read iterator pool changes to rocksdb shards.
Simulation with 500 tests passed with 485 tests.
=> Integration of read iterator pool changes to rocksdb shards.

bindings/bindingtester/known_testers.py, bindings/java/CMakeLists.txt, bindings/java/fdbJNI.cpp, bindings/java/src/main/com/apple/foundationdb/Database.java, bindings/java/src/main/com/apple/foundationdb/FDBDatabase.java, bindings/java/src/main/com/apple/foundationdb/FDBTenant.java, bindings/java/src/main/com/apple/foundationdb/Tenant.java, bindings/java/src/main/com/apple/foundationdb/TenantManagement.java, bindings/java/src/test/com/apple/foundationdb/test/AsyncStackTester.java, bindings/java/src/test/com/apple/foundationdb/test/Context.java, bindings/java/src/test/com/apple/foundationdb/test/Instruction.java, bindings/java/src/test/com/apple/foundationdb/test/StackOperation.java, bindings/java/src/test/com/apple/foundationdb/test/StackTester.java
This adds support for tenants to the Python bindings. It depends on the https://github.com/apple/foundationdb/pull/6642.
=> Java support for tenants

documentation/sphinx/source/client-design.rst, documentation/sphinx/source/developer-guide.rst, documentation/sphinx/source/tenants.rst
This adds a new document to our documentation with some basic info about the experimental tenants feature.
=> Add some basic documentation for tenants

bindings/java/src/main/com/apple/foundationdb/Database.java, documentation/sphinx/source/api-python.rst
This clarifies the behavior of opening a tenant in the documentation.
=> Add a note that opening a tenant does not check whether that tenant exists in the cluster

fdbserver/BlobManager.actor.cpp
Passes 10k BGCorrectness
With 1MB target size:
```
Uniform insert workload:
Type  |  Count  |    Average  |        Min  |        Max 
-------------------------------------------------------------
Snapshot  |    190  |  964.09 KB  |   48.00  B  |    1.83 MB
Delta  |   1479  |   59.21 KB  |   54.24 KB  |   60.51 KB
Splitting up existing database:
Type  |  Count  |    Average  |        Min  |        Max
-------------------------------------------------------------
Snapshot  |     39  |    1.06 MB  |  712.59 KB  |    1.62 MB
``` …
=> Better split sizing in blob manager

fdbserver/RemoteIKeyValueStore.actor.h
=> Fix the bug where use the IKVS pointer after it's cleaned

fdbrpc/SimExternalConnection.actor.cpp, fdbrpc/SimExternalConnection.h, fdbrpc/sim2.actor.cpp, flow/Net2.actor.cpp, flow/network.cpp, flow/network.h
20220404-003452-renxuan-e812ba36464eab63           compressed=True data_size=30960099 duration=4742187 ended=100000 fail=2 fail_fast=10 max_runs=100000 pass=99998 priority=100 remaining=0 runtime=1:01:04 sanity=False started=101102 stopped=20220404-013556 submitted=20220404-003452 timeout=5400 username=renxuan
=> Add DNS cache.

fdbclient/BlobWorkerCommon.h, fdbclient/ServerKnobs.cpp, fdbclient/ServerKnobs.h, fdbserver/BlobManager.actor.cpp, fdbserver/BlobWorker.actor.cpp, fdbserver/storageserver.actor.cpp
Fixing some metrics and operational improvements.
Passes 10k BlobGranule* correctness tests.
=> misc bg operational fixes and improvements

fdbserver/workloads/BlobGranuleVerifier.actor.cpp
=> fix: do not use a RYW transaction for a versionstamp because of randomize API version

flow/Arena.cpp, flow/Tracing.actor.cpp
=> Allocate at least sizeof(ArenaBlock) for an ArenaBlock

fdbserver/CommitProxyServer.actor.cpp, fdbserver/Resolver.actor.cpp
=> Fix bug about updating storageServerToTeamIdKey

documentation/sphinx/source/release-notes/release-notes-710.rst.txt
=> Add release notes template for 7.1.

documentation/sphinx/source/release-notes/release-notes-700.rst, documentation/sphinx/source/release-notes/release-notes-710.rst
=> Add release notes for grv cache in 7.1

documentation/sphinx/source/release-notes/release-notes-710.rst.txt
Add a note in regards to deprecating support for OpenTracing traces, in support of OpenTelemetry tracing which will be enabled in a future release.
=> OpenTracing deprecation notice.

fdbserver/KeyValueStoreRocksDB.actor.cpp
Histogram is a nice tool to let us understand the tail of latency.
However, the current implementation has data race issue when multiple read/write threads of RocksDB concurrently sample latency.
This is because histogram assumes a single-thread execution of the code.
However, a RocksDB KV store has multiple threads that can concurrently updates the histogram.
This PR fix this data race issue by using ThreadReturnPromiseStream to update the histogram in the main thread.
Note that ThreadReturnPromiseStream is thread-safe. …
=> Fix data race issue when multithreaded RocksDB store using histogram

fdbserver/TLogServer.actor.cpp
=> Check pseudo locality before pop

fdbrpc/HealthMonitor.actor.cpp
20220407-202751-zhewu_fix-48f26ca7c2412f0d
=> Fix valgrind error in HealthMonitor

fdbserver/ptxn/TLogServer.actor.cpp
In corner cases, a version can be read from memory and then be
read from disk again, since we serialize data in disk first,
we need to de-dup when serialize data in memory.
When spill by value, each version as a key, and data as value.
When spill by reference, not each version is present as a key,
because multiple versions can be combined, in this case key
will be the last version
spill by value: https://github.com/apple/foundationdb/blame/partitioned-txns/fdbserver/ptxn/TLogServer.actor.cpp#L2558-L2566
spill by ref: https://github.com/apple/foundationdb/blame/partitioned-txns/fdbserver/ptxn/TLogServer.actor.cpp#L2590-L2592 and https://github.com/apple/foundationdb/blame/partitioned-txns/fdbserver/ptxn/TLogServer.actor.cpp#L2608-L2610
The general guidelines can be …
=> Fix TLogPeek duplicate versions read from disk

bindings/c/fdb_c.cpp, bindings/c/foundationdb/fdb_c.h, bindings/c/test/unit/fdb_api.cpp, bindings/c/test/unit/fdb_api.hpp, bindings/c/test/unit/unit_tests.cpp, fdbclient/DatabaseContext.h, fdbclient/IClientApi.h, fdbclient/MultiVersionTransaction.actor.cpp, fdbclient/MultiVersionTransaction.h, fdbclient/NativeAPI.actor.cpp, fdbclient/SystemData.cpp, fdbclient/SystemData.h, fdbclient/ThreadSafeTransaction.cpp, fdbclient/ThreadSafeTransaction.h, fdbserver/BlobManager.actor.cpp, fdbserver/BlobWorker.actor.cpp, fdbserver/workloads/BlobGranuleVerifier.actor.cpp
=> Renaming bg prune to purge, and adding a C api and unit test for it

flow/Tracing.actor.cpp
These were some improvements @sfc-gh-anoyes and I discussed. Primarily around removing the need to calculate string length in test routines before reading strings, we've moved that into `readMPString` here. Also removed use of strcmp.
=> Simplify MessagePack string decoding logic.

fdbclient/MonitorLeader.actor.cpp, fdbrpc/genericactors.actor.h, fdbserver/ClusterController.actor.cpp, fdbserver/ConfigFollowerInterface.cpp, fdbserver/ConfigFollowerInterface.h, flow/Hostname.actor.cpp, flow/Hostname.h
Plus a few hostname fixes/improvements.
20220408-054854-renxuan-8aeebf962480c0dc           compressed=True data_size=31048558 duration=5463128 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:50:48 sanity=False started=100194 stopped=20220408-063942 submitted=20220408-054854 timeout=5400 username=renxuan
=> Simplify the isCoordinator check in registerWorker.

fdbclient/StorageServerInterface.h
=> Introduced fetchCheckpointKeyValues API in StorageServerInterface.

packaging/deb/builddebs.sh, packaging/msi/FDBInstaller.wxs, packaging/osx/buildpkg.sh, packaging/rpm/buildrpms.sh
Backport fixes for the client packages: https://github.com/apple/foundationdb/pull/6823
=> Backport client fix

fdbserver/storageserver.actor.cpp
Don't need to track private team ID in storageTeamIDs, since we know that the private Team ID is the SSID.
This makes it easier to differentiate private team from other teams in storageTeamIDs.
20220412-053821-zhewu_6836-c6282da3207620de        compressed=True data_size=30653730 duration=5045233 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:56:57 sanity=False started=100267 stopped=20220412-063518 submitted=20220412-053821 timeout=5400 username=zhewu_6836
=> Change how SS tracks private team ID

fdbserver/TagPartitionedLogSystem.actor.cpp
When replication factor * group number is smaller than tlog size, don't initialize tlogs if they are not used.
Also fix few minor bugs in the TLog initialization.
20220412-044916-zhewu_6833-a99f65d1223acba0        compressed=True data_size=30649325 duration=5840987 ended=100002 fail_fast=10 max_runs=100000 pass=100002 priority=100 remaining=0 runtime=1:02:47 sanity=False started=100045 stopped=20220412-055203 submitted=20220412-044916 timeout=5400 username=zhewu_6833
=> Do not initialize unused TLogs

fdbserver/KeyValueStoreRocksDB.actor.cpp
Address Comments in #6766
Passed Joshua Test with RocksDB off: 
20220413-185753-zhewang-2346a70618a9dffd           compressed=True data_size=31349652 duration=4960602 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:56:24 sanity=False started=100105 stopped=20220413-195417 submitted=20220413-185753 timeout=5400 username=zhewang
Passed Joshua Test with RocksDB on, except for known failures (FuzzApiCorrectnessClean.toml and FuzzApiCorrectness.toml):
20220412-020643-zhewang-af33f6da0e2fe0a6           compressed=True data_size=31351141 duration=5151659 ended=100000 fail=2 fail_fast=10 max_runs=100000 pass=99998 priority=100 remaining=0 runtime=0:49:55 sanity=False started=100374 stopped=20220412-025638 submitted=20220412-020643 timeout=5400 …
=> Address Comments in #6766

fdbserver/LogRouter.actor.cpp
There is a bug in how a log router handles streaming read:
* Log router has a `logRouterPeekStream` actor A running.
* Remote tlog detects some problem and starts another streaming connection (maybe just reuse the connection?)
* Log router now has a new `logRouterPeekStream` actor B running.
* B runs and found that popped version > reqBegin, so `LogRouterPeekPopped` . This is because A is still running and changed the popped version.
* A ends with `TLogPeekStreamEnd operation_obsolete`
* B become stuck at `wait(req.reply.onReady() && store(reply.rep, future)`, because the future was sent `Never()`.
As a result, the remote tlog can no longer retrieve data from this log router.
Fix by killing the `logRouterPeekStream` actor B.
To reproduce the error, use clang, commit c3c8511e1, seed …
=> Fix stuck PeekStream actor at log routers

fdbserver/workloads/TenantManagement.actor.cpp
This avoids problems when the storage server is buggified to hold much less than 5s worth of versions in memory. This PR also fixes some variable shadowing issues.
Passed 10K targeted correctness tests of the tenant management workload.
=> The tenant deletion test now deletes multiple tenants concurrently rather than serially

fdbserver/LogRouter.actor.cpp
Cherry-pick #6869
There is a bug in how a log router handles streaming read:
* Log router has a `logRouterPeekStream` actor A running.
* Remote tlog detects some problem and starts another streaming connection (maybe just reuse the connection?)
* Log router now has a new `logRouterPeekStream` actor B running.
* B runs and found that popped version > reqBegin, so `LogRouterPeekPopped` . This is because A is still running and changed the popped version.
* A ends with `TLogPeekStreamEnd operation_obsolete`
* B become stuck at `wait(req.reply.onReady() && store(reply.rep, future)`, because the future was sent `Never()`.
As a result, the remote tlog can no longer retrieve data from this log router.
Fix by killing the `logRouterPeekStream` B.
100k tests 20220415-183218-jzhou-ff18f4b741c24170 …
=> 7.1 Cherry-pick: Fix stuck PeekStream actor at log routers

bindings/c/CMakeLists.txt, tests/TestRunner/upgrade_test.py
=> Disable end-to-end upgrade tests for non-x86_64 platforms

fdbserver/OldTLogServer_6_0.actor.cpp, fdbserver/OldTLogServer_6_2.actor.cpp, fdbserver/TLogServer.actor.cpp
=> fix: pops which were ignored during a snapshot would not be replayed properly

bindings/c/test/mako/mako.c, fdbrpc/FlowTransport.actor.cpp, fdbserver/FDBExecHelper.actor.cpp, fdbserver/fdbserver.actor.cpp
some compile error:
```
/home/decster/projects/database/foundationdb/fdbserver/fdbserver.actor.cpp:520:24: error: format not a string literal and no format arguments [-Werror=format-security]
520 |   printf(result.c_str());
|                        ^
/home/decster/projects/database/foundationdb/fdbserver/fdbserver.actor.cpp:543:23: error: format not a string literal and no format arguments [-Werror=format-security]
543 |  printf(result.c_str());
/home/decster/projects/database/foundationdb/bindings/c/test/mako/mako.c:2135:8: error: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Werror=unused-result]
2135 |        fread(&dataPoints[op][k++], sizeof(uint64_t), 1, f);
|        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ …
```
=> Fix compile errors on ubuntu 20.04

fdbserver/SimulatedCluster.actor.cpp, tests/fast/FuzzApiCorrectness.toml, tests/fast/FuzzApiCorrectnessClean.toml, tests/slow/ApiCorrectnessAtomicRestore.toml, tests/slow/WriteDuringReadAtomicRestore.toml
=> Disable tests in Rocks.

fdbserver/workloads/TenantManagement.actor.cpp
This is a backport of #6873.
This avoids problems when the storage server is buggified to hold much less than 5s worth of versions in memory. This PR also fixes some variable shadowing issues.
Passed 10K targeted correctness tests of the tenant management workload.
=> The tenant deletion test now deletes multiple tenants concurrently rather than serially (release-7.1)

fdbserver/workloads/TenantManagement.actor.cpp
This is a backport of https://github.com/apple/foundationdb/pull/6873.
This avoids problems when the storage server is buggified to hold much less than 5s worth of versions in memory. This PR also fixes some variable shadowing issues.
Passed 10K targeted correctness tests of the tenant management workload.
=> The tenant deletion test now deletes multiple tenants concurrently rather than serially (snowflake/release-7.1)

documentation/sphinx/source/mr-status-json-schemas.rst.inc, documentation/sphinx/source/perpetual-storage-wiggle.rst, documentation/sphinx/source/release-notes/release-notes-710.rst
=> update release note 710

fdbserver/workloads/GetMappedRange.actor.cpp
Fix https://github.com/apple/foundationdb/issues/6819.
=> Fix GetMappedRange test when rangeResult has more

bindings/c/CMakeLists.txt
Cherry-picks https://github.com/apple/foundationdb/pull/6899 to `release-7.1`
=> Add new c libs to client package (release-7.1)

bindings/c/CMakeLists.txt
Cherry-picks https://github.com/apple/foundationdb/pull/6899 to `snowflake/release-7.1`
=> Add new c libs to client package (snowflake/release-7.1)

tests/TestRunner/upgrade_test.py
Check if the old binaries downloaded by the upgrade tests are not corrupted. If they are corrupted, retry the download several times.
=> Check the hash sum of the dowloaded binaries in the upgrade tests, retry on errors

documentation/sphinx/source/mr-status-json-schemas.rst.inc, documentation/sphinx/source/perpetual-storage-wiggle.rst, documentation/sphinx/source/release-notes/release-notes-710.rst
=> [cherry-pick] update 7.1 release notes

tests/TestRunner/upgrade_test.py
When executing multiple upgrade tests in parallel, they may be downloading the same old binaries into the local cache concurrently, which often leads to the downloaded files getting corrupted. It is fixed by downloading to temporary files first and then replacing the destination file atomically. 
=> Upgrade Tests: Avoid corrupting downloaded files in case of parallel test execution

fdbserver/workloads/GetMappedRange.actor.cpp
=> Fix GetMappedRange test when rangeResult has more [release-7.1]

fdbclient/MultiVersionTransaction.actor.cpp
Tested by running
```
ctest -V -R multiversion
```
after building with `-DUSE_ASAN=ON`
=> Disable leak checks for some tests that intentionally leak

packaging/docker/build-images.sh
=> update build-images.sh to play nice with AWS IMDSv2 (release-7.1)

fdbclient/MonitorLeader.actor.cpp, fdbserver/PaxosConfigConsumer.actor.cpp, fdbserver/worker.actor.cpp
This was found when running joshua on #6998.
=> One place in PaxosConfigConsumer was missed out in #6926.

fdbrpc/LoadBalance.actor.h, fdbserver/ClusterRecovery.actor.cpp, fdbserver/storageserver.actor.cpp, flow/actorcompiler.h
100k 20220430-230847-jzhou-ff0b5ca348987c8b passed.
=> Fix a few IDE build warnings and errors

bindings/bindingtester/spec/bindingApiTester.md
Add `GET_RANGE_SPLIT_POINTS` instruction documentation.
=> docs: add `GET_RANGE_SPLIT_POINTS`

fdbclient/RYWIterator.cpp
There's a test which checks behavior against a reference implementation,
and so the reference implementation needs to be updated as well.
=> Update RYWIterator test to match #6993

fdbserver/VersionedBTree.actor.cpp
..so if any of them failed the shutdown would never complete.
=> Bug fix:  Redwood shutdown would wait for pending IO success 

bindings/java/src/main/com/apple/foundationdb/MappedKeyValue.java
=> implement equals and hashCode in MappedKeyValue

fdbserver/VersionedBTree.actor.cpp
=> Bug fix:  Redwood shutdown would wait for pending IO success (Cherry-pick #7050 to release-7.1)

fdbclient/ClientKnobs.cpp, fdbclient/ServerKnobs.cpp
=> 7.1 cherry-pick: Decreasing MIN_SHARD_BYTES knob

flow/ProtocolVersion.h
=> bump the minInvalidProtocolVersion so that future Snowflake releases can increase a more significant digit

fdbserver/storageserver.actor.cpp
backporting https://github.com/apple/foundationdb/pull/7080
=> Eliminate vector string during mapped key processing(release-7.1)

fdbclient/CoordinationInterface.h, fdbserver/CoordinationInterface.h
New added field should be the last in serializer. #7095 in main.
=> Fix compatibility issue (release-7.1).

packaging/docker/sidecar.py
Backport of the sidecar changes to allow the operator to make use of it in the new version: https://github.com/apple/foundationdb/pull/7082
=> Sidecar add is present

fdbclient/Tuple.cpp, fdbclient/Tuple.h, fdbserver/storageserver.actor.cpp
joshua 20220505-214533-haofu-f0ed5ce76caebf76
=> add appendRaw and subTupleRawString for Tuple

packaging/docker/sidecar.py
Backport of: https://github.com/apple/foundationdb/pull/7103
=> Make use of relpath instead of basepath

packaging/docker/run_ycsb.sh
This is a backport of https://github.com/apple/foundationdb/pull/7097
We need this change in 6.3, where I tested it.
=> Backport ycsb 7.0

fdbbackup/backup.actor.cpp, fdbclient/S3BlobStore.actor.cpp
Only support non-TLS blobs now.
=> HTTP proxy for backup.

fdbrpc/TokenSign.cpp
In order to build with WolfSSL this header is required. I have tested that this builds without errors with an updated docker build image with WolfSSL installed.
=> WolfSSL fix for TokenSign

fdbserver/KeyValueStoreRocksDB.actor.cpp
cherry-pick #7075 
Adding rocksdb throttling counters to trace event.
=> Adding rocksdb throttling counters to trace event.

fdbserver/workloads/FuzzApiCorrectness.actor.cpp
=> Make FuzzApiCorrectness catch special_keys_api_failure()

bindings/c/CMakeLists.txt, bindings/c/test/apitester/TesterTransactionExecutor.cpp, tests/TestRunner/local_cluster.py, tests/TestRunner/upgrade_test.py
Automating a cluster wiggle process on a local cluster. 
Adding two new regression tests:
- Cluster wiggle in the current version
- Upgrading cluster from 7.0 to 7.2 after cluster wiggle
=> Cluster wiggle test

bindings/java/src/integration/com/apple/foundationdb/CycleMultiClientIntegrationTest.java
backporting https://github.com/apple/foundationdb/pull/7100
=> Reduce workload in CycleMultiClientIntegrationTest(release-7.1)

fdbclient/Tenant.h
=> Don't pass nullptr to memcpy

fdbcli/fdbcli.actor.cpp, fdbcli/fdbcli.actor.h
because the current implementation is killing processes one at a time
=> revert "kill" command to previous 7.0 behavior 

fdbrpc/FlowTransport.actor.cpp, flow/serialize.cpp
=> Log a backtrace before throwing serialization_failed

documentation/sphinx/source/release-notes/release-notes-710.rst
Checked the documentation build looks fine.
=> Update release notes 7.1.0 through 7.1.5

documentation/sphinx/source/release-notes/release-notes-710.rst
=> Update release notes 7.1.0 through 7.1.5 [release-7.1]

bindings/c/fdb_c.cpp, bindings/c/foundationdb/fdb_c.h, bindings/c/test/unit/fdb_api.cpp, bindings/c/test/unit/fdb_api.hpp, bindings/c/test/unit/unit_tests.cpp, bindings/java/fdbJNI.cpp, bindings/java/src/integration/com/apple/foundationdb/MappedRangeQueryIntegrationTest.java, bindings/java/src/main/com/apple/foundationdb/FDBTransaction.java, bindings/java/src/main/com/apple/foundationdb/ReadTransaction.java, fdbclient/FDBTypes.h, fdbclient/IClientApi.h, fdbclient/ISingleThreadTransaction.h, fdbclient/MultiVersionTransaction.actor.cpp, fdbclient/MultiVersionTransaction.h, fdbclient/NativeAPI.actor.cpp, fdbclient/NativeAPI.actor.h, fdbclient/PaxosConfigTransaction.h, fdbclient/ReadYourWrites.actor.cpp, fdbclient/ReadYourWrites.h, fdbclient/SimpleConfigTransaction.h, fdbclient/StorageServerInterface.h, fdbclient/ThreadSafeTransaction.cpp, fdbclient/ThreadSafeTransaction.h, fdbserver/storageserver.actor.cpp, fdbserver/workloads/ApiWorkload.h, fdbserver/workloads/GetMappedRange.actor.cpp
backporting https://github.com/apple/foundationdb/pull/7116
=> Optimization: support removing index conditionally(release-7.1)

fdbserver/ClusterRecovery.actor.cpp
=> remove duplicate recoveryCount++

fdbserver/EncryptKeyProxy.actor.cpp, fdbserver/RESTKmsConnector.actor.cpp, fdbserver/workloads/EncryptKeyProxyTest.actor.cpp
Description
Major changes proposed in the patch includes:
1. Update EncryptKeyProxy EncryptBaseCipherKeyId cache to be indexed
using {encryptDomainId, baseCipherId} instead of only 'baseCipherId'
2. Enhance RESTKmsConnector 'error' tag to encapsulate: errorMessage
and errorCode information
Testing
1. Updated EncryptKeyProxy test
2. Updated RESTKmsConnector unit test
=> Update EncryptBaseCipher cache to be index using {baseCipherId, domainId}

fdbserver/storageserver.actor.cpp
=> Fix -Wlogical-op-parentheses warning

bindings/c/test/unit/unit_tests.cpp, fdbserver/workloads/GetMappedRange.actor.cpp
backporting https://github.com/apple/foundationdb/pull/7185
=> Add missing secondary queries tests for index prefetch(release-7.1)

flow/Tracing.actor.cpp
The OTEL receiver does not utilize the parent Trace id, only parent Span id. Essentially the receiver and tracing services rely on trace ids implicitly matching during trace assembly. Therefore, we may remove these 16 bytes in during serialization as they are not used at the receiver, nor forwarded to collector services via OTEL.
Unit tested and correctness tested.
=> Remove parentContext.traceID from MessagePack serialization

fdbserver/storageserver.actor.cpp
No additional testing or description required.
=> Use semicolon for consistency with all other spans.

bindings/java/fdbJNI.cpp, bindings/java/src/integration/com/apple/foundationdb/MappedRangeQueryIntegrationTest.java, bindings/java/src/main/com/apple/foundationdb/FDBTransaction.java, bindings/java/src/main/com/apple/foundationdb/MappedKeyValue.java, bindings/java/src/main/com/apple/foundationdb/MappedRangeQuery.java, bindings/java/src/main/com/apple/foundationdb/MappedRangeResultDirectBufferIterator.java
backporting https://github.com/apple/foundationdb/pull/7186
=> Make java binding work for prefetch match index modes. (releas-7.1)

bindings/python/tests/fdbcli_tests.py, fdbcli/ExpensiveDataCheckCommand.actor.cpp, fdbcli/KillCommand.actor.cpp, fdbcli/SuspendCommand.actor.cpp, fdbcli/fdbcli.actor.cpp, fdbclient/IClientApi.h, fdbclient/NativeAPI.actor.cpp
Cherry-pick #7188 to fix the `kill` `suspend` and `expensive_data_check` commands
In addition, manually tested it's working as expected.
=> Extend the reboot interface to accept comma-delimited string;(snowflake/release-7.1)

fdbserver/storageserver.actor.cpp
=> Explicitly cancel byte sample recovery on SS failure (Cherry-pick #7212 to release-7.1)

fdbserver/storageserver.actor.cpp
=> Explicitly cancel byte sample recovery on SS failure (Cherry-pick #7212 to snowflake/release-7.1)

documentation/sphinx/source/tenants.rst
This configuration key may end up being removed, so we'll remove the documentation of it for now.
=> Remove documentation of the tenant prefix configuration key

fdbserver/TLogServer.actor.cpp, fdbserver/storageserver.actor.cpp
This is a cherry pick of #7236 
=> Cherry pick #7236 to snowflake/release-7.1 (revert #5637)

documentation/sphinx/source/release-notes/release-notes-710.rst
=> Update 7.1.6 and 7.1.7 release notes.

fdbcli/ExcludeCommand.actor.cpp
Fixes: https://github.com/apple/foundationdb/issues/7248 for more details see the issue.
=> Check if all specific processes are excluded

documentation/sphinx/source/backups.rst
=> Add documentation for aws sdk auth

fdbserver/KeyValueStoreRocksDB.actor.cpp
=> Traceevent correction.

fdbclient/CMakeLists.txt, fdbclient/WriteMap.cpp, fdbclient/WriteMap.h
Split the interface and implementation, so adding debugging information
in the code will not trigger a full rebuild.
=> Refactor the WriteMap.h

bindings/flow/tester/Tester.actor.cpp
20220603-131841-haofu-cb3d60fa060f7d72
=> Fix versionstamp in Tester

bindings/java/src/main/com/apple/foundationdb/KeyArrayResult.java
=> Make KeyArrayResult constructor public.

fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
=> Disable rocksdb metrics.

fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
=> [Sharded RocksDB] 3/N Implement functions for range clear.

documentation/sphinx/source/release-notes/release-notes-710.rst
=> Add 7.1.8 and 7.1.9 release notes

fdbkubernetesmonitor/main.go
Closing additional environment file description as soon as read it completely
@brownleej 
=> fix(fdbkubernetesmonitor): unclosed file description

flow/Arena.cpp
Valgrind with FDB_VALGRIND_PRECISE already tracks the accessibility of arena
metadata. Have asan do that as well (to the extent that it can).
=> Make ASAN arena aware

bindings/c/fdb_c.cpp, bindings/c/foundationdb/fdb_c.h, documentation/sphinx/source/administration.rst, documentation/sphinx/source/api-version-upgrade-guide.rst
=> Safely remove fdb_transaction_get_range_and_flat_map

tests/CMakeLists.txt
=> Ignore ShardedRocksDBTest.

fdbclient/Schemas.cpp, fdbserver/DDTeamCollection.actor.cpp, fdbserver/DDTeamCollection.h, fdbserver/DataDistribution.actor.cpp, fdbserver/DataDistribution.actor.h, fdbserver/DataDistributorInterface.h, fdbserver/Status.actor.cpp
This PR fills feature request #6813.
=> Adding paused/running wiggling status to status json and also the last running/paused timestamp

bindings/c/fdb_c.cpp, bindings/c/foundationdb/fdb_c.h, bindings/c/test/unit/fdb_api.cpp, bindings/c/test/unit/fdb_api.hpp, fdbclient/DatabaseContext.h, fdbclient/IClientApi.h, fdbclient/MultiVersionTransaction.actor.cpp, fdbclient/MultiVersionTransaction.h, fdbclient/NativeAPI.actor.cpp, fdbclient/ThreadSafeTransaction.cpp, fdbclient/ThreadSafeTransaction.h, fdbserver/workloads/BlobGranuleCorrectnessWorkload.actor.cpp, fdbserver/workloads/BlobGranuleVerifier.actor.cpp
Added tenant functionality to all blob granule client functions.
Had to expose new ITenant functions for functions that were previously IDatabase functions.
Running BlobGranule* correctness to sanity check.
=> Bg tenant improvements

packaging/docker/Dockerfile
Add openssl for TLS debugging + update the golang version to match the operator version.
=> Add openssl for debugging

packaging/docker/Dockerfile
Backport of https://github.com/apple/foundationdb/pull/6649 for 7.1 release branch.
=> Add openssl for debugging in container image

fdbclient/AsyncTaskThread.h, fdbclient/MultiVersionAssignmentVars.h, fdbclient/MultiVersionTransaction.actor.cpp, fdbclient/ThreadSafeTransaction.cpp, fdbclient/ThreadSafeTransaction.h, fdbrpc/AsyncFileEIO.actor.h, fdbserver/workloads/ExternalWorkload.actor.cpp, fdbserver/workloads/ThreadSafety.actor.cpp, flow/FileTraceLogWriter.cpp, flow/Net2.actor.cpp, flow/ThreadHelper.actor.h, flow/Trace.cpp, flowbench/flowbench.actor.cpp
Cherry pick of #7409 to `snowflake/release-7.1`.
=> Fix undefined behavior from accessing field of uninitialized object (snowflake/release-7.1)

fdbclient/AsyncTaskThread.h, fdbclient/IClientApi.h, fdbclient/MultiVersionAssignmentVars.h, fdbclient/MultiVersionTransaction.actor.cpp, fdbclient/MultiVersionTransaction.h, fdbclient/ThreadSafeTransaction.cpp, fdbclient/ThreadSafeTransaction.h, fdbrpc/AsyncFileEIO.actor.h, fdbserver/workloads/ApiWorkload.h, fdbserver/workloads/ExternalWorkload.actor.cpp, fdbserver/workloads/ThreadSafety.actor.cpp, flow/FileTraceLogWriter.cpp, flow/Net2.actor.cpp, flow/ThreadHelper.actor.h, flow/Trace.cpp, flowbench/flowbench.actor.cpp
Cherry pick of #7409 to `release-7.1`.
=> Fix undefined behavior from accessing field of uninitialized object (release-7.1)

fdbserver/KeyValueStoreRocksDB.actor.cpp
Adding logId to traceevents. This is important especially when we want to see per Rocksdb metrics.
=> Adding logId to traceevents.

documentation/sphinx/source/release-notes/release-notes-710.rst
=> Add 7.1.10, 7.1.11 release notes

documentation/sphinx/source/release-notes/release-notes-710.rst
=> Add 7.1.10, 7.1.11 release notes [release-7.1]

packaging/docker/Dockerfile, packaging/docker/Dockerfile.eks, packaging/docker/build-images.sh
Backport: https://github.com/apple/foundationdb/pull/7415
=> Refactor docker setup for GitHub 71

fdbserver/CommitProxyServer.actor.cpp, fdbserver/Resolver.actor.cpp
=> Remove some unused variables

cmake/InstallLayout.cmake
Revised versioned package format to be consistent with release packages and include git commit hash metadata in RPM query
**New versioned format**
```
foundationdb7.2.0.<buildtime>prerelease-clients-1.versioned.x86_64.rpm
foundationdb7.2.0.<buildtime>prerelease-server-1.versioned.x86_64.rpm
```
**Old versioned format**
```
foundationdb7.2.0.<buildtime>prerelease-server.<short_git_hash>.versioned.x86_64.rpm
foundationdb7.2.0.<buildtime>prerelease-clients.<short_git_hash>.versioned.x86_64.rpm
```
**Tests**
```
foundationdb7.2.0.20220629193414prerelease-clients-1.versioned.x86_64.rpm
foundationdb7.2.0.20220629193414prerelease-server-1.versioned.x86_64.rpm
foundationdb7.2.0_rc1-clients-7.2.0_rc1-1.x86_64.rpm
foundationdb7.2.0_rc1-clients-debuginfo-7.2.0_rc1-1.x86_64.rpm …
```
=> Revise versioned pkg format

fdbclient/CMakeLists.txt, fdbclient/FDBAWSCredentialsProvider.cpp
Removing antipatterns and moving implementation to a cpp file
=> Cleaning up AWS creds

bindings/c/test/apitester/TesterCorrectnessWorkload.cpp
Add getKey as a possible randomOperation in Client API tester workload. 
=> Add getKey support to ApiCorrectnessWorkload

packaging/docker/Dockerfile
Backport: https://github.com/apple/foundationdb/pull/7521
=> Fix permission in Dockerfile

documentation/sphinx/source/release-notes/release-notes-710.rst
=> Add 7.1.12, 7.1.13 release notes

fdbserver/DDTxnProcessor.actor.cpp, fdbserver/DataDistribution.actor.cpp, fdbserver/include/fdbserver/DDTxnProcessor.h
* Move possible circular dependency
* move getDatabaseConfiguration to txnProcessor
=>  [DD Testability] move getDatabaseConfiguration to txnProcessor

fdbclient/FDBTypes.h, fdbserver/storageserver.actor.cpp
=> Add StorageEngine type to StorageMetrics trace events (Cherry-pick #7534 to release-7.1)

fdbkubernetesmonitor/README.md
=> Add docs for how to run the operator with the unified image

documentation/sphinx/source/release-notes/release-notes-710.rst
=> Add 7.1.14 and 7.1.15 release notes

documentation/sphinx/source/release-notes/release-notes-710.rst
=> Add 7.1.14 and 7.1.15 release notes [release-7.1]

fdbserver/worker.actor.cpp
fix: when multiple shared tlogs are restored from disk, do not recruit a new one on the same process until all of the restored ones have shut down
passed 100k correctness
=> Avoid recruiting multiple shared tlogs

fdbserver/DDTxnProcessor.actor.cpp, fdbserver/DataDistribution.actor.cpp, fdbserver/include/fdbserver/DDTxnProcessor.h
refactor the code.
Part of #7568 
=> [DD Testability] move updateReplicaKey to txnProcessor

fdbserver/DDTxnProcessor.actor.cpp, fdbserver/DataDistribution.actor.cpp, fdbserver/include/fdbserver/DDTxnProcessor.h
=> [DD Testability] move waitDataDistributorEnabled to txnProcessor

fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
=> Add KVS physical shard metrics.

fdbclient/FDBTypes.h, fdbserver/storageserver.actor.cpp
=> Add StorageEngine type to StorageMetrics trace events (Cherry-pick #7534 to snowflake/release-7.1)

fdbserver/BlobManager.actor.cpp, fdbserver/BlobWorker.actor.cpp
Polish and first set of improvements discussed for granule merging.
Passes 100k BlobGranule* tests
=> Granule merging improvements

fdbserver/DataDistribution.actor.cpp
=> [DD Testability] create DataDistributor::init() method

fdbserver/KeyValueStoreRocksDB.actor.cpp
Adding rocksdb compression and data size stats.
Test output:
"LevelStats":"Level Files Size(MB)\\x0a--------------------\\x0a  0        2      502\\x0a  1        0        0\\x0a  2        0        0\\x0a  3        0        0\\x0a  4       15      891\\x0a  5       37     2101\\x0a  6      206    12226\\x0a",
"CompressionRatioAtLevel":"0:1.010337,1:-1.000000,2:-1.000000,3:-1.000000,4:1.011170,5:1.013587,6:1.012863,"
=> Adding rocksdb compression and data size stats.

fdbserver/storageserver.actor.cpp
Move code for cleaning up change feeds to a separate function, so that it can be shared by another version of changeServerKeysWithPhysicalShards. This makes the diff in another PR much cleaner.
=> Add cleanUpChangeFeeds().

design/data-distributor-internals.md
=> update data distributor design doc

fdbserver/storageserver.actor.cpp
10k correctness 20220720-000939-jzhou-8ce37fd114553a9c passed.
=> Add getMappedRange latency metrics

fdbserver/storageserver.actor.cpp
Cherrypick #7630 
10k 20220720-005149-jzhou-8c697a550ab3b26c passed.
=> Add getMappedRange latency metrics [release-7.1]

fdbserver/OldTLogServer_6_0.actor.cpp, fdbserver/OldTLogServer_6_2.actor.cpp, fdbserver/TLogServer.actor.cpp
=> [release-7.1] Increase AllTags field length in TLogReady TraceEvent

fdbserver/CommitProxyServer.actor.cpp
A new step after 7.0
20220721-222158-zhewu-commitdebug-a7cb7b4a9b93e6df
=> Add CommitDebug event after Commit Proxy reporting committed version

fdbserver/TagPartitionedLogSystem.actor.cpp
=> [release 7.1] Add TraceEvent for TLog initialization

bindings/java/fdbJNI.cpp, bindings/java/src/main/com/apple/foundationdb/Database.java, bindings/java/src/main/com/apple/foundationdb/FDBDatabase.java
Repeat of #6816 since that somehow didn't get merged into main?
=> Java bindings for BG Purge (#6816)

contrib/crc32/CMakeLists.txt
=> fixup! Let clang accepts crc32_wrapper.c

contrib/ddsketch_calc.py, contrib/ddsketch_compare.py, contrib/ddsketch_conversion.py, contrib/export_graph.py
* Adds ddsketch_calc.py which implements a class for DDSketch related calculations
* Adds ddsketch_conversion.py for quickly computing a bucket index to a value or vice-versa
* Adds ddsketch_compare.py to compute how similar two ddsketch distributions are
* Adds export_graph.py to graph the ddsketch distribution outputted from mako
The arguments for ddsketch_conversion.py are:
`-b, --bucket`: the bucket index that we need to calculate the value from (optional)
`-v, --value`: the value that we need to calculate the bucket index from (optional)
`-e, --error_guarantee`: the error guarantee for ddsketch (optional, default is 0.005)
The arguments for ddsketch_compare.py are:
`--file1`: Path to first ddsketch json
`--file2`: Path to second ddsketch json
`--txn1`: The transaction type to lookup …
=> Add utility scripts for ddsketch

documentation/sphinx/source/mr-status-json-schemas.rst.inc, fdbserver/Status.actor.cpp
Resolving hostname might be blocking.
100k 20220724-234307-jzhou-97d135a11ab860c2 passed.
=> Add timeout during Status generation

fdbserver/storageserver.actor.cpp
=> Fixed compiler warnings.

fdbclient/NativeAPI.actor.cpp, fdbclient/Schemas.cpp, fdbserver/Status.actor.cpp
cherry-pick #7501 and part of 75a90be0
=> Add timeout handler for status fetcher (cherry-pick to snowflake/release-7.1)

tests/fast/BlobGranuleVerifyAtomicOps.toml, tests/fast/BlobGranuleVerifyCycle.toml, tests/fast/BlobGranuleVerifySmall.toml, tests/restarting/from_7.1.0/SnapCycleRestart-1.txt, tests/restarting/from_7.1.0/SnapCycleRestart-2.txt, tests/restarting/from_7.1.0/SnapIncrementalRestore-1.txt, tests/restarting/from_7.1.0/SnapIncrementalRestore-2.txt, tests/restarting/from_7.1.0/SnapTestAttrition-1.txt, tests/restarting/from_7.1.0/SnapTestAttrition-2.txt, tests/restarting/from_7.1.0/SnapTestRestart-1.txt, tests/restarting/from_7.1.0/SnapTestRestart-2.txt, tests/restarting/from_7.1.0/SnapTestSimpleRestart-1.txt, tests/restarting/from_7.1.0/SnapTestSimpleRestart-2.txt, tests/slow/BlobGranuleCorrectness.toml, tests/slow/BlobGranuleCorrectnessClean.toml, tests/slow/BlobGranuleVerifyBalance.toml, tests/slow/BlobGranuleVerifyBalanceClean.toml, tests/slow/BlobGranuleVerifyLarge.toml, tests/slow/BlobGranuleVerifyLargeClean.toml, tests/slow/DiskFailureCycle.toml
=> Disabled unsupported tests.

fdbserver/DataDistribution.actor.cpp
resumeFromDataMoves() must start after resumeFromShards() finishes.
=> Make sure resumeFromDataMoves() starts after resumeFromShards().

fdbclient/NativeAPI.actor.cpp
Fixes #7586 
During a recovery, the cluster provides provisional proxy interfaces for a brief time. When these are sent to the clients, the tenant mode configuration is unknown and defaults to DISABLED. As a result, operations that try to use tenants would fail with an error until the real proxies were recruited.
This PR changes the tenant mode checking logic to allow a tenant transaction if there are no non-provisional proxies. Tenant transactions have also been updated to disallow using the provision proxy option. The result of this is that a tenant transaction may be able to briefly read from the cluster but will fail when it attempts to commit, either because there are no normal proxies or because the read version will be too old. The commit operation also checks the tenant mode …
=> Fix: during recovery, it was possible for tenant operations to briefly fail because the tenant mode was unknown

fdbserver/include/fdbserver/workloads/BulkSetup.actor.h, fdbserver/workloads/SkewedReadWrite.actor.cpp, flow/include/flow/genericactors.actor.h
=> remove runAfter actor

fdbclient/NativeAPI.actor.cpp
=> Add comments explaining the use of the TransactionState tenant() and hasTenant() functions

fdbserver/Status.actor.cpp
=> Fix a crash bug during CC shutdown process (Cherry-pick #7705 to snowflake/release-7.1)

documentation/sphinx/source/release-notes/release-notes-710.rst
=> Add 7.1.16, 7.1.17 release notes

documentation/sphinx/source/release-notes/release-notes-710.rst
=> Add 7.1.16, 7.1.17 release notes [release-7.1]

fdbserver/storageserver.actor.cpp
joshua 20220728-220401-haofu-4308c580378f2c24
=> Add g_traceBatch for prefetch query

fdbcli/BlobRangeCommand.actor.cpp, fdbclient/ClientKnobs.cpp, fdbclient/include/fdbclient/BlobWorkerCommon.h
Added new cli commands and made a couple other tweaks.
Running correctness now for the small changes, manually tested the new cli commands.
=> Adding more blobrange cli commands and a couple other tweaks

fdbserver/DataDistributionQueue.actor.cpp
=> [Read-aware DD] remove duplicate code in BgDDLoadRebalance

fdbserver/storageserver.actor.cpp
backporting https://github.com/apple/foundationdb/pull/7730
=> Add g_traceBatch for prefetch query (release-7.1)

flow/Hostname.actor.cpp, flow/include/flow/network.h, flow/network.cpp
20220729-030411-renxuan-7e4281256c2c161d           compressed=True data_size=35236790 fail_fast=10 max_runs=100000 priority=100 sanity=False submitted=20220729-030411 timeout=5400 username=renxuan
=> Prefer IPv6 in hostname resolving.

flow/Hostname.actor.cpp, flow/network.cpp, flow/network.h
=> Prefer IPv6 in hostname resolving (release-7.1).

fdbserver/storageserver.actor.cpp
=> Retain debug id in prefetch server-server call

fdbserver/storageserver.actor.cpp
=> Fixed ChangeServerKeysContext name issue.

fdbcli/BlobRangeCommand.actor.cpp, fdbserver/BlobManager.actor.cpp
Improved blobrange check cli command and added more metrics for blob manager
Passed 10k BlobGranule* correctness
=> More blob granule operational stuff

fdbserver/storageserver.actor.cpp
=> Clean up empty physical shards in KVS.

fdbclient/SpecialKeySpace.actor.cpp, fdbclient/SpecialKeySpace.actor.h, fdbserver/workloads/ReportConflictingKeys.actor.cpp, fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp
=> Add test coverage for SpecialKeyRangeAsyncImpl::getRange(release-7.1)

fdbserver/BlobWorker.actor.cpp, fdbserver/storageserver.actor.cpp
Assorted bug fixes for change feeds.
Passes 200k BlobGranule* and ChangeFeed* correctness with 1 unrelated failure (#7604)
=> More cf bug fixes

fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
=> Enable RocksDB metrics

fdbclient/SpecialKeySpace.actor.cpp, fdbclient/SpecialKeySpace.actor.h, fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp
=> Add test coverage for SpecialKeyRangeAsyncImpl::getRange (release-7.0)

pull_request_template.md
This will update the pull request template in wording and add some wording aswell, making it easier to read and understand as it can possibly be a little confusing in my opinion.
=> docs(pull_request_template) Update pull_request_template.md

fdbclient/SpecialKeySpace.actor.cpp
=> Write tracing and ALP special key errors as JSON

CONTRIBUTING.md
This will update the wording of the CONTRIBUTING.md file to potentially make it more readable / correct in my personal opinion.
=> docs(CONTRIBUTING.md) Update wording

fdbclient/include/fdbclient/ReadYourWrites.h
Special keys error messages are expected to be JSON objects, so verify that in simulation.
=> Add checking for invalid special keys errors in simulation

fdbserver/Status.actor.cpp
Add more details info about BlobWorker into fdbcli status command. The following is one example output with 2 blob workers 
```
"blob_granules" : {
"78838045d8e9ee32" : {
"bytes_buffered" : 1596740,
"compression_bytes_final" : {
"counter" : 122242520,
"hz" : 0,
"roughness" : -1
},
"compression_bytes_raw" : {
"counter" : 119554712,
"hz" : 0,
"roughness" : -1
},
"delete_requests" : {
"counter" : 0,
"hz" : 0,
"roughness" : -1
},
"get_requests" : {
"counter" : 99,
"hz" : 0,
"roughness" : -1
},
"number_of_key_ranges" : 6,
"put_requests" : {
"counter" : 75,
"hz" : 0,
"roughness" : -1
}
},
"b01c5b8c1d8c80a3" : {
"bytes_buffered" : 2158352,
"compression_bytes_final" : {
"counter" : 94846920,
"hz" : 0,
"roughness" : -1
},
"compression_bytes_raw" : {
"counter" : 92692052,
"hz" : 0,
"roughness" : -1 …
```
=> fdbcli: add more info to blob worker status

fdbclient/SpecialKeySpace.actor.cpp, fdbclient/SpecialKeySpace.actor.h, fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp
=> Add test coverage for SpecialKeyRangeAsyncImpl::getRange  (snowflake-7.1)

fdbclient/SpecialKeySpace.actor.cpp, fdbclient/SpecialKeySpace.actor.h
Cherry-pick #7671 with only the fix as the test in this version is different.
=> Cherry-pick pull request #7671

documentation/sphinx/source/release-notes/release-notes-710.rst
=> Added 7.1.18, 7.1.19 release notes

documentation/sphinx/source/release-notes/release-notes-710.rst
=> Added 7.1.18, 7.1.19 release notes [release-7.1]

fdbclient/NativeAPI.actor.cpp, fdbserver/BlobManager.actor.cpp, fdbserver/storageserver.actor.cpp
From correctness testing. Each fix is its own commit and should be descriptive.
Passed 200k BlobGranule+ChangeFeed correctness with no failures.
=> Several Assorted Blob Granule/Change Feed bug fixes

fdbclient/BackupContainer.actor.cpp, fdbclient/BackupContainerFileSystem.actor.cpp, fdbclient/include/fdbclient/BackupContainerAzureBlobStore.h, fdbserver/CommitProxyServer.actor.cpp, fdbserver/DataDistribution.actor.cpp, fdbserver/include/fdbserver/CoordinationInterface.h, fdbserver/worker.actor.cpp
Add logging and update comments.
=> Add traces for snapshot related updates

cmake/ConfigureCompiler.cmake
Fix Windows build broken by #7682
=> 7682 - Fix Windows build

bindings/c/CMakeLists.txt, bindings/c/test/apitester/TesterExampleWorkload.cpp, documentation/sphinx/source/client-testing.rst
Adding documentation for API Tester.
=> Add documentation for API Tester

fdbserver/GlobalTagThrottler.actor.cpp
Fixes https://github.com/apple/foundationdb/issues/7876
=> Fix uninitialized bool values in GlobalTagThrottler

fdbserver/storageserver.actor.cpp
=> Remove extremely spammy trace event in FetchKeys (Cherry-pick #7883 to snowflake/release-71.2)

flow/Net2.actor.cpp
* properly join the created threads 
* disable unseed check for multithreaded tests
* ensure that the epilog in ThreadSafeQueue/Threaded happens on the main thread
With these changes, the tests were verified to pass 100,000 times in a row.
=> Fix Net2 unittest flakiness

contrib/TestHarness/Program.cs
=> Add snowflake-specific binaries folder for restart tests

fdbserver/DDTxnProcessor.actor.cpp, fdbserver/DataDistribution.actor.cpp, fdbserver/include/fdbserver/DDTxnProcessor.h
=> Move pollMoveKeysLock method to DDTxnProcessor

fdbserver/DataDistributionTracker.actor.cpp
As title
With this change it's possible to initialize DDTracker with `nullptr`, which is useful when write unit tests
=> Change trackerCancelled and shards in DDTracker to pointer

fdbserver/BlobManager.actor.cpp, fdbserver/workloads/BlobGranuleVerifier.actor.cpp
More fixes for force purging data not fully cleaning up the range.
=> More force purge fixes

flow/BlobCipher.cpp
Fix Windows build broken by #7885
=> 7823-Fix Windows build

fdbclient/include/fdbclient/ClusterInterface.h
Resolves https://github.com/apple/foundationdb/issues/7907
=> Initialize clientcount in opendatabaserequest

fdbserver/workloads/BlobGranuleVerifier.actor.cpp
Added a force purge at the end of a force purging test if it didn't do it during the normal test, and reworked check to better handle certain types of failures.
Passed 100k force purge tests with no failures and 100k BlobGranule* tests with unrelated failures.
=> Improved purge tests

fdbclient/include/fdbclient/ClusterInterface.h
Add OpenDatabaseRequest::Samples::count to serialization.
=> fixup! Add count to serialization in OpenDatabaseRequest::Samples

fdbserver/BlobManager.actor.cpp, fdbserver/worker.actor.cpp, fdbserver/workloads/BlobGranuleCorrectnessWorkload.actor.cpp
more bg correctness fixes, specifically for key alignment
Passes 100k BlobGranuleCorrectness*, so it should fix all of the outstanding key alignment failures
=> Bg bug fixes3

flow/Net2.actor.cpp
This is a cherry-pick of #7877.
- properly join the created threads
- disable unseed check for multithreaded tests
- ensure that the epilog in ThreadSafeQueue/Threaded happens on the main thread
=> Fix Net2 unittest flakiness (snowflake/release-71.2)

fdbclient/BlobGranuleFiles.cpp, fdbclient/BlobGranuleReader.actor.cpp, fdbclient/NativeAPI.actor.cpp, fdbclient/ServerKnobs.cpp, fdbclient/include/fdbclient/BlobGranuleCommon.h, fdbclient/include/fdbclient/BlobWorkerCommon.h, fdbclient/include/fdbclient/BlobWorkerInterface.h, fdbserver/BlobManager.actor.cpp, fdbserver/BlobWorker.actor.cpp, fdbserver/storageserver.actor.cpp
Cleaning up some TODOs and FIXMEs, including implementing a couple new changes, and a couple bug fixes
Passes 200k BlobGranule* tests with 1 failure (unseed, unrelated)
=> Blob Granules Cleanup

contrib/transaction_profiling_analyzer/transaction_profiling_analyzer.py, fdbserver/storageserver.actor.cpp
=> Remove extremely spammy trace event in FetchKeys & Fix transaction_profiling_analyzer.py [release-7.1]

cmake/ConfigureCompiler.cmake
See https://github.com/apple/foundationdb/issues/7955
=> Use -fno-sanitize=function with UBSAN as a work around

fdbserver/ClusterController.actor.cpp
Description
Register worker maintain 'id_worker' map to track the worker interface
registeration, it also sets 'WorkerAvailabilityWatcher' actor to track
for failures. However, if worker is already registered but interface gets
updated, the existing code doesn't actively cancel the watcher. One possible
race condition is, old watcher detects worker failure and removes the worker
from id_worker map even before the new watcher started monitoring the new
interface. If such a scenario is hit, it trips an assert in rebootAndCheck
routine which expects the worker should be present in the id_worker map.
Patch addresses the race condition by actively cancelling existing watcher
actor before registering the new watcher actor.
Testing
The general pull request guidelines can …
=> RegisterWorker to cancel existing watcher if reusing the worker

packaging/docker/build-images.sh
move global variables into function args/local variables, build both regular and debug images by default
=> build both regular and debug images

bindings/c/CMakeLists.txt, bindings/c/test/apitester/TesterBlobGranuleCorrectnessWorkload.cpp, bindings/c/test/apitester/TesterBlobGranuleErrorsWorkload.cpp, bindings/c/test/apitester/TesterBlobGranuleUtil.cpp, bindings/c/test/apitester/TesterBlobGranuleUtil.h, bindings/c/test/apitester/blobgranuletests/CApiBlobGranuleErrorsMultiThr.toml, bindings/c/test/apitester/blobgranuletests/CApiBlobGranuleErrorsOnExternalThread.toml, bindings/c/test/apitester/blobgranuletests/CApiBlobGranuleErrorsSingleThr.toml, bindings/c/test/mako/blob_granules.cpp, fdbclient/BlobGranuleFiles.cpp, tests/TestRunner/local_cluster.py
Add Error handling test, fix bugs and improve debugging info for blob granule api tests
Testing: Passes 10k BlobGranule* correctness, and 500 `ctest -R fdb_c_api_tests_blob_granule` tests
=> Update BlobGranules API tests

fdbserver/include/fdbserver/DataDistribution.actor.h
=> Fix -Wreorder-ctor warning in PhysicalShardCollection constructor

fdbclient/BlobGranuleFiles.cpp
Fixes 2 ubsan issues in blob granule files. One zero-length array, and another integer overflow
=> Fixing UBSAN issues in BlobGranuleFiles

design/dynamic-knobs.md
Co-authored-by: Markus Pilman <markus.pilman@snowflake.com>
Co-authored-by: Trevor Clinkenbeard <trevor.clinkenbeard@snowflake.com>
=> Add dynamic knobs design doc

fdbclient/BlobGranuleCommon.cpp, fdbclient/ClientKnobs.cpp, fdbclient/NativeAPI.actor.cpp, fdbclient/include/fdbclient/BlobGranuleCommon.h, fdbclient/include/fdbclient/BlobWorkerCommon.h, fdbclient/include/fdbclient/BlobWorkerInterface.h, fdbclient/include/fdbclient/NativeAPI.actor.h, fdbserver/BlobGranuleServerCommon.actor.cpp, fdbserver/BlobGranuleValidation.actor.cpp, fdbserver/BlobWorker.actor.cpp, fdbserver/include/fdbserver/BlobGranuleServerCommon.actor.h, fdbserver/include/fdbserver/BlobGranuleValidation.actor.h, fdbserver/workloads/BlobGranuleCorrectnessWorkload.actor.cpp, fdbserver/workloads/BlobGranuleVerifier.actor.cpp
=> [snowflake/release-71.2] Blob granule summary implementation (in native client) (#7981)

fdbrpc/include/fdbrpc/LoadBalance.actor.h
=> Suppress AllLocalAlternativesFailed events

flow/ProtocolVersion.h.cmake, flow/ProtocolVersions.cmake
Moves the lsb mask to patch version.
=> flow: move the protocol version least significant bit mask to cmake

contrib/TestHarness2/test_harness/summarize.py
The old test harness allowed certain messages to appear in the stderr
text. Port that behavior to the new test harness so that the ASAN
ensemble works again.
=> Allow expected messages in stderr in new test harness

documentation/sphinx/source/release-notes/release-notes-710.rst
=> Add 7.1.20, 7.1.21 release notes

bindings/java/src/main/com/apple/foundationdb/Database.java, fdbclient/KeyRangeMap.actor.cpp, fdbclient/NativeAPI.actor.cpp, fdbclient/ReadYourWrites.actor.cpp, fdbclient/SystemData.cpp, fdbclient/include/fdbclient/KeyRangeMap.h, fdbserver/workloads/BlobGranuleRangesWorkload.actor.cpp
https://github.com/apple/foundationdb/pull/7938
=> blobapi updates + fixing minRows

fdbserver/include/fdbserver/DataDistribution.actor.h
=> Fix clang compiling error

fdbclient/include/fdbclient/ConfigTransactionInterface.h, fdbclient/include/fdbclient/EncryptKeyProxyInterface.h, fdbclient/include/fdbclient/GetEncryptCipherKeys.actor.h, fdbserver/BlobWorker.actor.cpp, fdbserver/CommitProxyServer.actor.cpp, fdbserver/EncryptKeyProxy.actor.cpp, fdbserver/RESTKmsConnector.actor.cpp, fdbserver/SimKmsConnector.actor.cpp, fdbserver/include/fdbserver/IEncryptionKeyProvider.actor.h, fdbserver/include/fdbserver/KmsConnectorInterface.h, fdbserver/include/fdbserver/SimEncryptKmsProxy.actor.h, fdbserver/include/fdbserver/TLogInterface.h, flow/include/flow/EncryptUtils.h
- Move arena members to the end of serializer calls
- Fix a heap-use-after-free
=> Improve memory safety

fdbserver/ClusterController.actor.cpp
Description
In current code the leader replacement handling is done by
ClusterControllerWatchDog, it is possible that if the cluster
recruitment is in-progress, the leader replacement handling gets
delayed causing the multiple leaders to present simulateneously
impacting cluster recovery.
Move the cluster leader replacement logic to ClusterController
core to avoid above described scenario.
Testing
devCorrectness - 100K
=> ClusterClusterCore to handle leader replacement

fdbserver/DDRelocationQueue.actor.cpp, fdbserver/DDShardTracker.actor.cpp, fdbserver/include/fdbserver/DataDistribution.actor.h
=> Prevent GetTopKMetricsRequest.topK < 1

fdbclient/NativeAPI.actor.cpp, flow/ApiVersion.h.cmake, flow/ApiVersions.cmake
Addressing review comments to https://github.com/apple/foundationdb/pull/8071
=> ApiVersion: Small cleanups

fdbclient/include/fdbclient/Tracing.h
Fixed Valgrind `Testing /flow/Tracing/AddLinks: ==24== Syscall param socketcall.sendto(msg) points to uninitialised byte(s)`
* Commit: f5dff14ab23091c286c95d9c0da8135a723d14e8
* `valgrind bin/fdbserver -r simulation -f tests/rare/SpecificUnitTests.toml -s 179123167 -b on  --crash --trace_format json`
=> Fixed Valgrind "uninitialised byte(s)" failure by initializing all member in Span

fdbserver/ClusterController.actor.cpp, fdbserver/TLogServer.actor.cpp
Cherrypick #8001 and #8035.
20220902-040413-jzhou-d4ac5bd1913235f4
=> TLog stopped bug fixes and CC leader replacement fix [release-7.1]

bindings/c/test/fdb_api.hpp
=> Add raw access to create tenant api in Mako

fdbserver/include/fdbserver/WorkerInterface.actor.h
This variable was being accessed in an uninitialized state.
=> Initialize and serialize WorkerDetails::recoveredDiskFiles

fdbclient/NativeAPI.actor.cpp
Fix
* Commit: 3ce737b2fae67cb3bf6de2b20888f4b3a2ad6f30
* Command: `devRetryCorrectnessTest bin/fdbserver -r simulation -f tests/rare/ReadSkewReadWrite.toml -s 3272607999 -b on  --crash --trace_format json`
```
{
"Backtrace" : "addr2line -e fdbserver.debug -p -C -f -i 0x4038131 0x2cd5f82 0x2cd878b 0x1884a69 0x194e23f 0x1884a69 0x32e2f76 0x1884a69 0x32e2ca3 0x1884a69 0x22f9a87 0x1884a69 0x2cce127 0x1884a69 0x1983618 0x1982779 0x398bd51 0x197b522 0x3989bdd 0x3989ad1 0x398a377 0x1978aa9 0x39844f8 0x3983021 0x1978aa9 0x1981b8f 0x197bb56 0x1980fe8 0x19814d9 0x1978aa9 0x19787e9 0x3e4962d 0x3e488d1 0x1897568 0x3f060d3 0x2b38ed2 0x7f83c3938555",
"DateTime" : "2022-09-05T07:03:43Z",
"Error" : "grv_proxy_memory_limit_exceeded",
"ErrorCode" : "1078",
"ErrorDescription" : "GetReadVersion proxy memory …
```
=> Catch grv_proxy_memory_limit_exceeded in getConsistentReadVersion

fdbserver/BlobWorker.actor.cpp
Passes 100k BlobGranule* correctness with 1 unrelated error
=> Fixing memory leak caused by extra notified version promises

fdbclient/MultiVersionTransaction.actor.cpp, fdbclient/ThreadSafeTransaction.cpp, fdbclient/include/fdbclient/MultiVersionTransaction.h
=> Blobapi fixes

fdbclient/MultiVersionTransaction.actor.cpp, fdbclient/ThreadSafeTransaction.cpp, fdbclient/include/fdbclient/MultiVersionTransaction.h
https://github.com/apple/foundationdb/pull/8130
=> Blobapi cherry-picks #8130

bindings/c/CMakeLists.txt, bindings/c/test/apitester/TesterApiWorkload.cpp, bindings/c/test/apitester/TesterBlobGranuleErrorsWorkload.cpp, bindings/c/test/apitester/TesterExampleWorkload.cpp, bindings/c/test/apitester/TesterTestSpec.cpp, bindings/c/test/apitester/TesterTestSpec.h, bindings/c/test/apitester/TesterTransactionExecutor.cpp, bindings/c/test/apitester/TesterTransactionExecutor.h, bindings/c/test/apitester/TesterUtil.cpp, bindings/c/test/apitester/TesterUtil.h, bindings/c/test/apitester/TesterWorkload.cpp, bindings/c/test/apitester/TesterWorkload.h, bindings/c/test/apitester/fdb_c_api_tester.cpp, bindings/c/test/apitester/tests/CApiTamperClusterFile.toml, bindings/c/test/fdb_api.hpp, fdbclient/MonitorLeader.actor.cpp, fdbclient/NativeAPI.actor.cpp, fdbclient/ThreadSafeTransaction.cpp, fdbclient/include/fdbclient/CoordinationInterface.h, flow/ApiVersion.h.cmake, flow/ApiVersions.cmake, tests/TestRunner/upgrade_test.py
Release 71.2 cherry-picks #8115 and #8126, as well as dependent PRs #8082 and #8016.
=> [snowflake/release-71.2] Cluster file fixes

fdbrpc/sim2.actor.cpp, fdbserver/workloads/ChangeConfig.actor.cpp
=> Initialize configuration database type in simulator

fdbclient/FileBackupAgent.actor.cpp
These code probes will never be hit since these backup tasks are no longer used
=> Remove FileBackupAgent Code Probes

fdbserver/storageserver.actor.cpp
=> Add new latency samples for GetValue, GetRange, QueueWait, and VersionWait (Cherry-Pick #8173 to snowflake/release-71.2)

fdbserver/storageserver.actor.cpp
Same address is being reused for multiple queries incorrectly.
20220915-185330-haofu-2c271a32654cc707
=> Fix memory bug in index prefetch code path

fdbserver/storageserver.actor.cpp
backport: https://github.com/apple/foundationdb/pull/8187
=> Fix memory bug in index prefetch code path(release-7.1)

documentation/sphinx/source/administration.rst, documentation/sphinx/source/authorization.rst, documentation/sphinx/source/tenants.rst
Add documentation for authorization feature.
=> Add documentation for Authz

fdbclient/BlobGranuleFiles.cpp, fdbclient/NativeAPI.actor.cpp
Removed some dead code with associated code probes, and 2 unnecessary code probes
=> cleaning tss and blob granule file code probes

fdbserver/TLogServer.actor.cpp
=> fix: persistentData->commit() was not protected by the persistentDataCommitLock

CMakeLists.txt, bindings/c/CMakeLists.txt, tests/TestRunner/upgrade_test.py
=> Version Bump from 7.1.4 to 7.1.5

fdbserver/include/fdbserver/workloads/workloads.actor.h, fdbserver/tester.actor.cpp, fdbserver/workloads/ChangeConfig.actor.cpp, fdbserver/workloads/SaveAndKill.actor.cpp
=> All workloads to disable some failures

documentation/sphinx/source/release-notes/release-notes-710.rst
=> Added 7.1.22, 7.1.23 release notes [release-7.1]

fdbclient/NativeAPI.actor.cpp, fdbserver/workloads/BlobGranuleRangesWorkload.actor.cpp
=> [snowflake/release-71.2] fixes for non-aligned blob range calls

bindings/c/fdb_c.cpp, bindings/java/fdbJNI.cpp, bindings/java/src/main/com/apple/foundationdb/Database.java, fdbclient/MultiVersionTransaction.actor.cpp, fdbclient/NativeAPI.actor.cpp, fdbclient/include/fdbclient/MultiVersionTransaction.h, fdbserver/workloads/BlobGranuleRangesWorkload.actor.cpp
=> blob: java api fixes (purge + verify)

fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp
=> disable MoveKeysWorkload when running SpecialKeySpaceCorrectness test

tests/CMakeLists.txt
Language bindings do not work well with sanitizer instrumentation
=> Disable authz integration test for sanitizer builds

bindings/c/fdb_c.cpp, bindings/java/fdbJNI.cpp, bindings/java/src/main/com/apple/foundationdb/Database.java, fdbclient/MultiVersionTransaction.actor.cpp, fdbclient/NativeAPI.actor.cpp, fdbclient/include/fdbclient/MultiVersionTransaction.h, fdbserver/workloads/BlobGranuleRangesWorkload.actor.cpp
=> blob: purge + verify java api fixes

fdbcli/BlobKeyCommand.actor.cpp, fdbcli/fdbcli.actor.cpp, fdbcli/include/fdbcli/fdbcli.actor.h, fdbclient/include/fdbclient/BlobGranuleCommon.h, fdbserver/include/fdbserver/BlobGranuleServerCommon.actor.h
=> [snowflake/release-71.2] Adding blobkey history fdbcli debug command

fdbserver/workloads/BlobGranuleVerifier.actor.cpp
=> [snowflake/release-71.2] Fix purge at latest racing with other checking threads at the end of BlobGranuleVerify

fdbclient/ServerKnobs.cpp
=> increase the target blob worker lag 

fdbclient/BlobGranuleFiles.cpp, fdbclient/NativeAPI.actor.cpp, fdbclient/ReadYourWrites.actor.cpp, fdbclient/ThreadSafeTransaction.cpp, fdbclient/include/fdbclient/BlobGranuleCommon.h, fdbclient/include/fdbclient/BlobGranuleFiles.h, fdbclient/include/fdbclient/DatabaseContext.h, fdbclient/include/fdbclient/IConfigTransaction.h, fdbclient/include/fdbclient/ISingleThreadTransaction.h, fdbclient/include/fdbclient/NativeAPI.actor.h, fdbclient/include/fdbclient/ReadYourWrites.h
=> [snowflake/release-71.2] Adding bg read amp metrics (#8275)

fdbserver/storageserver.actor.cpp
=> [snowflake/release-71.2] Allowing ss feed fetches to go over hard limit

CMakeLists.txt, bindings/c/CMakeLists.txt, tests/TestRunner/binary_download.py
=> Version Bump from 71.2.0 to 71.2.1

fdbrpc/include/fdbrpc/simulator.h, fdbserver/workloads/Rollback.actor.cpp
=> Correct a couple of comments in simulator and simulated workloads.

bindings/c/test/apitester/TesterBlobGranuleCorrectnessWorkload.cpp, bindings/c/test/apitester/TesterBlobGranuleErrorsWorkload.cpp, bindings/c/test/fdb_api.hpp
Added test functions for blob granule db management functions
=> Blob Granule Database API tests

fdbserver/include/fdbserver/DataDistribution.actor.h
=> Change constructor initialization order to silence -Wreoder-ctor.

contrib/libb64/cdecode.c, contrib/libb64/include/libb64/cdecode.h, fdbclient/Tenant.cpp
=> Fix base64 decoder bug (cherry-pick to snowflake/release-71.2)

fdbrpc/sim2.actor.cpp
=> Disable delayProcess. It's not ready yet.

flow/CMakeLists.txt
=> zstd + mac m1 currently does not link, so disable for now

cmake/awssdk.cmake
Cmake 3.24 seems to require this
=> Quote aws sdk cxx flags

fdbserver/storageserver.actor.cpp
Storage server readrange and update latency.
=> Storage server readrange and update latency.

fdbclient/BlobGranuleFiles.cpp
Fix regression issue for this unittest 
=> fix benchFromFiles unit test

.flake8, .pre-commit-config.yaml, CONTRIBUTING.md
To enforce python best practices I propose a pre-commit pipeline with black and flake8.
=> Python pre-commit pipeline to enforce best practices.

fdbrpc/include/fdbrpc/simulator.h, fdbrpc/sim2.actor.cpp, fdbserver/SimulatedCluster.actor.cpp
Fix correctness test failures caused by blob worker recruitment failure. 
=> fix killMachine - make sure we have at least 1 blob worker in a dc

fdbrpc/include/fdbrpc/simulator.h, fdbrpc/sim2.actor.cpp, fdbserver/BlobWorker.actor.cpp, fdbserver/SimulatedCluster.actor.cpp
=> Port PR 8366 and 8365

fdbserver/include/fdbserver/QuietDatabase.h, fdbserver/tester.actor.cpp, fdbserver/workloads/SnapTest.actor.cpp
=> Port PR 8359

fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
=> Add per CF stats.

fdbrpc/ActorFuzz.actor.cpp, fdbrpc/include/fdbrpc/AsyncFileCached.actor.h
I missed some review comments for #8397 -- this PR addresses those
=> Address review comments

fdbserver/KeyValueStoreSQLite.actor.cpp
=> Sim-only bug fix where SQLite can take too long to shut down (Cherry-pick #8400 to snowflake/release-71.2)

fdbserver/ClusterController.actor.cpp, fdbserver/ClusterController.actor.h
=> [release 7.1] Ignore max degradation degree for a disconnected worker.

fdbclient/MultiVersionTransaction.actor.cpp
1. The MVC timeout set a delay for the entire duration, which for long durations would consume memory until the timer elapsed even after the transaction was destroyed. This has been converted into a sequence of smaller timers (similar to RYW) allowing cancelation within some shorter amount of time.
2. The MVC didn't cancel the timeout actor when the transaction was destroyed, which seems to result in a similar leak to `#1` where we have to wait for the timer to complete.
3. The MVC didn't properly handle the case where the timeout value was set to 0, which should disable the timeout. Instead, the timeout in that case would immediately fire. Note: this only impacts a user if the timeout is set to 0 while disconnected from a cluster. …
=> Fix some timeout related issues in the multi-version client

fdbserver/include/fdbserver/workloads/MetaclusterConsistency.actor.h, fdbserver/include/fdbserver/workloads/TenantConsistency.actor.h
=> Include `unactorcompiler.h` in actor header files

fdbserver/storageserver.actor.cpp, fdbserver/workloads/BulkSetup.actor.h
And cherrypick a test bug fix: #8249
10k 20221010-172030-jzhou-fd211924d1651f52 passed.
=> Fix a clang compiling error [release-7.1]

design/dynamic-knobs.md, documentation/sphinx/source/command-line-interface.rst, fdbcli/fdbcli.actor.cpp, fdbcli/tests/fdbcli_tests.py, fdbclient/ConfigKnobs.cpp, fdbclient/Tuple.cpp, fdbclient/include/fdbclient/Tuple.h, fdbserver/ConfigDatabaseUnitTests.actor.cpp, fdbserver/worker.actor.cpp, fdbserver/workloads/ConfigIncrement.actor.cpp, flow/Knobs.cpp
This PR adds the `setknob` and `getknob` commands to `fdbcli`. 
The usage is as follows
`setknob <knob_name> <knob_value> [config_class]`
`getknob <knob_name> [config_class]`
Where `knob_name` is an already existing FDB knob, `knob_value` is the desired value to set the knob and `config_class` is the desired configuration class. 
You can change multiple knobs atomically in one transaction using `begin` and `commit`. An example is as follows
```
begin 
setknob min_trace_severity 30 
setknob max_metric_size 1000
commit <description>
```
Prior to committing a transaction with a `setknob`, `fdbcli` will prompt for a description of the change(s). An example follows:
```
Please set a description for the change. Description must be non-empty
description: <put your description here>
Committed (1) …
```
=> fdbcli: Add options for knob management

fdbclient/MultiVersionTransaction.actor.cpp
Cherry pick of https://github.com/apple/foundationdb/pull/8371
=> Fix some timeout related issues in the multi-version client (Cherry-pick #8371 to release-71.2)

fdbserver/workloads/DifferentClustersSameRV.actor.cpp
This workload had two problems:
1. Since we attempt to read at an old read version, we could attempt to read before all tenants have been created on the extra database. This is addressed by advancing the version of both clusters to the max version plus 10M (this also should make the test more effective).
2. The `CODE_PROBE` condition was wrong and would cause occasional crashes
=> Fix DifferentClustersSameRV workload

fdbclient/ManagementAPI.actor.cpp, fdbclient/SystemData.cpp, fdbclient/include/fdbclient/SystemData.h, fdbrpc/include/fdbrpc/simulator.h, fdbrpc/sim2.actor.cpp, fdbserver/ApplyMetadataMutation.cpp, fdbserver/ClusterController.actor.cpp, fdbserver/ClusterRecovery.actor.cpp, fdbserver/DDTeamCollection.actor.cpp, fdbserver/DDTxnProcessor.actor.cpp, fdbserver/FDBExecHelper.actor.cpp, fdbserver/SimulatedCluster.actor.cpp, fdbserver/TLogServer.actor.cpp, fdbserver/TagPartitionedLogSystem.actor.cpp, fdbserver/include/fdbserver/ClusterController.actor.h, fdbserver/include/fdbserver/DDTeamCollection.h, fdbserver/include/fdbserver/DDTxnProcessor.h, fdbserver/include/fdbserver/LogSystem.h, fdbserver/include/fdbserver/TagPartitionedLogSystem.actor.h, fdbserver/include/fdbserver/WorkerInterface.actor.h, fdbserver/storageserver.actor.cpp, fdbserver/worker.actor.cpp, fdbserver/workloads/ClientWorkload.actor.cpp, fdbserver/workloads/MachineAttrition.actor.cpp
Reverts apple/foundationdb #8472
This PR seems to break the CI and can cause "Build has timed out." error.
=> Revert "Data loss protection v2"

fdbclient/ManagementAPI.actor.cpp, fdbclient/SystemData.cpp, fdbclient/include/fdbclient/SystemData.h, fdbrpc/include/fdbrpc/simulator.h, fdbrpc/sim2.actor.cpp, fdbserver/ApplyMetadataMutation.cpp, fdbserver/ClusterController.actor.cpp, fdbserver/ClusterRecovery.actor.cpp, fdbserver/DDTeamCollection.actor.cpp, fdbserver/DDTxnProcessor.actor.cpp, fdbserver/FDBExecHelper.actor.cpp, fdbserver/SimulatedCluster.actor.cpp, fdbserver/TLogServer.actor.cpp, fdbserver/TagPartitionedLogSystem.actor.cpp, fdbserver/include/fdbserver/ClusterController.actor.h, fdbserver/include/fdbserver/DDTeamCollection.h, fdbserver/include/fdbserver/DDTxnProcessor.h, fdbserver/include/fdbserver/LogSystem.h, fdbserver/include/fdbserver/TagPartitionedLogSystem.actor.h, fdbserver/include/fdbserver/WorkerInterface.actor.h, fdbserver/storageserver.actor.cpp, fdbserver/worker.actor.cpp, fdbserver/workloads/ClientWorkload.actor.cpp, fdbserver/workloads/MachineAttrition.actor.cpp
Cherrypick #8521 to fix CI problem.
=> Revert "Data loss protection v2" [release-7.2]

fdbserver/RocksDBCheckpointUtils.actor.cpp, fdbserver/storageserver.actor.cpp, fdbserver/workloads/StorageServerCheckpointRestoreTest.actor.cpp
=> Fixed file offset not reset issue.

fdbclient/BlobGranuleFiles.cpp
=> Add blob granule benchmark to track stats by varying amount of deltas, and several simple perf improvements

fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
=> Destroy CF handle before closing physical shard.

fdbclient/include/fdbclient/GetEncryptCipherKeys.actor.h, fdbserver/EncryptKeyProxy.actor.cpp
Ensure that when using a system or default domain id that the correct domain name is used alongside with it
=> Add Encrypt Domain Name Asserts

bindings/go/src/fdb/generated.go, contrib/TestHarness2/test_harness/summarize.py, fdbclient/FileBackupAgent.actor.cpp, fdbclient/vexillographer/fdb.options, fdbrpc/sim2.actor.cpp, fdbserver/DiskQueue.actor.cpp, fdbserver/RocksDBCheckpointUtils.actor.cpp, fdbserver/VersionedBTree.actor.cpp, fdbserver/storageserver.actor.cpp, fdbserver/workloads/StorageServerCheckpointRestoreTest.actor.cpp
=> Cherrypick multiple fixes [Release 7.2]

documentation/sphinx/source/client-testing.rst
Updating API Tester documentation:
- Update instructions for execution with ctest
- Document server configuration
=> Update API Tester documentation for server config and ctest targets

fdbrpc/include/fdbrpc/FlowTransport.h, fdbrpc/include/fdbrpc/fdbrpc.h
This resolves https://github.com/apple/foundationdb/issues/4164
=> Make FlowReceiver NonCopyable

contrib/TestHarness2/test_harness/summarize.py, fdbrpc/sim2.actor.cpp
=> Fix a memory leak in simulation

fdbclient/include/fdbclient/TenantEntryCache.actor.h
An iterator was sometimes accessed after deletion in the `mapByTenantName` map.
=> Fix heap-use-after-free in `TenantEntryCache::put`

bindings/go/src/fdb/generated.go, fdbclient/vexillographer/fdb.options
This feature is not ready for use by applications
=> Mark idempotency id related transaction options as hidden

fdbserver/DDRelocationQueue.actor.cpp
20221023-034951-zhewu_8546-938682a3cda5382e        compressed=True data_size=39243278 duration=4308992 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=0:50:46 sanity=False started=100028 stopped=20221023-044037 submitted=20221023-034951 timeout=5400 username=zhewu_8546
=> Count the detailed reason for new physical shard creation during data move

fdbclient/BlobGranuleReader.actor.cpp, fdbclient/include/fdbclient/FDBTypes.h, fdbserver/BlobManager.actor.cpp, fdbserver/BlobManifest.actor.cpp, fdbserver/BlobMigrator.actor.cpp, fdbserver/BlobWorker.actor.cpp, fdbserver/ClusterController.actor.cpp, fdbserver/include/fdbserver/BlobGranuleServerCommon.actor.h, fdbserver/include/fdbserver/BlobMigratorInterface.h, fdbserver/storageserver.actor.cpp, fdbserver/worker.actor.cpp
Implement StorageServerInterface for BlobMigrator. It could copy data from s3 to storage server with this PR. 
Tests:
1) local cluster. data copy could complete successfully
2) correctness tests. 100K passed 
=> Implement StorageServerInterface for BlobMigrator

fdbclient/BackupContainer.actor.cpp, fdbclient/FileBackupAgent.actor.cpp, fdbrpc/AsyncFileNonDurable.actor.h, fdbrpc/AsyncFileReadAhead.actor.h, fdbrpc/AsyncFileWriteChecker.h, fdbserver/DiskQueue.actor.cpp, flow/genericactors.actor.h
Cherrypick #8526 and #8522
300k 20221024-221958-jzhou-ca54e126a2a47f40 passed.
=> Fix potential data corruptions [release 6.3]

fdbclient/BackupContainerLocalDirectory.actor.cpp, fdbclient/FileBackupAgent.actor.cpp, fdbrpc/AsyncFileEncrypted.actor.cpp, fdbrpc/include/fdbrpc/AsyncFileChaos.h, fdbrpc/include/fdbrpc/AsyncFileNonDurable.actor.h, fdbrpc/include/fdbrpc/AsyncFileReadAhead.actor.h, fdbrpc/include/fdbrpc/AsyncFileWriteChecker.h, fdbserver/DiskQueue.actor.cpp, fdbserver/VersionedBTree.actor.cpp, flow/include/flow/IAsyncFile.h, flow/include/flow/genericactors.actor.h
=> Bug fixes in IO buffer and class lifetimes (Cherry-pick #8526 to snowflake/release-71.2)

fdbclient/BackupContainerLocalDirectory.actor.cpp, fdbclient/FileBackupAgent.actor.cpp, fdbrpc/AsyncFileChaos.actor.h, fdbrpc/AsyncFileEncrypted.actor.cpp, fdbrpc/AsyncFileNonDurable.actor.h, fdbrpc/AsyncFileReadAhead.actor.h, fdbrpc/AsyncFileWriteChecker.h, fdbrpc/IAsyncFile.h, fdbserver/DiskQueue.actor.cpp, fdbserver/VersionedBTree.actor.cpp, flow/genericactors.actor.h
=> Bug fixes in IO buffer and class lifetimes (Cherry-pick #8526 to release-7.1)

fdbclient/BackupContainerLocalDirectory.actor.cpp, fdbclient/FileBackupAgent.actor.cpp, fdbrpc/AsyncFileEncrypted.actor.cpp, fdbrpc/include/fdbrpc/AsyncFileChaos.h, fdbrpc/include/fdbrpc/AsyncFileNonDurable.actor.h, fdbrpc/include/fdbrpc/AsyncFileReadAhead.actor.h, fdbrpc/include/fdbrpc/AsyncFileWriteChecker.h, fdbserver/DiskQueue.actor.cpp, fdbserver/VersionedBTree.actor.cpp, flow/include/flow/IAsyncFile.h, flow/include/flow/genericactors.actor.h
=> Bug fixes in IO buffer and class lifetimes (Cherry-pick #8522 and #8526 to release-7.2)

contrib/TestHarness2/test_harness/summarize.py
TestHarness was not passing the handler to the xml parser. I don't understand how this would work for any tests but it just started to fail now.
=> fix summarize bug

contrib/Joshua/scripts/correctnessTest.sh, contrib/TestHarness2/test_harness/summarize.py
Cherrypick #8567 #8575
Use old test harness.
=> fix summarize bug and switch back to old test harness [release-7.2]

packaging/docker/run_ycsb.sh
Reduce output (to stderr/out), correct shellcheck complaints
- remove global `set -x`, use selectively
- add more detail to echo statements
- remove unused variables
- quote variables and strings that contain variables
=> cleanup run_ycsb.sh script

packaging/docker/Dockerfile
Update to newer versions of tools in the image 
=> update kubectl and awscli

packaging/docker/Dockerfile, packaging/docker/Dockerfile.eks
Change `Dockerfile.eks` to use same tools as `Dockerfile`, and remove call to `uname`
=> make same change to Dockerfile.eks (from #8583)

packaging/docker/Dockerfile, packaging/docker/Dockerfile.eks, packaging/docker/build-images.sh, packaging/docker/fdb.bash, packaging/docker/run_ycsb.sh, packaging/docker/sidecar.py, packaging/docker/sidecar_test.py
pull in differences from `release-7.1` for `packaging/docker` .. not completely sure if all the changes should be here, will let PR builds tell us. 
=> pull packaging/docker diffs from release-7.1

fdbclient/NativeAPI.actor.cpp, fdbserver/workloads/BlobGranuleRangesWorkload.actor.cpp
=> blob: allow purge ranges to begin and end in unblobbified regions

fdbclient/include/fdbclient/TenantEntryCache.actor.h
=> Fix heap-use-after-free in TenantEntryCache::put [release-7.2]

fdbserver/DDRelocationQueue.actor.cpp, fdbserver/DDShardTracker.actor.cpp, fdbserver/include/fdbserver/DataDistribution.actor.h
=> [release 7.2] Cherry pick physical shard creation stats

fdbclient/FileBackupAgent.actor.cpp
Old `fdbserver`, e.g., 7.1.*, may not set the "enableSnapshotBackupEncryption" key, thus we should allow the key to be not present.
100k 20221027-155208-jzhou-b531f391d866b804 has unrelated failures
- `tests/slow/ApiCorrectnessAtomicRestore.toml` failed for `TracedTooManyLines`
- `tests/slow/DDBalanceAndRemove.toml`, failed for `ExternalTimeout, TestUnexpectedlyNotFinished`.
=> Fix restarting restore test failure

tests/rare/SpecificUnitTests.toml
=> Specific unit test should only run one tests instead of all tests

.flake8, bindings/bindingtester/tests/api.py, bindings/bindingtester/tests/directory.py
=> Applied flake8 rules to 2 python files

tests/slow/ApiCorrectnessAtomicRestore.toml
=> Add timeout for long running test.

bindings/bindingtester/tests/directory_state_tree.py, bindings/bindingtester/tests/directory_util.py, bindings/bindingtester/tests/test_util.py, bindings/bindingtester/tests/tuple.py
=> Applied flake8

fdbclient/NativeAPI.actor.cpp
=> blob: fix transaction reset in getBlobRanges() and refactor blob get tenant code

flowbench/BenchNet2.actor.cpp
Added delay and yield benchmarks, the bench parameter is used to fill the run loop priority queue with N delays.
Example results:
```
bench_delay<DELAY>/0           77.3 ns         77.3 ns      8954298 items_per_second=12.944M/s
bench_delay<DELAY>/1           76.2 ns         76.2 ns      9013071 items_per_second=13.1249M/s
bench_delay<DELAY>/8           76.7 ns         76.7 ns      9086869 items_per_second=13.036M/s
bench_delay<DELAY>/64          89.9 ns         89.9 ns      9146890 items_per_second=11.1185M/s
bench_delay<DELAY>/512         99.8 ns         99.8 ns      8070087 items_per_second=10.0237M/s
bench_delay<DELAY>/4096         110 ns          110 ns      7407241 items_per_second=9.08587M/s
bench_delay<DELAY>/32768        127 ns          127 ns      6073005 …
```
=> Added benchmark for delay(0) and yield().

flow/Net2.actor.cpp
=> Fix circular reference in SSLConnection [release-7.2]

fdbserver/DiskQueue.actor.cpp
=> File write() buffer lifetime fix in DiskQueue. (Cherry-pick #8646 to release-7.1)

fdbserver/ApplyMetadataMutation.cpp
20k 20221101-001339-jzhou-04fec122ae7c4cbe passed.
=> Remove unnecessary decodeServerTagValue calls

bindings/c/test/apitester/TesterBlobGranuleCorrectnessWorkload.cpp
Debugging improvements and one tenant-related fix to the blob granule api tests
Passes 100 fdb_c_upgrade_to_future_version_blob_granules with no failures
=> Better bg api debug

fdbserver/ApplyMetadataMutation.cpp, fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp
Cherrypick #8653 and #8643
100k 20221101-213832-jzhou-6f217cb973688276 passed
=> Fix a workload bug and small improvement [release-7.1]

fdbserver/DiskQueue.actor.cpp
=> File write() buffer lifetime fix in DiskQueue. (Cherry-pick #8646 to release-7.2)

fdbclient/ParallelStream.actor.cpp, fdbclient/include/fdbclient/GenericManagementAPI.actor.h, fdbserver/BlobWorker.actor.cpp, fdbserver/ConsistencyScan.actor.cpp, fdbserver/DDShardTracker.actor.cpp, fdbserver/DDTeamCollection.actor.cpp, fdbserver/GlobalTagThrottler.actor.cpp, fdbserver/KeyValueStoreMemory.actor.cpp, fdbserver/KeyValueStoreShardedRocksDB.actor.cpp, fdbserver/RocksDBLogForwarder.actor.cpp, fdbserver/include/fdbserver/RocksDBLogForwarder.h
20221101-232905-jzhou-12795808f5fa195a
=> Fix compiling errors and warnings

fdbserver/DiskQueue.actor.cpp
=> File write() buffer lifetime fix in DiskQueue. (Cherry-pick #8646 to snowflake/release-71.2)

fdbserver/GrvProxyServer.actor.cpp, fdbserver/GrvProxyTagThrottler.actor.cpp, fdbserver/include/fdbserver/GrvProxyTagThrottler.h
=> Make `GrvProxyTagThrottler` class name less verbose

documentation/sphinx/source/release-notes/release-notes-630.rst, documentation/sphinx/source/release-notes/release-notes-710.rst
=> Add 7.1.24, 7.1.25, and 6.3.25 release notes

documentation/sphinx/source/release-notes/release-notes-710.rst
=> Add 7.1.24, 7.1.25 release notes

fdbserver/workloads/TenantManagementWorkload.actor.cpp
The tenant management workload was not properly handling errors from GRV calls made in the delete tenant operation.
=> Fix tag_throttled failure in TenantManagement workload

fdbclient/NativeAPI.actor.cpp
In try commit, wait for the read version future before waiting for the commit cost estimate. This allows us to give precedence to the database_locked error over errors thrown by the commit cost estimation.
=> Fix tenant not found on locked database

fdbserver/BlobManager.actor.cpp
Parallelizes full granule purges instead of doing them sequentially, and fixed a bug in the purge order
Passes 10k BlobGranule* tests with purging enabled
=> Parallelize bg purge

documentation/sphinx/source/release-notes/release-notes-710.rst, fdbserver/FDBExecHelper.actor.cpp, fdbserver/Status.actor.cpp
Cherrypick #8684
20221103-194349-jzhou-17fc65d1d5b90e81
=> Fix ASan found memory bugs [release 7.1]

fdbserver/Status.actor.cpp
=> Cherrypick status json asan fix [release-7.2]

fdbserver/Status.actor.cpp
Previously, `status json` would report a machine as excluded when any of its processes were excluded. But a machine should only be reported as excluded when all of its processes are excluded.
I tested this change by running a small, three process test cluster. I excluded one machine, and verified `status json` reported the overall machine as not excluded.
=> Fix exclude status of machines in status json

fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
=> Add bounds to iterator.

fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
=> Add metrics for read range.

fdbserver/DDShardTracker.actor.cpp, fdbserver/DDTeamCollection.actor.cpp, fdbserver/DDTxnProcessor.actor.cpp, fdbserver/DataDistribution.actor.cpp, fdbserver/include/fdbserver/DDTeamCollection.h
Some notes and fixes while browsing the code.
20221104-055601-zhewu_8628-65c2a648a8054f82
=> Add some comments in DD and fix some nit

fdbclient/S3BlobStore.actor.cpp
=> fixing build vs with that caused compiling aws sdk to not work properly

.flake8, bindings/c/generate_asm.py, bindings/c/test/apitester/run_c_api_tests.py, bindings/c/test/fdb_c_shim_tests.py
=> /bindings/c/ Applied flake8

bindings/bindingtester/__init__.py, bindings/bindingtester/bindingtester.py
=> /bindings/bindingtester/ Applied flake8

fdbclient/include/fdbclient/VersionedMap.h
=> Explain where 4.3 comes from for PTree finger length explanation

fdbclient/BlobGranuleFiles.cpp, fdbclient/ServerKnobs.cpp, fdbserver/CommitProxyServer.actor.cpp, fdbserver/GrvProxyServer.actor.cpp, fdbserver/RestoreLoader.actor.cpp, fdbserver/fdbserver.actor.cpp
Cherrypick #8507 #8701 #8773
20221110-032337-jzhou-735fcc17b2c3e1b0
=> fix bg stats invalid memory access [release-7.2]

fdbserver/CommitProxyServer.actor.cpp, fdbserver/GrvProxyServer.actor.cpp, fdbserver/RestoreLoader.actor.cpp
Another instance missed in #8556
20221110-210956-jzhou-ce4e116e6f409554
=> Fix a stack overflow bug

fdbserver/KeyValueStoreShardedRocksDB.actor.cpp, tests/restarting/from_5.0.0_until_6.3.0/CycleTestRestart-1.txt, tests/restarting/from_5.0.0_until_6.3.0/CycleTestRestart-2.txt, tests/restarting/from_5.0.0_until_6.3.0/StorefrontTestRestart-1.txt, tests/restarting/from_5.0.0_until_6.3.0/StorefrontTestRestart-2.txt, tests/restarting/from_5.1.7_until_6.3.0/DrUpgradeRestart-1.txt, tests/restarting/from_5.1.7_until_6.3.0/DrUpgradeRestart-2.txt, tests/restarting/from_5.2.0_until_6.3.0/ClientTransactionProfilingCorrectness-1.txt, tests/restarting/from_5.2.0_until_6.3.0/ClientTransactionProfilingCorrectness-2.txt
Reverts apple/foundationdb#8542
Restarting tests are broken by it.
=> Revert "[release 7.2] Destroy CF handle before closing physical shard."

fdbclient/ServerKnobs.cpp
This is a cherrypick from 7.2 to main.
=> Disable forwarding log of RocksDB to FDB by default

fdbserver/DDRelocationQueue.actor.cpp
Should be no-op change.
20221111-215929-zhewu_8801-a7a054aec2f3a147
=> Clean up DD remote team selection in physical shard move

fdbserver/KeyValueStoreRocksDB.actor.cpp, fdbserver/storageserver.actor.cpp
Adding counters for singlekey clear requests
cherry-pick of #8747 
=> Adding counters for singlekey clear requests

fdbclient/FileBackupAgent.actor.cpp, fdbserver/Resolver.actor.cpp, tests/fast/EncryptedBackupCorrectness.toml
=> Revert "Extend Transaction Window during Restore in Simulation"

fdbclient/ManagementAPI.actor.cpp, fdbclient/include/fdbclient/ManagementAPI.actor.h, fdbserver/TenantCache.actor.cpp, fdbserver/workloads/StorageQuota.actor.cpp
Add a command to clear storage quota
=> Add a command to clear storage quota

bindings/go/src/fdb/generated.go
Cherry-pick #8761, since CI is also failing on this branch because of this issue
=> [snowflake/release-71.2] Update go bindings option file with go 1.19

fdbserver/DDRelocationQueue.actor.cpp, fdbserver/DDShardTracker.actor.cpp
20221114-202022-zhewu_8813-370b0e6b37549f75
=> Add more detailed reasons for physical shard creation

fdbserver/storageserver.actor.cpp
Cherry-picks:
#8751 
#8736 (Except for caching changes since those aren't in the release branch)
#8741
Passed 500k BlobGranule+ChangeFeed correctness and 50k BlobGranule+ChangeFeed ASAN correctness
=> [snowflake/release-71.2] Backport bug fix and perf improvements to release branch

CMakeLists.txt, bindings/c/CMakeLists.txt, tests/TestRunner/binary_download.py
=> Version Bump from 71.2.3 to 71.2.4

fdbserver/storageserver.actor.cpp
Cherry-pick #8830
Passes 250k blob granule + change feed correctness
=> [snowflake/release-71.2] Added FeedDiskReadState to make change feeds reading a large amount of disk data more efficient

fdbserver/DDRelocationQueue.actor.cpp, fdbserver/DDShardTracker.actor.cpp, fdbserver/include/fdbserver/DataDistribution.actor.h
Cherry-pick #8801 #8813 #8840 
=> [Release 7.2] DD physical shard creation improvements

cmake/CompileRocksDB.cmake, fdbserver/KeyValueStoreRocksDB.actor.cpp, fdbserver/KeyValueStoreShardedRocksDB.actor.cpp, fdbserver/RocksDBCheckpointUtils.actor.cpp
=> RocksDB 7.7.3 version upgrade

fdbserver/TenantCache.actor.cpp
fast/RandomUnitTests.toml -s 223597607 -b on
commit: 2bee6ccfa
=> Disable flaky TenantCache tests [relese-7.2]

fdbclient/ServerKnobs.cpp
=> [release-7.2] Update timeouts to 5 sec.

fdbclient/ServerKnobs.cpp
=> Set timeout to 5 sec.

documentation/sphinx/source/mr-status-json-schemas.rst.inc, fdbclient/Schemas.cpp
=> Add metacluster status details to schemas

fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
Reuse RocksDB options and CF options.
=>  Reuse RocksDB options and CF options.

fdbclient/NativeAPI.actor.cpp, fdbserver/LogSystem.cpp, fdbserver/MutationTracking.cpp, flow/Knobs.cpp
=> Fix span code probes

bindings/python/tests/cancellation_timeout_tests.py, bindings/python/tests/size_limit_tests.py, bindings/python/tests/tenant_tests.py, bindings/python/tests/tester.py, bindings/python/tests/tuple_tests.py
=> bindings/python/tests Applied flake8

flow/include/flow/flat_buffers.h, flow/include/flow/serialize.h
=> Make deserializing std::{map,set} O(n)

fdbclient/MultiVersionTransaction.actor.cpp
Upgrade tests were sporadically failing in case of onError calls on grv_proxy_memory_limit_exceeded after a downgrade to 7.1. The problem is that grv_proxy_memory_limit_exceeded is a new retryable error introduced in 7.2, so 7.1 client does not recognized it as such. So it is problematic to simply forward errors to onError of another client after a cluster version change.
This PR addresses the issue by letting onError to always succeed in case of a successful version change, so that the application retries the transaction on the other client version. …
=> Fix onError in case of new retryable errors after cluster downgrade

contrib/monitoring/fdb_c_version.py
=> contrib/monitoring Applied flake8

contrib/grv_proxy_model/grv_test.py, contrib/grv_proxy_model/plot.py, contrib/grv_proxy_model/priority.py, contrib/grv_proxy_model/proxy_model.py, contrib/grv_proxy_model/rate_model.py, contrib/grv_proxy_model/ratekeeper_model.py, contrib/grv_proxy_model/smoother.py, contrib/grv_proxy_model/workload_model.py
=> contrib/grv_proxy_model Applied flake8

fdbserver/storageserver.actor.cpp
=> Declare and define `FDB_BOOLEAN_PARAM` in one line

contrib/transaction_profiling_analyzer/transaction_profiling_analyzer.py, contrib/transaction_profiling_analyzer/transaction_profiling_analyzer_tests.py
=> contrib/transaction_profiling_analyzer Applied flake8

fdbserver/VersionedBTree.actor.cpp
=> Fix Redwood crash after shutdown (Cherry-Pick #8918 to snowflake/release-71.2)

fdbserver/KeyValueStoreRocksDB.actor.cpp, fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
CI failures are not related to RocksDB.
=> [release-7.2] Increase field length limit for rocksdb errors.

fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
=> Add canCommit to sharded rocksdb.

fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
https://github.com/apple/foundationdb/pull/8962
=> [release-7.2] Add canCommit to sharded rocksdb.

bindings/c/CMakeLists.txt, tests/TestRunner/binary_download.py, tests/TestRunner/upgrade_test.py
=> Fix the ctest failures

fdbrpc/FlowTransport.actor.cpp
=> Improve tracing for invalid packets in `scanPackets`

fdbclient/DatabaseContext.cpp, fdbclient/NativeAPI.actor.cpp, fdbclient/include/fdbclient/DatabaseContext.h, fdbserver/ClusterRecovery.actor.cpp, flow/include/flow/flow.h
This is to enable the watch reference counting to release-7.2
Backport of [PR#8663 ](https://github.com/apple/foundationdb/pull/8663)
=> Backport #8663 to release-7.2

bindings/c/test/mako/mako.cpp
This PR gives more meaningful names to mako threads on Linux systems. This allows for easier performance monitoring via, e.g., `top`. Testing was done by running `mako` and looking at the `top` output. 
=> Mako: Name Threads For Better Performance Monitoring

fdbserver/KeyValueStoreRocksDB.actor.cpp, fdbserver/KeyValueStoreShardedRocksDB.actor.cpp, fdbserver/include/fdbserver/IKeyValueStore.h, fdbserver/storageserver.actor.cpp
=> Remove cleanUpShard API. 

fdbserver/ClusterController.actor.h
=> [release 7.1] Add determinstic in gray failure degraded server selection

bindings/c/test/mako/stats.hpp, fdbbackup/backup.actor.cpp, fdbclient/NativeAPI.actor.cpp, fdbclient/VersionVector.cpp, fdbclient/include/fdbclient/MutationLogReader.actor.h, fdbrpc/ReplicationPolicy.cpp, fdbserver/DDRelocationQueue.actor.cpp, fdbserver/DDTeamCollection.actor.cpp, fdbserver/KeyValueStoreSQLite.actor.cpp, fdbserver/KeyValueStoreShardedRocksDB.actor.cpp, fdbserver/LogRouter.actor.cpp, fdbserver/RestoreApplier.actor.cpp, fdbserver/SimulatedCluster.actor.cpp, fdbserver/VersionedBTree.actor.cpp, fdbserver/workloads/BlobGranuleCorrectnessWorkload.actor.cpp, fdbserver/workloads/WatchAndWait.actor.cpp, flow/include/flow/TaskQueue.h
backporting https://github.com/apple/foundationdb/pull/9007
=> Fix clang 15 compiler warnings(release-7.2)

fdbserver/MetricClient.actor.cpp
Add include guard for `sys/socket.h`
=> metrics: Fix windows build

fdbclient/NativeAPI.actor.cpp, fdbrpc/HTTP.actor.cpp
=> Fix assertion failure from changeFeedTSSValidator() [release-7.2]

fdbserver/include/fdbserver/ClusterController.actor.h
=> [release 7.2] Add determinstic in gray failure degraded server selection

fdbserver/KeyValueStoreRocksDB.actor.cpp
Moving rocksdb read iterator destruction from commit path to actor.
cherry-pick of #8970 
=> Moving rocksdb read iterator destruction from commit path to actor.

bindings/c/test/apitester/fdb_c_api_tester.cpp, fdbclient/MultiVersionTransaction.actor.cpp, fdbclient/ThreadSafeTransaction.cpp, flow/Trace.cpp, tests/TestRunner/upgrade_test.py, tests/restarting/from_7.1.0/SnapIncrementalRestore-1.txt, tests/restarting/from_7.1.0/SnapIncrementalRestore-2.txt, tests/restarting/from_7.1.0/SnapTestAttrition-2.txt, tests/restarting/from_7.1.0/SnapTestRestart-2.txt, tests/restarting/from_7.1.0/SnapTestSimpleRestart-2.txt
cherrypick #8629 as well
20221214-005033-jzhou-4ff391371884fdac
=> Fix restarting test spec [release-7.2]

fdbcli/fdbcli.actor.cpp
Update the help text for the `quota` command to include the options for storage quota
=> Update the help text for the `quota` command

tests/slow/DifferentClustersSameRV.toml
=> Temporarily disable the default tenant in DifferentClustersSameRV

bindings/c/foundationdb/fdb_c.h, bindings/c/test/unit/unit_tests.cpp, bindings/java/fdbJNI.cpp, bindings/java/src/integration/com/apple/foundationdb/MappedRangeQueryIntegrationTest.java, bindings/java/src/main/com/apple/foundationdb/MappedKeyValue.java, bindings/java/src/main/com/apple/foundationdb/MappedRangeResultDirectBufferIterator.java, fdbclient/NativeAPI.actor.cpp, fdbclient/include/fdbclient/FDBTypes.h, fdbclient/include/fdbclient/MultiVersionTransaction.h, fdbserver/storageserver.actor.cpp
cherry-pick https://github.com/apple/foundationdb/pull/8994
=> Remove boundaryAndExist (release-7.2)

documentation/sphinx/source/mr-status-json-schemas.rst.inc, fdbclient/IdempotencyId.actor.cpp, fdbclient/Schemas.cpp, fdbclient/include/fdbclient/IdempotencyId.actor.h, fdbserver/Status.actor.cpp
=> Add .cluster.idempotency_ids to status json

fdbclient/include/fdbclient/MetaclusterManagement.actor.h
As a result of a recent bug fix, the code to remove tenants was reorganized. As a result, attempting to remove the rename destination of a tenant now triggers an assert.
This change properly rejects that removal prior to the failing assertion.
=> Properly reject tenant deletion for the rename destination of a tenant

fdbserver/worker.actor.cpp
=> [release 7.2] fix health monitor last logged time

fdbserver/worker.actor.cpp
=> [release 7.1] fix health monitor last logged time

fdbserver/MockGlobalState.actor.cpp, fdbserver/include/fdbserver/StorageMetrics.actor.h
These code coverage gaps have been fixed, so any future misses indicate a regression.
=> Remove outdated rare code probe annotations

fdbclient/include/fdbclient/CommitProxyInterface.h, fdbserver/ClusterController.actor.cpp, fdbserver/Coordination.actor.cpp, fdbserver/include/fdbserver/ClusterController.actor.h, fdbserver/worker.actor.cpp
This field is no longer needed so it should be removed
=> Remove ClientDBInfo Encryption State

fdbserver/ClusterController.actor.cpp, fdbserver/include/fdbserver/ClusterController.actor.h
=> [release 7.2] Disconnection to satellite TLog should trigger recovery in gray failure detection

fdbserver/ClusterController.actor.cpp, fdbserver/ClusterController.actor.h
=> [release 7.1] Disconnection to satellite TLog should trigger recovery in gray failure detection

fdbserver/fdbserver.actor.cpp, fdbserver/worker.actor.cpp, flow/SystemMonitor.cpp, flow/include/flow/SystemMonitor.h
=> Trace data hall id in `MachineMetrics` events

fdbserver/include/fdbserver/workloads/MetaclusterConsistency.actor.h
The metacluster consistency check didn't account for the possibility that a partially applied operation could leave the set of tenant groups different between the management cluster and a data cluster. 
This also updates the metacluster consistency check to use comparison based asserts, where appropriate.
=> Fix metacluster consistency check tenant group assertion failure

fdbclient/NativeAPI.actor.cpp
Fixing merge issue after my PR was out of date with main
=> tenant entry was removed, changed to fixme

fdbclient/ServerKnobs.cpp, fdbclient/include/fdbclient/ServerKnobs.h, fdbserver/ClusterRecovery.actor.cpp, fdbserver/TLogServer.actor.cpp, fdbserver/TagPartitionedLogSystem.actor.cpp
=> [Release 7.2] Add event for txn server initialization and a warning for TLog slow catching up

fdbclient/ServerKnobs.cpp, fdbclient/ServerKnobs.h, fdbserver/ClusterRecovery.actor.cpp, fdbserver/TLogServer.actor.cpp, fdbserver/TagPartitionedLogSystem.actor.cpp
=> [Release 7.1] Add event for txn server initialization and a warning for TLog slow catching up

fdbclient/FileBackupAgent.actor.cpp, fdbrpc/TokenCache.actor.cpp, fdbrpc/TokenSign.cpp
Code coverage has been improved for several code probes, so the rare annotation can be removed, in order to detect future regressions.
=> Remove more rare code probe annotations

CMakeLists.txt, bindings/c/CMakeLists.txt, tests/TestRunner/binary_download.py
=> Version Bump from 71.2.4 to 71.2.5

fdbserver/storageserver.actor.cpp
Passed 50k BlobGranule* correctness tests.
=> Better feed version semantics documentation, and a bug fix

documentation/sphinx/source/release-notes/release-notes-710.rst
=> Add 7.1.26, 7.1.27 release notes

documentation/sphinx/source/release-notes/release-notes-710.rst
cherrypick #9187
Documentation only change
=> Add 7.1.26, 7.1.27 release notes [release-7.1]

design/idempotency_ids.md
=> Add design for avoiding storage servers for idempotency ids

tests/rare/FuzzTest.toml
Solves issue https://github.com/apple/foundationdb/issues/9202
=> Remove database involvement from ActorFuzz test

fdbserver/KeyValueStoreRocksDB.actor.cpp, fdbserver/include/fdbserver/StorageMetrics.actor.h, fdbserver/storageserver.actor.cpp
Added metrics for read range operations.
=> Added metrics for read range operations.

contrib/local_cluster/README.md, contrib/local_cluster/binding_test.py, contrib/local_cluster/lib/__init__.py, contrib/local_cluster/lib/cluster_file.py, contrib/local_cluster/lib/fdb_process.py, contrib/local_cluster/lib/local_cluster.py, contrib/local_cluster/lib/process.py, contrib/local_cluster/lib/work_directory.py, contrib/local_cluster/local_cluster.py
=> Scripts to start a local cluster and run binding test in batch

fdbclient/CommitProxyInterface.cpp, fdbclient/include/fdbclient/CommitProxyInterface.h, fdbclient/include/fdbclient/CoordinationInterface.h, fdbrpc/include/fdbrpc/fdbrpc.h, fdbserver/include/fdbserver/MasterInterface.h, fdbserver/include/fdbserver/WorkerInterface.actor.h, fdbserver/masterserver.actor.cpp, fdbserver/worker.actor.cpp, flow/Hostname.actor.cpp, flow/flow.cpp, flow/include/flow/Hostname.h
This patch reduces about 5% of compile time furthur.
=> `extern template` various classes to reduce compile time

fdbrpc/FlowTransport.actor.cpp
=> [Release 7.1] Log PingLatency when there is no ping latency samples, but ping attempts

fdbrpc/FlowTransport.actor.cpp
=> [release 7.2] Log PingLatency when there is no ping latency samples, but ping attempts

fdbclient/CommitProxyInterface.cpp, fdbclient/NativeAPI.actor.cpp, fdbclient/include/fdbclient/ClusterInterface.h, fdbclient/include/fdbclient/CommitProxyInterface.h, fdbclient/include/fdbclient/CoordinationInterface.h, fdbrpc/TokenSign.cpp, fdbrpc/include/fdbrpc/fdbrpc.h, fdbserver/include/fdbserver/MasterInterface.h, fdbserver/include/fdbserver/ServerDBInfo.actor.h, fdbserver/include/fdbserver/WorkerInterface.actor.h, fdbserver/masterserver.actor.cpp, fdbserver/worker.actor.cpp, flow/Hostname.actor.cpp, flow/flow.cpp, flow/include/flow/FastRef.h, flow/include/flow/Hostname.h, flow/include/flow/ObjectSerializer.h, flow/include/flow/serialize.h, flow/serialize.cpp
=> Reduce the compile time of FoundationDB by using extern template and refactoring (release-7.2)

fdbclient/include/fdbclient/VersionedMap.h
=> Avoid repeated search in VersionedMap::erase(iterator)

fdbcli/AuditStorageCommand.actor.cpp, fdbcli/GetAuditStatusCommand.actor.cpp, fdbclient/include/fdbclient/Audit.h, fdbclient/include/fdbclient/StorageCheckpoint.h
Add explanation of command return. Amend return format (slightly).
=> Edit of audit_storage usage and help message.

flow/FastAlloc.cpp, flow/test_memcpy_perf.cpp
=> Fix compilation errors in Windows

documentation/sphinx/source/command-line-interface.rst
Added documentation for `consistencyscan` command and added a note about it to the `consistencycheck` command which is much harder to deploy.  
The changes render as follows:
=> Documentation for consistencyscan CLI command.

fdbserver/BlobManifest.actor.cpp
Add \xff/metadataVersion to blob manifest backup
=> Add metadataVersion to manifest backup

bindings/c/test/apitester/run_c_api_tests.py, tests/TestRunner/local_cluster.py, tests/TestRunner/tmp_cluster.py
Was modifying these files as part of a separate PR and black/flake reformatted them. So to make the diff in the other PR obvious, I made this PR that's just reformatting the files (and fixing a bare except clause it complained about) with no other changes.
=> formatting files

fdbclient/ServerKnobs.cpp
=> Enable `GLOBAL_TAG_THROTTLING` by default

bindings/c/test/apitester/run_c_api_tests.py, bindings/c/test/apitester/tests/CApiBlobGranuleCorrectnessMultiThr.toml, bindings/c/test/apitester/tests/CApiBlobGranuleTenantCorrectnessMultiThr.toml, bindings/c/test/apitester/tests/CApiBlobGranuleTenantEncryptionCorrectnessMultiThr.toml, tests/TestRunner/local_cluster.py, tests/TestRunner/tmp_cluster.py
Adding encryption at rest support to api tester and cluster scripts
=> adding encryption at rest support to local cluster and api tester

fdbclient/BlobCipher.cpp, fdbclient/BlobGranuleFiles.cpp, fdbclient/include/fdbclient/BlobCipher.h, tests/slow/BlobGranuleCorrectness.toml, tests/slow/BlobGranuleCorrectnessClean.toml
Description
Patch update BlobGranule encryption code to support Configurable encryption semantics
Testing
BlobGranuleCorrectness* - 100K
=> EaR: Configurable Encryption feature support for BlobGranules

fdbcli/StatusCommand.actor.cpp
=> Since FDB now limits memory by RSS, report RSS in `status details` view.

fdbserver/VersionedBTree.actor.cpp
Revert XOR encoding enabling logic to be compatible with pre-7.3 Redwood. This would fixing the CI failing with RedwoodBTreeUnexpectedNodeEncoding on downgrade test back to 7.1/7.2.
=> Redwood: fix restart test failure with XOR encoding

fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp
The intent of the test was to detect when you try to create the same tenant with a different assigned cluster and retry, but in certain rare cases it would not correctly detect what the original stored assignment was.
=> Fix logic in MetaclusterManagementWorkload when retrying a tenant creation with an invalid assigned cluster

fdbserver/storageserver.actor.cpp
backport https://github.com/apple/foundationdb/pull/9330
=> Fix getMappedRange metrics(release-7.2)

fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp
The fix from #9355 introduced a new problem that could occur when the create timed out but later succeeded. This addresses the problem by removing the cluster that caused the failure from the list of choices.
=> Try again to fix the logic in choosing the assigned cluster in the metacluster management test

fdbclient/include/fdbclient/MetaclusterManagement.actor.h
The metacluster restore reconcile transactions can be run in parallel for improved throughput
=> Run metacluster restore reconcile transactions in parallel

fdbclient/BlobCipher.cpp
Fixes Valgrind error "conditional jump depends on uninitialised value".
The root cause is comparing data against variable-length arrays that have been incompletely initialized.
=> Fix Valgrind error on BlobCipherUnitTest

fdbclient/BackupAgentBase.actor.cpp, fdbclient/BlobCipher.cpp, fdbclient/ClientKnobs.cpp, fdbclient/include/fdbclient/BlobCipher.h, fdbclient/include/fdbclient/CommitTransaction.h, fdbclient/include/fdbclient/GetEncryptCipherKeys.actor.h, fdbserver/BackupWorker.actor.cpp, fdbserver/CommitProxyServer.actor.cpp, fdbserver/KeyValueStoreMemory.actor.cpp, fdbserver/RestoreLoader.actor.cpp, fdbserver/SimulatedCluster.actor.cpp, fdbserver/StorageCache.actor.cpp, fdbserver/fdbserver.actor.cpp, fdbserver/storageserver.actor.cpp, fdbserver/workloads/SaveAndKill.actor.cpp, tests/TestRunner/local_cluster.py
Description
Major changes includes:
1. Update the code involved in ensuring Tlog mutation encryption to be
compliant with "configurable encryption" feature.
2. Enable ChangeFeed encryption to be compliant with "configurable encryption" feature.
3. Update ENABLE_CONFIGURABLE_ENCRYPTION flag to be 'true' by default
and BUGGIFY it.
Testing
=> EaR: Configurable encryption support for Tlog mutations

fdbclient/include/fdbclient/FDBTypes.h, flow/Platform.actor.cpp
Filesystems commonly reserve 5% of space which FDB would not be able to use, so do not include this space in the `total` space for the disk.
=> Adjust reported total space for a disk by the reserved space which normal users cannot use.

fdbserver/workloads/EncryptionOps.actor.cpp
Description
Fix ASAN build OOM failure while running OOM error. Patch addresses the issue by avoiding using a global arena shortening the lifecycle of allocation per iteration. Recently test was extended to support 'configurable encryption' codepath coverage, hence, per iteration the memory allocation was doubled.
Testing
EncryptionOps - ASAN compatible
=> EaR: Fix ASAN OOM failure - EncryptionOps

fdbclient/RESTClient.actor.cpp
Description
Reduce the logging level to SevDebug for RESTClient operation
Testing
compiles
=> EaR: Reduce logging level for RESTClient

fdbclient/ServerKnobs.cpp, fdbclient/include/fdbclient/ServerKnobs.h, fdbserver/VersionedBTree.actor.cpp
=> Optimize/fix node rebuild vs update trigger in Redwood (Cherry pick #9419 to snowflake/release-71.2)

fdbclient/include/fdbclient/FDBTypes.h, flow/Platform.actor.cpp
=> Adjust reported total space for a disk by the reserved space which normal users cannot use. (Cherry-pick #9396 to snowflake/release-71.2)

fdbclient/Metacluster.cpp, fdbclient/MetaclusterManagement.actor.cpp, fdbclient/include/fdbclient/KeyBackedTypes.h, fdbclient/include/fdbclient/Metacluster.h, fdbclient/include/fdbclient/MetaclusterManagement.actor.h, fdbclient/include/fdbclient/Tenant.h, fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp, fdbserver/workloads/MetaclusterRestoreWorkload.actor.cpp, fdbserver/workloads/TenantManagementConcurrencyWorkload.actor.cpp, fdbserver/workloads/TenantManagementWorkload.actor.cpp
Add testing of concurrent restores to the metacluster restore workload
=> Metacluster concurrent restore testing

fdbserver/SimulatedCluster.actor.cpp, fdbserver/coroimpl/CoroFlow.actor.cpp, flow/SystemMonitor.cpp, tests/fast/DataLossRecovery.toml
=> [snowflake/release-71.2] Lower ASAN memory usage

CMakeLists.txt, bindings/c/CMakeLists.txt, tests/TestRunner/binary_download.py
=> Version Bump from 71.2.5 to 71.2.6

fdbserver/workloads/BlobGranuleCorrectnessWorkload.actor.cpp
I encountered a bug with blob granule reads and tenant opening as a part of developing #9401 that simulation didn't catch but the API tester did. I had accidentally removed the tenant wait on ready as part of my refactoring https://github.com/apple/foundationdb/pull/9401/files#diff-b7ff0437a8e8c0dc97c77966a6f3de16478c9bb49abab8effdaf45a3b490815cR8185, which caused the later request to be made with the unknown tenant id instead of the correct one.
To ensure that simulation catches this, I added a random buggified renant re-opening, which reproduced the problem in ~1/4 BlobGranuleCorrectness* tests when I un-fixed the bug.
Now this passes 10k BlobGranuleCorrectness* tests when I add the fix back.
Doing the same type of testing more generically might be tricky though so I didn't attempt it. …
=> add tenant reopen to ensure no races with tenant opening

fdbserver/workloads/TenantLock.actor.cpp
A transaction in the tenant lock test read a key, verified that it's value matched expectation, and then wrote it with a new value. If this transaction is committed with an unknown result, the value verification would fail.
=> Fix maybe committed issue in tenant lock test

fdbclient/SpecialKeySpace.actor.cpp
Improve space estimation in checkExclusion()
=> Improve space estimation in checkExclusion()
