apple/foundationdb

fdbmonitor/CMakeLists.txt

If property LINK_OPTIONS or COMPILE_OPTIONS doesn't exist,  `fdbmonitor_options` will be set to `fdbmonitor_options-NOTFOUND`, which result to fdbmonitor link failure.
```
clang: error: no such file or directory: 'fdbmonitor_options-NOTFOUND'
```
Not sure why previous CI didn't find this issue until #6737 .

fix cmake bug when no link or compile options

---

bindings/c/test/unit/unit_tests.cpp
fdbserver/storageserver.actor.cpp
flow/error_definitions.h

- Throws specific exception instead of a more general error type.
- Log the violating bytes
- Make SS not retry/hang on this kind of errors
- Add and fix tests 

Fixes for when getMappedRange cannot parse as tuple

---

fdbclient/ClientKnobs.cpp
fdbclient/ClientKnobs.h
fdbclient/ServerKnobs.cpp
fdbserver/MoveKeys.actor.cpp

And add ENABLE_PARTITIONED_TRANSACTIONS in client knobs.
20220401-235426-zhewu_6747-7fccd874bccd3d1a        compressed=True data_size=30656791 duration=5248394 ended=89640 fail=10 fail_fast=10 max_runs=100000 pass=89630 priority=100 remaining=0 runtime=1:01:29 sanity=False started=92555 stopped=20220402-005555 submitted=20220401-235426 timeout=5400 username=zhewu_6747

Turn off TAG_ENCODE_KEY_SERVERS when PTXN is enabled

---

fdbclient/ClientKnobs.cpp
fdbclient/ServerKnobs.cpp

It turns out randomize gets set in not simulation. Fixing these to only change with buggify and additional guard on isSimulated

fixing shard size knobs outside of simulation

---

fdbserver/tester.actor.cpp

In commit 99b030c2f63a3c9ad92ed56aa2b5709322a4cb06, it is allowed to set
knob values in TOML file per single test, using syntax
```
[[test]]
[[test.knobs]]
knob_key = knob_value
```
the knob key/value pairs are changed before the TEST_CASE starts, then
reverted after TEST_CASE completes.
With this patch, it is possible to *globally* update the knob value,
e.g.
```
[[knobs]]
enable_encryption = true
[[test]]
testTitle = 'EncryptKeyProxy'
[[test.workload]]
testName = 'EncryptKeyProxyTest'
```
This is manually tested by printing out knob key/value pairs. Also
tested using Ata's EncryptKeyProxy test code by enabling
enable_encryption key.
Please check …

Allowing globally knob change in TOML file based test

---

fdbclient/GenericManagementAPI.actor.h
fdbclient/HighContentionPrefixAllocator.actor.h
fdbclient/NativeAPI.actor.h
flow/ThreadHelper.actor.h

When wrapping a standalone type, the memory for some ThreadFutures may be held by the ThreadFuture itself rather than the standalone. While we should aim to fix this, for the time being I've added some protection that makes it a compiler error to pass an anonymous thread future to `safeThreadFutureToFuture` when that thread future wraps a standalone type. For example, the following is now an error:
```
safeThreadFutureToFuture(tr.getRange(...)); 
```

Disallow anonymous standalone thread futures in safeThreadFutureToFuture

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/KeyValueStoreRocksDB.actor.cpp

Previously, performance metrics related to RocksDB is everywhere in the code, which is not well organized and makes the metrics hard to manage.
This PR refactors performance metrics related to RocksDB:
(1) Create an object `RocksDBMetrics` dedicated to any performance metric of RocksDB, including: RocksDB Statistics, RocksDB Property, Read/Write Iterator Pool Statistics, RocksDB PerfContext, Latency Histogram.
(2) Add a new function which collects memory usage by each RocksDB instance. As a result, we could know the memory usage for each shard, given that different active shard uses different RocksDB instance.
| Metric Type  | Scope | TraceEvent | How to open | 
| ------------- | ------------- | ------------- | ------------- |
| RocksDB Statistics  | Aggregation of all DB shards | …

RocksDB Performance Metrics

---

fdbbackup/FileDecoder.actor.cpp
fdbbackup/backup.actor.cpp
fdbcli/fdbcli.actor.cpp
fdbclient/IKnobCollection.cpp
fdbclient/IKnobCollection.h
fdbserver/fdbserver.actor.cpp

No functional changes to `fdbserver` and `fdbcli`. Added an option to `fdbdecode` for saving processed files and fixed a memory corruption issue in clang build.
Manually verified `fdbserver`, `fdbdecode` binaries worked with knob values.

Refactor duplicated code into IKnobCollection::setupKnobs()

---

fdbserver/BlobWorker.actor.cpp
fdbserver/storageserver.actor.cpp

Passed 100k blob granule correctness tests

blob workers properly destroy change feeds when they are no longer needed

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/worker.actor.cpp

This still requires the txn sub system in at least accept_commit phase.
connectFailedCount is already tracked in `peer`.
Next, we need to track destroyed peers due to connection failure.
20220405-055334-zhewu_6763-16cb0bd280f64159

Making gray failure monitor also takes connection failures into account

---

tests/CMakeLists.txt
tests/restarting/from_7.1.0/VersionVectorDisableRestart-1.toml
tests/restarting/from_7.1.0/VersionVectorDisableRestart-2.toml
tests/restarting/from_7.1.0/VersionVectorEnableRestart-1.toml
tests/restarting/from_7.1.0/VersionVectorEnableRestart-2.toml

This is a restarting test to verify that we can safely enable or disable VV with knob changes.
This PR depends on #6597 and #6751, both have been merged into VV branch.
100k these restarting tests, found 3 timeout for `VersionVectorEnableRestart-2.toml`, the first two are probably the existing issue related to blocking peek timeout, the last one is due to "Failed to extract MaxStorageServerQueue" for `QuietDatabaseConsistencyCheckStartError`.
-r simulation --crash --logsize 1024MB -f ./foundationdb/tests/restarting/from_7.1.0/VersionVectorEnableRestart-1.toml -s 696635965 -b on
-r simulation --crash --logsize 1024MB -f ./foundationdb/tests/restarting/from_7.1.0/VersionVectorEnableRestart-2.toml -s 696635966 -b on --restarting
-r simulation --crash --logsize 1024MB -f …

Add a test for turning off version vector feature

---

fdbbackup/FileConverter.h
fdbbackup/FileDecoder.actor.cpp

`fdbdecode` changes only. I've manually tested the backup files can be saved.

Added an option to fdbdecode for saving processed files and fixed a memory corruption issue in clang build

---

fdbclient/DatabaseConfiguration.cpp
fdbclient/DatabaseConfiguration.h
fdbserver/ClusterRecovery.actor.cpp

fix #6715 
pass 100k
The reason why the recruiteStorage is in an endless loop is that it keeps getting AttemptedDoubleRecruitment when it wants to initialize the worker. The worker had been a storage server b10a but this storage server is removed by DD because DD thought b10a is failed. However, even after the removeStorageServer transaction, b10a didn't realize it was removed.
Why b10a doesn't realize it? Because removeStorageServer is an Emergency Transaction, which means it's part of the Recovery Transaction, the commit version of this transaction is the newEpochStartVersion = RecoveryVersion+100M. The b10a first popped it's tag from the oldLogSystem when it realized the recovery happened, note at this time, b10a didn't peek up to newEpochVersion. Then the oldLogSystem is destructed …

Make Emergency Transaction only add mutations can change configuration (solve #6715)

---

fdbserver/ApplyMetadataMutation.cpp
fdbserver/ClusterController.actor.cpp
fdbserver/MoveKeys.actor.cpp
fdbserver/masterserver.actor.cpp

- Currently private team is populated twice in storageServerToTeam. So don't include it in seed server recruitment
- private team's storageTeam is not set up correctly.
- Disable betterMasterExist(), since we don't support recovery yet.

Address 3 issues in PTXN

---

fdbbackup/FileDecoder.actor.cpp

Fix broken Windows build by #6767

Add missing Windows headers for `FileDecoder.actor.cpp`

---

fdbclient/CoordinationInterface.h
fdbrpc/genericactors.actor.h
fdbserver/ConfigFollowerInterface.h
fdbserver/CoordinationInterface.h
flow/Hostname.actor.cpp
flow/Hostname.h

20220405-231050-renxuan-d1354993a5ff759c           compressed=True data_size=30997579 duration=5321771 ended=100000 fail=2 fail_fast=10 max_runs=100000 pass=99998 priority=100 remaining=0 runtime=0:50:45 sanity=False started=100173 stopped=20220406-000135 submitted=20220405-231050 timeout=5400 username=renxuan

Add tryGetReplyFromHostname() and retryGetReplyFromHostname().

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbrpc/HealthMonitor.actor.cpp
fdbrpc/HealthMonitor.h
fdbserver/worker.actor.cpp

As observed in real cluster testing, when a worker is having trouble connecting to another worker, sometimes it destroys the worker (remove the corresponding `peer` object from its network). In such case, the worker's health monitor will miss such connection failure.
Therefore, this PR also examines all the recent closed peers and find out those that are destroyed. If any of them are in the cluster's transaction sub system, report it to the cluster controller.
This feature is guarded by a knob and can be easily disabled.
20220406-054035-zhewu_6774-9143bba0921a9f60        compressed=True data_size=30771268 duration=5921307 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:11:06 sanity=False started=100130 stopped=20220406-065141 …

Allow worker health monitor to report recent destroyed peers

---

fdbserver/worker.actor.cpp
tests/fast/PhysicalShardMove.toml

The change explicitly disables remote kvs in simulation even if the knob is set.
Clear unnecessary test parameter after this.

Disable remote kvs if RocksDB is used

---

fdbserver/Resolver.actor.cpp

Remove duplicate decodeKeyServersValue call in resolver

---

fdbserver/TLogGroup.actor.cpp
fdbserver/ptxn/TLogServer.actor.cpp
fdbserver/worker.actor.cpp

- Fix missing TLogWorkerData reference counting
- getStorageTeamData() needs to make sure not creating new StorageTeamData(). This is an assertion in the code.
- Move endRole from LogGenerationData to where tlogCore return, which matches beginRole. Otherwise, endRole maybe called before beginRole is called.
- Fix tlog keyvalue store file name.

Various fixes in ptxn

---

flow/FastAlloc.h

I added a field to the `StorageServer` struct and started seeing the assertion in `nextFastAllocatedSize` fail. It seems there are so many fields in `StorageServer` now that 8192 bytes is not enough to allocate an instance of it. This PR doubles the byte limit.

Double existing FastAlloc limit

---

fdbcli/ConfigureCommand.actor.cpp
fdbclient/GenericManagementAPI.actor.h

Adding warning message on configuring rocksdb storage until production tested. This is basically a warning message for the open source community to be cautious.
Simulation testing passed.
Fdbmonitor testing:
fdb> configure new single ssd-rocksdb-v1
Database created
WARN: RocksDB storage engine type is still in experimental stage, not yet production tested.
fdb> configure ssd
Configuration changed
fdb> configure ssd-rocksdb-v1
Configuration changed
WARN: RocksDB storage engine type is still in experimental stage, not yet production tested. …

Adding warning on configuring rocksdb storage until production tested.

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/ClusterController.actor.cpp
fdbserver/ClusterController.actor.h
fdbserver/WorkerInterface.actor.h
fdbserver/worker.actor.cpp

This PR adds satellite worker monitor in FDB's gray failure monitoring and recovery.
In addition to single bad link, this PR tries to detect whether the entire connection between primary DC and satellite DC is bad. This is done by checking if enough number of satellite tlog workers got complained.
If so, a failover is suggested.
20220407-215419-zhewu_6792_correctness-d7ac5fa2b6fbc783 compressed=True data_size=30783291 duration=5162614 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:15:46 sanity=False started=100170 stopped=20220407-231005 submitted=20220407-215419 timeout=5400 username=zhewu_6792_correctness
20220407-233011-zhewu_6792_val-01fc101340134959    compressed=True data_size=30803237 duration=658974 ended=1000 fail_fast=10 …

Grey failure monitors satellite workers

---

fdbclient/MultiVersionTransaction.actor.cpp

This adds API version checking before attempting a map entry clear and avoids default constructing any elements in the shared state map when an upgrade is detected.

Provided additional safety checks in the upgrade scenario for GRV cache in MVC

---

fdbserver/workloads/ConfigureDatabase.actor.cpp
tests/restarting/from_7.1.0/ConfigureStorageMigrationTestRestart-2.toml
tests/restarting/to_7.1.0/ConfigureStorageMigrationTestRestart-2.toml

Fix: 
Commit: `465ff712b63eb78f13044a3dc68e2d63fd6c487c`
The restart-2 change the storage engine and replica which cannot be achieved without adding more SS and enabling perpetual wiggle. 
The fix is just changing the test to make it always simulate the reasonable configuration change.
```
| C | restarting/from_7.1.0/ConfigureStorageMigrationTestResta | F | 883463378 |
| C | restarting/from_7.1.0/ConfigureStorageMigrationTestResta | F | 883463379 |
```

Enforce storage migration compatible config in restarting test

---

bindings/c/fdb_c.cpp
documentation/sphinx/source/release-notes/release-notes-700.rst
documentation/sphinx/source/release-notes/release-notes-710.rst
fdbclient/MultiVersionTransaction.actor.cpp

Deprecate `fdb_transaction_get_range_and_flat_map` which was introduced prematurely in 7.0, in preference of `fdb_transaction_get_mapped_range` in 7.1.

Fixes #6793: Upgrade from 7.0.0 to 7.1.0 fails because of missing function fdb_transaction_get_mapped_range

---

fdbserver/workloads/EncryptionOps.actor.cpp
flow/BlobCipher.cpp
flow/BlobCipher.h
flow/EncryptUtils.h
flow/error_definitions.h

Description
Major changes proposed are:
1.Encryption header support two modes of generation 'authentication tokens':
a) SingleAuthTokenMode: the scheme generates single crypto-secure auth
token to protect {cipherText + header} payload. Scheme is geared towards
optimizing cost due to crypto-secure auth-token generation, however,
on decryption client needs to be read 'header' + 'encrypted-buffer'
to validate the 'auth-token'. The scheme is ideal for usecases where
payload represented by the encryptionHeader is not large and it is
desirable to minimize CPU/latency penalty due to crypto-secure ops,
such as: CommitProxies encrypted inline transactions,
StorageServer encrypting pages etc.
b) MultiAuthTokenMode: Scheme generates separate authTokens for
'encrypted buffer' & 'encryption-header'. …

Encryption header authentication tokens

---

flow/TDMetric.actor.h

ScopeEventFieldTypeMismatch trace event occurs when the detail field gets duplicates. Making it a Sev40 for simulation only runs to catch such duplicates in simulation.
Ran 100K simulation tests.

Convert the ScopeEventFieldTypeMismatch event to a Sev40 in simulation.

---

cmake/FindGperftools.cmake

Otherwise, I got weird errors like pthread library is not found when checking
compilers.

Fix cmake USE_GPERFTOOLS compiling error

---

fdbserver/KeyValueStoreRocksDB.actor.cpp

Two changes:
- Use `GetAggregatedIntProperty` instead of `GetIntProperty` to get RocksDB properties.
GetAggregatedIntProperty gets the sum of all column families.
GetIntProperty gets the value of the rocksdb default column family (name="default" but we are using name="fdb").
See: [GetIntProperty and GetAggregatedIntProperty](https://github.com/facebook/rocksdb/blob/633b7f15d5938ce509686916f2edb6dd8d0e3516/include/rocksdb/db.h#L1130-L1132)
- Add `LiveSstFilesSize` to `RocksDBMetrics`.

Fix RocksDB Metrics

---

bindings/java/fdbJNI.cpp
bindings/java/src/main/com/apple/foundationdb/Database.java
bindings/java/src/main/com/apple/foundationdb/FDBDatabase.java

Java bindings for BG purge calls. Not sure how to best test them but it compiles?

Java bindings for BG Purge

---

fdbserver/workloads/ConfigureDatabase.actor.cpp

#6806 follow up.
For `self->storageMigrationCompatibleConf`, [0,3) and [4,8) are valid because it's use for restarting test, in `restart-2` test the perpetual wiggle and storage migration setting are expected to be the same as `restart-1`.

fix configure workload typo

---

bindings/go/README.md
bindings/go/src/fdb/database.go
bindings/go/src/fdb/fdb_test.go

Add support for the `fdb_database_reboot_worker` method in the go bindings. I did some testing with the [fdb-kubernetes-operator](https://github.com/FoundationDB/fdb-kubernetes-operator) to ensure everything works.

Add support for the reboot command in go bindings

---

fdbserver/ptxn/MutableTeamPeekCursor.actor.h
fdbserver/ptxn/TLogPeekCursor.actor.cpp
fdbserver/ptxn/TLogPeekCursor.actor.h
fdbserver/ptxn/test/FakeTLog.actor.cpp
fdbserver/ptxn/test/TestTLogPeek.actor.cpp
fdbserver/storageserver.actor.cpp
tests/ptxn/TLogPeekCursor.toml

This is a fix to let recent cursor code change passes the unit test.

fixup! Fix the StorageTeamPeekCursor versioning

---

fdbclient/ServerKnobs.cpp
fdbserver/SimulatedCluster.actor.cpp

This is to reduce noise of correctness due to known issues in fault injection.

Disable remote KVS feature in simulation

---

fdbserver/ptxn/TLogPeekCursor.actor.cpp
fdbserver/ptxn/TLogPeekCursor.actor.h

This is a temporary solution to make StorageTeamPeekCursor to not lose data after Reset().
This will be replaced once we switch to use ArenaReader in `TwoLevelHeaderedItemsDeserializer`.
20220412-052437-zhewu_6835-4dada5e168429949        compressed=True data_size=30653842 duration=5592294 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=0:54:15 sanity=False started=100095 stopped=20220412-061852 submitted=20220412-052437 timeout=5400 username=zhewu_6835

Use a storageTeamCursor wide arena to hold the data

---

fdbclient/CMakeLists.txt
fdbclient/VersionVector.cpp
fdbclient/VersionVector.h
fdbserver/workloads/UnitTests.actor.cpp

Encode version vector before sending it over the wire.
Encoding methods used:
- Tag localities: Run length encoding
- Tag ids: Compact representation
- Commit versions: delta encoding.
If "n" is the number of entries in the version vector, with the tags
spread over "m" data centers, these techniques will reduce the number
of bytes to represent the version vector from "(11 * n)" bytes to
"(3 * m + 2 * n)" / "(3 * m + 3 * n)" bytes (depending on the max tag
id value, and ignoring some constants) in the best case.
Simulation tests (with version vector knobs enabled): 20220411-180801-sre-ff47af81926ae76f (no failures).
Simulation tests (with version vector knobs disabled): 20220412-151453-sre-bc5b13576cd093a2 (no failures). …

Version vector encoding

---

fdbserver/ClusterRecovery.actor.cpp

This was not set and can cause infinite loop in simulation where the client
calls getConsistentReadVersion(), in which we do "continue" for stale GRV reply
and retry. Then this repeats forever.
Found by @sfc-gh-satherton and @sfc-gh-etschannen .
To reproduce
compiler: clang
commit: 01234720
seed: -r simulation -f ./foundationdb/tests/slow/ParallelRestoreNewBackupCorrectnessAtomicOp.toml -s 504847191 -b on

Fix provisional GRV Proxy ID in GetReadVersionReply

---

fdbserver/ClusterRecovery.actor.cpp

cherry-pick: #6848
This was not set and can cause infinite loop in simulation where the client
calls getConsistentReadVersion(), in which we do "continue" for stale GRV reply
and retry. Then this repeats forever.
20220413-043547-jzhou-d2bd49c0585b1762

7.1 cherry-pick: Fix provisional GRV Proxy ID in GetReadVersionReply

---

fdbcli/fdbcli.actor.cpp
flow/ThreadHelper.actor.h

Previously a few catch blocks did not properly propagate operation_cancelled, which caused some code to run after the network had stopped. Also allow broken_promise in the ASSERT for `safeThreadFutureToFutureImpl` since it's not necessarily an error to call safeThreadFutureToFutureImpl after the network is stopped (although it's certainly not useful to do so)

Fix an ASSERT when an fdbcli command times out

---

fdbserver/ptxn/MutableTeamPeekCursor.actor.h
fdbserver/ptxn/test/TestTLogPeek.actor.cpp
fdbserver/storageserver.actor.cpp

make mutablePeekCursor takes a list of storage teams as an input.
This is a hacky version of the change, which has been proven to pass the cycle test. @xis19 is working on the actual fix.
20220413-050736-zhewu_6850-c7e8e5a10e83da6f

make mutablePeekCursor takes a list of storage teams as an input

---

fdbclient/ClientKnobCollection.h
fdbclient/IKnobCollection.h
fdbclient/ServerKnobCollection.h
fdbclient/TestKnobCollection.h
fdbserver/CMakeLists.txt
fdbserver/KnobProtectiveGroups.cpp
fdbserver/KnobProtectiveGroups.h
fdbserver/Knobs.h
fdbserver/tester.actor.cpp
fdbserver/workloads/workloads.actor.h
flow/Knobs.cpp
flow/Knobs.h

This patch allows manually override knob values in TOML files.
See
- https://github.com/apple/foundationdb/pull/6597
- https://github.com/apple/foundationdb/pull/6751

Allows temporarily modify knobs in test TOML files

---

fdbserver/KeyValueStoreRocksDB.actor.cpp

RocksDb using aggregated property metrics for pendingCompactionBytes.
GetAggregatedIntProperty gets the aggregated int property from all column families. Previously we were using getIntProperty and it returns only default column family metrics which is not correct.

RocksDb using aggr property metrics for pendingCompactionBytes.

---

bindings/c/CMakeLists.txt

Upgrade tests are using binaries of old FDB versions. These binaries are downloaded from the release repository and are thus not instrumented by the sanitizer, and thus cannot be used in sanitizer builds.

Disable upgrade tests in sanitizer builds

---

fdbclient/MonitorLeader.actor.cpp
fdbserver/worker.actor.cpp

The ClientDBInfo's comparison is through an internal UID and shrinkProxyList()
can change proxies inside ClientDBInfo. Since the UID is not changed by that
function, subsequent set can be unintentionally skipped.
This was not a big issue before. However, VV introduces a change that the
client side compares the returned proxy ID with its known set of GRV proxies
and will retry GRV if the returned proxy ID is not in the set. Due to the above
bug, GRV returned by a proxy is not within the client set, and results in
infinite retrying GRVs.
To reproduce: clang, commit c3c8511e1, seed fast/BlobGranuleVerifySmallClean.toml -s 934167474 -b on
100k correctness 20220416-045916-jzhou-1cb3f2053f483bdd passed. …

ClientDBInfo may be unintentionally not set

---

fdbclient/MonitorLeader.actor.cpp
fdbserver/worker.actor.cpp

Cherrypick #6877
The ClientDBInfo's comparison is through an internal UID and shrinkProxyList()
can change proxies inside ClientDBInfo. Since the UID is not changed by that
function, subsequent set can be unintentionally skipped.
This was not a big issue before. However, VV introduces a change that the
client side compares the returned proxy ID with its known set of GRV proxies
and will retry GRV if the returned proxy ID is not in the set. Due the above
bug, GRV returned by a proxy is not within the client set, and results in
indefinite retrying GRVs.
This fixed `fast/KillRegionCycle.toml -s 783190175 -b on` at commit c3c8511e1, clang build.
500k 20220416-051927-jzhou-release-7.1.2-995a4e09ddb61605 failed 2 (timeout, RecoveryDelayedTooManyOldGenerations), probably unrelated:
```
-r …
```

ClientDBInfo may be unintentionally not set (release-7.1)

---

fdbserver/workloads/PrivateEndpoints.actor.cpp

Some request objects don't initialize their members properly when being constructed using the default constructor. This makes valgrind unhappy.
Testing these request streams probably doesn't give us too much anyways (this test does the same thing for all private endpoints that are added), so for now I just commented those out.

Don't test requests that don't initialize properly

---

fdbserver/storageserver.actor.cpp

The real cluster upgrade tests added by @vikasgupta8 in #6651 were surfacing an upgrade failure when upgrading from FDB 7.0 -> 7.1 (or 7.2). It was due to a storage server not remembering its initial cluster version after the upgrade (it is not persisted durably).
Since the initial cluster version is always (for now) 1, we can always start at this version. In the future, this may no longer be the case, in which case we will need to instead persist the initial cluster version for upgrades. The appropriate logic can be added if/when all FDB clusters start at a version relative to time instead of at version 1.
Passed 10k `restarting/*` tests and 10k `*` tests.
Please check each …

Fix failing upgrades due to non-persisted initial cluster version

---

fdbcli/fdbcli.actor.cpp
flow/ThreadHelper.actor.h

Cherry pick https://github.com/apple/foundationdb/pull/6857 to snowflake/release-7.1
Previously a few catch blocks did not properly propagate operation_cancelled, which caused some code to run after the network had stopped. Also allow broken_promise in the ASSERT for `safeThreadFutureToFutureImpl` since it's not necessarily an error to call safeThreadFutureToFutureImpl after the network is stopped (although it's certainly not useful to do so)

Fix an ASSERT when an fdbcli command times out (snowflake/release-7.1)

---

fdbcli/fdbcli.actor.cpp
flow/ThreadHelper.actor.h

Cherry pick https://github.com/apple/foundationdb/pull/6857 to release-7.1
Previously a few catch blocks did not properly propagate operation_cancelled, which caused some code to run after the network had stopped. Also allow broken_promise in the ASSERT for `safeThreadFutureToFutureImpl` since it's not necessarily an error to call safeThreadFutureToFutureImpl after the network is stopped (although it's certainly not useful to do so)

Fix an ASSERT when an fdbcli command times out (release-7.1)

---

packaging/docker/run_ycsb.sh

The partial restart logic for the YCSB images doesn't work with the preload phase.  This deletes that, and also passes `-x` to bash so that the logs produced by the YCSB container are more useful.
I tested by backporting to release-6.3 (which is a clean backport), building the image, and using the resulting YCSB image to benchmark foundationdb-7.0.0-rc1.
I'm considering removing the .so's, etc from the YCSB image.  It'll make it much smaller, and also intentionally break misconfigured environments that try to use the YCSB image's version of the FDB drivers instead of getting matching drivers from the running version of fdbserver. …

Improve YCSB image logging; remove logic to support partial restarts

---

fdbserver/storageserver.actor.cpp

Cherry pick of #6863 to `release-7.1`.

Fix failing upgrades due to non-persisted initial cluster version (release-7.1)

---

fdbserver/storageserver.actor.cpp

Cherry pick of #6863 to `snowflake/release-7.1`.
Passed 10k correctness.

Fix failing upgrades due to non-persisted initial cluster version (snowflake/release-7.1)

---

fdbserver/workloads/EncryptionOps.actor.cpp
flow/BlobCipher.cpp
flow/BlobCipher.h

Description
Major changes:
1. Add 'salt' to BlobCipherEncryptHeader::cipherHeaderDetails.
2. During decryption it is possible that BlobKeyCacheId doesn't
contain required baseCipherDetails. Add API to KeyCache to
allowing re-populating of CipherDetails with a given 'salt'
3. Update BaseCipherKeyIdCache indexing using {BaseCipherKeyId, salt}
tuple. FDB processes leverage BlobCipherKeyCache to implement
in-memory caching of cipherKeys, given EncryptKeyProxy supplies
BaseCipher details, each encryption participant service would
generate its derived key by using different 'salt'. Further,
it is possible to cache multiple {baseCipherKeyId, salt} tuples;
for instance: CP encrypted mutations being deciphered by
StorageServer etc.
Testing
1. Update EncyrptionOps simulation test to simulate …

Update 'salt' details for EncryptHeader AuthToken details

---

fdbclient/MonitorLeader.actor.cpp
fdbserver/LogRouter.actor.cpp
fdbserver/worker.actor.cpp

Cherry-pick #6869 and #6877
There is a bug in how a log router handles streaming read:
* Log router has a `logRouterPeekStream` actor A running.
* Remote tlog detects some problem and starts another streaming connection (maybe just reuse the connection?)
* Log router now has a new `logRouterPeekStream` actor B running.
* B runs and found that popped version > reqBegin, so `LogRouterPeekPopped` . This is because A is still running and changed the popped version.
* A ends with `TLogPeekStreamEnd operation_obsolete`
* B become stuck at `wait(req.reply.onReady() && store(reply.rep, future)`, because the future was sent `Never()`.
As a result, the remote tlog can no longer retrieve data from this log router.
Fix by killing the `logRouterPeekStream` B.
The general …

7.1 Snowflake Cherry-pick: Fix stuck PeekStream actor at log routers

---

fdbserver/GrvProxyServer.actor.cpp
fdbserver/masterserver.actor.cpp

Cherry-pick pull request #6843 from "main".
Do not invoke version vector related code when the feature is disabled.
Simulation tests: 20220419-160319-sre-361f00fde5064959 (no failures).

7.1 Cherry-pick: Do not invoke version vector related code when the feature is disabled

---

fdbserver/OldTLogServer_6_0.actor.cpp
fdbserver/OldTLogServer_6_2.actor.cpp
fdbserver/TLogServer.actor.cpp

This could cause a recovery to get stuck in all_log_recruited if a storage server was removed while a pop was ongoing

fix: pops which were ignored during a snapshot would not be replayed correctly

---

bindings/c/CMakeLists.txt

Fixes: #6822
Looks like rpm/deb specs are generated by cmake/cpack and new libs are ignored due to missing CMakeLists.txt declaration

Add new c libs to client package (added to cmake configuration)

---

fdbserver/EncryptKeyProxy.actor.cpp
fdbserver/EncryptKeyProxyInterface.h
fdbserver/SimEncryptKmsProxy.actor.cpp
fdbserver/SimEncryptKmsProxy.actor.h
fdbserver/workloads/EncryptKeyProxyTest.actor.cpp

Description
Major changes include:
1. Update EKPServer LookupKeysByKeyIds API to include
'encryptDomainId' as input along with 'baseCipherId'
2. Unify EKPServer response definition to return
std::vector<EKPBaseCipherDetails>
3. Update SimKmsProxy interfaces as per above mentioned
changes.
Testing
1. Update EncryptKeyProxyTest simulation test.
2. Update SimEncryptKeyProxy unit test

Update EKPServer LookupKeysByKeyIds API

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/CMakeLists.txt
fdbserver/EncryptKeyProxy.actor.cpp
fdbserver/KmsConnector.h
fdbserver/KmsConnectorInterface.h
fdbserver/SimKmsConnector.actor.cpp
fdbserver/SimKmsConnector.actor.h
fdbserver/workloads/UnitTests.actor.cpp
flow/BlobCipher.h

Description
Major changes includes:
1. Framework code to enable FDB native KMS connector implementation.
2. SERVER_KNOBS->KMS_CONNECTOR_TYPE controls the connector type selection.
3. KmsConnectorInterface endpoint definitions, every KMSConnector
implementation needs to support defined endpoints.
4. Update EncryptKeyProxy to leverage KmsConnectorInterface endpoints
to fetch encryption keys on-demand and/or periodic refreshes.
Integrate SimKmsConnector implementation.
5. Implement SimKmsConnector by leveraging existing SimKeyProxy
implementation.
Testing
Unit test: fdbserver/SimKmsConnector
Simulation: EncryptKeyProxy …

FDB native KMS Connector Framework

---

fdbserver/EncryptKeyProxy.actor.cpp
flow/BlobCipher.h

Description
Fix Build: use boost::hash to compute hash for std::pair
Testing
1. Build - gcc/clang
2. Simulation test: EncryptKeyProxyTest, EncryptionOps
3. Unit test: flow/BlobCipher
4. Running 10k correctness Joshua run

Fix Build: use boost::hash to compute hash for std::pair

---

fdbserver/DDTeamCollection.actor.cpp
fdbserver/DDTeamCollection.h

Cherry-pick pull request https://github.com/apple/foundationdb/pull/6924 from "main".
Address the issue of the DDTeamCollection object destroyed from underneath the "storageRecruiter" actor.
Exposed by "SnapCycleRestart-1.txt" failure on release-7.1 branch:
Compiler: gcc
Commit: https://github.com/apple/foundationdb/commit/b7c05eb117bddc109eb8aa879a59573894315a94
build_output/bin/fdbserver -r simulation --crash -f /root/src/foundationdb/tests/restarting/from_7.0.0/SnapCycleRestart-1.txt -b on -s 530094113
Testing:
Simulation tests: 20220422-204941-sre-e2ee4a0e7cc1e0eb (no failures)
If this …

7.1 Cherry-pick: Address seg fault in "storageRecruiter" actor

---

fdbserver/DDTeamCollection.actor.cpp

fix: perpetual wiggle would not react to a pause that happened while starting the wiggle

---

fdbserver/SimulatedCluster.actor.cpp

Hostnames are causing simulation failures. Turn on again in #6926.

Disable hostname in simulations.

---

fdbserver/SimulatedCluster.actor.cpp

Backport #6947. Hostnames are causing simulation failures. Turn on again in #6926.

Disable hostname in simulations (release-7.1).

---

fdbserver/workloads/DataLossRecovery.actor.cpp

Cherrypick #6886
The timed_out error, if happens, could cause the test to fail, even though
there is nothing wrong with the database.

Fix a spurious DataLossRecovery test failure [release-7.1]

---

fdbserver/workloads/DataLossRecovery.actor.cpp

The timed_out error, if happens, could cause the test to fail, even though
there is nothing wrong with the database.
100k 20220425-231849-jzhou-52a86bfa04832104 passed. 10k DataLossRecovery tests passed.

Fix a spurious DataLossRecovery test failure

---

documentation/sphinx/source/class-scheduling-java.rst

Use CompletableFuture::join instead of CompletableFuture::get
when blocking on futures in java tutorial snippets. This avoids
the unreported checked exceptions which prevent the snippets from
compiling (and is in line with the full tutorial code).

Fix compile errors in Java tutorial code

---

bindings/c/CMakeLists.txt
bindings/c/test/apitester/run_c_api_tests.py

Some improvements in the run_c_api_tests.py script:
- Fix error reporting in case of a time out
- Enable client logs and dump them out in case of an error

Improve error reporting in C API tests 

---

fdbcli/fdbcli.actor.cpp
fdbclient/AutoPublicAddress.cpp
fdbclient/CoordinationInterface.h
fdbclient/ManagementAPI.actor.cpp
fdbclient/ManagementAPI.actor.h
fdbclient/MonitorLeader.actor.cpp
fdbclient/MonitorLeader.h
fdbclient/NativeAPI.actor.cpp
fdbclient/PaxosConfigTransaction.actor.cpp
fdbclient/SimpleConfigTransaction.actor.cpp
fdbclient/SpecialKeySpace.actor.cpp
fdbclient/StatusClient.actor.cpp
fdbrpc/genericactors.actor.h
fdbserver/ClusterController.actor.cpp
fdbserver/ClusterRecovery.actor.cpp
fdbserver/CoordinatedState.actor.cpp
fdbserver/Coordination.actor.cpp
fdbserver/CoordinationInterface.h
fdbserver/LeaderElection.actor.cpp
fdbserver/LeaderElection.h
fdbserver/PaxosConfigConsumer.actor.cpp
fdbserver/QuietDatabase.actor.cpp
fdbserver/SimpleConfigConsumer.actor.cpp
fdbserver/SimulatedCluster.actor.cpp
fdbserver/Status.actor.cpp
fdbserver/fdbserver.actor.cpp
fdbserver/worker.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp
fdbserver/workloads/RemoveServersSafely.actor.cpp
fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp

This PR takes hostname's resolving-related functionalities out of ClusterConnectionString. From now on, ClusterConnectionString will only store hostnames and coordinators as-is.
As a result, each hostname will be resolved independently. A resolving failure, or a detected hostname->address change will not cause resolvings of other hostnames. Resolving failures will also not crash or block where only a quorum is required, such as leader election.
The most noticeable change is, coordinator interfaces will not have initialized request streams if they are created from hostnames instead of network addresses. So the places sending related RPCs will now have a pattern of
```
if(interface.hostname.present()) {
reply = retryGetReplyFromHostname(request, interface.hostname.get(), TOKEN);
} else { …
```

Check in the new Hostname logic.

---

packaging/docker/build-images.sh

build-images.sh requires a token before accessing the Instance MetaData Service in AWS. This change adds that capability. 

update build-images.sh to play nice with AWS IMDSv2

---

fdbserver/storageserver.actor.cpp

limit for getRange was incorrectly set to 1, while a single logical record is consists of at least 2 keyValue, causing record layer fail to unsplit the logical record.
method definition: https://github.com/apple/foundationdb/blob/cc72d541e4c632634b8f37fe67ab726c634cc9b3/fdbclient/NativeAPI.actor.h#L306-L309
caller: https://github.com/apple/foundationdb/blob/cc72d541e4c632634b8f37fe67ab726c634cc9b3/fdbserver/storageserver.actor.cpp#L3458

Fix limit bug in indexPrefetch

---

fdbserver/storageserver.actor.cpp

backporting https://github.com/apple/foundationdb/pull/7004

Fix limit bug in indexPrefetch(release-7.1)

---

fdbcli/fdbcli.actor.cpp
fdbclient/AutoPublicAddress.cpp
fdbclient/CoordinationInterface.h
fdbclient/ManagementAPI.actor.cpp
fdbclient/ManagementAPI.actor.h
fdbclient/MonitorLeader.actor.cpp
fdbclient/MonitorLeader.h
fdbclient/NativeAPI.actor.cpp
fdbclient/PaxosConfigTransaction.actor.cpp
fdbclient/SimpleConfigTransaction.actor.cpp
fdbclient/SpecialKeySpace.actor.cpp
fdbclient/StatusClient.actor.cpp
fdbrpc/genericactors.actor.h
fdbserver/ClusterController.actor.cpp
fdbserver/ClusterRecovery.actor.cpp
fdbserver/CoordinatedState.actor.cpp
fdbserver/Coordination.actor.cpp
fdbserver/CoordinationInterface.h
fdbserver/LeaderElection.actor.cpp
fdbserver/LeaderElection.h
fdbserver/PaxosConfigConsumer.actor.cpp
fdbserver/QuietDatabase.actor.cpp
fdbserver/SimpleConfigConsumer.actor.cpp
fdbserver/SimulatedCluster.actor.cpp
fdbserver/Status.actor.cpp
fdbserver/fdbserver.actor.cpp
fdbserver/worker.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp
fdbserver/workloads/RemoveServersSafely.actor.cpp
fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp

Backporting #6926.
Before this PR, we treat the hostnames in a ClusterConnectionString as a whole. We resolve them together, and when there is a resolving failure, it crashes; when one hostname->address changes, we re-resolve the whole ClusterConnectionString. This can bring problems when: 1. if one or more hostnames in the ClusterConnectionString is just wrong, the server will crash; 2. when a coordinator pod is down, leader election will never finish and may even crash.
This PR takes hostname's resolving-related functionalities out of ClusterConnectionString. From now on, ClusterConnectionString will only store hostnames and coordinators as-is.
As a result, each hostname will be resolved independently. A resolving failure, or a detected hostname->address change will not cause resolvings …

Check in the new Hostname logic (release-7.1).

---

fdbserver/storageserver.actor.cpp

Fixes race with the same change feed being deleted in multiple ways on the same storage server.
Issue found on snowflake/release-7.1, passed 100k *BlobGranule* correctness there.

Fixing change feed deleted from multiple sources race

---

fdbserver/TagPartitionedLogSystem.actor.cpp

fix: when more tlogs are absent than the replication factor we would access invalid memory

---

fdbserver/workloads/ConsistencyCheck.actor.cpp

Fixes correctness issue found by non-responsive quarantined TSS.

Allow TSS failures in consistency check when fault injection is enabled

---

fdbrpc/AsyncFileNonDurable.actor.h
fdbrpc/sim2.actor.cpp
fdbrpc/simulator.h
fdbserver/SimulatedCluster.actor.cpp

Killing a machine process would not wait for AsyncFileNonDurable close operations to finish, causing a later reopen of the same file in a new process to hang forever.  Renamed AsyncFileNonDurable::deleteFile to closeFile for clarity.  Renamed Machine deletingFiles to deletingOrClosingFiles for clarity.

Bug fix: AsyncFileNonDurable close/open could hang

---

fdbserver/storageserver.actor.cpp

fix: prevent a storage server from attempting to read the cluster id from itself due to a stale cache entry

---

fdbrpc/AsyncFileNonDurable.actor.h
fdbrpc/sim2.actor.cpp
fdbrpc/simulator.h
fdbserver/SimulatedCluster.actor.cpp

Bug fix: AsyncFileNonDurable close/open could hang (Cherry-pick #7007 to release-7.1)

---

fdbrpc/TokenSign.cpp

TokenSign was copying unused Arena held by _Standalone_ instead of referring to it.
Copied Arenas aren't guaranteed to share with the original the lifecycle of the objects allocated post-copy.
Thus, when the copied arena went out of scope,
the memory supposed to be held by returned _Standalone_ also got released.
Fix: instead of copying, refer to _Standalone_'s arena.

Fix TokenSign copying and using uninitialized arena

---

fdbserver/DDTeamCollection.actor.cpp
fdbserver/DataDistribution.actor.h

It was previously possible for a team to be removed but for a relocate shard task to still have a reference to it. If that happened, the task would not detect when the team became unhealthy and could no longer be moved to.
Marking the team unhealthy signals to the relocate shard task that it should stop trying to relocate it.

Mark a team as unhealthy when it is removed

---

fdbserver/workloads/TPCC.actor.cpp

Variable `clientsUsed` is not initialized correctly.

Variable clientsUsed in TPC-C workload is not initialized correctly.

---

tests/TestRunner/upgrade_test.py

Various improvements to the robustness of the upgrade tests
* Download old FDB binaries only if they are not available in the Docker build image
* Retry on download errors
* Avoid tests getting stuck waiting for the named pipes to be opened, in the case when test binary fails to initialize, because of errors in the configuration or similar

Improve robustness of upgrade tests

---

bindings/c/test/apitester/TesterApiWrapper.cpp
fdbclient/MultiVersionTransaction.actor.cpp

Fixes ASAN issues (incorrect delete and memory leak) in fdb_c_api_tests_blob_granule.
Passes ASAN and valgrind with "ctest -R fdb_c_api_tests"

Blob Granules Multi-Version-Client ASAN fixes

---

fdbserver/storageserver.actor.cpp

Cherry-pick of https://github.com/apple/foundationdb/pull/6950 to release-7.1, fixing correctness failure

[release 7.1] Fixing change feed deleted from multiple sources race

---

fdbrpc/sim2.actor.cpp

Cherry-pick #6979 to release-7.1, fixing correctness failure

[release-7.1] Don't do huge tail latencies for network requests when speed up simulation is set

---

fdbclient/MultiVersionTransaction.actor.cpp

Cherry-pick #7015 to snowflake/release-7.1. Does not affect correctness tests

[snowflake/release-7.1] Blob Granules Multi-Version-Client ASAN fixes 

---

fdbclient/RYWIterator.cpp
fdbclient/WriteMap.h

- Add a test demonstrating the issue
- Treat SetVersionstampedValue as independent in coalesce and mutate
Previously the following sequence of operations would cause operation_failed to get thrown incorrectly.
1. Set the bypass_unreadable transaction option
2. Set a key k to a value
3. Set k to a versionstamped value
4. Read k
AFAICT FuzzApiCorrectness is capable of catching this, but the probability seems to be too low.

Fix operation_failed thrown incorrectly from transactions

---

flow/Platform.actor.cpp

Previously the page guard implementation assumed that the page size was 4k, and
you would see a "bus error" on mac m1. Also check for mmap and mprotect
returning errors.

Mac m1 has 16k pages

---

fdbserver/DDTeamCollection.actor.cpp
fdbserver/DataDistribution.actor.h

This is a backport of https://github.com/apple/foundationdb/pull/7020.
It was previously possible for a team to be removed but for a relocate shard task to still have a reference to it. If that happened, the task would not detect when the team became unhealthy and could no longer be moved to.
Marking the team unhealthy signals to the relocate shard task that it should stop trying to relocate it.

Mark a team as unhealthy when it is removed (backport #7020 to release-7.1)

---

fdbserver/LogRouter.actor.cpp
fdbserver/LogSystemPeekCursor.actor.cpp
fdbserver/TLogServer.actor.cpp
fdbserver/storageserver.actor.cpp

The force recovery can roll back the transaction that adds a storage server.
However, the storage server may now at version B > A, the recovery version.
As a result, its peek to buddy TLog won't return TLogPeekReply::popped to
trigger its exit, and instead getting a higher version C > B back. To the
storage server, this means the message is empty, thus not removing itself and
keeps peeking.
Because the SS is running, it prevents DD from recruiting it as a SS. This behavior
is found by consistency check.
The fix is to instead of using recovery version as the popped version for the
SS, we use the recovery transaction version, which is the first transaction
after the recovery. Force recovery bumps this version to a much higher version
than the SS's version. So the TLog would set …

Fix orphaned storage server due to force recovery

---

packaging/docker/sidecar.py

This allows the operator to query if a file is present without calculation the hash.

Add sidecar method to check if a file is present

---

fdbcli/ConfigureCommand.actor.cpp
fdbcli/KillCommand.actor.cpp
fdbcli/StatusCommand.actor.cpp
fdbcli/ThrottleCommand.actor.cpp
fdbcli/fdbcli.actor.cpp
fdbcli/fdbcli.actor.h

This is a refactoring that makes it easier to add new generators and cleans up command specific code in fdbcli.actor.cpp.

Move fdbcli command and hint generators into the CommandFactory

---

fdbclient/DatabaseContext.h
fdbclient/NativeAPI.actor.cpp
flow/error_definitions.h

Do not consult version vector if the client has obtained the read version from its GRV cache.
Test that detected this issue:
Branch: release-7.1 (with version vector enabled)
Compiler: gcc
Commit: f120b3f1a07b5804fee3d57a019df1a6ae410119
Test: build_output/bin/fdbserver -r simulation --crash -f /root/src/foundationdb/tests/fast/SidebandSingle.toml -b on -s 1651247938
Release-7.1 (with version vector enabled): 20220503-153015-sre-d45cb1e1fbf7c4e5 (no failures)
Release-7.1 (with version vector disabled): 20220503-170118-sre-a89fc0efc6f71ac1 (no failures)
main (with version vector disabled): 20220503-192232-sre-5cb10a57be96cce0 (has failures), 20220503-215929-sre-c8bf04c027ec6a3d (over the latest commit in this patch, no failures)
main (with version vector enabled): …

Address GRV cache and version vector incompatibility

---

fdbclient/DatabaseContext.h
fdbclient/NativeAPI.actor.cpp
flow/error_definitions.h

Cherry-pick pull request https://github.com/apple/foundationdb/pull/7057 from "main".
Do not consult version vector if the client has obtained the read version from its GRV cache.
Test that detected this issue:
Branch: release-7.1 (with version vector enabled)
Compiler: gcc
Commit: https://github.com/apple/foundationdb/commit/f120b3f1a07b5804fee3d57a019df1a6ae410119
Test: build_output/bin/fdbserver -r simulation --crash -f /root/src/foundationdb/tests/fast/SidebandSingle.toml -b on -s 1651247938
Release-7.1 (with version vector enabled): 20220503-153015-sre-d45cb1e1fbf7c4e5 (no failures)
Release-7.1 (with version vector disabled): 20220503-170118-sre-a89fc0efc6f71ac1 (no failures) …

7.1 Cherry-pick: Address GRV cache and version vector incompatibility

---

bindings/c/test/apitester/TesterBlobGranuleCorrectnessWorkload.cpp

Fix for ASSERT failing on error in arm blob granule tests.

Fix for arm BG tests

---

fdbserver/Resolver.actor.cpp

Cherrypick #7067 
To save Resolver CPU cost, especially for creating LogSystemConfig.
20k 20220505-155027-jzhou-1a5c4cbed9f9769a passed.

Avoid creating LogPushData when PROXY_USE_RESOLVER_PRIVATE_MUTATIONS is off [release-7.1]

---

fdbclient/Tuple.h
fdbserver/storageserver.actor.cpp

ConstructMappedKey seems to be a hotspot, try eliminate unnecessary
operations by
* re-using the same Tuple
* preprocess the formatTuple to get a list of Tuples and strings
20220505-003405-haofu-e943db3c75f10cc0: commit 1
20220505-174645-haofu-3d80901ef6df31fa : commit 2

re-use same arena when construct mapped key

---

fdbclient/Tuple.h
fdbserver/storageserver.actor.cpp

backporting https://github.com/apple/foundationdb/pull/7062 and https://github.com/apple/foundationdb/pull/7066

Clean up constructMappedKey method and reuse arena(release-7.1)

---

fdbserver/storageserver.actor.cpp
packaging/docker/sidecar.py

There was OOM if we pre-process all the strings.

Eliminate vector string during mapped key processing

---

packaging/docker/sidecar.py

Fixes the sidecar script. I tested this locally.

Fix sidecar script

---

fdbserver/KeyValueStoreRocksDB.actor.cpp

Adding rocksdb throttling counters to trace event.

Adding rocksdb throttling counters to trace event.

---

fdbserver/CommitProxyServer.actor.cpp
fdbserver/LogSystem.cpp
fdbserver/LogSystem.h
fdbserver/ProxyCommitData.actor.h
fdbserver/Resolver.actor.cpp

Which seems to be a CPU hot spot in our testing.
100k 20220505-190908-jzhou-71b580b4ff6211d2 has one failure that can't be reproduced.

Optimize LogPushData to avoid constructing LogSystemConfig

---

fdbserver/CommitProxyServer.actor.cpp
fdbserver/LogSystem.cpp
fdbserver/LogSystem.h
fdbserver/ProxyCommitData.actor.h
fdbserver/Resolver.actor.cpp

Cherrypick #7070 
Which seems to be a CPU hot spot in our testing.
100k 20220505-215659-jzhou-c1f22b99d946b5be has one `BlobGranuleVerifyLarge.toml` timeout failure (many BlobGranuleInitialSnapshotRetry with transaction_too_old error), probably not related.

[release-7.1] Optimize LogPushData to avoid constructing LogSystemConfig

---

fdbcli/ProfileCommand.actor.cpp
fdbcli/fdbcli.actor.cpp
fdbcli/fdbcli.actor.h
fdbclient/DatabaseContext.h
fdbclient/GlobalConfig.actor.cpp
fdbclient/GlobalConfig.actor.h
fdbclient/NativeAPI.actor.cpp
fdbclient/NativeAPI.actor.h
fdbclient/SpecialKeySpace.actor.cpp
fdbclient/SpecialKeySpace.actor.h
fdbserver/worker.actor.cpp
flow/genericactors.actor.h

Currently, GlobalConfig is a singleton that means for each process there is only
one GlobalConfig object. This is bug from clients perspective as a client can
keep connections to several databases. This patch tracks GlobalConfig for each
database by keeping it inside `DatabaseContext`.
We discovered this bug while testing multi-version client, where the client got
stuck. This was lucky, as normally it'd just write down config to the wrong
database.

Create GlobalConfig object for each database instance (release-7.1)

---

fdbclient/CoordinationInterface.h
fdbserver/CoordinationInterface.h

New added field should be the last in serializer.

Fix compatibility issue.

---

fdbclient/Tuple.cpp
fdbclient/Tuple.h
fdbserver/storageserver.actor.cpp

backporting https://github.com/apple/foundationdb/pull/7077

add appendRaw and subTupleRawString for Tuple(release-7.1)

---

fdbclient/NativeAPI.actor.cpp

If getRange() is called with "latestVersion" as the read version then both GetKeyValuesFamilyRequest and getRangeFallback should do reads at the same version.
NOTE: Found this issue on the version vector branch but I don't think this issue is specific to version vector logic.
Testing:
"main" (version vector disabled): 20220505-201024-sre-b12f50026a2b5c6f (shows a failure in BlobGranuleVerifyBalance.toml, but the test succeeds locally for me; also verified that "getRangeFallback()", in getRange() actor, is not getting in the context of this test, so it is unlikely this failure was caused by the change in this PR).
"main" (version vector enabled): 20220506-161351-sre-59b95c5f5123337d (shows a failure in DataLossRecovery.toml, which also fails locally, but verified that …

Address readVersion related bug in getRange actor

---

fdbserver/workloads/WriteDuringRead.actor.cpp

[Release 7.1] Fix for WriteDuringRead workload key sizes with useSystemKeys=true

---

packaging/docker/sidecar.py

We have to use `relpath` instead of the base path if a file is in a sub folder example:
```bash
2022-05-07 08:19:46,541 INFO path: /is_present/bin/7.1.3/fdbserver
2022-05-07 08:19:46,541 INFO real: bin/7.1.3/fdbserver
2022-05-07 08:19:46,541 INFO base: fdbserver
2022-05-07 08:19:46,541 INFO file is_present on disk
2022-05-07 08:19:46,541 INFO "GET /is_present/bin/7.1.3/fdbserver HTTP/1.1" 200 -
```

Make use of relpath instead of basepath

---

tests/TestRunner/upgrade_test.py

There were sporadical failures of the upgrade tests. The test binaries failed to load the client libraries using dlopen, getting an error that indicates file corruption. The file corruption was likely caused by multiple tests copying the same library file in parallel. The fix addresses this by replacing the file atomically.

Upgrade Tests: Avoid race conditions when copying library files from a local repo

---

fdbclient/NativeAPI.actor.cpp

Cherry-pick pull request https://github.com/apple/foundationdb/pull/7092 from "main".
If getRange() is called with "latestVersion" as the read version then both GetKeyValuesFamilyRequest and getRangeFallback should do reads at the same version.
NOTE: Found this issue on the version vector branch but I don't think this issue is specific to version vector logic.
Testing:
Release-7.1 (with version vector disabled): 20220509-142228-sre-f20b969240383dee (no failures)
Release-7.1 (with version vector enabled): 20220509-151532-sre-c34087a7c7827946 (no failures)
If this PR is …

7.1 Cherry-pick: Address readVersion related bug in getRange actor

---

bindings/java/src/integration/com/apple/foundationdb/CycleMultiClientIntegrationTest.java

By default we have 3 clusters, each have 5 threads running the same
workload, this PR reduces workload from 2k write txn to 200 because
2k txn takes too long to execute and 200 is enough for correcetness.

Reduce workload in CycleMultiClientIntegrationTest

---

bindings/c/CMakeLists.txt
tests/TestRunner/upgrade_test.py

Including 7.1 into the upgrade path of the regression tests, which effectively add a testing upgrade from 7.0 to 7.1 and then 7.1 to 7.2

Upgrade Tests: Including 7.1 into the upgrade paths

---

tests/CMakeLists.txt
tests/restarting/from_7.1.0/VersionVectorDisableRestart-1.toml
tests/restarting/from_7.1.0/VersionVectorDisableRestart-2.toml
tests/restarting/from_7.1.0/VersionVectorEnableRestart-1.toml
tests/restarting/from_7.1.0/VersionVectorEnableRestart-2.toml

Cherry-pick the following commits from the version vector branch (we somehow missed these commits when we merged that branch into "main"):
097c4de7270fa8089a85a308d146bbd9ddb51c7a
74e90d95ebce566b3ab2be51e19861c4165422e2
31aafc56d17428bec1a4bef84f0e6ed389f210e8
44eb2c916710612ccfbb7c86353c9cd3eac925ac
Testing:
Ran the version vector restart tests locally.  No failures.
Simulation tests: 20220510-151640-sre-bdf89a76c2707c7b (in progress)

Cherry-pick version vector disable/enable restart tests 

---

contrib/TestHarness/Program.cs
fdbserver/FDBExecHelper.actor.cpp

`outputBuffer` may not be null-terminated, so don't convert to std::string.
This fixes a heap buffer overflow caught by ASAN, and importantly not valgrind, since valgrind currently doesn't run on the first binary in restarting test. Change that so we always run valgrind on the binary under test when valgrind is enabled.

Fix heap overflow

---

tests/CMakeLists.txt
tests/restarting/from_7.1.0/VersionVectorDisableRestart-1.toml
tests/restarting/from_7.1.0/VersionVectorDisableRestart-2.toml
tests/restarting/from_7.1.0/VersionVectorEnableRestart-1.toml
tests/restarting/from_7.1.0/VersionVectorEnableRestart-2.toml

Cherry-pick the following commits from the version vector branch (we somehow missed these commits when we merged that branch into "main"):
https://github.com/apple/foundationdb/commit/097c4de7270fa8089a85a308d146bbd9ddb51c7a
https://github.com/apple/foundationdb/commit/74e90d95ebce566b3ab2be51e19861c4165422e2
https://github.com/apple/foundationdb/commit/31aafc56d17428bec1a4bef84f0e6ed389f210e8
https://github.com/apple/foundationdb/commit/44eb2c916710612ccfbb7c86353c9cd3eac925ac
Testing:
Ran the version vector restart tests locally. No failures.
Simulation tests: 20220510-212616-sre-2a2b65ec51946640 (no failures). …

Release 7.1: Cherry-pick version vector disable/enable restart tests

---

fdbserver/SimulatedCluster.actor.cpp
fdbserver/TesterInterface.actor.h
fdbserver/storageserver.actor.cpp
fdbserver/tester.actor.cpp

Some mapped range operations were incorrectly rejected when tenants existed in the cluster. This occurred because we have a check that disallow running mapped range operations inside of a tenant with raw transactions, but the check was not correctly determining if we were in a tenant or not.
This change fixes the check and adds some unit tests of it. It also updates the simulator to generate extra unused tenants, which results in the above bug being detected.
Passed 20K correctness and the new unit test.

Fix bug in interaction between mapped ranges and tenants

---

fdbrpc/FlowTransport.actor.cpp

When downgrading a cluster, it was possible for a `Peer` object on the destination version to be held open through the downgrade. Before the downgrade, the `Peer` would have marked the connection as incompatible and would stop sending messages to it. After the downgrade, that state would persist and it would continue refusing to send messages even though the remote endpoint is compatible.
With this change, the state marking the connection as ineligible for messages is cleared when an incompatible connection is closed.
Passed 10K correctness. Also passes downgrade testing when applied to 7.0 and 7.1. …

When an incompatible connection is closed, clear the state that prevents us from sending messages on it

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/CMakeLists.txt
fdbserver/EncryptKeyProxy.actor.cpp
fdbserver/EncryptKeyProxyInterface.h
fdbserver/KmsConnectorInterface.h
fdbserver/RESTKmsConnector.actor.cpp
fdbserver/RESTKmsConnector.h
fdbserver/SimKmsConnector.actor.cpp
fdbserver/SimKmsConnector.h
fdbserver/workloads/EncryptKeyProxyTest.actor.cpp
fdbserver/workloads/EncryptionOps.actor.cpp
flow/BlobCipher.cpp
flow/CMakeLists.txt
flow/EncryptUtils.cpp
flow/EncryptUtils.h
flow/IRandom.h
flow/flow.cpp

Description
Proposed changes include:
1. Update EncryptKeyProxy API to embded Optional<UID> for debugging
request execution.
2. Encryption participant FDB processes can set 'debugId' enabling
tracing requests within FDB cluster processes and beyond.
3. The 'debugId' if available is embedded as part of 'request_json_payload'
by RESTKmsConnector, enabling tracing request between FDB <--> KMS.
4. Fix EncryptKeyProxyTest which got broken due to recent changes.
Testing
Updated following test:
1. EncryptKeyProxy simulation test.
2. RESTKmsConnector simulation test. …

Enable debugId tracing for encryption requests

---

fdbserver/TLogServer.actor.cpp

tLogs cannot recover until versions up to the RV (for all tags) are peeked from the old log server, written to the SS, and then popped. While in that state, `tagData->unpoppedRecovered` is `true`. And even if no data is read from the old log server, the min popped version for all tags must be >= RV for the tLog to recover. Blocking empty message peeks shouldn't happen during this as it will elongate recovery time.
100K runs version vector enabled
`20220510-015744-henrylambright-9cac1bc064234fef`

Do not block empty peeks while a disk queue is recovering in version vector.

---

fdbclient/MonitorLeader.actor.cpp
fdbrpc/genericactors.actor.h
flow/Hostname.actor.cpp
flow/Hostname.h

They are no longer needed since we have coordinators DNS cache; and they are introducing complex crashes.
20220512-022453-renxuan-55abd010ef41ebd3           compressed=True data_size=31473630 duration=5110174 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:04:24 sanity=False started=100072 stopped=20220512-032917 submitted=20220512-022453 timeout=5400 username=renxuan

Remove HostnameStatus and resolve trigger.

---

fdbclient/MonitorLeader.actor.cpp
fdbrpc/genericactors.actor.h
flow/Hostname.actor.cpp
flow/Hostname.h

They are no longer needed since we have coordinators DNS cache; and they are introducing complex crashes.
PR on main: #7140.
20220512-022453-renxuan-55abd010ef41ebd3           compressed=True data_size=31473630 duration=5110174 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:04:24 sanity=False started=100072 stopped=20220512-032917 submitted=20220512-022453 timeout=5400 username=renxuan

Remove HostnameStatus and resolve trigger (release-7.1).

---

cmake/FDBComponents.cmake

Apple's CI build likely uses a docker image that has a newer version of
rocks than boost version fdb depends on. Disable rocksdb.

rocksdb: disable rocksdb by default

---

fdbcli/fdbcli.actor.cpp
fdbcli/fdbcli.actor.h

because the current implementation is killing processes one at a time
cherry pick of #7149 

revert "kill" command to previous 7.0 behavior

---

fdbrpc/FlowTransport.actor.cpp
fdbrpc/FlowTransport.h

**Problem**: When a client is connecting the server of a newer version, it marks the Peer of the connection as incompatible, and blocks any attempts to send packets over this connection. Even if the server is downgraded and the client reconnects, the flag remains and the compatibility of the protocol is not rechecked. The upgrades are working, because there is a special handing for the case when the Peer is of the older protocol version. 
**Fix** The fix restores equal handing of downgrades and upgrades. It restores the original strict protocol check  before sending packets. The protocol compatibility flag is reset each time, when connection is closed. So when a client reconnects to a cluster after its downgrade or upgrade the protocol compatibility is checked again.
In order to enable …

Fixing the problem with client getting stuck on server downgrades

---

flow/CMakeLists.txt
flow/MkCert.cpp
flow/MkCert.h
flow/TLSTest.cpp

Make sure the certificate generated by MkCert verifies correctly when fed to boost::asio's ssl::context.
This test doubles as a proof-of-concept correctness test for "elective mutual TLS" feature to come.

Unit test MkCert

---

bindings/c/fdb_c.cpp
bindings/c/foundationdb/fdb_c.h
bindings/c/test/unit/fdb_api.cpp
bindings/c/test/unit/fdb_api.hpp
bindings/c/test/unit/unit_tests.cpp
bindings/java/fdbJNI.cpp
bindings/java/src/integration/com/apple/foundationdb/MappedRangeQueryIntegrationTest.java
bindings/java/src/main/com/apple/foundationdb/FDBTransaction.java
bindings/java/src/main/com/apple/foundationdb/ReadTransaction.java
fdbclient/FDBTypes.h
fdbclient/IClientApi.h
fdbclient/ISingleThreadTransaction.h
fdbclient/MultiVersionTransaction.actor.cpp
fdbclient/MultiVersionTransaction.h
fdbclient/NativeAPI.actor.cpp
fdbclient/NativeAPI.actor.h
fdbclient/PaxosConfigTransaction.h
fdbclient/ReadYourWrites.actor.cpp
fdbclient/ReadYourWrites.h
fdbclient/SimpleConfigTransaction.h
fdbclient/StorageServerInterface.h
fdbclient/ThreadSafeTransaction.cpp
fdbclient/ThreadSafeTransaction.h
fdbserver/storageserver.actor.cpp
fdbserver/workloads/ApiWorkload.h
fdbserver/workloads/GetMappedRange.actor.cpp

Optimization: support removing index conditionally
This change enables 2 modes:
* return all indexes
* return none of the indexes(except for boundary)
Note that boundary index entries need to be returned so
that caller can have a continuation, otherwise I do not see
an easy way to achieve this. Since we have serializable,
we might also need it to compare the set.
There will be a follow up change that enables more modes,
that return indexes based on whether there is a secondary query match.
tests are added -- randomly using `non` or `all` mode, it worked in local and joshua.
joshua: 
20220511-082048-haofu-34b78611446ae04c
11d51f53a20fa10: 20220513-120500-haofu-7005f4d6229e5110 
The general guidelines can be found [here](https://github.com/apple/foundationdb/wiki/FoundationDB-Commit-Process) …

Optimization: support removing index conditionally

---

fdbrpc/FlowTransport.actor.cpp
flow/serialize.cpp

Log a backtrace before throwing serialization_failed [release-7.1]

---

fdbrpc/FlowTransport.actor.cpp
flow/serialize.cpp

Cherry pick https://github.com/apple/foundationdb/pull/7146 to snowflake/release-7.1

Log a backtrace before throwing serialization_failed (snowflake/release-7.1)

---

bindings/c/CMakeLists.txt
tests/TestRunner/upgrade_test.py

My previous PR erroneously moved cluster health & progress checks out of the loop in the upgrade test:
https://github.com/apple/foundationdb/pull/7085
This PR is a fix, that restores the checks after each upgrade step.
The downgrade test to 7.1 has to be disabled, because the downgrade fix for 7.1 is not released yet. 

Restoring checks after each step in upgrade test

---

bindings/java/src/main/com/apple/foundationdb/MappedKeyValue.java

Resolves #7125. Similar to KeyValue, make MappedKeyValue's constructor public.

Make MappedKeyValue constructor public

---

documentation/sphinx/source/mr-status-json-schemas.rst.inc
fdbclient/Schemas.cpp
fdbserver/ProxyCommitData.actor.h
fdbserver/Status.actor.cpp

Added a new "tenants" section to the json status inside cluster section. Only the number of tenants is added for now, but it could be expanded to show additional tenant-related information in the future. 
Testing:
- 10k correctness test runs
- Unit tests
- Manual verification on a local cluster, by adding and deleting tenants.
```
fdb> configure tenant_mode=optional_experimental
Configuration changed
fdb> createtenant a
The tenant `a' has been created
fdb> createtenant b
The tenant `b' has been created
fdb> createtenant c
The tenant `c' has been created
fdb> listtenants
1. a
2. b
3. c
fdb> status json
...
"tenants" : {
"num_tenants" : 3
},
...
fdb> deletetenant c
The tenant `c' has been deleted
fdb> deletetenant b
The tenant `b' has been deleted
fdb> listtenants
1. a
fdb> status json
... …
```

Add tenant information to status

---

cmake/FDBComponents.cmake

We use libcoro for the normal linux build, and so we want to also use that in valgrind. Ideally we'd like to use the same libcoro implementation in all formats but last we looked libcoro was faster, but not compatible with asan.

Use libcoro for valgrind

---

fdbrpc/FlowTransport.actor.cpp

This backports https://github.com/apple/foundationdb/pull/7124.
When downgrading a cluster, it was possible for a Peer object on the destination version to be held open through the downgrade. Before the downgrade, the Peer would have marked the connection as incompatible and would stop sending messages to it. After the downgrade, that state would persist and it would continue refusing to send messages even though the remote endpoint is compatible.
With this change, the state marking the connection as ineligible for messages is cleared when an incompatible connection is closed.
If this PR …

When an incompatible connection is closed, clear the state that prevents us from sending messages on it (cherry-pick #7124 to release-7.0)

---

fdbrpc/FlowTransport.actor.cpp

This backports #7124.
When downgrading a cluster, it was possible for a Peer object on the destination version to be held open through the downgrade. Before the downgrade, the Peer would have marked the connection as incompatible and would stop sending messages to it. After the downgrade, that state would persist and it would continue refusing to send messages even though the remote endpoint is compatible.
With this change, the state marking the connection as ineligible for messages is cleared when an incompatible connection is closed. …

When an incompatible connection is closed, clear the state that prevents us from sending messages on it (cherry-pick #7124 to snowflake/release-7.1)

---

bindings/go/src/fdb/generated.go
fdbclient/vexillographer/fdb.options

Duplicate code caused distributed_client_tracer to break.
Testing: Correctness and manual testing via Mako.

client_tmp_dir needs a unique code in bindings.

---

bindings/c/test/apitester/TesterOptions.h
bindings/c/test/apitester/TesterScheduler.cpp
bindings/c/test/apitester/TesterScheduler.h
bindings/c/test/apitester/TesterWorkload.cpp
bindings/c/test/apitester/TesterWorkload.h
bindings/c/test/apitester/fdb_c_api_tester.cpp
bindings/c/test/apitester/run_c_api_tests.py
tests/TestRunner/upgrade_test.py

Introducing an option to Api Tester to enable printing workload statistics in regular intervals, so that in case of long running tests we can see if the tester is still alive and the workloads are making progress. 
The statistics is currently limited to the number of completed transactions, but the design allows defining workload-specific statistic dump if necessary. 

Api Tester: print workload progress statistics in regular time intervals

---

fdbrpc/sim2.actor.cpp
fdbrpc/simulator.h
fdbserver/FDBExecHelper.actor.cpp
fdbserver/tester.actor.cpp
fdbserver/workloads/ClientWorkload.actor.cpp
fdbserver/workloads/SaveAndKill.actor.cpp

Fixes #7175 
I suspect, but have not confirmed, that the reason this used to work may be the jmalloc changes?
Either way, accessing these char* fields in the save and kill workload was accessing freed memory, and changing ProcessInfo to have ownership of the memory fixed it.
Sampled several of the previous nightly valgrind failures and they all pass now after this change.
Valgrind ensemble fails 1/1000 tests.

Switching char* to std::string for ProcessInfo to have it own memory (valgrind errors)

---

bindings/c/test/mako/mako.cpp
bindings/c/test/mako/mako.hpp

Add support for specifying distributed client tracer in Mako.
Introduces a new command line option --distributed_tracer_client. Defaults to disabled, user may specify
disabled, log_file, network_lossy, or sim_end.
Tested locally and verified with distributed tracing receiver. Note: We use a simple integer here to denote tracer type rather directly using the TracerType enum in flow/Tracing.h. Including Tracing.h pulls in FDBTypes.h and results in conflicts with several classes, including `Database`.

Mako add distributed tracing client

---

bindings/c/CMakeLists.txt
tests/TestRunner/upgrade_test.py

Extending regression tests to test client stability on downgrades from 7.2 to 7.1.

Upgrade Tests: Testing downgrade from 7.2 to 7.1

---

bindings/c/foundationdb/fdb_c.h
bindings/c/test/unit/unit_tests.cpp
bindings/java/src/main/com/apple/foundationdb/FDBTransaction.java
fdbclient/FDBTypes.h
fdbclient/MultiVersionTransaction.h
fdbclient/NativeAPI.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/workloads/GetMappedRange.actor.cpp

MATCHED mode returns index entries whose secondary KVs are present,
UNMATCHED mode returns index entries whose secondary KVs are absent.
Note that the conflict read range of this txn is set in 2 steps:
* Set the conflict range for primary query according to request
* Set the conflict ranges for secondary queries according to responses.
As a result, conflicts of different match_index mode are taken care of.
20220513-211442-haofu-df127d6255b17a4b
20220516-221937-haofu-82e80c376836f21a
`This PR includes C binding changes, Java binding will come in a following PR.(it is ready and tested, just spliting into multiple PR)` …

Enable MATCHED and UNMATCHED mode for index prefetch

---

bindings/c/test/unit/unit_tests.cpp
fdbserver/workloads/GetMappedRange.actor.cpp

a follow up PR for the TODO of https://github.com/apple/foundationdb/pull/7162
This change adds test for missing secondary queries for index prefetch,
in this case, MATCHED_ONLY mode would NOT return KV and UNMATCHED_ONLY
mode would return KV.
20220518-170140-haofu-59b4c4ff2cd3df33 

Add missing secondary queries tests for index prefetch

---

bindings/c/foundationdb/fdb_c.h
bindings/c/test/unit/unit_tests.cpp
bindings/java/src/main/com/apple/foundationdb/FDBTransaction.java
fdbclient/FDBTypes.h
fdbclient/MultiVersionTransaction.h
fdbclient/NativeAPI.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/workloads/GetMappedRange.actor.cpp

backporting https://github.com/apple/foundationdb/pull/7162

Enable MATCHED and UNMATCHED mode for index prefetch(release-7.1)

---

fdbclient/IKnobCollection.cpp
fdbserver/LocalConfiguration.actor.cpp
tests/argument_parsing/test_argument_parsing.py

This backports https://github.com/apple/foundationdb/pull/7187

(release-7.1) Process should not crash when given invalid knob name

---

fdbclient/MonitorLeader.actor.cpp
fdbclient/NativeAPI.actor.cpp
fdbrpc/FlowTransport.actor.cpp
fdbrpc/FlowTransport.h

This adds some logic to the protocol version monitoring to handle some special cases:
1. When the coordinator gets cycled in monitorProxies, notify the protocol version monitoring even if the coordinator did not change. This restarts the monitoring loop so that it can read updated Peer state.
2. Move the location where we update the coordinator in monitorProxies. The previous location should work because of the request streams created at the top of the loop, but the new location is more explicit by waiting until we've sent a request with the new Peer.
3. Check for the case where a Peer is unset when accessing its protocol version info. We don't expect this to happen, but now instead of throwing an unknown_error it will log a trace event and retry after a delay.
The …

Defensive changes to protocol version monitoring

---

fdbclient/IKnobCollection.cpp
fdbserver/LocalConfiguration.actor.cpp
tests/argument_parsing/test_argument_parsing.py

This backports https://github.com/apple/foundationdb/pull/7187.

(snowflake-7.1) Process should not crash when given invalid knob name

---

bindings/java/fdbJNI.cpp
bindings/java/src/integration/com/apple/foundationdb/MappedRangeQueryIntegrationTest.java
bindings/java/src/main/com/apple/foundationdb/FDBTransaction.java
bindings/java/src/main/com/apple/foundationdb/MappedKeyValue.java
bindings/java/src/main/com/apple/foundationdb/MappedRangeQuery.java
bindings/java/src/main/com/apple/foundationdb/MappedRangeResultDirectBufferIterator.java

a follow up PR to add java binding parts of https://github.com/apple/foundationdb/pull/7162
It adds boundaryAndExist in return value, so that caller can see
whether a boundary index is orphan or not.

Make java binding work for prefetch match index modes.

---

cmake/FDBComponents.cmake

Cherry pick https://github.com/apple/foundationdb/pull/7143 to snowflake/release-7.1
We use libcoro for the normal linux build, and so we want to also use that in valgrind. Ideally we'd like to use the same libcoro implementation in all formats but last we looked libcoro was faster, but not compatible with asan.

Use libcoro for valgrind (snowflake/release-7.1)

---

bindings/python/tests/fdbcli_tests.py
fdbcli/ExpensiveDataCheckCommand.actor.cpp
fdbcli/KillCommand.actor.cpp
fdbcli/SuspendCommand.actor.cpp
fdbcli/fdbcli.actor.cpp
fdbclient/IClientApi.h
fdbclient/NativeAPI.actor.cpp

Fix issue #7147 by extending the `rebootWorker` interface to accept comma-delimited addresses string,
where the underlying implementation will send requests to multiple processes simultaneously.
This fixed all the sequential issues for `kill`, `suspend`, and `expensive_data_check` commands.
-------------
Testing: 
correctness 100K
ctest for fdbcli 100K
Manually tested the three commands to make sure it's happening as expected.

Extend the reboot interface to accept comma-delimited string

---

bindings/c/test/mako/async.cpp

Current mako is adding commit latencies as transaction latencies in ResumableStateForRunWorkload::onTransactionSuccess(). This change makes sure that the correct latencies for OP_TRANSACTION are being reported.

Use correct transaction latency in async mako

---

fdbserver/storageserver.actor.cpp

If a storage server failed before the byte sample is recovered, the byte sample recovery might try to read from the IKeyValueStore after it was closed.

Explicitly cancel byte sample recovery on SS failure

---

bindings/c/fdb_c.cpp
bindings/c/foundationdb/fdb_c.h
bindings/c/test/unit/fdb_api.cpp
bindings/c/test/unit/fdb_api.hpp
bindings/c/test/unit/unit_tests.cpp
bindings/java/fdbJNI.cpp
bindings/java/src/integration/com/apple/foundationdb/MappedRangeQueryIntegrationTest.java
bindings/java/src/main/com/apple/foundationdb/FDBTransaction.java
bindings/java/src/main/com/apple/foundationdb/MappedKeyValue.java
bindings/java/src/main/com/apple/foundationdb/MappedRangeQuery.java
bindings/java/src/main/com/apple/foundationdb/MappedRangeResultDirectBufferIterator.java
bindings/java/src/main/com/apple/foundationdb/ReadTransaction.java
fdbclient/FDBTypes.h
fdbclient/IClientApi.h
fdbclient/ISingleThreadTransaction.h
fdbclient/MultiVersionTransaction.actor.cpp
fdbclient/MultiVersionTransaction.h
fdbclient/NativeAPI.actor.cpp
fdbclient/NativeAPI.actor.h
fdbclient/PaxosConfigTransaction.h
fdbclient/ReadYourWrites.actor.cpp
fdbclient/ReadYourWrites.h
fdbclient/SimpleConfigTransaction.h
fdbclient/StorageServerInterface.h
fdbclient/ThreadSafeTransaction.cpp
fdbclient/ThreadSafeTransaction.h
fdbserver/storageserver.actor.cpp
fdbserver/workloads/ApiWorkload.h
fdbserver/workloads/GetMappedRange.actor.cpp

Reverting following PRs:
* 98f5cc885 - Revert "Optimization: support removing index conditionally (#7116)" 
* a3c1e1d47 - Revert "Enable MATCHED and UNMATCHED mode for index prefetch (#7162)"
* 52a7b3570 - Revert "Add missing secondary queries tests for index prefetch (#7185)"
* bd667b890 - Revert "Make java binding work for prefetch match index modes. (#7186) (#7206)"

Revert index prefetch changes that breaks API compatibility

---

bindings/python/tests/fdbcli_tests.py
fdbcli/ExpensiveDataCheckCommand.actor.cpp
fdbcli/KillCommand.actor.cpp
fdbcli/SuspendCommand.actor.cpp
fdbcli/fdbcli.actor.cpp
fdbclient/IClientApi.h
fdbclient/NativeAPI.actor.cpp

Cherry-pick #7188  to fix the kill suspend and expensive_data_check commands
In addition, manually tested it's working as expected.

Extend the reboot interface to accept comma-delimited string(Release-7.1)

---

fdbclient/AutoPublicAddress.cpp
fdbclient/CoordinationInterface.h
fdbclient/ManagementAPI.actor.cpp
fdbclient/ManagementAPI.actor.h
fdbclient/MonitorLeader.actor.cpp
fdbclient/PaxosConfigTransaction.actor.cpp
fdbclient/SimpleConfigTransaction.actor.cpp
fdbclient/SpecialKeySpace.actor.cpp
fdbserver/Coordination.actor.cpp
fdbserver/fdbserver.actor.cpp
fdbserver/worker.actor.cpp
fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp
flow/Net2.actor.cpp

Currently, when we do a commit of coordinator change, we are always converting hostnames to IP addresses and store the converted results in coordinatorsKey (\xff/coordinators). This result in ForwardRequest also sending IP addresses, and receivers will update their cluster files with IPs, then we lose the dynamic IP feature.
20220520-064954-renxuan-cc1823b4dbede152           compressed=True data_size=31492695 duration=5119224 ended=100001 fail=1 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:48:20 sanity=False started=100110 stopped=20220520-073814 submitted=20220520-064954 timeout=5400 username=renxuan
Please check each of the following things …

coordinatorsKey should not always store IP addresses.

---

bindings/python/tests/fdbcli_tests.py
fdbcli/VersionEpochCommand.actor.cpp
fdbclient/SpecialKeySpace.actor.cpp
fdbserver/masterserver.actor.cpp

See the list of commits for details about each change. Responding to feedback from a version correction review session.
Remaining work:
* ~~Move buggification of version epoch out of `masterserver.actor.cpp`. This value must be set in the txnStateStore in order for QuietDatabase to be able to read it.~~ Will follow up on this when the backup/restore work is in progress, it isn't necessary until then.

Version correction fixes

---

fdbclient/IKnobCollection.cpp
fdbserver/LocalConfiguration.actor.cpp
tests/argument_parsing/test_argument_parsing.py

Process should not crash when given invalid knob name

---

fdbserver/TagPartitionedLogSystem.actor.cpp
fdbserver/TagPartitionedLogSystem.actor.h

When there are many txn system generations, one pop from remote tlog to log routers will pop all log routers in all generations (if we have 20 generations, and 10 log routers, those are 200 pop requests generated, for every pop a remote tlog wants to do). This causes the remote tlogs and log routers get overloaded, which makes remote storage catching up even slower.
To solve this issue, we make the remote tlog to only pop the generation that it needs to pop, i.g., if a log router is in charge of version [v1, v2] for a tag, it will only pop that log router until v2 is popped.
Passed 100K joshua test: 20220519-210429-zhewu-lr-fix-5-07dcbd57bd4621d3    compressed=True data_size=32378869 duration=5492543 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 …

Don't pop every generation of old log router

---

fdbserver/KeyValueStoreShardedRocksDB.actor.cpp

We branch on the value of cf, so we need to initialize it.

Fix use of uninitialized memory

---

fdbclient/AutoPublicAddress.cpp
fdbclient/CoordinationInterface.h
fdbclient/ManagementAPI.actor.cpp
fdbclient/ManagementAPI.actor.h
fdbclient/MonitorLeader.actor.cpp
fdbclient/PaxosConfigTransaction.actor.cpp
fdbclient/SimpleConfigTransaction.actor.cpp
fdbclient/SpecialKeySpace.actor.cpp
fdbserver/Coordination.actor.cpp
fdbserver/fdbserver.actor.cpp
fdbserver/worker.actor.cpp
fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp
flow/Net2.actor.cpp

PR on main: #7204.
Currently, when we do a commit of coordinator change, we are always converting hostnames to IP addresses and store the converted results in coordinatorsKey (\xff/coordinators). This result in ForwardRequest also sending IP addresses, and receivers will update their cluster files with IPs, then we lose the dynamic IP feature.
20220520-064954-renxuan-cc1823b4dbede152           compressed=True data_size=31492695 duration=5119224 ended=100001 fail=1 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:48:20 sanity=False started=100110 stopped=20220520-073814 submitted=20220520-064954 timeout=5400 username=renxuan …

coordinatorsKey should not always store IP addresses (release-7.1).

---

fdbclient/ClientKnobs.cpp
fdbclient/ClientKnobs.h
fdbclient/S3BlobStore.actor.cpp
fdbrpc/HTTP.actor.cpp

1. For v4 signature, http request path should be encoded, currently only parameters are encoded.
2. For v2 signature, http request date header should be in form of either the http date header or x-amz-date, currently in form of ISO 8601
3. Empty response header value cause http_bad_response error.
4. Skip verifying MD5 for range get request and if http response code 206  is returned.
Since different vendors have different Content-MD5 implementation, eg. Huawei Cloud return object content checksum instead of the checksum of response body. It is difficult to verify checksum at the level of single http response for range get request.  And Content-MD5 header is deprecated in http2.0 for the same reason. In this patch I skip verifying checksum for range get request.
Test:
Remaining issue:
1. …

Fix compatibility issue of s3 backup

---

fdbserver/TLogServer.actor.cpp
fdbserver/storageserver.actor.cpp

Cherry pick https://github.com/apple/foundationdb/pull/7236 to release-7.1
This change is causing SharedTLogs to not be displaced, even if it's for the correct cluster.
At the very least this leaks disk space, and we suspect that this is causing some memory error to manifest.
Reverts most logic in #5637.

Revert most logic in #5637 (release-7.1)

---

fdbclient/PaxosConfigTransaction.actor.cpp
fdbserver/PaxosConfigConsumer.actor.cpp

Make a local copy of a promise before calling sendError, in case the sendError call results in that promise getting destroyed. Only one of these call sites actually manifested, but let's defensively make a copy for each of them.

Fix a heap-use-after-free in PaxosConfigConsumer.actor.cpp

---

fdbclient/ServerKnobs.cpp

When version vector is enabled and BLOCKING_PEEK_TIMEOUT is much larger (10X) than MAX_READ_TRANSACTION_LIFE_VERSIONS, the likelihood of transactions throwing error_code_transaction_too_old is high, which can lead to cascading failures.
For example, when MAX_READ_TRANSACTION_LIFE_VERSIONS is .1 (1e5 versions) and BLOCKING_PEEK_TIMEOUT is 1 (1e6 version), and no data has been sent to the SS for the requested tag in this epoch (just empty messages with version updates)
a transaction's read version V may be higher than the SS's highest seen version S.
the transaction will wait for V on the SS.
when blocking peek times out, the new highest seen version S2 will be <= V+1e6.
the SS will consider any versions less than S2-1e5 to be too old.
More generally any read commit version chosen cannot be …

cherry pick PR 7199 

---

fdbclient/PaxosConfigTransaction.actor.cpp
fdbserver/PaxosConfigConsumer.actor.cpp

Cherry pick https://github.com/apple/foundationdb/pull/7244 to release-7.1
Make a local copy of a promise before calling sendError, in case the sendError call results in that promise getting destroyed. Only one of these call sites actually manifested, but let's defensively make a copy for each of them.

Fix a heap-use-after-free in PaxosConfigConsumer.actor.cpp (release-7.1)

---

fdbclient/BlobGranuleCommon.h
fdbclient/BlobGranuleFiles.cpp
fdbclient/BlobWorkerInterface.h
fdbclient/NativeAPI.actor.cpp
fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbrpc/FlowTransport.actor.cpp
fdbserver/BlobGranuleValidation.actor.cpp
fdbserver/BlobGranuleValidation.actor.h
fdbserver/BlobManager.actor.cpp
fdbserver/BlobWorker.actor.cpp
fdbserver/SimulatedCluster.actor.cpp
fdbserver/workloads/BlobGranuleCorrectnessWorkload.actor.cpp
tests/fast/BlobGranuleVerifyAtomicOps.toml
tests/fast/BlobGranuleVerifyCycle.toml
tests/fast/BlobGranuleVerifySmall.toml
tests/fast/BlobGranuleVerifySmallClean.toml
tests/slow/BlobGranuleCorrectness.toml
tests/slow/BlobGranuleCorrectnessClean.toml
tests/slow/BlobGranuleVerifyBalance.toml
tests/slow/BlobGranuleVerifyBalanceClean.toml
tests/slow/BlobGranuleVerifyLarge.toml
tests/slow/BlobGranuleVerifyLargeClean.toml

- Enable blob granules to use tenants as a source of ranges to blobbify
- Change blob granules to respect tenant boundaries
- Changed blob workers to handle tenants for read requests like SS does
- Change BlobGranuleCorrectness* to exclusively use tenants
My mechanism for tracking the tenant boundaries in the blob manager and worker was a bit hacky, but it works for now.
Passed 10k BlobGranuleVerify* (no tenants) and 10k BlobGranuleCorrectness* (with tenants).

blob granule - tenant integration

---

fdbserver/masterserver.actor.cpp

Make sequencer accept the recovery transaction version unconditionally.
Cluster controller could send multiple recovery transaction versions and not accepting them unconditionally could cause a discrepancy between the recovery transaction versions on the sequencer and the resolvers, resulting in a hung recovery (because the cluster controller wouldn't be able to commit the recovery transaction version).
NOTE: Found this issue on "release-7.1" branch with version vector enabled but I don't think this issue is in anyway related to the version vector logic.
Test that found this issue:
Branch: release-7.1
Commit: f58801f26f82be92e39b5d12fdb7aa0e66c1655f
Compiler: clang
Options: version vector enabled
Test: "build_output/bin/fdbserver -r simulation --crash -f …

Make sequencer accept the recovery transaction version unconditionally

---

documentation/sphinx/source/tenants.rst

Backports #7219.
This configuration key may end up being removed, so we'll remove the documentation of it for now.

Remove tenant prefix documentation (backport #7219 to release-7.1)

---

fdbserver/masterserver.actor.cpp

Merge pull request #7256 from sbodagala/main.
Make sequencer accept the recovery transaction version unconditionally.
Cluster controller could send multiple recovery transaction versions and not accepting them unconditionally could cause a discrepancy between the recovery transaction versions on the sequencer and the resolvers, resulting in a hung recovery (because the cluster controller wouldn't be able to commit the recovery transaction version).
NOTE: Found this issue on "release-7.1" branch with version vector enabled but I don't think this issue is in anyway related to the version vector logic.
Test that found this issue:
Branch: release-7.1
Commit: https://github.com/apple/foundationdb/commit/f58801f26f82be92e39b5d12fdb7aa0e66c1655f
Compiler: clang
Options: version vector enabled …

Cherry pick pull request #7256

---

fdbclient/PaxosConfigTransaction.actor.cpp
fdbserver/PaxosConfigConsumer.actor.cpp

Cherry pick https://github.com/apple/foundationdb/pull/7244 to snowflake/release-7.1
Make a local copy of a promise before calling sendError, in case the sendError call results in that promise getting destroyed. Only one of these call sites actually manifested, but let's defensively make a copy for each of them.

Fix a heap-use-after-free in PaxosConfigConsumer.actor.cpp (snowflake/release-7.1)

---

fdbclient/DatabaseContext.h
fdbclient/GlobalConfig.actor.cpp
fdbclient/GlobalConfig.actor.h
fdbclient/NativeAPI.actor.cpp
fdbclient/SpecialKeySpace.actor.cpp

This PR contains three [GlobalConfig](https://github.com/apple/foundationdb/wiki/Global-Configuration-Framework) fixes:
* Adds a transaction retry loop to GlobalConfig transactions (from #7079)
* Fixes a reference cycle with `DatabaseContext` and `GlobalConfig` smart pointers (from #7127)
* Fixes an issue where GlobalConfig would not be initialized on a newly cloned `Database` object

General GlobalConfig fixes

---

fdbclient/ServerKnobs.cpp
fdbserver/DataDistributionQueue.actor.cpp

`noErrorsActors` shouldn't be destroy before `inFlightActors` because there're tasks in `inFlightActors` use `noErrorsActors`.

Fix heap-use-after-free caused by early noErrorsActors destroy

---

fdbrpc/genericactors.actor.h

Fixes #7223.
The root cause is every retry in retryGetReplyFromHostname() creates a new RequestStream, which will create a new peer. The RequestStream is destructed when the request is sent, so the peer is also destructed. In the next retry, this repeats again, without knowing the last connection failed. If connecting to the new peer always fail (which happens when the peer process is dead), workers will think themselves are bad, then BetterMasterExist will try to do a recovery.
This issue is verified by running 10k DataLossRecovery.toml tests with useHostname=true:
20220526-233811-renxuan-544bf28126431c6d           compressed=True data_size=32808384 duration=470292 ended=10000 fail=2 fail_fast=10 max_runs=10000 pass=9998 priority=100 remaining=0 runtime=0:30:32 sanity=False started=10044 …

Avoid creating new RequestStream when retry.

---

bindings/go/README.md
bindings/go/src/fdb/database.go
bindings/go/src/fdb/fdb_test.go

Backport of https://github.com/apple/foundationdb/pull/6821 to allow the FDB kubernetes operator to use this method.

Backport go reboot

---

fdbrpc/genericactors.actor.h

PR on main: #7263. Fixes #7223.
The root cause is every retry in retryGetReplyFromHostname() creates a new RequestStream, which will create a new peer. The RequestStream is destructed when the request is sent, so the peer is also destructed. In the next retry, this repeats again, without knowing the last connection failed. If connecting to the new peer always fail (which happens when the peer process is dead), workers will think themselves are bad, then BetterMasterExist will try to do a recovery.
This issue is verified by running 10k DataLossRecovery.toml tests with useHostname=true:
20220526-233811-renxuan-544bf28126431c6d compressed=True data_size=32808384 duration=470292 ended=10000 fail=2 fail_fast=10 max_runs=10000 pass=9998 priority=100 remaining=0 runtime=0:30:32 sanity=False …

Avoid creating new RequestStream when retry (release-7.1).

---

bindings/c/test/mako/future.hpp

Currently Mako worker thread waits on the original future that produced the error. Not the future returned by onError. Fix this to wait on the correct future.

Correctly wait on onError() future

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/fdbserver.actor.cpp

fix: the peek_using_streaming can cause memory corruption

---

fdbclient/NativeAPI.actor.cpp
fdbclient/ThreadSafeTransaction.cpp
flow/Trace.cpp

**Fixing the call to closeTraceFile**
On the client side, the trace file was closed from a call to fdb_stop_network, which is usually called from an application thread other than the FDB network thread. After fdb_stop_network is called, the network thread may still continue executing scheduled tasks. We want to keep the trace file open, so that this pending activity is traced. Another problem is that trace file on the client side is initialized on demand on creation of the first database, so if there is a pending database creation task at the time of calling fdb_stop_network, it will attempt reinitializing the trace file and fail. 
The fix moves the closeTraceFile call from fdb_stop_network to the end of fdb_run_network. 
The problem is specific to the use of the client API, because FDB …

Fix race conditions on closeTraceFile and flushTraceFileVoid

---

bindings/c/CMakeLists.txt
bindings/c/symbolify.py

Without symbols from `fdb_c_internal.h` being exported to client side `.so` library, the C API tests are failing, see: https://github.com/apple/foundationdb/issues/7291
This PR extends the Apple-platform specific extraction of symbols to include not only symbols from `fdb_c.h`, but also `fdb_c_internal.h`. 
Tested by running `ctest -R fdb_c_api_tests` which passes with this PR on Apple, but times out without it. 

Include symbols from fdb_c_internal.h to C bindings client library for Apple platform

---

fdbclient/GlobalConfig.actor.cpp
fdbserver/workloads/Cycle.actor.cpp

Previously CycleTest was adding a parent span to 99% of transactions instead of the intended 1%, and some retry loops in GlobalConfig did not perform exponential backoff.

Fix some spammy trace events

---

fdbserver/EncryptKeyProxy.actor.cpp
fdbserver/EncryptKeyProxyInterface.h
fdbserver/KmsConnectorInterface.h
fdbserver/RESTKmsConnector.actor.cpp
fdbserver/SimKmsConnector.actor.cpp
fdbserver/workloads/EncryptKeyProxyTest.actor.cpp
flow/EncryptUtils.cpp
flow/EncryptUtils.h

Description
Major changes proposed include:
1. Update EncryptKeyServer APIs to be tenant aware.
2. Update KmsConnector APIs to be tenant aware
Client of above APIs such as: CP, SS and BlobWorker need to supply
encryption domain info that includes: tenantId and tenantName
Testing
1. Update EncryptKeyProxyTest
2. Update RESTKmsConnectorTest
3. Update SimKmsConnectorTest

Make EncryptKeyServer and KmsConnector API to be 'tenant' name aware

---

bindings/c/test/unit/unit_tests.cpp
bindings/flow/Tuple.cpp
bindings/flow/Tuple.h
bindings/flow/tester/Tester.actor.cpp
fdbclient/CMakeLists.txt
fdbclient/GlobalConfig.actor.cpp
fdbclient/Tuple.cpp
fdbclient/Tuple.h
fdbclient/Versionstamp.cpp
fdbclient/Versionstamp.h
flow/error_definitions.h

20220602-175030-haofu-870e5182cde63faf
fa7b788fc013dee0b117a78bf95b4a3725d2cc90: 20220602-205400-haofu-48da98901d4da01b

Add versionstamp support in tuple

---

fdbserver/KeyValueStoreRocksDB.actor.cpp

TraceEvent invalid character causing simulation harness to fail and hides the actual errors

Traceevent correction.

---

fdbclient/GlobalConfig.actor.cpp
fdbserver/workloads/Cycle.actor.cpp

Cherry pick https://github.com/apple/foundationdb/pull/7296 to release-7.1
Previously CycleTest was adding a parent span to 99% of transactions instead of the intended 1%, and some retry loops in GlobalConfig did not perform exponential backoff.

Fix some spammy trace events (release-7.1)

---

bindings/flow/tester/Tester.actor.cpp

backport https://github.com/apple/foundationdb/pull/7312

Fix versionstamp in Tester (release-7.1)

---

fdbclient/ReadYourWrites.actor.cpp
fdbserver/workloads/ConflictRange.actor.cpp

An off-by-one error in the RYW reverse range read logic caused us to generate a larger than expected conflict range in some cases. In particular, if the begin key selector was firstGreaterThan(<key>) or firstGreaterOrEqual(<key>) (the latter being the default), then the entire range between the begin and end key would be part of the conflict set. This was true even if a limit was specified that caused the range to terminate early.
The reason for this was because we need to include the entire range if the begin key selector resolves into the range. For example, if our begin key selector was firstGreaterThan(<key>) + 1, then changes anywhere in that range could impact our results when the key selector is resolved. This is not true when using just firstGreaterThan or firstGreaterOrEqual, …

Fix bug in reverse range reads causing larger than desired conflict ranges

---

fdbserver/LogRouter.actor.cpp
fdbserver/TLogServer.actor.cpp

In the streaming path this does make the `messages` arena live longer, but it just about pays for itself by not allocating new memory for the copy.

Save a memcpy in the tlog peek path

---

fdbserver/BlobManager.actor.cpp
fdbserver/BlobWorker.actor.cpp
fdbserver/workloads/BlobGranuleCorrectnessWorkload.actor.cpp

Fixes SAV destroy race in callback of bstoreLoaded, by letting all callbacks execute before continuing execution.
Passes 100 *BlobGranuleCorrectness* valgrind tests

fixes for blob metadata memory from valgrind

---

fdbserver/worker.actor.cpp

The data passed to IAsyncFile::write must remain valid until the future
is ready.

Fix a heap-use-after-free in a unit test

---

bindings/c/test/unit/unit_tests.cpp
tests/TestRunner/tmp_cluster.py

We want to suppress a specific asan message on stderr, and along the way it
seems to have changed somewhat. Update it.

Fix asan message detection

---

bindings/c/test/unit/third_party/CMakeLists.txt
fdbbackup/FileDecoder.actor.cpp
flow/WriteOnlySet.actor.cpp

Fixes the following build issues on arm64 (Mac with an M1 processor):
Sleep_for() method not found in std::this_thread: 
```
FAILED: flow/CMakeFiles/flow_sampling.dir/WriteOnlySet.actor.g.cpp.o
/usr/bin/c++ -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_SYSTEM_NO_DEPRECATED -DENABLE_SAMPLING -DNO_INTELLISENSE -I/foundationdb -I/build_output -isystem /build_output/boost_install/include -D_GLIBCXX_USE_NANOSLEEP -O3 -DNDEBUG -DCMAKE_BUILD -ggdb -fno-omit-frame-pointer -Wno-pragmas -Wno-attributes -Wno-error=format -Wunused-variable -Wno-deprecated -fvisibility=hidden -Wreturn-type -fPIC -march=armv8.2-a+crc+simd -DHAVE_OPENSSL -std=gnu++17 -MD -MT flow/CMakeFiles/flow_sampling.dir/WriteOnlySet.actor.g.cpp.o -MF flow/CMakeFiles/flow_sampling.dir/WriteOnlySet.actor.g.cpp.o.d -o …
```

Arm64 related build fixes

---

documentation/sphinx/source/mr-status-json-schemas.rst.inc
fdbclient/Schemas.cpp
fdbserver/Status.actor.cpp

Since memory is now limited with RSS size, add RSS size in status json for
reporting. Also change how available_bytes is calculated from:
(available + virtual memory) * process_limit / machine_limit
to:
(available memory) * process_limit / machine_limit
Now `status json` has process memory section like:
```
"memory" : {
"available_bytes" : 8589934592,
"limit_bytes" : 8589934592,
"rss_bytes" : 49131520,
"unused_allocated_memory" : 0,
"used_bytes" : 149008384
},
```
Correctness 20220608-000811-jzhou-c8ce3295a734bb22 …

Add rss_bytes to process memory and fix available_bytes calculation

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbclient/VersionVector.h
fdbserver/masterserver.actor.cpp

Merge pull request #7318 from sbodagala/main
Introduce a knob that will control the placement of the commit versions of remote storage servers in version vector. This optimization will help reduce the size of version vector in HA configuration. Disable this knob by default.
NOTE: We are not sure at this point whether we will need this optimization or not. We will know more once we start testing the version vector feature in a production size HA cluster.
Testing:
Simulation tests (compiler: gcc):
Version vector disabled: 20220608-213356-sre-0b89a5f0493c7850 (no failures).
Version vector enabled and the new knob enabled: 20220608-221535-sre-ece66a74c9f412a1 (shows a failure in "ParallelRestoreNewBackupWriteDuringReadAtomicRestore.toml", not sure if that failure is related to this change set …

Cherry pick pull request #7318

---

bindings/c/test/unit/unit_tests.cpp

From calling strlen on a not necessarily null-terminated buffer.

Fix more heap overflows

---

fdbclient/DatabaseContext.h
fdbclient/GlobalConfig.actor.cpp
fdbclient/NativeAPI.actor.cpp

We re-create the transaction every iteration of each of these retry
loops, so we need to manage exponential backoff here ourselves.
Closes #7301

Fix a few places we weren't doing exponential backoff

---

fdbserver/EncryptKeyProxy.actor.cpp
fdbserver/EncryptKeyProxyInterface.h
fdbserver/KmsConnectorInterface.h
fdbserver/RESTKmsConnector.actor.cpp
fdbserver/SimKmsConnector.actor.cpp
fdbserver/workloads/EncryptKeyProxyTest.actor.cpp
flow/EncryptUtils.cpp
flow/EncryptUtils.h

Description
KMS CipherKeys can be of two types:
1. Revocable CipherKeys: having a finite lifetime, after which the CipherKey
shouldn't be used by the FDB.
2. Non-revocable CipherKeys: ciphers are not revocable, however, FDB would
still want to refresh ciphers to support KMS cipher rotation feature.
Patch proposes following change to incorporate support for above defined cipher-key
types:
1. Extend KmsConnector response to include optional 'refreshAfter' & 'expireAfter'
time intervals. EncryptKeyProxy (EKP) cache would define corresponding absolute refresh &
expiry timestamp for a given cipherKey. On an event of transient KMS connectivity outage,
a caller of EKP API for a non-revocable key should continue using cached cipherKey until
it expires.
2. Simplify KmsConnector API arena handling …

KmsConnector implementation to support KMS driven CipherKey TTL

---

fdbclient/ClusterConnectionFile.h
fdbclient/GlobalConfig.actor.h
fdbrpc/AsyncFileChaos.h
fdbrpc/CMakeLists.txt
fdbrpc/Net2FileSystem.cpp
fdbrpc/sim2.actor.cpp
fdbserver/BlobGranuleServerCommon.actor.h
fdbserver/BlobGranuleValidation.actor.h
fdbserver/DDTeamCollection.h
fdbserver/QuietDatabase.h
fdbserver/ResolutionBalancer.actor.h
fdbserver/RestoreWorker.actor.h
fdbserver/RocksDBCheckpointUtils.actor.h
fdbserver/RoleLineage.actor.h
fdbserver/ServerCheckpoint.actor.h
fdbserver/workloads/ApiWorkload.h
fdbserver/workloads/AsyncFile.cpp

Whenever `flow/actorcompiler.h` is included in an actor header file, we should include `flow/unactorcompiler.h` at the end of the header file. Furthermore, `flow/actorcompiler.h` should be included if and only if the header file is an actor header file, and a header file should be an actor header file only if necessary (because actor keywords are used within the header file).
This PR fixes several instances throughout the code where the above rules are broken.

Clean up includes in actor header files

---

flow/XmlTraceLogFormatter.cpp

The original escape process uses a `loop` while the code is actually not
an ACTOR. So the actorcompiler is not reacting. This causes the escape
not escaping the XML fields properly.

fixup! Fix the XmlTraceLogFormatter

---

fdbclient/MonitorLeader.actor.cpp
fdbclient/ThreadSafeTransaction.cpp
fdbrpc/genericactors.actor.h
flow/Net2.actor.cpp

In k8s tests, we observed `Unhandled error in FoundationDB network thread: An unknown error occurred (4000)`. Digging into trace events, we see either std::bad_alloc or basic_string::_S_create exception.
The root cause of the bug is, member variables are not capture in lambda, thus, `host` and `service` are not captured. This somehow successfully compile, but throws std::bad_alloc or basic_string::_S_create exceptions when we call `host+":"+service` in dnsCache.remove(), which happens when hostname resolving fails.
In this PR, we also added 2 minor improvements:1
1. Improve the bestCount algorithm in getLeader(). In the existing implementation, if the moninees are [0,1,1,2,2], we will choose 1 as the leader; however, if the nominees are [0,1], the chosen leader will be 1, being an …

Fix bug in resolveTCPEndpoint() when hostname resolving fails.

---

fdbclient/MonitorLeader.actor.cpp
fdbclient/ThreadSafeTransaction.cpp
fdbrpc/genericactors.actor.h
flow/Net2.actor.cpp

PR on main: #7375.
In k8s tests, we observed Unhandled error in FoundationDB network thread: An unknown error occurred (4000). Digging into trace events, we see either std::bad_alloc or basic_string::_S_create exception.
The root cause of the bug is, member variables are not capture in lambda, thus, host and service are not captured. This somehow successfully compile, but throws std::bad_alloc or basic_string::_S_create exceptions when we call host+":"+service in dnsCache.remove(), which happens when hostname resolving fails.
In this PR, we also added 2 minor improvements:1
Improve the bestCount algorithm in getLeader(). In the existing implementation, if the moninees are [0,1,1,2,2], we will choose 1 as the leader; however, if the nominees are [0,1], the chosen leader will be 1, being an …

Fix bug in resolveTCPEndpoint() when hostname resolving fails (release-7.1).

---

flow/MkCertCli.cpp

BaseTraceEvent::setNetworkThread() and flushTraceFile[()|Void()]
has a long-standing race condition for traceEventThrottlerCache global
when flushTraceFileVoid() is not called from the network thread.
This race dates back to 2017 (commit hash 80e5fecfe2),
so before the race itself is fixed, work around the problem.

Work around flow trace's data race bug

---

bindings/c/fdb_c.cpp
documentation/sphinx/source/administration.rst
documentation/sphinx/source/api-version-upgrade-guide.rst

backporting https://github.com/apple/foundationdb/pull/7314

Safely remove fdb_transaction_get_range_and_flat_map (release-7.1)

---

fdbclient/ClientKnobs.cpp
fdbclient/ClientKnobs.h
fdbclient/ManagementAPI.actor.cpp

This is to fix an issue when recovery and change coordinator key happens together. The issue will occur when:
1. Recovery starts
2. Coordinator key change transaction started
3. During the recovery the coordinator key is read from cluster file and stored in the storage server
4. The cluster controller received `ChangeCoordiatorsRequest`, and updated the cluster name with the new value.
At this stage, the value related to coordinator key in storage server and
the worker is inconsistent.
5. changeQuorumChecker is called, which will verify such consistency. Since they are different, the call is returning failure and the caller, which could be a TEST_CASE, fails.
This is a rare race issue, and it is also noticed that when the recovery/coordinator key change process is done, the database is in …

fixup! Add a retry mechanism in changeQuorumChecker and changeQuorum

---

fdbclient/ISingleThreadTransaction.cpp
fdbclient/ThreadSafeTransaction.cpp

@sfc-gh-mdvorsky found a performance issue related to how `ReadYourWritesTransaction`s get initialized.
`ReadYourWritesTransaction` has memory allocated before being passed to
the main thread. This allows both threads to continue to access the
transaction object. Currently, the transaction gets allocated and
initialized on the foreign thread, and then re-initialized on the main
thread. This causes a bunch of extra, unnecessary work for each
`ReadYourWritesTransaction` where the temporary object gets destructed.
The fix is to only allocate memory for the `ReadYourWritesTransaction`
on the foreign thread, and then initialize it once on the main thread.
Cherry picks to 7.1: #7365, #7366.
The general guidelines can be found [here](https://github.com/apple/foundationdb/wiki/FoundationDB-Commit- …

Remove unnecessary ReadYourWritesTransaction initialization

---

fdbclient/S3BlobStore.actor.cpp

This patch is to fix the compile error
/root/src/fdbclient/S3BlobStore.actor.cpp:410:9: error: moving a local
object in a return statement prevents copy elision
[-Werror,-Wpessimizing-move]
return std::move(resource);
^
/root/src/fdbclient/S3BlobStore.actor.cpp:410:9: note: remove std::move
call here
return std::move(resource);
^~~~~~~~~~        ~
1 error generated.

fixup! Fix the clang error when using std::move

---

fdbserver/ClusterRecovery.actor.cpp
fdbserver/CommitProxyServer.actor.cpp
fdbserver/GetEncryptCipherKeys.actor.cpp
fdbserver/IKeyValueStore.h
fdbserver/KeyValueStoreMemory.actor.cpp
fdbserver/Resolver.actor.cpp

Adding encryption support for TxnStateStore. It is done by supporting encryption. for KeyValueStoreMemory. The encryption is currently done on operation level when the operations are being write to the underlying log file. See inline comment for the encrypted data format.
This PR depends on #7252. It is part of the effort to support TLog encryption #6942.

Support encrypting TxnStateStore

---

fdbclient/ISingleThreadTransaction.cpp
fdbclient/ThreadSafeTransaction.cpp

Cherry pick of #7364 to `release-7.1`.

Remove unnecessary ReadYourWritesTransaction initialization (release-7.1)

---

fdbserver/EncryptKeyProxy.actor.cpp
flow/Knobs.cpp

Description
Major changes include:
1. GetEncryptByKeyIds cache elements can expire.
2. Update iterator after erasing an element during refresh encryption keys
operation.
Testing
EncryptKeyProxyTest

Fix bugs in EncryptKeyProxy actor

---

contrib/mockkms/mock_kms.go

Description
Generate GNU compatible build-id for mockkms golang binary
Leverate "cgo" to generate build-id
Testing
Debian package build, verified the GNU build-id

Generate GNU compatible build-id for mockkms golang binary

---

fdbclient/ISingleThreadTransaction.cpp
fdbclient/ThreadSafeTransaction.cpp

Cherry pick of #7364 to `snowflake/release-7.1`.

Remove unnecessary ReadYourWritesTransaction initialization (snowflake/release-7.1)

---

fdbserver/masterserver.actor.cpp

Do not try to figure out the sequencer locality if knob ENABLE_VERSION_VECTOR_HA_OPTIMIZATION is disabled.
NOTE: There is a bug in the code that figures out the sequencer locality, which will be addressed in a follow up PR.
Compiler: gcc.
Version vector disabled: 20220615-160758-sre-4d4401896450eb20 (in progress).

Do not always try to figure out the sequencer locality

---

flow/Trace.cpp

Currently, a std::string is copied unnecessarily for every key and value
in a trace event.
This actually showed up in a jemalloc heap profile while I was
investigating something unrelated. I was surprised to see it since these
allocations should have a very short lifetime.

Save a bunch of copies in the trace thread

---

fdbserver/masterserver.actor.cpp

Merge pull request #7391 from sbodagala/main.
Do not always try to figure out the sequencer locality if knob ENABLE_VERSION_VECTOR_HA_OPTIMIZATION is disabled.
NOTE: There is a bug in the code that figures out the sequencer locality, which will be addressed in a follow up PR.
Compiler: gcc.
Version vector disabled: 20220615-182410-sre-6c787800a31a6626 (in progress).

Cherry pick pull request #7391

---

fdbclient/GenericManagementAPI.actor.h
fdbclient/SpecialKeySpace.actor.cpp
fdbserver/tester.actor.cpp
fdbserver/workloads/BlobGranuleCorrectnessWorkload.actor.cpp
fdbserver/workloads/FuzzApiCorrectness.actor.cpp
fdbserver/workloads/TenantManagement.actor.cpp

Resolves #7260.
This updates the `createTenantTransaction` function to take the tenant ID as a parameter rather than compute it itself. Update the special key-space tenant creation logic to generate a unique ID for each tenant being created.
Updated the tenant management test to detect the previous issue and verify the fix.

Support creating multiple tenants in the same transaction

---

fdbserver/LogSystemDiskQueueAdapter.actor.cpp
fdbserver/LogSystemDiskQueueAdapter.h

The transaction state store is recovered by peeking old tLogs starting at a particular version. On fault injection, this recovery can be restarted with a different starting version `poppedver`, which is a value returned by the tLog. 
But the tLog may not have set this value. If it didn't , `poppedver` defaults to 0. The problem is `0` is arbitrary so may be invalid. 
This PR just fixes fault injection to not change the starting range if the tLog did not supply one.
simulation test failure:
1. A version range starting with 0 may include old epochs. 
2. To peek from an older epoch, the (`peekall`) logic selects a tLog that was recorded to have existed during that epoch (see `TLogPeekAllAddingOld`). 
3. Such a tLog may no longer be reachable (e.g. its DC was since powered off). 
4. Trying to …

fix a fault injection bug in txn store recovery

---

packaging/docker/sidecar.py
packaging/docker/sidecar_test.py

This is an initial attempt to make the Sidecar testable and add unit tests for it to test it without the requirement to spin up a cluster. In the long term this should give us more confidence in making changes in this script. I'm not an expert with the CI setup in this repository so I will probably consult @ammolitor how to integrate this in the CI runs.
Current run:
```bash
$ python3 sidecar_test.py
........
----------------------------------------------------------------------
Ran 8 tests in 0.050s
OK
```

Add testing for Kubernetes sidecar

---

fdbserver/ConfigBroadcaster.actor.cpp
fdbserver/ConfigDatabaseUnitTests.actor.cpp
fdbserver/PaxosConfigConsumer.actor.cpp
fdbserver/Status.actor.cpp

The configuration database report will look something like this in status json:
```
"configuration_database" : {
"commits" : [
{
"description" : "second test description",
"timestamp" : 1655170000,
"version" : 9
}
],
"last_compacted_version" : 0,
"most_recent_version" : 9,
"mutations" : [
{
"config_class" : "",
"knob_name" : "min_trace_severity",
"knob_value" : "int:5",
"version" : 1
},
{
"config_class" : "",
"knob_name" : "min_trace_severity",
"knob_value" : "int:5",
"version" : 2
},
{
"config_class" : "az-1",
"knob_name" : "min_trace_severity",
"knob_value" : "int:5",
"version" : 3
},
{
"config_class" : "az-1",
"knob_name" : "min_trace_severity",
"knob_value" : "int:5",
"version" : 4
}
],
"snapshot" : {
"" : {
"min_trace_severity" : "int:5"
},
"az-1" : {
"min_trace_severity" : "int:5"
} …
```

Reenable status json for dynamic knobs and add a unit test

---

flow/Arena.h

This checks the length of the data before calling memcpy to avoid the potential for calling `copyTo` on a `StringRef` that has an invalid data pointer and 0 length.

Add check to avoid using memcpy with an invalid data pointer

---

fdbserver/ClusterController.actor.cpp
fdbserver/ClusterController.actor.h

In gray failure detection, currently there are two ways that the cluster controller will consider a degraded peer is health: (1) that peer is not reported by a worker for some period of time, or (2) that worker sends a peer degradation report that doesn't include this previous degraded peer.
This PR removes the second mechanism since it may be false positive that the degraded peer is recovered. This is because when a worker checks a peer, there is a minimum number of measurement samples required. If the measurement sample is too small, the worker won't check for this peer. This may make the cluster controller falsely treats the degraded peer as recovered.
This won't be a huge issue in prod cluster given that the number of measurement samples is always large, but affects testing clusters …

Remove explicit degraded peer recovery since this may be false positive

---

fdbserver/LogSystemDiskQueueAdapter.actor.cpp
fdbserver/LogSystemDiskQueueAdapter.h

Cherry pick PR `https://github.com/apple/foundationdb/pull/7405`
The transaction state store is recovered by peeking old tLogs starting at a particular version. On fault injection, this recovery can be restarted with a different starting version poppedver, which is a value returned by the tLog.
But the tLog may not have set this value. If it didn't , poppedver defaults to 0. The problem is 0 is arbitrary so may be invalid.
This PR just fixes fault injection to not change the starting range if the tLog did not supply one.
simulation test failure:
- A version range starting with 0 may include old epochs.
- To peek from an older epoch, the (peekall) logic selects a tLog that was recorded to have existed during that epoch (see TLogPeekAllAddingOld).
- Such a tLog may no longer be reachable …

cherry pick pr 7405 to 71 branch

---

fdbserver/ClusterController.actor.cpp
fdbserver/ClusterController.actor.h

Cherry pick #7418 
20220627-170528-zhe-7.1-708f526d93139e69           compressed=True data_size=31512113 duration=2629329 ended=100002 fail_fast=10 max_runs=100000 pass=100002 priority=100 remaining=0 runtime=0:36:10 sanity=False started=100315 stopped=20220627-174138 submitted=20220627-170528 timeout=5400 username=zhe-7.1

[release 7.1] Remove explicit degraded peer recovery since this may be false positive

---

fdbrpc/simulator.h

Valgrind was reporting access to an uninitialized field.

Initialize uninitialized field

---

.git-blame-ignore-revs

Generally, when looking at `git blame`, I don't want to see format commits as they don't affect functionality.  `git blame` has a parameter to ignore a commit (see https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revltrevgt). The Github UI also [supports this feature](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view). This PR adds the format changes from #4464 and #5497 to the set of ignored revisions in `git blame`.
Locally, the ignored revisions file must be manually specified with `--ignore-revs-file`:
```
git blame --ignore-revs-file .git-blame-ignore-revs <file>
```
or it can be set globally:
```
$ git config --global blame.ignoreRevsFile .git-blame-ignore-revs
```
The general guidelines can …

Ignore format commits in git blame

---

packaging/docker/Dockerfile
packaging/docker/Dockerfile.eks
packaging/docker/build-images.sh

This allows users to use the docker images without any modification. The changes are made to reflect that binaries are now hosted on GitHub. 
I build the image locally with the following command:
```bash
docker build -t foundationdb/foundationdb-kubernetes:7.1.5-local --target fdb-kubernetes-monitor --build-arg FDB_VERSION=7.1.5 --build-arg FDB_LIBRARY_VERSIONS="7.1.5 6.3.24 6.2.30" -f packaging/docker/Dockerfile .
```
I will run an additional test for the `build-images.sh` script.

Refactor Docker setup for new binary location

---

fdbclient/NativeAPI.actor.cpp

Without `state`, the code compiles to
```
if (coordinator->get().get().hostname.present())
{
Hostname h = coordinator->get().get().hostname.get();
StrictFuture<Void> __when_expr_1 = store(coordinatorAddress, h.resolveWithRetry());
if (static_cast<GetClusterProtocolImplActor*>(this)->actor_wait_state < 0) return a_body1Catch1(actor_cancelled(), std::max(0, loopDepth - 1));
if (__when_expr_1.isReady()) {
if (__when_expr_1.isError()) return a_body1Catch1(__when_expr_1.getError(), std::max(0, loopDepth - 1));
else return a_body1loopBody1when2(__when_expr_1.get(), loopDepth);
};
static_cast<GetClusterProtocolImplActor*>(this)->actor_wait_state = 2;"
__when_expr_1.addCallbackAndClear(static_cast<ActorCallback< GetClusterProtocolImplActor, 1, Void …
```

Fix a problem caused by missing state.

---

fdbclient/NativeAPI.actor.cpp

PR on main: #7479.
Without `state`, the code compiles to
```
if (coordinator->get().get().hostname.present())
{
Hostname h = coordinator->get().get().hostname.get();
StrictFuture<Void> __when_expr_1 = store(coordinatorAddress, h.resolveWithRetry());
if (static_cast<GetClusterProtocolImplActor*>(this)->actor_wait_state < 0) return a_body1Catch1(actor_cancelled(), std::max(0, loopDepth - 1));
if (__when_expr_1.isReady()) {
if (__when_expr_1.isError()) return a_body1Catch1(__when_expr_1.getError(), std::max(0, loopDepth - 1));
else return a_body1loopBody1when2(__when_expr_1.get(), loopDepth);
};
static_cast<GetClusterProtocolImplActor*>(this)->actor_wait_state = 2;"
__when_expr_1.addCallbackAndClear(static_cast<ActorCallback< GetClusterProtocolImplActor, 1, Void …
```

Fix a problem caused by missing state (release-7.1).

---

fdbcli/TenantCommands.actor.cpp

In the recent PR to apply my changes to the gettenant command to the main branch, a return statement in the error case got omitted. This adds that missing statement.

Add missing return statement in fdbcli gettenant command error case

---

fdbserver/GlobalTagThrottler.actor.cpp

This fixes some timeouts in the global tag throttling unit tests, by increasing the error tolerance for an "acceptable" equilibrium TPS limit from 0.1 to 1.0.

Make GlobalTagThrottlerTesting::monitorClientRates more lenient

---

fdbclient/SystemData.cpp
fdbclient/Tenant.cpp
fdbclient/include/fdbclient/SystemData.h
fdbclient/include/fdbclient/Tenant.h
fdbclient/include/fdbclient/TenantManagement.actor.h
fdbserver/ApplyMetadataMutation.cpp
fdbserver/BlobManager.actor.cpp
fdbserver/BlobWorker.actor.cpp
fdbserver/TenantCache.actor.cpp
fdbserver/storageserver.actor.cpp

This also adds a specific version to the encoding that matches the version this object was introduced (as is the only version used for it so far).

Refactor how tenant map entries are encoded and decoded

---

fdbserver/storageserver.actor.cpp

Improves cpu efficiency of finding change feed mutations in memory by binary searching, or exponential searching in cases where that is likely to be significantly more efficient than binary searching. 
Testing summary.
Correctness: passed 10k BlobGranule* tests, and added surgical validation ASSERTs to ensure correctness
Performance:
- in instrumented tests, number of search comparisons with the exponential search if atLatest optimization was ~1.8x fewer on average than always doing binary search, and > 30x fewer comparisons than the previous linear search
- On average, in single-process write-only tests, storage server cpu as a whole was around 8% lower, for both uniform random and sequential write workloads.
Workload generation with mako:
sequential:
mako -p 1 -t 1 --keylen 32 --vallen …

Change Feed Reading CPU optimization

---

fdbbackup/backup.actor.cpp
fdbclient/FileBackupAgent.actor.cpp
fdbclient/include/fdbclient/BackupAgent.actor.h
fdbclient/include/fdbclient/FDBTypes.h
fdbclient/include/fdbclient/KeyBackedTypes.h
fdbclient/include/fdbclient/RunTransaction.actor.h
fdbclient/include/fdbclient/TaskBucket.h
fdbserver/ApplyMetadataMutation.cpp
fdbserver/BackupWorker.actor.cpp
fdbserver/MoveKeys.actor.cpp
fdbserver/RestoreApplier.actor.cpp
fdbserver/TSSMappingUtil.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/workloads/BackupAndParallelRestoreCorrectness.actor.cpp
fdbserver/workloads/BackupCorrectness.actor.cpp

This updates all of the operations on key backed types to take a templated `Transaction` or `DB` variable. This lets us use the `IClientAPI` interfaces in addition to `ReadYourWrites`.
This also renames the `Codec` class to `TupleCodec` and then adds template parameters to each key backed type to allow one to choose the codec being used.

Update key backed types to support multiple transaction types and different codecs

---

fdbclient/include/fdbclient/VersionVector.h
flowbench/BenchVersionVectorSerialization.cpp

Add a google benchmark to measure the execution time of version vector serialization/deserialization code.
Version vector serialization/deserialization by using "serializable_traits" version of code:
-------------------------------------------------------------------------------------------------
Benchmark                                       Time             CPU   Iterations UserCounters...
-------------------------------------------------------------------------------------------------
bench_serializable_traits_version/16         1339 ns         1343 ns       522268 Size=104 Tags=16 items_per_second=744.681k/s
bench_serializable_traits_version/64         2370 ns         2375 ns       288902 Size=200 Tags=64 items_per_second=421k/s
bench_serializable_traits_version/512       29612 ns …

Microbenchmark version vector serialization/deserialization code

---

documentation/sphinx/source/tenants.rst

Backports https://github.com/apple/foundationdb/pull/7219.
This configuration key may end up being removed, so we'll remove the documentation of it for now.

Remove tenant prefix documentation (backport #7219 to snowflake/release-7.1)

---

fdbclient/DatabaseContext.h
fdbclient/NativeAPI.actor.cpp

Merge pull request #7482 from sbodagala/main.
Optimize out the version vector specific code on the client (the code that tries to update the version vector on receiving a read version reply from a GRV proxy, and the code in "DatabaseContext::getLatestCommitVersions()") when the version vector feature is disabled.
Testing:
Compiler: gcc.
Version vector disabled: 20220706-074612-sre-da2ffe3e53c1d0c8 (no failures).
Version vector enabled: 20220706-092503-sre-006bdedd8e02a4cf (no failures).

Cherry pick pull request #7482

---

fdbserver/ClusterRecovery.actor.cpp
fdbserver/include/fdbserver/MasterInterface.h
fdbserver/masterserver.actor.cpp

This is in the context of HA-related version vector optimization: propagate the locality of the primary region from ClusterController to the sequencer, rather than deriving it from "MasterInterface" on the sequencer (which is not correct). 
Testing:
Compiler: gcc.
Version vector disabled: 20220706-102147-sre-f3f7f09b7eac8fd9 (no failures).
Version vector enabled, knob ENABLE_VERSION_VECTOR_HA_OPTIMIZATION enabled: 20220706-103407-sre-180fb8af27a15e6d (no failures).

Make sequencer aware of the locality of the primary region

---

fdbserver/masterserver.actor.cpp

Cherry pick PR 7531
Change `VersionVectorTagUpdates` to `LatencySample`, so it gives meaning information on the number of tags modified in the version vector over intervals of time.

Cherry pick pr7531 - Change VersionVectorTagUpdates to LatencySample.

---

fdbclient/include/fdbclient/TenantManagement.actor.h
flow/include/flow/genericactors.actor.h

This can be helpful testing correct behavior of some transactions in simulation

Add a helper to simulate a commit that can fail with unknown result or take a long time

---

fdbserver/Resolver.actor.cpp

The erased bytes from recent state transactions was accidentally set to 0 and
cause anyPopped to be always false. Thus, when totalStateBytes will never
decrease and can cause high latency between "Resolver.resolveBatch.Before" and
"Resolver.resolveBatch.AfterQueueSizeCheck", in hundreds of milliseconds. This
will cause high server side commit latency.
Verified that `ResolverMetrics::ResolvedStateBytes` no longer monotonically increases in a manual simulation test.

Fix a performance bug in Resolver

---

fdbserver/Resolver.actor.cpp

Cherrypick #7547
The erased bytes from recent state transactions was accidently set to 0 and
cause anyPopped to be always false. Thus, when totalStateBytes will never
decrease and can cause high latency between "Resolver.resolveBatch.Before" and
"Resolver.resolveBatch.AfterQueueSizeCheck", in hundreds of milliseconds. This
will cause high server side commit latency.

Fix a performance bug in Resolver [release-7.1]

---

fdbserver/ClusterRecovery.actor.cpp
fdbserver/MasterInterface.h
fdbserver/masterserver.actor.cpp

Merge pull request #7529 from sbodagala/main.
This is in the context of HA-related version vector optimization: propagate the locality of the primary region from ClusterController to the sequencer, rather than deriving it from "MasterInterface" on the sequencer (which is not correct).
Testing:
Compiler: gcc.
Version vector disabled: 20220707-091505-sre-f49dde440378fc4f (no failures).
Version vector enabled, knob ENABLE_VERSION_VECTOR_HA_OPTIMIZATION enabled: 20220707-092621-sre-b678a4cd14287395 (no failures). …

Cherry pick pull request #7529

---

fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
fdbserver/include/fdbserver/IKeyValueStore.h

1. Replaced `DataShard` with `PhysicalShard` in each `Read.*Action`, so that even a DataShard is destructed in the main thread, the reader thread can continue do the reads.
2. Avoid modifying `dataShardMap` in the range-based loop in `removeRange()`.
3. Added implementation of readValuePrefix() 

Sharded RocksDB

---

fdbserver/DDTeamCollection.actor.cpp
fdbserver/DDTxnProcessor.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/DataDistributionQueue.actor.cpp
fdbserver/include/fdbserver/DDTxnProcessor.h
fdbserver/include/fdbserver/DataDistribution.actor.h

move one of the DD bootstrap step to txnProcessor.

[DD Testability] move takeMoveKeysLock to DDTxnProcessor

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/DataDistribution.actor.cpp

A very simple change to add a knob SNAPSHOT_ALL_STATEFUL_PROCESSES to snapshot all processes with the stateful class type(storage, log, transaction) even if they are not recruited
The change has no effect on simulation as in simulation, we simply copy data files under `simfdb/`,
processes snapshotted but without the data files will not trigger any difference.
In a real cluster, this will help provision disks for these processes in the restore.
Passes 100K correctness tests.

Support snapshotting all stateful FDB processes, even if not recruited

---

bindings/java/src/main/com/apple/foundationdb/tuple/Tuple.java
bindings/java/src/main/com/apple/foundationdb/tuple/TupleUtil.java

There is a hotspot when creating a lot of tuples.

Changing hasIncompleteVersionstamp to use iteration rather than stream processing #7543

---

bindings/java/src/main/com/apple/foundationdb/tuple/Tuple.java
bindings/java/src/main/com/apple/foundationdb/tuple/TupleUtil.java

Changing hasIncompleteVersionstamp to use iteration rather than stream processing [release-7.1]

---

tests/loopback_cluster/run_custom_cluster.sh

This script builds a single machine cluster with arbitrary number of stateless, logs, and storages roles. The classes may be pinned to CPUs on the machine (`taskset`). Useful to test different configurations of FDB on servers with many CPUs.
```
Usage
'cd working-directory; ./run_custom_cluster.sh path-to-build-root [OPTIONS]
Options
--knobs '--knob-KNOBNAME=KNOBVALUE' 
Changes a database knob. Enclose in single quotes.
--stateless_count COUNT
number of stateless daemons to start.  Default 4
--stateless_taskset BITMASK
Bitmask of CPUs to pin stateless tasks to. Default is all CPUs.
--logs_count COUNT
Number of stateless daemons to start.  Default 8
--logs_taskset BITMASK
bitmask of CPUs to pin logs to. Default is all CPUs.
--storage_count COUNT
number of storage daemons to start.  Default …
```

script to build a custom loopback cluster

---

fdbclient/NativeAPI.actor.cpp

When setting knob_fetch_using_streaming to true for data movement, we found that the IKVS::ReadType passed into storage readRange is not IKVS::ReadType::Fetch. The req.isFetchKeys is not set in the getRangeStreamFragment function. This PR initializes req.isFetchKeys. 

set isFetchKeys for getRangeStreamFragment

---

fdbserver/VersionedBTree.actor.cpp

IPager.h header file is included twice. 

Redwood remove duplicate header files

---

bindings/c/CMakeLists.txt
fdbserver/KeyValueStoreMemory.actor.cpp
fdbserver/TLogServer.actor.cpp

After this change, statically linking libcxx seems to work for UBSAN. Also fix a few instances of UB that are showing up in simulation frequently.

Fix UBSAN build when statically linking libcxx

---

fdbserver/ClusterController.actor.cpp
fdbserver/include/fdbserver/ClusterController.actor.h
fdbserver/include/fdbserver/WorkerInterface.actor.h
fdbserver/worker.actor.cpp

Previously worker servers only register with cluster controller after local file recovery. This PR change to let worker servers register itself before local file recovery, but indicate that although it can server stateless roles, it cannot become storage or TLog server. After local file recovery, the worker will register again to indicate it can now become storage and Tlog.
The change fixes the deadlock issue with encryption, where when there's only stateful workers that can become master and EKP, those worker servers won't be able to register with cluster controller since no EKP is available to provide cipher keys to decrypt encrypted storage.
For now we have the change only when encryption is on, and will make it the default behavior once we think it is stable.
The general guidelines …

Worker register with cluster controller before disk file recovery

---

bindings/python/tests/fdbcli_tests.py
documentation/sphinx/source/release-notes/release-notes-710.rst
documentation/sphinx/source/release-notes/release-notes-720.rst
fdbcli/fdbcli.actor.cpp

This allows specifying the string `"1"` instead of `"\x01\x00\x00\x00\x00\x00\x00\x00"`.
Resolves #7526 

Parse integer options in fdbcli rather than passing the bytes unparsed

---

fdbclient/Tracing.actor.cpp

In the `operator=` overload we need to check if the current span that is being
overwritten is eligible for serialization. If so we must send to the tracer
via the `g_tracer->trace(*this)` call. Previously we were incorrectly checking
the function argument `o`'s context for sampling. This resulted in lost traces
for the `NAPI:readVersionBatcher` spans.
Unit tested, Correctness tested, and manually verified using OTEL distributed tracing collector.

Conditional on context.isSampled in Span operator=().

---

fdbclient/ServerKnobs.cpp
fdbserver/fdbserver.actor.cpp

Seeing around 10-50 failures out of a million runs due to remote kv store testing in simulation. Disabling for now until it can be fixed.

Disable testing of the remote key value store in simulation

---

bindings/c/CMakeLists.txt
bindings/c/test/fdb_c_shim_tests.py
contrib/ctest_to_joshua.py

* Package inferred directories to the resulting tarball in ctest_to_joshua (except for the root source and build directories). This allows the API tests (which specify the workloads as a directory containing the workload specification files) to now work. 
* Add bin/mkcert which is used by some tests.
* Rewrite fdb_c_shim_tests.py to specify its dependencies on command line. 

Update ctest_to_joshua to work with new ctests

---

fdbserver/ClusterController.actor.cpp
fdbserver/KeyValueStoreMemory.actor.cpp
fdbserver/SimulatedCluster.actor.cpp
fdbserver/Status.actor.cpp
fdbserver/fdbserver.actor.cpp
fdbserver/include/fdbserver/EncryptedMutationMessage.h
fdbserver/tester.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp
fdbserver/workloads/SaveAndKill.actor.cpp
tests/restarting/to_7.1.0/ConfigureStorageMigrationTestRestart-1.toml
tests/restarting/to_7.1.0/CycleTestRestart-1.txt

Previously to get around the issue that EKP is not present when restart test switching encryption from on to off and read encrypted data, EKP was made to start in simulation regardless of encryption knob. This PR revert that change, and instead force restart test not to change encryption knob, by passing previous encryption knob through restartInfo.ini file. Also since we don't allow downgrading an encrypted cluster to previous version, disable encryption in downgrade tests.
Also adding an assert to allow reading encrypted mutations only if encryption knob is on. We may reconsider allowing switching encryption on/off for existing cluster, but for now we don't allow it. …

Restart tests carry forward encryption knobs value

---

fdbserver/KeyValueStoreRocksDB.actor.cpp

Cherrypick #7551
Adding rocksdb compression and data size stats.
Test output:
"LevelStats":"Level Files Size(MB)\x0a--------------------\x0a 0 2 502\x0a 1 0 0\x0a 2 0 0\x0a 3 0 0\x0a 4 15 891\x0a 5 37 2101\x0a 6 206 12226\x0a",
"CompressionRatioAtLevel":"0:1.010337,1:-1.000000,2:-1.000000,3:-1.000000,4:1.011170,5:1.013587,6:1.012863,"

Adding rocksdb compression and data size stats

---

bindings/python/tests/fdbcli_tests.py
bindings/python/tests/tenant_tests.py
documentation/sphinx/source/command-line-interface.rst
fdbcli/TenantCommands.actor.cpp
fdbcli/fdbcli.actor.cpp
fdbcli/include/fdbcli/fdbcli.actor.h
fdbclient/include/fdbclient/TenantManagement.actor.h
fdbclient/include/fdbclient/TenantSpecialKeys.actor.h
fdbclient/include/fdbclient/libb64/decode.h
fdbserver/workloads/TenantManagementWorkload.actor.cpp

The previous encoded used raw bytes presented as a unicode string, but this could is not standard and could not be decoded by some JSON libraries.
Now, the prefix is presented as an object with two fields: a base64 encoding of the binary string and a printable representation.

Use a more standard encoding in the JSON metadata reported for tenants

---

flow/Platform.actor.cpp

This allows their stack trace to be symbolized in CI/Jenkins XSAN runs

Apply RTLD_NODELETE for USE_SANITIZER builds

---

flow/Platform.actor.cpp

Fix processDiskReadSeconds and processDiskWriteSeconds (release-7.1).

---

flow/Platform.actor.cpp

Fix processDiskReadSeconds and processDiskWriteSeconds.

---

fdbclient/NativeAPI.actor.cpp

`getKeyLocation_internal` did not update the SSID->Tag cache when receiving results from the proxy's `GetKeyServerLocationsRequest` interface. This can result in `ssidTagMapping` not having information to populate the version vector, in turn resulting in the latest commit version used to fetch data from the SS. This caused waitForVersion to be entered, which can delay responses up to `BLOCKING_PEEK_TIMEOUT` (currently .4) seconds. If a specific workload from a client is being run this can be indefinite.
Tested running `mako` and verifying read latency fell back to baseline (non vv) levels.
`20220719-144218-henrylambright-bc617501d091b257 ` …

update tag client cache on getKeyLocation

---

fdbserver/storageserver.actor.cpp

The use of these functions causes the strings to be escaped twice.

Remove some instances of using printable or toString in a trace event detail

---

fdbclient/NativeAPI.actor.cpp

Cherry pick PR #7613.
getKeyLocation_internal did not update the SSID->Tag cache when receiving results from the proxy's GetKeyServerLocationsRequest interface. This can result in ssidTagMapping not having information to populate the version vector, in turn resulting in the latest commit version used to fetch data from the SS. This caused waitForVersion to be entered, which can delay responses up to BLOCKING_PEEK_TIMEOUT (currently .4) seconds. If a specific workload from a client is being run this can be indefinite.
Tested running mako and verifying read latency fell back to baseline (non vv) levels.
`20220719-152356-henrylambright-1d7ef76da4e02f1d` …

Cherry pick 7613 update tag client cache on getKeyLocation

---

fdbserver/BlobGranuleServerCommon.actor.cpp
fdbserver/MoveKeys.actor.cpp
fdbserver/include/fdbserver/BlobGranuleServerCommon.actor.h

This removes one unused variable and changes two functions to be non-static.

Fix a few compile warnings about unused variables

---

tests/loopback_cluster/run_custom_cluster.sh

some simple replication support in loopback tests.
- Each process is its own "machine" (which may be assigned to an actual core) .
- Processes are divided into zones. Number of zones equals replication count.
- Set coordinators using auto

simple replication support for test loopback cluster

---

fdbserver/StorageCache.actor.cpp
fdbserver/storageserver.actor.cpp

`readQueueSizeMetric` used to be stored in scope database, but was never used. So it's better to remove it for clarity.
10k correctness 20220719-215242-jzhou-c8f6e67476d0a133 passed.

Remove unused "readQueueSizeMetric"

---

fdbclient/azure_backup/BackupContainerAzureBlobStore.actor.cpp

The code adds a workaround for a Segfault appearing deep inside the azure sdk. The code checks for the existence of a
container before attempting creation. This is related to issue https://github.com/apple/foundationdb/issues/7570
Please note this code is enabled only when -DBUILD_AZURE_BACKUP=ON is turned on via cmake.
Release branches vs Master/main
Master has the affected file inside a subdirectory azure_backup. Release 7.1 branch (the release I am using) has the same file in the parent directory. I will be making a separate pull request for Release 7.1 and Release 7.2 branch.
If this …

Backups, Azure, Issue 7570: Check existance of container before creation attempt

---

fdbserver/OldTLogServer_6_0.actor.cpp
fdbserver/OldTLogServer_6_2.actor.cpp
fdbserver/TLogServer.actor.cpp

For better identifying Storage Servers that are required to recover after new epoch.
20220720-190851-zhewu-tlogready-b1fe4c8b7e7e2bbd   compressed=True data_size=34672710 duration=4004105 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:40:55 sanity=False started=100240 stopped=20220720-194946 submitted=20220720-190851 timeout=5400 username=zhewu-tlogready

Increase AllTags field length in TLogReady TraceEvent

---

fdbclient/include/fdbclient/CoordinationInterface.h
fdbclient/include/fdbclient/MultiVersionTransaction.h
flow/Arena.cpp
flow/include/flow/Arena.h

* Add the ability for StringRef.eat to return whether a separator was found. 
* Add a serialize function and equality operators to ClusterConnectionString. 
* Remove unused variable.

Add some helper functions to ClusterConnectionString and an improvement to StringRef.eat

---

bindings/c/test/unit/unit_tests.cpp
documentation/sphinx/source/global-configuration.rst
fdbcli/ProfileCommand.actor.cpp
fdbclient/ConfigKnobs.cpp
fdbclient/FileBackupAgent.actor.cpp
fdbclient/GlobalConfig.actor.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/SpecialKeySpace.actor.cpp
fdbclient/TagThrottle.actor.cpp
fdbclient/TaskBucket.actor.cpp
fdbclient/Tuple.cpp
fdbclient/include/fdbclient/BackupAgent.actor.h
fdbclient/include/fdbclient/HighContentionPrefixAllocator.actor.h
fdbclient/include/fdbclient/KeyBackedTypes.h
fdbclient/include/fdbclient/Subspace.h
fdbclient/include/fdbclient/Tuple.h
fdbserver/MetricLogger.actor.cpp
fdbserver/include/fdbserver/RestoreCommon.actor.h
fdbserver/storageserver.actor.cpp
fdbserver/workloads/ClientTransactionProfileCorrectness.actor.cpp
fdbserver/workloads/ConfigIncrement.actor.cpp
fdbserver/workloads/GetMappedRange.actor.cpp
fdbserver/workloads/TaskBucketCorrectness.actor.cpp

This also updates Tuple to allow all types to be passed via .append() so they can be used with makeTuple.
Note: this changes the type of the timestamp in [this tuple](https://github.com/apple/foundationdb/blob/0e03fbd9e7a01790a65305a14a9c915f733a6561/fdbclient/NativeAPI.actor.cpp#L1137) from int to double, but @sfc-gh-jslocum says this should be ok.

Add a Tuple::makeTuple function to easily construct a tuple

---

fdbserver/TagPartitionedLogSystem.actor.cpp

This is similar to `Commit/GrvProxy/ResolverReplies` TraceEvent during recovery. It helps to track participants in the new epoch.
20220720-220451-zhewu-log-tlog-init-30c40daeece3219b compressed=True data_size=34674088 duration=4922701 ended=100001 fail_fast=10 max_runs=100000 pass=100001 priority=100 remaining=0 runtime=0:27:27 sanity=False started=100109 stopped=20220720-223218 submitted=20220720-220451 timeout=5400 username=zhewu-log-tlog-init

Add TraceEvent for TLog initialization

---

fdbclient/SpecialKeySpace.actor.cpp
fdbclient/include/fdbclient/FDBTypes.h
fdbclient/include/fdbclient/SpecialKeySpace.actor.h
fdbserver/workloads/ReportConflictingKeys.actor.cpp

We need test coverage of reading subranges within special key space modules, as
there was a bug that could only manifest if you read a subrange of the
conflicting keys module.
- Add a utility that provides validation to special key space subrange reads in simulation
- Fix bugs turned up by validating subrange reads

Validate subrange reads in simulation

---

fdbclient/NativeAPI.actor.cpp

This is to figure out why huge databaseLogger related TraceEvents
generated after 7.1 released.

Add TraceEvent to the construction/destruction of DatabaseContext

---

fdbserver/storageserver.actor.cpp

Clang gives this diagnostic:
```
fdbserver/storageserver.actor.cpp:654:24: error: cannot pass object of non-trivial type 'const std::string' (aka 'const basic_string<char, char_traits<char>, allocator<char>>') through variadic function; call will abort at runtime [-Wnon-pod-varargs]
```
Just use fmt instead.

Don't pass non-pod to variadic function

---

fdbclient/NativeAPI.actor.cpp

Cherrypick #7662 
This is to figure out why huge databaseLogger related TraceEvents
generated after 7.1 released.

Add TraceEvent to the construction/destruction of DatabaseContext [release-7.1]

---

bindings/python/tests/fdbcli_tests.py
fdbcli/TenantCommands.actor.cpp
fdbclient/Tenant.cpp
fdbclient/include/fdbclient/SystemData.h
fdbclient/include/fdbclient/Tenant.h
fdbclient/include/fdbclient/TenantManagement.actor.h
fdbclient/include/fdbclient/TenantSpecialKeys.actor.h
fdbserver/ApplyMetadataMutation.cpp
fdbserver/BlobManager.actor.cpp
fdbserver/BlobWorker.actor.cpp
fdbserver/TenantCache.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/workloads/BlobGranuleCorrectnessWorkload.actor.cpp
fdbserver/workloads/TenantManagementWorkload.actor.cpp

This also adds a new `TenantState` field that will be used in the future metacluster work and does some other refactoring.

Use key-backed types for tenants

---

flow/FastAlloc.cpp

See #7610 for demonstration that guard pages count against VG_N_SEGMENTS limit

Disable guard pages for valgrind build

---

fdbserver/storageserver.actor.cpp

Since GRV error is an RPC error, which doesn't indicate that SS is in a bad state, any error thrown from getting the GRV shouldn't be thrown above fetchKeys()
20220725-053453-zhewu-fix-6600c816ddcc85d1         compressed=True data_size=34958013 duration=5344490 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:09:17 sanity=False started=100450 stopped=20220725-064410 submitted=20220725-053453 timeout=5400 username=zhewu-fix
(The failed test is not related to this PR, it fails at main branch as well)
I also did cluster testing using FDB deployed in a kubernetes cluster. With new way of handling GRV errors in SS, SS can no longer be terminated due to GRV errors. …

Error in FetchKey GRV shouldn't fail storage server

---

fdbserver/storageserver.actor.cpp

Cherrypick #7683 
20220725-164619-zhewu-grv-cherrypick-8da10f5d038e1418 compressed=True data_size=31507644 duration=5314363 ended=100005 fail_fast=10 max_runs=100000 pass=100005 priority=100 remaining=0 runtime=1:11:46 sanity=False started=100244 stopped=20220725-175805 submitted=20220725-164619 timeout=5400 username=zhewu-grv-cherrypick

[release 7.1] Error in FetchKey GRV shouldn't fail storage server

---

documentation/sphinx/source/mr-status-json-schemas.rst.inc
fdbclient/Schemas.cpp
fdbserver/Status.actor.cpp

Cherrypick #7681 and other changes from main. This is for #7684.  `storageWigglerStatsFetcher()` has diverged on main, so the fix to it is specific to 7.1.
Otherwise, the status generation becomes a blocking call, which is undesirable,
because many operational tools require a timely response, even if it is in-
complete.
100k 20220724-220008-jzhou-ffaac6fc4d869434 passed.

Add timeout to places during Status generation

---

fdbserver/TLogServer.actor.cpp

For easier unrecovered tag identification.
20220726-012311-zhewu-tlog-recover-tag-9a3b7ad8423eadca compressed=True data_size=34901148 duration=4560691 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:02:55 sanity=False started=100097 stopped=20220726-022606 submitted=20220726-012311 timeout=5400 username=zhewu-tlog-recover-tag

Print out unrecovered tags in TLogPoppedTag event

---

fdbserver/TLogServer.actor.cpp

[release 7.1] Print out unrecovered tags in TLogPoppedTag event

---

fdbserver/Status.actor.cpp

actor_cancel should be thrown, otherwise the rest code can access invalid
memory.
100k Status tests 20220726-182507-jzhou-0849bcdb1315c2cf 

Fix a crash bug during CC shutdown process

---

contrib/transaction_profiling_analyzer/transaction_profiling_analyzer.py

We're trying to interpret an Optional<TenantName> here, but the
python truthiness of self.get_bytes(1) is _always_ true, since it's
non-empty. We need to look at the _contents_ of that byte instead.

Fix incorrect deserialization of FdbClientLogEvents::Event

---

fdbclient/NativeAPI.actor.cpp
fdbserver/BlobGranuleValidation.actor.cpp
fdbserver/BlobManager.actor.cpp
fdbserver/include/fdbserver/BlobGranuleValidation.actor.h
fdbserver/workloads/BlobGranuleVerifier.actor.cpp

Collection of several bug fixes and testing improvements to granule purging. Still not correctness clean so enablePurging is still turned off for merge

Granule Purge Fixes

---

bindings/python/tests/fdbcli_tests.py
contrib/libb64/include/libb64/decode.h
fdbcli/TenantCommands.actor.cpp
fdbcli/fdbcli.actor.cpp
fdbcli/include/fdbcli/fdbcli.actor.h
fdbclient/SystemData.cpp
fdbclient/Tenant.cpp
fdbclient/TenantSpecialKeys.cpp
fdbclient/include/fdbclient/Tenant.h
fdbclient/include/fdbclient/TenantManagement.actor.h
fdbclient/include/fdbclient/TenantSpecialKeys.actor.h
fdbserver/tester.actor.cpp
fdbserver/workloads/FuzzApiCorrectness.actor.cpp
fdbserver/workloads/TenantManagementWorkload.actor.cpp
flow/include/flow/error_definitions.h
tests/slow/SwizzledTenantManagement.toml
tests/slow/TenantManagement.toml

This adds support for the ability to group tenants. This doesn't currently have much impact, but it will be used to form placement groups in a metacluster, and I believe it will also be used in tenant-aware data distribution and quota related features.

Add support for tenant groups

---

fdbclient/ClientKnobs.cpp
fdbclient/include/fdbclient/ClientKnobs.h
fdbclient/include/fdbclient/Tenant.h
fdbclient/include/fdbclient/TenantManagement.actor.h
fdbclient/include/fdbclient/TenantSpecialKeys.actor.h
fdbserver/BlobManager.actor.cpp
fdbserver/BlobWorker.actor.cpp
fdbserver/TenantCache.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/workloads/TenantManagementWorkload.actor.cpp
flow/include/flow/error_definitions.h

This change adds a knob that sets how many tenants can be in a cluster. When the number of tenants exceeds this amount, an error indicating the issue is raised.
This also adds a counter key for the number of tenants that is used to enforce the limit.

Add a limit to the number of tenants that can be created in a cluster

---

fdbserver/Status.actor.cpp

`if (iface.metadata.present()) {` guarantee `storage_metadata` won't throw `attribute_not_found()` it doesn't need to be in the `try..catch` block.
BTW, it seems like `BusiestReadTag` event removing the `TagCost` field causes the problem.
```
logs/trace.10.180.1.234.9800.1658963411.M9jyyK.0.1.xml:<Event Severity="10" Time="1658963565.378774" DateTime="2022-07-27T23:12:45Z" Type="BusiestReadTag" ID="6382b4324e520733" Elapsed="30" TotalSampledCost="4" Reported="0" ThreadID="12400470774736890218" Machine="10.180.1.234:9800" LogGroup="default" Roles="CC,CD,CP,DD,GP,MS,RK,RV,SS,TL" TrackLatestType="Original" />
``` …

fix storage_metadata disappear because other attribution is missed

---

fdbclient/SpecialKeySpace.actor.cpp
fdbclient/SpecialKeySpace.actor.h
fdbserver/workloads/ReportConflictingKeys.actor.cpp

Validate subrange reads in simulation (#7597) (snowflake-7.1)

---

fdbclient/SpecialKeySpace.actor.cpp
fdbclient/SpecialKeySpace.actor.h
fdbserver/workloads/ReportConflictingKeys.actor.cpp

Validate subrange reads in simulation (#7597) (release-7.1)

---

fdbclient/ManagementAPI.actor.cpp
fdbserver/ClusterRecovery.actor.cpp
fdbserver/CommitProxyServer.actor.cpp
fdbserver/include/fdbserver/MasterInterface.h

There was a rare but possible issue where a change coordinators request
could be in flight, but reading `\xff/coordinators` would return the old
set of coordinators, even though a previous attempt to write it returned
`commit_unknown_result`. This happened if there was an unrelated
recovery between setting `\xff/coordinators` and the updated
coordinators reaching each machine. The `commit_unknown_result` caused
by this recovery meant the change coordinators retry loop would read
`\xff/coordinators`, but since the request was ongoing it would read the
old set of coordinators. The fix is to have the cluster controller
ignore any change coordinators request from an old generation, meaning
when the retry loop reads the old coordiantors from `\xff/coordinators`,
it is guaranteed that the in …

Ensure change coordinators request came from the same generation proxy

---

fdbrpc/TokenCache.actor.cpp
fdbrpc/TokenSign.cpp

This unit test wasn't written for simulation, so it was consistently failing in joshua. This changes the test so it doesn't use non-deterministic functionality

fix token cache unit test

---

fdbclient/SpecialKeySpace.actor.cpp
fdbclient/SpecialKeySpace.actor.h
fdbserver/workloads/ReportConflictingKeys.actor.cpp

Cherry-pick the bug fix #7597 
- remove `fmt::print`
- `Reverse::False` and `Snapshot::True` to boolean

Validate subrange reads in simulation (#7597) (release-7.0)

---

fdbrpc/TokenCache.actor.cpp

The expiration time was generated by subtracting some number from the value returned by `g_network->timer()` and then casting this to a `uint64_t`. If the value subtracted was large enough, this caused the expiration time to underflow and become very large, and the token would not be expired as expected.

Fix bug in token cache unit test where the expiration time was underflowing

---

fdbclient/NativeAPI.actor.cpp
fdbserver/CommitProxyServer.actor.cpp

A tenant may have been able to make some requests with one tenant ID and then switch to another tenant ID part way through if the original tenant got deleted and recreated. Similarly, the dummy transaction could use a different tenant ID than the original. This latter case would cause an illegal tenant access error.

Fix: Transactions could change tenant ID part way through

---

fdbclient/SpecialKeySpace.actor.cpp
fdbclient/SpecialKeySpace.actor.h
fdbserver/workloads/ReportConflictingKeys.actor.cpp

Cherry-pick the bug fix #7597 
- remove `fmt::print`
- `RangeResult` changed back to `Standalone<RangeResultRef>`
- `Reverse::False` and `Snapshot::True` to boolean

Validate subrange reads in simulation (#7597) (release-6.3)

---

fdbclient/BlobGranuleFiles.cpp
fdbclient/include/fdbclient/BlobGranuleCommon.h
fdbclient/include/fdbclient/BlobGranuleFiles.h
fdbserver/BlobGranuleServerCommon.actor.cpp
fdbserver/BlobWorker.actor.cpp
fdbserver/include/fdbserver/BlobGranuleServerCommon.actor.h

Description
Major changes proposed by the patch are:
1. Refactor code to allow caching of 'encryption key ctx' as part of
BlobFilePointerRef. The refactoring allows snapshot and/or delta files
to store their own file encryption context.
2. Enable BlobGranule delta file encryption/decryption semantics.
Testing
BlobGranuleCorrrectness & BlobGranuleCorrectnessClean
BlobGranuleFileUnitTestToml

Encrypt  BlobGranule delta files

---

fdbserver/storageserver.actor.cpp

backporting https://github.com/apple/foundationdb/pull/7754

Retain debug id in prefetch server-server call(release-7.1)

---

fdbserver/workloads/ChangeFeedOperations.actor.cpp
tests/CMakeLists.txt
tests/fast/ChangeFeedOperationsMove.toml

Added 2 versions of test - both with chaos, but one with randomMoveKeys and one without
Latest run passes 100k correctness, except 1 TracedTooManyLines failure

Add Chaos to Change Feed Operations test

---

bindings/flow/Tuple.h
fdbclient/include/fdbclient/Tuple.h

This makes it less error-prone and more like other similar functions
like BinaryWriter::toValue
Closes #7748

Make Tuple::pack return a Standalone<StringRef>

---

fdbserver/DataDistribution.actor.cpp
flow/genericactors.actor.cpp
flow/include/flow/genericactors.actor.h

`waitForMost` is more like a generic actor rather than DD-specific.

move waitForMost into generic actors

---

design/global-tag-throttling.md
fdbclient/ServerKnobs.cpp
fdbserver/GlobalTagThrottler.actor.cpp
fdbserver/Ratekeeper.actor.cpp
fdbserver/Status.actor.cpp
fdbserver/TransactionTagCounter.cpp
fdbserver/include/fdbserver/Ratekeeper.h
fdbserver/include/fdbserver/TagThrottler.h
fdbserver/workloads/GlobalTagThrottling.actor.cpp
fdbserver/workloads/ReadWrite.actor.cpp

This pull request contains many improvements to the `GlobalTagThrottler`, initially introduced in https://github.com/apple/foundationdb/pull/7112. Among these improvements:
- Global tag throttler tracks more fine-grained metrics per storage server
- Tag quotas are now cleaned up properly when removed from the system keyspace
- Implemented `GlobalTagThrottler::busy*TagCount` methods
- Improved tracing
- A `/GlobalTagThrottling/` unit test suite is added (using a mock environment of clients, storage servers, and the global tag throttler)
- Several bug fixes uncovered by new unit test framework
- Documentation is added in comments and in `global-tag-throttling.md`
Please check …

Improvements to `GlobalTagThrottler`

---

fdbkubernetesmonitor/api/config.go
fdbkubernetesmonitor/api/config_test.go
fdbkubernetesmonitor/kubernetes.go

This is designed to support use cases on Kubernetes with a dual-stack network, where the IP comes as a list containing IPv4 and IPv6 addresses. This adds a new argument type to support selecting an IP address from a list, selecting the address with a specific IP family.
This is discussed in this issue on the operator: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1031

Add IP family argument to fdb-kubernetes-monitor

---

contrib/TestHarness/Program.cs

- Log OldBinary even if there are no trace files
- Add JoshuaSeed attribute to Test element in test harness
- Add NoTraceFilesFound event in test harness

Improve test harness logging when there are no trace files

---

fdbcli/BlobRangeCommand.actor.cpp
fdbclient/ClientKnobs.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/include/fdbclient/ClientKnobs.h

The blobrange check command would get stuck when each chunk got too big still.
Passes 1k BlobGranule* correctness

adding knob and fixing blobrange cli check bug with too many granules

---

fdbserver/include/fdbserver/workloads/MetaclusterConsistency.actor.h
fdbserver/include/fdbserver/workloads/TenantConsistency.actor.h

The metacluster and tenant consistency checks were setting range limits with an `int64_t` that overflowed the int type that was expected. Update the limit to be much smaller.

Fix integer overflow in test from setting a range limit too large

---

fdbclient/include/fdbclient/MetaclusterManagement.actor.h
fdbserver/workloads/TenantManagementConcurrencyWorkload.actor.cpp

In a metacluster, if a tenant creation on the data cluster permanently fails (because the tombstones have been cleaned up past its ID), it would retry the creation from the beginning. If that retry failed with a commit unknown result but actually committed, then the whole creation would fail out with a tenant already exists error and leave the management cluster in an inconsistent state. This happened because on retry, the operation would only succeed if the existing tenant matched the ID of the permanently failed creation.
The fix is to allow the create operation to work with any ID (so long as the configuration matches), exactly like it does before the data cluster failure. If the ID does match the failed ID, only then do we invoke the special replacement logic.
This also updates the …

Fix: tenant creation in metacluster failure

---

bindings/python/tests/size_limit_tests.py

This prevents future tests run with the same database being artificially limited in their byte sizes.

Reset the default transaction size limit at the end of the size limit test

---

fdbclient/include/fdbclient/BlobWorkerCommon.h
fdbserver/BlobWorker.actor.cpp

Add metric counters to compare compression ratio for blob files

add counters for blob compression

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/DDTeamCollection.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/include/fdbserver/DataDistribution.actor.h

Now the wiggler can finish 1 wiggle round every 2 days over a 25 storage server cluster (small cluster), which is more frequent than what is minimum to get the benefit of B-tree defragmentation and so on.
Then the storage server that is eligible for wiggle has to either:
* has wrong store engine or
* SS age > SS_MIN_AGE
pass 100k migration test, 100k simulation test

Make storage wiggler support SS_MIN_AGE

---

fdbclient/include/fdbclient/FDBTypes.h
fdbserver/DataDistribution.actor.cpp

This changes the timestamps to be relative to the knob that controls whether the servers are eligible. It also changes `StorageMetadataType` to take a double timestamp rather than `uint64_t` to allow smaller gaps between timestamps and to avoid the risk of underflow in this test.

Fix a bug in a storage wiggler unit test where some servers were added with too recent a timestamp

---

contrib/TestHarness/Program.cs
fdbserver/workloads/UnitTests.actor.cpp

When unit tests are run in test harness, the summarized result does not include the unit test name(s) if the test crashes (e.g. because it hit an assert and `--crash` is used). As a result, it is necessary to rerun a failed unit test run to even determine what the failed test was and triage it.
This change causes unit tests to log a trace event for every unit test it attempts to run, and the test harness adds this data to the summarize output.

Report the unit tests being run in test harness's summarized output

---

fdbserver/VersionedBTree.actor.cpp

The test was meant to cap the commit size to 10e6, but one of the arguments to the min function could overflow an int

Fix undefined behavior in versioned btree test due to integer overflow

---

fdbclient/ClientKnobs.cpp
fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp
fdbserver/workloads/TenantManagementConcurrencyWorkload.actor.cpp
fdbserver/workloads/TenantManagementWorkload.actor.cpp

This avoids problems with tenant-based tests that want to generate a lot of tenants.

Don't buggify max tenants per cluster globally; instead buggify it in specific tests

---

fdbclient/NativeAPI.actor.cpp
fdbclient/include/fdbclient/NativeAPI.actor.h

A recent change made it so that a tenantID can only be updated if it is unset. This interfered with unknown_tenant error handling, which was clearing the tenant cache entry and retrying the operation but leaving the tenant ID set on the TransactionState.
This change causes the tenant ID to be reset when an operation gets an unknown_tenant error. As a result, it will fetch an updated ID when it retries.
I also refactored the code a bit to make it easier to do the right thing.
Note: this bug is the source of (at least most of) the binding tester timeout errors. …

When a transaction operation gets an unknown tenant error, it needs to reset the tenantID

---

bindings/java/src/test/com/apple/foundationdb/test/Context.java

Convert it from a HashMap to a ConcurrentHashMap

Fix: the static tenant map in the Java tester was being accessed concurrently from multiple threads

---

flow/Net2.actor.cpp
flow/include/flow/network.h

Resurrected commented out tests for ThreadSafeQueue.
Added a test verifying FIFO guarantee of Net2::onMainThread().

Add Net2 unittests for ThreadSafeQueue and Net2::onMainThread

---

cmake/ConfigureCompiler.cmake
flow/Platform.actor.cpp

* Add SIGTERM to the list of signals upon which we flush process state.
* Add __gcov_flush to the list of things we do during flush.
* Add --coverage compile option when using GCOV (it's not enough to do it only during linking). 

Flush gcov coverage upon SIGTERM

---

fdbserver/DataDistribution.actor.cpp
tests/rare/SpecificUnitTests.toml

fix #7813 
When ASAN is enabled, decrease the max count of generated shard.
Test with ASAN build with 24000 shards.

fix ASAN OOM problem in ResumeFromShard unit test

---

fdbclient/include/fdbclient/MetaclusterManagement.actor.h
fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp
tests/slow/MetaclusterManagement.toml

Also update the metacluster management workload to decommission the metacluster at the end.

Fix: Decommissioning a metacluster could fail if some global state fields were set

---

bindings/c/CMakeLists.txt

Shim library tests are downloading old FDB binaries, which are not instrumented by a sanitizer, so it is better to disable these tests in santizer builds.

Disable shim library tests in sanitizer builds

---

fdbserver/DDTeamCollection.actor.cpp
fdbserver/DataDistributionQueue.actor.cpp
fdbserver/include/fdbserver/DataDistribution.actor.h

The default constructor of RelocateShard [here](https://sourcegraph.com/github.com/apple/foundationdb/-/blob/fdbserver/DDTeamCollection.actor.cpp?L952) set `moveReason(DataMovementReason::INVALID)`, which causes the [wantsNewServers](https://sourcegraph.com/github.com/apple/foundationdb/-/blob/fdbserver/DataDistributionQueue.actor.cpp?L158) incorrect when priority = `TEAM_REDUNDANT`.
This PR 
* removes the default constructor of `RelocateShard` because it's erroneous when separating necessary member assignment and definition;
* removes `RelocateReason::INVALID` because it's always guaranteed valid;
* add check for data movement priority uniqueness because the current team tracker relies on that.
Pass 100k test. …

Fix RelocateData initialization bug because RelocateShard.dataMovementReason is not set

---

contrib/pkg_tester/test_fdb_pkgs.py

* Avoid upgrading all centos7 packages in test_fdb_pkgs. This made the test unnecessarily slower.
* Update  test_execstack_permissions_libfdb_c after the addition of the shim library:
$ docker exec 4ddcf4bb-9e9f-4f82-ab1a-3f98de69dc18 bash -c 'execstack -q $(ldconfig -p | grep libfdb_c | awk '"'"'{print $(NF)}'"'"')'
- /lib/libfdb_c_shim.so
- /lib/libfdb_c.so

Make test_fdb_pkgs faster and fix test_execstack_permissions_libfdb_c

---

flow/actorcompiler/ActorCompiler.cs
flow/actorcompiler/ParseTree.cs
flow/actorcompiler/Program.cs

Currently, in the flow directory for the .cs file types the license year is 2013-2018. This will bump it to 2013-2022.

Update flow .cs files license year to 2022

---

tests/TestRunner/upgrade_test.py

The fdb_c_upgrade_to_future_version test was failing in address sanitizer builds, because it is producing warnings into server logs with Serverity=40. The change is fixing the filter for these warnings.

Fix filter for ASAN warnings in server logs in upgrade tests

---

fdbserver/DataDistributionQueue.actor.cpp

FIX #7841 
The old code wants to make a pair of references to the static objects, but the `make_pair` actually does a copy-by-value job. So the result the callers got is a const reference to a newly created object, which is destroyed before use. It wasn't caught by CI or normal Joshua Run, I guess because the compiler doing some optimization
The fix is to use pointers to the static objects, which is fine with copy-by-value.

fix heap-use-after-free caused by incorrect pair initialization

---

fdbcli/MetaclusterCommands.actor.cpp
fdbclient/Metacluster.cpp
fdbclient/include/fdbclient/KeyBackedTypes.h
fdbclient/include/fdbclient/Metacluster.h
fdbclient/include/fdbclient/MetaclusterManagement.actor.h
fdbclient/include/fdbclient/Tenant.h
flow/include/flow/error_definitions.h

Add some new fields to tenant:
* A tenant lock state that can be used to mark a tenant as read-only or inaccessible
* Some states and a new field to help with tenant renaming
Also convert the data cluster entry locked field to a more generic state field.

Metacluster metadata changes

---

fdbserver/storageserver.actor.cpp

Currently if encryption is enabled, when storage server pulls TLog, it needs an extra scan on the the TLog to see what are the cipher keys needed for decryption. But if the TLog cursor gets more messages at the end after fetching cipher keys, and before the decryption, the additional messages could need additional cipher keys, which causes an assert failure for missing cipher keys on decryption. This PR fixes that.
Closes #7836.

Fix storage server cipher key missing assert failure

---

fdbclient/ThreadSafeTransaction.cpp
fdbclient/include/fdbclient/ThreadSafeTransaction.h

Add an extra type parameter to the thread safe database constructor so that the connection record can be properly constructed on the network thread.
Resolves #7850 

Undo change that caused connection record reference to be created on application thread

---

fdbserver/DDTeamCollection.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/include/fdbserver/DataDistribution.actor.h
tests/rare/SpecificUnitTests.toml

This bug comes from the unit test actor state is destroyed, then the inner worker in `Debouncer` tried to access the destroyed future object. Now it's a unit test-only bug, but to avoid the same code pattern causing the same problem, and the `Debouncer` doesn't bring obvious benefit compared to periodically checking, in this PR I remove it from the storage wiggler.
pass 100k ASAN test
```
=================================================================
==24==ERROR: AddressSanitizer: heap-use-after-free on address 0x6150003be340 at pc 0x00000317d2df bp 0x7ffe3811b7d0 sp 0x7ffe3811b7c8
READ of size 8 at 0x6150003be340 thread T0
#0 0x317d2de in Promise<Void>::getFuture() const /mnt/ephemeral/xwang/readawareFdb/flow/include/flow/flow.h:909:3
#1 0x317d2de in AsyncVar<Void>::onChange() const …
```

Fix heap-use-after-free in storage wiggler unit test

---

fdbclient/include/fdbclient/BlobWorkerInterface.h

Adds tenant-based authorization to blob granule file request.
Passes 1k BlobGranule* correctness.

Authorization for blob granule file request

---

fdbclient/include/fdbclient/BlobWorkerCommon.h
fdbserver/BlobManager.actor.cpp
fdbserver/BlobWorker.actor.cpp
fdbserver/ClusterController.actor.cpp

3 bug fixes for blob granules
- don't pop change feed after a failed initial snapshot attempt
- check speed up simulation in isFull
- initialize memory stats #7865 

assorted bug fixes for blob granules

---

fdbclient/Metacluster.cpp
fdbclient/Tenant.cpp
fdbclient/include/fdbclient/Metacluster.h
fdbclient/include/fdbclient/MetaclusterManagement.actor.h
fdbclient/include/fdbclient/Tenant.h
fdbclient/include/fdbclient/TenantManagement.actor.h
fdbserver/include/fdbserver/workloads/MetaclusterConsistency.actor.h
fdbserver/include/fdbserver/workloads/TenantConsistency.actor.h

This adds some extra metadata for tenants and the metacluster in anticipation of supporting restoring clusters in a metacluster from backup. It includes:
1. A new data cluster state `RESTORING`.
2. An ID -> tenant name index that can be used to determine if there are ID collisions or to identify whether a tenant had been renamed.
This also makes a couple minor fixes to tenants to add the unused `RENAMING_FROM` and `RENAMING_TO` states to the conversion functions and to check for encrypted equality in `matchesConfiguration`. …

Metacluster restore preparation

---

bindings/c/CMakeLists.txt
bindings/c/test/apitester/TesterBlobGranuleCorrectnessWorkload.cpp
bindings/c/test/apitester/tests/upgrade/ApiBlobGranulesCorrectness.toml
bindings/c/test/apitester/tests/upgrade/MixedApiWorkloadMultiThr.toml
bindings/c/test/apitester/tests/upgrade/MixedApiWorkloadSingleThr.toml
tests/TestRunner/upgrade_test.py

Adding more API workloads to be tested in the upgrade scenarios. Adding support for blob granules in upgrade tests and adding an upgrade test for blob granule workload.

Test more C API in upgrade tests

---

fdbclient/BlobGranuleFiles.cpp
fdbserver/GetEncryptCipherKeys.actor.cpp
fdbserver/SimKmsConnector.actor.cpp
fdbserver/workloads/EncryptionOps.actor.cpp
flow/BlobCipher.cpp
flow/Knobs.cpp
flow/include/flow/BlobCipher.h
tests/fast/EncryptionOps.toml

Description
FDB native encryption data at-rest supports two type of cipher-keys
in-memory caching:
1. Revocable keys - with a definite expiry (future timestamp)
2. Non-revocable keys - with or without expiry timestamp and/or
refreshAt timestamp.
Patch update BlobCipherKey in-memory cache to respect EKP/KMS
supplied 'refreshAt' and 'expireAt' timestamp. GetLatestCipher
validates `cipher key freshness' as well as GetCipherKey checks
for 'cipher key liveness' before replying details to the caller.
Patch also optimizes the BlobCipher module logging by taking
following measures:
1. BLOB_CIPHER_DEBUG macro to guard spammy log messages needed
mostly for debugging failures.
2. Minimize log volume by logging cipherKey details for any new
key added to the cache, key-refreshes are not logged.
3. …

Update BlobCipher cache to respect EKP/KMS cipherKey TTL

---

fdbclient/ClientKnobs.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/include/fdbclient/ClientKnobs.h
fdbserver/BackupWorker.actor.cpp
fdbserver/GrvProxyServer.actor.cpp
fdbserver/include/fdbserver/workloads/BulkSetup.actor.h
fdbserver/workloads/FuzzApiCorrectness.actor.cpp
fdbserver/workloads/LocalRatekeeper.actor.cpp
fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp
fdbserver/workloads/TenantManagementWorkload.actor.cpp

GRV proxy may return `proxy_memory_limit_exceeded` and `batch_transaction_throttled` errors, which are not properly handled at many places.
100k 20220811-220634-jzhou-2e8c8744412b8112 passed.

Buggify GRV proxy to return errors and fix bugs found

---

contrib/TestHarness/Program.cs
fdbserver/workloads/UnitTests.actor.cpp

- Sort test files before picking one based on JOSHUA_SEED
- Track resident memory usage in test harness
- Sort unit tests before selecting random unit test
Previously there were some cases where rebuilding the correctness package and running with the same JOSHUA_SEED would not yield the same result. There might still be, but this addresses the ones I found.

Improve determinism (based on JOSHUA_SEED)

---

documentation/sphinx/source/special-keys.rst
fdbcli/ExpensiveDataCheckCommand.actor.cpp
fdbcli/KillCommand.actor.cpp
fdbcli/SuspendCommand.actor.cpp
fdbcli/Util.actor.cpp
fdbcli/fdbcli.actor.cpp
fdbcli/include/fdbcli/fdbcli.actor.h
fdbclient/NativeAPI.actor.cpp
fdbclient/SpecialKeySpace.actor.cpp
fdbclient/include/fdbclient/SpecialKeySpace.actor.h

Cherry-pick #7873 
In short, this removes the RPC calls in `kill`, `suspend`, and `expensive_data_check` to talk to the returned list of workers when you populate the worker list at the beginning.
These RPC calls block using multi-version fdbcli to run these commands.
This moves the behavior into special keys and does not have any behavior change, it's transparent to users.
I need to cherry-pick it to unblock multi-version fdbcli to run these commands.

Add an verify option for \xff\xff/worker_interfaces special keys (cherry-pick #7873)

---

fdbclient/ClientKnobs.cpp
fdbclient/ClientKnobs.h
fdbclient/NativeAPI.actor.cpp
fdbserver/BackupWorker.actor.cpp
fdbserver/GrvProxyServer.actor.cpp
fdbserver/workloads/BulkSetup.actor.h
fdbserver/workloads/FuzzApiCorrectness.actor.cpp
fdbserver/workloads/LocalRatekeeper.actor.cpp
fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp

Cherrypick #7844 
Note this will not change to use the new error code `grv_proxy_memory_limit_exceeded`.
100k 20220811-235034-jzhou-19c1f48e9fc7bb5c passed.
100k 20220815-213725-jzhou-11174bc685813ca0 passed.

Buggify GRV proxy to return errors and fix bugs found [release 7.1]

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/DDRelocationQueue.actor.cpp
fdbserver/DDShardTracker.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/include/fdbserver/DataDistribution.actor.h
tests/fast/PhysicalShardMove.toml

**This PR introduces PhysicalShard concept to Data Distribution**
The feature is protected by `ENABLE_DD_PHYSICAL_SHARD`.
`ENABLE_DD_PHYSICAL_SHARD` replies on `SHARD_ENCODE_LOCATION_METADATA`.
Please make sure `SHARD_ENCODE_LOCATION_METADATA` is set when setting `ENABLE_DD_PHYSICAL_SHARD`.
The core data structure is **PhysicalShardCollection**, which is responsible for the creation and maintenance of physical shards in data distribution (A physical shard contains multiple key ranges, aka shards).
PhysicalShardCollection has two jobs:
1. Create physical shards. Once a physical shard is created, it does not change, except for its metrics.
2. Update physical shard metrics. A physical shard metric is updated by shard trackers.
3. Transition. If a system with no PhysicalShard concept …

Add physical shard dd core

---

fdbserver/DDTxnProcessor.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/include/fdbserver/DDTxnProcessor.h

Mostly just convert the call directly from `Database cx` to use `txnProcessor` to do that.
Another change is to use the `ddEnabledState` in `DDSharedContext`.

[DD Testability] use txnProcessor to call removeKeysFromFailedServer and removeStorageServer

---

fdbserver/BlobManager.actor.cpp
fdbserver/workloads/BlobGranuleVerifier.actor.cpp

Added tests for purging at latest version, and ensuring non-force purges actually complete at the end of the test.
Also fixed a bug that this found racing with granule merges.
Passed 100k BlobGranuleVerify* tests with enablePurging=true and purgeAtLatest=true (equivalent to 900k BlobGranuleVerify* tests with current randomness)
- 1 unrelated redwood failure
I also tacked on a final data check into the blob granule verifier, it's a test-only change that found no new bugs, passing 100k BlobGranuleVerify* correctness …

More improved purge tests

---

fdbserver/masterserver.actor.cpp

The intent of this test is to show that figureVersion does something
reasonable if undefined behavior is invoked, but just invoking it is
already problematic so it's not an interesting test.

Remove a unit test which invokes undefined behavior

---

contrib/observability_splunk_dashboard/details.xml
contrib/observability_splunk_dashboard/performance_overview.xml
contrib/observability_splunk_dashboard/ratekeeper.xml
contrib/observability_splunk_dashboard/recovery.xml
contrib/observability_splunk_dashboard/transaction_latency.xml

This PR added a couple of Splunk dashboards for FDB trace events:
1. `Transaction Dashboard` When the cluster transaction appears long latency, this dashboard will tell you which particular step of the transaction is long.
2. `Recovery Dashboard` When the cluster becomes unavailable due to long recovery, this dashboard will show you which step in the recovery takes long time or any abnormal phenomenon in the cluster.
3. `Performance Overview` This dashboard shows the performance metrics of the cluster.
4. `RateKeeper` When the cluster gets throttled by the ratekeeper, this dashboard will show you the reason.
5. `Details` This dashboard shows the performance details on different nodes in the cluster. …

Add splunk dashboards

---

fdbclient/ServerKnobs.cpp

In some rare simulation tests, particularly with log_spill:=1 configured, the 10 second limit is exceeded, causing SevError trace events and simulation test failure. Increasing the knob value to 15.0 in simulation is a workaround to avoid these failures.

Increase `TLOG_MAX_CREATE_DURATION` to 15.0 in simulation

---

flow/Trace.cpp

This PR eliminates UnseedMismatch errors caused by allocation logging.
Fixes https://github.com/apple/foundationdb/issues/7872

Call getTraceThreadId() before we enable allocation tracing

---

contrib/TestHarness/Program.cs

This generates an `addr2line` command that can be used to get a backtrace for a valgrind error reported by TestHarness. This still requires that you run a command with the tested binary, but it's easier that re-running the test itself.
Also, this helps provide more detail for non-deterministic valgrind errors (e.g. from noSim tests) that don't readily reproduce.
Example output:
```
<ValgrindError 
Severity="40" 
What="Invalid read of size 4" 
Backtrace="addr2line -e fdbserver.debug -p -C -f -i 0x39ff57b 0x2e98341 0x2e99d31 0x2e9a1b6 0x22f4b83 0x22f4dd2 0x23091ac 0x2309cf0 0x230a728 0x230ac40 0x232146e 0x2321a67" 
WhatAux1="Address 0x84ac920 is 0 bytes inside a block of size 4 free'd" 
BacktraceAux1="addr2line -e fdbserver.debug -p -C -f -i 0x69b8897 0x39ff57a 0x2e98341 0x2e99d31 0x2e9a1b6 …
```

Include an addr2line backtrace with valgrind errors in test harness

---

flow/Knobs.cpp

As of version 7.1, knob parsing started using std::stol which will
partially consume its input and return success, even if that's not
what we want, e.g. std::stol("4GiB") returns 4.
This changes returns the behavior of 7.0, which would consider the
above example invalid.
Fixes #7619

Fix parsing of knob values to reject invalid values.

---

cmake/awssdk.cmake

This awssdk release fixes awssdk compilation bug, which specified -moutline-atomics even in cases when it was not fully supported. This was fixed in https://github.com/awslabs/aws-c-common/commit/73983d70d45d30834e5fad0a062398b057a1764d
Fixes https://github.com/apple/foundationdb/issues/7863

Upgrade awssdk to v1.9.331

---

flow/ProtocolVersion.h.cmake

While only major and minor version matters for fdb releases regarding
protocol version, this makes testing a little bit easier.

flow: allow for patch version to be set again for protocol version

---

fdbrpc/include/fdbrpc/LoadBalance.actor.h
fdbrpc/include/fdbrpc/MultiInterface.h
fdbserver/worker.actor.cpp

The localities are stored in ServerDBInfo for calculating distances to other
processes. The localities are not set when creating ServerDBInfo, thus any
distances calculated before UpdateServerDBInfoRequest will be wrong.
This PR fixes this issue, thus preventing unnecessary cross DC calls,
especially for index prefetching on the storage servers.
Also added more traces for load balancing.
100k 20220825-213352-jzhou-4fc8cbab8319a4ea passed.

Fix missing localities for fdbserver

---

fdbclient/S3BlobStore.actor.cpp
fdbrpc/HTTP.actor.cpp
fdbrpc/include/fdbrpc/HTTP.h

After this PR, FDB can backup to S3 (https) via proxy. The connection to proxy cannot be SSL though.
20220725-232951-renxuan-9f1df6cc57c9f273

Complete the proxy support for backup to S3.

---

fdbclient/BlobGranuleCommon.cpp
fdbclient/ClientKnobs.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/include/fdbclient/BlobGranuleCommon.h
fdbclient/include/fdbclient/BlobWorkerCommon.h
fdbclient/include/fdbclient/BlobWorkerInterface.h
fdbclient/include/fdbclient/NativeAPI.actor.h
fdbserver/BlobGranuleServerCommon.actor.cpp
fdbserver/BlobGranuleValidation.actor.cpp
fdbserver/BlobWorker.actor.cpp
fdbserver/include/fdbserver/BlobGranuleServerCommon.actor.h
fdbserver/include/fdbserver/BlobGranuleValidation.actor.h
fdbserver/workloads/BlobGranuleCorrectnessWorkload.actor.cpp
fdbserver/workloads/BlobGranuleVerifier.actor.cpp

This PR introduces a new BlobGranuleSummary* client function that piggybacks on readBlobGranules to generate a much more concise metadata representation, that have several uses:
- for clients to reason about blob granule state
- to improve performance of the "verifyBlobGranules" native function/"blobrange check" fdbcli command, as it would previously run slowly and/or run out of memory for large clusters, as it was loading all mutations and filenames into memory on the client before discarding them
Passes 100k BlobGranule* correctness tests.
I will create the C api bindings in a follow-up PR. …

Blob granule summary implementation (in native client)

---

fdbclient/BlobGranuleReader.actor.cpp
fdbclient/include/fdbclient/BlobGranuleReader.actor.h
fdbclient/include/fdbclient/FDBTypes.h
fdbserver/storageserver.actor.cpp

Check if a range is fully covered for StorageServer FetchKeys. If not, throw exception and log trace

check if fetchKeys is covered by blob storage

---

fdbserver/fdbserver.actor.cpp
flow/Platform.actor.cpp

Variable `environ` is defined for Linux, does not exist in Mac, is deprecated in Windows, and is breaking Mac build.
Adapt `Platform.actor.cpp:getEnvironmentKnobOptions()` accordingly.

Make envvar access in envvar-knob parsing cross-platform

---

fdbclient/NativeAPI.actor.cpp
tests/loopback_cluster/run_custom_cluster.sh

- Consider logging a trace event in "DatabaseContext::getLatestCommitVersions" only if the version vector doesn't have an entry for a tag.
- Address a bug in "run_custom_cluster.sh" (Note: code change provided by Dan).
Testing:
Simulation test run (with version vector enabled, compiler: gcc): 20220826-224300-sre-03f301f4f14fb634 (in progress)

Track only when version not found in version vector

---

documentation/sphinx/source/architecture.rst

Description
Improve FDB architecture documentation to explicitly mention that
Stateless processes may get recruited on a single cluster process
Testing

Improve FDB architecture documentation related to cluster recruitment

---

tests/fast/ChangeFeedOperations.toml
tests/fast/ChangeFeedOperationsMove.toml

Test was occasionally hitting TraceTooManyLines just due to a huge number of data moves and private mutations generated by those moves.

scaling back ChangeFeedOperationsMove to avoid TraceTooManyLines

---

fdbclient/BlobGranuleReader.actor.cpp

we assume input of isRangeFullyCovered is sorted. so the unit test should be updated accordingly

fix unit test isRangeCoveredByBlob

---

fdbserver/BlobWorker.actor.cpp

That would cause blob worker to get file not found trying to re-snapshot a granule that was already force purged.

Fix rare force purge and granule assignment race

---

fdbclient/NativeAPI.actor.cpp
flow/include/flow/error_definitions.h

Passes 10k correctness (except one unrelated issue) and 10k BlobGranule correctness

Adding new retryable error type for blob granule requests

---

fdbclient/Tuple.cpp

This happens to compile for some reason with libc++, but we don't open
the std namespace so we should fully qualify it.

Fully qualify std::nullptr_t

---

fdbserver/workloads/ConfigureDatabase.actor.cpp

By adding a delay before start checking to make sure the recovery has started already.
commit: [5685f03b5a](https://github.com/apple/foundationdb/commit/5685f03b5ae37f252831867a4cca7e7795b71c18)
Seed: `ConfigureStorageMigrationTest.toml -s 116383675 -b on`

Fix a race that check happened before last configure command

---

bindings/c/CMakeLists.txt

FDB C shim library is a small library, and it is more convenient to link it statically to a project, so that it does not need to be distributed and deployed as a separate file. 

Make FDB C shim library static

---

contrib/TestHarness2/test_harness/config.py

Previously setting the environment variable for an option with a default value
had no effect. Tested ad-hoc by submitting an ensemble with `--env
TH_INCLUDE_TEST_FILES='.*restarting.*'` and observing that only restart tests
were chosen.

Set the default testharness config from environment

---

fdbserver/GlobalTagThrottler.actor.cpp

Increase timeout for GlobalTagThrottler unit tests to 600 seconds

---

bindings/java/src/main/com/apple/foundationdb/Database.java
fdbclient/KeyRangeMap.actor.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/ReadYourWrites.actor.cpp
fdbclient/SystemData.cpp
fdbclient/include/fdbclient/KeyRangeMap.h
fdbserver/workloads/BlobGranuleRangesWorkload.actor.cpp

The current api for KeyRangeMap truncates start and end. However, for blob ranges, we'll want start and end being aligned to the known boundaries, and not start and end.
- [x ] The PR has a description, explaining both the problem and the solution.
- [ x] The description mentions which forms of testing were done and the testing seems reasonable.
- [ x] Every function/class/actor that was touched is reasonably well documented.

Blobapi: make blob api return ranges aligned to blobbified ranges or blob granules.

---

contrib/TestHarness2/test_harness/config.py
contrib/TestHarness2/test_harness/summarize.py

Also increase the threshold. 10000 seems more appropriate for asan since
it prints a symbolized stack trace to stderr.

Fix a type error when stderr is too large in test harness

---

fdbserver/ClusterRecovery.actor.cpp

This fixes #8039
The original event was deleted after a refactor. I've verified manually that the "seconds_since_last_recovered" is brought back with the change.
10k 20220831-220432-jzhou-5c38c038e31d2940 passed.

Add back RecoveryAvailable trace event for status

---

fdbserver/ClusterRecovery.actor.cpp

Cherrypick #8067 
Manually verified  "seconds_since_last_recovered" is brought back with the change.

Add back RecoveryAvailable trace event for status [release-7.1]

---

fdbclient/ClientKnobs.cpp
fdbclient/include/fdbclient/ClientKnobs.h
fdbclient/include/fdbclient/TenantEntryCache.actor.h
fdbserver/workloads/TenantEntryCacheWorkload.actor.cpp

BackupAgent will need to interact with the cache to fetch Tenant names given a tenant id for encryption, so moving this to the client . Tested correctness using existing TenantEntryCacheWorkload

Move TenantEntryCache to fdbclient

---

fdbclient/NativeAPI.actor.cpp
fdbrpc/include/fdbrpc/fdbrpc.h
fdbserver/LogSystemPeekCursor.actor.cpp
fdbserver/networktest.actor.cpp

Per discovery of this error in change feeds in real cluster tests.
I added delay injection in change feeds to confirm that it hits this problem when waiting on failure monitors to become available, and then added buggified injecting of request_maybe_delivered and properly handled that error being thrown in all uses of ReplyPromiseStream.
Passes 100k BlobGranule* correctness, and 100k normal correctness with 1 unrelated error (GetMappedRange)

Handling request_maybe_delivered in reply promise stream and injecting faults to make sure the code path is exercised

---

contrib/TestHarness/Program.cs

revert commit removing snowflake directory, and change test harness to only look in snowflake directory

[snowflake/release-71.2] Fix snowflake restart tests

---

documentation/sphinx/source/command-line-interface.rst
documentation/sphinx/source/mr-status-json-schemas.rst.inc
fdbcli/ConfigureCommand.actor.cpp
fdbcli/StatusCommand.actor.cpp
fdbclient/DatabaseConfiguration.cpp
fdbclient/ManagementAPI.actor.cpp
fdbclient/Schemas.cpp
fdbclient/SystemData.cpp
fdbclient/include/fdbclient/DatabaseConfiguration.h
fdbclient/include/fdbclient/FDBTypes.h
fdbclient/include/fdbclient/GenericManagementAPI.actor.h
fdbclient/include/fdbclient/SystemData.h
fdbserver/SimulatedCluster.actor.cpp

Description
Major changes proposed:
1. Introduce 'encryption_data_at_rest_mode" 'configure new'
option to enable Encryption data at-rest. The feature is disabled
by default. The db-config is NOT set at the moment. 
2. The configuration is meant to be set at the time of database
creation, addition checks will be done to avoid updating the config
in subsequent PR.
Testing
devCorrectness - 100K

Encryption data at-rest db-config

---

fdbclient/NativeAPI.actor.cpp
fdbclient/include/fdbclient/NativeAPI.actor.h
fdbrpc/include/fdbrpc/RangeMap.h
flow/include/flow/flow.h

This method modifies the underlying state of the notified queue, so it should be mark non-const.

Mark `PromiseStream::send` non-const

---

bindings/python/tests/fdbcli_tests.py
fdbcli/fdbcli.actor.cpp
flow/MkCertCli.cpp

Currently `fdbcli` connects to coordinator even if client is TLS-enabled while coordinator address specified in cluster file is not, and vice versa.
Instead, let `fdbcli` check the `:tls` suffix in coordinator addresses before database connection takes place, only proceeding further if there is at least one coordinator address whose TLS suffix matches client's TLS configuration.
The necessary condition for "client has configured TLS" is that the dynamically resolved TLS configuration (`LoadedTLSConfig`) of `fdbcli`'s client instance holds non-empty string for at least one of the following fields: `certificateBytes`, `keyBytes`, or `caBytes`. …

Make FDBCLI check coordinator :tls suffix

---

fdbserver/workloads/SlowTaskWorkload.actor.cpp
flow/Net2.actor.cpp
flow/Platform.actor.cpp
flow/SignalSafeUnwind.cpp
flow/include/flow/SignalSafeUnwind.h

Valgrind is complaining about use of uninitialized memory in
absl::GetStackTrace, and the cases where it complains the backtraces are
incomplete. Note: this means that jemalloc heap profiling no longer
works out of the box. Advanced users who want to enable jemalloc heap
profiling will now have to revert this change and build from source.

Rollback #7374

---

bindings/go/src/fdb/generated.go
fdbclient/vexillographer/fdb.options

Although setting it would be a no-op, make the `AUTHORIZATION_TOKEN` option a "transaction option", instead of a "network option".

Authz transaction option

---

fdbcli/BlobRangeCommand.actor.cpp
fdbclient/KeyRangeMap.actor.cpp
fdbclient/NativeAPI.actor.cpp
fdbserver/workloads/BlobGranuleRangesWorkload.actor.cpp

Passes 100k of the new unit test in BlobGranuleRangeCorrectness and 10k BlobGranuleRange with everything enabled.

Blob range idempotency test and fixes

---

fdbclient/include/fdbclient/CommitProxyInterface.h
fdbclient/include/fdbclient/EncryptKeyProxyInterface.h
fdbclient/include/fdbclient/StorageServerInterface.h
fdbserver/include/fdbserver/DataDistributorInterface.h
fdbserver/include/fdbserver/ResolverInterface.h
fdbserver/include/fdbserver/TLogInterface.h
flow/flat_buffers.cpp
flow/include/flow/Arena.h
flow/include/flow/ObjectSerializerTraits.h
flow/include/flow/serialize.h

- Assert that arena's appear last in serializer calls
- Fix all occurrences of Arena's not appearing last in serializer call

Assert that Arena's appear last in serializer calls

---

bindings/c/CMakeLists.txt
bindings/c/test/apitester/TesterApiWorkload.cpp
bindings/c/test/apitester/TesterBlobGranuleErrorsWorkload.cpp
bindings/c/test/apitester/TesterExampleWorkload.cpp
bindings/c/test/apitester/TesterTestSpec.cpp
bindings/c/test/apitester/TesterTestSpec.h
bindings/c/test/apitester/TesterTransactionExecutor.cpp
bindings/c/test/apitester/TesterTransactionExecutor.h
bindings/c/test/apitester/TesterUtil.cpp
bindings/c/test/apitester/TesterUtil.h
bindings/c/test/apitester/fdb_c_api_tester.cpp
bindings/c/test/apitester/tests/CApiTamperClusterFile.toml
bindings/c/test/fdb_api.hpp
fdbclient/MonitorLeader.actor.cpp
fdbclient/include/fdbclient/CoordinationInterface.h
tests/TestRunner/upgrade_test.py

Fixing a crash that happened when updating the connection string from the a changed cluster file, but the connection string was invalid and thus failed to load.
Extending the ApiTester framework with error injection based on using invalid cluster files. Also introducing a special testing mode that begins with an invalid cluster file and updates it to a valid one. 

Testing with invalid cluster files, fixing update from changed cluster file

---

flowbench/BenchEncrypt.cpp
flowbench/BenchHash.cpp
flowbench/BenchIterate.cpp
flowbench/BenchMem.cpp
flowbench/BenchMetadataCheck.cpp
flowbench/BenchPopulate.cpp
flowbench/BenchRandom.cpp
flowbench/BenchRef.cpp
flowbench/BenchTimer.cpp
flowbench/BenchVersionVector.cpp
flowbench/BenchVersionVectorSerialization.cpp

This is the pattern recommended by https://github.com/google/benchmark/blob/main/docs/user_guide.md#a-faster-keeprunning-loop.

Use faster `KeepRunning` loops in `flowbench`

---

fdbserver/StorageCache.actor.cpp

This feature is currently not enabled or being tested, so we do not expect the code probes in `StorageCache.actor.cpp` to be hit. This PR comments out the code probes so that we see a more accurate picture of the intended code coverage in a Joshua ensemble.

Disable CODE_PROBEs in StorageCache.actor.cpp

---

fdbserver/SimulatedCluster.actor.cpp
tests/restarting/from_7.1.0/ConfigureTestRestart-2.toml

Previously this section was being ignored because `toml::find(file, "configuration").is_table()` was false. This was causing a code probe for "Zone ID names altered in restart test" to be missed.

Fix configuration section of ConfigureTestRestart-2.toml test file

---

bindings/c/CMakeLists.txt

I encountered some linker errors due to missing symbols:
fdb_transaction_summarize_blob_granules
fdb_future_get_granule_summary_array
They go away with a clean build, but the underlying problem seems to be a missing
dependency in the makefiles that causes the fdb_cpp library to not get rebuilt when
it should.

Add missing fdb_cpp ->fdb_c dependency.

---

contrib/TestHarness/Program.cs

Add snowflake-specific directory of old binaries as candidates for old binaries in restart tests, if that directory exists.

Add restart test coverage from snowflake-specific binaries

---

fdbclient/MonitorLeader.actor.cpp

This is not intended to be hit in simulation, and we have visibility into these events with the "MonitorProxiesConnectFailed" trace event.

Remove code probe for "Coordinator hostname resolving failure"

---

tests/CMakeLists.txt

Previously, you would see the following in command_line_argument_test:
```
File "/home/jenkins/fdb/extra/long/path/to/work/around/strange/cpack/debug/rpm/behavior/tests/argument_parsing/test_argument_parsing.py", line 113, in <module>
test_fdbcli(args.build_dir)
File "/home/jenkins/fdb/extra/long/path/to/work/around/strange/cpack/debug/rpm/behavior/tests/argument_parsing/test_argument_parsing.py", line 79, in test_fdbcli
check(is_unknown_knob(run_command(command, ["--knob-fake-knob", "foo"])))
File "/home/jenkins/fdb/extra/long/path/to/work/around/strange/cpack/debug/rpm/behavior/tests/argument_parsing/test_argument_parsing.py", line 30, in check
assert condition, "Command output:\n" + last_command_output
AssertionError: Command output:
Unable to read …
```

Set FDB_CLUSTER_FILE for command_line_argument_test

---

bindings/java/src/main/com/apple/foundationdb/TenantManagement.java
bindings/python/fdb/tenant_management.py
fdbclient/MultiVersionTransaction.actor.cpp

These options were meant to aid the case where we are accessing a special key-space module in an old version that didn't have the module. We don't really need this, though, since the outcome of trying to access these keys in an unsupported version without the option is an error, and with the option it is likely a silent failure.

Remove unnecessary special key-space relaxed option in binding tenant management

---

contrib/TestHarness2/test_harness/config.py
contrib/TestHarness2/test_harness/run.py
fdbservice/FDBService.cpp
fdbservice/ServiceBase.cpp

This fixes restart tests from old binaries < 5.2.0, which previously
were immediately crashing in a TLS codepath. This behavior was not
originally ported from the old test harness to the new test harness.

Use tls plugin for old binaries < 5.2.0

---

fdbserver/workloads/BackupCorrectness.actor.cpp

This ensures that the code probes in `TaskBucket::checkActive` are hit. Previously, this code was never exercised in simulation because it was only called through the `backup.actor.cpp` driver.

Check backup agent activity in BackupAndRestoreCorrectnessWorkload

---

fdbrpc/tests/CMakeLists.txt

What seems like a TSAN-induced crash is causing the test to hang.
Set a timeout to prevent it from blocking rest of the test runs.

Set timeout on Authz TLS unit test

---

fdbserver/DDRelocationQueue.actor.cpp
fdbserver/MoveKeys.actor.cpp
fdbserver/include/fdbserver/DDTxnProcessor.h
fdbserver/include/fdbserver/MoveKeys.actor.h
fdbserver/workloads/DataLossRecovery.actor.cpp
fdbserver/workloads/PhysicalShardMove.actor.cpp
fdbserver/workloads/RandomMoveKeys.actor.cpp

This PR also refactors `moveKeys` parameter list into `MoveKeysParams` this PR. The reason is I want to avoid changing the signature of `IDDTxnProcessor::moveKeys()` whenever we need a new parameter in the future. They should be added in `MoveKeysParams`.

Implement txnProcessor->moveKeys(const MoveKeysParams& params)

---

fdbclient/Atomic.cpp
fdbclient/include/fdbclient/Atomic.h
fdbserver/workloads/UnitTests.actor.cpp

This hits the previously rarely-hit code probe for "AppendIfFits resulted in truncation". In the future, more unit tests should be added for the atomic operations.

Add `/Atomic/DoAppendIfFits` unit test

---

bindings/c/CMakeLists.txt

Beginning with clang 9, <filesystem> support is included without needing to link anything else.
https://releases.llvm.org/9.0.0/projects/libcxx/docs/UsingLibcxx.html

bindings/c: fix std++fs dependency

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/worker.actor.cpp

Introduce STORAGE_SERVER_REBOOT_ON_IO_TIMEOUT knob to control SS behavior at io_timeout errors. 
When enabled, storage server's worker will crash on io_timeout error; this allows fdbmonitor to restart the worker and recreate the same SS.
**When will this new behavior be helpful?**
SS can be temporarily throttled by infrastructure, e.g, k8s. Without this knob, the current behavior is that SS will stop running silently, which results to less SSes in a cluster. SRE will need to manually restart the worker process to restart the SS. The manual process introduces later latency in recovering the SS and the longer latency may likely cause high SS lag and cause DD to exclude the SS.  Enabling this can reduce toil of manually restarting the SS and hopefully reduce the amount of unnecessary data …

Add STORAGE_SERVER_REBOOT_ON_IO_TIMEOUT knob to reboot SS on io_timeout

---

documentation/sphinx/source/release-notes/release-notes-710.rst
fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/worker.actor.cpp

Backport of PR[#8122](https://github.com/apple/foundationdb/pull/8122)

[Release 7.1] Add STORAGE_SERVER_REBOOT_ON_IO_TIMEOUT knob to reboot SS on io_timeout

---

fdbclient/PaxosConfigTransaction.actor.cpp

fdbclient/PaxosConfigTransaction.actor.cpp:221:77: runtime error: shift exponent 32 is too large for 32-bit type 'int'
I confirmed that `1 << 30` is not UB

Fix undefined behavior when retries is too large

---

fdbclient/BuildFlags.h.in

Also fixes the Boost lib version.
Example:
```
$ ./bin/fdbserver --build_flags
{
"arch" : "Linux-5.4.117-58.216.amzn2.x86_64",
"boost_version" : "1_78",
"build_date" : "Aug 17 2022",
"build_time" : "23:34:55",
"ccache" : "OFF",
"cmake_version" : "3.19.6",
"compiler" : "Clang",
"cpp_standard" : 201703,
"fdb_version" : "7.2.0",
"git_hash" : "",
"glibc_version" : "2.17"
}
```
(the `git_hash` field is populated correctly for releases).

Add build date and time to build_flags

---

fdbclient/include/fdbclient/Tuple.h

To avoid potential problem of invalidating contents that were previously returned from `pack()` calls.
Found from #8187
20220915-201113-jzhou-b4183eebf82d2079

Make a new memory arena for Tuple::clear

---

fdbclient/Tuple.h

Cherrypick #8191
To avoid potential problem of invalidating contents of previously returned from pack() calls.

Make a new memory arena for Tuple::clear [release-7.1]

---

fdbclient/NativeAPI.actor.cpp

[snowflake/release-71.2] not counting end of stream as an error for change feeds

---

fdbserver/TLogServer.actor.cpp

Because the call to commit was not protected by the lock, partial data from updatePersistentData could be written to disk

fix: persistentData->commit() was not protected by the persistentDataCommitLock

---

fdbclient/include/fdbclient/GetEncryptCipherKeys.actor.h
fdbserver/BlobWorker.actor.cpp
fdbserver/CommitProxyServer.actor.cpp
flow/EncryptUtils.cpp
flow/include/flow/EncryptUtils.h

Previously, we had Ref types outliving the arena's that owned them,
specifically encryptDomains in the getResolution actor. Refactor to use
Standalone's, which both fixes the memory error and makes this easier to
reason about.
Also fix a potential ODR violation.

Fix heap use after free

---

fdbserver/TLogServer.actor.cpp

fix: persistentData->commit() was not protected by the persistentDataCommitLock [release-7.1]

---

contrib/TestHarness2/test_harness/config.py
contrib/TestHarness2/test_harness/run.py

I'm using this for experimenting with criu: https://criu.org/Main_Page,
which doesn't support kernel aio.

Add an option to disable kernel-aio in test harness

---

cmake/CompileBoost.cmake

After commit #24b2de8de8 Boost could not be found during configuration procedure and always building in time of FoundationDB compilation. The problem is in IF statement: it is checking not initialized variable Boost_iostreams_FOUND. To initialize it we have to ask FIND_PACKAGE statement to search iostreams component of Boost as well as others (context and filesystem).

Set Boost_iostreams_FOUND variable before check it

---

bindings/c/foundationdb/fdb_c.h

There was an [discussion](https://discourse.llvm.org/t/rfc-enabling-wstrict-prototypes-by-default-in-c/60521) in clang mailing list about -Wstrict-prototypes flag. In Clang 15 compiler flag -Wstrict-prototypes was [enable by default](https://releases.llvm.org/15.0.0/tools/clang/docs/DiagnosticsReference.html#wstrict-prototypes) so without these changes compiler will produce an error:
```
FAILED: bindings/c/CMakeFiles/fdb_c90_test.dir/test/fdb_c90_test.c.o 
/usr/local/bin/clang -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_SYSTEM_NO_DEPRECATED -DNO_INTELLISENSE -Ibindings/c -I/home/src/foundationdb/bindings/c -Ibindings/c/foundationdb -O3 -DNDEBUG -DCMAKE_BUILD -ggdb -fno-omit-frame-pointer -mavx -Wall -Wextra -Wredundant-move -Wpessimizing-move -Woverloaded-virtual -Wshift-sign-overflow …
```

ANSI C syntax mandates declare functions without parameters with void in parameters list. K&R syntax is obsolete.

---

fdbclient/NativeAPI.actor.cpp
fdbserver/workloads/BlobGranuleRangesWorkload.actor.cpp

Fixes purge calls to fail if not aligned to a blob range
Fixes getBlobGranuleRanges to not truncate granule boundaries
Passes 100k BlobGranule* and BlobGranuleRanges correctness on snowflake/release-71.2, running 10k on main

fixes for non-aligned blob range calls

---

fdbclient/SpecialKeySpace.actor.cpp
fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp

Let the special key space correctness workload to generate limit=0
and hit the code probe in simulation tests.

Change the special key space correctness workload to hit code probe

---

flow/include/flow/IRateControl.h

UBSAN found a bug where this int could overflow (which is undefined behavior).

prevent int overflow

---

fdbserver/TLogServer.actor.cpp

TLogs initially write persistent data in `initPersistentState`, called from `tLogStart`. This is important because `restorePersistentState` checks for the existence of `persistFormat.key`. If it doesn't exist, it is expected that no other persistent state exists (ie `persistFormat.key` should be the first thing written and saved). However, `updateDurableClusterID` was writing to persistent state before `initPersistentState` was called, triggering https://github.com/apple/foundationdb/blob/f471f3da04415f04fe7b89b06e0c1029f7da8316/fdbserver/TLogServer.actor.cpp#L3065 in some correctness runs.
This PR is a temporary fix for #8200 to fix failing correctness. We expect to re-enable data loss protection in the future. …

Remove durable cluster ID write

---

fdbserver/tester.actor.cpp

We need to pass dbInfo to compound workload context, so that CompoundWorkload::addFailureInjection() can initialize workload correctly

pass dbInfo to compond workload

---

cmake/ConfigureCompiler.cmake

Reducing the size of debug symbols in FDB binaries by
- Enabling compression of debug symbols
- Reducing the debug symbols level to ggdb1 by default, which is sufficient for symbolizing stack traces
If full debug symbols are necessary for debugging, they can be enabled by configuring cmake with -D FULL_DEBUG_SYMBOLS=ON

Reduce the size of debug symbols in FDB binaries

---

fdbserver/workloads/DiskFailureInjection.actor.cpp

The diagnostic is
fdbserver/workloads/DiskFailureInjection.actor.cpp:57:64: runtime error: load of value 208, which is not a valid value for type 'bool'
The fix is simply to initialize the default value of verificationMode

Fix a UBSAN diagnostic caused by use of uninitialized memory

---

cmake/awssdk.cmake

Previously binaries depended on libcurl dynamically, which broke our package
testing with a missing dependency. Arguably this would be ok if the RPMs
explicitly depended on curl, but since many folks use the binary directly
without a package manager, and since we've historically gone to great lengths
to have minimal dynamic dependencies, it's better to link statically.
Testing plan is to test aws-related functionality ad hoc in a real cluster.

Statically link libcurl for the aws sdk

---

fdbclient/BlobCipher.cpp
fdbclient/include/fdbclient/BlobCipher.h
fdbserver/SimKmsConnector.actor.cpp
fdbserver/include/fdbserver/IEncryptionKeyProvider.actor.h
fdbserver/include/fdbserver/IPageEncryptionKeyProvider.actor.h

Description
Major changes include:
1. Eliminate memcpy due to authToken
2. Update TraceEvent message format
3. Remove redundant code.
Testing
flow/BlobCipher unit test
devRunCorrectness - 100k

Encryption: Remove memcpy due to computeToken

---

fdbserver/include/fdbserver/workloads/workloads.actor.h
fdbserver/tester.actor.cpp
fdbserver/workloads/ChangeConfig.actor.cpp
fdbserver/workloads/SaveAndKill.actor.cpp

Some workloads don't work well if failure injection is enabled. This allows workload authors to disable those

All workloads to disable some failures

---

fdbserver/workloads/RandomMoveKeys.actor.cpp

Fix lock issue in MoveKeysWorkLoad. If database is locked in ConfigureLock.toml, we still want MoveKeysWorkload to continue. 
Test tests/fast/ConfigureLocked.toml passed 10K times

Fix correctness test: skip lock check in MoveKeysWorkload

---

fdbserver/tester.actor.cpp

Previously this method would always return `true`, regardless of the results of the component checks.

Fix `CompoundWorkload::check` method

---

bindings/python/fdb/impl.py

All python documentations indicate you shouldn't put prefixes like 'lib' or suffixes like '.so', '.dll', or '.dylib' in argument to ctypes.util.find_library(), unlike ctypes.CDLL() which demands an exact file name. I suppose this case hasn't been tested.

Fix Python binding's fdb_c lookup

---

fdbclient/include/fdbclient/GetEncryptCipherKeys.actor.h
fdbserver/CommitProxyServer.actor.cpp

Description
Patch update writeMutation handling of RAW_ACCESS mutations by looking up Encryption keys if not already part of 'cipherKeys' map.
Testing
FuzzApiCorrectnessClean.toml -s 3194376849 - issue was found devCorrectnesRun - 100k

Lookup encryption cipher key while writing RAW_ACCESS mutation

---

flow/StreamCipher.cpp
flow/include/flow/StreamCipher.h

Remove dead code for `applyHmacKeyDerivationFunc`

---

fdbserver/storageserver.actor.cpp

This was dead code kept around in case we wanted to optimize the change feed implementation to only fetch part of the feed and merge with the local copy.
However, reading the local copy is logically a no-op, but was causing some performance overhead by reading from the local SS before filtering down to nothing and "merging" with the remote stream.
Passes 100k *BlobGranule* + ChangeFeed* correctness on snowflake/release-71.2, running 10k correctness on main.

Removing overhead of local change feed stream copy

---

fdbserver/storageserver.actor.cpp

[snowflake/release-71.2] Removing overhead of local change feed stream copy

---

cmake/awssdk.cmake

According to
https://ftp.gnu.org/old-gnu/Manuals/ld-2.9.1/html_node/ld_3.html,
dependencies should appear after. Since curl depends on zlib, put zlib
after curl.
Fixes linker errors with ld like the following:
```
fdbclient/awssdk-build/install/external-install/curl/lib/libcurl.a(version.c.o): In function `curl_version':
version.c:(.text+0xbf): undefined reference to `zlibVersion'
```

Swap the order of curl and zlib for awssdk

---

fdbclient/ServerKnobs.cpp
fdbserver/KeyValueStoreShardedRocksDB.actor.cpp

RocksDB block cache size increase.

RocksDB block cache size increase.

---

contrib/libb64/cdecode.c
contrib/libb64/include/libb64/cdecode.h
fdbclient/Tenant.cpp

The base64 decoder we use (libb64) was assuming that the char type is signed, which is not guaranteed to be the case. When it isn't, the decoder produced incorrect results.
This changes the arithmetic being done to use int types and only converts to char when putting the result into the output string.

Fix base64 decoder bug

---

fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp

MoveKeysWorkload and SpecialKeySpaceCorrectness test have conflict. They both try to manipulate data distribution keys and cause assertions. To fix the conflicts, just disable MoveKeysWorkload

disable MoveKeysWorkload when running SpecialKeySpaceCorrectness test

---

bindings/python/tests/fdbcli_tests.py
documentation/sphinx/source/command-line-interface.rst
fdbcli/TenantCommands.actor.cpp
fdbcli/fdbcli.actor.cpp
fdbcli/include/fdbcli/fdbcli.actor.h

For example, `createtenant` becomes `tenant create`.
This also updates the tenant fdbcli tests to be split into multiple functions.

Convert fdbcli tenant commands to a single command with subcommands

---

fdbserver/workloads/ConfigureDatabase.actor.cpp
fdbserver/workloads/KillRegion.actor.cpp
fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp
fdbserver/workloads/TenantEntryCacheWorkload.actor.cpp

Disables machine attrition in a few workloads

Machine Attrition Failures

---

fdbserver/include/fdbserver/workloads/BulkSetup.actor.h

To ignore timed_out error from `getDataInFlight()` calls.
Seed: `-f rare/CheckRelocation.toml -b on -s 614932376`
Commit: [982240c1c](https://github.com/apple/foundationdb/commit/982240c1c160443c24e27f778be2d5485ebde6e5)
10k CheckRelocation.toml tests passed. 20220921-034226-jzhou-35e2e3afdf61d81a

Fix rare/CheckRelocation setup failure

---

bindings/python/tests/fdbcli_tests.py
documentation/sphinx/source/command-line-interface.rst
fdbcli/TenantCommands.actor.cpp
fdbcli/TenantGroupCommands.actor.cpp
fdbcli/fdbcli.actor.cpp
fdbcli/include/fdbcli/fdbcli.actor.h
fdbclient/Tenant.cpp
fdbclient/include/fdbclient/MetaclusterManagement.actor.h
fdbclient/include/fdbclient/Tenant.h
fdbclient/include/fdbclient/TenantManagement.actor.h
fdbserver/workloads/TenantManagementWorkload.actor.cpp

This adds two commands `tenantgroup list` and `tenantgroup get` that can be used to get the list of tenant groups in a (meta)cluster and to print the metadata for a tenant group (currently just the assigned cluster).

Fdbcli command to get tenant group metadata

---

cmake/CompileBoost.cmake
cmake/CompileZstd.cmake
cmake/user-config.jam.cmake
fdbclient/BlobGranuleFiles.cpp
fdbclient/ServerKnobs.cpp
flow/CMakeLists.txt
flow/CompressionUtils.cpp
flow/include/flow/CompressionUtils.h

Description
Patch proposes changes to enable ZSTD dirven compression/decompression
support. Major changes include:
1. Update CMake to build/install v1.5.2 (latest stable release) of ZSTD
2. Update CompressionFilter to support ZTSD compressor/decompressor
NOTE: ZSTD availability is limited to CLANG compiler for now. 
Testing

Enable ZSTD compression support

---

cmake/CompileBoost.cmake
cmake/CompileZstd.cmake
cmake/user-config.jam.cmake
fdbclient/BlobGranuleFiles.cpp
fdbclient/ServerKnobs.cpp
flow/CMakeLists.txt
flow/CompressionUtils.cpp
flow/include/flow/CompressionUtils.h

* Enable ZSTD compression filter
Description
diff-4: Randomize Knob Compression filter selection diff-3: Minor refactoring diff-2: Limit ZSTD availability to CLANG compiler diff-1: Add ZSTD compression option to BlobGranule tests
Major changes includes:
1. Update FDB CMake to download, install and build Boost with ZSTD compatibility
2. Update CompressionUtils to enable boost::iostreams::zstd compression filter
Testing
CompressionUtilsUnit.toml
BlobGranuleCorrectness/BlobGranuleCorrectnessClean devRunCorrectness - 100K (in-progress) …

[cherry-pick] Enable ZSTD compression support (#8014)

---

fdbserver/storageserver.actor.cpp

Some testing was seeing SS feed fetches get rejected under heavy load, which makes this problem worse.
Passes 10k BlobGranule correctness

Allowing ss feed fetches to go over hard limit

---

fdbclient/BlobGranuleFiles.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/ReadYourWrites.actor.cpp
fdbclient/ThreadSafeTransaction.cpp
fdbclient/include/fdbclient/BlobGranuleCommon.h
fdbclient/include/fdbclient/BlobGranuleFiles.h
fdbclient/include/fdbclient/DatabaseContext.h
fdbclient/include/fdbclient/IConfigTransaction.h
fdbclient/include/fdbclient/ISingleThreadTransaction.h
fdbclient/include/fdbclient/NativeAPI.actor.h
fdbclient/include/fdbclient/ReadYourWrites.h

Add metrics to compute blob granule read amp.
Passed 10k BlobGranule* correctness (although this barely touches that codepath).
Passed the blob granule api tester tests, and i manually validated the trace events.

Adding bg read amp metrics

---

fdbserver/BlobWorker.actor.cpp

Fixing off by one in refactor of original fix that broke original fix.
Passed 100k BlobGranule* correctness on snowflake/release-71.2, running 100k on main.

Fixing sequential write optimization for blob granules

---

fdbserver/BlobWorker.actor.cpp

Cherry-pick #8279
Passes 250k BlobGranule* correctness with 2 unrelated errors

[snowflake/release-71.2] Fixing sequential write optimization for blob granules

---

fdbserver/workloads/BlobGranuleVerifier.actor.cpp

Passes 10k BlobGranuleVerify* correctness

Fix purge at latest racing with other checking threads at the end of BlobGranuleVerify

---

cmake/FDBComponents.cmake
cmake/awssdk.cmake

Cherry pick https://github.com/apple/foundationdb/pull/8226 to snowflake/release-71.2
Previously binaries depended on libcurl dynamically, which broke our package
testing with a missing dependency. Arguably this would be ok if the RPMs
explicitly depended on curl, but since many folks use the binary directly
without a package manager, and since we've historically gone to great lengths
to have minimal dynamic dependencies, it's better to link statically.
Testing plan is to test aws-related functionality ad hoc in a real cluster. …

Statically link libcurl for the aws sdk (snowflake/release-71.2)

---

fdbserver/include/fdbserver/workloads/workloads.actor.h
fdbserver/tester.actor.cpp
fdbserver/workloads/DiskFailureInjection.actor.cpp
fdbserver/workloads/MachineAttrition.actor.cpp
fdbserver/workloads/RandomClogging.actor.cpp
fdbserver/workloads/RandomMoveKeys.actor.cpp
fdbserver/workloads/Rollback.actor.cpp

Refactor FailureInjectionWorkload so that we can disallow MoveKeysWorload running in parallel

disallow MoveKeysWorkload running in parallel

---

cmake/FDBComponents.cmake

With aarch64, in the current docker image, linking curl statically doesn't work yet.
This is the diagnostic:
```
fdbclient/awssdk-build/curl/lib/strerror.c:32:6: error: #error "strerror_r MUST be either POSIX, glibc or vxworks-style"
2022-09-22 16:05:30   #    error "strerror_r MUST be either POSIX, glibc or vxworks-style"
2022-09-22 16:05:30        ^~~~~
```
The root cause is that curl's cmake feature detection logic gets
confused since it can't build binaries that execute successfully with
the link flags it wants:
```
$ cc test.c -lssl
$ ./a.out
./a.out: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```
The general pull request guidelines can be found [here](https://github.com/apple/foundationdb/wiki/FoundationDB-Commit-Pro …

Limit BUILD_AWS_BACKUP to x86_64 for now

---

fdbserver/workloads/DataLossRecovery.actor.cpp
fdbserver/workloads/PhysicalShardMove.actor.cpp
fdbserver/workloads/StorageServerCheckpointRestoreTest.actor.cpp

A few workloads need to call setDDMode directly which may cause race condition issues with MoveKeysWorkload. So we need to disable the failure injection. 

disable MoveKeysWorkload for a few tests that need to manipulate dd

---

fdbserver/include/fdbserver/workloads/workloads.actor.h
fdbserver/tester.actor.cpp
fdbserver/workloads/DataLossRecovery.actor.cpp
fdbserver/workloads/DiskFailureInjection.actor.cpp
fdbserver/workloads/MachineAttrition.actor.cpp
fdbserver/workloads/PhysicalShardMove.actor.cpp
fdbserver/workloads/RandomClogging.actor.cpp
fdbserver/workloads/RandomMoveKeys.actor.cpp
fdbserver/workloads/Rollback.actor.cpp
fdbserver/workloads/StorageServerCheckpointRestoreTest.actor.cpp

Port fixes to split-failure-injection-workloads

---

fdbrpc/include/fdbrpc/simulator.h
fdbrpc/sim2.actor.cpp
fdbserver/SimulatedCluster.actor.cpp

killProcess_internal assumes that we've already checked and won't attempt to kill a protected process. It's up to killProcess and killInterface, which are invoked externally from simulated workloads, to enforce that constraint.

sim: don't allow calls to killProcess or killInterface to kill protected processes.

---

fdbserver/workloads/Rollback.actor.cpp

Indiscriminately killing machines can lead to unrecoverable clusters, even if we avoid killing the protected coordinators.

Downgrade kill to reboot in Rollback workload.

---

flow/Platform.actor.cpp
flow/include/flow/Platform.h

This way we still terminate early when `--crash` is set, but folks
inspecting error reports don't get mislead and confuse assertion
failures with genuine memory errors.

Change crashAndDie to abort instead of segv

---

contrib/TestHarness2/test_harness/run.py

Only run valgrind on the binary under test

Port #7123 to new test harness

---

fdbclient/Tuple.cpp
fdbclient/include/fdbclient/Tuple.h
fdbserver/BlobManager.actor.cpp
fdbserver/workloads/BlobGranuleCorrectnessWorkload.actor.cpp

While user defined codes are in the tuple documentation. Neither the c++ or the java tuple implementations allow for parsing the user defined codes.
This series makes the assumption that user defined codes are expected to be at the end of a tuple and consume the remainder. This is because no delimiter is defined for this user defined types. The area can be accessed as a string and users can use that accordingly.
Passes 100k correctness.

tuple: user defined type support

---

fdbclient/Atomic.cpp

This fixes a valgrind failure found in the nightly.

Initialize memory in new DoAppendIfFits unit test

---

fdbclient/include/fdbclient/MetaclusterManagement.actor.h
fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp

Add tenant group support to the metacluster management workload and add operations to configure and rename tenants. 
This also fixes a few error scenarios detected by these test updates where we were previously throwing the wrong error type.

Improve Metacluster Management Workload

---

fdbclient/ServerKnobs.cpp

The previous default value, `1`, is too small, and doesn't account for any retries.
20220926-221139-zhewu_knob-dc9be1b25a4be06d

Update default PEER_DEGRADATION_CONNECTION_FAILURE_COUNT value

---

fdbserver/CMakeLists.txt

I introduced a stupid compilation bug that this should fix

Only pass SSD_ROCKSDB_EXPERIMENTAL if RocksDB is actually enabled

---

documentation/sphinx/source/tls.rst
flow/TLSConfig.actor.cpp
flow/include/flow/TLSConfig.actor.h

I found it surprising that if I had a file named `fdb.pem` in my current directory that this pem file would be used by `fdbcli` rather than the default `/etc/foundationdb/fdb.pem`. This change makes it so that `/etc/foundationdb/fdb.pem` is the default unless another certificate is explicitly specified.

TLS certificate path should not be based on present working directory

---

fdbclient/ServerKnobs.cpp

[release 7.1] Cherry pick update default PEER_DEGRADATION_CONNECTION_FAILURE_COUNT value

---

fdbcli/fdbcli.actor.cpp
fdbcli/tests/fdbcli_tests.py

TLS parameters may be loaded by default system paths, which would cause a false-positive and block connection to non-TLS coordinators.

Make TLSConfig check against coordinator addresses one-way

---

fdbclient/SpecialKeySpace.actor.cpp

Tries to account for shared disks by looking at disk_id if available.
#8127 

Make exclusion less pessimistic when warning about low space usage

---

fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp

Use different variables that already store the same data as an invalidated iterator

Fix heap use after free in metacluster management workload

---

fdbserver/ClusterController.actor.cpp
fdbserver/include/fdbserver/ClusterController.actor.h
fdbserver/include/fdbserver/WorkerInterface.actor.h
fdbserver/worker.actor.cpp

We want to differentiate disconnected peers vs. degraded peers in gray failure. Currently, degraded peer has more sophisticated logic to determine whether we want to exclude it from the txn system due to accounting for hot servers, disconnected server indicates definite error.
This PR only adds a disconnectedPeer field in the worker health RPC. Cluster controller still treats disconnected peer as degraded peer. Next peer, I'll implement the logic to deal with disconnected peer in cluster controller.
20220929-171838-zhewu-gray-e95ad09e456a3f80        compressed=True data_size=37939975 duration=4088832 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=0:44:36 sanity=False started=100071 stopped=20220929-180314 submitted=20220929-171838 timeout=5400 …

Differentiate degraded peers and disconnected peers in gray failure

---

fdbclient/SpecialKeySpace.actor.cpp

Tries to account for shared disks by looking at disk_id if available.
Cherry-Picks: #8185 

Make exclusion less pessimistic when warning about low space usage (release-7.1)

---

fdbclient/ServerKnobs.cpp

Based on experience, 90th percentile gives too much noise and using median gives better stability and signal.

Update default peer latency degradation percentile to 0.5

---

fdbserver/SimulatedCluster.actor.cpp

We were seeing unit test failures in simulation where RocksDB was being set as the storage engine when it was compile time disabled. One example:
Commit: `ff6514527cdc4988f38e2da5e54755a623dfeab8`
Seed: `72117743`
Buggify: `on`
The failing unit test creates a [new test configuration](https://github.com/apple/foundationdb/blob/03f1d13be343f7adbab33e3f0337fb0d7269ffb4/fdbserver/MockGlobalState.cpp#L94) which doesn't have `storageEngineExcludeTypes` set, meaning RocksDB was a valid option even if FDB was built without it. …

Disable RocksDB storage engine in unit test TestConfig

---

fdbserver/BlobWorker.actor.cpp

Allow blob worker to reopen change feed for injected faults. Test passed for inject faults.

injected faults should be retryable errors in blob worker

---

fdbclient/ServerKnobs.cpp

Cherry pick #8361 to release 7.1

[release 7.1] Update default peer latency degradation percentile to 0.5

---

fdbserver/include/fdbserver/QuietDatabase.h
fdbserver/tester.actor.cpp
fdbserver/workloads/SnapTest.actor.cpp

Currently certain workloads with attrition injected will fail because a repair is not performed on a dead (killed) data center until Quiet Database (end of the test) is called. This PR fixes this by repairing the dead data center after `SIM_SPEEDUP_AFTER_SECONDS`

Repair Dead Data Center Outside Quiet Database

---

fdbserver/TLogServer.actor.cpp

Description
Patch updates the code to initialize TLogPersistent storage for a shared TLog independent of initializing persistentState for a versioned Tlog data. Approach allows initializing Tlog persistent storage as well as writing 'persistFormat' key for a shared TLog earlier in the TLog creation lifecycle.
Testing

Init TLogPersistent storage for a sharedTLog

---

fdbserver/workloads/TenantEntryCacheWorkload.actor.cpp

Description
Patch update TenantEntryCache::testCacheRefresh to better handle fault injection causing longer cluster recovery/availability delays. The test is modified to loop for a threshold time waiting for next round of tenantCache refresh cycle to happen. Otherwise throws 'timed_out' error.
Testing
devRunCorrectness - 100K (inprogress)

Update TenantEntryCache workload refresh to handle fault injection

---

fdbrpc/sim2.actor.cpp

Trace event name must be capitalized. This PR is to fix this error:
Trace event detail Type `canKillMachineWithBlobWorkers' is invalid 

Fix trace event error

---

fdbclient/FileBackupAgent.actor.cpp

Ensure nullptr is not passed to memcpy

---

flow/CMakeLists.txt

Apparently it wasn't guaranteed before. Not sure how it fixed my local
build in the previous PR (#8338).

Guarantee that IS_ARM_MAC is set in flow/CMakeLists.txt

---

bindings/java/src/test/com/apple/foundationdb/test/Context.java
contrib/Joshua/scripts/bindingTestScript.sh
contrib/Joshua/scripts/localClusterStart.sh

Fixes a few binding tester issues:
1. The Java binding tester would ignore some types of errors, allowing a test to succeed when it shouldn't have
2. The Java binding tester was incorrectly managing the transactions in a context
3. The binding tester script was attempting to stop the cluster twice, resulting in an error message the second time
4. There was an unnecessary output line being logged when the cluster is killed

Fix some binding tester issues

---

fdbserver/ClusterController.actor.cpp
fdbserver/ClusterController.actor.h
fdbserver/WorkerInterface.actor.h
fdbserver/worker.actor.cpp

Cherry-pick #8352 
20221003-170317-zhewu-pick-981b8544aac4decb        compressed=True data_size=31571291 duration=5265475 ended=100001 fail_fast=10 max_runs=100000 pass=100001 priority=100 remaining=0 runtime=1:09:26 sanity=False started=100170 stopped=20221003-181243 submitted=20221003-170317 timeout=5400 username=zhewu-pick

[Release 7.1] Differentiate degraded peers and disconnected peers in gray failure

---

fdbcli/BlobKeyCommand.actor.cpp
fdbclient/BlobGranuleFiles.cpp
fdbclient/DatabaseBackupAgent.actor.cpp
fdbclient/FileBackupAgent.actor.cpp
fdbclient/MonitorLeader.actor.cpp
fdbclient/ReadYourWrites.actor.cpp
fdbclient/S3BlobStore.actor.cpp
fdbclient/Schemas.cpp
fdbclient/include/fdbclient/BackupAgent.actor.h
fdbclient/include/fdbclient/TagThrottle.actor.h
fdbclient/include/fdbclient/TaskBucket.h
fdbrpc/FlowTests.actor.cpp
fdbserver/Coordination.actor.cpp
fdbserver/KeyValueStoreRocksDB.actor.cpp
fdbserver/RestoreCommon.actor.cpp
fdbserver/TagThrottler.actor.cpp
fdbserver/VersionedBTree.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/workloads/ApiCorrectness.actor.cpp
fdbserver/workloads/BulkSetup.actor.cpp
fdbserver/workloads/IDDTxnProcessorApiCorrectness.actor.cpp
fdbserver/workloads/TaskBucketCorrectness.actor.cpp
flow/Platform.actor.cpp
flow/README.md
flow/actorcompiler/ActorCompiler.cs
flow/include/flow/Arena.h
flow/include/flow/TDMetric.actor.h

This makes a variety of changes to usages of `LiteralStringRef`, culminating in the removal of `LiteralStringRef` altogether. Each commit handles a different class of usages that involve different solutions.

LiteralStringRef removal

---

fdbserver/VersionedBTree.actor.cpp
fdbserver/include/fdbserver/IPageEncryptionKeyProvider.actor.h
fdbserver/include/fdbserver/IPager.h

Redwood encrypt with page granularity. To do per-tenant encryption (i.e. each tenant are encrypted with different set of cipher keys), we need to split Redwood pages by tenant boundary. Moreover, it also needs to handle different tenant modes:
* tenantMode = disabled: do not split page by tenant, all data encrypt using default encryption domain.
* tenantMode = required: look at the prefix of the keys and split by tenant accordingly, and encrypt in tenant specific encryption domain accordingly.
* tenantMode = optional: some key ranges may not map to a tenant. In additional to looking at the key prefix, the key provider also query the tenant prefix index. For prefixes not found in the tenant prefix index, corresponding key should be encrypted using the default encryption domain.
The change …

Split Redwood page by tenant boundary

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/BlobManager.actor.cpp
fdbserver/BlobManifest.actor.cpp
fdbserver/include/fdbserver/BlobGranuleServerCommon.actor.h

1) move dumper to a dedicated actor
2) include blob manager epoch into the manifest name. the manifest file name is manifest/manifest.<epoch>.<seq>
3) keep multiple manifest files(up to 5)
test passed for 100K correctness. all changes are protected by knob blob_manifest_backup. it's disabled as default

Misc changes for blob manifest dumper

---

fdbclient/NativeAPI.actor.cpp
fdbrpc/include/fdbrpc/simulator.h
fdbserver/BlobManager.actor.cpp
fdbserver/BlobWorker.actor.cpp
fdbserver/SimulatedCluster.actor.cpp

Added targeted fault and chaos injection to blob granules to improve test coverage.
Passed 100k BlobGranule* correctness on main and 250k on snowflake/release-71.2, except for 1 unrelated failure.

Targeted blob granules fault injection

---

cmake/CompileZstd.cmake
contrib/boost_zstd/zstd.cpp
flow/CMakeLists.txt

With this patch, a new option, FLOW_USE_ZSTD, is introduced. If turned ON, flow will compile with zstd compression library.
This is tested in the Okteto environment using both gcc and clang compilation set.

Allow build FoundationDB with zstd compression library

---

fdbclient/NativeAPI.actor.cpp
fdbclient/include/fdbclient/DatabaseContext.h
fdbserver/ConsistencyScan.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp

- Version vector specific: Propagate the latest commit version, as part of the read request, when reading from a storage server.
Test that found this issue: Enabling version vector, with BLOCKING_PEEK_TIMEOUT set to 1.0sec, on "release-7.1" branch.
build_output/bin/fdbserver -r simulation --crash -f /root/src/foundationdb/tests/fast/MutationLogReaderCorrectness.toml -b on -s 152835360
Testing:
The above test succeeds with this change set.
Compiler: gcc.
With version vector disabled: 20221004-213254-sre-cf7f1b0aabbb1d35 (shows a failure in test "IDDTxnProcessorApiCorrectness.toml" with RocksDB, but the test succeeds for me locally).
With version vector enabled: 20221004-220550-sre-554c07c98940dd12 (reports these failures: IDDTxnProcessorApiCorrectness.toml, twice with …

Address MutationLogReaderCorrectness.toml simulation test failure

---

bindings/c/test/unit/unit_tests.cpp
bindings/flow/Tuple.h
fdbclient/Tuple.cpp
fdbclient/TupleVersionstamp.cpp
fdbclient/include/fdbclient/FDBTypes.h
fdbclient/include/fdbclient/KeyBackedTypes.h
fdbclient/include/fdbclient/Tuple.h
fdbclient/include/fdbclient/TupleVersionstamp.h

This defines a `Versionstamp` type and adds a function to set versionstamps in `KeyBackedBinaryValue` that would utilize this object.
There previously existed a `Versionstamp` class that uses the slightly different versionstamp definition as used in tuples. This class has been renamed to `TupleVersionstamp`, though the flow bindings have a `typedef` that allows them to continue using the same `Versionstamp` name without breaking existing flow code.
This has not really been tested; the plan is to leverage these changes in an upcoming PR that will test the new functionality.
If …

Support versionstamps in KeyBackedBinaryValue

---

fdbclient/NativeAPI.actor.cpp
fdbserver/workloads/DifferentClustersSameRV.actor.cpp
tests/slow/DifferentClustersSameRV.toml

When updating watches after a database switch, look up the tenant again to get the ID on the new cluster. Update the switching test to set up tenants properly.

Add tenant support for database switching

---

tests/restarting/from_7.0.0/UpgradeAndBackupRestore-1.toml
tests/restarting/from_7.0.0/UpgradeAndBackupRestore-2.toml
tests/restarting/from_7.1.0/SnapCycleRestart-1.txt
tests/restarting/from_7.1.0/SnapCycleRestart-2.txt
tests/restarting/from_7.1.0/SnapIncrementalRestore-1.txt
tests/restarting/from_7.1.0/SnapIncrementalRestore-2.txt
tests/restarting/from_7.1.0/SnapTestAttrition-1.txt
tests/restarting/from_7.1.0/SnapTestAttrition-2.txt
tests/restarting/from_7.1.0/SnapTestRestart-1.txt
tests/restarting/from_7.1.0/SnapTestRestart-2.txt
tests/restarting/from_7.1.0/SnapTestSimpleRestart-1.txt
tests/restarting/from_7.1.0/SnapTestSimpleRestart-2.txt

Old binaries don't understand the testClass field, so we can't have it
in test files old binaries might read. In the future we can have it for
7.2+

Remove testClass from restart tests

---

fdbclient/DatabaseContext.h
fdbclient/NativeAPI.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp

Version vector specific: Propagate the latest commit version, as part of the read request, when reading from a storage server.
Test that found this issue: Enabling version vector, with BLOCKING_PEEK_TIMEOUT set to 1.0sec, on "release-7.1" branch.
build_output/bin/fdbserver -r simulation --crash -f /root/src/foundationdb/tests/fast/MutationLogReaderCorrectness.toml -b on -s 152835360
Testing:
The above test succeeds with this change set.
Compiler: gcc.
With version vector disabled: 20221006-133758-sre-b80b9a256782a16e (no failures).
With version vector enabled: 20221006-134942-sre-15b91d7b6ca98d64 (shows a failure in MutationLogReaderCorrectness.toml, a crash after "TracedTooManyLines" trace event, the failure that I saw on "main" too, in the context of PR …

Cherry pick pull request #8393

---

fdbserver/include/fdbserver/IPageEncryptionKeyProvider.actor.h

`TenantMapEntry::idToPrefix` returns a `Key` which owns its own memory. Converting to `StringRef` will drop the ownership.

Fix heap-use-after-free in TenantAwareEncryptionKeyProvider

---

fdbserver/ClusterController.actor.cpp
fdbserver/include/fdbserver/ClusterController.actor.h

Different from peers with high latency (we try to ignore a common bad server with many other server complaining high latencies), when a worker is disconnected (despite how many servers are complaining about it), we should exclude it from the active transaction system.
20221004-203602-zhewu-disconnect-40f49f826673d2be

In gray failure, ignore max degradation degree for a disconnected worker.

---

fdbserver/OldTLogServer_4_6.actor.cpp
fdbserver/OldTLogServer_6_0.actor.cpp
fdbserver/OldTLogServer_6_2.actor.cpp
fdbserver/TLogServer.actor.cpp
fdbserver/VersionedBTree.actor.cpp

TLog KVS::init() and allow overlapping commits in Redwood in which the caller drops commit futures (Cherry-pick #8410 to snowflake/release-71.2)

---

tests/restarting/from_7.0.0/UpgradeAndBackupRestore-1.toml
tests/restarting/from_7.1.0/ConfigureStorageMigrationTestRestart-1.toml
tests/restarting/from_7.1.0/ConfigureTestRestart-1.toml
tests/restarting/from_7.1.0/SnapCycleRestart-1.txt
tests/restarting/from_7.1.0/SnapCycleRestart-2.txt
tests/restarting/from_7.1.0/SnapIncrementalRestore-1.txt
tests/restarting/from_7.1.0/SnapIncrementalRestore-2.txt
tests/restarting/from_7.1.0/SnapTestAttrition-1.txt
tests/restarting/from_7.1.0/SnapTestAttrition-2.txt
tests/restarting/from_7.1.0/SnapTestRestart-1.txt
tests/restarting/from_7.1.0/SnapTestRestart-2.txt
tests/restarting/from_7.1.0/SnapTestSimpleRestart-1.txt
tests/restarting/from_7.1.0/SnapTestSimpleRestart-2.txt
tests/restarting/from_7.1.0/VersionVectorDisableRestart-1.toml
tests/restarting/from_7.1.0/VersionVectorEnableRestart-1.toml
tests/restarting/to_7.1.0/ConfigureStorageMigrationTestRestart-1.toml

For .txt test specs the format for `storageEngineExcludeTypes` should be `=3,4,5` instead of `=[3, 4, 5]`
Also temporarily disable Redwood from 7.1.0 restart tests.

Fix storageEngineExcludeTypes format in test specs

---

bindings/c/test/apitester/TesterApiWorkload.cpp
bindings/c/test/fdb_api.hpp
fdbclient/ReadYourWrites.actor.cpp

Make ApiWorkload::clearData tx self-conflicting

---

fdbserver/worker.actor.cpp

Add info in HealthMonitorDetectDegradedPeer to indicate whether a peer is in satellite DC

Add info in HealthMonitorDetectDegradedPeer to indicate whether a peer is in satellite DC

---

fdbserver/OldTLogServer_4_6.actor.cpp
fdbserver/OldTLogServer_6_0.actor.cpp
fdbserver/OldTLogServer_6_2.actor.cpp
fdbserver/TLogServer.actor.cpp
fdbserver/VersionedBTree.actor.cpp

Allow overlapping commits in Redwood in which the caller drops references to commits that have not yet completed and are not the most recently issued commit.
Also added KVS init to TLogServer, which is required by the IKeyValueStore contract,  so it can use Redwood.

TLog KVS::init() and allow overlapping commits in Redwood in which the caller drops commit futures

---

fdbclient/include/fdbclient/CommitTransaction.h

This caused upgrades from 7.1 to fail

fix: spanContext was deserialized at the wrong protocol version

---

flow/Platform.actor.cpp

Otherwise SIGTERM (and rightly so) causes TSAN to lose its noodle when
fdbmonitor kills fdbserver in the normal way.

Only register SIGTERM with crashHandler for USE_GCOV

---

cmake/FDBComponents.cmake
fdbclient/CMakeLists.txt
fdbclient/FDBAWSCredentialsProvider.cpp
fdbclient/include/fdbclient/FDBAWSCredentialsProvider.h

- Use WITH_AWS_BACKUP instead of BUILD_AWS_BACKUP
- Re-enable aws sdk + arm

Clarify WITH_AWS_BACKUP vs BUILD_AWS_BACKUP and re-enable aws sdk with arm

---

fdbserver/worker.actor.cpp

[release 7.1] Add info in HealthMonitorDetectDegradedPeer to indicate whether a peer is in satellite DC

---

fdbclient/include/fdbclient/FDBTypes.h
fdbserver/include/fdbserver/DBCoreState.h

Description
Patch updates DBCoreState to include `encryptionAtRestMode` stored in co-ordinators. The change only extends DBCoreState, however, the value wouldn't get serialized as the 'CoordinateState' writer (ReusableCoordiantedState) protocol version is left at DBCoreState. Approach assists in playing nice with downgrades, the subsequent release would bump up writer protocol version to support 'EncryptionAtRest' protocol version compatibility.
Testing
devRunCorrectness - 100K (20221008-030233-ahusain-foundationdb-10d28b2123e6838b) …

[cherry-pick]: Extend DBCoreState to store EncryptionAtRest status

---

fdbclient/include/fdbclient/FDBTypes.h
fdbserver/include/fdbserver/DBCoreState.h

Description
Patch updates DBCoreState to include `encryptionAtRestMode` stored in co-ordinators. The change only extends DBCoreState, however, the value wouldn't get serialized as the 'CoordinateState' writer (ReusableCoordiantedState) protocol version is left at DBCoreState. Approach assists in playing nice with downgrades, the subsequent release would bump up writer protocol version to support 'EncryptionAtRest' protocol version compatibility.
Testing
devRunCorrectness - 100K (in-progress)

Extend DBCoreState to store EncryptionAtRest status

---

bindings/java/CMakeLists.txt

This PR effectively disables the java-workload in IDE-mode as this currently doesn't compile. We probably could fix this somehow, but this seems unimportant enough so I decided to just exclude it.

Fix IDE CI

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/include/fdbserver/IPageEncryptionKeyProvider.actor.h

Essentially disabling #7979 before correctness failures of 
```
"FailedAssertion": "btree->m_pBoundaryVerifier->verify(link.get().getChildPage().front(), pager->getVersion(), link.get().key, link.next().getOrUpperBound().key, domainId, cursor)",
```
related to inconsistent tenant map is resolved.

Add a knob to disable Redwood tenant page split

---

tests/CMakeLists.txt

Cherry pick https://github.com/apple/foundationdb/pull/8283 to snowflake/release-71.2
Language bindings do not work well with sanitizer instrumentation

Disable authz integration test for sanitizer builds (snowflake/release-71.2)

---

cmake/CompileZstd.cmake
flowbench/BenchZstd.cpp
flowbench/CMakeLists.txt

Add benchmark for zstd APIs, so that we can know how to use zstd properly for blob compression

Add benchmark for zstd

---

fdbserver/workloads/IDDTxnProcessorApiCorrectness.actor.cpp
tests/fast/IDDTxnProcessorApiCorrectness.toml

This fixes the timeout failure in `IDDTxnProcessorApiCorrectness`. 
The root cause is when `RandomMoveKeys` is injected, both workloads will change the DD mode and cause DD mode race.

disallow workload injection in IDDTxnProcessorApiCorrectness

---

fdbclient/BlobCipher.cpp
fdbclient/include/fdbclient/BlobCipher.h
fdbserver/workloads/EncryptionOps.actor.cpp
flow/EncryptUtils.cpp
flow/include/flow/EncryptUtils.h

Description
The current code supports two modes for authentication encryption:
1. Single auth-token mode
2. Multi auth-token mode
The code currently uses SingleAuthToken mode only, the multi-auth token mode was added to support large file (such as backup files) encryption assisting encryption authentication by allowing reading header independently from encrypted payload itself. However, the backup files are organized as 'chunks' and every chunk is encrypted, hence, MultiToken mode isn't used in the code.
Removing the usage saves 32 bytes per encryption header, which might translate to decent storage saving, further, allows lesser encryption header overhead when encrypting small Key-Value mutations.
Testing
BlobCipher unittests
The general pull request guidelines can be …

Remove MultiToken Encryption auth-token generation

---

fdbserver/KeyValueStoreRocksDB.actor.cpp

RocksDB commit latency sample corrections.

RocksDB commit latency sample corrections.

---

fdbserver/GrvProxyTransactionTagThrottler.actor.cpp
fdbserver/include/fdbserver/GrvProxyTransactionTagThrottler.h
tests/rare/SpecificUnitTests.toml

This PR adds a unit test to ensure that the `GrvProxyTransactionTagThrottler::releaseTransactions` function preserves FIFO ordering of transactions, even when these transactions have different tags. It also fixes two bugs uncovered by this test:
- `TagQueueHandle::operator<` was assuming `std::priority_queue` was a min heap
- `GrvProxyTransactionTagThrottler::TagQueue::TagQueue()` was always initializing a `GrvTransactionRateInfo` object, even when a tag was not meant to be throttled.

Add `/GrvProxyTransactionTagThrottler/Fifo` unit test

---

fdbserver/ClusterRecovery.actor.cpp
fdbserver/LogRouter.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp

Cherrypick #8290 
* fix: the log router could see popped() versions between recoveredAt and the recovery txn version which cause remote tlogs to be stopped at a version in this range, which causes storage servers to read at versions in this range
* fix: a spurious correctness bug resulted from the consistency check running during a recovery
20221013-203020-jzhou-5801c3ee38c66422 has an unrelated error.
```
-r simulation --crash --logsize 1024MB -f ./foundationdb/tests/fast/SidebandWithStatus.toml -s 813067620 -b on
-r simulation --crash --logsize 1024MB -f ./foundationdb/tests/fast/SidebandWithStatus.toml -s 887405094 -b on
```
Both failed in `malloc()`, and `crashHandler` of Platform.actor.cpp:3500 tried to get backtrace, which stuck at `malloc()` when acquiring locks. The test didn't …

Fixed a bug where rollbackVersion >= data->storageVersion() [release-7.1]

---

fdbserver/SimKmsConnector.actor.cpp

Fixes a valgrind failure after merging PR #8415 
This problem was reproducing in about 50% of BlobGranuleCorrectness* valgrind tests, with this fix it passes 100 with no failures.

Fixing memory ownership  in T -> TRef conversion

---

fdbclient/BlobConnectionProvider.cpp
fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/BlobConnectionProvider.h
fdbclient/include/fdbclient/BlobMetadataUtils.h
fdbserver/BlobGranuleServerCommon.actor.cpp
fdbserver/BlobManager.actor.cpp
fdbserver/BlobWorker.actor.cpp
fdbserver/EncryptKeyProxy.actor.cpp
fdbserver/SimKmsConnector.actor.cpp
fdbserver/include/fdbserver/BlobGranuleServerCommon.actor.h
fdbserver/workloads/BlobGranuleCorrectnessWorkload.actor.cpp

Added blob metadata expiration and refresh to EKP and process-local cache.
Passed 20k BlobGranuleCorrectness* with 1 unrelated failure (InvalidPeerReferences)

Blob metadata refresh

---

bindings/c/test/mako/mako.cpp

`--disable_client_bypass` did not have an entry in mako's `--help`. This adds it. 

Add help for mako's --disable_client_bypass

---

fdbserver/storageserver.actor.cpp

Cherry-pick #8331
Passes 250k BlobGranule* and ChangeFeed* correctness.
Then Failed 5 out of 1 million BlobGranule* correctness with unrelated and non-concerning failures.

[snowflake/release-71.2] Fixing race between feed cleanup and persisting memory mutations

---

cmake/CompileBoost.cmake

The location of the boost build artifact config.hpp was wrong, so since no file at that path is ever created boost is always rebuilt.  Found this from `ninja -d explain`
```
ninja explain: output boost_install/boost/config.hpp doesn't exist
```

Fix cmake config so boost does not rebuild every time

---

fdbserver/include/fdbserver/IPageEncryptionKeyProvider.actor.h
fdbserver/include/fdbserver/IPager.h
tests/restarting/from_7.1.0/ConfigureStorageMigrationTestRestart-1.toml
tests/restarting/from_7.1.0/ConfigureTestRestart-1.toml
tests/restarting/from_7.1.0/SnapCycleRestart-1.txt
tests/restarting/from_7.1.0/SnapIncrementalRestore-1.txt
tests/restarting/from_7.1.0/SnapTestAttrition-1.txt
tests/restarting/from_7.1.0/SnapTestRestart-1.txt
tests/restarting/from_7.1.0/SnapTestSimpleRestart-1.txt
tests/restarting/from_7.1.0/VersionVectorDisableRestart-1.toml
tests/restarting/from_7.1.0/VersionVectorEnableRestart-1.toml
tests/restarting/from_7.2.0/DrUpgradeRestart-1.txt
tests/restarting/to_7.1.0/ConfigureStorageMigrationTestRestart-1.toml

Fixing XOR encryption encoding format change due to #8172. The XOR encryption encoding is simulation only though.
Also enabling Redwood for all restart test to/from 7.1.
Tested with 100K normal correctness run and 100K restart test only correctness run.

Fix Redwood xor encoding incompatibility with 7.1

---

documentation/sphinx/source/mr-status-json-schemas.rst.inc
fdbclient/Schemas.cpp
fdbserver/Status.actor.cpp

Otherwise, it blocks getting status when there is no database running in the cluster.
20221017-212241-zhewu_8489_3-4835b329114a3d59      compressed=True data_size=38444136 duration=3487281 ended=100004 fail=1 fail_fast=10 max_runs=100000 pass=100003 priority=100 remaining=0 runtime=1:05:28 sanity=False started=100286 stopped=20221017-222809 submitted=20221017-212241 timeout=5400 username=zhewu_8489_3

Use consistencyScanInfoFetcher function and add a timeout

---

fdbserver/DDTxnProcessor.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/MockGlobalState.cpp
fdbserver/MoveKeys.actor.cpp
fdbserver/include/fdbserver/DDTxnProcessor.h
fdbserver/include/fdbserver/MockGlobalState.h
fdbserver/include/fdbserver/MoveKeys.actor.h
fdbserver/workloads/IDDTxnProcessorApiCorrectness.actor.cpp
flow/DeterministicRandom.cpp
tests/fast/IDDTxnProcessorApiCorrectness.toml

There are mainly 2 changes in this PR:
* `MockDDTxnProcessor` and `MockGlobalState` get the code for mock mode `moveKeys` implementation
* Add test in `IDDTxnProcessorApiWorkload` to verify the consistency of mock and real-world after moveKeys

Implement mock mode moveKeys in MockDDTxnProcessor and simulation test

---

fdbclient/BlobGranuleFiles.cpp
fdbclient/BlobGranuleReader.actor.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/include/fdbclient/BlobGranuleCommon.h
fdbclient/include/fdbclient/BlobGranuleFiles.h
fdbclient/include/fdbclient/DatabaseContext.h

So that these metrics are only logged if client is doing blob granule reads.
Passes 1000 BlobGranule* correctness tests, and verified traces manually with mako run.

adding new bg read metrics to client and refactoring them into a new trace event

---

fdbserver/EncryptKeyProxy.actor.cpp
fdbserver/RESTKmsConnector.actor.cpp
fdbserver/SimKmsConnector.actor.cpp
fdbserver/include/fdbserver/KmsConnector.h
fdbserver/include/fdbserver/RESTKmsConnector.h
fdbserver/include/fdbserver/SimKmsConnector.h
fdbserver/workloads/EncryptKeyProxyTest.actor.cpp
tests/CMakeLists.txt

Description
Major changes include:
1. Enable EncryptKeyProxyTest, the test was modified to leverage GetEncryptCipherKey actor, as existing code wouldn't work if EKP process gets restarted while test is running.
2. Add code probes to EKP
3. Minor refactoring.
Testing
EncryptKeyProxyTest - 100K

Enable EncryptKeyProxy test and add code probes

---

CMakeLists.txt
bindings/c/CMakeLists.txt
tests/TestRunner/binary_download.py

This version will be 71.2.3 which will be all fixes  after 71.2.1  including Steve's guard fix.

Version Bump from 71.2.1 to 71.2.3

---

bindings/c/CMakeLists.txt
bindings/c/test/apitester/run_c_api_tests.py

To have symbolized stack traces when xSAN error reproduces

Disable delete-native-lib-after-loading client knob for some C API tests

---

fdbclient/IdempotencyId.cpp
fdbclient/ServerKnobs.cpp
fdbserver/tester.actor.cpp

The buggified knob MAX_WRITE_TRANSACTION_LIFE_VERSIONS can be only 1M and cause test timeout.
Seed: `-f ./foundationdb/tests/fast/AutomaticIdempotency.toml -s 2280218520 -b on`
Commit: 50b425389
Compiler: Clang
20221017-223440-jzhou-4100dfead7f16827 passed.
20221018-215838-jzhou-4cb75a57999a7acb has an unrelated random unit test `/fdbclient/IdempotencyId/basic` failure.
`-r simulation --crash --logsize 1024MB -f ./foundationdb/tests/fast/RandomUnitTests.toml -s 3581842356 -b on`

Fix a test timeout

---

fdbclient/include/fdbclient/BlobMetadataUtils.h

For UBSAN failure
Passed 1000 KmsConnector unit tests under UBSAN

Fixing type in constructor

---

fdbclient/ManagementAPI.actor.cpp
fdbclient/SystemData.cpp
fdbclient/include/fdbclient/SystemData.h
fdbrpc/include/fdbrpc/simulator.h
fdbrpc/sim2.actor.cpp
fdbserver/ApplyMetadataMutation.cpp
fdbserver/ClusterController.actor.cpp
fdbserver/ClusterRecovery.actor.cpp
fdbserver/DDTeamCollection.actor.cpp
fdbserver/DDTxnProcessor.actor.cpp
fdbserver/FDBExecHelper.actor.cpp
fdbserver/SimulatedCluster.actor.cpp
fdbserver/TLogServer.actor.cpp
fdbserver/TagPartitionedLogSystem.actor.cpp
fdbserver/include/fdbserver/ClusterController.actor.h
fdbserver/include/fdbserver/DDTeamCollection.h
fdbserver/include/fdbserver/DDTxnProcessor.h
fdbserver/include/fdbserver/LogSystem.h
fdbserver/include/fdbserver/TagPartitionedLogSystem.actor.h
fdbserver/include/fdbserver/WorkerInterface.actor.h
fdbserver/storageserver.actor.cpp
fdbserver/worker.actor.cpp
fdbserver/workloads/ClientWorkload.actor.cpp
fdbserver/workloads/MachineAttrition.actor.cpp

Data loss protection is a feature to disallow processes from joining the wrong cluster and deleting their data (see #5375). The original implementation (#5637) had to be reverted due to some problems.
This PR re-enables data loss protection, but with a slightly different implementation. Each cluster generates a random cluster ID on the CC after recovery. This UID is stored in the database and sent to all processes through the `ServerDBInfo` object. Previously, stateful processes would write the cluster ID to their data files, and compare this value to that of the txnStateStore on boot. This PR modifies this approach. Now, each process will write the cluster ID to a durable file in the data directory (the file is named `clusterId`). When a process starts, it will include its cluster ID, …

Data loss protection v2

---

bindings/c/test/mako/mako.cpp
bindings/c/test/mako/mako.hpp

Support --load_factor, its default value is 1.0, it works together with --rows, the final rows inserted into database in build stage is rows * load_factor, if load_factor < 1, will pick up keys randomly in range [0, rows - 1].

support --load_factor

---

documentation/sphinx/source/backups.rst
fdbbackup/backup.actor.cpp

Currently we need a way to restore tenant metadata before restoring user data, otherwise we encounter errors in the storage server when encryption is enabled. This PR adds `--user-data` and `system-metadata` options to the `fdbrestore` CLI utility to make it easier to restore tenant (system) and user data separately.

Add Options to restore user/system keys in backup agent

---

fdbclient/include/fdbclient/FDBTypes.h
fdbserver/workloads/TenantManagementWorkload.actor.cpp

Adds testing to the `TenantMetadata::lastTenantModification` field to make sure its updated during tenant operations.
Passes 100k correctness on TenantManagement workloads.

Add Testing for LastTenantModification Field

---

fdbclient/FileBackupAgent.actor.cpp

Small code refactor.
10k 20221020-174606-jzhou-c2382e177efa6d04 passed.

Make decodeKVPairs a non-actor function

---

fdbcli/fdbcli.actor.cpp

The fdbcli command `setknob` requires a description in the transaction for the change. Currently, we prompt in the CLI for a description. However, if the prompt lasts too long the `warn` actor will trigger stating that there is a `Long delay` when in reality we're just waiting the user to enter a description.
The solution is to simply cancel the actor before prompting for a description and re-enable it before we submit the transaction. 

fdbcli: Cancel warn actor when prompting for description

---

fdbserver/DiskQueue.actor.cpp

Bug fix: If a disk queue reader drops its future memory corruption could occur (Cherry-pick #8522 to release-7.1)

---

bindings/c/test/apitester/fdb_c_api_tester.cpp
bindings/c/test/client_memory_test.cpp
bindings/c/test/shim_lib_tester.cpp
bindings/c/test/unit/disconnected_timeout_tests.cpp
bindings/c/test/unit/setup_tests.cpp
bindings/c/test/unit/trace_partial_file_suffix_test.cpp
bindings/c/test/unit/unit_tests.cpp
bindings/c/test/unit/unit_tests_version_510.cpp

Avoid FDB network thread to be silently failing on unexpected errors in C API and unit tests.

Check network thread error in API and unit tests

---

fdbserver/DDRelocationQueue.actor.cpp
fdbserver/DDShardTracker.actor.cpp
fdbserver/include/fdbserver/DataDistribution.actor.h

This is to trace how frequent we reuse existing physical shard.
20221020-051032-zhewu_8510-85b5aba5c499f12d        compressed=True data_size=39211132 duration=4618722 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=0:46:08 sanity=False started=100086 stopped=20221020-055640 submitted=20221020-051032 timeout=5400 username=zhewu_8510

Add a counter to track physical shard creation through moves

---

fdbserver/DiskQueue.actor.cpp

Bug fix: If a disk queue reader drops its future memory corruption could occur (Cherry-pick #8522 to snowflake/release-71.2)

---

fdbserver/DiskQueue.actor.cpp

If a disk queue reader drops its future the disk queue would drop reference to the output buffer for the disk read which the OS might later complete and write the result to memory in use by something else.

Bug fix: If a disk queue reader drops its future memory corruption could occur

---

fdbclient/BlobGranuleFiles.cpp

Fixes incorrect logic on when to add snapshot rows stats

fix bg stats invalid access

---

fdbclient/BlobGranuleFiles.cpp

Porting perf improvements found with benchmark #8533 to snowflake/release-71.2
Passed 100k BlobGranule* correctness and 100k /blobgranule/files* unit tests

[snowflake/release-71.2] Several Blob Granule Files Perf Improvements

---

fdbcli/QuotaCommand.actor.cpp
fdbcli/tests/fdbcli_tests.py
flow/include/flow/error_definitions.h

This PR contains three changes:
- Fail the `quota set` command if the quota is invalid (instead of waiting until the quota is used to throw an error)
- Print when a `quota set` or `quota clear` command is successful
- Make the `invalid_throttle_quota_value` error message more descriptive.

Improve error messages for `fdbcli` quota commands

---

fdbclient/ManagementAPI.actor.cpp
fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ManagementAPI.actor.h
fdbclient/include/fdbclient/ServerKnobs.h
fdbrpc/include/fdbrpc/TenantInfo.h
fdbserver/DataDistribution.actor.cpp
fdbserver/TenantCache.actor.cpp
fdbserver/include/fdbserver/DataDistribution.actor.h
fdbserver/include/fdbserver/TCInfo.h
fdbserver/include/fdbserver/TenantCache.h
fdbserver/workloads/StorageQuota.actor.cpp

Add functionality to get tenants over storage quota. Additionally, refactor the code to simplify and improve the relevant monitors and simplify the data stored in TenantCache.

Add functionality to get tenants over storage quota and improve the relevant monitors

---

fdbserver/RestoreLoader.actor.cpp

The loop is transformed by actor compiler into recursions that may cause stack overflows. Thus, I added yield() to unwind stack and refactor the parsing code so that the subsequent files are blocked until previous ones have finished.
Fixes #8553
20221024-175653-jzhou-14479ffdf1ae487c

Fix stack overflows

---

fdbserver/RestoreLoader.actor.cpp

The loop is transformed by actor compiler into recursions that may cause stack overflows. Thus, I added yield() to unwind stack and refactor the parsing code so that the subsequent files are blocked until previous ones have finished.
cherrypick #8556
20221024-173822-jzhou-6fcd4dc5ed2f7508

Fix stack overflows [release-7.2]

---

fdbclient/BlobCipher.cpp
fdbclient/TaskBucket.actor.cpp
fdbclient/include/fdbclient/BlobWorkerCommon.h
fdbrpc/Stats.actor.cpp
fdbrpc/include/fdbrpc/Stats.h
fdbserver/BackupWorker.actor.cpp
fdbserver/BlobManager.actor.cpp
fdbserver/ClusterController.actor.cpp
fdbserver/ConfigBroadcaster.actor.cpp
fdbserver/ConfigNode.actor.cpp
fdbserver/GrvProxyServer.actor.cpp
fdbserver/LocalConfiguration.actor.cpp
fdbserver/LogRouter.actor.cpp
fdbserver/OldTLogServer_4_6.actor.cpp
fdbserver/OldTLogServer_6_0.actor.cpp
fdbserver/OldTLogServer_6_2.actor.cpp
fdbserver/Resolver.actor.cpp
fdbserver/SimpleConfigConsumer.actor.cpp
fdbserver/StorageCache.actor.cpp
fdbserver/TLogServer.actor.cpp
fdbserver/include/fdbserver/ClusterRecovery.actor.h
fdbserver/include/fdbserver/ProxyCommitData.actor.h
fdbserver/include/fdbserver/RestoreApplier.actor.h
fdbserver/include/fdbserver/RestoreLoader.actor.h
fdbserver/masterserver.actor.cpp
fdbserver/storageserver.actor.cpp

This PR encapsulates the `CounterCollection` class. In particular:
- `id`, `name`, `counters`, and `countersToRemove` fields are made private
- `traceCounters` is made a method of `CounterCollection`

Encapsulate `CounterCollection`

---

contrib/TestHarness2/test_harness/summarize.py

The new test harness ignored `ErrorIsInjectedFault`. This makes some restarting tests fail since old versions of FDB (<6.0 it seems) don't lower the severity when logging injected failures.

ignore injected errors in old fdb versions

---

fdbserver/KeyValueStoreRocksDB.actor.cpp

The code throws error if we don't set the sync to false when wal is enabled.
I was in confused in my last diff and removed it..
Cherry-pick of #8443 

Setting sync to false when wal enabled.

---

fdbserver/ConsistencyScan.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp

ConsistencyCheck fails when it sees the first corrupted shard. We may want to keep it running so that we can see all the corrupted data in logs.

Don't fail ConsistencyCheck on first mismatch

---

fdbserver/workloads/ConsistencyCheck.actor.cpp

ConsistencyCheck fails when it sees the first corrupted shard. We may want to keep it running so that we can see all the corrupted data in logs.
cherrypick #8539

Don't fail ConsistencyCheck on first mismatch (release-7.1)

---

fdbclient/FDBTypes.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/include/fdbclient/FDBTypes.h
fdbclient/include/fdbclient/KeyLocationService.h
fdbclient/include/fdbclient/NativeAPI.actor.h
fdbserver/ConsistencyScan.actor.cpp
fdbserver/DDShardTracker.actor.cpp
fdbserver/DDTeamCollection.actor.cpp
fdbserver/DDTxnProcessor.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/MockGlobalState.actor.cpp
fdbserver/MockGlobalState.cpp
fdbserver/Resolver.actor.cpp
fdbserver/RestoreLoader.actor.cpp
fdbserver/ShardsAffectedByTeamFailure.cpp
fdbserver/StorageMetrics.actor.cpp
fdbserver/include/fdbserver/DDTxnProcessor.h
fdbserver/include/fdbserver/DataDistribution.actor.h
fdbserver/include/fdbserver/IKeyValueStore.h
fdbserver/include/fdbserver/MockGlobalState.h
fdbserver/include/fdbserver/ShardsAffectedByTeamFailure.h
fdbserver/include/fdbserver/StorageMetrics.actor.h
fdbserver/include/fdbserver/StorageMetrics.h
fdbserver/storageserver.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp

* Add the abstraction of `IStorageMetricsService`
* Make both of StorageServer and MockStorageServer implement the interface, so that they can share the same code serving StorageMetrics related requests
* Add unit tests that tests the correctness of MockStorageServer implementation.
100k pass and unit test pass

Make MockStorageServer serve StorageMetrics related request

---

fdbserver/ConsistencyScan.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp

ConsistencyCheck fails when it sees the first corrupted shard. We may want to keep it running so that we can see all the corrupted data in logs.
cherrypick https://github.com/apple/foundationdb/pull/8539

Don't fail ConsistencyCheck on first mismatch (release-7.2)

---

cmake/FlowCommands.cmake
cmake/awssdk.cmake
fdbmonitor/CMakeLists.txt

A rebuild with no changes took a very long time due to a cmake problem with aws sdk. In addition, checking whether the old build system was used is unnecessary now and removing that logic also speeds things up a bit.
With these changes `ninja fdbserver` completes in less than 200ms if there are no changes in the code base.

Fix AWS SDK build and removed check for old build system

---

bindings/c/CMakeLists.txt

Build fdb_c_shim to a shared library, because in Snowflake processes have problems of linking with the static library because of incompatibilities of underlying standard libraries. 

Build fdb_c_shim to a shared library

---

fdbclient/DatabaseContext.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/include/fdbclient/DatabaseContext.h
fdbserver/ClusterRecovery.actor.cpp
flow/include/flow/flow.h

Currently, there is a cyclic reference situation in
DatabaseContext -> WatchMetadata -> watchStorageServerResp ->
DatabaseContext
If there is a watch created in the DatabaseContext, even the
corresponding wait ACTOR is cancelled, the WatchMetadata will still hold
a reference to watchStorageServerResp ACTOR, which holds a reference to
DatabaseContext.
In this situation, any DatabaseContext who held a watch will not be
automatically destructed since its reference count will never reduce to
0 until the watch value is changed. Every time the cluster recoveries,
several watches are created, and when the cluster restarts, the
DatabaseContext which not being used, will not be able to destructed due
to these watches.
With this patch, each wait to the watch will be counted. Either the
watch is …

Cancel watch when the key is not being waited

---

fdbclient/FileBackupAgent.actor.cpp

Old fdbserver may not set the "enableSnapshotBackupEncryption" key, thus we should allow the key to be not present.
cherrypick #8598

Fix restarting restore test failure

---

fdbclient/ManagementAPI.actor.cpp
fdbclient/MultiVersionTransaction.actor.cpp
fdbclient/SystemData.cpp
fdbclient/include/fdbclient/MultiVersionTransaction.h
fdbclient/include/fdbclient/SystemData.h
fdbrpc/include/fdbrpc/simulator.h
fdbrpc/sim2.actor.cpp
fdbserver/ApplyMetadataMutation.cpp
fdbserver/ClusterController.actor.cpp
fdbserver/ClusterRecovery.actor.cpp
fdbserver/DDTeamCollection.actor.cpp
fdbserver/DDTxnProcessor.actor.cpp
fdbserver/FDBExecHelper.actor.cpp
fdbserver/SimulatedCluster.actor.cpp
fdbserver/TLogServer.actor.cpp
fdbserver/TagPartitionedLogSystem.actor.cpp
fdbserver/include/fdbserver/ClusterController.actor.h
fdbserver/include/fdbserver/DDTeamCollection.h
fdbserver/include/fdbserver/DDTxnProcessor.h
fdbserver/include/fdbserver/LogSystem.h
fdbserver/include/fdbserver/TagPartitionedLogSystem.actor.h
fdbserver/include/fdbserver/WorkerInterface.actor.h
fdbserver/storageserver.actor.cpp
fdbserver/worker.actor.cpp
fdbserver/workloads/ClientWorkload.actor.cpp
fdbserver/workloads/MachineAttrition.actor.cpp

Builds on #8472, but fixes an fdbcli test timeout due to the `ClientDBInfo` not being updated with the cluster ID. Also disables reading of `\xff\xff/cluster_id` from configuration databases.

Data loss protection v3

---

flow/Platform.actor.cpp

A cherry-pick of https://github.com/apple/foundationdb/pull/8428

Only register SIGTERM with crashHandler for USE_GCOV [cherry-pick to snowflake/release-71.2]

---

fdbserver/DiskQueue.actor.cpp

A simple unit test which pushes data to a disk queue 1MB at a time, occasionally popping mutations.

added a disk queue load generator

---

fdbclient/include/fdbclient/StorageCheckpoint.h
fdbserver/DDTxnProcessor.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/MoveKeys.actor.cpp
fdbserver/RocksDBCheckpointUtils.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/workloads/PhysicalShardMove.actor.cpp

Replace `KeyRange range` with `std::vector<KeyRange> ranges` in CheckpointMetaData and DataMoveMetaData, since both of them could affect multiple keyranges.

Replace KeyRange with std::vector<KeyRange> in DataMoveMetaData and

---

flow/Net2.actor.cpp

TLS verify-callback lambda holds reference to `SSLConnection`, its containing object, preventing SSLConnection memory from being freed and leaking memory up to ~124KB per connection, which includes OpenSSL data structures, asio SSL streams, etc.
Based on repeated ASAN test run outcome, normal TLS-enabled servers vs normal trusted/untrusted TLS clients don't seem to suffer from this issue. Only in the case when servers/clients are configured with bad certificates or didn't speak TLS was the memory left allocated even after network has stopped. This is likely due to the fact that `FlowTransport` closes the connection explicitly in non-adversarial cases, closing the `asio::ssl_stream` and destroying verify-callback object holding the reference, instead of simply letting connection references …

Fix circular reference in SSLConnection

---

fdbclient/BlobGranuleFiles.cpp
fdbclient/ServerKnobs.cpp
fdbserver/ApplyMetadataMutation.cpp
fdbserver/CommitProxyServer.actor.cpp
fdbserver/Resolver.actor.cpp
fdbserver/include/fdbserver/ApplyMetadataMutation.h
fdbserver/storageserver.actor.cpp
tests/fast/EncryptionOps.toml

This PR adds the following:
- Code probes for validating encryption code flow in the commit proxy
- Asserts to make sure all data written to Tlogs is encrypted
- Encrypt resolver private mutations
- Encrypt idempotency keys (as they may contain sensitive user data)

Commit Proxy Encryption Code Probes

---

fdbserver/BlobManager.actor.cpp

bin/fdbserver -r simulation -f tests/slow/BlobGranuleVerifyBalance.toml -s 68505494 -b off --crash --trace_format json

blob: fix bad continuation actor after shutdown

---

fdbserver/storageserver.actor.cpp
flow/include/flow/network.h

In sequential saturating write tests, sometimes blob worker + data movement reads could saturate a SS. When the priority of the feed reads was higher than UpdateStorage, this would starve out update storage, causing the SS to hit its ebrake, and then creating a death spiral because the memory portion of change feed reads are more expensive the larger the storage queue is.
This makes feed reads lower priority, because not-at-latest feed reads are generally only for blob worker recovery or data movement, and this doesn't change at-latest feed read behavior.
This fixed the poor behavior seen in the saturating sequential tests, and passed 1k BlobGranule* correctness (even though simulation doesn't use priorities) …

Changing priority for not-at-latest change feed reads

---

fdbserver/DiskQueue.actor.cpp

Both push() and pushAndCommit() now require reference-counted pageData and file->write() is wrapped in uncancellable(holdWhile(pageData, ..)).  To support this with no additional overhead, StringBuffer returns a Standalone reference to its contents.

File write() buffer lifetime fix in DiskQueue.

---

bindings/c/test/mako/mako.cpp

Previously, passing  `--json filename` to mako led to a segmentation fault. I fixed this by making the parsing of `--json` similar to the parsing of `--stats_export_path`.

Fix segmentation fault when parsing json path in Mako

---

fdbserver/KeyValueStoreShardedRocksDB.actor.cpp

Reduced `Read non-exist key range` severity level to SevWarn.

Reduced `Read non-exist key range` severity level to SevWarn.

---

fdbclient/include/fdbclient/Tenant.h
fdbserver/ApplyMetadataMutation.cpp
fdbserver/CommitProxyServer.actor.cpp
fdbserver/include/fdbserver/IPageEncryptionKeyProvider.actor.h
fdbserver/include/fdbserver/ProxyCommitData.actor.h
fdbserver/storageserver.actor.cpp

During a restore, the tenant map may not be self-consistent. For example, it is possible for a tenant to exist with two names if it was renamed during a backup. This updates the tenant maps in SS and CP to allow there to be multiple tenants with the same ID, but it expects there to only be one such tenant once the restore is complete and the data is accessed.

Handle out-of-order tenant map mutations during restore

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/LogRouter.actor.cpp
fdbserver/TLogServer.actor.cpp
fdbserver/TagPartitionedLogSystem.actor.cpp

As @sfc-gh-ajbeamon found out, batching empty peek may lost pop generated by storage server removal, so a removed storage server may still live after the storage server removal.
This is not an issue when `PEEK_BATCHING_EMPTY_MSG` is turned off.
Also add some assertions to catch the invariant that when replying TLogPeek, the begin version must be greater than the popped version.
500K simulation test: 20221102-060846-zhewu_7.1_fix-604d5aec66036f65     compressed=True data_size=31702403 duration=26141298 ended=500000 fail_fast=10 max_runs=500000 pass=500000 priority=100 remaining=0 runtime=2:52:57 sanity=False started=501434 stopped=20221102-090143 submitted=20221102-060846 timeout=5400 username=zhewu_7.1_fix …

Fix a race condition between batched peek and pop

---

fdbserver/DiskQueue.actor.cpp

It was assumed that the payloadSize field in the page header was 32 bits. This was checked by a static_assert on the size of the PageHeader struct.
This change makes that field size explicit, rather than assuming that sizeof(int) == sizeof(int32_t).

DiskQueue: use explicitly sized int32_t instead of int in on-disk format.

---

packaging/docker/Dockerfile
packaging/docker/Dockerfile.eks

`build_images.sh` is failing when trying to download `kubectl` from S3 through a proxy, this change bypasses the proxy for that one `curl` command. 

skip proxy when fetching kubectl

---

fdbclient/DatabaseConfiguration.cpp
fdbclient/include/fdbclient/FDBTypes.h
fdbrpc/include/fdbrpc/fdbrpc.h
fdbserver/ClusterController.actor.cpp
fdbserver/ClusterRecovery.actor.cpp
fdbserver/TLogServer.actor.cpp
fdbserver/include/fdbserver/ClusterController.actor.h
fdbserver/include/fdbserver/ClusterRecovery.actor.h
fdbserver/include/fdbserver/DBCoreState.h
fdbserver/include/fdbserver/WorkerInterface.actor.h

Description
Major changes proposed are:
1. Extend TLog persistentStorage to persist encryption state
2. Encryption state persisted is derived from corresponding
db-config and relevant SERVER_KNOBS. In near future, knobs
shall be removed.
3. On TLog startup, the persisted encryption state is compared
against cluster configuration, if mismatch, the TLog is killed
and not allowed to rejoin the cluster.
Testing

Extend Tlog persistentStorage to persist encryption state

---

fdbclient/include/fdbclient/FDBTypes.h
fdbserver/CommitProxyServer.actor.cpp

Fix a potential memory error and improve memory/arena usage

Improve keyAfter, singleKeyRange, and an arena usage

---

fdbserver/workloads/TransactionCost.actor.cpp

A value whose contents are unused was uninitialized, which made valgrind unhappy when serializing it.

Fix valgrind error in TransactionCost test

---

fdbserver/storageserver.actor.cpp
flow/include/flow/network.h

[snowflake/release-71.2] Changing priority for not-at-latest change feed reads

---

documentation/sphinx/source/release-notes/release-notes-710.rst
fdbserver/Status.actor.cpp

`incomplete_reasons` can be destroyed already.
20221103-192945-jzhou-c791074d389af86b failed with `tests/rare/ThroughputQuota.toml`, which is unrelated to this change.

Fix ASan failure heap use after free in status json generation

---

fdbserver/include/fdbserver/StorageMetrics.actor.h
fdbserver/storageserver.actor.cpp

```
trace.127.0.0.1.4602.1667517847.AFVJYO.0.1.xml:<Event Severity="10" Time="1667518747.095738" DateTime="2022-11-03T23:39:07Z" Type="Histogram" ID="0000000000000000" Group="StorageServer" Op="SSReadRangeBytesLimit" Unit="count" LessThan2355304645="2160" TotalCount="2160" ThreadID="15121063143063586446" Machine="127.0.0.1:4602" LogGroup="default" Roles="SS" />
trace.127.0.0.1.4602.1667517847.AFVJYO.0.1.xml:<Event Severity="10" Time="1667518747.095738" DateTime="2022-11-03T23:39:07Z" Type="Histogram" ID="0000000000000000" Group="StorageServer" Op="SSReadRangeBytesReturned" Unit="count" LessThan138547332="960" LessThan1385473320="600" LessThan1524020653="600" TotalCount="2160" ThreadID="15121063143063586446" Machine="127.0.0.1:4602" LogGroup="default" Roles="SS" />
```
The general pull …

Add SS read range bytes metrics.

---

fdbclient/ServerKnobs.cpp
fdbserver/fdbserver.actor.cpp

The cause of the unseed failures for BlobGranule tests with fault injection enabled was the non-determinism in Platform.actor.cpp, caused by this folder not being reset between runs.
Passes 100k BlobGranule* correctness tests with attrition and fault injection enabled with no Unseed mismatches

moving fdbblob in sim folder for simulations

---

fdbclient/include/fdbclient/FDBTypes.h

The keyAfter function has undefined behavior if copying an empty string with a null data pointer.

Fix undefined behavior in keyAfter

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/LogRouter.actor.cpp
fdbserver/TLogServer.actor.cpp
fdbserver/TagPartitionedLogSystem.actor.cpp

Port #8660 back to main branch.
As @sfc-gh-ajbeamon found out, batching empty peek may lost pop generated by storage server removal, so a removed storage server may still live after the storage server removal.
This is not an issue when PEEK_BATCHING_EMPTY_MSG is turned off.
Also add some assertions to catch the invariant that when replying TLogPeek, the begin version must be greater than the popped version.
20221104-202112-zhewu_8704-b08ca9afe5d675a6        compressed=True data_size=39694723 duration=3057331 ended=100000 fail=4 fail_fast=10 max_runs=100000 pass=99996 priority=100 remaining=0 runtime=1:28:16 sanity=False started=100073 stopped=20221104-214928 submitted=20221104-202112 timeout=5400 username=zhewu_8704
Errors are RocksDb nondeterministic related. …

[Main] Fix a race condition between batched peek and pop

---

bindings/c/test/mako/async.cpp
bindings/c/test/mako/async.hpp
bindings/c/test/mako/future.hpp
bindings/c/test/mako/mako.cpp

- The error statistics in mako has previously been updated with the error returned by the `onError` call. I fixed this such that the original error is now used for this. This is relevant for retryable errors since the `onError` call does not return an error in the retryable case. Note that for operations of the kind `StepKind::ON_ERROR`, the old behavior has been kept for now.
-  In the async run mode, an iteration has previously not been restarted in case of an abort error (because the async actor did not register a new callback in this case). The new behavior is that the transaction is reset and the iteration is restarted.
-  In the async run mode, the ending condition is now checked after every iteration. Previously this check has only been performed in …

Fix unintended behavior in Mako

---

bindings/c/test/mako/mako.cpp

In Mako, `Arguments::num_report_files` was not initialised to 0 in `Arguments::Arguments()` which led to issues in some cases in report mode. 

Mako: Initialize Arguments::num_report_files to 0

---

flow/actorcompiler/ActorParser.cs

The actor compiler does not handle this correctly, so disallow it for now. We could probably support this someday if someone is sufficiently motivated.
Previously this would miscompile and hopefully cause some kind of syntax error in the generated code. Now it issues a helpful diagnostic.
Tested by adding an actor with a state variable that tries to use uniform initialization syntax and observing the error message looks good. We don't have any infrastructure for testing that the ActorCompiler rejects something, so I'm not including a test in this change. We could probably add that relatively easily though.
Please check each of the following things and check …

Disallow uniform initialization syntax for state variables

---

cmake/FDBComponents.cmake

Before this, cmake would not find the go binary in the docker image. After this, cmake finds it.

Add a hint for the GO path

---

fdbclient/NativeAPI.actor.cpp

Previously when multiple getRange requests are from the same parent RL request, they share the same trace id from TransactionState, with this change it has better granularity and makes it easier to compare latency between getRange requests.
20221012-192221-haofu-12d3335c074a3bae

Each getRange request in a txn has a distinct trace id

---

fdbserver/DDTxnProcessor.actor.cpp

So that DD initialization won't be blocked by Ratekeeper and read-only txn won't be blocked by locked database.

Add immediate priority and read_lock options to DD transactions

---

fdbserver/BlobManager.actor.cpp
fdbserver/BlobManifest.actor.cpp
fdbserver/include/fdbserver/BlobGranuleServerCommon.actor.h

Blob Manager epoc need to be updated after blob restore.. otherwise it starts to generate blob manifest files with epoc 1, which breaks the epoc order of manifest files

Update BlobManager epoc after restore

---

fdbclient/include/fdbclient/TagThrottle.actor.h
fdbserver/GlobalTagThrottler.actor.cpp

Any transaction that does any work will have a cost of at least one page, so having a minimum average cost of only one byte led to confusing metrics.

Make `GlobalTagThrottler` minimum average transaction cost equal to one page

---

fdbserver/DDTeamCollection.actor.cpp

Otherwise, when ratekeeper throttle the cluster to 0 because a Storage server is in a bad state. The `exclude` command can't fix the problem because DD can't read that change.

make trackExcludedServers PRIORITY_SYSTEM_IMMEDIATE

---

fdbserver/storageserver.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp

Cherrypick #8745
When VV is enabled, ~~the comparison of storage server version and read version should use the original read version, otherwise, the client may get the wrong transaction_too_old error. In the failed seed, this prevents the consistency check from finishing.~~ the `waitForVersion()` may use the oldest version in the MVCC window as the actual read version, which may often result in the `transaction_too_old` if the MVCC moved, especially during a `readRange()`. The change here is to try using a higher read version that is still valid, but not likely to cause  `transaction_too_old` error.
commit: 333a8bfbe
seed:  -f ./foundationdb/tests/fast/MutationLogReaderCorrectness.toml -s 728034139 -b on
clang
500k 20221105-190436-jzhou-52ae8ebf0861e8bd passed. …

Fix transaction_too_old error when version vector is enabled

---

fdbclient/ServerKnobs.cpp
fdbserver/GlobalTagThrottler.actor.cpp

This PR makes the following changes:
- Increase default `GLOBAL_TAG_THROTTLING_FOLDING_TIME` value to 60.0, for more stable tag throttling behaviour
- Fixes a failing `/GlobalTagThrottler/IgnoreWorstZone` unit test
- Updates comments for `GlobalTagThrottler` unit tests

Increase default `GLOBAL_TAG_THROTTLING_FOLDING_TIME` value

---

bindings/go/src/fdb/generated.go

CI's go updated to 1.19 and is producing `generated.go` different from existing file generated with 1.18, which breaks `update_bindings_go_src_fdb_generated_go`.
Update the file with the one generated with 1.19.

Update go bindings option file with go 1.19

---

fdbserver/SimulatedCluster.actor.cpp
fdbserver/include/fdbserver/SimulatedCluster.h
tests/slow/LongRunning.toml

Added three parameters in tests files 
```
[configuration]
longRunningTest =
simulationNormalRunTestsTimeoutSeconds = 
simulationBuggifyRunTestsTimeoutSeconds =
```
Something like the above,
default is the same as the current hardcoded values.

Make the hardcoded runTests timeouts as parameters in test files

---

fdbclient/NativeAPI.actor.cpp
fdbserver/storageserver.actor.cpp

Handle future_version() in tenant-aware storage metrics function. This error can only be thrown in a rare edge case where the storage server has a version of `0`. With this change, the storage server returns this error to the caller, which then retries after a delay.

Handle future_version() in tenant-aware storage metrics function

---

fdbserver/KeyValueStoreRocksDB.actor.cpp
fdbserver/storageserver.actor.cpp

Adding counters for singlekey clear requests

Adding counters for singlekey clear requests

---

fdbcli/tests/fdbcli_tests.py

`quota` is somehow failing when using the external library. The database somehow becomes unavailable after running it.
`suspend` is flaky which I guess is the `kill` is not successful, disable it too for now.
Same reason as #8783

Disable the quota,suspend commands; Add timeout for fdbcli commands

---

fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp

One of the special keyspace tests reads values from `\xff\xff/worker_interfaces' in two different ways. The rollback workload can trigger a cluster recovery between the two reads. The cluster controller can update the worker interface for a machine in that time, causing the test to fail.
It's not expected that the worker_interfaces keyspace will remain unchanged through a cluster reconfiguration. The purpose of the test was to check that 'get' and 'getRange' returned consistent results for this special keyspace.
Therefore, we've disabled Rollback failures in this test.
Testing: 100,000 runs of SpecialKeyspaceCorrectness test. …

Disable Rollback fault injection workload for SpecialKeySpaceCorrectness test.

---

bindings/c/test/fdb_c_client_config_tests.py

Defining the new client configuration tests as proper python unit tests. This way we can reuse the python unit test framework for reporting failed tests and executing individual tests when necessary.

Define FDB client configuration tests as python unit tests

---

fdbcli/BlobRestoreCommand.actor.cpp
fdbcli/fdbcli.actor.cpp
fdbcli/include/fdbcli/fdbcli.actor.h
fdbclient/NativeAPI.actor.cpp
fdbclient/SystemData.cpp
fdbclient/include/fdbclient/BlobGranuleCommon.h
fdbclient/include/fdbclient/DatabaseContext.h
fdbclient/include/fdbclient/SystemData.h
fdbserver/BlobManager.actor.cpp
fdbserver/BlobManifest.actor.cpp
fdbserver/BlobMigrator.actor.cpp
fdbserver/BlobWorker.actor.cpp
fdbserver/ClusterController.actor.cpp
fdbserver/include/fdbserver/BlobGranuleServerCommon.actor.h
fdbserver/include/fdbserver/BlobMigratorInterface.h
fdbserver/include/fdbserver/ClusterController.actor.h
fdbserver/storageserver.actor.cpp
fdbserver/worker.actor.cpp

This PR includes the following changes:
1) add fdbcli blobrestore to start the restore process
2) The blobrestore command writes the request to special key \xff\x02/blobRestoreCommand. ClusterController triggers BlobManager restart and BlobMigrator
3) isFullRestoreMode() now checks the special key to know if a given key range is restoring. 
Tested ok with 100K correctness

Add fdbcli blobrestore to start the full restore

---

fdbrpc/include/fdbrpc/TimedRequest.h

There is a discrepancy between certain times in simulation.
In [GRVProxy server](https://github.com/apple/foundationdb/blob/ca1f3140c4018e147c778ce46df28fca6c7bb8f5/fdbserver/GrvProxyServer.actor.cpp#L949), we add a time entry to defaultTxnGRVTimeInQueue  LatencySample. The way it works is it takes the difference from the current time g_network->timer() vs the time of the request req.requestTime() . However, in simulation these times are way off since simulation time is set back to beginning of unix epoch. This means that a negative time is entered into the LatencySample which doesn't really make sense. …

Make the timing consistent in simulation

---

flow/Arena.cpp

It introduces a cycle in the `next` pointers in the ArenaBlockRef's, which results in infinite recursion as we follow them in `getTotalSize`.
Instead, make Arena::dependOn(Arena) a no-op in case they're referring to the same ArenaBlock.
The intent is to have one ArenaBlock live at least at long as another. If they're
the same, that's accomplished without doing any additional bookkeeping.

Assert that we don't try to have an ArenaBlock depend on itself.

---

fdbrpc/include/fdbrpc/simulator.h
fdbserver/ConsistencyScan.actor.cpp
fdbserver/QuietDatabase.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp

Cherrypick #8672
Fix the CI failure in #8782 `slow/SwizzledRollbackTimeLapse.toml -s 861978879 -b on`
20221111-040234-jzhou-706e1471a273cbe4

Avoid changing the configuration during consistency check [release-7.2]

---

fdbclient/Tracing.actor.cpp
fdbrpc/include/fdbrpc/Msgpack.h

This PR refactors the msgpack encoding logic into its own file and generalizes the serialization to work with arbitrary types (given a function to serialize such type). 
This has passed 100K Joshua tests
20221029-011545-khoxha-foundationdb-01df101581403c3c

msgpack: Refactor msgpack encoding in tracing

---

fdbclient/ManagementAPI.actor.cpp
fdbclient/SystemData.cpp
fdbclient/include/fdbclient/ManagementAPI.actor.h
fdbclient/include/fdbclient/SystemData.h
fdbserver/TenantCache.actor.cpp
fdbserver/include/fdbserver/TenantCache.h
fdbserver/workloads/CreateTenant.actor.cpp
fdbserver/workloads/StorageQuota.actor.cpp
tests/rare/StorageQuotaTest.toml

This PR changes the storage quota mechanisms to set quota on tenant groups instead of tenants.
* Set the storage quota on tenant groups instead of tenants. Update all the relevant data structures and monitors accordingly.
* Update the CreateTenant workload to allow specifying a tenant group.
* Update the simulation testing for storage quota to use tenant groups (with multiple tenants in a group).
The quota metadata that is stored in the special keyspace will be moved to be part of the tenant metadata keyspace in a separate PR. …

Update the storage quota mechanisms to set quota on tenant groups instead of tenants

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/CommitProxyServer.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/workloads/StorageQuota.actor.cpp

Add a knob to enable/disable storage quota enforcement
Add a global knob: `STORAGE_QUOTA_ENABLED` in `ServerKnobs`. This can be used to enable/disable the storage quota enforcement for all tenant groups as well as all the monitors that track the storage quota and storage usage.

Add a knob to enable/disable storage quota enforcement

---

fdbclient/ServerKnobs.cpp
fdbserver/workloads/GetMappedRange.actor.cpp

store and reset original Knob value in GetMappedRange test

---

fdbclient/BlobGranuleFiles.cpp
fdbclient/include/fdbclient/BlobGranuleFiles.h
flowbench/BenchBlobDelta.cpp

Add benchmark for delta file serialization functions  sortDeltasByKey and serializeChunkedDeltaFile

Add micro-benchmark for blob delta serialization

---

fdbrpc/include/fdbrpc/TimedRequest.h
flow/Arena.cpp

Cherrypick #8753 #8696
Fixes `slow/ParallelRestoreNewBackupWriteDuringReadAtomicRestore.toml -s 416410271 -b off` at [62970b37](https://github.com/FoundationDB/foundationdb-nightly-clang/commit/62970b374d31405fe94dfb63dd58da8186b2cbef)
20221114-202540-jzhou-defd79e723ffe943

Fix arena dependOn and timing in simulation [release-7.2]
