flow/include/flow/PriorityMultiLock.actor.h

Bug fix: Use-after-destruct in PriorityMultiLock because kill() was clearing the priorities vector which can no longer be done because release handlers can still hold a reference to the instance and point into the vector.

Bug fix: Use-after-destruct in PriorityMultiLock

---

tests/TestRunner/local_cluster.py
tests/TestRunner/upgrade_test.py

The FDB client tests based on local cluster dynamically detects free ports and uses them for the cluster processes. When multiple such tests are executed in parallel, it may happen that different tests try to use the same port which leads to one of the tests failing. 
The local cluster now reserves ports by locking corresponding files in /tmp/fdb_local_cluster_port_locks. The locks are released and files are deleted upon completion of the test. The locks are also automatically released by the operating system upon termination of the python process.  …

Avoid port collisions in ctests

---

flow/include/flow/flow.h

This method grants mutable access to the underlying `NotifiedQueue` object, so it should not be `const`.

Mark `PromiseStream::getFuture` non-const

---

fdbserver/CommitProxyServer.actor.cpp
fdbserver/include/fdbserver/RatekeeperInterface.h

Previously, there was a short gap between when commit costs were reported to ratekeeper and when these costs were cleared. During this gap, commit costs were not recorded. This PR fixes this issue, and only removes some unnecessary copies.

Track commit costs while `ReportCommitCostEstimationRequest` is in-flight

---

fdbclient/ServerKnobs.cpp
fdbserver/workloads/GetMappedRange.actor.cpp

backporting https://github.com/apple/foundationdb/pull/8800

store and reset original Knob value in GetMappedRange test(release-7.2)

---

fdbserver/DDRelocationQueue.actor.cpp
fdbserver/DDShardTracker.actor.cpp
fdbserver/include/fdbserver/DataDistribution.actor.h

The goal is to reduce new physical shard creation and reuse existing physical shards as much as possible.
Before, every time when the first attempt to find destination physical shard fails, it tries to create new physical shard. This is not ideal since there may be other physical shard candidates that we can move data to.
This PR change the behavior to retry reusing other existing physical shard, until a new shard is required to finish the move (e.g., there is no available physical shard in the selected dst team, or we have tried enough number of times).
Before this PR, in a cluster testing, there can be hundreds of physical shards in a SS. After this PR, it can be reduced to 20s.
before
after
20221116-041547-zhewu_8840-d70448ea07bcee73 …

Reusing existing physical shard for data movement as much as possible

---

fdbserver/LogRouter.actor.cpp
fdbserver/LogSystemPeekCursor.actor.cpp
fdbserver/TLogServer.actor.cpp

A remote tlog issues 32 parallel requests to a log router. The first (seq=0) response advances tlog's version. Then the tlog processes the (empty) batch and pops the log router. In the mean time, the log router sends the second (seq=1) response back, which was corrupted due to fault injection. Since tlog doesn't get the response back, it retries by sending requests again. This time, since the log router has been popped to a higher version, the log router considers the request to be stale and sends Never() back, thus blocking the tlog from making further progress.
Found via simulation -f ./foundationdb/tests/fast/LocalRatekeeper.toml -s 420961125 -b on at commit [62970b374d](https://github.com/FoundationDB/foundationdb-nightly-clang/commit/62970b374d31405fe94dfb63dd58da8186b2cbef).
The …

Fix a log router race condition that blocks remote tlogs forever

---

fdbserver/LogRouter.actor.cpp
fdbserver/LogSystemPeekCursor.actor.cpp
fdbserver/TLogServer.actor.cpp

cherrypick #8856
A remote tlog issues 32 parallel requests to a log router. The first (seq=0) response advances tlog's version. Then the tlog processes the (empty) batch and pops the log router. In the mean time, the log router sends the second (seq=1) response back, which was corrupted due to fault injection. Since tlog doesn't get the response back, it retries by sending requests again. This time, since the log router has been popped to a higher version, the log router considers the request to be stale and sends `Never()` back, thus blocking the tlog from making further progress.
Found via simulation `-f ./foundationdb/tests/fast/LocalRatekeeper.toml -s 420961125 -b on` at commit [62970b374d](https://github.com/FoundationDB/foundationdb-nightly-clang/commit/62970b374d31405fe94dfb63dd58da …

Fix a log router race condition that blocks remote tlogs forever [release-7.2]

---

fdbclient/ServerKnobs.cpp
fdbserver/KeyValueStoreRocksDB.actor.cpp

memtable and writebuffer size are too small in simualtion, which causes thousands of sst files and at least 6 levels of ssts. Both makes compaction slower in simulation and contribute to timeout errors.
After increasing the size, failure rate (timeout failures) when we only run rocksdb and sharded rocksdb engines in simulation drops from 10 out of 332339 tests to 10 out of 497532 tests.
Release-7.2 branch's PR: https://github.com/apple/foundationdb/pull/8822 

Increase memtable and writebuffer size for rocksdb simulation test 

---

fdbserver/DDRelocationQueue.actor.cpp
fdbserver/DDShardTracker.actor.cpp
fdbserver/include/fdbserver/DataDistribution.actor.h

The current logic may run into the risk where when getting the remote team for a physical shard, it is not available. And we end up selecting a new remote team but with existing physical shard ID. This may result in one physical shard existing in multiple remote teams.
20221117-190038-zhewu_8854-29325dda85196bb5

Retry dst physical shard selection when remote physical shard is not available

---

cmake/CompileRocksDB.cmake
fdbserver/KeyValueStoreRocksDB.actor.cpp
fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
fdbserver/RocksDBCheckpointUtils.actor.cpp

RocksDB 7.7.3 version upgrade
cherry-pick of #8858

RocksDB 7.7.3 version upgrade

---

fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp

As the `SpecialKeySpaceCorrectnessWorkload` is testing special keys' functions to monitor and change the cluster configurations,
we do not want to see cluster changes like recoveries not caused by the special keys' operations.
Disable all failure injection workloads for it.

Disable all failure injection workloads for special key space correctness workload

---

flow/Arena.cpp

Narrow the self-reference ASSERT in ArenaBlock::dependOn to only the cases where we're trying to make a reference from self -> other.
It's allowed for self.getPtr() to be null, in which case we create the ArenaBlock anew and there's no danger of self-reference.
Fixes Issue #8869.

Arena: avoid null-pointer reference in ASSERT

---

fdbcli/BlobRestoreCommand.actor.cpp
fdbcli/StatusCommand.actor.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/include/fdbclient/BlobGranuleCommon.h
fdbserver/BlobManager.actor.cpp
fdbserver/BlobManifest.actor.cpp
fdbserver/BlobMigrator.actor.cpp
fdbserver/ClusterController.actor.cpp
fdbserver/Status.actor.cpp
fdbserver/include/fdbserver/BlobGranuleServerCommon.actor.h

This PR shows blob restore status in fdbcli like the following
> status details
...
Blob Granules:
Number of Workers      - 2
Number of Key Ranges   - 86
Full Restore           - Copying data 40%
...
The key changes are:
1) add BlobRestorePhase to BlobRestoreStatus 
2) add api to update/get restore status
3) fdbcli changes to show status
4) a misc fix to use krmSetRangeCoalescing to replace krmSetRange in blob migrator.

Show blob restore in fdbcli status command

---

fdbrpc/sim2.actor.cpp

Set default value for ISimulator::blobGranulesEnabled

Init blobGranulesEnabled in ISimulator

---

bindings/go/src/fdb/database.go
bindings/go/src/fdb/fdb.go
bindings/go/src/fdb/fdb_test.go

Fixes: https://github.com/apple/foundationdb/issues/8388 for go bindings. This allows to close a database after using it. For testing I ran the unit tests for go and they passed locally.
We can think about back porting those changes to 7.1 if we want. I can look at the other bindings in a separate PR, the go bindings are currently the most interesting one for us.

Allow to close database in go bindings

---

bindings/c/CMakeLists.txt
contrib/lsan.suppressions
tests/CMakeLists.txt

Works around a leak reported in API tests in ConnectionReaderActorState:   https://github.com/apple/foundationdb/issues/7849

Suppress LSAN leak reports from ConnectionReaderActorState

---

fdbserver/workloads/SnapTest.actor.cpp

This PR ensures that if a `SnapTestWorkload` is meant to take a snapshot (i.e. `testID == 1`), and the snapshot fails, then the workload will fail. Without this change, the restore would attempt to run, and fail with more confusing error messages, because there's no valid snapshot to restore.
Also, some deprecated code is removed from `SnapTestWorkload`.

Fail SnapTestWorkload if taking a snapshot fails

---

fdbclient/NativeAPI.actor.cpp
fdbserver/workloads/BlobGranuleRangesWorkload.actor.cpp

There were 2 issues with the range check in purge:
1. an empty range passed to getRange() is problematic.
2. the check should be if the end range begins before the end of the purge range - an overlap.

blob: purge range fix

---

fdbserver/BackupWorker.actor.cpp

The number of released bytes exceeds the number of acquired bytes in locks. This is because the bytes counted towards release is calculated after a "wait", when more bytes could be allocated.

Fix backup worker assertion failure

---

tests/slow/DiskFailureCycle.toml

This fixes StorageServerDurabilityErrors in DiskFailureCycle (https://github.com/apple/foundationdb/issues/8847)

Avoid memory storage engines in DiskFailureCycle

---

fdbserver/BackupWorker.actor.cpp

cherrypick #8886 
The number of released bytes exceeds the number of acquired bytes in locks. This is because the bytes counted towards release is calculated after a "wait", when more bytes could be allocated.
20221119-173034-jzhou-f6b6a287506b8645

Fix backup worker assertion failure [release-7.1]

---

fdbserver/workloads/ClientTransactionProfileCorrectness.actor.cpp

When writing to the special key space, if RAW_ACCESS is not added, the default tenant for the database is used. This causes a failure in the SpecialKeySpace actor where it looks to see if accessing a key by tenant is allowed, but if it isn't and there is a tenant, we fail. The fix is RAW_ACCESS prevents propagation of the default tenant.

test: add RAW_ACCESS when touching global special key space

---

fdbserver/BackupWorker.actor.cpp

cherrypick #8886
The number of released bytes exceeds the number of acquired bytes in locks. This is because the bytes counted towards release is calculated after a "wait", when more bytes could be allocated.
100k 20221119-063713-jzhou-9a17b8579fe7e3e8 passed.

Fix backup worker assertion failure [release-7.2]

---

tests/slow/DifferentClustersSameRV.toml

Temporarily disable the default tenant in different clusters same RV until some tenant related changes are made.

Temporarily disable the default tenant in DifferentClustersSameRV

---

fdbrpc/include/fdbrpc/simulator.h
fdbserver/include/fdbserver/ClusterController.actor.h

`logWorkerUnavailable` prints a message when a worker is unable to be recruited. As part of this message it prints the attempted recruitment strategy. The two strings I changed in the `logWorkerUnavailable` calls are to match the recruitment strategy being used. For example, the first change is made inside a function `getWorkersForTlogsSimple`, so the recruitment strategy in that case is `simple`.
The other change is adding a comment to a new kill type that switches the cluster files of processes in simulation …

Fix recruitment method string in error messages

---

documentation/sphinx/source/client-testing.rst
fdbclient/ManagementAPI.actor.cpp
fdbclient/PaxosConfigTransaction.actor.cpp
fdbserver/ConfigBroadcaster.actor.cpp
fdbserver/ConfigNode.actor.cpp
fdbserver/PaxosConfigConsumer.actor.cpp
fdbserver/include/fdbserver/ConfigFollowerInterface.h

See the comment contained in the PR for a more thorough explanation.
This bug could only manifest under a specific set of circumstances:
1. A coordinator change is started
2. The coordinator change succeeds, but its action of clearing
`previousCoordinatorsKey` is delayed.
3. A minority of `ConfigNode`s have an old state of the configuration
database, compared to the majority.
4. A `ConfigNode` in the majority dies and permanently loses data.
5. A long delay occurs on the `PaxosConfigConsumer` when it tries to
read the latest changes from the `ConfigNode`s.
In the above circumstances, the `ConfigBroadcaster` could incorrectly
send a snapshot of an old state of the configuration database to a
majority of `ConfigNode`s. This would cause new, durable, and
acknowledged commit data to be …

Fix a rare configuration database data loss bug

---

fdbclient/include/fdbclient/Tenant.h
fdbserver/OldTLogServer_4_6.actor.cpp
fdbserver/OldTLogServer_6_0.actor.cpp
fdbserver/OldTLogServer_6_2.actor.cpp
fdbserver/TLogServer.actor.cpp
fdbserver/VersionedBTree.actor.cpp
fdbserver/include/fdbserver/IPageEncryptionKeyProvider.actor.h
fdbserver/include/fdbserver/WorkerInterface.actor.h
fdbserver/storageserver.actor.cpp

We have a recent redesign that no longer required to pass tenant name to get encryption key, and also not allowing optional tenant mode for tenant-aware encryption. This PR clean up Redwood code to remove tenant map usage, and update various checks accordingly.
Changes:
* Cleanup TenantPrefixIndex in TenantAwareEncryptionKeyProvider and related logic in storage server and Redwood for passing the map around.
* Cleanup and update DecodeBoundaryVerifier the reflect the new design.
* A minor fix to writePages() that avoid a page that's default domain encrypted having a lower bound key belonging to a non-default domain.
* Fix TenantAwareEncryptionKeyProvider::getEncryptionDomain() returning wrong prefix long for system domain.
* A minor change to add a context string to IoTimeoutError.
The …

EAR: Cleanup Redwood tenant map usage

---

fdbserver/workloads/SnapTest.actor.cpp
tests/restarting/from_7.1.0/SnapCycleRestart-1.txt
tests/restarting/from_7.1.0/SnapTestAttrition-1.txt
tests/restarting/from_7.1.0/SnapTestRestart-1.txt
tests/restarting/from_7.1.0/SnapTestSimpleRestart-1.txt

Snapshots are already not supported when `logAntiQuorum > 0`, so we should mandate that `logAntiQuorum = 0` when running snapshot tests, to avoid test failures.

Disable log anti quorum for snapshot tests

---

bindings/bindingtester/tests/api.py

The API tester was intended to generate operations with the _TENANT suffix, but it was not doing so.

Allow the binding tester API test to generate reads and writes on tenant objects

---

fdbclient/ServerKnobs.cpp

To fix simulation failures where the knob value is too small.
Nightly failures in release-7.1 branch at commit [ae6ae7c60042](https://github.com/FoundationDB/foundationdb-nightly-clang/commit/ae6ae7c60042c12ae8b77a0bb0d6de8b869e4e3f)
| Test File                                           |       Seed |   Buggify |
|-----------------------------------------------------|------------|-----------|
| slow/ParallelRestoreNewBackupCorrectnessMultiCycles.toml|  303849481 |         1 |
| slow/ParallelRestoreNewBackupCorrectnessMultiCycles.toml|  298083936 |         1 |
If this PR is …

Increase buggified lock bytes for backup workers

---

fdbclient/ServerKnobs.cpp

cherrypick https://github.com/apple/foundationdb/pull/8929
To fix simulation failures where the knob value is too small.

Increase buggified lock bytes for backup workers [release-7.2]

---

fdbclient/ServerKnobs.cpp

cherrypick #8929
To fix simulation failures where the knob value is too small.
20221128-183721-jzhou-bdfe7355a2332938

Increase buggified lock bytes for backup workers [release-7.1]

---

fdbserver/VersionedBTree.actor.cpp

A Redwood shutdown could leave references to destroyed objects in the global Evictor, causing the next Evictor operation to use the eviction order to crash.
This is fixed by adding explicit cancel of FIFOQueue operations during Redwood shutdown to prevent page cache additions after the page cache clear.  Clearing the page cache reclaims its pages from the Evictor, so any pages added after clearing the cache will then be in the Evictor's eviction order list so the next Redwood instance to use the Evictor will crash. …

Fix Redwood crash after shutdown

---

fdbrpc/HTTP.actor.cpp
fdbrpc/include/fdbrpc/AsyncFileReadAhead.actor.h

1.the content length from http response transformed using 'atoi' would rise int32 overflow. 
2.the offset's aligning would rise int32 overflow.

Fix the bug of variable int32 overflow.

---

fdbclient/Tracing.actor.cpp

Previously we did not null out "attributes" in `Span& Span::operator=(Span&& o);`, but we destroyed the arena owning memory referenced by "attributes". Fix that by nulling out "attributes", and rewrite it in a way that's (hopefully) less error-prone.
ASAN diagnostic:
```
==24==WARNING: ASan doesn't fully support makecontext/swapcontext functions and may produce false positives in some cases!
=================================================================
==24==ERROR: AddressSanitizer: heap-use-after-free on address 0x60300033fa06 at pc 0x0000026eadcf bp 0x7ffca646fe50 sp 0x7ffca646f618
READ of size 9 at 0x60300033fa06 thread T0
#0 0x26eadce in __asan_memmove /tmp/llvm-project/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:30:3
#1 0xd43db76 in __copy<const unsigned char, …
```

Fix an asan error

---

fdbserver/DDRelocationQueue.actor.cpp
fdbserver/DDTxnProcessor.actor.cpp
fdbserver/MoveKeys.actor.cpp
fdbserver/include/fdbserver/MoveKeys.actor.h
fdbserver/workloads/DataLossRecovery.actor.cpp
fdbserver/workloads/IDDTxnProcessorApiCorrectness.actor.cpp
fdbserver/workloads/PhysicalShardMove.actor.cpp
fdbserver/workloads/RandomMoveKeys.actor.cpp

Adding `Optional<std::vector<KeyRange>> ranges` into `MoveKeysParams`.
20221129-060111-zhewu_8938-077bd68211e3ef29        compressed=True data_size=41277190 duration=4077067 ended=100000 fail=6 fail_fast=10 max_runs=100000 pass=99994 priority=100 remaining=0 runtime=0:50:34 sanity=False started=100231 stopped=20221129-065145 submitted=20221129-060111 timeout=5400 username=zhewu_8938
All test failures are due to `Traced too many lines`, and seems unrelated to this PR.

Make startMoveShards and finishMoveShards to take a list of ranges

---

fdbserver/SimulatedCluster.actor.cpp

Enabling backup tests with rocksdb storage engine.
Joshua tests:
20221128-152839-neethu-all1-9cd5e19c426e7bbe   ended=100011 fail=1
20221128-152852-neethu-all2-9cd5e19c426e7bbe   ended=100004 fail=5
20221128-152909-neethu-all3-9cd5e19c426e7bbe   ended=100014 fail=3
No backup test failures.

Enabling backup tests with rocksdb storage engine.

---

fdbclient/DatabaseContext.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/include/fdbclient/DatabaseContext.h
flow/include/flow/flow.h

This isa revert for #8602 
In the following scenario a watch might be deleted by mistake:
Two watches over key A
```
Watch 1                     Watch 2                 Reference Count
|                                                          []
|   Version 100, Value 10
T |   Add reference count                                    [100]
I |   Metadata added
M |   ...
E |                               Version 200, Value 20
|                               Add reference count        [100, 200]
|                               Delete the old metadata
|                                      *together with the reference count*    <----- [1]
|                                                          []
|                               Trigger watch 1
|                               Update metadata …
```

Bring reference count to watch metadata

---

fdbserver/BlobManifest.actor.cpp
fdbserver/include/fdbserver/BlobGranuleServerCommon.actor.h
fdbserver/storageserver.actor.cpp

It's a fix for an edge case. FetchKeys may get a continuous key range which includes blobfied and non-blobfied ranges. If we pass the whole range to blob workers, It causes failures when reading from blob storage. So the fix is to only fetch keys for restoring ranges. Others will be handled in next fetch key request. 

BlobRestore - only fetch keys from blob storage for those are restoring

---

bindings/bindingtester/tests/api.py
bindings/python/fdb/impl.py
bindings/python/tests/tester.py
cmake/AddFdbTest.cmake

The binding tester was not properly handling operations that had the _TENANT suffix. This fixes that problem and a few related bugs.

Properly generate operations with the _TENANT suffix

---

fdbclient/MonitorLeader.actor.cpp
fdbclient/NativeAPI.actor.cpp
fdbrpc/TokenCache.actor.cpp
fdbserver/GrvProxyTagThrottler.actor.cpp
fdbserver/MockGlobalState.actor.cpp
fdbserver/Resolver.actor.cpp
fdbserver/workloads/IDDTxnProcessorApiCorrectness.actor.cpp

These code probes are now hit regularly in nightly correctness testing, so the rare annotation no longer applies to them.

Remove rare annotation from some code probes

---

fdbclient/ServerKnobs.cpp

When buggified at 1, recovery could get stuck looping indefinitely because the source/dest servers would not fill in properly during DD moveKeys

Disable buggify for DD_QUEUE_MAX_KEY_SERVERS knob

---

bindings/c/foundationdb/fdb_c.h
bindings/c/foundationdb/fdb_c_internal.h
bindings/go/src/fdb/database.go
bindings/go/src/fdb/fdb.go
bindings/go/src/fdb/fdb_test.go

This allows to create a database from a connection string inside the go bindings. That feature is useful for tools that try to connect with different connection strings to database, or if they use the database structure only for a short time e.g. like the operator is using the go bindings.
I added a new example to test the new setup.

Allow to create database in go bindings with connection string

---

bindings/java/src/main/com/apple/foundationdb/Database.java
bindings/java/src/main/com/apple/foundationdb/JNIUtil.java
bindings/java/src/main/com/apple/foundationdb/ReadTransaction.java
bindings/java/src/main/com/apple/foundationdb/Tenant.java

Malformed javadocs broke the latest release build. This makes the errors/warnings go away, but does not pass really help with meaningful documentation. 
I'd appreciate some help from reviewers to get this fixed up before merging. 

remove javadoc errors/warnings -- this needs to be cleaned up.

---

fdbclient/ReadYourWrites.actor.cpp
fdbserver/workloads/WriteDuringRead.actor.cpp
flow/include/flow/genericactors.actor.h

Track whether an AndFuture has begun
Previously, for deciding whether or not it was legal to set READ_YOUR_WRITES_DISABLE, it was allowed as long as no reads were in-flight. It's possible that a read can have been initiated, but the RYW caches are empty and no reads are in-flight. See #8925 for an example.
Reviewers: @sfc-gh-tclinkenbeard for c++ style and @sfc-gh-etschannen for the functional change.
Closes #8925

Track whether an AndFuture has begun

---

fdbclient/HTTP.actor.cpp
fdbrpc/AsyncFileReadAhead.actor.h

cherrypick #8939
Fix the bug of variable int32 overflow.
1.the content length from http response transformed using 'atoi' would rise int32 overflow.
2.the offset's aligning would rise int32 overflow.

Release 6.3-Fix the bug of variable int32 overflow.

---

fdbserver/include/fdbserver/ClusterController.actor.h

If A is disconnected with B, we always want to select one of them deterministically, instead of sometimes, A is selected to be degraded and sometimes, B is selected to be degraded.
20221202-190926-zhewu_8967-e82af554593e66eb

Add determinstic in gray failure degraded server selection

---

fdbserver/DataDistribution.actor.cpp
fdbserver/workloads/SnapTest.actor.cpp

This improves test coverage for the data distributor snapshot request handling. Some dead code is also removed from `SnapTest.actor.cpp`.

Randomly attempt duplicate snapshot in `SnapTestWorkload`

---

bindings/c/test/mako/async.cpp
bindings/c/test/mako/async.hpp
bindings/c/test/mako/mako.cpp
bindings/c/test/mako/mako.hpp
bindings/c/test/mako/mako.rst

This PR adds the possibility to specify timeouts via the transaction option. Previously, timeouts were always set via the database option. For testing, I ran mako and verified that timeouts occur with both possibilities to set them and in both modes (sync and async). 

Mako: Timeout Support on Transaction Level

---

fdbserver/Status.actor.cpp
flow/Trace.cpp
flow/include/flow/Trace.h

server/status: fix cgroup reporting to fail silently for v2
There are a few issues here:
1. The cgroup reporting added looks for top level metrics of cgroup v1.
2. Looking at the whole machine tells us nothing about fdbserver.
3. The reporting itself expects the values to be there rather than
failing silently if we're not on v1. As cgroup v2 is significantly
more prominent.
This fixes 3, but 1 and 2 are open and quite questionable. These really
ought to be reported by a 3rd party observer and not fdb itself.
While I'm here also add tryget helpers to TraceEventFields.
If this …

server/status: fix cgroup reporting to fail silently for cgroup v2

---

fdbclient/include/fdbclient/VersionedMap.h
fdbserver/ClusterRecovery.actor.cpp

Seed storage servers are recruited as the intial set of storage servers when a database is first created. They function a little bit differently than normal, and do not set an initial version like storages normally do when they get recruited (typically equal to the recovery version).
Version correction is a feature where versions advance in sync with the clock, and are equal across FDB clusters. To allow different FDB clusters to have matching versions, they must share the same base version. This defaults to the Unix epoch, and clusters with the version epoch enabled will have a current version equal to the number of microseconds since the Unix epoch.
When the version epoch is enabled on a cluster, it causes a one time jump from the clusters current version to the version based on the …

Fix issue where the versions on seed storage servers decreased

---

bindings/c/foundationdb/fdb_c.h
bindings/c/test/unit/unit_tests.cpp
bindings/java/fdbJNI.cpp
bindings/java/src/integration/com/apple/foundationdb/MappedRangeQueryIntegrationTest.java
bindings/java/src/main/com/apple/foundationdb/MappedKeyValue.java
bindings/java/src/main/com/apple/foundationdb/MappedRangeResultDirectBufferIterator.java
fdbclient/NativeAPI.actor.cpp
fdbclient/include/fdbclient/FDBTypes.h
fdbclient/include/fdbclient/MultiVersionTransaction.h
fdbserver/storageserver.actor.cpp

Client knows whether an entry is a boundary, and client also can see whether the record for that entry exist by checking whether the rangeResult is empty. This field is useless.
This field breaks backward compatibility, need to remove it.
20221207-175829-haofu-34a25372006405b8

Remove boundaryAndExist

---

fdbclient/NativeAPI.actor.cpp

Many `ChangeFeed*` and `BlobGranule*` tests failed with `Assertion impl.has_value() failed @ /codebuild/output/src420617781/src/github.com/apple/foundationdb/flow/include/flow/Arena.h 267:`.
20221210-181533-jzhou-2c585a5fa5417229

Fix assertion failure from changeFeedTSSValidator()

---

cmake/ConfigureCompiler.cmake

In release builds (i.e. with FDB_RELEASE on), we use cpack to strip debug sections from the binaries and create separate debuginfo RPMs. This process was failing on the main branch. 
After I disabled debug section compression, the debuginfo  packages could be successfully generated again, so this PR is removing debug section compression for release builds. However, I was not able to find any information about support for debug section compression in cpack. 

Do not compress debug sections in release builds

---

fdbclient/FDBTypes.cpp
fdbclient/include/fdbclient/FDBTypes.h
fdbserver/DDShardTracker.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/include/fdbserver/DataDistribution.actor.h

Create the basic structure for tracking physical shard metrics.
The basic idea is that for each physical shard, we want to track the data metrics (size, bandwidth, etc.) of all the key ranges in it. Therefore, in each physical shard instances, we keep track of all the key ranges that belong to this physical shard, and use existing per key range metrics tracking to aggregate all the metrics.
This PR creates the basic structure: for each physical shard instance, it needs to maintain the list of key ranges it owns, and such list needs to be consistent with keyRangePhysicalShardIDMap.
In the next PR, we wii add per range metrics tracking and aggregation.
20221207-190355-zhewu_8999-2775a849c1d144da …

Create the skeleton for physical shard metrics tracking

---

fdbserver/fdbserver.actor.cpp
fdbserver/worker.actor.cpp
flow/SystemMonitor.cpp
flow/include/flow/SystemMonitor.h

- Log FoundationDB version as part of "ProcessMetrics":
The goal is to make processes log the FoundationDB version more often.
Testing:
Simulation tests: 20221212-211736-sre-5c8b4e0e45d994ea (shows failures in tests "HighContentionPrefixAllocator.toml", "MetaclusterManagement.toml", and "FuzzApiCorrectness.toml". I don't think these failures are related to the changes in this PR - I think "HighContentionPrefixAllocator.toml" is a known RocksDB related failure, "MetaclusterManagement.toml" fails even after I disabled the FoundationDB version related logging statement in "SystemMonitor.cpp", and "FuzzApiCorrectness.toml" is also running with "ssd-rocksdb-v1" and it gets stuck when I run it locally even after I disabled the FoundationDB version related logging statement in …

Extend "ProcessMetrics" to include FoundationDB version

---

fdbserver/KeyValueStoreRocksDB.actor.cpp

Moving rocksdb read iterator destruction from commit path to actor.

Moving rocksdb read iterator destruction from commit path to actor.

---

bindings/c/CMakeLists.txt

clang15 will recognize some of the GNU extensions and mark the warnings as errors. This patch will set the errors back to warnings so they will not fail the build.
The warnings/errors are:
```
FAILED: bindings/c/CMakeFiles/fdb_c90_test.dir/test/fdb_c90_test.c.o
ccache /usr/local/bin/clang -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_SYSTEM_NO_DEPRECATED -DNO_INTELLISENSE -I/root/release-7.2/bindings/c -I/root/src/bindings/c -I/root/release-7.2/bindings/c/foundationdb -O3 -DNDEBUG -DCMAKE_BUILD -ggdb -fno-omit-frame-pointer -mavx -Wall -Wextra -Wredundant-move -Wpessimizing-move -Woverloaded-virtual -Wshift-sign-overflow -Wno-sign-compare -Wno-undefined-var-template -Wno-unknown-warning-option -Wno-unused-parameter -Wno-constant-logical-operand -Wno-deprecated-copy …
```

fixup! Fix the clang error in bindings/c

---

flow/TLSConfig.actor.cpp

Currently, when a TLS certificate, CA or key is configured and is not found, the error messages include the word "Failure" and confuses users when the FDB client goes on to connect successfully to a cluster that is not configured with TLS.
To avoid confusing users, TLS error messages should reflect the fact that they are non-fatal warnings.
Testing: Text-only change.
- [k] Every function/class/actor that was touched is reasonably well documented.

TLS error messages should reflect their non-fatal nature

---

fdbserver/fdbserver.actor.cpp
fdbserver/worker.actor.cpp
flow/SystemMonitor.cpp
flow/SystemMonitor.h

Log FoundationDB version as part of "ProcessMetrics":
The goal is to make processes log the FoundationDB version more often.
Testing:
Simulation tests: 20221213-185729-sre-c7fdc51588201dee (no failures).

Release 7.1: Cherry pick pull request #9033

---

flow/include/flow/OTELMetrics.h

Fix #9046
I think in OTEL point the startTime is not used, so I set the default value to -1. Correct me if I am wrong.

fix uninitialised byte(s) field in NumberDataPoint

---

fdbclient/IdempotencyId.actor.cpp
fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/IdempotencyId.actor.h
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/CommitProxyServer.actor.cpp
fdbserver/workloads/AutomaticIdempotencyWorkload.actor.cpp
tests/fast/AutomaticIdempotency.toml

Add a new actor to the first proxy which periodically checks for old idempotency ids and deletes them. Tested by adding a new workload which validates that the cleaner cleans ids older than a min age configurable via a knob, and does not clean ids younger than that knob.
Normally idempotency ids are deleted as part of the normal commit process, so this only needs to clean ids that leaked during a failure scenario. The rate of leaked idempotency ids should be low. The rate is zero during normal operation, and proportional to the number of in-flight transactions during a failure scenario.
New knobs:
1. IDEMPOTENCY_IDS_CLEANER_POLLING_INTERVAL
1. IDEMPOTENCY_IDS_MIN_AGE_SECONDS
Co-authored by @sfc-gh-akejriwal and Santosh Porwal …

Automatically clean old idempotency ids

---

fdbrpc/Stats.actor.cpp
flow/Knobs.cpp
flow/include/flow/Knobs.h

We don't always need to emit all DDSketch buckets. Since it might be a costly operation, the default is false. The knob `METRICS_EMIT_DDSKETCH` determines whether or not the buckets get emitted. 

Add knob to control emission of DDSketch buckets

---

fdbserver/fdbserver.actor.cpp
fdbserver/worker.actor.cpp
flow/SystemMonitor.cpp
flow/include/flow/SystemMonitor.h

Merge pull request #9033 from sbodagala/main.
Log FoundationDB version as part of "ProcessMetrics":
The goal is to make processes log the FoundationDB version more often.
Testing:
Simulation tests: 20221215-150606-sre-4335a248362ef91a  (shows a failure in "SnapTestSimpleRestart-1.txt" test; I see this test failing intermittently in nightly clang runs, so I assume this failure was not caused by this change set).

Release-7.2: Cherry pick pull request #9033

---

fdbserver/DDShardTracker.actor.cpp
fdbserver/include/fdbserver/DataDistribution.actor.h

Create a key range metrics tracker for each range inside a physical shard. This meant to be temporary until we have a new interface that tracks physical shard metrics more efficiently.
20221214-235000-zhewu_9055-1cb01857d3668458

Track individual key range metrics in each physical shard

---

fdbclient/MultiVersionTransaction.actor.cpp

This PR removes unnecessary calls to setTimeout in MultiVersionTransaction::setOption. 100% of the ctest's passed on the team server. 

MultiVersionTransaction: call setTimeout in setOption only when necessary

---

fdbrpc/AsyncFileCached.actor.cpp
fdbrpc/include/fdbrpc/AsyncFileChaos.h
fdbrpc/include/fdbrpc/LoadBalance.actor.h
fdbserver/VersionedBTree.actor.cpp
flow/include/flow/genericactors.actor.h
flow/network.cpp

`mapAsync` specified a third parameter that it tried to set to a default, but usage of the function was trying to deduce the third parameter and generally failed. This change removes the third parameter and replaces it's usage with the default value everywhere.

Make mapAsync usable without specifying template parameters

---

fdbserver/KeyValueStoreRocksDB.actor.cpp
fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
fdbserver/RocksDBCheckpointUtils.actor.cpp

If a log directory is specified in the "db_log_dir" option, RocksDB will add the whole file path in the log file name, which can exceed the 255 byte limit of Linux file system, causing storage server failures.
See
https://github.com/facebook/rocksdb/blob/c3f720c60db59c27486d8f18e094f9d1eb3c33cf/include/rocksdb/options.h#L674-L679
Test: manually verified running simulation in a long file path crashed without the fix and passed with the fix.
20221219-181608-jzhou-037c748234b47381

Fix log file name too long for RocksDB in simulation

---

fdbserver/KeyValueStoreRocksDB.actor.cpp
fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
fdbserver/RocksDBCheckpointUtils.actor.cpp

cherrypick #9066
If a log directory is specified in the "db_log_dir" option, RocksDB will add the whole file path in the log file name, which can exceed the 255 byte limit of Linux file system, causing storage server failures.
See
https://github.com/facebook/rocksdb/blob/c3f720c60db59c27486d8f18e094f9d1eb3c33cf/include/rocksdb/options.h#L674-L679

Fix log file name too long for RocksDB

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/DDTeamCollection.actor.cpp
flow/flow.cpp
flow/include/flow/flow.h

**Bug behavior:**
When DD has zero healthy machine teams but more unhealthy machine teams than the max machine teams DD plans to build, DD will stop building new machine teams. Due to zero healthy machine team (and zero healthy server team), DD cannot find a healthy destination team  to relocate data. When data relocation stops, exclusion stops progressing and stuck.
Bug happens when we *shrink* a k-host cluster by
first adding k/2 new host;
then quickly excluding all old hosts.
**Fix:**
Let DD build temporary extra teams to relocate data. The extra teams will be cleaned up later by DD's remove extra teams logic.
**Simulation test:**
There is no simulation test to cover cluster expansion scnenario. To most closely simulate this behavior, we intentionally overbuild all possible machine …

Fix:Exclusion stuck because DD cannot build new teams

---

fdbclient/ServerKnobs.cpp
fdbclient/ServerKnobs.h
fdbserver/DDTeamCollection.actor.cpp
flow/flow.cpp
flow/flow.h

Backport of [PR#9021](https://github.com/apple/foundationdb/pull/9021)
Bug behavior:
When DD has zero healthy machine teams but more unhealthy machine teams than the max machine teams DD plans to build, DD will stop building new machine teams. Due to zero healthy machine team (and zero healthy server team), DD cannot find a healthy destination team  to relocate data. When data relocation stops, exclusion stops progressing and stuck.
Bug happens when we *shrink* a k-host cluster by
first adding k/2 new host;
then quickly excluding all old hosts.
Fix:
Let DD build temporary extra teams to relocate data. The extra teams will be cleaned up later by DD's remove extra teams logic.
Simulation test:
There is no simulation test to cover cluster expansion scnenario. To most closely simulate this …

[Release 7.1] Fix:Exclusion stuck because DD cannot build new teams

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/DDTeamCollection.actor.cpp
flow/flow.cpp
flow/include/flow/flow.h

Backport for [PR#9021](https://github.com/apple/foundationdb/pull/9021) 
Bug behavior:
When DD has zero healthy machine teams but more unhealthy machine teams than the max machine teams DD plans to build, DD will stop building new machine teams. Due to zero healthy machine team (and zero healthy server team), DD cannot find a healthy destination team  to relocate data. When data relocation stops, exclusion stops progressing and stuck.
Bug happens when we *shrink* a k-host cluster by
first adding k/2 new host;
then quickly excluding all old hosts.
Fix:
Let DD build temporary extra teams to relocate data. The extra teams will be cleaned up later by DD's remove extra teams logic.
Simulation test:
There is no simulation test to cover cluster expansion scnenario. To most closely simulate this …

[Release-7.2] Fix:Exclusion stuck because DD cannot build new teams

---

fdbserver/QuietDatabase.actor.cpp
fdbserver/worker.actor.cpp

This is to be consistent with production deployment where low DC lag is expected.
20221220-033554-jzhou-a55ffd608e7e39b1

Add DC lag check in quiet database checks

---

cmake/ConfigureCompiler.cmake

The results of using the default DWARF 5 format in clang currently does not play well with GNU Binutils and results in `addr2line` and other tools omitting line numbers.

Use DWARF 4 in clang builds

---

fdbserver/DDShardTracker.actor.cpp
fdbserver/include/fdbserver/DataDistribution.actor.h

Create a single stats per physical shard instance and updated by trackKeyRangeInPhysicalShardMetrics.
This metrics is currently redundant to the `metrics` in physical shard instance and meant to replace it.
20221220-005908-zhewu_9067-df0df76ab9f4c491

Aggregate all key range metrics into single physical shard stats

---

fdbserver/TLogServer.actor.cpp

These were lost, likely due to refactoring. Now TLogMetrics have meaningful data like:
TLogMetrics ID=59ec9c67b4d07433 Elapsed=5 BytesInput=0 -1 17048 BytesDurable=47.4 225.405 17048 BlockingPeeks=0 -1 0 BlockingPeekTimeouts=0 -1 0 EmptyPeeks=1.6 2.79237 236 NonEmptyPeeks=0 -1 32 ...
20221221-192416-jzhou-2f8bf90cc4f03584

Add back samples for (non)empty peeks stats

---

fdbserver/TLogServer.actor.cpp

cherrypick #9072
These were lost, likely due to refactoring. Now TLogMetrics have meaningful data like:
TLogMetrics ID=59ec9c67b4d07433 Elapsed=5 BytesInput=0 -1 17048 BytesDurable=47.4 225.405 17048 BlockingPeeks=0 -1 0 BlockingPeekTimeouts=0 -1 0 EmptyPeeks=1.6 2.79237 236 NonEmptyPeeks=0 -1 32 ...

Add back samples for (non)empty peeks stats [release-7.1]

---

fdbserver/TLogServer.actor.cpp

cherrypick #9072 
These were lost, likely due to refactoring. Now TLogMetrics have meaningful data like:
TLogMetrics ID=59ec9c67b4d07433 Elapsed=5 BytesInput=0 -1 17048 BytesDurable=47.4 225.405 17048 BlockingPeeks=0 -1 0 BlockingPeekTimeouts=0 -1 0 EmptyPeeks=1.6 2.79237 236 NonEmptyPeeks=0 -1 32 ...

Add back samples for (non)empty peeks stats [release-7.2]

---

cmake/AddFdbTest.cmake

The unquoted value would break the build when sanitizer options were included.

Fix unquoted variable in cmake that cause certain builds to fail

---

fdbrpc/IPAllowList.cpp

A memcpy invocation was only copying 4 of the needed 16 bytes, leaving the remaining 12 uninitialized.

Fix use of uninitialized memory in IP AllowList test

---

fdbserver/worker.actor.cpp

To account for newly added peer. Currently, the elapsed time is the process up time.
20221222-004239-zhewu_9078-3d066b152b7be4f0

fix health monitor last logged time

---

bindings/c/CMakeLists.txt
cmake/ConfigureCompiler.cmake

This is a backport that lets clang uses dwarf4 on release-7.2. After we moved to clang15, by default we use dwarf5 which breaks addr2line.

Use dwarf-4 on release-7.2 branch

---

fdbserver/KeyValueStoreRocksDB.actor.cpp

Adding rocksdb read latency metrics.

Adding rocksdb read latency metrics.

---

cmake/CompileBoost.cmake

Fix Windows build broken by #8904
- Add missing boost libraries
- Add missing flow dependencies

Fix Windows build broken by #8904

---

fdbserver/KeyValueStoreShardedRocksDB.actor.cpp

Line 948 hit this bug where id was free'ed at line 946 
946	pendingDeletionShards.pop_front();
948	physicalShards.erase(id);

Fix use after free bug

---

fdbserver/KeyValueStoreShardedRocksDB.actor.cpp

cherrypick #9089
Line 948 hit this bug where id was free'ed at line 946
946	pendingDeletionShards.pop_front();
948	physicalShards.erase(id);
Seed: `-f slow/DDBalanceAndRemove.toml  -s 905559887 -b on`
commit: [62626ca](https://github.com/apple/foundationdb/commit/62626ca9b32f498af5a796e830ca0a8c8678a329)

Fix use after free bug [release-7.2]

---

fdbclient/ManagementAPI.actor.cpp
fdbrpc/AsyncFileChaos.cpp
fdbrpc/FailureMonitor.actor.cpp
fdbrpc/include/fdbrpc/AsyncFileChaos.h
fdbrpc/include/fdbrpc/genericactors.actor.h
fdbrpc/include/fdbrpc/simulator.h
fdbrpc/sim2.actor.cpp
fdbserver/KeyValueStoreSQLite.actor.cpp
fdbserver/MoveKeys.actor.cpp
fdbserver/SimulatedCluster.actor.cpp
fdbserver/VersionedBTree.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/workloads/BlobGranuleCorrectnessWorkload.actor.cpp
fdbserver/workloads/BlobGranuleVerifier.actor.cpp
fdbserver/workloads/DataLossRecovery.actor.cpp
fdbserver/workloads/DiskFailureInjection.actor.cpp
fdbserver/workloads/FastTriggeredWatches.actor.cpp
fdbserver/workloads/GetMappedRange.actor.cpp
fdbserver/workloads/LowLatency.actor.cpp
fdbserver/workloads/MachineAttrition.actor.cpp
fdbserver/workloads/PhysicalShardMove.actor.cpp
fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp
fdbserver/workloads/StorageServerCheckpointRestoreTest.actor.cpp
flow/include/flow/network.h

This is to fix the issue that if bit flipping is injected, StorageServer backend may not recognize the error is caused by DiskFailure injector, and raise a SevError. By differentiating an injected error (which raises SevWarnAlways) and a real error
(which raises SevError), the correctness false failure should disappear.

Backport machine attrition code to release-7.2

---

fdbserver/MoveKeys.actor.cpp

The data_move_cancelled error doesn't cause DD to restart.
test: passed 100k `tests/fast/KillRegionCycle.toml`: 20230106-072712-heliu-75de1cfcd92e17d1

Fixed error type.

---

bindings/go/src/fdb/generated.go
design/idempotency_ids.md
documentation/sphinx/source/automatic-idempotency.rst
documentation/sphinx/source/client-design.rst
documentation/sphinx/source/developer-guide.rst
fdbclient/vexillographer/fdb.options

- Add user-facing documentation for the AUTOMATIC_IDEMPOTENCY transaction option
- Update the design doc. I believe the design is now sufficient for higher-level retry loops (e.g. the multi-version client, or a custom retry loop that wants to retry `transaction_timed_out`) to provide automatic idempotency.
- Mark AUTOMATIC_IDEMPOTENCY as not hidden (but still not recommended for production use). The reason for doing this is to make the example code in the user docs valid. I do think it's close enough to ready for folks to experiment with. …

Add initial documentation for automatic idempotency

---

fdbserver/ClusterController.actor.cpp
fdbserver/include/fdbserver/ClusterController.actor.h

Different from satellite server degradation which is based on latency and prune to WAN instability, disconnection between primary and primary satellite definitely indicate issue, and therefore it is a strong indicator that a recovery is required to exclude disconnected servers.
20230106-062544-zhewu_9100-acd0ffb483796daf

Disconnection to satellite TLog should trigger recovery in gray failure detection

---

fdbserver/VersionedBTree.actor.cpp

The unit test intentionally cause unexpected_encoding_type being thrown, which would hit a simulation only assert failure. Disabling that assert in this case.

Fix /redwood/correctness/EnforceEncodingType unit test

---

fdbrpc/sim2.actor.cpp
fdbserver/BlobWorker.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/workloads/SpecialKeySpaceCorrectness.actor.cpp

Cherrypick #8552 and #8682 for blob worker correctness failures.
Cherrypick #8465 and #8866 for special key correctness failures.
20230109-050926-jzhou-d414cfa6eb5ac54e

Cherrypick blob worker fixes [release-7.2]

---

fdbserver/fdbserver.actor.cpp

i.e., FETCH_USING_STREAMING and PEEK_USING_STREAMING
The corruption bugs have been fixed by https://github.com/apple/foundationdb/pull/8646 and https://github.com/apple/foundationdb/pull/8526

Remove dangerous label for streaming knobs

---

fdbrpc/sim2.actor.cpp

Cherrypick #8881 to fix valgrind restarting failures

Init blobGranulesEnabled in ISimulator [release-7.2]

---

contrib/TestHarness2/test_harness/joshua.py

Fix restart test command missing --restarting params.

TestHarness2: fix reproduce command missing --restarting param

---

fdbserver/BlobManager.actor.cpp
fdbserver/BlobManifest.actor.cpp
fdbserver/BlobMigrator.actor.cpp
fdbserver/workloads/BlobRestoreWorkload.actor.cpp
fdbserver/workloads/IncrementalBackup.actor.cpp
tests/fast/BlobRestoreBasic.toml

Run Cycle check after blob restore. Addtionally 2 minor fixes
1) revert waitRetries in previous PR. it doesn't help.
2) use dbInfo->get().client.clusterId for managerEpochsSeen. it doesn't change across ClusterController restarts. 
zero errors for 100K tests of BlobRestoreBasic.toml, and 100K BlobGranule* tests

Run Cycle check for BlobRestoreBasic.toml

---

fdbserver/RESTKmsConnector.actor.cpp

A unit test was trying to access a JSON field at the wrong location, and this triggered assertions in debug builds.
@sfc-gh-ahusain I'm not sure why this doesn't fail the test in non-debug builds, but you may want to investigate that.

Fix incorrect JSON access of blob metadata partitions in REST KMS test

---

fdbserver/ApplyMetadataMutation.cpp
fdbserver/BlobWorker.actor.cpp
fdbserver/Resolver.actor.cpp

Blob worker encryption is no longer dependent on the `BG_METADATA_SOURCE` knob

Blob Worker Encryption doesn't use BG_METADATA_SOURCE

---

bindings/go/src/fdb/fdb_freebsd.go

The build of Go language bindings for FoundationDB has failed on FreeBSD.
I added new binding for FreeBSD using the Darwin (MacOS) binding as an example.

Add Golang binding for FreeBSD

---

fdbserver/RocksDBCheckpointUtils.actor.cpp

It looks like the rocks version was upgraded by the build system, and this static assert is incorrect.
This is causing all gccCI to fail on snowflake/release-71.2.
Snowflake doesn't use rocks so just fixing the assert is fine.

[snowflake/release-71.2] fixing rocks assert

---

fdbserver/tester.actor.cpp

Fixes running `fdbserver -r multitest` (see https://apple.github.io/foundationdb/client-testing.html#running-a-workload-on-an-actual-cluster) by ignoring `g_simulator` when not running in simulation.

Ignore `g_simulator` in multitest mode

---

fdbclient/ServerKnobs.cpp

disable buggify for DD_QUEUE_MAX_KEY_SERVERS knob [release-7.2]

---

fdbserver/workloads/HighContentionPrefixAllocatorWorkload.actor.cpp

The high contention allocator test sometimes times out in CI. I can't easily reproduce the 30 minute runtimes, though I did observe that the test does often take many minutes. In an attempt to resolve the CI issues, I'm decreasing the length of the main portion of the test by a factor of 5.

Decrease the number of HCA test rounds to decrease the test time

---

fdbclient/include/fdbclient/VersionedMap.h
fdbclient/include/fdbclient/WriteMap.h

Maintaining partial persistence of course.
We can theoretically also avoid creating a new node if the insert version of the node comparing equal to `x` is the latestVersion. There isn't a generic way to tell from the ptree though since insertAt is a concept that only exists within VersionedMap. Either way, avoiding the `contains` call and the tree rotations is already a big improvement.
The old node should only be reachable from old roots, and so it should get cleaned up as part of forgetVersions in the storage server. …

Change PTreeImpl::insert to overwrite existing entries

---

flow/include/flow/FastRef.h
flow/include/flow/ObjectSerializer.h
flow/include/flow/serialize.h
flow/serialize.cpp

clang takes long time to instantiate the `std::function`, by replacing it by a function pointer, the compile time is reduced.

Remove the `std::function` use in ObjectWriter

---

fdbclient/NativeAPI.actor.cpp
fdbrpc/FlowTransport.actor.cpp
fdbserver/CommitProxyServer.actor.cpp
fdbserver/DataDistribution.actor.cpp

There are a few Sev30s that are very noisy in production and can be downgraded to Sev20s

Change Noisy Sev30s to Sev20s

---

fdbserver/tester.actor.cpp

Cherrypick #8853
The crash was introduced in #8318
Manually confirmed `./fdbserver -C ./loopback-cluster/fdb.cluster -r consistencycheck` no longer crashes.
20230119-212632-jzhou-90f4dc942bd46a3c

Fix consistency check crashes [release-7.2]

---

fdbcli/BlobRestoreCommand.actor.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/SystemData.cpp
fdbclient/include/fdbclient/BlobGranuleCommon.h
fdbclient/include/fdbclient/DatabaseContext.h
fdbclient/include/fdbclient/SystemData.h
fdbserver/BlobManifest.actor.cpp
fdbserver/BlobMigrator.actor.cpp
fdbserver/include/fdbserver/BlobGranuleServerCommon.actor.h
fdbserver/storageserver.actor.cpp
fdbserver/workloads/BlobRestoreWorkload.actor.cpp

Support restore to a previous version
1) Add BlobRestoreArg to store the restore version from cli
2) FetchKeys - read blob data from given restore version
3) ApplyMutationLogs - apply mutation logs to certain restore version
100K tests passed for BlobRestore*

Restore to a previous version

---

fdbclient/ServerKnobs.cpp

We are still encountering simulation failures where the backup worker is waiting on the lock and an assertion fails.
128MB was not enough for the test to pass, but 256MB was.

Increase buggified lock bytes for backup workers to at least 256 MB.

---

fdbserver/BlobManager.actor.cpp

Removes unnecessary conflict range checks in blob manager lock check that caused transactions to be serialized.
Correctness in progress

removing extra unecessary conflict checking in BM lock check

---

fdbclient/NativeAPI.actor.cpp
fdbclient/StorageServerInterface.cpp
fdbrpc/include/fdbrpc/TenantInfo.h
fdbserver/BlobWorker.actor.cpp
fdbserver/CommitProxyServer.actor.cpp
fdbserver/TenantCache.actor.cpp
fdbserver/include/fdbserver/DataDistributorInterface.h
fdbserver/include/fdbserver/ProxyCommitData.actor.h
fdbserver/include/fdbserver/TCInfo.h
fdbserver/include/fdbserver/TenantCache.h
fdbserver/workloads/AuthzSecurity.actor.cpp
tests/CMakeLists.txt

Remove tenant names from the `TenantInfo` object. This will require a change to AuthZ to support token validation based on IDs, and for now this disables AuthZ tests.

Remove tenant name from the TenantInfo object

---

fdbserver/CommitProxyServer.actor.cpp

s/ApplyMetada/ApplyMetadata/ is not a big deal, but might as well spell it right.
The two identical ApplyMetaDaEffect entries were a little trickier to pick apart in the logs, when otherwise grouping CommitDebug entries by ID.

Fix some typos in the CommitDebug tags.

---

bindings/c/test/mako/async.hpp
bindings/c/test/mako/mako.cpp
bindings/c/test/mako/shm.hpp
bindings/c/test/mako/stats.hpp

With this PR, different CPU usage statistics are tracked in mako. This change required some small refactoring of the statistics accumulator classes. In particular, there are now three different classes for this purpose: one class to track statistics on the worker level, another class to track statistics on the thread level, and a third class to track statistics on the process level.  
Testing was done by running mako and comparing the final results with what I observed in `top` and `top -H`. 

Mako: Add CPU Usage statistics

---

fdbserver/worker.actor.cpp
flow/include/flow/CodeProbe.h

The `lock_file_failure` error can only be thrown outside of simulation, so the code probe for catching this error should be annotated accordingly.

Mark code probe as non-simulation only

---

fdbrpc/sim2.actor.cpp

Previously, the drop rate was too low, so sometimes even in 250k Joshua runs, no UDP packets were being dropped. This PR increases the drop rate so that we have sufficient code coverage.

Drop UDP packets more frequently in simulation

---

fdbrpc/FlowTransport.actor.cpp

Currently, when two processes can't talk to each other, the PingLatency won't be printed since there is no latency samples. Therefore, we also check connection failure status and print a PingLatency.
20230121-024106-zhewu_9195-d997e4dc135c8a14

Log PingLatency when there is no ping latency samples, but ping attempts

---

fdbserver/storageserver.actor.cpp

In certain parts of the storage server, we create a new transaction in response to an external request, and that new transaction should use the tenant of the original. In cases where the tenant wasn't set, this was actually setting an invalid tenant and causing an assertion failure.

Avoid using an invalid tenant when creating a transaction from a tenant ID

---

fdbserver/ConsistencyScan.actor.cpp

If a storage server was removed, the consistency scan may be looping forever, because "request_maybe_delivered" was not handled and the team's SS interfaces are not updated.
20230114-175225-jzhou-a22c9e64753db47c

Fix a consistency scan infinite looping without progress

---

fdbclient/NativeAPI.actor.cpp

The `getKeyLocation` functions were checking if the read version future was ready, but it was also possible for the future to not be set at all (e.g. in getRangeSplitPoints). If that were to happen, then an invalid memory access would result.

Fix a memory issue in getKeyLocation functions

---

fdbcli/TenantCommands.actor.cpp
fdbclient/BackupAgentBase.actor.cpp
fdbclient/Metacluster.cpp
fdbclient/Tenant.cpp
fdbclient/include/fdbclient/BackupAgent.actor.h
fdbclient/include/fdbclient/MetaclusterManagement.actor.h
fdbclient/include/fdbclient/Tenant.h
fdbclient/include/fdbclient/TenantEntryCache.actor.h
fdbclient/include/fdbclient/TenantManagement.actor.h
fdbclient/include/fdbclient/TenantSpecialKeys.actor.h
fdbserver/ApplyMetadataMutation.cpp
fdbserver/BlobGranuleServerCommon.actor.cpp
fdbserver/BlobManager.actor.cpp
fdbserver/BlobWorker.actor.cpp
fdbserver/TenantCache.actor.cpp
fdbserver/include/fdbserver/BlobGranuleServerCommon.actor.h
fdbserver/include/fdbserver/ProxyCommitData.actor.h
fdbserver/include/fdbserver/workloads/MetaclusterConsistency.actor.h
fdbserver/include/fdbserver/workloads/TenantConsistency.actor.h
fdbserver/storageserver.actor.cpp
fdbserver/workloads/BlobGranuleCorrectnessWorkload.actor.cpp
fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp
fdbserver/workloads/TenantEntryCacheWorkload.actor.cpp
fdbserver/workloads/TenantManagementConcurrencyWorkload.actor.cpp
fdbserver/workloads/TenantManagementWorkload.actor.cpp

Update the tenant maps stored in the database and in various places in the code to be keyed by ID rather than name. This also updates the metacluster tenant rename logic now that we don't need to maintain two separate entries for the rename.

Update tenant maps to be keyed by ID

---

fdbclient/ClientKnobs.cpp

Cherry-pick #9207.
Feed coalesce was potentially causing issues.
Passes 100k BlobGranule/ChangeFeed correctness with no failures.

[snowflake/release-71.2] disabling feed coalesce for now

---

fdbserver/SimulatedCluster.actor.cpp
fdbserver/coroimpl/CoroFlow.actor.cpp
fdbserver/include/fdbserver/SimulatedCluster.h
flow/SystemMonitor.cpp
tests/fast/DataLossRecovery.toml

Previously this test would routinely OOM by using more than 8GiB resident memory in the ASAN build

Lower ASAN memory usage

---

fdbcli/StatusCommand.actor.cpp

It's a fix for fdbcli "status details" error when blob_granules is enabled. The following is error message:
fdb> status details
ERROR: An unknown error occurred (4000)
The fix is to check if some field is included in status json first before accessing it. The error disappears after the fix. 

fix fdbcli status error

---

fdbclient/MonitorLeader.actor.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/include/fdbclient/CoordinationInterface.h
fdbclient/include/fdbclient/MonitorLeader.h
fdbserver/Coordination.actor.cpp

- Do not add fdbserver processes to the client list.
Note: Server processes started getting reported as clients since 7.1.0 (not sure if this change in behavior was intentional or not), and this breaks the operator upgrade logic.
Testing:
Simulation tests: 20230124-200510-sre-729672149736c9d4 (shows a failure in PerpetualWiggleStats.toml test; I revered my changes in"Coordination.actor.cpp" and the test still fails, so that failure doesn't appeared to be related to this change set).
Manual testing: Created a cluster locally, by using "tests/loopback_cluster/run_cluster.sh" and verified the "status json" output.
Status output: "clients" output, in "status json" output, over this change set:
"clients" : {
"count" : 0
},
NOTE: This behavior (of showing client count as zero) is not consistent …

Do not report fdbserver processes as clients in "status" output

---

fdbserver/BlobMigrator.actor.cpp

This is a fix for the following restore error caused by s3 url. We don't need to call listContainers for s3 url
"Invalid backup container base URL, resource aka path should be blank.". 
100K correctness tests passed for BlobRestore*.toml

Fix mutation log s3 url for blob restore

---

fdbserver/fdbserver.actor.cpp
fdbserver/workloads/SaveAndKill.actor.cpp

Pass authentication mode through restartInfo.ini and use the same authentication mode after restart in simulation.

EaR: make authentication mode non-changeable in restart tests

---

bindings/go/src/fdb/generated.go
fdbclient/vexillographer/fdb.options

`test_causal_read_risky` expects an argument specifying the probability the client checks whether its read is stale. The database option specification should include this parameter so it gets included in the generated bindings.

Add parameter for test_causal_read_risky database option

---

fdbserver/BlobManager.actor.cpp

Fixes one case of `now() - stableTimestamp.get() <= checkTimeoutOnceStable` failure
Passed 100k correctness with only unrelated #9242 failure

fixing racing BM assignment and split update from previous owner

---

fdbserver/coroimpl/CoroFlow.actor.cpp
flow/include/flow/network.h

This PR fixed the following 2 compile errors with VSCode on MacOS
[build] In file included from /Users/huliu/fdb_repos/foundationdb/flow/Hostname.actor.cpp:21:
[build] In file included from /Users/huliu/fdb_repos/foundationdb/flow/include/flow/Hostname.h:26:
[build] /Users/huliu/fdb_repos/foundationdb/flow/include/flow/network.h:67:7: error: no template named 'unordered_map' in namespace 'std'
[build]         std::unordered_map<TaskPriority, struct PriorityStats> activeTrackers;
[build]         ~~~~~^
[build] 1 error generated.
[build] /Users/huliu/fdb_repos/foundationdb/fdbserver/coroimpl/CoroFlow.actor.cpp:109:67: error: member access into incomplete type 'ISimulator::ProcessInfo' (aka 'simulator::ProcessInfo')
[build]                 if (g_network->isSimulated() && …

Fix compile error with VSCode

---

fdbclient/BlobGranuleFiles.cpp
fdbclient/include/fdbclient/VersionedMap.h
fdbclient/include/fdbclient/WriteMap.h
fdbrpc/sim2.actor.cpp
fdbserver/BlobManager.actor.cpp
fdbserver/QuietDatabase.actor.cpp
fdbserver/SimulatedCluster.actor.cpp
fdbserver/coroimpl/CoroFlow.actor.cpp
fdbserver/include/fdbserver/SimulatedCluster.h
flow/SystemMonitor.cpp
tests/fast/DataLossRecovery.toml

cherrypick 
20230126-181542-jzhou-4b12c5e57375f971

cherrypick multiple fixes and improvement [release-7.2]

---

documentation/sphinx/source/release-notes/release-notes-710.rst
fdbclient/CoordinationInterface.h
fdbclient/MonitorLeader.actor.cpp
fdbclient/MonitorLeader.h
fdbclient/NativeAPI.actor.cpp
fdbserver/Coordination.actor.cpp

Merge pull request https://github.com/apple/foundationdb/pull/9225 from sbodagala/main.
- Do not add fdbserver processes to the client list.
Note: Server processes started getting reported as clients since 7.1.0 (not sure if this change in behavior was intentional or not), and this breaks the operator upgrade logic.
Testing:
- Simulation tests: 0230126-213915-sre-a1a79f2b51849414 (in progress).
- Per Jingyu's suggestion, created a local cluster and connected with Release 7.1.25 fdbcli successfully (this is to be sure that no compatibility problems across versions).
If this PR …

Release 7.1: Cherry pick pull request #9225

---

fdbserver/GrvProxyServer.actor.cpp
flow/include/flow/error_definitions.h

GRV Proxy can convert a broken_promise errors to tlog_failed or master_failed depending on the role that was actually responsible for the broken promise.

GRV Proxy converts broken_promise errors to master_failed or tlog_failed

---

fdbserver/storageserver.actor.cpp

In one test, a storage server ran expensive validation after it started shutting down and closed its redwood instance. I didn't fully dig into the metadata discrepancies caused during shutdown, but it seemed like the PTree's data and the shard map were not cleared out atomically, causing part of the check to fail.
But overall this seems like not a useful check to do, as data structures and state are actively being cleared out during the check if the ss is shutting down.
Passes 10k correctness

skipping ss validation while shutting down because of races

---

fdbserver/KeyValueStoreRocksDB.actor.cpp
fdbserver/include/fdbserver/RocksDBLogForwarder.h

Removing extra logging rocksdb call, if logs are muted.

Removing extra logging rocksdb call, if logs are muted.

---

fdbserver/workloads/DataLossRecovery.actor.cpp

Due to buggifies and fault injection (for example, [this one](https://github.com/apple/foundationdb/blob/main/fdbserver/ClusterRecovery.actor.cpp#L1391) ), a recovery caused this read to take ~33s, longer than this 30s timeout. Since the timeout is just an optimization to end the test earlier if something goes wrong, I increased the timeout.
Passes 1k DataLossRecovery tests.

increasing timeout since simulated recovery can take >30s, and adding comment

---

documentation/sphinx/source/mr-status-json-schemas.rst.inc
fdbclient/Schemas.cpp
fdbserver/Status.actor.cpp

Adds a new `version_epoch` object to `status json`, which includes the status of the feature, and the current epoch if it is enabled. If the version epoch is disabled, the `epoch` field will not be present.
```
{
"client" : {
...
},
"cluster" : {
...
"version_epoch" : {
"enabled" : "true",
"epoch" : "100000"
},
...
}
}
```

Add version epoch to status json

---

fdbclient/NativeAPI.actor.cpp
fdbserver/BlobMigrator.actor.cpp
fdbserver/Status.actor.cpp
flow/include/flow/error_definitions.h

Fix a few blob restore errors:
1) Added a few error code to indicate missing or corrupted mutation logs
2) Print the error message when blob restore fails
3) Don't show mutation log applying progress because we don't have this progress number yet 
Tested ok in a local cluster

Fix misc blob restore error messages

---

fdbclient/BlobGranuleFiles.cpp
fdbclient/BlobGranuleReader.actor.cpp
fdbclient/include/fdbclient/BlobGranuleFiles.h

The deltaFileData parameter was type StringRef[], this indirectly causes
issue #9206. By setting the incoming parameter type to be
std::vector<StringRef>, the issue might be fixed plus adding extra
memory safety.
Please let me know how do I test this patch

    Let materializeBlobGranule accept a std::vector<StringRef> instead of StringRef[]

---

fdbserver/workloads/BlobGranuleCorrectnessWorkload.actor.cpp
fdbserver/workloads/BlobGranuleVerifier.actor.cpp

Passes 50k BlobGranule* correctness with 1 unrelated failure

move feed cleanup check to after data is guaranteed to be available for granules

---

tests/fast/RawTenantAccessClean.toml

timeout=200 is too small in some buggify case. Leave it to default value to fix early `time_out` errors

Remove test timeout

---

fdbclient/ServerKnobs.cpp
fdbserver/RestoreController.actor.h
fdbserver/RestoreLoader.actor.cpp

cherrypick #9184  https://github.com/apple/foundationdb/pull/9282
We are still encountered simulation failures where the backup worker is waiting on the lock and an assertion fails.

Increase buggified lock bytes for backup workers to at least 256 MB. [release-7.1]

---

fdbrpc/sim2.actor.cpp

In the HA configuration, it's possible the remote DC was killed 2 out of 3 machines with double replication, left not enough machines for a successful recovery. So this PR changes to Reboot to avoid such excessive killings.

Fix excessive killing for HA configuration

---

fdbrpc/sim2.actor.cpp
flow/FastAlloc.cpp
flow/test_memcpy_perf.cpp

cherrypick #9289 https://github.com/apple/foundationdb/pull/9273
In the HA configuration, it's possible the remote DC was killed 2 out of 3 machines, left not enough machines for a successful recovery. So this PR changes to Reboot to avoid such excessive killings.
20230201-230737-jzhou-d19151dd278b614b

Fix excessive killing for HA configuration [release-7.2]

---

fdbserver/fdbserver.actor.cpp
flow/Trace.cpp
flow/include/flow/Trace.h
flowbench/BenchTimer.cpp

CommitDebug trace events are useful for measuring, in detail, the time spent in
the various parts of a single transaction. Like all log events, they have a time
associated with them. This time comes for now(), which in a real fdb system is
only updated in the run loop. This renders the timestamps inaccurate in certain
CPU bound sections which don't have a wait, e.g. in the resolver.
We want to preserve the current behavior in simulation, where the timestamps are
artificial, deterministic between runs, and only updated in the run loop.
In a real system, we prefer to use a real clock so we can use the difference
between two trace events in the logs as a measurement of elapsed time.
This does not modify the behavior of other parts of the system, which use the
cached now() for various …

Use real clock source for trace events in real fdbserver, but now() in simulation.

---

fdbserver/fdbserver.actor.cpp
flow/Trace.cpp
flow/include/flow/Trace.h
flowbench/BenchTimer.cpp

This reverts commit 02f78500b50a4e29fae00965fc7509b6966c8353.
That changed the default behavior of the clock used for trace logs, which might break some tooling or workflows.

Revert "Use real clock source for trace events in real fdbserver, but now() in simulation. (#9270)

---

tests/fast/RawTenantAccessClean.toml

The `tr->readRange()` in the `TesterCheckDatabase` phase keeps getting transaction_too_old() until timeout. This has no apparent causal relation with the tenant check in Commit Proxy.
And this happens in buggify scenarios, though not sure whether this is the correct fix, mark this phase to false solve the timeout problem.
(Also, I noticed that there are other test toml file also set `clearAfterTest=false`, whether they are getting the same problem?

set clearAfterTest=false in RawTenantAccessClean test

---

contrib/TestHarness2/test_harness/run.py
fdbserver/workloads/BlobGranuleVerifier.actor.cpp
tests/CMakeLists.txt
tests/restarting/from_7.3.0/BlobGranuleRestartCycle-1.toml
tests/restarting/from_7.3.0/BlobGranuleRestartCycle-2.toml

Added basic blob granule granule restarting tests.
I'll add chaos to the cycle test, and add other workload tests in future PR(s).
Passes 10k of the new test.
To validate the test harness change, it also passed 10k normal correctness, and correctly found unseed errors in non-restarting tests when i injected non-determinism.

Blob granule restarting tests

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/CommitProxyInterface.h
fdbclient/include/fdbclient/FDBTypes.h
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/ClusterRecovery.actor.cpp
fdbserver/CommitProxyServer.actor.cpp
fdbserver/DDTeamCollection.actor.cpp
fdbserver/KeyValueStoreCompressTestData.actor.cpp
fdbserver/KeyValueStoreMemory.actor.cpp
fdbserver/KeyValueStoreRocksDB.actor.cpp
fdbserver/KeyValueStoreSQLite.actor.cpp
fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
fdbserver/SimulatedCluster.actor.cpp
fdbserver/VersionedBTree.actor.cpp
fdbserver/fdbserver.actor.cpp
fdbserver/include/fdbserver/IKeyValueStore.h
fdbserver/include/fdbserver/IPageEncryptionKeyProvider.actor.h
fdbserver/include/fdbserver/IPager.h
fdbserver/include/fdbserver/RemoteIKeyValueStore.actor.h
fdbserver/include/fdbserver/WorkerInterface.actor.h
fdbserver/storageserver.actor.cpp
fdbserver/worker.actor.cpp
fdbserver/workloads/ConfigureDatabase.actor.cpp
fdbserver/workloads/SaveAndKill.actor.cpp
flow/include/flow/error_definitions.h

The PR is updating storage server and Redwood to enable encryption based on the encryption mode in DB config, which was previously controlled by a knob. High level changes are
1. Passing encryption mode in DB config to storage server
1.1 If it is a new storage server, pass the encryption mode through `InitializeStorageRequest`. the encryption mode is pass to Redwood for initialization
1.2 If it is an existing storage server, on restart the storage server will send `GetStorageServerRejoinInfoRequest` to commit proxy, and commit proxy will return the current encryption mode, which it get from DB config on its own initialization. Storage server will compare the DB config encryption mode to the local storage encryption mode, and fail if they don't match
2. Adding a new `encryptionMode()` …

EaR: storage server uses encryption DB config

---

fdbserver/BlobGranuleValidation.actor.cpp
fdbserver/BlobWorker.actor.cpp

Passes 50k BlobGranule* correctness with 1 unrelated error.

adding metadata-only update for empty delta files to avoid blob storage writes

---

fdbclient/FileBackupAgent.actor.cpp
fdbclient/include/fdbclient/TenantEntryCache.actor.h
fdbserver/workloads/RestoreBackup.actor.cpp

For empty key ranges we would attempt to fetch a tenant id which is not possible since they don't belong to a tenant. This PR fixes this issue by assuming empty key ranges belong to the default encryption domain

Snapshot Backup Bug Fix

---

fdbserver/GrvProxyTagThrottler.actor.cpp

This test validates that multiple tags can concurrently be throttled to the correct rate.

Add `/GrvProxyTagThrottler/MultiTag` unit test

---

fdbserver/storageserver.actor.cpp

Metrics related to getMappedRange API are counted twice, having a set of new metrics specifically for getMappedRange solves the issue.

Fix getMappedRange metrics

---

fdbclient/include/fdbclient/MetaclusterManagement.actor.h
fdbclient/include/fdbclient/TenantManagement.actor.h
fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp

Fix the failed assertion 
```
ASSERT(found || checkEntry2.tenantState != checkState);
```
The failure appears because the renamed tenant is in `TenantMapEntry.renameDestination` not `TenantMapEntry.tenantName`. So the returned name should come from the original tenant name list.

Fix list tenant name bug

---

flow/Trace.cpp
flow/include/flow/Trace.h

CommitDebug trace events are useful for measuring, in detail, the time spent in the various parts of a single transaction. Like all log events, they have a time associated with them. This time comes for now(), which in a real fdb system is only updated in the run loop. This renders the timestamps inaccurate in certain CPU bound sections which don't have a wait, e.g. in the resolver.
The desired solution is to directly call ::timer_monotonic() instead of now() for a timestamp, since ::timer_monotonic() is what now() ultimately uses in the run loop, but is updated between waits as well.
In order to not disrupt any current uses of the logs which might depend on the current behavior of the Time field, we introduced the `MonotonicTime` field.
This change only affects CommitDebug trace events, …

Add timer_monotonic() to CommitDebug trace events.

---

bindings/c/test/mako/mako.cpp
bindings/c/test/mako/operations.cpp

`AUTHORIZATION_TOKEN` transaction option gets cleared upon call to `Transaction::reset()` and needs to be assigned again.
This PR implements that for Mako and also removes redundant calls to `Transaction::reset()` in Mako benchmark step functions which could cause subsequent operations to fail.
Also fix the bug where `createNewTransaction()` returns, along with the new transaction object, a tenant name instead of a token.
(Correctness-tested via Mako run with write workload)

Mako: fix token not being reassigned after every reset

---

fdbclient/NativeAPI.actor.cpp
fdbclient/include/fdbclient/CommitProxyInterface.h
fdbclient/include/fdbclient/CoordinationInterface.h
fdbclient/include/fdbclient/GrvProxyInterface.h
fdbclient/vexillographer/fdb.options
fdbserver/worker.actor.cpp
fdbserver/workloads/Cycle.actor.cpp
tests/CMakeLists.txt
tests/authorization/admin_server.py
tests/authorization/authz_test.py
tests/authorization/conftest.py

- Make public the private endpoints that are only used in multi-version client mode: `ProtocolInfoRequest` and `GlobalConfigRefreshRequest` RPC endpoints are affected.
- Make authz token option a persistent option that survives soft reset but not hard reset of transaction objects. Add matching tests to verify.
- Increase Authz test coverage to include forced multi-version client usage

Publish private endpoints used in MVC mode

---

fdbclient/include/fdbclient/StorageServerInterface.h

Add a default value for `minVersion` in `WaitMetricsRequest`. This is useful for callers that use the default `WaitMetricsRequest()` constructor and don't need to set `tenantInfo` and `minVersion`.

Add a default value for `minVersion` in `WaitMetricsRequest`

---

fdbclient/include/fdbclient/FDBTypes.h
fdbrpc/include/fdbrpc/simulator.h
fdbrpc/sim2.actor.cpp
fdbserver/DDTeamCollection.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/MoveKeys.actor.cpp
fdbserver/QuietDatabase.actor.cpp
fdbserver/include/fdbserver/DDTeamCollection.h
flow/include/flow/NetworkAddress.h

When remote DC is down, the remote team collection of DD can be initializing waiting for the remote to recover (all_tlog_recruited state). However, the getTeam request can already be served by the remote team collection. So, for a RelocateShard (data movement such as split, move), it will get a team for the remote DC. But the data movement can't make progress on the remote team because the remote DC hasn't recovered yet. Because of the stuck of data movement, the primary cannot reach the "storage_recovered" state and stay in accepting_commit state.
The specifc test failure: slow/ApiCorrectness.toml -s 339026305 -b on at commit: https://github.com/apple/foundationdb/commit/0edd899d653cbbf1f575feb17dc6e6675c90d41c
In this test with double replication, primary DC has 1 SS killed, remote DC …

Fix DD stuck when remote DC is dead

---

fdbclient/include/fdbclient/FDBTypes.h
fdbrpc/include/fdbrpc/simulator.h
fdbrpc/sim2.actor.cpp
fdbserver/DDTeamCollection.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/MoveKeys.actor.cpp
fdbserver/QuietDatabase.actor.cpp
fdbserver/include/fdbserver/DDTeamCollection.h
flow/include/flow/NetworkAddress.h

cherrypick #9338
When remote DC is down, the remote team collection of DD can be initializing waiting for the remote to recover (all_tlog_recruited state). However, the getTeam request can already be served by the remote team collection. So, for a RelocateShard (data movement such as split, move), it will get a team for the remote DC. But the data movement can't make progress on the remote team because the remote DC hasn't recovered yet. Because of the stuck of data movement, the primary cannot reach the "storage_recovered" state and stay in accepting_commit state.
The specifc test failure: slow/ApiCorrectness.toml -s 339026305 -b on at commit:  0edd899d65
In this test with double replication, primary DC has 1 SS killed, remote DC has 2 TLog and 2 SS killed. So the remote is dead, the …

Fix DD stuck when remote DC is dead [release-7.2]

---

tests/restarting/to_7.1.0_until_7.2.0/ConfigureStorageMigrationTestRestart-1.toml
tests/restarting/to_7.1.0_until_7.2.0/CycleTestRestart-1.toml
tests/restarting/to_7.2.0_until_7.3.0/ConfigureStorageMigrationTestRestart-1.toml
tests/restarting/to_7.2.0_until_7.3.0/CycleTestRestart-1.toml
tests/restarting/to_7.3.0/ConfigureStorageMigrationTestRestart-1.toml

Some downgrade tests were already disabling tenants, but I changed them to use a different parameter to disable them.

Disable tenants in downgrade tests to versions before 7.3

---

fdbserver/workloads/DiskFailureInjection.actor.cpp

The machine attrition logic doesn't take into account the possibility that a disk corruption could an unrecoverable failure in the cluster.
Before disabling attrition during the DiskFailure workload, the failure rate was >10/100,000 in the DiskFailureCycle test. Afterwards, there were no failures in 100,000 runs.

Disable machine attrition in DiskFailure workload.

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/VersionedBTree.actor.cpp

Introduced a new knob to control Redwood slack balance when splitting a page (Cherry-pick #9042 to snowflake/release-71.2)

---

fdbclient/BlobCipher.cpp
fdbclient/include/fdbclient/BlobCipher.h
fdbserver/workloads/EncryptionOps.actor.cpp

Description
Add helper methods to BlobCipherEncryptHeaderRef enabling:
1. Extract 'IV' abstracting out underlying algorithm header
1. Extract 'cipherDetails' abstracting out underlying algorithm header
Testing
BlobCipherUnitTest & EncryptionOps are updated - 100K loop

EaR: Helper routines to support configurable encryption

---

fdbserver/workloads/TenantManagementWorkload.actor.cpp

Fix 
`devRetryCorrectnessTest bin/fdbserver -r simulation -f tests/slow/TenantManagement.toml -s 1075250111 -b on --crash --trace_format json`
which has assertion failure
```
self->useMetacluster == (operationType == OperationType::METACLUSTER)
```
This is a workload bug when `beginTenant==endTenant` the tenants is empty, so the deleteTenant won't throw a exception we expecting.

fix anyExisted when beginTenant==endTenant

---

fdbserver/workloads/GetMappedRange.actor.cpp

The GetMappedRange workload was asserting that a range read returned the expected number of results, but it didn't account for the possibility that a range could return early due to hitting the end of a shard.

Fix get mapped range test assertion

---

fdbclient/include/fdbclient/BlobCipher.h

Remove duplicated isValid() method.

EaR: fix BlobCipher.h build failure

---

fdbserver/SimulatedCluster.actor.cpp
fdbserver/fdbserver.actor.cpp
fdbserver/workloads/SaveAndKill.actor.cpp
tests/fast/BlobGranuleMoveVerifyCycle.toml
tests/fast/BlobGranuleVerifyAtomicOps.toml
tests/fast/BlobGranuleVerifyCycle.toml
tests/fast/BlobGranuleVerifySmall.toml
tests/fast/BlobGranuleVerifySmallClean.toml
tests/rare/BlobGranuleRanges.toml
tests/restarting/to_7.1.0_until_7.2.0/ConfigureStorageMigrationTestRestart-1.toml
tests/restarting/to_7.1.0_until_7.2.0/CycleTestRestart-1.toml
tests/restarting/to_7.2.0_until_7.3.0/ConfigureStorageMigrationTestRestart-1.toml
tests/restarting/to_7.2.0_until_7.3.0/CycleTestRestart-1.toml
tests/restarting/to_7.3.0/ConfigureStorageMigrationTestRestart-1.toml
tests/restarting/to_7.3.0/CycleTestRestart-1.toml
tests/slow/BlobGranuleCorrectness.toml
tests/slow/BlobGranuleCorrectnessClean.toml
tests/slow/BlobGranuleVerifyBalance.toml
tests/slow/BlobGranuleVerifyBalanceClean.toml
tests/slow/BlobGranuleVerifyLarge.toml
tests/slow/BlobGranuleVerifyLargeClean.toml

Disable sharded rocks storage for downgrade tests where we need to keep knob "shard_encode_location_metadata" so that downgrade tests can pass the second phase.
If sharded rocks is used in part 1, then `shard_encode_location_metadata` has to be set in part-2.
20230214-040949-jzhou-b418b49ed351b9e7
```
-f tests/fast/AtomicBackupCorrectness.toml -s 656346199 -b on
-f tests/fast/FuzzApiCorrectnessClean.toml -s 2066162177 -b on
```
20230214-183911-jzhou-ad9829c30fc9d965 restarting tests only
```
-f tests/restarting/from_7.2.0/DrUpgradeRestart-1.toml -s 2771988862 -b on
-f tests/restarting/from_7.2.0/DrUpgradeRestart-2.toml --restarting -s 2771988863 -b on (OOM)
```
20230214-213555-jzhou-f3198b8626f11838 …

Enable RocksDB restarting tests

---

fdbserver/workloads/DiskFailureInjection.actor.cpp
fdbserver/workloads/TenantManagementWorkload.actor.cpp

cherrypick correctness fixes [release-7.2]

---

fdbserver/BlobManifest.actor.cpp

A few caller for BackupContainerFileSystem need to be adjusted for S3. The implementation for local directory and S3 are not consistent.
Tested ok with 100K BlobRestoreCorrectness tests

Fix manifest file list issue on s3

---

fdbclient/Metacluster.cpp
fdbclient/include/fdbclient/Metacluster.h
fdbclient/include/fdbclient/MetaclusterManagement.actor.h
flow/include/flow/error_definitions.h
flow/include/flow/genericactors.actor.h

Store restore IDs in the metacluster metadata that are used to prevent the transactions being run in a restore from succeeding unless they are associated with the most recent restore for that cluster.

Prevent the same cluster from being restored concurrently

---

fdbserver/QuietDatabase.actor.cpp
fdbserver/workloads/SkewedReadWrite.actor.cpp

cherrypick #9388 #9274
If primary is excluded, the recovery will become stuck because no servers can be recruited in the next time, i.e., stuck in the `recruiting_transaction_servers` state.
20230215-181043-jzhou-04396677dee49560

Fix exclusion in repairDeadDatacenter to be remote only [release-7.2]

---

fdbserver/tester.actor.cpp
tests/fast/AuthzSecurity.toml
tests/fast/GetEstimatedRangeSize.toml
tests/fast/RawTenantAccessClean.toml
tests/fast/TenantCycle.toml
tests/fast/TenantCycleTokenless.toml
tests/rare/StorageQuotaTest.toml

This allows the clear database check that reads the entire database to complete without having to scan a lot of shards

When clearing the database after a test, delete all tenants except the default tenant

---

fdbserver/QuietDatabase.actor.cpp

If primary is excluded, the recovery will become stuck because no servers can be recruited in the next time, i.e., stuck in the `recruiting_transaction_servers` state.
Testing done in #9385

Fix exclusion in repairDeadDatacenter to be remote only

---

bindings/c/fdb_c.cpp
bindings/c/test/apitester/TesterBlobGranuleCorrectnessWorkload.cpp
bindings/c/test/fdb_api.hpp
fdbclient/BlobGranuleFiles.cpp
fdbclient/include/fdbclient/BlobGranuleCommon.h
fdbserver/BlobGranuleServerCommon.actor.cpp
fdbserver/BlobWorker.actor.cpp

Addressing fixme in new blob granule files client and native code.
Passes 1k BlobGranule* correctness, 10k /blobgranule/files unit tests, and the client api tests.

adding version metadata to blob granule file pointers

---

fdbserver/VersionedBTree.actor.cpp

This matches the behavior of other storage engines, in particular it matches SQLite's definition of 'used' exactly.

Update StorageBytes::used reported by Redwood to be the physical file size

---

bindings/c/fdb_c.cpp
bindings/c/foundationdb/fdb_c.h
bindings/c/test/apitester/TesterApiWorkload.cpp
bindings/c/test/apitester/TesterApiWorkload.h
bindings/c/test/apitester/TesterBlobGranuleErrorsWorkload.cpp
bindings/c/test/fdb_api.hpp
bindings/c/test/mako/admin_server.cpp
bindings/java/fdbJNI.cpp
bindings/java/src/integration/com/apple/foundationdb/BlobGranuleIntegrationTest.java
bindings/java/src/main/com/apple/foundationdb/Database.java
bindings/java/src/main/com/apple/foundationdb/FDBDatabase.java
bindings/java/src/main/com/apple/foundationdb/FDBTenant.java
bindings/java/src/main/com/apple/foundationdb/Tenant.java
fdbclient/MultiVersionTransaction.actor.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/ThreadSafeTransaction.cpp
fdbclient/include/fdbclient/DatabaseContext.h
fdbclient/include/fdbclient/IClientApi.h
fdbclient/include/fdbclient/MultiVersionTransaction.h
fdbclient/include/fdbclient/ThreadSafeTransaction.h
fdbserver/workloads/BlobGranuleCorrectnessWorkload.actor.cpp
fdbserver/workloads/BlobGranuleRangesWorkload.actor.cpp
fdbserver/workloads/BlobGranuleVerifier.actor.cpp

Adding wait parameter to blobbify api, via the method of adding a new function type for this release and deprecating the old one in the next release.
The API just wraps the previous behavior a user would have to do of calling blobbify and then verify in a loop until success, but this can be improved transparently to the user in the future.
Passes 1k BlobGranule* correctness, 1k BlobGranuleRange* correctness, the api tester BlobGranule* tests, and the java integration test.

adding wait parameter to blobbify api

---

fdbserver/storageserver.actor.cpp

Assert that storage server is reading `tenantMap` at a legal version in `checkTenantEntry()` to prevent undefined behavior when reading from the map.

Assert that `checkTenantEntry()` on storage server is reading tenantMap at a legal version

---

fdbclient/ServerKnobs.cpp

Rocksdb knob changes.
cherry-pick of #9389

Rocksdb knob changes.

---

fdbclient/BlobGranuleFiles.cpp

Cherry-pick #9059
I think ubsan tests had been broken on the release-71.2 nightlies, since this fix was made in december on main and only now showed up on the release branch.

[snowflake/release-71.2] Fix BlobGranuleCorrectness.toml undefined behavior in mergeDeltaStreams

---

CMakeLists.txt

Adding support to pass custom fdb_build timestamp, required to achieve uniform naming across different builds.
Motivation :
---
Release Team is running into issue with fdb prerelease packaging. The naming for a specific version isn't consistent between CPU architectures i.e. the daily builds are named slightly differently on arm vs x86 because the timestamp portion differs.
So in order to make timestamp portion uniform adding support to pass  `FDB_BUILDTIME` as string parameter to cmake.
It can be passed as for example `-DFDB_BUILDTIME=202302345678`
**Note**: Default existing behavior will not change. 
Testing
---
* Tested with default behavior without passing any external `-DFDB_BUILDTIME` parameter
* Tested with passing `-DFDB_BUILDTIME=202302345678` as external arguments to Cmake.
The …

Adding support to pass custom fdb_build timestamp, required to achieve uniform naming across different builds

---

fdbclient/include/fdbclient/MetaclusterManagement.actor.h
fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp

A few fixes to restore IDs found by @sfc-gh-jfu and fixed in a larger PR. I'm extracting them here so they can merge sooner.
1. we weren't generating a restore ID
2. we weren't storing the restore ID on the management cluster in some restore modes
3. it is possible in some test scenarios to encounter a restore conflict, in which case we need to retry

Fixes to metacluster restore ID

---

fdbserver/tester.actor.cpp

The tenant deletion at the end of simulated tests is done in batches, but we weren't reseting the transaction between batches.
This was discovered and fixed by @sfc-gh-jfu in a larger PR, and I've extracted it so we can get it merged faster.

When clearing tenants at the end of a simulation test, reset the transaction when looping

---

bindings/bindingtester/tests/api.py
bindings/bindingtester/tests/test_util.py

Fixing generation of the bindingtester API tests, so that deterministic for the given random seed:
- Fix determinism of tenant selection
- Generate deterministic UUIDs
The relevant python files are reformatted in a separate commit

Fix determinism in the generated bindingtester API tests

---

fdbserver/storageserver.actor.cpp

There are two main fixes here.
- Don't explicitly require new mutation versions to arrive to start a commit if the FetchKeys budget is already used, but do yield the CPU so that if any new mutations have arrived they will be processed.
- After applying the mutation batch in the current commit, increase the FetchKeys budget by any remaining mutation bytes budget so it can do more work.
Also reduced two yields and combined the set / byteSample update loops for better memory locality when processing an incoming data batch. …

Allow FetchKeys to do more work in an idle or low load cluster.

---

flow/Arena.cpp

UBSAN build fails the existing test, not just ASAN.
Disable `/flow/Arena/Secure` unit test for all sanitizer builds.

Disable client memory wipe test for all XSAN builds

---

fdbserver/BlobManager.actor.cpp
fdbserver/BlobManifest.actor.cpp
fdbserver/include/fdbserver/BlobGranuleServerCommon.actor.h

Add stats counters for manifest size, last seq no, truncation version and flush version. 

Add stats counters for manifest dump

---

contrib/TestHarness2/test_harness/summarize.py

Successful and non-crashing tests will print a `RealTime` field in the joshua output. However, if a test crashes (or failes and `--crash` is passed), this field will be missing since it is produced by FDB and not TestHarness.
This PR introduces a change so that we will always at least see the real runtime as observed by test harness (this will usually be a few ms longer than `RealTime`). Test output looks like this:
```
"devRetryCorrectnessTest bin/fdbserver -r simulation -f tests/fast/ConfigureLocked.toml -s 3577692748 -b on --crash --trace_format json": {
"Type": "Test",
"Command": "devRetryCorrectnessTest bin/fdbserver -r simulation -f tests/fast/ConfigureLocked.toml -s 3577692748 -b on --crash --trace_format json",
"TestUID": "3858507f-7c12-4ccf-b65d-c31a06e9218b",
"Statistics": …
```

Add Runtime measured by TestHarness

---

fdbserver/Ratekeeper.actor.cpp
fdbserver/include/fdbserver/Ratekeeper.h

Passes 10k BlobGranule* correctness, and confirmed with local testing that ratekeeper does nothing if blob_granules_enabled=1 but there are no blob workers.

No RK throttling on blob workers if no blob ranges

---

fdbclient/include/fdbclient/BlobWorkerCommon.h
fdbserver/BlobWorker.actor.cpp

[snowflake-release-71.2] Fixing several metrics issues in blob workers

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/VersionedBTree.actor.cpp

The existing logic was not forcing a rebuild of BTree nodes based on binary tree height imbalance.  It would rebuild any leaf node for every update once its height reaches 8, which in practice would allow an imbalance of up to 7 levels and then rebuild the node because a balanced height of 8 is very hard to reach within a leaf node (it would require tiny values and very compressible keys).
A new knob is introduced which controls the maximum height imbalance allowed in a BTree node, and its default value of 2 was chosen experimentally using `mako` across a variety of read-only and read-write workloads on a cached data set. …

Optimize/fix node rebuild vs update trigger in Redwood

---

bindings/java/src/integration/com/apple/foundationdb/BlobGranuleIntegrationTest.java
fdbclient/NativeAPI.actor.cpp

Now testing equivalent tenant versions of the blob management functions.
This found a bug where in granule purge, the tenant prefix wasn't being included in the purge range, causing it to purge an incorrect range.
Passes the new java test and 10k BlobGranule* correctness tests.

adding java tenant blob management test and fixing bug it found

---

bindings/java/src/integration/com/apple/foundationdb/GetClientStatusIntegrationTest.java

Java GetClientStatusIntegrationTest was sporadically failing. The test was assuming that the database connection is fully initialized after executing a simple transaction, so the getClientStatus should report that the connection is in a healthy state. 
However, the transaction implementation was missing a wait on the future, so it sometimes happened that the getClientStatus was called on not yet initialized connection.

Fix Java GetClientStatusIntegrationTest

---

fdbclient/include/fdbclient/BlobWorkerCommon.h
fdbserver/BlobWorker.actor.cpp

Fixes
- incorrect bytes buffered int type (causes negative metrics)
- counter "leaks" buffered bytes if granule is revoked/cancelled
- counter "leaks" active requests if tenant error or cancelled
Passed 20k BlobGranule* correctness with an unrelated error.

Fixing several metrics issues in blob workers

---

fdbcli/MetaclusterCommands.actor.cpp
fdbclient/Metacluster.cpp
fdbclient/include/fdbclient/MetaclusterManagement.actor.h
fdbserver/include/fdbserver/workloads/MetaclusterConsistency.actor.h
fdbserver/include/fdbserver/workloads/MetaclusterData.actor.h
fdbserver/workloads/MetaclusterManagementConcurrencyWorkload.actor.cpp
fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp
fdbserver/workloads/MetaclusterRestoreWorkload.actor.cpp

A set of fixes and improvements to metacluster restore.
1. Add a boolean parameter for `ForceRemove` and rename `ForceJoinNewMetacluster` to `ForceJoin` to account for other uses cases of `ForceJoin`.
2. Some updates to tenant and metacluster consistency checks to account for tenant counts during renames
3. Prevent operations on clusters that are restoring
4. Properly fail certain cases where it is illegal to restore a cluster
5. Check for registration tombstones when restoring a cluster
6. Attempt to roll back a cluster register operation if the attempt to update the data cluster fails …

Metacluster restore fixes

---

contrib/TestHarness2/test_harness/summarize.py

In order to cluster test failures more efficiently having the `configure` string is often useful. This is a simple change and will include the configure string.
Sample output:
```
"devRetryCorrectnessTest bin/fdbserver -r simulation -f tests/fast/ConfigIncrementWithKills.toml -s 2859554869 -b on --crash --trace_format json": {
"Type": "Test",
"Command": "devRetryCorrectnessTest bin/fdbserver -r simulation -f tests/fast/ConfigIncrementWithKills.toml -s 2859554869 -b on --crash --trace_format json",
"TestUID": "882c527a-1dce-4b0c-89da-d82334f21e37",
"Statistics": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA …
```

Include configure string in test harness output

---

fdbclient/include/fdbclient/Tenant.h
fdbserver/ApplyMetadataMutation.cpp

We don't need all of the tenant fields to be stored in the txn state store for use on the CP and SS, so store a subset containing only the needed fields.

Store a smaller tenant object in the txn state store

---

fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp

This adds support for force removal of clusters and repopulating a management cluster in the metacluster managament workload.

Improve restore support in the metacluster management workload

---

fdbclient/ServerKnobs.cpp
fdbserver/BlobMigrator.actor.cpp

Implement splitmetrics pagination api for blob migrator to avoid large response for blob restore. 
Passed 100K BlobRestore correctness tests for

Implement SplitMetric pagination in blob migrator

---

fdbclient/CMakeLists.txt

As of today the awssdk doesn't work on ARM so the intend was to have this disabled. But the code that was supposed to do that is wrong
Cherry-pick of #9463

Fix build issue with awssdk_target

---

fdbserver/Resolver.actor.cpp
fdbserver/TLogServer.actor.cpp
fdbserver/include/fdbserver/ResolverInterface.h
fdbserver/include/fdbserver/TLogInterface.h

Add some missing metrics to help better understand time spent during commit.
There are already pretty good metrics on the commit proxy, so this set focuses on the resolver and tlog.
* server-side RPC latency metrics for resolver and tlog.
* breakdown of time spent waiting and computing on the resolver, per-request.
* queue depth observed on the resolver.
I've decided to use Histogram over LatencySample, because Histogram is implemented as
32, power-of-2 buckets, while LatencySample is a couple thousand buckets at the default
accuracy of 1% for percentiles. I'd rather have the lower memory footprint plus the full
distribution into buckets, over accurate percentiles for 5 second intervals.
The last one is a proxy for a short-lived backlog on the resolver. Hopefully, that metric plus
time …

Sfc gh dadkins/resolver metrics

---

fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp

A test workload was erasing an iterator from a map and then trying to use it

Fix memory error from using invalidated iterator

---

fdbcli/MetaclusterCommands.actor.cpp
fdbcli/tests/metacluster_fdbcli_tests.py
fdbclient/include/fdbclient/MetaclusterManagement.actor.h
fdbserver/workloads/MetaclusterManagementConcurrencyWorkload.actor.cpp
fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp
fdbserver/workloads/MetaclusterRestoreWorkload.actor.cpp
fdbserver/workloads/TenantCapacityLimits.actor.cpp
fdbserver/workloads/TenantManagementConcurrencyWorkload.actor.cpp
fdbserver/workloads/TenantManagementWorkload.actor.cpp

Enforces that when a metacluster is created the tenant mode for it is disabled. This check is currently disabled in simulation due to needing to refactor alot of workloads but this work will need to be done soon in a followup PR.

Enforce Disabled Tenant Mode in Metacluster

---

fdbcli/TenantCommands.actor.cpp
fdbcli/tests/fdbcli_tests.py
fdbclient/Metacluster.cpp
fdbclient/include/fdbclient/MetaclusterManagement.actor.h
fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp
fdbserver/workloads/MetaclusterRestoreWorkload.actor.cpp
fdbserver/workloads/TenantManagementConcurrencyWorkload.actor.cpp
fdbserver/workloads/TenantManagementWorkload.actor.cpp

This can be used to temporarily move a tenant out of a tenant group prior to moving it to another cluster. Without this option, we would have to temporarily raise the capacity limit of a cluster and then risk the possibility that another group takes the extra allocation.

Add an option to allow exceeding the tenant group capacity limit when changing tenant configuration

---

fdbclient/include/fdbclient/FDBTypes.h
flow/Arena.cpp
flow/Error.cpp
flow/include/flow/Error.h
flow/include/flow/FastRef.h
flow/include/flow/IRandom.h
flow/include/flow/Trace.h
flow/include/flow/Traceable.h

This updates `ASSERT_EQ`, etc., to work with any type that is traceable and supports the target comparison operator.

Allow performing assert comparisons with any traceable type

---

tests/fast/TenantEntryCache.toml

This fixes an issue similar to https://github.com/apple/foundationdb/pull/9296.

Don't clear after `TenantEntryCacheTest`

---

fdbbackup/backup.actor.cpp
fdbclient/BackupContainerFileSystem.actor.cpp
fdbclient/include/fdbclient/BackupContainer.h
fdbclient/include/fdbclient/FDBTypes.h

- Previously, it always uses the closest snapshot from the restore version. Now, it can uses --query-restore-snapshot-version to set which snapshot version to use. It will pick the latest snapshot version prior to that version.
- Also fix --query-restore-version == -2, which doesn't produce minimum restore version (rather, it produces just the latest snapshot).
- Introduce `earliestVersion` constant.

Enhance fdbbackup query command to estimate data processing from a specific snapshot to a target version

---

bindings/c/test/unit/third_party/CMakeLists.txt
bindings/go/go.mod
bindings/go/src/fdb/database.go
bindings/java/CMakeLists.txt
cmake/CompileBoost.cmake
cmake/Jemalloc.cmake
fdbcli/FlowLineNoise.actor.cpp
fdbclient/AutoPublicAddress.cpp
fdbrpc/Net2FileSystem.cpp
fdbrpc/SimExternalConnection.actor.cpp
fdbrpc/sim2.actor.cpp
fdbserver/FDBExecHelper.actor.cpp
flow/IThreadPool.cpp
flow/Net2.actor.cpp
flowbench/CMakeLists.txt
flowbench/benchmark.cmake
tests/CMakeLists.txt

This PR makes it possible for FDB to use a pre-build version of googlebenchmark.  The pre-built version is not included in the FDB build image yet.

Add support for pre-built googlebenchmark

---

fdbserver/workloads/ClogTlog.actor.cpp
tests/CMakeLists.txt

Found by ASAN. I've verified this fix the bug.

Fix a memory bug in ClogTlog workload

---

fdbclient/include/fdbclient/MetaclusterManagement.actor.h
fdbserver/include/fdbserver/workloads/MetaclusterConsistency.actor.h
fdbserver/include/fdbserver/workloads/MetaclusterData.actor.h
fdbserver/workloads/MetaclusterManagementConcurrencyWorkload.actor.cpp
fdbserver/workloads/TenantManagementConcurrencyWorkload.actor.cpp

This adds the restore operation to the metacluster management concurrency workload and fixes various bugs that it found.

Add restore to the metacluster management concurrency workload

---

fdbbackup/backup.actor.cpp
fdbclient/BackupContainerFileSystem.actor.cpp
fdbclient/include/fdbclient/BackupContainer.h
fdbclient/include/fdbclient/FDBTypes.h

[Release 7.2] Enhance fdbbackup query command to estimate data processing from a specific snapshot to a target version

---

fdbclient/VersionedMap.h
fdbclient/WriteMap.h

Cherry-pick https://github.com/apple/foundationdb/pull/9138 and https://github.com/apple/foundationdb/pull/9143
20230227-225532-jzhou-093d77d69fe2d344

PTree improvements [release-7.1]

---

fdbcli/TenantCommands.actor.cpp
fdbcli/tests/fdbcli_tests.py
fdbclient/Metacluster.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/Tenant.cpp
fdbclient/include/fdbclient/Metacluster.h
fdbclient/include/fdbclient/MetaclusterManagement.actor.h
fdbclient/include/fdbclient/Tenant.h
fdbclient/include/fdbclient/TenantManagement.actor.h
fdbserver/include/fdbserver/workloads/MetaclusterConsistency.actor.h
fdbserver/include/fdbserver/workloads/TenantConsistency.actor.h
fdbserver/workloads/TenantLock.actor.cpp
fdbserver/workloads/TenantManagementConcurrencyWorkload.actor.cpp
fdbserver/workloads/TenantManagementWorkload.actor.cpp

Adds support at the metacluster level for tenant locking. Also adds some tenant lock testing to a couple tenant workloads.

Metacluster tenant lock support

---

contrib/mockkms/CMakeLists.txt
fdbclient/include/fdbclient/Tenant.h
fdbserver/KeyValueStoreShardedRocksDB.actor.cpp

The lock id doesn't have to be stored in the txnStateStore, this PR removes that.

Don't store lockid in txnStateStore

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/CommitProxyServer.actor.cpp
fdbserver/include/fdbserver/ProxyCommitData.actor.h

The commit proxy writes a `ProxyMetrics` trace every 5 seconds. This event contains a lot of useful information, such as the number of commit batches that arrived and exited, the number of mutations processed, the number of bytes those mutations made up, etc.. However, it is difficult to tell what the workload pattern looks like within these 5 second intervals when the metrics are being calculated.
This PR adds a new trace, `ProxyDetailedMetrics`, which logs itself every 100ms. It currently only writes the number of mutations and the number of mutation bytes that arrived during the 100ms time period. But it should be easy to add more metrics in the future.
It's possible this increased logging could cause issues. Based off a simulation run of the `WriteDuringRead` test, I got the following …

Adds more detailed mutation logging to commit proxy

---

fdbserver/SimKmsConnector.actor.cpp

Follow-up from discussion on #9500
Passes 1k BlobGranuleCorrectness* correctness.

adding simulation check guard

---

tests/TestRunner/local_cluster.py

- Added knobs to decrease granule size/increase granule count
- Refactored blob granule and encryption config to be simpler
- A couple unrelated changes from flake/black

decreasing granule size knobs to enable more granules in local cluster tests

---

fdbclient/include/fdbclient/TagThrottle.actor.h

Subroutine of getter actor function for throttled and recommended tags
was, upon retry, resetting the transaction object which the caller also uses,
resetting the transaction option and causing a key_outside_legal_range by caller
Also, allowing a subroutine to conditionally, non-trivially modify the passed object
(i.e. transaction reset) is a risky pattern.
Fix: confine subroutine's responsibility to "attempting to" fetch and parse "autoThrottlingEnabled" key. Let the calling function reset the object if needed. …

Fix transaction option consistency in TagThrottleInfo getter

---

flow/Arena.cpp

Corner cases where newBuf == buf assertion fails have been observed in Valgrind runs

Disable ArenaBlock wipe test for Valgrind

---

fdbserver/BlobManager.actor.cpp
tests/TestRunner/upgrade_test.py

It appears my more granules change #9432 + evan's stateful blob worker change #9347 change caused the blob granules upgrade test to time out on the progress check more frequently.
black autoformatted the python file again, the only change i made is bumping the timeout from 30 to 60 seconds
I found one cause of increased time, but there appears to be something else. I'll investigate, but in the meantime, bumping the timeout fixes the failure rate.

Bg ctest fixes

---

fdbserver/Resolver.actor.cpp
fdbserver/TLogServer.actor.cpp
fdbserver/include/fdbserver/ResolverInterface.h
fdbserver/include/fdbserver/TLogInterface.h

* Add server-side latency metrics for Resolver requests.
* Add separate resolver latency metrics for queue wait and compute time.
* Add histogram for queue depth observed on resolver (during metrics interval).
* Fix tlog latency measurement to use timer() instead of now().

Add metrics to understand tail commit latency (cherry-pick #9435 to snowflake/release-71.2)

---

fdbbackup/FileDecoder.actor.cpp
fdbclient/BackupContainer.h
fdbclient/FileBackupAgent.actor.cpp

Use KeyspaceSnapshotFile to filter range files

---

fdbserver/BlobManager.actor.cpp
fdbserver/BlobMigrator.actor.cpp

deepScan is needed to get up-to-date ContiguousLogEndVersion during blob restore. Otherwise it's far below manifest version and blob restore may fail sometimes. 
100K blob restore test passed

BlobRestore - add deepScan option when describing backup

---

fdbclient/include/fdbclient/MetaclusterManagement.actor.h
fdbserver/include/fdbserver/workloads/MetaclusterData.actor.h
fdbserver/include/fdbserver/workloads/TenantData.actor.h
fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp
tests/slow/MetaclusterRecovery.toml

1. When retrying the transaction to register a restoring cluster, don't choose a new ID if the current ID matches the one already recorded for the restoring cluster 
2. Fix a couple test issues where we were incorrectly handling the case where a transaction was retried with unknown result
3. An assertion could be triggered during a concurrent metacluster restore if a tenant was being renamed. The anomalous condition would only arise if the transaction was already going to be failed anyway
4. Change some test parameters to try to avoid rare occurrences of a test tracing too many lines …

Fix some metacluster issues

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbclient/include/fdbclient/StorageServerInterface.h
fdbserver/DDShardTracker.actor.cpp
fdbserver/StorageMetrics.actor.cpp
fdbserver/include/fdbserver/StorageMetrics.actor.h

* add read ops sampler and corresponding knobs
* replace the old `getReadHotRanges` implementation to achieve the following syntax:
```
fdbcli > hotrange <IP:PORT> <bytes|readBytes|readOps> <begin> <end> <splitCount> 
// This will send a request to a storage server and ask it to return <splitCount> ranges. The <bytes|readBytes|readOps> of each range is about equal to “Sum[bytes|readBytes|ReadOps][begin…end) / splitCount”.
```
In this way, we can locate a hot range in a binary search manner (by progressively refining the key range given to the function and/or modifying the number of splits requested).
- begin, end
- bytes
- readBytesSec
- readOpsSec
Please check …

Hot range detection improvement

---

fdbserver/TLogServer.actor.cpp
fdbserver/include/fdbserver/TLogInterface.h

* Add metric for queue wait time in tlog.
* Add metric for tlog commit time minus time spent waiting in the queue.

Add metrics to tlog to understand tail commit latency (cherry-pick #9480 to snowflake/release-71.2)

---

fdbclient/BlobGranuleFiles.cpp

Cherry-pick #9205 to fix a nightly ubsan failure

[snowflake/release-71.2] Set VLA minimum length to 1

---

fdbserver/BlobManager.actor.cpp
fdbserver/storageserver.actor.cpp

With these bug fixes, the only failures in the 250k BlobGranule* tests run are not related to blob granules.
The fixes are separated by commit, and are all very safe fixes, as all bugs were erroneously triggering an assert, and the fixes only consist of not triggering the assert.

More bg correctness fixes

---

tests/fast/RandomUnitTests.toml
tests/noSim/RandomUnitTests.toml
tests/rare/SpecificUnitTests.toml

This is a cherry pick of #9532. This resolves the RocksDB related unit test failures showing up in CI.

Disable empty range check in unit tests [snowflake/release-71.3]

---

fdbserver/Resolver.actor.cpp
fdbserver/TLogServer.actor.cpp
flow/include/flow/Histogram.h

cherry-pick #9546
The conversion from double -> uint32_t in sampleSeconds is potentially undefined behavior for very large or negative values. We safely clamp the value to [0, UINT32_MAX] before converting to integer.
Note: negative values are possible here, because timers can go backwards. That case should be clamped to zero rather than underflowing.
This problem was discovered because we were mixing g_network->timer() and timer(). Normally, these are the same and comparable. In simulation, they are not and subtracting them led to the undefined behavior above. These sites are now fixed. …

Fix overflow/underflow in Histogram.sampleSeconds (cherry-pick #9546 to snowflake/release-71.3)

---

fdbserver/Resolver.actor.cpp
fdbserver/TLogServer.actor.cpp
flow/include/flow/Histogram.h

The conversion from double -> uint32_t in sampleSeconds is potentially
undefined behavior for very large or negative values. We safely clamp
the value to [0, UINT32_MAX] before converting to integer.
Note: negative values are possible here, because timers can go backwards.
That case should be clamped to zero rather than underflowing.
This problem was discovered because we were mixing g_network->timer() and
timer(). Normally, these are the same and comparable. In simulation, they
are not and subtracting them led to the undefined behavior above. These
sites are now fixed.
If …

Fix overflow/underflow in Histogram.sampleSeconds.

---

fdbserver/CommitProxyServer.actor.cpp
fdbserver/workloads/SpecialKeySpaceRobustness.actor.cpp

This is a cherry-pick of #9523 
This allows us to report the appropriate non-retryable error instead.

Check transaction validity with respect to tenants even if it will fail with a conflict [snowflake/release-71.3]

---

bindings/c/symbolify.py

Apple builds use symbolify.py to extract the exported symbols from C API headers. After a recent change to the headers, the pattern matching have taken some wrong strings. This PR improves the pattern matching to avoid these false positives.

Fix exported symbol extraction in Apple builds

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/DDRelocationQueue.actor.cpp

This won't bring a behavior change unless the knob becomes lower than the average load.

add knob for min read rebalance shard bandwidth

---

fdbserver/workloads/UnitTests.actor.cpp
flow/ActorCollection.actor.cpp

[snowflake/release-71.2] Rewrote ActorCollection to be O(1) instead of O(log n) for actor add and completion

---

bindings/c/symbolify.py
flowbench/CMakeLists.txt

Cherry-picking recent fixes of Linux and Apple builds from main: #9569 and #9562 

Fixing Linux and Apple builds (cherry-pick #9569 and #9562 to snowflake/release-71.3) 

---

cmake/ConfigureCompiler.cmake

Building with -ggdb1 by default to reduce the size of debug symbols, so that we can use binaries with debug symbols in our deployments.

[snowflake/release-71.2] Build with minimal debug symbols by default

---

fdbserver/DataDistribution.actor.cpp
fdbserver/workloads/ValidateStorage.actor.cpp

Problem: auditStorage and resumeAuditStorage can interleave with each other. As a result, resumeAuditStorage can pollute the state updated by auditStorage. 
Solution: 
1. A resumeAuditStorage should not overwrite any ongoing auditStorage triggered before the resumeAuditStorage;
2. Any auditStorage triggered after a resumeAuditStorage must wait for the completion of resumeAuditStorage;
3. Initialization of DD does not wait on resumeAuditStorage.
20230303-052121-zhewang-673d52218c893684           compressed=True data_size=47433527 duration=4095010 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:00:57 sanity=False started=100000 stopped=20230303-062218 submitted=20230303-052121 timeout=5400 username=zhewang
The general pull request guidelines can be …

Fix race between auditStorage and resumeAuditStorage

---

fdbclient/include/fdbclient/MetaclusterManagement.actor.h
fdbserver/include/fdbserver/workloads/MetaclusterData.actor.h
fdbserver/include/fdbserver/workloads/TenantData.actor.h
fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp
tests/slow/MetaclusterRecovery.toml

This is a cherry-pick of #9521 
1. When retrying the transaction to register a restoring cluster, don't choose a new ID if the current ID matches the one already recorded for the restoring cluster 
2. Fix a couple test issues where we were incorrectly handling the case where a transaction was retried with unknown result
3. An assertion could be triggered during a concurrent metacluster restore if a tenant was being renamed. The anomalous condition would only arise if the transaction was already going to be failed anyway
4. Change some test parameters to try to avoid rare occurrences of a test tracing too many lines …

Fix some metacluster issues [snowflake/release-71.3]

---

fdbcli/tests/fdbcli_tests.py

20 seconds look long enough,
but I will remove this to see if the `coordinators` change is just slow or bring the cluster down.

Remove the time guard on fdbcli commands in tests

---

fdbclient/include/fdbclient/MetaclusterManagement.actor.h

Print the tenant mode string rather than integer value when reporting that we couldn't create a metacluster. Example new output:
```
ERROR: cluster is configured with tenant mode `required_experimental' when tenants should be disabled.
```

Fix metacluster create error message

---

fdbcli/StatusCommand.actor.cpp
fdbclient/include/fdbclient/BlobGranuleCommon.h
fdbserver/BlobManager.actor.cpp
fdbserver/BlobManifest.actor.cpp
fdbserver/BlobMigrator.actor.cpp
fdbserver/ClusterController.actor.cpp
fdbserver/Status.actor.cpp
fdbserver/include/fdbserver/BlobGranuleServerCommon.actor.h
fdbserver/workloads/BlobRestoreWorkload.actor.cpp

This PR is mostly fdbcli changes. It shows when we start each phase of restore, so that we can record the time easier for perf testing. 
Some examples:
```
Blob Granules:
Number of Workers      - 2
Number of Key Ranges   - 258
Full Restore           - Completed at 03/03/23 18:02:53. Total 4 minutes used
```
```
Blob Granules:
Number of Workers      - 2
Number of Key Ranges   - 258
Full Restore           - Copying data 30%. Started at 17:58. ETA about one minute
```
```
Blob Granules:
Number of Workers      - 2
Number of Key Ranges   - 258
Full Restore           - Aborted with fatal error at 03/03/23 17:39:53: migrator failure on 127.0.0.1:4100
```
Please check …

Report restore phase start time and eta

---

fdbcli/tests/fdbcli_tests.py

Cherry-pick #9533, making the CI less noisy.

Cherry-pick#9533, remove the time guard on fdbcli commands in tests

---

fdbbackup/FileDecoder.actor.cpp
fdbclient/BackupAgent.actor.h
fdbclient/FileBackupAgent.actor.cpp

cherrypick part of #9505
To reduce the number of network requests. The network saving reduces 30~50% time.
20230303-171733-jzhou-944d463f9681e635

Refactor decoder to read file as a whole once

---

fdbclient/include/fdbclient/MetaclusterManagement.actor.h

Cherry-pick #9584 
Print the tenant mode string rather than integer value when reporting that we couldn't create a metacluster. Example new output:
```
ERROR: cluster is configured with tenant mode `required_experimental' when tenants should be disabled.
```

Fix metacluster create error msg (snowflake/release-71.3)

---

fdbserver/DataDistribution.actor.cpp
fdbserver/workloads/ValidateStorage.actor.cpp

Cherry picks https://github.com/apple/foundationdb/pull/9555
Problem: auditStorage and resumeAuditStorage can interleave with each other. As a result, resumeAuditStorage can pollute the state updated by auditStorage.
Solution:
A resumeAuditStorage should not overwrite any ongoing auditStorage triggered before the resumeAuditStorage;
Any auditStorage triggered after a resumeAuditStorage must wait for the completion of resumeAuditStorage;
Initialization of DD does not wait on resumeAuditStorage.

Fix race between auditStorage and resumeAuditStorage (snowflake/release-71.3)

---

bindings/ruby/lib/fdbimpl.rb

PR from [Andrew Hayworth](https://forums.foundationdb.org/u/ahayworth)
While fixing the gem build, I noticed that the gem will not run on arm64 machines, like the new spiffy M1/M2 MacBooks. On a whim, I tried just removing that restriction... and it does seem to work:
```
foundationdb/bindings/ruby/lib on  ahayworth/fix-ruby-binding-build [?] via 💎 v3.2.1 took 2s
zsh ❯ pry
[1] pry(main)> require 'fdb'
=> true
[2] pry(main)> FDB.api_version 720
LoadError: FoundationDB API only supported on x86_64 (not arm64)
from /Users/andrew/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/fdb-7.3.0/lib/fdbimpl.rb:40:in `<module:FDBC>'
[3] pry(main)>
``` …

Allow ruby bindings on arm64

---

bindings/ruby/CMakeLists.txt
bindings/ruby/fdb.gemspec.cmake

PR from [Andrew Hayworth](https://forums.foundationdb.org/u/ahayworth)
The ruby bindings are not currently installable. We can reproduce this with a build from source:
```
foundationdb/tmp on  main [$?] via △ v3.25.2
zsh ❯ gem install ./bindings/ruby/fdb-7.3.0.gem
ERROR:  While executing gem ... (Gem::Package::PathError)
installing into parent path /Users/andrew/projects/foundationdb/LICENSE of /Users/andrew/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/fdb-7.3.0 is not allowed
```
The problem is that the gemspec is interpolating the source directory into the `files` array - and while this allows the gem to build, it prevents it from actually being installed.
To fix it, we borrow similar code from the python bindings to copy the necessary files and license into the build directory …

Fix build for ruby bindings

---

CMakeLists.txt

@mavenraven found 3.1.8 can no longer compile FDB, so he bumps the version.
CI failure of correctness is not related.

Bumps minimum cmake required version.

---

fdbserver/VersionedBTree.actor.cpp
flow/include/flow/genericactors.actor.h

Avoid broken_promise in Redwood before shutdown after queue read error. (Cherry-Pick #9554 to snowflake/release-71.3)

---

fdbserver/BlobWorker.actor.cpp
fdbserver/worker.actor.cpp

Cherry-pick #9568 to fix nightly/CI bugs

[snowflake/release-71.3] Even more bg fixes

---

documentation/sphinx/source/command-line-interface.rst
fdbcli/TenantCommands.actor.cpp
fdbclient/include/fdbclient/MetaclusterManagement.actor.h
fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp

This is a cherry-pick of #9613.
This fixes a few minor issues with the metacluster and tenants:
1. Throw an error if a cluster name starts with `\xff`
2. Improve the help text in fdbcli for some tenant commands
3. Fix a link in the fdbcli documentation that was incorrectly placed above the tenant section

Metacluster/tenant fixes (snowflake/release-71.3)

---

fdbserver/workloads/ClogTlog.actor.cpp

addr is the one we want to keep. vector push_back() just adds a copy into the vector.

Fix ClogTlog valgrind error

---

tests/rare/ClogTlog.toml

When the ClogTlog is running, we may already pass the 450s, i.e., SIM_SPEEDUP_AFTER_SECONDS, and clogging is no longer effective. If that's the case, we want to finish the test quickly.

Reduce running time for ClogTlog

---

fdbserver/BlobManager.actor.cpp
fdbserver/BlobMigrator.actor.cpp
fdbserver/BlobRestoreController.actor.cpp
fdbserver/include/fdbserver/BlobGranuleServerCommon.actor.h

Fix for asan error - heap used after freed: need to pass Standalone<StringRef> as actor parameter so that StringRef is pointing to a valid memory address.

Fix asan error caused by StringRef parameter of updateRestoreState

---

bindings/c/CMakeLists.txt

Fix for building fdb_c_shim with sanitizers was committed a while ago. This PR enables packaging the shim library in the generated artifacts as well.

Enable fdb_install of fdb_c_shim for sanitizer builds

---

fdbcli/TenantCommands.actor.cpp

When using thread futures with transaction API functions, the thread future can own the memory for the returned result, making it necessary to keep it around after waiting on it.

Fix memory error in fdbcli tenant lock command

---

fdbcli/tests/fdbcli_tests.py

Update the expected error message from exclude in fdbcli_tests.
Follow up to #9449, change "free" -> "available" in the expected error message.

Update the expected error message from exclude in fdbcli_tests

---

bindings/python/CMakeLists.txt

Loading the client library over python FDB API in sanitizer builds leads to crashes. Therefore disabling python unit tests in sanitizer builds.

Disable Python unit tests in sanitizer builds

---

fdbserver/VersionedBTree.actor.cpp

Cherry-Pick of #9662
Injected (or real) faults here cause shutdown to hang and a zombie worker that is still up but doesn't respond to requests.

swallowing errors in redwood dispose (Cherry-Pick #9662 to snowflake/release-71.3)

---

fdbclient/RESTUtils.actor.cpp
fdbclient/include/fdbclient/RESTUtils.h
fdbserver/RESTKmsConnector.actor.cpp
flow/Net2.actor.cpp

Description
Patch addresses following issues:
1. Fix "return connection" routine, it fixes a regression introduced by an earlier fix.
2. Update RESTConnectionPool::connectionPoolMap to an "unordered_map" for O(1) lookups
3. Improve logging
4. Make RESTUrl parsing handle extra '/' for 'resource'
5. Ensure localhost connections are batched properly.
Testing
Standalone fdbserver with external KMS; able to create database

EaR: REST kms misc fixes

---

documentation/sphinx/source/release-notes/release-notes-710.rst
fdbclient/VersionedMap.h
fdbserver/ClusterRecovery.actor.cpp
tests/rare/ClogTlog.toml

cherrypick #8972 #9671  #9623
Seed storage servers are recruited as the intial set of storage servers when a database is first created. They function a little bit differently than normal, and do not set an initial version like storages normally do when they get recruited (typically equal to the recovery version).
Version correction is a feature where versions advance in sync with the clock, and are equal across FDB clusters. To allow different FDB clusters to have matching versions, they must share the same base version. This defaults to the Unix epoch, and clusters with the version epoch enabled will have a current version equal to the number of microseconds since the Unix epoch.
When the version epoch is enabled on a cluster, it causes a one time jump from the clusters current version …

Fix issue where the versions on seed storage servers decreased [release-7.1]

---

fdbcli/TenantCommands.actor.cpp
fdbcli/tests/fdbcli_tests.py

Similar to `delete` and `deleteId`, provide the ability to use either the name of the tenant or its ID to get the metadata.

Add tenant getId api to fdbcli

---

flow/Trace.cpp
flow/include/flow/error_definitions.h

The error handling for tracing too many lines was creating an `unknown_error`, which immediately terminates a test when `--crash` is used. To allow us to collect and log all of the relevant details for this scenario, use a new, different error that doesn't immediately fail.

Fix early unknown_error crash when tracing too many lines

---

fdbcli/TenantCommands.actor.cpp
fdbcli/tests/fdbcli_tests.py

Cherry-Pick of #9658
Similar to `delete` and `deleteId`, provide the ability to use either the name of the tenant or its ID to get the metadata.

Add tenant getId api to fdbcli (Cherry-Pick #9658 to snowflake/release-71.3)

---

flow/Hostname.actor.cpp
flow/include/flow/error_definitions.h

This is a cherry pick of #9676 
This catches the std::exception, logs a trace event, and converts it to an FDB exception

The isHostname function could cause an unknown_error if regex parsing failed (snowflake/release-71.3)

---

cmake/CompileZstd.cmake
flow/CMakeLists.txt

So that blob granules can use it in the 71.3 release
Passed 1k correctness and 1k blobgranule* correctness

Enable zstd on 71.3

---

fdbcli/TenantCommands.actor.cpp

This is a cherry-pick of #9655.
When using thread futures with transaction API functions, the thread future can own the memory for the returned result, making it necessary to keep it around after waiting on it.

Fix memory error in fdbcli tenant lock command (snowflake/release-71.3)

---

fdbserver/include/fdbserver/ProxyCommitData.actor.h

This is a backport of https://github.com/apple/foundationdb/pull/9643.

(snowflake/release-71.3) Fix argument type in ProxyCommitData::updateSSTagCost

---

fdbserver/DDRelocationQueue.actor.cpp

Cherry-Pick of #9629
Found by 71.2.7 release correctness tests, and appears to be a rare latent bug
Correctness in progress

Fixing double-completing of destination servers in busy map (Cherry-Pick #9629 to snowflake/release-71.3)

---

bindings/c/test/apitester/TesterCancelTransactionWorkload.cpp
bindings/c/test/apitester/TesterCorrectnessWorkload.cpp
bindings/c/test/apitester/TesterExampleWorkload.cpp
bindings/c/test/fdb_api.hpp

Add a toCharsRef function that allows converting an optional byte string to a chars ref.

Avoid potential access of empty optionals when printing errors in the api tester

---

tests/TestRunner/local_cluster.py
tests/authorization/conftest.py

AuthZ test: add a wait-reply loop to tenant id getter

---

fdbserver/workloads/FastTriggeredWatches.actor.cpp

Cherry-Pick of #9627
In FastTriggeredWatchesWorkload, if the randomized new value for the given `setKey` happens to be the same as the current value, the following will hold
- `first` is true, and
- `getDuration` is 0, and
- assertion `lastReadVersion - ver >= SERVER_KNOBS->MAX_VERSIONS_IN_FLIGHT || lastReadVersion - ver < SERVER_KNOBS->VERSIONS_PER_SECOND * (25 + getDuration)` will fail
To fix this, change the assertion to
```
assert(first || lastReadVersion - ver >= SERVER_KNOBS->MAX_VERSIONS_IN_FLIGHT ||
lastReadVersion - ver < SERVER_KNOBS->VERSIONS_PER_SECOND * (25 + getDuration));
```
Test plan:
On c27cdcd2df0aecc5973829c0542858d4f380850f:
- Apply to the fix on top of the commit reported by Joshua test. Rerun the command to make sure it passes.
- …

Deflake test FastTriggeredWatches (Cherry-Pick #9627 to snowflake/release-71.3)

---

fdbclient/RESTUtils.actor.cpp
fdbclient/include/fdbclient/RESTUtils.h
fdbserver/RESTKmsConnector.actor.cpp
flow/Net2.actor.cpp

* EaR: REST kms misc fixes
Description
Patch addresses following issues:
1. Fix "return connection" routine, it fixes a regression introduced by an earlier fix.
2. Update RESTConnectionPool::connectionPoolMap to an "unordered_map" for O(1) lookups
3. Improve logging
4. Make RESTUrl parsing handle extra '/' for 'resource'
Testing
Standalone fdbserver connecting to external KMS and database create
(cherry picked from commit ea796eb3ecb5fb3e7cc128f9579d0e61b839856b)

[snowflake/release-71.3] EaR: REST kms misc fixes (#9664)

---

cmake/FDBComponents.cmake

With this patch, jemalloc version must be 5.3.0; otherwise error is thrown.

Enforce the jemalloc version

---

fdbclient/NativeAPI.actor.cpp
fdbserver/BlobWorker.actor.cpp
tests/TestRunner/local_cluster.py

And also an assertion failure.
2 perf bugs
- head-of-line blocking in change feed empty version that would cause delta files writing at latest version to always block for 5 seconds
- not enough versions getting added to grv history to unblock delta files writing at non-latest versions
Fixes flaky BlobGranule* ctests that were timing out.
Passes 50k BlobGranule* correctness with no related failures
Supercedes #9694

fixing 2 bugs related to high delta file waitCommitted latency

---

fdbserver/TenantCache.actor.cpp

Then the tenant number when insert (implicitly converted to int 65536) and updated (overflow to 1) doesn't match.

fix unit test failure because of implicit uint16_t conversion to int

---

bindings/c/test/apitester/TesterCancelTransactionWorkload.cpp
bindings/c/test/apitester/TesterCorrectnessWorkload.cpp
bindings/c/test/apitester/TesterExampleWorkload.cpp
bindings/c/test/fdb_api.hpp

Cherry picks #9688 
Add a toCharsRef function that allows converting an optional byte string to a chars ref.

Avoid potential access of empty optionals when printing errors in the api tester (snowflake/release-71.3)

---

fdbclient/NativeAPI.actor.cpp
fdbserver/BlobWorker.actor.cpp

Cherry-pick #9702
And also an assertion failure.
2 perf bugs
head-of-line blocking in change feed empty version that would cause delta files writing at latest version to always block for 5 seconds
not enough versions getting added to grv history to unblock delta files writing at non-latest versions
Fixes flaky BlobGranule* ctests that were timing out.
Passes 50k BlobGranule* correctness with no related failures

fixing 2 bugs related to high delta file waitCommitted latency (snowflake/release-71.3)

---

fdbclient/BlobGranuleReader.actor.cpp
fdbclient/include/fdbclient/FDBTypes.h

This PR fixed a bug in KeyRangeRef:isCovered(), which is used by hybrid restore. 
cherry pick #9675

Fix KeyRangeRef::isCovered() (#9675)

---

fdbclient/include/fdbclient/BlobMetadataUtils.h
fdbserver/RESTKmsConnector.actor.cpp

Cherry-Pick of #9711
Passes 1000 /RestKmsConnector unit tests

fixing copy constructor error and adding test for it (Cherry-Pick #9711 to snowflake/release-71.3)

---

fdbserver/storageserver.actor.cpp

This bug can manifest as a quiet database failure because the cluster will repeatedly try to recruit a new SS on this process and fail because of the existing SS role.

When a storage server fails to register, we need to throw that error to terminate it

---

fdbserver/DDShardTracker.actor.cpp

The `DD_TENANT_AWARENESS_ENABLED` was not explicitly disabling the feature but instead indirectly doing so by not creating a dd tenant cache. Storage quotas also create a dd tenant cache, and this was causing tenant aware DD to be enabled.
This makes the feature more explicitly controlled by the knob.

The `DD_TENANT_AWARENESS_ENABLED` knob was accidentally bypassed by the `STORAGE_QUOTA_ENABLED` knob

---

fdbclient/TenantManagement.actor.cpp
fdbclient/include/fdbclient/MetaclusterManagement.actor.h
fdbclient/include/fdbclient/TenantManagement.actor.h
fdbclient/include/fdbclient/TenantSpecialKeys.actor.h

When incrementing a tenant ID, first validate that the non-prefix portion stays in bounds. If it does, then compute the ID with the prefix.

More carefully validate tenant increments to avoid overflows

---

fdbclient/TenantManagement.actor.cpp
fdbclient/include/fdbclient/MetaclusterManagement.actor.h
fdbclient/include/fdbclient/TenantManagement.actor.h
fdbclient/include/fdbclient/TenantSpecialKeys.actor.h

Cherry picks #9714.
When incrementing a tenant ID, first validate that the non-prefix portion stays in bounds. If it does, then compute the ID with the prefix.

More carefully validate tenant increments to avoid overflows (snowflake/release-71.3)

---

fdbserver/workloads/ConsistencyCheck.actor.cpp

CheckExtraDataStores reboots or kills storage servers with extra data stores. Since this occurs during a consistency check, the expectation is that the database is quiet and not in the midst of recovery. This was done with a 10-second delay, but it's possible during simulation tests that it takes longer than 10 seconds to recruit a new master, so this assumption is invalid and can cause a test failure when the consistency checks proceed.
Instead of a delay, we run an empty transaction through the system and explicitly wait for the cluster to return to a fully-recovered state.
Testing: 250,000 correctness tests.
7 failed due to jemalloc assertion
2 failed stuck in accepting_commits, with usable_regions=2
Both are known issues. …

Replace 10-second delay with explicit wait for cluster recovery in checkExtraDataStores

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
fdbserver/include/fdbserver/StorageMetrics.h
fdbserver/storageserver.actor.cpp
fdbserver/worker.actor.cpp

- Add knob to inject delay to limit FetchKeys' write rate
- Return server_overloaded rather than fail the storage server on timeouts
- Add delay when opening multiple key value stores to avoid memory exhaustion 
- Add rocksdb rate limiter to control write rate
- More metrics in storage server to track data move load

Sharded RocksDB reliability improvements

---

fdbserver/KeyValueStoreSQLite.actor.cpp

When detecting failed checksums in KeyValueStoreSQLite, we were computing the start and end affected pages and comparing that to the set of known corrupted pages to see if the failed checksum was expected. In the case that the page being checked didn't align with a 4096-sized block boundary, the end page was one too small and could result in us not detecting that a corruption was expected.

Fix possible off-by-one in the simulation upper bound check for page corruption

---

fdbclient/ServerKnobs.cpp

Having a frequent tag measurement interval generates a lot of trace spam

Increase the buggified tag measurement interval

---

fdbserver/workloads/AutomaticIdempotencyWorkload.actor.cpp

The automatic idempotency workload has a long runtime and occasionally fails due to logging too many events, etc.

Decrease number of transactions in automatic idempotency workload

---

fdbserver/DataDistributionQueue.actor.cpp

Cherry-Pick of #9629
Found by 71.2.7 release correctness tests, and appears to be a rare latent bug

Fixing double-completing of destination servers in busy map (Cherry-Pick #9629 to snowflake/release-71.2)

---

fdbserver/tester.actor.cpp

This modifies the simulated remote log policy to require more logs, preventing the simulator from killing machines that may be needed by other regions.

Avoid killing too many machines if one region is being shared between the remote primary and a satellite

---

fdbclient/RESTUtils.actor.cpp
fdbserver/EncryptKeyProxy.actor.cpp

Description
Patch propose two changes:
1. Avoid appending `tls` as part of URI for secure connections
2. RefreshEKs recurring task can be skipped if there are no keys to be refreshed
Testing
EncryptKeyProxyTest.toml
devRunCorrectness  - Inprogress
devRunCorrectnessFiltered 'Encrypt*' - Inprogress

EaR: Avoid appending `tls` to the URL

---

fdbserver/tester.actor.cpp

Cherry pick #9727. This isn't strictly necessary at the moment since multi-region tests are disabled on this branch, but it's good to have if that ends up changing.
This modifies the simulated remote log policy to require more logs, preventing the simulator from killing machines that may be needed by other regions.

Avoid killing too many machines if one region is being shared between the remote primary and a satellite (snowflake/release-71.3)

---

fdbserver/SimulatedCluster.actor.cpp

Disables another instance of usable_regions=2

---

fdbserver/KeyValueStoreSQLite.actor.cpp

Cherry picks #9724 
When detecting failed checksums in KeyValueStoreSQLite, we were computing the start and end affected pages and comparing that to the set of known corrupted pages to see if the failed checksum was expected. In the case that the page being checked didn't align with a 4096-sized block boundary, the end page was one too small and could result in us not detecting that a corruption was expected.

Fix possible off-by-one in the simulation upper bound check for page corruption (snowflake/release-71.3)

---

fdbclient/RESTUtils.actor.cpp
fdbserver/EncryptKeyProxy.actor.cpp

Description
Patch proposes two changes:
1. Avoid appending tls as part of URI for secure connections
2. RefreshEKs recurring task can be skipped if there are no keys to be refreshed
Testing
EncryptKeyProxyTest.toml
devRunCorrectness
devRunCorrectnessFiltered 'Encrypt*'
(cherry picked from commit c492f83bf4754faaf146c5100a2970b9651e3bba)
https://github.com/apple/foundationdb/pull/9734#issuecomment-1473127835

EaR: Avoid appending `tls` to the URL (#9734)

---

fdbserver/BlobWorker.actor.cpp

Cherry-Pick of #9670
This effectively tests the ability to toggle compression on and off for new file writing dynamically.

buggify blob granule compression per-file (Cherry-Pick #9670 to snowflake/release-71.3)

---

fdbserver/storageserver.actor.cpp

Cherry picks #9712
This bug can manifest as a quiet database failure because the cluster will repeatedly try to recruit a new SS on this process and fail because of the existing SS role.

When a storage server fails to register, we need to throw that error to terminate it (snowflake/release-71.3)

---

fdbclient/include/fdbclient/ConsistencyScanInterface.actor.h
fdbserver/ConsistencyScan.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp

Also as a result, we no longer need to verify that a recovery completed when killing/rebooting a machine during the consistency check

The consistency check should retry if it couldn't find all the commit proxies when getting key server locations

---

fdbserver/workloads/AutomaticIdempotencyWorkload.actor.cpp

Cherry picks #9718 
The automatic idempotency workload has a long runtime and occasionally fails due to logging too many events, etc.

Decrease number of transactions in automatic idempotency workload (snowflake/release-71.3)

---

fdbserver/DDShardTracker.actor.cpp

Cherry picks #9716
The DD_TENANT_AWARENESS_ENABLED was not explicitly disabling the feature but instead indirectly doing so by not creating a dd tenant cache. Storage quotas also create a dd tenant cache, and this was causing tenant aware DD to be enabled.
This makes the feature more explicitly controlled by the knob.

The `DD_TENANT_AWARENESS_ENABLED` knob was accidentally bypassed by the `STORAGE_QUOTA_ENABLED` knob (snowflake/release-71.3)

---

fdbclient/ServerKnobs.cpp

Cherry picks #9717 
Having a frequent tag measurement interval generates a lot of trace spam

Increase the buggified tag measurement interval (snowflake-release-71.3)

---

fdbclient/include/fdbclient/ConsistencyScanInterface.actor.h
fdbserver/ConsistencyScan.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp

Cherry picks #9744 
Also as a result, we no longer need to verify that a recovery completed when killing/rebooting a machine during the consistency check

The consistency check should retry if it couldn't find all the commit proxies when getting key server locations (snowflake/release-71.3)

---

fdbbackup/backup.actor.cpp
fdbclient/CoordinationInterface.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/include/fdbclient/CoordinationInterface.h
fdbclient/include/fdbclient/JsonBuilder.h
fdbrpc/include/fdbrpc/Locality.h
fdbserver/Status.actor.cpp
fdbserver/fdbserver.actor.cpp
flow/Hostname.actor.cpp
flow/include/flow/Hostname.h

In order to keep `locality` JSON objects the same between server roles and the Backup and DR agents, `LocalityData::toJSON()` was added.  
It may be best to move the JSON types into the `flow/` project but this PR will be cherry-picked to release branches so I'm deferring that for now to keep the change set smaller.

Add processID, networkAddress, and locality to layer status JSON for Backup Agents.

---

fdbbackup/backup.actor.cpp
fdbclient/CoordinationInterface.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/include/fdbclient/CoordinationInterface.h
fdbclient/include/fdbclient/JsonBuilder.h
fdbrpc/include/fdbrpc/Locality.h
fdbserver/Status.actor.cpp
fdbserver/fdbserver.actor.cpp
flow/Hostname.actor.cpp
flow/include/flow/Hostname.h

Cherry-Pick of #9736
In order to keep `locality` JSON objects the same between server roles and the Backup and DR agents, `LocalityData::toJSON()` was added.  
It may be best to move the JSON types into the `flow/` project but this PR will be cherry-picked to release branches so I'm deferring that for now to keep the change set smaller.

Add processID, networkAddress, and locality to layer status JSON for Backup Agents. (Cherry-Pick #9736 to snowflake/release-71.3)

---

fdbbackup/backup.actor.cpp
fdbclient/CoordinationInterface.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/include/fdbclient/CoordinationInterface.h
fdbclient/include/fdbclient/JsonBuilder.h
fdbrpc/include/fdbrpc/Locality.h
fdbserver/Status.actor.cpp
fdbserver/fdbserver.actor.cpp
flow/Hostname.actor.cpp
flow/include/flow/Hostname.h

Cherry-Pick of #9736
In order to keep `locality` JSON objects the same between server roles and the Backup and DR agents, `LocalityData::toJSON()` was added.  
It may be best to move the JSON types into the `flow/` project but this PR will be cherry-picked to release branches so I'm deferring that for now to keep the change set smaller.

Add processID, networkAddress, and locality to layer status JSON for Backup Agents. (Cherry-Pick #9736 to snowflake/release-71.2)

---

fdbserver/BlobWorker.actor.cpp
fdbserver/include/fdbserver/BlobGranuleServerCommon.actor.h
fdbserver/include/fdbserver/BlobWorker.h

refactor struct blobworkerdata to and struct granuleMetadata to blobworker.h
The PR has passed the following simulation test
The command I use:
`devRunCorrectness --env TH_INCLUDE_TEST_FILES='.*BlobGranule.*' --max-runs 100000`
`devRunCorrectness --max-runs 100000`

refactor struct BlobWorkerData and struct GranuleMetadata

---

fdbclient/include/fdbclient/MetaclusterManagement.actor.h

Listing tenant metadata would return the same tenant twice when a tenant was being renamed. This changes the behavior so that the rename destination is not included in the output.
This also fixes a rare infinite loop when the last tenant in a batch was being renamed and had the same ID as the last tenant read in the previous batch. 

Do not list renaming tenants twice when listing tenant metadata

---

fdbclient/include/fdbclient/MetaclusterManagement.actor.h

Cherry-pick #9753 
Listing tenant metadata would return the same tenant twice when a tenant was being renamed. This changes the behavior so that the rename destination is not included in the output.
This also fixes a rare infinite loop when the last tenant in a batch was being renamed and had the same ID as the last tenant read in the previous batch.

Do not list renaming tenants twice when listing tenant metadata (snowflake/release-71.3)

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/DDRelocationQueue.actor.cpp

Cherry-Pick of #9547
This won't bring a behavior change unless the knob becomes lower than the average load.

add knob for min read rebalance shard bandwidth (Cherry-Pick #9547 to snowflake/release-71.3)

---

bindings/c/test/fdb_c_client_config_tests.py

Improve stability of client configuration test [snowflake/release-71.3]

---

fdbserver/QuietDatabase.actor.cpp

If we stop repairing a dead datacenter part way through (e.g. because quite database completed during the repair), then we might leave the cluster in an unintended state.

Once we start repairing a dead datacenter, don't allow it to be canceled

---

tests/CMakeLists.txt
tests/restarting/from_71.3.0/ClientTransactionProfilingCorrectness-1.txt
tests/restarting/from_71.3.0/ClientTransactionProfilingCorrectness-2.txt
tests/restarting/from_71.3.0/CycleTestRestart-1.txt
tests/restarting/from_71.3.0/CycleTestRestart-2.txt
tests/restarting/from_71.3.0/StorefrontTestRestart-1.txt
tests/restarting/from_71.3.0/StorefrontTestRestart-2.txt

These are tests that were originally in `from_6.3.13`. In a previous PR they were moved to `from_6.3.13_until_71.2.0` and `from_71.2.0_until_71.3.0`. This commit adds coverage for upto the current version by adding a third copy in `from_71.3.0`.

Add more tests in `tests/restarting/from_71.3.0`

---

fdbserver/QuietDatabase.actor.cpp

Cherry-pick #9768 
If we stop repairing a dead datacenter part way through (e.g. because quite database completed during the repair), then we might leave the cluster in an unintended state.

Once we start repairing a dead datacenter, don't allow it to be canceled (snowflake/release-71.3)

---

fdbrpc/include/fdbrpc/simulator.h
fdbrpc/sim2.actor.cpp
fdbserver/LogSystemPeekCursor.actor.cpp

This is an issue discovered in simulation where connection failure is enabled around 150s, and disabled around 150+450 = 600s. But the log cursor check is exercised at 450+120 = 570, which violate that Log cursor shouldn't return timeout. However, since the connection failure is still enabled, it is a valid log cursor timeout.
Therefore, the log cursor timeout check should take when connection failure is enabled into account.
20230322-051028-zhewu_cursor_check-a145f9a47e01b302

LogCursor timeout check should take when connection failure is enabled into account

---

fdbserver/ClusterController.actor.cpp

Cherry picks https://github.com/apple/foundationdb/pull/9772
This is an issue found in simulation that when the cluster controller cannot communicate with a registered worker, the CC will be blocked in broadcastDBInfoRequest indefinitely. When a new worker joins the cluster, although updateDBInfo.trigger() is called, it won't trigger a new serverDbInfo updater.
This PR fixes this issue by starting a new round of DbInfo updater in the middle of broadcastDBInfoRequest.

Update info trigger new DB info update immediately [release-7.1]

---

fdbclient/SpecialKeySpace.actor.cpp

Currently the exclude command will block exclusions if the (new) free capacity is below 10%. This also blocks exclusions for processes that don't serve a storage role e.g. stateless processes. I don't think it make sense to block the exclusion of a stateless process based on the free capacity. With those changes the free capacity check will be skipped if no process in the exclusion set is serving a storage role, if at least one process is serving a storage role the free capacity check will be done.

Don't block the exclusion of stateless processes by the free capacity check

---

fdbserver/ClusterController.actor.cpp

[Release 7.2] updateDBInfo.trigger() should trigger a new round of DbInfo update

---

fdbserver/QuietDatabase.actor.cpp

An 'attribute_not_found' error was slipping through the cracks when attempting to get the max storage queue size for a storage server which has been removed. This change explicitly logs the error where it occurs, making it easier to debug.

Log reason for QuietDatabase check failure.

---

fdbclient/SpecialKeySpace.actor.cpp

cherrypick #9468
Back-port of: https://github.com/apple/foundationdb/pull/9468

Backport exclusion fix #9468

---

fdbserver/storageserver.actor.cpp
fdbserver/workloads/GetMappedRange.actor.cpp
tests/fast/GetMappedRange.toml

20230323-183541-haofu-31f88aa7fae092f4
before the fix
```
trace.0.0.0.0.0.1679585524.NeL00s.0.1.xml:QueryQueueMax="0"
trace.0.0.0.0.0.1679585524.NeL00s.0.1.xml:QueryQueueMax="0"
trace.0.0.0.0.0.1679585524.NeL00s.0.1.xml:QueryQueueMax="0"
trace.0.0.0.0.0.1679585524.NeL00s.0.1.xml:QueryQueueMax="0"
trace.0.0.0.0.0.1679585524.NeL00s.0.1.xml:QueryQueueMax="9"
trace.0.0.0.0.0.1679585524.NeL00s.0.1.xml:QueryQueueMax="25"
trace.0.0.0.0.0.1679585524.NeL00s.0.1.xml:QueryQueueMax="0"
trace.0.0.0.0.0.1679585524.NeL00s.0.1.xml:QueryQueueMax="0"
trace.0.0.0.0.0.1679585524.NeL00s.0.1.xml:QueryQueueMax="0"
trace.0.0.0.0.0.1679585524.NeL00s.0.1.xml:QueryQueueMax="6"
trace.0.0.0.0.0.1679585524.NeL00s.0.1.xml:QueryQueueMax="0"
trace.0.0.0.0.0.1679585524.NeL00s.0.1.xml:QueryQueueMax="0" …
```

 Fix finishedQueries metric, add metrics reporting in GetMappedRange test [release-7.1]

---

fdbserver/VersionedBTree.actor.cpp

- After maxColdStarts is hit, stop the test instead of stopping cold starts.
With this change, running 100k of just the BTree unit test does not result in any timeouts and the longest execution time is  1700 seconds.  This would probably still time out for test with ASAN.

Make Redwood unit test run shorter amounts of time.

---

fdbserver/ClusterController.actor.cpp

Cherry picks #9772 
This is an issue found in simulation that when the cluster controller cannot communicate with a registered worker, the CC will be blocked in broadcastDBInfoRequest indefinitely. When a new worker joins the cluster, although updateDBInfo.trigger() is called, it won't trigger a new serverDbInfo updater.
This PR fixes this issue by starting a new round of DbInfo updater in the middle of broadcastDBInfoRequest.

updateDBInfo.trigger() should trigger a new round of DbInfo update (snowflake/release-71.3)

---

fdbserver/QuietDatabase.actor.cpp

Cherry-Pick of #9775
An 'attribute_not_found' error was slipping through the cracks when attempting to get the max storage queue size for a storage server which has been removed. This change explicitly logs the error where it occurs, making it easier to debug.

Log reason for QuietDatabase check failure. (Cherry-Pick #9775 to snowflake/release-71.3)

---

fdbclient/ManagementAPI.actor.cpp
fdbclient/SpecialKeySpace.actor.cpp
fdbclient/include/fdbclient/ManagementAPI.actor.h
fdbserver/workloads/DataLossRecovery.actor.cpp
fdbserver/workloads/SpecialKeySpaceRobustness.actor.cpp
tests/fast/SpecialKeySpaceRobustness.toml

The motivation is that exclude command triggers recovery if the system is not in `fully_recovered` state. This causes trouble during unstable states.
20230325-031637-zhewu_exclude-a96cf27b7a08a2db     compressed=True data_size=32586002 duration=4731216 ended=100000 fail=4 fail_fast=10 max_runs=100000 pass=99996 priority=100 remaining=0 runtime=1:02:28 sanity=False started=100000 stopped=20230325-041905 submitted=20230325-031637 timeout=5400 username=zhewu_exclude
All unrealted failures.

Do not update exclude/failed system metadata in excludeServers if the input list is already excluded/failed.

---

fdbserver/workloads/SlowTaskWorkload.actor.cpp
flow/Platform.actor.cpp
flow/Profiler.actor.cpp
flow/include/flow/Platform.h

The slow task profiler had two problems when used with the multi-version client:
1. Each external client sets a signal handler for the process, but these overwrite each other. In the end, one signal handler would be called from one of the libraries.
2. It used thread local variables to handle some of its logic. For externally loaded clients (loaded using dlopen), the memory for these variables was allocated dynamically the first time they were used, and if we called into another client's signal handler then this allocation would occur in the signal handler. It is not safe to call malloc in a signal handler, and this led to deadlocks.
This changes the signal handler to not use thread local variables but to instead compare the thread ID of the network thread with the thread id in the signal …

Fix the slow task profiler when used with the multi-version client

---

fdbclient/ServerKnobs.cpp
fdbserver/ConsistencyScan.actor.cpp
fdbserver/include/fdbserver/StorageMetrics.actor.h
fdbserver/storageserver.actor.cpp

Cherry-Pick of #9799
In the pathological case that both key size and value size are 0,
the probability of choosing that key-value pair is 0, and we divide
by zero when computing the sampledSize.
This change adds documentation to that function, which was quite
difficult to understand. In addition, we add `probability` to the
returned values, since one of the callers was backing it out from
sampledSize and itself in danger of dividing by zero.

Avoid divide-by-zero in isKeyValueInSample. (Cherry-Pick #9799 to snowflake/release-71.3)

---

fdbserver/Ratekeeper.actor.cpp

If ratekeeper started throttling, this new transaction I added in #9425 didn't have the right flags. This would cause RK to get stuck computing the new blob worker transaction rate whenever RK was throttling based on blob workers being behind. This would basically deadlock until a cluster recovery happened and a new RK started.

fixing txn flags in new bw rk function

---

fdbclient/ManagementAPI.actor.cpp
fdbclient/ManagementAPI.actor.h
fdbclient/SpecialKeySpace.actor.cpp
fdbserver/workloads/DataLossRecovery.actor.cpp

Cherry-pick #9803 
Didn't add SpecialKeySpaceRobustness.actor.cpp since it doesn't exist in 7.1
20230327-170002-zhewu_exclude_7.1-950d1a741aa7ffea compressed=True data_size=37914275 duration=3328832 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:31:48 sanity=False started=100000 stopped=20230327-173150 submitted=20230327-170002 timeout=5400 username=zhewu_exclude_7.1

[Release 7.1] Do not update exclude/failed system metadata in excludeServers if the input list is already excluded/failed

---

fdbserver/workloads/MetaclusterRestoreWorkload.actor.cpp
tests/slow/MetaclusterRecovery.toml

The metacluster recovery workload has a particular long runtime when run in ASan. This uses a simplified configuration for the metacluster recovery workload to speed up its runtime.
Here is a distribution of ~10K ASan runs before and after the change:
```
Num tests:    10479                10499
Median   :   428.93       192.50 (0.45x)
p90      :   863.39       351.60 (0.41x)
p99      :  1478.09       570.22 (0.39x)
p99.9    :  2097.96       923.79 (0.44x)
Max      :  2861.45      1098.96 (0.38x)
```

Speed up the runtime of the metacluster recovery tests

---

fdbserver/Ratekeeper.actor.cpp

Cherry-Pick of #9813
If ratekeeper started throttling, this new transaction I added in #9425 didn't have the right flags. This would cause RK to get stuck computing the new blob worker transaction rate whenever RK was throttling based on blob workers being behind. This would basically deadlock until a cluster recovery happened and a new RK started.

fixing txn flags in new bw rk function (Cherry-Pick #9813 to snowflake/release-71.3)

---

fdbserver/workloads/GetMappedRange.actor.cpp
tests/fast/GetMappedRange.toml

Also retry when operation_cancelled happens
20230327-132924-haofu-327eacda35619bf1
part of https://github.com/apple/foundationdb/pull/9796

Parameterized queue length in GetMappedRange test(release-7.1)

---

fdbclient/NativeAPI.actor.cpp

Handling case where ss or tss is multiple rollbacks ahead of its pair (infrequent).

handling multiple in-flight rollbacks for tss change feed stream comparison

---

fdbserver/workloads/PerpetualWiggleStatsWorkload.actor.cpp

Cherry-Pick of #9690. And re-ran *Perpetual* tests 100k pass.
PerpetualWiggleStatsWorkload assumes itself as the only writer to `PerpetualWiggleMetrics` in the database, so in the `setup` phase it disables DD.
However, there is a rare case that the DD hasn't finished the quit process before the workload enters the `start` phase, so the new `PerpetualWiggleMetrics` written by the workload may be overridden by DD before DD finishes the quit process, which causes the test failure.
The easy solution here is to wait for extra 30s in the setup phase which is 99.9% if not 100% enough for the DD completely quit before `start` phase. If DD hasn't quit after 30s since disabled, it also indicates other bugs.
Pass 100k Perpetual* workload.
The general pull request guidelines can …

fix a rare race condition in PerpetualWiggleStatsWorkload.actor.cpp (Cherry-Pick #9690 to snowflake/release-71.3)

---

documentation/sphinx/source/configuration.rst
fdbmonitor/fdbmonitor.cpp

Brings #4870 up to date with main.
Previously, --parentpid was only supported on windows. https://github.com/apple/foundationdb/pull/1496 extended that to other platforms for a CI usecase. On Linux, prctl(PR_SET_PDEATHSIG, SIGHUP) should arrange for the subsequently exec()'d fdbserver to get a SIGHUP and die if fdbmonitor is killed. In local testing, I've confirmed that this works, but I've also seen evidence that on some hosts/clusters it appears to possibly not work.
Therefore, having --parentpid as a backup for the cases where it seems like hosts might not properly support PR_SET_PDEATHSIG is nice.
This was tested by running a local cluster, and confirming that $PID is properly translated into the fdbmonitor process ID. …

Make fdbmonitor understand $PID, so that --parentpid is usable on fdbserver

---

fdbclient/NativeAPI.actor.cpp

Cherry-Pick of #9816
Handling case where ss or tss is multiple rollbacks ahead of its pair (infrequent).

handling multiple in-flight rollbacks for tss change feed stream comparison (Cherry-Pick #9816 to snowflake/release-71.3)

---

fdbserver/BlobManager.actor.cpp
fdbserver/workloads/ConsistencyCheck.actor.cpp

Cherry-Pick of #9819
Running 10k BlobGranule* correctness

fixing system priority flags usage in blob manager (Cherry-Pick #9819 to snowflake/release-71.3)

---

fdbserver/workloads/ValidateStorage.actor.cpp

100K ValidateStorage:
20230329-220011-zhewang-73a042385b2f8e1f           compressed=True data_size=32642311 duration=1312360 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:26:32 sanity=False started=100000 stopped=20230329-222643 submitted=20230329-220011 timeout=5400 username=zhewang
100K Correctness test with 4 irrelevant failures:
20230329-221003-zhewang-24676354dee72c79           compressed=True data_size=32613329 duration=3661856 ended=100000 fail=4 fail_fast=10 max_runs=100000 pass=99996 priority=100 remaining=0 runtime=0:47:52 sanity=False started=100000 stopped=20230329-225755 submitted=20230329-221003 timeout=5400 username=zhewang
The general pull request guidelines can be found [here](https://github.com/apple/foundationdb/wiki/FoundationD …

Disable failure injection in ValidateStorage test

---

fdbrpc/include/fdbrpc/simulator.h
fdbserver/SimulatedCluster.actor.cpp
fdbserver/workloads/MachineAttrition.actor.cpp

Occasionally a restarting test would hit an issue where the first phase of the test would set the healthy zone key to ignore ss failures. If the first test was stopped before the healthy zone key could be cleared, the second test would ignore any ss failures permanently.
This would cause DD to never remove the storage servers, which would cause the quiet database check to continually reach out to these dead storage servers asking for their storage metrics, resulting in attribute_not_found and the test timing out.
Passes 10k correctness. …

fixing healthy zone issue with restarting tests

---

fdbserver/RESTKmsConnector.actor.cpp

Description
Fix valgrind issues with RESTKmsConnector unit tests
Testing
RESTKmsConnectorUnit.toml - valgrind and asan runs

Fix valgrind issues with RESTKmsConnector unit tests

---

bindings/c/test/apitester/TesterOptions.h
bindings/c/test/apitester/TesterTestSpec.cpp
bindings/c/test/apitester/TesterTestSpec.h
bindings/c/test/apitester/fdb_c_api_tester.cpp
bindings/c/test/apitester/tests/CApiRunLoopProfiler.toml
fdbclient/NativeAPI.actor.cpp
flow/Platform.actor.cpp
flow/include/flow/Platform.h

Adding a test that reproduces the deadlock caused by mallocs in the signal handler triggered by the loop profiler. 
The test  is not deterministic, so it sometime succeeds. For me it failed about 80% of times.

Test loop profiler using API Tester

---

fdbclient/ServerKnobs.cpp
fdbserver/RESTKmsConnector.actor.cpp

Description
RESTKms validation tokens are provided using foundationdb.conf, the file uses '#' as comment start character. Update the token-name seperator to '$' instead of '#'
Testing
RESTKmsConnectorUnit.toml

EaR: Update REST validation token-name separator from '#' -> '$'

---

fdbserver/workloads/MetaclusterRestoreWorkload.actor.cpp
tests/slow/MetaclusterRecovery.toml

Cherry pick #9798 
The metacluster recovery workload has a particular long runtime when run in ASan. This uses a simplified configuration for the metacluster recovery workload to speed up its runtime.
Here is a distribution of ~10K ASan runs before and after the change:
```
Num tests:    10479                10499
Median   :   428.93       192.50 (0.45x)
p90      :   863.39       351.60 (0.41x)
p99      :  1478.09       570.22 (0.39x)
p99.9    :  2097.96       923.79 (0.44x)
Max      :  2861.45      1098.96 (0.38x)
``` …

Speed up the runtime of the metacluster recovery tests (snowflake/release-71.3)

---

fdbclient/ServerKnobs.cpp
fdbserver/RESTKmsConnector.actor.cpp

Description
RESTKms validation tokens are provided using foundationdb.conf, the file uses '#' as comment start character. Update the token-name separator to '$' instead of '#'
Testing
RESTKmsConnectorUnit.toml
(cherry picked from commit 054358e63f832e67e1a379ee468f3a001b2977a1)
(https://github.com/apple/foundationdb/pull/9848)

EaR: Update REST validation token-name separator from '#' -> '$' (#9848)

---

fdbclient/SpecialKeySpace.actor.cpp

In the current code we stop iterating over all storage servers once we find a storage server that is in the newly excluded list.

Don't stop iterating over all storage processes in exclusion check

---

fdbserver/include/fdbserver/MovingWindow.h

Cherry-Pick of #9812
Add comments on the use case of `MovingWindow` and its difference with `Smoother`.

add comment on where to use MovingWindow rather than Smoother (Cherry-Pick #9812 to snowflake/release-71.3)

---

fdbserver/RESTKmsConnector.actor.cpp

Description
Fix valgrind issues with RESTKmsConnector unit tests
Testing
RESTKmsConnectorUnit.toml - valgrind and asan runs
(cherry picked from commit 7ea410a7416f47ee985feba49a7d05d00ac2c543)
(https://github.com/apple/foundationdb/pull/9832)

Fix valgrind issues with RESTKmsConnector unit tests (#9832)

---

fdbrpc/TokenSign.cpp
tests/TestRunner/local_cluster.py
tests/authorization/conftest.py

Per [JWT RFC](https://www.rfc-editor.org/rfc/rfc7519#section-4.1.3), `aud` claim `["value"]` MAY be replaced with a single string `"value"`, whose support is optional.
This PR allows this behavior to stay flexible to the other interpretations of the token standard.

Allow token "aud" field to have a string as value

---

tests/TestRunner/binary_download.py

By setting the latest version to 7.2.6

Fix ctest errors after 7.2.5 release

---

fdbclient/NativeAPI.actor.cpp

We recently added a test to test `exclude failed` command which exposed this bug in the existing code.
When a client is issuing an ExclusionSafetyCheckRequest to check safe exclusion, if during this time, there is a proxy change, this will cancel the current basicLoadBalance() function along with the future created for the ExclusionSafetyCheckReply. However, when we re-issue the ExclusionSafetyCheckRequest again, we will use the same req object, whose reply future has already being cancelled. This causes the request to throw broken promise immediately, and then the host will mistakenly think the remote endpoint is failed.
This leads to the ExclusionSafetyCheckRequest to be blocked forever.
The fix is to re-create the ExclusionSafetyCheckRequest every time when issuing a new …

checkSafeExclusion should always create new ExclusionSafetyCheckRequest

---

tests/fast/SpecialKeySpaceRobustness.toml

Since we are using pseudo IPs for the exclude command, we no longer need extra processes in the test.

Update SpecialKeySpaceRobustness config

---

fdbclient/ManagementAPI.actor.cpp
fdbclient/SpecialKeySpace.actor.cpp
fdbclient/include/fdbclient/ManagementAPI.actor.h
fdbserver/workloads/SpecialKeySpaceRobustness.actor.cpp
tests/CMakeLists.txt

Similar to #9803 , we also don't want to update system metadata if exclude locality has already exist in the system metadata.
100K SpecialKeySpaceRobustness:
20230402-022130-zhewu_robustness_single-04a4fba40ca9d7d0 compressed=True data_size=32541672 duration=1720033 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:38:09 sanity=False started=100000 stopped=20230402-025939 submitted=20230402-022130 timeout=5400 username=zhewu_robustness_single
100K random simulation test:
20230402-023555-zhewu_exclude_locality_all-380d791038bcc78f compressed=True data_size=47768723 duration=5009879 ended=100000 fail=2 fail_fast=10 max_runs=100000 pass=99998 priority=100 remaining=0 runtime=0:49:57 sanity=False started=100000 stopped=20230402-032552 …

Check if the locality is already excluded before issuing exclude locality transaction

---

fdbclient/NativeAPI.actor.cpp

[release 7.1] checkSafeExclusion should always create new ExclusionSafetyCheckRequest

---

fdbclient/NativeAPI.actor.cpp

[release 7.2] checkSafeExclusion should always create new ExclusionSafetyCheckRequest

---

fdbclient/BlobCipher.cpp

Description
Heap overflow was due to recent upgrade in BlobCipherTest to use variable size 'baseCipher' buffer.
Testing
BlobCipherUnit test

EaR: Fix heap-over-flow in BlobCipherTest

---

cmake/CompileRocksDB.cmake
documentation/sphinx/source/release-notes/release-notes-710.rst
fdbserver/KeyValueStoreRocksDB.actor.cpp
fdbserver/RocksDBCheckpointUtils.actor.h

RocksDB 7.10.2 version upgrade.
cherrypick of #9828

RocksDB 7.10.2 version upgrade

---

fdbcli/StatusCommand.actor.cpp
fdbserver/BlobManager.actor.cpp
fdbserver/BlobMigrator.actor.cpp
fdbserver/Status.actor.cpp

Fdbcli changes. New fields are added to reflect manifest and mutation log status.  some example output:
```
Blob Granules:
Number of Workers      - 2
Number of Key Ranges   - 12
Last Manifest          - 1.3 dumped at 16:17. Total 41248 bytes.
Restorable log version     - 13600359120 - 13680359120
```

Add blob manifest and mutation log status to fdbcli

---

fdbserver/MoveKeys.actor.cpp

* fdbserver/MoveKeys.actor.cpp Make startMoveShards work like startMoveKeys handling TSS. Make finishMoveShards work like finishMoveKeys handling TSS.

The sharded rocks implementation skipped on TSS handling. Backfill.

---

flow/Platform.actor.cpp

The signal handler for the run loop profiler accesses a variable called `chainedSignalHandler` that is configured after the signal handler is set. This introduces a brief period where there could be a race between getting the signal and accessing `chainedSignalHandler` and the variable being set.
Instead, this change updates the logic so that we use the `struct sigaction` returned from the `sigaction` call directly and avoid modifying it after setting the signal handler.

Avoid a thread race trying to initialize the chained signal handler

---

fdbclient/BlobCipher.cpp

Description
Heap overflow was due to recent upgrade in BlobCipherTest to use variable size 'baseCipher' buffer.
Testing
BlobCipherUnit test
(cherry picked from commit 769226e5c0f97ece66150fa6bb9efa267d8b6c7d)
(https://github.com/apple/foundationdb/pull/9877)

EaR: Fix heap-over-flow in BlobCipherTest (#9877)

---

flow/Arena.cpp

Cherry-Pick of #9865
Original code comment says
"there's no hard guarantee about the above equality and the result could vary by platform, malloc implementation, and tooling instrumentation (e.g. ASAN, valgrind)"
Therefore, we should remove the assertion on UB.
Furthermore, we have a case in which, even without ASAN or other instrumentation, e.g. Valgrind, etc, the equality does not hold.
Profile: team
Commit hash: 3164cadc6f7bf6ed00e8d22ce8dcd51820a152a7
Command: devRetryCorrectnessTest bin/fdbserver -r simulation -f tests/fast/RandomUnitTests.toml -s 3939330597 -b on  --crash --trace_format json
The general pull request guidelines can be found [here](https://github.com/apple/foundationdb/wiki/FoundationDB-Commit-Proces …

Remove an assertion for UB (Cherry-Pick #9865 to snowflake/release-71.3)

---

fdbclient/include/fdbclient/TenantData.actor.h
fdbclient/include/fdbclient/TenantManagement.actor.h
fdbserver/workloads/MetaclusterRestoreWorkload.actor.cpp
fdbserver/workloads/TenantManagementWorkload.actor.cpp
metacluster/include/metacluster/RenameTenant.actor.h
metacluster/include/metacluster/UpdateTenantGroups.actor.h

The tenant group index is now a tuple of the form (tenant group name, tenant name, tenant ID). This allows us to read the index paged by the tenant name and to get both the name and ID in one read.

Update the tenant group index to include the tenant name

---

fdbcli/tests/fdbcli_tests.py

Since `versionepoch` can trigger recovery, 
we need to wait until the database is available to move to the next test.
Otherwise, unexpected behavior can be seen as tests are added under the assumption that DB is healthy at the beginning of each test.
- Add wait at the end of the `versionepoch` fdbcli test, which triggers recovery
- Add start&end logging of each command test

Add wait at the end of the versionepoch fdbcli test which triggers recovery

---

documentation/sphinx/source/release-notes/release-notes-710.rst
fdbserver/DataDistributionQueue.actor.cpp

When a server is removed, `dataDistributionRelocator` doesn't remove the work for the destination storage workers. As a result, it can no long move shard into any of the healthy workers in the destination team.
seed: `-r simulation -f ./tests/slow/ConfigureTest.toml -s 688316276 -b on`
commit: d4ffd358d676869e144aff38565406291138021d
cherrypick #9629 and previous changes
20230405-153518-jzhou-ee5ac1a8d0fc66a3

Fixed stuck data movement when a server is removed [release-7.1]

---

fdbclient/ServerKnobs.cpp

Description
EKP failure detection time is choosen to be fairly low given EKP availability could impact cluster availability. However, in simulation runs, for various reasons such a low-latency failure detection could cause EKP recruitment to be done in a loop. Patch relaxes the failure detection time for simulation runs
Testing

Relax EKP failure detection time for simulated runs

---

fdbserver/BlobWorker.actor.cpp
fdbserver/workloads/BlobGranuleVerifier.actor.cpp
tests/CMakeLists.txt
tests/restarting/from_71.2.8/BlobGranuleRestartCycle-1.toml
tests/restarting/from_71.2.8/BlobGranuleRestartCycle-2.toml
tests/restarting/from_71.2.8/BlobGranuleRestartLarge-1.toml
tests/restarting/from_71.2.8/BlobGranuleRestartLarge-2.toml

Cherry-picking blob granule restarting tests to 71.2 so we can test BG upgrades and downgrades with 71.3:
#9259 
#9313 
Passes 10k BlobGranuleRestart* correctness

backporting blob granule restarting tests

---

fdbclient/ClientKnobs.cpp
fdbclient/FileBackupAgent.actor.cpp
fdbclient/include/fdbclient/ClientKnobs.h

Use KeyBackedSet to replace KeyBackedProperty<std::vector<KeyRange>>. If there are lot of ranges to restore, it may throw value_too_large errors when writing this property. 
100k correctness test passed

RestoreConfig - use restoreRangeSet to replace restoreRanges

---

fdbclient/BlobCipher.cpp

Description
Patch proposes BlobCipher cache bug related to handling of cipherKeys that either 'needsRefresh' and/or 'expired'
Also, adds a unit-test to cover the following use case:
1. Test refreshAt and expireAt properties of the cipherKey
2. Validate corresponding Counter value increments
Testing
Extend /blobCipher unit-test tests

EaR: Fix BlobCipher cache handling for cipher needs refresh and/or expired

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/VersionedBTree.actor.cpp
fdbserver/worker.actor.cpp

Fix out-of-disk-space issue for storage servers with io_timeout. It happens as the following:
1) io_timeout error happens in updateStorage() of storage server when writing commits to disk
2) DD treats it as a failed storage server and repairs the team. 
3) The worker resigns the storage server role, but not reboot
4) The worker is recruited as a new storage server and creates new data file. The old file stays on the disk until next reboot of the worker. 
If io_timeout happens frequently, there are many leftover data files and eventually it runs into out of disk space error.
The fix is on step 4. Before the worker is recruited as a new storage server, try to cleanup old data files. 
100K correctness tests passed.  …

Cleanup stale disk files for double recruitment of storage server

---

fdbclient/include/fdbclient/TenantData.actor.h
fdbclient/include/fdbclient/TenantManagement.actor.h
fdbserver/workloads/MetaclusterRestoreWorkload.actor.cpp
fdbserver/workloads/TenantManagementWorkload.actor.cpp
metacluster/include/metacluster/RenameTenant.actor.h
metacluster/include/metacluster/UpdateTenantGroups.actor.h

Cherry pick #9899 
The tenant group index is now a tuple of the form (tenant group name, tenant name, tenant ID). This allows us to read the index paged by the tenant name and to get both the name and ID in one read.

Update the tenant group index to include the tenant name (snowflake/release-71.3)

---

fdbserver/DDRelocationQueue.actor.cpp
fdbserver/DDTxnProcessor.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/MoveKeys.actor.cpp
fdbserver/include/fdbserver/DataDistribution.actor.h

Persisted data move keeps following invariant:
A persisted data move has an empty range if and only if the persisted data move is a tombstone of a data move.
This persisted data move is generated by a background cleanup. See PR #9421.
Any tombstone of data move should be cleanup later. 
There are two cases of cleaning tombstone: (1) the tombstone is cleaned by a background data move, as it does in PR #9421; (2) before the background data move is triggered, DD restarts. For the second case, we want the tombstone is cleaned when DD is inited.
In this PR, we clean the tombstone for the second case.
Pass 100K with 2 irrelevant failure:
20230406-015534-zhewang-12a0792761b37748           compressed=True data_size=32691062 duration=4981917 ended=100000 fail=2 fail_fast=10 max_runs=100000 …

Clean up data move tombstone when DD init

---

fdbserver/storageserver.actor.cpp

So that if the actor collection actor already exited due to the terminating error, we still clean up those futures. This would sometimes result in a segfault since actors would keep going after the actor collection was cleared.
Passes 50k correctness

Also clear the promise stream in actor collection on SS shutdown

---

fdbclient/BlobCipher.cpp

Description
Fix Asan reporting heap overflow
Testing
BlobCipherUnitTest with failing seed

Fix Asan reporting heap overflow

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/ClusterController.actor.cpp
fdbserver/include/fdbserver/ClusterController.actor.h
fdbserver/worker.actor.cpp

This PR implements gray failure detection for disconnected remote log router.
When a remote log router is disconnected from TLogs in the primary region, either in the primary or primary satellite, this can result in high DC lags between primary and remote region. This lag needs to be actively addressed since the remote region stops getting data from the primary region.
This PR allows gray failure detection to detect disconnections between primary region tlogs and remote log router, and trigger a recovery to remove problematic remote log router. For remote log router, we only monitor the disconnection, but not performance.
Besides unit tests added in this PR, we also test this in a real cluster with injected disconnection between satellite TLogs and one remote log router. And as we can see …

Gray failure detects disconnected remote log router and recover high DC lag

---

fdbserver/BlobManager.actor.cpp
fdbserver/BlobManifest.actor.cpp

This PR is to split manifest backup into 2 actors: one is to dump manifest, and the other is to truncate mutation logs. Sometimes mutation log backup takes long time because of flushing granules and it blocks manifest backup. So it's better to  split them and make sure we can always dump manifests. 
The other fix is in manifest cleanup. we should wait on the deletion future before return. 
100K correctness tests passed

Use separated actors to dump manifest and truncate mutation logs

---

fdbserver/DDRelocationQueue.actor.cpp
fdbserver/DDTeamCollection.actor.cpp
fdbserver/include/fdbserver/DataDistributionTeam.h

Cherry-Pick of #9713
`GetTeamRequest` has two boolean variables `wantsNewServers`, `wantsTrueBest`, which are not mutually exclusive. The `wantNewServers=false, wantsTrueBest=true` condition does not hold true semantically and theoretically. We want to use a single enum class TeamSelect to express the valid leftover 3 situations.
```
TeamSelect::WANT_TRUEBEST = wantsNewServers=True && wantsTrueBest=True
TeamSelect::ANY = wantsNewServers=True && wantsTrueBest=False
TeamSelect::WANT_SRCSERVERS = wantsNewServers=Fasle && wantsTrueBest=False
```
If this PR is …

refactor GetTeamRequest (Cherry-Pick #9713 to snowflake/release-71.3)

---

fdbclient/ServerKnobs.cpp

Description
EKP failure detection time is chosen to be fairly low given EKP availability could impact cluster availability. However, in simulation runs, for various reasons such a low-latency failure detection could cause EKP recruitment to be done in a loop. Patch relaxes the failure detection time for simulation runs
Testing
(cherry picked from commit 625eb00d369dd6dc6016c5ea6b2ca12bf25a1cd0)
(https://github.com/apple/foundationdb/pull/9908)

Relax EKP failure detection time for simulated runs (#9908)

---

fdbclient/BlobCipher.cpp

* EaR: Fix BlobCipher cache handling for cipher needs refresh and/or expired
Description
Patch proposes BlobCipher cache bug related to handling of cipherKeys that either 'needsRefresh' and/or 'expired'
Also, adds a unit-test to cover the following usecase:
1. Test refreshAt and expireAt properties of the cipherKey
2. Validate corresponding Counter value increments
Testing
Extend /blobCipher unittest tests
(cherry picked from commit ecc6d5a712dac0a762ae8d6708c465e03d83953d)
(https://github.com/apple/foundationdb/pull/9845)
If …

[snowflake/release-71.3] EaR: Fix BlobCipher cache handling for cipher needs refresh and/or expired (#9845)

---

fdbclient/BackupContainerLocalDirectory.actor.cpp
fdbrpc/include/fdbrpc/SimulatorProcessInfo.h
fdbrpc/include/fdbrpc/simulator.h
fdbrpc/sim2.actor.cpp
fdbserver/BlobManager.actor.cpp
fdbserver/workloads/BlobFailureInjection.actor.cpp
flow/FaultInjection.cpp
flow/include/flow/FaultInjection.h
tests/fast/BlobGranuleMoveVerifyCycle.toml
tests/fast/BlobGranuleVerifyAtomicOps.toml
tests/fast/BlobGranuleVerifyCycle.toml
tests/fast/BlobGranuleVerifySmall.toml
tests/rare/BlobGranuleRanges.toml
tests/restarting/from_71.3.0/BlobGranuleRestartCycle-1.toml
tests/restarting/from_71.3.0/BlobGranuleRestartCycle-2.toml
tests/restarting/from_71.3.0/BlobGranuleRestartLarge-1.toml
tests/restarting/from_71.3.0/BlobGranuleRestartLarge-2.toml
tests/slow/BlobGranuleCorrectness.toml
tests/slow/BlobGranuleVerifyBalance.toml
tests/slow/BlobGranuleVerifyLarge.toml

Cherry-Pick of #9833
Fixing a testing gap by making the simulated blobstore implementation flaky and/or completely broken for a period of time, for either all servers or a subset of servers, and included it in the blob granule tests.
Fixed a couple small bugs that came up as a result of this testing.
We can eventually extend this to work outside of simulation, enable it for all workloads, add other error types, etc...
Passes 100k BlobGranule* correctness tests, with only 2 failures being unrelated. 1 is fixed by #9780 and the other is documented by issue #9834.
Please check each of the following things and check *all* boxes before accepting …

Adding BlobFailureInjection workload (Cherry-Pick #9833 to snowflake/release-71.3)

---

fdbclient/ManagementAPI.actor.cpp
fdbclient/include/fdbclient/ManagementAPI.actor.h
fdbserver/BlobWorker.actor.cpp
fdbserver/Ratekeeper.actor.cpp

Cherry-Pick of #9864
and several debugging improvements
Passes 10k BlobGranule* correctness.

adding system priority option to getDatabaseConfiguration (Cherry-Pick #9864 to snowflake/release-71.3)

---

fdbserver/DDTeamCollection.actor.cpp

Cherry-Pick of #9911
In this simulation test, there were 2 transaction class processes and one storage class processes in one of the data halls.
Fault injection was enabled on the storage and one of the transaction processes.
During the test, the storage processes kept getting io_timeouts. In this case, our desired behavior is to "hang" the storage process and try to rebuild a third replica from the other storage processes, because an io_timeout can indicate larger problems with a disk, including durability problems.
However, because recruitment did not exclude failed processes, and allows itself to recruit up to 3 storage servers on one process, we eventually had 3 storage servers that were all hung in this io_timeout state on the one storage class process.
And, …

solving strange recruitment deadlock in three_data_hall (Cherry-Pick #9911 to snowflake/release-71.3)

---

fdbcli/tests/fdbcli_tests.py

Cherry-Pick of #9902
Since `versionepoch` can trigger recovery, 
we need to wait until the database is available to move to the next test.
Otherwise, unexpected behavior can be seen as tests are added under the assumption that DB is healthy at the beginning of each test.
- Add wait at the end of the `versionepoch` fdbcli test, which triggers recovery
- Add start&end logging of each command test

Add wait at the end of the versionepoch fdbcli test which triggers recovery (Cherry-Pick #9902 to snowflake/release-71.3)

---

fdbrpc/sim2.actor.cpp

RebootProcessAndSwitch is meant to be used across an entire cluster, but it was not being applied on protected processes. When not all processes were switched to the new cluster, it was possible for a CC to log a SevError event if it connected to a coordinator that had changed clusters.

Don't downgrade RebootProcessAndSwitch to Reboot

---

fdbrpc/sim2.actor.cpp

Cherry pick #9941 
RebootProcessAndSwitch is meant to be used across an entire cluster, but it was not being applied on protected processes. When not all processes were switched to the new cluster, it was possible for a CC to log a SevError event if it connected to a coordinator that had changed clusters.

Don't downgrade RebootProcessAndSwitch to Reboot (snowflake/release-71.3)

---

fdbserver/include/fdbserver/DataDistributionTeam.h

```
src237931343/src/github.com/apple/foundationdb/build_output/fdbserver/DDTeamCollection.actor.g.cpp
distcc[9528] ERROR: compile /codebuild/output/src237931343/src/github.com/apple/foundationdb/build_output/fdbserver/DDTeamCollection.actor.g.cpp on distcc-4ef89001724141db.elb.us-west-2.amazonaws.com/96 failed
In file included from /codebuild/output/src237931343/src/github.com/apple/foundationdb/fdbserver/include/fdbserver/TCInfo.h:26,
from /codebuild/output/src237931343/src/github.com/apple/foundationdb/fdbserver/include/fdbserver/TenantCache.h:26,
from /codebuild/output/src237931343/src/github.com/apple/foundationdb/fdbserver/include/fdbserver/DataDistribution.actor.h:29,
from /codebuild/output/src237931343/src/github.com/apple/foundationdb/fdbserver/include/fdbserver/DataDistribution.a …
```

Fix gcc build warning

---

fdbrpc/sim2.actor.cpp

When usableRegions is 1, we need to treat the cluster as not being in a multi-region config when deciding whether it is legal to kill processes. For example, it is possible in this configuration that a storage team is split across multiple of the defined regions, and so we need to check whether we could be killing an entire team using all of the servers across the cluster.

Fix canKillProcesses to ignore region config when usableRegions is 1

---

flow/Platform.actor.cpp
flow/SignalSafeUnwind.cpp

The test `fdb_c_api_test_CApiRunLoopProfiler` was failing relatively frequently in sanitizer builds, running in a deadlock when the profiler signal hander is triggered in a context of code doing stack unwind and calls backtrace, which tries to acquire the same lock. 
This deadlock is avoided in normal builds by overloading `dl_iterate_phdr` and disabling the profiler in its context. This workaround is disabled in sanitizer builds, because sanitizers use this function during initialization of their state. 
This fix avoids the deadlock by disabling `backtrace` call from profiler handler in sanitizer builds. …

Avoid run loop profiler deadlocking in sanitizer builds

---

fdbserver/BlobWorker.actor.cpp

Cherry-Pick of #9784
A bug in attributing reads incorrectly in read-driven compaction meant that we would try to resnapshot twice at the same snapshot version, causing an issue.

fix for bw read driven compaction rare race (Cherry-Pick #9784 to snowflake/release-71.3)

---

fdbserver/storageserver.actor.cpp

Cherry-Pick of #9926
So that if the actor collection actor already exited due to the terminating error, we still clean up those futures. This would sometimes result in a segfault since actors would keep going after the actor collection was cleared.
Passes 50k correctness

Also clear the promise stream in actor collection on SS shutdown (Cherry-Pick #9926 to snowflake/release-71.3)

---

bindings/c/fdb_c.cpp
bindings/c/foundationdb/fdb_c.h
fdbclient/BlobCipher.cpp
fdbclient/BlobGranuleFiles.cpp
fdbclient/include/fdbclient/BlobCipher.h
fdbclient/include/fdbclient/BlobGranuleCommon.h
fdbclient/include/fdbclient/EncryptKeyProxyInterface.h
fdbclient/include/fdbclient/GetEncryptCipherKeys_impl.actor.h
fdbserver/EncryptKeyProxy.actor.cpp
fdbserver/IPager.cpp
fdbserver/RESTKmsConnector.actor.cpp
fdbserver/SimKmsConnector.actor.cpp
fdbserver/include/fdbserver/IPageEncryptionKeyProvider.actor.h
fdbserver/include/fdbserver/KmsConnectorInterface.h
fdbserver/workloads/EncryptionOps.actor.cpp
flow/include/flow/EncryptUtils.h
flow/include/flow/error_definitions.h
flowbench/BenchEncrypt.cpp

Description
Key Check Value (KCV) is a checksum of cryptographic encryption key used to validate encryption keys's integrity. FDB Encryption at-rest relies on external KMS to supply encryption keys.
Patch proposes following major changes:
1. Implement Sha256 based KCV implementation to protect against 'baseCipher' corruption in two possible scenarios:
a) potential corruption external to FDB
b) potential corruption within FDB processes.
2. Scheme persists computed KCV token in block encryption header, which then gets validated as part of header validation during decryption.
3. FDB Encryption key derivation uses HMAC_SHA256 digest generation scheme, which allows max 64 bytes of 'cipher buffer', patch add required check to ensure 'baseCipher' length are within bounds. OpenSSL HMAC underlying …

EaR: Implement Key Check Value semantics

---

bindings/python/fdb/impl.py

Cherry-pick of https://github.com/apple/foundationdb/pull/9940
This exposes a C binding needed to facilitate tenant movement, but was only present in the C and Java bindings.

Expose list_blobbified_ranges for tenants in python API (Cherry-Pick #9940 to snowflake/release-71.3)

---

fdbclient/NativeAPI.actor.cpp
fdbclient/SystemData.cpp
fdbclient/include/fdbclient/SystemData.h
fdbserver/BlobManager.actor.cpp

To support later attaching a metadata struct to each range after 71.3

refactoring and adding future compatibility to blob range metadata

---

flow/Arena.cpp
flow/FastAlloc.cpp
flow/include/flow/FastAlloc.h

Test for `WipeAfterUse`+`Arena` overload of `operator new` has been disabled due to flakiness of pointer equivalency upon immediate reallocation of memory.
Introduce scope class and helper functions to safely, temporarily override memory (de)allocation functions underlying the Arena such that `ArenaBlock`s survive deallocation for the tests to verify correct wiping.

Fix flaky ArenaBlock wipe test

---

fdbserver/ApplyMetadataMutation.cpp

If the server tag key doesn't exist, don't send a privatized mutation to the SS.

Verify server tag key existence when handling checkpoint metadata mutation

---

fdbserver/BlobWorker.actor.cpp
fdbserver/include/fdbserver/BlobWorker.h

PR adds support for preventing an unencrypted blob worker to join an encrypted cluster or vise-versa (an encrypted blob worker joining an unencrypted cluster)
Passes 100k BlobGranule and 100k correctness

Disallow Unencrypted Blob Worker from Joining Encrypted Cluster

---

fdbclient/NativeAPI.actor.cpp
fdbclient/SystemData.cpp
fdbclient/include/fdbclient/SystemData.h
fdbserver/BlobManager.actor.cpp

Cherry-Pick of #9955
To support later attaching a metadata struct to each range after 71.3

refactoring and adding future compatibility to blob range metadata (Cherry-Pick #9955 to snowflake/release-71.3)

---

fdbserver/BlobManager.actor.cpp

Cherry-Pick of #9945
…d if BM has already been scheduled to restart

properly handling BM targeted restart injection during BM recovery an… (Cherry-Pick #9945 to snowflake/release-71.3)

---

fdbrpc/sim2.actor.cpp

Cherry pick #9956 
When usableRegions is 1, we need to treat the cluster as not being in a multi-region config when deciding whether it is legal to kill processes. For example, it is possible in this configuration that a storage team is split across multiple of the defined regions, and so we need to check whether we could be killing an entire team using all of the servers across the cluster.

Fix canKillProcesses to ignore region config when usableRegions is 1 (snowflake/release-71.3)

---

flow/Platform.actor.cpp
flow/SignalSafeUnwind.cpp

Avoid run loop profiler deadlocking in sanitizer builds [snowflake/release-71.3]

---

fdbserver/tester.actor.cpp

I introduced a small bug in #9599 -- this is fixing it.

Trigger timeout event in correct place in tester

---

bindings/c/fdb_c.cpp
bindings/c/foundationdb/fdb_c.h
fdbclient/BlobCipher.cpp
fdbclient/BlobGranuleFiles.cpp
fdbclient/include/fdbclient/BlobCipher.h
fdbclient/include/fdbclient/BlobGranuleCommon.h
fdbclient/include/fdbclient/EncryptKeyProxyInterface.h
fdbclient/include/fdbclient/GetEncryptCipherKeys_impl.actor.h
fdbserver/EncryptKeyProxy.actor.cpp
fdbserver/IPager.cpp
fdbserver/RESTKmsConnector.actor.cpp
fdbserver/SimKmsConnector.actor.cpp
fdbserver/include/fdbserver/IPageEncryptionKeyProvider.actor.h
fdbserver/include/fdbserver/KmsConnectorInterface.h
fdbserver/workloads/EncryptionOps.actor.cpp
flow/include/flow/EncryptUtils.h
flow/include/flow/error_definitions.h
flowbench/BenchEncrypt.cpp

* EaR: Implement Key Check Value semantics
Description
Key Check Value (KCV) is a checksum of cryptographic encryption key used to validate encryption keys's integrity. FDB Encryption at-rest relies on external KMS to supply encryption keys.
Patch proposes following major changes:
1. Implement Sha256 based KCV implementation to protect against 'baseCipher' corruption in two possible scenarios:
a) potential corruption external to FDB
b) potential corruption within FDB processes.
2. Scheme persists computed KCV token in block encryption header, which then gets validated as part of header validation during decryption.
3. FDB Encryption key derivation uses HMAC_SHA256 digest generation scheme, which allows max 64 bytes of 'cipher buffer', patch add required check to ensure 'baseCipher' length …

[snowflake/release-71.3 cherry-pick] EaR: Implement Key Check Value semantics (#9936)

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/GlobalTagThrottler.actor.cpp

This knob can be used to reduce the frequency of `GlobalTagThrottler_Got*Rate` trace events.

Add `GLOBAL_TAG_THROTTLING_TRACE_INTERVAL` knob

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/Ratekeeper.actor.cpp
fdbserver/TransactionTagCounter.cpp

These knobs' names refer to pages, but previously their meaning still assumed they referred to bytes. This PR fixes this discrepancy. It also updates the default value of `MIN_TAG_WRITE_PAGES_RATE` to match the default value of `MIN_TAG_READ_PAGES_RATE`.

Fix semantics of `MIN_TAG_*_PAGES_RATE` knobs

---

bindings/c/fdb_c.cpp
bindings/c/foundationdb/fdb_c.h
bindings/c/test/unit/fdb_api.cpp
bindings/c/test/unit/fdb_api.hpp
bindings/c/test/unit/unit_tests.cpp
bindings/java/fdbJNI.cpp
bindings/java/src/integration/com/apple/foundationdb/MappedRangeQueryIntegrationTest.java
bindings/java/src/main/com/apple/foundationdb/FDBTransaction.java
bindings/java/src/main/com/apple/foundationdb/MappedRangeQuery.java
bindings/java/src/main/com/apple/foundationdb/ReadTransaction.java
fdbclient/MultiVersionTransaction.actor.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/ReadYourWrites.actor.cpp
fdbclient/ThreadSafeTransaction.cpp
fdbclient/include/fdbclient/FDBTypes.h
fdbclient/include/fdbclient/IClientApi.h
fdbclient/include/fdbclient/ISingleThreadTransaction.h
fdbclient/include/fdbclient/MultiVersionTransaction.h
fdbclient/include/fdbclient/NativeAPI.actor.h
fdbclient/include/fdbclient/PaxosConfigTransaction.h
fdbclient/include/fdbclient/ReadYourWrites.h
fdbclient/include/fdbclient/SimpleConfigTransaction.h
fdbclient/include/fdbclient/StorageServerInterface.h
fdbclient/include/fdbclient/ThreadSafeTransaction.h
fdbserver/include/fdbserver/workloads/ApiWorkload.h
fdbserver/storageserver.actor.cpp
fdbserver/workloads/GetMappedRange.actor.cpp

It is not protocol compatible, revert it to avoid deployment issue. Will have a new PR to have the feature if moving forward.
20230331-171550-haofu-b3f97a64ee29bdaa

Revert matchIndex feature

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/GlobalTagThrottler.actor.cpp

This is a backport of https://github.com/apple/foundationdb/pull/9982.

(snowflake/release-71.3) Add `GLOBAL_TAG_THROTTLING_TRACE_INTERVAL` knob

---

fdbclient/include/fdbclient/StorageServerInterface.h
fdbserver/include/fdbserver/TLogInterface.h

This is a backport of https://github.com/apple/foundationdb/pull/9976.

(snowflake/release-71.3) Fix uninitialized memory issues in ratekeeper metrics

---

fdbclient/ServerKnobs.cpp

Sets more reasonable default throughput thresholds for tag throttling tracking.

Decrease `MIN_TAG_*_PAGES_RATE` defaults

---

bindings/c/fdb_c.cpp
bindings/c/foundationdb/fdb_c.h
bindings/c/test/unit/fdb_api.cpp
bindings/c/test/unit/fdb_api.hpp
bindings/c/test/unit/unit_tests.cpp
bindings/java/fdbJNI.cpp
bindings/java/src/integration/com/apple/foundationdb/MappedRangeQueryIntegrationTest.java
bindings/java/src/main/com/apple/foundationdb/FDBTransaction.java
bindings/java/src/main/com/apple/foundationdb/MappedRangeQuery.java
bindings/java/src/main/com/apple/foundationdb/ReadTransaction.java
fdbclient/MultiVersionTransaction.actor.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/ReadYourWrites.actor.cpp
fdbclient/ThreadSafeTransaction.cpp
fdbclient/include/fdbclient/FDBTypes.h
fdbclient/include/fdbclient/IClientApi.h
fdbclient/include/fdbclient/ISingleThreadTransaction.h
fdbclient/include/fdbclient/MultiVersionTransaction.h
fdbclient/include/fdbclient/NativeAPI.actor.h
fdbclient/include/fdbclient/PaxosConfigTransaction.h
fdbclient/include/fdbclient/ReadYourWrites.h
fdbclient/include/fdbclient/SimpleConfigTransaction.h
fdbclient/include/fdbclient/StorageServerInterface.h
fdbclient/include/fdbclient/ThreadSafeTransaction.h
fdbserver/include/fdbserver/workloads/ApiWorkload.h
fdbserver/storageserver.actor.cpp
fdbserver/workloads/GetMappedRange.actor.cpp

backporting https://github.com/apple/foundationdb/pull/9862
20230417-200222-haofu-666e2b9a9469a2ad 

Revert matchIndex feature (release-7.2)

---

fdbclient/BackupAgentBase.actor.cpp
fdbclient/FileBackupAgent.actor.cpp
fdbclient/include/fdbclient/GetEncryptCipherKeys_impl.actor.h
fdbserver/workloads/EncryptKeyProxyTest.actor.cpp

Currently any errors thrown by the EKP are converted to `encrypt_keys_fetch_failed`. This is incorrect and we should propagate the correct errors to the clients

Propagate Encryption Errors Properly

---

fdbclient/BackupContainer.actor.cpp
fdbclient/BackupContainerFileSystem.actor.cpp
fdbclient/BackupContainerS3BlobStore.actor.cpp
fdbclient/BlobConnectionProvider.cpp
fdbclient/include/fdbclient/BackupContainerFileSystem.h
fdbclient/include/fdbclient/BackupContainerS3BlobStore.h

Cherry-Pick of #10011
…repend "/data/" to path and to not double-slash the resource if the user-provided one ends in a slash.
Also handles backwards compatibility to 71.2 such that existing clusters that configure a url instead of using BlobMetadata continue to use the old path and logic.
Passes:
10k correctness
20k BlobGranule* correctness
10k Backup* correctness
Non-simulation - passed /fdbserver/blob/connectionprovider unit test on s3
Validated manually that path worked with and without trailing slash in resource …

Fixing path for non-backup (blob granule) blob url use cases to not p… (Cherry-Pick #10011 to snowflake/release-71.3)

---

fdbclient/BlobCipher.cpp

Description
Patch removes an unused CODE_PROBE checking the encryption header being read flag version is valid, given the flag-version is determined by peeking into std::variant index and we only have version-1 supported, for now converted the check to an ASSERT
Testing
EncryptionUnitTests.toml
BlobGranuleCorrectness/Clean.toml

EaR: Remove unused CODE_PROBE handling encrpyiton header flag version

---

fdbserver/include/fdbserver/DataDistributionTeam.h

Cherry-Pick of #9948
```
src237931343/src/github.com/apple/foundationdb/build_output/fdbserver/DDTeamCollection.actor.g.cpp
distcc[9528] ERROR: compile /codebuild/output/src237931343/src/github.com/apple/foundationdb/build_output/fdbserver/DDTeamCollection.actor.g.cpp on distcc-4ef89001724141db.elb.us-west-2.amazonaws.com/96 failed
In file included from /codebuild/output/src237931343/src/github.com/apple/foundationdb/fdbserver/include/fdbserver/TCInfo.h:26,
from /codebuild/output/src237931343/src/github.com/apple/foundationdb/fdbserver/include/fdbserver/TenantCache.h:26,
from /codebuild/output/src237931343/src/github.com/apple/foundationdb/fdbserver/include/fdbserver/DataDistribution.actor.h:29,
from /codebuild/output/src237931343/src/github.com/apple/foundationdb/fdb …
```

Fix gcc build warning (Cherry-Pick #9948 to snowflake/release-71.3)

---

fdbclient/NativeAPI.actor.cpp
fdbserver/tester.actor.cpp

Cherry-Pick of #9966
In `clearData()` used by simulation test to clean up, we re-use the same debugID for multiple transactions,
making it less clear when grepping for the debugID. This PR assigns a new debugID for each new transaction.
Some of the commented-out tracing code are already obsolete, I updated several of them, but am not sure if
the tracing should be enabled when enabling debug transaction.
Finally, use different but similar with the same prefix error messages for different call stacks. …

Improve logging for test (Cherry-Pick #9966 to snowflake/release-71.3)

---

fdbclient/BlobGranuleFiles.cpp
fdbserver/SimKmsConnector.actor.cpp
fdbserver/storageserver.actor.cpp

- removing code probes in BlobGranuleFiles in code that can be executed off-network-thread for tsan
- sending error that actually propagates back to the client for testing to fix "blob metadata fetch error" probe being missed
- marked change feed probe as rare

fixing code probe issues

---

fdbserver/DDRelocationQueue.actor.cpp
fdbserver/DDShardTracker.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/include/fdbserver/DDRelocationQueue.h
fdbserver/include/fdbserver/DataDistribution.actor.h
flow/include/flow/genericactors.actor.h

Cherry-Pick of #9991
For write-bandwidth-based splits, we want to know whether the split decision is good by looking at the storage metrics of parent shard and splitted shard. Otherwise, it is hard to tell if the splitter acted as expected.
The next step might be to use the ongoing shard re-evaluation project to prevent unnecessary splitting movement.

Log the relocation decision at the time of launching relocations (Cherry-Pick #9991 to snowflake/release-71.3)

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/Ratekeeper.actor.cpp

If this knob is set to true, the global tag throttler will still compute rates, but these rates won't be sent to GRV proxies for enforcement.

Add `GLOBAL_TAG_THROTTLING_REPORT_ONLY` knob

---

fdbclient/BlobCipher.cpp

Description
Patch removes an unused CODE_PROBE checking the encryption header being read flag version is valid, given the flag-version is determined by peeking into std::variant index and we only have version-1 supported, for now converted the check to an ASSERT
Testing
EncryptionUnitTests.toml
BlobGranuleCorrectness/Clean.toml
(cherry picked from commit a099d377fa212d23d420cf5a05d987d8e468c1e2)
Cherrypick PR #10020

EaR: Remove unused CODE_PROBE handling encryption header flag version (#10020)

---

fdbclient/BlobGranuleFiles.cpp
fdbserver/SimKmsConnector.actor.cpp
fdbserver/storageserver.actor.cpp

Cherry-Pick of #10023
- removing code probes in BlobGranuleFiles in code that can be executed off-network-thread for tsan
- sending error that actually propagates back to the client for testing to fix "blob metadata fetch error" probe being missed
- marked change feed probe as rare

fixing code probe issues (Cherry-Pick #10023 to snowflake/release-71.3)

---

fdbcli/TenantCommands.actor.cpp
fdbclient/include/fdbclient/TenantManagement.actor.h
fdbserver/workloads/TenantManagementWorkload.actor.cpp
metacluster/include/metacluster/ListTenants.actor.h

Cherry-Pick of #9967
This provides the client a simpler way to filter tenants by their tenant groups, as well as adding some useful additional info (tenant IDs) that can be retrieved in bulk. 
Some sample output on a metacluster with the following tenant locations:
| Tenant | Cluster | Tenant Group |
|--------|---------|--------------|
| t1     | d1      | tg1          |
| t2     | d2      | tg2          |
| t3     | d1      | tg1          |
| t4     | d1      | tg1          |
| t5     | d2      | tg2          |
| t6     | d1      | tg3          |
On the management cluster:
```
fdb> tenant list a z
1. t1
2. t2
3. t3
4. t4
5. t5
6. t6
fdb> tenant list a z tenant_group=tg1
1. t1
2. t2
3. t4
fdb> tenant list a z tenant_group=tg2
1. t3
2. t5
fdb> tenant list a z …
```

Update fdbcli tenant list function to take tenant group filter, support JSON, and report tenant IDs (Cherry-Pick #9967 to snowflake/release-71.3)

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/Ratekeeper.actor.cpp

This is a backport of https://github.com/apple/foundationdb/pull/10005.

(snowflake/release-71.3) Add `GLOBAL_TAG_THROTTLING_REPORT_ONLY` knob

---

fdbserver/include/fdbserver/WorkerInterface.actor.h

So that it wouldn't hide bugs where something in the disk queue or storage engine gets stuck but works after a reboot as the test wouldn't fail so the hang would not be exposed as an issue.
The issue for #9913 is solved by increasing TLOG_MAX_CREATE_DURATION in simulation, which is already done in commit 0aa096dc1.

Revert error masking in #9913

---

fdbclient/ServerKnobs.cpp
fdbserver/WorkerInterface.actor.h

There were cases this would cause failure in simulation, where the commit time just exceeds 10s.
From commit https://github.com/apple/foundationdb/commit/0aa096dc17ecf5267ec0691942c461bfa33e1e0a:
```
// In some rare simulation tests, particularly with log_spill:=1 configured, the 10 second limit is exceeded, causing SevError trace events
// and simulation test failure. Increasing the knob value to 15.0 in simulation is a workaround to avoid these failures.
```

Double TLOG_MAX_CREATE_DURATION in simulation [release-7.1]

---

fdbserver/tester.actor.cpp

In `clearData()`, the second transaction may retry on the no-exception path. We need to
call `debugTransaction()` to reset the debugID there as well.

Call debugTransaction() before retry

---

fdbserver/tester.actor.cpp

This makes tooling scripts easier to write, because tracing is consistent at all stages of test progress.

Make test progress tracing in `runWorkload` consistent

---

fdbserver/workloads/TenantManagementWorkload.actor.cpp

Cherry-Pick of https://github.com/apple/foundationdb/pull/10030
Fix a test issue from nightly correctness runs by accounting for limit parameter

Fix tenant test to account for limit parameter (Cherry-Pick #10030 to snowflake/release-71.3) 

---

fdbserver/Status.actor.cpp

Cherry-pick #10044
Validate if the url is not empty before calling openContainer

Empty check before opening backup container for mutation logs

---

fdbclient/NativeAPI.actor.cpp
fdbclient/include/fdbclient/DatabaseContext.h
fdbserver/CommitProxyServer.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/workloads/AuthzSecurity.actor.cpp

When a commit proxy becomes overloaded, it will send back `commit_proxy_memory_limit_exceeded` error. This error is often not caught, e.g., in storage server's fetch key operation. We've seen `StorageServerFailed` in live clusters due to this problem. The proposed solution is to catch this error and automatically retry the request with backoffs, which is a per database backoff, instead of the normal per transaction backoff. The current thinking is that once the database is overloaded, we should avoid sending too many `GetKeyServerLocationsRequest` to commit proxies.
Also added buggify to inject the error in simulation for `GetTenantIdRequest` as well and fixed some issues found.
The backoff logic is at the database level: for each error, double the backoff time (starting at 0.01s); for …

Properly handle proxy_memory_limit_exceeded error for GetKeyServerLocationsRequest

---

fdbserver/tester.actor.cpp

Cherry-Pick of #10033
In `clearData()`, the second transaction may retry on the no-exception path. We need to
call `debugTransaction()` to reset the debugID there as well.

Call debugTransaction() before retry (Cherry-Pick #10033 to snowflake/release-71.3)

---

.git-blame-ignore-revs
fdbclient/DatabaseContext.h
fdbclient/NativeAPI.actor.cpp
fdbserver/CommitProxyServer.actor.cpp
fdbserver/storageserver.actor.cpp

cherrypick #10010
When a commit proxy becomes overloaded, it will send back commit_proxy_memory_limit_exceeded error. This error is often not caught, e.g., in storage server's fetch key operation. We've seen StorageServerFailed in live clusters due to this problem. The proposed solution is to catch this error and automatically retry the request with backoffs, which is a per database backoff, instead of the normal per transaction backoff. The current thinking is that once the database is overloaded, we should avoid sending too many GetKeyServerLocationsRequest to commit proxies.
Also added buggify to inject the error in simulation.
The backoff logic is at the database level: for each error, double the backoff time (starting at 0.01s); for each success, half the backoff time (when less than …

Properly handle proxy_memory_limit_exceeded error for GetKeyServerLocationsRequest [release-7.1]

---

fdbserver/DataDistribution.actor.cpp
fdbserver/worker.actor.cpp
fdbserver/workloads/SnapTest.actor.cpp
flow/include/flow/error_definitions.h

This is the fix when you run snapshot restarting tests and issue duplicate snapshot requests.
Details are commented on the change of the code.
The fix basically contains the following:
- Commit proxy sends the newly added `duplicate_snapshot_request` error back when the old request is discarded.
- SnapTest retry and error handling for the error

Fix for correctness failures when issuing duplicate snapshot requests

---

bindings/flow/FDBLoanerTypes.h
fdbclient/MutationLogReader.actor.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/include/fdbclient/FDBTypes.h
fdbserver/BlobManifest.actor.cpp
fdbserver/BlobRestoreController.actor.cpp
fdbserver/KeyValueStoreMemory.actor.cpp
fdbserver/KeyValueStoreRocksDB.actor.cpp
fdbserver/KeyValueStoreSQLite.actor.cpp
fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
fdbserver/StorageCache.actor.cpp
fdbserver/VersionedBTree.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/workloads/BlobRestoreWorkload.actor.cpp
fdbserver/workloads/StreamingRangeRead.actor.cpp

Fix a few `RangeResult.readThrough` misuses:
1. `KeyValueStore`s do not need to set readThrough, as it will not be serialized and return. Also setting it to the last key of the result is not right, it should at least be the keyAfter of the last key;
2. Fix NativeAPI doesn't set `RangeResult.more` in a few places;
3. Avoid `tryGetRange()` setting `readThrough` when `more` is false, which was a workaround for the above item 2;
4. `tryGetRangeFromBlob()` doesn't set `more` but set `readThrough` to indicate it is end, which was following the same above workaround I think. Fixed that.
5. `getRangeStream()` is going to set `more` to true and then let the `readThrough` be it's boundary.
Also added readThrough getter/setter function to validate it's usage.
Replace this text with your description …

Fix RangeResult.readThrough misuse

---

fdbserver/workloads/MetaclusterManagementConcurrencyWorkload.actor.cpp
fdbserver/workloads/MetaclusterRestoreWorkload.actor.cpp
fdbserver/workloads/TenantCapacityLimits.actor.cpp
fdbserver/workloads/TenantManagementConcurrencyWorkload.actor.cpp
fdbserver/workloads/TenantManagementWorkload.actor.cpp
metacluster/MetaclusterUtil.actor.cpp
metacluster/include/metacluster/MetaclusterConsistency.actor.h
metacluster/include/metacluster/MetaclusterData.actor.h
metacluster/include/metacluster/MetaclusterUtil.actor.h
metacluster/include/metacluster/TenantConsistency.actor.h

There are several workloads that need to create a metacluster, and this adds a function that can be called to help do that. This function is used in all workloads that create metaclusters except for the metacluster management workload, which will be changed in a subsequent PR.

Add a utility function for creating a simulated metacluster

---

fdbserver/workloads/MetaclusterManagementConcurrencyWorkload.actor.cpp
fdbserver/workloads/MetaclusterRestoreWorkload.actor.cpp
fdbserver/workloads/TenantCapacityLimits.actor.cpp
fdbserver/workloads/TenantManagementConcurrencyWorkload.actor.cpp
fdbserver/workloads/TenantManagementWorkload.actor.cpp
metacluster/MetaclusterUtil.actor.cpp
metacluster/include/metacluster/MetaclusterConsistency.actor.h
metacluster/include/metacluster/MetaclusterData.actor.h
metacluster/include/metacluster/MetaclusterUtil.actor.h
metacluster/include/metacluster/TenantConsistency.actor.h

Cherry-pick #10057 
There are several workloads that need to create a metacluster, and this adds a function that can be called to help do that. This function is used in all workloads that create metaclusters except for the metacluster management workload, which will be changed in a subsequent PR.

Add a utility function for creating a simulated metacluster (snowflake/release-71.3)

---

fdbserver/BlobManager.actor.cpp

Fixing race in blob manager assignment that happens with delays and dead blob workers.

BM should drop continue assignment if BW is dead

---

fdbclient/DatabaseConfiguration.cpp
fdbclient/include/fdbclient/DatabaseConfiguration.h

…) regardless of whether the user sets it explicitly. If the existing process count is not enough for the default configuration, we can detect that.
Note: The change is not in Apple branch in case the cluster monitor tool use different semantic meaning.
Configured values for
- grv_proxies
- commit_proxies
- resolvers
- logs
are reported in status json in the cluster.configuration section.
Default values are not reported if they have never been changed manually and are defaulting to a value determined by fdb.
This should be changed to report default values in the status json, so efdb can properly import the current state of the role counts. This can be especially problematic if the default on fdb side where to change since we have no way of learning about it.
Manually fdbcli test:
``` …
```

make status json report desired role count (log, resolver, proxies...… 

---

fdbserver/ConsistencyScan.actor.cpp

ConsistencyCheck thinks the shard is too large and should be split. However, it is possible that the split point returned by the Storage Server is discarded due to "unfair" sizes after the split. Fix this problem by checking if this is the case in ConsistencyCheck.
20230427-215044-jzhou-a3e4bb4d97f3bd02
Reproduction:
- `-f ./tests/fast/FuzzApiCorrectness.toml -s 749622535 -b on`
- 7.1 Commit ID: d4ffd358d676869e144aff38565406291138021d
- gcc

Fix ConsistencyCheck_InvalidShardSize due to unfair split

---

fdbclient/NativeAPI.actor.cpp
fdbclient/include/fdbclient/DatabaseContext.h
fdbserver/CommitProxyServer.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/workloads/AuthzSecurity.actor.cpp

cherrypick #10010
20230425-204730-jzhou-2b6193cd6bff3a7b

Properly handle proxy_memory_limit_exceeded error for GetKeyServerLocationsRequest [release-7.3]

---

fdbserver/DDTeamCollection.actor.cpp

Cherry-Pick of #10028
Add trace event "TeamEligibilityCount" to indicate that how many team has passed CPU or Space pivot check.

Add trace event "TeamEligibilityCount" (Cherry-Pick #10028 to snowflake/release-71.3)

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/DDShardTracker.actor.cpp
fdbserver/DDTeamCollection.actor.cpp

the fallback path for too many large teams needs to be based on the number of shards rather than number of teams for instances where the large team uses the majority of servers

fix: do not let too many shards use large teams

---

fdbserver/ConsistencyScan.actor.cpp
fdbserver/include/fdbserver/DataDistributionTeam.h

cherrypick #10066 and #9948
ConsistencyCheck thinks the shard is too large and should be split. However, it is possible that the split point returned by the Storage Server is discarded due to "unfair" sizes after the split. Fix this problem by checking if this is the case in ConsistencyCheck.
20230428-210937-jzhou-93595c8410e21461

Fix ConsistencyCheck_InvalidShardSize due to unfair split [release-7.3]

---

flow/Trace.cpp
flow/include/flow/Trace.h

Cherry-Pick of #9326
CommitDebug trace events are useful for measuring, in detail, the time spent in the various parts of a single transaction. Like all log events, they have a time associated with them. This time comes for now(), which in a real fdb system is only updated in the run loop. This renders the timestamps inaccurate in certain CPU bound sections which don't have a wait, e.g. in the resolver.
The desired solution is to directly call ::timer_monotonic() instead of now() for a timestamp, since ::timer_monotonic() is what now() ultimately uses in the run loop, but is updated between waits as well.
In order to not disrupt any current uses of the logs which might depend on the current behavior of the Time field, we introduced the `MonotonicTime` field.
This …

Add timer_monotonic() to CommitDebug trace events. (Cherry-Pick #9326 to snowflake/release-71.2)

---

documentation/sphinx/source/mr-status-json-schemas.rst.inc
fdbclient/MetaclusterRegistration.cpp
fdbclient/Schemas.cpp
fdbclient/include/fdbclient/MetaclusterRegistration.h
fdbserver/ApplyMetadataMutation.cpp
fdbserver/ClusterController.actor.cpp
fdbserver/ClusterRecovery.actor.cpp
fdbserver/Status.actor.cpp
fdbserver/include/fdbserver/ClusterController.actor.h
fdbserver/include/fdbserver/Status.actor.h
fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp
fdbserver/workloads/TenantManagementWorkload.actor.cpp
flow/include/flow/error_definitions.h
metacluster/MetaclusterMetrics.actor.cpp
metacluster/include/metacluster/CreateMetacluster.actor.h
metacluster/include/metacluster/MetaclusterConsistency.actor.h
metacluster/include/metacluster/MetaclusterMetrics.h

This add a version field to `MetaclusterRegistrationEntry` and enforces that the version be a legal version when performing metacluster operations. This will help to prevent an old version of an FDB client from modifying metacluster state if the metadata format has changed.
The implementation is in the first commit, tests are added in the second commit.

Add a metacluster version to the MetaclusterRegistrationEntry and validate it when loading the entry

---

fdbserver/ConsistencyScan.actor.cpp

We know that the hash function used for sampling keys is biased and oversamples.
The fix is non-trivial, since we can't straightforwardly change the sampling function
for existing FDB databases. Thus, we downgrade this particular test failure to a warning.

Downgrade "inaccurate shard estimate" consistency check to warning, not test failure.

---

fdbserver/DiskQueue.actor.cpp
fdbserver/TLogServer.actor.cpp
fdbserver/include/fdbserver/IDiskQueue.h
fdbserver/include/fdbserver/LogSystemDiskQueueAdapter.h

We encountered a situation in simulation where the disk queue was in the following state
+------------+------------+
| page 1     | page 2     |
+------------+------------+
|rec |.......|rec |.......|
+------------+------------+
0..85        4096..4181
^.   ^__             ^
popped. committed    pushed
and we attempted to pop up to 4096, i.e. everything before page 2. This triggered one of the assertions in the disk queue code which was meant to catch tlog logic bugs where we pop too much.
The issue, though, is the accounting of the commit location in the disk queue. While we only pushed records through posiiton 85, we committed the entire page. Attempts to pop everything before page 2 should have succeeded since we're not attempting to pop any uncommitted data.
The solution is to fix the …

Fix commit location accounting in DiskQueue.

---

documentation/sphinx/source/mr-status-json-schemas.rst.inc
fdbclient/MetaclusterRegistration.cpp
fdbclient/Schemas.cpp
fdbclient/include/fdbclient/MetaclusterRegistration.h
fdbserver/ApplyMetadataMutation.cpp
fdbserver/ClusterController.actor.cpp
fdbserver/ClusterRecovery.actor.cpp
fdbserver/Status.actor.cpp
fdbserver/include/fdbserver/ClusterController.actor.h
fdbserver/include/fdbserver/Status.actor.h
fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp
fdbserver/workloads/TenantManagementWorkload.actor.cpp
flow/include/flow/error_definitions.h
metacluster/MetaclusterMetrics.actor.cpp
metacluster/include/metacluster/CreateMetacluster.actor.h
metacluster/include/metacluster/MetaclusterConsistency.actor.h
metacluster/include/metacluster/MetaclusterMetrics.h

Cherry picks #10047 
This add a version field to MetaclusterRegistrationEntry and enforces that the version be a legal version when performing metacluster operations. This will help to prevent an old version of an FDB client from modifying metacluster state if the metadata format has changed.

Add a metacluster version to the MetaclusterRegistrationEntry and validate it when loading the entry (snowflake/release-71.3)

---

.pre-commit-config.yaml

The pre-commit config would not properly parse due to bad indentation

Fix bad indentation in the pre-commit config

---

fdbcli/ExcludeCommand.actor.cpp

For operational purposes, the help message was unclear and confusing because it did not distinguish between `excluded` and `failed`. This change aims to help clarify the differences.

Separate failed and excluded servers on fdbcli output

---

fdbcli/ExcludeCommand.actor.cpp

Cherry-Pick of #10089
For operational purposes, the help message was unclear and confusing because it did not distinguish between `excluded` and `failed`. This change aims to help clarify the differences.

Separate failed and excluded servers on fdbcli output (Cherry-Pick #10089 to snowflake/release-71.3)

---

fdbclient/ServerKnobs.cpp

When a storage server is overloaded by queries, writing to disk is stalled. LOW_PRIORITY_DURABILITY_LAG is supposed to make sure that when durability lag is high, we convert queries to low priority queries so that commit has a chance to write to disk.
Currently LOW_PRIORITY_DURABILITY_LAG is 200M versions (roughly 3 minutes of commits) where as MAX_STORAGE_COMMIT_TIME is 120 seconds. Therefore, we need to make MAX_STORAGE_COMMIT_TIME is inline with LOW_PRIORITY_DURABILITY_LAG.
We could also reduce LOW_PRIORITY_DURABILITY_LAG, but when SS is overloaded with queries, writes probably has lower priority.
20230502-182449-zhewu_ss_timeout-6ed691eb06976904
Please check …

Increase MAX_STORAGE_COMMIT_TIME to be inline with LOW_PRIORITY_DURABILITY_LAG

---

fdbclient/MultiVersionTransaction.actor.cpp

Cherry-Pick of #10086 - fixed a deadlock in Multi-Version Client
Fixed several cases where a user of threadsafe async var would use the value directly and then separately call onChange instead of using get() and using the returned value and onChange from get.
Passes ctest.

fixing incorrect uses of ThreadSafeAsyncVar (Cherry-Pick #10086 to snowflake/release-71.3)

---

fdbserver/DiskQueue.actor.cpp
fdbserver/TLogServer.actor.cpp
fdbserver/include/fdbserver/IDiskQueue.h
fdbserver/include/fdbserver/LogSystemDiskQueueAdapter.h

Cherry-Pick of #10075
We encountered a situation in simulation where the disk queue was in the following state
+------------+------------+
| page 1     | page 2     |
+------------+------------+
|rec |.......|rec |.......|
+------------+------------+
0..85        4096..4181
^.   ^__             ^
popped. committed    pushed
and we attempted to pop up to 4096, i.e. everything before page 2. This triggered one of the assertions in the disk queue code which was meant to catch tlog logic bugs where we pop too much.
The issue, though, is the accounting of the commit location in the disk queue. While we only pushed records through posiiton 85, we committed the entire page. Attempts to pop everything before page 2 should have succeeded since we're not attempting to pop any …

Fix commit location accounting in DiskQueue. (Cherry-Pick #10075 to snowflake/release-71.3)

---

fdbcli/MetaclusterCommands.actor.cpp
fdbcli/tests/metacluster_fdbcli_tests.py
fdbserver/workloads/MetaclusterManagementConcurrencyWorkload.actor.cpp
fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp
metacluster/Metacluster.cpp
metacluster/include/metacluster/MetaclusterConsistency.actor.h
metacluster/include/metacluster/MetaclusterInternal.actor.h
metacluster/include/metacluster/MetaclusterTypes.h
metacluster/include/metacluster/RegisterCluster.actor.h

Cherry-Pick of #10058
This PR adds `auto_tenant_assignment` option to register/configure data clusters.
Setting `auto_tenant_assignment` to `disabled` means the data cluster is a dedicated one and won't be
used for auto tenant assignment. This option is enabled by default (allowing auto tenant assignment).
Test plan:
simulation tests and metacluster_fdbcli_tests.py

Add configuration option `auto_tenant_assignment` to data clusters (Cherry-Pick #10058 to snowflake/release-71.3)

---

fdbrpc/include/fdbrpc/AsyncFileWriteChecker.h
fdbrpc/sim2.actor.cpp
fdbserver/VersionedBTree.actor.cpp
fdbserver/include/fdbserver/VersionedBTreeDebug.h

- Move AsyncFileWriteChecker to right above SimpleFile in the file stack in simulation, which is analogous to where it is created in production and prevents false positive errors caused by stacking it on top of AsyncFileNonDurable multiple times for different users of the same file.
- Explicitly cancel background actors in ~VersionedBTree() as a precaution in case they were to have references elsewhere when the tree is destroyed.
- Make ICloseable()::close() implementations in Redwood delete the object *before* triggering the onClosed() future, just in case a future use case would try to immediately reopen the instance in the callback that handles the closed signal.
- Fix divide by zero in RedwoodMetrics if no time has passed at all in the logging period (not possible outside of …

AsyncFileWriteChecker false-positive bug fix and sim-only Redwood shutdown improvements found along the way.

---

fdbclient/GlobalConfig.actor.cpp

Original bug report: https://forums.foundationdb.org/t/100-cpu-usage-on-an-idle-cluster/3928
In FoundationDB 7.1, if a database is locked (e.g. on DR destination clusters), the following error is reported periodically in fdbserver log. This seems to cause some tasks to leak, and the `Transaction started` metric keeps increasing until useless GRVs saturate the cluster and make it no longer responsive.
```
<Event Severity="10" Time="1682418199.889216" DateTime="2023-04-25T10:23:19Z" Type="GlobalConfig_RetryableMigrationError" ID="0000000000000000" Error="database_locked" ErrorDescription="Database is locked" ErrorCode="1038" SuppressedEventCount="32350" ThreadID="14882012433472669136" Machine="10.220.11.2:4500" LogGroup="default" Roles="CC,CD,CP,DD,GP,MS,RK,RV,SS,TL" />
```
This patch sets …

Fix GlobalConfig_RetryableMigrationError when the database is locked

---

fdbserver/BackupWorker.actor.cpp
fdbserver/storageserver.actor.cpp

So that `\x00\x01` won't be logged as `\\x00\\x01`.

Avoid double escaping for SSValidateRangeKeyOutOfRange events

---

packaging/docker/samples/python/app/requirements.txt

Cherry-picks #10087. This appears to fix the doc build

testing doc build fix

---

fdbclient/ServerKnobs.cpp

[release 7.1] Increase MAX_STORAGE_COMMIT_TIME to be inline with LOW_PRIORITY_DURABILITY_LAG

---

fdbserver/fdbserver.actor.cpp
fdbserver/worker.actor.cpp
flow/SystemMonitor.cpp
flow/include/flow/SystemMonitor.h

This is a backport of https://github.com/apple/foundationdb/pull/9118.

(snowflake/release-71.2) Trace data hall id in MachineMetrics events

---

fdbclient/AuditUtils.actor.cpp
fdbclient/SystemData.cpp
fdbclient/include/fdbclient/SystemData.h
fdbserver/DataDistribution.actor.cpp
fdbserver/tester.actor.cpp

1. Cleanup audit progress metadata when audit complete;
2. Changing audit metadata name, highlighting the functionality of recording progress;
3. Tester issues audit requests directly to DD instead of CC.
100K Correctness test with 3 irrelevant failures:
20230503-195643-zhewang-9f3f469e1cacebd0           compressed=True data_size=33111807 duration=4589053 ended=100000 fail=3 fail_fast=10 max_runs=100000 pass=99997 priority=100 remaining=0 runtime=1:28:14 sanity=False started=100000 stopped=20230503-212457 submitted=20230503-195643 timeout=5400 username=zhewang
100K AduitStorageTest:
20230503-195709-zhewang-bd26ae660974c954           compressed=True data_size=33143943 duration=3145881 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 …

Adding cleanup of audit progress metadata when audit complete

---

bindings/java/src/main/com/apple/foundationdb/FDBDatabase.java
bindings/java/src/main/com/apple/foundationdb/FDBTenant.java
bindings/java/src/main/com/apple/foundationdb/FDBTransaction.java

7.3 changed the way that the used during commit option was set from a transaction option to a database default option. This option is not supported in older clients, so we cannot use it unless we specify an API version that is new enough.
This adds API version guards to use of this option and falls back to the transaction option for older versions.

Add API version protection to Java's used during commit option

---

fdbclient/ManagementAPI.actor.cpp

If a quorum of coordinators is unreliable, we could kill too many clusters such that the cluster will not recover.

Do not allow changing the coordinators to a set that is unreliable in simulation

---

contrib/TestHarness2/test_harness/summarize.py
contrib/cherry-pick-upstream.py

Also add tags when using `cherry-pick-upstream.py`

When fdbserver reports no logs, include the stderr in the TestHarness2 output

---

fdbserver/storageserver.actor.cpp

GetKeyValuesRequest keeps a reference to begin and end keys, so we must ensure the range doesn't go out of scope while the request is still being used. 
This was detected by ASAN:
```
=================================================================
==47==ERROR: AddressSanitizer: heap-use-after-free on address 0x6060068bbf48 at pc 0x000002db55f6 bp 0x7ffc2380ff60 sp 0x7ffc2380f710
READ of size 2 at 0x6060068bbf48 thread T0
#0 0x2db55f5 in MemcmpInterceptorCommon(void*, int (*)(void const*, void const*, unsigned long), void const*, void const*, unsigned long) /tmp/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:932:7
#1 0x2db5ae9 in memcmp /tmp/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:964:10
#2 0x85080c6 …
```

Fix heap use-after-free in validateRangeAgainstServer

---

fdbclient/BackupAgentBase.actor.cpp

Adds blob key ranges to system mutation logs.
Passes 10k Backup* correctness.

adding blob ranges to backup keys to not lose blobbification on restore

---

bindings/java/src/main/com/apple/foundationdb/FDBDatabase.java
bindings/java/src/main/com/apple/foundationdb/FDBTenant.java
bindings/java/src/main/com/apple/foundationdb/FDBTransaction.java

Cherry-picks #10126 
71.3 changed the way that the used during commit option was set from a transaction option to a database default option. This option is not supported in older clients, so we cannot use it unless we specify an API version that is new enough.
This adds API version guards to use of this option and falls back to the transaction option for older versions.

Add API version protection to Java's used during commit option (snowflake/release-71.3)

---

fdbserver/BlobManager.actor.cpp

Cherry-Pick of #9987
Fixing race in blob manager assignment that happens with delays and dead blob workers.

BM should drop continue assignment if BW is dead (Cherry-Pick #9987 to snowflake/release-71.3)

---

fdbclient/ManagementAPI.actor.cpp

Cherry-pick #10129
If a quorum of coordinators is unreliable, we could kill too many clusters such that the cluster will not recover.

Do not allow changing the coordinators to a set that is unreliable in simulation (snowflake/release-71.3)

---

fdbserver/DDRelocationQueue.actor.cpp

Cherry-Pick of #10076
Let BytesWritten in MovingData trace event show the actually moved bytes taking into account non-overlapped server lists.

Enable MovingData to show overall moved bytes rather than just one copy (Cherry-Pick #10076 to snowflake/release-71.3)

---

fdbclient/ClientKnobs.cpp

The previous buggified value 3 can be the same as key location size, thus causing `splitStorageMetrics()` to stuck.
Fixes #10153

Increase buggified STORAGE_METRICS_SHARD_LIMIT value

---

fdbclient/ClientKnobs.cpp

cherrypick #10150
The previous buggified value 3 can be the same as key location size, thus causing splitStorageMetrics() to stuck.
Reproduction:
seed: `-f ./tests/fast/MutationLogReaderCorrectness.toml -s 930331995 -b on`
commit: [5fe1bd8c2b2478238992c56fb49d30d1abb3678f](https://github.com/apple/foundationdb/commit/5fe1bd8c2b2478238992c56fb49d30d1abb3678f)
gcc
20230505-024756-jzhou-8c4e8a33365b52c7

Increase buggified STORAGE_METRICS_SHARD_LIMIT value [release-7.1]

---

fdbclient/SystemData.cpp

Cherry-Pick of #10157
Bug fix, check is supposed to be for overlap, not lack of overlap.

Bug fix, check is supposed to be for overlap, not lack of overlap. (Cherry-Pick #10157 to snowflake/release-71.3)

---

fdbserver/storageserver.actor.cpp

This PR introduces AuditStorageStatistic trace event to:
(1) Understand the progress of audit storage;
(2) Understand the fragment of serverKeys introduced by encode_shard_location_metadata.
100K correctness test with 2 irrelevant failures
20230504-223330-zhewang-b9c720dd6272566a           compressed=True data_size=33126674 duration=6473460 ended=100000 fail=2 fail_fast=10 max_runs=100000 pass=99998 priority=100 remaining=0 runtime=1:12:45 sanity=False started=100000 stopped=20230504-234615 submitted=20230504-223330 timeout=5400 username=zhewang
100K ValidateStorage test
20230504-223406-zhewang-eaa2bcbcd54aaef1           compressed=True data_size=33155985 duration=3378096 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:52:40 sanity=False …

Audit storage statistic

---

fdbserver/DDTeamCollection.actor.cpp

Cherry-Pick of #10028
Add trace event "TeamEligibilityCount" to indicate that how many team has passed CPU or Space pivot check.

Add trace event "TeamEligibilityCount" (Cherry-Pick #10028 to snowflake/release-71.2)

---

fdbserver/MoveKeys.actor.cpp

A bug caused by typo in #10067 

Fix bug: isEnabled() to !isEnabled()

---

fdbclient/include/fdbclient/BlobGranuleCommon.h
fdbserver/BlobManager.actor.cpp
fdbserver/BlobManifest.actor.cpp
fdbserver/BlobMigrator.actor.cpp
fdbserver/BlobWorker.actor.cpp
fdbserver/include/fdbserver/BlobGranuleServerCommon.actor.h
fdbserver/storageserver.actor.cpp
fdbserver/workloads/BlobGranuleCorrectnessWorkload.actor.cpp
fdbserver/workloads/BlobRestoreWorkload.actor.cpp

Cherry-Pick of #10081
Add encryption support for blob manifest files. Passed 100K Blob test

Add manifest encryption (Cherry-Pick #10081 to snowflake/release-71.3)

---

flow/ProtocolVersion.h

Downgrading from 7.3 to 7.2 is broken due to missing blobbify related functions in 7.2 branch (a testing branch). To make downgrade test work, we need to allow downgrading from 7.3 to 7.1.

[release 7.1] Update 7.1 minInvalidProtocolVersion to 7.4 to make downgrading from 7.3 to 7.1 work

---

fdbserver/storageserver.actor.cpp

Cherry-Pick of #10132
GetKeyValuesRequest keeps a reference to begin and end keys, so we must ensure the range doesn't go out of scope while the request is still being used. 
This was detected by ASAN:
```
=================================================================
==47==ERROR: AddressSanitizer: heap-use-after-free on address 0x6060068bbf48 at pc 0x000002db55f6 bp 0x7ffc2380ff60 sp 0x7ffc2380f710
READ of size 2 at 0x6060068bbf48 thread T0
#0 0x2db55f5 in MemcmpInterceptorCommon(void*, int (*)(void const*, void const*, unsigned long), void const*, void const*, unsigned long) /tmp/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:932:7
#1 0x2db5ae9 in memcmp /tmp/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_ …
```

Fix heap use-after-free in validateRangeAgainstServer (Cherry-Pick #10132 to snowflake/release-71.3)

---

fdbclient/ServerKnobs.cpp

Update knob values for Storage Quota polling intervals.
* Mainly, reduce the frequency of polling storage servers for the size estimates to avoid overwhelming the cluster with these requests.
* Correspondingly, also reduce the frequency of refreshing the cache of tenant list.
* Update the potential knob values when `randomize && BUGGIFY` is enabled to include values lower as well as greater than the default.

Update knob values for Storage Quota polling intervals

---

fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp

In MetaclusterManagementWorkload, if we lock a tenant that has already been locked with a different lockId, it's possible that a tenant_locked error is thrown. We need to account for this instead of terminating the test.
Test plan:
Regular simulation and a deterministic reproduction
Branch: https://github.com/sfc-gh-yajin/foundationdb/tree/snow-791039
Commit hash: 7356504723d3c77de501b5683b0a159676c56840
Profile: team
Command: devRetryCorrectnessTest bin/fdbserver -r simulation -f tests/slow/MetaclusterManagement.toml -s 3475230174 -b off --crash --trace_format json
If this PR …

Account for 'tenant_locked' error in MetaclusterManagementWorkload

---

fdbbackup/backup.actor.cpp
fdbclient/FileBackupAgent.actor.cpp
fdbclient/include/fdbclient/BackupAgent.actor.h
fdbclient/include/fdbclient/BlobGranuleCommon.h
fdbclient/include/fdbclient/BlobRestoreCommon.h
fdbserver/BlobManager.actor.cpp
fdbserver/BlobManifest.actor.cpp
fdbserver/Status.actor.cpp
fdbserver/workloads/BlobRestoreWorkload.actor.cpp
fdbserver/workloads/IncrementalBackup.actor.cpp
tests/fast/BlobRestoreBasic.toml
tests/fast/BlobRestoreLarge.toml
tests/fast/BlobRestoreTenantMode.toml
tests/fast/BlobRestoreToVersion.toml

Add command line option "--blob-manifest-url" to fdbbackup. To enable blob granules backup:
"fdbbackup start --blob-manifest-url file:///path/to/manifest --destcontainer file:///path/to/mlogs/ -z -t sometag"
- if tag is not specified, we'll use 'default' as the default tag name
- there is only one blob granules backup allowed at a time. Error message will show up if you try to submit more than one 
To disable blob granules backup
"fdbbackup abort -t sometag"
100K correctness test passed

Support blob manifest backup for fdbbackup cmdline

---

bindings/java/src/main/com/apple/foundationdb/MappedKeyValue.java

The key and value fields are compared in C++ struct, but not in Java. This changes fixed it.
C++ part is correct, ref: https://github.com/apple/foundationdb/blob/main/fdbclient/include/fdbclient/FDBTypes.h#L910

Fix hashCode() and equals() for MappedKeyValue

---

fdbclient/NativeAPI.actor.cpp
fdbserver/workloads/BlobGranuleRangesWorkload.actor.cpp

Allowed unblobbify to work with a superset of ranges, eg unblobbifying [A - Z) would work if your blob ranges were [B - C), [C - D),  [F - G).
Also strengthened testing to add extra checks that blob granules would not be merged across consecutive but explicitly different blobbified ranges.
Passes 50k BlobGranuleRange* correctness and 50k BlobGranule* correctness with 1 unrelated error.

Block unblobbify

---

bindings/java/src/main/com/apple/foundationdb/MappedKeyValue.java

bacporting https://github.com/apple/foundationdb/pull/10170

Fix hashCode() and equals() for MappedKeyValue (release-7.2)

---

fdbclient/NativeAPI.actor.cpp
fdbserver/workloads/BlobGranuleRangesWorkload.actor.cpp

Cherry-Pick of #10182
Allowed unblobbify to work with a superset of ranges, eg unblobbifying [A - Z) would work if your blob ranges were [B - C), [C - D),  [F - G).
Also strengthened testing to add extra checks that blob granules would not be merged across consecutive but explicitly different blobbified ranges.
Passes 50k BlobGranuleRange* correctness and 50k BlobGranule* correctness with 1 unrelated error.

Block unblobbify (Cherry-Pick #10182 to snowflake/release-71.3)

---

bindings/java/src/main/com/apple/foundationdb/MappedKeyValue.java

backporting https://github.com/apple/foundationdb/pull/10170

Fix hashCode() and equals() for MappedKeyValue (release-7.3)

---

tests/rare/BlobGranuleRangesChangeLog.toml

Logical merge conflict between #10174 and #10183 that causes BlobGranuleRangesChangeLog test to fail
Now passes 10k BlobGranuleRanges* tests

fixing logical merge conflict that dropped tenant modes

---

fdbrpc/FailureMonitor.actor.cpp

This can be too verbose to cause test failures.
Reproduction:
-f ./tests/rare/HighContentionPrefixAllocator.toml -s 39701549 -b on
commit on release-7.1: 180ce51db

Suppress AlreadyDisconnected events

---

fdbserver/SimulatedCluster.actor.cpp

Fix a corner case failure where rebooting flag is forgotten to set to true when the process is executing _`RebootProcessAndSwitch`_
It's a very rare case where a protected process is executing the code path.

Fix a corner case failure where rebooting flag left to false when a protected process executing RebootProcessAndSwitch

---

fdbcli/BlobKeyCommand.actor.cpp
fdbcli/BlobRangeCommand.actor.cpp
fdbcli/ChangeFeedCommand.actor.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/include/fdbclient/BlobGranuleRequest.actor.h
fdbserver/workloads/BlobGranuleRangesWorkload.actor.cpp
tests/rare/BlobGranuleRanges.toml

Cherry-Pick of #10183
…g test to find them
- changed BlobGranuleRanges workload to use tenant_mode=required and buggify non-internal clients to reproduce issues
- fixed blob management apis to properly use tenant where provided to fix errors
Passes 50k BlobGranuleRanges correctness and 50k BlobGranule* correctness with 1 unrelated error.
Also tested manually with fdbcli on a cluster with tenant_mode=required

fixing bugs with tenant_mode required on external clients and changin… (Cherry-Pick #10183 to snowflake/release-71.3)

---

tests/rare/BlobGranuleRangesChangeLog.toml

Cherry-Pick of #10190
Logical merge conflict between #10174 and #10183 that causes BlobGranuleRangesChangeLog test to fail
Now passes 10k BlobGranuleRanges* tests

fixing logical merge conflict that dropped tenant modes (Cherry-Pick #10190 to snowflake/release-71.3)

---

fdbserver/Status.actor.cpp

Yeidl in processStatusFetcher when getting log and log router processes in earlier generations

---

cmake/CompileRocksDB.cmake
fdbserver/KeyValueStoreRocksDB.actor.cpp
fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
fdbserver/RocksDBCheckpointUtils.actor.cpp
fdbserver/include/fdbserver/FDBRocksDBVersion.h
fdbserver/include/fdbserver/RocksDBCheckpointUtils.actor.h

* Upgrade to RocksDB 8.1.1
* Revert an ASSERT on the previous rocksdb bug. The test was a guard to show the failure.

Cherry-pick Upgrade to RocksDB 8.1.1 (#10039)

---

fdbcli/GetAuditStatusCommand.actor.cpp
fdbclient/AuditUtils.actor.cpp
fdbclient/include/fdbclient/Audit.h
fdbclient/include/fdbclient/AuditUtils.actor.h

Main branch PR: #10188
* Added `get_audit_status checkmigration` to print out the number of data shards and `physical shards`, so that we know the progress of migration to `shard_encode_location_metadata`
* Fixed print format.
* Addressed comments.

Cherry-pick #10188 to 7.3

---

fdbclient/ServerKnobs.cpp
fdbserver/DDRelocationQueue.actor.cpp

Fix clean up of data moves when encode location metatdata [release-7.3]

---

fdbclient/ClientKnobs.cpp
fdbclient/include/fdbclient/ClientKnobs.h
fdbclient/include/fdbclient/SimKmsVault.cpp
fdbclient/include/fdbclient/SimKmsVault.h
fdbserver/SimKmsConnector.actor.cpp
fdbserver/workloads/UnitTests.actor.cpp

Description
Patch implements a SimKmsVault interface allowing unittest/simulation to satisfy encryption lookup usecases. It also refactors existing SimKmsConnector to leverage SimKmsVault APIs
Testing
/simKmsVault - asan & valgrind
EncryptionUnitTest
(cherry picked from commit 18fd2702c4369d5637d61da56fffef96694ddfeb)

EaR: Implement SimKmsVault interface, refactor SimKmsConnector (#10194)

---

fdbserver/RESTKmsConnector.actor.cpp

cherrypick #9943 to fix a unit test failure
Description
The test does the following:
1.Randomly appends new-line character to the token value buffer
2. If #1 is done, it generates temp token file with buffer containing new-line character.
3. Also, it remember the original token for future validation
4. The code parse and read token-validation files and removes the new-line character as desired.
Failure in this case due to random buffer used to populate token value contained newline character which was used for validation, however, the file parse/read code as expected removed the newline character, hence causing the mismatch.
Patch addresses the concern by ensuring test generated random token-value has no trailing newline chars.
Testing
tests/fast/RandomUnitTests.toml -s 1355028229
Replace …

Update TestMultiValidationTokeFile token generation with no trailing newline char [release-7.3]

---

fdbserver/MoveKeys.actor.cpp

Revert part of logic introduced in #10110
Reproduction on commit https://github.com/apple/foundationdb/commit/c423a60e506b69373fe1b1cadf1f268219b5e0a3:
./fdbserver-7.1.27 -r simulation -f ./tests/restarting/from_7.1.0_until_7.2.0/ConfigureTestRestart-1.toml -s 1969136453 -b on ./fdbserver -r simulation -f ./tests/restarting/from_7.1.0_until_7.2.0/ConfigureTestRestart-2.toml --restarting -s 1969136454 -b on

Remove an assertion for a condition that can happen

---

fdbserver/MoveKeys.actor.cpp

cherrypick #10222
Revert part of logic introduced in #10110
Reproduction on commit https://github.com/apple/foundationdb/commit/c423a60e506b69373fe1b1cadf1f268219b5e0a3:
./fdbserver-7.1.27 -r simulation -f ./tests/restarting/from_7.1.0_until_7.2.0/ConfigureTestRestart-1.toml -s 1969136453 -b on ./fdbserver -r simulation -f ./tests/restarting/from_7.1.0_until_7.2.0/ConfigureTestRestart-2.toml --restarting -s 1969136454 -b on

Remove an assertion for a condition that can happen [release-7.3]

---

bindings/java/CMakeLists.txt
bindings/java/src/integration/com/apple/foundationdb/FutureIntegrationTest.java
bindings/java/src/integration/com/apple/foundationdb/RequiresDatabase.java
bindings/java/src/main/com/apple/foundationdb/NativeFuture.java
bindings/java/src/tests.cmake

`NativeFuture.cancel` may run into a deadlock when recursively calling `NativeFuture.close`. This can happen in a configuration with an external client and when the executor decides to execute the callback in the caller thread.
These methods use a reentrant lock, but `ReentrantReadWriteLock` deadlocks on an attempt to upgrade from read lock to  write lock. 
We fix it by acquiring the write lock already in the `NativeFuture.cancel`.
The PR also a capability to execute the Java integration tests with an external client, as well as a test reproducing the issue. …

Fix deadlock in Java bindings on future cancellation

---

fdbclient/ClientKnobs.cpp
fdbserver/SimulatedCluster.actor.cpp

cherrypick #10150 and [#10195](https://github.com/apple/foundationdb/pull/10195)

Increase buggified STORAGE_METRICS_SHARD_LIMIT value and  fix rebooting flag [release-7.3]

---

fdbcli/TenantCommands.actor.cpp
fdbcli/tests/metacluster_fdbcli_tests.py
fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp
fdbserver/workloads/MetaclusterRestoreWorkload.actor.cpp
fdbserver/workloads/TenantCapacityLimits.actor.cpp
fdbserver/workloads/TenantManagementConcurrencyWorkload.actor.cpp
fdbserver/workloads/TenantManagementWorkload.actor.cpp
metacluster/include/metacluster/CreateTenant.actor.h

Cherry-Pick of #10173
Similar to `tenant configure`, this PR adds `ignore_capacity_limit` as an optional argument to `tenant create`.
This allows the user of fdbcli to create a new tenant on an **assigned** cluster, ignoring the tenant group capacity
on that specific cluster.
When creating a tenant with `ignore_capacity_limit`.
- If the user specifies neither of `assigned_cluster` nor `tenant_group`, this is an error.
- If the user specifies `assigned_cluster` but not `tenant_group`, then the new tenant will be an ungrouped tenant on the `assigned_cluster` ignoring the capacity limit
- If the user specifies `tenant_group` but not `assigned_cluster`, and the tenant group already exists, then it means no new tenant group is being created, thus there will always be …

Add `ignore_capacity_limit` to `tenant create` (Cherry-Pick #10173 to snowflake/release-71.3)

---

fdbclient/ServerKnobs.cpp

Buggified value of 100s is too long to cause consistency check failures.

Reduce STORAGE_FETCH_KEYS_DELAY to speedup data movement

---

documentation/sphinx/requirements.txt

(Cherry-Pick #10141 to snowflake/release-71.2) (#10147)
Add `urllib3<2` to `documentation/sphinx/requirements.txt` in `main` branch

Add urllib3<2 to requirements.txt for Sphinx

---

fdbclient/BlobConnectionProvider.cpp
fdbclient/BlobMetadataUtils.cpp
fdbclient/include/fdbclient/BlobConnectionProvider.h
fdbclient/include/fdbclient/BlobMetadataUtils.h
fdbserver/RESTKmsConnector.actor.cpp
fdbserver/SimKmsConnector.actor.cpp

Refactor the interface of the rest kms connector for blob metadata to be simpler and also to pass ids with each storage location.

Blob kms connector ids

---

fdbclient/include/fdbclient/BlobGranuleRequest.actor.h

In case where some requests failed because the mapping was wrong, the retry loop would sleep instead of throwing an error, meaning the read version would not be reset on the following retry and it would read the same stale mapping.
This would cause the request to continue retrying until the read version got transaction_too_old, meaning the request could take 5 seconds extra (or some multiple of 5 seconds for a large range).
Passes 50k BlobGranule* correctness with no errors and manually verified flush performance and behavior in the error case with fdbcli. …

fixing BlobGranuleRequests to properly bump read version on retry

---

tests/restarting/to_71.2.8_until_71.3.0/BlobGranuleRestartCycle-1.toml
tests/restarting/to_71.2.8_until_71.3.0/BlobGranuleRestartLarge-1.toml

Logical merge conflict between #10217 and #10220.
One disabled http servers in downgrade tests from 71.3, the other added new 71.3 downgrade tests that missed this change.
Passes 10k BlobGranuleRestart* - 20230516-181246-jslocum-86601ed4ebe4fdb1

fixing bg downgrade to also disable http servers

---

fdbclient/BlobConnectionProvider.cpp
fdbclient/BlobMetadataUtils.cpp
fdbclient/include/fdbclient/BlobConnectionProvider.h
fdbclient/include/fdbclient/BlobMetadataUtils.h
fdbserver/RESTKmsConnector.actor.cpp
fdbserver/SimKmsConnector.actor.cpp

Cherry-Pick of #10121
Passes 10k BlobGranuleCorrectness, which is currently the only full simulation workload that exercises this logic - 20230516-171059-jslocum-7d89f35144ceb754
100k correctness passed with 1 unrelated failure - 20230516-173533-jslocum-7d89f35144ceb754 
Refactor the interface of the rest kms connector for blob metadata to be simpler and also to pass ids with each storage location.

Blob kms connector ids (Cherry-Pick #10121 to snowflake/release-71.3)

---

fdbserver/RESTSimKmsVault.actor.cpp

Description
Fix invalid header test to throw appropriate error
Testing
RESTSimKmsVault unittest - 100K

SimKmsVault: Fix invalidHeader test

---

documentation/sphinx/source/command-line-interface.rst
documentation/sphinx/source/mr-status-json-schemas.rst.inc
fdbcli/ConsistencyScanCommand.actor.cpp
fdbclient/Schemas.cpp
fdbclient/SystemData.cpp
fdbclient/include/fdbclient/ConsistencyScanInterface.actor.h
fdbclient/include/fdbclient/KeyBackedTypes.actor.h
fdbclient/include/fdbclient/SystemData.h
fdbrpc/include/fdbrpc/simulator.h
fdbserver/ConsistencyScan.actor.cpp
fdbserver/Status.actor.cpp
fdbserver/include/fdbserver/SingletonRoles.h
fdbserver/workloads/ConsistencyCheck.actor.cpp

Replaces existing consistency scan with new purpose-build consistency scan that is much simpler and operationally superior.
- tracks its state and statistics durably in the database and commits progress periodically
- does not restart on any error
- does not read the entire database's shard map and byte sample every time it restarts
- adjusts its speed dynamically based on the size of the database and the target time-to-completion
A follow-on PR will add additional testing of the consistency scan state and validating that the consistency scan does find a corruption if it exists, but this PR is already large.
Passes 50k correctness tests. …

New ConsistencyScan

---

fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp

This PR fixes an unitialized-value error reported by valgrind.
Steps to reproduce:
Ensemble: 20230516-050214-nightly_valgrind_main_x86_64_apple-b77b4ac44a15911e
Profile: team valgrind
Commit hash: 0ce1ab3162006a1ff40b652f1ccc21c7b9d7d837 on apple/main
Command: devRetryCorrectnessTest valgrind bin/fdbserver -r simulation -f tests/slow/MetaclusterManagement.toml -s 1695330198 -b off --crash --trace_format json

Update a test to check data cluster's version only when registered

---

fdbserver/storageserver.actor.cpp

It's a workround for the release branch 71.3 without #10002. It set the `readThrough` when the response is empty.
After #10002, it is not needed, as there's no `more` data after this.
It fixes a bug in 71.3 release that `fetchKeys()` may fail when the response from `GetRangeFromBlob` is empty.

Set readThrough for empty response as a workaround

---

fdbserver/CommitProxyServer.actor.cpp
fdbserver/ConsistencyScan.actor.cpp

In the KillRegion workload, a force recovery can intentionally kill a region and recover from another region with data loss. It's possible that when the ConsistencyScan (CS) role is checking a shard from two storage servers, the one from the failed region returned first for a higher version, then the SS was killed. Later, CS got data from the second SS from a different region, where forced recovery rollback happened and a lower version value was returned. In this case, even though the data is inconsistent, we shouldn't fail the test.
Reproduction:
commit: 8e0c9eab8 on release-7.3 branch
seed: -f ./tests/fast/KillRegionCycle.toml -s 2713020850 -b on
build: gcc
```
128.285111 KillMachineProcess ID=0000000000000000 KillType=0 Process=name: Server address: 2.0.1.0:1 zone: …
```

Fix ConsistencyCheck_DataInconsistent failure in simulation

---

bindings/c/foundationdb/fdb_c.h

The same declaration of `fdb_tenant_list_blobbified_ranges` appears twice, which is unnecessary.

Remove unnecessary duplicate declaration

---

fdbserver/MoveKeys.actor.cpp

Cherry-pick #10222
Original description:
Revert part of logic introduced in https://github.com/apple/foundationdb/pull/10110
Reproduction on commit https://github.com/apple/foundationdb/commit/c423a60e506b69373fe1b1cadf1f268219b5e0a3:
./fdbserver-7.1.27 -r simulation -f ./tests/restarting/from_7.1.0_until_7.2.0/ConfigureTestRestart-1.toml -s 1969136453 -b on ./fdbserver -r simulation -f ./tests/restarting/from_7.1.0_until_7.2.0/ConfigureTestRestart-2.toml --restarting -s 1969136454 -b on
Ensemble with 100K runs: `20230518-180726-akejriwal-3c8a03e7d72a1bcd`: had 2 unrelated failures (`ExternalTimeout`s in `tests/fast/BlobRestoreLarge.toml` which passes when run on teamserver).
This is being cherry-picked to 71.3 to fix a failure in correctness ensembles (it showed up recently in …

Remove an assertion for a condition that can happen (Cherry-pick #10222 to snowflake/release-71.3)

---

fdbserver/DDTeamCollection.actor.cpp
fdbserver/include/fdbserver/DDTeamCollection.h

In some rare cases, using the same failure time may prevent a certain size from getting a team, thus cause data movement to become stuck.
Reproduction:
Seed: -f ./tests/rare/DcLag.toml -s 924031356 -b on
commit: 0975874b9 on release-7.3
build: gcc
20230519-230626-jzhou-17054722c33accc9

Track failure time of different team sizes separately

---

fdbclient/RandomKeyValueUtils.cpp
fdbserver/ConsistencyScan.actor.cpp
tests/rare/SpecificUnitTests.toml

Fix the issue introduced in #10276
Also fix a GCC compiling error and cherrypick #10288
500k 20230522-161148-jzhou-be0d09cd728e5bc5

Don't retry consistency scan if expected TSS faults [release-7.3]

---

fdbclient/include/fdbclient/SimKmsVault.cpp
fdbclient/include/fdbclient/SimKmsVault.h
fdbserver/RESTSimKmsVault.actor.cpp
fdbserver/SimKmsConnector.actor.cpp
fdbserver/include/fdbserver/RESTSimKmsVault.h

Description
Patch refactor SimKmsConnector to move SimBlobMetadata store to SimKmsVault
Testing
BlobGranuleCorrectness - 100K
/fdbserver/blob/connectionprovider - 100K

BlobMetadata: Move SimBlobMetada store to SimKmsVault

---

bindings/java/src/integration/com/apple/foundationdb/BlobGranuleIntegrationTest.java
bindings/java/src/integration/com/apple/foundationdb/MappedRangeQueryIntegrationTest.java
bindings/java/src/integration/com/apple/foundationdb/RangeQueryIntegrationTest.java
bindings/java/src/integration/com/apple/foundationdb/WatchesIntegrationTest.java
bindings/java/src/tests.cmake
fdbclient/include/fdbclient/MultiVersionAssignmentVars.h

The PR fixes the issue of watches not being released when the future holding them is cancelled. The root cause of it is a change to abortable future introduced in https://github.com/apple/foundationdb/pull/8334 with the wrong assumption that cancellation is necessary just for notifying the callback about the operation being cancelled. In reality the cancellation is also necessary for aborting the background actor handing the request. This is especially critical in case of watches, because they are designed to wait indefinitely for change notification.
The fix ensures that MVC abortable future cancels the wrapped future in all code paths.
The PR also introduces a set of Java binding tests for watch limit control and the release of watches on cancellation of futures.
The general pull …

Fix releasing watches on future cancellation

---

fdbserver/storageserver.actor.cpp

Cherrypick fix from #10070
Reproduction:
seed: -f ./tests/fast/BlobRestoreLarge.toml -s 3284092948 -b on
commit: 2e62b577f
build: clang

Fix assertion failure in RangeResultRef::getReadThrough() [release-7.3]

---

fdbclient/AuditUtils.actor.cpp
fdbclient/include/fdbclient/AuditUtils.actor.h
fdbserver/DataDistribution.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/tester.actor.cpp

Cherry-pick https://github.com/apple/foundationdb/pull/10245
100K Correctness Test with 3 irrelevant failures:
20230522-194814-zhewang-7c1f81f8d6f51e34           compressed=True data_size=33221184 duration=4942087 ended=100000 fail=3 fail_fast=10 max_runs=100000 pass=99997 priority=100 remaining=0 runtime=1:18:30 sanity=False started=100000 stopped=20230522-210644 submitted=20230522-194814 timeout=5400 username=zhewang
100K ValidateStorage Test:
20230522-194906-zhewang-b5abc3bf0a145e3e           compressed=True data_size=33255889 duration=3991974 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:00:04 sanity=False started=100000 stopped=20230522-204910 submitted=20230522-194906 timeout=5400 username=zhewang
Tested by test_shardedrocksdb_audit.run …

[release-7.3] Cherry-pick Improve throughput of audit storage (#10245)

---

bindings/java/src/integration/com/apple/foundationdb/BlobGranuleIntegrationTest.java
bindings/java/src/integration/com/apple/foundationdb/MappedRangeQueryIntegrationTest.java
bindings/java/src/integration/com/apple/foundationdb/RangeQueryIntegrationTest.java
bindings/java/src/integration/com/apple/foundationdb/WatchesIntegrationTest.java
bindings/java/src/tests.cmake
fdbclient/include/fdbclient/MultiVersionAssignmentVars.h

Cherry-pick of https://github.com/apple/foundationdb/pull/10304
The PR needs to be included to 71.3, because it fixes a critical issue of watches not being released on cancellation of futures, which is a regression from 71.2.
100000 correctness tests passed, 20230523-092118-vgasiunas-1aff94d0c696b1f0

Fix releasing watches on future cancellation [snowflake/release-71.3]

---

fdbclient/ClientKnobs.cpp

Improves performance of large feeds, particularly cases in simulation where shard size is buggified << feed size. This fixes some joshua timeouts in blob granule tests and in general is a useful performance improvement.
This knob was previously disabled due to an issue that was likely unrelated.
Passed 250k BlobGranule* correctness on snowflake/release-71.3 with 1 unrelated error and 0 ExternalTimeouts

re-enabling change feed coalesce knob

---

fdbserver/storageserver.actor.cpp

Fixes issue on temptest that change feed was sending far too large of packets, causing timeouts and other issues.
This bug appears to have been introduced when the refactoring adding change feed encryption dropped this line - https://github.com/apple/foundationdb/pull/9164/files#diff-c4dbfae809f757f2061099ee5021ce2cbbf0f4dbc2f0f18480a4856d63d033ceL2889
Passed 50k BlobGranule* correctness with 1 unrelated error

fixing too large packets from change feeds

---

fdbrpc/include/fdbrpc/simulator.h
fdbserver/workloads/ConsistencyCheck.actor.cpp

Adding check that singletons are in fact single.
It fails a bunch now though so leaving it disabled.
Passed 10k correctness with the check disabled

adding disabled consistency check test to check singletons

---

fdbserver/storageserver.actor.cpp

Cherry-pick #10315 
This should be included in the 71.3.0 release because, despite not being a client fix, it is enough of a performance issue that it is blocking any large scale integration testing of the client that uses change feeds.
100k correctness - 20230523-183816-jslocum-a20a8eb9c86b562f - no failures
50k BlobGranule* correctness - 3 unrelated failures (2 external timeouts fixed by #10318, 1 restarting test failure that would be fixed by backporting #9840 to 71.2)

[snowflake/release-71.3] fixing too large packets from change feeds

---

fdbclient/ServerKnobs.cpp

The blob worker needs more time to catchup, about 388s in the failed simulation test.
Reproduction:
seed: -f ./tests/slow/BlobGranuleVerifyLargeClean.toml -s 4068151139 -b on
commit: 3bdd71cb0 at release-7.3 branch
build: gcc

Increase BW_RK_SIM_QUIESCE_DELAY to 400s

---

fdbclient/SpecialKeySpace.actor.cpp

Cherrypick https://github.com/apple/foundationdb/pull/10330.
This is being included in 71.3.0 since this is a client side change that fixes a bugs in a command that has been causing issues during cluster wiggles.
100K run ensemble: `20230523-233454-akejriwal-94ed3ee54ac2e64a`: all tests pass
Original description:
This PR fixes two bugs in checkExclusion():
Increment ssExcludedCount only if the role is storage. (It was previously incrementing this number regardless of the role, and then comparing it to ssTotalCount which is only updated when the role is storage.)
Fix the computation of finalUnavailableRatio to use a double division. (It was previously using a integer division which truncates the result.)
Also add a trace event which exposes the aggregate metrics used in checkExclusion() …

[snowflake/release-71.3] Fix two bugs in checkExclusion() and add a trace event for better observability (cherry-pick #10330)

---

fdbclient/BackupContainerLocalDirectory.actor.cpp
fdbclient/ClientKnobs.cpp
fdbclient/include/fdbclient/ClientKnobs.h

Cherry-pick #10328
This PR is non-behavior changing by default, but if the knob is changed, it will enable to integration test blob granules and as such is required for 71.3.0
100k correctness complete -  20230524-140603-jslocum-79c48826fe6279cb
1 failure (ExternalTimeout) which is fixed by https://github.com/apple/foundationdb/pull/10318

adding knob to allow relative paths for local backup containers

---

fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp

Cherry-Pick of #10275
This is a low-risk, test-only fix for valgrind with no change or impact on functionality and performance.
Run 100k without valgrind
ensemble id; 20230522-175632-yajin-d9db699cd94ac2eb
the only one failure should be fixed by #10244 
This PR fixes an unitialized-value error reported by valgrind.
Steps to reproduce:
Ensemble: 20230516-050214-nightly_valgrind_main_x86_64_apple-b77b4ac44a15911e
Profile: team valgrind
Commit hash: 0ce1ab3162006a1ff40b652f1ccc21c7b9d7d837 on apple/main
Command: devRetryCorrectnessTest valgrind bin/fdbserver -r simulation -f tests/slow/MetaclusterManagement.toml -s 1695330198 -b off --crash --trace_format json
The general pull request guidelines can be found [here](https://github.com/apple/foundationdb/wiki/FoundationDB- …

Update a test to check data cluster's version only when registered (Cherry-Pick #10275 to snowflake/release-71.3)

---

fdbclient/SpecialKeySpace.actor.cpp

This PR fixes two bugs in checkExclusion():
Increment ssExcludedCount only if the role is storage. (It was previously incrementing this number regardless of the role, and then comparing it to ssTotalCount which is only updated when the role is storage.)
Fix the computation of finalUnavailableRatio to use a double division. (It was previously using a integer division which truncates the result.)
Also add a trace event which exposes the aggregate metrics used in checkExclusion() which can be used if the the function shows unexpected behavior.
This has been tested on an FDB cluster. Previously, the exclude command had been failing on this cluster (when it shouldn't have been), but after this fix, the command succeeded. This trace event (as well as more detailed temporary trace events) showed …

Fix two bugs in checkExclusion() and add a trace event for better observability

---

README.md

Remove mentioning of build directory in README.md

---

fdbserver/MutationTracking.cpp
fdbserver/include/fdbserver/MutationTracking.h

This is causing TracedTooManyLines errors

Disable mutation tracking by default

---

fdbrpc/include/fdbrpc/simulator.h
fdbserver/DDTeamCollection.actor.cpp
fdbserver/tester.actor.cpp

Storage wiggle can cause consistency check to restart due to wrong_shard_server error. This can sometimes repeatedly happen and cause consistency check timeout.
Reproduction:
seed: -f ./tests/fast/MutationLogReaderCorrectness.toml -s 575471711 -b on
commit: 2e62b577f at release-7.1
build: clang
20230523-185513-jzhou-6a80ca868dfe2956

Slow down wiggler when in ConsistencyCheck

---

fdbrpc/include/fdbrpc/simulator.h
fdbserver/DDTeamCollection.actor.cpp
fdbserver/tester.actor.cpp

cherrypick #10320
Storage wiggle can cause consistency check to restart due to wrong_shard_server error. This can sometimes repeatedly happen and cause consistency check timeout.
Reproduction:
seed: -f ./tests/fast/MutationLogReaderCorrectness.toml -s 575471711 -b on
commit: 2e62b577f at release-7.1
build: clang
20230523-192435-jzhou-2440f73df4b213f6
20230524-212519-jzhou-a42df3d2ae471197

Slow down wiggler when in ConsistencyCheck [release-7.3]

---

fdbserver/BlobMigrator.actor.cpp
fdbserver/MockGlobalState.actor.cpp
fdbserver/include/fdbserver/MockGlobalState.h
fdbserver/include/fdbserver/StorageMetrics.actor.h
fdbserver/storageserver.actor.cpp

- Xiaoxi did some refactoring for StorageServerInterface and we are changing BlobMigrator accordingly. We refactor `BlobMigrator` implement the `IStorageMetricsService` interface.
Test
- 100K correctness tests, all passed
- Ensemble ID `20230525-222612-jzhong-95273e221786072b`
- 50K correctness tests filtered by keyword *BlobRestore*, all passed
- Ensemble ID `20230525-193434-jzhong-df0d8e3f7343aa90`

Cherry-pick commit to implement IStorageMetricsService inteface for BlobMigrator

---

fdbserver/ConsistencyScan.actor.cpp

Had an issue that it would stall on too large of a shard because it used the same transaction to read and then commit.
Also fixed a couple other little things
Running 50k correctness

fixing consistency scan loop and completion check

---

fdbclient/ClientKnobs.cpp
fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbserver/GlobalTagThrottler.actor.cpp
fdbserver/TransactionTagCounter.cpp

This PR makes the following changes:
- Update `TAG_THROTTLING_PAGE_SIZE` default to 4096
- Update `GLOBAL_TAG_THROTTLING_RW_FUNGIBILITY_RATIO` to 4.0
- Fix a bug in the GlobalTagThrottler_GotRate tracing
- Removes unnecessary `GLOBAL_TAG_THROTTLING_MIN_TPS` knob
- Fixes a ScopeEventFieldTypeMismatch warning on BusiestReadTag traces

Miscellaneous bug fixes and improvements for `GlobalTagThrottler`

---

fdbclient/NativeAPI.actor.cpp
fdbserver/fdbserver.actor.cpp
flow/Trace.cpp
flow/include/flow/BooleanParam.h
flow/include/flow/CodeProbe.h
flow/include/flow/Trace.h
flow/include/flow/Traceable.h

This fixes two thread safety issues:
Convert CodeProbeImpl::_hitCount to an atomic so that it can be incremented from multiple threads simultaneously.
Update accesses of logTraceEventMetrics so that it is written before a trace log is opened and read after it is opened and only from the network thread.

Fix a couple thread-safety issues

---

fdbserver/GlobalTagThrottler.actor.cpp
fdbserver/GrvProxyTagThrottler.actor.cpp
fdbserver/TransactionTagCounter.cpp
fdbserver/storageserver.actor.cpp

In trace event details, escaping is already applied, so it shouldn't be applied twice.

Remove unnecessary usage of `printable`

---

fdbclient/NativeAPI.actor.cpp
fdbserver/fdbserver.actor.cpp
flow/Trace.cpp
flow/include/flow/BooleanParam.h
flow/include/flow/CodeProbe.h
flow/include/flow/Trace.h
flow/include/flow/Traceable.h

This fixes two thread safety issues:
- Convert `CodeProbeImpl::_hitCount` to an atomic so that it can be incremented from multiple threads simultaneously.
- Update accesses of logTraceEventMetrics so that it is written before a trace log is opened and read after it is opened and only from the network thread.
Cherry-pick of https://github.com/apple/foundationdb/pull/10359

Fix a couple thread-safety issues [snowflake/release-71.3]

---

fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/KeyBackedTypes.actor.h

cherrypick #10329 and fix a windows build error
The original PR increases to 400s, which seems small as there are still failures, so set to 500 in this PR.

Increase BW_RK_SIM_QUIESCE_DELAY to 500s [release-7.3]

---

tests/TestRunner/upgrade_test.py

Restoring missing download step in upgrade tests

Fix download in upgrade test [snowflake/release-71.3]

---

fdbclient/DatabaseBackupAgent.actor.cpp

When buggify is enabled, it's possible the version map has 5 entries, which is larger than `BACKUP_MAP_KEY_LOWER_LIMIT=4`, causing the range task to be delayed infinitely: the `BackupRangeTaskFunc::_execute()` skips the execution and schedules the task to be added back in `BackupRangeTaskFunc::_finish()`.
Fix by ignore the buggified value when in simulation, buggy is on, and `speedUpSimulation` is true.
Reproduction:
Seed: `-f ./tests/slow/SharedDefaultBackupCorrectness.toml -s 3202874095 -b on`
`-f ./tests/slow/VersionStampBackupToDB.toml -s 1190111003 -b on`
Commit: 6e5773dd5 at release-7.3
Build: clang …

Fix a simulation DR stuck issue

---

fdbclient/DatabaseBackupAgent.actor.cpp

cherrypick #10379
When buggify is enabled, it's possible the version map has 5 entries, which is larger than `BACKUP_MAP_KEY_LOWER_LIMIT=4`, causing the range task to be delayed infinitely: the `BackupRangeTaskFunc::_execute()` skips the execution and schedules the task to be added back in `BackupRangeTaskFunc::_finish()`.
Fix by ignore the buggified value when in simulation, buggy is on, and `speedUpSimulation` is true.
Reproduction:
Seed: `-f ./tests/slow/SharedDefaultBackupCorrectness.toml -s 3202874095 -b on`
`-f ./tests/slow/VersionStampBackupToDB.toml -s 1190111003 -b on`
Commit: 6e5773dd5 at release-7.3
Build: clang
500k 20230530-170656-jzhou-0c5532d201c01796 passed!
The general pull request guidelines can be found [here](https://github.com/apple/foundationdb/wiki/FoundationDB-Commi …

Fix a simulation DR stuck issue [release-7.3]

---

cmake/ConfigureCompiler.cmake

Change the compiler option order so that -g1 is added after -gdwarf, because otherwise -gdwarf resets it to -g2. It is is important for reducing the size of our release binaries.

Change compiler options order to avoid -gdwarf overriding -g1

---

fdbcli/GetAuditStatusCommand.actor.cpp
fdbclient/AuditUtils.actor.cpp
fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/Audit.h
fdbclient/include/fdbclient/FDBTypes.h
fdbserver/DataDistribution.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/workloads/ValidateStorage.actor.cpp

Cherry-pick https://github.com/apple/foundationdb/pull/10322
20230529-215801-zhewang-968a61eaec351700           compressed=True data_size=33228064 duration=6356429 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:18:44 sanity=False started=100000 stopped=20230529-231645 submitted=20230529-215801 timeout=5400 username=zhewang
100K ValidateStorage:
20230529-215838-zhewang-b8fcf515d18552df           compressed=True data_size=33259331 duration=4229446 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:59:34 sanity=False started=100000 stopped=20230529-225812 submitted=20230529-215838 timeout=5400 username=zhewang
Tested by test_frm.run …

[Release 7.3] Cherry-pick SS Audit Storage Throttling (#10322)

---

cmake/ConfigureCompiler.cmake

Reorder the compiler options so that -g1 is added after -gdwarf, because otherwise -gdwarf resets it to -g2. It is important for reducing the size of our release binaries.

Change compiler options order to avoid -gdwarf overriding -g1 [snowflake/release-71.3]

---

fdbserver/ClusterController.actor.cpp

[FDBCORE-4801](https://snowflakecomputing.atlassian.net/browse/FDBCORE-4801)
We disable consistency scanner during blob restore, since the data during restore is inconsistent in nature.
100K correctness tests, 1 failure
- ensemble `20230531-172547-jzhong-f56c5dc2b6c6bff8`
- The failure occurred in `tests/fast/PerpetualWiggleStats.toml` with error `TesterFailed` and reason `Test timed out`
- The same error has been obeserved in FDB Correctness Triage's spreadsheet

Cherry-pick FDBCORE-4801 Stop consistency scanner while restore is in progress

---

design/global-tag-throttling.md
fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/ServerKnobs.h
fdbrpc/include/fdbrpc/Smoother.h
fdbserver/GlobalTagThrottler.actor.cpp

This PR creates a `HoltLinearSmoother` class, which implements double exponential smoothing. This class is more accurate than `Smoother` for data with trends. This new class is used for the `GlobalTagThrottlerImpl::PerTagStatistics::transactionCounter` field. Furthermore, the `GLOBAL_TAG_THROTTLING_SMOOTHING_TIME` knob is split into several knobs, to give more fine-grained control over the various smoothers used in `GlobalTagThrottler`. The following knobs are introduced:
- `GLOBAL_TAG_THROTTLING_TARGET_RATE_SMOOTHING_INTERVAL`
- `GLOBAL_TAG_THROTTLING_TRANSACTION_COUNTER_SMOOTHING_INTERVAL` (defaults to 2.0, which is a behaviour change from the previous value of 10.0. This change was based on performance tests)
- `GLOBAL_TAG_THROTTLING_TRANSACTION_RATE_SMOOTHING_INTERVAL`
- …

Add `HoltLinearSmoother` class

---

fdbserver/storageserver.actor.cpp

Fixes a debugTransaction chain of logs for every fetchKeys, which is very verbose

removing debug id for every fetch keys transaction

---

cmake/FDBComponents.cmake

This PR disables `SSD_ROCKSDB_EXPERIMENTAL` on snowflake/release-71.3 branch.
This is being done to fix the CI failures on the branch due to assertions in the RocksDB code. One option was to cherry-pick the RocksDB version upgrade. Trying that option led to a very large and complex cherry-pick since the version upgrade PR depended on another PR (from main), which depended on another PR, and so on. Second option was to disable the specific assertions that were failing in CI, however, that led to additional failures. Since Snowflake doesn't use RocksDB, disabling this knob is a simpler approach. …

[snowflake/release-71.3] Disable SSD_ROCKSDB_EXPERIMENTAL

---

fdbrpc/SimExternalConnection.actor.cpp
fdbserver/workloads/HTTPKeyValueStore.actor.cpp

Cherry-Pick of #10396
Required for 71.3.1 for simulated http server testing
…on public to fix resolving an fdb process' ip in simulation
100k HTTP* correctness and 100k standard correctness passed (1 unrelated error) on main
On 71.3:
100k HTTP* correctness: 20230606-143116-jslocum-3f3a0f4a9fe5dcd1: no failures
100k standard correctness: 20230606-143051-jslocum-3f3a0f4a9fe5dcd1: no faliures

make network address returned by SimExternalConnection's dns resoluti… (Cherry-Pick #10396 to snowflake/release-71.3)

---

fdbserver/ConsistencyScan.actor.cpp

In simulation, the consistency check was not properly throttling itself in error cases.
Normally this would still allow for test progress as reads take some time, but in the error case, when the CC and SS were on the same process, there was little to no latency for the read request, so it would essentially spin loop, causing joshua to time out.
100k correctness passed with 1 likely unrelated TracedTooManyLines failure

Correctly throttling consistency check on error case

---

fdbserver/BlobGranuleValidation.actor.cpp

Cherry-Pick of #10327
… ensuring retry uses higher read version for the check
100k normal correctness: 20230606-164430-jslocum-af37a6dd43570cb6: 0 failures
50k BlobGranule* correctness: 20230606-164347-jslocum-af37a6dd43570cb6 - 0 failures

fixing stable feeds check by allowing more time post speedup sim, and… (Cherry-Pick #10327 to snowflake/release-71.3)

---

fdbserver/worker.actor.cpp

(Cherry-Pick #10363 to snowflake/release-71.3)
The only case when a coordination server should fail with file_not_found is when the DiskQueue only finds 1 out of its 2 queue files. This either means data has been lost, or the initial creation of the two files failed partway through. In either case, it's sensible to crash the process and refuse to start.
The existing code was catching the file_not_found error and letting the FDBD process continue after the coordination server failed. This resulted in clients attempting to contact the coordination server on a well-known endpoint and never getting a response, because Flow transport silently dropped the request when there was no receiver for it. By terminating the process instead, we effectively notify waiting clients that they won't get a …

Let coordination server crash on file_not_found error.

---

fdbclient/include/fdbclient/NativeAPI.actor.h
fdbserver/RkTagThrottleCollection.cpp

This is a backport of https://github.com/apple/foundationdb/pull/10367.

(snowflake/release-71.3) Fix `get*OperationCost` functions for empty mutations/results

---

fdbclient/include/fdbclient/VersionedMap.h

- Return const references in PTree accessors
- Remove unnecessary refcounting for rotating ptree

Remove some unnecessary ref-counting in the PTree

---

contrib/TestHarness2/test_harness/run.py

We should check a variable is not None before comparing with integer in python.
100k ensemble: 20230607-173503-yajin-a01d9450252da05e

Check if var is None before comparing with int

---

fdbclient/PaxosConfigTransaction.actor.cpp

Make a local copy of the promise before calling `send` in case the promise gets destroyed as a result of fulfilling it.
This issue was previously fixed for sending errors to the `result` promise, but it was never fixed when fulfilling the promise. The issue manifested as an invalid generation returned when running a `set` against the configuration database immediately followed by a `get` with a new transaction object.

Fix a dynamic knobs bug where fulfilling a promise could cause it to get deleted

---

contrib/TestHarness2/test_harness/run.py

Cherry-Pick of #10433
This PR fixes rare failures caused by test result not having a random unseed.
We should check a variable is not None before comparing with integer in python.
100k ensemble:
20230607-215319-yajin-4995f598b401cc06, fail=0

Check if var is None before comparing with int (Cherry-Pick #10433 to snowflake/release-71.3)

---

fdbserver/BlobMigrator.actor.cpp
fdbserver/MockGlobalState.actor.cpp
fdbserver/include/fdbserver/MockGlobalState.h
fdbserver/include/fdbserver/StorageMetrics.actor.h
fdbserver/storageserver.actor.cpp

Cherry-Pick of #10336
- This commit is helpful for branch 71.3 release because it refactors code and reduces complexity.
- Xiaoxi did some refactoring for StorageServerInterface and we are changing BlobMigrator accordingly. We refactor `BlobMigrator` implement the `IStorageMetricsService` interface.
Test
- 100K correctness tests, all passed
- Ensemble ID `20230606-194526-jzhong-11a06ade9611209c`

Cherry-pick commit to implement IStorageMetricsService interface

---

fdbserver/CommitProxyServer.actor.cpp

now() is only updated in the run loop, so timer() is more appropriate for accurate measurements of latency. This change is limited to the commit proxy server, where we observed inaccurate latency statistics.

Replace calls to now() with timer() when measuring durations.

---

fdbclient/include/fdbclient/VersionedMap.h

Cherry-Pick of #10401
100k correctness: 20230607-191558-jslocum-35a41f7bb32913fb: 0 failures
- Return const references in PTree accessors
- Remove unnecessary refcounting for rotating ptree

Remove some unnecessary ref-counting in the PTree (Cherry-Pick #10401 to snowflake/release-71.3)

---

fdbclient/FileBackupAgent.actor.cpp
fdbclient/include/fdbclient/BlobRestoreCommon.h
fdbserver/BlobMigrator.actor.cpp

This PR fixes two bugs for blob granules restore when restoring to a previous version
we can complete the restore job sooner if no mutation log need to be applied.
Set the correct beginVersion for the restore job so that it only loads mutation log files needed to be applied
50K BlobRestore test passed. 100k correctness test is in progress

BlobGranuleRestore - skip muations applying if restore target version

---

flow/Net2.actor.cpp

In order to improve auditing we've added a peerIP field to BindPromise in order to decorate `N2_(Connect|Accept)Handshake(Unknown)*Error` with the peerIP. 

Decorate TLS handshake errors with peerAddr

---

fdbclient/FileBackupAgent.actor.cpp
fdbclient/include/fdbclient/BlobRestoreCommon.h
fdbserver/BlobMigrator.actor.cpp

Cherry-Pick of #10442
100K BlobRestore test passed. 20230608-161155-huliu-d3d2893e6ef4315d
100k correctness test passed. 20230608-162712-huliu-9fec608613fba7dc
This PR fixes two bugs for blob granules restore when restoring to a previous version
we can complete the restore job sooner if no mutation log need to be applied.
Set the correct beginVersion for the restore job so that it only loads mutation log files needed to be applied
50K BlobRestore test passed. 100k correctness test passed …

BlobGranuleRestore - skip muations applying if restore target version (Cherry-Pick #10442 to snowflake/release-71.3)

---

bindings/c/test/fdb_c_client_config_tests.py
bindings/go/src/fdb/generated.go
documentation/sphinx/source/api-common.rst.inc
documentation/sphinx/source/api-python.rst
documentation/sphinx/source/tls.rst
fdbcli/fdbcli.actor.cpp
fdbclient/NativeAPI.actor.cpp
fdbclient/vexillographer/fdb.options
fdbserver/fdbserver.actor.cpp
flow/Net2.actor.cpp
flow/TLSConfig.actor.cpp
flow/include/flow/TLSConfig.actor.h
tests/TestRunner/local_cluster.py

By default, FDB clients configured with TLS credentials (CA, cert, key) are able to connect to clusters using TLS (and matching credentials) or plaintext clusters. As a potential attack vector, an attacker may be able to redirect a TLS-configured client's connections to a plaintext cluster in their control and read sensitive data. For security purposes, it is desirable to disallow a client to connect to non-TLS FDB clusters with a network option.
To solve this, I've added `NetworkOption::TLS_DISABLE_PLAINTEXT_CONNECTION` to fail all non-TLS connections made through `Net2::connect()` with a `connection_failed` error. 
Cherry-picks #9984
20230608-181106-sgwydir-157a17732bb017b1           branch=snowflake/release-71.3 commit=370bf14aaa19393b3bfafce341255a1ae5068f73 compressed=True …

Add networkoption to disable non-TLS connections (Cherry-pick #9984 to snowflake/release-71.3)

---

fdbserver/BlobWorker.actor.cpp
fdbserver/include/fdbserver/BlobWorker.h

Cherry-pick #10447
100k correctness: 20230608-181122-jslocum-a99c7b7576239f9a: no failures
50k BlobGranule* correctness: 20230608-181028-jslocum-a99c7b7576239f9a: 1 failure
(same 71.2.8 healthyZone restarting failure)

[snowflake/release-71.3] Adding delta file count before resnapshot to minimize impact of small delta files

---

contrib/branch_diff.py

* Diff two branches FROM..TO
* Record all commits that in TO but not in FROM
* List the Pull Requests related to the commits together with authors in a Markdown format
An example output:
|PR ID|Author|Title|
|-----|------|-----|
|10302|Yao Xiao|[release-7.3] Knobs to speed up DB open.| |10311|Jingyu Zhou|Fix assertion failure in RangeResultRef::getReadThrough() [release-7.3]| |10306|Zhe Wang|[release-7.3] Cherry-pick Improve throughput of audit storage (#10245)| |10289|Zhe Wu|[Release 7.3] GC earlier TLog generation using each generation's recover at version instead of start version| |10296|Jingyu Zhou|Don't retry consistency scan if expected TSS faults [release-7.3]| |10276|Jingyu Zhou|Fix ConsistencyCheck_DataInconsistent failure in simulation [release-7.3]| |10257|Yao …

Tool that diffs two branches, e.g. 7.2.0 .. release-7.3

---

fdbclient/ServerKnobs.cpp
fdbserver/workloads/ValidateStorage.actor.cpp

100K correctness test with 8 irrelevant failures: 
20230608-214221-zhewang-456ba581e3507201           compressed=True data_size=34205445 duration=6155064 ended=100000 fail=8 fail_fast=10 max_runs=100000 pass=99992 priority=100 remaining=0 runtime=1:24:26 sanity=False started=100000 stopped=20230608-230647 submitted=20230608-214221 timeout=5400 username=zhewang
100K ValidateStorage test:
20230608-214326-zhewang-863278d79b92a9a5           compressed=True data_size=34235131 duration=8320042 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:23:56 sanity=False started=100000 stopped=20230608-230722 submitted=20230608-214326 timeout=5400 username=zhewang …

Fix audit storage testAuditStorageConcurrentRunForSameType test

---

fdbcli/DebugCommands.actor.cpp
fdbcli/fdbcli.actor.cpp
fdbcli/include/fdbcli/fdbcli.actor.h
fdbclient/include/fdbclient/NativeAPI.actor.h
fdbserver/CommitProxyServer.actor.cpp

Can be useful for debugging. Manually tested in a loopback cluster.
getlocation: returns the SS list for a key
getall: returns both the SS list and values on the SS for a key

Add getlocation and getall fdbcli debug commands

---

fdbclient/BlobCipher.cpp

Description
Extend BlobCipher unit test to provide coverage for the scenario where buffer got encrypted with a EncryptionKey K, however, decryption for some reason got attempted with K'.
Testing
EncryptionUnit.toml - 100K

EaR: Add test case to validate decryption with invalid key

---

fdbcli/CMakeLists.txt
fdbcli/DebugCommands.actor.cpp
fdbcli/fdbcli.actor.cpp
fdbcli/fdbcli.actor.h
fdbclient/NativeAPI.actor.h

cherrypick #10436
getlocation: returns the SS list for a key
getall: returns both the SS list and values on the SS for a key
Manually tested in clusters.

Add getlocation and getall fdbcli commands [release-7.1]

---

fdbserver/BlobManager.actor.cpp
fdbserver/Status.actor.cpp

Cherry-Pick of #10454
100K correctness test passed. 20230608-213103-huliu-1f241d68b2a4b3f6
This PR is to add more fields to status json for ease of management. It also refactor mutation log truncation function. 

Add blob manifest url and mlogs url in status json. (Cherry-Pick #10454 to snowflake/release-71.3)

---

fdbcli/AuditStorageCommand.actor.cpp
fdbcli/GetAuditStatusCommand.actor.cpp
fdbcli/fdbcli.actor.cpp
fdbclient/AuditUtils.actor.cpp
fdbclient/ManagementAPI.actor.cpp
fdbclient/ServerKnobs.cpp
fdbclient/include/fdbclient/Audit.h
fdbclient/include/fdbclient/AuditUtils.actor.h
fdbclient/include/fdbclient/ManagementAPI.actor.h
fdbserver/ClusterController.actor.cpp
fdbserver/DataDistribution.actor.cpp
fdbserver/storageserver.actor.cpp
fdbserver/workloads/ValidateStorage.actor.cpp
flow/include/flow/error_definitions.h

100K correctness test with 2 irrelevant failures:
20230609-013805-zhewang-46607244d14a05cd           compressed=True data_size=33350015 duration=5726197 ended=100000 fail=2 fail_fast=10 max_runs=100000 pass=99998 priority=100 remaining=0 runtime=1:16:54 sanity=False started=100000 stopped=20230609-025459 submitted=20230609-013805 timeout=5400 username=zhewang
100K ValidateStorage test:
20230609-013851-zhewang-a25d10e6250f5119           compressed=True data_size=33380737 duration=7934388 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:21:12 sanity=False started=100000 stopped=20230609-030003 submitted=20230609-013851 timeout=5400 username=zhewang
tested by test_frm.run …

[Release 7.3] Cherry-pick Add audit storage cancellation (#10386)

---

fdbclient/ServerKnobs.cpp

Rocksdb max auto readahead size knob change to 64k (default=256K). This showed better latency improvements in ckperf cluster.

Rocksdb max auto readahead size knob change to 64k

---

fdbserver/DDRelocationQueue.actor.cpp

In a corner case, one pending DD request might be split into two requests, and fetchingSourcesQueue would take those two as single one.

Fix queued relocations missing

---

fdbclient/ManagementAPI.actor.cpp
fdbserver/ConsistencyScan.actor.cpp

Cherry-Pick of #10470
100K correctness tests: 20230612-203427-huliu-5b0dfdb52c1ddeee
RandomMoveKeys is stuck at ManagementAPI::setDDMode() when db is throttled. So set PRIORITY_SYSTEM_IMMEDIATE option for the transaction.
Another change in ConsistencyScanner. Let it delay longer. Otherwise it creates more problems when DD is not started yet because of the above DD mode issue

Fix MoveKeysClean.toml failure (Cherry-Pick #10470 to snowflake/release-71.3)

---

fdbclient/NativeAPI.actor.cpp
fdbclient/include/fdbclient/DatabaseContext.h

This is a backport of https://github.com/apple/foundationdb/pull/10297.
This is being included in 71.3 because it helps provide very valuable visibility into the client-side behavior of watches.

(snowflake/release-71.3) Add `WatchMapSize` and `OutstandingWatches` to `TransactionMetrics`

---

cmake/CompileRocksDB.cmake
fdbserver/KeyValueStoreRocksDB.actor.cpp
fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
fdbserver/RocksDBCheckpointUtils.actor.cpp
fdbserver/include/fdbserver/FDBRocksDBVersion.h
fdbserver/include/fdbserver/RocksDBCheckpointUtils.actor.h
tests/TestRunner/binary_download.py

main branch RP: #10039 
* Upgrade to RocksDB 8.1.1
* Revert an ASSERT on the previous rocksdb bug. The test was a guard to show the failure.

Upgrade to RocksDB 8.1.1 (#10039)

---

fdbclient/RESTClient.actor.cpp
fdbclient/RESTUtils.actor.cpp
fdbclient/include/fdbclient/RESTUtils.h
fdbserver/RESTKmsConnector.actor.cpp
tests/fast/RESTUnit.toml

Description
RESTKmsConnector implements discovery and refresh semantics i.e. on bootstrap it discovers KMS Urls and periodically refresh the URLs (handle server upgrade scenario). The current implementation caches the URLs in a min-heap, as part of serving a request, actor pops out elements from min-heap and attempts connecting to the server, on failure, the URL is temporarily stored in a stack, at the end of the request processing, the stack is merged back into the heap. The code doesn't work as expected if there are multiple requests consumes the heap causing following issues:
1. Min-heap would retain old URLs replaced by latest refresh (stack merge)
2. URL discovery file is read more than expected as multiple requests can empty heap, causing the code to read URLs from the file.
Patch …

EaR: Update KMS URL refresh policy and fix bugs

---

fdbserver/KeyValueStoreRocksDB.actor.cpp
fdbserver/KeyValueStoreShardedRocksDB.actor.cpp

Avoiding read timeout checks for eager reads(write path) and system keys

Avoiding read timeout checks for eager reads(write path) and system keys

---

fdbclient/FileBackupAgent.actor.cpp
fdbserver/BlobGranuleValidation.actor.cpp
fdbserver/include/fdbserver/BlobGranuleValidation.actor.h
fdbserver/workloads/BlobGranuleVerifier.actor.cpp
fdbserver/workloads/BlobRestoreWorkload.actor.cpp

Need to cleanup blobGranuleLockKeys after restore. Otherwise change feed couldn't be created successfully. Also add post-restore test for BlobRestoreWorkload.

Remove blobGranuleLockKeys after blob granule restore

---

fdbclient/BlobCipher.cpp

AES CTR mode doesn't need padding: https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Padding

Remove unnecessary padding for encrypt/decrypt

---

fdbclient/BackupContainerFileSystem.actor.cpp

Cherry-Pick of #10488
100k correctness test passed: 20230614-210156-huliu-bf24d023013e27e1
This PR fixes a bug in computeRestoreEndVersion() when outLogs is null. It causes describeBackup() never updates continousLogEnd property on disk until deepScan is true. The correct behavior is to update continousLogEnd property when it's changed..

Fix computeRestoreEndVersion bug when outLogs is null (Cherry-Pick #10488 to snowflake/release-71.3)

---

fdbclient/FileBackupAgent.actor.cpp
fdbserver/BlobGranuleValidation.actor.cpp
fdbserver/include/fdbserver/BlobGranuleValidation.actor.h
fdbserver/workloads/BlobGranuleVerifier.actor.cpp
fdbserver/workloads/BlobRestoreWorkload.actor.cpp

Cherry-Pick of #10477
100k correctness test passed 20230613-171431-huliu-f7929f33f23508a7
Need to cleanup blobGranuleLockKeys after restore. Otherwise change feed couldn't be created successfully. Also add post-restore test for BlobRestoreWorkload.

Remove blobGranuleLockKeys after blob granule restore (Cherry-Pick #10477 to snowflake/release-71.3)

---

fdbserver/DDRelocationQueue.actor.cpp

Cherry-Pick of #10472
Passed 100k, ensemble ID: 20230613-213446-zhzhang-16e9e0c6de33229f
In a corner case, one pending DD request might be split into two requests, and fetchingSourcesQueue would take those two as single one.

Fix queued relocations missing (Cherry-Pick #10472 to snowflake/release-71.3)

---

fdbrpc/FlowTransport.actor.cpp

Cherry-Pick of #10495
The problem:
Server A has a network connection to Server B.
The normal expected behavior is that:
1. On Server B, Server A's peer is destroyed by connectionKeeper with PeerDestroy on a network error.
2. Server A sends a new message re-establishing the connection, re-creating the peer, with lastDataPacketSentTime=now().
But, if in between these (before the client tries to reconnect), something else on Server B recreates the Peer to A, the Peer will already exist when the connection comes in with an old lastDataPacketSentTime.
If the time that has passed between when the peer was recreated and when the new connection came in exceeded CONNECTION_MONITOR_UNREFERENCED_CLOSE_DELAY, connectionMonitor would immediately close the connection, retriggering …

Reset connection idle time when restarting connection monitor (Cherry-Pick #10495 to snowflake/release-71.3)

---

fdbserver/BlobGranuleServerCommon.actor.cpp
fdbserver/BlobWorker.actor.cpp
fdbserver/include/fdbserver/BlobGranuleServerCommon.actor.h

Cherry-Pick of #10463
100k normal correctness: 20230612-133549-jslocum-58ddfb4c1c3b3368: 0 failures
50k blobgranule correctness: 20230612-133515-jslocum-58ddfb4c1c3b3368: 0 failures

made blob metadata load lazily from EKP (Cherry-Pick #10463 to snowflake/release-71.3)

---

fdbserver/ConsistencyScan.actor.cpp

Cherry-Pick of #10492
UBSAN triggered because db size * replication factor > INT_MAX.
This was due to a bug of replication factor being higher than it should be when encountering errors, but is an actual issue when DB size > INT_MAX as well.
100k correctness: 20230614-135304-jslocum-bb8beb1830a43c52: 0 failures

fix consistency scan ubsan issue and replication factor calculation (Cherry-Pick #10492 to snowflake/release-71.3)

---

fdbclient/BackupContainerFileSystem.actor.cpp

This PR fixes a bug in computeRestoreEndVersion() when outLogs is null. It causes describeBackup() never updates continousLogEnd property on disk until deepScan is true. The correct behavior is to update continousLogEnd property when it's changed..

Fix computeRestoreEndVersion bug when outLogs is null

---

fdbserver/ConsistencyScan.actor.cpp

UBSAN triggered because db size * replication factor > INT_MAX.
This was due to a bug of replication factor being higher than it should be when encountering errors, but is an actual issue when DB size > INT_MAX as well.

fix consistency scan ubsan issue and replication factor calculation

---

documentation/sphinx/source/command-line-interface.rst
documentation/sphinx/source/consistency-scan.rst
documentation/sphinx/source/operations.rst
fdbcli/ConsistencyScanCommand.actor.cpp
fdbclient/include/fdbclient/ConsistencyScanInterface.actor.h
fdbserver/ConsistencyScan.actor.cpp

Cherry-Pick of #10465
- document consistency scan feature
- add "consistencyscan stats" command
- provide validation and clamping on user-specified knob value
- fix bug of not serializing last progress version/timestamp, causing them to be missing from status json + stats
100k correctness: 20230612-203911-jslocum-485d65b48e5efaf8: 2 failures, which look to be issues solved by #10496

misc operational and documentation improvements (Cherry-Pick #10465 to snowflake/release-71.3)

---

fdbrpc/include/fdbrpc/simulator.h
fdbserver/storageserver.actor.cpp

Cherry-pick #10491
100k correctness: 20230613-223128-jslocum-b603fbb4788e8127: 0 failures

fix retransmits in corruption check

---

fdbrpc/FlowTransport.actor.cpp

The problem:
Server A has a network connection to Server B.
The normal expected behavior is that:
1. On Server B, Server A's peer is destroyed by connectionKeeper with PeerDestroy on a network error.
2. Server A sends a new message re-establishing the connection, re-creating the peer, with lastDataPacketSentTime=now().
But, if in between these (before the client tries to reconnect), something else on Server B recreates the Peer to A, the Peer will already exist when the connection comes in with an old lastDataPacketSentTime.
If the time that has passed between when the peer was recreated and when the new connection came in exceeded CONNECTION_MONITOR_UNREFERENCED_CLOSE_DELAY, connectionMonitor would immediately close the connection, retriggering this loop.
The fix is to reset …

Reset connection idle time when restarting connection monitor

---

contrib/TestHarness2/test_harness/run.py

For 1% of test selections, select the test that's been run the fewest number of times, ignoring CPU statistics (in TestHarness2).

(snowflake/release-71.3) Increase coverage for slow tests in TestHarness2

---

fdbclient/include/fdbclient/RandomKeyValueUtils.h

For small key set, RandomStringSetGenerator may not try enough random key to generate unique key set.
Increase the retry for smaller key set number.
Test: passed 1000k `/randomKeyValueUtils/generate`

Fix RandomStringSetGenerator may not generate enough unique key

---

fdbserver/BlobGranuleValidation.actor.cpp

Buggified code could create an empty range if a test was using variable length null strings as keys.
Fixed it to check for this before flushing.

fix flushing empty range

---

fdbcli/TenantCommands.actor.cpp
fdbcli/tests/metacluster_fdbcli_tests.py
fdbserver/workloads/MetaclusterRestoreWorkload.actor.cpp
metacluster/include/metacluster/ConfigureTenant.actor.h
metacluster/include/metacluster/RestoreCluster.actor.h

If we restore a cluster and a previously created tenant was not included in the backup, then the tenant will be marked in an error state on the management cluster. It is then up to the operator to resolve the error, generally by deleting the tenant and recreating it if needed.
There is, however, the possibility that we restored a backup that was older than we wanted, and a newer backup would have the tenant. If we tried to restore the newer backup, it would not leave the previously missing tenant in a fully usable state.
We need to have a way to deal with this case. One option is to allow us to clear the error state of a tenant, and that can be performed before (or maybe even after) the second restore.
Test plan:
Joshua test
100K ensemble: 20230616-053206-yajin-c88e5c9fabb9b272 fail=2, …

Support restoring a cluster with a tenant in the error state
