apple/foundationdb

- fdbbackup/FileConverter.h
> Fix -t flag bug for fdbdecode

- tests/CMakeLists.txt
> Disable ClogTlog.toml due to ASAN failures

- flow/include/flow/genericactors.actor.h
As title
Test plan (TBD):
can add some code instantiating this template somewhere in a test. Not sure if it's necessary in this specific case, given how trivial this fix is.
> Fix a typo in one actor helper `filter(...)`

- fdbclient/include/fdbclient/VersionedMap.h
- fdbclient/include/fdbclient/WriteMap.h
> [snowflake/release-71.2] PTree improvements

- fdbbackup/backup.actor.cpp
- fdbclient/BackupContainer.h
- fdbclient/BackupContainerFileSystem.actor.cpp
- fdbclient/FDBTypes.h
> [Release 7.1] Enhance fdbbackup query command to estimate data processing from a specific snapshot to a target version

- fdbserver/workloads/AuthzSecurity.actor.cpp
Ensures that all privileged-level blob management functions cannot be called by an untrusted tenant.
Passes 10k AuthzSecurity* correctness.
> adding authz blob management tests

- fdbserver/BlobWorker.actor.cpp
Lumped two fixes in the same PR, in separate commits
- nightly failure with BlobWorkerUnexpectedErrorRangeAssign of granule_assignment_conflict
- leaked delta file write lock permits callback order issue
> Blob Granule correctness fixes

- fdbclient/NativeAPI.actor.cpp
- fdbclient/include/fdbclient/CommitProxyInterface.h
- fdbserver/CommitProxyServer.actor.cpp
- fdbserver/workloads/AuthzSecurity.actor.cpp
Comments from #9470
- Added FDB_BOOLEAN_PARAM for justGranules
- Changed Commit Proxy BlobGranuleLocationsReply to dedupe included BlobWorkerInterfaces
Passes 50k BlobGranule* correctness and 10k AuthzSecurity* correctness
> addressing review comments and fixmes in bg commit proxy code

- fdbserver/workloads/BlobGranuleRangesWorkload.actor.cpp
Passes 10k BlobGranuleRanges correctness
> added unit test for bg tenant deletion to make sure nothing breaks

- fdbclient/ServerKnobs.cpp
- fdbclient/include/fdbclient/ServerKnobs.h
- fdbserver/CommitProxyServer.actor.cpp
- fdbserver/include/fdbserver/ProxyCommitData.actor.h
Cherry pick of #9405 to `snowflake/release-71.2`.
> Adds more detailed mutation logging to commit proxy (snowflake/release-71.2)

- fdbserver/VersionedBTree.actor.cpp
… size to match the behavior of other storage engines.
Cherry-pick #9397 to snowflake/release-71.2
> Update StorageBytes::used reported by Redwood to be the physical file... (cherry-pick #9397 to snowflake/release-71.2)

- fdbserver/BlobManager.actor.cpp
- tests/TestRunner/upgrade_test.py
Cherry-pick #9519
Fixes flaky blob granule upgrade ctest
> [snowflake/release-71.3] bg ctest fixes

- fdbserver/workloads/SnapTest.actor.cpp
Reverts apple/foundationdb#8907
> Revert "(snowflake/release-71.2) Fail SnapTestWorkload if taking a snapshot fails"

- fdbserver/BlobManager.actor.cpp
- fdbserver/BlobMigrator.actor.cpp
> BlobRestore Add deepScan when describing backup

- tests/fast/RandomUnitTests.toml
- tests/noSim/RandomUnitTests.toml
- tests/rare/SpecificUnitTests.toml
> Disable empty range check in unit tests.

- fdbserver/CommitProxyServer.actor.cpp
- fdbserver/workloads/SpecialKeySpaceRobustness.actor.cpp
This allows us to report the appropriate non-retryable error instead
> Check transaction validity with respect to tenants even if it will fail with a conflict

- fdbclient/SpecialKeySpace.actor.cpp
Cherrypick #9449 to snowflake/release-71.2
> [snowflake/release-71.2] Improve space estimation in checkExclusion()

- CMakeLists.txt
- bindings/c/CMakeLists.txt
- tests/TestRunner/binary_download.py
> skip to 71.2.6

- fdbclient/ServerKnobs.cpp
- fdbclient/include/fdbclient/ServerKnobs.h
- fdbserver/DataDistributionQueue.actor.cpp
> add knob for min read rebalance shard bandwidth

- CMakeLists.txt
- bindings/c/CMakeLists.txt
- tests/TestRunner/binary_download.py
> version bump 71.2.6 to 71.2.7

- fdbserver/BlobManager.actor.cpp
- fdbserver/storageserver.actor.cpp
> [snowflake/release-71.3] More bg correctness fixes

- flowbench/CMakeLists.txt
trying to fix all the broken builds 
> update target_link with new path from build image

- fdbcli/StatusCommand.actor.cpp
- fdbclient/include/fdbclient/BlobGranuleCommon.h
- fdbserver/BlobManager.actor.cpp
- fdbserver/BlobManifest.actor.cpp
- fdbserver/BlobMigrator.actor.cpp
- fdbserver/ClusterController.actor.cpp
- fdbserver/Status.actor.cpp
- fdbserver/include/fdbserver/BlobGranuleServerCommon.actor.h
- fdbserver/workloads/BlobRestoreWorkload.actor.cpp
> Report restore phase start timestamp

- bindings/c/test/fdb_c_client_config_tests.py
> Disable client config trace check for previous version

- CMakeLists.txt
- bindings/c/CMakeLists.txt
Release version bump for snowflake/release-71.3.
Also disable `fdb_c_upgrade_from_prev...` tests.
> Release version bump for Snowflake release 71.3

- contrib/TestHarness2/test_harness/config.py
Note that this should not be merged until we update the protocol and API versions
> [snowflake/release-71.3] Changed restarting test old binaries to snowflake binaries

- tests/fast/RandomUnitTests.toml
Description
Remove Test pattern from RandomUnit Test
Testing
> Remove Test pattern from RandomUnit Test

- cmake/FDBComponents.cmake
- cmake/Findjemalloc.cmake
- fdbserver/CMakeLists.txt
By use jemalloc, it is possible to 
* Use system installed jemalloc
* Use a custom jemalloc by specifying jemalloc_ROOT_DIR 
> CMake find_package module for jemalloc

- fdbcli/tests/fdbcli_tests.py
> Update the expected error message from exclude in fdbcli_tests

- documentation/sphinx/source/release-notes/release-notes-710.rst
> Added 7.1.28 and 7.1.29 release notes

- fdbclient/RESTUtils.actor.cpp
Description
Fix RestUtilUnit test
Testing
RESTUtilUnits.toml
> Fix RestUtilUnit test

- fdbserver/DDTeamCollection.actor.cpp
- fdbserver/include/fdbserver/ExclusionTracker.actor.h
This is a precursor to adding blob worker exclusion, but is also a nice new component in general.
> add exclusion tracker utility and use it in DD

- bindings/python/CMakeLists.txt
> Disable Python unit tests in sanitizer builds [cherry-pick to snowflake/release-71.3]

- fdbclient/include/fdbclient/BlobMetadataUtils.h
- fdbserver/RESTKmsConnector.actor.cpp
Passes 1000 /RestKmsConnector unit tests
> fixing copy constructor error and adding test for it

- bindings/python/tests/fdbcli_tests.py
> [snowflake/release-71.2] Update the expected error message from exclude in fdbcli_tests

- fdbserver/BlobManager.actor.cpp
- fdbserver/include/fdbserver/ExclusionTracker.actor.h
- fdbserver/workloads/ConsistencyCheck.actor.cpp
Follow-on to #9669
Passes 50k BlobGranule* correctness and tested manually as well.
> adding implementation and check for blob worker exclusion

- fdbserver/KeyValueStoreSQLite.actor.cpp
Rewrite of changes made in #9724 to be easier to follow.
> Rewrite corrupt block number calculations to be more clear.

- fdbclient/include/fdbclient/ConsistencyScanInterface.actor.h
- fdbserver/ConsistencyScan.actor.cpp
- fdbserver/tester.actor.cpp
- fdbserver/workloads/ConsistencyCheck.actor.cpp
> Fix: the consistency check did not properly report failed tests

- CMakeLists.txt
- bindings/ruby/CMakeLists.txt
- bindings/ruby/fdb.gemspec.cmake
- bindings/ruby/lib/fdbimpl.rb
- documentation/sphinx/source/command-line-interface.rst
- fdbclient/BlobGranuleReader.actor.cpp
- fdbclient/include/fdbclient/BlobMetadataUtils.h
- fdbclient/include/fdbclient/ConsistencyScanInterface.actor.h
- fdbclient/include/fdbclient/FDBTypes.h
- fdbserver/ConsistencyScan.actor.cpp
- fdbserver/DDRelocationQueue.actor.cpp
- fdbserver/TenantCache.actor.cpp
- fdbserver/storageserver.actor.cpp
- fdbserver/tester.actor.cpp
- fdbserver/workloads/ConsistencyCheck.actor.cpp
- fdbserver/workloads/FastTriggeredWatches.actor.cpp
- flow/Hostname.actor.cpp
- flow/include/flow/error_definitions.h
cherrypick
20230317-225145-jzhou-91e21575ab43e825
20230317-012444-jzhou-73895584efd10958
> cherrypick multiple fixes [release-7.2]

- contrib/TestHarness2/test_harness/run.py
- contrib/TestHarness2/test_harness/summarize.py
1. Take the buggify config parameter into account when choosing to enable buggify
2. Report the last logged event and time when getting TestUnexpectedlyNotFinished
> A couple TestHarness2 improvements

- fdbserver/BlobWorker.actor.cpp
- fdbserver/include/fdbserver/BlobWorker.h
> [snowflake/release-71.3] Refactor struct BlobWorkerData and struct GranuleMetadata (#9659)

- bindings/c/test/fdb_c_client_config_tests.py
Improve stability test_external_client_not_matching_cluster_version_ignore for the case when protocol version fails to be determined within the 100ms timeout.
> Improve stability of client configuration test

- contrib/TestHarness2/test_harness/run.py
- contrib/TestHarness2/test_harness/summarize.py
Cherry-picks #9754 
1. Take the buggify config parameter into account when choosing to enable buggify
2. Report the last logged event and time when getting TestUnexpectedlyNotFinished
> A couple TestHarness2 improvements (snowflake/release-71.3)

- fdbclient/ServerKnobs.cpp
- fdbclient/include/fdbclient/ServerKnobs.h
- fdbrpc/include/fdbrpc/simulator.h
- fdbserver/ConsistencyScan.actor.cpp
- fdbserver/DDRelocationQueue.actor.cpp
- fdbserver/DDShardTracker.actor.cpp
- fdbserver/DDTeamCollection.actor.cpp
- fdbserver/DDTxnProcessor.actor.cpp
- fdbserver/DataDistribution.actor.cpp
- fdbserver/MoveKeys.actor.cpp
- fdbserver/ShardsAffectedByTeamFailure.cpp
- fdbserver/include/fdbserver/DDTeamCollection.h
- fdbserver/include/fdbserver/DataDistribution.actor.h
- fdbserver/include/fdbserver/DataDistributionTeam.h
- fdbserver/include/fdbserver/ShardsAffectedByTeamFailure.h
- fdbserver/tester.actor.cpp
- fdbserver/workloads/MockDDTrackerShardEvaluator.actor.cpp
> Added the ability to manually create a shard and also increase its replication factor

- fdbclient/ServerKnobs.cpp
> Rocksdb knob changes.

- fdbcli/MetaclusterCommands.actor.cpp
> Fix metacluster get segfault in fdbcli

- fdbclient/ServerKnobs.cpp
- fdbclient/include/fdbclient/ServerKnobs.h
- fdbserver/DDRelocationQueue.actor.cpp
- fdbserver/DataDistribution.actor.cpp
- fdbserver/include/fdbserver/DDRelocationQueue.h
- fdbserver/include/fdbserver/MovingWindow.h
> add a field to show average data movement bytes in MovingData trace (Cherry-Pick #9591 to snowflake/release-71.3)

- fdbcli/MetaclusterCommands.actor.cpp
> Fix metacluster get segfault in fdbcli (Cherry-Pick #9693 to snowflake/release-71.3)

- contrib/lint.py
> Add a linter scans for wait in when clause

- contrib/Joshua/scripts/binding_test_start.sh
- contrib/local_cluster/binding_test.py
- contrib/local_cluster/lib/cluster_file.py
- contrib/local_cluster/lib/fdb_process.py
- contrib/local_cluster/lib/local_cluster.py
- contrib/local_cluster/lib/process.py
- contrib/local_cluster/lib/work_directory.py
- contrib/local_cluster/local_cluster.py
This is the fix to the bindingtest2 package error.
The internal bindingtest will not output XML but some raw text, I believe translate this to XML at this stage is not so much important as long as the issue is locally reproducible.
> Fix the bindingtest2 package error

- fdbserver/include/fdbserver/MovingWindow.h
Add comments on the use case of `MovingWindow` and its difference with `Smoother`.
> add comment on where to use MovingWindow rather than Smoother

- fdbserver/BlobManager.actor.cpp
- fdbserver/workloads/ConsistencyCheck.actor.cpp
Running 10k BlobGranule* correctness
> fixing system priority flags usage in blob manager

- documentation/sphinx/source/release-notes/release-notes-710.rst
> Add 7.1.30, 7.1.31 release notes

- documentation/sphinx/source/release-notes/release-notes-710.rst
cherrypick #9823
Documentation changes.
> Add 7.1.30, 7.1.31 release notes [release-7.1]

- fdbclient/ServerKnobs.cpp
- fdbclient/include/fdbclient/ServerKnobs.h
- fdbserver/DataDistribution.actor.cpp
- fdbserver/DataDistributionQueue.actor.cpp
- fdbserver/include/fdbserver/MovingWindow.h
> add a field to show average data movement bytes in MovingData trace (Cherry-Pick #9591 to snowflake/release-71.2)

- fdbserver/BlobGranuleValidation.actor.cpp
- fdbserver/BlobWorker.actor.cpp
Cherry-Pick of #9780
In one test, this the read transaction lifetime was buggified to 100k versions, and that caused some granule open transactions to consistently get transaction too old until speed up simulation was set.
So I made 2 fixes
- Also adding some amount of time since speed up simulation was set for this check to quiesce
- Optimizing several serial reads to be parallel in granule open
Passes 25k BlobGranule* correctness
> optimzing latency of granule open and adding some buffer for speed up sim (Cherry-Pick #9780 to snowflake/release-71.3)

- fdbserver/ClusterController.actor.cpp
- fdbserver/DDRelocationQueue.actor.cpp
- fdbserver/include/fdbserver/BlobMigratorInterface.h
> Remove the data movement restriction for blob migrator

- fdbclient/RESTUtils.actor.cpp
Cherry Pick: https://github.com/apple/foundationdb/pull/9858
> [snowflake/release-71.3] Enable TLS with HTTPS connection

- fdbclient/SpecialKeySpace.actor.cpp
Back-port of https://github.com/apple/foundationdb/pull/9846
> Don't stop iterating over all storage processes in exclusion check

- fdbrpc/TokenSign.cpp
- tests/authorization/conftest.py
> Allow token "aud" field to have a string as value

- cmake/CompileRocksDB.cmake
- documentation/sphinx/source/release-notes/release-notes-710.rst
- fdbserver/KeyValueStoreRocksDB.actor.cpp
- fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
- fdbserver/RocksDBCheckpointUtils.actor.cpp
- fdbserver/include/fdbserver/RocksDBCheckpointUtils.actor.h
RocksDB 7.10.2 version upgrade
> RocksDB 7.10.2 version upgrade

- fdbserver/include/fdbserver/MovingWindow.h
Cherry-Pick of #9812
Add comments on the use case of `MovingWindow` and its difference with `Smoother`.
> add comment on where to use MovingWindow rather than Smoother (Cherry-Pick #9812 to snowflake/release-71.2)

- fdbserver/LeaderElection.actor.cpp
Fdbserver not able to join cluster (during upgrade): Address this by allowing the process to
proceed with an updated connection string even if a majority of coordinators (in the stale connection string) don't reply.
Testing:
- Wrote a manual test (using a loopback cluster) that shows this problem, and verified that this change set addresses the issue. Will try to write an automated test for it (in chaos test framework).
- Simulation tests: 
Job id: 20230327-190152-sre-30c5ebb6d951ad3e (shows failures in "tests/restarting/from_7.3.0/DrUpgradeRestart-1.toml" and "tests/restarting/from_7.3.0/DrUpgradeRestart-2.toml" tests; I see those failures in nightly tests too, so I don't think they were caused by this change set). …
> FdbServer not able to join cluster

- fdbclient/ManagementAPI.actor.cpp
- fdbclient/ManagementAPI.actor.h
- fdbclient/SpecialKeySpace.actor.cpp
> [Release 7.1] Check if the locality is already excluded before issuing exclude locality transaction

- fdbcli/StatusCommand.actor.cpp
- fdbserver/BlobManager.actor.cpp
- fdbserver/BlobMigrator.actor.cpp
- fdbserver/Status.actor.cpp
> Add blob manifest and mutation log status to fdbcli

- documentation/sphinx/source/release-notes/release-notes-710.rst
> Update 7.1.30 release notes

- fdbclient/BackupAgentBase.actor.cpp
- fdbclient/CommitProxyInterface.cpp
- fdbclient/FileBackupAgent.actor.cpp
- fdbclient/include/fdbclient/CommitProxyInterface.h
- fdbclient/include/fdbclient/CommitTransaction.h
- fdbclient/include/fdbclient/GetEncryptCipherKeys.h
- fdbclient/include/fdbclient/GetEncryptCipherKeys_impl.actor.h
- fdbserver/BackupWorker.actor.cpp
- fdbserver/BlobWorker.actor.cpp
- fdbserver/CommitProxyServer.actor.cpp
- fdbserver/KeyValueStoreMemory.actor.cpp
- fdbserver/Resolver.actor.cpp
- fdbserver/RestoreLoader.actor.cpp
- fdbserver/StorageCache.actor.cpp
- fdbserver/include/fdbserver/IPageEncryptionKeyProvider.actor.h
- fdbserver/include/fdbserver/IPager.h
- fdbserver/include/fdbserver/ServerDBInfo.actor.h
- fdbserver/masterserver.actor.cpp
- fdbserver/storageserver.actor.cpp
- fdbserver/worker.actor.cpp
- fdbserver/workloads/EncryptKeyProxyTest.actor.cpp
> Revert "Revert "Refactor GetEncryptCipherKeys (#9600)""

- fdbclient/BackupAgentBase.actor.cpp
- fdbclient/CommitProxyInterface.cpp
- fdbclient/FileBackupAgent.actor.cpp
- fdbclient/include/fdbclient/CommitProxyInterface.h
- fdbclient/include/fdbclient/CommitTransaction.h
- fdbclient/include/fdbclient/GetEncryptCipherKeys.h
- fdbclient/include/fdbclient/GetEncryptCipherKeys_impl.actor.h
- fdbserver/BackupWorker.actor.cpp
- fdbserver/BlobWorker.actor.cpp
- fdbserver/CommitProxyServer.actor.cpp
- fdbserver/KeyValueStoreMemory.actor.cpp
- fdbserver/Resolver.actor.cpp
- fdbserver/RestoreLoader.actor.cpp
- fdbserver/StorageCache.actor.cpp
- fdbserver/include/fdbserver/IPageEncryptionKeyProvider.actor.h
- fdbserver/include/fdbserver/IPager.h
- fdbserver/include/fdbserver/ServerDBInfo.actor.h
- fdbserver/masterserver.actor.cpp
- fdbserver/storageserver.actor.cpp
- fdbserver/worker.actor.cpp
- fdbserver/workloads/EncryptKeyProxyTest.actor.cpp
> [snowflake/release-71.3] Refactor GetEncryptCipherKeys

- flow/Platform.actor.cpp
Cherry picks #9895.
The signal handler for the run loop profiler accesses a variable called chainedSignalHandler that is configured after the signal handler is set. This introduces a brief period where there could be a race between getting the signal and accessing chainedSignalHandler and the variable being set.
Instead, this change updates the logic so that we use the struct sigaction returned from the sigaction call directly and avoid modifying it after setting the signal handler.
> Avoid a thread race trying to initialize the chained signal handler (snowflake/release-71.3)

- fdbclient/include/fdbclient/GetEncryptCipherKeys_impl.actor.h
- fdbserver/BlobGranuleServerCommon.actor.cpp
- fdbserver/ClusterController.actor.cpp
- fdbserver/CommitProxyServer.actor.cpp
- fdbserver/Status.actor.cpp
- fdbserver/include/fdbserver/ClusterController.actor.h
- fdbserver/include/fdbserver/ServerDBInfo.actor.h
- fdbserver/worker.actor.cpp
- fdbserver/workloads/ConsistencyCheck.actor.cpp
- fdbserver/workloads/EncryptKeyProxyTest.actor.cpp
> [snowflake/release-71.3] Remove EKP Interface from ServerDBInfo

- fdbcli/tests/fdbcli_tests.py
- fdbclient/ServerKnobs.cpp
- fdbclient/include/fdbclient/ServerKnobs.h
- fdbserver/VersionedBTree.actor.cpp
- fdbserver/worker.actor.cpp
Cherry-pick #9794  #9902
@jzhou77  can you let me know who will be the right reviewer for the cherry-picks?
> Cherry-pick #9794 && #9902 from main to release-7.3

- fdbclient/ServerKnobs.cpp
- fdbclient/ServerKnobs.h
- fdbserver/ClusterController.actor.cpp
- fdbserver/ClusterController.actor.h
- fdbserver/worker.actor.cpp
> [Release 7.1] Gray failure detects disconnected remote log router and recover high DC lag

- fdbserver/DDTeamCollection.actor.cpp
In this simulation test, there were 2 transaction class processes and one storage class processes in one of the data halls.
Fault injection was enabled on the storage and one of the transaction processes.
During the test, the storage processes kept getting io_timeouts. In this case, our desired behavior is to "hang" the storage process and try to rebuild a third replica from the other storage processes, because an io_timeout can indicate larger problems with a disk, including durability problems.
However, because recruitment did not exclude failed processes, and allows itself to recruit up to 3 storage servers on one process, we eventually had 3 storage servers that were all hung in this io_timeout state on the one storage class process.
And, because the storage team including this host …
> solving strange recruitment deadlock in three_data_hall

- flow/ActorCollection.actor.cpp
Simple unit tests for validating actor collection shutdown contract.
Reproduces the bug in the storage server from #9926 cleanly and provides an easy regression test if these assumptions the SS makes of the actor collection ever fail.
Passes 10k /flow/actorCollection/testCancel* unit tests.
> adding simple unit tests to validate actor collection cancel behavior

- flow/ActorCollection.actor.cpp
Cherry-Pick of #9929
Simple unit tests for validating actor collection shutdown contract.
Reproduces the bug in the storage server from #9926 cleanly and provides an easy regression test if these assumptions the SS makes of the actor collection ever fail.
Passes 10k /flow/actorCollection/testCancel* unit tests.
> adding simple unit tests to validate actor collection cancel behavior (Cherry-Pick #9929 to snowflake/release-71.3)

- fdbclient/BlobCipher.cpp
- fdbclient/include/fdbclient/BlobCipher.h
- fdbserver/include/fdbserver/IPager.h
- fdbserver/workloads/ReadAfterWrite.actor.cpp
- flowbench/BenchEncrypt.cpp
Cherry-Pick of #9610
* Add decrypt/encyptInplace() API to avoid memcpy
* fix a header size bug, which can override payload while set header
microbenchmark shows inplace encrypt/decrypt are 2-3x faster:
```
$ bin/flowbench --benchmark_filter=blob_chipher
-----------------------------------------------------------------------------------------
Benchmark                                               Time             CPU   Iterations
-----------------------------------------------------------------------------------------
blob_chipher_encrypt/pageLen:8000/isInplace:0        7128 ns         7128 ns        98946
blob_chipher_encrypt/pageLen:8000/isInplace:1        2505 ns         2505 ns       279544
blob_chipher_encrypt/pageLen:16000/isInplace:0      14299 ns        14299 …
```
> Add inplace encryption and decryption API (Cherry-Pick #9610 to snowflake/release-71.3)

- fdbcli/tests/metacluster_fdbcli_tests.py
Cherry-Pick of #9802
Test plan:
```bash
mkdir build && cd build && cmake -G Ninja ..
ninja fdbcli fdbserver fdbmonitor
ctest -R metacluster_fdbcli_tests
```
> Add test coverage for metacluster operations via fdbcli (Cherry-Pick #9802 to snowflake/release-71.3)

- fdbserver/workloads/ReadAfterWrite.actor.cpp
Revert a minor naming change from #9610
> Revert a minor naming change by mistake

- fdbserver/include/fdbserver/WorkerInterface.actor.h
Sometimes simulation can take a long simulated time to complete I/O request, e.g., in TLog's initial commit: "wait(self->persistentData->commit());". This type of slow I/O seems to happen quite often, as "KVCommit10sSample" events show many such occurrences, which are not causing problems in most cases.
This PR treats such error in simulation as injected ones so that it won't cause test to emit SevError events.
Reproduction:
- seed: `-f ./tests/fast/MutationLogReaderCorrectness.toml  -s 372173044 -b on`
- Branch: [release-7.1](https://github.com/apple/foundationdb/tree/release-7.1)
- Commit ID: [451a8ae424fcb3acd056f682409ea5dd605e106e](https://github.com/apple/foundationdb/commit/451a8ae424fcb3acd056f682409ea5dd605e106e)
20230406-163514-jzhou-39d1e322baa07eb4 …
> Fix simulation IoTimeoutError error

- fdbserver/BlobWorker.actor.cpp
- fdbserver/include/fdbserver/BlobWorker.h
> Disallow Unencrypted Blob Worker from Joining Encrypted Cluster

- fdbserver/GlobalTagThrottler.actor.cpp
This is a backport of https://github.com/apple/foundationdb/pull/9978.
> (snowflake/release-71.3) Update `GlobalTagThrottlerImpl::tryUpdateAutoThrottling`

- fdbclient/ServerKnobs.cpp
- fdbclient/include/fdbclient/ServerKnobs.h
- fdbserver/Ratekeeper.actor.cpp
- fdbserver/TransactionTagCounter.cpp
This is a backport of https://github.com/apple/foundationdb/pull/9980.
> (snowflake/release-71.3) Fix semantics of `MIN_TAG_*_PAGES_RATE` knobs

- contrib/cherry-pick-upstream.py
> Add a script that helps cherry-picking PR commits to other branches

- fdbclient/NativeAPI.actor.cpp
- fdbclient/include/fdbclient/ServerKnobs.h
- fdbclient/include/fdbclient/StorageServerInterface.h
- fdbserver/DDRelocationQueue.actor.cpp
- fdbserver/DDTeamCollection.actor.cpp
- fdbserver/StorageMetrics.actor.cpp
- fdbserver/include/fdbserver/DataDistributionTeam.h
- fdbserver/include/fdbserver/TCInfo.h
> fix HealthMetrics update bug and correct comments about readLoadKSecond()

- fdbclient/BackupAgentBase.actor.cpp
- fdbclient/FileBackupAgent.actor.cpp
- fdbclient/include/fdbclient/GetEncryptCipherKeys_impl.actor.h
- fdbserver/workloads/EncryptKeyProxyTest.actor.cpp
> [snowflake/release-71.3] Propagate Encryption Errors Properly

- flow/Platform.actor.cpp
Cherry-Pick of #9950
…latform.actor.cpp(3769,18): error : variable has incomplete type 'struct sigaction'
Still another error though,
```   106>CUSTOMBUILD : Configuration error :  [C:\ci\fdb_pr_builder\run\build\documentation\html.vcxproj]
There is a programmable error in your configuration file:
File "C:\Python310\lib\site-packages\sphinx\config.py", line 351, in eval_config_file
exec(code, namespace)  # NoQA: S102
File "C:\ci\fdb_pr_builder\run\foundationdb\documentation\sphinx\conf.py", line 13, in <module>
import sphinx_bootstrap_theme
ModuleNotFoundError: No module named 'sphinx_bootstrap_theme'
``` …
> fix windows build error: C:/ci/fdb_pr_builder/run/foundationdb/flow/P… (Cherry-Pick #9950 to snowflake/release-71.3)

- fdbclient/NativeAPI.actor.cpp
- fdbclient/ServerKnobs.cpp
- fdbclient/include/fdbclient/DatabaseContext.h
- fdbclient/include/fdbclient/ServerKnobs.h
- fdbclient/include/fdbclient/StorageServerInterface.h
- fdbserver/DDRelocationQueue.actor.cpp
- fdbserver/DDShardTracker.actor.cpp
- fdbserver/DDTeamCollection.actor.cpp
- fdbserver/DDTxnProcessor.actor.cpp
- fdbserver/DataDistribution.actor.cpp
- fdbserver/StorageMetrics.actor.cpp
- fdbserver/TCInfo.actor.cpp
- fdbserver/include/fdbserver/DDTeamCollection.h
- fdbserver/include/fdbserver/DDTxnProcessor.h
- fdbserver/include/fdbserver/DataDistribution.actor.h
- fdbserver/include/fdbserver/DataDistributionTeam.h
- fdbserver/include/fdbserver/TCInfo.h
- tests/rare/SpecificUnitTests.toml
> Improve getTeam to prevent disk and read rebalance contention (cherry-pick snowflake/release-71.3)

- fdbserver/Status.actor.cpp
> Empty check before calling openContainer on it

- fdbserver/DDTeamCollection.actor.cpp
Add trace event "TeamEligibilityCount" to indicate that how many team has passed CPU or Space pivot check.
> Add trace event "TeamEligibilityCount"

- fdbserver/storageserver.actor.cpp
Cherry-Pick of #10045
If a PTree set is overlap with a range clear, the insert could be expensive. Add a metric to track such operation.
> Add basic PTree metrics (Cherry-Pick #10045 to snowflake/release-71.2)

- fdbserver/tester.actor.cpp
This is a backport of https://github.com/apple/foundationdb/pull/10037.
> (snowflake/release-71.3) Make test progress tracing in `runWorkload` consistent

- fdbserver/worker.actor.cpp
- fdbserver/workloads/ConsistencyCheck.actor.cpp
cherrypick #10066
20230428-172448-jzhou-7862a4a0cf833cea
> Fix ConsistencyCheck_InvalidShardSize due to unfair split [release-7.1]

- documentation/sphinx/source/mr-status-json-schemas.rst.inc
- fdbclient/Schemas.cpp
- fdbclient/include/fdbclient/KeyBackedTypes.actor.h
- fdbserver/DDTeamCollection.actor.cpp
- fdbserver/MoveKeys.actor.cpp
- fdbserver/Status.actor.cpp
- fdbserver/include/fdbserver/DDTeamCollection.h
- fdbserver/workloads/ConsistencyCheck.actor.cpp
> Write storage_metadata for TSS and add test for it

- fdbclient/ServerKnobs.cpp
- fdbclient/include/fdbclient/ServerKnobs.h
- fdbserver/DDShardTracker.actor.cpp
- fdbserver/DDTeamCollection.actor.cpp
> fix: do not let too many shards use large teams

- documentation/sphinx/source/mr-status-json-schemas.rst.inc
- fdbclient/Schemas.cpp
- fdbclient/include/fdbclient/KeyBackedTypes.actor.h
- fdbserver/DDTeamCollection.actor.cpp
- fdbserver/MoveKeys.actor.cpp
- fdbserver/Status.actor.cpp
- fdbserver/include/fdbserver/DDTeamCollection.h
- fdbserver/workloads/ConsistencyCheck.actor.cpp
> Write storage_metadata for TSS and add test for it (Cherry-Pick #10073 to snowflake/release-71.3)

- fdbserver/RESTKmsConnector.actor.cpp
Description
'Type' is a reserved keywork for TraceEvent, RESTKmsConnector was usng 'Type' to log CipherDetail or BlobMetadata type information. It causes 'fdbserver' binary to crash/restart
Patch addresses the usage to ensure TraceEvent compatibility is maintained. Further, it proposes following test improvements:
1. Fix existing unit-test that 'should' have caught this issue.
2. Add more test coverage.
3. Add CODE_PROBE to ensure relevant corner cases are validated.
Testing
RESTKmsConnectorUnit
> EaR: Avoid RESTKmsConnector code to use 'Type' in TraceEvents

- fdbclient/NativeAPI.actor.cpp
- fdbclient/ServerKnobs.cpp
- fdbclient/include/fdbclient/DatabaseContext.h
- fdbclient/include/fdbclient/ServerKnobs.h
- fdbclient/include/fdbclient/StorageServerInterface.h
- fdbserver/DDTeamCollection.actor.cpp
- fdbserver/DDTxnProcessor.actor.cpp
- fdbserver/DataDistributionQueue.actor.cpp
- fdbserver/DataDistributionTracker.actor.cpp
- fdbserver/StorageMetrics.actor.cpp
- fdbserver/TCInfo.actor.cpp
- fdbserver/include/fdbserver/DDTeamCollection.h
- fdbserver/include/fdbserver/DDTxnProcessor.h
- fdbserver/include/fdbserver/DataDistribution.actor.h
- fdbserver/include/fdbserver/TCInfo.h
cherry-pick https://github.com/apple/foundationdb/pull/9944 and https://github.com/apple/foundationdb/pull/9964 .
100k correctness pass.
> Improve getTeam to prevent disk and read rebalance contention (cherry-pick snowflake/release-71.2)

- documentation/sphinx/source/release-notes/release-notes-710.rst
> Add 7.1.32, 7.1.33 release notes

- documentation/sphinx/source/release-notes/release-notes-710.rst
> Add 7.1.32, 7.1.33 release notes [release-7.1]

- fdbserver/DDRelocationQueue.actor.cpp
> Enable MovingData to show overall moved bytes rather than just one copy

- documentation/sphinx/requirements.txt
Add urllib3<2 to requirements.txt for Sphinx
> Add urllib3<2 to requirements.txt for Sphinx

- fdbserver/RESTKmsConnector.actor.cpp
Description
'Type' is a reserved keyword for TraceEvent, RESTKmsConnector was using 'Type' to log CipherDetail or BlobMetadata type information. It causes 'fdbserver' binary to crash/restart
Patch addresses the usage to ensure TraceEvent compatibility is maintained. Further, it proposes following test improvements:
1. Fix existing unit-test that 'should' have caught this issue.
2. Add more test coverage.
3. Add CODE_PROBE to ensure relevant corner cases are validated.
Testing
RESTKmsConnectorUnit
(cherry picked from commit 7e872c4a590ebecf720b6ebf90e6fea8b1ccafa4)
(https://github.com/apple/foundationdb/pull/10108) …
> EaR: Avoid RESTKmsConnector code to use 'Type' in TraceEvents (#10108)

- fdbclient/SystemData.cpp
Bug fix, check is supposed to be for overlap, not lack of overlap.
> Bug fix, check is supposed to be for overlap, not lack of overlap.

- documentation/sphinx/requirements.txt
> Add urllib3<2 to requirements.txt for Sphinx [release-7.1]

- documentation/sphinx/requirements.txt
> Add urllib3<2 to requirements.txt for Sphinx [release-7.3]

- fdbclient/include/fdbclient/BlobGranuleCommon.h
- fdbserver/BlobManager.actor.cpp
- fdbserver/BlobManifest.actor.cpp
- fdbserver/BlobMigrator.actor.cpp
- fdbserver/BlobWorker.actor.cpp
- fdbserver/include/fdbserver/BlobGranuleServerCommon.actor.h
- fdbserver/storageserver.actor.cpp
- fdbserver/workloads/BlobGranuleCorrectnessWorkload.actor.cpp
- fdbserver/workloads/BlobRestoreWorkload.actor.cpp
Add encryption support for blob manifest files. Passed 100K Blob test
> Add manifest encryption

- bindings/c/test/apitester/tests/CApiBlobGranuleCorrectnessBlocking.toml
- bindings/c/test/apitester/tests/CApiBlobGranuleCorrectnessMultiThr.toml
- bindings/c/test/apitester/tests/CApiBlobGranuleEncryptionCorrectnessMultiThr.toml
- bindings/c/test/apitester/tests/CApiBlobGranuleErrorsDBPerTX.toml
- bindings/c/test/apitester/tests/CApiBlobGranuleTenantEncryptionCorrectnessDBPerTX.toml
- bindings/c/test/apitester/tests/CApiBlobGranuleTenantEncryptionCorrectnessMultiThr.toml
Passes 100 of each of the new tests with the fix from #10086
> adding DBPerTXN blob granule tests

- fdbclient/ServerKnobs.cpp
- fdbserver/ConsistencyScan.actor.cpp
- fdbserver/DataDistribution.actor.cpp
Also made the consistency scan verify the proper number of shards have been over replicated
> buggified max_shards_on_large_teams

- fdbserver/workloads/MetaclusterManagementWorkload.actor.cpp
Cherry-Pick of #10175
In MetaclusterManagementWorkload, if we lock a tenant that has already been locked with a different lockId, it's possible that a tenant_locked error is thrown. We need to account for this instead of terminating the test.
Test plan:
Regular simulation and a deterministic reproduction
Branch: https://github.com/sfc-gh-yajin/foundationdb/tree/snow-791039
Commit hash: 7356504723d3c77de501b5683b0a159676c56840
Profile: team
Command: devRetryCorrectnessTest bin/fdbserver -r simulation -f tests/slow/MetaclusterManagement.toml -s 3475230174 -b off --crash --trace_format json
Please check each of the following things and check …
> Account for 'tenant_locked' error in MetaclusterManagementWorkload (Cherry-Pick #10175 to snowflake/release-71.3)

- .flake8
- bindings/bindingtester/__init__.py
- bindings/c/test/fdb_c_client_config_tests.py
- bindings/python/fdb/__init__.py
- bindings/python/fdb/impl.py
- bindings/python/tests/tuple_tests.py
- contrib/TestHarness2/test_harness/joshua.py
- contrib/apiversioner.py
- contrib/cherry-pick-upstream.py
- contrib/commit_debug.py
- contrib/lint.py
- contrib/local_cluster/binding_test.py
- contrib/serialize-check/script/renormalize.py
- documentation/sphinx/conf.py
- documentation/sphinx/extensions/relativelink.py
- packaging/make_public.py
- tests/TestRunner/TestRunner.py
- tests/TestRunner/authz_util.py
- tests/TestRunner/tmp_multi_cluster.py
- tests/authorization/admin_server.py
- tests/authorization/authz_test.py
- tests/authorization/conftest.py
- tests/authorization/util.py
- tests/python_tests/multithreaded_client.py
This also ignores E402, which detects when we have module level import statements not at the top of the file, since we have many files that use this pattern and are not easy to fix.
> Fix several issues found by flake8

- design/encryption-data-at-rest.md
- flow/EncryptUtils.cpp
Description
Updates FDB Encryption at-rest design document as per the recent changes
Testing
> EaR: Update encryption at-rest design with recent changes

- .flake8
- bindings/bindingtester/__init__.py
- bindings/c/test/fdb_c_client_config_tests.py
- bindings/python/fdb/__init__.py
- bindings/python/fdb/impl.py
- bindings/python/tests/tuple_tests.py
- contrib/TestHarness2/test_harness/joshua.py
- contrib/apiversioner.py
- contrib/commit_debug.py
- contrib/local_cluster/binding_test.py
- documentation/sphinx/conf.py
- documentation/sphinx/extensions/relativelink.py
- packaging/make_public.py
- tests/TestRunner/TestRunner.py
- tests/TestRunner/authz_util.py
- tests/TestRunner/tmp_multi_cluster.py
- tests/authorization/admin_server.py
- tests/authorization/authz_test.py
- tests/authorization/conftest.py
- tests/authorization/util.py
- tests/python_tests/multithreaded_client.py
Cherry picks #10093 
This also ignores E402, which detects when we have module level import statements not at the top of the file, since we have many files that use this pattern and are not easy to fix.
> Fix several issues found by flake8 (snowflake/71.3)

- fdbserver/Status.actor.cpp
- fdbserver/workloads/GcGenerations.actor.cpp
Currently, "tlog" roles are only marked for the latest generation TLogs.
> Status json should show tlog roles for old generation tlogs.

- fdbserver/Status.actor.cpp
> [release 7.3] Status json should show tlog roles for old generation tlogs

- fdbserver/Status.actor.cpp
> [release 7.1] Status json should show tlog roles for old generation tlogs

- fdbclient/RESTClient.actor.cpp
> copying headers into http request

- fdbclient/RESTClient.actor.cpp
> fixing headers

- design/encryption-data-at-rest.md
- flow/EncryptUtils.cpp
Description
Updates FDB Encryption at-rest design document as per the recent changes
Testing
(cherry picked from commit 03dc8e07a5378a144333352dfbdc0437747aa4ba, PR https://github.com/apple/foundationdb/pull/10168)
> EaR: Update encryption at-rest design with recent changes (#10168)

- documentation/sphinx/source/release-notes/release-notes-710.rst
- fdbclient/ServerKnobs.cpp
> Add 7.1.32, 7.1.33 release notes [release-7.3]

- flow/ApiVersions.cmake
> Update FDB_AV_LATEST_BINDINGS_VERSION to 730

- fdbrpc/HTTP.actor.cpp
- flow/include/flow/IDispatched.h
Also clean up a bit of comments in IDispatch
> Use fmt::print instead of printf 

- fdbserver/MoveKeys.actor.cpp
- fdbserver/workloads/PhysicalShardMove.actor.cpp
- tests/fast/PhysicalShardMove.toml
> Fix psm test

- fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
> Initialize counter.

- tests/rare/SpecificUnitTests.toml
> Fix a test pattern so that simulator tests do not run non-sim tests

- fdbserver/ConsistencyScan.actor.cpp
In `consistencyScan()`, a pointer to a state variable `memState` is passed to `consistencyScanCore()`.
Later, `consistencyScan()` returns and frees the memory of `memState`. However, `consistencyScanCore()` continues
to access it, thus causing use-after-free.
How to repro
asan, or valgrind
Commit: 686bd529531e15dc54265fffa479a6aa3a26559b
Command:
```
devRetryCorrectnessTest bin/fdbserver -r simulation -f tests/fast/AtomicBackupToDBCorrectness.toml -s 2263819634 -b on  --crash --trace_format json
```
The fix is to replace raw pointer with `Reference`. …
> Fix use-after-free in ConsistencyScan

- fdbserver/CommitProxyServer.actor.cpp
- fdbserver/ConsistencyScan.actor.cpp
> Fix ConsistencyCheck_DataInconsistent failure in simulation [release-7.3]

- CMakeLists.txt
- bindings/c/CMakeLists.txt
- tests/TestRunner/binary_download.py
> Bump version from 71.2.8 to 71.2.9

- fdbclient/NativeAPI.actor.cpp
- fdbclient/include/fdbclient/DatabaseContext.h
> Add `OutstandingWatches` and `WatchMapSize` to `TransactionMetrics`

- fdbclient/NativeAPI.actor.cpp
- fdbclient/include/fdbclient/DatabaseContext.h
This is a backport of https://github.com/apple/foundationdb/pull/10297.
> (snowflake/release-71.2) Add `OutstandingWatches` and `WatchMapSize` to `TransactionMetrics`

- tests/slow/ApiCorrectness.toml
> Revert unintended changes to APICorrectnessTest.

- flow/ApiVersions.cmake
> [Release 7.3] Update FDB_AV_LATEST_BINDINGS_VERSION to 730

- fdbclient/SpecialKeySpace.actor.cpp
> [snowflake/release-71.2] Fix two bugs in checkExclusion() and add a trace event (cherry-picked from #10330)

- fdbserver/worker.actor.cpp
This is for preparing tracking recovered peers in the worker.
This PR should be a no-op.
20230523-210510-zhewu-gray-refactor-00ba9bda40cbc9fd
> Refactor healthMonitor in worker.actor.cpp

- bindings/go/src/fdb/doc.go
- bindings/java/pom.xml.in
- bindings/java/src/main/overview.html.in
- bindings/python/README.rst
- bindings/ruby/fdb.gemspec.cmake
- bindings/ruby/fdb.gemspec.in
- packaging/docker/samples/local/README.md
- tests/CMakeLists.txt
update links to foundationdb.org to reference GitHub
> update links to foundationdb.org to reference GitHub (main)

- bindings/go/src/fdb/doc.go
- bindings/java/pom.xml.in
- bindings/java/src/main/overview.html.in
- bindings/python/README.rst
- bindings/ruby/fdb.gemspec.cmake
- bindings/ruby/fdb.gemspec.in
- packaging/docker/samples/local/README.md
- tests/CMakeLists.txt
update links to foundationdb.org to reference GitHub
> update links to foundationdb.org to reference GitHub (7.3)

- bindings/go/src/fdb/doc.go
- bindings/java/pom.xml.in
- bindings/java/src/main/overview.html.in
- bindings/python/README.rst
- bindings/ruby/fdb.gemspec.cmake
- bindings/ruby/fdb.gemspec.in
- packaging/docker/samples/local/README.md
- tests/CMakeLists.txt
update links to foundationdb.org to reference GitHub
> update links to foundationdb.org to reference GitHub (7.2)

- bindings/go/src/fdb/doc.go
- bindings/java/pom.xml.in
- bindings/java/src/main/overview.html.in
- bindings/python/README.rst
- bindings/ruby/fdb.gemspec.cmake
- bindings/ruby/fdb.gemspec.in
- packaging/docker/samples/local/README.md
- tests/CMakeLists.txt
update links to foundationdb.org to reference GitHub
> update links to foundationdb.org to reference GitHub (7.1)

- fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
> Sharded RocksDB logging and testing improvements. 

- contrib/TestHarness2/test_harness/run.py
- contrib/joshua_logtool.py
> Fix joshua logtool (release-7.3)

- fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
- fdbserver/storageserver.actor.cpp
- fdbserver/worker.actor.cpp
> Clear metadata before destroyDB.

- fdbrpc/include/fdbrpc/LoadBalance.actor.h
- fdbserver/storageserver.actor.cpp
100k correctness: 20230607-141115-jslocum-8023d630fb37dc24: 0 failures
> removing verbose logs that are not useful for 71.3

- fdbserver/PaxosConfigConsumer.actor.cpp
Cherry pick of #10418 to `snowflake/release-71.3`.
> Handle operation_cancelled properly in configuration database (snowflake/release-71.3)

- fdbcli/LocationMetadataCommand.actor.cpp
> Print server IP address. (#10423)

- fdbserver/DDTeamCollection.actor.cpp
> Add logs to track storage server status.

- fdbserver/BlobManager.actor.cpp
- fdbserver/Status.actor.cpp
This PR is to add more fields to status json for ease of management. It also refactor mutation log truncation function. 
> Add blob manifest url and mlogs url in status json.

- fdbcli/MetaclusterCommands.actor.cpp
- fdbcli/include/fdbcli/fdbcli.actor.h
- fdbcli/tests/metacluster_fdbcli_tests.py
Adding to main and then to 71.3
> Add tenant_id_prefix to metacluster status

- contrib/TestHarness2/test_harness/run.py
- contrib/joshua_logtool.py
* Fix the issue that JoshuaLogTool is not called when the test fails.
> fixup! Fix various issues in test_harness

- CMakeLists.txt
> Bump version from 71.3.0 to 71.3.1

- fdbcli/MetaclusterCommands.actor.cpp
- fdbcli/include/fdbcli/fdbcli.actor.h
- fdbcli/tests/metacluster_fdbcli_tests.py
Cherry-Pick of #10455
Adding to main and then to 71.3
> Add tenant_id_prefix to metacluster status (Cherry-Pick #10455 to snowflake/release-71.3)

- bindings/flow/Tuple.h
backporting https://github.com/apple/foundationdb/pull/10479
> Add comments for VERSIONSTAMP_96_CODE(release-7.3)

- contrib/TestHarness2/test_harness/run.py
- contrib/joshua_logtool.py
This is a cherrypick of #10469 to release-7.3
> Cherry-pick the bugfix for joshua_logtool.py to release 7.3

- fdbserver/DDRelocationQueue.actor.cpp
- fdbserver/DataDistribution.actor.cpp
- fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
- fdbserver/workloads/PhysicalShardMove.actor.cpp
Cherry-pick #10407 #10425 #10462 to release-7.3
> Cherry-pick #10407 #10425 #10462 to 7.3

- fdbserver/BlobGranuleServerCommon.actor.cpp
- fdbserver/BlobWorker.actor.cpp
- fdbserver/include/fdbserver/BlobGranuleServerCommon.actor.h
> made blob metadata load lazily from EKP

- fdbserver/KeyValueStoreRocksDB.actor.cpp
- fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
cherry-pick of #10486
Avoiding read timeout checks for eager reads(write path) and system keys
> Avoiding read timeout checks for eager reads(write path) and system keys

- fdbserver/Status.actor.cpp
- flow/Error.cpp
- flow/Trace.cpp
- flow/include/flow/Error.h
> Report missing attribute in StorageServer status

- fdbclient/ServerKnobs.cpp
> [Release 7.3] Turn on batching empty peek by default

- metacluster/include/metacluster/ConfigureTenant.actor.h
> SNOW-XXXXXX Mark a rare code probe as rare

- fdbserver/DDTeamCollection.actor.cpp
- fdbserver/worker.actor.cpp
> Nit fixing

- fdbserver/Status.actor.cpp
- flow/Error.cpp
- flow/Trace.cpp
- flow/include/flow/Error.h
This is a cherry-pick of #10498 
> [release-7.3] Report missing attributes when constructing status

- fdbclient/NativeAPI.actor.cpp
Update the getExactRange function to not retry the get key location query until after it has checked whether the results have satisfied the min rows and can return early.
This fixes an assert in the GetMappedRange that depends on the range read returning once it has at least one result.
Passed 100K correctness: 20230621-171545-abeamon-f57f9dc33c7ccedb
> Fix check in getExactRange that determines whether we can return early (snowflake/release-71.3)

- fdbclient/BlobCipher.cpp
* EaR: Add test case to validate decryption with invalid key
Description
Extend BlobCipher unit test to provide coverage for the scenario where buffer got encrypted with a EncryptionKey K, however, decryption for some reason got attempted with K'.
Testing
EncryptionUnit.toml - 100K
* EaR: Add test case to validate decryption with invalid key
Description
Address review comments
Testing
(cherry picked from commit 31aa06cfbc1748f7ca92b185e21984cf7598969e)
> EaR: Add test case to validate decryption with invalid key (#10394)

- fdbserver/Coordination.actor.cpp
Cherry pick of #10548 to `snowflake/release-71.3`.
An inconsistent coordinator disk queue could cause repeated reboots of the coordinator process. In simulation, this could cause stuck runs if another role was running on the coordinator process, as the other role would also repeatedly reboot (specifically stateful roles like tlogs).
See the comment included in this commit for much more detail.
> Fix issue with inconsistent coordinator disk queue (snowflake/release-71.3)

- fdbserver/Coordination.actor.cpp
An inconsistent coordinator disk queue could cause repeated reboots of the coordinator process. In simulation, this could cause stuck runs if another role was running on the coordinator process, as the other role would also repeatedly reboot (specifically stateful roles like tlogs).
See the comment included in this commit for much more detail.
> Fix issue with inconsistent coordinator disk queue

- fdbclient/BackupAgentBase.actor.cpp
This PR addressed a rare race condition when apply mutation logs for restore. It causes data loss during restore.
The race happens in the following scenario:
1) Mutation 1 inserts a new tenant to tenant map
2) Mutation 2 is a transaction for this tenant
With previous logic, we don't wait for mutation 1 completed before processing mutation 2, so mutation 2 is skipped since the new tenant is not in tenant map yet.
The fix is to wait for mutation 1 applied before processing mutation 2.
100K BlobRestore correctness passed. …
> Fix tenant map update race when applying mutations

- fdbclient/BackupAgentBase.actor.cpp
Cherry-Pick of #10557
100K correctness passed 20230627-172933-huliu-ba898fe4a0c7942f
This PR addressed a rare race condition when apply mutation logs for restore. It causes data loss during restore.
The race happens in the following scenario:
Mutation 1 inserts a new tenant to tenant map
Mutation 2 is a transaction for this tenant
With previous logic, we don't wait for mutation 1 completed before processing mutation 2, so mutation 2 is skipped since the new tenant is not in tenant map yet.
The fix is to wait for mutation 1 applied before processing mutation 2.
100K BlobRestore correctness passed.
Please check each of the following things …
> Fix tenant map update race when applying mutations (Cherry-Pick #10557 to snowflake/release-71.3)

- contrib/joshua_logtool.py
e.g., 20230627-102446-nightly-release-7.3-clang-45609535-729-20a8c
> Fix joshua_logtool.py to allow . in ensemble ID

- contrib/joshua_logtool.py
cherrypick #10568
e.g., 20230627-102446-nightly-release-7.3-clang-45609535-729-20a8c
> Fix joshua_logtool.py to allow . in ensemble ID [release-7.3]

- fdbclient/MultiVersionTransaction.actor.cpp
Throw error in tenantUpdater if result is an error
> Fix bug in FDB MultiVersionTransaction.actor.cpp 

- fdbclient/ServerKnobs.cpp
- fdbclient/include/fdbclient/ServerKnobs.h
- fdbserver/DDRelocationQueue.actor.cpp
- fdbserver/DDTeamCollection.actor.cpp
- fdbserver/include/fdbserver/DataDistributionTeam.h
> [Release 7.3] Add an option to limit the number of shard per team

- fdbcli/DebugCommands.actor.cpp
- fdbcli/fdbcli.actor.cpp
- fdbcli/include/fdbcli/fdbcli.actor.h
- fdbclient/include/fdbclient/NativeAPI.actor.h
- fdbserver/CommitProxyServer.actor.cpp
> Add getlocation and getall fdbcli debug commands [release-7.3]

- contrib/local_cluster/local_cluster.py
> fixup! Set up fdbcli path when running a local cluster

- fdbrpc/HTTPServer.actor.cpp
- fdbrpc/include/fdbrpc/HTTP.h
- fdbrpc/include/fdbrpc/simulator.h
- fdbrpc/sim2.actor.cpp
- fdbserver/SimulatedCluster.actor.cpp
> Stable http ports

- fdbcli/AuditStorageCommand.actor.cpp
- fdbcli/GetAuditStatusCommand.actor.cpp
- fdbclient/AuditUtils.actor.cpp
- fdbclient/ServerKnobs.cpp
- fdbclient/include/fdbclient/AuditUtils.actor.h
- fdbserver/DataDistribution.actor.cpp
- fdbserver/storageserver.actor.cpp
- fdbserver/workloads/ValidateStorage.actor.cpp
Correctness test with 4 irrelevant failures:
20230719-165003-zhewang-17a91cd805e8aaec           compressed=True data_size=33393671 duration=5588121 ended=100000 fail=4 fail_fast=10 max_runs=100000 pass=99996 priority=100 remaining=0 runtime=1:18:10 sanity=False started=100000 stopped=20230719-180813 submitted=20230719-165003 timeout=5400 username=zhewang
AuditStorage test:
20230719-165032-zhewang-23231dcee1ca3cd0           compressed=True data_size=33427163 duration=7784843 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:21:03 sanity=False started=100000 stopped=20230719-181135 submitted=20230719-165032 timeout=5400 username=zhewang …
> [Release-7.3] Cherry-pick new implementation of auditing replica and complete check of location metadata

- fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
> [release-7.3] Log counters.

- fdbbackup/FileDecoder.actor.cpp
- fdbclient/BackupAgentBase.actor.cpp
- fdbclient/StorageServerInterface.cpp
- fdbserver/storageserver.actor.cpp
- flow/Arena.h
Added backup key mutation logs
> Added backup key mutation logs

- fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
> Add logs for write stalls.

- fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
> Log counters.

- fdbserver/storageserver.actor.cpp
> Fix bytesPerCommit histogram.

- fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
> [release-7.3] Add logs for write stalls.

- fdbclient/ServerKnobs.cpp
> Set some rocksdb knobs to reduce simulation runtime. 

- fdbserver/storageserver.actor.cpp
> [release-7.3] Fix bytesPerCommit histogram.

- fdbclient/ServerKnobs.cpp
> [release-7.3] Set some rocksdb knobs to reduce simulation runtime. 

- fdbserver/CommitProxyServer.actor.cpp
Mutation is like `param1: \xff\x02/dlog/\xb1\x023,U\x8c9\x0c\xa6\xd69\x1e_;B\x1d\x8b\x00\x00\x00\x00\x1d\xdd\xa1\xfa\x00\x00\x00\x00 param2: \xfa\xa1\xdd\x1d\x00\x00\x00\x000:0 0:1 1:0 1:1"`
> Add tags in the value for original mutations [release-7.1]

- fdbserver/storageserver.actor.cpp
> Added logs for backup keyrange data moves.

- fdbserver/KeyValueStoreRocksDB.actor.cpp
Storing the inprocess-commit deleted keysets until the commit is complete
> Storing the inprocess-commit deleted keysets until the commit is complete

- fdbclient/ServerKnobs.cpp
- fdbclient/include/fdbclient/ServerKnobs.h
- fdbserver/include/fdbserver/StorageMetrics.actor.h
> fix read ops sample name typo

- fdbcli/DebugCommands.actor.cpp
- fdbcli/fdbcli.actor.cpp
- fdbcli/fdbcli.actor.h
> Add "checkall" for checking \xff\x02/blog/ keys [release-7.1]

- fdbserver/DDShardTracker.actor.cpp
This is how it happened. Inside of _DataDistributionTrackerImpl::run_, one actor calls the send on the reply of a Promise and it then directly jumps to the followup callbacks which waits on the message. Then follows a long call stack, one function throws an error which cancels the _DataDistributionTracker::run_, and then the `std::vector<Future<Void>> actors` ([code](https://github.com/apple/foundationdb/blob/main/fdbserver/DataDistribution.actor.cpp#L1036)) gets cancelled when code jumps to the catch block. And then when the call stack went back to _DataDistributionTrackerImpl::run_, the _DataDistributionTracker_ has been destroyed in the previous cancel.
Passed 100K Snap restarting tests and 100K correctness tests. …
> Cherry-pick a fix for segfault happens on DDShardTracker where the tracker gets destroyed before ::run finished

- documentation/sphinx/source/release-notes/release-notes-710.rst
> Add 7.1.34, 7.1.35 release notes

- documentation/sphinx/source/release-notes/release-notes-710.rst
> Add 7.1.34, 7.1.35 release notes [release-7.1]

- documentation/sphinx/source/release-notes/release-notes-7131.rst
Description
Release notes - snowflake/71.3.1a
Testing
> Release notes - snowflake/71.3.1

- documentation/sphinx/source/release-notes/release-notes-7130.rst
Description
Release notes for snowflake/release-71.3
Testing
> Release notes - snowflake/release-71.3

- fdbserver/workloads/DataLossRecovery.actor.cpp
The hanging was caused by a bad storage server endpoint being used as a destination for moving keys to, causing the finishMoveKeys routine to infinite looping. Further debugging reveals that this was attributed to how this test workload was constructed as DD was disabled when the storage server endpoints are selected. The fix here is to add a RPC call to verify that the storage server is alive before selecting one.
Credits to @sfc-gh-etschannen and @sfc-gh-xwang for lots of helpful discussions and guidances.
Ensemble with 100K runs for the targeted test: `20230724-194900-xcheng-3b344ab7da834c28`: had 2 failures that are unrelated to this change. 
In the first failure case (`devRetryCorrectnessTest bin/fdbserver -r simulation -f tests/fast/DataLossRecovery.toml -s 913104481 -b on --crash …
> FDBCORE-5124 Fix the DataLossRecovery workload stuck issue detected in correctness test

- CMakeLists.txt
Bump snowflake/release-71.3 branch release version to 71.3.2 for the next patch release
> Bump snowflake/release-71.3 branch release version to 71.3.2

- documentation/sphinx/source/release-notes/release-notes-710.rst
cherrypick https://github.com/apple/foundationdb/pull/10695
> Add 7.1.34, 7.1.35 release notes [release-7.3]

- CMakeLists.txt
> Bump version from 71_3_2 to 71_3_3

- documentation/sphinx/source/release-notes/release-notes-7132.rst
Description
Release notes snowflake/71.3.2
Testing
> Release notes snowflake/71.3.2

- documentation/sphinx/source/release-notes/release-notes-7132.rst
Description
Release notes for snowflake/release-71.3.2
Testing
> Release notes for snowflake/release-71.3.2

- bindings/go/src/fdb/tuple/tuple_test.go
Recently we updated the default go version in the builder image to go 1.20.6. In go 1.20 there was a change that the random generator from the math package will automatically be seeded: https://pkg.go.dev/math/rand@go1.20.7#Seed. This breaks the current go tuple tests for numerics, as those tests make use of the random generator.
In general I'm not sure how useful the random number generator is for those tests, given that we compare against a static set of values and there a specific seed is required. …
> Fix the go tuple tests for new go version

- documentation/sphinx/source/release-notes/release-notes-7132.rst
Description
Fix 71.3.2 notes earlier notes section linkage
Testing
> Fix 71.3.2 notes earlier notes section linkage

- bindings/go/src/fdb/tuple/tuple_test.go
cherry-pick #10736 to release-7.2
> cherry-pick #10736 to release-7.2

- fdbclient/ServerKnobs.cpp
- fdbserver/storageserver.actor.cpp
- tests/slow/ApiCorrectness.toml
> Allow applyUpdates in multiple batches.

- fdbserver/SimulatedCluster.actor.cpp
> Fix a crash error

- documentation/sphinx/source/release-notes/release-notes-730.rst
> Add a release note for 7.3.0

- fdbclient/ServerKnobs.cpp
- fdbserver/TenantCache.actor.cpp
Cherry-pick https://github.com/apple/foundationdb/pull/10759.
> [snowflake/release-71.3] Stagger storage quota estimation requests and observability improvements

- CMakeLists.txt
> Bump version from 71.3.3 to 71.3.4

- fdbrpc/sim2.actor.cpp
- fdbrpc/simulator.h
- fdbserver/workloads/ClogTlog.actor.cpp
> [Release 7.1] Simulate connection failure between specific pairs of machines

- tests/fast/AtomicBackupToDBCorrectness.toml
- tests/fast/MemoryLifetime.toml
- tests/fast/StreamingRangeRead.toml
- tests/fast/Watches.toml
- tests/rare/TransactionTagApiCorrectness.toml
- tests/restarting/from_7.3.0/DrUpgradeRestart-1.toml
- tests/slow/ParallelRestoreOldBackupCorrectnessAtomicOp.toml
> Disabled ShardedRocks for some sim tests due to timeout issue.

- documentation/sphinx/source/release-notes/release-notes-710.rst
> Release notes for 7.1.36/37.

- fdbclient/S3BlobStore.actor.cpp
> Avoid to send request to empty resource [release-7.1]

- fdbserver/DDTeamCollection.actor.cpp
- fdbserver/workloads/DcLag.actor.cpp
> Fix a few typos

- fdbclient/ClientKnobs.cpp
- fdbclient/ClientKnobs.h
- fdbclient/S3BlobStore.actor.cpp
- fdbrpc/HTTP.actor.cpp
> Fix compatibility issue of s3 backup [release-7.1]

- fdbclient/S3BlobStore.actor.cpp
> Avoid to send request to empty resource [release-7.3]

- documentation/sphinx/source/release-notes/release-notes-710.rst
> Release notes for 7.1.36/7.1.37.

- cmake/awssdk.cmake
So the cmake process can be done
> Backport main:awssdk.cmake to release-7.1

- documentation/sphinx/source/api-c.rst
Update the C API documentation to match the changes in the client packages and document what files are installed and where.
> Update C documentation of installed files and locations

- documentation/sphinx/source/release-notes/release-notes-7134.rst
Description
Release notes - snowflake 71.3.4
Testing
> Release notes - snowflake 71.3.4

- fdbserver/DDTeamCollection.actor.cpp
> Add perpetual wiggle pause reason.

- flow/Knobs.cpp
- flow/Knobs.h
- flow/network.cpp
- flow/network.h
> Add a knob RESOLVE_PREFER_IPV4_ADDR to prefer IPv4 addresses [release-7.1]

- fdbserver/BlobManifest.actor.cpp
Need to wait container->deleteFile() to be completed before proceeding. It's a missing cherry-pick from main
100K correctness test passed. 20230817-202759-huliu-a1c814164369f5ee
100K blobrestore test passed. 20230817-195321-huliu-fd962e2aa1a6bab0
> Wait file deleted in blob manifest cleanup

- CMakeLists.txt
Description
Bump version to 71.3.5
Testing
> Bump version to 71.3.5

- fdbserver/DataDistribution.actor.cpp
> fixup! Add back missing initializer

- tests/fast/AtomicBackupToDBCorrectness.toml
- tests/fast/MemoryLifetime.toml
- tests/fast/StreamingRangeRead.toml
- tests/fast/Watches.toml
- tests/rare/CheckRelocation.toml
- tests/rare/LargeApiCorrectness.toml
- tests/rare/LargeApiCorrectnessStatus.toml
- tests/rare/TransactionTagApiCorrectness.toml
- tests/rare/TransactionTagSwizzledApiCorrectness.toml
- tests/restarting/from_7.3.0/DrUpgradeRestart-1.toml
- tests/slow/ApiCorrectnessAtomicRestore.toml
- tests/slow/DDBalanceAndRemove.toml
- tests/slow/ParallelRestoreOldBackupCorrectnessAtomicOp.toml
- tests/slow/SharedDefaultBackupCorrectness.toml
- tests/slow/SwizzledDdBalance.toml
- tests/slow/ddbalance.toml
> [release-7.3] Cherrypick simulation fixes. 

- fdbserver/SimulatedCluster.actor.cpp
- fdbserver/fdbserver.actor.cpp
- fdbserver/include/fdbserver/SimulatedCluster.h
- tests/fast/PhysicalShardMove.toml
> Fix the storage engine for PhysicalShardMove

- design/dynamic-knobs.md
- documentation/sphinx/source/command-line-interface.rst
- fdbcli/fdbcli.actor.cpp
- fdbcli/tests/fdbcli_tests.py
The `clearknob` command clears the value that a knob has been set to in the configuration database. Note that this does not mean the knob value itself gets cleared - only the value in the configuration database is cleared. The value of the knob will revert to whatever is hardcoded in the corresponding `*Knobs.cpp` file.
Sample `fdbcli` session:
```
Welcome to the fdbcli. For help, type `help'.
fdb> getknob min_trace_severity
`min_trace_severity' is not found
fdb> setknob min_trace_severity 20
Please set a description for the change. Description must be non-empty
description: test
Committed (2)
fdb> getknob min_trace_severity
`min_trace_severity' is `20'
fdb> clearknob min_trace_severity
Please set a description for the change. Description must be non-empty
description: clear
Committed (4) …
```
> Add `clearknob` fdbcli command

- fdbserver/Status.actor.cpp
Cherry pick of #10859 to `snowflake/release-71.3`.
> Avoid creating a DatabaseContext on every status json call (snowflake/release-71.3)

- CMakeLists.txt
Description
Bump snowflake/release-71.3 from 71.3.5 -> 71.3.6
Testing
> Bump version to 71.3.6 for snowflake/release-71.3

- fdbclient/FileBackupAgent.actor.cpp
we need to initialize apply mutation map for non hybrid restore case. Otherwise incremental fdbrestore always starts from version 0.
> Initialize apply mutations map for restore to version

- documentation/sphinx/source/mr-status-json-schemas.rst.inc
> Fix status json schemas perpetual_storage_wiggle_engine

- fdbserver/DDTeamCollection.actor.cpp
Locality check on perpetualStorageWiggleIDPrefix when DD restarts
> Locality check on perpetualStorageWiggleIDPrefix when DD restarts

- fdbcli/ConfigureCommand.actor.cpp
- fdbclient/include/fdbclient/GenericManagementAPI.actor.h
> Make sure that storage and tlog are always set to a valid type

- documentation/sphinx/source/release-notes/release-notes-710.rst
Release notes for 7.1.38/7.1.39
> Release notes for 7.1.38/7.1.39

- documentation/sphinx/source/release-notes/release-notes-730.rst
> Release notes for 7.3.17.

- fdbbackup/backup.actor.cpp
- fdbclient/FileBackupAgent.actor.cpp
- fdbclient/include/fdbclient/BackupAgent.actor.h
backport https://github.com/apple/foundationdb/pull/10885
> Add proxy to backup agent via global var(release-7.3)

- tests/fast/GetEstimatedRangeSize.toml
- tests/fast/MutationLogReaderCorrectness.toml
- tests/rare/ClogTlog.toml
- tests/rare/TransactionCost.toml
- tests/rare/WriteTagThrottling.toml
- tests/restarting/from_7.3.0/UpgradeAndBackupRestore-1.toml
- tests/slow/DDBalanceAndRemoveStatus.toml
- tests/slow/SharedBackupCorrectness.toml
- tests/slow/SwizzledApiCorrectness.toml
cherrypick #10897, #10888 and #10894
> Disable sharded rocks for more sim tests and fix another sim test [release-7.3]

- fdbclient/ServerKnobs.cpp
> Disable read aware DD.

- fdbclient/ServerKnobs.cpp
> [release-7.3] Disable read aware DD.

- fdbserver/DDTeamCollection.actor.cpp
Erase storageWiggleID from disk if not used
cherry-pick of #10912
> Erase storageWiggleID from disk if not used

- documentation/sphinx/source/release-notes/release-notes-710.rst
> Add 7.1.40, 7.1.41 release notes

- fdbbackup/backup.actor.cpp
- fdbclient/BackupContainer.actor.cpp
- fdbclient/BackupContainerFileSystem.actor.cpp
- fdbclient/S3BlobStore.actor.cpp
PR https://github.com/apple/foundationdb/pull/10903 for release 7.3.
> Correct proxy handling backup agent 7.3

- documentation/sphinx/source/release-notes/release-notes-7131.rst
- documentation/sphinx/source/release-notes/release-notes-7132.rst
- documentation/sphinx/source/release-notes/release-notes-7134.rst
- documentation/sphinx/source/release-notes/release-notes-7135.rst
- documentation/sphinx/source/release-notes/release-notes-720.rst
Description
Release notes for snowflake/release-71.3.5
Testing
> Release notes for snowflake/release-71.3.5

- fdbbackup/backup.actor.cpp
- fdbclient/BackupContainer.actor.cpp
- fdbclient/BackupContainerFileSystem.actor.cpp
- fdbclient/S3BlobStore.actor.cpp
PR https://github.com/apple/foundationdb/pull/10903 for main.
> Correct proxy handling backup agent main

- documentation/sphinx/source/release-notes/release-notes-710.rst
cherrypick #10918 
Documentation changes only
> Add 7.1.40, 7.1.41 release notes [release-7.1]

- documentation/sphinx/source/release-notes/release-notes-7135.rst
- documentation/sphinx/source/release-notes/release-notes-7136.rst
Description
Release notes - snowflake/release-71.3.6
Testing
> Release notes - snowflake/release-71.3.6

- contrib/Implib.so/implib-gen.py
- fdbserver/DDTeamCollection.actor.cpp
- fdbserver/GrvProxyServer.actor.cpp
- fdbserver/IPager.cpp
- fdbserver/MoveKeys.actor.cpp
- fdbserver/Status.actor.cpp
Cherrypick
20230921-195400-jzhou-8c3a083731e96687
> cherrypick multiple fixes [release-7.3]

- fdbclient/FDBTypes.cpp
- fdbclient/include/fdbclient/FDBTypes.h
- fdbserver/DDTeamCollection.actor.cpp
- fdbserver/workloads/ConfigureDatabase.actor.cpp
- fdbserver/workloads/ConsistencyCheck.actor.cpp
- tests/SpecificUnitTest.txt
> [Release 7.3] Make perpetual_storage_wiggle_locality database option to take a list of localities

- contrib/CMakeLists.txt
- documentation/sphinx/source/release-notes/release-notes-730.rst
- flow/ThreadPrimitives.cpp
- flow/include/flow/ThreadPrimitives.h
> Implement Event using std::latch (#10705) and 7.3.16-19 release notes[release-7.3]

- fdbserver/QuietDatabase.actor.cpp
- tests/slow/ExcludeIncludeStorageServers.toml
Found in release correctness tests
> Fix two test failures

- fdbclient/DatabaseConfiguration.cpp
- fdbclient/include/fdbclient/DatabaseConfiguration.h
- fdbserver/ClusterController.actor.cpp
- fdbserver/Status.actor.cpp
- fdbserver/include/fdbserver/ClusterController.actor.h
- fdbserver/include/fdbserver/ExclusionTracker.actor.h
- fdbserver/workloads/ConsistencyCheck.actor.cpp
- fdbserver/workloads/RemoveServersSafely.actor.cpp
> Cherry-pick #10623 to release-7.3

- fdbclient/S3BlobStore.actor.cpp
Added an overflow test as well.
> Fix strtol return type and error checking

- fdbclient/S3BlobStore.actor.cpp
cherrypick #10950 #10763 #10960
> Fix an invalid memory access [release-7.3]

- fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
- tests/rare/ClogTlog.toml
- tests/rare/SwizzledLargeApiCorrectness.toml
- tests/slow/GcGenerations.toml
- tests/slow/ParallelRestoreNewBackupCorrectnessAtomicOp.toml
- tests/slow/VersionStampBackupToDB.toml
> Fix an unitialized variable and disable more sharded rocks sim tests [release-7.3]

- fdbclient/FDBTypes.cpp
- fdbclient/include/fdbclient/FDBTypes.h
> Fix perpetual wiggle locality match regex.

- fdbclient/FDBTypes.cpp
- fdbclient/include/fdbclient/FDBTypes.h
> [release-7.3] Fix perpetual wiggle locality match regex.

- documentation/sphinx/source/release-notes/release-notes-710.rst
> Add 7.1.42, 7.1.43 release notes

- fdbserver/storageserver.actor.cpp
100K correctness test with 3 irrelevant failures:
20231012-193315-zhewang-bc1cbeb0cb111538           compressed=True data_size=35923058 duration=6758841 ended=100000 fail=3 fail_fast=10 max_runs=100000 pass=99997 priority=100 remaining=0 runtime=1:21:49 sanity=False started=100000 stopped=20231012-205504 submitted=20231012-193315 timeout=5400 username=zhewang
100K ValidateStorage:
20231012-193408-zhewang-2f4e87ea5af3c177           compressed=True data_size=35953518 duration=10591484 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:34:01 sanity=False started=100000 stopped=20231012-210809 submitted=20231012-193408 timeout=5400 username=zhewang …
> Fix corner cases of auditStorageServerShardQ

- documentation/sphinx/source/release-notes/release-notes-710.rst
cherrypick https://github.com/apple/foundationdb/pull/10979
> Add 7.1.42, 7.1.43 release notes [release-7.3]

- fdbserver/storageserver.actor.cpp
Cherry-pick PR https://github.com/apple/foundationdb/pull/10980
100K correctness test with 1 irrelevant failure:
20231013-170208-zhewang-ea38023d766c0d6e           compressed=True data_size=34492390 duration=5938365 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:28:10 sanity=False started=100000 stopped=20231013-183018 submitted=20231013-170208 timeout=5400 username=zhewang
100K ValidateStorage test:
20231013-170314-zhewang-cf02ecaacbb87137           compressed=True data_size=34524842 duration=10615388 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:31:57 sanity=False started=100000 stopped=20231013-183511 submitted=20231013-170314 timeout=5400 username=zhewang
The general pull request guidelines can …
> [Release-7.3] Cherry-pick fix corner cases of auditStorageServerShardQ

- documentation/sphinx/source/release-notes/release-notes-730.rst
> Release notes for 7.3.25

- fdbserver/Status.actor.cpp
Backport of: https://github.com/apple/foundationdb/pull/10997
> [release-7.3] Correct the check for a machine being excluded

- fdbserver/Status.actor.cpp
Backport of: https://github.com/apple/foundationdb/pull/10997
> [release-7.1] Correct the check for a machine being excluded

- cmake/ConfigureCompiler.cmake
- fdbmonitor/fdbmonitor.cpp
- fdbserver/tester.actor.cpp
- fdbserver/workloads/DcLag.actor.cpp
- fdbserver/workloads/GcGenerations.actor.cpp
- metacluster/include/metacluster/MetaclusterConsistency.actor.h
fixes #10986
cherrypick #10518 and #11017
> Fix MacOS compiling errors [release-7.3]

- fdbclient/ManagementAPI.actor.cpp
- fdbserver/include/fdbserver/ExclusionTracker.actor.h
- fdbserver/workloads/RemoveServersSafely.actor.cpp
- tests/slow/MoveKeysSideband.toml
cherrypick https://github.com/apple/foundationdb/pull/11001
> Fix RemoveServersSafely workload timeout error [release-7.3]

- documentation/sphinx/source/release-notes/release-notes-710.rst
> Update 7.1.42 release notes

- documentation/sphinx/source/release-notes/release-notes-710.rst
cherrypick https://github.com/apple/foundationdb/pull/11030
> Update 7.1.42 release notes [release-7.3]

- fdbrpc/HTTP.actor.cpp
Same as: https://github.com/apple/foundationdb/pull/11039
> Fix nil pointer in proxy setup

- fdbserver/ConsistencyScan.actor.cpp
- fdbserver/workloads/ConsistencyCheck.actor.cpp
Cherry-pick PR https://github.com/apple/foundationdb/pull/11018
100K correctness test with 1 failure:
20231025-203029-zhewang-6592a2f81a617192           compressed=True data_size=34503125 duration=6860344 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:03:15 sanity=False started=100000 stopped=20231025-213344 submitted=20231025-203029 timeout=5400 username=zhewang
This is a data inconsistency failure with redwood engine in a restarting test.
Code is based on CommitID: 468dc1bbd28551e66cb7657c75d22d4dcd575ccb
```
../build_output/bin/fdbserver -r simulation -f ../src/foundationdb/tests/restarting/from_7.3.0/ConfigureTestRestart-1.toml --buggify on --seed 1855375089 --logsize 1024MiB
../build_output/bin/fdbserver -r simulation -f …
```
> [Release-7.3] Cherry-pick Improve visibility of consistency checker (#11018)

- fdbcli/ExcludeCommand.actor.cpp
- fdbclient/DatabaseConfiguration.cpp
- fdbclient/ManagementAPI.actor.cpp
- fdbclient/SpecialKeySpace.actor.cpp
- fdbclient/include/fdbclient/DatabaseConfiguration.h
- fdbclient/include/fdbclient/ManagementAPI.actor.h
- fdbrpc/Locality.cpp
- fdbrpc/include/fdbrpc/Locality.h
Backport: https://github.com/apple/foundationdb/pull/11009
> [release-7.3] Make sure server list is validated against the excluded localities

- fdbcli/ExcludeCommand.actor.cpp
Backport: https://github.com/apple/foundationdb/pull/11033
> [release-7.1] Allow the exclusions of localities that are not matching any process

- documentation/sphinx/source/release-notes/release-notes-730.rst
> Updates the release notes for 7.3.27 and 7.3.26

- documentation/sphinx/source/release-notes/release-notes-730.rst
> Cherry pick #11061 (add release notes for 7.3.26 and 7.3.27) to release-7.3

- fdbserver/Ratekeeper.actor.cpp
The ratekeeper checks the tps of all SS to determine if ingress should be limited. Its algorithm skips the zone with the SS with the lowest tps. The zone with the SS with the second slowest tps is selected to make the determination (`SERVER_KNOBS->MAX_MACHINES_FALLING_BEHIND` is 1). In production, we would like to know more about the SS in the "skipped" zone with the lowest tps. This PR adds some visibility by logging any RK limit "reasons" for SS in the "ignored" zones in the `RkUpdate*` messages.
Example: if zone DC1-Z-1 was ignored, containing some SS slowed for reason 1 and others for reason 2, we would log  `IgnoredZonesReasons="DC1-Z-1 [1 2 ] "`
Correctness test `20231116-145651-henrylambright-4c7d3e422fc6c4bb` …
> Log ignored zones and reasons in RkUpdate

- fdbserver/Ratekeeper.actor.cpp
Otherwise, the restored database is not consistent. A follow-up for #10970
To reproduce, at commit 45c459cfc of PR #11064:
-f ./tests/restarting/from_7.3.0/DrUpgradeRestart-1.toml -s 4210130489 -b off
-f ./tests/restarting/from_7.3.0/DrUpgradeRestart-2.toml --restarting -s 4210130490 -b on
20231117-221105-jzhou-3f8cd6c03a5ff8e4
> Disable hot shard throttling for restore

- packaging/docker/fdb.bash
- packaging/docker/fdb_single.bash
Add the knob to support running the image on an arm Mac: https://github.com/apple/foundationdb/issues/4111#issuecomment-1284040423 + https://forums.foundationdb.org/t/how-to-run-foundationdb-on-a-mac/3563 adding this knob should be harmless as those scripts are only intended for local testing.
> Improve the Docker setup for Mac

- fdbclient/ServerKnobs.cpp
- fdbclient/include/fdbclient/ServerKnobs.h
- fdbserver/storageserver.actor.cpp
> Throttle low-priority fetchKeys.

- fdbserver/DDTeamCollection.actor.cpp
> Logging improvement.

- fdbclient/SystemData.cpp
- fdbserver/workloads/IDDTxnProcessorApiCorrectness.actor.cpp
> Fixed unassigned data move reasons.

- fdbcli/DebugCommands.actor.cpp
- Address an issue that can cause "fdbcli checkall" to get into an infinite loop
- Address another overflow related issue.
Testing:
- Joshua job: 20231207-003704-sre-ffc5f9cd0a4fe98c (started).
> Address issues in code related to "fdbcli checkall" command

- fdbrpc/CoroTests.cpp
- flow/include/flow/CoroUtils.h
We found a bug in `Choose` which can cause memory errors if a Choose actor is getting cancelled. This PR fixes this and adds some additional tests
> Fix cancellation bug in Choose class

- fdbbackup/FileDecoder.actor.cpp
In the filter file, now we can use key ranges like "\x01\x05-\x01\x06" as the filter, in addition to prefix filters.
> Add key ranges as filters for fdbdecode

- bindings/go/src/fdb/fdb.go
This change attempts to address the SIGSEGV happening when network routine is started multiple times concurrently.
It changes the network mutex to be a RW mutex, to optimize the case of calls when network is already started.
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f4600000011 pc=0x7f46a405678e]
runtime stack:
runtime.throw({0x1169773?, 0x7f46a479f96c?})
/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7f465affb790 sp=0x7f465affb760 pc=0x44e45d
runtime.sigpanic()
/usr/local/go/src/runtime/signal_unix.go:821 +0x3e9 fp=0x7f465affb7f0 sp=0x7f465affb790 pc=0x466e49
goroutine 60 [syscall]:
runtime.cgocall(0xf4f640, 0xc0001f7f80)
/usr/local/go/src/runtime/cgocall.go:157 +0x6e fp=0xc0001f7f58 sp=0xc0001f7f20 pc=0x41840e …
> Go: simplify network start check logic

- fdbclient/ServerKnobs.cpp
- fdbclient/include/fdbclient/ServerKnobs.h
- fdbserver/DDRelocationQueue.actor.cpp
> Ignore CPU usage for team selection when read rebalance is disabled.

- fdbclient/ServerKnobs.cpp
- fdbclient/include/fdbclient/ServerKnobs.h
- fdbserver/DDRelocationQueue.actor.cpp
> [release-7.3] Ignore CPU usage for team selection when read rebalance is disabled. 

- fdbserver/KeyValueStoreRocksDB.actor.cpp
Removed latencySamples in kvstorerockddb to avoid DDSketch race access.
> Removed latencySamples in kvstorerockddb to avoid DDSketch race access.

- fdbclient/ServerKnobs.cpp
- fdbclient/SystemData.cpp
- fdbclient/include/fdbclient/ServerKnobs.h
- fdbclient/include/fdbclient/SystemData.h
- fdbserver/ApplyMetadataMutation.cpp
- fdbserver/storageserver.actor.cpp
Cherry pick PR #11107 - Add support to synthesize data in QA clusters
This includes the bug fix in PR #11115
> Cherry pick PR 11107 - Add support to synthesize data in QA clusters

- fdbserver/BlobManager.actor.cpp
- fdbserver/BlobManifest.actor.cpp
- fdbserver/BlobWorker.actor.cpp
> Fix tenant watching

- documentation/sphinx/source/release-notes/release-notes-7133.rst
Description
Release notes for snowflake/71.3.3
Testing
> Release notes 71.3.3

- fdbserver/Ratekeeper.actor.cpp
> Retry when Ratekeeper failed to get StorageQueueInfo.

- fdbserver/storageserver.actor.cpp
Ensure synthetic data is written to existing shards, for each mutation, using `rangeContaining`.
> ensure synthetic data is written to existing shards

- fdbserver/storageserver.actor.cpp
ensure synthetic data is written to existing shards.
> Cherry pick PR 11128 to 7.3 - ensure synthetic data is written to existing shards

- documentation/sphinx/source/mr-status-json-schemas.rst.inc
- fdbclient/Schemas.cpp
- fdbserver/DDTeamCollection.actor.cpp
- fdbserver/MoveKeys.actor.cpp
- fdbserver/Status.actor.cpp
- fdbserver/include/fdbserver/DDTeamCollection.h
- fdbserver/workloads/ConsistencyCheck.actor.cpp
Populate storage metadata for tss and a test to check it.
cherry-pick of #10073
> Populate storage metadata for tss and a test to check it.

- README.md
Hello FoundationDB team,
This PR contains a minor grammar suggestion for you to consider.
Best regards,
David
> A minor grammar and spelling suggestion

- fdbrpc/include/fdbrpc/AsyncFileWriteChecker.h
> Allow AsyncFileWriteChecker history.timestamp to have better precision

- flow/Platform.actor.cpp
- flow/SystemMonitor.cpp
Same as: https://github.com/apple/foundationdb/pull/11164
> Fix complie issue for ALLOC_INSTRUMENTATION

- flow/Platform.actor.cpp
- flow/SystemMonitor.cpp
Same as: https://github.com/apple/foundationdb/pull/11164
> [release-7.3] Fix compile issue for ALLOC_INSTRUMENTATION

- fdbclient/ServerKnobs.cpp
> Enable DD verbose tracing by default.

- fdbserver/KeyValueStoreRocksDB.actor.cpp
Removing the type check unit test
> Removing the type check unit test

- documentation/sphinx/source/release-notes/release-notes-710.rst
cherrypick #11184
Documentation only change.
> Add 7.1.44 to 7.1.55 release notes [release-7.1]

- documentation/sphinx/source/release-notes/release-notes-710.rst
> Add 7.1.44 to 7.1.55 release notes

- fdbclient/ServerKnobs.cpp
> Enable DD verbose tracking by default.

- documentation/sphinx/source/release-notes/release-notes-710.rst
cherrypick https://github.com/apple/foundationdb/pull/11184
> Add 7.1.44 to 7.1.55 release notes [release-7.3]

- flow/Knobs.cpp
- flow/Platform.actor.cpp
- flow/include/flow/Knobs.h
Changes from https://github.com/apple/foundationdb/pull/11191
> Abort process when abnormal shutdown is initiated to allow coredumps to be generated

- flow/Knobs.cpp
- flow/Platform.actor.cpp
- flow/include/flow/Knobs.h
Changes from https://github.com/apple/foundationdb/pull/11191
> [RELEASE-7.3] Abort process when abnormal shutdown is initiated to allow coredumps to be generated 

- fdbcli/DebugCommands.actor.cpp
Simply copy the implementation from 3cf894c30549531a8b3d189048e21ece07f2486f (release-7.1) to here.
> Checkall fixes (Cherrypicked from release-7.1)

- fdbcli/DebugCommands.actor.cpp
Cherrypick https://github.com/apple/foundationdb/pull/11204
> [Release-7.3] Cherrypick checkall command fixes

- fdbserver/DDTeamCollection.actor.cpp
> Don't treat SS as failed when ignoreSSFailure is set.

- contrib/transaction_profiling_analyzer/transaction_profiling_analyzer.py
> Parse version_stamp and print if necessary

- contrib/transaction_profiling_analyzer/transaction_profiling_analyzer.py
backport https://github.com/apple/foundationdb/pull/11231
> Parse version_stamp and print if necessary(release-7.3)

- fdbclient/ClientKnobs.cpp
- fdbclient/include/fdbclient/Atomic.h
- fdbclient/include/fdbclient/ClientKnobs.h
- fdbclient/include/fdbclient/CommitTransaction.h
- fdbserver/AccumulativeChecksumUtil.cpp
- fdbserver/ApplyMetadataMutation.cpp
- fdbserver/ClusterRecovery.actor.cpp
- fdbserver/CommitProxyServer.actor.cpp
- fdbserver/include/fdbserver/AccumulativeChecksumUtil.h
- fdbserver/include/fdbserver/ProxyCommitData.actor.h
- fdbserver/include/fdbserver/WorkerInterface.actor.h
- fdbserver/storageserver.actor.cpp
With cs and acs feature off:
20240307-233038-zhewang-1d4e52e3f6ba4eab           compressed=True data_size=36834943 duration=6368050 ended=100000 fail=3 fail_fast=10 max_runs=100000 pass=99997 priority=100 remaining=0 runtime=1:02:48 sanity=False started=100000 stopped=20240308-003326 submitted=20240307-233038 timeout=5400 username=zhewang
With cs feature on but acs off:
20240307-232931-zhewang-e8d5587b1228f329           compressed=True data_size=36834947 duration=7111258 ended=100000 fail=2 fail_fast=10 max_runs=100000 pass=99998 priority=100 remaining=0 runtime=1:30:16 sanity=False started=100000 stopped=20240308-005947 submitted=20240307-232931 timeout=5400 username=zhewang
With cs and acs feature on:
20240307-232628-zhewang-372316bd1995627d           compressed=True data_size=36834938 …
> Enable Accumulative Checksum in MutationRef

- fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
> Fix block cache usage reporting.

- documentation/sphinx/source/release-notes/release-notes-730.rst
> Fix documentation build that breaks CI [release-7.3]

- fdbkubernetesmonitor/.gitignore
- fdbkubernetesmonitor/copy.go
- fdbkubernetesmonitor/copy_test.go
- fdbkubernetesmonitor/go.mod
- fdbkubernetesmonitor/go.sum
- fdbkubernetesmonitor/main.go
- fdbkubernetesmonitor/monitor.go
- fdbkubernetesmonitor/suite_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/726
> Change the way how the fdb kubernetes monitor is copying files

- bindings/c/test/unit/third_party/CMakeLists.txt
- bindings/c/test/unit/unit_tests.cpp
- fdbserver/Status.actor.cpp
- tests/slow/ApiCorrectnessSwitchover.toml
- tests/slow/WriteDuringReadSwitchover.toml
cherrypick #11241
Updated doctest to resolve compiling issues.
> Fix a DR corruption bug [release-7.1]

- documentation/sphinx/source/release-notes/release-notes-710.rst
> Cherrypick release note from PR 11209

- fdbclient/include/fdbclient/RunRYWTransaction.actor.h
For easy debugging with `runRYWTransaction()` calls.
> Add runRYWTransactionDebug()

- documentation/sphinx/source/release-notes/release-notes-710.rst
> [Release-7.3] Cherrypick release note from PR 11209

- fdbrpc/AsyncFileWriteChecker.cpp
joshua:  20240401-231737-haofu-76fc1d29bbf963b0 
> Add destructor in LRU2 to release memory

- documentation/sphinx/source/mr-status.rst
The key has to be of byte type in Python, not str.
> fixup! Update the document of Machine-Readable Status

- documentation/sphinx/source/release-notes/release-notes-730.rst
> Add 7.3.32 - 7.3.37 release notes [release-7.3]

- documentation/sphinx/source/consistency-check-urgent.rst
- documentation/sphinx/source/technical-overview.rst
> Add consisteny check urgent doc

- documentation/sphinx/source/consistency-check-urgent.rst
- documentation/sphinx/source/technical-overview.rst
> [Release-7.3] Cherry-pick consisteny check urgent doc

- fdbserver/ClusterController.actor.cpp
Raise visibility of gray failure actions
> Raise visibility of gray failure actions

- fdbserver/CommitProxyServer.actor.cpp
> Increase CommitProxyTerminated severity for failed_to_progress errors.

- fdbkubernetesmonitor/README.md
> Correct the docker image name in fdb-kubernetes-monitor docs

- documentation/sphinx/source/mr-status-json-schemas.rst.inc
- fdbclient/Schemas.cpp
- fdbserver/KeyValueStoreRocksDB.actor.cpp
- fdbserver/Status.actor.cpp
Rocksdb metrics in status json.
> Rocksdb metrics in status json

- fdbserver/ClusterController.actor.cpp
Cherry pick #11309 Raise visibility of gray failure actions
> Cherry pick #11309 Raise visibility of gray failure actions

- fdbclient/ServerKnobs.cpp
- fdbclient/include/fdbclient/ServerKnobs.h
- fdbserver/DDTeamCollection.actor.cpp
> Don't remove team when total team count is within threshold.

- fdbserver/tester.actor.cpp
Cherry-pick https://github.com/apple/foundationdb/pull/11336
> [Release-7.3] Cherry-pick Fix assert false in consistency check urgent

- fdbserver/CommitProxyServer.actor.cpp
For better visibility.
cherrypick #11313
> Increase CommitProxyTerminated severity for failed_to_progress errors [release-7.3]

- fdbserver/CommitProxyServer.actor.cpp
For better visibility.
cherrypick #11313
> Increase CommitProxyTerminated severity for failed_to_progress errors. [release-7.1]

- .devcontainer/devcontainer.json
This is a proposal to fix #11307. I managed to build FDB in the main branch, but I'm not using the docker daily to develop on FDB. There might be missing elements to actually use it to develop FDB, feel free to test it and contribute to the branch.
> Ad devcontainer.json

- documentation/sphinx/source/experimental-features.rst
- documentation/sphinx/source/technical-overview.rst
> Add documentation about experimental features

- fdbserver/LogRouter.actor.cpp
Add logging to LogRouter's waitForVersion function
`20240503-184530-dlambrig-eecc5e058fe06521`
> Add logging to LogRouter's waitForVersion function

- fdbserver/LogRouter.actor.cpp
Cherry-pick Add logging to LogRouter's waitForVersion function (#11359)
* Add logging to waitForVersion
* Respond to review comments.
20240506-151749-dlambrig-2f7964edb6fc58eb
> Cherry-pick Add logging to LogRouter's waitForVersion function (#11359)

- bindings/go/src/fdb/generated.go
> fixup! Fix the ctest fialure at update_bindings_go_src_fdb_generated_go

- bindings/go/src/fdb/fdb_test.go
> [Release 7.1] Disable TestOpenNotExistTenant test

- bindings/go/src/fdb/fdb_test.go
> [Release-7.3] Disable fdb_test.go:TestOpenNotExistTenant

- fdbclient/ServerKnobs.cpp
> Adjust knob.

- fdbbackup/backup.actor.cpp
https://github.com/apple/foundationdb/pull/11392 for relase-7.1
> [RELEASE-7.1] Add default timeout fdbbackup

- documentation/sphinx/source/release-notes/release-notes-710.rst
> Add 7.1.58 to 7.1.61 release notes

- documentation/sphinx/source/release-notes/release-notes-710.rst
> Add 7.1.58 to 7.1.61 release notes [release-7.1]

- documentation/sphinx/source/release-notes/release-notes-710.rst
- documentation/sphinx/source/release-notes/release-notes-730.rst
> Added 7.3.38 to 7.3.43 release notes

- documentation/sphinx/source/release-notes/release-notes-710.rst
- documentation/sphinx/source/release-notes/release-notes-730.rst
> Added 7.3.38 to 7.3.43 release notes [release-7.3]

- tests/CMakeLists.txt
- tests/restarting/to_7.3.0_until_7.4.0/BlobGranuleRestartCorrectness-1.toml
- tests/restarting/to_7.3.0_until_7.4.0/BlobGranuleRestartCorrectness-2.toml
> Fix blob granule restarting test failures

- fdbclient/SystemData.cpp
- fdbserver/storageserver.actor.cpp
> Fix data move id decoding compatibility issue  in upgrading tests

- fdbserver/storageserver.actor.cpp
Also update a previous use of the "getting lower_bound from lastLessOrEqual" technique to use the same pattern.
~~Performance testing (using mako with a point clear workload, or something similar) pending local compilation finishing.~~ Mostly relying on the CI infrastructure for correctness testing.
Setup: mac m1 2020, single-process fdbserver using ssd storage engine. cpu usage hovered around 100%.
Summary: sets went from 17165 TPS to 17455 TPS, and clears went from 18292 TPS to 18941 TPS.
```
$ DYLD_LIBRARY_PATH=lib/ bin/mako --mode=run -xo1 --rows 1000000 -s 60 --async_xacts 400 > set.txt & DYLD_LIBRARY_PATH=lib/ bin/mako --mode=run -xc1 --rows 1000000 -s 60 --async_xacts 400 > clear.txt ;wait; cat set.txt clear.txt
[1] 85010
[1]  + done       DYLD_LIBRARY_PATH=lib/ bin/mako --mode=run …
```
> Remove two ptree searches when processing a clear

- design/metadata-version.md
This is to address Issue #3050 
> Add documentation for metadata version system key

- fdbcli/DebugCommands.actor.cpp
Improved checkall tool:
1. Logging locality information when printing inconsistency key information;
2. Logging reference server info and server set when comparing
> Improve checkall tool

- fdbkubernetesmonitor/main.go
Made some tests locally:
```bash
$ ./fdbkubernetesmonitor
{"level":"info","ts":1718374909.7578251,"msg":"should enable pprof","enable-pprof":false}
$ ENABLE_PPROF=true ./fdbkubernetesmonitor
{"level":"info","ts":1718374917.926634,"msg":"should enable pprof","enable-pprof":true}
$ ENABLE_PPROF=falsee ./fdbkubernetesmonitor
panic: strconv.ParseBool: parsing "falsee": invalid syntax
goroutine 1 [running]:
main.main()
/Users/jscheuermann/workspace/apple/foundationdb/fdbkubernetesmonitor/main.go:130 +0xd08
$ ENABLE_PPROF=false ./fdbkubernetesmonitor
{"level":"info","ts":1718374929.785943,"msg":"should enable pprof","enable-pprof":false}
$ ENABLE_PPROF="false" ./fdbkubernetesmonitor
{"level":"info","ts":1718374937.487411,"msg":"should enable pprof","enable-pprof":false}
$ ENABLE_PPROF="false" …
```
> Add a mechanism to allow to specifiy the command line flags over env variables

- fdbcli/DebugCommands.actor.cpp
> Cherry-pick Improve checkall tool (#11440)

- fdbcli/DebugCommands.actor.cpp
> [Release-7.3] Cherry-pick Improve checkall tool (#11440) (#11476)

- fdbkubernetesmonitor/kubernetes.go
- fdbkubernetesmonitor/monitor.go
Tests:
```bash
$ go test ./...
?       github.com/apple/foundationdb/fdbkubernetesmonitor/internal/certloader  [no test files]
ok      github.com/apple/foundationdb/fdbkubernetesmonitor      0.414s
ok      github.com/apple/foundationdb/fdbkubernetesmonitor/api  (cached)
```
> fdb-kubernetes-monitor: Ensure that the annotations are updated when the correct configuration is already loaded

- packaging/docker/samples/golang/app/Dockerfile
- packaging/docker/samples/golang/app/go.mod
This updates a sample app to go 1.22, which is the version used in most other contexts in our builds.
> Update the go version in a sample app.

- documentation/sphinx/source/consistency-check-urgent.rst
> Update DCC doc

- documentation/sphinx/source/release-notes/release-notes-730.rst
> Add release notes for 7.3.20 thru 7.3.23

- documentation/sphinx/source/release-notes/release-notes-730.rst
> Release notes for 7.3.20 thru 7.3.23 [release-7.3]

- fdbserver/workloads/ClientMetric.actor.cpp
> Fix an IDE build error

- fdbserver/workloads/ClientMetric.actor.cpp
I missed the later 2 commits from https://github.com/apple/foundationdb/pull/11466, in 
https://github.com/apple/foundationdb/pull/11506
now adde them in this PR
> Consolidate test code

- fdbrpc/FlowTransport.actor.cpp
- fdbrpc/sim2.actor.cpp
- fdbserver/CommitProxyServer.actor.cpp
- fdbserver/DataDistribution.actor.cpp
- fdbserver/LogRouter.actor.cpp
- fdbserver/LogSystemPeekCursor.actor.cpp
- fdbserver/OldTLogServer_4_6.actor.cpp
- fdbserver/OldTLogServer_6_0.actor.cpp
- fdbserver/OldTLogServer_6_2.actor.cpp
- fdbserver/TLogServer.actor.cpp
- fdbserver/include/fdbserver/ClusterController.actor.h
- fdbserver/storageserver.actor.cpp
- fdbserver/worker.actor.cpp
- flow/Net2.actor.cpp
> Add PeerAddress to all PeerAddr/Peer TraceEvent

- fdbclient/ServerKnobs.cpp
- fdbclient/include/fdbclient/ServerKnobs.h
- fdbserver/MoveKeys.actor.cpp
- fdbserver/storageserver.actor.cpp
- flow/include/flow/error_definitions.h
> Wait for TSS during finishMoveShards. 

- fdbclient/ServerKnobs.cpp
- fdbclient/include/fdbclient/ServerKnobs.h
- fdbserver/MoveKeys.actor.cpp
- fdbserver/storageserver.actor.cpp
- flow/include/flow/error_definitions.h
> [release-7.3] Wait for TSS during finishMoveShards.

- fdbserver/workloads/ClientMetric.actor.cpp
- tests/fast/ClientMetric.toml
backport https://github.com/apple/foundationdb/pull/11523
> lower the sample rate of client metric in simulation(release-7.1)

- fdbclient/include/fdbclient/CommitProxyInterface.h
- fdbserver/CommitProxyServer.actor.cpp
- fdbserver/TagPartitionedLogSystem.actor.cpp
- fdbserver/TestTLogServer.actor.cpp
- fdbserver/include/fdbserver/LogSystem.h
- fdbserver/include/fdbserver/TagPartitionedLogSystem.actor.h
Plus some minor fixes, e.g. override decorator/better readability
> When a commit is cancelled, record all unresponsive/failed TLogs

- design/tuple.md
* Added few line breaks (trailing two spaces). The second paragraph looks more readable now.
* Added more integer typecode examples for 2 and 4 bytes variations.
* Replaced curved “ and ” quotations with the right quote char in code snippets.
> Minor doc fixes in design/tuple.md

- fdbkubernetesmonitor/kubernetes.go
> Check the returned error from the setupCache method

- README.md
Enhance README.md for adding 'sh' to the code block.
> Enhance README.md for adding 'sh' to the code block.

- fdbserver/include/fdbserver/workloads/BulkSetup.actor.h
Cycle's setup phase calls setupRange() to insert data, which can timeout especially when knob MAX_WRITE_TRANSACTION_LIFE_VERSIONS is 1'000'000. This is because the transaction's read version can be more than 1e6 below the commit version, thus the transaction cannot commit due to transaction_too_old errors.
The fix is to skip the read so hopefully read version and commit version will not diff more than 1e6. Without the fix, this test fails roughly 10 out of 25k.
100k CacheTest passed: 20240727-171703-cachefix-f455241119323599
100k correctness: 20240727-180928-jzhou-8a8359cd5babbea0
2 unrelated failures:
```
-f ./tests/slow/CloggedStorefront.toml -s 323381148 -b on
-f ./tests/fast/BackupCorrectnessWithEKPKeyFetchFailures.toml -s 1722918551 -b on
```
The first one is a data movement stuck …
> Fix CacheTest timeout

- fdbserver/include/fdbserver/workloads/BulkSetup.actor.h
Since the transaction already declars a large write conflict range.
> Remove conflict range for set

- fdbserver/TestTLogServer.actor.cpp
- fdbserver/include/fdbserver/TestTLogServer.actor.h
simulate more than one tlog in unit tests
Joshua `20240731-211215-dlambrig-c813aa3b29a62cf6`
> simulate more than one tlog in unit tests

- packaging/docker/Dockerfile
- packaging/docker/entrypoint.bash
- packaging/docker/kubernetes/test_config.yaml
PR for https://github.com/apple/foundationdb/pull/11538
> [RELEASE-7.3] Change the default base image to RockyLinux9

- packaging/docker/Dockerfile
- packaging/docker/entrypoint.bash
- packaging/docker/kubernetes/test_config.yaml
PR for https://github.com/apple/foundationdb/pull/11538
> [RELEASE-7.1] Change the default base image to RockyLinux9

- fdbcli/ExcludeCommand.actor.cpp
When fdbcli user invokes the `exclude` command without any subcommands, now we also add additional information listing processes for which exclusion is in progress (e.g. because of exclude triggered data movement).
This has some overlap with https://github.com/apple/foundationdb/issues/5871 where now we have additional signal in the fdbcli that mentions in progress excludes. But it doesn't fully address that issue because the workflow there is kill triggered data movement, not exclude triggered data movement.
Did a test with this setup:
1. Started a local cluster via `foundationdb/tests/loopback_cluster/run_custom_cluster.sh <build_dir> --stateless_count 1 --logs_count 1 --storage_count 4 --replication_count 2`
2. Wrote a script to write around 300MB of logical data to this cluster with …
> [fdbcli] Add exclude in progress signal

- fdbcli/ExcludeCommand.actor.cpp
- fdbcli/Util.actor.cpp
- fdbserver/Status.actor.cpp
cherrypick https://github.com/apple/foundationdb/pull/11571 https://github.com/apple/foundationdb/pull/11573
> Add more trace events for exclude command and fix a cluster controller crash [release-7.3]

- documentation/sphinx/source/release-notes/release-notes-730.rst
> Add 7.3.44-7.3.49 release notes

- cmake/ConfigureCompiler.cmake
- cmake/FDBComponents.cmake
- cmake/Jemalloc.cmake
This is a cherry-pick of #11499 from release-7.3 -> main
> Add a new flag of USE_CUSTOM_JEMALLOC

- fdbclient/BackupAgentBase.actor.cpp
- fdbclient/BlobCipher.cpp
- fdbclient/BlobGranuleFiles.cpp
- fdbclient/FileBackupAgent.actor.cpp
- fdbserver/ApplyMetadataMutation.cpp
- fdbserver/BlobGranuleServerCommon.actor.cpp
- fdbserver/BlobGranuleValidation.actor.cpp
- fdbserver/BlobWorker.actor.cpp
- fdbserver/ClusterRecovery.actor.cpp
- fdbserver/CommitProxyServer.actor.cpp
- fdbserver/SimulatedCluster.actor.cpp
- fdbserver/tester.actor.cpp
- fdbserver/worker.actor.cpp
- fdbserver/workloads/BlobGranuleCorrectnessWorkload.actor.cpp
- fdbserver/workloads/BlobGranuleVerifier.actor.cpp
- flow/StreamCipher.cpp
In order to get higher SNR for test coverage, making some code probes rare. 
_Note: RFC for now to ensure all probes that I am updating to rare make sense._ 
Build passes. Joshua running (`20240827-001623-praza-ade5163a793abb22`).
---
> Make some codeprobes rare

- fdbserver/workloads/ClientMetric.actor.cpp
backport https://github.com/apple/foundationdb/pull/11606/
> Fix overflow(release-7.3)

- fdbserver/storageserver.actor.cpp
> Convert ASSERT to error logs.

- fdbserver/storageserver.actor.cpp
> [release-7.3] Convert ASSERT to error logs.

- fdbserver/MoveKeys.actor.cpp
Passed 500K correctness tests:
20240909-224854-zhewang-90e17c34e85cadcb           compressed=True data_size=35101529 duration=18632005 ended=500000 fail_fast=10 max_runs=500000 pass=500000 priority=100 remaining=0 runtime=3:18:07 sanity=False started=500000 stopped=20240910-020701 submitted=20240909-224854 timeout=5400 username=zhewang  
> [Release-7.3] Fix finishMoveShards partially update location metadata

- fdbserver/MoveKeys.actor.cpp
Cherry-pick: https://github.com/apple/foundationdb/pull/11640
20240910-030237-zhewang-4f3b515f27b6d0a7 
> Remove complete flag in moveShard related functions

- fdbclient/ServerKnobs.cpp
> Disable physical shard move in 7.3

- fdbserver/TLogServer.actor.cpp
Move "unknownCommittedVersions" to LogData data structure. This allows "unknownCommittedVersions" to be kept in sync with the containing LogData's "knownCommittedVersion", which is needed in order to find the correct recovery version in the presence of multiple recovery restarts.
Here is the issue with "unknownCommittedVersions" not being in "LogData" (found while investigating a failure in "tests/fast/Unreadable.toml" test):
- Let LD_a be the latest recruited log server (LogData) in a shared log server process
- Recovery starts and LD_a gets locked and sends its "unknownCommittedVersions" list to the cluster controller
- Recovery proceeds
- Another log server/LogData LD_b gets recruited and LD_b is now the latest LogData in the shared log server
- LD_b receives a commit and prunes …
> Transfer the ownership of "unknownCommittedVersions" to LogData data structure

- fdbserver/storageserver.actor.cpp
- tests/fast/DataLossRecovery.toml
> Remove storage engine type from DataLossRecovery test.

- fdbclient/FDBTypes.cpp
- fdbclient/ManagementAPI.actor.cpp
- fdbserver/SimulatedCluster.actor.cpp
- fdbserver/workloads/ConfigureDatabase.actor.cpp
Also remove mentioning of ssd-redwood-1-experimental.
20240912-194655-jzhou-616499f678e2401e
> Add rocksdb, sharded rocksdb to configure workload

- fdbserver/storageserver.actor.cpp
- tests/fast/DataLossRecovery.toml
> Cherry pick to 7.3 empty range fix

- fdbclient/ServerKnobs.cpp
- fdbclient/include/fdbclient/ServerKnobs.h
- fdbserver/DDRelocationQueue.actor.cpp
- fdbserver/DDTeamCollection.actor.cpp
- fdbserver/include/fdbserver/DataDistributionTeam.h
We want TeamRedundant and TeamUnhealthy data moves do not make the min SS available % worse quickly when massive those data moves have been triggered. Therefore, we decide to randomly choose to move data to the team with the minimal average bytes. 
Add two knobs:
1. PROBABILITY_TEAM_REDUNDANT_DATAMOVE_CHOOSE_TRUE_BEST_DEST
2. PROBABILITY_TEAM_UNHEALTHY_DATAMOVE_CHOOSE_TRUE_BEST_DEST
For the TeamRedundant data move, the implementation is equal to randomly select a TeamRedundant data move and generate a Rebalance data move on the same range to overwrite the data move.
For the TeamUnhealthy data move, the implementation is equal to randomly select a TeamUnhealthy data move and if this data move decides to move data out of a SS, DD generates a Rebalance data move on the same range to …
> [Release-7.3] TeamRedundant and TeamUnhealthy data moves choose best destination with probability

- fdbserver/workloads/DcLag.actor.cpp
> [fdbserver] Remove dead code in DcLag sim test

- fdbserver/LogRouter.cpp
This addresses https://github.com/apple/foundationdb/pull/11600/files#r1731945929. 
100K Joshua: `20240920-071448-praza-fd5171f8582bc61b`
> [logrouter] Convert actor based loops to native C++

- fdbclient/ServerKnobs.cpp
- fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
> Fix block cache size error and improve logging.

- fdbclient/ServerKnobs.cpp
- fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
> [release-7.3] Fix block cache size error and improve logging.

- documentation/sphinx/source/guide-common.rst.inc
- packaging/rpm/buildrpms.sh
- packaging/rpm/foundationdb.spec.in
> Remove rpm packaging related to el6

- fdbserver/include/fdbserver/TLogInterface.h
Cherry-pick PR https://github.com/apple/foundationdb/pull/11696.
Testing:
Joshua job: 20241001-215133-sre-eef1d9c30b5fc299 (no failures).
> Cherry-pick PR #11696 (Address a serialization issue that is blocking patch upgrade)

- README.md
> Add information about stable releases in README

- fdbclient/ServerKnobs.cpp
> [release-7.3] Adjust sharded rocksdb knobs.

- fdbclient/ServerKnobs.cpp
> Update sharded rocksdb knobs.

- documentation/sphinx/source/release-notes/release-notes-730.rst
Update "release-notes-730.rst" with 7.3.52 and 7.3.53 release notes.
> Add 7.3.52 and 7.3.53 release notes

- documentation/sphinx/source/release-notes/release-notes-730.rst
Cherry-pick PR https://github.com/apple/foundationdb/pull/11710.
> Cherry-pick PR #11710 (Add 7.3.52 and 7.3.53 release notes)

- fdbserver/storageserver.actor.cpp
> Ignore data move conflict on TSS in simulation.

- fdbserver/storageserver.actor.cpp
> Cherry-pick 7.3 #11714

- fdbmonitor/fdbmonitor.h
- fdbmonitor/fdbmonitor_tests.cpp
> Add missing headers

- fdbclient/include/fdbclient/ServerKnobs.h
Addresses https://github.com/apple/foundationdb/pull/11717#pullrequestreview-2381361425. 
> [gray_failure] Update CC_ONLY_CONSIDER_INTRA_DC_LATENCY knob documentation

- fdbserver/include/fdbserver/ProxyCommitData.actor.h
- fdbserver/workloads/ConflictRange.actor.cpp
- fdbserver/workloads/ReportConflictingKeys.actor.cpp
> Disable range lock injection in range conflict workload

- documentation/sphinx/source/release-notes/release-notes-730.rst
Update "release-notes-730.rst" with 7.3.54 and 7.3.55 release notes
> Add 7.3.54 and 7.3.55 release notes

- documentation/sphinx/source/release-notes/release-notes-730.rst
Cherry-pick PR https://github.com/apple/foundationdb/pull/11740.
> Cherry-pick PR #11740 (Add 7.3.54 and 7.3.55 release notes)

- fdbserver/CommitProxyServer.actor.cpp
- fdbserver/include/fdbserver/ProxyCommitData.actor.h
- fdbserver/workloads/RandomRangeLock.actor.cpp
20241031-174144-zhewang-574ee62c3fb8199e
> Turn off rangeLock if versionvector is on

- fdbserver/CommitProxyServer.actor.cpp
- fdbserver/include/fdbserver/ProxyCommitData.actor.h
100K correctness test
20241101-012504-zhewang-83dda0327ba07496           compressed=True data_size=36888716 duration=5298040 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=0:52:15 sanity=False started=100000 stopped=20241101-021719 submitted=20241101-012504 timeout=5400 username=zhewang
The correctness test has 1 corruption failure: AccumulativeCheckSumValidation Error but no rangeLock is running. Will investigate in a separate PR:
Event Severity="40" ErrorKind="Unset" Time="262.618873" DateTime="2024-11-01T02:48:37Z" Type="AcsValidatorCorruptionDetected" Machine="2.2.2.2:2" ID="0208c9e2b6ba352c" Reason="Mutation version changed when AddMutation" AcsTag="2:0" AcsIndex="11" MissingVersion="369477198" Mutation="checksum: 666531549 …
> Make range lock compatibility clear

- fdbserver/TagPartitionedLogSystem.actor.cpp
back-port of: https://github.com/apple/foundationdb/pull/11772
> [RELEASE-7.3] Add debug id trace event 7.3

- cmake/CompileBoost.cmake
Check if CI is updated correctly.
> Update boost to 1.86 from 1.78

- documentation/sphinx/source/release-notes/release-notes-730.rst
backport https://github.com/apple/foundationdb/pull/11795
> Add 7.3.56, 7.3.57 release notes(release-7.3)

- fdbserver/workloads/ClogRemoteTLog.actor.cpp
Context: https://github.com/apple/foundationdb/pull/11797#discussion_r1851701897. 
Ran simulation test manually, ensured it passed.  
> Address feedback in PR #11797

- fdbclient/include/fdbclient/Status.h
This specific error was introduced in https://github.com/apple/foundationdb/pull/11797 but I did not notice it because another ssh error was masking it. 
> Fix mac build

- fdbbackup/tests/backup_common.sh
- fdbbackup/tests/dir_backup_test.sh
- fdbbackup/tests/fdb_cluster_fixture.sh
- fdbbackup/tests/s3_backup_test.sh
- fdbclient/tests/s3cp_test.sh
- fdbclient/tests/seaweedfs_fixture.sh
Minor change.  'exit' exits the script which was ok here but 'return' is more correct.
> Use 'return' instead of 'exit' exiting functions.

- fdbbackup/backup.actor.cpp
- fdbrpc/include/fdbrpc/AsyncFileEncrypted.h
- flow/include/flow/IAsyncFile.h
Following https://github.com/apple/foundationdb/pull/6314, which made this change.
> Update documentation to reflect upgrading from AES-128 GCM to AES-256 GCM

- fdbclient/S3BlobStore.actor.cpp
- fdbserver/DDShardTracker.actor.cpp
Found by ASAN s3_backup_tests and correctness
> Fix heap-use-after-free bugs

- fdbserver/CommitProxyServer.actor.cpp
When version vector is enabled, make proxies advance min committed version only after receiving a commit version reply from the sequencer. Advancing the min committed version prior to that point may result in invalid DBRecoveryDurability errors (if a recovery happens after the advancement) in simulation tests.
Testing:
Joshua id: 20241206-005617-sre-2b47810578fa7e18 (started).
> DBRecoveryDurability errors with version vector

- fdbserver/RocksDBCheckpointUtils.actor.cpp
I found this issue because of debug build which exposed the race, although the issue itself is not caused by debug build and can happen in release build as well. The problem happens when running sharded rocks sim tests. It manifests as a rocksdb crash:
```
fdbserver: rocksdb/db/column_family.cc:1647: rocksdb::ColumnFamilySet::~ColumnFamilySet(): Assertion `last_ref' failed.
```
The root cause is related to `ROCKSDB_CHECKPOINT_READER_PARALLELISM` (default = 4) and a race condition / synchronization problem between these reader threads. Here's the sequence of events:
1. We create 4 threads in https://github.com/apple/foundationdb/blob/5a615df85ffb41b175686f1610d755b460174a93/fdbserver/RocksDBCheckpointUtils.actor.cpp#L421-L423.
2. Thread 1 calls …
> Fix race condition in rocksdb checkpoint readers

- cmake/ConfigureCompiler.cmake
- cmake/Findjemalloc.cmake
- fdbclient/include/fdbclient/RangeLock.h
- flow/include/flow/Arena.h
- flow/include/flow/CompressedInt.h
> Fix a few issues with gcc 13

- fdbclient/ServerKnobs.cpp
- fdbclient/include/fdbclient/ServerKnobs.h
- fdbserver/DDTeamCollection.actor.cpp
> Pause perpetual storage wiggle when TSS count target is met.

- fdbclient/ServerKnobs.cpp
- fdbclient/include/fdbclient/ServerKnobs.h
- fdbserver/DDTeamCollection.actor.cpp
> [release-7.3] Pause perpetual storage wiggle when TSS count target is met.

- fdbserver/storageserver.actor.cpp
gcc build randomly crashes because the StorageServer structure exceeded 16KB size, but is still FastAllocated. Thus, LatencySample can overwrite memory during initialization, causing random segfaults.
Added a static assertion to catch this problem for future modifications to the structure.
20241219-004417-jzhou-66463596fc290b64
> Fix storage server crashes

- fdbclient/S3BlobStore.actor.cpp
Variables before "wait()" are temporary ones that will be destructed in the actor compiled code. So adding "state" to keep them live while executing the "wait()" calls.
This is found by ASAN s3_backup_tests.
20241220-061010-jzhou-195720aba37b4bf2
> Fix stack use-after-return bugs in S3BlobStore.actor.cpp

- fdbcli/ExcludeCommand.actor.cpp
- fdbclient/SpecialKeySpace.actor.cpp
Back port of https://github.com/apple/foundationdb/pull/11838
> [RELEASE-7.3] Refactor locality-based exclusion checks to reduce additional overhead

- cmake/awssdk.cmake
Old version has compiling errors with gcc-13.
> Upgrade awssdk to 1.11.473

- cmake/CompileBoost.cmake
cherrypick #11858 
This problem affects our Valgrind and ASAN builds.
> Fix boost URL [release-7.3]

- fdbclient/include/fdbclient/BulkLoading.h
> Fix uninitialized value in BulkLoadManifest

- cmake/FDBComponents.cmake
> Fix ZLIB not found error [release-7.1]

- design/recovery-internals.md
The doc is outdated since FDB 7.1
> Update recovery doc with CC orchestrated process

- fdbcli/BulkDumpCommand.actor.cpp
- fdbcli/BulkLoadCommand.actor.cpp
- fdbcli/fdbcli.actor.cpp
- fdbcli/include/fdbcli/fdbcli.actor.h
- fdbclient/BulkDumping.cpp
- fdbclient/ManagementAPI.actor.cpp
- fdbclient/include/fdbclient/BulkDumping.h
- fdbclient/include/fdbclient/ManagementAPI.actor.h
> Bulkload FDBCLI Command

- fdbserver/MoveKeys.actor.cpp
20250117-223756-zhewang-3ec05c975296bad3           compressed=True data_size=37568475 fail_fast=10 max_runs=100000 priority=100 sanity=False submitted=20250117-223756 timeout=5400 username=zhewang
> Improve AuditLocationMetadataPostCheck coverage

- fdbserver/MoveKeys.actor.cpp
Cherrypick: https://github.com/apple/foundationdb/pull/11888
20250118-004524-zhewang-15d3e55c3d164d32           compressed=True data_size=35143916 duration=2887221 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:51:10 sanity=False started=100000 stopped=20250118-023634 submitted=20250118-004524 timeout=5400 username=zhewang
> [Release-7.3] Cherry-pick Improve AuditLocationMetadataPostCheck coverage (#11888)

- documentation/sphinx/source/release-notes/release-notes-730.rst
As title. 
Testing: Github viewer shows the rendered file. Ensured text is formatted properly and URLs work. 
> Release notes for 7.3.58 and 7.3.59

- documentation/sphinx/source/release-notes/release-notes-730.rst
Cherry-pick https://github.com/apple/foundationdb/pull/11902 to 7.3 branch.
> [release-7.3] Release notes for 7.3.58 and 7.3.59

- fdbserver/TagPartitionedLogSystem.actor.cpp
Do not do the replication policy validation check when trying to find the recovery version in the context of version vector. We will need to extend the version vector recovery algorithm to do this check in an efficient manner later.
Testing:
- Simulation test "tests/rare/WriteTagThrottling.toml" fails over an assertion in "getRecoverVersionUnicast()" without this change, and succeeds over this change.
- Joshua job (with version vector disabled): 20250117-123242-sre-9027cb0ee4ab6098 (no failures).
> Disable the replication policy validation check in version vector recovery algorithm

- packaging/docker/build-images.sh
See https://github.com/FoundationDB/fdb-kubernetes-tests/pull/859
> Push the fdb-kubernetes-monitor 'unified' image.

- fdbclient/ServerKnobs.cpp
- fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
> [release-7.3] Update shared rocksdb knobs. 

- fdbserver/BulkLoadUtil.actor.cpp
- fdbserver/DataDistribution.actor.cpp
- fdbserver/include/fdbserver/DataDistribution.actor.h
- fdbserver/workloads/MockDDTrackerShardEvaluator.actor.cpp
20250211-191749-zhewang-16a1aa67b9408f08           compressed=True data_size=36777381 fail_fast=10 max_runs=100000 priority=100 sanity=False submitted=20250211-191749 timeout=5400 username=zhewang
100K bulkLoad:
20250211-054943-zhewang-18a62af3cb5687b0           compressed=True data_size=36812719 duration=8107722 ended=100000 fail=2 fail_fast=10 max_runs=100000 pass=99998 priority=100 remaining=0 runtime=1:11:08 sanity=False started=100000 stopped=20250211-070051 submitted=20250211-054943 timeout=5400 username=zhewang
100K BulkDump:
20250211-172433-zhewang-4ae390e1fb80183a           compressed=True data_size=36812274 duration=13781200 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:39:48 sanity=False started=100000 …
> Refactor BulkLoad Engine and Improve Trace Events

- documentation/sphinx/source/release-notes/release-notes-730.rst
> Add 7.3.60, 7.3.61 release notes [release-7.3]

- documentation/sphinx/source/release-notes/release-notes-730.rst
> Add 7.3.60, 7.3.61 release notes

- fdbserver/storageserver.actor.cpp
> Update SS data move logs.

- fdbclient/CommitProxyInterface.cpp
- fdbclient/FileBackupAgent.actor.cpp
- fdbclient/include/fdbclient/CommitProxyInterface.h
- fdbserver/CommitProxyServer.actor.cpp
To reuse code.
correctness 20250210-222747-jzhou-d5e17deb43ca5a4f
20250123-170525-flowguru-036302765816ce02 
> Refactor backup mutation serialization

- fdbclient/ServerKnobs.cpp
- fdbserver/KeyValueStoreRocksDB.actor.cpp
- fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
- tests/noSim/PerfShardedRocksDBTest.toml
> Remove per thread histogram in storage engine and fix bugs in range scan.

- fdbcli/BulkDumpCommand.actor.cpp
- fdbcli/BulkLoadCommand.actor.cpp
- fdbclient/ManagementAPI.actor.cpp
- fdbclient/include/fdbclient/BulkLoading.h
- fdbclient/include/fdbclient/ManagementAPI.actor.h
- fdbserver/DataDistribution.actor.cpp
- fdbserver/workloads/BulkDumping.actor.cpp
- fdbserver/workloads/BulkLoading.actor.cpp
BulkLoad job metadata indicates which range is running a bulkload job. In a job, the job range is partitioned into smaller ranges and the job spawns bulkload tasks for each child range. The tasks are run by the bulkload task engine. BulkLoad task metadata indicates all details to do the bulkload on a range.
When a task runs into an unretrievable error, the job is marked as error. Otherwise, the job is marked as completed.
20250222-042411-zhewang-359e2b08e273d886           compressed=True data_size=40817907 duration=5439628 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:53:48 sanity=False started=100000 stopped=20250222-051759 submitted=20250222-042411 timeout=5400 username=zhewang
500K bulkload tests: …
> Simplify BulkLoad Job Metadata

- documentation/sphinx/source/release-notes/release-notes-730.rst
Release notes for 7.3.62 and 7.3.63
> Release notes for 7.3.62 and 7.3.63

- fdbserver/workloads/ExcludeIncludeStorageServersWorkload.actor.cpp
Excluding LR would trigger recovery because of: https://github.com/apple/foundationdb/blob/26f38c8970e2705e4f9ad60bf6092cd8f3db925c/fdbserver/include/fdbserver/ClusterController.actor.h#L2477-L2482
In this workload, it's expected that SS takes some time to catch up which means it takes some time before recovery can reach storage_recovered or fully_recovered. But if LR is excluded during this time, it won't let the recovery finish and trigger a new recovery. This eventually results in: https://github.com/apple/foundationdb/blob/1bd6f0aeabecf05025cd6b7f379d65aac0a5f314/fdbserver/ClusterRecovery.actor.cpp#L1553-L1558
This was found in nightly run:
- clang
- commit `a02f1078f0c7de2257bb9934d54a2e018b76fdf1`
- slow/ExcludeIncludeStorageServers.toml
- seed 3508461006
- buggify on
Ran …
> Do not pick SS with a colocated LR in ExcludeIncludeStorageServersWorkload

- documentation/sphinx/source/auditstorage.rst
- documentation/sphinx/source/technical-overview.rst
> AuditStorage Documentation

- fdbserver/KeyValueStoreRocksDB.actor.cpp
Adding rocksdb obsolete files size property in metrics.
And also back porting of #11981 and #11957 main branch changes.
Correctness run:
20250303-204102-neethuhaneeshabingi-5ce8118894804fe5 compressed=True data_size=55904693 duration=5647605 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:57:04 sanity=False started=100000 stopped=20250303-213806 submitted=20250303-204102 timeout=5400 username=neethuhaneeshabingi
> Adding rocksdb obsolete files size property in metrics.

- fdbclient/CMakeLists.txt
- fdbclient/S3BlobStore.actor.cpp
- fdbclient/S3Client.actor.cpp
- fdbclient/include/fdbclient/S3BlobStore.h
- fdbclient/tests/s3client_test.sh
Hash file before uploading. Add it as tag after successful multipart upload. On download, after the file is on disk, get its hash and compare to that of the tag we get from s3.
* fdbclient/include/fdbclient/S3BlobStore.h
* fdbclient/S3BlobStore.actor.cpp
Add putObjectTags and getObjectTags
* fdbclient/S3Client.actor.cpp
Clean up includes.
On file upload, before pushing, get hash
and add it as tag after upload.
On download, compare hash to s3 tag.
> Add checksumming across multipart upload and download

- fdbcli/BulkLoadCommand.actor.cpp
- fdbserver/DataDistribution.actor.cpp
> Add BulkLoad Task Count to BulkLoad FDBCLI Command

- fdbclient/ServerKnobs.cpp
- fdbserver/DDShardTracker.actor.cpp
- fdbserver/DataDistribution.actor.cpp
- fdbserver/MoveKeys.actor.cpp
- fdbserver/include/fdbserver/DataDistribution.actor.h
100K BulkDump:
20250315-033337-zhewang-ec8717478f157109           compressed=True data_size=41001166 duration=3189137 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=0:39:30 sanity=False started=100000 stopped=20250315-041307 submitted=20250315-033337 timeout=5400 username=zhewang
> Avoid Shard Merge When BulkLoad

- fdbclient/ClientKnobs.cpp
- fdbserver/storageserver.actor.cpp
This PR also improves trace events for audit storage.
20250319-182724-zhewang-675298b72f170180           compressed=True data_size=41055969 fail_fast=10 max_runs=100000 priority=100 sanity=False submitted=20250319-182724 timeout=5400 username=zhewang
> Disable Mutation Checksum and Accumulative Checksum By Default

- fdbserver/CommitProxyServer.actor.cpp
Disable version vector unicast with idempotent transactions, because it adds tags post resolution, which is incompatible with version vector unicast. There are two such cases to handle.
Case 1: an idempotent transaction has a valid "idempotencyId". This can be detected pre-resolution.
Case 2: an asynchronous actor queues old keys to be cleared. The queue is checked post resolution. Modify the code to check the queue at pre-resolution time, if any exist, disable unicast for this transaction. In post-resolution, only clear if unicast is disabled. …
> Disable version vector unicast with idempotent transactions

- fdbserver/KeyValueStoreShardedRocksDB.actor.cpp
> [release-7.3] Add metrics for number of shards updated within a period. 

- documentation/sphinx/source/release-notes/release-notes-740.rst
7.4 Release Notes. I filtered and reworded a lot so please review carefully. I still have some open questions, will tag relevant people in this PR.
This is against main branch. Once accepted and merged, will backport this PR to 7.4 branch. 
Github render if interested: https://github.com/apple/foundationdb/blob/42e8d3c3a5cf2153677517adaaad438c30182fb5/documentation/sphinx/source/release-notes/release-notes-740.rst. 
> 7.4 Release Notes

- documentation/sphinx/source/release-notes/release-notes-740.rst
Cherry-pick https://github.com/apple/foundationdb/pull/12059 to `release-7.4` branch. 
Confirmed that code compiles. Did not run joshua since this is a doc change, does not affect correctness.
> Backport 7.4 Release Notes

- bindings/python/CMakeLists.txt
Since we only need the generated sdist .tar.gz file to be uploaded by pypi (wheel files are not accepted anymore, see
https://packaging.python.org/en/latest/specifications/source-distribution-format/ ) for more details.
> fixup! Do not generate wheel file

- fdbcli/DebugCommands.actor.cpp
> Checkall Command with DCID

- fdbcli/BulkLoadCommand.actor.cpp
> Fix assertion failure in fdbcli

- fdbcli/DebugCommands.actor.cpp
Cherrypick https://github.com/apple/foundationdb/pull/12089
> Checkall Command with DCID (#12089)

- fdbclient/BackupAgentBase.actor.cpp
Cherry-pick: https://github.com/apple/foundationdb/pull/12088
20250422-182125-zhewang-edd0dd3a714f3a0a           compressed=True data_size=41103101 duration=5274183 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:09:41 sanity=False started=100000 stopped=20250422-193106 submitted=20250422-182125 timeout=5400 username=zhewang
> [Release-7.4] Cherry-pick Fix restore speed regression (#12088)

- fdbcli/DebugCommands.actor.cpp
Cherry pick: https://github.com/apple/foundationdb/pull/12089
> [Release-7.4] Cherry-pick Checkall Command with DCID (#12089) (#12099)

- fdbclient/BackupAgentBase.actor.cpp
Cherry-pick: https://github.com/apple/foundationdb/pull/12088
20250422-175454-zhewang-0e34efee787317b4           compressed=True data_size=41106806 duration=5115672 ended=100000 fail=1 fail_fast=10 max_runs=100000 pass=99999 priority=100 remaining=0 runtime=1:26:56 sanity=False started=100000 stopped=20250422-192150 submitted=20250422-175454 timeout=5400 username=zhewang
> Fix restore speed regression (#12088)

- packaging/docker/Dockerfile
> Update dockerfile golang version to 1.23

- fdbclient/S3Client_cli.actor.cpp
Sets the global fileBackupAgentProxy = param->proxy.get();
> Have s3client take a --proxy argument as backup_agent does.

- fdbkubernetesmonitor/go.mod
- packaging/docker/Dockerfile
Follow up of https://github.com/apple/foundationdb/pull/12105 with a more recent go version.
> Update the golang build container to 1.23.8

- documentation/sphinx/source/release-notes/release-notes-730.rst
> Add 7.3.63 to 7.3.67 release notes

- fdbserver/Status.actor.cpp
We log errors when storage metrics is not immediately available. CC should be able to get metrics later. Add logs to verify that. 
`20250428-203230-yaoxiao-74448623d4a07428           compressed=True data_size=49637042 duration=4204277 ended=100000 fail_fast=10 max_runs=100000 pass=100000 priority=100 remaining=0 runtime=1:06:51 sanity=False started=100000 stopped=20250428-213921 submitted=20250428-203230 timeout=5400 username=yaoxiao`
> [release-7.3] Log server info when StorageMetrics is not available

- fdbclient/BackupContainerFileSystem.actor.cpp
cherry-pick of #12102 
Backup unit test fix. The code did not handle the missing log file overlapping with the snapshots after the next one. Fixed it.
Running 100k run:
20250429-210342-neethu1-a2ac66604d69683d           compressed=True data_size=56135535 duration=5364020 ended=100000 fail_fast=10 max_runs=100000 pass=100000
> Backup unit test fix.

- fdbclient/S3Client.actor.cpp
Useful when we want to list what is in a bucket.
> Allow resource to be empty

- documentation/sphinx/source/release-notes/release-notes-730.rst
> Add 7.3.63 to 7.3.67 release notes [release-7.4]

- packaging/docker/Dockerfile
- packaging/docker/README.md
- packaging/docker/build-images.sh
> Update the default version of the Dockerfile and remove 6.3

- fdbbackup/backup.actor.cpp
Layer backup status update transaction retry in case of failure.
Testing:
-correctness 100K test passed
-Tested by doing manual upgrade in playstation_prod/s11.
> Layer backup status update transaction retry in case of failure.

- documentation/sphinx/source/release-notes/release-notes-740.rst
As title. Once merged, will forward port to `main` branch.
> Release notes for 7.4.2 and 7.4.3

- documentation/sphinx/source/release-notes/release-notes-740.rst
Forward port https://github.com/apple/foundationdb/pull/12192 to main branch.
> Release notes for 7.4.2 and 7.4.3 (main branch)

- tests/CMakeLists.txt
> Disable physical move test.

- documentation/sphinx/source/release-notes/release-notes-730.rst
> Add 7.3.68, 7.3.69 release notes [release-7.4]

- fdbbackup/tests/s3_backup_test.sh
- fdbclient/tests/bulkload_test.sh
- fdbclient/tests/s3client_test.sh
Running against s3 was broken.
./bulkload_test.sh ~/src/foundationdb/ ~/build_output/
Warning: Error reading TLS CA [/etc/ssl/cert.pem]: File not found
FDBD joined cluster.
....
which then did....
Warning: Error reading TLS CA [/etc/ssl/cert.pem]: File not found
libc++abi: terminating due to uncaught exception of type Error
SIGNAL: Aborted (6)
... and dropped a core.
Clean up s3 handling -- cert, aws:kms, and secure_connection setting.
* fdbbackup/tests/s3_backup_test.sh
* fdbclient/tests/bulkload_test.sh
* fdbclient/tests/s3client_test.sh
Clean up around s3 (secure, certs) vs seaweed (insecure, no certs).
> Broke running against s3

- fdbserver/KeyValueStoreRocksDB.actor.cpp
Rocksdb trace event changes.
Logging trace event too many times, reducing it 
2 unrelated errors in Joshua
20250717-212921-neethuhaneeshabingi-011c0ec45a76649f compressed=True data_size=56507683 duration=5351163 ended=100000 fail=2
> Rocksdb trace event changes.

- fdbserver/include/fdbserver/workloads/workloads.actor.h
- flow/FileTraceLogWriter.cpp
- flow/Trace.cpp
Some accumulated minor changes:
workloads.actor.h: ensure workload names are unique
FileTraceLogWriter.cpp: report more detail relating to non-zero errno values generally; in one place, ensure we don't report a value that might have got clobbered
Trace.cpp: checkAndInsertSuppression(): avoid overloading function return value
Testing:
After 5 commits: 
20250813-161012-gglass-2b717d6098698b1d            compressed=True data_size=41397719 duration=155228 ended=2941 fail_fast=10 max_runs=100000 pass=2941 priority=100 remaining=5:20:40 runtime=0:09:43 sanity=False started=3684 submitted=20250813-161012 timeout=5400 username=gglass
Original PR posting:
20250813-002443-gglass-558f5a2ffeeb7d14            compressed=True data_size=41436446 duration=6333441 ended=100000 fail_fast=10 max_runs=100000 …
> Minor changes from reading code

- fdbrpc/FlowTransport.actor.cpp
- flow/Net2.actor.cpp
- flow/SystemMonitor.cpp
- flow/include/flow/SystemMonitor.h
> [Release-7.4] Cherrypick connection counter

- fdbclient/MultiVersionTransaction.actor.cpp
- fdbclient/include/fdbclient/MultiVersionTransaction.h
This is needed for 6.1 or older fdbserver which is quite old and we no longer need to support.
> Remove LegacyVersionMonitor in MultiVersionClient

- fdbcli/FileConfigureCommand.actor.cpp
> fix "Unknown error" when  configuring regions (#11806) [release-7.3]

- flow/Net2.actor.cpp
Cherrypick: https://github.com/apple/foundationdb/pull/12322
> [Release-7.4] Cherrypick Improve handshake error trace event

- documentation/sphinx/source/kv-architecture.rst
cherrypick #12341
documentation only change
> Update roles in documentations [release-7.4]

- fdbclient/ServerKnobs.cpp
See https://github.com/apple/foundationdb/pull/12369#discussion_r2349886192 for context.
No testing needed.
> Fix spacing issue introduced in #12368

- fdbserver/SkipList.cpp
Refines the hot path in the conflict-set skiplist sorter. No functional changes intended; only allocation/branch behavior should differ.
- compare(StringRef,StringRef): 
Use memcmp(min(|a|,|b|)) and normalize sign ((c>0)-(c<0)) with a "branch-lean" length tie-breaker. This reduces branches on common prefixes.  Preserve the strict trichotomy {-1,0,+1} expected by callers.
- sortPoints():
Amortize allocations by allocating once to avoid repeated heap allocations in the MSD radix sort. This reduces malloc/free churn.
* tasks.reserve(points.size())
* newPoints.reserve(points.size())
* counts.resize(261)  // 256 byte buckets + 5 sentinels (end-of-key + extra ordering)
The sorter buckets 0..260: 5 sentinels (end-of-key and the 4-way extra ordering one past end) plus 256 byte values (offset by …
> Optimize conflict detection with pre-allocated buffers and branchless comparison

- documentation/tutorial/CMakeLists.txt
- documentation/tutorial/play.actor.cpp
The code documentation describes the purpose. 
For testing, I ensured the `play` target compiles and runs as expected. 
> Flow playground

- documentation/sphinx/source/release-notes/release-notes-730.rst
> [Release-7.4] Cherrypick release note

- documentation/sphinx/source/release-notes/release-notes-730.rst
> [Release-7.3] Cherrypick release note

- design/feature-status.md
> Add W32 Support entry to feature status

- fdbserver/TLogServer.actor.cpp
Minor optimization. Currently we call  peekTracker.find(peekId)  to test for existence but immediately call  peekTracker[peekId]  (which inserts a default PeekTrackerData  if absent). Similar duplicated work happens on sequence_version , where  find  is followed by  operator[]  in the same block. Each  operator[]  also constructs a default  Promise  even when the lookup is just for inspection.  
Replace two lookups with one by storing the iterator once:  `auto [trackerIt, inserted] =  peekTracker.try_emplace(peekId);` and work from  trackerIt->second . For sequence_version , use `auto [seqIt, inserted] = trackerData. sequence_version.try_emplace(sequence)`; 
100K `20251001-190449-dlambrig-a6cf3e3da19d0c6d ` …
> Optimize peekTracker lookups to use single try_emplace instead of find+lookup

- fdbserver/TagPartitionedLogSystem.actor.cpp
taken from [here](https://fdb.teamscale.io/findings/list/apple-foundationdb/fdbserver%2FTagPartitionedLogSystem.actor.cpp?t=main%3A1759288628000&tolerate=EXCLUDED&pending=ALL).
100K 20251001-190449-dlambrig-a6cf3e3da19d0c6d
Problems corrected by claude:
Added missing braces for if statement 
Comments should not contain //
> TeamScale cleanup for TagPartitionedLogSystem.actor.cpp

- fdbclient/FileBackupAgent.actor.cpp
Decode range file interpreting keys and values bug fix.
cherry-pick of #12399
> Decode range file interpreting keys and values bug fix.
